### ISSUE TITLE
Processes disappearing?

### ISSUE THREAD

**Issue by Warblefly** [microsoft/WSL#2469] opened 2017-09-02 15:03 UTC
On Build 16278, processes occasionally 'disappear'. This type of error has occured several times during compilation of GCC 7.2.0 as a cross-compiler. The common elements are `fork: Invalid argument`, and `wait_for: No record of process nnnnn`.

```
gcc-7.2.0/libcpp/configure: fork: Invalid argument
checking for build system preprocessor... 
gcc-7.2.0/libcpp/configure: line 1: wait_for: No record of process 16132
```

**Comment by shevegen** [comment] 2017-09-02 17:31
Hmm... have you had problems like this with other GCC variants too?

I haven't yet tried but perhaps this is seen in gcc 7.x and less so on gcc 6.x or gcc 5.x

What host gcc did you use? I was using ubuntu which, I think has had 5.3.x or or some other 5.x - this may of course be totally unrelated but it may be interesting for the BashOnWindows team too, since we definitely know that the gcc that comes with default ubuntu, works fine for the most part (I have had problems with the latest gcc 7.2.0 too but I wasn't sure whether it was not my lack of knowedge; on linux I can compile gcc 7.2.0 just fine though).

**Comment by Warblefly** [comment] 2017-09-02 18:38
Yes, the host Ubuntu GCC. Version 5.4.0.

**Comment by therealkenc** [comment] 2017-09-03 01:14
```>
gcc-7.2.0/libcpp/configure: fork: Invalid argument
checking for build system preprocessor... 
```

The problem doesn't seem to be so much "processes disappearing" as the process didn't happen, screwing up the job accounting in `bash` [here](http://git.savannah.gnu.org/cgit/bash.git/tree/jobs.c?h=bash-4.4#n2602). A fork failed. If you can catch the `EINVAL` in an `strace` we might be able to guess, but compiling gcc 7 under `strace` is a bear of a repro. And, given Murphy, it might not even fail under `strace`. Tough one.

**Comment by Warblefly** [comment] 2017-09-03 08:43
It's happened in other giant compiles I do, beside GCC. Reproduction is difficult because it is a rare failure, but potent when it happens.

**Comment by therealkenc** [comment] 2017-09-03 09:51
Could be just running out of resources (memory) and the error message is less than ideal, like [this example](https://stackoverflow.com/questions/26985229/ssh-and-bash-fork-cannot-allocate-memory-vps-ubuntu). Maybe try upping your Windows page file to something ridiculously large. Compile with `make -j 1`. 

Or it could be a bug. You'll see more "same here" posts roll in if it's a general problem with 16278 versus previous releases.

**Comment by Majsvaffla** [comment] 2017-09-08 12:40
I have a similar issue that could be related.

I'm running a pytest browser test suite that launches gunicorn webserver through Python's subprocess module. Before upgrading to build 16278 it launched properly but now my code seems to lose the process and time out.

I haven't located the root of this issue all I get from Python is `OSError: [Errno 9] Bad file descriptor`. I'll keep looking into it!

**Comment by bitcrazed** [comment] 2017-11-21 18:57
@sunilmut @scooley Could you take a look if we're recording any errors that would result in a `fork: Invalid argument` errors being returned?

@benhillis is OOF for a while, but copying too in case he's bored and looking for something to do ;)

**Comment by rdp** [comment] 2017-12-15 10:33
I get this "somewhat reproducibly" doing some cross compiling, ex:

```
opencore-amr-0.1.5 as $ make  -j 4
...
../libtool: fork: Invalid argument

```
or sometimes (I assume related)
`
...
x86_64-w64-mingw32-g++: error: : No such file or directory
`

that's with like 8GB of RAM free according to Task Manager FWIW.  If I restart the same "make" command then it may (or may not) continue smoothly to completion.

**Comment by HinTak** [comment] 2018-02-26 10:25
I got this while cross-compiling fftw in two bash windows, one for win32 and the other for win64 (and both doing "make -j 4") . I think it is just WSL being a bit flaky when spawning new processes too quickly.

**Comment by rdp** [comment] 2018-02-26 16:47
I don't get this "this morning" maybe try with this patch applied? https://github.com/Microsoft/WSL/issues/2697

**Comment by HinTak** [comment] 2018-03-02 10:50
```
Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Hin-Tak>ver

Microsoft Windows [Version 10.0.16299.248]

C:\Users\Hin-Tak>
```

I get that quite often with cross tools.

**Comment by cosmicdan** [comment] 2019-03-21 04:17
I got a `/bin/bash: fork: Invalid argument` while compiling AOSP 9.0 (Android Pie) under Ubuntu 18.04 in WSL (make -j6). Repeating make with the same job count produced no error.

Doubt it's a RAM thing as I have 32GB total and total usage never went above 20GB. This did happen after an hour or so of sustained heavy-load, like some others have encountered - but the possibly-interesting part was that this was at the end of AOSP compiling, where most of the work is compiling lots of Java.

I am also using ccache, as is pretty standard in AOSP compiling. 

My Win10 build is 17763.379.

Dunno what else I can say, just a "me too" and "still happens for me", I guess.

**Comment by piiroim1** [comment] 2019-03-31 02:06
I was creating bash script for some ocr stuff. It would run multiple instances imagemagick and tesseract-ocr. It was doing somewhat heavy IO, processing around 600-700 images, totaling about 500MB. It would also cap my CPU most of the time.

I realized that when letting the script create more than 4-5 subprocessess, I would start getting the "<scriptname>: fork: Invalid argument" -error. Checking the task manager revealed Microsoft Antimalware taking up most of the CPU time.

Disabling the real time protection at the Windows Defender settings seems to have solved the problem.

**Comment by cosmicdan** [comment] 2019-03-31 09:49
I had defender already disabled in my WSL setup because of the performance issues - I still had the problem, so that's a red herring.

You mention 4-5 subprocesses, so 6 at most; but how many logical cores does your host have?


On 31 Mar. 2019, piiroim1 <notifications@github.com> wrote:
>I was creating bash script for some ocr stuff. It would run multiple
>instances imagemagick and tesseract-ocr. It was doing somewhat heavy
>IO, processing around 600-700 images, totaling about 500MB. It would
>also cap my CPU most of the time.
>
>I realized that when letting the script create more than 4-5
>subprocessess, I would start getting the "<scriptname>: fork: Invalid
>argument" -error. Checking the task manager revealed Microsoft
>Antimalware taking up most of the CPU time.
>
>Disabling the real time protection at the Windows Defender settings
>seems to have solved the problem. 

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by piiroim1** [comment] 2019-03-31 12:01
I have 8 logical cores. However I don't seem to be able to reproduce the problem anymore. Before it would consistently happen when I set the number of subprocessess to 12. But now it seems to run just fine. The antivirus CPU usage does still ramp up though.

Not sure what to make of this. Seems quite random.

> 
> I had defender already disabled in my WSL setup because of the performance issues - I still had the problem, so that's a red herring. You mention 4-5 subprocesses, so 6 at most; but how many logical cores does your host have?
> […](#)
> On 31 Mar. 2019, piiroim1 ***@***.***> wrote: I was creating bash script for some ocr stuff. It would run multiple instances imagemagick and tesseract-ocr. It was doing somewhat heavy IO, processing around 600-700 images, totaling about 500MB. It would also cap my CPU most of the time. I realized that when letting the script create more than 4-5 subprocessess, I would start getting the "<scriptname>: fork: Invalid argument" -error. Checking the task manager revealed Microsoft Antimalware taking up most of the CPU time. Disabling the real time protection at the Windows Defender settings seems to have solved the problem.
> -- Sent with <a href="[https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@](https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2%22><b>K-@) Mail</b></a> - the evolution of emailing.

**Comment by toncho11** [comment] 2019-04-06 05:43
I have the same problem: compiling gcc, random messages from the same type ...
Disabling Windows Defender real time protection seems to help.

**Comment by saschanaz** [comment] 2019-06-24 08:00
Had this problem when building Servo and @toncho11's suggestion helped. Astonishing solution 😲

Didn't happen on WSL2, only on WSL1. Using AMD Ryzen 5 2600X on Windows Insider build 18922 if you ask.

```
--- stderr
No module named mako
Package libtizcore was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtizcore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtizcore' found
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
../../../../libtool: fork: Invalid argument
make[4]: *** [sp_state_so.lo] Error 254
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
thread 'main' panicked at 'failed with: exit code: 2', /home/saschanaz/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/build.rs:61:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build FAILED in 0:03:31
```

**Comment by fdcds** [comment] 2019-10-29 16:09
Could this be an instance of the following bug in bash 4.3 (e.g. Ubuntu 16.04) which is fixed in bash 4.4 (e.g. Ubuntu 18.04)?

https://lists.gnu.org/archive/html/bug-bash/2016-06/msg00052.html

**Comment by cslycord** [comment] 2020-06-25 06:38
> Could this be an instance of the following bug in bash 4.3 (e.g. Ubuntu 16.04) which is fixed in bash 4.4 (e.g. Ubuntu 18.04)?
> 
> https://lists.gnu.org/archive/html/bug-bash/2016-06/msg00052.html

I get hit by the bug with bash 5 from debian. 

`GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.`

Although, debian lists it as version 5.0-6.

**Comment by therealkenc** [comment] 2021-05-05 21:12
An `EINVAL` on `fork(2)` is "just wrong" even if the cause was OOM. Better in WSL2.

**Closed by therealkenc** 2021-05-05 21:12 UTC

**Comment by GrayXu** [comment] 2022-03-22 09:24
> Had this problem when building Servo and @toncho11's suggestion helped. Astonishing solution 😲
> 
> Didn't happen on WSL2, only on WSL1. Using AMD Ryzen 5 2600X on Windows Insider build 18922 if you ask.
> 
> ```
> --- stderr
> No module named mako
> Package libtizcore was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libtizcore.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libtizcore' found
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ar: `u' modifier ignored since `D' is the default (see `U')
> ../../../../libtool: fork: Invalid argument
> make[4]: *** [sp_state_so.lo] Error 254
> make[4]: *** Waiting for unfinished jobs....
> make[3]: *** [all-recursive] Error 1
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all] Error 2
> make: *** [all-recursive] Error 1
> thread 'main' panicked at 'failed with: exit code: 2', /home/saschanaz/.cargo/git/checkouts/osmesa-src-bf84ce2b80210dd7/97f4613/build.rs:61:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> [Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
> Build FAILED in 0:03:31
> ```

`libtool: fork: Invalid argument`  
similar problems here during `make`, but I found if I reduce the number of threads, it doesn't fail.

**Comment by adrian-gierakowski** [comment] 2022-05-04 09:44
why is this issue closed? has a root cause been identified and fixed?
