### ISSUE TITLE
port forwarding not working

### ISSUE THREAD

**Issue by localvar** [microsoft/WSL#11599] opened 2024-05-19 02:53 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2 (root@65c757a075e2)

### Distro Version

Ubuntu 24.04

### Other Software

Visual Studio Code: 1.89.1

### Repro Steps

actually, I don't know the exact steps to reproduce the issue, everything works fine yesterday but stops work today, I think all I have done is shutdown my computer yesterday and restart it today.

I can ping my distro from windows successfully, but when I try to connect the forwarded port (1313, opened by hugo), it says: connection refused.

I tried to turn off the windows defender firewall, I also tried reset all the network, but the issue still there.

### Expected Behavior

connect forwarded port successfully.

### Actual Behavior

connection refused.

**Comment by localvar** [comment] 2024-05-19 03:19
the WSL logs has been submit via Feedback hub, the link is: https://aka.ms/AAqhhv5

**Comment by OneBlue** [comment] 2024-05-20 18:37
@localvar: Can you share repro instructions ? We need to reproduce the issue to understand its root cause

**Comment by localvar** [comment] 2024-05-22 01:15
> @localvar: Can you share repro instructions ? We need to reproduce the issue to understand its root cause

I don't know the exact instructions to reproduce the issue, as I don't aware it will cause an issue before I encounter the issue.

A possible cause is the host port was already occupied by another application, because  after I change the guest port from 1313 to 2323, the issue resolved (however, I have tried to map guest 1313 to host port other than 1313 in vscode, it didn't work). If this is the case, could wsl give a message saying "host port is occupied" to notify user to change the port?

**Comment by localvar** [comment] 2024-05-22 02:53
> @localvar: Can you share repro instructions ? We need to reproduce the issue to understand its root cause

I don't know the exact instructions to reproduce the issue, as I don't aware it will cause an issue before I encounter the issue.

A possible cause is the host port was already occupied by another application, because  after I change the guest port from 1313 to 2323, the issue resolved (however, I have tried to map guest 1313 to host port other than 1313 in vscode, it didn't work). If this is the case, could wsl give a message saying "host port is occupied" to notify user to change the port?

**Comment by OneBlue** [comment] 2024-05-28 21:33
Thank you. I'll close this issue for now since it doesn't have clear repro instructions. Feel free to reopen if you find a way to reproduce this that we could try.

**Closed by OneBlue** 2024-05-28 21:33 UTC
