### ISSUE TITLE
Calling clip.exe incorrectly can cause the process to hang

### ISSUE THREAD

**Issue by burkeholland** [microsoft/WSL#4475] opened 2019-09-06 21:30 UTC
* Your Windows build number:  Windows [Version 10.0.18956.1000]

* What you're doing and what's happening:  

```
clip.exe < ~/.ssh/id_rsa.pub
```

* What's wrong / what should be happening instead:

The process hangs. It looks like it might have succeeded, but the prompt never returns.

It should probably throw an error since this is an invalid command. Note that running `~/.ssh/id_rsa.pub > cat.exe` throws a "permission denied" error instead.

**Comment by benhillis** [comment] 2019-09-06 21:34
This is a duplicate of #4337.

**Comment by benhillis** [comment] 2019-09-06 21:41
@burkeholland - That command should work (and certainly shouldn't hang).  What do you mean by "this is an invalid command"?

**Comment by benhillis** [comment] 2019-09-06 22:10
I have a repro of this, looks like interop isn't correctly handling redirecting from files as stdin in WSL2.  I'll get this sorted out, thanks for the posting!

**Comment by johndkraft** [comment] 2019-09-13 22:14
it looks like this is already understood, but here's more data just in case.
These all work in WSL 1, but in WSL 2:

`clip.exe < file `        # does not work, hangs
`cat file | clip.exe`    # works as expected

and most importantly for me, the following does not work in .tmux.conf:
`bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "/mnt/c/Windows/System32/clip.exe"`

that last one surprises me, because other piped input to clip.exe is working, so maybe it's me.

**Comment by benhillis** [comment] 2019-10-03 17:14
Fixed in [18995](https://blogs.windows.com/windowsexperience/2019/10/03/announcing-windows-10-insider-preview-build-18995).

**Comment by hwine** [comment] 2019-10-25 21:51
@benhillis -- seems to have regressed in 19008.1 -- neither of these works (but neither hangs):
```
$ clip.exe </etc/resolv.conf ; echo ${PIPESTATUS[@]}
1
$ cat /etc/resolv.conf | clip.exe ; echo ${PIPESTATUS[@]}
0 1
```
s/a tmux-plugins/tmux-yank#130

**Comment by benhillis** [comment] 2019-10-25 22:01
@hwine - It's working for me, can you please file a new issue with more information?

**Closed by benhillis** 2019-10-25 22:01 UTC
Labels: bug, fixedininsiderbuilds, interop, wsl2
