### ISSUE TITLE
Disabled Windows Subsystem for Linux Optional Component after updating to store version

### ISSUE THREAD

**Issue by xudyang1** [microsoft/WSL#9411] opened 2022-12-28 20:00 UTC
### Version

Microsoft Windows [Version 10.0.19045.2364]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Installed in-box version WSL2 (installed 6 months ago), and then update the old Windows component WSL to store version by `wsl --update`.
2. disabled the optional feature `Windows Subsystem for Linux` in `Turn Windows features on or off`.
3. restart pc
4. run `wsl --version`, and got `This application requires the Windows Subsystem for Linux Optional Component.
The system may need to be restarted so the changes can take effect.`

### Expected Behavior

According to the [blog](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-in-the-microsoft-store-is-now-generally-available-on-windows-10-and-11/#:~:text=Support%20for%20running%20WSL%201,wsl1%20%2C%20or%20manually%20at%20anytime.), "wsl.exe --install will now automatically install the Store version of WSL, and will **no longer enable** the “Windows Subsystem for Linux” optional component, or install the WSL kernel or WSLg MSI packages as they are no longer needed (The Virtual machine platform optional component will still be enabled, and by default Ubuntu will still be installed)." Since the optional component is no longer needed in store version, wsl2 should be normally activated even with this feature disabled.

### Actual Behavior

The store version of WSL still requires the Windows Subsystem for Linux Optional Component.

**Comment by NotTheDr01ds** [comment] 2022-12-30 00:15
I have two Windows 10 system and two with Windows 11 (and all with WSL).  From what I can tell, the WSL optional feature is still required on Windows 10.  On my Windows 11 systems, the App/Store version of WSL2 still functions when the optional feature is disabled.

**Comment by benhillis** [comment] 2023-01-04 17:31
Thanks for posting. The store version of Windows Subsystem for Linux requires the WSL optional component on Windows 10. On Win11, it's only required for WSL1 support. Closing as by design.

**Closed by benhillis** 2023-01-04 17:31 UTC
