### ISSUE TITLE
Files served over internal network are cut off

### ISSUE THREAD

**Issue by saschagehlich** [Microsoft/WSL#1413] opened 2016-11-24 14:14 UTC
* A brief description

Since upgrading to the latest Insider Preview, I can't seem to get any webserver serving a larger file (in my case an unminified build of React.JS of 685KB). The file seems to be cut off at some random point.

* Expected results

I'd expect a `curl` to a file on a local server (running with `python -m SimpleHTTPServer`) to return the whole file.

* Actual results (with terminal output if applicable)

```bash
$ curl "http://localhost:8082/build/js/vendor/react.js"
# ... prints some file contents ...
curl: (18) transfer closed with 170392 bytes remaining to read
```

(Remaining byte count varies)

* Your Windows build number
Insider Preview 14965

* Steps / All commands required to reproduce the error from a brand new installation 
Place some larger file in a directory, run `python -mSimpleHTTPServer 8082`. Then open another terminal, run `curl http://localhost:8082/myfile.js`. Similar issues occur when running a server using `node-static`, except that the curl process just hangs at some random point (connection stays open).

**Comment by aseering** [comment] 2016-11-24 16:48
Hi @saschagehlich -- could you take a look at #610 ?  I think it's the same issue.  If so, it has actually been around since the initial WSL release, but it's a race condition so some change may have made it worse on your machine.

**Comment by saschagehlich** [comment] 2016-11-24 20:06
Hey @aseering, thanks for replying. I just did a fresh reinstall which did not help unfortunately. Not sure if the issue is related since I'm also not able to load *any* files using Chrome on Windows from a SimpleHTTPServer server running WSL right now. If I use node-static, I at least get some response, before it stops mid-file and keeps loading indefinitely. node-static is also reporting "Request contains invalid range header:  [ '612152', '612152' ]".

While typing this response, I tried downloading another browser (Firefox) which does not work either (Chrome reports "Network error"). I also can't download any larger files via Edge ("This file couldn't be downloaded"). So it seems that the whole networking is broken in Windows right now.

This used to work with the latest stable release of Win10, which I am now going to downgrade to.

**Comment by jackchammons** [comment] 2016-11-28 19:35
I can reproduce on 14965

**Comment by saschagehlich** [comment] 2016-11-28 19:40
I noticed that my network errors were caused by my Antivirus / Firewall "ESET NOD32". Uninstalling it fixed the download issues.

**Comment by LordMonoxide** [comment] 2016-12-05 19:24
Probably related to #1377?  See my comment at the bottom of the thread for details

**Comment by saschagehlich** [comment] 2016-12-05 20:04
I was able to track this down to my Antivirus software (NOD32) which doew
not seem to play well with the insider build.

**Comment by LordMonoxide** [comment] 2016-12-05 20:06
I don't use an antivirus, but I'm guessing #610 is my issue

**Comment by scooley** [comment] 2018-05-22 21:37
Closing as a duplicate of another issue (which has been fixed).  https://github.com/Microsoft/WSL/issues/610

**Closed by scooley** 2018-05-22 21:37 UTC
Labels: duplicate
