### ISSUE TITLE
Can not overwrite symbolic link

### ISSUE THREAD

**Issue by munemasa** [microsoft/WSL#6362] opened 2020-12-21 07:37 UTC
# Environment

```none
Windows build number: [Microsoft Windows [Version 10.0.18363.1256]]
Your Distribution version: [Ubuntu 18.04 and any distributions]
Whether the issue is on WSL 2 and/or WSL 1: [WSL1]
```

# Steps to reproduce

```
$ ln -s a b
$ touch c
$ mv c b
mv: cannot move 'c' to 'b': No such device or address

$ ln -sf c b
ln: failed to create symbolic link 'b': No such device or address
```

```
$ strace mv c b
...
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
stat("b", 0x7fffcc680110)               = -1 ENOENT (No such file or directory)
lstat("c", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lstat("b", {st_mode=S_IFLNK|0777, st_size=1, ...}) = 0
rename("c", "b")                        = -1 ENXIO (No such device or address)
...
```

#  Expected behavior

Overwrite symbolic link.

# Actual behavior

Can not overwrite.

**Comment by therealkenc** [comment] 2020-12-23 19:30
> Windows build number: [Microsoft Windows [Version 10.0.18363.1256]]

Thanks for the report and the strace log. The `ENXIO` is novel (no dupe target). Appears to be addressed in more recent WSL (notwithstanding other unmentioned variables). Try 20H2 aka build 19042. You can stay on WSL1, it isn't necessary to upgrade to WSL2, unless you want. Also just so it is on the books, what is your [`pwd`](https://man7.org/linux/man-pages/man1/pwd.1.html) (your repro uses relative paths without stating the path).

**Comment by munemasa** [comment] 2020-12-24 02:34
Thank you for your comment.
This problem is occurred at everywhere, home directory, /etc, and etc.
so update-alternatives, apt install, etc command is failed because symlinks can not overwrite.

I want to use WSL2 but Symantec Endpoint Protection (used in my company and can not change FW settings) blocked internet connection.

**Comment by therealkenc** [comment] 2020-12-28 16:03
> I want to use WSL2

You can stay on WSL1 with newer builds (19042). The novel part is the `ENXIO`, which suggests upgrading might not help, but it is worth the try. Most likely you have some third-party software interaction that is going badly.

**Comment by fukuda668** [comment] 2022-04-22 05:17
Sorry for old topics.

I find that this issue occurs with procedures written in "Steps to reproduce":
- WSL1 ( Ubuntu-20.04 )
- Windows 10 21H2, build 19044.1645

**Closed** 2024-02-01 12:13 UTC
Labels: file system
