### ISSUE TITLE
umask not taking?

### ISSUE THREAD

**Issue by jdalton** [Microsoft/WSL#866] opened 2016-08-11 14:55 UTC
I noticed when I `touch a.js` it's created with the default permissions of `-rwxrwxrwx` and I'm wanting to change that to `-rw-r--r--`. I tried using `umask 022`  but it's not seeming to make a difference.

``` bash
touch a.js
ls -l a.js
-rwxrwxrwx a.js
umask 022
touch b.js
ls -l b.js
-rwxrwxrwx b.js
```

**Comment by jdalton** [comment] 2016-08-11 17:56
It looks like this is only an issue in folders in `/mnt/c/` as `umask` is respected within my home directory.

**Comment by aseering** [comment] 2016-08-11 22:45
I think this is a symptom of a more general issue -- AFAIK file permissions in general aren't fully supported on DrvFS (ie., /mnt/*)

**Comment by rodrymbo** [comment] 2016-08-13 21:17
Well, NTFS file permissions are supported and enforced, they just aren't translated to the usual linux attributes. Apparently, the only way to find out if you have permission to do something (from within WSL) on a file in DriveFS is to try it and see if it works.

**Comment by neurogenesis** [comment] 2016-10-16 21:36
@jdalton : this is possibly a duplicate of #352

**Closed** 2017-12-01 22:48 UTC
Labels: duplicate
