### ISSUE TITLE
WSL2 - clock problems during build

### ISSUE THREAD

**Issue by rupor-github** [microsoft/WSL#4975] opened 2020-03-16 15:49 UTC
Sorry if this duplicate - I tried to search and saw several messages which are referring to same/similar problem, however there seems to be no separate assigned recent entry tracking this particular problem. Mostly people complain about date being skewed (some workarounds are available) - this one however as far as I could tell has no workaround and is easily reproducible in the latest 2004 build, which make WSL 2 completely unsuitable for any real development use.

Windows 10 build 19041.153, attempting to use WSL2, files are on Windows file system (not rootfs):

```
-- Build files have been written to: /mnt/e/projects/misc/wsl-ssh-agent/release
make: Warning: File 'Makefile' has modification time 0.6 s in the future
make[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 0.65 s in the future
make[2]: Warning: File 'CMakeFiles/bin_agent.dir/progress.make' has modification time 0.61 s in the future
Scanning dependencies of target bin_agent
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'CMakeFiles/bin_agent.dir/progress.make' has modification time 0.51 s in the future
[100%] Building wsl-ssh-agent-gui...
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target bin_agent
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
```

Could `hv_utils: cannot register PTP clock: 0` be the reason for that?

**Comment by sirredbeard** [comment] 2020-03-17 15:11
This is a duplicate of #4677 which you have also commented in @rupor-github 

Use `sudo hwclock -s` to re-sync your hardware clock in your build scripts.

**Comment by rupor-github** [comment] 2020-03-17 15:27
It does not help

**Comment by sirredbeard** [comment] 2020-03-17 15:33
That would be very helpful to know and provide useful in that issue.

**Comment by rupor-github** [comment] 2020-03-17 17:23
Sure - I am here to provide anything which is missing, could you please kindly explain what you need?

So far it goes like that:
1. I have been using WSL v1 for quite sometime, one of the projects I work on is https://github.com/rupor-github/wsl-ssh-agent. It has bash script to build it which invokes cmake. Works like a charm. My distro is Pengwin (which from what I could tell is slightly customized Debian testing)
2. Converted WSL distro to WSL v2 yesterday after installing Windows 10 build 19041.153. Now when I am running build script I get above mentioned error (every time all the time - reliably). Running `hwclock` or `ntpdate` only changes the skew value - problem stays.
3. Running dmesg I could see:
```
[    0.446543] hv_utils: cannot register PTP clock: 0
......
[    0.464916] Unstable clock detected, switching default tracing clock to "global"
               If you want to keep using the local clock, then add:
                 "trace_clock=local"
               on the kernel command line
```
4. Looked around - similar problems have been mentioned in context of time/date sync problems due to sleep.  In my case this is desktop which does not sleep. So I decided to make it separate - as this is important.

**Comment by rupor-github** [comment] 2020-05-03 19:01
After using WSL2 for a while I could state with reasonable accuracy that this problem only shows when build happens outside rootfs - in other words if build directory is hosted on devfs (9p?) mounted NTFS file system. When I move everything into home directory - this problem disappears. This holds true even for latest 2004.208 build. At the same time under WSL1 this never happens.

**Comment by lygstate** [comment] 2020-05-12 18:25
Yeap, I also face this problem.

**Comment by sloong** [comment] 2020-05-20 07:59
same problem.

**Closed** 2020-06-03 21:39 UTC
