### ISSUE TITLE
dbus problems when trying to run electron

### ISSUE THREAD

**Issue by timdeng2324** [Microsoft/WSL#2295] opened 2017-07-07 01:51 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Installed node.js using nvm
Cloned a repo to try and run some example electron apps: `git clone https://github.com/hokein/electron-sample-apps`
I have Xming and have set my display environment variable.
When tried to start electron, it said I was missing various libraries, so I installed all the necessary ones using https://electron.atom.io/docs/development/build-instructions-linux/ (Ubuntu instructions).
Now, when I run `electron helloworld`, a window briefly shows up and disappears. The error is as follows:
```process 466: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
[466:0706/184226:FATAL:udev_linux.cc(20)] Check failed: monitor_.
#0 0x000001cb9a3e <unknown>
#1 0x000001ccf83b <unknown>
#2 0x000000bd9026 <unknown>
#3 0x000002e01b62 <unknown>
#4 0x000001cba71c <unknown>
#5 0x000001cd595b <unknown>
#6 0x000001cd5c48 <unknown>
#7 0x000001cd5e0b <unknown>
#8 0x000001caf719 <unknown>
#9 0x000001ceb3a0 <unknown>
#10 0x000001cd51ca <unknown>
#11 0x00000249c616 <unknown>
#12 0x00000249c813 <unknown>
#13 0x000001d0ad28 <unknown>
#14 0x000001d07263 <unknown>
#15 0x7f9e9ffd76ba start_thread
#16 0x7f9e99b473dd clone```

* What's wrong / what should be happening instead:
Electron should of course be opening up. I took a look at #2016 but it didn't help.

**Comment by sunjoong** [comment] 2017-07-07 02:17
@timdeng2324 - Well... I saw a very similar error message on #2293, and there I knew @therealkenc have a project https://github.com/therealkenc/libudev-stub .

**Comment by therealkenc** [comment] 2017-11-15 17:40
Issue title here is misleading; it's udev not dbus). Dupe of #1121.

**Closed by therealkenc** 2017-11-15 17:40 UTC
Labels: duplicate
