### ISSUE TITLE
wslbridge error: failed to start backend process

### ISSUE THREAD

**Issue by 88lexd** [Microsoft/WSL#3330] opened 2018-06-26 23:27 UTC
*** Your Windows build number:**  
Microsoft Windows [Version 10.0.17134.48]

*** What you're doing and what's happening:**  
When Windows start up, I open CMD > type Bash and I get the error saying:
"wslbridge error: failed to start backend process
note: bash.exe output: Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore"

![image](https://user-images.githubusercontent.com/40483748/41944628-288239a8-79ec-11e8-89e0-6922823e23a8.png)

*** What's wrong / what should be happening instead:**
Ubuntu Bash should start without giving any errors.

*** Strace of the failing command, if applicable:** 
N/A

*** Other information**
I notice this issue is intermittent and works fine if I manually restart the LxssManager service or wait maybe 5-10 minutes upon boot up before trying to run bash. 

I am not aware if LxssManager stores any logs on the system so I cannot provide any further details..

**Comment by benhillis** [comment] 2018-06-26 23:29
Thanks for filing. This is a duplicate of #2576.

**Closed by benhillis** 2018-06-26 23:29 UTC
