### ISSUE TITLE
Only one lo network card with networkingMode=mirrored

### ISSUE THREAD

**Issue by FlowerBirds** [microsoft/WSL#10650] opened 2023-10-20 07:11 UTC
### Windows Version

 10.0.22635.2486

### WSL Version

2.0.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Ubuntu 18.04

### Repro Steps

use ifconfig command

### Expected Behavior

should show eth0 netwrok card indo

### Actual Behavior

(base) root@LAPTOP-TC4A0SCV:~# ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 16  bytes 1336 (1.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 1336 (1.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

(base) root@LAPTOP-TC4A0SCV:~#

### Diagnostic Logs

network not work!

**Comment by FlowerBirds** [comment] 2023-10-20 07:13
![image](https://github.com/microsoft/WSL/assets/9587518/ea91e773-83aa-4458-9792-3d797d38e6a6)

![image](https://github.com/microsoft/WSL/assets/9587518/c7019d0f-4373-4469-8321-500c4592d718)

**Comment by FlowerBirds** [comment] 2023-10-24 01:00
wls logs：https://github.com/FlowerBirds/wsl2/blob/main/WslLogs-2023-10-24_08-49-22.zip

**Comment by Yolo-plop** [comment] 2023-11-08 12:47
Having the same issue. I can't connect to my WSL nginx server from Windows and it seems like the wsl instance doesn't even have access to Internet.

**Comment by keith-horton** [comment] 2023-11-14 07:16
Hi there. I looked at the trace but there isn't much there. Can you stop wsl, start the trace, repro the issue, then stop the trace for us?
we have a better script now: https://github.com/microsoft/WSL/blob/master/diagnostics/collect-networking-logs.ps1

Thanks!

**Comment by Ynewtime** [comment] 2023-11-16 20:17
Same issue here only when configured with `networkingMode=mirrored`.

Want to have a trace though unfortunately it is a company laptop...

**Comment by FlowerBirds** [comment] 2023-11-17 10:56
The problem still occurs in the 2.0.9 version.

**Comment by FlowerBirds** [comment] 2023-11-23 01:02
The problem still occurs in the 2.0.11 version.

**Comment by FlowerBirds** [comment] 2023-11-23 01:13
[networkingLogs.zip](https://github.com/microsoft/WSL/files/13445347/networkingLogs.zip)

- Before start: WslNetworkingLogs-2023-11-23_09-06-25
- Running: WslNetworkingLogs-2023-11-23_09-07-44
- After running and shutdown: WslNetworkingLogs-2023-11-23_09-08-31

@keith-horton thanks.

**Comment by FlowerBirds** [comment] 2023-11-23 01:41
[wsl debug info.txt](https://github.com/microsoft/WSL/files/13445430/wsl.debug.info.txt)

```
debugConsole=true
```

**Comment by FlowerBirds** [comment] 2023-11-28 00:07
[WslNetworkingLogs-2023-11-28_08-03-22.zip](https://github.com/microsoft/WSL/files/13481882/WslNetworkingLogs-2023-11-28_08-03-22.zip)

@CatalinFetoiu Thanks

**Comment by CatalinFetoiu** [comment] 2023-11-28 20:08
@FlowerBirds thanks for sharing the traces

it appears that WSL was not fully stopped before taking the traces.
to get a trace of a fresh boot of WSL, can you please do the following?
net.exe stop WslService
net.exe stop LxssManager
start the script
start WSL and confirm the issue
stop the script

Also, after traces are stopped, can you please copy the output of the script in a file and attach it to the issue? I see some files were not collected in the zip and I want to check if there was any issue when running the script

thanks

**Comment by FlowerBirds** [comment] 2023-11-29 01:47
[WslNetworkingLogs-2023-11-29_09-41-47.zip](https://github.com/microsoft/WSL/files/13495160/WslNetworkingLogs-2023-11-29_09-41-47.zip)

[capture-logs.txt](https://github.com/microsoft/WSL/files/13495169/capture-logs.txt)

![image](https://github.com/microsoft/WSL/assets/9587518/1b3ec309-06fb-4d9f-85d6-a0b68bcf7483)

**Comment by ArslanTu** [comment] 2024-04-05 11:28
I have solved this with the help of [this issue](https://github.com/microsoft/WSL/issues/11002).
Just open regedit and chang the value of `DisabledComponents` (`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\`) from 0xFF to something else, like Decimal 32. Then reboot and enjoy it.
[Reference](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows)

**Comment by Ynewtime** [comment] 2024-04-05 16:40
@ArslanTu  You are unbelievable! This just solve my long lasting problem!!! Thank you!

**Comment by keith-horton** [comment] 2024-04-05 20:05
Right. setting this to 0xFF will risk apps and services to not behave correctly - it's an old registry value from before the tcpip stack rewrite in Windows Vista.

As in the linked PR, you can directly removing the v6 binding if you want to disable IPv6 - which is supported:

Set-NetAdapterBinding -Name Wi-Fi -ComponentID ms_tcpip6 -Enabled $false

(replace "Wi-Fi" with the adapter name you have)

**Comment by keith-horton** [comment] 2024-04-05 20:06
@FlowerBirds , can you see if the Tcpip6\Parameters DisabledComponents registry value is set on your machine?

**Comment by FlowerBirds** [comment] 2024-04-07 01:21
@keith-horton Change the default value of DisabledComponents from 255 to 32, after restarting the computer, open WSL, and there will be four additional network card information, from eth0 to eth3.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:ff:b6:0b:78:c6 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether f4:a4:75:10:4a:b9 brd ff:ff:ff:ff:ff:ff
4: loopback0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:17:96:5a brd ff:ff:ff:ff:ff:ff
5: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 7c:8a:e1:c3:e8:64 brd ff:ff:ff:ff:ff:ff
    inet 191.168.4.38/21 brd 191.168.7.255 scope global noprefixroute eth2
       valid_lft forever preferred_lft forever
6: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:ff:3b:8b:62:2c brd ff:ff:ff:ff:ff:ff
```
When I check the default value of DisabledComponents again, it changes back to 255.

Finally, I tested the connectivity using localhost and the IP address, and found that localhost is accessible, but using the IP address does not work.

.wslconfig
```
[wsl2]
processors=6
memory=8G
swap=8G
localhostForwarding=true
dhcp=false
kernelCommandLine = vsyscall=emulate ipv6.disable=1
nestedVirtualization=false
debugConsole=false
autoProxy=false
networkingMode=mirrored
```

**Comment by keith-horton** [comment] 2024-04-08 19:24
@FlowerBirds , thanks. using the local IP address requires setting [experimental] hostAddressLoopback = true

We have this false by default to work around other Linux container issues.

**Comment by CatalinFetoiu** [comment] 2024-07-26 22:38
closing since the issue is resolved

**Closed by CatalinFetoiu** 2024-07-26 22:38 UTC
Labels: network

**Comment by rliuyi** [comment] 2025-09-27 05:14
> I have solved this with the help of [this issue](https://github.com/microsoft/WSL/issues/11002). Just open regedit and chang the value of `DisabledComponents` (`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\`) from 0xFF to something else, like Decimal 32. Then reboot and enjoy it. [Reference](https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows)

Thanks for saving my life...
