### ISSUE TITLE
WSL2 Fast Ring broke `code .` to open files

### ISSUE THREAD

**Issue by SeanTAllen** [microsoft/WSL#4362] opened 2019-08-01 02:31 UTC
Prior to insiders build 18945, i could use `code .` from inside wsl2 from the terminal to open code with the remote extension at that location. As of the 18945 update being installed, that no longer works. 

Now, the following command from the `code` bash script hangs:

```
WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" ".\resources\app\out\cli.js" --locate-extension $WSL_EXT_ID)  
```

once it hangs, i am able to ctrl-c to exit and get back to the shell.
with the latest vscode insider, i have a similar issue that happens except you can't ctrl-c out. it isn't recognized.

With:

```
Version: 1.37.0-insider (user setup)
Commit: d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
Date: 2019-07-31T05:24:41.973Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18945
```

it hangs at:

```
WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID)  
```

Both versions of VSCode worked prior to the installation of the fast ring 18945 windows insider build.

**Comment by lengthmin** [comment] 2019-08-01 04:57
The same thing happened to me.

**Comment by christianklauss** [comment] 2019-08-03 10:48
Can confirm

**Comment by garricknorthover** [comment] 2019-08-07 08:10
For me as well on Fast ring 18950.

But if you try the insiders wsl integrated terminal, it will open a folder in insiders, 
eg: code-insiders ./testfolder

**Comment by mscraigloewen** [comment] 2019-08-07 20:06
This has also been cross posted to the VSCode repo in [this issue](https://github.com/microsoft/vscode/issues/78596). We'll start looking into why this may be happening!

**Comment by aeschli** [comment] 2019-08-16 20:47
What the line does is calling the Windows VSCode executable with some command line parameters.

Hereis a equivalent sample that shows the same problem:

- install NodeJS in Windows
- from a WSL2 shell, run `"/mnt/c/Users/martinae/AppData/Roaming/nvm/v10.11.0/node.exe" -e "console.log('hello')"`.  This works, 'hello' is printed
- now try `foo=$("/mnt/c/Users/martinae/AppData/Roaming/nvm/v10.11.0/node.exe" -e "console.log('hello')")`. Does not complete.

**Comment by craigloewen-msft** [comment] 2019-08-16 21:05
I believe this error is related to interop not working which we're tracking here: https://github.com/microsoft/WSL/issues/4337

The issue is fixed internally, I'm able to run `code .` and the sample code @aeschli posted above whereas I wasn't able to before, so this should be resolved in the next Windows Insider update that contains WSL updates.

**Closed** 2019-08-20 21:06 UTC

**Comment by badgh** [comment] 2019-08-24 14:57
it still doesn't work in 18965

**Comment by Alirezanet** [comment] 2019-08-24 20:38
For now just comment these few lines : 
![image](https://user-images.githubusercontent.com/7004080/63642458-8815b080-c6d4-11e9-9b93-3f6729c7b048.png)
 in : 
`C:\Users\<USERNAME>\AppData\Local\Programs\Microsoft VS Code\bin\code`

if you want to use Remote-WSL you can reopen file/folder in vscode easily.

**Comment by aeschli** [comment] 2019-08-27 09:33
I pushed a workaround to code-insiders so that the command line works again. But we still need to get the proper fix from WSL as there are still various issues that likely are related.
