### ISSUE TITLE
WSL2 to can't browse in `/mnt/c`

### ISSUE THREAD

**Issue by trondhindenes** [microsoft/WSL#4122] opened 2019-06-13 21:00 UTC
**Please fill out the below information:**
* Your Windows build number:  `10.0.18917.1000`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
in wsl:
`ls /mnt/c`

* What's wrong / what should be happening instead:
the folder is empty. Should have listed my `Users` folder etc

**Comment by benhillis** [comment] 2019-06-13 23:31
Are there any interesting errors in dmesg?

Can you provide the output of the mount command?

**Comment by hadim** [comment] 2019-06-14 13:54
I had the same issue and in my case it was because I added:

```
[automount]
options = "metadata"
```

in `wsl.conf`. I think when using WSL2 you can comment or delete this file.

**Comment by benhillis** [comment] 2019-06-14 13:59
@hadim - The metadata option should still work with WSL2, I will take a look though.

**Comment by hadim** [comment] 2019-06-14 14:03
Is it still relevant? If it is then mounting C drive only works for me when removing this option.

**Comment by benhillis** [comment] 2019-06-14 14:06
@hadim - Do you have any output in dmesg?  I am unable to repro this locally:

```
root@BENHILL-VM4:/mnt/c/benhill# cat /etc/wsl.conf
[automount]
options = "metadata"
root@BENHILL-VM4:/mnt/c/benhill# mount | grep drvfs
C:\ on /mnt/c type 9p (rw,noatime,sync,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata,access=client,trans=fd,rfd=8,wfd=8)
D:\ on /mnt/d type 9p (rw,noatime,sync,dirsync,aname=drvfs;path=D:\;uid=1000;gid=1000;metadata,access=client,trans=fd,rfd=8,wfd=8)
```

**Comment by hadim** [comment] 2019-06-14 14:10
My bad, I just re-enable the metadata option, restarted WSL and I can mount the C drive...

```
C:\ on /mnt/c type 9p (rw,noatime,sync,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata,access=client,trans=fd,rfd=9,wfd=9)
```

No idea what was happening before but the C drive wasn't mounted...

**Comment by benhillis** [comment] 2019-06-14 14:28
If you are able to narrow down what the issue was, please reopen.

Thanks!

**Comment by trondhindenes** [comment] 2019-06-16 20:25
I think my error is different. C is indeed mounted, its just not browsable.
I can do `ls /mnt/c/Users/myUserName`, but not `ls /mnt/c`

**Comment by trondhindenes** [comment] 2019-06-16 20:26
@benhillis I don't have an option to re-open this but like I wrote I don't think mine and @hadim 's errors are the same.

**Comment by edwindijas** [comment] 2019-06-22 08:02
I encountered the same issue. My problem was with my service initializing scripts. I delayed the initializing scripts in task scheduler by 30 seconds and the problem was resolved.

**Comment by samdenty** [comment] 2019-07-08 03:36
@benhillis Came across the same issue. I ran `wsl --shutdown` and next time I booted, `/mnt/c/` comes up as blank, same after a system reboot

```
[samdd@samdd ~]$ ls /mnt/c -lah
total 8.0K
drwxrwxrwx 2 root root 4.0K Jun 17 07:21 .
drwxr-xr-x 9 root root 4.0K Jun 24 09:16 ..
```


```
sudo dmesg
...


[   63.135712] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[   63.284299] init: (1) ERROR: UtilCreateProcessAndWait:430: /bin/mount failed with status 0x
[   63.284303] 100
[   63.284308] init: (1) ERROR: ConfigMountFsTab:2018: Processing fstab with mount -a failed.
[   63.287980] init: (1) ERROR: UtilCreateProcessAndWait:430: /bin/mount failed with status 0x
[   63.287983] 100
[   63.287987] init: (1) ERROR: MountPlan9:426: mount noatime,trans=fd,rfdno=9,wfdno=9,cache=none,aname=drvfs;path=A:\;uid=1000;gid=1000
[   63.287989]  failed 17
[   63.309906] init: (1) ERROR: UtilCreateProcessAndWait:430: /bin/mount failed with status 0x
[   63.309909] 100
```

**Comment by JoshuaCWebDeveloper** [comment] 2019-07-15 16:58
I just had this problem happen for the second time since converting an instance from WSL 1 to WSL 2 a little over a week ago.

In both cases, the problem happened after attempting to access the `/mnt/c` directory right after booting Windows. In both cases, the problem was resolved by simply restarting Windows. The first time I was mucking around with the network settings, and so I blamed it on something I did. However, since then, it had been working fine until this morning when the problem happened again; I had made no changes to the environment in the interim.

Running `ls -la /mnt/c` shows an empty directory, running `ls -la /mnt/c/Users` returns no such file or directory. I do not have any `/etc/wsl*` file.

@edwindijas What service initializing scripts are you using? I do indeed have a Windows batch script that is run on logon by the Task scheduler, this batch script calls `ifconfig` and `service ssh start` on my `ubuntu1604` instance.

**Comment by JoshuaCWebDeveloper** [comment] 2019-07-18 18:25
I have been further able to narrow this problem down. Every day this week, when I first start my computer up, this problem has happened, but restarting would fix the problem.

Today I did some more testing. This seems to happen every time Windows is booted after having been previously Shut Down (i.e. the computer was turned off). However, if Windows was merely Restarted (computer stays on), then this problem will not happen. I'm not sure why this would matter, but I have been able to reproduce this on my pc reliably today.

Additionally, I tried disabling the scheduled batch script I mentioned in my previous comment, and it had no effect; `ls -la /mnt/c` would still return an empty directory if Windows was booted after having been previously shut down. I'm not aware of any other changes I have made in my environment that could be causing this.

**Comment by onomatopellan** [comment] 2019-07-18 19:17
@JoshuaCWebDeveloper That sounds a lot like [Fast Startup](https://www.howtogeek.com/243901/the-pros-and-cons-of-windows-10s-fast-startup-mode/). I always disable it because it's incompatible with dual booting.

**Comment by pietrodito** [comment] 2019-08-29 20:31
@onomatopellan Disabling the Fast Startup solves the issue for me

**Comment by datocrats-org** [comment] 2019-09-16 18:56
I am also having this issue;
Please fill out the below information:

Your Windows 10 Enterprise Version: 1903 OS Build: 18362.356 

What you're doing and what's happening: (Copy&paste the full set of specific command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
in wsl:
ls /mnt/c

What's wrong / what should be happening instead:
The folder is empty. Should have listed my Users folder etc

Possible configuration issues: Ubuntu 18.04 (not supported for WSL), Go installed in windows and on WSL possibly in same root

**Comment by datocrats-org** [comment] 2019-09-16 19:16
> I had the same issue and in my case it was because I added:
> 
> ```
> [automount]
> options = "metadata"
> ```
> 
> in `wsl.conf`. I think when using WSL2 you can comment or delete this file.
> 
> (then you'll have to restart WSL with `wsl --shutdown`)

I have similar options in .conf to run docker per [these instructions](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly), something in those settings cause the same behavior reported here, which appears to be expected behavior

**Comment by ctivanovich** [comment] 2019-10-17 01:49
I encountered this issue as well, and for me, it was because I followed this guide to [scheduling a cron job](https://blog.snowme34.com/post/schedule-tasks-using-crontab-on-windows-10-with-wsl/index.html). I guess the start up task on the windows side to launch the cron process at windows start up time somehow short-circuits the mounting operation.

**Comment by Garibaldy** [comment] 2019-10-29 03:50
what helped me was to shutdown wsl then run it again 

powershell -> wsl --shutdown 
powershell -> wsl 

then i got it back

**Comment by CMiksche** [comment] 2020-03-12 21:20
I have the same issue when i enter 

    [automount]
    options = "metadata"

into /etc/wsl.conf. Restarting the wsl hasn't helped me. 

`mount | grep drvfs` outputs nothing.

I only need the correct file permissions - is there any other way to do this than metadata? (I don't get the right permissions when i leave the /etc/wsl.conf file empty)

**Comment by cloudkarma** [comment] 2020-07-08 22:55
I had the same issue, i could not access any of the drives though they were shown ls /mnt, 
I had to comment all the lines in /etc/wsl.conf, 
hope this helps

**Comment by theogtg** [comment] 2020-08-10 14:43
solved by only having

`[automount]`

in my /etc/wsl.conf. Then running

`sudo apt update`

in my wsl instance. Solved everything right away!

**Comment by florton** [comment] 2020-08-10 20:12
In my case this was due to not having the correct permissions on my linux user solved by running `sudo usermod -G sudo [username]`

**Comment by michaelj-smith** [comment] 2020-09-18 17:07
My issue was a misunderstanding of the automount behavior.

```
~$ ls -la /mnt/c
total 8
drwxrwxrwx 2 root root 4096 Sep 15 12:39 .
drwxr-xr-x 4 root root 4096 Sep 15 14:04 ..

~$ mount | grep drvfs
C:\ on /c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)

~$ cat /etc/wsl.conf
[automount]
root = /
options = "metadata"
```

What threw me is that I had added the automount settings in wsl with the root = / option. For some time both /mnt/c and /c were empty. But after a `wsl --shutdown` command in PowerShell, the /c root was then mounted correctly.

**Comment by jjschweigert** [comment] 2020-10-15 16:19
Since wsl.exe --shutdown seems to be the only true way to get around this issue when it does occur, I have the following command to run the shutdown command then open the windows terminal

powershell.exe -windowstyle hidden -noLogo -NoProfile -command "wsl.exe --shutdown; explorer.exe shell:appsFolder\Microsoft.WindowsTerminal_8wekyb3d8bbwe!App"

You can get the explorer.exe command for any app, such as ubuntu, by using a tutorial like https://www.tenforums.com/software-apps/57000-method-open-any-windows-10-apps-command-line.html

So if you wanted to open ubuntu, just replace the explorer.exe command with the correct command to open Ubuntu. Then you can create a new shortcut and paste the full powershell command in and then set the shortcuts icon to whatever app icon you need.

For instance, I set the windows terminal icon for the shortcut and pinned it to the taskbar, you can see when I run it a seperate icon shows on the taskbar for the running windows terminal window vs the shortcut which does not show a running status.

![image](https://user-images.githubusercontent.com/46967710/96157617-8282b780-0ee0-11eb-93bb-f6fdbf7bd29e.png)

**Comment by CliffHan** [comment] 2020-10-18 08:00
I met this problem too, on windows 10 home 2004, version 19041.572
I guess maybe it's caused after windows sleep or hibernate.

**Comment by mike-usa** [comment] 2020-12-07 01:40
> I met this problem too, on windows 10 home 2004, version 19041.572
> At first I guess maybe it's caused after windows sleep or hibernate.
> Now it seems I met this every time after system boot. Need "wsl --shutdown" to make /mnc/c work.

As a new WSL user, I'm not too versed on the documentation, so I don't know if this is expected or not.

I concur that every time I shutdown/restart the Windows PC, /mnt/c (in the WSL terminal) is no longer connected. Issuing a `wsl --shutdown` from PS/Command Prompt and then starting WSL back up will remount the drives.

1. Is this expected behavior? 
1. Does it unmount because WSL is a HyperV?
1. Also noted, the wsl does not appear in File Explorer (under Network) until typing `\\wsl$` in the address bar; is there a way to automate that? -- I've added my WSL distro to the Quick Access to give it a GUI. I haven't found any documentation to list on startup.

**Comment by useafterfree** [comment] 2020-12-23 01:38
If you compiled a custom kernel be sure that VIRTIO is set:

```

CONFIG_VIRTIO_FS=y

```

**Comment by MueR** [comment] 2021-02-08 17:15
> what helped me was to shutdown wsl then run it again
> 
> powershell -> wsl --shutdown
> powershell -> wsl
> 
> then i got it back

This fixed it for me. Thank you!

**Comment by lolo9538** [comment] 2023-01-13 23:29
Had the same issue, restarting wsl solves it but the final solution for me was to increase the delay of my windows task that automatically starts wsl at windows startup.

**Comment by Sebazzz** [comment] 2023-02-10 12:54
I believe this also occurs when you have run `wsl --update` on an older Windows 10 installation (like 21H2). It apparently installs a Windows 11 WSL update which uses a different way of communication between host and WSL, so the drives cannot be mounted.

**Comment by benhillis** [comment] 2023-04-04 15:59
This issue is quite old, could somebody who is experiencing this please provide /logs?

1. sc stop wslservice
2. start collecting logs
3. repro issue
4. Add the below test to `%userprofile%\.wslconfig`
```
[wsl2]
virtio9p=false
```
6. wsl.exe --shutdown
7. attempt to repro issue, do the drives mount now?
8. stop collecting logs

**Comment by Sebazzz** [comment] 2023-04-04 16:02
> This issue is quite old, could somebody who is experiencing this please provide /logs?
> start collecting logs
> 

I presume you specifically mean [using collect-wsl-logs.ps1](https://github.com/microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1), right?

**Closed** 2023-04-21 16:26 UTC
Labels: needs-author-feedback, wsl2
