### ISSUE TITLE
WSL Install Ubuntu  0x80070003

### ISSUE THREAD

**Issue by smallprogram** [microsoft/WSL#11019] opened 2024-01-14 06:59 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3007]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu，Ubuntu22.04.3 LTS，Ubuntu22.04.6 LTS

### Other Software

Visual Studio 2022 17.8.3
Visual Studio code 1.85.1

### Repro Steps

```mermaid
flowchart TD 
01[Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux]
02[Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform]
03[Restart Windows]
04[Download Ubuntu from Microsoft Store]
05[Download Ubuntu 22.04.3 LTS from Microsoft Store]
06[Download Ubuntu 22.04.6 LTS from Microsoft Store]
07[Install Ubuntu]
08[Install Ubuntu 22.04.3 LTS]
09[Install Ubuntu 22.04.6 LTS]
10[Report 0x80070003]

    01 --> 02
    02 --> 03
    03 --> 04
    03 --> 05
    03 --> 06
    04 --> 07
    05 --> 08
    06 --> 09
    07 --> 10
    08 --> 10
    09 --> 10
```

### Expected Behavior

I hope this can be fixed and allow me to use WSL normally

### Actual Behavior

<img width="579" alt="image" src="https://github.com/microsoft/WSL/assets/6050360/0c88a3ad-0ae9-4bcd-a0cf-13ad3bbafe83">

I tried the following solutions, none of which worked:

1. run `wsl --update` ，The command is executed normally, but the problem is not solved ❌ 
2. Set the windows default storage path to `C:\`. After checking, the default path is originally `C:\`. Didn't solve the problem ❌
3. I tried windows update, but it said there was no update.❌
4. Modify the registry, HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive, to 1, useless❌
5. Delete the %USERPROFILE%\.wslconfig file, but there is no .wslconfig file in the %USERPROFILE% directory on my computer. Useless❌
6. Confirm whether the CPU virtualization function is enabled in the BIOS and confirm that it is enabled, but the problem is still not solved.❌
7. Use `chkdsk /f` to detect the disk without any problems❌
8. Use `netsh winsock reset` to reset the network, useless❌
9. Use `SFC /scannow` to check system integrity. No problems were found and the problem was not solved.❌

### Diagnostic Logs

[WslLogs-2024-01-17_16-56-32.zip](https://github.com/microsoft/WSL/files/13960809/WslLogs-2024-01-17_16-56-32.zip)

**Comment by smallprogram** [comment] 2024-01-17 08:58
> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> If you choose to email these logs instead of attaching to the bug, please send them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) with the number of the github issue in the subject, and in the message a link to your comment in the github issue.
> 
> Thank you!



> Hello! Could you please provide more logs to help us better diagnose your issue?
> 
> To collect WSL logs, download and execute [collect-wsl-logs.ps1](https://github.com/Microsoft/WSL/blob/master/diagnostics/collect-wsl-logs.ps1) in an **administrative powershell prompt**:
> 
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
> Set-ExecutionPolicy Bypass -Scope Process -Force
> .\collect-wsl-logs.ps1
> ```
> 
> The scipt will output the path of the log file once done.
> 
> Once completed please upload the output files to this Github issue.
> 
> [Click here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) for more info on logging
> 
> If you choose to email these logs instead of attaching to the bug, please send them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com) with the number of the github issue in the subject, and in the message a link to your comment in the github issue.
> 
> Thank you!

WSL Log updated

**Comment by smallprogram** [comment] 2024-01-17 08:58
> /logs please

Wsl log is update

**Comment by LaysonShen** [comment] 2024-04-03 05:05
Have you solved yet? I ran into the same problem and worse more I cannot start my docker

**Comment by smallprogram** [comment] 2024-04-03 08:23
> Have you solved yet? I ran into the same problem and worse more I cannot start my docker

I solved the problem by reinstalling Windows 11, but this problem also occurs on newly installed Windows 11. I don't know how to solve the problem without reinstalling the system.

**Comment by LaysonShen** [comment] 2024-04-03 09:02
Nope.If the only solution is to reinstall windows, I have to give up wsl LOL

在 2024-04-03 16:23:55，zhusir ***@***.***> 写道：

Have you solved yet? I ran into the same problem and worse more I cannot start my docker
I solved the problem by reinstalling Windows 11, but this problem also occurs on newly installed Windows 11. I don't know how to solve the problem without reinstalling the system.

**Comment by BinaryErrol** [comment] 2024-05-26 03:29
LOL

How is this not solved yet this is ridiculous

**Comment by LaysonShen** [comment] 2024-05-26 03:32
Yep, and the only solution for me is to install an Ubuntu somewhere on my SSD XD

在 2024-05-26 11:29:43，Ronewa ***@***.***> 写道：

LOL
How is this not solved yet this is ridiculous

**Comment by smallprogram** [comment] 2024-05-28 08:20
After many tests, I finally found that the problem was with my computer hardware, which was a CPU failure. The Intel 13900ks I bought last year ran unstable this year, which caused WSL to report an error. I changed to a new CPU via Intel and the problem was solved. However, this does not rule out the possibility of operating system errors.
At present, the problem has been solved by replacing the CPU and reinstalling the system.

**Comment by OneBlue** [comment] 2024-08-15 22:16
Closing since the issue is resolved.

**Closed by OneBlue** 2024-08-15 22:16 UTC
