### ISSUE TITLE
why I cant listion any port in WSL

### ISSUE THREAD

**Issue by yuantongkang** [Microsoft/WSL#2171] opened 2017-05-30 01:40 UTC
my windows version is 16188.1000
I also try to bulid a nodejs server,  browser also cant access the port 
![](https://ooo.0o0.ooo/2017/05/30/592cccc948432.png)
I also close the firewall and AV software,but it dosent work

**Comment by sunjoong** [comment] 2017-05-30 13:13
@yuantongkang - I think.... that's too small informations you gave for figureing it out. I found two comments from @sunilmut that describe to collect logs.

https://github.com/Microsoft/BashOnWindows/issues/1853#issuecomment-301176037 say about event auditing for 8000 port, but you need to modify it for 22 port in number 4 and 5 of that comment because you look like to raise issue for ssh (ssh port is 22). For number 5, open cmd.exe window and then command "`netstat -aqp tcp | findstr 22`" in that cmd.exe window.

https://github.com/Microsoft/BashOnWindows/issues/1554#issuecomment-294950891 is also about 8000 port and python web server in number 3 of that comment; you need to modify it for ssh.

**Comment by sunilmut** [comment] 2018-01-24 23:22
This looks duplicate of #1554. See if [this](https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927) comment helps you.

**Closed by sunilmut** 2018-01-24 23:22 UTC
