### ISSUE TITLE
wsl --import Unspecified Error / The specified network name is no longer available.

### ISSUE THREAD

**Issue by kristof-mattei** [microsoft/WSL#4835] opened 2020-01-21 20:05 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.19041.21]
* What you're doing and what's happening: 
Exported Ubuntu from C Drive due to size issues. I now have a .tar sitting on `D:\Ubuntu.tar`
Trying to import the file yields `Unspecified Error` or `The specified network name is no longer available.`
Command executed: `wsl --import Ubuntu-18.04 d:\WSL\Ubuntu-18.04\ d:\Ubuntu.tar`

* What's wrong / what should be happening instead:
This shouldn't happen, the Distro should import. 

* For WSL launch issues, please [collect detailed logs] [logs.zip](https://github.com/microsoft/WSL/files/4093456/logs.zip)
Logs attached!

**Comment by Kristof-Mattei** [comment] 2020-01-21 22:53
Update: 

When deleting `/usr` and `/var` from the tar the import works (WSL obviously doesn't work then...).

I'm suspecting either conflicts with the `overlay2` fs (docker), and/or the fact that in many folders there are files which only differ by case, not by name.

**Comment by antonymarion** [comment] 2020-03-12 10:19
Same for me.  Unspecified Error each time I try the wsl --import command on a previously exported (in.tar) image

**Comment by davidwudv** [comment] 2020-03-23 07:59
Same for me.

**Comment by nimamahmoudi** [comment] 2020-04-19 23:59
What worked for me was importing the WSL 2 distribution as WSL 1 using `--import ... --version 1`, and then convert it to version 2 using `--ser-version`.

**Comment by nimamahmoudi** [comment] 2020-04-20 00:01
But obviously this is a temporary workaround. In my case, the import would cause the RAM utilization to go to about 95%, and then I would see the aforementioned error. It seems like there is something wrong with importing large image sizes (mine was about 18GB).

**Comment by KnuX** [comment] 2020-05-02 19:18
Same here. @nimamahmoudi's method works but now running "wsl -d MyImportedDistrib" give me a root prompt instead of the correct user... ^^' (the import process can be speedup by excluding the install directory in defender...)

**Comment by Kristof-Mattei** [comment] 2020-05-06 21:29
@KnuX that is expected. https://github.com/microsoft/WSL/issues/3974 see here for fixes :)

**Comment by CharlieTheProgrammer** [comment] 2020-05-25 17:45
Ran into the same issue, which appears to be related to RAM. I'm on 8GB trying to import an image that is also about 8GB. I was able to get around this issue by temporarily increasing the virtual RAM to 16GB.

https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/how-to-increase-virtual-memory-in-windows-10-a/46dacaf5-15cf-4f5d-9d5a-cba1401ae4c9

**Comment by jerrodrs** [comment] 2020-06-05 00:20
I was getting this error on my WSL2 image which was 45GB. I ended up installing a new Ubuntu WSL2 instance then just copying over my vhdx file. Just had to setup my user again as it was logging in with 
 as root.

**Comment by alexvorobiev** [comment] 2020-06-12 03:15
The import fails for me with the Unspecified error regardless of whether I try version 1 or version 2. I have 16G of memory, the image size is about 2G. Is there any way to diagnose further?

**Comment by stormysky** [comment] 2020-06-29 03:23
I got same sutiation, after that I set "swap=120GB"  in .wslconfig file, it worked! @Kristof-Mattei this may be memory lack caused

**Comment by ss44** [comment] 2020-07-18 15:02
@nimamahmoudi solution of importing as v1 then converting was the only one that worked for me.

**Comment by charlysotelo** [comment] 2020-07-18 16:08
Only thing that worked for me was importing as v1 and turning it into v2.

**Comment by adolgoff** [comment] 2020-08-02 08:39
@stormysky Where is the .wslconfig file stored for WSL2? Or if it's not existing you need to create it by your own?

For me importing as V1 and converting then has worked out, but I've been able to login as root by default after re-import (not sure if it's connected to converting). So had to patch the register to fix it to my primary OS user.

**Comment by stormysky** [comment] 2020-08-06 07:56
@adolgoff  .wslconfig need to created strored at current user path (c:\users\xxxx, xxx is current user),

**Comment by Bobbbay** [comment] 2020-10-27 04:07
None of these work for me, I've tried importing as `v1` as well as modifying `.wslconfig`. No luck

**Comment by billy-king** [comment] 2021-04-16 09:49
I solved this problem after compact my wsl vdisk:
`wsl --terminate ubuntu-18.04
diskpart
DISKPART> select vdisk file=%USERPROFILE%\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx
DISKPART> compact vdisk`
After that, please try `wsl export` and `wsl import` again.

**Comment by Yogurt4** [comment] 2021-05-09 16:51
Maybe a duplicate of [issue #4735](https://github.com/microsoft/WSL/issues/4735).

**Closed** 2024-02-01 12:19 UTC
Labels: distro-mgmt
