### ISSUE TITLE
Windows Defender detects Ubuntu 16 nsupdate as Trojan

### ISSUE THREAD

**Issue by jarmo** [microsoft/WSL#4758] opened 2019-12-14 12:10 UTC
* Your Windows build number:
Microsoft Windows [Version 10.0.18363.535]

* What's wrong / what should be happening instead:
Defender detects `rootfs\usr\bin\nsupdate` inside of WSL Ubuntu 16 as `Trojan:Win64/Longage`. I don't think that should happen?

**Comment by jarmo** [comment] 2019-12-14 12:16
For some reason here it will not be detected as a trojan https://www.virustotal.com/gui/file/56b0c341b151ffa6e8472e9f1275bab02e39668ec1cf8589722ffeff15eb1a04/detection

**Comment by sirredbeard** [comment] 2019-12-16 00:00
Duplicate of #4757. Both are in dnsutils package.

**Closed** 2019-12-16 17:46 UTC
