### ISSUE TITLE
setpgid fails in fish shell

### ISSUE THREAD

**Issue by Perlence** [Microsoft/WSL#1210] opened 2016-10-15 20:26 UTC
In [fish](http://fishshell.com) 2.0.0 and newer, piping `find / -maxdepth 0` to any other command, e.g. `head`, returns an error.

Expected:

```
sviatoslav@7 ~> find / -maxdepth 0 | head
/
```

Got:

```
sviatoslav@7 ~> find / -maxdepth 0 | head
Could not send process 17, 'head' in job 1, 'find / -maxdepth 0 | head' from group 2 to group 16
setpgid: Operation not permitted
head: error reading ‘standard input’: Input/output error
```

My Windows build number is 14393.321

To install fish, run `sudo apt install fish`

**Comment by stehufntdev** [comment] 2016-10-17 14:52
Thanks for reporting the issue.  Can you please collect a strace with follow forks of the failing command?

**Comment by Perlence** [comment] 2016-10-17 18:13
Well, as odd as it is, the command works when invoked like this:

```
sviatoslav@7 ~> fish -c "find / -maxdepth 0 | head"
/
sviatoslav@7 ~> echo "find / -maxdepth 0 | head" | fish
/
```

I thought I would run `strace -f -o fish.log fish -c "find / -maxdepth 0 | head"`, but it works that way 🤔

**Comment by Perlence** [comment] 2016-10-17 18:29
Actually, flag `-maxdepth 0` is not significant:

```
sviatoslav@7 ~> find | head
Could not send process 5772, 'head' in job 1, 'find | head' from group 3 to group 5771
setpgid: Operation not permitted
head: error reading ‘standard input’: Input/output error
```

**Comment by Perlence** [comment] 2016-10-17 21:09
Ok, I couldn't reproduce the error in follow forks mode, so here's strace attached to a fish interactive session right before executing `cat blank | head` https://gist.github.com/Perlence/691e956985e556b8e359e36bcd40d4cc

**Comment by stehufntdev** [comment] 2016-10-19 15:48
Thanks for providing the strace, but there's not much information we can get without follow forks since the error is happening in the child process.  I double checked the strace and confirmed.  We'll have to try and get a local repro for debugging.

**Comment by aandreev** [comment] 2016-10-28 12:33
I am having a similar issue on build 14955:
`~ λ> touch mouse

~ λ> cat mouse | sort | uniq | wc -l
Could not send process 257, 'sort' in job 1, 'cat mouse | sort | uniq | wc -l' from group 15 to group 256
setpgid: Operation not permitted
sort: read failed: -: Input/output error
Could not send process 258, 'uniq' in job 1, 'cat mouse | sort | uniq | wc -l' from group 15 to group 256
setpgid: Operation not permitted
uniq: error reading '-'
Could not send process 259, 'wc' in job 1, 'cat mouse | sort | uniq | wc -l' from group 15 to group 256
setpgid: Operation not permitted
wc: 'standard input': Input/output error
0

~ λ> id
uid=1000(andrey) gid=1000(andrey) groups=1000(andrey),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev)

~ λ> sudo cat mouse | sort | uniq | wc -l
[sudo] password for andrey:
0

~ λ> ll mouse
-rw-rw-rw- 1 andrey andrey 0 Oct 28 14:21 mouse

~ λ> fish -c "cat mouse | sort | uniq | wc -l"
0

~ λ> pstree
init─┬─bash───tmux
     └─tmux───fish───pstree`

**Comment by aandreev** [comment] 2016-10-28 12:37
Strangely enough, if i continue with:
```
~ λ> strace -o fishdump -ff fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

~ λ> cat mouse | sort | uniq | wc -l
0

~ λ> pstree
init─┬─bash───tmux
     └─tmux───fish───strace───fish───pstree
````
it works?!?!

**Comment by Perlence** [comment] 2016-10-28 12:42
@aandreev Yep, I was puzzled by this too :smile:

**Comment by aandreev** [comment] 2016-10-28 14:42
Looks to me like a race condition. I occasionally get it to run, and always under strace.
```
Welcome to fish, the friendly interactive shell                                                                                                                                                                                                                                                           [6/6]Type help for instructions on how to use fish

~ λ> cat mouse | sort | uniq | wc -l
0

~ λ> cat mouse | sort | uniq | wc -l
Could not send process 59, 'sort' in job 1, 'cat mouse | sort | uniq | wc -l' from group 15 to group 58
setpgid: Operation not permitted
sort: read failed: -: Input/output error
Could not send process 60, 'uniq' in job 1, 'cat mouse | sort | uniq | wc -l' from group 15 to group 58
setpgid: Operation not permitted
uniq: error reading '-'
Could not send process 61, 'wc' in job 1, 'cat mouse | sort | uniq | wc -l' from group 15 to group 58
setpgid: Operation not permitted
wc: 'standard input': Input/output error
0
```

**Comment by aandreev** [comment] 2016-10-28 16:20
Confirming it is a timing issue. If I load the CPU by
```
 bash -c 'fulload() { dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null | dd if=/dev/zero of=/dev/null & }; fulload; read; killall dd'
```
I am getting the cat pipe to run almost always successfully, with rare errors.

**Comment by saschagehlich** [comment] 2016-11-24 18:14
@aandreev Is this something that needs to be fixed by MS or by the fish people?

**Comment by mqudsi** [comment] 2017-04-06 21:03
I'm pretty sure this is a WSL bug that could be worked around in fish, but the right fix would have to come from MSFT? Please correct me if I'm wrong, though!

**Comment by gglanzani** [comment] 2017-04-18 20:12
I'm getting hit by this pretty hard as well since the latest release. Probably WSL is now more efficient, so I hit the race condition more often :P

**Comment by benhillis** [comment] 2017-07-06 16:26
I have been unable to reproduce this in Creator's update.  If anybody is able to reproduce this reliably with build 15063 or later please let me know.

**Comment by mqudsi** [comment] 2017-07-06 16:26
I experience this on a semi-daily basis on 15063.

**Comment by benhillis** [comment] 2017-07-06 16:29
@mqudsi - Do you have some consistent repro instructions? That would be very useful.  Now that I'm looking at this path again I believe this may have been fixed after Creator's Update, potentially related to #1973.

**Comment by mqudsi** [comment] 2017-07-06 16:44
I just ran this twice, it succeeded the first time and crashed the second:

     cat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)/\1: \2/g'

Here's the actual shell output:

	mqudsi@ZBook ~/r/f/doc_src> cat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)/\1: \2/g'
	mqudsi@ZBook ~/r/f/doc_src> cat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)/\1: \2/g'
	Could not send process 4252, 'egrep' in job 1, 'cat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)' from group 3819 to group 4251
	setpgid: Operation not permitted
	Could not send job 1 ('cat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)') to foreground
	tcsetpgrp: Operation not permitted
	Could not send process <4253W, '>sed ' in job f1i, 'scat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)h' from group :3819  to group C4251o
	usetpgid: Operation not permitted
	ld Could not send job n1o ('tcat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*) ') to foregrounds
	etcsetpgrp: Operation not permitted
	nd job 1 ('cat string.txt | egrep "^fn .*\[" | sed -r -e 's/fn ([^(]+)(.*)/\1: \2/g'') to foreground
	tcsetpgrp: Operation not permitted
	Job 1, 'cat string.txt | egrep "^fn .*\…' has stopped
	mqudsi@ZBook ~/r/f/doc_src>


The problem is that this cannot be reproduced if fish is running under strace.

**Comment by mqudsi** [comment] 2017-07-09 01:47
@benhillis can we re-open? Just don't want this to get lost.

**Comment by benhillis** [comment] 2017-08-15 15:10
I believe this was fixed in 16251.  Please let me know if you're still experiencing issues.

**Comment by mqudsi** [comment] 2017-08-15 16:21
@benhillis so I tracked down this bug on the fish side of things and the only idiosyncrasy I could find in WSL was that sometimes immediately after a new process group is created, EPERM is returned when another tries to join this group (via `tcsetpgrp`) but upon retry, the operation succeeds. Could you possibly expound on the fix for this to see if it matches our experience? In the meantime, fish 3.0 pre release builds work around the issue.

**Comment by benhillis** [comment] 2017-08-15 16:41
Didn't mean to close this, buttons are too close together.  There were some tty related bugfixes in the build I linked that I believe will have resolved this.  @mqudsi - Are you still able to reproduce this issue?

**Comment by mqudsi** [comment] 2017-08-15 16:44
@benhillis I'm on 15063 because my pasts experience with beta builds taught me that symbols are almost never available, which made getting useful info out of BSODs impossible. So I can't comment on whether it's fixed in 16251. My commits to Fish should avoid the issue from appearing to the end user entirely in all cases if they're running an up-to-date build, but that shouldn't be taken as an issue that the `tcsetpgrp` matter was resolved, naturally.

**Comment by mqudsi** [comment] 2017-08-15 16:57
@benhillis sorry, I somehow didn't catch what you said about tty. The problem we ran into seemed to affect both foreground and background process with and without terminal input/output equally; I don't think that would take care of it. It was almost as if tcsetpgrp was querying an out-of-date snapshot of process groups instead of the latest.

**Comment by arooni** [comment] 2018-03-03 20:10
Would this error (trying to use fish shell + fisher + fzf plugin) be related to this bug?

v/w/m/wp-content ÓÇ∞ Could not send process 23992, '__fzfcmd' in job 2, 'history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r ' from group 30993 to group 23717
setpgid: Operation not permitted
Could not send job 2 ('history | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r ') to foreground
tcsetpgrp: No such process
ls
<W> fish: Could not send job 2 (‚Äúhistory | __fzfcmd +s +m --tiebreak=index --toggle-sort=ctrl-r | read -l select‚Äù) to foreground
tcsetpgrp: No such process

**Closed** 2018-03-26 00:34 UTC
Labels: fixedincreatorsupdate
