### ISSUE TITLE
"Failed to translate" errors in CreateProcessParseCommon and UtilTranslatePathList

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/WSL#8723] opened 2022-08-14 08:53 UTC
### Version

WSL version: 0.65.3.0 Kernel version: 5.15.57.1 WSLg version: 1.0.41 MSRDC version: 1.2.3213 Direct3D version: 1.601.0 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.22000.856

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

Linux version 4.4.0-22000-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #653-Microsoft Wed Apr 27 16:06:00 PST 2022

### Distro Version

Debian 11

### Other Software

A functioning [JDK](https://github.com/openjdk/jdk/) build/test setup

### Repro Steps

`make TEST='test/jdk/tools/launcher/ClassPathWildCard.sh' test`

### Expected Behavior

No WSL errors occur

### Actual Behavior

The following occurs on stderr:
```
<3>WSL (206) ERROR: CreateProcessParseCommon:731: Failed to translate E:\Repositories\com.github\jdk\build\windows-x86_64-server-release\test-support\jtreg_test_jdk_tools_launcher_ClassPathWildCard_sh\scratch\0
<3>WSL (206) ERROR: UtilTranslatePathList:2509: Failed to translate e:\repositories\com.github\jdk\build\windows-x86_64-server-release\images\jdk
<3>WSL (206) ERROR: UtilTranslatePathList:2509: Failed to translate e:\repositories\com.github\jdk\build\windows-x86_64-server-release\images\jdk
<3>WSL (206) ERROR: UtilTranslatePathList:2509: Failed to translate E:\Repositories\com.github\jdk\test\jdk
<3>WSL (206) ERROR: UtilTranslatePathList:2509: Failed to translate e:\repositories\com.github\jdk\build\windows-x86_64-server-release\images\test\jdk\jtreg\native
sh: 0: Can't open /mnt/e/Repositories/com.github/jdk/test/jdk/tools/launcher/ClassPathWildCard.sh
```

### Diagnostic Logs

[strace-ff.zip](https://github.com/microsoft/WSL/files/9332979/strace-ff.zip)
[WslLogs-2022-08-14_10-40-46.zip](https://github.com/microsoft/WSL/files/9332980/WslLogs-2022-08-14_10-40-46.zip)
[strace-no-ff.log](https://github.com/microsoft/WSL/files/9332981/strace-no-ff.log)

**Comment by OneBlue** [comment] 2022-08-16 21:10
Thanks for reporting this @anthonyvdotbe.

What kind of folder is `E:\Repositories\com.github\jdk` ? Is it a symlink / reparse point ? 

I'd be curious to see the output of `Get-Acl :\Repositories\com.github\jdk\test\jdk | Format-list` as well

**Comment by anthonyvdotbe** [comment] 2022-08-17 07:16
> Thanks for reporting this @anthonyvdotbe.

Thanks for investigating.

> What kind of folder is `E:\Repositories\com.github\jdk` ? Is it a symlink / reparse point ?

It's a regular folder. However, E: is a mounted BitLocker-encrypted .vhdx file, so that might play a role. And the .vhdx file itself is located in my user folder on C:, where C: is the BitLocker-encrypted system partition.

> I'd be curious to see the output of `Get-Acl :\Repositories\com.github\jdk\test\jdk | Format-list` as well

(ETA is an Active Directory domain)

```
PS E:\> Get-Acl E:\Repositories\com.github\jdk\test\jdk | Format-list

Path   : Microsoft.PowerShell.Core\FileSystem::E:\Repositories\com.github\jdk\test\jdk
Owner  : ETA\VANELVEA
Group  : ETA\VANELVEA
Access : BUILTIN\Administrators Allow  FullControl
         BUILTIN\Administrators Allow  268435456
         NT AUTHORITY\SYSTEM Allow  FullControl
         NT AUTHORITY\SYSTEM Allow  268435456
         NT AUTHORITY\Authenticated Users Allow  Modify, Synchronize
         NT AUTHORITY\Authenticated Users Allow  -536805376
         BUILTIN\Users Allow  ReadAndExecute, Synchronize
         BUILTIN\Users Allow  -1610612736
Audit  :
Sddl   : O:S-1-12-1-837982814-1106714980-3376534193-400267843G:S-1-12-1-837982814-1106714980-3376534193-400267843D:(A;I
         D;FA;;;BA)(A;OICIIOID;GA;;;BA)(A;ID;FA;;;SY)(A;OICIIOID;GA;;;SY)(A;ID;0x1301bf;;;AU)(A;OICIIOID;SDGXGWGR;;;AU)
         (A;ID;0x1200a9;;;BU)(A;OICIIOID;GXGR;;;BU)
```

**Comment by OneBlue** [comment] 2022-09-09 18:50
Thank you @anthonyvdotbe. Out of curiosity, do you see the same errors if you start wsl.exe as administrator ?

**Comment by anthonyvdotbe** [comment] 2022-09-10 05:38
@OneBlue I deleted my JDK setup because of all the BSODs I ran into (#8803 #8805 #8469), so I can't readily answer now. Having the mentioned BSOD issues resolved would help tremendously in providing exact reproduction steps for this issue as well.

**Comment by mklueh** [comment] 2022-11-20 15:41
Facing the same problem with one of the latest updates.

What I did long before was preventing auto-mounts, because I don't want WSL to have access to my Windows directories

**/etc/wsl.conf**
```
[automount]
enabled=false
mountFsTab=true
```


**stdout**
```
<3>WSL (1300) ERROR: CreateProcessParseCommon:782: Failed to translate C:\WINDOWS\system32
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\tools\ruby31\bin
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Python27\
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Python27\Scripts
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\nodejs\default
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Program Files\nodejs
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\system32
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32\Wbem
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Windows\System32\OpenSSH\
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\ProgramData\chocolatey\bin
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\MyUser\AppData\Roaming\Python\Python37\Scripts
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\MyUser\AppData\Local\Programs\Python\Python37-32\Scripts\
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\MyUser\AppData\Local\Programs\Python\Python37-32\
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\Users\MyUser\AppData\Local\Microsoft\WindowsApps
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS\system32
<3>WSL (1300) ERROR: UtilTranslatePathList:2671: Failed to translate C:\WINDOWS
```

**Comment by OneBlue** [comment] 2022-11-21 18:06
Thank you @mklueh. Can you share the content of `/etc/fstab` ?

**Comment by flipkickmedia** [comment] 2022-11-21 18:47
FWIW this fstab works ok without errors being rendered

```
LABEL=cloudimg-rootfs   /       ext4    discard,errors=remount-ro 0 1
C: /c drvfs defaults,rw,noatime,dirsync,uid=1000,gid=130,mmap,access=client,msize=262144,trans=virtio,case=off 0 1
C:/Users/tbmst/.cme  /home/tshaw/.cme drvfs defaults,rw,noatime,dirsync,uid=130,gid=130,mmap,access=client,msize=262144,trans=virtio,case=off 0 1
```

**Comment by OneBlue** [comment] 2022-11-21 19:19
Interesting. Does this reproduce all the time when you open WSL ? 

Does starting WSL as administrator / non administrator make a difference ?

**Comment by flipkickmedia** [comment] 2022-11-21 19:31
Starting wsl as a normal/admin user makes no difference.

I only get these errors whilst I'm setting up the WSL instance.  I'm about to do another iteration on the setup script so when I get there I'll post all the logs etc you asked for.originally.

**Comment by OneBlue** [comment] 2022-11-21 19:38
Oh I see. In that case, it's expected (since until the instance has been restarted, the fstab will not be mounted and so init will fail to translate the Windows path, which explains the warnings).

**Comment by flipkickmedia** [comment] 2022-11-21 19:50
So in this case, after downloading the rootfs, importing it then launching it is where the errors show.  I'm sure you're correct but do you think these errors are valid and should be shown?

**Comment by mklueh** [comment] 2022-11-21 21:35
@OneBlue 

/etc/fstab: LABEL=cloudimg-rootfs   /        ext4   defaults        0 1

But why did this not happen some versions before and just appeared recently? Is there any good reason to show those errors every time now?

**Comment by flipkickmedia** [comment] 2022-11-21 23:29
@mklueh this started happening for me after installing the wsl feature from the app store on a h22 upgraded Windows 11

**Comment by mishka81** [comment] 2022-11-22 08:04
Same errors everytime I log in my ubuntu 20.04 instance

`PS C:\Users\ms> wsl --version
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1219`

This appeared after upgrading my "inbox" WSL (kernel version 5.10.102 ) to the Microsoft Store version

**Comment by flipkickmedia** [comment] 2022-11-22 22:11
I've gotten to the bottom of the issues I was having.  This relates to the `/etc/fstab` failing to have the correct entries after you import the rootfs.

```
$targetPath="c:\somepathforwslinstance"
$tarGzPath="C:\users\tshaw\Documents\ubuntu-kinetic-wsl-amd64-wsl.rootfs.tar.gz"
$instanceName="testWSL"
wsl --import $instanceName "$targetPath" "${tarGzPath}"
```

```
*** do not stop this process or you will hang the WSL subsystem ***
Import in progress, this may take a few minutes.
The operation completed successfully.
```

```
wsl --distribution wslTest
```
No errors.

```
$ cat /etc/fstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM
```
So after the import, everything is ok apart from the empty fstab.  Let's clear the fstab..
```
$ echo -e "" >/etc/fstab
$ exit
wsl --distribution testWSL
```
No errors

```
$ mount
---8< snip----
drvfs on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=0;gid=0;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio)
```
So we can see our C: drive mounted despite it not being listed in `/etc/fstab`.

```
$ ls /etc/wsl.conf
ls: cannot access '/etc/wsl.conf': No such file or directory
```

/etc/wsl.conf and .wslconfig do not exist.

The problem seems simple enough, where someone has setup their WSL installation using the app store, their fstab will not have the correct entries so any additional mounts added after will fail.

**Comment by mklueh** [comment] 2022-11-22 22:22
@flipkickmedia 
> The problem seems simple enough, where someone has setup their WSL installation using the app store, their fstab will not have the correct entries so any additional mounts added after will fail.

In my case I tried to get rid of the standard mounts so WSL can't interfere with the actual Windows system. I believe I did nothing except for disabling the auto mounts. And I'm also not sure if I've installed it via Windows Store. At least none of the Ubuntu "Apps" in the store says "Installed already"

**Comment by flipkickmedia** [comment] 2022-11-22 22:45
@mklueh I updated my comment, if you use
```
[automount]
enabled = false
root = /
options = `"metadata, mask=22`"
mountFsTab = true
```

you will see errors. This is a bug.

**Comment by flipkickmedia** [comment] 2022-11-22 22:46
> @flipkickmedia
> 
> > The problem seems simple enough, where someone has setup their WSL installation using the app store, their fstab will not have the correct entries so any additional mounts added after will fail.
> 
> In my case I tried to get rid of the standard mounts so WSL can't interfere with the actual Windows system. I believe I did nothing except for disabling the auto mounts. And I'm also not sure if I've installed it via Windows Store. At least none of the Ubuntu "Apps" in the store says "Installed already"

I did the same thing.

**Comment by OneBlue** [comment] 2022-11-24 01:08
> @mklueh I updated my comment, if you use
> 
> ```
> [automount]
> enabled = false
> root = /
> options = `"metadata, mask=22`"
> mountFsTab = true
> ```
> 
> you will see errors. This is a bug. Specifically, if you `enabled=false` under automount.

To give some context on this:

If the drives are not mounted, WSL cannot translate between Windows and Linux path. If that's what you want, you can set:

```
[interop]
appendWindowsPath = false
```
in `/etc/wsl.conf`  and the warnings will go away.

If automount is disabled but you have manual mounts in `/etc/fstab`, the distribution needs to restarted for path translation to work.

Closing since this should cover both scenarios.

**Closed by OneBlue** 2022-11-24 01:08 UTC
Labels: needs-author-feedback

**Comment by flipkickmedia** [comment] 2022-11-24 11:41
You still get errors with the setup you provided. This needs to be reopened.

**Comment by bekacodex** [comment] 2022-12-01 07:06
<3>WSL (70) ERROR: CreateProcessParseCommon:782: Failed to translate D:\Kali Linux UIUX
<3>WSL (70) ERROR: UtilTranslatePathList:2671: Failed to translate D:\Programma\Java\bin
<3>WSL (70) ERROR: UtilTranslatePathList:2671: Failed to translate D:\Fullter\src\bin
<3>WSL (70) ERROR: UtilTranslatePathList:2671: Failed to translate D:\Fullter\flutter_windows_3.3.7-stable\flutter\bin
<3>WSL (70) ERROR: UtilTranslatePathList:2671: Failed to translate D:\Fullter\flutter\bin
<3>WSL (70) ERROR: UtilTranslatePathList:2671: Failed to translate D:\Programma\Vs Code\Microsoft VS Code\bin
Failed to mount D:\, see dmesg for more details.

┏━(Message from Kali developers)
┃
┃ This is a minimal installation of Kali Linux, you likely
┃ want to install supplementary tools. Learn how:
┃ ⇒ https://www.kali.org/docs/troubleshooting/common-minimum-setup/
┃
┗━(Run: “touch ~/.hushlogin” to hide this message)
┌──(code-x13㉿WIN-6G2CFD61UB7)-[~]





<<WHAT IS MY D: >>

**Comment by protella** [comment] 2022-12-16 18:04
@OneBlue 

This issue still exists. I just updated WSL to the store version per the startup text recommendation in WSL. After this, my Ubuntu2004 installation now won't mount /mnt/c or /mnt/d. 
Manaually attempting to mount them throws this message (the same one that's found in dmesg.
```
mount -t drvfs c: /mnt/c/
<3>WSL (236) ERROR: MountWithRetry:306: mount(drvfs, /mnt/c, 9p, 0x00000000, cache=mmap,msize=262144,trans=virtio,aname=drvfs;path=c:;symlinkroot=/) failed: Invalid argument
```

This has broken my vscode integration as well and my entire development workflow depended on these translations being functional. Is there a workaround? I've tried several of the above methods in this thread.

**Comment by flipkickmedia** [comment] 2022-12-18 20:32
The other thread at https://github.com/microsoft/WSL/issues/9167 was closed as well.

....completely ignoring any sort of actual development QA process.

In short, there is now an additional dependency that you MUST have an instance of your C: drive mounted in order for WSL to work without errors being shown which is completely undocumented, goes against the documentation for the WSL flags.

@OneBlue please reopen this.

**Comment by protella** [comment] 2022-12-18 21:47
I Uninstalled the store app version until this is addressed. Luckily this allowed wsl to revert to the previous version and everything works again.

Side note, I also attempted to install a fresh distribution and the issue persists there as well. How can this clear QA? It has to have broken things for many users.

@flipkickmedia did you have any details of your work around of having the C: mounted as you mentioned? Are you referring to using the external wsl mount command?

**Comment by flipkickmedia** [comment] 2022-12-18 23:12
> I Uninstalled the store app version until this is addressed. Luckily this allowed wsl to revert to the previous version and everything works again.
> 
> Side note, I also attempted to install a fresh distribution and the issue persists there as well. How can this clear QA? It has to have broken things for many users.
> 
> @flipkickmedia did you have any details of your work around of having the C: mounted as you mentioned? Are you referring to using the external wsl mount command?

Unfortunately not :(

It seems that with this version of WSL, after trying every possible combination of mounts, flags, etc it all still fails.  However....if you build a WSL instance, using the old version, then upgrade your WSL, this runs without issue and you don't see the errors.

If you distribute the vhdx file used to build the WSL instance, and import it (details below) you can work round these issues.

On a side note, if you do happen to have a machine with the old version on, create a new WSL instance without the changes and compare the two that might provide some sort of solution whilst Microsoft closes some more tickets without actually fixing the problem.

**Comment by OneBlue** [comment] 2022-12-20 20:55
> @OneBlue You still get errors with the setup you provided. This needs to be reopened.
> 
> /etc/fstab
> 
> ```
> #empty
> ```
> 
> /etc/wsl.conf
> 
> ```
> [automount]
> enabled = false
> root = /
> options = metadata, mask=22
> mountFsTab = true
> [network]
> generateHosts = true
> generateResolvConf = true
> [user]
> default = tshaw
> [interop]
> appendWindowsPath = false
> enabled = false
> ```
> 
> C:\Users\tbmst>wsl --distribution cme-kinetic
> 
> ```
> <3>WSL (9) ERROR: CreateProcessParseCommon:782: Failed to translate C:\Users\tbmst
> <3>WSL (9) ERROR: CreateProcessEntryCommon:345: getpwnam(tshaw) failed 0
> ```
> 
> Where is `C:\Users\tbmst` path being required in the WSL instance? This is a fresh imported rootfs.
> 
> [WslLogs-2022-11-24_15-12-29.zip](https://github.com/microsoft/WSL/files/10085663/WslLogs-2022-11-24_15-12-29.zip)

@flipkickmedia: Looking at the logs, it looks like there is something wrong with you `/etc/passwd` file. Can you share its content on this issue ? 

This is clearly a different problem than the one this issue was created on so please open a new issue to track this

**Comment by flipkickmedia** [comment] 2022-12-21 12:47
Done - https://github.com/microsoft/WSL/issues/9384

**Comment by Sebazzz** [comment] 2023-02-10 12:56
As I mentioned in #4122:

> I believe this also occurs when you have run `wsl --update` on an older Windows 10 installation (like 21H2). It apparently installs a Windows 11 WSL update which uses a different way of communication between host and WSL, so the drives cannot be mounted.

**Comment by protella** [comment] 2023-03-04 01:31
For anyone still experiencing this issue, I seem to have figured out why it was occurring for me. As I was migrating my distro to a new laptop, I copied over my `.wslconfig` in my windows profile root directory. Apparently I didn't initially copy over a custom kernel image that I was using on the old machine and things had been working fine until then on the new laptop. I went back and copied down that image (bzImage2 for me) and then as soon as i did a wsl --shutdown and restarted my distro, these errors returned. I commented out the `# kernel=C:\\Users\\myser\\bzImage2` line in .wslconfig and all was well again. I had forgotten I'd done this a while back. Apparently using the old kernel is what broke this after later updates to WSL and how it handles mounts.

**Comment by devindang** [comment] 2023-03-24 15:54
> I haven't had time to dig into this, but will report I too am seeing this problem after an update to wsl:
> 
> ```
> <3>WSL (7916) ERROR: UtilTranslatePathList:2721: Failed to translate \\xxx\public\dnt\tools
> <3>WSL (7916) ERROR: UtilTranslatePathList:2721: Failed to translate \\xxx\public\dnt\tools\inetW7\bin
> Sleeping for 1 second to let systemd settle
> Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)
> ```
> 
> \xxx is a LAN share, that contains nothing I would have ever intentionally associated with WSL (they contain private windows utilities). This is the first thing output (above the "systemd settle" message). They are in the PATH (exe search path) of the hosting environment, but other than that they are not attached/mounted on the host (for example psdrive doesn't show them). Nor are they mentioned in the WSL session's /etc/ftab (nor any /etc/*.conf, I grep for it, nor any $HOME files). Does WSL do anything with the host search path before/during starting an instance?
> 
> Note that I read @Sebazzz comment above and this seems to be the case, in that this is a Win10 19044 host, am I seen a new .systemd-env file in my home directory which as a "WAYLAND_DISPLAY" setting. In this case WSL is working and a --shutdown doesn't change anything. Perhaps some Win10/WSL snafu.

Thanks, after deleted invalid ENVIRONMENT, and execute `wsl --shutdown`, it disappeared.

**Comment by maczamora** [comment] 2023-04-13 01:37
After performing a wsl--shutdown this got rid of some problems, I'm still seeing the following though: 

`<3>WSL (143) ERROR: CreateProcessParseCommon:789: Failed to translate \\wsl.localhost\Ubuntu\home\marzamor
 * start-stop-daemon: wsl-vpnkit is already running`

Not sure how or why. All that I do know is that I started to see these problems after running wsl --update because I was trying to install and run an app on WSL Linux. Actually, that app didn't work... unfortunately but somehow now that I updated I ran into all these issues. Some of the initial issues have to deal with mounting C: drive. Again, performing a simple wsl --shutdown and relaunching appears to help but still can't find an explanation as to why this error comes up.

If someone could provide me some context as to why these issues happened, timelines on fix, or any other details that would be appreciated. Just more or less hurts the developers lifecycle and workflow especially if we have work to get done. Make's things really unreliable. 

`WSL version: 1.2.0.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2728`

**Comment by Dweeberly** [comment] 2023-04-13 16:25
@maczamora Sorry to hear that.  I have a very similar problem.  This ticket and, best I found as of March, all other tickets like this have been closed.  Pretty much according to the WSL project, this never actually happens and anyone who encounters it is confused and imaging things. <sigh>  You can tell by the '\' paths this is a problem on the Windows side and it occurs (for me) every time I open a shell.  

If you happen across any useful documentation as to how WSL boots or what it does before opening a new shell, please post it here.  I've had no time to dig into this since encountering it, so I just live with it.  Be very careful updating anything WSL or Ubuntu.  I bricked my Ubuntu because the folks that made it thought it would be very clever replacing a text MOTD file with a live python script and their update broke it.  Fixing it seemed to run afoul of whatever WSL does in the boot process.  However, at that point I was quite frustrated and just saved my files, deleted Ubuntu and added OpenSuse which can least reliably process their own MOTD file.   OpenSuse exhibits exactly the same " Failed to translate" ... because it's clearly a Window's side problem <sigh>  Getting OpenSuse Leap to run docker (under WSL) is not something I'd recommend, worked fine under Ubuntu. Sooo... <sigh>

If you are using any of this for a time sensitive project, or depend on it for daily productivity, my advice is _never - ever update WSL or a linux distro running under it_.  If you need a "newer" distro just create a new WSL distro install and work from that.   WSL is impressive, but it's clearly reached the point where any additional added complexity destabilizes it.  Linux is equally impressive, but no two distros run, act or are managed in the same way.  Just pick a distro and never upgrade it.  This is of course bad advice security-wise, but there aren't really good alternatives ATM. ... Oh and always keep a backup.  Remember you can reach your WSL Linux filesystems via \\WSL$\

**Comment by ajaxStardust** [comment] 2023-04-15 06:02
> After performing a wsl--shutdown this got rid of some problems, I'm still seeing the following though:

I too was experiencing this problem, but after wsl --shutdown / wsl -t Distroname

I believe it's worth nothing that the paths reported in the stdout in my situation are the same as in my windows sytem %PATH% environment variable. 

i reopened the WSL terminal directly w/ admin privs, and did not experience the issue any longer. i have not restarted my system. 

[WslLogs-2023-04-15_01-52-53.zip](https://github.com/microsoft/WSL/files/11238483/WslLogs-2023-04-15_01-52-53.zip)

**Comment by MySurmise** [comment] 2023-05-28 14:55
I also have this issue.
When I try to open wsl from the mapped network drive, e.g. in Z:\Studium I get:
`<3>WSL (403) ERROR: CreateProcessParseCommon:789: Failed to translate Z:\Studium
`
If I start it in %userprofile% and cd into the folder, though, it works:
```
ll /mnt/z/studium
total 16K
drwxr-xr-x 2 root root   0 Sep  5  2022 'Semester 1'
...

```
My fstab:
```
LABEL=cloudimg-rootfs   /       ext4    discard,errors=remount-ro 0 1
//192.168.0.42/data /mnt/z cifs defaults,credentials=/etc/smbcredentials,vers=3.0 0 0
```
My wsl.conf:
```
[automount]
enabled = true
mountFsTab = true
[boot]
systemd=true
```
My current workaround for this is to create a symbolic link to the network share in Windows and then start wsl from there. Not ideal, but works:
I created the symbolic link %userprofile%\Documents\Studium -> Z:\Studium
```
~/Documents/Studium/Semester 4 
> wsl
wslname at pcname in /mnt/z/Studium/Semester 4
>
```
