### ISSUE TITLE
Error: 0x80070005 after installing on Win10 Skip Ahead build 17618

### ISSUE THREAD

**Issue by richlilly2004** [Microsoft/WSL#3020] opened 2018-03-13 00:55 UTC
Installed the new Kali build yesterday and received the following, on a Skip Ahead Insider build:

Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...

Also bash from PowerShell throws teh same

**Comment by Biswa96** [comment] 2018-03-13 04:14
Did you install it from Windows Store?

**Comment by benhillis** [comment] 2018-03-13 22:40
Could you collect logs?

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by chwarr** [comment] 2018-04-24 00:26
@benhillis, I believe I'm having the same problem. I've collected the ETL logs. Shall I attach them here, or do you want me to send them to you another way?

Problem: attempting to launch Ubuntu on Windows 10 Version 1803 (OS Build 17133.1) fails with "Error: 0x80070005".

Repro steps:

1. `ubuntu /clean`
1. Go to Apps in Setting and remove the Ubutnu app
1. Visit https://aka.ms/wslstore
1. Install Ubuntu
1. From an admin command prompt, start the 3 logman.exe traces.
1. From a non-elevated command prompt run `ubuntu`.
1. Stop the three logman traces.

Expected results:

Prompted to set username and password.

Actual results:
```
C:\Users\chwarr>ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
```

**Comment by Biswa96** [comment] 2018-04-24 03:26
Try to run kali.exe in start menu as administrator.

**Comment by chwarr** [comment] 2018-04-25 08:01
Tickle. I have logs for the repro running `ubuntu` , but I need instructions for how to get them to you, as I believe they have PII inside of them.

**Comment by DarthSpock** [comment] 2018-04-25 18:53
@chwarr, out of curiousity, did you try using `wsl.exe` under an elevated CMD/PS? If the appx is installed, some users have reported using this works around the issue and afterwards they can run distro.exe. Note that `wsl.exe` will launch your default distro. You'll need `wslconfig.exe` to change the default, in case you need to do the same thing for each distro.

**Comment by chwarr** [comment] 2018-04-25 22:02
`wsl` is reporting that there are no distros installed:

```
4/25/2018 3:01:45 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [5] # wslconfig /l
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
4/25/2018 3:01:48 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [6] # wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
```

**Comment by Biswa96** [comment] 2018-04-26 01:32
I sais.run Kali as administrator for first time. The use wal.exe.

**Comment by chwarr** [comment] 2018-04-26 19:03
Good suggestion, @Biswa96: elevated vs. unelevated doesn't appear to matter.

The run in [my previous comment](https://github.com/Microsoft/WSL/issues/3020#issuecomment-384196147) was unelevated.

Here's an elevated run:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 7398ms.
4/26/2018 12:02:13 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  jobs: 1  [1] # get-command kali

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     kali.exe                                           0.0.0.0    C:\Users\chwarr\AppData\Local\Microsoft\WindowsApps\kali.exe


4/26/2018 12:02:23 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [2] # kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
```

**Comment by Biswa96** [comment] 2018-04-26 19:11
That's weired. This problem arises in my PC in build 17650, not in previous builds. Only elevated command prompt can install tar.gz. Although I haven't tried with Store Apps.

**Comment by DarthSpock** [comment] 2018-04-26 19:53
Shouldn't need to run elevated for extraction, very odd. Ok so just to verify this isn't a dupe/regression, how about restarting the LXSS service (if you even see it running). What would be ironic is if the issue is simply because all the Store apps updated to use the updated launcher from https://github.com/Microsoft/WSL-distrolauncher. Of course the only way to test that is to manually compile it yourself.

**Comment by Biswa96** [comment] 2018-04-26 19:59
Are you sure that Kali team use that repository?  ¯\_(ツ)_/¯

**Comment by chwarr** [comment] 2018-04-26 21:57
@DarthSpock: I found a service with short name "LxssManager". Restarting that doesn't fix the access denied error.

```
4/26/2018 2:43:15 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [9] # get-service -name LxssManager

Status   Name               DisplayName
------   ----               -----------
Running  LxssManager        LxssManager


4/26/2018 2:43:20 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [10] # Stop-Service -Name LxssManager
4/26/2018 2:43:28 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [11] # Start-Service -Name LxssManager
4/26/2018 2:43:36 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [12] # ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
4/26/2018 2:43:41 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [13] # kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
4/26/2018 2:43:45 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [14] # get-service LxssManager

Status   Name               DisplayName
------   ----               -----------
Running  LxssManager        LxssManager
```

**Comment by chwarr** [comment] 2018-04-30 19:15
@DarthSpock: I found a service with short name "LxssManager". Restarting that doesn't fix the access denied error.

```
4/26/2018 2:43:15 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [9] # get-service -name LxssManager

Status   Name               DisplayName
------   ----               -----------
Running  LxssManager        LxssManager


4/26/2018 2:43:20 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [10] # Stop-Service -Name LxssManager
4/26/2018 2:43:28 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [11] # Start-Service -Name LxssManager
4/26/2018 2:43:36 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [12] # ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
4/26/2018 2:43:41 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [13] # kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
4/26/2018 2:43:45 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [14] # get-service LxssManager

Status   Name               DisplayName
------   ----               -----------
Running  LxssManager        LxssManager
```

**Comment by chwarr** [comment] 2018-04-30 22:31
Just got force upgraded to OS Build 17134.1 and I'm still seeing this behavior.

My outstanding offer to send logs or get you access to the machine in question still stands: I just need to know how you'd like me to submit them.

```
4/30/2018 3:26:42 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  jobs: 1  [1] # cmd /c ver

Microsoft Windows [Version 10.0.17134.1]
4/30/2018 3:28:16 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [2] # wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
4/30/2018 3:28:19 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [3] # ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
4/30/2018 3:28:22 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [4] # kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
4/30/2018 3:28:24 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [5] # restart-service -name LxssManager
4/30/2018 3:28:31 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [6] # wsl
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
4/30/2018 3:28:35 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [7] # ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
4/30/2018 3:28:39 PM :: chwarr@CHWARR-ZEN4 :: C:\src
  [8] # kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
```

**Comment by benhillis** [comment] 2018-04-30 22:33
Logs would be useful, here are the instructions:

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by chwarr** [comment] 2018-04-30 22:50
I e-mailed the logs to InsiderSupport@microsoft.com.

The e-mail contains:

1. a console session trace of the commands I ran,
1. the detailed .etl log files,
1. the string "4cb5ee761adf45b5a0cbd31cda4bd4b8" so that it can be correlated to this comment in this issue.

**Comment by benhillis** [comment] 2018-05-02 16:55
@chwarr - Thanks for providing the logs.  I took a look and it looks like something is blocking access to the lxcore driver.  I will follow up with you via email to see if we can diagnose this further.

**Comment by GuyGoldenberg** [comment] 2018-05-03 06:08
Turning off device guard, credentials guard and HyperV fixed this issue for me

**Comment by benhillis** [comment] 2018-05-03 14:34
@GuyGoldenberg - is it possible for you to narrow down which of those three components was causing the issue so I can follow up with them?

**Comment by TheGoddessInari** [comment] 2018-05-04 02:50
I've been consistently seeing this issue, and what I found on my system upgraded to RS4 was that turning off Driver Signature Enforcement via the advanced boot menu made everything work fine (no more permission denied), knowing that, is there anything of a remedy or workaround, at least for this case?

I've had the error consistently without hypervisor/device guard/etc enabled at all. I'd really rather not be forced into a reinstall.

**Comment by benhillis** [comment] 2018-05-04 19:29
@chwarr dropped by my office today and I was able to identify the issue and will be working on a fix to backport to 1803.

**Comment by pentatonicfunk** [comment] 2018-05-15 23:28
@TheGoddessInari any other workaround ? turning off `Driver Signature Enforcement` didnt help me

**Comment by benhillis** [comment] 2018-05-16 17:52
This should be resolved in 17672.  We are currently working with the servicing team to get this backported to 1803, bear with us!

**Comment by benhillis** [comment] 2018-05-16 18:00
The issue is with configurations that have user mode code integrity (UMCI) is enabled via a WDAC policy.

**Comment by richlilly2004** [comment] 2018-05-16 19:38
So I didn't have UMCI enabled, are we sure it's not VBS? Believe when i saw this (before I rebuilt w/ 1803) that I only had WDAG and Cred Guard enabled. No WDAC, but possibly could have been in audit mode.

**Comment by benhillis** [comment] 2018-05-16 20:03
@richlilly2004 - Are you sure you don't have UMCI enabled?

`powershell get-cipolicyinfo`


if the 0x10 bit is set, you have it enabled.

**Comment by TheGoddessInari** [comment] 2018-05-16 20:56
I never had a WDAC/Code Integrity policy created, but apparently 1709 made one for me back in September (no idea how). Finding the [WDAC Guide](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create), it told me I could disable that by moving C:\Windows\System32\CodeIntegrity\SIPolicy.p7b out of the way

This finally worked. Strange that disabling signature integrity checking got by that somehow, too. Either way, WSL works now. I'm now left wondering how UMCI got enabled in the first place.

I have used VBS at various times, but never with the user-mode policies/application control.

**Comment by snobu** [comment] 2018-05-22 07:53
I too hit this edge case, as @TheGoddessInari mentioned, moving `C:\Windows\System32\CodeIntegrity\SIPolicy.p7b` somewhere else on the disk and rebooting fixes it:

![image](https://user-images.githubusercontent.com/6472374/40349156-6192302c-5dae-11e8-9039-df1ea1c8617f.png)

**Comment by sunilmut** [comment] 2018-05-29 18:06
This should be fixed in Insider build [17677](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17677).

**Comment by di-mae** [comment] 2018-05-29 21:37
Do you know when/if this issue will be patched on 1803?

**Comment by richlilly2004** [comment] 2018-05-29 22:06
+1
________________________________

**Comment by BeErikk** [comment] 2018-06-07 19:29
Installing WSL with the server installation method on Windows 10.0.17134.81 (1803) in a non-system directory.
`PS L:\ubuntu> ./ubuntu1804.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 ┼tkomst nekad.`
The last is Windows-garbled Swedish for Access denied

running an elevated console resolves the issue

**Comment by Biswa96** [comment] 2018-06-08 20:45
This also happens in insider builds. The WslRegistwrDistribution() and the COM method both need elevated permission.

**Comment by rifuller** [comment] 2018-06-14 17:29
I'm also running into this issue.

Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...

**Been blocked on this for few months now.  Is there any work around?**  I understand that the fix is already in the newer builds but I need it in 1803. :)

[logs.zip](https://github.com/Microsoft/WSL/files/2103357/logs.zip)

**Comment by shoffmeister** [comment] 2018-06-14 18:51
One workaround mentioned above is https://github.com/Microsoft/WSL/issues/3020#issuecomment-389662966

Does that work?

**Comment by rifuller** [comment] 2018-06-14 19:05
That did work.  Seems I did do that in the past (I see the file I renamed last time) so it must get itself into a bad state again at some point.

**Comment by Biswa96** [comment] 2018-06-15 21:34
@sunilmut @benhillis This error also present in build 17134.81 and 17686 (haven't tested 17692). I've tested in a clean installed Win 17134.81 VM in VBox. When I launched Ubuntu from Start menu, it shows:

![ubuntu_1804](https://user-images.githubusercontent.com/31443074/41490322-242b6084-7111-11e8-8588-a1b4af2b176a.png)

The error may be in COM interface. The event log shows error with `Microsoft-Windows-DistributedCOM` and `Microsoft-Windows-AppModel-Runtime` services.  The following line confirms that: `"The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID"`. Also same error `0x80070005: Access Denied` shown in `WslRegisterDistribution()` function and `LxssUserSession::RegisterDistribution()` COM method.

As expected, if I extract the ubuntu.exe and install.tar.gz in a separate folder and run ubuntu.exe as administrator, it works well. Here are the event logs:

[Ubuntu_1804.zip](https://github.com/Microsoft/WSL/files/2107560/Ubuntu_1804.zip)

**Comment by voidsteed** [comment] 2018-06-21 20:22
i can confirm the workaround works. Thanks a lot!

**Comment by BeErikk** [comment] 2018-06-22 07:49
Windows 10.0.17134.81 (1803)
To clarify, I do not use insider builds and the Store installation method works for me. The server installation method does not work unless you run as an administrator. However, it is probably a non-supported option to use the server installation on Windows 10, but not so uncommon I think.

**Comment by Biswa96** [comment] 2018-06-22 08:19
@BeErikk Try this solution https://github.com/Microsoft/WSL/issues/3304#issuecomment-398489972

**Closed** 2018-10-08 21:55 UTC
Labels: fixedin1809

**Comment by agowa338** [comment] 2019-01-27 13:13
@therealkenc Can you reopen this issue? I'm hitting it within Fast Ring.
Winver: 1903 (118323.1000)
I've Hyper-v and Docker installed on that box, too.

**Comment by agowa338** [comment] 2019-01-27 14:09
Can confirm the issue with Hyper-V.
After upgrading to the latest windows version one needs to reinstall the Hyper-V feature or WSL is broken.

1. Uninstall Hyper-V feature
2. Reboot
3. Install Hyper-V feature
4. Reboot
5. WSL will work again.

**Comment by pkeir** [comment] 2019-02-19 13:36
I still have this problem, and alas now routinely use Cygwin again. I installed via the store, and running "powershell get-cipolicyinfo" gives me

Options HVCIOptions Version PolicyGuid
------- ----------- ------- ----------
      0           0       0 {0, 0, 0, 0...}

...which looks like I don't have UMCI on.

Perhaps a fresh install might work, but some advice on whether I can retrieve my files from the failed disk image would be useful. This would give some assurance in case this were to happen again in future.

**Comment by zoechi** [comment] 2019-04-27 11:34
I still have this with Debian from Store.

Windows 10 Pro
10.0.17763

C:\Windows\System32\CodeIntegrity\SIPolicy.p7b does not exist

```
PS C:\windows\system32> get-cipolicyinfo
get-cipolicyinfo : Device Guard ist in dieser Edition von Windows nicht verfügbar.
In Zeile:1 Zeichen:1
+ get-cipolicyinfo
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CIPolicyInfo], NotSupportedException
    + FullyQualifiedErrorId : System.NotSupportedException,Microsoft.SecureBoot.UserConfig.GetCIPolicyInfoCommand
```
Reinstalling Hyper-V didn't help.

**Comment by tomshaffner** [comment] 2019-05-09 11:41
A side note for others who encounter this problem; one of the above comments triggered me to the fact that I was trying to install this in a system folder. When I moved it to a user folder it worked fine. For anyone who's trying this that might be an easier solution to test than some of the above.

**Comment by DDvO** [comment] 2019-05-28 10:09
I just figured out that the following solved the problem for me:

Invoke the `bash` command from a Windows shell with admin rights.

Since then I can use WSL / `bash` again also with normal user rights.

**Comment by nataelj** [comment] 2019-08-27 10:48
Bizarrely I had this problem again on a different computer with a more recent Windows build and my own solution above didn't work. The new solution was to give my user account full read/write rights to the folder and then, bizarrely, to run bash in a non-administrative window. Apparently my admin rights weren't sufficient for this but once I'd used that admin account to give my non-admin account rights it could then run fine.

**Comment by zipswich** [comment] 2019-09-15 16:36
I had the same problem with Ubuntu1804. 
Per the tip of @tomshaffner, I copied directory 
C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc  
into 
C:\Applications
and run  ubuntu1804.exe from 
C:\Applications\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc
The problem is gone. It has been working fine with all kinds of commands.

**Comment by mrboli** [comment] 2019-09-16 16:19
I'm getting this with 1903 and 1803 with ubuntu 18.04.

I don't have the command `get-cipolicyinfo` and I don't have any security profiles set.

**Comment by benstaniford** [comment] 2019-11-13 20:51
I just started getting this today after installing some updates to my Windows 10 1803 (Build 17134) machine.   Initially ubuntu just stopped working and reported 80070040 and then when I tried to reinstall by re-running Ubuntu under an elevated command prompt.  I got 8007005.  I seem to be stuck now.

**Comment by agowa338** [comment] 2019-11-23 18:02
@benstaniford Can you please try this: https://github.com/microsoft/WSL/issues/3020#issuecomment-457920974

**Comment by benstaniford** [comment] 2019-11-26 15:59
@agowa338 Hmm, that doesn't seem to have worked.  I didn't have Hyper-V enabled at all previously so I guess that's become a pre-req quite recently?  However, enabling it, rebooting, and re-running the ubuntu18-4.exe process still shows an access denied HRESULT.  

Oddly I can simply run bash.exe from a standard command prompt to gain access to WSL but the console that comes with Ubuntu no longer works.  Running wsl or wslbridge also no longer work though and VS Code can no longer show the WSL terminal.

**Comment by lagosj** [comment] 2020-03-26 18:08
> I had the same problem with Ubuntu1804.
> Per the tip of @tomshaffner, I copied directory
> 
> > C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc
> 
> into
> 
> > C:\Applications
> 
> and run ubuntu1804.exe from
> 
> > C:\Applications\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2018.817.0_x64__79rhkp1fndgsc
> 
> The problem is gone. It has been working fine with all kinds of commands.

This right here worked all miracles. THIS GOES TO ALL OF YOU WITH LATEST WINDOWS 10.

**Comment by stdedos** [comment] 2020-07-19 09:14
Definitely _not_ fixedin1809.
As per the comment above (https://github.com/microsoft/WSL/issues/3020#issuecomment-604589190 aka https://github.com/microsoft/WSL/issues/3020#issuecomment-490868622), just _don't_ have spaces in your path.

**Comment by airtonix** [comment] 2020-10-08 01:02
:( this is back again after Windows Insider build 20231.re_prelease.201002-1444

Can't install Alpine Linux.:

```console
~ $ alpine
Temporary directory: C:\Users\zenobius\AppData\Local\Temp\wsl_Alpine_setup
Downloading   : http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-minirootfs-3.9.0-x86_64.tar.gz
To local file : install.tar.gz
The current working directory is: C:\Users\zenobius\AppData\Local\Temp\wsl_Alpine_setup
File successfully deleted
Mime type available
Begin download
Cache filename available
100% [====================]
End download
Downloaded OK
Hash of file install.tar.gz is: f82efed1a80c9af86c38bed10f3541c5588453b97684d767a5a3b0f3fa0e3f09

Verifying Hash: OK
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
WslRegisterDistribution failed
Error: 0x80070005 Access is denied.

Press any key to continue...
```


### Info

```console
~ $ wsl -l -v
  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  docker-desktop         Running         2
```

```
Device name	pennyroyal
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
Graphics cards	Intel(R) HD Graphics 630 
NVIDIA GeForce GTX 1050 
Intel(R) HD Graphics 630
Installed RAM	32.0 GB (31.9 GB usable)
Device ID	94BE758E-135E-44FB-BEE1-E22CD026D42E
Product ID	00330-80000-00000-AA080
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```


```console
~ $ npx envinfo
npx: installed 1 in 1.852s

  System:
    OS: Windows 10 10.0.20231
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 20.79 GB / 31.86 GB
  Binaries:
    Node: 8.9.0 - C:\Program Files (x86)\Nodist\bin\node.EXE
    Yarn: 1.3.2 - C:\Program Files (x86)\Nodist\bin\yarn.CMD
    npm: 6.0.1 - C:\Program Files (x86)\Nodist\bin\npm.EXE
  Managers:
    pip2: 19.0.3 - C:\Python27\Scripts\pip2.EXE
    pip3: 20.2 - C:\Python38\Scripts\pip3.EXE
  Utilities:
    Git: 2.27.0.
  Virtualization:
    Docker: 19.03.13 - C:\ProgramData\DockerDesktop\version-bin\docker.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
  IDEs:
    VSCode: 1.49.3 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Python: 3.8.1
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (44.20231.1000.0), Chromium (Login Succeeded), ChromiumDev (Login Succeeded)
    Internet Explorer: 11.0.20231.1000
```

submitted feedback, but the feedback app decided to not give me a link...

T_T

**Comment by rodragon737** [comment] 2022-09-20 18:17
Windows Insider broke permisions and no have rollback. [ @InsiderSupport@microsoft.com]


_I_nstalling, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Acceso denegado._

Press any key to continue..._

**Comment by PaulA-V** [comment] 2023-11-01 02:10
> A side note for others who encounter this problem; one of the above comments triggered me to the fact that I was trying to install this in a system folder. When I moved it to a user folder it worked fine. For anyone who's trying this that might be an easier solution to test than some of the above.

This worked for me but make sure you copy it to a folder on the system drive per the following MS documentation.

https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#installation-issues


Regards,

Paul

**Comment by agowa** [comment] 2023-11-16 14:48
People in here https://github.com/microsoft/WSL/issues/6744 reported that this issue only exists with the store version and vanishes when WSL is installed without the Store and `wsl.exe --update` is ran.

The windows store probably causes this permission issue.
