### ISSUE TITLE
Qt5.10 corelib cannot link

### ISSUE THREAD

**Issue by yuk7** [Microsoft/WSL#2820] opened 2018-01-09 06:36 UTC
Your Windows build number: Microsoft Windows [Version 10.0.17063.1000]

* What you're doing and what's happening: 
I'm tried to use Qt5.10 base corelib(llibQt5Core.so.5.10.0) but cannot link in all application using qt5(ex: texmaker,qgit and others)
(Qt 5.9 and earlier versions is working correctly)

1. Install Qt5.10 base libraries.
2. Run Application using Qt5.
```
$ texmaker
texmaker: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```
```
$strace -f texmaker
~
stat("/usr/lib/x86_64", 0x7fffc1950e80) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7fffc1950e80) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200]\t\0\0\0\0\0"..., 832) = 832
lseek(3, 5194016, SEEK_SET)             = 5194016
read(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\21\0\0\0\0\0\0\0", 32) = 32
close(3)                                = 0
stat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
~
```
```
$ls -la /usr/lib/ | grep libQt5Core
-rw-r--r-- 1 root root     1114 Dec  7 16:30 libQt5Core.prl
lrwxrwxrwx 1 root root       20 Dec  7 16:30 libQt5Core.so -> libQt5Core.so.5.10.0
lrwxrwxrwx 1 root root       20 Dec  7 16:30 libQt5Core.so.5 -> libQt5Core.so.5.10.0
lrwxrwxrwx 1 root root       20 Dec  7 16:30 libQt5Core.so.5.10 -> libQt5Core.so.5.10.0
-rwxr-xr-x 1 root root  5250712 Dec  7 16:30 libQt5Core.so.5.10.0
```

[log gist](https://gist.github.com/yuk7/43d1c9771adce25d5ba9267744380c65)

Same binary package is working on Official Linux kernel.

**Comment by therealkenc** [comment] 2018-01-09 12:18
You might want to post baby steps to get to your `texmaker` fail since Qt 5.10 isn't what ships with Xenial. Normally Qt5 lives in `/usr/lib/x86_64-linux-gnu`, not `/usr/lib`.

It is interesting that there's no `rename2` `ENOSYS` making it into the strace output. No rename2 _at all_. Missing `ENOSYS` in an strace is a known issue, but I thought that was addressed in 17063. Or at least that's how I read the [release notes](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17063).

I expected to be able to find the fail line in Qt pretty quick, but I am having trouble pinning the blame on `rename2` proper. One thing that tilts my head to the side is the code [_looks_](https://github.com/qt/qtbase/blob/bbcd4533889b3f3ae45917d638e06bedc9e5c536/src/corelib/io/qfilesystemengine_unix.cpp#L1288) like it ought to fall back:
```
    // If we're using syscall(), check for ENOSYS;
    // if renameat2 came from libc, we don't accept ENOSYS.
    // We can also get EINVAL for some non-local filesystems.
    if ((QT_CONFIG(renameat2) || errno != ENOSYS) && errno != EINVAL) {
        error = QSystemError(errno, QSystemError::StandardLibraryError);
        return false;
    }
   ..... at this point it tries to use hard links instead of rename2, I think.
```
That's the _only_ place `rename2()` is called. I could be reading the `if` statement wrong. Probably am. But even if I am wrong and that `QSystemError` above fires, I'd expect to get a glaring "`Function not implemented`” out the command line, not "`No such file or directory`". In the strace output you pasted there are `ENOENT`s, but that last `openat()` _succeeds_ (with fd 3) in the end. Not helpful mind. Just odd. Qt 5.4 is fine so `rename2()` is still as good a guess as any.

**Comment by DDoSolitary** [comment] 2018-02-07 02:15
Same here. It can be reproduced on Arch Linux on WSL. Simply install qt5-base (`pacman -S qt5-base`) and run an application depends on Qt.

For example, running `pinentry-qt`:

```
$pinentry-qt       
pinentry-qt: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

But `libQt5Core.so.5` does exists:

```
$stat /usr/lib/libQt5Core.so.5
  File: /usr/lib/libQt5Core.so.5 -> libQt5Core.so.5.10.0
  Size: 20        	Blocks: 0          IO Block: 512    symbolic link
Device: 2h/2d	Inode: 1970324837097831  Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-02-07 10:14:20.000000000 +0800
Modify: 2018-02-04 03:35:59.000000000 +0800
Change: 2018-02-07 10:14:20.935738700 +0800
 Birth: -

$stat /usr/lib/libQt5Core.so.5.10.0
  File: /usr/lib/libQt5Core.so.5.10.0
  Size: 5251976   	Blocks: 10624      IO Block: 512    regular file
Device: 2h/2d	Inode: 1970324837097730  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-02-07 10:14:20.000000000 +0800
Modify: 2018-02-04 03:36:16.000000000 +0800
Change: 2018-02-07 10:14:20.353363700 +0800
 Birth: -
```

**Comment by DDoSolitary** [comment] 2018-02-07 02:21
strace output

```
$strace pinentry-qt                  
execve("/usr/sbin/pinentry-qt", ["pinentry-qt"], 0x7fffcccaf410 /* 33 vars */) = 0
brk(NULL)                               = 0x7fffdd98d000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=79074, ...}) = 0
mmap(NULL, 79074, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fea7b7e4000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libsecret-1.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\344\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=333280, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fea7b7e0000
mmap(NULL, 2428992, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fea7b1a0000
mprotect(0x7fea7b1ee000, 2093056, PROT_NONE) = 0
mmap(0x7fea7b3ed000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4d000) = 0x7fea7b3ed000
mmap(0x7fea7b3f1000, 64, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fea7b3f1000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libglib-2.0.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\241\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1129568, ...}) = 0
mmap(NULL, 3227752, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fea7ae80000
mprotect(0x7fea7af93000, 2093056, PROT_NONE) = 0
mmap(0x7fea7b192000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x112000) = 0x7fea7b192000
mmap(0x7fea7b194000, 104, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fea7b194000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libassuan.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\3601\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=75688, ...}) = 0
mmap(NULL, 2171232, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fea7ac60000
mprotect(0x7fea7ac71000, 2097152, PROT_NONE) = 0
mmap(0x7fea7ae71000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x11000) = 0x7fea7ae71000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libgpg-error.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@.\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=84680, ...}) = 0
mmap(NULL, 2179816, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fea7aa40000
mprotect(0x7fea7aa54000, 2093056, PROT_NONE) = 0
mmap(0x7fea7ac53000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7fea7ac53000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libQt5Widgets.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\243\24\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=6655152, ...}) = 0
mmap(NULL, 8750856, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fea7a1e0000
mprotect(0x7fea7a807000, 2093056, PROT_NONE) = 0
mmap(0x7fea7aa06000, 208896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x626000) = 0x7fea7aa06000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libQt5Gui.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\330\f\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=6007192, ...}) = 0
mmap(NULL, 8122056, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fea79a20000
mprotect(0x7fea79fc5000, 2097152, PROT_NONE) = 0
mmap(0x7fea7a1c5000, 86016, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5a5000) = 0x7fea7a1c5000
mmap(0x7fea7a1da000, 20168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fea7a1da000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/tls/x86_64/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64/x86_64", 0x7fffe4996340) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64", 0x7fffe4996340) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls/x86_64", 0x7fffe4996340) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/tls/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/tls", 0x7fffe4996340)    = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64/x86_64", 0x7fffe4996340) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7fffe4996340) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7fffe4996340) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200]\t\0\0\0\0\0"..., 832) = 832
lseek(3, 5195652, SEEK_SET)             = 5195652
read(3, "\4\0\0\0\20\0\0\0\1\0\0\0GNU\0\0\0\0\0\3\0\0\0\21\0\0\0\0\0\0\0", 32) = 32
close(3)                                = 0
stat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=512, ...}) = 0
writev(2, [{iov_base="pinentry-qt", iov_len=11}, {iov_base=": ", iov_len=2}, {iov_base="error while loading shared libra"..., iov_len=36}, {iov_base=": ", iov_len=2}, {iov_base="libQt5Core.so.5", iov_len=15}, {iov_base=": ", iov_len=2}, {iov_base="cannot open shared object file", iov_len=30}, {iov_base=": ", iov_len=2}, {iov_base="No such file or directory", iov_len=25}, {iov_base="\n", iov_len=1}], 10pinentry-qt: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
) = 126
exit_group(127)                         = ?
+++ exited with 127 +++
```

**Comment by therealkenc** [comment] 2018-02-07 08:33
Your `openat()` succeeded as well, just like the OP.
```
openat(AT_FDCWD, "/usr/lib/libQt5Core.so.5", O_RDONLY|O_CLOEXEC) = 3
```
What is required here is a set of repro steps from a Xenial commandline.

**Comment by Gelmo** [comment] 2018-02-25 20:13
I'm having the same issue @yuk7 and I'm using your Arch setup, as well. Getting the issue when compiling QT apps.

**Comment by therealkenc** [comment] 2018-04-03 17:07
Long enough on need-repro pile. **If** the problem can be pinned on `rename2()` (not clear either way) then a test case in a new issue would be most welcome.

**Closed by therealkenc** 2018-04-03 17:07 UTC
Labels: need-repro
