### ISSUE TITLE
Can't start Ubuntu - Windows cannot access the specified device, path, or file.

### ISSUE THREAD

**Issue by MattHorvay** [microsoft/WSL#3612] opened 2018-10-12 21:38 UTC
Windows build number:  Version 10.0.17134.345 (Windows 10 Pro, Version 1803, x64)

When I try to launch Ubuntu, I get an error dialog that "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item." The title bar for the window is "C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2018.817..."

Every time I try to start it two AppModel-Runtime errors are generated in the Event Viewer:
Event 216: 0x80070005: Cannot create the Desktop AppX container for package CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc because an error was encountered configuring the runtime.
Event 208: 0x80070005: Cannot create the process for package CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc because an error was encountered while configuring runtime. [LaunchProcess]

I ran Sysinternals Process Monitor filtering for Result is Access Denied.
Everytime I try to start Ubuntu there is one Access Denied:
Process Name: svchost.exe
Operation: CreateFile
Path: \\[removed]-DC.[removed].local\users$\matthew.horvay\
Result: ACCESS DENIED
Desired Access:	Read Data/List Directory, Synchronize
Disposition:	Open
Options:	Directory, Synchronous IO Non-Alert
Attributes:	n/a
ShareMode:	Read, Write, Delete
AllocationSize:	n/a
User: NT AUTHORITY\SYSTEM

The computer is domain joined and is using folder redirection.
I checked the security properties for \\[removed]-DC.[removed].local\users$\matthew.horvay\
SYSTEM, [domain]\Administrators, and my domain account all have full control.

If this is something I can fix, I'd appreciate any assistance. Otherwise I'd like to report a bug.

Thank you.

**Comment by MattHorvay** [comment] 2018-10-18 15:34
I got it to work by manually downloading and following the instructions to install on Windows Server.
[https://docs.microsoft.com/en-us/windows/wsl/install-on-server](url)

I downloaded [https://aka.ms/wsl-ubuntu-1804](url), renamed it to a .zip, extracted it to C:\Users\matthew.horvay\Ubuntu and ubuntu1804.exe ran fine, finally.

It still doesn't explain why it won't run from the store or how to fix that problem, but at least it runs now.

**Comment by Margen67** [comment] 2020-04-17 17:41
Duplicate of #2323?

**Comment by TerrorFactor** [comment] 2020-04-23 15:37
Same issue here. 
- Installed a fresh 1909 pro (iso from microsoft site)
- downloaded the ubuntu and kali appx packages (no direct internet access on this machine)
- used the add-appxpackage command to install the package (with the initial admin user, but without elevated rights), no errors
- tried to run ubuntu, using the shortcut in the start menu.

Same issue with Kali. Changes to my clean Windows before installing the packages:
- add features wsl, openssh server, openssh client
- enable remote desktop
- configure proxy settings

The server install method mentioned (https://github.com/microsoft/WSL/issues/3612#issuecomment-431056309) does work however.

**Closed** 2024-02-01 12:53 UTC
Labels: failure-to-launch
