### ISSUE TITLE
WSL2 ping issue when NIC has mutiple IP addresses - reopened

### ISSUE THREAD

**Issue by escherstair** [microsoft/WSL#11751] opened 2024-07-04 13:20 UTC
### Windows Version

Microsoft Windows [Versione 10.0.19045.4529]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu-22.04

### Repro Steps

1. Assign two IP addresses (on different subnets) to a Network Interface Card (NIC)
2. Using that NIC, connect an ethernet cable to a device which has an IP address on the network of the second IP address of the NIC (not the first one)
3. ping the device from Windows, and check that it answers
4. ping the device from WSL2

### Expected Behavior

The device should answer to the ping.

### Actual Behavior

No answer from the ping.
If the device has an IP address on the network of the first IP of the NIC, the ping is successful.

### Diagnostic Logs

This is a re-file of issue #9803 that has been closed for no activity

**Comment by escherstair** [comment] 2024-07-04 14:50
[WslLogs-2024-07-04_16-35-21.zip](https://github.com/user-attachments/files/16100382/WslLogs-2024-07-04_16-35-21.zip)

**Comment by OneBlue** [comment] 2024-07-09 21:23
@escherstair: In step 1, you're saying that you have a Windows NIC that has two Ip addresses on different subnets ? 

If so, it makes sense that WSL fails to ping the secondary IP address, given that there's most likely not routing table entry that would allow WSL to reach that NIC via that ip address. 

Feel free to reopen if I misunderstood the issue and add more info. In the meantime I'll close this as by design.

**Closed by OneBlue** 2024-07-09 21:23 UTC
Labels: network
