### ISSUE TITLE
17123, strace hang w/ CPU?

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/WSL#3036] opened 2018-03-18 15:43 UTC
I'm not sure what's up, but suddenly I'm running into an odd issue with WSL under 17123, a lot of processes (but no specific pattern as of yet) simply hang at startup.... including `strace`.

I can run `bash.exe` just fine. `ifconfig` runs fine, but `strace ifconfig` just "hangs" indefinitely - but I say that quotes because it's eating CPU doing _something_ - just not clear what (eats a single core at 100%). I can't kill them at that point, not via task manager or via `kill -9`.

I tried to capture a full memory dump but it was transferring at 5.1MB/s over USB 3.0 and needed over 2 hours (32GB machine) so I had to abort. I'll probably let it run overnight. I couldn't find anything helpful in `kd` but I didn't look too hard (and it's just debugging so slow).

(Restarting the subsystem service ultimately hangs on attempting to stop the service.)

**Comment by fubar-coder** [comment] 2018-03-19 23:29
The same happens with - for example - `lsof`.

**Comment by mqudsi** [comment] 2018-03-20 02:55
@benhillis per your comment on #3039 I'm thinking you don't need the dump?

**Comment by benhillis** [comment] 2018-03-20 03:08
@mqudsi - We have a local repro so no dump needed. Thanks for the offer.

**Comment by mqudsi** [comment] 2018-03-20 03:31
Cheers.

**Comment by benhillis** [comment] 2018-03-20 15:50
Marking as a duplicate of #3039.

**Closed by benhillis** 2018-03-20 15:50 UTC
