### ISSUE TITLE
WSL broke after Windows update

### ISSUE THREAD

**Issue by refinedkontrol** [microsoft/WSL#10831] opened 2023-11-27 16:28 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.2715]

### WSL Version

Cannot determine N/A

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Cannot determine N/A

### Distro Version

Cannot determine N/A

### Other Software

```
PS> code --version
1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
x64
```

### Repro Steps

After the following Windows updates, my WSL installation seems to have disappeared. When I run the Ubuntu app, I get this:

(It's repetitive because I followed the prompts to continue/restart.)

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007019e
Error: 0x8007019e The Windows Subsystem for Linux has not been enabled.

Press any key to continue...

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007019e
Error: 0x8007019e The Windows Subsystem for Linux has not been enabled.

Press any key to continue...

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

I cannot access WSL via VSCode like normal either.

I tried [this fix from StackOverflow](https://superuser.com/a/1614905). I will copy the fix here for the record:

> - Run (`Win+R`) `optionalfeatures.exe`
> - untick Windows Subsystem for Linux and click OK Allow the system to restart if prompted
> - Run (`Win+R`) `optionalfeatures.exe` again
> - tick Windows Subsystem for Linux and click OK
>
> This will effectively uninstall the WSL and install it again.
> 
> The existing WSL installations seem not affected by this procedure in any way (they look exactly like before).

It looks like [this commenter](https://stackoverflow.com/questions/77501847/wsl-responds-on-every-command-wsl-is-finishing-upgrading-update-failed-exit#comment136660365_77501847) on a different StackOverflow question had the same issue.

### Expected Behavior

I expected to be able to open the Ubuntu app or the Terminal app and access my WSL command line like normal.

### Actual Behavior

Even though I'm running Windows 11, VSCode reports:

> Windows Subsystem for Linux not detected. The WSL extension requires Windows 10 with the Windows Subsystem for Linux feature installed.
>
> Source: WSL (Extension)

(For some reason it says Windows 10.)

See additional info under diagnostic logs section...

### Diagnostic Logs

I had to answer N/A to a bunch of questions because I couldn't get WSL to give me the information.

Some commands I tried running:

```
PS> cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.2715]
PS> wsl.exe --version
WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT
PS> wsl -l -v
WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT
PS> wsl.exe --status
WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT
PS> code --version
1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
x64
PS> ver&wsl --list --all -v

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      Job1            BackgroundJob   Running       True            localhost            ver
WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT

PS> wsl.exe --help
WSL is finishing an upgrade...
Update failed (exit code: 1603).
Error code: Wsl/CallMsi/E_ABORT
```

Windows updates that have been installed since the last time WSL worked for me:

![Windows updates screenshot](https://github.com/microsoft/WSL/assets/138532440/9d086c02-47a2-4c55-9516-15a3e95c6afa)

**Comment by refinedkontrol** [comment] 2023-11-27 16:44
Additional info:

![Ubuntu app info screenshot](https://github.com/microsoft/WSL/assets/138532440/1e61c2fb-937b-4ae3-94b3-1ff3145fbb72)

Ubuntu (Windows app) version: `2204.2.33.0`

**Comment by leone93** [comment] 2023-12-05 08:34
Same problem to me after that updates. Every time I tried to open later on I have your same error and after some times a blue screen of death appear. Trying to resinstall wsl didn't work at all.

**Comment by johrstrom** [comment] 2023-12-05 15:18
I too have the same issue, using WSL 2.0.9 (I asssume that verion, I can't issue any comamnds successfully, but the binary is in the `MicrosoftCorporationII.WindowsSubsystemForLinux_2.0.9.0_x64__8wekyb3d8bbwe` folder).

I really only tried to bounce my system as a workaround. I'm a bit hesitant to really mutate my system further, so I haven't reinstalled, edited registry keys or similar system mutations (I'm afraid to lose my data, though if it's inaccessible I suppose what's the worry?).

**Comment by OneBlue** [comment] 2023-12-05 20:17
> I really only tried to bounce my system as a workaround. I'm a bit hesitant to really mutate my system further, so I haven't reinstalled, edited registry keys or similar system mutations (I'm afraid to lose my data, though if it's inaccessible I suppose what's the worry?).

I would recommend trying to install the [latest version of WSL](https://github.com/microsoft/WSL/releases/tag/2.0.14) before doing anything like that

**Comment by johrstrom** [comment] 2023-12-05 20:18
> I would recommend trying to install the [latest version of WSL](https://github.com/microsoft/WSL/releases/tag/2.0.14) before doing anything like that

Thanks, I'll try this and let this thread know. (I thought 2.0.9 was the latest and didn't dig any further on it).

**Comment by johrstrom** [comment] 2023-12-06 14:32
>> I would recommend trying to install the [latest version of WSL](https://github.com/microsoft/WSL/releases/tag/2.0.14) before doing anything like that

> Thanks, I'll try this and let this thread know. (I thought 2.0.9 was the latest and didn't dig any further on it).

I cannot install that msi on this machine (a work machine) apparently. I have admin privileges, but alas get the error, even if I try through an administrative powershell.

![image](https://github.com/microsoft/WSL/assets/4874123/9e2f5bb1-9c35-4579-a92c-2a907f32f37f)

**Comment by OneBlue** [comment] 2023-12-07 00:31
> I cannot install that msi on this machine (a work machine) apparently. I have admin privileges, but alas get the error, even if I try through an administrative powershell.

Interesting. Could you try to run (elevated):

```
msiexec /i path/to/msi /L*V C:\logs.txt
```

And share C:\logs.txt ?

**Comment by johrstrom** [comment] 2023-12-07 17:24
I ran it and got the logs, but as it's a work machine I'm not entirely sure if I can share it here in it's entirety (I'm asking around for the same).

Is there something specific I can look for/`grep` to extract?

**Comment by OneBlue** [comment] 2023-12-07 19:28
> Is there something specific I can look for/`grep` to extract?

Not easily. The only thing that this log file should contain would be user names and file paths but to root cause I'd need to see the entire file. 

You can always redact things that you don't want to share because posting the log file if you want.

**Comment by koemaeda** [comment] 2023-12-08 16:29
I am also having this same issue, and installing the latest version (2.0.14) did not help.

When running the MSI with `msiexec /i path/to/msi /L*V`, it fails at the end:
[msi installation logs.txt](https://github.com/microsoft/WSL/files/13618777/msi.installation.logs.txt)

When running the MSI with `msiexec /a path/to/msi /L*V` the installation completes without errors:
[msi elevated installation logs.txt](https://github.com/microsoft/WSL/files/13618778/msi.elevated.installation.logs.txt)

**Comment by OneBlue** [comment] 2023-12-08 19:18
> I have the same problem, and I don't mind sharing the file. [logs.txt](https://github.com/microsoft/WSL/files/13615084/logs.txt)

Thank you @xiaoxi-david. Just to confirm, you ran this command as administrator right ? If so, can you please share the output of (elevated powershell): 

```
Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers
```

And the content of the registry key: `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WSLService` ?

**Comment by xiaoxi-david** [comment] 2023-12-08 20:54
> Thank you @xiaoxi-david. Just to confirm, you ran this command as administrator right ? 

Yes
> If so, can you please share the output of (elevated powershell):
> 
> ```
> Get-AppxPackage MicrosoftCorporationII.WindowsSubsystemforLinux -AllUsers
> ```

![image](https://github.com/microsoft/WSL/assets/24303680/cd0a3cd0-3fed-4f4e-8e3b-a2867138455d)

> And the content of the registry key: `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WSLService` ?

![image](https://github.com/microsoft/WSL/assets/24303680/0ba5663f-bc46-4bef-8738-f112b55256f0)

**Comment by OneBlue** [comment] 2023-12-08 21:56
Thank you @xiaoxi-david. Looks like you somehow have an older wslservice left behind. Can you try to run (elevated cmd):

```
sc.exe delete wslservice
``` 

And see if that solves the issue ?

**Comment by OneBlue** [comment] 2023-12-13 18:55
> > Can you try to run (elevated cmd):
> > ```
> > sc.exe delete wslservice
> > ```

Ah that's too bad. This might be something that we'll need to do as part of the WSL 2.0 installation logic. I'll update this thread when I'll have more info on the subject;

**Comment by benhillis** [comment] 2023-12-21 01:19
Fixed with https://github.com/microsoft/WSL/releases/tag/2.0.15

**Closed by benhillis** 2023-12-21 01:19 UTC

**Comment by benhillis** [comment] 2024-01-08 21:53
Fixed with https://github.com/microsoft/WSL/releases/tag/2.1.0

**Comment by Reperion** [comment] 2024-12-15 15:51
Mmm.. after upgrading to W24H2 after first reboot and clicking WSL, it installed something or so..
Then VS code lost connection to my project folder on WSL.
Started WSL, thank the lord , it just boots and shows my home folder, project folder still there.

Disabled the WSL extension in VS CODE, restart VS Code, and after some clicking or opening recent project, it's back.

THe only issue left is that sometimes the Linux/WSL drive icon in file explorer is gone, opening a project on WSL via VS code makes it appear again. 97% back.. I am not touching it anymore 🗡

**Comment by foremtehan** [comment] 2025-03-14 06:10
This is what happened after a mandatary update:

```
Failed to attach disk 'C:\Program Files\WSL\system.vhd' to WSL2: The system cannot find the file specified.
Error code: Wsl/Service/CreateInstance/CreateVm/MountVhd/HCS/ERROR_FILE_NOT_FOUND
Press any key to continue...
```
