### ISSUE TITLE
WSL Startup/Networking Failure - Error Code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff

### ISSUE THREAD

**Issue by brianjlacy** [microsoft/WSL#11334] opened 2024-03-21 18:49 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Ubuntu

### Repro Steps

```
> wsl
Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\...\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
```

- WSL 2 was working for me prior to the 2024-03 Cumulative Update for Windows 11 Version 23H2 (KB5035853) update.
- Virtual Machine Platform is already installed.
- Windows Hypervisor Platform was NOT checked/installed; I tried installing and rebooting but the problem persists.
- I tried adding a .wslconfig file as recommended by [L-ingqin12](https://github.com/L-ingqin12) and others; problem persists.
- I complete uninstalled VMP, WHP, and WSL itself, rebooted, then re-installed them, updated WSL, and rebooted. The problem persists.

```
> wsl --version

WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296

> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
```

### Expected Behavior

Ubuntu launches successfully (with functional NAT network support).

### Actual Behavior

WSL Ubuntu fails to launch:
```
> wsl
Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\...\.wslconfig
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/HNS/0xffffffff
```

**Comment by brianjlacy** [comment] 2024-03-21 18:52
@keith-horton  Looks like you're one of the key people working on this?

I attempted to attach the WslNetworkingLogs zip file generated by the "collect-networking-logs.ps1" script. GitHub won't allow this; the file is 52 MB (limit is 25 MB). What files if any can I remove from the archive? Is there another way to send you the logs?

**Comment by OneBlue** [comment] 2024-03-21 20:10
> I attempted to attach the WslNetworkingLogs zip file generated by the "collect-networking-logs.ps1" script. GitHub won't allow this; the file is 52 MB (limit is 25 MB). What files if any can I remove from the archive? Is there another way to send you the logs?

You can use google drive / onedrive to upload logs if the file is too big.

/logs

**Comment by keith-horton** [comment] 2024-03-21 21:12
@brianjlacy , or you can email them to wsl-gh-logs@microsoft.com

**Comment by brianjlacy** [comment] 2024-03-22 23:49
> @brianjlacy , or you can email them to [wsl-gh-logs@microsoft.com](mailto:wsl-gh-logs@microsoft.com)

I've emailed the Google Drive link.

**Comment by keith-horton** [comment] 2024-03-26 02:19
Thank you for the trace. This is very bizarre - SharedAccess is failing to start the DNS proxy due to failing to bind to 0.0.0.0:53. Can you see if you have something else already listening on port 53?

If you run "Get-NetUDPEndpoint", that might show you.

**Comment by brianjlacy** [comment] 2024-04-16 00:12
How do I enable DNS Tunneling?

This is causing me tremendous stress right now as I'm unable to use Docker Desktop. I was able to work around this for a couple of weeks, but now I'm to a point where I absolutely have to get Docker Desktop and WSL working.

**Comment by brianjlacy** [comment] 2024-04-16 00:22
**Update:**
Running `Get-NetUDPEndpoint` showed that something was indeed using port 53 -- a little utility I've used occasionally the years that acts as a DNS proxy for greater control over DNS on my local PC.

Removed it, and now WSL is working again.

**Comment by CatalinFetoiu** [comment] 2024-07-26 22:35
closing since the issue is resolved

**Closed by CatalinFetoiu** 2024-07-26 22:35 UTC
Labels: network

**Comment by CodeShane** [comment] 2024-08-04 05:10
> Thank you for the trace. SharedAccess is failing to start the DNS proxy due to failing to bind to 0.0.0.0:53. Can you see if you have something else already listening on port 53?

Thank you! Solved an WSL2/Docker issue for me as well

**Comment by nguyenminhtho911** [comment] 2024-10-03 03:58
Try it:
1. open cmd run as admin  `netstat -aon | findstr 53`
2. kill the process: `taskkill /f /pid [PID]`
3. reopen Ubuntu

**Comment by Ninjaphil24** [comment] 2024-11-08 07:36
Check to see: cat /etc/resolv.conf

If it doesn't exist try: sudo nano /etc/wsl.conf

Change contents from false to true: [network] generateResolvConf = true

exit wsl

wsl --shutdown

Reenter wsl

Check again: cat /etc/resolv.conf

ping google.com

& Bob's your uncle.
