### ISSUE TITLE
No access from Subsystem for Linux 2 distro to Windows file system

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/WSL#5612] opened 2020-07-19 08:19 UTC
# Environment
Microsoft Windows [Version 10.0.20170.1000]
WSL Kerner version: Linux version 4.19.121-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Fri Jun 19 21:06:10 UTC 2020
WSL Distro - ALL - version 2
wsl.conf:
[automount]
enabled = true
root = /windir/
options = "metadata,umask=22,fmask=11"
mountFsTab = false

C:\Windows\System32>wsl -d Ubuntu-20.04 -u root lsb_release -r
Release:        20.04

/etc/hosts:
127.0.0.1       localhost
127.0.1.1       MSI.localdomain MSI
﻿
172.19.160.1    host.wsl
192.168.1.168   host.docker.internal
192.168.1.168   gateway.docker.internal
127.0.0.1       kubernetes.docker.internal
...
CentOS8
OpenSuse
Docker-desktop
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

1. config wsl.conf or leave it unattended
2. Open File Explorer 
Select either Linux subfolder or \\wsl$ subfolder
3. navigate to /mnt/c, try to open
4. run wsl -d distro-name> -u root
5. cd /mnt/c/Users ...
6. cat any text file - success

No logs created by logman although all logman.exe create trace were executed without error messages.

#  Expected behavior

1. wsl.conf is respected
2. /etc/hosts is respected
3. Windows FS is accessible from any Linux distro

Additionally - run /init verbose mode

# Actual behavior
Access from WSL2 distros to Windows folders is broken in my build 161.
1. All Windows drives and WSL are mounted at /mnt/host although /etc/wsl.conf [automount section contains root= /windir/
2. /Windir/ folder is not created
3. In the File Explorer I can't access /mnt/c ... - shows message \\wsl$ <distroname> /c is not accessible.You might have no permission to use this network resource
4. If the distro is executed with **wsl -u root** /mnt/c is accessible. Does P9 server require root privileges??? 
It happens in all distros.

**Comment by therealkenc** [comment] 2020-07-20 18:35
> 4. navigate to /mnt/c, try to open
> 5. cd /mnt/c/Users ...

Can't reproduce this here. The my `/mnt/c` is empty, as expected, because the `root =` isn't `mnt`. Posting two issues (whatever is going on with `/etc/hosts` is a thread-killer, but maybe you get some me2s or explanation on the `root =` oddness. Your `/mnt/c` should not have any contents at step 5.

**Comment by PavelSosin-320** [comment] 2020-07-21 08:43
I think I have some hint: when several distros are in the running state there is no "root" process because PID is running continuously and my /init process PID is 434. Systemd can't work in such a situation because it checks strictly PID. WT also confusing because of "used shell" configuration - it obviously tries to start the selected shell and increasing PID. The current distro never has process PID 1.
If /init is a symlink to systemd - see above.
Neither my installed distro had pstree but it can be added using apt-get psmisc and  :
[root@MSI Pavel]# pstree
init─┬─3*[init───init───bash]
     ├─init───init───bash───pstree
     ├─init───init─┬─bash
     │             └─nginx───8*[nginx]
     ├─init───init───bash───bash
     └─{init}
The root /init process has PID 3
Unfortunately, I didn't find any way to do "real reboot" the distro and reset PID.

**Comment by therealkenc** [comment] 2020-07-21 15:13
the PID of the first `/init` of each distro is `1` (use `pstree -p`). There is some `systemd` discussion over in #994. Closing as your OP cannot reasonably be turned into a WSL actionable.

**Closed by therealkenc** 2020-07-21 15:13 UTC
Labels: need-repro

**Comment by PavelSosin-320** [comment] 2020-07-22 06:59
@therealkenc Unfortunately, I retested and the assumption that /init PID is 1 for every distro is not correct! It continuously increases every time. I tried to terminate distro, shutdown wsl but /init PID never returned to 1.
The outcome is that every time I tried to shutdown, reboot, etc. I get "System has not been booted with systemd as init system (PID 1). Can't operate."
```
Even in the old Ubuntu 18.04 without any systems after the termination of distro /init died and after the restart, PID continues to run up to 48.
C:\WINDOWS\system32>wsl -d Ubuntu-18.04 ps
    PID TTY          TIME CMD
     48 pts/0    00:00:00 ps
It is not related to systemd!

```
It looks like every single command execution triggers /init execution, adds 4 to PID but doesn't cleans PID after exit.
wsl shutdown doesn't help evenly.
It was also mentioned that people saw /init process 4 times. I think It is not possible because /init is the root process, i.e. singleton. But I see:
 pstree -p
init(1)─┬─init(6)───init(7)───pstree(8)
        └─{init}(5)

**Comment by PavelSosin-320** [comment] 2020-07-22 07:52
@therealkenc , Please, test combination of wsl - u root and wsl -u root -e  some command.
In the 1st case exit is obligatory. But exit is not shutdown and all started processes continue to run and hold PIDs
If wsl - u root is followed by wsl -u root -e  some command the "new init" replaces the "old init". The old init can be exited because of a user has entered exit and the entire process tree is broken. The user's command runs on the "alternative" process tree.
Since -e I the default user is not able to distinguish in which mode the command is executed. In such a way every wsl -e destroys process tree creating parallel scope with its own root.
After execution of wsl -e process tree is empty:
init─┬─init───init───bash───pstree
     └─{init}

**Comment by therealkenc** [comment] 2020-07-22 13:48
> Unfortunately, I retested and the assumption that /init PID is 1 for every distro is not correct!

It is. Or more accurately there is one PID 1 for each distribution instance that is in the 'Running' state. There are also other `/init` subprocess PIDs as well, but they serve a different purpose. [They are sort of analogous of a `sshd` subprocess in a very loose and and somewhat inaccurate sense.]

> "System has not been booted with systemd as init system (PID 1). Can't operate."

You are running some (unstated) process that expects to be running under `systemd`. WSL has a house brand `/init`. For discussion of that, #994.

> Please, test combination of wsl - u root and wsl -u root -e some command.

"Some command" is not a repro, but in the interest of closure, using the "command" `pstree -p`:

![image](https://user-images.githubusercontent.com/7049700/88183708-a8046b80-cbe6-11ea-9842-e566979d4845.png)

>  the entire process tree is broken

The entire process tree is not broken. PID 1 persists so long as the distribution instance remains in the running state. In the above screencap, my `focal2` distro and `Ubuntu-18.04` distro both have a root PID of `1`. [That's actually a tautology. The "root" process is PID 1 by definition.] Those other `focal2` `9`, `10`, `11` PIDs are different processes under the same `/init` PID 1 for a given distro instance. 

The OP (`root = /windir/`) issue could not be reproduced. I suspect (but can't prove) that was due to changing `wsl.conf` without a (sometimes nonobvious) need for a subsequent `wsl.exe --shutdown`. The `/init` process ID behavior is by-design. The `systemd` related error message is #994.
