### ISSUE TITLE
timerfd_settime reads invalid values with select

### ISSUE THREAD

**Issue by jimmyvanhest** [microsoft/WSL#3210] opened 2018-05-17 19:18 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.431]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I compile the following code which lets an interval timer run for 1 second with an 1 millisecond interval.

```
#include <sys/timerfd.h>
#include <sys/select.h>
#include <unistd.h>
#include <iostream>

int main() {
	auto intervalfd = timerfd_create(CLOCK_MONOTONIC, TFD_NONBLOCK | TFD_CLOEXEC);
	if(intervalfd == -1) {
		std::cerr << "error creating interval fd" << std::endl;
		exit(-1);
	}
	auto timeofd = timerfd_create(CLOCK_MONOTONIC, TFD_NONBLOCK | TFD_CLOEXEC);
	if(timeofd == -1) {
		std::cerr << "error creating timeo fd" << std::endl;
		exit(-1);
	}
	itimerspec interval{{0, 1000000}, {0, 1000000}};
	if(timerfd_settime(intervalfd, 0, &interval, nullptr) == -1) {
		std::cerr << "error setting interval fd" << std::endl;
		exit(-1);
	}
	itimerspec timeo{{0, 0}, {1, 0}};
	if(timerfd_settime(timeofd, 0, &timeo, nullptr) == -1) {
		std::cerr << "error setting timeo fd" << std::endl;
		exit(-1);
	}

	auto countMoreTicks = 0;
	uint64_t countTicks = 0;

	fd_set rfds;
	auto maxFd = std::max(intervalfd, timeofd) + 1;
	while(1) {
		FD_ZERO(&rfds);
		FD_SET(intervalfd, &rfds);
		FD_SET(timeofd, &rfds);
		if(select(maxFd, &rfds, nullptr, nullptr, nullptr) == -1) {
			std::cerr << "failed to select" << std::endl;
			exit(-1);
		}
		if(FD_ISSET(timeofd, &rfds)) {
			break;
		}
		if(FD_ISSET(intervalfd, &rfds)) {
			uint64_t ticks;
			if(read(intervalfd, &ticks, sizeof(ticks)) == -1) {
				std::cerr << "failed to read timerfd" << std::endl;
				exit(-1);
			}
			if(ticks > 1) {
				countMoreTicks++;
			}
			countTicks += ticks;
		}
	}

	std::cout << "expected 1000 ticks got " << countTicks << " amount of multiple ticks: " << countMoreTicks << std::endl;
}
```

* What's wrong / what should be happening instead:
The read on a timerfd is always returning 1 but should return the number of ticks that have passed resulting in something like this from the above code:
expected 1000 ticks got 679 amount of multiple ticks: 0

**Comment by DarthSpock** [comment] 2018-05-17 19:40
Dupe of #3091

**Comment by benhillis** [comment] 2018-05-17 20:51
@jimmyvanhest - What is the output you are seeing on WSL?  When I run your testcase with the fix for #3091 I'm seeing:

`expected 1000 ticks got 933 amount of multiple ticks: 0`

**Comment by jimmyvanhest** [comment] 2018-05-18 06:44
@benhillis at my first post at the last paragraph you see my output for this test.

`expected 1000 ticks got 679 amount of multiple ticks: 0`

what i want to show with this test is that the read on a timerfd is not conform to what the man page says it needs to do.
```
Operating on a timer file descriptor
       The file descriptor returned by timerfd_create() supports the follow‐
       ing operations:

       read(2)
              If the timer has already expired one or more times since its
              settings were last modified using timerfd_settime(), or since
              the last successful read(2), then the buffer given to read(2)
              returns an unsigned 8-byte integer (uint64_t) containing the
              number of expirations that have occurred.  (The returned value
              is in host byte order—that is, the native byte order for inte‐
              gers on the host machine.)
```

**Comment by jimmyvanhest** [comment] 2018-07-19 09:35
anyone looking or planning to look at this?

**Comment by onomatopellan** [comment] 2018-07-19 12:05
On build 17134

> expected 1000 ticks got 975 amount of multiple ticks: 0
expected 1000 ticks got 979 amount of multiple ticks: 1
expected 1000 ticks got 979 amount of multiple ticks: 1
expected 1000 ticks got 979 amount of multiple ticks: 0
expected 1000 ticks got 980 amount of multiple ticks: 1
expected 1000 ticks got 980 amount of multiple ticks: 0
expected 1000 ticks got 979 amount of multiple ticks: 1
expected 1000 ticks got 971 amount of multiple ticks: 28
expected 1000 ticks got 979 amount of multiple ticks: 0
expected 1000 ticks got 980 amount of multiple ticks: 1
expected 1000 ticks got 980 amount of multiple ticks: 0

On build 17713

> expected 1000 ticks got 950 amount of multiple ticks: 16
expected 1000 ticks got 959 amount of multiple ticks: 1
expected 1000 ticks got 957 amount of multiple ticks: 6
expected 1000 ticks got 960 amount of multiple ticks: 0
expected 1000 ticks got 958 amount of multiple ticks: 1
expected 1000 ticks got 958 amount of multiple ticks: 0
expected 1000 ticks got 959 amount of multiple ticks: 0
expected 1000 ticks got 958 amount of multiple ticks: 3
expected 1000 ticks got 957 amount of multiple ticks: 2

I'd need a better test case because I really don't get it.

**Closed** 2024-02-01 12:54 UTC
Labels: wsl1
