### ISSUE TITLE
 File permission on 9P server

### ISSUE THREAD

**Issue by LightMelodies** [Microsoft/WSL#3990] opened 2019-04-23 03:47 UTC
It seems that file access to wsl via 9P server is limited by the default user's permission. 
For example, you can not copy file to /  in explorer,  or edit /etc/profile using visual studio code,  even when they are launched  by root user.  Does this work by design？

Microsoft Windows [Version 10.0.18875]

**Comment by therealkenc** [comment] 2019-04-23 04:40
> using visual studio code, even when they are launched by root user

You can't launch (Windows) VS Code as root user. Because Windows doesn't have a root user.

Bet you could get it to go by changing the distro's default user to root (`UID 0`) and rebooting. Haven't tried (nor should anyone try). But that's not really your ask.

> Does this work by design？

Probably best to lump these (which will be incoming for a while) into #3966 as the catchall landing zone. MSFT win32 will probably get `chown` on their 9P fs around the same time as `chmod`. Which, for the immediate purposes of your question, it has neither, by design -- for lack of a better way to describe it.

**Closed by therealkenc** 2019-04-23 04:40 UTC
