### ISSUE TITLE
Docker vulkaninfo only showing CPU

### ISSUE THREAD

**Issue by selmiskr** [microsoft/WSL#11303] opened 2024-03-14 16:25 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Other Software

Docker Desktop (Windows): 4.28.0

### Repro Steps

GIVEN following Dockerfile

```dockerfile
FROM nvidia/cuda:12.3.2-base-ubuntu22.04
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

# DEPENDENCIES
RUN apt update && apt install -y software-properties-common
RUN add-apt-repository ppa:kisak/kisak-mesa && apt update
RUN apt update && apt install -y \                       
        libatomic1 \
        libxi6 \
        libxrandr2 \
        libxt6 \
        libegl1 \
        libglu1-mesa \
        libgomp1 \
        libsm6 \
        libvulkan1 \
        mesa-vulkan-drivers \
        vulkan-tools \
        sudo && rm -rf /var/lib/apt/lists/*

WORKDIR /etc/vulkan/icd.d
RUN ls -l
RUN sudo touch nvidia_icd.json
RUN printf "{ \"file_format_version\" : \"1.0.0\", \"ICD\": { \"library_path\": \"libGLX_nvidia.so.0\", \"api_version\" : \"$(dpkg -s libvulkan1 | grep -oP 'Version: [0-9|\.]+' | grep -oP '[0-9|\.]+')\" } }" | sudo tee nvidia_icd.json
```

BUILD Dockerfile

### Expected Behavior

WHEN running ```vulkaninfo --summary``` command in WSL2 (Default distro is Ubuntu) itself it gives the following result:
![image](https://github.com/microsoft/WSL/assets/8503234/1704a563-28a3-4651-ab57-073bcff648be)

So WSL2 recognizes the GPU

### Actual Behavior

RUNNING following command:
```bash
docker run `
--rm `
--privileged `
--gpus=all `
-it `
vulkaninfo --summary
```

GIVES the following result:
![image](https://github.com/microsoft/WSL/assets/8503234/f97b7540-9f4b-4b03-84f7-cd5f20e58dc7)

RUNNING following command:
```bash
docker run `
--rm `
--privileged `
--gpus=all `
-it `
nvidia-smi
```

GIVES the following result:
![image](https://github.com/microsoft/WSL/assets/8503234/5a977788-f711-4674-9ac1-6d3b174ed180)

**Comment by OneBlue** [comment] 2024-03-14 17:57
The GPU is available in WSL2 so the issue is most likely at the docker level. I'd recommend raising the issue [here](https://github.com/docker/for-win/issues) instead.

Closing since this is not a WSL2 issue.

**Closed by OneBlue** 2024-03-14 17:57 UTC
