### ISSUE TITLE
Error 0x80370102: WSL 2 installation step fails, doesn't tell what failed

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/WSL#5921] opened 2020-09-14 16:32 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

Reported on Twitter by @randomascii 

https://twitter.com/BruceDawson0xB/status/1304656073312202752

Apparently I failed to do one of the fourteen steps to install WSL 2 and Windows doesn't want to tell me which step it is.

![image](https://user-images.githubusercontent.com/679326/93112258-a0a09200-f66c-11ea-8896-b18936bc787f.png)

**WSL logs**: 

#  Expected behavior

Should provide more details about what actually failed

# Actual behavior

Recap: Ubuntu said that a feature needed to be installed. Nope. Virtualization needed to be enabled. Done, Ubuntu now works.
OOB experience: you have 48 packages to upgrade. Here's how to list them. You're on your own for figuring out how to upgrade them.
Linux, don't ever change

Error 0x80370102

**Comment by randomascii** [comment] 2020-09-14 17:48
Thanks for filing. Yes, it would be good to make this error message much cleaner. In particular:
1) The numeric error code should be translated into meaningful text.
2) The current text which says "a required feature is not installed" should be fixed to be accurate.

I assume that it is difficult for WSL to understand why WslRegisterDistribution failed but just assuming that "a required feature is not installed" without somehow verifying what feature that is and whether a lack of installation is the problem is a failure. Maybe the command to enable virtualization should also check to see if virtualization is enabled? I don't know. There are a lot of places to catch this issue and I'm assuming it should be possible to do better.

This was on a Lenovo P51 purchased in 2017, FWIW, and presumably virtualization was off by default.

**Comment by therealkenc** [comment] 2020-12-04 20:25
Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows.

**Comment by randomascii** [comment] 2020-12-04 20:51
I'm not even sure what machine I saw this error on. The third-party networking software question isn't relevant because the root cause of the problem was determined before the bug was even filed:

> Recap: Ubuntu said that a feature needed to be installed. Nope. Virtualization needed to be enabled. Done, Ubuntu now works.

That is, the problem is that if virtualization is not enabled properly the WSL 2 installation will fail with misleading error messages.

**Closed** 2024-02-01 12:15 UTC
Labels: failure-to-launch
