### ISSUE TITLE
Cannot install ifort on BashOnWindows

### ISSUE THREAD

**Issue by tedoreve** [Microsoft/WSL#794] opened 2016-08-06 15:33 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description : I cannot install ifort following the instructions on the website, which work well on my linux system.
- Expected results : install successfully.
- Actual results (with terminal output if applicable) : 
  ## Initializing, please wait...
  
  Something wrong with activation module. Please go to
  ## http://www.intel.com/software/products/support/ for your support options.
  
  Press "Enter" key to quit:
- Your Windows build number: 14393.10
- Steps / commands required to reproduce the error : sudo ./install.sh
- Strace of the failing command：
  [{WIFEXITED(s) && WEXITSTATUS(s) == 2}], 0, NULL) = 2601
  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2601, si_status=2, si_utime=0, si_stime=0} ---
  rt_sigreturn()                          = 2601
  pipe([3, 4])                            = 0
  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fd93cdb0a10) = 2638
  close(4)                                = 0
  read(3, "Linux\n", 128)                 = 6
  read(3, "", 128)                        = 0
  close(3)                                = 0
  wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 2638
  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2638, si_status=0, si_utime=0, si_stime=0} ---
  rt_sigreturn()                          = 2638
  stat("/home/tedoreve/parallel_studio_xe_2016_update2/./cd_eject.sh", {st_mode=S_IFREG|0777, st_size=3264, ...}) = 0
  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fd93cdb0a10) = 2639
  wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 2639
  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2639, si_status=1, si_utime=0, si_stime=0} ---
  rt_sigreturn()                          = 2639
  exit_group(2)                           = ?
  +++ exited with 2 +++ 
- Required packages and commands to install：
  sudo apt-get install build-essential
  sudo apt-get install g++
  sudo apt-get install gcc-multilib
  sudo apt-get install rpm
  sudo apt-get install openjdk-6-jre-headless
  sudo apt-get install libstdc++6

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment] 2016-08-06 16:32
Thanks @tedoreve for reporting this!  I'm not personally familiar with ifort -- is it Java-based?  There are a bunch of Java-related issues currently filed in this bug tracker; Microsoft has indicated that they're working on fixes.

**Comment by tedoreve** [comment] 2016-08-07 03:26
Hi @aseering ,
Thanks for your reaction. Its GUI is based on Java. But I only tried to install it on command line and got this bug. So it is not Java's problems.

**Comment by wuhongyewhy** [comment] 2016-08-07 04:10
ifort is intel fortran compiler. You can get it form https://software.intel.com/en-us/intel-parallel-studio-xe for trail. The whole intel parallel studio, which also include c++ compiler, cannot be installed.

**Comment by aludin** [comment] 2016-11-24 13:49
The installers for the Intel compilers (Parallel Studio) also fail as described in issue #1402, which has been closed as a duplicate of this one

**Comment by sameer** [comment] 2017-04-05 16:27
Is there any update on this?

**Comment by crcrewso** [comment] 2017-04-05 17:31
This has to do with a device id and authentication. It can't complete the activation process for the licensing. I have a separate VM just for icc/ifort testing because of this and there is no solution to date. 

Word to the wise, don't use regenerating mac addresses on eth0 after install either.

**Comment by aseering** [comment] 2017-04-06 00:09
Has this been tried on the pre-release Creators update?  That update exposes a lot more system information, including (I believe) device MAC addresses.

If it still doesn't work, could someone post an updated strace, invoking strace as ` strace -ff`?  (It looks like ifort immediately forks a child process, which causes strace to disconnect early in the trace above.)

**Comment by sameer** [comment] 2017-04-06 00:10
@aseering I am on 1703 15063.14 and it isn't working

**Comment by balabi0github** [comment] 2017-05-16 01:00
any progress on this issue? I can confirm win 10 creator doesn't work.

The installer complains below message

--------------------------------------------------------------------------------
Initializing, please wait...
--------------------------------------------------------------------------------
Something wrong with activation module. Please go to
http://www.intel.com/software/products/support/ for your support options.
--------------------------------------------------------------------------------
Press "Enter" key to quit:

**Comment by dmey** [comment] 2017-11-02 23:00
IPS XE 2018 does install on WSL - see #2608. 
The problem appears to be with a system call.
It may be worth closing this issue as this specific problem has been resolved.

**Comment by tara-raj** [comment] 2018-05-29 21:11
Closing - See above comment

**Closed by tara-raj** 2018-05-29 21:11 UTC
