### ISSUE TITLE
`dnsTunneling = true` doesn't work with split DNS

### ISSUE THREAD

**Issue by K900** [microsoft/WSL#10680] opened 2023-10-25 14:59 UTC
### Windows Version

Microsoft Windows [Version 10.0.22635.2486]

### WSL Version

2.0.6.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

NixOS unstable

### Repro Steps

Install Tailscale with split DNS ("MagicDNS") configuration.

On Windows side: 

```
PS C:\Users\me> Get-DnsClient

InterfaceAlias               Interface ConnectionSpecificSuffix ConnectionSpecificSuffix RegisterThi
                             Index                              SearchList               sConnection
                                                                                         sAddress
--------------               --------- ------------------------ ------------------------ -----------
Tailscale                            9 0uptime.ts.0upti.me      {0uptime.ts.0upti.me}    True
Wired                               16 home                     {home}                   True
<snip>

PS C:\Users\me> Resolve-DnsName yui.home  # host on the local network, resolve via local DNS server

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
yui.home                                       AAAA   0     Answer     fd07:2496:3cb2::991
yui.home                                       AAAA   0     Answer     fd07:2496:3cb2::cff
yui.home                                       A      0     Answer     192.168.2.1


PS C:\Users\me> Resolve-DnsName yui.0uptime.ts.0upti.me  # same host via Tailscale, resolved via Tailscale's DNS server

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
yui.0uptime.ts.0upti.me                        A      600   Answer     100.64.0.11
```

On WSL side:

```
~
❯ drill yui.home @127.0.0.42
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 13324
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; yui.home.    IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
.       86400   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2023102500 1800 900 604800 86400

;; ADDITIONAL SECTION:

;; Query time: 375 msec
;; SERVER: 127.0.0.42
;; WHEN: Wed Oct 25 17:58:35 2023
;; MSG SIZE  rcvd: 101

~
❯ drill yui.0uptime.ts.0upti.me @127.0.0.42
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 47533
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; yui.0uptime.ts.0upti.me.     IN      A

;; ANSWER SECTION:
yui.0uptime.ts.0upti.me.        600     IN      A       100.64.0.11

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.42
;; WHEN: Wed Oct 25 17:58:41 2023
;; MSG SIZE  rcvd: 80
```

### Expected Behavior

WSL applications can resolve domains on both networks, choosing the correct nameserver.

### Actual Behavior

Only the Tailscale DNS server is used, local network is ignored.

**Comment by CatalinFetoiu** [comment] 2023-10-27 21:00
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by K900** [comment] 2023-10-28 12:59
[WslNetworkingLogs-2023-10-28_15-59-31.zip](https://github.com/microsoft/WSL/files/13195834/WslNetworkingLogs-2023-10-28_15-59-31.zip)

**Comment by CatalinFetoiu** [comment] 2023-11-14 19:56
@K900 thank you for reporting the issue and adding the traces!

We have identified this as a Windows OS bug and we are working on a fix

**Comment by K900** [comment] 2023-11-14 19:57
Great news! Please keep us updated :)

**Comment by trallnag** [comment] 2024-04-17 11:28
Seeing the same with Cisco AnyConnect. Using dnsmasq as a workaround.

**Comment by chanpreetdhanjal** [comment] 2024-04-25 18:28
Can you please take KB5036980 published in [Windows 11, version 22H2 update history - Microsoft Support](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Ftopic%2Fwindows-11-version-22h2-update-history-ec4229c3-9c5f-4e75-9d6d-9025ab70fcce&data=05%7C02%7Cchdhan%40microsoft.com%7C41bfe1eed68b4b6e74cc08dc5fcc886d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638490579297557463%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=1oJ%2FqtdWzGS16Yx1%2FUIx0QQgln0PJb9TW0eV5cjDSxI%3D&reserved=0), install it and confirm the fix works?

**Comment by CatalinFetoiu** [comment] 2024-07-26 22:39
closing since the issue is fixed. if you still encounter issue after installing KB5036980, please open a new issue. thanks

**Closed by CatalinFetoiu** 2024-07-26 22:39 UTC
Labels: network
