### ISSUE TITLE
nameserver IP address is loopback when dnsTunneling is on

### ISSUE THREAD

**Issue by CarlosNihelton** [microsoft/WSL#10561] opened 2023-09-28 13:32 UTC
### Windows Version

Microsoft Windows [Version 10.0.25951.1010]

### WSL Version

2.0.2.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

Enable DNS tunneling in `~/.wslconfig`

```ini
[experimental]
dnsTunneling=true
```
Restart the VM: `wsl --shutdown`

Run the default distro and loop for the IP address assigned to the nameserver in `/etc/resolv.conf`:

```sh
wsl.exe
cat /etc/resolv.conf

# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 127.0.0.42
```

### Expected Behavior

Expected to find the host address (or an address which the host would respond by).

### Actual Behavior

That address is in the loopback range.

---

That breaks workflows in which we need to talk to servers running inside the host from inside WSL. Those workflows usually relied on the nameserver address written in the autogenerated `/etc/resolv.conf`.
One workaround for such issue is finding the `eth0` adapter default gateway and use that address to talk to the host.

```sh
❯ curl http://127.0.0.42:8000 # ofc that's a loopback to the WSL distro itself, which didn't open that port.
curl: (7) Failed to connect to 127.0.0.42 port 8000 after 0 ms: Couldn't connect to server

❯ ip route ls
default via 172.30.32.1 dev eth0 proto kernel
172.30.32.0/20 dev eth0 proto kernel scope link src 172.30.41.141

❯ curl http://172.30.32.1:8000
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Directory listing for /</title>
</head>
...
```

---

Is that by design? Is it a mistake to rely on the nameserver address in `/etc/resolv.conf` for such workflows?

Enabling the mirrored networking mode also doesn't solve the issue, because the mirrored loopback only replies to `127.0.0.1`, any other address in the loopback range goes back to the WSL distro itself.

### Diagnostic Logs

[WslLogs-2023-09-28_10-22-05.zip](https://github.com/microsoft/WSL/files/12749870/WslLogs-2023-09-28_10-22-05.zip)

**Comment by CatalinFetoiu** [comment] 2023-10-03 22:03
@CarlosNihelton thanks for reaching out

"Is it a mistake to rely on the nameserver address in /etc/resolv.conf for such workflows?" this can still be used when DNS tunneling is turned off and mirrored mode is turned off.

For other configurations, you can still communicate to a host server from inside WSL, using the following methods:

1) For the case of mirrored mode turned off, but DNS tunneling turned on you can do the following:
Obtain the host IP address using "ipconfig /all" and use that for your host server.

Note that it needs to be an IPv4 address in order for WSL to connect to it
Also note that Windows firewall must allow traffic to your host server.

2) For the case of mirrored mode turned on, DNS tunneling turned on you can do the following:
Start the host server on 127.0.0.1 and access it from WSL. As you mentioned, other loopback IPs such as 127.0.0.2 will not work, but 127.0.0.1 works.

You can also start the host server on an IP assigned to the host (different from 127.0.0.1). You can take that IP from "ipconfig /all" as well. In order for this to work, you need to also set "hostAddressLoopback=true" in your wslconfig file (you can find more details in https://learn.microsoft.com/en-us/windows/wsl/wsl-config)

Let us know if those methods work for your use case and if you have other questions

**Comment by CatalinFetoiu** [comment] 2023-10-03 22:41
"One workaround for such issue is finding the eth0 adapter default gateway and use that address to talk to the host" this also works - if you have mirrored mode off, DNS tunneling on

**Comment by CatalinFetoiu** [comment] 2023-10-03 23:28
Resolving as the issue is by design.

Please reopen the issue if the alternative methods for connecting to a host server from WSL are not working for you.

**Comment by CatalinFetoiu** [comment] 2023-10-03 23:28
Resolving as the issue is by design.

Please reopen the issue if the alternative methods for connecting to a host server from WSL are not working for you.

**Closed by CatalinFetoiu** 2023-10-03 23:28 UTC
Labels: network
