### ISSUE TITLE
WSL complete freeze

### ISSUE THREAD

**Issue by androiddisk** [microsoft/WSL#9114] opened 2022-11-04 10:00 UTC
### Version

10.0.22621.674

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

Ununtu 20.04

### Repro Steps

I have the same problem. No new wsl shell window can be created, and the wsl -- shutdown window is stuck. Even the window cannot be closed.  Version 0.70.4.0 is not downloaded from GitHub. It is the 0.70.4.0 version automatically updated by Windows. It should be the same as GitHub https://github.com/microsoft/WSL/releases/tag/0.70.4
This problem has troubled me for a long time.

```
PS C:\Users\zhong> wsl --version
WSL 版本： 0.70.4.0
内核版本： 5.15.68.1
WSLg 版本： 1.0.45
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.674
```

I will cooperate with you if you need me. thank you

### Expected Behavior

Open or shut down the wsl shell normally

### Actual Behavior

get stuck

### Diagnostic Logs

[WslLogs-2022-11-04_14-42-14.zip](https://github.com/microsoft/WSL/files/9937092/WslLogs-2022-11-04_14-42-14.zip)

**Comment by androiddisk** [comment] 2022-11-10 12:18
[wsl2log.zip.005.zip](https://github.com/microsoft/WSL/files/9980562/wsl2log.zip.005.zip)
[wsl2log.zip.006.zip](https://github.com/microsoft/WSL/files/9980563/wsl2log.zip.006.zip)
[wsl2log.zip.007.zip](https://github.com/microsoft/WSL/files/9980564/wsl2log.zip.007.zip)
[wsl2log.zip.008.zip](https://github.com/microsoft/WSL/files/9980565/wsl2log.zip.008.zip)
[wsl2log.zip.009.zip](https://github.com/microsoft/WSL/files/9980566/wsl2log.zip.009.zip)
[wsl2log.zip.010.zip](https://github.com/microsoft/WSL/files/9980567/wsl2log.zip.010.zip)
[wsl2log.zip.011.zip](https://github.com/microsoft/WSL/files/9980568/wsl2log.zip.011.zip)
[wsl2log.zip.012.zip](https://github.com/microsoft/WSL/files/9980569/wsl2log.zip.012.zip)
[wsl2log.zip.013.zip](https://github.com/microsoft/WSL/files/9980570/wsl2log.zip.013.zip)
[wsl2log.zip.014.zip](https://github.com/microsoft/WSL/files/9980571/wsl2log.zip.014.zip)
[wsl2log.zip.001.zip](https://github.com/microsoft/WSL/files/9980572/wsl2log.zip.001.zip)
[wsl2log.zip.002.zip](https://github.com/microsoft/WSL/files/9980573/wsl2log.zip.002.zip)
[wsl2log.zip.003.zip](https://github.com/microsoft/WSL/files/9980575/wsl2log.zip.003.zip)
[wsl2log.zip.004.zip](https://github.com/microsoft/WSL/files/9980577/wsl2log.zip.004.zip)



270+M logs cannot be uploaded. So, I compress in segments. And renamed it. Please download 14 zip files and remove the suffix of. zip

**Comment by androiddisk** [comment] 2022-11-10 13:14
Most windows keep flashing. Occasionally the window will prompt


```
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
Error code: Wsl/Service/0x8007274c
请按任意键继续. . .
```

**Comment by androiddisk** [comment] 2022-11-10 13:28
@OneBlue  thank you

**Comment by mwoodpatrick** [comment] 2022-11-11 13:00
I am still seeing the same issue I captured 

[core.zip](https://github.com/microsoft/WSL/files/9990379/core.zip)

output from curl command

curl -k https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/dump-init.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   843  100   843    0     0   2365      0 --:--:-- --:--:-- --:--:--  2367
Loaded plugin: tdnfrepogpgcheck
Package gdb is already installed.
Nothing to do.
[New LWP 5]
0x00000000003bc9cd in ?? ()
Saved corefile core.1
[Inferior 1 (process 1) detached]
[New LWP 30]
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0x00000000003bc9cd in ?? ()
Saved corefile core.2
[Inferior 1 (process 2) detached]
0x00000000003bc9cd in ?? ()
Saved corefile core.6
[Inferior 1 (process 6) detached]
[New LWP 29]
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0x00000000003bc9cd in ?? ()
warning: target file /proc/28/cmdline contained unexpected null characters
Saved corefile core.28
[Inferior 1 (process 28) detached]
0x00000000003bc9cd in ?? ()
Saved corefile core.52
[Inferior 1 (process 52) detached]
0x00000000003bc9cd in ?? ()
Saved corefile core.53
[Inferior 1 (process 53) detached]
Logs and dumps written in /mnt/c/wsl-init-dump-2022-11-11_04-46-29

**Comment by androiddisk** [comment] 2022-11-11 15:20
> 

 tdnf: command not found

**Comment by androiddisk** [comment] 2022-11-11 15:22
@OneBlue 

tdnf: command not found

**Comment by OneBlue** [comment] 2022-11-11 19:11
@androiddisk: Did you run this command in a system shell (via `wsl.exe --system -u root` )? That's where tdnf would be)

**Comment by mwoodpatrick** [comment] 2022-11-11 20:01
I hit the same issue again and captured all the requested files (this time) in
[capture_part1.zip](https://github.com/microsoft/WSL/files/9992962/capture_part1.zip)
there will be a second part as the data exceeds 25MB

**Comment by mwoodpatrick** [comment] 2022-11-11 20:02
second part

**Comment by OneBlue** [comment] 2022-11-11 20:53
Thank you for the files @mwoodpatrick. Next time this reproes can you also a dump of `wslservice.exe` (along with the other files)` ? I'd like to see both from the same repro.

If it's too big for Github, feel free to use OneDrive / GoogleDrive.

**Comment by androiddisk** [comment] 2022-11-12 05:14
> @androiddisk: Did you run this command in a system shell (via `wsl.exe --system -u root` )? That's where tdnf would be)

```
D:\kooapk\yuanc\data>wsl --u root --system
无效的命令行参数： --u
请使用"wsl.exe --help"获取受支持的参数列表。
```

**Comment by mwoodpatrick** [comment] 2022-11-12 10:41
You should be able to  access the files https://drive.google.com/drive/folders/12xKDVhbyeY8pFNaGsZaumffOxJQPUaCk?usp=sharing please let me know if you have any issues

**Comment by mwoodpatrick** [comment] 2022-11-12 13:14
Here is another datapoint https://drive.google.com/file/d/134CzXAJv0gngd50sLDGGv9Ww9N7-_N2A/view?usp=sharing

**Comment by inoue-katsumi** [comment] 2022-11-17 09:42
I can only run `dump-init.sh` in `WSL Debug Shell` when this symptom occurs. How is it possible to tar up and upload core.* and *.txt files under /mnt/c/wsl-*  ?

**Comment by OneBlue** [comment] 2022-11-22 19:58
> Here is another datapoint https://drive.google.com/file/d/134CzXAJv0gngd50sLDGGv9Ww9N7-_N2A/view?usp=sharing

Thanks a lot @mwoodpatrick. With this information we have identified the issue. The fix is in [1.0.1](https://github.com/microsoft/WSL/releases/tag/1.0.1).

To install it, download [the package](https://github.com/microsoft/WSL/releases/download/1.0.1/Microsoft.WSL_1.0.1.0_x64_ARM64.msixbundle) and install via: `Add-AppxPackage /path/to/package` in an elevated powershell

Let me know if the issue is solved for you !

**Comment by mwoodpatrick** [comment] 2022-11-25 11:05
I''m running with an updated WSL-2 and was still seeing a hang I will try to capture new data to debug this

WSL version: 1.0.1.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.891

**Comment by OneBlue** [comment] 2022-11-28 19:21
Thank you for the update @mwoodpatrick. Reopened this issue since it seems that the issue is still there for you.

**Comment by mwoodpatrick** [comment] 2022-11-28 19:42
It did hang once after doing the update but I have not seen it recur since and unfortunately, I did not capture that first fail. It definitely seems more reliable with the latest update. I will update the bug with debug info once I get it to fail.

**Comment by MichealReed** [comment] 2022-12-05 22:46
Also experiencing this on a heavy build over WSL.

**Comment by jetvp** [comment] 2022-12-16 03:15
I'm experiencing the same issue using 1.0.3 release.

The steps to recreate the issue are:
- WSL with Ubuntu.
- Docker installed without containerd enabled (haven't seen it with containerd yet).
- Pull computer into hibernation whilst running, and on wake-up the CPU will slowly ramp up to the point WSL can not longer be stopped via the --shutdown option.

Only solution at that stage is to restart the computer.  I've done clean installs of WSL and Docker, and appears to happen each time.

**Comment by Cosss7** [comment] 2022-12-16 03:24
You can stop wslservice.exe instead of restart computer.
And I also get the issue, anything can I provide？



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 16, 2022 11:16 AM
To: ***@***.***&gt;;
Cc: "Wang ***@***.******@***.***&gt;;
Subject: Re: [microsoft/WSL] WSL complete freeze (Issue #9114)




 
I'm experiencing the same issue using 1.0.3 release.
 
The steps to recreate the issue are:
  
WSL with Ubuntu.
 
Docker installed without containerd enabled (haven't seen it with containerd yet).
 
Pull computer into hibernation whilst running, and on wake-up the CPU will slowly ramp up to the point WSL can not longer be stopped via the --shutdown option.
  
Only solution at that stage is to restart the computer.  I've done clean installs of WSL and Docker, and appears to happen each time.

**Comment by mwoodpatrick** [comment] 2022-12-16 14:50
> 

Try capturing the data requested in [OneBlue](https://github.com/OneBlue) commented [on Nov 10](https://github.com/microsoft/WSL/issues/9114#issuecomment-1310736002)

I have not had any recurrence of this issue in last couple of weeks I'm running 

WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22623.1037

**Comment by OneBlue** [comment] 2022-12-16 19:11
Thanks for confirming @mwoodpatrick.

I'll close this for now since the original issue appears to be resolved.

Thanks for reporting this @jetvp. We're tracking this issue on #8696

**Closed by OneBlue** 2022-12-16 19:11 UTC

**Comment by MichealReed** [comment] 2022-12-20 22:20
Fyi my freeze is not related to hibernate, I do not use this feature.

**Comment by androiddisk** [comment] 2022-12-21 05:15
@OneBlue 
```
C:\Users\zhong>wsl
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
Error code: Wsl/Service/0x8007274c

```


```
C:\Users\zhong>wsl --version
WSL 版本： 1.0.3.0
内核版本： 5.15.79.1
WSLg 版本： 1.0.47
MSRDC 版本： 1.2.3575
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.963

```

Duplicate the same bug

But after a few minutes, you can open the wsl terminal again
