### ISSUE TITLE
Unable to connect to docker daemon from inside WSL

### ISSUE THREAD

**Issue by tnguyen14** [Microsoft/WSL#2102] opened 2017-05-14 04:29 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

    Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

    I have Docker for Windows running on the Windows host, and then `docker` client from inside WSL. I also set `DOCKER_HOST` to point to `tcp://0.0.0.0:2375`. This was working a few days ago. But recently, it couldn't connect to the docker daemon anymore.
    ```
    :; docker ps
    Cannot connect to the Docker daemon at tcp://0.0.0.0:2375. Is the docker daemon running?
    :; echo $DOCKER_HOST
    tcp://0.0.0.0:2375
    ```

    From the regular CMD terminal, I can run `docker.exe ps` and that works fine.

    ```
    C:\Users\tri
    λ docker.exe ps
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               
    NAMES
    ```

**Comment by friism** [comment] 2017-05-15 02:41
![image](https://cloud.githubusercontent.com/assets/126104/26040813/2c15524a-38dd-11e7-8332-c4facd4a8ebc.png)

Having the Docker API available on :2375 is not secure so we turned it off by default, but you can enable it if you want.

**Comment by tnguyen14** [comment] 2017-05-15 14:34
Thanks @friism. Is there a way to make TLS work from inside WSL?

**Comment by alexsandro-xpt** [comment] 2017-05-15 18:48
@friism where can I enable for my Docker for Windows it?

**Comment by friism** [comment] 2017-05-15 18:52
@alexsandro-xpt it's in Docker for Windows settings (the whale icon in your systray).

**Comment by mmarchini** [comment] 2017-06-02 00:25
@tnguyen14 I was able to make TLS work from inside WSL by changing `DOCKER_CERT_PATH` environment variable (which I got from running `eval $(docker-machine.exe env --shell bash)`) from `"C:\C:\Users\mmarchini\.docker\machine\machines\default"` to `"/mnt/c/Users/mmarchini/.docker/machine/machines/default/"` . At least `docker build` seems to be working now, I'll try using docker-compose later.

**Comment by tnguyen14** [comment] 2017-06-02 13:24
@mmarchini very cool! Is that something you only need to do once? Is it required upon restart?

**Comment by mmarchini** [comment] 2017-06-05 15:53
Yes, you need to do this on each bash instance (the same way `docker-machine env | Invoke-Expression` needs to be run on each PowerShell instance). I [created a script](https://gist.github.com/mmarchini/bc9df7b82127fea13612edf8bffdf96f) to help doing that, it will run `docker-machine env` and convert the path on `DOCKER_CERT_PATH` to a valid WSL path. You can add this script in any folder present on your `PATH` and run it as follow:

`eval $(docker-env)`

Much easier than changing the value on `DOCKER_CERT_PATH` manually :)

**Comment by sgtoj** [comment] 2017-11-19 13:01
I believe this ticket can be closed as working as intended. Furthermore, the _issue_ was unrelated to WSL.

**Closed** 2017-11-19 14:58 UTC

**Comment by guobiao-cn** [comment] 2020-10-11 18:45
ISSUE: Cannot connect to the Docker daemon at tcp://127.0.0.1:2375

>!Please follow the order
# 0. PWOERSHELL
wsl -l -v   # ALL DISPLAY "2"

# 1. LINUX
unset DOCKER_HOST
/etc/init.d/docker restart

# 2. restart docker
- windows docker restart
- windows firewall off

# 3. LINUX
docker ps
