### ISSUE TITLE
WSL freezes intermittently when using its file system via Windows Explorer

### ISSUE THREAD

**Issue by danchitnis** [microsoft/WSL#8218] opened 2022-04-01 06:07 UTC
### Version

Microsoft Windows [Version 10.0.22581.200]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

(Intermittent) use any tools which access wsl file system, especially in Windows via `\\wsl `. If a large number of files are accessed, then wsl freezes, which leads to freezing of the software which is accessing it, freezing of cmd, powershell, some time Windows Store. The only remedy is to reboot since it is not possible to stop the `VmemWSL` process.  This problem has happened in the recent build (or previous), either related to Explorer.exe, the updated WSL Kernel or the new windows terminal.

### Expected Behavior

All files should be accessible.

### Actual Behavior

Freezing of wsl, the software which is accessing wsl, the entire `Linux` section in Windows Explorer, Windows Terminal, and Windows Store.

**Comment by pmartincic** [comment] 2022-04-01 17:02
Duplicate of #8170

**Closed by pmartincic** 2022-04-01 17:02 UTC
