### ISSUE TITLE
Dark blue text on black background unreadable

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/WSL#930] opened 2016-08-18 12:07 UTC
It seems some output of the bash is usually in dark blue on black background. This is impossible to read.
![image](https://cloud.githubusercontent.com/assets/1658949/17773069/aaa4cc86-654c-11e6-963b-6943cfe238bc.png)

Changing the background color of the window to a different color is pointless, because the blue output actually defines a black background.
![image](https://cloud.githubusercontent.com/assets/1658949/17773092/d86b9e42-654c-11e6-95a4-53f8be7f2c4e.png)
- Expected results
  There would either be a default color scheme that makes more sense or the option to change it.
- Actual results (with terminal output if applicable)
  See above
- Your Windows build number
  14393.51

**Comment by LFBernardo** [comment] 2016-08-18 12:34
cd ~
vim ~/.bashrc
paste this at bottom of file
LS_COLORS=$LS_COLORS:'di=0;36' ; export LS_COLORS
PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\] '
save exit
. .bashrc (note the space between the two dots)

![image](https://cloud.githubusercontent.com/assets/18407412/17773883/e6e34eb2-6550-11e6-8d1e-ecba05177263.png)

**Comment by ConnorVG** [comment] 2016-08-18 15:33
Did you restart your console after applying the background colour @oliversalzburg? A full restart of the console is required.

**Comment by oliversalzburg** [comment] 2016-08-19 07:53
@ConnorVG Very interesting. That does change the outcome indeed. However, not fully.
![image](https://cloud.githubusercontent.com/assets/1658949/17802692/111bb83a-65f2-11e6-908c-73b6013ca921.png)
`blkid.tab` still has the wrong background color, but this definitely helps.

I also realized that when you adjust the RGB values for black, that takes effect immediately.

I also now realized something else. It *is* possible to adjust all colors, it's just cumbersome af. You can click any of the colors on the palette, which selects it as the default background color, then you can adjust that palette index's RGB values and switch the background back to the palette index you had before. Then you repeat that for every single color you want to adjust and hope that you don't kill yourself in the process.

**Comment by ConnorVG** [comment] 2016-08-19 08:05
@oliversalzburg yeah - it's a bit brutal. It took me way too long to achieve this: 
![image](https://cloud.githubusercontent.com/assets/3260091/17803106/16b57250-65ec-11e6-9477-ba3bf13572ed.png)

**Comment by oliversalzburg** [comment] 2016-08-19 08:05
@LFBernardo Those additions to my `.bashrc` have no effect. Only when I start *another* bash *from* bash, then they're applied. No idea why that is.

**Comment by oliversalzburg** [comment] 2016-08-19 08:22
@ConnorVG Looking good. I would assume this information is stored *somewhere*, but I couldn't find anything in the registry so far. :\

**Comment by ericblade** [comment] 2016-08-19 11:12
I have to say that the default dark red looks terrible on 3 of my 4 monitors as well, the only one that it looks ok on has really broken color settings anyway.

**Comment by LFBernardo** [comment] 2016-08-19 13:43
@oliversalzburg that is very weird, but then again there seems to be subtle difference between the three machines I am running now as well that reach beyond appearance. Copy and paste for example, works on one but not the other two, have to select the Ubuntu icon at the top to do that..... But that is why it isn't a full release yet so that we can help them iron out the bugs. The blue definitely has to go, not just in WSL but also in other versions of linux, it's never properly visible and has been a pain in the butt for many years. I suggest googling LS_COLORS and seeing the other configuration options?

**Comment by oliversalzburg** [comment] 2016-08-19 14:47
@LFBernardo The funny thing is that I have already set `LS_COLORS`. I'm actually running `dircolors`, but none of this has any effect unless I start bash again from within the first bash.

**Comment by ni554n** [comment] 2016-08-25 06:56
@ConnorVG Your console is looking awesome. How do I customize console colors like that?

**Comment by rodrymbo** [comment] 2016-08-25 14:36
@LFBernardo - How are you starting `dircolors` or whatever? 

The default Bash.exe doesn't do a login shell yet. (It just reads `.bashrc`.) If you do `su - <username>` or `bash -l`, you'll get both `.bashrc` and `.bash_profile`, etc. Maybe that is why you aren't getting the right colors until you start a new bash from within Bash.exe? (My dircolors is in `.bashrc` at present, but maybe yours is in `.bash_profile`?)

**Comment by oliversalzburg** [comment] 2016-08-25 15:10
@rodrymbo I think I reverted most of my initial attempts, but AFAIR, I used `/etc/bash.bashrc`. But I guess what you're saying is something to take into consideration.

As it always was, using a different console emulator is the way to go as it seems:
![image](https://cloud.githubusercontent.com/assets/1658949/17974551/d6cb88dc-6ae6-11e6-85d6-81e50a9cae54.png)

**Comment by rodrymbo** [comment] 2016-08-25 17:39
@oliversalzburg - may we ask which terminal emulator you selected? Looks like it might be ConEmu. 

I mostly just use PuTTY, since I'm used to it.

It'll be good to get the Console working as a terminal emulator for Bash.exe...

**Comment by oliversalzburg** [comment] 2016-08-25 17:46
@rodrymbo Yes, that is ConEmu. Sorry for not mentioning it.

**Comment by zadjii-msft** [comment] 2016-10-04 22:44
First off, this is kind of a dupe of #366, but I'm going to mark that one as a dupe as this one has WAY more discussion.

MSFT:8661767 is our internal number for updating the color palette. I'm not sure if we'll have time to do it in this particular round of updates, but we've definitely got our eye on it. Bother @bitcrazed on twitter (his work handle is @richturn-ms) if you want to see it done sooner :P. 

Moreso, which I've definitely mentioned before but bears repeating because it came up on this thread - I'm very aware of how hard it is to work with the colors dialog currently. It's personally high on my list of priorities, but not necessarily so high on our overall priorities.

**Comment by laktak** [comment] 2016-11-18 07:54
One workaround (or the only one that really worked for me) is to install the solarized-dark theme from https://github.com/neilpa/cmd-colors-solarized (close/open the console window to activate)

**Comment by Trainmaster** [comment] 2017-04-14 11:23
@zadjii-msft I can't understand why this has such low priority. After enabling the WSL you just want to work with the bash. If I first have to fiddle around to have a color scheme one can actually work with - that's really bad in terms of usability.

**Comment by JimAmuro** [comment] 2017-04-14 14:07
Since now 24-bit color only works with default shell (without open API), we don't have other choices (like ComEmu), hence I think MS is responsible for the user experience of the default shell, especially the appearance and editing experience (I wish something like Cmder, but maybe that's too much, at least it should be usable).

**Comment by aseering** [comment] 2017-04-14 16:20
@Trainmaster -- I agree for what it's worth that this is important.  But I can see why it wouldn't be top priority:  I personally have no desire to reconfigure the defaults for the Windows console.  In fact, I often go out of my way to configure other shells on other platforms to more-closely match what the default Windows shell does, because for my eyes it is more readable.  (I didn't start off using this color scheme; I've settled on it after some experimentation.)  Perhaps some people on the WSL team happen to have eyes whose color responsiveness is closer to mine than to yours?

**Comment by Po-wei** [comment] 2017-04-27 12:10
I have a problem here
I use @LFBernardo 's solution to adjust ls color, and it works pretty well3
However, when I use zsh's tab-auto-complete, it turns out the same color as before.
Anyone has idea?

**I type cd and hit tab**
![image](https://cloud.githubusercontent.com/assets/17596021/25482676/618258ca-2b85-11e7-9c65-9126b44e2b08.png)

**Comment by akorb** [comment] 2017-07-10 21:02
This is still a problem

**Comment by zadjii-msft** [comment] 2017-07-10 21:19
@akorb Don't you know it. The default palette is just terrible. We've been having a lot of discussions related to this recently. We should have an update for you later this week on this very topic. Stay tuned :)

**Comment by evandrocoan** [comment] 2017-07-17 07:16
I applied this registry entries:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
;                    00BBGGRR, not RGB!
"ColorTable00"=dword:00000000 ;  0 - black
"ColorTable04"=dword:000000CD ;  1 - dark red
"ColorTable02"=dword:0000CD00 ;  2 - dark green
"ColorTable06"=dword:0000CDCD ;  3 - dark yellow
"ColorTable01"=dword:00EE0000 ;  4 - dark blue
"ColorTable05"=dword:00CD00CD ;  5 - dark magenta
"ColorTable03"=dword:00CDCD00 ;  6 - dark cyan
"ColorTable07"=dword:00E5E5E5 ;  7 - light gray
"ColorTable08"=dword:007F7F7F ;  8 - dark gray
"ColorTable12"=dword:000000FF ;  9 - red
"ColorTable10"=dword:0000FF00 ; 10 - green
"ColorTable14"=dword:0000FFFF ; 11 - yellow
"ColorTable09"=dword:00FF5C5C ; 12 - blue
"ColorTable13"=dword:00FF00FF ; 13 - magenta
"ColorTable11"=dword:00FFFF00 ; 14 - cyan
"ColorTable15"=dword:00ffffff ; 15 - white
```

From:

1. https://github.com/Microsoft/vscode/issues/7556#issuecomment-309307794 Bash for Windows colors are unreadable with default terminal theme

And fixed my colors problems. They said we need to set the:
 > default console colors to be the same as the default XTerm colors

**Comment by zadjii-msft** [comment] 2017-07-17 16:23
@evandrocoan I disagree that they need to be the same as xterm's defaults - every terminal in the world [has it's own defaults](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) - but it does need improvement. 

I may have jumped the gun when I said "this week" - but it will be Soon<sup>TM</sup>

**Comment by markeissler** [comment] 2017-07-24 21:44
A huge step forward would be to simply support themes that could be imported into the terminal emulator just like [iTerm2 ](https://www.iterm2.com/)for macOS:

[iTerm Color Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes)

Right now I have the following appended to my `.bashrc` and it does a pretty good job so far:

```sh
LS_COLORS='rs=0:di=1;35:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41
:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=
01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;3
1:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=
01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.x
bm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;
35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.n
uv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*
.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;3
6:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga
=00;36:*.spx=00;36:*.xspf=00;36:';
export LS_COLORS

PS1='\e[37;1m\u@\e[35m\W\e[0m\$ ' # this will change your prompt format
```

...but I certainly don't have to customize colors like this on my Macbook, other than selecting a workable theme in iTerm2.

**Comment by zadjii-msft** [comment] 2017-08-02 22:16
I can finally comment on this!

https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/
![image](https://user-images.githubusercontent.com/18356694/28897432-887b8008-7795-11e7-831b-f43f80a2cb52.png)

Should be fixed in 16257

**Comment by mhchu** [comment] 2017-08-03 19:02
@zadjii-msft It sounds like they aren't updating people who already have Windows 10... so we have to wait to get that new tool they hinted at? Trying to decide to wait or go ahead and change my registry (never to remember to change them back if the tool comes out eventually).

**Comment by zadjii-msft** [comment] 2017-08-03 19:21
@mhchu It's very likely that if you've ever changed your colors before, you will probably not see the change, just from the nature of how console properties are loaded. 

You're always free to set the table to whatever you'd like, this is just a new default experience, so hopefully people like myself won't be so frustrated with the defaults.

We should have more news about the tool in the next week, stay tuned.

**Comment by erichiller** [comment] 2017-08-12 20:26
I'm using `dircolors` just fine in Linux directories, the problem is under `/mnt` **every** file is marked `EXECUTABLE` and every directory as `OTHER_WRITEABLE` - and I can't seem to filter out the actual executables with `*.exe 00;32` or whatever. Shouldn't the individual file types take precedence?

**Comment by 8ivek** [comment] 2017-10-26 19:51
@markeissler  : thanks

Following as per @markeissler  worked for me:

> LS_COLORS='rs=0:di=1;35:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41
:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=
01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;3
1:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=
01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.x
bm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;
35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.n
uv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*
.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;3
6:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga
=00;36:*.spx=00;36:*.xspf=00;36:';
export LS_COLORS

PS1='\e[37;1m\u@\e[35m\W\e[0m\$ ' # this will change your prompt format

**Comment by rm-bergmann** [comment] 2018-01-10 14:11
I'm using Powershell + ZSH. I have configured powershell so the normal text is bright pink on black background and I changed my LS_COLORS in my .zshrc file to Cyan which is great!

My current config in .zshrc / .bashrc
#Change ls colours
LS_COLORS="ow=01;36;40" && export LS_COLORS

# Make cd use the ls colours
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
autoload -Uz compinit
compinit

However, I still have a problem with dark blue text on black background. I don't think this text is part of LS_COLORS. Anyone know how or where to update those 2 dark blue colours? I have no idea where they come from? Is it something in the windows registry?


![powershell](https://user-images.githubusercontent.com/7300540/34776441-d751aa70-f60e-11e7-9695-66b2314a1e8c.png)

**Comment by bitcrazed** [comment] 2018-01-10 18:03
*This issue is now closed as it has been fixed in Win10 Fall Creators Update*

Please file Console related issues in the Windows Console Issues Repo: https://github.com/microsoft/console/issues

Thanks.

**Closed by bitcrazed** 2018-01-10 18:03 UTC
Labels: console, fixedininsiderbuilds

**Comment by bitcrazed** [comment] 2018-01-10 18:20
@rm-bergmann If Fall Creators Update (FCU), we updated the Console's default color palette: https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/

Alas, for a variety of reasons, if you've upgraded your machine to FCU from a previous release, you won't see the new default Console color palette unless you use the ColorTool to modify the default Console colors: https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/

If you've clean-installed FCU, you should see the updated palette being used if you launch a distro from Cmd, from the start menu distro tile, or from a shortcut you pin to your taskbar.


However, if you launch a distro from PowerShell, the Console you're using will have a different palette defined by PowerShell, which still includes the default dark blue == RGB(0, 0, 128) which is very dark.

If you want, you could modify your PowerShell settings to change the dark blue at index #1 (zero-based) to RGB(0,  55, 218) as per the Console's new default:

![image](https://user-images.githubusercontent.com/961950/34788419-5f86ca94-f5ef-11e7-886d-ced51719a1ed.png)

Also, try launching your distro from a cmd Window, or directly from your distro's start menu tile.

**Comment by rm-bergmann** [comment] 2018-01-10 19:58
Thanks @bitcrazed!

I have the FCU update and I have the new colour pallette, which is what I used to make the background black and the screen text pink. 

I actually didn't realize that I could change those colours in the pallete inside the 'selected color values' section without selecting the colour as the default! 

I love the flexibility, and my issue is sorted now.
Thank You

**Comment by naalberg** [comment] 2018-11-01 20:19
there is not a single solution in this entire page. someone at microsoft needs to be FIRED

**Comment by rfaile313** [comment] 2019-07-09 20:06
>LS_COLORS='rs=0:di=1;35:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41
:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=
01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;3
1:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=
01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.x
bm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;
35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.n
uv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*
.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;3
6:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga
=00;36:*.spx=00;36:*.xspf=00;36:';
export LS_COLORS

>PS1='\e[37;1m\u@\e[35m\W\e[0m\$ ' # this will change your prompt format

This works. Thanks @markeissler

**Comment by spacemudd** [comment] 2019-07-10 22:46
> This works. Don't forget to restart the terminal. Thanks @markeissler

Or you can just do `source ~/.bashrc` to load the settings w/o restart.

**Comment by rfaile313** [comment] 2019-07-11 13:56
> Or you can do source ~/.bashrc to load the settings w/o restart.

True true - you can invoke it for the current sesssion. For most folks I'd say a restart is simpler/easier 😄

**Comment by khervey** [comment] 2019-08-25 01:55
I have this problem...but only when in VIM.  Any solution for me?

Incredibly, the below has text:  #!/bin/sh

In blue on black

![image](https://user-images.githubusercontent.com/41525831/63644564-7b339580-c6b1-11e9-99b8-ffc31b26619a.png)

**Comment by LFBernardo** [comment] 2019-08-25 09:40
> I have this problem...but only when in VIM. Any solution for me?
> 
> Incredibly, the below has text: #!/bin/sh
> 
> In blue on black
> 
> ![image](https://user-images.githubusercontent.com/41525831/63644564-7b339580-c6b1-11e9-99b8-ffc31b26619a.png)

vim ~/.bashrc
set background=dark
:wq

The above will resolve your issue

**Comment by khervey** [comment] 2019-08-25 16:07
That was helpful.  I achieved relief by typing into the particular VIM instance as :set background=dark

![image](https://user-images.githubusercontent.com/41525831/63652676-7eb63380-c728-11e9-9fa7-e7162983ff7d.png)

**Comment by khervey** [comment] 2019-08-25 16:09
However, this is the newly edited .bashrc file:

![image](https://user-images.githubusercontent.com/41525831/63652697-d359ae80-c728-11e9-848e-3378f1ce9564.png)

**Comment by LFBernardo** [comment] 2019-08-26 13:11
you need to edit the ~/.vimrc file and add set background=dark
![image](https://user-images.githubusercontent.com/18407412/63693202-b8b03400-c813-11e9-9b30-fbe33474e39d.png)

**Comment by LFBernardo** [comment] 2019-08-26 14:55
in your folder (~) there is a .vimrc file, you will not always have this by default. When you edit it and save it it will become permanent. You must do this as your normal user and not sudo. If you do this in sudo you are exiting your user space. Copy and paste the following line by line into your editor (not the lines with : as they are commands for vim)

vim ~/.vimrc
set background=dark
:wq 

and test it

**Comment by LFBernardo** [comment] 2019-08-27 08:38
you added the command to edit with vim into the file that you were editing
![image](https://user-images.githubusercontent.com/18407412/63755293-aa672400-c8b6-11e9-9ebe-fb487fe3f945.png)

Vim is the editor that you use to edit the files, please remove that first line and save it. Also I cannot guarantee that any of these settings will work when you activate wsl through powershell.

**Comment by LFBernardo** [comment] 2019-08-27 20:02
Happy to hear that worked. I would leave the messages, everything is new to someone at some time. The learning aspect is valuable.

**Comment by mtaylor567** [comment] 2020-05-03 22:30
this is really hard to fix. when are you silly c*nts going to resolve this?

**Comment by oliversalzburg** [comment] 2020-06-24 14:40
I don't understand why it is apparently such a massive challenge to come up with a way to produce a usable appearance for a terminal. I reported this 4 years ago and this is what has been achieved in the meanwhile:

![image](https://user-images.githubusercontent.com/1658949/85576376-a4f27b80-b638-11ea-9757-7707b5c12ed3.png)

I'm baffled as to how this is considered shippable, given this is a directory listing of my home directory with default settings.

For anyone coming here, hoping to get some relief, you're going to want to [remove all background colors from `ls` output](https://stackoverflow.com/a/49390731/259953):
```shell
eval "$(dircolors -p | \
    sed 's/ 4[0-9];/ 01;/; s/;4[0-9];/;01;/g; s/;4[0-9] /;01 /' | \
    dircolors /dev/stdin)"
```

That same garbage output will then look like this:
![image](https://user-images.githubusercontent.com/1658949/85576742-f3a01580-b638-11ea-8e97-c0f22c0e0f00.png)

**Comment by zadjii-msft** [comment] 2020-06-24 15:05
That's a totally different bug my dude - see https://github.com/microsoft/terminal/issues/3848 for more details.

**Comment by pale2hall** [comment] 2020-07-29 12:40
> @rodrymbo I think I reverted most of my initial attempts, but AFAIR, I used `/etc/bash.bashrc`. But I guess what you're saying is something to take into consideration.
> 
> As it always was, using a different console emulator is the way to go as it seems:
> ![image](https://cloud.githubusercontent.com/assets/1658949/17974551/d6cb88dc-6ae6-11e6-85d6-81e50a9cae54.png)

No! That's not a solution to the original XY Question!

that being said, I'm going with it.  Thank you.  ConEmu is beautiful and I think I'll switch.

**Comment by zadjii-msft** [comment] 2020-07-29 12:55
@pale2hall I mean, the [Windows Terminal](https://github.com/microsoft/terminal) does have support for lots of user-defined [color schemes](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes) that don't have the same problem as OP. In fact, [since 2017](blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors) the _console_ hasn't had that problem either. Is there a particular reason you're choosing ConEmu over the Terminal?

**Comment by ProfessorGram** [comment] 2021-07-24 18:09
<add to bottom of ~/.bashrc>
LS_COLORS=$LS_COLORS:'di=0;36' ; export LS_COLORS
$source .bashrc
