### ISSUE TITLE
sync_file_range: Function not implemented

### ISSUE THREAD

**Issue by mathieupost** [microsoft/WSL#645] opened 2016-07-12 15:26 UTC
When I try to run a MongoDB instance (version 3.2.7) with `mongod --dbpath /path/to/database` I get an error saying: `sync_file_range: Funtion not implemented` when using the standard WiredTiger storage engine (when using the old mmapv1, this error doesn't occur).

I've tried this with a dbpath that was an empty directory on a ntfs disk and I also tried a exFat filesystem, but it looks like the sync_file_range function is a linux function that is not yet implemented in the linux subsystem (http://man7.org/linux/man-pages/man2/sync_file_range.2.html).

I'm running build 14379.rs1_release.160627-1607

**Comment by therealkenc** [comment] 2016-07-13 23:35
Also TCP_KEEPIDLE and TCP_KEEPINTVL also appear to be problematic [here](https://github.com/mongodb/mongo/blob/master/src/mongo/util/net/sock.cpp#L134). 

If you're willing to [build](https://github.com/mongodb/mongo/blob/master/docs/building.md) from source, I've hacked a tiny [patch](https://gist.github.com/therealkenc/617e54d75df42b81a050fbdc0730960e) ([short raw](https://goo.gl/RkXL2j)) that works around both issues. Build instructions for WSL are [here](https://gist.github.com/therealkenc/bcd8f51991c85a1df596bdc706b7912c).

**Comment by acezard** [comment] 2016-09-18 11:18
I had the same problem as @mathieupost and installed an old version instead. That v2.4.9 also give me the TCP_KEEPIDLE and TCP_KEEPINTVL errors.

**Comment by hasenbanck** [comment] 2017-04-19 13:49
This issue also arises when you use PostgreSQL under WSL. 
[Affected code line in PostgreSQL](https://github.com/postgres/postgres/blob/master/src/backend/storage/file/fd.c#L443).

**Comment by TheJP** [comment] 2018-04-22 19:12
What is the status on this? I tried to run [borg](/borgbackup/borg) (https://github.com/borgbackup/borg/issues/1961) on WSL but got stuck on this sync_file_range.

```
  File "src/borg/platform/linux.pyx", line 255, in borg.platform.linux.SyncFile.write
  File "src/borg/platform/linux.pyx", line 229, in borg.platform.linux._sync_file_range
OSError: [Errno 38] Function not implemented
```

**Comment by therealkenc** [comment] 2018-06-21 23:32
@dcayme asked in a dupe:
> Does anyone know if this issue will be fixed?

Given this is two years old it would be nice if `sync_file_range(2)` were just stubbed to do nothing. Fine, it can't be implemented right now for _reasons_. MongoDB probably won't pass an ACID test with this stubbed. I get that. But anyone using WSL as their MongoDB _deployment_ environment is high, and for anyone using MongoDB in their _development_ environment, it doesn't matter. 

I'd say different if this were still 2016, and the feature had a snowballs chance of making the Fall 2018 Update. But at this point we aren't learning which surface is missing and in what packages the API is being used. We know.

**Comment by ThomasWaldmann** [comment] 2018-10-07 17:00
borgbackup 1.1.x is not usable on WSL due to sync_file_range failing.

**Comment by ThomasWaldmann** [comment] 2018-10-07 17:03
@mathieupost there's a typo in the issue title. /nitpick

**Comment by mathieupost** [comment] 2018-10-09 11:38
@ThomasWaldmann fixed ;)

**Comment by adrach** [comment] 2019-01-04 06:08
has there been any progress? is there anything we can do to move this along? happy to contribute my time if somebody is willing to partner up with me

**Comment by therealkenc** [comment] 2019-01-04 09:03
> happy to contribute my time if somebody is willing to partner up with me

It is a [trivial](https://gist.githubusercontent.com/therealkenc/617e54d75df42b81a050fbdc0730960e/raw/dafd9267ccfbeba1d118d470f41f1b15ce81d9a5/mongo-3_3_9-wsl.patch) config tweak posted in [July of 2016](https://github.com/Microsoft/WSL/issues/645#issuecomment-232517428). It does not require a team effort. It requires a compiler.

[that patch is why the function call might as well be stubbed in WSL btw]

**Comment by TheJP** [comment] 2019-01-04 13:05
MongoDB is not the only software that calls sync_file_range (e.g. Borg is another one as I pointed out)
Would be cool if adrach or someone else could implement it. But I agree, if it can't be done I would prefer it to be stubbed for now.

**Comment by therealkenc** [comment] 2019-01-04 19:15
> MongoDB is not the only software that calls sync_file_range

🙄

> Would be cool if adrach or someone else could implement it

And how would you propose he or "someone" do that. 

[Allowing for the fact that if don't care if the behavior is stubbed and you are willing to entertain the idea of "Cygwin for WSL" you can do a lot of things. Mask it in the glibc function [here](https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/sync_file_range.c.html#26). Another one-liner that does not require a team.]

**Comment by therealkenc** [comment] 2019-01-04 20:03
Or for that matter [this](https://gist.githubusercontent.com/therealkenc/fbfdca81f6a02e472cfd90d7027ceadc/raw/314b384c08e3deb0096b090f4ae4b06fa40eb340/no-sfr.c) will probably work:

```
// stub-sfr.c
#define _GNU_SOURCE         /* See feature_test_macros(7) */
#include <fcntl.h>
int sync_file_range(int fd, off64_t offset, off64_t nbytes,
                           unsigned int flags)
{
    return 0;
}
```

Build:

```
$ sudo apt-install build-essential wget 
$ cd ~ && mkdir -p ~/no-sfr && cd no-sfr
$ wget -O no-sfr.c https://bit.ly/2LPMywi
$ gcc -fPIC -c -o no-sfr.o no-sfr.c
$ gcc -shared -o no-sfr.so no-sfr.o
$ export LD_PRELOAD="$PWD/no-sfr.so"
$ # ... run stuff
```

Left as an exercise to do `setsockopt(...SO_KEEPALIVE...)`.

**Comment by ThomasWaldmann** [comment] 2019-01-04 20:55
While the dummy implementation might get some stuff "working" (in the sense of "not crashing immediately", not necessarily "working in a always correct manner and/or with good performance"), I'ld appreciate if someone would really **fix** the root cause, i.e. implement the missing function and emulate it as closely as possible for WSL.

It might be really important for transactional behaviour sometimes (like stuff ending up on-disk in right order, e.g. first data, then commit) and also for performance (like avoiding first caching lots of stuff and then having burst of I/O when the cache gets flushed).

**Comment by therealkenc** [comment] 2019-01-04 21:59
> It might be really important for transactional behaviour sometimes

Sigh. Your post (a) states the catastrophically obvious, and, (b) just decreased our changes of the syscall being stubbed by some large percent (if some percent ever existed; I had feint hopes). One imagines this is the reason the devs decided to leave this function return `ENOSYS`.

> ending up on-disk in right order

The syscall is for durability not atomicity or isolation.

Let me repeat: Anyone using WSL as their MongoDB _deployment_ environment is high, and for anyone using MongoDB in their _development_ environment, it doesn't matter. If you are worried about the state of your data in the event of a hard system falldown, **and** don't have a UPS and a clean shutdown protocol in place, **_and_** are using WSL as your platform of choice_, then you have reached a very (let's call it) unusual set of circumstances. Which goes to where implementation of this syscall likely sits in the priority queue (I wouldn't know, but I can make educated guesses). You could, however, open a [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l) ticket describing your specific scenario and needs.

**Comment by ThomasWaldmann** [comment] 2019-01-05 07:00
No need to jump at me.

It seems I confused this syscall with other syscalls borgbackup is doing to make sure stuff ends up on disk in right order before a transaction is committed. I edited my previous comment to remove what was wrong.

borgbackup only uses `sync_file_range` to avoid too much write data piling up in the system's write cache, eating a lot of memory and causing huge bursts later.

I do not use mongodb, nor do I use WSL. I am just trying to help `borgbackup` users who want to run a recent version of it on WSL to backup their data. Hopefully you do not consider them `high` also.

**Comment by therealkenc** [comment] 2019-01-06 16:19
>> While the dummy implementation might get some stuff "working"  (in the sense of "not crashing immediately", not necessarily "working with good performance")

> No need to jump at me.

The shortness was due to the scare quote. The work-around, which is now [buried](https://github.com/Microsoft/WSL/issues/645#issuecomment-451553389), addresses borgbackup issue for the people you are trying to help full stop. With good performance (or rather, as good as it gets on WSL; which is not great).

> I am just trying to help borgbackup users who want to run a recent version of it on WSL to backup their data.

A constructive way to do that would be to upstream a patch to borg that makes that call to `sync_file_range()` a soft fail. There is no reason for borg to falldown. In the alternative, if that sync is considered critical and you want to trap the fail _hard_ on Real Linux (for reasons), guard WSL by parsing `/proc/version`. This will almost certainly be necessary because whatever hope we (you and me) collectively had (if there was any) likely died the moment you posted quoth: "[I'd] appreciate if someone would really fix the root cause", despite the late edit. [Although I would like to be proved wrong, natch.]

> Hopefully you do not consider them high also

Meh. I don't judge.

**Comment by adrach** [comment] 2019-01-08 23:52
sorry, did not mean to cause a storm here... I should have time this weekend to stub it out, how would we go about making a note/warning somewhere that the function is stubbed out?

**Comment by therealkenc** [comment] 2019-01-09 01:53
```
// stub-sfr.c version 2.0
#define _GNU_SOURCE         /* See feature_test_macros(7) */
#include <fcntl.h>
#include <stdio.h>
int sync_file_range(int fd, off64_t offset, off64_t nbytes,
                           unsigned int flags)
{
    static int warning_given = 0;
    if (!warning_given && sync_file_range(fd, offset, nbytes, flags) != 0) {
        fprintf(stderr, "Heads up the program you are running called sync_file_range(),\n"
            "but it failed, so we aren't calling it again. Sorry it didn't work out.\n");
        warning_given = 1;
    };
    return 0;
}
```

That said, such a message conveys no actionable information to the user whatsoever and thus violates some commonly (but by no means universally) accepted UX principles.

**Comment by macdice** [comment] 2019-02-22 02:21
Hello, FYI we'll probably fix this for PostgreSQL by tolerating ENOSYS (we didn't know it was already spewing warnings on WSL because nobody complained; now that we made it into a PANIC, we found out pretty quickly...).  Discussion: https://www.postgresql.org/message-id/flat/CA%2BmCpegfOUph2U4ZADtQT16dfbkjjYNJL1bSTWErsazaFjQW9A%40mail.gmail.com

**Comment by NickMoignard** [comment] 2020-01-18 05:38
can confirm this still exists using rails & pg10.4 on an Ubuntu WSL

**Comment by macdice** [comment] 2020-01-28 06:10
> can confirm this still exists using rails & pg10.4 on an Ubuntu WSL

Please try a current release (eg 10.11).

**Closed** 2020-06-03 05:11 UTC
Labels: feature, fixed-in-wsl2

**Comment by scy** [comment] 2020-06-03 10:50
@therealkenc I’m assuming this issue has been closed because it doesn’t exist anymore in WSL2? And that closing it also means that it won’t be fixed ever for WSL1 users?
