### ISSUE TITLE
Wsl bug report - unbound variable

### ISSUE THREAD

**Issue by GXC2356** [microsoft/WSL#10406] opened 2023-08-21 10:02 UTC
### Windows Version

Microsoft Windows [10.0.22000.2295]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-22.04

### Other Software

Remote desktop but at that time didn't use it, only Windows terminal 

### Repro Steps

Hi, I'm custom ROM builder I have built several roms on wsl but there's an issue happens randomly, sometimes wen I enter ROM command it gives me ' /etc/bash.bashrc: line 7: PS1: unbound variable '

I really hate this error, wen it shows makes wsl Ubuntu freezes/ in xfce4 environment it didn't freeze and build ROM build has been completed successfully but wen I flashed it some problems occured to phone thank God it didn't brick

Plz solve this issue or tell me solution, every time I face it I delete whole wsl and install again

### Expected Behavior

Freezes

### Actual Behavior

In Windows terminal it freezes

In xfce4 it works fine (only terminal not process like building the ROM)

**Comment by OneBlue** [comment] 2023-08-22 21:44
The issue is most likely due a scripting error your .bashrc. WSL doesn't interfere with this file at all.

Closing since this isn't a WSL issue.

**Closed by OneBlue** 2023-08-22 21:44 UTC

**Comment by GXC2356** [comment] 2023-08-22 21:46
> The issue is most likely due a scripting error your .bashrc. WSL doesn't interfere with this file at all.
> 
> Closing since this isn't a WSL issue.

Ohh ok thanks

**Comment by GXC2356** [comment] 2023-08-22 21:54
Another thing plz (not a problem)

How I can apply that kernel? https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.15.123.1

Download source code zip and apply it in wsl.config file or what to do

Sorry if I breaked rules
