### ISSUE TITLE
script command fails, Function not implemented

### ISSUE THREAD

**Issue by brendandburns** [Microsoft/WSL#2053] opened 2017-05-03 18:01 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
`script "echo foo"`

* What's wrong / what should be happening instead:

Observed: Crashes with `script: cannot set signal handler: Function not implemented`
Expected: It should work and not crash.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Relevant strace:
```
... more trace above this ...
open("/usr/share/locale-langpack/en_US.UTF-8/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.UTF-8/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/util-linux.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
fstat(1, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "Script started, file is typescri"..., 35) = 35
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 -opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 -opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [INT QUIT TERM CHLD WINCH], [], 8) = 0
write(2, "script: ", 8)                 = 8
write(2, "cannot set signal handler", 25) = 25
write(2, ": ", 2)                       = 2
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "Function not implemented\n", 25) = 25
close(1)                                = 0
close(2)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment] 2017-05-03 19:24
It definitely looks like we aren't getting `ENOSYS` out of `strace` output these days. All the relevant syscalls look like they succeed above because one is missing. It looks like the relevant line of code in [`script(1)`](http://man7.org/linux/man-pages/man1/script.1.html) is [here](https://github.com/karelzak/util-linux/blob/6f3c9c34306cb40115dc878629667c22a36115a4/term-utils/script.c#L778):
```
	/* block signals used for signalfd() to prevent the signals being
	 * handled according to their default dispositions */
	sigprocmask(SIG_BLOCK, &ctl.sigset, &ctl.sigorg);

	if ((ctl.sigfd = signalfd(-1, &ctl.sigset, SFD_CLOEXEC)) < 0)
		err(EXIT_FAILURE, _("cannot set signal handler"));
```
[`signalfd(2)`](http://man7.org/linux/man-pages/man2/signalfd.2.html) is oldie but a goodie #129. But that `strace` problem really needs addressing.

**Comment by stehufntdev** [comment] 2017-05-04 16:10
Thanks for reporting the issue, yes I can confirm signalfd is not implemented.

@therealkenc, is there a post on the strace ENOSYS issue?  Just started a thread with folks internally and we will take a look.

**Comment by therealkenc** [comment] 2017-05-04 17:42
@stehufntdev - No issue ticket specific to the `ENOSYS` strace issue, probably because it is nontrivial to recognize. It has shown up in #2013 ([message](https://github.com/Microsoft/BashOnWindows/issues/2013#issuecomment-298614843)) and previously in #1530. Might explain why my vscode straces look so clean too 😶.

**Comment by CherryDT** [comment] 2017-06-26 09:55
Note that this also, for some reason, messes up the terminal after it failed. I'm on 15063.

When I run `script` I get the output:

```
Script started, file is typescript
script: cannot set signal handler: Function not implemented
```

And afterwards, the terminal doesn't echo stdin anymore and it doesn't handle newlines correctly (Enter will just append another prompt, and Ctrl+C will go to the next line but not reset the column):

![image](https://user-images.githubusercontent.com/6010463/27534157-51d20686-5a66-11e7-8482-53f829439cdd.png)

**Comment by superherointj** [comment] 2017-10-13 17:12
Right now, can't use 'bs-loader' on WSL, main webpack module loader for bucklescript/reason because of this. Instead of working around upstream everywhere that is using `script`, would be nice having it fixed instead.

This is breaking *everything* that relies on 'script'. 

Is it going to be fixed?

**Comment by superherointj** [comment] 2017-10-13 18:12
Right now, can't use 'bs-loader' on WSL, main webpack module loader for bucklescript/reason, because of this. Instead of working around upstream everywhere that is using script, would be nice having it fixed instead.

This is breaking everything that relies on 'script'.

@jackchammons @benhillis Is it going to be fixed?

**Comment by therealkenc** [comment] 2017-11-15 18:34
Dupe of #129 to keep unimplemented `signalfd` in one place. 10 votes on [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17230763-implementing-signalfd-syscall-in-wsl) as of this writing.

**Closed by therealkenc** 2017-11-15 18:34 UTC
Labels: duplicate
