### ISSUE TITLE
Cannot connect to mysql server in WSL2 from Windows Mysql client

### ISSUE THREAD

**Issue by sonhc** [microsoft/WSL#4369] opened 2019-08-02 04:52 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows 10 v18950
Ubuntu 16.04LTS in WSL2

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)  Cannot connect to mysql server that is running w/in WSL2 with Mysql client HeidiSQL running in Windows.
![image](https://user-images.githubusercontent.com/14983599/62345185-14520080-b4a6-11e9-9f28-5a9302bebd09.png)

It works fine if I run the server in my Ubuntu 18.04LTS WSL1 instance

* What's wrong / what should be happening instead:
What's wrong: Cannot connect to mysql server that is running w/in WSL2 with Mysql client HeidiSQL running in Windows.
What should be happening: Should be able to connect mysql server running in WSL2 from Windows Mysql Client

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by owennewo** [comment] 2019-08-02 15:30
This is sort of a duplicate of #4353 and @benhillis says they are working on it.

In the mean time you need to get mysqld to bind to 0.0.0.0 and also (probably) do another grant as mysql often has username@ip type grants
Doing a quick google:
https://dba.stackexchange.com/questions/64581/mysql-bind-address-0-0-0-0-in-my-cnf-does-not-work

**Comment by sonhc** [comment] 2019-08-02 18:26
That works!!! Thank you.

**Closed** 2019-08-07 00:12 UTC

**Comment by denormalizer** [comment] 2019-12-04 14:02
@sonbach Can you clarify what you did to make it work.

I've changed the bind-address to:

    bind-address            = 0.0.0.0

And HeidiSQL is still not connecting.
