### ISSUE TITLE
2.0.0 to 2.0.3 update failure

### ISSUE THREAD

**Issue by elsaco** [microsoft/WSL#10577] opened 2023-10-02 13:39 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.3448]

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1

### Repro Steps

Run `wsl --update --web-download --pre-release`

### Expected Behavior

Successful update

### Actual Behavior

Fails with `Error code: Wsl/UpdatePackage/E_ABORT`

### Diagnostic Logs

```
PS C:\Users\elsaco> wsl --version
WSL version: 2.0.0.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.57
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.19045.3448
PS C:\Users\elsaco> wsl --update --web-download --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.0.3.
Update failed (exit code: 1603).
Log file: C:\Users\elsaco\AppData\Local\Temp\wsl-install-logs.txt
Error code: Wsl/UpdatePackage/E_ABORT
```

**Comment by DLBerger** [comment] 2023-10-02 14:47
[wsl-install-logs.txt](https://github.com/microsoft/WSL/files/12783668/wsl-install-logs.txt)

**Comment by DLBerger** [comment] 2023-10-02 14:49
Log of my failure

**Comment by g2flyer** [comment] 2023-10-02 22:19
I had same failure, but https://github.com/microsoft/WSL/issues/10574#issuecomment-1743161774 gave the workaround: download the msi and upgrade that way ...

**Comment by OneBlue** [comment] 2023-10-02 22:22
Thank you for reporting this. The issue is that the installation was not run as administrator: 

```
Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.
```

This is already fixed in 2.0.3

**Closed by OneBlue** 2023-10-02 22:22 UTC
Labels: install

**Comment by g2flyer** [comment] 2023-10-02 22:28
Actually,  `--web-download --update` did _not_ work even when run as administrator!  Contrary to non-admin no error was reported but version stayed 2.0.0.  Only .msi install worked for me to upgrade ...

**Comment by pcause** [comment] 2023-10-03 09:45
I just tried to update from 2.0.2->2.0.3 and still needs to be administrator to update.

**Comment by OneBlue** [comment] 2023-10-03 19:02
> I just tried to update from 2.0.2->2.0.3 and still needs to be administrator to update.

That's expected. Updating WSL via the .msi requires administrator. You can still update via the store though
