### ISSUE TITLE
WSL failed to start after system update

### ISSUE THREAD

**Issue by rickywu** [microsoft/WSL#4889] opened 2020-02-13 09:25 UTC
Windows ver 10.0.19559.1000

![image](https://user-images.githubusercontent.com/442398/74420043-c91d9f00-4e85-11ea-9ae3-df0032b1f46d.png)

**Comment by Gongxter** [comment] 2020-02-13 10:43
I have a similar problem which this might be related to  which is mentioned in issue #4860 .

you can create an event log as described here: 
https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

and then read the *.etl file with [tracerpt](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/tracerpt_1)

maybe if you track down the issue it might be the same as mentioned above

**Comment by flipflopfpv** [comment] 2020-02-13 14:20
#4860 is fixed for me in 19564, try updating and testing if it's related it should be fixed as well.

**Comment by craigloewen-msft** [comment] 2020-02-13 20:35
This seems like a duplicate of #4860 as others have pointed out. Please try 19564 and see if it's resolved, if it isn't then please let us know! 

/dupe #4860

**Closed by craigloewen-msft** 2020-02-13 20:35 UTC
