### ISSUE TITLE
tmux does not pick up on current command running in pane

### ISSUE THREAD

**Issue by artursapek** [Microsoft/WSL#1412] opened 2016-11-24 12:54 UTC
I'm trying to run tmux in WSL. I've tried versions 1.8 (installed with `apt-get`) and 2.3 (built from source). In both versions, tmux seems unable to recognize the currently running command in its panes.

WIndows build 14393.447.

Here are expected results, as an example from my Mac. Note how the `pane_current_command` is printed correctly.

![image](https://cloud.githubusercontent.com/assets/897596/20599065/39277d90-b21a-11e6-8cf5-673dcbfdb36c.png)

Here is the broken result demonstrated in the stock windows Command Prompt app. Note how the `pane_current_command` is always `bash`.

![image](https://cloud.githubusercontent.com/assets/897596/20599122/836119ac-b21a-11e6-8a97-7dfd8bc6e901.png)

I get the same result in Cmder:

![image](https://cloud.githubusercontent.com/assets/897596/20599003/d84e5598-b219-11e6-96f1-74a6b9aa0fa2.png)

Running command prompt as an administrator does not help.

This is a big setback because it breaks things like [tmux-vim-navigator](https://github.com/christoomey/vim-tmux-navigator). I'm in the process of switching away from using macs for development, and hoping I can fix this!

BTW, I just found another person asking about a similar issue (`pane_current_path`) on [StackOverflow](http://stackoverflow.com/questions/40784215/tmux-pane-current-path-on-windows-subsystem-for-linux#).

**Comment by fpqc** [comment] 2016-11-24 16:20
This actually happens to me in both Arch and Windows.

**Comment by artursapek** [comment] 2016-11-29 23:35
I'm not sure, but the tabs at the bottom have the same problem (this is what you meant by status bar?). No matter what is running in a window, its tab at the bottom says `bash`. This is not the case in linux/OSX.

**Comment by Perlence** [comment] 2017-02-09 19:07
I'm having a similar issue with `pane_current_path`. When I execute tmux command `split-window -c '#{pane_current_path}' -h`, new pane starts in `$HOME`, not in the path of current pane.

Looks like there's a problem with variable substitution in tmux.

**Comment by ddickstein** [comment] 2017-03-25 04:24
I'm hitting this issue with fzf.  If I run fzf directly it picks up that the command is fzf, but if I pipe to it, e.g. `ls mydir | fzf` and then while fzf is open I try to display pane_current_command I just get "bash".

**Comment by fpqc** [comment] 2017-03-25 08:59
@zadjii-msft @jackchammons I did some research on this, and it is emphatically not a console problem.

First of all, the tmux window's title is set perfectly fine while connected to a remote tmux instance over ssh, and moreover, it's not a problem with the pty code, since doing

`printf "\033k$title\007"`

will actually correctly set the tmux window's title.

The problem is that there is some kind of function inside of tmux that tries to grab the command that launched the process with current control of the pty, and this query is failing, that is to say, it's probably some kind of weird procfs issue.

**Comment by zadjii-msft** [comment] 2017-03-27 18:23
@fpqc thanks for investigating! I'll take the console tag off. @jackchammons I'm not sure which is the best tag to re-categorize this as, so I'll leave that to you :)

**Comment by gpakosz** [comment] 2017-06-18 16:35
I believe this is a dupe of https://github.com/Microsoft/BashOnWindows/issues/1063 and `tcgetpgrp()` returning `-1`

**Comment by sunilmut** [comment] 2017-06-22 00:31
@gpakosz - Thanks. Marking it as dupe. #1063 is already tagged as a bug.

**Closed** 2018-03-18 23:14 UTC
Labels: duplicate, need-repro
