### ISSUE TITLE
Docker on Bash on Windows - Unable to bind unix socket

### ISSUE THREAD

**Issue by mattoni** [microsoft/WSL#2527] opened 2017-09-27 19:18 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
While running the Docker daemon on windows, I connect to it over TCP so I can use bash on windows to send commands. Most things work, but one of the programs I'm writing needs to open a unix socket, and this fails when I try to run the container with the following: 

`Cannot create unix socket '/var/run/agent.sock': listen unix /var/run/agent.sock: bind: operation not permitted`

I'm guessing based on some research that this is due to the docker daemon trying to run the container on the windows file system, which I don't believe supports unix sockets.

* What's wrong / what should be happening instead:
It should create the socket. I'm not sure if there's a workaround that would allow the docker daemon to run on the linux file system, but if this feature was supported it would be fantastic.

**Comment by sunilmut** [comment] 2017-09-28 18:14
@mattoni - `bind` of a unix socket requires write permission on the directory (see `man7 unix`). `/var` by default is only writable by `root`. Are you running the command as `sudo`? Or, you can try `bind` on a different directory.

**Comment by mattoni** [comment] 2017-09-29 17:36
when i try running docker as root with sudo, it defaults back to not using the DOCKER_HOST env variable.

```
$ sudo docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

but this works fine when just running `docker ps`. How can I get sudo to connect to the daemon properly?

Thanks for all the help.

**Comment by mattoni** [comment] 2017-09-29 17:40
Ah, if I run it like `sudo -E docker ps` it finds it. However it's still giving me the same issue even running as root :/

**Comment by sunilmut** [comment] 2017-10-04 17:24
Can you describe your setup a bit more in detail or preferably, repro steps?

**Comment by mattoni** [comment] 2017-10-06 02:46
So it turns out that trying to bind a socket directly into the windows file system like so: 
`docker run --rm -it -v c:/Users/matto/Downloads:/var/run/test sock-server`

 causes the issue, whereas just mounting it like this:
`docker run --rm -it -v ${PWD}/test:/var/run/test sock-server`

 causes no issues. However, I cannot locate the file it creates. Is it in some virtual file system? I need to have access to the files my container creates for various purposes, but I think this will work.

**Comment by mattoni** [comment] 2017-10-06 21:28
Also, this storage does not appear to be persistent. I receive authorization key files through the socket and those don't persist through restarting the docker client. That may not be a BashOn Windows issue, but it's worth noting in case anyone has an explanation on that.

**Comment by mas-dse-gargote** [comment] 2017-10-18 15:53
If I'm understanding this correctly, Docker running is a service on Windows and you're trying to connect using the Docker Client from Bash and on the same host machine. Since Docker Machine itself isn't running via Bash, the Unix file isn't available for you to read like (unix:///var/run/docker.sock), you'll want to tell your client to use TCP, probably through port 2375 (default). 
Try 
`
export DOCKER_HOST="tcp://0.0.0.0:2375"
`
Add this to your .bashrc if you want to keep using the docker client through bash.

**Comment by mattoni** [comment] 2017-10-23 18:41
I've never had trouble accessing the Docker host from bash on windows. My issue is I have no idea what's happening to my mounted volume. Every time I restart the windows docker daemon, my mounted volume (where I'm binding the socket) is reset. I store some authentication info there and it disappears. So I guess I'm trying to figure out when I mount a /mnt/* volume, where does it actually go?

**Comment by Rainbowlemon** [comment] 2017-11-08 14:29
@mattoni Did you get any further with this? I'm running into the same problems you've had at the moment on a project I'm starting on:

    ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

`env | grep DOCKER_HOST` returns the correct env variable:

    DOCKER_HOST=127.0.0.1:2375

It looks like the same issue with sudo ignoring environment variables...

**Comment by mattoni** [comment] 2017-11-09 17:33
@Rainbowlemon I ended up not needing sudo, but I got it working by copying the config into the sudo settings. `sudo` uses a different setup file than your regular user.

Still have to go through the painstaking issue of reconfiguring my volumes  mounted under /mnt any time the docker client restarts. Anyone have any idea on why the volumes aren't persistent?

**Comment by shinercan** [comment] 2018-02-11 12:32
I get the same issue:
Can't start server : Bind on unix socket: Operation not permitted

logs:
 Starting MySQL 5.7.21-1.1.3
2018-02-11T12:27:13.850102Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-02-11T12:27:13.855011Z 0 [Note] mysqld (mysqld 5.7.21) starting as process 1 ...
2018-02-11T12:27:13.867804Z 0 [Note] InnoDB: PUNCH HOLE support available
2018-02-11T12:27:13.867877Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-02-11T12:27:13.867954Z 0 [Note] InnoDB: Uses event mutexes
2018-02-11T12:27:13.868025Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-02-11T12:27:13.868078Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
2018-02-11T12:27:13.868152Z 0 [Note] InnoDB: Using Linux native AIO
2018-02-11T12:27:13.868436Z 0 [Note] InnoDB: Number of pools: 1
2018-02-11T12:27:13.868604Z 0 [Note] InnoDB: Using CPU crc32 instructions
2018-02-11T12:27:13.869992Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2018-02-11T12:27:13.878197Z 0 [Note] InnoDB: Completed initialization of buffer pool
2018-02-11T12:27:13.880039Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-02-11T12:27:13.928468Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2018-02-11T12:27:14.047248Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-02-11T12:27:14.047416Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-02-11T12:27:14.049365Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-02-11T12:27:14.209140Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-02-11T12:27:14.219025Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2018-02-11T12:27:14.219241Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2018-02-11T12:27:14.220368Z 0 [Note] InnoDB: 5.7.21 started; log sequence number 2552443
2018-02-11T12:27:14.220549Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2018-02-11T12:27:14.220875Z 0 [Note] Plugin 'FEDERATED' is disabled.
2018-02-11T12:27:14.269780Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2018-02-11T12:27:14.269970Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2018-02-11T12:27:14.273602Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180211 12:27:14
2018-02-11T12:27:14.276170Z 0 [Warning] CA certificate ca.pem is self signed.
2018-02-11T12:27:14.276567Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2018-02-11T12:27:14.278591Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2018-02-11T12:27:14.278690Z 0 [Note] IPv6 is available.
2018-02-11T12:27:14.278777Z 0 [Note]   - '::' resolves to '::';
2018-02-11T12:27:14.278847Z 0 [Note] Server socket created on IP: '::'.
2018-02-11T12:27:14.287409Z 0 [ERROR] Can't start server : Bind on unix socket: Operation not permitted
2018-02-11T12:27:14.287586Z 0 [ERROR] Do you already have another mysqld server running on socket: /var/lib/mysql/mysql.sock ?
2018-02-11T12:27:14.287655Z 0 [ERROR] Aborting

2018-02-11T12:27:14.287733Z 0 [Note] Binlog end
2018-02-11T12:27:14.287872Z 0 [Note] Shutting down plugin 'ngram'
2018-02-11T12:27:14.287909Z 0 [Note] Shutting down plugin 'partition'
2018-02-11T12:27:14.288004Z 0 [Note] Shutting down plugin 'BLACKHOLE'
2018-02-11T12:27:14.288039Z 0 [Note] Shutting down plugin 'ARCHIVE'
2018-02-11T12:27:14.288071Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2018-02-11T12:27:14.288193Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2018-02-11T12:27:14.288226Z 0 [Note] Shutting down plugin 'MyISAM'
2018-02-11T12:27:14.288277Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2018-02-11T12:27:14.288335Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2018-02-11T12:27:14.288366Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2018-02-11T12:27:14.288436Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2018-02-11T12:27:14.288471Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2018-02-11T12:27:14.288497Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2018-02-11T12:27:14.288522Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2018-02-11T12:27:14.288577Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2018-02-11T12:27:14.288608Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2018-02-11T12:27:14.288633Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2018-02-11T12:27:14.288689Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2018-02-11T12:27:14.288719Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2018-02-11T12:27:14.288779Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2018-02-11T12:27:14.288813Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2018-02-11T12:27:14.288875Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2018-02-11T12:27:14.288900Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2018-02-11T12:27:14.288989Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2018-02-11T12:27:14.289025Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2018-02-11T12:27:14.289045Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2018-02-11T12:27:14.289107Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2018-02-11T12:27:14.289148Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2018-02-11T12:27:14.289208Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2018-02-11T12:27:14.289242Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2018-02-11T12:27:14.289277Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2018-02-11T12:27:14.289350Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2018-02-11T12:27:14.289381Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2018-02-11T12:27:14.289442Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2018-02-11T12:27:14.289498Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2018-02-11T12:27:14.289587Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2018-02-11T12:27:14.289632Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2018-02-11T12:27:14.289657Z 0 [Note] Shutting down plugin 'InnoDB'
2018-02-11T12:27:14.289787Z 0 [Note] InnoDB: FTS optimize thread exiting.
2018-02-11T12:27:14.289950Z 0 [Note] InnoDB: Starting shutdown...
2018-02-11T12:27:14.390411Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2018-02-11T12:27:14.404192Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 180211 12:27:14
2018-02-11T12:27:16.024054Z 0 [Note] InnoDB: Shutdown completed; log sequence number 2552462
2018-02-11T12:27:16.028942Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2018-02-11T12:27:16.029057Z 0 [Note] Shutting down plugin 'MEMORY'
2018-02-11T12:27:16.029121Z 0 [Note] Shutting down plugin 'CSV'
2018-02-11T12:27:16.029145Z 0 [Note] Shutting down plugin 'sha256_password'
2018-02-11T12:27:16.029159Z 0 [Note] Shutting down plugin 'mysql_native_password'
2018-02-11T12:27:16.029332Z 0 [Note] Shutting down plugin 'binlog'
2018-02-11T12:27:16.033047Z 0 [Note] mysqld: Shutdown complete

**Comment by uzillion** [comment] 2018-07-13 07:58
Run bash with administrative priveledges. You can either do this by right-clicking bash/ubuntu, and then run by administrator; or by CTRL+SHIFT and then double clicking bash.

After that run `sudo dockerd`. This worked for me. The terminal will be running the docker process, so you'll need to start another terminal to work.

**Comment by Almenon** [comment] 2019-01-02 05:20
> Run bash with administrative priveledges. You can either do this by right-clicking bash/ubuntu, and then run by administrator; or by CTRL+SHIFT and then double clicking bash.

When I try right clicking bash in the start menu there is no run as admin option.

https://puu.sh/Cqqav/17cf77cd89.png

And control-shift results in this error:

C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuOnWindows_1804.2018.817....\ubuntu.exe

The request is not supported.

**Comment by Biswa96** [comment] 2019-01-02 18:21
In build 18305, `dockerd` can bind with unix socket but can't bind with TCP socket. This issue is closed.

**Comment by Biswa96** [comment] 2019-01-02 18:22
@therealkenc may be dupe of # 85.

**Comment by ram0973** [comment] 2021-04-17 20:29
Instructions for installing systemd and docker in WSL2 (and this is native docker, netstat, nmap and other delights):
0) (May be skipped) wsl --set-default-version 2
1) We convert our wsl1 to wsl2, if this has not been done yet, I have it wsl --set-version Ubuntu 2
2) update the kernel (download the wsl_update_x64.msi file from MS)
3) go to wsl, put the script https://github.com/damionGans/ubuntu-wsl2-systemd-script
4) exit, do wsl -t ubuntu
5) go to wsl, install the docker, do sudo usermod -aG docker $ USER, in /etc/docker/daemon.json write {"hosts": ["unix: ///var/run/docker.sock", " tcp: //127.0.0.1: 2375 "]}
6) re-login and restart docker, profit

**Closed** 2021-04-20 00:16 UTC
Labels: need-repro
