### ISSUE TITLE
Unable to obtain configuration from: 'System.String'.

### ISSUE THREAD

**Issue by ChristianBirkenmaier** [microsoft/WSL#7616] opened 2021-10-28 11:29 UTC
### Version

Microsoft Windows [Version 10.0.19043.1288]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 20.04

### Other Software

Docker version 20.10.8, build 3967b7d
.Net mcr.microsoft.com/dotnet/sdk:5.0.103-buster-slim-amd64

### Repro Steps

- start our docker service, which runs a dotnet5 web app inside the backend container

### Expected Behavior

The application connects successfully to the microsoft oidc login service, which returns our valid user

### Actual Behavior

Sometimes (~80% of the time) the website responds with the attached error message. This error message will be displayed again and again, until eventually the service seems to have successfully conntected to the ms oidc login service. The time needed for the connection to successfully resolve spans from a few to up to 15 minutes, it is unclear what changes that leads to a then successful connection. This issue is only appearing under wsl, on a clean ubuntu installation it has never appeared, also none of my collegues (all using linux) know of this error.

### Diagnostic Logs

![unhandled_exception](https://user-images.githubusercontent.com/15781121/139246046-c479e475-f608-4977-a0a5-6b02ee7d93a8.PNG)

**Comment by OneBlue** [comment] 2021-11-09 23:44
Hi @ChristianBirkenmaier, thanks for reporting this.
There's not enough information to root cause this issue. I'd recommend investigating what's causing this error inside OpenId.

I'll close this issue for now, feel free to reopen it if you find that the root cause is a WSL issue.

**Closed by OneBlue** 2021-11-09 23:44 UTC
