### ISSUE TITLE
No installed distributions when there are indeed distros installed

### ISSUE THREAD

**Issue by notlaforge** [Microsoft/WSL#3244] opened 2018-05-25 18:17 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.1]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

bash.exe

* What's wrong / what should be happening instead:

My pre-existing debian installation should open. Instead, I get the "you don't have any distros installed, go to this url and get one" message.

Installing any other distro fixes it, and it even leaves my previous distro as the default one. I can then un-register the additional distro, and things continue to work until next time (can't quite pin down what triggers it).

**Comment by sirredbeard** [comment] 2018-05-25 20:47
Are you installing using lxrun or from the Microsoft Store?
The method of installing [changed](https://docs.microsoft.com/en-us/windows/wsl/install-win10) but a lot of third party documentation with the old method is still out there.
I have found if you mix and match install methods it can cause some unusual behavior.

**Comment by notlaforge** [comment] 2018-05-25 20:49
Both distros (Debian which I use normally and Kali that I install to fix things) are from the store.

**Comment by scooley** [comment] 2018-05-28 05:35
@notlaforge - what's the output for wslconfig.exe?

**Comment by notlaforge** [comment] 2018-05-29 16:52
```
C:\Users\jordi>wslconfig /list /all
Windows Subsystem for Linux Distributions:
Debian (Default)

C:\Users\jordi>
```

Whenever I install Kali to bring Debian back I unregister it, so right now it's only Debian there.

**Comment by Biswa96** [comment] 2018-05-29 17:09
You can install both. Just use `wslconfig /s distro_name` to make it default distro.

**Comment by benhillis** [comment] 2018-06-01 00:30
I am fairly certain that this is a duplicate of #2576.

**Comment by pfaffle** [comment] 2018-06-09 00:57
I was observing this same issue, but the workaround described in #2576 (restarting the lxssmanager service) fixed it for me.

**Comment by benhillis** [comment] 2018-06-11 16:21
Cool thanks for confirming.

**Comment by benhillis** [comment] 2018-06-11 16:21
Oh sorry, you're not OP.

**Comment by benhillis** [comment] 2018-06-28 21:37
@notlaforge - If restarting the lxssmanager service does not fix the issue, please reopen.

**Closed by benhillis** 2018-06-28 21:37 UTC

**Comment by ygale** [comment] 2018-07-16 05:02
I experienced this issue, and worked around it in a simpler way:

The output of `wslconfig /l` was

    Windows Subsystem for Linux Distributions:
    Ubuntu (Default)

but no distribution was found when I ran `bash.exe`.

I then ran `wslconfig /s Ubuntu` (even though Ubuntu was already reported as the default), and after that `bash.exe` succeeded.

**Comment by Nadav-Ruskin** [comment] 2018-07-26 06:20
Thank you @ygale!

**Comment by saifalfalah** [comment] 2018-10-28 08:45
@ygale Worked for me too!

**Comment by mdnpascual** [comment] 2018-11-13 16:32
I got this error after installing python 3.7 while having ubuntu installed before in win 10. Running @ygale solution fixed it for me. Thanks!

**Comment by CngKO** [comment] 2019-02-22 06:55
You can also run the following commands to restart the linux subsystem manager using CMD as an **administrator**:

```
net stop LxssManager
net start LxssManager
```

**Comment by wollip** [comment] 2019-02-25 18:19
I had the same issue. Restarting the computer also worked.

**Comment by cnc-bdibene** [comment] 2020-07-12 19:54
The distros are installed into your Windows user profile (not the system profile) so you won't get accurate results if you run
`wslconfig /l` from either cmd-asAdmin or powershell-asAdmin.
When running those shells 'as Admin', they're not running in your same user space, so the results will be different.

Also reboot after the initial WSL install, or some files might not be registered before you try to access them.

**Comment by Lftobs** [comment] 2023-06-01 13:25
I had same issue..... later fixed it by installing a lower version of wsl extension on vscode
