### ISSUE TITLE
Unable to open VSCode from WSL

### ISSUE THREAD

**Issue by aedryan** [microsoft/WSL#8183] opened 2022-03-24 18:14 UTC
### Version

10.0.22581.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu  20.04

### Other Software

VSCode 1.65.2
VSCode Remote - WSL v0.64.2

### Repro Steps

Open a Windows Terminal into WSL, enter the command "code ."  

### Expected Behavior

Opens VSCode on my host machine.  

### Actual Behavior

Does nothing, command just hangs indefinitely.  

### Diagnostic Logs

Prior to updating to the win11_22581.1 ni_release, when I used "code ." in WSL it opened VSCode in an elevated Windows Terminal and gave me a permission error in a non-elevated terminal.  Now the command does nothing in both.

**Comment by DoctorWho8** [comment] 2022-03-24 23:32
I'm not sure if this is related, but I have the same problem for bringing up VSCode from an arrangement of Slackware under WSL. But it works elsewhere.

**Comment by Biswa96** [comment] 2022-03-25 04:25
Please provide the logs as mentioned here https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md

**Comment by fatihkabakk** [comment] 2022-03-25 10:39
@aedryan If you have installed vscode inside the wsl, then you should uninstall it and install vscode in your host (windows) machine. Then restart the wsl and try again. Also, vscode remote should be automatically downloaded and installed. So, no manual steps shall be required.

**Comment by aedryan** [comment] 2022-03-25 14:13
> Please provide the logs as mentioned here https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md

Thanks, I went to do this and suddenly it started working again, I'm confused but this may not be an issue or whatever state I managed to get my system in that caused the issue eludes me.  

> @aedryan If you have installed vscode inside the wsl, then you should uninstall it and install vscode in your host (windows) machine. Then restart the wsl and try again. Also, vscode remote should be automatically downloaded and installed. So, no manual steps shall be required. **Important:** Vscode in wsl is only available in terminal, not in any vnc applications.

VSCode is installed on my host machine.  I already had VSCode and the remote extension installed, this happened after a Windows upgrade.  I was indeed invoking this from Windows Terminal.

**Comment by oaklandcorp-jkaiser** [comment] 2022-03-25 14:42
I believe I run into the same issue on a daily basis. During my daily development routine (running Windows Terminal, GIT, Minikube, Lens IDE, VS Code, and Docker) I'll run into a system state where certain actions (`code .`, `get fetch -ap`, `explorer.exe $(wslpath -w .)` to name the most common ones) just hang indefinitely through the shell. When I discover this hanging for any single command it is a clue the whole system is in trouble. Previously WSL issues (a month or two prior) were resolved with a `wsl --shutdown` but now things get so stuck I need to do a full system reset to resume using the Linux half of my computer. Based on the timing I'd guess the progression of this issue came from swapping to the Windows Store version of WSL.

Here are a few system details if it helps provide a focus.

```
C:\Users\user>cmd.exe --version
Microsoft Windows [Version 10.0.22000.556]
```

```
user@user:~$ uname -a
Linux user 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
C:\Users\user>winget list
Name                              Id                                Version           Available    Source
---------------------------------------------------------------------------------------------------------
Docker Desktop                    Docker.DockerDesktop              4.6.1                          winget
Windows Terminal                  Microsoft.WindowsTerminal         1.12.10393.0                   winget
Windows Subsystem for Linux Prev… MicrosoftCorporationII.WindowsSu… 0.56.2.0
Microsoft Visual Studio Code      Microsoft.VisualStudioCode        1.65.2                         winget
Windows Subsystem for Linux Upda… {8BC9BA1B-F6F3-471D-8773-5283F0C… 5.10.60.1
Windows Subsystem for Linux WSLg… {E04B0005-A349-4BCC-9662-CA01320… 1.0.26
```

I'll follow this issue and if @aedryan is unable to reproduce it I could always create a new issue with details from what I've seen.

**Comment by aedryan** [comment] 2022-03-25 15:26
I can vouch for having Docker running in my configuration when the issue is reproduced as well as making use of WSLG.

**Comment by mlohstroh** [comment] 2022-03-25 17:00
I am running into this issue daily it seems. 
Here is a link to my strace output when running the command.  https://gist.github.com/mlohstroh/c0f6a9325377069a0fb18027e8c49894

The reverse also happens where I cannot access the WSL filesystem when trying to go through the network drive that WSL makes for the windows side.

So this is much bigger than just vscode. It's really not allowing any cross OS file system interaction to happen.

**Comment by oaklandcorp-jkaiser** [comment] 2022-03-25 17:05
I would agree with @mlohstroh. It feels a problem generalized to networking between the systems. Local programs in WSL continue to work (`nano` for example) but any program that calls between the systems seems to hang indefinitely. The last time my system got in this state I tried accessing `\\wsl.localhost\home` from Windows explorer and it became unresponsive. Interestingly enough I was able open VSCode through the Windows search and view + change files within WSL while the system was in this broken state.

**Comment by aedryan** [comment] 2022-03-25 17:09
Sorry if this is off topic for this issue but if it is indeed more generalized I thought it might be worth describing.  Since updating to win11_22581.1 ni_release I have gotten my system into such a state that I cannot access WSL at all and even gotten into a state where running `wsl --shutdown` locked up my system entirely.  I was able to recover with a reboot in both instances.

**Closed** 2022-04-19 22:04 UTC
