### ISSUE TITLE
wslpath doesn't resolve symlinks

### ISSUE THREAD

**Issue by vlovich** [microsoft/WSL#4583] opened 2019-10-08 19:52 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.356]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
ln -s /mnt/c/Users/vlovich/Downloads ~/Downloads
wslpath -w ~/Downloads

* What's wrong / what should be happening instead:
Expect it to resolve to C:\Users\vlovich\Downloads\
Instead I get \\wsl$\Ubuntu\home\vlovich\Downloads

This causes a bunch of issues since "Downloads" appears as a regular file under \\wsl$ and no Windows apps can open the files.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by xtremeperf** [comment] 2019-10-14 03:00
Build 18945 included a bug fix:

> - Fix wslpath to properly resolve symlinks, this was regressed in 19h1 [GH 4078]

**Comment by xtremeperf** [comment] 2019-10-14 03:09
I just tried to reproduce up against 18999 using the repro steps you provided, and it does appear to have been fixed.  I got "C:\Users\<username>\Downloads"

**Comment by craigloewen-msft** [comment] 2019-10-14 23:27
@vlovich I'll close this out since it seems to have been resolved. Please update and try again, and if you find the issue still persists please reopen this issue. Thank you for filing this!

**Closed by craigloewen-msft** 2019-10-14 23:27 UTC
