### ISSUE TITLE
Can't set different font for the terminal

### ISSUE THREAD

**Issue by trainto** [Microsoft/WSL#757] opened 2016-08-04 07:22 UTC
When I change font via setting menu of Bash on Ubuntu on Windows terminal, it's applied. But close the terminal and relaunch it, then it goes to default font. However in case of background colour setting, it keeps what I set before.

Is ther anyone who went through this situation?

**Comment by clarkzjw** [comment] 2016-08-04 11:23
@trainto It seems current build has this problem indeed.

However, you can use some third party tools like [ConEmu](https://conemu.github.io/). The latest version of ConEmu can use bash on Windows out-of-box. And it comes with tons of configurations as you can imagine, fonts and themes setting of course.

![image](https://cloud.githubusercontent.com/assets/2663319/17400086/92cefc96-5a78-11e6-8421-0b7f0df7f6a2.png)

**Comment by onomatopellan** [comment] 2016-08-04 11:27
I changed yesterday the font of Bash on Ubuntu on Windows to DejaVuSansMono.ttf and today font is still applied.
Could it be you changed it while being in an admin bash and now the normal bash doesn't apply the change?

**Comment by clarkzjw** [comment] 2016-08-04 11:35
@onomatopellan Whether I change the font in an admin bash or a normal bash, the font falls back to default as long as I open a new bash console.

I changed fonts via: Right click on the title bar -> Properties -> Font.

**Comment by onomatopellan** [comment] 2016-08-04 12:14
Correct, I did it same way. It's a clean install too?

**Comment by clarkzjw** [comment] 2016-08-04 13:04
@onomatopellan Well, it's not. I upgraded from Windows 10 version 1511.

Maybe that is the reason?

**Comment by onomatopellan** [comment] 2016-08-04 13:35
It could. Old CMD version stored changes on registry and they could conflict with the new CMD. You can try to right click title bar -> enable Defaults and try again.

The Ubuntu guy also explained how he had to use regedit to install Ubuntu font in old CMD versions.
http://blog.dustinkirkland.com/2016/04/howto-ubuntu-on-windows.html

**Comment by clarkzjw** [comment] 2016-08-04 14:18
Well, maybe I know the reason why.

There are two ways to open bash.

1. Press Win + R, enter "cmd.exe" then press enter, and enter "bash".
2. Click Windows search, enter "bash" and then enter.

Method 1 launches bash within from cmd.exe, while method 2 launches bash.exe directly( Correct me if I am wrong ). You can set fonts in both methods, but method 1 keeps your setting and method 2 loses.

So it seems method 1 sets fonts for cmd.exe while method 2 sets fonts for bash.exe. I was using method 2 all the time. And the font config keeps losing. I tried method 1 just now, and the font config keeps.

**Comment by onomatopellan** [comment] 2016-08-04 14:21
I can confirm that. CMD didn't apply DejaVu font like bash did.

**Comment by bitcrazed** [comment] 2016-08-10 01:13
@clarkzjw Could I ask you to repro the following steps:

1. Upgrade to Win10AU
2. Open cmd from the start menu (non-elevated). Set its font to Consolas
3. Close cmd window
4. Reopen the cmd window from the start menu (non-elevated). It should have the same font as selected in 2.

Note that if you run Win + R -> cmd, you're running cmd.exe, which has a different set of properties to the shortcut used by the start-menu when you find and open the console from the start menu.

And if you open cmd or Command Line (start menu tile) or PowerShell and THEN run bash from within that console, Bash's font properties aren't used - just the fonts preferred by the console you first opened.

+ @zadjii-msft & @paulcam206 for visibility 😉

**Comment by clarkzjw** [comment] 2016-08-10 01:27
@bitcrazed Exactly. I just followed your step. It seems the `Command Prompt` in Step 2 and `cmd.exe` via Win + R are different. I didn't noticed that before. Are they different before Win10AU?

**Comment by zadjii-msft** [comment] 2016-08-24 22:10
@clarkzjw `cmd.exe` and `Command Prompt` are the same thing, but they are loaded slightly differently, so they each have separately stored properties (it's confusing, but legacy, behavior).

Changing the properties on a bash window launched from the start menu (Win Key -> "bash") should persist the properties, but again, separately from the properties of Win Key + R -> "bash".

Perhaps you're setting the "Defaults" and not the "Properties"? These are again, different (and complicated for legacy reasons),  and in my experience, changing the "Properties" is the option you always want.

**Comment by clarkzjw** [comment] 2016-08-25 00:33
@zadjii-msft Well, things become more interesting after some additional tests.

First, I am pretty sure I am editing `Properties`, not `Defaults`. If I use `Win Key -> "bash"` to launch a bash window, and change the fonts in `Properties`. and type `exit` to close and reopen in the same way. I tried some different fonts, it seems some fonts can persist while some cannot. 

But if I use `Win Key + R -> bash` to launch a bash window, and change font settings, in my tests, all fonts can persist, including the fonts failed in  (Win Key -> "bash") case. 

It's quite interesting. I am not sure if this is what you mean `they are loaded slightly differently`.

**Comment by LeonYang5114** [comment] 2016-09-09 07:26
I think the difference is due to **using shortcut or not**, but not depends on using cmd or not.
You can go to `system32` and double click the `bash.exe` instance, and it behaviors exactly the same as opening it through `cmd`. But when you use shortcut, it's different. (at least for me)

By different I mean both the font as and a coloring issue. This is the `PS1` I am using:
```
\n${debian_chroot:+($debian_chroot)}\[\033[38;5;226m\]\u\[$(tput sgr0)\]\[\033[38;5;39m\]@\[$(tput sgr0)\]\[\033[38;5;46m\]\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;87m\]\w\[$(tput sgr0)\]\[\033[38;5;28m\]\\$
```
It seems that only the bash launched through shortcut could display the color of the PS1 correctly. That's why I want to fix the font problem when using the Win Key + bash (shortcut) way to launch bash.

**Comment by zadjii-msft** [comment] 2016-09-12 15:27
@clarkzjw That's strange to me. I'm gonna ping @bitcrazed and @paulcam206 (who has a bit more experience with the properties loading) to see if we can't triage this 

@LeonYang5114 Are the colors on the "Colors" properties tab the same for both your bash.exe shortcut and launching it from Win+R the same? This is a bit of what I meant by `they are loaded slightly differently` - Launching from the shortcut stores the properties in the shortcut itself which the shortcut reads on future relaunches, while launching from Win+R launches the exe directly, reading&writing the properties from the registry. 

Because the console doesn't support 256-color in the AU, `\033[38;5;226m` will get translated into the nearest color in the color table to color 266, so if you have different color tables, it will get translated differently depending on what's available. You can see #76 for more on this.

**Comment by gurnec** [comment] 2016-09-13 21:55
FWIW I just ran into what I believe is a general Windows console bug which I at first thought was WSL related, but no longer do. I'm just pointing it out on the off chance it's being encountered by anyone watching this issue.

To reproduce (on Win10AU):

1. Open the font properties (via any method), change the font size to something that's *not* in the font size list (e.g. 15) by typing it into the provided edit box, OK out. (The size will change as expected.)

2. Open the font properties again. You'll see that 15 has been added to the font size list and it's pre-selected. Leave it alone, choose a different font, and OK out. The font *should* change as requested, however it doesn't (and the new setting isn't persisted).

For whatever reason, if that 15 temporarily added to the list box remains selected, font changes are ignored.

The workaround is to ensure the 15 in the list box isn't selected before OKing out, either by selecting a different size or by entering 15 in the edit box.

My apologies for the noise it this is unrelated...

**Comment by spivoler** [comment] 2016-09-18 20:35
Hi Guys, 

I am having exactly the same problem. The only thing I wanted to do is to use font consolas and save it as default. That used to work until after I install language package (Simplified Chinese). After that, the default font is always a Chinese font. I can manually change the font of current bash, while the setting cannot be saved for future usage...

It would be good to have the bug fixed asap. Appreciate it.

**Comment by mchenzero** [comment] 2016-10-07 09:19
I have this same issue too. I figured that this may only happen to Asian installations.

Asian installations have different fonts available for use in a console session window than non Asian installations. (See the explanation [here](http://superuser.com/a/584598/649442).)

While, for example, _Consolas_ is available for use in console for non Asian installations (yes?), it is not shown in the font list of _Command Prompt_'s properties setting window. However, it **is** shown and usable in _Bash on Ubuntu on Windows_.

I found that for any fonts shown in _Command Prompt_'s font list, for example _MS Gothic_, the setting on _Bash on Ubuntu on Windows_ could persist. (A shortcut need to be used as pointed out by @LeonYang5114.) But for any fonts not shown in _Command Prompt_'s font list, the font setting on _Bash on Ubuntu on Windows_ only works for the current session. However, if we right click and see properties of the shortcut, we can see that font setting has actually been saved.

**Comment by bitcrazed** [comment] 2016-10-10 18:19
@all: There are several nuances to how and where console apps get their settings from when launched directly, via start-menu tiles, and via shortcuts / pinned apps. We'll be writing-up a blog post on this v. soon.

For now, remember:

1. If you run a console app directly (e.g. via [Win] + [R] -> console app), its settings are pulled from the registry. If there are no pre-existing settings configured for a console app, its settings are initialized from the console **defaults**.
2. If you launch a console app from a shortcut or tile, the settings for that app are pulled from the shortcut/tile. If you create your own pinned links to apps, each pinned link can have it's own font, colors, etc.
3, If you make changes to the settings of a system-managed .lnk / shortcut / start menu tile / [Win] + [X] menu item, your settings will be restored to defaults each time you upgrade to a new OS build.

In the screenshot below, you'll notice that the two bash consoles, started via different means, have different fonts:
![image](https://cloud.githubusercontent.com/assets/961950/19246428/2cf5a752-8edb-11e6-99a8-4a759daff916.png)

Same app. Same ConHost terminal, different settings due to different start-mechanisms. This can be a very useful feature if you want to create terminals with different settings for different tasks.

**Comment by ryanerwin** [comment] 2016-10-29 07:54
@bitcrazed,

It's been 19 days since you posted, and I hope your blog post is coming soon.

Still don't understand HOW to change the font when launching it via a Live Tile or Pinned app? Strange that it would be different from launching via a shortcut...

**Comment by afinnell** [comment] 2016-10-29 13:57
@ryanerwin Personally I recommend ALWAYS launching it via a Shortcut. The best way I've found is to Right click on the Start Menu shortcut, Pin to Taskbar, then change those properties. Bash for Windows for Ubuntu (i.e. bash.exe.) needs to Run As Administrator anyways, which can only be done via a shortcut. If it isn't Run As Administrator so many things do not work.

**Comment by willise** [comment] 2016-10-29 15:46
@bitcrazed Very looking forward to your post.

**Comment by ryanerwin** [comment] 2016-10-30 03:55
@afinnell

Besides ping (which I replace with httping) what else doesn't work without bash.exe being run as administrator? I can't stand that full screen warning each time I launch an app confirming it requires admin access, and I don't want to disable UAC (doesn't sound like a good idea)... 

Must admit that it's very strange basic things like mklink can fail in cmd.exe when you're not running with administrator access...

**Comment by sunilmut** [comment] 2016-10-31 17:55
@afinnell @ryanerwin - The requirement of admin privileges for ping is only true for the Windows Anniversary update build. In the Windows Insider build, starting build 14926 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)), ping no longer requires admin privileges. We are not aware of any other tool that requires admin privileges, other than performing an operation that natively requires admin privileges on Windows.

**Comment by zadjii-msft** [comment] 2016-11-01 14:43
Just as a follow up: @bitcrazed has been swamped with other bureaucratic nonsense for a couple weeks now. We really do want to get a blog post out, but its still just a draft at the moment. We've all been pretty preoccupied with other higher priority tasks.

When BoUoW is installed, it creates a start menu shortcut (the one with the Ubuntu logo). This is what can be used for the tile as well. Because it's a shortcut, it maintains it's own property set, which is part of the .lnk itself, and only uses the registry for things that aren't in the .lnk. 

You can view and edit the console properties for the bash.exe shortcut by right clicking on the tile/shortcut, then right clicking on "Bash on Ubuntu on Windows", then viewing the console tabs (Colors, Font, Layout, Options)that show up in that dialog,  Or by right clicking the title bar of the BoUoW console and clicking properties, and using that dialog.

If any properties aren't persisting there, then that's definitely a bug. I'll look into the font issues mentioned by @gurnec (and others) today. There was some issue about certain settings not persisting if they were set to the same as the defaults that was fixed by @miniksa a couple weeks ago, but this sounds different. I'm tracking this with MSFT:9615358

**Comment by zadjii-msft** [comment] 2016-11-01 23:02
I believe @gurnec found it. I'd love if @clarkzjw and @trainto could reply back with the font size you guys have selected. I'll work on fixing the root cause of that issue, but I believe that's why your fonts aren't persisting, but your colors will. If I'm not mistaken, your preview window doesn't update as you select different fonts, correct?

If that is indeed the problem, then the workaround is just pick a different font size. 
<hr>
Some people were also discussing that there are different fonts in the list depending on whether the properties are for bash vs Command Prompt. I believe the list is populated based on the currently active codepage for the console window. You can see that in the options tab, or from cmd.exe, `mode` will print your codepage. @spivoler, @mchenzero, could you confirm that your codepage is different for bash vs cmd.exe? I believe also that running (in cmd) `mode con:cp select=65001` will enable all the fonts you see in bash.exe.

**Comment by gurnec** [comment] 2016-11-01 23:09
@zadjii-msft FYI the font preview wasn't updating for me under those circumstances.

**Comment by clarkzjw** [comment] 2016-11-02 14:59
@zadjii-msft I'm sorry but I am currently not using Windows 10 because of some work reasons. So I cannot reproduce my previous issues anymore. :(

**Comment by ryanerwin** [comment] 2016-11-19 02:50
@zadjii-msft 

For me, that's not quite the situation... Note that I'm using the English build of the anniversary update, but with Pinyin as my default input method.

If I do Start > Run > "bash.exe", select Properties and try to choose a font, I'm able to choose Ubuntu Mono.
If I do Start > Run > "cmd.exe", select Properties and try to choose a font, only a handful of asian fonts are available (MS Gothic, Raster Fonts, SimSum-ExtB, 仿宋, 黑体, 楷体, 新宋体).

**Comment by zadjii** [comment] 2016-11-19 03:00
@ryanerwin I'd suggest looking at the codepage your conhost is in. You can do this from cmd using `mode`, and iirc you can see it on the "Options" page of the Properties menu (regardless of which shell you're in). Bash.exe and cmd.exe use different codepage settings, so it's possible Ubuntu Mono isn't available for that codepage.

**Comment by ryanerwin** [comment] 2016-11-21 02:40
@zadjii

I've run `mode` under cmd.exe and I'm getting that the codepage is GB2313 (CP 936).

```
Status for device CON:
----------------------
    Lines:          9001
    Columns:        120
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      936
```

How do I run the equivilent under Windows Subsystem for Linux to see if it's using a different codepage?

I saw one open source per app locale emulator that claims to work with Windows 10, but they've got a Virus warning on the first page about it, which is quite concerning... See [https://github.com/xupefei/Locale-Emulator](url)

**Comment by miniksa** [comment] 2016-11-21 16:23
WSL is always running under codepage 65001 which is UTF-8.

The rendering engine and the property sheet asks GDI to match a font to your code page. It's probably artificially limiting the options for codepage 65001 by accident because GDI can't tell what character set worth of characters UTF-8 represents.

I've filed MSFT: 9891954 to investigate why exactly the UTF-8 codepage is causing your font choices to be restricted and remove that restriction.

**Comment by zadjii-msft** [comment] 2016-11-21 16:38
@miniksa I think it's the other way around, I believe @ryanerwin has more options with CP 65001 than with 936

**Comment by miniksa** [comment] 2016-11-21 16:46
@zadjii-msft, well that's probably expected. But either way, we currently don't have time to debate it or investigate it without an appropriately triaged bug. The bug has been filed. We'll look into it and get back to this thread when we can.

**Comment by VincentTam** [comment] 2017-01-11 14:16
Use [goreliu/wsl-terminal](https://github.com/goreliu/wsl-terminal) to customize fonts permanently.
Here I used Ubuntu Mono at size 12.

![wsl-term](https://cloud.githubusercontent.com/assets/5748535/21851782/e11d2dd0-d810-11e6-9079-1ba68c0e7913.png)

**Comment by zadjii-msft** [comment] 2017-01-11 16:38
Actually, the fix for this issue was checked into our codebase a few weeks ago, and should be on its way out to an insiders build near you soon<sup>tm</sup>. Thanks @paulcam206

**Comment by miniksa** [comment] 2017-01-20 16:12
The fix for this should be in today's Insider Build 15014.

**Comment by slgray** [comment] 2017-04-14 06:14
I have Build 16170 now. Still have the same problem as @ryanerwin has.

![console](https://cloud.githubusercontent.com/assets/1411489/25034854/35d41146-211c-11e7-9f2a-fd07003819c3.PNG)

**Comment by PaaandaChen** [comment] 2017-04-18 05:03
Same problem as @ryanerwin and @slgray, OS Build 15063. In properties while some font changes such as "新宋体", "黑体" can persist, other fonts can not. I always lose the Consolas font change

**Comment by slgray** [comment] 2017-04-18 05:43
I change my `system locale` to `English` to workaround this problem.

**Comment by PaaandaChen** [comment] 2017-04-18 08:38
@slgray My system locale is English by default, but I also installed Chinese language pack. I've also run the `mode` command under cmd.exe and my Code page is 936, will that be the problem?

**Comment by slgray** [comment] 2017-04-19 06:51
@PaaandaChen I think you should double check you `system locale`.
 When `system locale` is `China`, `Code page` is `936`,  after change it to `English (Hong Kong SAR)`, `Code page`  becomes `850`. By that change I can save font setting for `Bash on Windows`.

![cmd](https://cloud.githubusercontent.com/assets/1411489/25166561/91444172-250e-11e7-9219-d41e93ef8e87.PNG)

**Comment by Po-wei** [comment] 2017-04-26 07:39
I have ver 10.0.15063. I still have the same problem......
@slgray that solution will work but it have some side-effect...
you can see my post #1994

**Comment by ChenYangShao** [comment] 2017-06-12 14:42
Sorry, how you solved it?

**Comment by ryanerwin** [comment] 2017-06-13 06:04
@ChenYangShao 

I worked around the issue by using WSLTTY to access the terminal instead of launching it inside the traditional cmd window... See: https://github.com/mintty/wsltty

**Comment by liupengf12** [comment] 2017-07-13 03:43
@Po-wei 
I think the the issue in your post #1994 is a issue of Win10, because of application  "Command Prompt" has same problem.

I have to changed the setting of "system locale" with "English (United States) :(

**Comment by gyc990326** [comment] 2017-08-10 18:45
@liupengf12 @ryanerwin 
It seems that this issue only happens when we have multi language set in our system.
This issue has nothing to lnk or sort of that. 
**In fact, it is because that the charset of font is not inconsistent with the charset of console.** 
By default the console opens in the non-unicode codepage set in the Control Panel(936 if Chinese), so you will see that most mono fonts (including Consolas), which have changed to UTF8 codepage in Win10, **don't** show up in the properties window.
After exectuing "chcp 65001" in cmd and reopen the properties window, you can see the a bunch of fonts magically appeared there.
For Bash, it changed the charset to UTF8 afterwards, so you can see those fonts directly.
So after we changed the font without any fault and reopen bash, the conhost tried **hard** to find the usable font. Surely the font we set cannot be used for the inconsistent charset (so if your computer is slow you can notice the cmd opens more slowly and waited about 0.5~1s before it finally poped out), and silently it failed, falling back to the default font.
With the theory above, the question comes to changing the default codepage of bash.
Then after some Googling, I got a simple workround:
Add a **REG_DWORD** named "**CodePage**" with the value **65001 (decimal)** under `HKEY_CURRENT_USER\Console\%SystemRoot%_system32_bash.exe\` 
Doing this can change the default charset to UTF8, then those can be correctly loaded and used by console

**Comment by SwimmingTiger** [comment] 2017-10-06 08:23
I've been having this problem for a long time but I solved it today. I know that to solve this problem simply, I just need a font that supports CP936 like SimSun. I tried some of mixed fonts in Chinese and Western characters, but all didn't work.

But just now, I found "[Microsoft YaHei Mono](http://download.csdn.net/download/acvay/8517889)". You don't need any extra action, just install it, and then select this font in the Bash property. Then the font will never change again.

Download: [Microsoft YaHei Mono.zip](https://github.com/Microsoft/BashOnWindows/files/1362006/Microsoft.YaHei.Mono.zip)

The font = Microsoft YaHei + Consolas

----------------------------
zh_CN version （中文版）:

我被这个问题困扰很久了，不过今天终于解决了。我知道要简单的解决这个问题，我只需要找到一款像新宋体那样支持CP936字符集的字体就好。不过，我尝试过好几个中英文混合字体，但是都没有用。

直到刚才，我发现了“[Microsoft YaHei Mono](http://download.csdn.net/download/acvay/8517889)”。不需要进行任何额外的操作，只需要安装这款字体，然后在Bash的属性里面启用它就OK了。从此以后字体再也不会变成默认的了。

下载：[Microsoft YaHei Mono.zip](https://github.com/Microsoft/BashOnWindows/files/1362006/Microsoft.YaHei.Mono.zip)

该字体 = 微软雅黑 + Consolas

**Comment by southparadise** [comment] 2017-10-10 19:07
@slgray That's the solution I've been looking for!!! Thanks a lot.

**Comment by Po-wei** [comment] 2017-10-11 05:49
Does it support codepad 950(traditional Chinese)?

**Comment by Po-wei** [comment] 2017-10-11 07:11
Unfortunatelly, it seems that this font does not persist in CP950.

**Comment by licett** [comment] 2017-11-11 02:59
@SwimmingTiger You are so wonderful guy! 
I'm almost killed by this problem, and your advice really come to my rescue.

**Comment by liuluheng** [comment] 2017-11-12 01:42
use `cmder ` and type `wsl` and `Enter`. The font problem  solves perfectly

**Comment by ac-m** [comment] 2017-11-17 06:22
Bug reproduce :
1. Install Win10 1709 Simplified Chinese Version and WSL
2. Install ubuntu font :
    Download 
    http://font.ubuntu.com/download/ubuntu-font-family-0.83.zip
    Unzip ubuntu-font-family-0.83.zip
    Install font UbuntuMono-R.ttf
3. Open  shortcuts / pinned "Bash on Ubuntu on Windows", change font to "Ubuntu Mono"
4. Close and reopen "Bash on Ubuntu on Windows", the font isn't "Ubuntu Mono"
5. Right click the pinned  "Bash on Ubuntu on Windows" icon,  continue right click "Bash on Ubuntu on Windows", select "property", goto font tab, you can see the font is "Ubuntu Mono".
 
So,the change of font do persist to "Ubuntu Mono".
Maybe problem is, it can not init from font "Ubuntu Mono".

**Comment by winteryoung** [comment] 2017-12-01 05:55
Can anybody reopen this issue?

**Comment by miniksa** [comment] 2017-12-01 16:28
MSFT: 14907854 filed for additional investigation.

**Comment by winteryoung** [comment] 2017-12-02 02:19
The best way to do this is adding a fallback font. Windows has already used the system default font (in the case of East Asia) for non-ascii characters. You just need to make this setting available for users.

**Comment by miniksa** [comment] 2017-12-04 16:56
Our current rendering system in the console doesn't support font fallback.

I can work on resolving the persistence of any given font if it is not sticking, but font fallback would require a near complete overhaul of the renderer (which is on the long-term plan, but isn't a bug-size fix.)

**Comment by NyaMisty** [comment] 2017-12-07 05:02
@ac-m running from Win+R will solve that issue

**Comment by ac-m** [comment] 2017-12-08 17:41
@NyaMisty

Thx.

 I just tried it on the command line, the UbuntuMono font is OK, the SourceCodePro font is still not good.

I'm using a customized font, YaHei mixed with SourceCodePro.
It's OK.

**Comment by miniksa** [comment] 2017-12-08 17:51
I've submitted an additional fix today to this issue. It should go out to Insiders sometime in the next few weeks (probably in January since we're about to hit the holiday season in the United States).

@NyaMisty had the best explanation above of why this is happening with the console.

As an example on a Traditional Chinese system, the non-Unicode Codepage will be 950. On any console host start, it will retrieve this value from the system and then load up all your settings and preferences. It will convert the codepage to a charset (https://msdn.microsoft.com/en-us/library/cc194829.aspx) getting the CHINESEBIG5_CHARSET and submit that along with the font name preference to GDI. At that point, GDI will realize that your preferred font might not have CHINESEBIG5_CHARSET as an option and instead fallback to another font that does have CHINESEBIG5_CHARSET as an option. Then the console host startup sequence is complete and we will accept a connection from an application.

The WSL subsystem attaches to the console and immediately changes the codepage through SetConsoleCP (https://docs.microsoft.com/en-us/windows/console/setconsolecp) to 65001 (UTF-8). 65001 doesn't have a particular charset associated with it, but the console host doesn't retry your preferred font face name with GDI at the later time.

What I've done in the fix I just submitted is that we will retry setting your preferred font face name with GDI each time your codepage changes. This should mean that while when the console immediately loads, it may not choose Ubuntu Mono for the few moments when the window displays and is waiting for WSL to attach, that it will retry Ubuntu Mono when it receives the SetConsoleCP(65001) command from the subsystem and it will switch to your preferred font by the time the shell prompt comes up.

**Comment by liyuan-rey** [comment] 2017-12-15 10:37
I'm using Chinese-Simplified Win10 version 1709, I have same font issue when run  cmd.exe/wsl.exe/bash.exe/ubuntu.exe from `Start -> Run...`
After specified the codepage to 65001(0xfde9) with regedit like below, the font of terminal can be chosen and persistent.
```
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
"CodePage"=dword:fde9
```
But if run cmd.exe/wsl.exe/bash.exe/ubuntu.exe by a shortcut(*.lnk), the font of terminal fallback to Chinese font `Simsun`.

I found these information, https://msdn.microsoft.com/en-us/library/dd891330.aspx , does that means .lnk file have its own codepage information, and if we run a console application through .lnk, system will use codepage in .lnk rather than registry - `HKEY_CURRENT_USER\Console\*`?

**Comment by bitcrazed** [comment] 2017-12-15 19:19
@liyuan-rey Yes, shortcuts may contain codepage info.

**Comment by Brainor** [comment] 2018-01-19 03:15
Here's how I solve the problem, inspired by @liyuan-rey .
My situation: using Chinese-Simplified Win10 version 1709, using `Run->Bash` to invoke bash interface. The font can't be changed to Consolas permanently.
Solution: `Run->regedit`, in the path `HKEY_CURRENT_USER\Console\%SystemRoot%_system32_bash.exe`, add/modify item `CodePage->(DWORD)FDE9(65001)`

**Comment by bitcrazed** [comment] 2018-01-19 17:48
@All: As discussed above, we posted two relevant blogs on this subject:

1. [How Console and command-line app settings work](https://blogs.msdn.microsoft.com/commandline/2017/06/20/understanding-windows-console-host-settings/)
2. [The default Console colors have been updated (in current Insider builds)](https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/)
3. [Announcing the Console ColorTool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) to help you apply color themes to Console instances

The first of these blogs is likely of most interest, and we encourage you to read it through several times to make sure you grok the nuances of how Console finds and loads settings for command-line apps from the registry or from shortcuts (inc. shortcuts on the start menu, or pinned to your taskbar/desktop).

Note that the discussion about settings is orthogonal to the Console's current inability to display a broad range of international characters, symbols, and glyphs: That's an entirely different issue that we are keen to address. Please bear with us for now.

**Comment by bitcrazed** [comment] 2018-01-19 17:52
@liyuan-rey - If you modify the default codepage of cmd.exe in the registry, it'll likely be ignored when you start Cmd from a start menu or pinned shortcut because Console is reading the codepage set in the shortcut itself, and not bothering to look at the registry because shortcut settings override registry settings.

**Comment by liyuan-rey** [comment] 2018-01-22 08:49
@bitcrazed 
Yes. And I'm failing to find tools to adjust codepage settings of the shortcut, I just use [Win+R] to start the console now. 😞

**Comment by xqdoo00o** [comment] 2018-01-23 17:30
@Brainor @liyuan-rey 
in the path `HKEY_CURRENT_USER\Console\C:_Program Files_WindowsApps_CanonicalGroupLimited.UbuntuonWindows_xxxx.ubuntu.exe`,
add `CodePage->(DWORD)FDE9(65001)`
then I start `Ubuntu` directly from start menu, It's Consolas !

**Comment by bitcrazed** [comment] 2018-01-23 18:16
@xqdoo00o This should be unnecessary - when you launch a Linux/WSL Console, the codepage is automatically set to UTF-8 anyhow.

Execute the following from within your Linux instance's Console:

``` bash
$ cmd.exe /C chcp
Active code page: 65001
```

**Comment by PaaandaChen** [comment] 2018-02-01 13:19
I use the ubuntu app from windows store now, my code page is 65001 after running `cmd.exe /C chcp` command.

In default settings I can set font to consolas, but everytime I run ubuntu from windows start the font is still Chinese font `SimSun`

**Comment by xqdoo00o** [comment] 2018-02-01 14:56
@PaaandaChen  you could follow my setup I published 9 days ago。

**Comment by PaaandaChen** [comment] 2018-02-01 15:04
@xqdoo00o 
that works, many thanks to you XDDD
didn't watch this issue for a long time.

**Comment by bitcrazed** [comment] 2018-05-22 21:13
Thanks for the discussion regarding this issue. Closing for now since there are several solutions to the posted issues. 

Please open an issue on the [Console Issues repo](https://github.com/microsoft/console) if you have continued/related issues.

**Closed by bitcrazed** 2018-05-22 21:13 UTC
Labels: bug, console, fixinbound

**Comment by zhuzisheng** [comment] 2019-09-25 02:45
> Here's how I solve the problem, inspired by @liyuan-rey .
> My situation: using Chinese-Simplified Win10 version 1709, using `Run->Bash` to invoke bash interface. The font can't be changed to Consolas permanently.
> Solution: `Run->regedit`, in the path `HKEY_CURRENT_USER\Console\%SystemRoot%_system32_bash.exe`, add/modify item `CodePage->(DWORD)FDE9(65001)`

this workaround is nice. Works perfectly on my side.
Thanks a lot!

**Comment by jbonnier** [comment] 2024-08-31 05:29
How is this issue closed the problem seems to still be there on a fresh Windows 11 (23H2 Build 22631.4037) install
