### ISSUE TITLE
When installing a distribution the process fails with: "WslRegisterDistribution failed with error: 0x800706be.

### ISSUE THREAD

**Issue by IPlayZed** [microsoft/WSL#5768] opened 2020-08-16 11:14 UTC
# Environment

Windows build number: Win32NT 10.0.20190.0 Microsoft Windows NT 10.0.20190.0
Your Distribution version: Can not be verified, as distro does not launch due to installtion error.
Whether the issue is on WSL 2 and/or WSL 1: Can not be verified, as distro does not launch due to installtion error.

# Steps to reproduce

Turn on Hyper-V in feature settings -> Turn on WSL in feature settings-> Restart -> Download some distro -> Launch distro.

**WSL logs**: https://aka.ms/AA99uko

#  Expected behavior

Distro should install on system.

# Actual behavior

Installation terminates with error code 0x800706be.

**Comment by IPlayZed** [comment] 2020-08-16 12:21
**Update**
It seems like this is a bug in the preview build. 
The process worked flawlessly when rolled back to a previous build.

**Comment by ajpeacock0** [comment] 2020-08-16 19:59
Hitting same issue on Windows 10 Enterprise Insider Preview 20193.  Launching Ubuntu fails with:
```
WslRegisterDistribution failed with error: 0x800706be
Error: 0x800706be The remote procedure call failed.
```

I tried disabling the WSL feature from "Turn Windows features on or off", rebooting, turning it back on with no success.

**Comment by zanettea** [comment] 2020-08-17 14:53
I have the same issue. Looks like the lsxxmanager is crashing when the distro tries to install:

Faulting application name: svchost.exe_LxssManager, version: 10.0.20190.1000, time stamp: 0xb3740412
Faulting module name: lxssmanager.dll, version: 10.0.20190.1000, time stamp: 0xca1f91f1
Exception code: 0xc0000005
Fault offset: 0x000000000003192d
Faulting process id: 0x46e4
Faulting application start time: 0x01d674a49588d0e4
Faulting application path: C:\WINDOWS\system32\svchost.exe
Faulting module path: c:\windows\system32\lxss\lxssmanager.dll
Report Id: 5fa5be4b-5fc7-416c-bd17-24c6bc9d8f3e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by yurividal** [comment] 2020-08-18 13:46
Same problem on Insider 20190

**Comment by Loca123** [comment] 2020-08-18 15:33
I'm also having this issue. I've only managed to get WSL2 working correctly on 1 of 3 machines so far.

**Comment by rdkbrady** [comment] 2020-08-18 17:37
@Loca123 any ideas on what made it work on the one successful machine?

**Comment by Duayt** [comment] 2020-08-18 18:49
I was able to resolve the problem by cleaning up some system file using disk cleanup together with the solution from [GeorgeApostolopoulos1 in this link](https://answers.microsoft.com/en-us/windows/forum/all/wsl-is-broken/13f14e76-b5be-4daf-97ec-0e186161b3f1?rtAction=1597775956121&tm=1597775960317) 

copying from his suggestion: 
Basically he reset a number of related services, while clearing out your temporary folder, eliminates this error. you can do this by making the following .bat file on your desktop and running from there:

net stop wuauserv
net stop Cryptsvc
ren %windir%\SoftwareDistribution sdold.old
ren %windir%\system32\catroot2 crt2old.old
net start wuauserv
net start Cryptsvc

Need to give GeorgeApostolopoulos1 the credit for this

**Comment by yurividal** [comment] 2020-08-18 21:42
> I was able to resolve the problem by cleaning up some system file using disk cleanup together with the solution from [GeorgeApostolopoulos1 in this link](https://answers.microsoft.com/en-us/windows/forum/all/wsl-is-broken/13f14e76-b5be-4daf-97ec-0e186161b3f1?rtAction=1597775956121&tm=1597775960317)
> 
> copying from his suggestion:
> Basically he reset a number of related services, while clearing out your temporary folder, eliminates this error. you can do this by making the following .bat file on your desktop and running from there:
> 
> net stop wuauserv
> net stop Cryptsvc
> ren %windir%\SoftwareDistribution sdold.old
> ren %windir%\system32\catroot2 crt2old.old
> net start wuauserv
> net start Cryptsvc
> 
> Need to give GeorgeApostolopoulos1 the credit for this

Unfortunately this did not work for me. Tried running theses commands manually, tried them in a .bat file, and also used disk cleanup to clean every cleanable bit. WSL still fails to install.

**Comment by Loca123** [comment] 2020-08-18 22:54
> @Loca123 any ideas on what made it work on the one successful machine?

I've just noticed that it looks like virtualization might be off in the BIOS on the machine that has this error. Unfortunately it's remote so I'm not sure when I'll be able to get that enabled and see if it fixes anything. I'll update here after I've enabled it.

I've managed to get a second machine out of the three working properly now. That was actually a different issue, it was unable to connect to the internet. Running "Network reset" and adding "nameserver 8.8.8.8" to the resolv.conf seems to have fixed that one.

**Comment by rdkbrady** [comment] 2020-08-19 05:02
The solution @Duayt linked did not work for me either.

**Comment by benhillis** [comment] 2020-08-20 04:46
Thanks for reporting, I have identified the issue and a fix is incoming.  Change needs to make it to the rs_prerelease branch but I'm optomistic the first Insider Fast build in September will have the fix.

**Comment by dudeisbrendan03** [comment] 2020-08-20 14:44
Anything we can do in the meantime before the fix is out?

**Comment by benhillis** [comment] 2020-08-20 14:54
I would roll back to the previous insider version.

**Comment by tpjones-coder** [comment] 2020-08-24 17:08
> > Running this command solved it for me
> > ```shell
> > wsl.exe --update
> > ```
> 
> This really worked for me, thank you @aCoder2013 . I'm currently on 20197 version which also had the same problem but everything works perfectly rn.

Also worked for me too - thankyou @aCoder2013 - I'am on version 2004 20197.

**Comment by voidiak** [comment] 2020-08-24 17:25
I have encountered this error too. I tried " wsl.exe --update", it updated, but it did not resolve the error. Suddenly I realized that I did not enable virtualization in bios. After I turn on the "SVM Mode" for AMD cpu, the error is gone now.

**Comment by deepan2509** [comment] 2020-08-25 06:47
I encountered the same problem. Run the following commands this helped me sure it will help you too.

dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

wsl --set-default-version 2

wsl.exe --update

wsl --shutdown

wsl <distribution_name>

**Comment by keremnymn** [comment] 2020-08-25 15:51
> > Running this command solved it for me
> > ```shell
> > wsl.exe --update
> > ```
> 
> Can confirm this worked for me too, insider build 20197.

Thank you!!!

**Comment by radovanobal** [comment] 2020-08-26 21:00
> > > Running this command solved it for me
> > > ```shell
> > > wsl.exe --update
> > > ```
> > 
> > 
> > Can confirm this worked for me too, insider build 20197.
> 
> Thank you!!!

Did not work for me on 20197

**Comment by tpanj** [comment] 2020-08-26 21:59
On Microsoft Windows [Version 10.0.20201.1000] this helped
> wsl.exe --update

**Comment by dntfckmmnd** [comment] 2020-08-27 10:30
2004 20201.1000 Windows Feature Experience Pack 120.21600.0.0

Microsoft Windows [Version 10.0.20201.1000]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>wsl.exe --update
Проверяется наличие обновлений...
Отсутствуют доступные обновления.
Версия ядра: 4.19.128

Ubuntu 18.04 LTS - works
Ubuntu 20.04 LTS - Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706be
Error: 0x800706be ???? ??? ????????? ?????? ?????????.

**Comment by presteus** [comment] 2020-08-27 13:01
> 
> 
> Running this command solved it for me, ` insider preview 2004`
> 
> ```shell
> wsl.exe --update
> ```

This worked for me too ;)
Thanks !

**Comment by matheushent** [comment] 2020-08-28 02:27
> Running this command solved it for me, ` insider preview 2004`
> 
> ```shell
> wsl.exe --update
> ```

2004 version and OS build 20201.1000 and it solved for me.

**Comment by guilhermetod** [comment] 2020-08-29 06:44
I'm on 2004 OS build 20201.1000.

wsl.exe --update didn't work for me. Only works if I use wsl 1.

**Comment by survivant** [comment] 2020-09-01 00:45
PS C:\WINDOWS\system32> wsl.exe --update
Recherche de mises à jour en cours... Veuillez patienter
Téléchargement de mises à jour en cours... Veuillez patienter.
Installation en cours des mises à jour... Veuillez patienter
Cette modification sera effective au prochain redémarrage complet de WSL. Pour forcer un redémarrage, exécutez « wsl --shutdown ».
Version du noyau : 4.19.128
PS C:\WINDOWS\system32> wsl --shutdown
PS C:\WINDOWS\system32> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Stopped         2
  Ubuntu-18.04           Stopped         2
  docker-desktop-data    Stopped         2
  Ubuntu                 Stopped         2

I launched Docker for Windows.. but It didn't start

PS C:\WINDOWS\system32> wsl -l -v

**Comment by Oddmaniv** [comment] 2020-09-02 11:59
Build 20201.rs_prerelease.200822-1922 Not working with ubuntu, haven't tried other distros, 
>    WslRegisterDistribution failed with error: 0x800706be
>    Error: 0x800706be The remote procedure call failed.

**Comment by lachlan-smith** [comment] 2020-09-02 12:25
I noticed upon switching from regular builds to the fast track insider builds the "Receive updates for other Microsoft products when you update Windows" setting got turned off automatically. I believe this setting is required for WSL updates to be delivered automatically through Windows update, which would circumvent the need to run the `wsl.exe --update` command manually?

**Comment by guilhermetod** [comment] 2020-09-02 13:29
> I noticed upon switching from regular builds to the fast track insider builds the "Receive updates for other Microsoft products when you update Windows" setting got turned off automatically. I believe this setting is required for WSL updates to be delivered automatically through Windows update, which would circumvent the need to run the `wsl.exe --update` command manually?

I noticed that too. It wasn't actually looking for the updated until I activated the settings. It stil didn't work tho.

**Comment by SchizoDuckie** [comment] 2020-09-02 20:35
Allright, so this hit me today too.
Booting wsl resulted in absolutely no response, and a Green Screen Of Death as soon as i tried to reboot.
*none* of the solutions provided here actually worked.

Gist of what I did over like 6 hours.
- atttempt every solution i could find
- finally out of despair backup the `ext4.vhdx` file from  `%userprofile%\AppData\Local\Packages\<linuxflavor>\LocalState\`
- totally uninstall wsl, windows virtual machine platform and windows hypervisor platform from here 
![image](https://user-images.githubusercontent.com/111710/92033538-1a32a900-ed6c-11ea-8cc5-7f0d56862fae.png)
- reboot and reinstall wsl from scratch, make sure that the original vhdx you backed up is not in the same place!
- install your distro
- shutdown reboot again
- replace vhdx with your previous vhdx

Hope that helps someone

**Comment by phoenixjyb** [comment] 2020-09-04 03:01
Tried all the means mentioned above and still no luck in getting wsl working.  Windows build version:  Windows 10 Home Insider Preview,   Build 20206.rs.prerelease.200828-1431. WSL kernel version:  4.19.128.

**Comment by remenyo** [comment] 2020-09-06 08:05
Build 20206.rs.prerelease.200828-1431. WSL kernel version: 4.19.128.
(0. Installed Ubuntu 20.04)
1.: Enabled WSL in features -> 0x800706be
2.: wsl.exe --update -> 0x800706be
3: Enabled Virtual Machine Platform + reboot: it works now.

**Comment by wpzero** [comment] 2020-09-06 08:45
same issue for me.  Build 20206.rs.prerelease.200828-1431. WSL kernel version: 4.19.128. I can not install ubuntu. I have tried many methods, still not work. any other methods?

**Comment by doctordns** [comment] 2020-09-07 16:27
I have the same issue as @wpzero - running 20206 insiders build, ubuntu fails with the same error. 
Tried adding Hyper-V, and other fixes. Still get the error when installing:
``` powershell
PS C:\Ubuntu> .\ubuntu2004.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800706be
Error: 0x800706be The remote procedure call failed.
```

**Comment by superZhouDaLu** [comment] 2020-09-08 03:20
i have the same issue - running 20206, WSL kernel version: 4.19.128.

**Comment by superZhouDaLu** [comment] 2020-09-08 07:08
I fixed, reason is make sure that virtualization is enabled inside of mycomputer's BIOS.

**Comment by doctordns** [comment] 2020-09-08 09:05
> I fixed, reason is make sure that virtualization is enabled inside of my computer's BIOS.

Sadly, that fix does not seem to work here.

I suspect there IS a bug, but...
IF the WSL installer discovers virtualisation is NOT bios enabled, can't the distribution installer give a better error message - please provide actionable error messages.

**Comment by bmartinson** [comment] 2020-09-08 16:47
@doctordns, what build are you currently using? I spent hours trying to resolve this issue on the latest RC and Beta channel builds without any luck. Had to switch to the dev channel and install build 20206 to resolve the issue. Definitely a bug that is sitting fixed in the dev insider channel right now.

**Comment by benhillis** [comment] 2020-09-08 16:51
Fis is inbound.

**Comment by benhillis** [comment] 2020-09-11 13:49
Fixed in [20211](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20211).

**Closed by benhillis** 2020-09-11 13:49 UTC
Labels: bug, fixinbound

**Comment by JTDaddy17** [comment] 2020-09-11 18:18
Having problems with this error too, currently on Insider Release Preview Channel 20H2 19042.508

**Comment by tigerblue77** [comment] 2020-09-12 12:10
> Fixed in [20211](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20211).

Nope, I reinstalled everything (WSL + Debian distro) and same error

**Comment by toddmc** [comment] 2020-09-13 23:32
> Fixed in [20211](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20211).

I recently installed 20211.  

- Even with 20211, I initially had issues with running ubuntu.  After trying some series of steps here, I was able to get ubuntu 20.04 to run briefly.  Unfortunately, I am now getting the following message when starting it: 

WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel
Press any key to continue...

And the 3 ways that I know to update the kernel are failing for me: 
- System Update 
There were some problems installing updates, but we'll try again later. If you keep seeing this and want to search the web or contact support for information, this may help: (0x80070643)

- Download from https://aka.ms/wsl2kernel
When running wsl_update_x64 I get a prompt to insert a 'Windows Subsystem for Linux Update' disk.  It fails when I do not. 

- wsl --update 
Same as above

**Comment by doctordns** [comment] 2020-09-14 09:18
> Fixed in [20211](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20211).

No. It's not. At least not here...

First time I try to install ubuntu:

![2020-09-14_10-15-40](https://user-images.githubusercontent.com/3630329/93067772-8d44f500-f673-11ea-82a6-692e7cf4e4d2.png)

Then I try again and show the Winver

![2020-09-14_10-17-36](https://user-images.githubusercontent.com/3630329/93067766-8b7b3180-f673-11ea-9192-608de189aea9.png)

**Comment by hylowaker** [comment] 2020-09-15 01:41
Upgrading from 20206 to 20211 caused the error.

When I rollbacked to 20206, the error is gone.

**Comment by tommy-hansen** [comment] 2020-09-21 21:50
I was trying to run in VMWare Fusion, the solution was a hypervisor CPU setting as described in the answer to [this question]( 
https://stackoverflow.com/questions/62941823/run-wsl-2-on-a-virtual-machine-through-vmware-fusion). 

All good.

**Comment by Paranoid-OS** [comment] 2020-09-25 07:07
> I'm on 2004 OS build 20201.1000.
> 
> wsl.exe --update didn't work for me. Only works if I use wsl 1.

I'm on 20201 now, and the wsl.exe update worked!

**Comment by zhaolei-momo** [comment] 2020-09-25 09:24
Now I can only update from 2004 to 20150,
I donot know how can I update to 20201.

**Comment by tigerblue77** [comment] 2020-09-25 09:28
Hello,

So I installed build 20221 (should have fixed this problem) but it was not working. Here is what I did :

1) Uninstalled my distro (debian)
2) Uninstalled WSL functionnality
3) Restarted
4) Reinstalled WSL
5) Reinstalled Debian
6) (didn't worked) so I followed this : https://docs.microsoft.com/en-us/windows/wsl/install-win10
7) Step 4 fixed the problem :)

**Comment by tigerblue77** [comment] 2020-09-25 10:22
Hello,

So I installed build 20221 (should have fixed this problem) but it was not working. Here is what I did :

1) Uninstalled my distro (debian)
2) Uninstalled WSL functionnality
3) Restarted my PC
4) Reinstalled WSL
5) Reinstalled Debian (didn't worked) so I followed this : https://docs.microsoft.com/en-us/windows/wsl/install-win10
6) After step 4 my problem seems fixed because debian asked me an username for the new user to create
But when I enter an username : "Remote procedure call failure" (translated message)

**Comment by Paranoid-OS** [comment] 2020-09-25 11:22
> Now I can only update from 2004 to 20150,
> I donot know how can I update to 20201.

https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced

Here, the ISO is version 20201 last time I checked
If you upgrade by ISO, instead of the usual method of using the update center, you can install without giving Windows (and MS) your MS account, so less telemetry this way

**Comment by tigerblue77** [comment] 2020-10-03 15:00
Build 20226.1000 : I can confirm that this problem has been fixed now ! It works perfectly again 👍

**Comment by MKhoshnevis** [comment] 2020-12-11 20:51
I had the same issue with wsl , tring to install opensuse to install netdata on windows machine . 
to resolve , 
1 -remove the WSl and Virtual machine platform options form  windows apps and feature  
2- reboot machine 
3- go regedit > HKEY_LOCAL_MACHINE/SYSTEM/CURRENT CONTROL SET/SERVICES
 here you may see multiple LSXXMANAGER service listed 
4 - REMOVE LSXXMANAGER , starting from the last on elisted ( if you can't remove some, just change the Start key tp 1 , and start LSXXMANAGER from the Services.msc )
5 - reboot
6 - Install back WSL and Virtual Machine Platform options in Apps and Features 
7 - get opensuse 15.1 from microsoft store .

this worked for me .

**Comment by hekailiang** [comment] 2021-01-14 15:25
> Running this command solved it for me, ` insider preview 2004`
> 
> ```shell
> wsl.exe --update
> ```

worked for me, but need to run PowerShell as administrator first
