### ISSUE TITLE
Windows 10 April update 1803 WLS bash.exe error Error: 0x80070040

### ISSUE THREAD

**Issue by mudriion** [Microsoft/WSL#3143] opened 2018-05-03 08:07 UTC
After latest Windws 10 Aprile update;

1. Ubuntu WSL is installed
2. Ubuntu can be started from Application Start by clicking on "Bash on Ubuntu on Windows"
3. Running bash.exe from cmd or powershell getting the error
Error: 0x80070040
Press any key to continue...

Note:
From another thread checked content of the resolv,conf

cd %HOMEPATH%\AppData\Local\lxss\rootfs\etc\

type resolv.conf
../run/resolvconf/resolv.conf

Checking at the startup for Bash on Ubuntu on Windows  that is working

C:\Windows\System32\bash.exe {12345678-1234-5678-0123-456789abcdef} ~

**Comment by mudriion** [comment] 2018-05-03 12:38
The problem was related to Arch linux for WSL installation
Aftre clean uninstall of the Arch and install back now seems to work

**Comment by DarthSpock** [comment] 2018-05-03 15:01
> Error: 0x80070040
Press any key to continue...

This is most likely a dupe of #3020.

**Closed** 2018-05-03 15:31 UTC
