### ISSUE TITLE
<3>init: (4830) ERROR: UtilConnectUnix:467: connect failed 111 - When gnome-terminal is opened with shortcut

### ISSUE THREAD

**Issue by swinder0161** [microsoft/WSL#7174] opened 2021-07-13 17:58 UTC
### Windows Build Number

Microsoft Windows [Version 10.0.22000.65]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.43

### Distro Version

\ubuntu 20.04

### Other Software

wslg
gnome-terminal from wslusc shortcut

### Repro Steps

created gnome-terminal shortcut with wslusc

in shortcut properties, command is: C:\Users\swind\AppData\Local\Microsoft\WindowsApps\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\ubuntu2004.exe run "cd ~; gnome-terminal"

run gnome-terminal using shortcut

### Expected Behavior

interop should be working with shortcut in the same way like it works when gnome-terminal is started from ubuntu commandline

![image](https://user-images.githubusercontent.com/397543/125501803-d7190f4f-9cd8-4a92-962d-bf576d366e50.png)

### Actual Behavior

interop doesnot work

![image](https://user-images.githubusercontent.com/397543/125206251-f00f1900-e2a3-11eb-91d3-cceffb87b76c.png)

### Diagnostic Logs

none needed - 100% issue

**Comment by swinder0161** [comment] 2021-07-13 18:20
additional information:

on gnome-terminal started with shortcut
swinder@Windows10-Lenovo:~$ echo $WSL_INTEROP 
/run/WSL/4799_interop
swinder@Windows10-Lenovo:~$ cmd.exe
<3>init: (4934) ERROR: UtilConnectUnix:467: connect failed 111

==========================
on gnome-terminal start from ubuntu shell
swinder@Windows10-Lenovo:/mnt/c/Users/swind$ echo $WSL_INTEROP 
/run/WSL/4832_interop
swinder@Windows10-Lenovo:/mnt/c/Users/swind$ cmd.exe
Microsoft Windows [Version 10.0.22000.65]
(c) Microsoft Corporation. All rights reserved.

C:\Users\swind>

===========================
back to gnome-terminal started from shortcut and set WSL_INTEROP from working shell, that also works
swinder@Windows10-Lenovo:~$ echo $WSL_INTEROP 
**/run/WSL/4799_interop**
swinder@Windows10-Lenovo:~$ export WSL_INTEROP=**/run/WSL/4832_interop**
swinder@Windows10-Lenovo:~$ cmd.exe
'\\wsl.localhost\Ubuntu-20.04\home\swinder'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Microsoft Windows [Version 10.0.22000.65]
(c) Microsoft Corporation. All rights reserved.

C:\Windows>

**Comment by swinder0161** [comment] 2021-07-17 03:56
@craigloewen-msft By when is the fix expected for this 100% reproduced problem?

**Comment by craigloewen-msft** [comment] 2021-07-27 16:55
@swinder0161 I was able to reproduce this problem as well and filed a bug for it. It's hard to give an ETA as we triage a lot of different bugs. Is there a use case that this is blocking you from doing? Is the workaround of not accessing interop from a GUI app not viable for you in the meantime?

**Comment by swinder0161** [comment] 2021-07-28 03:25
The main use of this feature is to use fastboot/adb from wsl. it is more on convenience to use single shell.
Workaround is ofcource available and I am using a script to find a working interop before issue the command.

**Comment by tom-cook-pmev** [comment] 2021-10-11 13:28
@craigloewen-msft - could you please link to the other bug you raised?

This is a nasty inconvenience for me.  My usual workflow is to poke around until I find what I want to edit, then type `code .` to get a VS Code editor where I'm at to do the change.  When that does or doesn't work depending on _how you started your terminal_ it's pretty disruptive.

Even better would be a way to fix it, even manually, of course.

**Comment by Growiel** [comment] 2022-03-01 08:51
Hi,

Sorry to revive this, but I have the same issue when trying to connect to my docker-compose through PHPStorm and this is the only post that looks remotely close.

I tried @tom-cook-pmev code but I get the following issue:

![image](https://user-images.githubusercontent.com/5228735/156136020-adad6cf3-d567-4050-9e04-6f1e316fb115.png)

My $WSL_INTEROP shows: `/run/WSL/1986_interop` but when I run `ps auwxf` i do not have a 1986 process running.

**Comment by tom-cook-pmev** [comment] 2022-03-01 10:21
@Growiel I think this means that it's failing to find the parent process that has a valid interop socket and the attempt to break out in this case is failing.  I'm not running WSL any more (have bailed back to real Linux) so can't try to debug, sorry.

**Comment by yoDon** [comment] 2022-04-28 02:46
I'm currently experiencing this issue in multiple VS-Code terminals (VS Code server is running inside WSL, VS Code UI is running under Windows). If I create a new wsl terminal prompt in Windows (not inside VS Code) docker-compose up works as expected in the non-VS-Code terminal even though it's failing in the VS-Code terminal.

**Comment by cstmth** [comment] 2022-05-26 18:20
I am experiencing the same issue right now.

**Comment by adiletelf** [comment] 2022-05-27 11:51
I also face the problem but only when Docker is not running.

**Comment by alifdarsim** [comment] 2022-06-04 00:55
Got the same problem when using vscode terminal. After running docker-compose using PowerShell one time, everything is ok, including when vscode terminal.

**Comment by gthaka** [comment] 2022-06-16 20:24
Got the same error
```
<3>init: (8174) ERROR: UtilConnectUnix:467: connect failed 111
```

Reloading **wsl** and **restarting docker desktop** worked for me

**Comment by fcwoknhenuxdfiyv** [comment] 2022-06-25 06:57
Could the issue title be renamed? This problem happens to me daily but not in relation to Gnome terminal.

My workflow is based around tmux and I use a lot of sessions, windows and panes. It's really annoying to have to run `wsl --shutdown` at least a couple of times a day because I can no longer call `clip.exe`

Is there a way of debugging this?

**Comment by reynoldsbd** [comment] 2022-07-01 16:26
This issue is preventing me from executing Git push/pull commands within VS Code's integrated terminal.

I've set up my WSL Git to use GCM Core from the Windows side, as described here:

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup

This works fine from a plain terminal window. But if I start a VS Code session (using the Remote WSL extension) then the authentication plugin fails with this same error message.

**Comment by jackheuberger** [comment] 2022-07-15 19:03
Had the exact same issue. Closing and reopening vscode solved it. Once I closed vscode, the popup appeared saying it needed to update. It seems to be working fine now though.

Maybe it has something to due with vscode updating in the background?

**Comment by deblasis** [comment] 2022-08-04 16:30
same issue here

**Comment by trallnag** [comment] 2022-08-08 21:39
Is there an open issue that covers the more general problem as it is not just with gnome-terminal? In my case I frequently come across this behavior in VS Code when I want to call Windows executables from the internal terminal. Running the script provided by @tom-cook-pmev resolves it

**Comment by wallds** [comment] 2022-08-15 06:39
same issue here.
This bug is triggered when I close the wsl terminal used to launch vscode.
![1](https://user-images.githubusercontent.com/12907032/184587405-bd847b23-b9b8-4324-88a6-c28d820a0447.gif)

**Comment by gerhard4** [comment] 2022-08-22 15:42
I encounter this (or a similar) error when running Docker (on Ubuntu).
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
<3>init: (26522) ERROR: UtilConnectUnix:467: connect failed 2
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:7d246653d0511db2a6b2e0436cfd0e52ac8c066000264b3ce63331ac66dca625
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
...
```
It eventually succeeds here. But what appears to be the same bug prevents Docker from automatically pulling images referenced in a Dockerfile. It seems to work by manually pulling them.

**Comment by n-y-kim** [comment] 2023-02-17 04:18
Encountering exactly same issues as @yoDon. `docker build` Works fine at Ubuntu WSL2 terminal, but VSCode bash terminal pops 

```
<3>WSL (114456) ERROR: UtilConnectUnix:510: connect failed 2
Cannot connect to the Docker daemon at tcp://localhost:2375.
```

 Thought I had configuration issue with docker & wsl2 and wasted plenty of time trying to resolve the connection issue 😭 Hope this issue resolves soon & if somebody having problem with docker wsl2, please try your docker at non-vscode terminal.

**Comment by gerhard4** [comment] 2023-02-17 15:13
Somebody from Microsoft told me to try the Microsoft Store version of WSL. (I had installed it through the Windows components applet.) I did; the reinstall was smooth and didn't affect my existing configuration. Afterwards, I didn't see the problem anymore.

Weird that they can't sync the two versions, but that's where we are.

**Closed** 2024-07-11 12:01 UTC
Labels: bug
