### ISSUE TITLE
Bash on Ubuntu for Windows has no connectivity. Reinstalled multiple times.

### ISSUE THREAD

**Issue by Todai88** [Microsoft/WSL#1725] opened 2017-02-24 23:08 UTC
As with many other people I'm completely unable to run any network functions; neither cURL, ping or any package updates (sudo apt-get update).

I've tried many of the suggested changes in other threads (running bash with elevated priviligies, adding nameserver 8.8.8.8 in /etc/resolv.conf etc), but nothing seems to work. 

I should mention that I'm running BullGuard AV, but I've attempted to turn off both the Windows Firewall and BullGuards bundled Firewall. Again, doesn't work.

* Expected results

Clearly I want bash to work as intended, where I can curl servers etc.

* Actual results (with terminal output if applicable):

`sudo apt-get update` gives me 

```
Err http://archive.ubuntu.com trusty InRelease

Err http://security.ubuntu.com trusty-security InRelease

Err http://archive.ubuntu.com trusty-updates InRelease

Err http://archive.ubuntu.com trusty-backports InRelease

Err http://security.ubuntu.com trusty-security Release.gpg
  Could not resolve 'security.ubuntu.com'
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-backports Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-backports/InRelease

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'security.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-backports/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

And `ping www.google.com` gives me:
`ping: unknown host www.google.com`

Finally `ping 8.8.8.8` gives me:
`Do you want to ping broadcast? Then -b`

* Your Windows build number

![image](https://cloud.githubusercontent.com/assets/2641122/23324475/eafecd8e-fae5-11e6-8ec2-b1bfda1f0030.png)

* Steps / All commands required to reproduce the error from a brand new installation 

In my case, absolutely nothing. I've removed and installed the Bash service twice with no changes.

* Strace of the failing command

-

* Required packages and commands to install

-

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment] 2017-02-25 00:11
Hi @Todai88 -- as you mention, a number of people have experienced this issue; it has actually turned out to have many different unrelated causes, and often (though not always) with a root cause of a misconfigured network or buggy third-party Windows security application.  So it may be worth your time to dig through more of the existing resolved tickets to see if their resolutions help you.  (It would be great if WSL provided a debugging wizard or something to help catch the common cases; alas, this doesn't exist to my knowledge.)

One thing immediately jumps out at me:  Has anyone verified that BullGuard AV works with WSL?  I'm not familiar with it.  I know you've turned it off.  But a lot of early WSL users had problems where their antivirus or firewall software blocked WSL even when it was turned off.  The only fix was to uninstall, or to upgrade to a fixed version of the security software once one was released.

**Comment by sunilmut** [comment] 2017-03-03 00:34
@Todai88 - You can also try deleting your `/etc/resolv.conf` and see if that makes any difference.

**Comment by sunilmut** [comment] 2017-03-03 00:34
@Todai88 - You can also try deleting your `/etc/resolv.conf`, closing and reopening bash again, and see if that makes any difference.

**Comment by tara-raj** [comment] 2018-08-21 20:19
Please try this on a more recent Windows Build (EX: 1803) and please reopen if you still run into this issue

**Closed by tara-raj** 2018-08-21 20:19 UTC
Labels: network
