### ISSUE TITLE
Docker does not starts automaticity after installation and containers cannot access the internet nor DNS from docker0 interface (bridged network).

### ISSUE THREAD

**Issue by amadeuszkryze** [microsoft/WSL#4185] opened 2019-06-18 17:17 UTC
* Windows build number: `10.0.18917.1000`

* Steps on fresh instance of WSL2:
```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable edge test"
sudo apt-get update
sudo apt-get install -y docker-ce #installs 19.03.0-rc2
```
or
```
curl https://get.docker.com/ | bash
```
* What's wrong / what should be happening instead:

After logout&login or reboot:
1. `docker` is not started as it is in baremetal linux.
2. `docker run --net host debian ping 8.8.8.8` works
3. `docker run --net host debian ping google.com` works
4. `docker run debian ping 8.8.8.8` does not work
5. `docker run debian ping google.com` does not work

_has been tested on WSL2: Debian 9.9, Ubuntu 18.04 and Ubuntu 19.04 with both ways of installing docker_

* RELATED:
1. https://github.com/MicrosoftDocs/WSL/issues/422
2. #4133

**Comment by Biswa96** [comment] 2019-06-18 17:46
As a workaround, use the sysVinit script instead of systemd which requires some extra work.

**Comment by amadeuszkryze** [comment] 2019-06-19 10:44
As a workaround I can even run `sudo service docker start` and it will be working. 

Bigger problem is with networking. Even when trying to add NAT rules in `ufw`:
1. `ufw` is disabled by default
2. After enabling `ufw` in `/etc/ufw/ufw.conf` it does not work due to:
```
<DATE> with <USER> in /etc/init.d at <HOST>
1 > sudo ./ufw start
 * Starting firewall: ufw...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module nf_conntrack_ftp not found in directory /lib/modules/4.19.43-microsoft-standard
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module nf_nat_ftp not found in directory /lib/modules/4.19.43-microsoft-standard
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.43-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module nf_conntrack_netbios_ns not found in directory /lib/modules/4.19.43-microsoft-standard
iptables-restore: line 80 failed
iptables-restore: line 11 failed
 * ...
 * Problem running '/etc/ufw/before.rules'...
 * Problem running '/etc/ufw/user.rules'...
```

Additional config added to `/etc/ufw/before.rules`:
```
*nat
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 172.17.0.0/16 -j MASQUERADE
COMMIT
```

`DEFAULT_FORWARD_POLICY="ACCEPT"` is set in: `/etc/default/ufw`

**Comment by onomatopellan** [comment] 2019-06-19 15:41
Duplicate of #4107

**Comment by therealkenc** [comment] 2019-06-24 14:47
Thanks Ono.

**Closed by therealkenc** 2019-06-24 14:47 UTC

**Comment by tobiaskohlbau** [comment] 2019-07-02 10:40
I don't think this issue duplicates #4107. The workaround attempt duplicates #4107 but the underlying issue with dns not resolvable within docker containers remains. I ran into the same issue and searched for some kind of workaround or acknowledgement that it's a known issue and not my setup.
