### ISSUE TITLE
Postman request issues with WSL2

### ISSUE THREAD

**Issue by muhammadsalmanafzal** [microsoft/WSL#7965] opened 2022-01-24 16:06 UTC
### Version

Microsoft Windows [Version 10.0.22000.438]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Distro Version

Ubuntu 20.04

### Other Software

- Node JS
- Mongoose (Mongodb as db)
- Express 
- Postman for Windows

### Repro Steps

I'm using the store version of WSL i.e. Windows Subsystem for Linux Preview. I'm learning about web dev as MERN stack and was doing work with Postman. It was running fine until the app got updated over the weekend. So, basically I think update is the main issue.

### Expected Behavior

I need to click only once on the send button in postman to send my request to the localhost api, even when changing the methods   between get, patch, post etc.

### Actual Behavior

In reality, after I switch methods like I go from GET to any other method (including GET), the request gets stuck and I have to cancel the request and send it again. On the second run it always works. So, I think, the request is getting stuck somewhere due to the update. I have also tried it on Ubuntu PC and it works just fine.

[as](https://nustedupk0-my.sharepoint.com/:v:/g/personal/mafzal_bee17seecs_student_nust_edu_pk/ETyp1sI4gZBBuqNUNViY4pABxIxhnXJyGm7RXXIuH2RRgQ?e=VadhbZ)

### Diagnostic Logs

As can be seen from the attached [video](https://nustedupk0-my.sharepoint.com/:v:/g/personal/mafzal_bee17seecs_student_nust_edu_pk/ETyp1sI4gZBBuqNUNViY4pABxIxhnXJyGm7RXXIuH2RRgQ?e=VadhbZ), whenever I switch the request or modify it, it gets stuck. 
If additional info is required, do reply and I'll provide it asap.

**Comment by gerardojbaez** [comment] 2022-01-24 23:23
It may be possible that this is the same issue as #7958. I managed to get around it by uninstalling Windows Subsystem For Linux Preview (the store version), then updated the WSL Kernel using `wsl --update --inbox` - this applies an update without downloading from the store.

**Comment by muhammadsalmanafzal** [comment] 2022-01-25 09:35
What about my files? Do I need to backup? Do I have to setup my environment again? That would be too much of a work😥😥

**Comment by gerardojbaez** [comment] 2022-01-25 19:30
My files and projects weren't affected. I think the Microsoft Store version provides just the kernel.

**Comment by OneBlue** [comment] 2022-01-25 22:48
Thanks for reporting this @muhammadsalmanafzal. Can you share the output of the [Postman console](https://blog.postman.com/the-postman-console/) when the request is "hanging" ?

Can you also see if you can reproduce the same behavior with a web browser ? I'm wondering if the issue comes from postman or the web server that you're running.

**Comment by craigloewen-msft** [comment] 2022-01-25 22:58
I went and tried this and wasn't able to reproduce your issue. I'm also using the Store version of WSL. 

Maybe you could also try installing Postman as a GUI app inside of your WSL distro and use it from there, do you see the same issue? If yes then you know that it's your code and not Postman or WSL in that sense.

![gui](https://user-images.githubusercontent.com/42221804/151073601-56945905-b94e-493c-ab62-578816e4a7c0.gif)

**Comment by guilhermetod** [comment] 2022-01-26 01:44
Probably related to this and #7958, I'm experiencing issues with localhost too. Simply serving an Angular app is enough to feel the issue. It does compile and open well on the first time (some images don't get correctly loaded randomly, but it open the app). Once I make some change to the code and it recompiles, it hangs on the reload until I hit `CTRL+F5` a few times.

It's been happening since the latest Windows build (I'm an Insider on the dev channel)

**Comment by muhammadsalmanafzal** [comment] 2022-01-26 11:33
> I went and tried this and wasn't able to reproduce your issue. I'm also using the Store version of WSL.
> 
> Maybe you could also try installing Postman as a GUI app inside of your WSL distro and use it from there, do you see the same issue? If yes then you know that it's your code and not Postman or WSL in that sense.
> 
> ![gui](https://user-images.githubusercontent.com/42221804/151073601-56945905-b94e-493c-ab62-578816e4a7c0.gif)

@craigloewen-msft I did what you told me. Installed Postman manually (since snap doesn't work with WSL as of now except for the hacks). And run it. Here is a [video](https://nustedupk0-my.sharepoint.com/:v:/g/personal/mafzal_bee17seecs_student_nust_edu_pk/EQPpAYczk41OkRK0hw_e-jIBvvpNqTyWOV3KomKc5fKaUA?e=mbnYHV). As you can see, it works just fine there. 

@OneBlue Here is also a [video](https://nustedupk0-my.sharepoint.com/:v:/g/personal/mafzal_bee17seecs_student_nust_edu_pk/EdhL6gtm0alPmF06tbeYltABCb6_CwHcwc1VP5bjdvCz2Q?e=QzuONO) where I'm testing on browser and Postman Desktop Agent with the console enabled. As you can see, for Postman it does not display anything, while for the edge, it displays that it is pending.

**Comment by muhammadsalmanafzal** [comment] 2022-01-26 11:35
> My files and projects weren't affected. I think the Microsoft Store version provides just the kernel.
> 
> I'm not sure, if you are using WSL, I suspect that you already have the Window Subsystem for Linux feature enabled. You can check the command by opening CMD or PowerShell and try `wsl --status`, if you get a response back then it should work with other commands.

I don't have the windows feature enabled since it wasn't really required for the store version. But I do get a response back as:
```
PS C:\Users\msalm> wsl --status
Default Distribution: Ubuntu
Default Version: 2
WSL1 is not supported with your current machine configuration.
Please enable the "Windows Subsystem for Linux" optional component to use WSL1.
WSL version: 0.51.2.0
Kernel version: 5.10.81.1
WSLg version: 1.0.30
Windows version: 10.0.22000.438
```

**Comment by 39digits** [comment] 2022-01-26 11:48
I'm experiencing an issue that I feel is related.

### My Setup

Windows 11 Pro with the MS Store version of WSL2 running Ubuntu 20.04.

Specific details:
- Windows Version: Windows 11 Pro 21H2 (10.0.22000.469)
- WSL2 version: 0.51.2.0
- Kernel version: 5.10.81.1
- Linux Distribution: Ubuntu 20.04

### Issue Experienced
If I access a Node application running inside of WSL2 the browser Network tab will sometimes get stuck in a pending state for fetch requests.  The Network details shows that it gets stuck in the Initial Connection stage.  This is corroborated by there being no hits in the app log inside WSL2.

This only happens if I try to access the app from Windows using http://localhost against the relevant port (usually 3000 or 8000 depending on the app I'm running).  If I access the site using the IP address for WSL2 then the GET requests are never stuck in the pending state.

I have had the issue since the last update - everything was running perfectly against localhost prior to the update.

The common thread is Node's HTTP library and the default **keep-alive timeout** of 5 seconds.  I have experienced the issue using Express, Next.js, and Remix - Gatsby was unaffected.

I confirmed this by creating the Hello World Express app, verified the issue still occurred under this simplest of apps, then explicitly set the http server's keepaliveTimeout setting to 0.  The issue went away completely. 

To reiterate, the issue only showed up since the last update and was working as expected prior to that.

### Steps to Reproduce
- Run any Express-based application (their Hello World example for the easiest) inside WSL2
- Open the Dev Tools and have the Network tab open
- Access the app from Windows using http://localhost:3000 (or the relevant port)
- Note the Request returns a 200
- Refresh the page a few times then wait longer than the timeout (5 seconds) before refreshing and you'll hit the stuck pending state.

**Comment by 39digits** [comment] 2022-01-26 12:04
@muhammadsalmanafzal could you run your GET requests from the Windows installed version of Postman against the WSL2 IP address and not localhost/127.0.0.1 and see if that works?  I suspect hitting the actual IP will work without issue based on what I wrote in my previous comment.

**Comment by muhammadsalmanafzal** [comment] 2022-01-26 12:25
> @muhammadsalmanafzal could you run your GET requests from the Windows installed version of Postman against the WSL2 IP address and not localhost/127.0.0.1 and see if that works? I suspect hitting the actual IP will work without issue based on what I wrote in my previous comment.

Sorry for the noob question but can you kindly elaborate on how to get that actual IP? and I'll test it.

**Comment by 39digits** [comment] 2022-01-26 12:47
> > @muhammadsalmanafzal could you run your GET requests from the Windows installed version of Postman against the WSL2 IP address and not localhost/127.0.0.1 and see if that works? I suspect hitting the actual IP will work without issue based on what I wrote in my previous comment.
> 
> Sorry for the noob question but can you kindly elaborate on how to get that actual IP? and I'll test it.

If you run `ip addr | grep eth0` inside the terminal connected to WSL2 you can find the IP address next to `inet`.  It might look something like `inet 172.26.93.66/20`

Then in Postman use that IP address (ignore the `/20` bit) instead of 127.0.01 while your app is running.  

Keep in mind that that IP address isn't static and will change with reboots, etc.

**Comment by muhammadsalmanafzal** [comment] 2022-01-26 12:56
> > > @muhammadsalmanafzal could you run your GET requests from the Windows installed version of Postman against the WSL2 IP address and not localhost/127.0.0.1 and see if that works? I suspect hitting the actual IP will work without issue based on what I wrote in my previous comment.
> > 
> > 
> > Sorry for the noob question but can you kindly elaborate on how to get that actual IP? and I'll test it.
> 
> If you run `ip addr | grep eth0` inside the terminal connected to WSL2 you can find the IP address next to `inet`. It might look something like `inet 172.26.93.66/20`
> 
> Then in Postman use that IP address (ignore the `/20` bit) instead of 127.0.01 while your app is running.
> 
> Keep in mind that that IP address isn't static and will change with reboots, etc.

This is the response that I get while using the original IP saying connection refused:
```
GET http://172.29.85.52:8000/api/v1/tours: {
  "Error": "connect ECONNREFUSED 172.29.85.52:8000",
  "Request Headers": {
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "postman-token": "8993a0b7-5dd1-4700-851d-2bb731551e4c",
    "host": "172.29.85.52:8000",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  }
}
```

**Comment by 39digits** [comment] 2022-01-27 22:00
I'm pretty sure there is an issue with connections against localhost since the last update.  I've opened a more general issue #7982

**Comment by pikadun** [comment] 2022-01-28 02:17
I also encountered the same problem, and found that it was a tcp connection problem https://github.com/microsoft/WSL/issues/7979

**Comment by muhammadsalmanafzal** [comment] 2022-01-28 12:21
> I'm pretty sure there is an issue with connections against localhost since the last update. I've opened a more general issue #7982
@39digits So should I close issued opened by me or keep it as is until the problem is solved? New to all this, so don't really understand the workflow of things.😓😢

**Comment by 39digits** [comment] 2022-01-28 23:36
> > I'm pretty sure there is an issue with connections against localhost since the last update. I've opened a more general issue #7982
> 
> @39digits So should I close issued opened by me or keep it as is until the problem is solved? New to all this, so don't really understand the workflow of things.😓😢

I'd say you're good to keep this one open :)  We can leave the decision to the maintainers whether they feel the two issues are distinct enough to keep open or to close one in favour of the other if they feel the issue is duplicated.

**Comment by jaredholdcroft** [comment] 2022-01-30 19:08
Uninstalling the store version of WSL fixed it for me.

**Comment by guilhermetod** [comment] 2022-01-31 16:53
For the people that uninstalled the store version, you do have to restore all your files then, right? Or is there a way to keep them?

**Comment by jaredholdcroft** [comment] 2022-01-31 16:56
> For the people that uninstalled the store version, you do have to restore all your files then, right? Or is there a way to keep them?

You don't need to do anything. I uninstalled, restarted WSL and everything was still there.

**Comment by owenschupp** [comment] 2022-01-31 20:15
@muhammadsalmanafzal would you mind running and posting the output of `nc -l -p 80` in WSL instead of running the web application. This would help us confirm whether this is a networking issue or not

**Comment by anurag2361** [comment] 2022-02-01 09:37
> @muhammadsalmanafzal would you mind running and posting the output of `nc -l -p 80` in WSL first instead of running the web application. This would help us confirm whether this is a networking issue or not

I have the same problem as the issue. I tried running this command and nothing is happening.
![Screenshot 2022-02-01 150524](https://user-images.githubusercontent.com/27642991/151944743-3ef9bb2a-d1de-4a52-91be-026dbdfbc783.png)

**Comment by anurag2361** [comment] 2022-02-01 09:59
I am keeping the store version of WSL2. This issue doesn't occur for me if I'm using the wsl ip and only occurs if I use `localhost` or `127.0.0.1`. With WSL IP got through `ip addr | grep eth0` command, it works fine.

**Comment by muhammadsalmanafzal** [comment] 2022-02-01 10:09
> @muhammadsalmanafzal would you mind running and posting the output of `nc -l -p 80` in WSL first instead of running the web application. This would help us confirm whether this is a networking issue or not

 As @anurag2361 mentioned, I don't get anything in output.

![image](https://user-images.githubusercontent.com/53542416/151949558-116fce60-7dd2-4141-b1f7-b370c7a1376e.png)

**Comment by anurag2361** [comment] 2022-02-11 13:58
This is fixed in the latest preview build on Windows Store. If its working, I think this issue can be closed @muhammadsalmanafzal

**Closed** 2022-02-11 16:18 UTC

**Comment by muhammadsalmanafzal** [comment] 2022-02-11 17:42
> This is fixed in the latest preview build on Windows Store. If its working, I think this issue can be closed @muhammadsalmanafzal

@anurag2361 Just checked it out. Yes, its working now and that's great!!! Kudos to the team. Can you also outline what was actually happening to cause this issue? Since it will be great from learning point of view. 
Also, where can we see the build notes to checkout the changes which are made in updates? I'll appreciate your feedback.

**Comment by craigloewen-msft** [comment] 2022-02-15 22:07
@muhammadsalmanafzal you can see release notes here:
https://github.com/microsoft/WSL/releases/tag/0.51.3
