### ISSUE TITLE
Unsupported escape sequence with gh + WSL2 + Windows Terminal

### ISSUE THREAD

**Issue by ymmt2005** [microsoft/WSL#11995] opened 2024-09-05 00:31 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.4037]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Mar 29 23:14:13 UTC 2024

### Distro Version

Ubuntu 22.04

### Other Software

- gh version 2.55.0 (2024-08-20)
    - Installed via the APT repository of GitHub.
- Windows Terminal 1.20.11781.0

### Repro Steps

Tried to list pull requests and got the attached output
with unsupported escape sequences. The `TERM` value was
`xterm-256color`, which was set by default.

### Expected Behavior

The output should be nice.

### Actual Behavior

![image](https://github.com/user-attachments/assets/46a4a939-c9eb-4943-b7fa-eb1e3a635ef0)

```console
$ gh --version
gh version 2.55.0 (2024-08-20)
https://github.com/cli/cli/releases/tag/v2.55.0
$ echo $TERM
xterm-256color
$ gh pr list

Showing 1 of 1 open pull request in cybozu/yrmcds

ESC[0;2;4;37mID ESC[0m  ESC[0;2;4;37mTITLE                                      ESC[0m  ESC[0;2;4;37mBRANCH    ESC[0m  ESC[0;2;4;37mCREATED AT        ESC[0m
ESC[0;32m#90ESC[0m  Implement file-based leader election method  ESC[0;36mJTASK-1062ESC[0m  ESC[38;5;242mabout 2 months agoESC[m
```

**Comment by ymmt2005** [comment] 2024-09-05 00:36
/question

I'm not sure which part of the tools was not working well.
Please let me know how it works correctly, or it might be a bug of something.

**Comment by zcobol** [comment] 2024-09-05 16:32
Since you're using Ubuntu, does your shell prompt renders in color? It's usually green on Ubuntu.

Quick test using same `gh` version and your `yrmcds` repo. The output is colored in the terminal, this is just pasted output:

```
zcobol@toto:~/yrmcds$ gh --version
gh version 2.55.0 (2024-08-20)
https://github.com/cli/cli/releases/tag/v2.55.0
zcobol@toto:~/yrmcds$ gh pr list

Showing 1 of 1 open pull request in cybozu/yrmcds

ID   TITLE                                        BRANCH      CREATED AT
#90  Implement file-based leader election method  JTASK-1062  about 2 months ago
```

**Comment by zcobol** [comment] 2024-09-05 16:43
What is the output of `echo $PS1`?

**Comment by ymmt2005** [comment] 2024-09-05 21:02
@zcobol Yes, it shows colors and interprets various other escape sequences.
I changed `PS1` on purpose to hide any sensitive information.

In fact, it interprets `curl https://raw.githubusercontent.com/csdvrx/sixel-testsuite/master/ansi-vte52.sh | bash` perfectly.
Only `gh` behaves badly.
![image](https://github.com/user-attachments/assets/7b21894d-34b9-4995-8820-891c6dded4ff)

**Comment by ymmt2005** [comment] 2024-09-05 21:02
I believe anyone can repro this easily.

**Comment by OneBlue** [comment] 2024-09-11 17:11
Thank you for reporting this @ymmt2005. Based on the output you're seeing, the most likely explanation is that this is a bug in the gh tool. 

The best course of action would be to report the issue [here](https://cli.github.com/manual/gh_issue_create).

Closing since the issue isn't coming from WSL

**Closed by OneBlue** 2024-09-11 17:11 UTC
Labels: question

**Comment by ymmt2005** [comment] 2024-09-11 20:20
@OneBlue 
Understood, but the link was a user manual and I'm confused.
Do you mean https://github.com/cli/cli ?
