### ISSUE TITLE
Lower CPU usage with 1.13.14

### ISSUE THREAD

**Issue by Frozaccio** [microsoft/WSL#10310] opened 2023-07-20 04:24 UTC
### Windows Version

Windows 11 pro 22621.1992 22H2

### WSL Version

1.13.14

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu 22.04

### Repro Steps

I am using WSL1 for long time. When passing from 1.13.11 to 1.13.14, CPU usage is divided by 2. This can be reproduced with any calculation code / compiler / script. I downgraded to 1.13.11 and my CPU usage went back to 100 % (instead of 56 % with 1.13.14). Note that I do parallel calculation on multiple cores. I have an intel core 13th gen i9-13980HX. Maybe that is linked with the way WSL manages the E cores and the P cores. I did not test with WSL2

### Expected Behavior

CPU usage 100 %

### Actual Behavior

CPU usage 50 %

**Comment by OneBlue** [comment] 2023-07-25 21:39
Thank you for reporting this @Frozaccio. Which process is taking the extra CPU for you in 1.3.14 ? 

Is the CPU being used in Linux, or by a Windows process ?

**Comment by Frozaccio** [comment] 2023-07-25 22:54
I was performing a calculation with the simulation code GEANT4 using multiple threads but I tested other parallelized codes with the same result of not being able to go beyond ~50 %. 
The CPU was used in Linux (WSL) and almost not used by windows (just standard background usage).

**Comment by OneBlue** [comment] 2023-07-25 23:00
Thank you @Frozaccio. Is this simulation using wslg / GUI apps ?

**Comment by Frozaccio** [comment] 2023-07-25 23:01
Yes it has a user interface based on QT. I can try to execute it without the user interface if it helps

**Comment by OneBlue** [comment] 2023-07-25 23:36
Yes, that would help us understand if the issue comes from wsl or wslg

**Comment by Frozaccio** [comment] 2023-07-26 05:23
@OneBlue,  I reinstalled WSL 1.3.14 to perform the test we talked about with the user interface. I do not succeed to reproduce the issue. Everything goes smoothly with the simulations now, even when the user interface is activated. I guess I did a mistake during my first installation ?!.... sorry for the time lost...

**Comment by OneBlue** [comment] 2023-08-08 18:14
Ok thank you for the sharing the results. Closing since the issue is gone.

**Closed by OneBlue** 2023-08-08 18:14 UTC
Labels: wsl1
