### ISSUE TITLE
WSL2: babel watch silently fails

### ISSUE THREAD

**Issue by zersiax** [microsoft/WSL#4411] opened 2019-08-15 01:27 UTC
**Please fill out the below information:**
* Your Windows build number:  18956 (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
  - With Node, Npm/yarn, babel and babel presets installed, run: babel <source dir> --out-dir <dist dir> --watch --presets=<your presets>.
  - Babel will run once and then seemingly wait for filesystem changes.'

* What's wrong / what should be happening instead:
  - When files in the src dir are changed, which should trigger a retranspile of the files in src dir to dist dir, nothing happens. No output is given, but nothing happens in the dist dir either.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/zersiax/b047699869b5ff68ab35d632fe0c070b
  *warning* that file is rather large
* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by onomatopellan** [comment] 2019-08-15 18:10
Probably a duplicate of #4169. Try a /home folder instead of a /mnt one.

**Closed** 2019-09-17 20:13 UTC
Labels: duplicate
