### ISSUE TITLE
Arrow keys (and Home, End, etc) not working when wsl command spawned via pipe

### ISSUE THREAD

**Issue by drafnel** [microsoft/WSL#4754] opened 2019-12-12 02:52 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.535]

    > wsl.exe --list
    Windows Subsystem for Linux Distributions:
    Ubuntu-18.04 (Default)

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

From cmd.exe:

    > type somefile.txt | wsl.exe -e less

From powershell:

    > Get-Content somefile.txt | wsl.exe -e less

In the above, somefile.txt should be a text file that exists on the windows filesystem that contains a number of lines of text, preferably greater than the number of rows in the terminal you are using so that scrolling is possible.

In both cases, the 'j' and 'k' keys may be used to scroll the text piped into the less command running in wsl, but the arrow keys are not functional and neither are any of the Home/End/PageUp/PageDown etc. keys.

* What's wrong / what should be happening instead:

The expectation is that the arrows keys should be functional and, with respect to the 'less' command, the 'down' and 'up' arrows should scroll the text in the same way that the 'j' and 'k' keys do, and the 'left' and 'right' arrows should scroll the text in the same way that ESC-( and ESC-) do.

If a pipe is not used, then the arrow keys work correctly.  For example, the arrow keys work as expected if the following command is run from either powershell or cmd.exe:

    > wsl.exe -e less somefile.txt

**Comment by davidhewitt** [comment] 2019-12-12 20:55
I actually also just ran into this. It seems to me that no keys are working - I can't use `q` to quit `less`, or `/` to search the file. `Ctrl+C` works to quit, though.

This isn't unique to `less` either: I get the same problem with `type somefile.txt | wsl.exe -e more`

**Comment by drafnel** [comment] 2019-12-12 21:43
Interesting.  Yeah, it's not limited to `less`; another example is `type somefile.txt | wsl.exe -e vim -`.  The rest of the keys do work for me.  It's only the navigation keys that do not work.

To help out anyone that may investigate this, you may want to post your windows version and if relevant, whether you're using Wsl1 or Wsl2.

**Comment by davidhewitt** [comment] 2019-12-12 23:35
Good point!

Windows 10 build 19037
WSL 2

**Comment by ambarve** [comment] 2019-12-23 18:25
Thanks for reporting the bug. We have identified the issue and we are working on the fix.

**Comment by vefatica** [comment] 2021-01-21 16:25
Any updates on this issue?

**Comment by JoeC4281** [comment] 2021-01-21 17:22
```
Windows 10 [Version 10.0.19042.746]
BuildNumber  Caption                   CSDVersion  OSArchitecture  Version
19042        Microsoft Windows 10 Pro              64-bit          10.0.19042
```
Same problem here, with WSL1.

Any estimate when this can be rectified?

Joe

**Comment by NotTheDr01ds** [comment] 2021-02-09 17:35
This looks to be a duplicate of #4646 which was closed as being "as designed".

**Comment by NotTheDr01ds** [comment] 2022-08-08 22:47
After getting fed up with trying to work through some long `Get-CimClass` output last week, I decided to come up with a solution (at least for my use-case).  For those who come across this in a search for something like *powershell pipe to wsl less*, try the following PowerShell function:

```PowerShell
Function Out-WSLPager {
    $pagerGUID = (New-Guid)
    $input | Out-String -Stream | wsl -e bash -c "cat > /tmp/pager.$lessGUID"
    wsl -e less -R /tmp/pager.$lessGUID
    wsl -e rm /tmp/pager.$lessGUID
}
```

If you have [`bat`](https://github.com/sharkdp/bat) installed in WSL for syntax highlighting (and other features), then simply substitute it in place of `less -R`.

It's not a complete replacement, since it doesn't truly stream to the pager (it accumulates all output in a temporary file), but it should work for the majority of use-cases.

**Closed** 2024-02-01 12:19 UTC
Labels: needs-investigation
