### ISSUE TITLE
The Android subsystem running software shows that the openGL version is too low

### ISSUE THREAD

**Issue by zhang110105** [microsoft/WSL#11524] opened 2024-04-27 07:51 UTC
![屏幕截图 2024-04-27 154920](https://github.com/microsoft/WSL/assets/168264329/0db42a4a-e8c4-4fdb-b857-b2ec72b9b0bf)
![image](https://github.com/microsoft/WSL/assets/168264329/d84e7c36-0b37-4fd0-8e6c-8c4928a3473c)
![image](https://github.com/microsoft/WSL/assets/168264329/8093f1a8-7114-4d90-81ca-19ab0572a236)
![image](https://github.com/microsoft/WSL/assets/168264329/ac646120-8ed9-479f-b5a6-b092c34987a9)

The Android subsystem running software shows that the openGL version is too low
Windows Version:10.0.26200.5001

**Comment by OneBlue** [comment] 2024-05-28 21:36
Closing since the issue isn't about WSL

**Closed by OneBlue** 2024-05-28 21:36 UTC
Labels: question
