### ISSUE TITLE
SSH hangs the terminal completely

### ISSUE THREAD

**Issue by Entroper** [Microsoft/WSL#3430] opened 2018-08-01 22:20 UTC
* Your Windows build number:  10.0.17134.165

* What you're doing and what's happening:  
```
$ ssh -vv big-daddy
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "big-daddy" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to big-daddy [192.168.1.6] port 22.
debug1: Connection established.
debug1: identity file /home/entroper/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/entroper/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to big-daddy:22 as 'entroper'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:VKaWjwwZztq9REeVBWq5BoROhztDgFU3WwlQ9LFrYPQ
debug1: Host 'big-daddy' is known and matches the ECDSA host key.
debug1: Found key in /home/entroper/.ssh/known_hosts:10
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug2: key: /home/entroper/.ssh/id_rsa (0x7fffed1aa350), agent
debug2: key: /home/entroper/.ssh/id_dsa ((nil))
debug2: key: /home/entroper/.ssh/id_ecdsa ((nil))
debug2: key: /home/entroper/.ssh/id_ed25519 ((nil))
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/entroper/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/entroper/.ssh/id_dsa
debug1: Trying private key: /home/entroper/.ssh/id_ecdsa
debug1: Trying private key: /home/entroper/.ssh/id_ed25519
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
entroper@big-daddy's password:
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to big-daddy ([192.168.1.6]:22).
debug1: channel 0: new [client-session]
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug2: channel 0: request shell confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
```

At this point, the terminal hangs, and won't even respond to Ctrl-C.

* What's wrong / what should be happening instead: It should connect to `big-daddy` and give me a shell.  This was working at some point in the recent past (2-3 months?), I'm not certain if it stopped working after a Windows Update or not.

* Nothing that requires SSH works -- git push/pull, ssh proxy tunneling to postgres, all things that were working before.
* The network works, and HTTPS works, I can `wget https://www.google.com`.
* I can't get any host -- `big-daddy` is on my LAN, but `github.com` doesn't work either.
* I can SSH from Windows just fine, to `big-daddy` or `github.com` using Git Bash or PuTTY.  It just doesn't work on WSL.

* Strace of the failing command, if applicable: There's sensitive data in here, so I'm just posting what happened after `ssh` stopped outputting to the terminal:

```
6484  write(2, "debug1: channel 0: free: client-"..., 54) = -1 EIO (Input/output error)
6484  close(5)                          = 0
6484  close(6)                          = 0
6484  close(7)                          = 0
6484  ioctl(0, TCGETS, {B38400 -opost -isig -icanon -echo ...}) = 0
6484  ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
6484  ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
6484  ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
6484  ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
6484  ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
6484  write(2, "debug1: Killed by signal 1.\r\n", 29) = -1 EIO (Input/output error)
6484  exit_group(129)                   = ?
6484  +++ exited with 129 +++
```

**Comment by MichaelTong** [comment] 2018-08-02 15:50
This happens to me too just recently.

**Comment by carlocalica** [comment] 2018-08-02 18:49
Started noticing this on Tues.  Was fine last week.  

Surface Pro (2017)
Windows 10 Pro
Version: 1803
OS build: 17134.165

Not sure what other info is useful.

**Comment by therealkenc** [comment] 2018-08-08 01:44
Making the hangout for this #3434, since they are almost certainly the same and there is a developer bite over there.

**Comment by benhillis** [comment] 2018-08-08 21:50
@Entroper , @carlocalica - I suspect you are both running into #3252.

**Comment by LordMonoxide** [comment] 2018-08-14 15:36
@benhillis #3252 states that it is fixed in build 17728.  I'm running 17733, and SSH is still hanging (as well as git, etc.)

**Comment by Entroper** [comment] 2018-08-14 15:40
I'll see if I can check my uptime on my 16.04 instance.  I installed Ubuntu 18.04, which fixed the issue, but possibly only until it happens again (unless I update).

**Comment by LordMonoxide** [comment] 2018-08-14 15:57
I'm on 18.04

**Comment by benhillis** [comment] 2018-08-14 16:28
Marking as a duplicate of #3434.

**Closed by benhillis** 2018-08-14 16:28 UTC
