### ISSUE TITLE
I can delete mini-filtered-antivirus-self-protected files using bash.

### ISSUE THREAD

**Issue by choaw** [Microsoft/WSL#926] opened 2016-08-18 01:17 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  While I was playing with bash on Windows, I noticed that I could delete files that anti-virus self-protected using mini filter driver by typing “rm [anti-virus mini-filter-self-protected-file]” command.
  It cannot be deleted on standard Windows environment such as File Explorer and so on.
- Expected results
  Should be access denied and cannot be deleted.
- Actual results (with terminal output if applicable)
  AV-mini-filter-self-protected-files are successfully deleted using bash.
- Your Windows build number
  Windows 10 14393.51
- Steps / commands required to reproduce the error
1. I used Kaspersky anti-virus 2017 
   (Downloaded kav17.0.0.611en_10733.exe through the official US Kaspersky web site)
2. Run bash with admin privilege
3. rm [any anti-virus mini-filter-self-protected-file]

**Comment by russalex** [comment] 2016-08-18 16:52
Running bash with admin privileges (step 2 above) gives the same permissions as running a standard CMD windows with admin privileges.

To make certain there are no issues:
1) Try deleting the files in bash without running bash with admin privileges
2) Try deleting the files from a CMD prompt running as admin

**Comment by choaw** [comment] 2016-08-19 02:05
Here are what I did

1) Run CMD prompt WITH ADMIN privilege and delete Kaspersky files which are self-protected
"delete avp.com"   
-> [RESULT]  Access denied.

2) Run BASH WITH ADMIN privilege and delete Kaspersky files which are self-protected
"rm avp.com"
-> [RESULT] Deleted SUCCESSFULLY.

3) Run BASH WITHOUT ADMIN privilege and delete Kaspersky files which are self-protected
"rm getsysteminfo.exe"
-> [RESULT] Access denied.

**Comment by fpqc** [comment] 2016-08-19 05:40
@russalex Could kaspersky be using some weird undocumented security feature to prevent deletion using their signed av driver, but that is circumvented by WSL, which has native kernel access.

I'm imagining that Kaspersky's driver is blocking win32 applications from access to those files (maybe by intercepting permission requests from ntdll into the native kernel and denying them), but since Kaspersky's driver does not sit in the column of drivers between LXCORE/LXSS and the native kernel, it can't do that.

Not being part of the Kernel team (or any team) at Microsoft, and not knowing the exact architecture of the undocumented interface between the win32 subsystem and the native kernel, I am just speculating, but according to @ionescu007 (who probably understands these systems as much as an outsider can, being a key member of the ReactOS reverse engineering project) lots of antivirus software vendors like to hack around and reverse engineer the undocumented parts of Windows in order to implement their software's functions.  

We already saw on this very github repo a couple of issues where people were able to gain access to Windows system files that would normally spit back an access denied error to an ordinary win32 program and then BSOD their systems, so I don't know that it's absolutely true that you couldn't get slightly more privileged access to driver-protected files, especially when the driver is a hack.

**Comment by russalex** [comment] 2016-08-19 19:10
@choaw Thanks for bringing this to our attention.  I have reproduced the steps locally and have filed a bug internally on it.

At this time I am in the same camp as @fpqc.  Nothing looks out of the ordinary on the file or directory which would account for this behavior.  At this point I'm thinking that Kapersky is performing some out of the ordinary steps to secure the file.

As for the other issues @fpqc calls out.  We have seen those on this forum and take them very seriously. Anything that provides access or causes a BSOD has a very high priority on the team.  Due to the nature of the issues we do not always comment on them, but we do always research.

**Comment by fpqc** [comment] 2016-08-19 20:57
@russalex Yeah, I know that you guys take it seriously, but I was just giving an example of a place where during testing, one of MS's own security features was not fully engaged on a WSL process.  Since Kaspersky may also be attempting a similar sort of driver security, at least on the Win32 side, this example allows a WSL admin process to delete files that Kaspersky locks from Win32 (whence my guess that they are loading their driver between either User mode on the Win32 subsystem, or between the Win32 subsystem and the NT Kernel (unlikely because afaik, the NT Kernel team would have to sign that kind of driver directly).

**Comment by choaw** [comment] 2016-08-23 07:51
@fpqc I actually have no idea whether virus can access to WSL with admin privilege and can delete local AV file regardless of self-protection feature. 

@russalex Is there any WINAPI to gain access to WSL?


I have not reported yet, but I will do that soon.

**Comment by russalex** [comment] 2016-08-24 20:21
@fpqc Always happy to have your help and feedback.  I have been grateful for your posts on many of these threads, including this one.  Just wanted to put on the record that we take these issues seriously for everyone reading.  In this case, I am following up with the involved teams and seeing where any holes may be.

@choaw Can you please clarify "gain access" to WSL?  We do not have any APIs in this release that poke into WSL.  If this is something you're looking to do I would suggest putting an item over on our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page, along with what you're looking to do with the access.

**Comment by mikeguidry** [comment] 2016-08-25 21:03
You can however use tactics such as LD_PRELOAD, etc to 'gain access' or manipulate Linux binaries executing under WSL.  This also gives options to fix bugs, or emulate various system calls, or other functionality that is not yet completed by Microsoft.  This means that you can insert your own protection mechanisms, or create a solution to get some other currently unusable apps to function properly...

**Comment by tara-raj** [comment] 2018-06-19 20:14
This is a fairly old bug. We have since worked with AV vendors to update their APIs to support WSL-related scenarios (such as supporting pico processes). Closing this issue. Please re-open if you run into any new issues/unexpected behavior

**Closed by tara-raj** 2018-06-19 20:14 UTC
