### ISSUE TITLE
WSL2 date incorrect - critical bug unfixed for more than one and a half years

### ISSUE THREAD

**Issue by steve-kidreads-app** [microsoft/WSL#6521] opened 2021-02-05 18:08 UTC
# Environment

```WSL 2```

# Steps to reproduce
See #5324 

#  Expected behavior
System time in WSL2 is the same as system time in Windows (or at least independently synced by `ntpdate` or the like)

# Actual behavior
System time in WSL2 does not advance during sleep and therefore gets far behind realtime

# Why this is a critical bug
Important security components rely on the date being correct. X509 validation of SSL certs fail, etc.  Security packages don't get installed.  Myriad other problems occur.

# Why this has taken so long to fix
There is no indication that MSFT is working to fix it.  The first bug (#4245, 135 comments) was filed in June 2019 but inexplicably closed as "fixedinreleasedbuild" when it was not.  The current master bug appears to be #5324 (70 comments).  There's also #4677 (17 comments), #4975 (9 comments), #4677 (2 comments).  As noted in the many comments, this is a huge problem for developers.  Seems like MSFT'ers like @craigloewen-msft @mattwojo @benhillis @dimithras @mikebattista and others should care about this issue.

**Comment by dimithras** [comment] 2021-02-05 19:51
Hi, @steve-kidreads-app . I'm not a part of MSFT so I can not really help to neither rise attention to the issue nor speed up the fix.

@craigloewen-msft checks github once in two weeks, hopefully he can comment on this. As far as I see from the threads issue is not present on WSL1 so there might be an easy fix.

For now `ntpdate` in crontab seems to be a temporary solution.

**Comment by steve-kidreads-app** [comment] 2021-02-05 20:10
> For now `ntpdate` in crontab seems to be a temporary solution.

Thanks for the reply! I saw you on the WSL2 announcement blog post so I thought you were MSFT.

Unfortunately, I think that cron is [another whole mess with WSL2](https://scottiestech.info/2018/08/07/run-cron-jobs-in-windows-subsystem-for-linux/).  Apparently WSL has no standard way of running deamons.

**Comment by dimithras** [comment] 2021-02-05 20:25
>  > For now `ntpdate` in crontab seems to be a temporary solution.
> 
> Thanks for the reply! I saw you on the WSL2 announcement blog post so I thought you were MSFT.
Ohh, I was not aware I was credited. Nice to know :)
Can you share the link? 
> Unfortunately, I think that cron is [another whole mess with WSL2](https://scottiestech.info/2018/08/07/run-cron-jobs-in-windows-subsystem-for-linux/).  Apparently WSL has no standard way of running deamons.
Interesting. I have not done anything with WSL for a while, but I guess there should be more ellegant way to start cron. The same place where Windows directories get mounted. Nice matter for commit, I'll be able to look into this approximately in a week.

**Comment by steve-kidreads-app** [comment] 2021-02-05 20:57
> Ohh, I was not aware I was credited. Nice to know :)
> Can you share the link?

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by drkvogel** [comment] 2021-02-06 13:44
> There is no indication that MSFT is working to fix it.

Yep. In #5324 there are plenty of workarounds which are much appreciated and work pretty well, but none of these address the root cause which must be in the code for the WSL kernel. I've spent enough time getting involved on GitHub to work around my immediate problems and try to help other people, but I haven't heard a peep from MSFT about actually fixing the problem. Do they even look at these issues any more?

**Comment by craigloewen-msft** [comment] 2021-02-08 17:10
Hi folks! I can let you know we are looking into resolving this error. I wanted to pop into this thread to say this is something we care about and are investigating. I'll get an internal status of where we're at and come back to this update this thread. Thank you for your patience here.

**Comment by getify** [comment] 2021-02-09 03:44
@craigloewen-msft this is definitely a dupe of #5234, where many of us have been tracking this (since last June). Merge these issues so we can all be updated?

**Comment by craigloewen-msft** [comment] 2021-02-09 17:39
@getify great call. /dupe #5234 and let's follow up on the original issue.

**Closed by craigloewen-msft** 2021-02-09 17:39 UTC
