### ISSUE TITLE
Hard drive devices do not have a serial number

### ISSUE THREAD

**Issue by thegitworker** [microsoft/WSL#8244] opened 2022-04-07 10:46 UTC
### Version

Microsoft Windows [Version 10.0.19044.1586]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

20.04

### Other Software

lsblk from util-linux 2.34

### Repro Steps

sudo lsblk --raw -o name,type,serial

### Expected Behavior

```
NAME TYPE SERIAL
sda disk abc
sdb disk xyz
```
Expecting the serial number to be listed.

### Actual Behavior

```
NAME TYPE SERIAL
sda disk 
sdb disk 
```
Nothing is listed under serial.

**Comment by elsaco** [comment] 2022-04-07 14:27
@thegitworker `/dev/sda` is emulated (virtualized) by the hypervisor and does not represent a real device, thus no serial number. Try getting more info from the device with `sudo hdparm -I /dev/sda` and see what's being reported back.

**Comment by OneBlue** [comment] 2022-04-07 19:13
This indeed by design. Closing.

**Closed by OneBlue** 2022-04-07 19:13 UTC
Labels: bydesign

**Comment by thegitworker** [comment] 2022-04-08 10:22
That is bad design. It should be using the serial number of the actual HDD it is virtualizing or provide a method of obtaining the serial number of the real device. I have programs that cannot run because this serial number is inaccessible. This should not be closed and is a real issue.
