### ISSUE TITLE
Bash EXIT Trap

### ISSUE THREAD

**Issue by samu31nz** [microsoft/WSL#1430] opened 2016-11-29 04:34 UTC
* A brief description
When a bash session ends, the exit should be trappable to run an exit script, which works fine if using the bash exit command, but doesn't run if the window is closed via the window controls. On linux the exit is still trapped even when closed this way.

* Expected results
Terminal should trap exit when closed via window controls

* Actual results (with terminal output if applicable)
Bash process is killed before exit can be trapped

* Your Windows build number
14971

* Steps / All commands required to reproduce the error from a brand new installation
Close the bash terminal via the window controls and via the exit command, with an exit trap script in .bashrc (eg `trap 'touch ~/$RANDOM' EXIT`)

**Comment by rodrymbo** [comment] 2016-11-29 14:41
If I run sshd and use puTTY to log in to a bash shell, then close puTTY without exiting the bash shell, the exit is trapped. Of course, with sshd running (in another bash.exe window) it makes sense that the trap would work. So it sounds like this is pretty much the same as the issue where closing the (last) bash.exe window shuts down the whole WSL subsystem precipitously and inelegantly. But I could be wrong.

Oh, sorry, that's not an issue, it is by design. :P

I suppose you could try running with two bash.exe windows open, to see if the trap works when you close one of them, if you're looking for a workaround that doesn't involve sshd.

**Comment by fpqc** [comment] 2016-11-29 22:23
@rodrymbo To be fair, the uservoice says that they're looking at ways to implement applications running after the last bash window closes.

**Comment by jlahijani** [comment] 2017-01-07 08:36
Not sure if this is related, but when you exit Bash by closing the window (using the X icon in top right) it doesn't save you Bash history.  It does save it when running the 'exit' command however.

**Comment by JackPenry** [comment] 2020-01-03 02:15
bump. I have Ubuntu configured to start a tmux session upon launch, assuming it doesn't already exist. If I close the window, tmux and parent bash processes still exist upon relaunching. It would be preferable if an attempt to close the window followed a procedure similar to the following:
1. determine if a command is in progress and confirm close if so
2. if the user wants to continue, kill the command in process
3. exit the shell normally

**Comment by therealkenc** [comment] 2020-01-24 21:53
> Close the bash terminal via the window controls and via the exit command, with an exit trap script in .bashrc (eg trap 'touch ~/$RANDOM' EXIT)

This was addressed probably circa 17046/17134. Below on WSL 19551.

![wsl-trap-test2](https://user-images.githubusercontent.com/7049700/73106369-1bcff080-3eb0-11ea-802e-21b46687a2f1.gif)

**Closed by therealkenc** 2020-01-24 21:53 UTC
