### ISSUE TITLE
apt borked after installing ubuntu desktop?

### ISSUE THREAD

**Issue by Hifilo** [microsoft/WSL#10322] opened 2023-07-23 18:44 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.3086]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

`apt install ubuntu-desktop`

### Expected Behavior

to still be able to use apt commands as normal after installing ubuntu-desktop

### Actual Behavior

apt currently gives errors on updates

I can use ubuntu, but updating seems broken, & certain aliases like `zshrc` to launch `.zshrc` in code editor now give `zsh: permission denied`

I'm assuming it's because of running `apt install ubuntu-desktop` , but I'm not 100% sure. Maybe its a `$PATH` issue?

can this be fixed without a reinstall?

```
Failed to start apt-news.service: Transport endpoint is not connected See system logs and 'systemctl status apt-news.service' for details. 
Failed to start esm-cache.service: Transport endpoint is not connected See system logs and 'systemctl status esm-cache.service' for details. 
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB] 
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease 
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB] 
Hit:4 https://cli.github.com/packages stable InRelease 
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB] 
Hit:6 https://ppa.launchpadcontent.net/daniel-milde/gdu/ubuntu jammy InRelease 
Hit:8 https://ppa.launchpadcontent.net/neovim-ppa/stable/ubuntu jammy InRelease Hit:7 https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease 

Fetched 337 kB in 1s (236 kB/s)  <-- hangs here
```

I've tried `sudo dpkg --configure -a`

```
Setting up xserver-xorg-input-all (1:7.7+23ubuntu2) ... 
Setting up whoopsie (0.2.77) ... 
Failed to preset unit: Transport endpoint is not connected /usr/bin/deb-systemd-helper: error: systemctl preset failed on whoopsie.path: No such file or directory Failed to reload daemon: Transport endpoint is not connected
[process exited with code 1 (0x00000001)]
```

**Comment by OneBlue** [comment] 2023-07-25 21:17
Thank you for reporting this @Hifilo. Is systemd enabled in your distribution ? 

What's the output of `cat /etc/wsl.conf` ?

**Comment by Hifilo** [comment] 2023-07-25 22:55
> Thank you for reporting this @Hifilo. Is systemd enabled in your distribution ?
> 
> What's the output of `cat /etc/wsl.conf`?

I did enable it for the distro before the one I had this issue with. However I can't confirm for this issue because I backed up & reset.

It is currently disabled & I haven't enabled it yet. I can see whether running `apt install ubuntu-desktop` causes the same problem on a fresh install if necessary.

**Comment by OneBlue** [comment] 2023-08-08 18:14
Ok. Closing for now but feel free to reopen if the issue happens again.

**Closed by OneBlue** 2023-08-08 18:14 UTC

**Comment by pwang2** [comment] 2023-08-26 02:18
I do have the same error today.  All apt commands will hang..

![image](https://github.com/microsoft/WSL/assets/1592014/396966b0-4243-454c-9946-a9cd52ff0d61)

**Comment by pwang2** [comment] 2023-08-26 03:31
a long clueless google leads me to a simple fix as below.
```sh
 sudo rm -rf /etc/acpi/events
```

**Comment by AlphaSierraHotel** [comment] 2023-08-29 01:12
I found this by searching the error messages I was getting trying to update 22.04.

I ran 'sudo apt install ubuntu-desktop' command in a fresh new install of 18.04 yesterday and first noticed this behaviour in my 22.04 (default) distro today but that may be a coincidence.  I checked my 22.04 dpkg.log and I had installed ubuntu-desktop on 22.04 in April of 2022.  I haven't run the 22.04 distro for about 4 months but I know I've done updates periodically ever since the initial install - dpkg.log has 34 unique dates in it.

I don't have a problem with 18.04, just 22.04.  Renaming the /etc/acpi/events folder did indeed allow me to perform the usual update procedures but I first had to kill the 'unattended-upgrade' process which seemed to have hung. Renaming the events folder back to the original name brings back the errors but allows the apt command to proceed.  I'd be happy to provide additional input if needed.  I do have systemd enabled.

C:\Users\allen>wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134

**Comment by Yokinshita** [comment] 2023-10-20 02:53
I have the same problem.  I run "apt install ubuntu-desktop"  but it failed. After that, every apt command will hang as well other commands like systemctl, reboot... I solved this probelm using the method from @pwang2 .
The cat /etc/wsl.conf outpus:
![image](https://github.com/microsoft/WSL/assets/45240010/b05cb1bd-8fc7-4462-a461-15260fc8737d)
And the system details:
OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
Kernel: 5.15.123.1-microsoft-standard-WSL2
Shell: zsh 5.8.1

**Comment by maffinyep** [comment] 2024-01-21 22:12
I reproduced the same issue while following the official documentation [https://docs.docker.com/desktop/wsl/](https://docs.docker.com/desktop/wsl/)

WSL version: `2.1.0.0`
Kernel version: `5.15.137.3-1`
Windows version: `10.0.23619.1000`
Ubuntu `22.04.3 LTS`
Docker Engine: `24.0.7`

**Comment by Omico** [comment] 2024-02-08 03:45
> a long clueless google leads me to a simple fix as below.
> 
> ```shell
>  sudo rm -rf /etc/acpi/events
> ```
Thanks, you saved my life! It works in my situation.

WSL version: `2.0.9.0`
Kernel version: `5.15.133.1-1`
WSLg version: `1.0.59`
MSRDC version: `1.2.4677`
Direct3D version: `1.611.1-81528511`
DXCore version: `10.0.25131.1002-220531-1700.rs-onecore-base2-hyp`
Windows version: `10.0.22631.3085`
Docker Desktop `4.27.1 (136059)`

**Comment by wingkuitsoi** [comment] 2024-02-12 14:59
> a long clueless google leads me to a simple fix as below.
> 
> ```shell
>  sudo rm -rf /etc/acpi/events
> ```

This error has gone for me:

> /usr/bin/deb-systemd-helper: error: systemctl preset failed on xxxxx: No such file or directory

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3085

**Comment by Firsto** [comment] 2024-03-07 19:30
same problem.

> a long clueless google leads me to a simple fix as below.
> 
> ```shell
>  sudo rm -rf /etc/acpi/events
> ```

save my day.'

how it works?

**Comment by AstroJosePC** [comment] 2024-03-12 05:31
same problem! I couldn't find a solution until I found the fix from @pwang2 
This gave me a big scare.

Linux Distribution: Ubuntu-22.04
WSL version: 2.1.4.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22635.3286

**Comment by PelerYuan** [comment] 2024-03-29 03:44
> a long clueless google leads me to a simple fix as below.
> 
> ```shell
>  sudo rm -rf /etc/acpi/events
> ```

works pretty good on ubuntu22.04
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296

**Comment by pwang2** [comment] 2024-09-15 18:51
It is related to ACPI support.  More details can be found here. https://github.com/microsoft/WSL/issues/10059

It is suggested apt-mark hold the acpi related package before we run apt update.   Still I found it is an unwise thing to install all the Bloatware from Ubuntu-desktop package to WSL.  

```
sudo apt-mark hold acpid acpi-support
```

**Comment by Sherlock-feng** [comment] 2024-10-08 05:22
> a long clueless google leads me to a simple fix as below.
> 
> ```shell
>  sudo rm -rf /etc/acpi/events
> ```

resolve my problem
Setting up whoopsie (0.2.77) ...
Failed to preset unit: Transport endpoint is not connected
/usr/bin/deb-systemd-helper: error: systemctl preset failed on whoopsie.path: No such file or directory

**Comment by lizhongneu** [comment] 2024-12-09 07:14
> a long clueless google leads me to a simple fix as below.
> 
>  sudo rm -rf /etc/acpi/events

tested, very useful
