### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket...

### ISSUE THREAD

**Issue by hacdias** [Microsoft/WSL#745] opened 2016-08-03 20:27 UTC
Hello!

I'm trying to install MySQL on Bash on Ubuntu on Windows. I'm running bash as admin and run `sudo apt-get install mysql-server`. In the middle of the installation I can find this:

```
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of stop.
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
runlevel:/var/run/utmp: No such file or directory
invoke-rc.d: policy-rc.d denied execution of start.
```

And when I start mysql, I get this:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

Are this sockets not supported yet or am I doing something wrong?
Thanks!

**Comment by adeeb1** [comment] 2016-08-04 00:06
I had this issue as well. MySQL is installed but could not be run automatically. You can start MySQL with this command:

`sudo /etc/init.d/mysql start`

**Comment by hacdias** [comment] 2016-08-04 07:21
Hey! Thanks for the tip. I'll hear forward to know if this is going to be fixed.

**Comment by sunilmut** [comment] 2016-08-05 21:37
@hacdias - Thanks for reporting this. Is manually starting MySQL using `mysql start` working for you? Currently, in WSL we do not start the 'upstart' service and so you are seeing the failure. We are looking into supporting some of these services\deamons.

**Comment by hacdias** [comment] 2016-08-05 21:38
```
hacdias@HENRIQUE-PC:/mnt/c/Users/Henrique Dias$ mysql start
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

I don't think so :(

**Comment by ATouhou** [comment] 2016-08-08 02:51
Same thing here
![image](https://cloud.githubusercontent.com/assets/6802820/17467974/b3efa29c-5d23-11e6-962b-35c0dad55cb3.png)

**Comment by mbeijen** [comment] 2016-10-12 20:58
I updated to the xenial-based image (ref: https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) and now mysql runs just fine!

**Comment by hacdias** [comment] 2016-10-13 09:20
Maybe because of one of the new syscall support. I'll create a virtual machine with the insider preview to test it. Thanks for letting us know that! :)

**Comment by aniskhan001** [comment] 2016-11-07 18:22
Same for me as well. Happened right after installation while tried to logging in. Build 14959.

**Comment by VoLuong** [comment] 2017-02-19 04:27
Is the xenial based image officially supported yet ? I found some method to do the upgrade on the internet but people say this is neither supported by cannonical or windows

**Comment by sunilmut** [comment] 2017-03-01 23:24
@VoLuong - Yes, Xenial is officially supported in the [Insider builds](https://insider.windows.com/). It will be also be officially supported in the Windows `Creators Update` release.

**Comment by Bigg-Mike** [comment] 2017-04-25 12:04
Hi

I have the same issue with Mysql.

> mysql --host=localhost --user=root -p
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

Not exactly the same error with

> mysql --host=127.0.0.1 --user=root -p
Enter password:
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

i try this 

> mysql -uroot -p --host=localhost --port=3308 --protocol=TCP
Enter password:
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)

Build 15063.138

Need some help please... thank you! :-)

**Comment by db2k** [comment] 2017-04-28 06:42
This is a big problem for me right now. My usecase looks like this:

I'm handling my local development environment with AMPPS and the AMPPS GUI so the service is already running in the background and I can control it without using the terminal/cmd.

On my development stack I have an automated script for cloning database content from my remote host to my local machine and on OSX we're using `localhost` by default, which means I have to change the mysql host to 127.0.0.1 everytime when I want to work on some internal project and change it back to localhost later again.

Is there any progress on this issue? I would love to see it resolved asap since it's not the expected behaviour (if no mysql server is running on the bash, I would like to rather connect to the one running in Windows directly).

Looking forward, thank you!

**Comment by mbeijen** [comment] 2017-04-29 07:06
@db2k your problem is not completely related to this issue. This issue was about the fact that in earlier builds of Bash on Ubuntu on Windows, not enough linux was emulated to successfully run MySQL. That has been fixed with newer builds.

Your issue is, in MySQL, `localhost` is considered a special name and mysql will try to connect using unix socket instead of TCP/IP if you tell it to connect to localhost. If you run MySQL in Windows, that one is available through TCP/IP and named pipes, not through local socket.

You already found a workaround which is specifying 127.0.0.1 as the IP address which forces TCP/IP and then reaches the Windows MySQL.

Alternate solutions would be to specify a different hostname for your development environment in the `hosts` file on your local machine and use that, in which case you need to change the configuration file in your script anyway, or to switch to using MySQL in the bash on ubuntu on windows, which might not be an option for you because you use AMPPS.

I guess the best solution for you might be to modify the automated script you have to take a parameter for the MySQL host location, so it's not hard-coded to `localhost` anymore. Maybe you can have it use an environment variable?

**Comment by Kubitomakita** [comment] 2017-06-12 15:08
Bump, same here

**Comment by bdbch** [comment] 2017-06-27 21:45
@mbeijen thanks for the information. It worked out with `--protocol=tcp` but I had to rewrite some lines of the CLI until I got to the point where some parts weren't editable. :)

Still looking for some better solution.

**Comment by danwhitston** [comment] 2017-07-10 11:16
Bump. Same issue with a fresh MySQL2 install.

**Comment by bdbch** [comment] 2017-09-05 20:59
I found a temporary solution. Open `/etc/mysql/mysqld.conf.d/mysqld.conf` and add the following to the bottom of the file

```
[client]
protocol=tcp
```

This will force the mysql client to use TCP clients instead of unix sockets. That way you can connect to your localhost database running on Windows.

**Comment by tara-raj** [comment] 2018-05-29 20:59
WSL now supports MySQL, so closing this issue. Refer to this comment - https://github.com/Microsoft/WSL/issues/745#issuecomment-298152054. Please re-open and provide additional details if you run into this issue again.

**Closed by tara-raj** 2018-05-29 20:59 UTC

**Comment by bdbch** [comment] 2018-05-31 18:16
@tara-raj thats great to hear. will this be updated via Windows Store or come with the next major Windows update?

**Comment by ljh131** [comment] 2018-12-16 13:32
I had similar issue but slightly different. I can connect through unix socket but not through tcp. I checked mysql error log and it was very fine (it says server socket created on 127.0.0.1). 

The problem was due to the Korean security programs.  Stopping entire security programs in services.msc and problem is solved.

Don't know exactly what it is, but I think one of them interrupt tcp communication with port 3306.

**Comment by ljh131** [comment] 2018-12-16 13:37
I had similar issue but slightly different. I can connect through unix socket but not through tcp. I checked mysql error log and it was very fine (it says server socket created on 127.0.0.1).

The problem was due to the Korean security programs for internet banking. Stopping entire security programs in services.msc and problem is solved.

Don't know exactly what it is, but I think one of them interrupt tcp communication with port 3306.

**Comment by NarniaT** [comment] 2019-01-24 17:53
How is this said to be fixed? I'm having the same issue.

**Comment by HenkPoley** [comment] 2019-04-25 09:14
Just dropping something related here:

Say you run `mysqld` under Windows (Win64). And you want to connect _from WSL_. It will try to connect to through a socket file (named pipe), but that won't work. Here's how to do that:

```
mysql --protocol=TCP
```

You of course need to add all your own options (e.g `-u <name> -p`).

You can set this as the default behaviour. ```sudo vim /etc/mysql/mariadb.conf.d/50-client.cnf```, under `[client]` comment out the socket line with a `#`, add a line that reads `protocol = TCP`. The path of this file might be different with an actual Oracle MySQL install, instead of MariaDB.

https://stackoverflow.com/a/55844865/273668

**Comment by johnini** [comment] 2019-07-23 00:34
I found that I needed to stop mysql service running in windows before I could run mysql in WSL. 

I already have another mysqld server running on port: 3306

See this answer on S/O: https://stackoverflow.com/questions/44247342/starting-mysql-on-bash-on-ubuntu-on-windows

**Comment by fightTone** [comment] 2020-01-31 11:46
> @mbeijen thanks for the information. It worked out with `--protocol=tcp` but I had to rewrite some lines of the CLI until I got to the point where some parts weren't editable. :)
> 
> Still looking for some better solution.

yea same, it works 
$ mysql -u root -p --protocol=tcp

**Comment by aderchox** [comment] 2020-04-27 10:02
I still have this issue.
It neither works with `--protocol=tcp` nor with `sudo /etc/init.d/mysql start`. I've also made sure I've got no previously mysql installation on my system and no mysql processes are running.
```
DESKTOP*** ~$ sudo /etc/init.d/mysql start
[sudo] password for ***:
 * /etc/init.d/mysql: WARNING: /etc/mysql/my.cnf cannot be read. See README.Debian.gz
 * Starting MySQL database server mysqld                                                                No directory, logging in with HOME=/
```

**Comment by bdbch** [comment] 2020-04-27 11:24
@aderchox did you try adding the tcp information to your mysql configuration?

https://github.com/microsoft/WSL/issues/745#issuecomment-327301645

**Comment by aderchox** [comment] 2020-04-27 12:04
@bdbch  Unfortunately I've gone through some steps since when I commented here but fortunately I can say what I observed in each step and what I did afterwards for being clearer about my problem(Prior apologies: If a step is absurdly wrong, my linux knowledge isn't deep)(Also sorry it's got a bit long).
STEP1:
(answering to your question): Yes, but I get this error: `Error writing /etc/mysql/mysqld.conf.d/mysqld.conf: No such file or directory` when I try to save that file (opened with `sudo nano`).
I even cleaned up everything and installed mysql from scratch, as many answers suggest:
```
sudo apt-get remove --purge *mysql*
sudo rm -rf /etc/mysql /var/lib/mysql
sudo apt-get remove --purge *mariadb*
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt update
sudo apt upgrade
sudo apt-get install mysql-server
```
But still that configuration file doesn't even exist for me.
STEP2:
I see that running `mysql` says `mysql.exe: command not found` , so I think the main problem is with finding the executable from PATH. But the `/etc/bin/mysql` exists and also the `/etc/bin` is in the PATH, so I don't know why I get the command-not-found error when I run `mysql`. Anyway, I run the `/etc/bin/mysql` and it gives another error:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
Accidentally, I try `sudo mysql` and it connects to the mysql server and shows the version 5.7.  I.e., only adding the `sudo` made it work! I am not a Linux guru but I [used to] think that when `sudo` is needed I should get a `permission error` and not a `mysql.exe: command not found`.
STEP3:
I'm following a tutorial which is based on MySQL 8. So I think _probably_ upgrading to MySQL version 8 might fix both of my issues. So I follow the instructions here (https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-replacing)[Replacing a Native Distribution of MySQL Using the MySQL APT Repository]. I add the MySQL APT repositories to my repository list and then apt update & re-install the mysql-server. This time, I get a window which asks about the version and I choose version 8. Installation finishes and `sudo mysql --version` gives `mysql  Ver 8.0.20 for Linux on x86_64 (MySQL Community Server - GPL)`, HOWEVER, this time even `sudo mysql` gives the error: `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`. Now even `sudo` is not helping!

**Comment by aderchox** [comment] 2020-04-27 22:08
For future visitors, I fixed my problem with MySQL version 8 installation using [this comment](https://github.com/Microsoft/WSL/issues/3631#issuecomment-465966498):

> Direct installation of MySQL 8.x will not work on WSL, even after your have selected 8.x as the default install candidate. It has problem starting the server.
> 
> Steps below should work (tried out on few WSL instances):
> 
> **Remove MySQL 8.x:**
> sudo apt-get purge mysql-server mysql-client
> sudo apt-get -y autoremove
> **Change to MySQL 5.x candidate:**
> sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb
> (if you don't have it, get it from here: https://dev.mysql.com/downloads/repo/apt/)
> **Double check current apt policy of MySQL is 5.x:**
> sudo apt policy mysql-server (it will show 5.x is the default candidate)
> sudo apt-get update
> **Install MySQL 5.x**
> sudo apt-get -y install mysql-server
> sudo service mysql start (this should work without error)
> **Change to MySQL 8.x candidate**
> sudo dpkg -i mysql-apt-config_0.8.12-1_all.deb (select 8.x)
> sudo apt-get update
> sudo apt policy mysql-server (it will show 8.x is the default candidate)
> **Install MySQL 8.x**
> sudo apt-get -y install mysql-server
> **Modify a script as there is a bug**
> sudo nano /etc/init.d/mysql
> (search for a line ". /usr/share/mysql/mysql-helpers" and change it to
> ". /usr/share/mysql-8.0/mysql-helpers")
> **Upgrade system tables to MySQL 8.x**
> sudo service mysql start (this should start without error)
> sudo mysql -u root -p

I checked the error log in /var/log/mysql/error.log and realized there was a problem with this description "Linux Native AIO interface is not supported on this platform." so I Googled it and bumped into the [very helpful] above comment. Hope this also works for you!

**Comment by vinithmathews** [comment] 2020-05-11 08:33
I have Windows 10 and Centos 7 Distro. I am getting the mysql 2002 error as well as apache is also failing once I restart the system. How I solved this is shown below: 

My major issue is httpd directory is getting deleted in /run directory causing Apache Server to fail

Also /var/run folder is missing mysqld folder after restart which will block the creation of mysql.pid

So what we need to do is

`cd /run
sudo mkdir httpd

cd /var/run
sudo mkdir mysqld

sudo chown mysql:mysql mysqld

sudo service httpd start
sudo service mysqld start`

And the Server as well as MySQL should start. 

[This issue is for MySQL 8]

Hope this helps some one. 

[This is a temporary solution. To avoid repeating the process, add the above steps to a shell script and execute the shell script each time the WLS is invoked]

**Comment by sucicf1** [comment] 2020-07-15 21:24
@aderchox Thank you, after reseting debian to remove the old mysql8 packages your solution worked

**Comment by Estebanrg21** [comment] 2021-02-12 05:50
[@aderchox's  answer](https://github.com/microsoft/WSL/issues/745#issuecomment-620261681) helped me, I'm on windows 10 with wsl 2 running ubuntu 18.04. in my case the problem was in the installation of MySQL using the current apt .deb package.
just adding to @aderchox's answer, the link of mysql-apt-config_0.8.15-1_all.deb [is here](https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb)

**Comment by MHamzaRajput** [comment] 2021-04-05 07:18
I have solved this issue from the below answere. Yaho0o0o.
https://stackoverflow.com/questions/64883580/wsl-cant-connect-to-local-mysql-server-through-socket-var-run-mysqld-mysqld/66949451#66949451

**Comment by Inewcoming** [comment] 2021-09-10 14:18
This problem can be caused by out of memory. I have deployed a 1 core CPU,1G memory VPS. I encountered this problem "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)". I tried many methods, but they were not working. I see this page, https://www.digitalocean.com/community/questions/trying-to-install-mysql-but-i-cannot-start-the-service-and-cannot-locate-mysqld-sock. It work!

**Comment by Menelion** [comment] 2022-08-01 21:12
for me nothing works for MariaDB 10.8, Windows 10 and Ubuntu 20.04 in WSL. 

```shell
andre@andre-vivobook:~$ mysql -v                                                                                        
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)                          
andre@andre-vivobook:~$ sudo service mysql start                                                                        
mysql: unrecognized service                                                                                             
```

Any ideas please? Thanks!

**Comment by OmerMessing** [comment] 2023-04-16 08:25
Hi, this problem keep persisting and I have the latest versions of WSL2, Ubuntu 22 and mysql. The only thing that solved it is the following stackoverflow post, and I have to run 3 commands each and every time I open WSL or else I will get the following error: 

`Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

These are the commands I always run:
```
sudo mkdir /var/run/mysqld
sudo chmod 777 -R /var/run/mysqld
mysqld 
```

Is there anyone working on this issue to fix this in future versions?
