### ISSUE TITLE
HCS_E_CONNECTION_TIMEOUT after adding systemd entry into wsl.conf

### ISSUE THREAD

**Issue by vomidug** [microsoft/WSL#9442] opened 2023-01-05 15:29 UTC
### Version

Microsoft Windows [Version 10.0.19045.2364]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

6.x.x

### Repro Steps

My distro was imported from a file and now it has ext4.vhdx file.
I was trying to enable systemd in my machine creating a file /etc/wsl.conf and adding
```
[boot]
systemd=true
```
as it is mentioned in the instruction on MS website.
After performing ```wsl --shutdown``` my instance does not boot up anymore with an error attached
![image](https://user-images.githubusercontent.com/38423889/210810412-1059ad7e-8cd7-4aea-9c3e-733d97002a4b.png)
Russian text means smth like "Timeout due to no response from a virtual machine or a container".
tried reinstalling wsl and hyper-v from apps and features, upgraded wsl by ```wsl --update```, tried full reboot by rebooting with shift-key -> no result, wsl does not boot up.
Please, assist and thank you in advance.

### Expected Behavior

My wsl distro would boot up normally, no matter with systemd or not.

### Actual Behavior

WSL is not running with error from a screenshot

**Comment by vomidug** [comment] 2023-01-05 15:50
>export, unregister and import again

Not suitable, because in the end it gives the same "no response from VM or container" error and the same Error code: Wsl/Service/HCS_E_CONNECTION_TIMEOUT.
>opening \\wsl$\ in explorer

just hangs, not opening. This is working for other distros, which are working fine the usual way too

**Comment by vomidug** [comment] 2023-01-05 15:50
[WslLogs-2023-01-05_19-48-25.zip](https://github.com/microsoft/WSL/files/10353541/WslLogs-2023-01-05_19-48-25.zip)
Attaching logs

**Comment by benhillis** [comment] 2023-01-05 19:29
It looks like something is wrong with the vhdx, there is a mesasge from the kernel about not being able to find the ext4 filesystem:

[   31.604432] EXT4-fs (sdc): VFS: Can't find ext4 filesystem

**Comment by OneBlue** [comment] 2023-01-05 21:30
@vomidug: Looking at the distribution registration, you have two distributions (Arch and Arch2) registered in the same place (C:\\Users\\vomidug\\Downloads\\Arch). 

This probably led to the disk being corrupted.  I'd recommend recovering the data out of the distro (if any), unregistering both a starting over. If you need instructions on how to recover the data, see [Mouting a VHD in WSL](https://learn.microsoft.com/en-us/windows/wsl/wsl2-mount-disk#mount-a-vhd-in-wsl)

Closing since the corruption is most likely caused by the dual registration

**Closed by OneBlue** 2023-01-05 21:30 UTC
