### ISSUE TITLE
OS build 17134.5 Stop Code: SYSTEM_THREAD_EXCEPTION_NOT_HANDLED FLTMGR.SYS

### ISSUE THREAD

**Issue by mattmon1** [Microsoft/WSL#3148] opened 2018-05-04 19:24 UTC
I used the insider's program to upgrade some W10 machines:
From:  Version 1803 (OS build 17.134.1) - RTM
To: Version 1803 (OS build 17134.5) - GA

After upgrading, running ubuntu.exe from a command window with administrator perms yields:
StdOut: Performing one-time upgrade of the Windows Subsystem for Linux file system for this distribution.
Machine: <blue screen>
Stop Code: SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
What Failed: FLTMGR.SYS

I'm getting this error on two different machines. Just reaching out to see if others are experiencing the same issue and if there is a fix pending?

Thanks,
Matt

**Comment by Biswa96** [comment] 2018-05-04 19:27
MS programmers may want Memory dump. Did you dump the kernel memory because the problem shows a driver issue?

**Comment by Brian-Perkins** [comment] 2018-05-04 19:48
@mattmon1, do you have Bitdefender installed? There was a similar issue reported [here](https://github.com/Microsoft/WSL/issues/2982#issuecomment-386137077).

**Comment by mattmon1** [comment] 2018-05-04 20:30
@Biswa96 Per WSL post instructions, a mini-dump has been sent to secure@microsoft.com.

**Comment by Biswa96** [comment] 2018-05-04 21:40
Did you try to uninstall Bitdefender and run WSL? In that thread OP said that issue was solved by uninstalling it.

**Comment by mluypaert** [comment] 2018-05-07 11:29
+1, same problem here after updating to Windows 1803 (OS build 17134.1). After uninstalling Bitdefender (Endpoint security tools here) Ubuntu on windows works, but as soon as I installed Bitdefender again, the blue screens are back.

**Comment by mattmon1** [comment] 2018-05-07 17:16
Attached are my test findings. In short, the issue seems due to filter driver collisions between W10, SnagIt and Bitdefender.

Uninstalled Bitdefender
Ran administrator command prompt & executed ubuntu.exe - ASW
Installed Bitdefender and rebooted(required)
Ran administrator command prompt & executed ubuntu.exe - ASW

Bitdefender reported need to reboot for engine update and rebooted
Bitdefender enabled Bitdefender Firewall when Skype for business opened after reboot
Bitdefender installed Engine Update 6.2.36.1014 -> 7.75907(11861612)
Ran administrator command prompt & executed ubuntu.exe - ASW
Ran Check for Bitdefender updates - Updated to 7.75908(11862372)
Ran check for Bitdefender updates - No update available
Ran administrator command prompt & executed ubuntu.exe - ASW

Installed SnagIt & Rebooted
Ran administrator command prompt & executed ubuntu.exe - Blue Screen FLTMGR.SYS
Uninstalled SnagIt & Rebooted
Ran administrator command prompt & executed ubuntu.exe - Blue Screen FLTMGR.SYS
Uninstalled Bitdefender
Ran administrator command prompt & executed ubuntu.exe - ASW

Installed Bitdefender and rebooted
Bitdefender reported need to reboot for engine update and rebooted
Bitdefender enabled Bitdefender Firewall when Skype for business opened after reboot
Bitdefender installed Engine Update 6.2.36.1014 -> Updated to 7.75908(11862372)
Ran administrator command prompt & executed ubuntu.exe - ASW
Running Bitdefender Full Scan - In progress

**Comment by mattmon1** [comment] 2018-05-08 13:26
Uninstalled Ubuntu and disabled the WSL feature. After reboot, Bitdefender and SnagIt both perform fine - no Blue screens. My plans are to use Cygwin for my Linux needs on W10 and migrate back to WSL Ubuntu when it has stabilized. My hopes are that the WSL team can resolve this issue soon.

**Comment by mattmon1** [comment] 2018-05-08 13:29
The SYSTEM_THREAD_EXCEPTION_NOT_HANDLED Blue screen was also encountered after 1803 upgrade on a W10 machine running Windows defender and firewall, where Bitdefender and SnagIt were not installed. This same machine, earlier, experienced rolling exceptions during WSL ubuntu command invocations (#2931) when defender/firewall were actively scanning. I worked around the rolling
exceptions issue per the workaround documented in #2931.

**Comment by DamienGombaultRecia** [comment] 2018-05-18 17:36
Hi.
I have opened a ticket on the Bitdefender support :
> Thank you for reaching Bitdefender Enterprise Support.
> We are aware of this issue and it will be resolved on the 24th of May when the new product update will be released.

**Comment by DamienGombaultRecia** [comment] 2018-05-23 09:48
Hi.
The problem is fixed with the Bitdefender Endpoint Security Tools 6.6.1.36 version.
This version is available in the Fast Ring channel.
The update should reach the Slow Ring channel soon.

**Comment by heepdog** [comment] 2018-05-24 12:16
Received Bitdefender update this morning and can confirm it was fixed.

**Closed** 2018-05-24 15:30 UTC
Labels: external
