### ISSUE TITLE
VS Code won't open in Windows Bash

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/WSL#1233] opened 2016-10-20 15:24 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  I was able to install the VS Code deb version. I got Xserve running in Windows 10, but unfortunately is giving an error when executing "code":
  /usr/share/code/bin/../code: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
- Expected results
  To be able to open VS Code in Windows Bash in Xwindows.
- Actual results (with terminal output if applicable)

maxt@MTrinidadLT2:/mnt/c/Users/mtrinidad/Downloads$ sudo dpkg -i code_1.6.1-1476373175_amd64.deb
[sudo] password for maxt:
(Reading database ... 46508 files and directories currently installed.)
Preparing to unpack code_1.6.1-1476373175_amd64.deb ...
Unpacking code (1.6.1-1476373175) over (1.6.1-1476373175) ...
Setting up code (1.6.1-1476373175) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
maxt@MTrinidadLT2:/mnt/c/Users/mtrinidad/Downloads$ code
/usr/share/code/bin/../code: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
maxt@MTrinidadLT2:/mnt/c/Users/mtrinidad/Downloads$
- Your Windows build number
  Windows 10 Pro Insider Preview - Build 14946
- Steps / All commands required to reproduce the error from a brand new installation 
  VS Code installation went without any errors:
  maxt@MTrinidadLT2:/mnt/c/Users/mtrinidad/Downloads$ sudo dpkg -i code_1.6.1-1476373175_amd64.deb
  [sudo] password for maxt:
  (Reading database ... 46508 files and directories currently installed.)
  Preparing to unpack code_1.6.1-1476373175_amd64.deb ...
  Unpacking code (1.6.1-1476373175) over (1.6.1-1476373175) ...
  Setting up code (1.6.1-1476373175) ...
  Processing triggers for mime-support (3.54ubuntu1.1) ...
- Strace of the failing command
  N/A
- Required packages and commands to install
  N/A

![winbashcodeerr_2016-10-20_11-21-45](https://cloud.githubusercontent.com/assets/19892435/19566259/9b6afd48-96b7-11e6-9565-472b3c6de622.jpg)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment] 2016-10-20 17:09
I haven't tried vcXsrv for vscode, but you will need at least that, and to export DISPLAY=:0

**Comment by qazwsxedcrfvtg14** [comment] 2016-10-20 17:10
In Build 14951
You can try to add 
alias code="\"/mnt/c/Program Files (x86)/Microsoft VS Code/Code.exe\""
in ~/.bashrc 
(You need to install VS Code in windows first.)
Then you can type "code FILENAME" to open file.
(but this only work fine in windows directory(/mnt/c/, /mnt/d/) )

**Comment by MaximoTrinidad** [comment] 2016-10-20 17:32
I'm way ahead!  I've been using vcXsrv for a while. 

As I mention before, vs code is loaded.  I'm just still getting the same error message when its trying to load: 

"/usr/share/code/code: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory"

And, I don't want to run it from Windows Program files as is already loaded under the Linux subsystem.  

See images Windows 10, BASH, and vcXsrv as I created some Linux batch to run some Linux apps.
It's so close for VS Code work!

![winbashcodeerr2_2016-10-20_11-21-45](https://cloud.githubusercontent.com/assets/19892435/19570731/3467daf0-96c9-11e6-8323-0007b4b20b5d.jpg)

![winbashcodeerr3_2016-10-20_11-21-45](https://cloud.githubusercontent.com/assets/19892435/19570739/3dd3b370-96c9-11e6-864a-9f35a5077a24.jpg)

**Comment by MaximoTrinidad** [comment] 2016-10-20 17:37
Hum!  As I posted the previous code, I realized the code for VS Code, I found the "standard install location".  It has to be something in BASH because this VS Code work in Linux perfect.

![vscode_code_2016-10-20_13-35-38](https://cloud.githubusercontent.com/assets/19892435/19571019/6184bde0-96ca-11e6-955f-c8db77828380.jpg)

**Comment by therealkenc** [comment] 2016-10-21 07:47
"It's so close for VSCode to work". Electron apps are based on a large body of software not currently supported by WSL. See #648.

Weird you don't have libXss though, given that you've made it this far. That's the Screen Saver extension library, which should have come along for the ride with your other X11 stuff. You can install it with `sudo apt-get install libxss1`, but that isn't going to help your cause much. Sublime Text works well, for what it's worth.

**Comment by MaximoTrinidad** [comment] 2016-10-21 13:46
Awesome!  

Now the error message changes to:
maxt@MTrinidadLT2:/mnt/c/Windows/System32$ code
/usr/share/code/bin/../code: error while loading shared libraries: **libgconf-2.so.4**: cannot open shared object file: No such file or directory

:)

**Comment by fpqc** [comment] 2016-10-21 14:01
Sounds like the next thing you need is gtk?

**Comment by therealkenc** [comment] 2016-10-21 14:02
Do `sudo apt-get install ubuntu-desktop` so at least you have the bits and pieces needed to run graphic apps, including firefox. All of which is [unsupported](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250499-support-for-x-server-running-in-windows-on-the-sam?tracking_code=6be7122042c59b213451b9198f208f27) by WSL at the moment, but like the man said if it works you can go and have fun. ;)

**Comment by MaximoTrinidad** [comment] 2016-10-21 14:05
@therealkenc 

Found it missing library: http://stackoverflow.com/questions/37624225/shared-libraries-libgconf-2-so-4-is-missing 

So I ran:
sudo apt-get install Gconf2

Now, when executing "code". No errors but is not showing on the screen.  
But, I'm use the cmd "top" to list all services running and it showing three "code" running.

I'm almost there!

Any ideas are Welcome!!

![bash_code_2016-10-21_9-57-01](https://cloud.githubusercontent.com/assets/19892435/19601117/e297785e-9775-11e6-819c-ea92224f413d.jpg)

**Comment by therealkenc** [comment] 2016-10-21 14:17
From here mostly my idea would be to recompile [libchromiumcontent](https://github.com/electron/libchromiumcontent) and figure out why glibc's pthread implementation is setting `FUTEX_CMP_REQUEUE_PRIVATE` on `futex()` even though no special flags seem to be set anywhere in the source. That's where I got last time I looked, anyway.

**Comment by MaximoTrinidad** [comment] 2016-10-21 15:01
After installing xubuntu-desktop, and running the "code" from "nautilus" I can see a message pop out:

Home directory not accessible: Permission denied
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
libGL error: failed to load driver: swrast
[75:1021/104943:FATAL:thread_helpers.cc(44)] Check failed: 3UL <= task_stat.st_nlink (3 vs. 1)
#0 0x000001e0962e <unknown>
#1 0x000001e1f23b <unknown>
#2 0x000001261765 <unknown>
#3 0x00000258737f <unknown>
#4 0x000002586d16 <unknown>
#5 0x0000012711f8 <unknown>
#6 0x000001270672 <unknown>
#7 0x000001203e97 <unknown>
#8 0x000001202970 <unknown>
#9 0x0000033a9313 main
#10 0x7fa3b30e1f45 __libc_start_main
#11 0x000000574d79 <unknown>

![bash_code2_2016-10-21_9-57-01](https://cloud.githubusercontent.com/assets/19892435/19603047/a88d0fb8-977d-11e6-9b3b-4412683c217d.jpg)

**Comment by therealkenc** [comment] 2016-10-21 15:06
Yes that's (3) in the list [here](https://github.com/Microsoft/BashOnWindows/issues/648#issuecomment-233163399). You might want to take the rest of this over to that thread.

**Comment by MaximoTrinidad** [comment] 2016-10-21 15:24
Ah! I'm guessing I'm running into a dead-end route.  I'm finally getting a grip on Linux but I reach my limit now.  Only I could make the code to come up. :P 

I'm will follow the other thread then.

Thanks @therealkenc!

**Comment by benhillis** [comment] 2016-10-21 15:27
@Manouchehri Shameless plug for running the Windows version of VSCode with our new interop feature :)

**Comment by MaximoTrinidad** [comment] 2016-10-21 15:39
Just to be clear! I know I can run Windows VS Code and point to the Linux subsystem folder where my scripts are stored.  I just wanted to be able to install the debian version of Code and run it separate from the Windows version. Just for demo purpose!

I think it would be nice if is possible.
:)


:)

**Comment by therealkenc** [comment] 2016-10-21 15:45
VS Code works beautifully with the new interop. Really fantastic work. Prepare for the flood of "VS Code can't edit .bashrc in my home directory" issues though, because it's going to be nonobv to the uninitiated why that doesn't work.

**Comment by benhillis** [comment] 2016-10-21 15:54
@therealkenc Thank you sir!  Yeah I'm prepared for it.  FYI: The limitation of current working directory not propagating along and not being able to launch .exe files out of LxFs ("/", "/home", etc) directories isn't a technical limitation - it's to avoid our old friend NT binaries stomping over extended attributes.

Cwd propagation for virtual directories (procfs, sysfs) doesn't work for obvious reasons.

**Comment by fpqc** [comment] 2016-10-21 16:02
@benhillis By the way, Xilun's cbwin had one feature that you don't quite have in the new interop:

If you ran `wrun chrome`, it would execute chrome from the Windows Runline (Win+R), which was sometimes convenient.  I guess with the current solution, you can manually set your aliases directly to executables, but say I wanted to use edge to open a link or something. 

With Xilun's thing, I could execute edge on a link %L with 
`wrun microsoft-edge:%L`.  I don't know of a way to execute modern Windows apps without a runline like that.

**Comment by therealkenc** [comment] 2016-10-21 16:08
Yeah I understand. That's what I meant by "to the uninitiated" (I should have been more clear).  Seems to me you're eventually going to have to convince the Win32 side people to meet you half way on some of this stuff -- ie teach CRT and Nt*File your clever extended attributes. As I quipped in another thread, it's ineviatable anyway because if you don't, someone is going to mount VolFs on a SMB or NFS over loopback, if only to demonstrate the incongruity. That person might be me if I get bored enough on a weekend. ;)

**Comment by benhillis** [comment] 2016-10-21 16:09
@fpqc I didn't realize he had that functionality, that's awesome.

**Comment by Manouchehri** [comment] 2016-10-21 16:16
@benhillis Did you accidentally tab my name there? I don't think I've used VS Code since before WSL was released.

**Comment by benhillis** [comment] 2016-10-21 16:17
@Manouchehri yep my bad!

**Comment by ConAntonakos** [comment] 2017-03-06 02:42
I've been following this thread, and installing all the extra packages that were missing. Now when I execute `code` in the command line, it appears to just do nothing.

**Comment by therealkenc** [comment] 2017-03-13 03:52
I put up `strace`s for VSCode on [WSL](https://gist.github.com/therealkenc/fa78fdd0fb903ec7055eae761184c3c1/raw/1e0a6ff98d38daea9a488cde01d0ccec41e9192e/wsl.strace.tgz) and [native](https://gist.github.com/therealkenc/fa78fdd0fb903ec7055eae761184c3c1/raw/1e0a6ff98d38daea9a488cde01d0ccec41e9192e/vscode-native.strace.tgz) [here](https://gist.github.com/therealkenc/fa78fdd0fb903ec7055eae761184c3c1). I tried to track it down with node debug, but it blackholes down [vscode-loader](https://github.com/Microsoft/vscode-loader) never to return. Or, possibly, never to return from something vscode-loader is trying to load. Atom and [electron-quick-start](https://github.com/electron/electron-quick-start), not to mention Chrome light up fine. Here is the diverge. Notable mostly because I haven't seen ` ERESTARTNOHAND` value before:
```
WSL process 2262
18:55:53 rt_sigaction(SIGCHLD, {0x7fc3a92db450, [], SA_RESTORER, 0x7fc3a7331630}, NULL, 8) = 0
18:55:53 rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
18:55:53 ppoll([{fd=3, events=POLLIN}], 1, NULL, [], 8) = 1 ([{fd=3, revents=POLLIN}])
18:55:53 clock_gettime(CLOCK_MONOTONIC, {20697, 558524000}) = 0
18:55:53 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\4\0\0\0\3\0\0\0", 8192}], msg_controllen=0, msg_flags=0}, 0) = 8
18:55:53 write(3, "\0\0\0\0", 4)        = 4
18:55:53 ppoll([{fd=3, events=POLLIN}], 1, NULL, [], 8) = ? ERESTARTNOHAND (To be restarted if no handler)
```
Native process 7578:
```
18:54:36 rt_sigaction(SIGCHLD, {0x7f685d932450, [], SA_RESTORER, 0x7f685bb3c630}, NULL, 8) = 0
18:54:36 rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
18:54:36 ppoll([{fd=3, events=POLLIN}], 1, NULL, [], 8) = 1 ([{fd=3, revents=POLLIN}])
18:54:36 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\4\0\0\0\3\0\0\0", 8192}], msg_controllen=0, msg_flags=0}, 0) = 8
18:54:36 write(3, "\0\0\0\0", 4)        = 4
18:54:36 ppoll([{fd=3, events=POLLIN}], 1, NULL, [], 8) = 1 ([{fd=3, revents=POLLIN}])
18:54:37 recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"<\3\0\0\0\0\0\0\10\0\0\0renderer\23\0\0\0\16\0\0\0/pro"..., 8192}], msg_controllen=32, [{cmsg_len=32, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, [214, 215, 216, 217]}], msg_flags=0}, 0) = 832
```

**Comment by MaximoTrinidad** [comment] 2017-03-13 12:54
Hi @therealkenc ,

Question: What's the Windows 10 build you're on WSL?  

I'm glad someone is trying to get this resolved.  I on the latest Windows 10 Insider Build 15048 but haven't try to reinstalled code yet.  I know WSL has some improvements which clears some issues with PowerShell 6 to work as expected.

I'm to try it today and see if we still having the issue.

:)

**Comment by MaximoTrinidad** [comment] 2017-03-13 15:32
Ah! It still doesn't work.  
:(

So, the only work around is to create your script files (Python, PowerShell...) using your Windows Editors apps and then run the code on either your WSL Bash console or, if you have it installed, on your Ubuntu Desktop. 

I know it will be just a matter of time when this issue get fixed.

:)

**Comment by felocru** [comment] 2017-04-27 21:23
Something new? I have the same problem

**Comment by MaximoTrinidad** [comment] 2017-04-27 21:36
I think... the reality is that WSL wasn't meant to work with the GUI Ubuntu Desktop although it possible.  But trying to load the debian version of VS Code won't work (yet).  

So, my option is to build my cross-platform code using the Windows Editors then later I can execute then under WSL Bash subsystem.  The only GUI editor I can run in my WSL Ubuntu Desktop is Gedit and I can run terminal and PowerShell with no issues (yet).   At least for testing demo purpose, it doable now!

Again, installing Ubuntu Desktop is not certified to run under WSL but for me is pretty functional.

:)

**Comment by therealkenc** [comment] 2017-11-15 17:52
A VSCode team member chimed in #2293 so it is probably going to be most practical to track further developments regarding VSCode native there since he's subscribed. The OP here was a missing `libxss1` followed by a dupe of #1267.

**Closed by therealkenc** 2017-11-15 17:52 UTC
Labels: duplicate

**Comment by MaximoTrinidad** [comment] 2018-05-19 12:40
@nityansuman 

But, the only way to run VS Code under WSL is to install Windows X Server in Windows 10, and in WSL install the Ubuntu Desktop.

So, Yes! Installing the Ubuntu Desktop you can use VS Code in WSL.

Unfortunately, the Ubuntu Desktop is not supported in Windows 10.  But, I've been using it for the last few years!

:)

**Comment by therealkenc** [comment] 2018-05-19 17:39
>  it appears to just do nothing.

`code --verbose` will "do something". Likely pointing out that you don't have `$DISPLAY` set.

**Comment by MaximoTrinidad** [comment] 2018-05-19 19:36
@therealkenc 

Yes! If you installed VS Code in WSL console, then it won't open in Windows 10.  It need to the Ubuntu Desktop GUI to open VS Code Linux version.

**Comment by therealkenc** [comment] 2018-05-19 20:10
> It need to the Ubuntu Desktop GUI

No, you don't. Which is why no one should read #637.

**Comment by MaximoTrinidad** [comment] 2018-05-19 23:53
@therealkenc 

It will be nice to know if you got a workaround.  But, this got me thinking.  I've been using this for about two years now.

I got a VM with the latest Windows 10 Insider Version 10.0.17672.1000 and only WSL Ubuntu install (no GUI).  I installed the latest VS Code stable edition... And ... Yes!!

It's working without installing VSCode in WSL. You can run "Code" from the WSL console and it will open the Windows VS Code version.

There's nothing wrong experimenting with installing GUI in WSL.  

So, if you have installed the Ubuntu GUI in WSL then you lose the ability to call the VS Code Windows app.

And, if you still want to install the VS Code Linux version in WSL, then you need to install Ubuntu Desktop to run it.

Interesting findings!  Just pick the right environment for your work.

:)

Below image showing calling VS Code Windows App from the WSL console (no Ubuntu Desktop installed).
![wsl_wincode_2018-05-19_19-46-02](https://user-images.githubusercontent.com/19892435/40274161-f371869a-5b9d-11e8-92d5-b70c6831a3f1.jpg)

**Comment by therealkenc** [comment] 2018-05-20 01:55
> There's nothing wrong experimenting with installing GUI in WSL.

Correct. There is, rather, something not right with installing the Ubuntu Desktop; which is neither necessary nor desirable to run native Linux VS Code on WSL.

> So, if you have installed the Ubuntu GUI in WSL then you lose the ability to call the VS Code Windows app.

```
alias winvscode='/mnt/c/Program\ Files/Microsoft\ VS\ Code/bin/code'
winvscode
```

**Comment by MaximoTrinidad** [comment] 2018-05-20 13:26
@therealkenc 

Awesome!! Thanks for sharing.  I love learning stuff.

Thank You!!
:)
