### ISSUE TITLE
Can't run some ELF64 amd64 binaries, perhaps the 'GNU/Linux' linked ones?

### ISSUE THREAD

**Issue by whereisaaron** [Microsoft/WSL#2834] opened 2018-01-11 19:41 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

1. Download `cli53-linux-amd64` binary from https://github.com/barnybug/cli53 (it is compiled golang)
```
$ wget -q https://github.com/barnybug/cli53/releases/download/0.8.12/cli53-linux-amd64
```
2. Check file type is correct
```
$ file cli53-linux-amd64
cli53-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, stripped
```
3. Make executable
```
$ chmod a+x cli53-linux-amd64
```
4. Run
```
$ ./cli53-linux-amd64
-bash: ./cli53-linux-amd64: cannot execute binary file: Exec format error
```
5. Cry :-)

* What's wrong / what should be happening instead:

Should run. The exact same binary works fine on Ubuntu 14.04 on an amd64 CPU, so it seems like a problem with WSL specifically.
```
$ wget -q https://github.com/barnybug/cli53/releases/download/0.8.12/cli53-linux-amd64

$ file cli53-linux-amd64 
cli53-linux-amd64: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), statically linked, stripped

$ chmod a+x cli53-linux-amd64 

$ ./cli53-linux-amd64 --version
cli53 version 0.8.12
```

Other similar ELF64 golang binaries do run on WSL. Notable these are 'SYSV' rather than 'GNU/Linux' linked. Is there an incompatibility there?
```
$ file helm
helm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

$ ./helm version --client
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

$ file kubectl
kubectl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

$ ./kubectl version --client
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

```
$ strace -f ./cli53-linux-amd64
execve("./cli53-linux-amd64", ["./cli53-linux-amd64"], [/* 17 vars */]) = -1 ENOEXEC (Exec format error)
write(2, "strace: exec: Exec format error\n", 32strace: exec: Exec format error
) = 32
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by benhillis** [comment] 2018-01-11 19:46
Duplicate of #1884, I verified this binary runs with my fix.

**Closed by benhillis** 2018-01-11 19:46 UTC

**Comment by whereisaaron** [comment] 2018-01-11 20:06
Great news @benhillis thanks for the fix. What is the release cycle for such a `fixinbound` fix?

**Comment by benhillis** [comment] 2018-01-11 20:11
@whereisaaron - Next update of Windows will have the fix, I don't think the release date has been finalized but I believe it's early spring 2018.

**Comment by whereisaaron** [comment] 2018-07-24 16:45
Yay, the ~~Spring~~ ~~April~~ ahem June 1803 update fixes this.
```
$ cli53 --version
cli53 version 0.8.12
```

Thanks for the fix @benhillis!
