### ISSUE TITLE
Serious problem with Simplified Chinese translation of wsl.exe help message

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#8857] opened 2022-09-23 02:01 UTC
### Version

OS: Win11 22H2
WSL: 0.67.6.0

### WSL Version

- [X] WSL 2
- [x] WSL 1

### Repro Steps

wsl.exe --help

### Expected Behavior

Show correct translation

### Actual Behavior

The Chinese language translator of this program has also translated the names of the parameters provided in the wsl.exe help message into Chinese, it is very difficult for our users to use wsl.exe because it is impossible to operate wsl.exe according to the help information.

If we want to solve this problem, our users can only consult English documents, but this is very troublesome.
This mistake should be corrected.

![translation](https://user-images.githubusercontent.com/18372244/191987658-4c3ac41e-2449-4a06-b00c-3522bcc8711e.png)

**Comment by driver1998** [comment] 2022-09-23 02:05
BTW, do you have the store version of WSL installed?

**Comment by WitherZuo** [comment] 2022-09-23 04:32
@driver1998 The Store version of WSL also have this problem.

WSL version command output:

```
WSL 版本： 0.67.6.0
内核版本： 5.15.62.1
WSLg 版本： 1.0.44
MSRDC 版本： 1.2.3401
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.25206.1000
```

And the help command output:  

```
版权所有 (c) Microsoft Corporation。保留所有权利。
有关此产品的隐私信息，请访问 https://aka.ms/privacy。

用法: wsl.exe [参数] [选项...] [命令行]

用于运行 Linux 二进制文件的参数:

    如果未提供命令行，wsl.exe 将启动默认 shell。

    --exec, -e <命令行>
        在不使用默认 Linux shell 的情况下执行指定的命令。

    -shell-类型 <类型>-
        使用提供的 shell 类型执行指定的命令。

        类型:
            标准
                使用默认 Linux shell 执行指定的命令。

            登录
                使用默认的 Linux shell 作为登录 shell 执行指定的命令。

            无
                在不使用默认 Linux shell 的情况下执行指定的命令。

    --
        按当前方式传递剩余的命令行。

选项:
    --cd <目录>
        将指定目录设置为当前工作目录。
        如果使用 ~ ，则将使用 Linux 用户的主路径。如果路径
        以 / 字符开头，则将该路径解释为绝对 Linux 路径。
        否则，该值必须为绝对 Windows 路径。

    --发行版, -d <发行版>
        运行指定的发行版。

    --用户, -u <用户名>
        以指定的用户身份运行。

    --系统
        为系统分发启动 shell。

用于管理 Linux 的 Windows 子系统的参数：

    --帮助
        显示使用情况信息。

    --安装 <发行版> [选项...]
        安装适用于 Linux 发行版的 Windows 子系统。
        对于有效发行版的列表，请使用“wsl.exe --列表 --online”。

        选项:
            --不启动, -n
                安装后不启动发行版。

            --web-download
                从 Internet 而不是 Microsoft Store 下载发行版。

    --装载 <磁盘>
        在所有 WSL 2 发行版中附加并安装物理或虚拟磁盘。

        选项:
            --vhd
                指定<磁盘>是指虚拟硬盘。

            --裸露
                将磁盘附加到 WSL2，但不进行安装。

            --名称 <名称>
                使用安装点的自定义名称安装磁盘。

            --类型 <类型>
                安装磁盘时要使用的文件系统，如果未指定，则默认为 ext4。

            --选项 <选项>
                其他安装选项。

            --分区 <索引>
                要安装的分区索引，如果未指定，则默认为整个磁盘。

    --set-default-version <版本>
        更改新发行版的默认安装版本。

    --关闭
        立即终止所有正在运行的发行版和 WSL 2
        轻型实用程序虚拟机。

    --状态
        显示适用于 Linux 的 Windows 子系统的状态。

    --卸载 [磁盘]
        从所有 WSL2 发行版中卸载并分离磁盘。
        如果在没有参数的情况下调用，则卸载和分离所有磁盘。

    --更新
        更新适用于 Linux 包的 Windows 子系统。

        选项:
            --web-下载
                从互联网而不是 Microsoft 商店下载更新。

    --版本, -v
      显示版本信息。

用于在适用于 Linux 的 Windows 子系统中管理发行版参数:

   --导出 <发行版> <FileName> [选项]
        将发行版导出为 tar 文件。
        对于标准输出，文件名可以为 -。

        选项:
            --vhd
                指定该发行版应导出为 .vhdx 文件。

    --导入 <发行版> <InstallLocation> <FileName> [选项]
        将指定的 tar 文件作为新发行版导入。
        对于标准输入，文件名可以为 -。

        选项:
            --版本 <版本>
                指定新发行版要使用的版本。

            --vhd
                指定提供的文件是 .vhdx 文件，而不是 tar 文件。
                此操作会在指定的安装位置复制 .vhdx 文件。

    --import-in-place <Distro> <FileName>
        将指定的 .vhdx 文件导入为新发行版。
        此虚拟硬盘必须以 ext4 文件系统类型格式化。

    --列表, -l [选项]
        列出各个发行版。

        选项:
            --所有
                列出所有发行版，包括
                当前正在安装或卸载的发行版。

            -运行
                仅列出当前正在运行的发行版。

            --安静, -q
                仅显示发行版名称。

            --详细的, -v
                显示有关所有发行版的详细信息。

            --在线, -o
                显示可使用“wsl.exe --install”安装的发行版列表。

    --set-default, -s <发行版>
        将发行版设置为默认。

    --set-version <发行版> <版本>
        更改指定发行版的版本。

    --终止, -t <发行版>
        终止指定的发行版。

    --注销 <发行版>
        注销发行版并删除根文件系统。
```

**Comment by benhillis** [comment] 2022-09-23 15:48
Yes this is problematic. Let me follow up with the team that does the translation. Thanks for bringing this to my attention.

**Comment by itviewer** [comment] 2022-12-02 13:46
Anyone with a basic programming knowledge should know that you should not translate command line options!

**Comment by Winson-Huang** [comment] 2022-12-07 13:11
Three month later, this issue is still unsolved...... @benhillis could u help to provide some feedback? I really don't think it's a complex task, maybe there is a way for community to help?

**Comment by Winson-Huang** [comment] 2022-12-25 07:26
Duplicate of #4111

**Comment by wsy** [comment] 2023-09-27 23:31
> Duplicate of #4111

This is not a duplicate of #4111
#4111 is about "incorrect explaination of commandline arguments of wsl.exe".
This bug is about: "Commandline option itself got translated and related features got unusable".
This bug is a blocking issue!

**Closed** 2024-10-03 12:19 UTC
Labels: localization
