### ISSUE TITLE
Since updating to Windows 11 WSL fails to start

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/WSL#7512] opened 2021-10-09 09:28 UTC
### Windows Build Number

Microsoft Windows [Version 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Kernel version: 5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

N/A

### Repro Steps

After booting up the PC click on Windows Termianal.

### Expected Behavior

I should be straight onto the command line

### Actual Behavior

```
[error 0x8007010b when launching `wsl.exe -d Ubuntu-20.04']
Could not access starting directory "\\wsl$\Ubuntu-20.04\home\[User]\workspace"
```

It will eventually get me there if I close the terminal and start again

**Comment by marcelormendes** [comment] 2021-10-09 17:12
same here

**Comment by Nexer8** [comment] 2021-10-10 11:13
I'm witnessing the same problem.

**Comment by Guarmanda** [comment] 2021-10-10 13:05
I uninstalled it before windows , and now I can't install it at all

**Comment by jasonwilliams** [comment] 2021-10-12 16:33
@stehufntdev https://aka.ms/AAe22iv

**Comment by stehufntdev** [comment] 2021-10-14 20:06
Duplicate of #6995

**Closed** 2021-10-14 20:05 UTC
