### ISSUE TITLE
[Bug] Not being able to use ':' in filenames causes issues

### ISSUE THREAD

**Issue by QuadPiece** [Microsoft/WSL#2952] opened 2018-02-14 10:16 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.15063] (Windows 10 Enterprise 1703)

* What you're doing and what's happening:  Creating files with a `:` in the name

* What's wrong / what should be happening instead: 

Most Linux filesystems support colons in names. Therefore it is not often, but at times expected that creating files with colons in their names is possible. Not being able to use files with a `:` in their name can cause issues.

Most notably this breaks the Linux distribution Void Linux, whose package manger uses colons in the filenames when storing keys for xbps repos. Meaning you will not be able to update your system while running Void in WSL

A workaround or solution to storing files with colons in their name on NTFS filesystems should be considered.

* ~~Strace~~ Screenshot of the failing command, if applicable: 

![powershell_2018-02-14_11-10-22](https://user-images.githubusercontent.com/6379091/36198769-ce858d7e-1177-11e8-96e2-dff32ef26bd9.png)

For comparison, here's the `/var/db/xbps/keys` folder on a regular Void Linux machine:

![hyper_2018-02-14_11-10-53](https://user-images.githubusercontent.com/6379091/36198776-d37cdb0c-1177-11e8-9eb5-357975cd164f.png)

**Comment by 0xbadfca11** [comment] 2018-02-14 11:00
Looks like it's doing in DrvFs.
In VolFs, supports ":".
![image](https://user-images.githubusercontent.com/7390559/36200840-4227ea12-11c1-11e8-9aff-6525a62bff7d.png)

**Comment by QuadPiece** [comment] 2018-02-14 11:11
Interesting, I didn't realize that it had no effect on the virtual filesystem. I've mostly encountered this issue while doing chroot or extracting files from archives stored on the C: drive. If it's expected behavior that the /mnt drives act differently from the virtual linux filesystem then this might not be much of an issue after all

**Comment by benhillis** [comment] 2018-02-14 16:43
Duplicate of #1514.

**Closed by benhillis** 2018-02-14 16:43 UTC
