### ISSUE TITLE
Ubuntu (WSL) hangs on launch with black screen

### ISSUE THREAD

**Issue by Convincible** [microsoft/WSL#4569] opened 2019-10-04 09:41 UTC
* Windows build: 10.0.18362.356
* When I click "Ubuntu" in Start Menu to run Ubuntu as installed via Windows Store after WSL enabled...
* ...a console opens with a flashing cursor in the top left, and nothing happens. It doesn't arrive at the Ubuntu command prompt.

To be clear, the Ubuntu installation had been working fine up to this point; the issue has appeared seemingly at random. I didn't change any particular setting.

The hang doesn't always occur. Just sometimes (and I can't spot a cause).

When the issue is present, restarting the whole PC usually fixes the problem.

**Comment by craigloewen-msft** [comment] 2019-10-04 17:37
This issue seems to have a variety of causes and some potential fixes, such as rebooting, temporarily disabling bitdefender, turning off 'Legacy mode' in the Windows Console, or changing terminal properties in the shortcut you're using.

Here are the relevant threads on the issue:
https://github.com/microsoft/WSL/issues/2352
https://github.com/microsoft/WSL/issues/4055

I'm going to mark this issue as duplicate and close it so we can use those issues as landing zones for discussion, please try some of the fixes there and if your problem still persists comment on a thread. And if you can include [logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) for when the issue is happening that'll help us diagnose it. Thank you!

**Closed by craigloewen-msft** 2019-10-04 17:37 UTC
