### ISSUE TITLE
BSOD: Probably caused by : LXCORE.SYS ( LXCORE!LxpFutexEvictWaitQueue+47 )

### ISSUE THREAD

**Issue by sunxiaoguang** [Microsoft/WSL#2648] opened 2017-11-10 07:31 UTC
Windows version / build number
  Microsoft Windows [Verson 10.0.16299.19]
Steps  required to reproduce,
running cargo build on a project which reference another project using path

**Comment by sunxiaoguang** [comment] 2017-11-10 07:34
Minidump has been sent to secure@microsoft.com.

**Comment by sunxiaoguang** [comment] 2017-11-14 00:47
Just realized It's probably related to mounting tmpfs. I was able to reproduce this just cargo build a self contained project.
The command I used to mount tmpfs was
mount -t tmpfs -o size=256m tmpfs /path/to/my/project/target

**Comment by ColinChargyBentley** [comment] 2017-11-30 10:36
Hello,
I also had multiple times the same issue when making incremental C++ build code with GCC/G++ launch by make, launch by a BuildBot slave (ie python). I'm unable to narrow this down more. However, cleaning the build folder (new build from scratch) seems to fix the issue. I'm also sending the dump to secure@microsoft.com. I'm using Windows 10.0.16299.15 . I'm posting this here and in https://github.com/Microsoft/WSL/issues/2697 as I think that could be the same issue.
Regards,
Colin Chargy

**Comment by sunilmut** [comment] 2017-11-30 21:52
Thanks for forwarding the memory dump file. The issue is well understood here and the fix is already on it's way to the Insiders. It hasn't made it to the insiders and we will be sure to report back when it does. Marking this as a dupe.

**Closed by sunilmut** 2017-11-30 21:52 UTC
