### ISSUE TITLE
Waiting long for something happen

### ISSUE THREAD

**Issue by martijnvwezel** [Microsoft/WSL#1305] opened 2016-11-01 09:28 UTC
**A brief description**
There are some problems with loading things like git status. It takes to long sometime more then a minute. When my virtual machine does this in milliseconds for the same project. It is also with ssh to other machines, sometimes ssh user@server1156 as example will take 5 a 6 seconds before connection which putty or virtualbox-ubuntu does this imedatelly (server is on the same switch). 

**Expected results**
waiting long for something happen

**Windows build number**
Microsoft Windows [Version 10.0.14393]

**Repro Steps**
start bash
$ ssh [user@server1156]

or 

go to project git directory
$ git status

**output**
strace git status

clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5793940a10) = 13611
close(6)                                = 0
read(5, "", 1)                          = 0
close(5)                                = 0
close(4)                                = 0
read(3,

The last point he is waiting...

**Comment by therealkenc** [comment] 2016-11-01 23:23
Git is using _some_ pattern WSL doesn't like from a performance standpoint; there are some comments in #981. Similarly with ssh #1076. I am not sure if the issue is connected though it seems likely.

**Comment by aseering** [comment] 2016-11-02 00:03
I forget, what's the default value of `git config core.fscache` on Ubuntu?  Setting it to `true` is a common performance recommendation on Windows.  I wonder if it would help WSL as well.  If so, that might shed some light on the source of the performance slowdown.  (And be a viable/convenient workaround.)

**Comment by misenesi** [comment] 2016-11-02 00:52
You might be hitting an performance issue we are actively investigating with NTFS. Git was written using certain operations that are very fast on Linux but slow on Windows.

**Comment by therealkenc** [comment] 2016-11-02 00:53
[Looks like](https://github.com/git-for-windows/git/commit/88a0090d1a8172ed27beb8f18c450b81f5c12fff) 'core.fscache' option is only respected on Git for Windows. But I think you might have shed a bright light. `rsync` per #1076 is going to crap all over `lstat()` too.

This [link](https://github.com/msysgit/msysgit/wiki/Diagnosing-why-Git-is-so-slow) has some pertinent info also. In particular `git config core.ignoreStat` might be a useful workaround for WSL. Weird though, I have never (knowingly) set that config variable on Windows, yet git status is tolerable with large trees.

**Comment by bootstraponline** [comment] 2017-04-16 03:20
The agnoster theme on both [zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme) and [bash](https://github.com/speedenator/agnoster-bash) is incredibly slow. Pressing return inside a large git repo will trigger a large delay. Spamming return will consume 100% CPU. Most of the delay is attributed to running git commands:

- git rev-parse --git-dir 
- git rev-parse --is-inside-work-tree 
- git symbolic-ref HEAD
- git rev-parse --short HEAD

Commenting out the git commands helps however the terminal is still quite slow (multi-second delay) when pressing return.

**Comment by nesl247** [comment] 2017-04-18 18:59
Why was this closed?

**Comment by bootstraponline** [comment] 2017-04-18 19:11
It'd be nice to have a link to some ticket that's tracking the performance issues? If there's not already a ticket, then this should remain open.

**Comment by sunilmut** [comment] 2017-04-18 19:52
@bootstraponline - Agreed. I couldn't find one in the [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash). It might be worthwhile to get one logged there so that people can up vote.

**Comment by bootstraponline** [comment] 2017-04-18 19:56
[Filesystem is slow](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system) is probably the closest existing user voice ticket.

**Comment by sunilmut** [comment] 2017-04-18 19:59
@bootstraponline - Thanks. Yes, that's the right one. I was searching with the keyword "perf" :).

**Comment by martijnvwezel** [comment] 2017-06-03 20:03
@nesl247 indead I reopend it again ;)

**Comment by adeeb1** [comment] 2017-08-23 06:58
I know that some of the performance issues are outside the realm of WSL, but any updates on improving performance? Slow performance, especially for Git and Ruby, really hurts my productivity.

**Comment by mo18** [comment] 2017-09-01 19:51
I've noticed the same issue, but I also noticed that the issue is much worse when the directory I cloned the project to was in the windows filesystem. I double checked and for some reason, the cloned project on the windows directory is 369G where the same cloned project is 741M on the linux filesystem. In the following output, "projects" is a symlink to /mnt/c/Users/me/projects.

```
$ pwd
/home/me

$ ls -l projects
lrwxrwxrwx 1 me me 29 Jul 20 14:48 projects -> /mnt/c/Users/me/projects

$ du -sh projects/mygitproject
369G    projects/mygitproject

$ du -sh mygitproject
741M    mygitproject

```

**Comment by sunilmut** [comment] 2017-09-05 18:43
@mo18 - Do you know what is taking up that much room on the Windows directory? Maybe `du` is not correctly reporting the size on Windows dirs. Can you double check from explorer or cmd?

**Comment by mo18** [comment] 2017-09-06 03:02
@sunilmut - In Windows explorer, the mygitproject directory reports 731 MB.

**Comment by sunilmut** [comment] 2017-09-06 20:00
So, it looks like `du` in DrvFS (/mnt/c etc) in some cases could report false values. Adding @SvenGroot

**Comment by SvenGroot** [comment] 2017-09-06 20:38
What build was the "du" output from? There was a bug with block counts reported in both LxFs and DrvFs that leads to "du" giving wildly inaccurate numbers that is fixed in current insider builds, but would be broken in the Creator's Update.

**Comment by mo18** [comment] 2017-09-07 13:11
@SvenGroot - I'm on 1703

**Comment by therealkenc** [comment] 2017-11-18 22:09
Dupe #981.

**Closed by therealkenc** 2017-11-18 22:09 UTC
Labels: file system
