### ISSUE TITLE
host randomly hang up when operating file by \\wsl$

### ISSUE THREAD

**Issue by jie-ss** [microsoft/WSL#7953] opened 2022-01-21 10:41 UTC
### Version

Win 10.0.19044.1469

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Other Software

explore/notepad

### Repro Steps

open \\wsl$\<user>\foo.txt by notepad, write couple characters occasionally, sometimes save actions are failed and notepad hangs forever. the opened ubuntu terminal still works fine but can't open another terminal, by command "wsl --shutdown" can quit the hang state. no extra info. on fileServer log file when entered hang state, but there are many " Exception: Invalid argument @..\p9handler.cpp:1099 (LookupFid)" messages after wsl is terminated and ubuntu terminal is opend again.

### Expected Behavior

read/write files in guest os normally

### Actual Behavior

can't open/write files in guest os occasionally

**Comment by equation-group** [comment] 2022-01-25 14:49
Need more information.  Consider attaching screenshots and diagnostic logs.

**Comment by Ansuel** [comment] 2022-01-25 21:53
@equation-group can confirm this...
I initially tought this was caused by me using optimized-vhd but yesterday I decided to purge the entire wsl and restore everything (so a clean new bhd)

Problem is not solved.

This is present from at least 10 insider dev build.

Installation is from WSL store Package.
The image is Ubuntu updated to devel.

To me it looks like the 9p share just randomly die... wsl is still accessible from terminal or using vscode remote extension.

Any access to wsl$ will make explorer hang and crash. wsl --shutdown doesn't fix the problem. I have to reboot the system to make the 9p share accessible.

Feel free to ask me ANY info. This is getting really annyoing.
Also it doesn't seems to be related to stressing the 9p share with multiple access since now it just died with just 4-5 file open in vscode and by opening a directory in explorer I discovered is death.

**Comment by jie-ss** [comment] 2022-01-26 04:53
> Need more information. Consider attaching screenshots and diagnostic logs.

The log file is attached but just what I described  in the previous post, my issue is different with @Ansuel 's, "wsl --shutdown" can fix the problem 
[log.txt](https://github.com/microsoft/WSL/files/7939007/log.txt)

**Comment by ShahinKohan** [comment] 2022-03-02 17:32
This is for sure a problem and a reboot is the only thing that fixes it. 

WSL version: 0.51.3.0
Kernel version: 5.10.93.2
WSLg version: 1.0.30
Windows version: 10.0.22000.527

**Comment by benhillis** [comment] 2022-04-05 21:48
A fix for this issue will be available in an upcoming version of WSL!

**Closed by benhillis** 2022-04-05 21:48 UTC
