### ISSUE TITLE
wsl stops responding after suspend/hibernate wakeup vmmem 100% cpu

### ISSUE THREAD

**Issue by alonbl** [microsoft/WSL#8881] opened 2022-09-24 19:50 UTC
### Version

Microsoft Windows [Version 10.0.22000.978]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu-22.04

### Repro Steps

Run WSL with graphic application such as xfce4-terminal.
Suspend/hibernate a few times.
WSL stops responding.

### Expected Behavior

WSL operational as it was few days ago.

### Actual Behavior

WSL is not responding.
vmmem (vmwp.exe) takes 100% CPU

`> wsl.exe true` does not respond.
`> wsl.exe --shutdown` takes a lot of time to run (minutes)

### Diagnostic Logs

Worked up to 2022-09-23.

Recent updates:

*   KB5017328
*   KB5017497

Relatively recent updates:

*  KB5016629
*  KB5012170

Reproduced first with release preview:

```
>wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2
WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.978
```

Then downgraded to stable and also reproduced.

```
>wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2

Windows Subsystem for Linux was last updated on 24/09/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1
```

Related to https://github.com/docker/for-win/issues/12968

**Comment by hypeitnow** [comment] 2022-09-25 06:16
I can confirm, I've been running shutdown for 10 minutes now, tried to restart lxssmanager in the meantime but no avail :(

**Comment by viceice** [comment] 2022-09-25 06:26
Duplicate of #6982

**Comment by alonbl** [comment] 2022-09-26 19:39
Duplicate of https://github.com/microsoft/WSL/issues/6982

**Closed** 2022-09-27 09:58 UTC

**Comment by alonbl** [comment] 2022-10-13 21:33
Related-To: #8930
