### ISSUE TITLE
Blank screen when starting up (similar to #2352)

### ISSUE THREAD

**Issue by Kurgol** [microsoft/WSL#4055] opened 2019-05-20 10:32 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.503]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Clicking the shortcut to open my Ubuntu 18.04 bash terminal (or the Debian one I installed to test appears to be affected as well).

![image](https://user-images.githubusercontent.com/15245142/58015198-8e532a00-7af2-11e9-9373-ef3d77b6ccc2.png)

* What's wrong / what should be happening instead:

It should be opening a functional prompt.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

I can't type any commands, so not possible to run an Strace.

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

I have captured the detailed logs as requested (it was also mentioned on issue #2352 ):

[blank-screen-when-starting-up.zip](https://github.com/microsoft/WSL/files/3197409/blank-screen-when-starting-up.zip)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by jheffez** [comment] 2019-05-21 07:39
Same problem on two windows pc's.. If I close WSL <Ctrl+D> and later try to lauch WSL/ubuntu I get a blank screen. Reboot fixes the problem.

**Comment by Protazy21** [comment] 2019-05-22 16:05
same as #4047

**Comment by Stoner60** [comment] 2019-05-31 14:43
Same for me. I uninstall Ubuntu and WSL, but then if I start command prompt as administrator and without legacy console option of cmd, I also got a Blank screen. If i do it as "normal" User then all is fine. cmd works also fine with admin and normal user, if I activate legacy console. But then it will not work during install of ubuntu.

**Comment by Stoner60** [comment] 2019-06-01 17:40
It seems I found the solution concerning blank screen: 
Press the icon of Ubuntu in the blank screen, properties, Terminal, uncheck separate foreground and background, then you will see the output of the Terminal. Same with the cursor. Perhaps you have to reinstall Ubuntu and start again. I have a german Windows installation, hope to find the right translation.
Now I was able to create a user and give them a password, and do an update with sudo ....

**Comment by Kurgol** [comment] 2019-06-12 13:32
@Stoner60 neither of those options are selected for me, and I still can't get a functioning terminal. Also I have restarted multiple times since I opened this, and although some people say a reboot resolves the issue for them - it does not for me. 
![image](https://user-images.githubusercontent.com/15245142/59355466-eb6f8380-8d1e-11e9-96a1-0c8777510d0c.png)

**Comment by Stoner60** [comment] 2019-06-12 14:29
@Kurgol , perhaps it help, if you play with the colours of foreground and background. For me it seems, that font colour and background is the same. Black font on black background, then you see nothing.

**Comment by benhillis** [comment] 2019-06-21 22:24
When you get into this state, can you check the status of the LxssManager service?

`sc query lxssmanager`

**Comment by Kurgol** [comment] 2019-06-22 14:39
![image](https://user-images.githubusercontent.com/15245142/59965301-f63acd00-9503-11e9-9d3a-90f1fe9c9d27.png)

**Comment by Kurgol** [comment] 2019-06-22 14:40
![image](https://user-images.githubusercontent.com/15245142/59965309-136f9b80-9504-11e9-9c01-3db4b512e5f6.png)

**Comment by hnlpower** [comment] 2019-06-24 10:46
I have the exact same issue.

I dont fully know the exact steps to reproduce but it simply seems just a "time" issue, if I open it right after boot, it works fine after a few minutes after closing and not touching it the terminal goes into the frozen state.

This issue makes WSL(1) completely unusable for me.

A reboot fixes the issue.

Im on windows 10 pro (1903)

I do have BitDefender installed (maybe that does something to the files)
I also use VsCode with the Remote extension which consistently also freezes WSL

Does switching to WSL 2 fix the issue?

**Comment by nicolaboscaro** [comment] 2019-06-25 18:37
Hi everyone

Me too when I try to open the bash terminal I have your same blank screen with the blinking cursor. If I restart my pc then the bash starts but then, if I close it, the problem starts all over again.

OS: Windows 10 Home (Microsoft Windows [Version 10.0.17134.829])
Ubuntu 18.04 bash terminal
LxssManager is working

Like @hnlpower I also have BitDefender installed.

**Comment by Kurgol** [comment] 2019-06-26 10:16
like the two above, I also use BitDefender!

**Comment by nicolaboscaro** [comment] 2019-06-26 11:10
I've just found out that until last year there were people that had installed BitDefender and they had problems with network connection (that problem seems solved right now).

Maybe this is a new problem caused by that AV...

**Comment by dan-danciu** [comment] 2019-07-03 08:02
Same problem,
I also have Bitdefender although if that is just coincidence or not I do not know.

**Comment by E14** [comment] 2019-07-03 17:43
If that's BD again, that will be the last straw... same issue here.

**Comment by EdwinCheruiyot** [comment] 2019-07-06 16:23
Same Problem I also have Bitdefender Installed restarting the computer seemed to make it work but switching it off after a while resulted in the same error

**Comment by E14** [comment] 2019-07-09 15:51
Anyone still able to reproduce it? I can't anymore. **Previously** I could reproduce the issue by

1. Open Ubuntu Bash
2. Close Ubuntu Bash
3. Wait a bit
4. Open Ubuntu Bash (Hangs here and any further attempts)

There was a BitDefender and Windows update last week

**Comment by nicolaboscaro** [comment] 2019-07-10 13:11
Actually @E14 is right, it seems (I haven't had the time yet to try it
thoroughly) that the bash is working fine now, even if I try to repeat the
steps from 1 to 4. I should be able to test it in about one week or two, if
no one can answer this thread before.

Thank you @E14 for telling us!

Il giorno mar 9 lug 2019 alle ore 17:51 E14 <notifications@github.com> ha
scritto:

**Comment by Kurgol** [comment] 2019-07-10 14:01
I was affected yesterday @E14 and am pretty much affected by it every day. I have moved back to Cygwin as my daily driver, much to my dismay as bash has been working perfectly until the 1903 update.

**Comment by flojon** [comment] 2019-07-11 07:41
I got this today after using WSL for a month on a new computer...

**Comment by flojon** [comment] 2019-07-11 08:15
After a few reboots it's working again. I also had problem with a folder that could not be deleted so I had to boot into command prompt to get rid of it. Not sure if that's related. I'm using Windows 10 Pro with BitLocker and Symantec Endpoint Protection.

**Comment by Kurgol** [comment] 2019-07-18 08:08
still not working on a daily basis for me, if the devs want any more triage please let me know what else I can provide other than what I put in the issue up top?

**Comment by alexejk** [comment] 2019-08-11 09:44
I have been experimenting with this issue and right now it seems to work for me on boot when Hyper-V is enabled and fully working. I was facing this issue when VMWare Workstation was installed and Hyper-V disabled. Note that this is for WSL v1 which I do not really understand the reason for (but had a hunch that seems to help workaround)..

**Comment by dan-danciu** [comment] 2019-08-11 11:47
It is working again for me.
There was a BD update a couple of days ago. I have not had any issues since then.

**Comment by Kurgol** [comment] 2019-08-12 09:23
@dan-danciu I have not had an occurrence for the last few days either. 

@alexejk this problem affects me on two different systems, one has Hyper-V fully installed and the other does not have it installed at all - so I think the Hyper-V is unrelated.

**Comment by alexejk** [comment] 2019-08-12 10:30
@Kurgol, its a fair note. It seemed to be something else indeed because now its back. Even though my PC was of for an hour after enabling Hyper-V yesterday things worked as expected. Today they are broken again.

Interesting enough I have Bitdefender as well but it's still causing issues.
Would you or @dan-danciu mind sharing Versions of BitDefender and what protections are enabled? I would like to see how it differs from my setup.

**Comment by Kurgol** [comment] 2019-08-12 11:39
@alexejk I'm using fully updated versions of Bitdefender Antivirus Free on both. 
![image](https://user-images.githubusercontent.com/15245142/62862582-25004300-bcfe-11e9-82c7-adc99281fe8e.png)

**Comment by dan-danciu** [comment] 2019-08-12 19:20
![image](https://user-images.githubusercontent.com/19431872/62891768-44738c00-bd4f-11e9-8ebc-1e2f931bdd4b.png)

**Comment by alexejk** [comment] 2019-08-13 07:10
I'm on the same version as @dan-danciu but the issue still seems to persist for me. And contrary to what I previously thought - HyperV does not make a difference.

What is still extremely confusing is that a reboot always solves the problem.

**Comment by Kurgol** [comment] 2019-08-13 09:00
@alexejk a reboot does not always solve the problem for me.

**Comment by alexejk** [comment] 2019-08-13 09:44
Even more confusing then, I guess. For me now I basically have to take it as a routine to start & reboot if i want to use WSL which hasnt failed me yet. But I guess we all have slightly different problem that manifest the same way..

@Kurgol when it's "not working" for you, I assume `wsl` commands hang no matter what you do with it, right?

**Comment by Kurgol** [comment] 2019-08-13 09:46
As noted in the original bug report, all I get is a completely unresponsive black window. 
![image](https://user-images.githubusercontent.com/15245142/62932194-994aed00-bdb7-11e9-891d-9c5d1bdc481b.png)

**Comment by avinal** [comment] 2019-08-14 17:38
I am also experiencing same issue. Last time when it happened, even PowerShell was not starting, so I reset my Laptop. Everything worked fine since then until today when WSL failed to start. Last time I did changed some fundamental configurations so I thought It may had a link with changes. But this time its all new and I have just installed a few packages. 
OS: Windows 10 1903 18362.267
WSL: Debian GNU & Ubuntu 18.04 LTS (none starting)
I too have BitDefender installed. 
![image](https://user-images.githubusercontent.com/42297946/63042770-52a8e000-bee8-11e9-8983-9f7c20339bb7.png)

**Comment by archilkarchava** [comment] 2019-08-19 13:51
The problem is with the wslu package (or its dependencies). Holding updates for the package via
`sudo apt-mark hold wslu`
solved the issue for me.
P.S. I don't use Bit Defender so the issue wasn't related to it in my case.

**Comment by ppoffice** [comment] 2019-08-19 14:43
@ archilkarchava which version of wslu are you using?

**Comment by alexejk** [comment] 2019-08-20 07:57
@archilkarchava does the reboot solve the issue temporarily? Because if not - i think those are two different and separate issue.

**Comment by archilkarchava** [comment] 2019-08-21 06:42
> @archilkarchava which version of wslu are you using?

2.0.0-0ubuntu2~18.04.0

**Comment by archilkarchava** [comment] 2019-08-21 06:48
@alexejk Everything works as long as I'm using wslu 2.0.0-0ubuntu2~18.04.0. Rebooting didn't help when using the latest version of the package as well as I remember.

**Comment by dan-danciu** [comment] 2019-08-27 07:13
Issue is back. I am pretty sure it returned after updating Windows to 1903 last week.

**Comment by Fearswe** [comment] 2019-09-23 17:03
I have this issue with Debian on two different PC's. One running 1903 and the other 18 something.
One has BitDefender, the other does not. Same issue on both.
Rebooting does not help. LxssManager is running fine.

**Comment by Padi2312** [comment] 2019-10-20 10:47
Recently i found out that turning off and on the function of linux subsystem is solving the error.

**Comment by Fearswe** [comment] 2019-10-20 16:25
I think I have found the cause of the issue. Disabling Fast Startup prevents it from happening. I'm guessing the LxssManager enters some sort of error state during start/shutdown with Fast Startup.

**Comment by alexejk** [comment] 2019-10-21 16:42
Really? I've tried disabling it before but it still happened fairly consistentl.  For me the fix was doing full system repair which detected some issues. After that no issues for a few weeks so far.

**Comment by Padi2312** [comment] 2019-10-22 09:14
You have to go to Windows Settings and then on Features and Programs. While you there disable Windows Subystem for Linux. Reboot, activated again reboot and the error is fixed.

**Comment by jorgii** [comment] 2019-12-06 21:14
Disabling and re-enabling WSL did not work for me.
What worked for me was holding updates for wslu: `sudo apt-mark hold wslu`.

> The problem is with the wslu package (or its dependencies). Holding updates for the package via
> `sudo apt-mark hold wslu`
> solved the issue for me.
> P.S. I don't use Bit Defender so the issue wasn't related to it in my case.

**Comment by Oeffner** [comment] 2020-01-30 12:16
After following the advice on #4490 to see if the LXSS Manager service is running (it wasn't) and then manually starting it I finally got a working Ubuntu shell. I'm confused as to why my system has two LXSS Manager services. One is named LxssManagerUser_1a0068 and starts automatically. The other one is named LxssManager and is set to start manually. I get access denied if trying to set it to start it automatically, even as administrator. I'm running Windows10 version 1909 build 18363.592

**Comment by jey07** [comment] 2020-02-28 15:53
I am into this issue in midst of my project. Does anyone has permanent solution

**Comment by tummybunny** [comment] 2020-03-18 01:17
I had the same issue, but it turned out to be the color issue.
I can see the terminal after I made the following changes to the properties:
![image](https://user-images.githubusercontent.com/22067638/76915694-2c717580-68f9-11ea-9dc3-be6283a62898.png)

And make sure the text and background color not the same, thenclick Ok, button, and viola!

**Comment by dchennaraidu** [comment] 2020-04-16 00:19
This [method](https://answers.microsoft.com/en-us/windows/forum/all/error-server-execution-failed-when-trying-to-run/1e834b62-8106-4fc3-8bbf-9ab1b1218388) worked for me
![image](https://user-images.githubusercontent.com/12108102/79401146-ed8d1900-7fa5-11ea-8b25-c4add57f3f86.png)

**Comment by Oeffner** [comment] 2020-04-16 09:30
Actually from what I read elsewhere on the internet I have now enabled "Virtual Machine Platform" in the "Turn Windows Features on or off" (where you also enable "Windows Subsystem for Linux"). with that being enabled the bash shell works fine again without hanging.

**Comment by dreykhtman** [comment] 2020-05-26 17:15
Same here. My terminal is a blank window with cursor blinking. Cannot type. When I try to open VSCode, it's stuck on loading and on the bottom left where it usually says "WSL Remote" it's stuck on "⟳ Opening Remote...". I enabled "Virtual Machine Platform" a while ago, so I don't think it's related like the previous poster said. I also have Bitdefender installed. 

Have to restart the PC to fix the problem.

**Comment by adarshaj** [comment] 2020-07-15 09:11
I had the same issue today after upgrading with KB4565503, I followed steps in the above comment: https://github.com/microsoft/WSL/issues/4055#issuecomment-614343660 and it worked after disable + reboot + enable + reboot steps.

**Comment by stevenlafl** [comment] 2020-07-15 15:41
> I had the same issue today after upgrading with KB4565503, I followed steps in the above comment: [#4055 (comment)](https://github.com/microsoft/WSL/issues/4055#issuecomment-614343660) and it worked after disable + reboot + enable + reboot steps.

I am also having this problem with KB4565503 and these steps do not solve the problem for me.

**Comment by stevenlafl** [comment] 2020-07-15 15:45
Here are the ETL files for debugging when I try it. After a while, it shows `The Windows Subsystem for Linux instance has terminated.`  I can't really understand what I'm seeing in these ETL files. 
[lxcore_multiple.etl.zip](https://github.com/microsoft/WSL/files/4926300/lxcore_multiple.etl.zip)

**Comment by Peiqi-Hu** [comment] 2020-08-25 02:22
> This [method](https://answers.microsoft.com/en-us/windows/forum/all/error-server-execution-failed-when-trying-to-run/1e834b62-8106-4fc3-8bbf-9ab1b1218388) worked for me
> ![image](https://user-images.githubusercontent.com/12108102/79401146-ed8d1900-7fa5-11ea-8b25-c4add57f3f86.png)

This works for me, although I don't have Bitdefender installed, so my situation may not apply.

**Comment by EvgeneKuklin** [comment] 2020-09-24 13:29
I have the same problem
Terminal is freezing forever, when I'm trying install or open Ubuntu 
Also all wsl commands are freezing terminal too, but after system restart - wsl commands are working untill I'm trying start Ubuntu
I think the problem apeared after apdating Windows to prerelease version (build 20221.rs_prerelease.200919-1857)(with old version there were no problems)
I had to install this version of Win to get WSL CUDA - according to this guide:
https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-nvidia-drivers
![изображение](https://user-images.githubusercontent.com/52193937/94150495-e128b880-fe81-11ea-8ecd-b31357a05d46.png)

**Comment by stevenlafl** [comment] 2020-09-24 13:34
An update, I had to store a copy of the WSL instance to another location and then delete the Debian WSL install, creating a new one. After that I mounted the old one and copied over all of my data using DiskInternals Linux Reader. It's worked fine since then. Very crappy situation.. it's basically equivalent to having a corrupted drive. Still no idea what caused it - it just randomly happened one day.

**Comment by ryancwalsh** [comment] 2020-10-10 16:01
> Actually from what I read elsewhere on the internet I have now enabled "Virtual Machine Platform" in the "Turn Windows Features on or off" (where you also enable "Windows Subsystem for Linux"). with that being enabled the bash shell works fine again without hanging.

@Oeffner  Thank you! I think this is what fixed it for me.

**Comment by ygerbovits** [comment] 2020-10-16 07:49
Hello,
Simpliest workaround found : 
proceed to a **complete reboot** of Windows. (**press and hold SHIFT / clic Windows / Shutdown / Reboot** / Continue)

**Comment by huchim** [comment] 2020-10-21 03:48
I almost sure I was installed Ubuntu 18.04, but after a blank console, and enable/disable linux subsystem (reboot etc)  it works again but now, Ubuntu is 20.04.1... may be Ubuntu failed when it was upgrading... :/

**Comment by w4hf** [comment] 2021-03-07 11:37
I got the same issue after upgrading from WSL 1 to WSL 2 on a Ubuntu.

This simple workaround works for me : I launch the Ubuntu Terminal (it's blank), wait few seconds then I press CTRL+C, and poof the command line appears.

No idea about the root cause yet, but I hope this simple trick works for you two and help identify the issue.

(I'm on Windows Version 20H2 Build 19042.804)

**Comment by francogp** [comment] 2021-03-23 14:27
Have the same issue, 2021. Windows defender as antivirus. LxssManager refuse to start.

**Closed** 2021-05-10 20:13 UTC

**Comment by FlorientR** [comment] 2021-09-09 08:08
> The problem is with the wslu package (or its dependencies). Holding updates for the package via
> `sudo apt-mark hold wslu`
> solved the issue for me.
> P.S. I don't use Bit Defender so the issue wasn't related to it in my case.

This work fine for me thank you very much !

**Comment by yabuking84** [comment] 2022-09-28 05:45
how do you even `sudo apt-mark hold wslu` if you cant even open the WSL ubuntu bash terminal????

**Comment by JubberyXL** [comment] 2023-01-13 20:08
Oddly enough, ctrl-z, ctrl-x, ctrl-c in this order allowed me to use the terminal

**Comment by liveeverymoment** [comment] 2023-02-24 04:55
I am using wsl2, I got the same issue that occured to @kurgol , I manually tried to restart Lxss Manager and then it gave error, but issue was resolved.
