### ISSUE TITLE
CTRL + key does not work properly using Brazilian Portuguese keyboard layout

### ISSUE THREAD

**Issue by LuisHDantas** [microsoft/WSL#11591] opened 2024-05-16 14:23 UTC
### Windows Version

Microsoft Windows [versão 10.0.22631.3447]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu 22.04

### Other Software

Discovered the problem while trying to use Neovim, but it happens anywhere in WSL.

### Repro Steps

Pressing CTRL-] using BR keyboard layout results in "^\\". Pressing ']' key without CTRL works properly, but it CTRL is pressed it thinks I am pressing '\', which is the key that should be in that place if I used a US layout.

### Expected Behavior

CTRL - ] should give me ^]

### Actual Behavior

CTRL - ] gives me ^\

**Comment by LuisHDantas** [comment] 2024-05-16 14:24
Basically, I believe it is considerand the US layout instead of the BR layout when trying to use shortcuts that require 2 or more keys.

**Comment by OneBlue** [comment] 2024-05-16 18:41
Thank you @LuisHDantas. Is this in a terminal app, or in a GUI app that you see this ?

**Comment by LuisHDantas** [comment] 2024-05-16 18:49
> Thank you @LuisHDantas. Is this in a terminal app, or in a GUI app that you see this ?

I have not tried a GUI app, but I can say that it happens anywhere in the terminal (Neovim, or just the command line). I have tested with "showkey -a" and it gives me the wrong output that I mentioned above as well.

**Comment by OneBlue** [comment] 2024-05-16 18:51
Ok thank you. In this case this means that the issue comes from your terminal. If you're using Windows Terminal, I'd recommend [opening an issue there](https://github.com/Microsoft/terminal/issues).

Closing since the issue isn't coming from WSL.

**Closed by OneBlue** 2024-05-16 18:51 UTC
