### ISSUE TITLE
wsl 2.4.4.: An assertion failure has occurred. Error code: Wsl/Service/0x8007029c [SOLVED - but...]

### ISSUE THREAD

**Issue by josemtella** [microsoft/WSL#12294] opened 2024-11-19 15:46 UTC
### Windows Version

Microsoft Windows [Version 10.0.26100.2448]

### WSL Version

2.4.4.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.167.4-1

### Distro Version

Any distro

### Repro Steps

start any distro

### Expected Behavior

start distro

### Actual Behavior

The error `An assertion failure has occurred. Error code: Wsl/Service/0x8007029c` appears and the distribution does not start.

**Comment by espresso3389** [comment] 2024-11-19 17:23
I have the same issue. And, just trying to install another distro (debian), it shows the following error:

![Image](https://github.com/user-attachments/assets/ffc375d3-75a1-42bf-9d60-dfab7a290b6c)

**Comment by Marukome0743** [comment] 2024-11-20 01:14
The log file:
[WslLogs-2024-11-20_09-59-45.zip](https://github.com/user-attachments/files/17823254/WslLogs-2024-11-20_09-59-45.zip)

**Comment by thomasyangbo** [comment] 2024-11-21 04:15
the same problem[WslLogs-2024-11-21_11-59-48.zip](https://github.com/user-attachments/files/17839698/WslLogs-2024-11-21_11-59-48.zip)

**Comment by ssi-kt** [comment] 2024-11-21 05:28
I have the same issue, but it was resolved by downgrading to version 2.3.26.

**Comment by thomasyangbo** [comment] 2024-11-21 05:32
> I had the same issue, but it was resolved by downgrading to version 2.3.26.

how to downgrade to 2.3.26?

**Comment by ssi-kt** [comment] 2024-11-21 05:46
> > I had the same issue, but it was resolved by downgrading to version 2.3.26.
> 
> how to downgrade to 2.3.26?

https://github.com/microsoft/WSL/releases/tag/2.3.26
only need to run either wsl.2.3.26.0.x64.msi or wsl.2.3.26.0.arm64.msi.
Which one to run depends on your environment.

**Comment by espresso3389** [comment] 2024-11-21 06:14
> how to downgrade to 2.3.26?

To downgrade WSL version is very easy regardless of how you install WSL 2.4.4:

```
wsl --uninstall
wsl --install Ubuntu-24.04
```

`Ubuntu-24.04` on the command line is just a example, use any distro you want to install.

**Comment by OneBlue** [comment] 2024-11-22 23:53
Thank you @josemtella. Looking at the logs, the issue seems to be coming from a string encoding errors. 

Could you share what's your Windows username, and what environment variables you have set on the machine ? I wonder if there are special characters that are causing this error.

**Comment by josemtella** [comment] 2024-11-23 09:51
Tank @OneBlue, Indeed, the characters in the "prompt" environment variable are causing the error.
I have:

prompt=$_$E[92m┌─$E[93m[CMD]$E[92m─($E[94mcpanld4@%computername%$E[92m)$_└─$E[93m[$E[97m$p$E[93m]$E[94m$$$S$E[0m

If I remove it or set the value prompt=[$p], the Linux distributions boot without problems.
Just putting the previous prompt back, it fails again

I would like to keep the prompt, please consider this a bug.

**Comment by josemtella** [comment] 2024-11-23 10:16
I leave the logs once I have seen the problem with my answer: https://github.com/microsoft/WSL/issues/12294#issuecomment-2495421233

[WslLogs-2024-11-23_11-13-40.zip](https://github.com/user-attachments/files/17879296/WslLogs-2024-11-23_11-13-40.zip)

**Comment by benhillis** [comment] 2024-11-25 21:59
@josemtella - I think I have a fix, could you give me some instructions on how validate this? You're setting some environment variable on the Windows side right?

**Comment by josemtella** [comment] 2024-11-26 09:59
@benhillis see:

![Image](https://github.com/user-attachments/assets/7b8722e5-748c-4b07-9c18-64609bb6fb41)

**Comment by josemtella** [comment] 2024-11-26 15:28
[code]
set var=└─
[/code]

**Comment by benhillis** [comment] 2024-11-26 20:25
Thanks! I have confirmed my fix resolves this issue.

**Comment by benhillis** [comment] 2024-12-03 23:08
Fixed with https://github.com/microsoft/WSL/releases/tag/2.4.5 - sorry for the inconvenience here.

**Closed by benhillis** 2024-12-03 23:08 UTC
Labels: fixinbound
