### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by meishiqi** [microsoft/WSL#11130] opened 2024-02-07 08:52 UTC
### Windows Version

10.0.22621.2506

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Other Software

flutter

### Repro Steps

flutter doctor
![image](https://github.com/microsoft/WSL/assets/69063519/5609f3f0-c5c4-4821-98da-1686bd18f379)

### Expected Behavior

flutter download

### Actual Behavior

/usr/bin/env: ‘bash\r’: No such file or directory

**Comment by OneBlue** [comment] 2024-02-07 23:07
Closing since the issue isn't caused by WSL. I'd recommend investigating what exactly flutter is doing to understand what the root cause is.

**Closed by OneBlue** 2024-02-07 23:07 UTC

**Comment by MostafaKK00** [comment] 2024-03-19 03:48
kali@DESKTOP-1CNI336:~$ flutter doctor
/usr/bin/env: ‘bash\r’: No such file or directory
kali@DESKTOP-1CNI336:~$ cd ..
kali@DESKTOP-1CNI336:/home$ cd ..
kali@DESKTOP-1CNI336:/$ ls
bin   dev  home  lib    lib64   lost+found  mnt  proc  run   snap  sys  usr
boot  etc  init  lib32  libx32  media       opt  root  sbin  srv   tmp  var
kali@DESKTOP-1CNI336:/$ cd snap
kali@DESKTOP-1CNI336:/snap$ ls
README  android-studio  bare  bin  core20  core22  flutter  gtk-common-themes  snapd  ubuntu-desktop-installer
kali@DESKTOP-1CNI336:/snap$
look
