### ISSUE TITLE
rethinkdb fail to start on windows subsystem for ubuntu!

### ISSUE THREAD

**Issue by anlexN** [Microsoft/WSL#2892] opened 2018-01-31 02:16 UTC
1. rethinkdb 2.3.6~0xenial (GCC 5.3.1)
2. Ubuntu 16.04.3 LTS
3. microsoft windows version 10.0.16299.192

wsl always hang up this problem:
```
anlex_N@N-Acer:~
$ rethinkdb
Recursively removing directory /home/anlex_N/rethinkdb_data/tmp
Previous message may not have been written to the log file (cannot flush stdout/stderr: Input/output error).
```
i also posted a [issue](https://github.com/rethinkdb/rethinkdb/issues/6606) on the rethinkdb repo, but don't solve my problem.
### please help me , good peoples!

**Comment by aseering** [comment] 2018-01-31 16:50
For what it's worth, I'm not able to reproduce this in the latest Insider builds.  So it may be fixed internally?

I installed rethinkdb following these instructions.  @anlexN, is this what you are doing?
https://rethinkdb.com/docs/install/ubuntu/

**Comment by aseering** [comment] 2018-01-31 16:54
(I know you said you can't actually run Insider builds for stability reasons, but at least that could narrow things down, and it means you will eventually get the fix via regular Windows Update.)

**Comment by therealkenc** [comment] 2018-05-25 02:31
Flies here on 17672 and Ubuntu 16.04. No idea what was broken or what might have been fixed since 16299 because no strace was provided. Executive decision to call this fixedin1803 until proven otherwise.

```
$ source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
$ wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install rethinkdb
 rethinkdb
Recursively removing directory /home/ken/rethinkdb_data/tmp
Initializing directory /home/ken/rethinkdb_data
Running rethinkdb 2.3.6~0xenial (GCC 5.3.1)...
Running on Linux 4.4.0-17672-Microsoft x86_64
Loading data from directory /home/ken/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 127.0.1.1, ::1
Listening on driver addresses: 127.0.0.1, 127.0.1.1, ::1
Listening on http addresses: 127.0.0.1, 127.0.1.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "DESKTOP_4UTIQSF_j87" 782f01bc-c854-4975-bd86-d61648e80268
```

**Closed by therealkenc** 2018-05-25 02:31 UTC
