### ISSUE TITLE
Error: 0x80070570 The file or directory is corrupted and unreadable.

### ISSUE THREAD

**Issue by NewtonChutney** [microsoft/WSL#10925] opened 2023-12-15 16:51 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.2861]

### WSL Version

WSL version: 2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu (all versions)

### Other Software

Docker Desktop (desktop/desktop-data disabled)
Podman Desktop (machine disabled)

### Repro Steps

Just had an update with wsl --update, and poof... started getting this issue

### Expected Behavior

wsl should launch/install properly

### Actual Behavior

wsl isn't getting installed properly
```shell
~
❯ wsl --install
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070570
Error: 0x80070570 The file or directory is corrupted and unreadable.

Press any key to continue...
The operation completed successfully.
```

### Diagnostic Logs

Email sent to wsl-gh-logs@microsoft.com

**Comment by NewtonChutney** [comment] 2023-12-15 17:00
I currently do not have any installed version of Ubuntu.. but before I had reset the installed "Ubuntu" distro, when I launched would say something about the `C:\Program Files\WSL\system.vhd` file being corrupted

**Comment by NewtonChutney** [comment] 2023-12-15 18:11
The same popup appears when I try to run the latest installer from github releases:
<img width="551" alt="image" src="https://github.com/microsoft/WSL/assets/70827815/6e51ba26-d022-4631-b4d2-d07962ab6010">

When I run the older one:
<img width="542" alt="image" src="https://github.com/microsoft/WSL/assets/70827815/fd11c282-21b0-4f6b-bee5-5a56e63a7746">

**Comment by OneBlue** [comment] 2023-12-15 18:50
> I currently do not have any installed version of Ubuntu.. but before I had reset the installed "Ubuntu" distro, when I launched would say something about the `C:\Program Files\WSL\system.vhd` file being corrupted

This is indeed what I saw in the logs. Unfortunately it might be that your disk is corrupted. One thing you can try would be to run: 

```
chkdsk /r /f
```

And see if that recovers. If not you might need to reinstall Windows.

**Comment by NewtonChutney** [comment] 2023-12-16 06:39
@OneBlue, thanks for the suggestion.. 
But nope.. chkdsk didn't help out 🥲

Cleaning up is the solution.. But shouldn't there be an uninstaller/installer that isolates the WSL components and fixes them.. I really don't understand how an installer fails to launch..

Anyhow, I ended up doing an in place upgrade.. (keep personal files only, removed apps) 
And all's good.. ♥ 
Thanks!

**Comment by ricardoboss** [comment] 2023-12-16 21:51
I had issues with docker engine not being able to start, so I decided to reinstall WSL.

Ended up with the same error message. `chkdsk /r /f` also didn't find any issues.

**Comment by OneBlue** [comment] 2023-12-18 19:34
Thank you for confirming. Closing since the issue is fixed.

**Comment by NewtonChutney** [comment] 2023-12-19 02:55
Yes, a component that's installed through the store.. But I couldn't fix it..
The WSL "app" wouldn't uninstall or anything..
There ought to be some other user-friendly way?

**Comment by OneBlue** [comment] 2023-12-19 22:05
> Yes, a component that's installed through the store.. But I couldn't fix it.. The WSL "app" wouldn't uninstall or anything.. There ought to be some other user-friendly way?

What do you mean by the "App app wouldn't uninstall" ? What exact error did you see ?

**Closed** 2023-12-19 22:06 UTC

**Comment by NewtonChutney** [comment] 2023-12-19 22:31
> ![image](https://github.com/microsoft/WSL/assets/70827815/b8ddbab6-46bc-4b1f-acd7-6098ede459d0)
> How do I reinstall wsl? I'm able to uninstall the upper app, but for the lower one, when I trigger an uninstall raises some weird error:
> ![image](https://github.com/microsoft/WSL/assets/70827815/eceaab93-83fe-49e6-ab1e-2e1e6b294547)

This is the error I get when uninstalling the "store app"

**Comment by NewtonChutney** [comment] 2023-12-19 22:33
> dism and sfc say restored and verification complete..
> Tried enabling and disabling the optional WSL feature.. and restarted
> 
> The same popup appears when I try to run the latest installer from github releases:
> <img width="551" alt="image" src="https://github.com/microsoft/WSL/assets/70827815/6e51ba26-d022-4631-b4d2-d07962ab6010">
> 
> When I run the older one:
> <img width="542" alt="image" src="https://github.com/microsoft/WSL/assets/70827815/fd11c282-21b0-4f6b-bee5-5a56e63a7746">
> 
> 

Alright, if we say it is disk corruption.. How does a freshly downloaded installer fail to launch as well?

**Comment by OneBlue** [comment] 2023-12-19 22:55
This would be because the previous installation is corrupted, and so the installer would fail to upgrade the previous installation. Unfortunately this is not something that can be fixed on the installer side

**Comment by NewtonChutney** [comment] 2023-12-20 04:22
> This would be because the previous installation is corrupted, and so the installer would fail to upgrade the previous installation. Unfortunately this is not something that can be fixed on the installer side 

Alright.. 🥶
ᓚᘏᗢ

Thanks for helping out!

**Comment by AidanWelch** [comment] 2024-04-18 22:59
> This would be because the previous installation is corrupted, and so the installer would fail to upgrade the previous installation. Unfortunately this is not something that can be fixed on the installer side

So why cannot it not be deleted and reinstalled?

**Comment by AidanWelch** [comment] 2024-04-18 23:18
Okay, I was able to fix the issue without reinstalling my OS be deleting everything I could in `C:\Program Files\WSL` except 2 files that were being used by a program.  I then uninstalled Ubuntu.  Next, I disabled the Windows Features `Windows Subsystem for Linux`, `Windows Hypervisor Platform`, and `Virtual Machine Platform`.  I rebooted once that was done.  Then I enabled the features again(and I think rebooted again), and finally reinstalled Ubuntu from the MS Store- and it worked again.

**Comment by NewtonChutney** [comment] 2024-04-19 02:36
Ahh, that's nice. 
I had the same error message when uninstalling.. And reinstalling didn't work..

I guess mine was in a really bad state or else the team might have fixed something meanwhile.. 🥲

**Comment by chbroecker** [comment] 2024-04-20 13:15
I am also experiencing the same error. 

When you are saying that you deleted the `C:\Program Files\WSL` folder how did you manage to run `wsl --install` again @AidanWelch? If I delete the folder it does not reappear and I get the path not found error below. 

![image](https://github.com/microsoft/WSL/assets/24273989/13f6886f-858b-48b2-bbe9-e2ab6fd8f80f)

Really do not want reinstall Windows again because one of its apps got corrupted..

**Comment by AidanWelch** [comment] 2024-04-20 13:24
@chbroecker Did you uninstall your distro from the MS store then reinstall it?

**Comment by Lorenzo9196** [comment] 2024-09-24 02:16
> Okay, I was able to fix the issue without reinstalling my OS be deleting everything I could in `C:\Program Files\WSL` except 2 files that were being used by a program. I then uninstalled Ubuntu. Next, I disabled the Windows Features `Windows Subsystem for Linux`, `Windows Hypervisor Platform`, and `Virtual Machine Platform`. I rebooted once that was done. Then I enabled the features again(and I think rebooted again), and finally reinstalled Ubuntu from the MS Store- and it worked again.

This worked for me, I was facing the same issue
