### ISSUE TITLE
Broke in 1.13: localhost:PORT from windows host no longer gets handled by process running in WSL2

### ISSUE THREAD

**Issue by Persedes** [microsoft/WSL#9746] opened 2023-03-06 18:13 UTC
Follow up from linked issue:
After updating the WSL version, got the following error message:

```
The connection to the server kubernetes.docker.internal:6443 was refused - did you specify the right host or port?
```

```
wsl --version
WSL version: 1.1.3.0
Kernel version: 5.15.90.1
WSLg version: 1.0.49
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1574
```

_Originally posted by @Persedes in https://github.com/microsoft/WSL/issues/8679#issuecomment-1456261513_

Was able to fix it by downgrading to 1.0.3

**Comment by pmartincic** [comment] 2023-03-06 19:54
Can you give the output of `ss -lntp` from the guest, and the output of `netstat -an | findstr /c:"6443" | findstr /c:"LISTENING"` from the host(windows)?

And /logs would be lovely.

**Comment by spitcat** [comment] 2023-03-08 10:01
Hi same here:

ss -lntp 
```❯ ss -lntp
State        Recv-Q       Send-Q              Local Address:Port                Peer Address:Port       Process
LISTEN       0            511                       0.0.0.0:3007                     0.0.0.0:*           users:(("node",pid=5315,fd=22))```

**Comment by spitcat** [comment] 2023-03-08 10:08
Same issue here 
```bash
State        Recv-Q       Send-Q              Local Address:Port                Peer Address:Port       Process
LISTEN       0            511                       0.0.0.0:3007                     0.0.0.0:*           users:(("node",pid=5315,fd=22))
```

`netstat -an | findstr /c:"6443" | findstr /c:"LISTENING"`

```
 netstat -an | findstr /c:"3007" | findstr /c:"LISTENING"
  TCP    127.0.0.1:3007         0.0.0.0:0              LISTENING
```

when use address from ubuntu 172.31.114.179 all works

**Comment by pmartincic** [comment] 2023-03-08 17:28
@spitcat, that all looks expected and normal to me. You're bound on 0.0.0.0:3007 on the guest and 127.0.0.1:3007 on the host?

**Comment by pmartincic** [comment] 2023-03-08 17:29
Does 127.0.0.1:3007 not work on the host?

**Comment by chrisnruud** [comment] 2023-03-09 06:21
I have the same issue - using azure-sql-edge getting either the same issues as here:
https://github.com/microsoft/mssql-docker/issues/804
or getting "cannot bind to 0.0.0.0:11433 already bound"
Had to revert to 1.0.3 to continue working. I won't upgrade to 1.1.3 to provide loge because I have to be able to work on wsl :)

**Comment by spitcat** [comment] 2023-03-09 09:24
```powershell
PS C:\Users\_> Invoke-WebRequest -URI http://127.0.0.1:3007
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
PS C:\Users\_> Invoke-WebRequest -URI http://172.31.114.179:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
PS C:\Users\_> Invoke-WebRequest -URI http://localhost:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
PS C:\Users\_> Invoke-WebRequest -URI http://localhost:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
PS C:\Users\_> Invoke-WebRequest -URI http://127.0.0.1:3007
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
PS C:\Users\_> Invoke-WebRequest -URI http://localhost:3007/
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
PS C:\Users\_> Invoke-WebRequest -URI http://172.31.114.179:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
PS C:\Users\_> Invoke-WebRequest -URI http://172.31.114.179:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
PS C:\Users\_> Invoke-WebRequest -URI http://172.31.114.179:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
PS C:\Users\_> Invoke-WebRequest -URI http://172.31.114.179:3007/
Invoke-WebRequest: {"statusCode":404,"message":"Cannot GET /","error":"Not Found"}
```

```bash
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.31.114.179/20 brd 172.31.127.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe6e:f712/64 scope link
       valid_lft forever preferred_lft forever
```
@pmartincic  this is what happen when port stop responding. 
node application runs all the time i can sometimes get response by 127.0.0.1 / localhost. When i use internal ubuntu address i get response all the time.

**Comment by sec** [comment] 2023-03-10 12:36
Having the same problem - looking at other issues like #9760 or #9751 this looks connected.
Running some services inside WSL2, I can access them from host machine.
But after some time and/or load on those - they cannot be reached from host - even they are working fine under WSL and can be accessed from within WSL.

`netstat` is showing something like
```
  TCP    127.0.0.1:8080         0.0.0.0:0              LISTENING
  TCP    [::1]:8080             [::]:0                 LISTENING
```

When I try to `telnet` - connection is made, but no data in or out.
Only `wsl --shutdown` help to resolve the issue, but only for a short time.

**Comment by pmartincic** [comment] 2023-03-11 01:09
Thanks @spitcat, @sec

I'm sorry, I've gotten routed elsewhere and won't be able to look into this right now.

**Comment by ahmed2m** [comment] 2023-03-14 10:19
I got this one as well. For some reason needs a system restart (not just wsl shutdown) to be fixed.

**Comment by kluevandrew** [comment] 2023-04-12 13:43
Same for me, sometimes restart helps, sometimes it's not

**Comment by pmartincic** [comment] 2023-04-12 16:42
https://github.com/microsoft/WSL/releases/tag/1.2.1 Addresses some causes of this.

**Comment by chrisnruud** [comment] 2023-04-17 08:40
Seems to be fixed in 1.2.1 and onward, at least for my use cases.

**Closed** 2023-04-24 11:06 UTC
Labels: needs-author-feedback

**Comment by eldair** [comment] 2023-04-28 10:05
This issue is still not resolved

**Comment by sec** [comment] 2023-04-28 10:06
Yes, also having still the same issue.

**Comment by pmartincic** [comment] 2023-05-01 17:04
@eldair, @sec,

Which `wsl --version` are you on?

**Comment by pmartincic** [comment] 2023-05-02 18:07
Thanks for reporting it. All the logs I've seen point to the issue that was fixed in `1.2.1`. If you're still experiencing issues I will need more logs.

- `wsl.exe --shutdown`
- Start [log](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs-recommended-method) collection
- Reproduce the issue
- Stop log collection and send them our way.

I may end up asking for information about your enviroment/repro after looking at the logs.

**Comment by eldair** [comment] 2023-05-03 09:41
@pmartincic I will send the logs the next time it happens :/ it's pretty inconsistent

**Comment by sec** [comment] 2023-05-08 09:43
@pmartincic Hi, sorry for late reply, I was on vacation :) I'm using newest WSL. Attaching both network logs and other collected logs. Repro is something like:
- run docker inside wsl, start some services (some are grpc, some http)
- run some services on host, that connect to those services
- after multiple connections, all new connections are "stale" - they seem connected, but no data is sent/received (or the connection speed is counted in bytes per minute)
- connecting from inside wsl to those services work, but from outside it's getting timeouts
- restarting docker/services doesn't help
- only `wsl --shutdown` resolve the issue, until next run :)

[WslLogs-2023-05-08_11-24-11.zip](https://github.com/microsoft/WSL/files/11419929/WslLogs-2023-05-08_11-24-11.zip)
[networking.bat.output.txt](https://github.com/microsoft/WSL/files/11419931/networking.bat.output.txt)
[wsl.etl.zip](https://github.com/microsoft/WSL/files/11419938/wsl.etl.zip)
