### ISSUE TITLE
Cannot read keys (from Windows exe)

### ISSUE THREAD

**Issue by laktak** [Microsoft/WSL#1433] opened 2016-11-29 19:53 UTC
When I launch a C# Windows executable inside bash that calls `Console.ReadKey()` I get the following error:

> Error: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.

Rewriting these apps is not really an option. Would it be possible to support this feature (inside tmux)?

OS Name: Microsoft Windows 10 Enterprise Insider Preview
OS Version: 10.0.14971 N/A Build 14971

**Comment by benhillis** [comment] 2016-11-29 22:01
I looked into this a bit and what's happening here is an ioctl is being issued to the StandardInput handle. This is a Windows ioctl and the handle representing StandardInput a special WSL handle that's referencing a TTY or PTY handle.  I'll have to chat with my console comrades about the right way to get this plumbed up. Perhaps we can special case this ioctl into a "read one byte" or something...

**Comment by laktak** [comment] 2016-12-01 07:38
@benhillis That's great!

Could you also check if cmd.exe is using the same function for its input? I sometimes need to start cmd.exe (inside tmux) for various reasons (starting .bat files is easier or pasting a \ path). Maybe this could be fixed as well?

**Comment by laktak** [comment] 2017-01-30 13:03
@benhillis do you have any updates on this?

**Comment by benhillis** [comment] 2017-01-31 16:18
@laktak - This is on the backlog but it's unlikely to be fixed in time for Creator's update. Frankly I think this is a CRL bug.  They're issuing ioctls on whatever handle happens to be the standard input handle without checking the type.  There is no guarantee this will be a console handle yet they are issuing unique console-specific ioctls to the handle.

**Comment by laktak** [comment] 2017-04-27 08:29
@benhillis now that the Creator's update is done (great job btw), could you take another look at this or ping the necessary people?

**Comment by benhillis** [comment] 2017-05-05 17:02
@laktak - looking at this a bit more, I do think this is a bug with the Windows application.  Assuming that standard input is a console is not always a safe assumption. Even outside of wsl input can be a pipe or a file, for example:

`echo foo | consoleapp.exe`

https://msdn.microsoft.com/en-us/library/471w8d85(v=vs.110).aspx

**Comment by laktak** [comment] 2017-05-09 17:51
@benhillis Indeed, buried in the remarks of [Console.ReadKey](https://msdn.microsoft.com/en-us/library/x3h8xffw(v=vs.110).aspx):

> The ReadKey method reads from the keyboard even if the standard input is redirected to a file with the SetIn method.

However AFAIK this is the only method that can read a single key (in the C# api) and is thus used by everyone. If this can't be made to work, do you know of a workaround or API I could use?

PS: the error message suggests `Console.Read` but this does not read a single key:

> The Read method blocks its return while you type input characters; it terminates when you press the Enter key.

**Comment by 131** [comment] 2017-11-04 00:57
Still an issue in Fall Update (coming from #2629).

**Comment by parkovski** [comment] 2017-12-04 00:36
The relevant problem line in .NET Core - it's probably similar on .NET desktop: https://github.com/dotnet/corefx/blob/1687ee590a3449a8f72a5550ab1cddc93f2c7832/src/System.Console/src/System/ConsolePal.Windows.cs#L345

The solution unfortunately is for the .NET app to support this by checking if input is redirected and using `Console.In.Read` instead, but it has to only do this with redirected input because for a regular console handle that won't return after just one key.

Translating Linux ttys to Windows console devices would help in this case, but still won't enable piped input on Windows.

**Comment by benhillis** [comment] 2018-04-04 18:13
Marking as a duplicate of #2370

**Closed by benhillis** 2018-04-04 18:13 UTC
Labels: console, fixedininsiderbuilds, interop
