### ISSUE TITLE
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.

### ISSUE THREAD

**Issue by rcordoni** [microsoft/WSL#5371] opened 2020-06-09 23:56 UTC
Windows 10 build 19640
Automount not working

**Comment by rcordoni** [comment] 2020-06-10 00:04
wsl.conf:
[automount]
enabled = true
mountFsTab = true
root = /
options = "uid=1000,gid=1000,umask=022,fmask=11,metadata"

fstab:
LABEL=cloudimg-rootfs   /        ext4   defaults        0 0
C: /c drvfs uid=1000,gid=1000,umask=022,fmask=11,metadata       0 0
D: /d drvfs uid=1000,gid=1000,umask=022,fmask=11,metadata       0 0
F: /f drvfs uid=1000,gid=1000,umask=022,fmask=11,metadata       0 0
G: /g drvfs uid=1000,gid=1000,umask=022,fmask=11,metadata       0 0

Note - mountFsTab option is being used to workaround the problem - so I have duplicate entries in fstab.  With this workaround, I am not able to enable wsl 2 support in Docker for Desktop.

Sample error in dmesg output for drive c mount:
[   10.655517] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /c (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=1000;gid=1000;uid=1000;gid=1000;umask=022;fmask=11;metadata;symlinkroot=/
[   10.655518] ) failed: 2
[   10.655681] 9pnet_virtio: no channels available for device drvfs
[   10.655683] init: (1) WARNING: mount: waiting for virtio device...

**Comment by rcordoni** [comment] 2020-06-10 00:06
not sure if this matters - but my boot drive is ssd.  The rest of my drives are spinning disks.  They don't automount either.

**Comment by therealkenc** [comment] 2020-06-10 02:54
/dupe #5371. If the status over there flips and you are still experiencing problems, speak up and we can revisit.

**Comment by inthevortex** [comment] 2020-06-16 07:20
Has any solution come for this yet? I am on OS build 19645.1 and still having the issue.

**Comment by dannya** [comment] 2020-06-19 10:31
@therealkenc it seems that you've marked this issue as a duplicate of itself?

**Comment by therealkenc** [comment] 2020-06-19 11:21
Thanks. That was a botched attempt at ref #4101. Now you're free, but probably worth keep an eye out over there.

**Comment by inthevortex** [comment] 2020-06-19 17:52
The issue has been fixed in OS Build 20150.1000

**Comment by dannya** [comment] 2020-06-19 19:33
@inthevortex I've seen this error today myself on 20150.1000 (though it didn't reoccur after I restarted)

**Comment by inthevortex** [comment] 2020-06-19 19:35
@dannya  Yaa, restarting must have done the trick. But I think it is now fixed. I had put the basic scripts in my .zshrc before.

**Comment by rcordoni** [comment] 2020-06-19 23:25
Just to confirm upgrading to build 20150 and updating to the latest WSL2 has fixed my problem.  Automount now works. Yeah!
Thanks All.

**Comment by therealkenc** [comment] 2020-06-19 23:38
Alright thanks, and apologies for the botched link earlier. If the OP is okay on 20150 then the reasonable corollary is this was /dupe #4101. If folks experience further "`9pnet_virtio: no channels available for device drvfs`" related unpleasantness in >20150 (to the extent that's likely), please open a new issue so it can be tracked separately from whatever was addressed here.

**Closed by therealkenc** 2020-06-19 23:38 UTC

**Comment by xuelongqy** [comment] 2021-05-22 15:35
[download-the-linux-kernel-update-package](https://docs.microsoft.com/zh-cn/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
