### ISSUE TITLE
Serial Connection Movidius Neural Compute Stick

### ISSUE THREAD

**Issue by EscVM** [Microsoft/WSL#3185] opened 2018-05-12 10:36 UTC
Hi! I'm trying to use the Movidius neural compute stick devise on WSL. Unfortunately, I can't figure out how to enable the serial communication. 

Firstly, I've tried with `stty -F /dev/ttyS5 -a`, but it gives me a stty error "stty: /dev/ttyS5: Input/output error". Thanks for your help.

**Comment by DarthSpock** [comment] 2018-05-14 12:49
This is a dupe of quite a number of other dev/tty* issues. Short answer is WSL doesn't support raw device and needs `libusb` to be fully implemented. Here's the [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/31920928-add-libusb-support-to-wsl)

**Comment by DarthSpock** [comment] 2018-05-14 13:48
Yes. The UserVoice provided clarity for what you can and can't do.

**Comment by benhillis** [comment] 2018-05-14 13:57
USB serial devices should work on newer builds. What build are you running?

**Comment by EscVM** [comment] 2018-05-14 14:05
Ok! Thank you for your help @DarthSpock

**Comment by EscVM** [comment] 2018-05-14 19:50
@benhillis I'm using the OS Build 16299.431. Before opening this issue, I had found this article (https://blogs.msdn.microsoft.com/wsl/2017/04/14/serial-support-on-the-windows-subsystem-for-linux/). Unfortunately, I when I run 'tty -F /dev/ttySN -a', with N=COM port, I have an Input/Output error.

**Comment by therealkenc** [comment] 2018-05-14 20:07
I don't have one of these, but for the lulz I cloned `https://github.com/movidius/ncsdk.git`. Sure enough it links [libusb](https://launchpad.net/ubuntu/+source/libusb). That blog post is about RS232 serial devices, which typically these days are USB dongles but don't have to be. I don't think you are going to find this thing on `/dev/ttyS?` either.

This is dupe #1521 #2287 #2195 #2185 #412 et at. User Voice already cited above.
`

**Closed** 2018-05-24 18:51 UTC

**Comment by kablondino** [comment] 2018-08-17 11:06
This issue shouldn't be marked as closed. There is no solution in actually getting it recognized by the WSL that I could find.

**Comment by therealkenc** [comment] 2018-08-17 18:06
No because dupe #2195 #2185 #412 are open (which is two too many) as is the [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/31920928-add-libusb-support-to-wsl).
