### ISSUE TITLE
WSL doesn't works

### ISSUE THREAD

**Issue by Aoerz** [microsoft/WSL#4265] opened 2019-07-03 11:37 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.593]
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

Today I installed WSL, and it worked well in past hours, but when I restart WSL, it doesn't appear some prompt information, and it looks like:

![Snipaste_2019-07-03_19-14-55](https://user-images.githubusercontent.com/32593941/60587963-5a914280-9dc8-11e9-9a06-556d3acf2ea9.jpg)
and I can input, but just input, it doesn't respond.

I reboot my PC several times, but the prompt information still disappears.  

So what can I do?

**Comment by mscraigloewen** [comment] 2019-07-03 17:17
This seems to be a duplicate of #4047

**Closed by mscraigloewen** 2019-07-03 17:17 UTC
