### ISSUE TITLE
GDB will not launch debuggee - regression since 16299

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/WSL#2870] opened 2018-01-22 21:39 UTC
I can debug with GDB on 16299.192 and it works fine.
```
dan@danmose2:~/gcc$ gdb ./test
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
...
Reading symbols from ./test...done.
(gdb) break main
Breakpoint 1 at 0x40052a: file test.c, line 5.
(gdb) run
Starting program: /home/dan/gcc/test

Breakpoint 1, main () at test.c:5
5           printf("Hello world\n");
```

But on 17074 insider build it fails:
```
dan@DESKTOP:/mnt/c/gcc$ gcc -o test -Wall test.c -g
dan@DESKTOP:/mnt/c/gcc$ strace -f -o out2 gdb ./test
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
...
Reading symbols from ./test...done.
(gdb) break main
Breakpoint 1 at 0x400875: file test.c, line 17.
(gdb) run
Starting program: /mnt/c/gcc/test
During startup program exited normally.
(gdb) q
dan@DESKTOP:/mnt/c/gcc$ grep PTRACE out2
7416  ptrace(PTRACE_TRACEME, 0, NULL, NULL) = -1 EPERM (Operation not permitted)
```
 @therealkenc mentioned the PTRACE_TRACEME EPERM is the same on regular Linux. I'll share a full strace when I get back home to this box.

Broken out from https://github.com/Microsoft/WSL/issues/2028 which concerns LLDB being broken.

**Comment by danmosemsft** [comment] 2018-01-23 03:27
I can confirm that @Brian-Perkins suggestion of ` set disable-randomization off` in gdb seems to work around it:
```
dan@DESKTOP-CJJBOPC:/mnt/c/gcc$ gdb ./test
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
...
Reading symbols from ./test...done.
(gdb) set disable-randomization off
(gdb) break main
Breakpoint 1 at 0x400875: file test.c, line 17.
(gdb) run
Starting program: /mnt/c/gcc/test

Breakpoint 1, main (argc=1, argv=0x7fffe03f4f68) at test.c:17
17          doit();
```

**Comment by therealkenc** [comment] 2018-01-23 04:06
Ref #1185 ([message](https://github.com/Microsoft/WSL/issues/1185#issuecomment-354350959)). If the regression was 17063, that's a month (since Dec 19th) that no one on Insiders noticed. Interesting data point.

**Comment by Brian-Perkins** [comment] 2018-01-24 21:28
This should be fixed in 17083.

**Comment by danmosemsft** [comment] 2018-01-30 00:50
@therealkenc you confirmed this fix it seems from the vscode issue? If so I will close.

**Comment by therealkenc** [comment] 2018-01-30 01:21
Yeah we are all good now. Normally fixedinsiderbuilds tags are held in the open state until the next stable release (for better or worse), which is probably why Brian didn't close it. But since this was transient seems appropriate to call it a wrap. Maybe we need a insider-regression tag or something 🤷.

**Comment by danmosemsft** [comment] 2018-01-30 01:27
Thanks for confirmation.

**Closed** 2018-01-30 01:26 UTC
Labels: fixedininsiderbuilds
