### ISSUE TITLE
Error Wsl/Service/CreateInstance/0xd000020c with code 4294967295 (0xffffffff)

### ISSUE THREAD

**Issue by dashqua** [microsoft/WSL#11255] opened 2024-03-06 19:05 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3235]

### WSL Version

2.1.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

CYGWIN_NT-10.0-22631 version 3.4.5-1.x86_64 (runneradmin@fv-az420-156) (gcc version 11.3.0 (GCC) ) 2023-01-19 19:09 UTC

### Distro Version

Ubuntu-22.04

### Repro Steps

- Opening my Ubuntu setup in Windows Terminal (Preview)
I believe the command of the shortcut is C:\WINDOWS\system32\wsl.exe -d Ubuntu

### Expected Behavior

I was expecting to be connected to my Ubuntu setup; I attach here an example of what it looked like
![pbm](https://github.com/microsoft/WSL/assets/29821878/d719ce60-a1c6-4afa-bad6-09cbd26df8f2)

The user is 'thomas', my user's home directory contains a tree of directories and files. As you can see, .bashrc and my PS1 were also altered. I cannot recall the WSL version I was using before this issue, as I tried to install the version 2 at some point but I am not sure I succedded at the time.

### Actual Behavior

When I replicate the aboe steps, instead of seeing my WSL setup, I get the following error

> Error: 0xd000020c
> Error code: Wsl/Service/CreateInstance/0xd000020c
> 
> [process exited with code 4294967295 (0xffffffff)]
> You can now close this terminal with Ctrl+D, or press Enter to restart.
> 

### Diagnostic Logs

[WslLogs-2024-03-06_20-03-40.zip](https://github.com/microsoft/WSL/files/14514377/WslLogs-2024-03-06_20-03-40.zip)

**Comment by dashqua** [comment] 2024-03-06 19:15
I had already seen some of the links proposed by the bot, but abyways none of them is helpful for me.
I hope I was clear in my post, please ask me more details if needed.

**Comment by raydavis** [comment] 2024-03-06 20:08
I've been using WSL Ubuntu successfully for years, but as of this morning it fails with the above error.

```
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c

Current directory:
C:\Users\k

Command to be executed:
"C:\WINDOWS\SYSTEM32\wsl.exe"

ConEmuC: Root process was alive less than 10 sec, ExitCode=xFFFFFFFF(4294967295).
Press Enter or Esc to close console...
```

"wsl.exe --status" reports no problem.

```
PS C:\Users\k> wsl.exe --version
WSL version: 2.1.4.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3930

PS C:\Users\k> wsl.exe --status
Default Distribution: Ubuntu
Default Version: 2
```

**Comment by dashqua** [comment] 2024-03-06 20:33
I have not used WSL in a month on this machine, but if was working fine last time I checked. This is what I get:
```
C:\Users\thomas>wsl --version
WSL version: 2.1.4.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3235

C:\Users\thomas>wsl --status
Default Distribution: Ubuntu-22.04
Default Version: 2

C:\Users\thomas>
```

**Comment by dpiccoloCSC** [comment] 2024-03-06 21:59
Following. I have the same exact issue. I use WSL (ubuntu) periodically, at least once a week if no more. It used to work without any issues, but since today I'm also getting the "Wsl/Service/CreateInstance/0xd000020c" error.

**Comment by benhillis** [comment] 2024-03-06 23:46
Thanks for your patience, everybody. We've been unable to reproduce this locally, but I have some additional steps that will help us debug this. Could you please set the below reg key, then re-run log collection? This will put the lxcore driver into verbose logging mode which should help identify why init is falling over.

1. Set this reg key
`reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lxss /v PrintLogLevel /t REG_DWORD /d 3 /f`
2. Collect logs (https://aka.ms/wsllogs)
3. Delete Key:
`reg delete HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lxss /v PrintLogLevel /f`

**Comment by pc-guan** [comment] 2024-03-07 08:49
rollback to lower version

**Comment by hdc-dragonfly** [comment] 2024-03-07 10:15
I faced this yesterday, I have no clue what is going on here, It was working fine until yesterday. I'm just a "advanced user" I did fully reset WSL, DISM, SFC. System restore didn't help either but it seems to have crashed yesterday with some windows updates...
but even rolling back the updates didn't help.

KB5034848
KB5034467
KB5034765

The weird thing is that Docker seems to be working normally by the way

**Comment by mhacklAimit** [comment] 2024-03-07 10:17
also had the same, docker was not working till I switched docker to use wsl2 
ubuntu still has the problem
now installed debian, debian is working fine.

for me the problem started yesterday, but my update history says my last update was installed on 15/02, the only update I had yesterday were some windows defender rules

**Comment by dipling78** [comment] 2024-03-07 13:24
Same issue here since today with WSL 2.1.4.0 on Win10 22H2 (10.0.19045.4046), last MS updates were installed on Feb 28th.

Fortunately, on my machine only WSL1 makes trouble - after executing `wsl --set-version Ubuntu-22.04 2` I'm able to utilize WSL again.

**Comment by dpiccoloCSC** [comment] 2024-03-07 13:41
Ok, I gave up. I ended up disabling WSL 1 (ubuntu 18) and installing WSL 2 Ubuntu 22.04.

**Comment by bboysil** [comment] 2024-03-07 14:36
I just did a "wsl --update" and got afterwards when trying to start "wsl" the error in questino came up: "Error code: Wsl/Service/CreateInstance/0xd000020c"

**Comment by hdc-dragonfly** [comment] 2024-03-07 15:00
> Did a "wsl --update", tried to start "wsl"; the error in question came up: "Error code: Wsl/Service/CreateInstance/0xd000020c"

same here. No way to use WSL1 anymore

**Comment by hdc-dragonfly** [comment] 2024-03-07 15:12
> Same here.
> 
> I was in an active WSL1 session that suddenly died.
> 
> I go have a look in the Store app -- Windows Subsystem for Linux showing "Modified minutes ago"
> 
> Rude!

Can you share the link with us?


By the way, did anyone try

wsl --install --enable-wsl1

?

**Comment by DesktopECHO** [comment] 2024-03-07 15:23
[WslLogs-2024-03-07_11-22-00.zip](https://github.com/microsoft/WSL/files/14526439/WslLogs-2024-03-07_11-22-00.zip)

**Comment by benhillis** [comment] 2024-03-07 15:34
@DesktopECHO - thank you, to confirm you set the below reg key prior to starting the trace? I'm not seeing any more traces.
reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lxss /v PrintLogLevel /t REG_DWORD /d 3 /f

You may actually need to restart after setting that key. Could you try that?

**Comment by DesktopECHO** [comment] 2024-03-07 16:57
I set the registry key, but I did not restart.   Not near this box right now, will have to pick this back up later today.

**Comment by raydavis** [comment] 2024-03-07 17:08
@benhillis I followed your instructions and produced the attached logs. Hope they help!

[WslLogs-2024-03-07_08-58-56.zip](https://github.com/microsoft/WSL/files/14527590/WslLogs-2024-03-07_08-58-56.zip)

**Comment by firewave** [comment] 2024-03-07 17:27
Happens with WSL1 Kali Linux but not with WSL1 Ubuntu 20.04.

[WslLogs-2024-03-07_18-25-48.zip](https://github.com/microsoft/WSL/files/14527837/WslLogs-2024-03-07_18-25-48.zip)

**Comment by dashqua** [comment] 2024-03-07 18:46
> Thanks for your patience, everybody. We've been unable to reproduce this locally, but I have some additional steps that will help us debug this. Could you please set the below reg key, then re-run log collection? This will put the lxcore driver into verbose logging mode which should help identify why init is falling over.
> 
>     1. Set this reg key
>        `reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lxss /v PrintLogLevel /t REG_DWORD /d 3 /f`
> 
>     2. Collect logs (https://aka.ms/wsllogs)
> 
>     3. Delete Key:
>        `reg delete HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lxss /v PrintLogLevel /f`

Here is the results of the log script, that I had already ran yesterday:
[WslLogs-2024-03-07_19-37-28.zip](https://github.com/microsoft/WSL/files/14528637/WslLogs-2024-03-07_19-37-28.zip)

Some important (and puzzling) things to mention:
- If I ran wsl.exe, I can start WSL on an Ubuntu session that is NOT the one I was using before.
- If I try to launch my WSL session via Windows Terminal Preview (as I always do, see below picture) I get the aforementioned error...
![Screenshot 2024-03-07 194235](https://github.com/microsoft/WSL/assets/29821878/ec909229-7676-493e-8082-0f462ec2ec1e)

**Comment by benhillis** [comment] 2024-03-07 19:15
@dashqua - thanks! It looks like you have two different distros, a WSL1 and a WSL2. The WSL2 is working and the WSL1 is not. Unfortunately the reg key is not causing any more logging to show up for WSL1, so I suspect the init user mode process is just crashing very early. I have a theory about what might be happening, but I would need somebody with a repro to try out a private version of the WSL msi to test. Let me know if anybody is open to that and I can coordinate with you.

Thanks for the help! Once we sort out what's wrong we'll get this added to our test matrix so this doesn't happen again...

**Comment by dashqua** [comment] 2024-03-07 19:22
@benhillis Happy to see that you take the problem seriously. I have to admit I did not understand all the jargon you employed, but I understand you need a volunteer to experiment something before coming back to me. I just want to make sure the issue is solved and my data is intact.

**Comment by hdc-dragonfly** [comment] 2024-03-07 19:27
So this one worked for me after unregistering every wsl1 distro

You may try it with a registered distro 

wsl --install --enable-wsl1

**Comment by wjristow** [comment] 2024-03-08 00:35
I've been using WSL for years without ever running into anything like this, but I ran into this same problem this morning.  I eventually worked around it by essentially uninstalling and re-installing.  I was already on WSL2, and I'm still on it after the workaround.  Not sure if there is anything new here that I have, in that it seems most of the frustration in the comments above are people who were using WSL1 and are now being forced to move to WSL2.  That said, if anyone else was frustrated by this in the wsl2 world, here is what I did:
```
wsl --unregister Ubuntu
```

followed by:
```
wsl --install Ubuntu
```

**Comment by benhillis** [comment] 2024-03-08 01:43
@wjristow - we're working on resolving this ASAP, sorry for the frustration. I want to advise people to avoid doing what you suggest though since it will result in data loss. We hope to have this resolved here shortly.

**Comment by wjristow** [comment] 2024-03-08 03:32
Ahhh, thanks for the update and warning @benhillis !

I did lose some environment/setup things using the approach I described, and I wish that hadn't happened.  I hope I haven't lost anything more.

**Comment by superEGO72** [comment] 2024-03-08 03:41
> @wjristow - we're working on resolving this ASAP, sorry for the frustration. I want to advise people to avoid doing what you suggest though since it will result in data loss. We hope to have this resolved here shortly.

Second that --- just had to rewrite all my aliases and reconstruct dev environment

Would have preferred to stay WSL1 for simplicity, but ended up tweaking bios settings and moving to WSL2

**Comment by crozone** [comment] 2024-03-08 06:37
Just hit this with both my WSL1 Debian installs, on two different PCs. They're both on Win11 22H2 22621.3155.

They were both working yesterday.
Interestingly, they have different errors. My Surface Book 2 gives the error `Wsl/Service/CreateInstance/0xd000020c` immediately. However, my other machine actually starts WSL and runs for a few seconds, but then crashes with `Wsl/Service/0xd00002fe`

@benhillis Would be open to testing an .msi.

**Comment by RAVoigt** [comment] 2024-03-08 11:52
Downgrading to 2.0.15 fixed this for me.

Microsoft Store background-updated WSL to 2.1.x overnight for me, which broke all of my open instances with the same errors as above.

**Comment by boulund** [comment] 2024-03-08 12:02
I just experienced this issue as well. I was using my WSL2 Ubuntu this morning, but when I came back after lunch it won't start.

**Comment by firewave** [comment] 2024-03-08 15:16
> I have a theory about what might be happening, but I would need somebody with a repro to try out a private version of the WSL msi to test. Let me know if anybody is open to that and I can coordinate with you.

@benhillis Do you still someone to test this? I would be open to do so.

**Comment by benhillis** [comment] 2024-03-08 16:25
@firewave - if you're down to try a few private MSI's shoot me an email, it would really help! My address is benhill (at) microsoft (dot) com.

**Comment by Adanufgail** [comment] 2024-03-08 17:13
Confirming the same thing. Worked yesterday, today it will not launch.

**Comment by dashqua** [comment] 2024-03-08 19:14
To everybody joining the thread: please provide as much info as you can. You can get the powershell log script above, and I also encourage you to attach screenshots to second your post. 

Hopefully, with a growing number of users reporting problems, a fix may appear soon!

**Comment by JRMatey-NIST** [comment] 2024-03-09 20:14
I have the same error on Ubuntu 20.04 + WSL 1.  Ubuntu 22.04 + WSL 1 is working.

>   NAME            STATE           VERSION
> \* Ubuntu-20.04    Stopped         1
>     Ubuntu-22.04    Running         1
> 

- In retrospect, I should have more faithfully backed up my Ubuntu WSL instances using wsl export;  I will do so in the future ☹️.  At the moment I am reluctant to do anything to the failing 20.04 until this is resolved -- for fear of data loss.  It would be really useful to recover my 20.04 instance -- it has configuration information for which I have inadequate backup.
- Does anyone know if using wsl --set-version  to convert a version 1 to a version 2 will recover a 20.04 instance that is failing under version 1?
- What about doing a rollback of wsl? https://devblogs.microsoft.com/commandline/install-wsl-with-a-single-command-now-available-in-windows-10-version-2004-and-higher/ -- wsl --update rollback 

Happy to run diagnostics if that will help resolve the problem.  Here is some information:

On my primary machine (fips enabled) where 20.04, wsl-1 is failing:

  WSL version: 2.1.4.0
  Kernel version: 5.15.146.1-2
  WSLg version: 1.0.60
  MSRDC version: 1.2.5105
  Direct3D version: 1.611.1-81528511
  DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
  Windows version: 10.0.19045.4046

On a second machine (not fips) where 20.04, wsl-1 works:

  WSL version: 2.0.9.0
  Kernel version: 5.15.133.1-1
  WSLg version: 1.0.59
  MSRDC version: 1.2.4677
  Direct3D version: 1.611.1-81528511
  DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
  Windows version: 10.0.19045.4046

**Comment by MitchBradley** [comment] 2024-03-10 00:22
I had the same problem with a Debian distro that uses WSL1.  Installing 2.0.15 fixed it.  I also tried 2.1.0, 2.1.1, and 2.1.3 but they all failed the same as 2.1.4

I can try to get some logs if you don't already have enough of them to inspect.

**Comment by Prototyped** [comment] 2024-03-10 11:36
I too needed to downgrade to the last stable release msi on this GitHub project (2.0.14) from 2.1.4 installed by the Microsoft Store automatically (Windows 10 Pro 22H2) to get my Debian distro on WSL1 working again. Seems like 2.1.x introduced a regression.

**Comment by dashqua** [comment] 2024-03-10 15:40
> I too needed to downgrade to the last stable release msi on this GitHub project (2.0.14) from 2.1.4 installed by the Microsoft Store automatically (Windows 10 Pro 22H2) to get my Debian distro on WSL1 working again. Seems like 2.1.x introduced a regression.

Can you give us the commands you used?

**Comment by MitchBradley** [comment] 2024-03-10 16:13
FWIW, the procedure I used to downgrade/test various versions was
* Go to https://github.com/microsoft/WSL/releases
* Choose a release
* From the Assets, download the .msi file like wsl.2.0.15.0.x64.msi
* Open that file to install WSL
* To test, run "wsl" from PowerShell.  I have only one disto (Debian Buster release 10 using WSL 1) configured

2.0.15 worked; others in the 2.1 series immediately failed with 0xd000020c.  There was no data loss as far as I can tell.  Debian has been behaving the same as before since the downgrade.

**Comment by dashqua** [comment] 2024-03-10 21:11
> FWIW, the procedure I used to downgrade/test various versions was
> 
>     * Go to https://github.com/microsoft/WSL/releases
> 
>     * Choose a release
> 
>     * From the Assets, download the .msi file like wsl.2.0.15.0.x64.msi
> 
>     * Open that file to install WSL
> 
>     * To test, run "wsl" from PowerShell.  I have only one disto (Debian Buster release 10 using WSL 1) configured
> 
> 
> 2.0.15 worked; others in the 2.1 series immediately failed with 0xd000020c. There was no data loss as far as I can tell. Debian has been behaving the same as before since the downgrade.

@MitchBradley Thanks for your detailed answer. I have followed EXACTLY what you suggested (took the 2.0.15 release) and I am happy to tell you that I recovered my WSL session. 

My problem seems resolved. I let this thred open in case the developpers want to say something. Also, people are welcome to give explanation about what's happening with WSL. Cheers

**Comment by willemsjon** [comment] 2024-03-10 23:15
Just wanted to say, I was having the same problem and this fixed it for me. Thanks a bunch! 

> FWIW, the procedure I used to downgrade/test various versions was
> 
> * Go to https://github.com/microsoft/WSL/releases
> * Choose a release
> * From the Assets, download the .msi file like wsl.2.0.15.0.x64.msi
> * Open that file to install WSL
> * To test, run "wsl" from PowerShell.  I have only one disto (Debian Buster release 10 using WSL 1) configured
> 
> 2.0.15 worked; others in the 2.1 series immediately failed with 0xd000020c. There was no data loss as far as I can tell. Debian has been behaving the same as before since the downgrade.

**Comment by Fahmiin-Abdullah** [comment] 2024-03-11 03:27
> FWIW, the procedure I used to downgrade/test various versions was
> 
> * Go to https://github.com/microsoft/WSL/releases
> * Choose a release
> * From the Assets, download the .msi file like wsl.2.0.15.0.x64.msi
> * Open that file to install WSL
> * To test, run "wsl" from PowerShell.  I have only one disto (Debian Buster release 10 using WSL 1) configured
> 
> 2.0.15 worked; others in the 2.1 series immediately failed with 0xd000020c. There was no data loss as far as I can tell. Debian has been behaving the same as before since the downgrade.

Lifesaver! This fixed it for me at the moment

**Comment by benhillis** [comment] 2024-03-11 16:05
I have a working theory but I would need somebody who's able to repro this to try a private version of WSL. Is anybody able to assist?

**Comment by MitchBradley** [comment] 2024-03-11 16:30
If you can give me an msi or some such I will test it, especially if you give me good instructions for what you want me to do.  I am a software developer so I won't need much handholding, but mostly I do embedded stuff so I don't live and breathe Windows arcana.

**Comment by MitchBradley** [comment] 2024-03-11 17:19
Email sent

**Comment by boulund** [comment] 2024-03-11 17:19
I'll also happily test tomorrow when I'm working from the home office
(where I run WSL). I'll send you an email as well!

I may have really messed my machine up though, as I aborted unregistering
my Ubuntu instance halfway through when I panicked about potentially losing
data.

Den mån 11 mars 2024 18:16Ben Hillis ***@***.***> skrev:

**Comment by benhillis** [comment] 2024-03-11 19:49
Thanks for your patience everyone, this was a tricky one but @OneBlue and I were finally able to get a repro locally. I have a fix for this and will roll out an updated WSL package ASAP.

Sorry for the disruption this caused.

**Comment by MitchBradley** [comment] 2024-03-11 20:03
Tricky ones are fun after the fact.  Good job.

**Comment by benhillis** [comment] 2024-03-12 02:42
Fixed with https://github.com/microsoft/WSL/releases/tag/2.1.5. Sorry again for the pain here - I will introduce a test to make sure something like this can't happen again.

**Comment by MitchBradley** [comment] 2024-03-12 04:02
Fix confirmed.  Thanks.

**Comment by crramirez** [comment] 2024-03-12 09:59
@electrofloat the code is not in this repo. WSL is not open source

**Comment by electrofloat** [comment] 2024-03-12 10:02
Ahh... microsoft... What was I thinking...

**Closed** 2024-03-12 18:56 UTC
Labels: bug, fixinbound

**Comment by crozone** [comment] 2024-03-13 04:01
2.1.5 fixed both my machines, thanks for the quick turnaround!

**Comment by Preciel** [comment] 2024-03-13 09:07
Glad this helped a lot of users... Though this version broke my WSL when I had no issues it seems...
![image](https://github.com/microsoft/WSL/assets/15726325/633621e0-0153-4405-be82-22b1fb73f901)

**Comment by mizoru** [comment] 2024-08-25 21:38
I have started getting this same error on 2.2.4.0 of WSL 1
```
wsl
Error: 0xd000020c
Error code: Wsl/Service/CreateInstance/0xd000020c
wsl --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.19045.4780
```
Downgrading to 2.1.5.0 or 2.0.15.0 didn't help
