### ISSUE TITLE
Accessing \\wsl.localhost results in logon failures being logged while \\wsl$ does not

### ISSUE THREAD

**Issue by kitu-sbruce** [microsoft/WSL#11198] opened 2024-02-23 00:42 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3155]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.133.1-microsoft-standard-WSL2 (root@1c602f52c2e4) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Oct 5 21:02:42 UTC 2023

### Distro Version

Ubuntu 22.04

### Repro Steps

1. Access `\\wsl.localhost\Ubuntu` from explorer. Loads fine
2. Event ID 4625 logged in Security event log
3. Access `\\wsl$\Ubuntu` from explorer. Loads fine
4. No 4625 events logged

### Expected Behavior

Either path should work without generating logon failures.

### Actual Behavior

Logon failures are logged for `\\wsl.localhost\Ubuntu`

**Comment by OneBlue** [comment] 2024-04-18 20:23
Thank you, closing since the issue is resolved.

**Closed by OneBlue** 2024-04-18 20:23 UTC
