### ISSUE TITLE
WSL ubuntu 18.04 cant get update

### ISSUE THREAD

**Issue by hugochavezzz** [microsoft/WSL#5195] opened 2020-05-10 09:49 UTC

**Comment by hugochavezzz** [comment] 2020-05-10 09:56
I use Windows 10 Pro 1803
Build n 17134.1069
Enabled developer mode
Enabled WSL mode
Installed Ubuntu 18.04
First time start failed with cannot specific file location....
Googled and copy all content from windowsapp/....ubuntu18.04  to created new folder C: ubuntu18.04
Then run ubuntu.exe installd succesfully
I want to install ansible, to do so i want to get updates
I tgives error like:
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Could not connect to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (2001:67c:1562::18). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (2001:67c:1562::15). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (91.189.88.142). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (91.189.88.152). - connect (111: Connection refused)

**Comment by hugochavezzz** [comment] 2020-05-10 09:58
I cant connect to archive.ubuntu.com with my browser also, so I use shadowsocksR. With shadowsocks i can connect to archive.ubuntu.com.
But WSL still cant get update with shadowsocks

**Comment by hugochavezzz** [comment] 2020-05-10 10:01
I cant connect to archive.ubuntu because government is blocking some websites

**Comment by dhikrahashim** [comment] 2020-05-11 07:08
same issue for me also.

**Comment by DimDroll** [comment] 2020-05-11 08:19
Same as here:
https://github.com/microsoft/WSL/issues/5198

Make sure nothing is blocking repos on your host machine.

**Comment by bpulliam** [comment] 2021-05-07 12:51
Marking as duplicate of #5198

**Closed by bpulliam** 2021-05-07 12:51 UTC
Labels: duplicate
