### ISSUE TITLE
No sound in wsl2 

### ISSUE THREAD

**Issue by elswerky** [microsoft/WSL#4205] opened 2019-06-20 21:57 UTC
i was following a tutorial to enable sound in wsl and was working 

https://token2shell.com/howto/x410/enabling-sound-in-wsl-ubuntu-let-it-sing/

but this tutorial no longer works on wsl2 

can you plz help me to make it work on wsl2 ??

**Comment by Gabrielcarvfer** [comment] 2019-06-20 22:16
Did you change the IP used in the tutorial? Try 0.0.0.0 instead of 127.0.0.1. The server will listen to any IPs instead of being restricted to the localhost. Should work just fine, but I wouldn't recommend using it in public networks.

**Comment by elswerky** [comment] 2019-06-21 09:16
> Edit: I've forgotten that you will need a script to get the Windows IP (running the pulseaudio server) and export it to the WSL environment so that the programs can find it. (e.g. powershell -Command "$ipv4 = Test-Connection -ComputerName (hostname) -Count 1 | Select -ExpandProperty IPV4Address; $ipv4.IPAddressToString")

i pasted this " $ipv4 = Test-Connection -ComputerName (hostname) -Count 1 | Select -ExpandProperty IPV4Address; $ipv4.IPAddressToString "           in PowerShell and it gave me this 192.168.1.4 
how to export it to wsl 
for example 
export PULSE_SERVER=tcp:192.168.1.4   or what 

can you explain this plz ?? 

also i was using this bat file to launch xfce4 desktop on arch wsl on x410 with pusleaudio enabled from a shortcut to this bat file on wsl1 
if you can tell me what to just change in this file to make pusle audio works 
in this screenshot i just changed DISPLAY from localhost to what in screenshot to make it take the new ip address in wsl2 
i want to do the same for pulse server to make it work on wsl2 

can you 
![1](https://user-images.githubusercontent.com/26687459/59912030-7afaed80-9415-11e9-816a-618c66ce76f6.PNG)

**Comment by Gabrielcarvfer** [comment] 2019-06-21 14:16
Change your bat file to include the following. It will create a local variable (MYIP) with your Windows IP. After that, you can call %MYIP% where you would have a server IP (e.g. export PULSE_SERVER=tcp:%MYIP%).

`@echo off
FOR /F "delims=\" %%A IN ('powershell -Command "$ipv4 = Test-Connection -ComputerName (hostname) -Count 1 | Select -ExpandProperty IPV4Address; $ipv4.IPAddressToString"') DO SET "MYIP=%%A"
::echo %MYIP%`

P.S.: This is a workaround and if your computer IP changes during your use (e.g. connecting to a different WiFi network), you will probably need to stop the services and then run this script again to update the IP and restart the services.

**Comment by bigworld12** [comment] 2019-09-04 01:53
i am also facing the same issue, i even tried using ALSA to host an audio server, but it looks like it's not supported ? 
all the old guides apparently don't work on wsl 2

**Comment by JackTheMico** [comment] 2019-11-19 02:28
I think I have figure out one or two solutions for this issue.

1.  Check out your wsl's ip with this command for ubuntu:
`ifconfig eth0 | grep 'inet '`
you will get some thing like "inet 172.24.201.27  netmask 255.255.240.0  broadcast 172.24.207.255",
and that ip after "inet" is your wsl' ip.
Add it to pulseaudio /etc/pulse/default.pa line 61 auth-ip-acl and run pulseaudio.exe again, it should work now.

2.  According to this: [archlinux-pulseaudio](https://wiki.archlinux.org/index.php/PulseAudio/Examples), you can add "auth-anonymous=1" to /etc/pulse/default.pa line 61. 
After you done that, restart pulseaudio.exe and wsl2 can use audio correctly. 

I tried both solutions out with cmus in wsl2, it works for me with ArchLinux.

**Comment by raekuul** [comment] 2020-02-13 15:47
@JackTheMico Is that a client-side change (inside WSL2) or a server-side one (inside Windows)?

**Comment by hemanta212** [comment] 2020-03-21 07:01
@raekuul All changes are in windows side.

**Comment by k0pernicus** [comment] 2020-05-05 15:03
Hi all - I am facing the same issue described here, and I tried the solution from @JackTheMico but it did not worked as expected...

So, to explain what I did:  
1. I setted up pulseaudio on Windows10 to match with the IP of my WSL2 image instance (let's call it $MY_IP) (+ other config in daemon.conf), and run it on Windows10.
2. I installed pulseaudio on my Ubuntu 20.04 in WSL2, and exported the PULSE_SERVER to tcp:$MY_IP.

Do I need to run the daemon on Ubuntu, or nothing more than what I already did?

For now, using X410 as X11 server, I expected to have sound when launching Firefox (or whatever), but nothing more than the video :/

I tried cmus as well, but I have the following error when playing a sound:
```
Error: opening audio device: No such device
```

**Comment by k0pernicus** [comment] 2020-05-05 15:31
Ok, solved!

So, I exported this environment variable in my Ubuntu:
```
export PULSE_SERVER=tcp:$(grep nameserver /etc/resolv.conf | awk '{print $2}')
```
and the result of the command `ifconfig eth0 | grep 'inet '` in /etc/pulse/default.pa (line 61).

I have now sound and video launching Firefox from Ubuntu, on Windows now 👍

**Comment by Adriankhl** [comment] 2020-05-16 16:21
I recommend running a script like [this](https://github.com/Adriankhl/wsl2-tips-and-scripts/blob/master/bin/xpa) to configure and run PulseAudio .

```
wsl_ip=$(ip a | grep "inet " | grep "eth0" | awk '{print $2}')                                                                        cygwin.exe -c "pactl load-module module-native-protocol-tcp auth-ip-acl=$wsl_ip"
```

I install PulseAudio with cygwin but I believe something similar should work with other installation methods.

**Comment by nkrapivin** [comment] 2020-05-23 14:21
I was able to install PulseAudio in WSL2 too, but the sound is very choppy.

Any way to fix this?

**Comment by devcircus** [comment] 2020-05-24 04:18
There are many ways to be sure the wsl ip is set correctly each time it changes, but what I ended up doing for now, is creating shell script(setup-pulseaudio.sh) in /usr/profile.d that runs a script I made in /usr/bin named ```setup-pulseaudio``` like below:
```sh
#!/bin/bash

PULSE_FILE="/mnt/c/location/to/pulseaudio/etc/pulse/default.pa"
PULSE_IP=$(ip a | grep "inet " | grep "eth0" | awk '{print $2}')
REPLACE="load-module module-native-protocol-tcp auth-ip-acl=$PULSE_IP auth-anonymous=1"

if test -f "$PULSE_FILE"; then
    sed -i "61s|.*|$REPLACE|" $PULSE_FILE
fi
```
The script will run each time your shell is started and it simply replaces line 61 of ```default.pa``` with the line assigned to ```REPLACE```, which contains the current ```PULSE_ID```.

If you wanted, you could also check to see if pulseaudio.exe is running, kill it, delete any existing runtime pid file at ```C:\Users\<username>\.pulse```, and start pulseaudio.exe. In addition, you could make sure your x-server is running. Personally, my x-server is always running and I don't mind starting pulseaudio manually since I don't use it very often.

**Comment by juancopi81** [comment] 2020-06-03 03:28
> Ok, solved!
> 
> So, I exported this environment variable in my Ubuntu:
> 
> ```
> export PULSE_SERVER=tcp:$(grep nameserver /etc/resolv.conf | awk '{print $2}')
> ```
> 
> and the result of the command `ifconfig eth0 | grep 'inet '` in /etc/pulse/default.pa (line 61).
> 
> I have now sound and video launching Firefox from Ubuntu, on Windows now 👍

Hi k0pernicus,

I am having problems with this. I already tried:

```
export PULSE_SERVER=tcp:$(grep nameserver /etc/resolv.conf | awk '{print $2}')
```

and write the result of `ifconfig eth0 | grep 'inet '` in /etc/pulse/default.pa (line 61).  But when I try: '.\pulseaudio.exe' I get: .pulseaudio.exe: command not found

I do not know what I am missing. Any help would really appreciated .
![2020-06-02_2226](https://user-images.githubusercontent.com/4313860/83592612-5877bc80-a520-11ea-8236-02c2b19f3736.png)

**Comment by Adriankhl** [comment] 2020-06-03 05:19
@juancopi81 do `./pulseaudio.exe` instead

**Comment by juancopi81** [comment] 2020-06-03 20:04
Thanks Adriankhl for your answer...  I was not understanding so actually I was doing the first steps inside Ubuntu (WSL 2) and not the powershell of windows. Now it is working, but sound it is really bad, any way to improve that?

**Comment by JEmlay** [comment] 2020-06-19 22:46
Many thanks to JackTheMico.  Could not get audio working with WSL2.  Was thinking my Windows host IP had to be in that config file.  Working good now!

**Closed** 2020-08-26 07:24 UTC
Labels: question

**Comment by eamondo2** [comment] 2020-10-09 17:33
So I had attempted to get some of the suggestions from this thread, as well as from others I'd found while doing research and wasn't able to get them working reliably. 

[Git Page](https://git.bortle-host.io/eamondo2/wsl2-pulse-x11-setup)

This is an attempt to collate what ended up working, hopefully it will be of some help.

**Comment by timriker** [comment] 2020-10-21 16:05
I’ve set in etc/pulse/default.pa this:

`load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;172.16.0.0/12`

This will authorize all local connections for WSL1 and the RFC-1918 block 172.16.0.0/12 which is the default space for WSL2.

I would not recommend `auth-anonymous=1` as this would allow any remote machine to connect. I use this inside my .bashrc:

```
if grep -q "microsoft" /proc/version &>/dev/null; then
  # WSL2
  export DISPLAY="$(ip route|awk '/^default/{print $3}'):0.0"
  export PULSE_SERVER="${PULSE_SERVER:-tcp:$(ip route|awk '/^default/{print $3}')}"
fi
```

**Comment by JEmlay** [comment] 2020-10-21 16:46
> 
> 
> I’ve set in etc/pulse/default.pa this:
> 
> `load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;172.16.0.0/12`
> 
> This will authorize all local connections for WSL1 and the RFC-1918 block 172.16.0.0/12 which is the default space for WSL2.
> 
> I would not recommend `auth-anonymous=1` as this would allow any remote machine to connect. I use this inside my .bashrc:
> 
> ```
> if grep -q "microsoft" /proc/version &>/dev/null; then
>   # WSL2
>   export DISPLAY="$(ip route|awk '/^default/{print $3}'):0.0"
>   export PULSE_SERVER="${PULSE_SERVER:-tcp:$(ip route|awk '/^default/{print $3}')}"
> fi
> ```

Excellent suggestions, thank you!  Although I couldn't get anything to work right by editing bashrc so I just updated my bat file instead:

`ubuntu2004.exe run "if [ -z \"$(pidof xfce4-session)\" ]; then export DISPLAY=$(ip route|awk '/^default/{print $3}'):0.0; export PULSE_SERVER=${PULSE_SERVER:-tcp:$(ip route|awk '/^default/{print $3}')}; startxfce4; pkill '(gpg|ssh)-agent'; taskkill.exe /IM pulseaudio.exe /F; taskkill.exe /IM vcxsrv.exe; fi;"`

Woot!  No more having to change the IPs.

**Comment by timriker** [comment] 2020-10-22 06:34
See my notes in #5816 which works for WSL1 as well.

**Comment by dcharlespyle** [comment] 2021-02-22 01:52
If none of the above options works, as has happened to me since changing to WSL 2, you can use the following in your ~/.bashrc file to correct for deficiencies:

```
# Get the IP Address of the Windows 10 Host and use it in Environment.
HOST_IP=$(host `hostname` | grep -oP '(\s)\d+(\.\d+){3}' | tail -1 | awk '{ print $NF }' | tr -d '\r')
export DISPLAY=$HOST_IP:0.0
export PULSE_SERVER=tcp:$HOST_IP
```

It grabs the IP address of the Windows host, no matter what it is, and exports it to the WSL 2 environment.

**Comment by marksteward** [comment] 2021-05-07 20:33
Audio will be built in, https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/

**Comment by dcharlespyle** [comment] 2021-05-14 18:49
Now using the built-in audio of WSLg.  Works very well!  No more need to redirect PULSE_SERVER to specific IP address.  Just works out of the box in WSL2 in Windows 10 Preview builds higher than 21364.  What doesn't work is theming for QT and GTK2 apps. Cannot launch elevated GUI programs anymore.  These will require adjusting command lines and some experimentation.  But sound works great!  Have full GPU acceleration, too!  Transparency in Gnome-Terminal functions as intended.

![image](https://user-images.githubusercontent.com/5110398/118315443-c3f93680-b4b2-11eb-87c0-611cd87e5d00.png)

And did I say that sound works really well for a preview?

**Comment by FirefoxSystem** [comment] 2021-09-06 21:03
Hello guys,

after days of unsuccessful attempts I solved the no sound problem by inserting in the file **/etc/pulse/client.conf** the following line:

`default-server = 192.168.1.2`

_obviously the IPv4 LAN address of your computer not that of the virtual card 'vEthernet (WLS)'_

Happy listening :)
Hello

**Comment by singhdilveer1** [comment] 2022-12-12 09:19
I came here for a solution but installing pulseaudio on the ubuntu instance solved the issue.
