### ISSUE TITLE
Mounted filesystem issue on Debian WSL when running CMake

### ISSUE THREAD

**Issue by sfreed141** [microsoft/WSL#4257] opened 2019-07-01 22:18 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.175]

* WSL kernel info (uname -a): Linux SAFREED-DESKTOP 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 GNU/Linux

* What you're doing and what's happening:  I have a simple CMake project on the mounted fileystem (under /mnt) which fails to configure when run the first time with this error message:
```
Cannot copy output executable
  '/mnt/c/users/safreed/source/repos/wslbug/build/CMakeFiles/CMakeTmp/cmTC_06b98'
to destination specified by COPY_FILE:
  '/mnt/c/users/safreed/source/repos/wslbug/build/CMakeFiles/3.7.2/CMakeDetermineCompilerABI_CXX.bin'
```

* What's wrong / what should be happening instead: The file copy should carry out successfully without errors.

The strange part is the files that 'fail' to copy are actually being copied, so the next time CMake is run it completes without errors. Also, if I copy the project to the root filesystem instead (under $HOME) there are no issues. I verified this only repros when using Debian under WSL (Ubuntu is fine and Debian running under HyperV is fine).

Repro steps:
1. Create directory somewhere under /mnt on Debian WSL.
2. Create project files and run cmake
```
cat > CMakeLists.txt << EOM
cmake_minimum_required(VERSION 3.7)
add_executable(main "main.cpp")
EOM
cat > main.cpp << EOM
#include <iostream>
int main() {
    std::cout << "hello world" << std::endl;
    return 0;
}
EOM
cmake .
```

Expected output:
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sam/wslbug
```
Actual output:
```
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineSystem.cmake:180 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt


-- The C compiler identification is GNU 6.3.0
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCCompiler.cmake:175 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt


-- The CXX compiler identification is GNU 6.3.0
CMake Error at /usr/share/cmake-3.7/Modules/CMakeDetermineCXXCompiler.cmake:170 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt


-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
CMake Error at /usr/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:71 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt


-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
CMake Error at /usr/share/cmake-3.7/Modules/CMakeTestCXXCompiler.cmake:64 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "/mnt/c/users/safreed/source/repos/wslbug/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/c/users/safreed/source/repos/wslbug/build/CMakeFiles/CMakeError.log".
```

**Comment by therealkenc** [comment] 2019-07-02 00:17
+1 thanks for CLI repro steps.

If you link a gist to the `strace(1)` log we can probably see the fail. `strace -f -o cmake.strace cmake .` (on the first run, natch).

I wasn't actually able to reproduce the problem here (no errors) on my `/mnt/c/users/ken/source/repos`, but the only WSL1 I have handy is 16.04 with `cmake 5.4.0`. That difference _very probably_ isn't going to be game changing tho. Just giving full disclosure caveat on the "can't repro here".

> The strange part is the files that 'fail' to copy are actually being copied, so the next time CMake is run it completes without errors.

The "Actual output" part of your OP doesn't have a "Cannot copy output executable" cited earlier. Those kinds of copy fails are often acute #1529, but the failure pattern doesn't match very well here. There is no indication the _reason_ the copy failed was `EACCES`. The fact that `/home` works suggest that isn't the problem. But it is the canonical reason for a failed copy on WSL1.

One thing to try first if you've got a win32 (Windows) `cmake`, `gcc`, etc installed is to launder your `$PATH` and see if that helps.
```
$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ # [create project files]
$ cmake .
```

But that's a WAG.

> (under $HOME) there are no issues

That's how I'd roll.

**Comment by sfreed141** [comment] 2019-07-02 17:04
Thanks for the quick reply!

I made the [gist](https://gist.github.com/sfreed141/64efe268261591f8ea1014c5138e25e1) with strace and CMake logs if you'd like to take a look. Also, the CMakeError.log contains the "Cannot copy output executable" message I mentioned, apologies for not making that clear.

I don't see any `EACCES`, but I do see an `EPERM` on the file that "failed" to copy:
```
10702 chmod("/mnt/c/users/safreed/source/repos/wslbug/build/CMakeFiles/3.7.2/CMakeDetermineCompilerABI_C.bin", 0100777) = -1 EPERM (Operation not permitted)
```
Perhaps this is causing CMake to think the file copy failed? It's strange though because I don't see this error on my Ubuntu instance of WSL. I only see the issue when running Debian (I have Debian 9.9 installed).

Laundering the path doesn't seem to work for me unfortunately.

In general I'd agree the easiest solution is to just move the project under the root filesystem. However, for Visual Studio integration with WSL we need to have access from the Windows side so the project files have to be on the mounted filesystem.

**Comment by therealkenc** [comment] 2019-07-02 18:15
> I don't see any EACCES, but I do see an EPERM on the file that "failed" to copy:

Close enough. That's going to be variation #1529. Very good to have this on the books, so thank-you for the report. Make sure Visual Studio (_and anything else_ touching that whole directory tree on the Windows side) is closed when you run the `cmake` on the WSL side. The whole tree. Even `cmd.exe`. Hopefully that helps. 

If not then there _might_ have been a change in `cmake` after all. If you are feeling motivated, try Ubuntu 16.04 from the Store which ships with `cmake 5.4.0`. That won't 'fix' your problem in any long term sense, natch, but at least you'll know the cause. That combination did work for me. I didn't open MSVS or anything else on the Windows side; I just pasted your (most excellent) repro in WSL Ubuntu 16.04.

> Laundering the path doesn't seem to work for me unfortunately.

Yeah, it won't under the circumstance. That was a Hail Mary pass on the assumption this _wasn't_ #1529.

> Visual Studio integration with WSL we need to have access from the Windows side

Try [Code](https://code.visualstudio.com/) with the [Remote](https://code.visualstudio.com/docs/remote/remote-overview) plugin. Visual Studio is soooo 2010. ;)

(Slightly) more seriously, you should be able to use [MSVS for Linux](https://devblogs.microsoft.com/cppblog/linux-development-with-c-in-visual-studio/) on `/home`.

If neither of those suit your workflow, and closing everything in Windows doesn't help, there is no simple work-around. In this case the `cmake` crowd joins the `npm` crowd, for the same underlying reason.

This is fundamentally (and most unfortunately) tag dupe, but I'll hold it open for a bit to see if there is any more community input on the `cmake` specific use case.

**Comment by therealkenc** [comment] 2019-07-02 18:45
[mass edit: do-over post to check something before making possibly false assumptions]

That `chmod` line suggests this might be because metadata isn't enabled on `/mnt/c`. I didn't have metadata enabled on my run either, so I didn't think of it. But then it working _could_ be explained by my `cmake` version difference.

To enable metadata on your /mnt/c add this to `/etc/wsl.conf`.
```
[automount]
enabled = true
options = "metadata"
```

**Comment by sfreed141** [comment] 2019-07-02 22:38
Enabling metadata seems to have fixed it, thanks!

**Closed** 2019-07-02 22:41 UTC

**Comment by nmoreaud** [comment] 2021-05-28 15:44
This happened to me when I moved WSL from disk C to disk D.
