### ISSUE TITLE
postgres config file not created on install

### ISSUE THREAD

**Issue by Abz2604** [Microsoft/WSL#864] opened 2016-08-11 12:27 UTC
`jarvis@JARVIS:/mnt/c$ postgres -i --coordinator -h localhost -p 5432 -D /etc/postgres/9.3/`

after digging through the internet to solve the  "connection refused" "no permission" and "no file or directory" error with psql i came down to this:

`postgres cannot access the server configuration file "/etc/postgres/9.3/postgresql.conf": No such file or directory
`
The normal command to check psql and its output was

```
jarvis@JARVIS:/mnt/c$ psql
psql: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

```

spent 2 days on trying to get postgres to work on my windows bash 

any fix?

**Comment by SRGOM** [comment] 2016-08-11 12:44
You actually have PostgresQL working? Some don't! https://github.com/Microsoft/BashOnWindows/issues/61  (I haven't tried)

**Comment by rodrymbo** [comment] 2016-08-27 20:30
Is there a file at `"/etc/postgres/9.3/postgresql.conf"? Does it have appropriate permissions? Are there any symlinks in the path?

In the bash.exe in which you are about to run pgsql, if you do a `ps -A` do you see postgres listed?

Those are a couple of things you could add to your report for completeness...

**Comment by shoffmeister** [comment] 2018-06-15 07:28
This seems to be an artefact of the init system not present as expected under WSL.

On current Windows and Ubuntu 18.04, I was able to
* `sudo apt install postgresql`
* `sudo -u postgres service postgresql start`

Following that `sudo -u postgres psql` seemed to do the right thing:

```
psql (10.4 (Ubuntu 10.4-0ubuntu0.18.04))
Type "help" for help.

postgres-# \list
                              List of databases
   Name    |  Owner   | Encoding | Collate |  Ctype  |   Access privileges
-----------+----------+----------+---------+---------+-----------------------
 postgres  | postgres | UTF8     | C.UTF-8 | C.UTF-8 |
 template0 | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
           |          |          |         |         | postgres=CTc/postgres
 template1 | postgres | UTF8     | C.UTF-8 | C.UTF-8 | =c/postgres          +
           |          |          |         |         | postgres=CTc/postgres
(3 rows)
```

**Comment by therealkenc** [comment] 2018-06-15 10:31
Appreciate the follow-up. This probably falls under the "a lot has changed in WSL since 2016" category. In the OP we don't have any information regarding the `apt install postgresql` process, only that `/etc/postgres/9.3/postgresql.conf` didn't exist after the fact (even that much wasn't confirmed or denied). 

If it works now (to a first order, notwithstanding initd/systemd unpleasantness) that is good to know. Any other outstanding issues with postgresql deserve to be filed under a different cover, so closing.

**Closed by therealkenc** 2018-06-15 10:31 UTC
