### ISSUE TITLE
dbus-launch 100% CPU usage

### ISSUE THREAD

**Issue by cj** [Microsoft/WSL#3039] opened 2018-03-19 17:15 UTC
Ubuntu Version: **16.04.4 LTS**
Windows Version: **10.0.17123.1**

Steps to recreate:

Install VcXsrv version 1.19.6.0, open bash.exe run `sudo apt-get install gnome-terminal`, this will also install dbus-x11.  Make sure VcXsrv is running and then run `gnome-terminal` in your bash.exe.  You'll notice a new process running in the windows task manager `dbus-launch` it sits at over 20% CPU usage, which does not seem right.

![](https://image.prntscr.com/image/-b8QwA7mQ8SMq1h_gq673Q.png)

If you then run `top` inside your bash.exe, you'll see `dbus-launch` running at 100% CPU usage!

![](https://image.prntscr.com/image/iK8O2u_RRsmWG77-wlO-lA.png)

If you need me to run anything to get you more information, please let me know.

**Comment by Biswa96** [comment] 2018-03-19 17:51
You may follow this issue #637 where @Guerra24 mentioned this [Reddit link](https://www.reddit.com/r/Windows10/comments/4rsmzp/bash_on_windows_getting_dbus_and_x_server_working/) for dbus issue. Try xfce4.

**Comment by cj** [comment] 2018-03-19 17:57
@Biswa96 thank you for the response.  This issue is unrelated, there's no issue running `gnome-terminal` or `xfce4`, the issue is the CPU usage.  You can use any xserver like `Xlaunch` and get the same result, it's not limited to VcXsrv.  The issue seems to be with `dbus-x11`, if you say install `google-chrome-stable` and run that via bash.exe, there is no high CPU usage as it doesn't use `dbus-x11`.

**Comment by DarthSpock** [comment] 2018-03-19 18:16
`top` doesn't show proper cpu usage (or any other usage). You can literally put Task Manager next to your terminal to compare outputs and they won't be close.

**Comment by therealkenc** [comment] 2018-03-19 18:23
> mentioned this Reddit link for dbus issue

No, no. There aren't any known issues with `dbus` over `AF_UNIX` for quite some time. [That's doesn't mean it is impossible a problem exists, but if one does, someone needs to post a repro demonstrating as much.]

xfce4 is completely unrelated. That's a window manager. VcXsrv is unrelated. That's an X server.

In any case, if you are going to be running dbus stuff in WSL you need a session.
```
$ export DISPLAY=localhost:0
$ export NO_AT_BRIDGE=1
$ exec dbus-run-session -- bash
$ sudo service dbus start
$ gnome-terminal
```
Works fine. 

I suspect this is why `xrdp` is gaining (most unfortunate) popularity. In that case the X server really is on the WSL side, and there is a well formed session (because you get a login screen). 

> top doesn't show proper cpu usage (or any other usage).

Please stop.

**Comment by Biswa96** [comment] 2018-03-19 19:56
Here is my configuration with 0% CPU usage of dbus-launch. I'm using xfce4 in Ubuntu 18.04 in Windows 10.0.17618.1000.

![xfce4_terminal](https://user-images.githubusercontent.com/31443074/37618837-7ba656c6-2bdd-11e8-92bb-625e20bd051d.PNG)

**Comment by therealkenc** [comment] 2018-03-19 21:50
That isn't a configuration. It is a screenshot of top. This discussion can be continued in #637.

**Comment by cj** [comment] 2018-03-19 21:56
@therealkenc I'm the author of this thread, but you've been replying to @Biswa96 and hist comments the entire time.  As I said to @Biswa96 this has nothing to do with #637 and the dbus issue he mentioned.

**Comment by therealkenc** [comment] 2018-03-19 22:32
Yes understood. If you still see the problem with a well formed dbus session per my earlier post (with no window manager, xfce4 or otherwise, naturally) then please re-file the issue with a CLI repro following [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md). I am not able to reproduce the high CPU load here. _If you have a repro_ that can be cut and paste into a headless Real Linux (usually a VM sans X server) and into WSL, with an `strace` log showing the diverge, there will be party poppers all around. Conversely, for general discussion the landing zone for gnome-terminal or dbus session troubleshooting is #637. 

[Heads up when I did the test today I had better luck with Xming; VcXsrv seemed to be having grief with gnome-terminal today. That is _utterly unrelated_ to `dbus-launch` of course. You might or might not see it. I just wanted to give full disclosure on the test I ran earlier. Bonne chance as always.]

**Comment by cj** [comment] 2018-03-19 23:01
@therealkenc I really appreciate the response and your time -- I wasn't using a windows manager like `xfce4`.  The CPU results in my screenshots were from just running `gnome-terminal` directly in `bash.exe` with `VcXsrv` as the Xserver.  Once I get the time, I'll try and re-create the issue with a fresh install and make a bash script which will automate the commands that can be run on an Ubuntu VM and WSL.  Hope you have a great rest of your week!

**Comment by jowadmax** [comment] 2018-03-20 00:55
I've started running into this issue today after updating to Windows 10.0.17123.1.

I use WSL mostly in CLI mode, but every now and then I'd use gui meld.
On my Windows side, I have VcXsrv installed and have been using it for gui stuff for almost a year now.

I noticed the issue today after realizing that my laptop's fan has been running at full speed all day.
Checking Task Manager showed that dbus-launch is using 25% of my CPU (I have a quad-core processor on the laptop). I tried right clicking on the process and selecting "End task" with no luck. Task manager doesn't show me any error; it just doesn't stop the dbus process. I also tried "End process tree" with no luck.
I then tried setting the process priority to low, but that showed a "Access is denied" error.

Now I switched to WSL side. 'ps aux' shows me that the process is taking 58% of the 'CPU'.
I tried `kill [PID]`, `kill -9 [PID]`, `kill -STOP [PID]` with no luck. I also tried closing all my WSL sessions and waiting for around 30 minutes, but the process was still running.

Just wanted to report that I've been seeing the issue too just in case it's a regression with the latest Insiders build. I realize it's going to be difficult to diagnose this issue since it's not a failure that we can catch with strace.

Thanks

**Comment by cj** [comment] 2018-03-20 01:24
@jowadmax that's the exact issue I'm having, and come to think of it, I also only started noticing it with the new preview build **10.0.17123.1**.

**Comment by therealkenc** [comment] 2018-03-20 01:31
>  after updating to Windows 10.0.17123.1

It could well be that something regressed in 17123 (and I'm beginning to suspect something did). We've got #3036 floating out there too. But again, do you see the problem _if you have a well-formed dbus session started_ per [above](https://github.com/Microsoft/WSL/issues/3039#issuecomment-374315849)?

@cj @jowadmax If you can catch the `dbus-launch --autolaunch` spinning in an `strace` that might shed a clue. Or if it's a regression they _might_ already be on it; or it _might_ already be fixed. I am on 17623.

**Comment by benhillis** [comment] 2018-03-20 02:40
Looks like some misbehaving NT MM code. We have a thread open with the owners to investigate. We will make sure this gets fixed.

**Comment by heldchen** [comment] 2018-03-20 19:44
anyone tried this on 17127?

**Comment by benhillis** [comment] 2018-03-20 19:45
@heldchen - This will definitely still be broken in 17127. The fix was just submitted today.

**Comment by heldchen** [comment] 2018-03-20 20:21
thanks, sitting this build out then

**Comment by Brian-Perkins** [comment] 2018-03-23 18:48
As Insider Builds continue to be released, it should be noted that the first build containing a fix for this internally is 17131, so until an Insider Build at or greater than that is released externally, this issue will continue to be present.

**Comment by mqudsi** [comment] 2018-03-23 22:19
Make sure you guys turn “pause updates” on until then, as the algorithm that decides how long until a build autoinstalls is on overdrive these days.

**Comment by sunilmut** [comment] 2018-03-27 21:48
Should be fixed in [17133](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17133-fast)

**Comment by Uldiniad** [comment] 2018-03-29 04:04
what about skip ahead branches?

**Comment by Brian-Perkins** [comment] 2018-03-29 16:32
17627 is OK. There are some internal builds that do exhibit this problem, so we will keep an eye on which build gets flighted next and will be sure to add a warning message if necessary.

**Comment by Brian-Perkins** [comment] 2018-03-29 17:41
17634 is also good, because it contains the fix for the original problem, meaning we should not see this issue reappear.

**Closed** 2018-04-03 16:33 UTC
Labels: bug, fixedinsidertransient
