### ISSUE TITLE
WSL2 fails to start with HCS_E_CONNECTION_TIMEOUT after KB5043145 is installed

### ISSUE THREAD

**Issue by andymeadows** [microsoft/WSL#12087] opened 2024-09-27 18:39 UTC
### Windows Version

10.0.22631.4169

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-microsoft-standard-WSL2

### Distro Version

 22.04

### Other Software

WSL fails to start, so any and all applications that need WSL -- docker, remote containers, etc. -- all fail.

### Repro Steps

With the above versions installed: 

* Install KB5043145
* Reboot Windows
* Attempt to launch WSL terminal by launching Ubuntu

### Expected Behavior

Expecting WSL2 container to launch and present a shell prompt.

### Actual Behavior

The terminal window will hang and will eventually present an HCS_E_CONNECTION_TIMEOUT error.  Error code: wsl/service/createinstance/createvm/hcs_e_connection_timeout

### Diagnostic Logs

I do not have access to the logs as it was critical to revert the patch to get work completed.

**Comment by branpurn** [comment] 2024-09-27 19:45
Same issue. The KB is breaking WSL, which breaks other critical applications that rely on WSL, like Docker. (https://github.com/docker/for-win/issues/14336)

**Comment by CristianCavanzo** [comment] 2024-09-27 20:14
Same issue here 🫨🫨

**Comment by OneBlue** [comment] 2024-09-27 20:30
Thank you @andymeadows. Unfortunately we need /logs to be able to root cause the issue. 

If either you or someone else could share logs, that would be very helpful to help us resolve this issue

**Comment by manuelhc621** [comment] 2024-09-27 21:42
[WslLogs-2024-09-27_14-12-33.zip](https://github.com/user-attachments/files/17170663/WslLogs-2024-09-27_14-12-33.zip)

**Comment by manuelhc621** [comment] 2024-09-27 21:43
@OneBlue  just added error logs

**Comment by manuelhc621** [comment] 2024-09-27 22:21
I have upgraded to WSL 2.3.24, but the issue is still there.

In both ETL files, the same error appear when the VM is being initialized
```
onecore\vm\worker\vmb\vmbcomservices.cpp(1604)\vmwp.exe!00007FF7F36B4387: (caller: 00007FFB630AD601) ReturnHr(1) tid(194) 80070490 Element not found.
    Msg:[onecore\vm\worker\vmb\vmbcomservices.cpp(1600)\vmwp.exe!00007FF7F36B42F1: (caller: 00007FFB630AD601) Exception(1) tid(194) 80070490 Element not found.
    Msg:[Failed to find handle VmbusVdevHandle for device with instance ID: D41A1872-3740-41CE-A1EE-4522AB82F991 of type: D41A1872-3740-41CE-A1EE-4522AB82F991 in handle broker manager] CallContext:[\VmInitialize\VmbInitialize\VdevOperation] 
] CallContext:[\VmInitialize\VmbInitialize\VdevOperation] 

```

![image](https://github.com/user-attachments/assets/f1060412-3354-4e8f-b997-7f092b854588)


Here are the logs with the newest WSL version, just in case.

[WslLogs-2024-09-27_16-10-01.zip](https://github.com/user-attachments/files/17170992/WslLogs-2024-09-27_16-10-01.zip)

**Comment by OneBlue** [comment] 2024-09-27 22:24
Thank you @manuelhc621.

Looking at the logs, it looks like something gets stuck on the VM boot path, but it's unclear what exactly at this point. 

To help us figure that out, could you: 

- run wsl.exe and wait about 10 seconds (wsl.exe should be 'stuck' for about 30 seconds before timing out)
- Capture dumps of vmwp.exe (might also appear as vmwpWSL.exe) and vmcompute.exe
- Share the dump with us

**Comment by manuelhc621** [comment] 2024-09-27 22:51
@OneBlue please find below links to both dums, both are quite large so I uploaded it to Google drive.

[vmwp](https://drive.google.com/file/d/1o5BLp1k3yyCuURp4_8iPWSfhvS8yQ1-B/view?usp=drive_link)
[vmcompute](https://drive.google.com/file/d/1GAN3hQWOR7sHSY3OuH6C5hR7wEqFOiGO/view?usp=drive_link)

The one for vmwp dissapears after the error is shown, so I hope it contains the correct data.

**Comment by OneBlue** [comment] 2024-09-27 22:52
Also @manuelhc621, could you also write:
```
[wsl2]
earlyBootLogging=false
``` 

In `%USERPROFILE%/.wslconfig` 

And share /logs of a repro again ? This should give us more details

**Comment by OneBlue** [comment] 2024-09-27 22:56
Also, what's your hardware configuration ? (CPU, GPU, Memory, etc)

**Comment by OneBlue** [comment] 2024-09-27 23:03
Another thing that would be super useful would be a kernel dump. To capture one, can you please: 

- Reproduce the issue (same as ealier)
- While WSL is booting, open task manager, select "System", right click -> "Create live kernel memory dump file" -> "Change memory dump settings" -> select "Capture Hypervisor pages", "include nonessential pages", "Capture user pages"
- Then go back to "System" -> right click,  "Create live kernel memory dump file" -> "full live kernel memory dump" 
- Share that file with us

**Comment by manuelhc621** [comment] 2024-09-28 00:47
Sorry @OneBlue I reverted the update before reading your messages and WSL is back and I can not apply it again, at least I do not know how.

Here is my system info, hope it helps.

![image](https://github.com/user-attachments/assets/8f3b97a5-3e34-4d09-8a35-ba93d0607dc3)


If I ran into the issue again will update this ticket

**Comment by identityope** [comment] 2024-09-28 06:55
just got the same issue, any solution?

**Comment by MartinSGill** [comment] 2024-09-28 12:13
Seems uninstalling KB5043145 is a workaround for now. At least it worked for me.

**Comment by identityope** [comment] 2024-09-28 14:43
> Seems uninstalling KB5043145 is a workaround for now. At least it worked for me.

Yeah I also confirm that uninstalling this update fixed the issue

**Comment by glide007** [comment] 2024-09-30 04:18
> Seems uninstalling KB5043145 is a workaround for now. At least it worked for me.

yes, it worked for me too!

**Comment by luciandf** [comment] 2024-09-30 10:04
confirm that uninstalling worked for me too!

**Comment by armando-herastang** [comment] 2024-09-30 17:22
Same issue here. Uninstalling the update it solved it. Hopefully this gets resolved.

I don´t know if this is relevant. I have an AMD Ryzen CPU, a college of mine has an Intel CPU an wasn't affected by the update.

**Comment by luciandf** [comment] 2024-09-30 18:14
> Same issue here. Uninstalling the update solved it. Hopefully this gets resolved.
> 
> I don´t know if this is relevant. I have an AMD Ryzen CPU, a college of mine has an Intel CPU an wasn't affected by the update.

i also have a laptop with an AMD CPU. I have read on reddit that mostly the amd cpus were affected.

**Comment by MartinSGill** [comment] 2024-10-01 09:45
Just to confirm here as well, the PC with the problem was also running an AMD CPU. I have another laptop with an intel chip and the KB installed and it's not exhibiting this issue.

**Comment by OneBlue** [comment] 2024-10-01 21:25
Thank you @manuelhc621. Unfortunately I don't have access to a live repro of this issue at the moment so I'd still need a kernel dump to understand what's stuck here.

If anyone can reproduces this issue, please: 

- Reproduce the issue by calling into wsl.exe and waiting about 5 seconds
- While WSL is booting, open task manager, select "System", right click -> "Create live kernel memory dump file" -> "Change - - 
-  memory dump settings" -> select "Capture Hypervisor pages", "include nonessential pages", "Capture user pages"
- Then go back to "System" -> right click, "Create live kernel memory dump file" -> "full live kernel memory dump"
- Share that file with us (either via Google Drive, OneDrive, or send to secure@microsoft.com

For this to work, the dump must be captured while WSL is in that "hung" state (once the error is displayed, you need to start wsl.exe again)

**Comment by bssrdf** [comment] 2024-10-02 12:30
Looks like the issue is fixed. Now WSL2 is running with  KB5043145 installed.
![Screenshot 2024-10-02 082905](https://github.com/user-attachments/assets/c6ef8778-99bb-42e3-8fe6-55e727cad1b0)

**Comment by gaborauth** [comment] 2024-10-02 13:07
> Looks like the issue is fixed. Now WSL2 is running with KB5043145 installed.

Is it a new WSL update or the KB5043145 altered?

**Comment by armando-herastang** [comment] 2024-10-02 13:19
> > Looks like the issue is fixed. Now WSL2 is running with KB5043145 installed.
> 
> Is it a new WSL update or the KB5043145 altered?

I don't see any new WSL release. The update is asking me to download, since I uninstalled. I paused the updates, but with this I am worried it doesn't work. I am going to wait until the end of the week to try.

**Comment by bssrdf** [comment] 2024-10-02 13:22
> > Looks like the issue is fixed. Now WSL2 is running with KB5043145 installed.
> 
> Is it a new WSL update or the KB5043145 altered?

I didn't update wsl2. KB5043145 got reinstalled (I previously uninstalled it) inadvertently when I restarted the machine. But this time WSL runs.

**Comment by daryllmoya-sixmoae** [comment] 2024-10-02 14:15
Is there such documentation we can reference if the new KB5043145 fixes the main issue of WSL?

**Comment by daryllmoya** [comment] 2024-10-02 14:18
Can someone send any documentation for reference that this issue has been addressed properly?

**Comment by armando-herastang** [comment] 2024-10-03 00:08
> > > Looks like the issue is fixed. Now WSL2 is running with KB5043145 installed.
> > 
> > 
> > Is it a new WSL update or the KB5043145 altered?
> 
> I don't see any new WSL release. The update is asking me to download, since I uninstalled. I paused the updates, but with this I am worried it doesn't work. I am going to wait until the end of the week to try.

Can confirm **WSL is working for me** now after installing the update again!

Haven´t found anything official related to WSL issues being fixed by the update. [Here ](https://support.microsoft.com/en-us/topic/september-26-2024-kb5043145-os-builds-22621-4249-and-22631-4249-preview-71ee16f6-9a39-4569-937c-fe0fd8577285) they acknowledge there are issues, no mention of WSL thought, but they say to have mitigated them.

Anyway. I am good for now!

**Comment by datacompboy** [comment] 2024-10-03 16:46
> If anyone can reproduces this issue, please:
> * Then go back to "System" -> right click, "Create live kernel memory dump file" -> "full live kernel memory dump"
> * Share that file with us (either via Google Drive, OneDrive, or send to [secure@microsoft.com](mailto:secure@microsoft.com)

I've sent the dump to secure@

**Comment by gaborauth** [comment] 2024-10-04 11:29
I installed again the KB5043145 and the issue somehow fixed. Maybe an uninstall of the update and reinstall of it fixed? Hm. Strange.

**Comment by anhdinh** [comment] 2024-10-08 03:20
> > If anyone can reproduces this issue, please:
> > 
> > * Then go back to "System" -> right click, "Create live kernel memory dump file" -> "full live kernel memory dump"
> > * Share that file with us (either via Google Drive, OneDrive, or send to [secure@microsoft.com](mailto:secure@microsoft.com)
> 
> I've sent the dump to secure@, CRM:0305058140
> 
> Uninstall of KB5043145 fixes wsl but brakes explorer ("can't open start menu, reboot"); re-installation of KB fixes explorer but breaks wsl :(

the issue happens on my system,  Uninstall KB5043145 WSL works but the search bar doesn't work completely

**Comment by anhdinh** [comment] 2024-10-08 03:21
> I installed again the KB5043145 and the issue somehow fixed. Maybe an uninstall of the update and reinstall of it fixed? Hm. Strange.
should I do that? I need the search bar for everything

**Comment by luciandf** [comment] 2024-10-08 07:03
> > > If anyone can reproduces this issue, please:
> > > 
> > > * Then go back to "System" -> right click, "Create live kernel memory dump file" -> "full live kernel memory dump"
> > > * Share that file with us (either via Google Drive, OneDrive, or send to [secure@microsoft.com](mailto:secure@microsoft.com)
> > 
> > 
> > I've sent the dump to secure@, CRM:0305058140
> > Uninstall of KB5043145 fixes wsl but brakes explorer ("can't open start menu, reboot"); re-installation of KB fixes explorer but breaks wsl :(
> 
> the issue happens on my system, Uninstall KB5043145 WSL works but the search bar doesn't work completely

is this with the new KB5043145? After I uninstalled it, it didn't pop back until a few days later when I saw that they apparently changed it but I didn't have the patience for another f-up so I have not installed it yet.

**Comment by anhdinh** [comment] 2024-10-08 08:20
> > > > If anyone can reproduces this issue, please:
> > > > 
> > > > * Then go back to "System" -> right click, "Create live kernel memory dump file" -> "full live kernel memory dump"
> > > > * Share that file with us (either via Google Drive, OneDrive, or send to [secure@microsoft.com](mailto:secure@microsoft.com)
> > > 
> > > 
> > > I've sent the dump to secure@, CRM:0305058140
> > > Uninstall of KB5043145 fixes wsl but brakes explorer ("can't open start menu, reboot"); re-installation of KB fixes explorer but breaks wsl :(
> > 
> > 
> > the issue happens on my system, Uninstall KB5043145 WSL works but the search bar doesn't work completely
> 
> is this with the new KB5043145? After I uninstalled it, it didn't pop back until a few days later when I saw that they apparently changed it but I didn't have the patience for another f-up so I have not installed it yet.

I updated wsl to the newest version, then uninstalled and reinstalled KB5043145 and now it seems everything is working correctly(docker and also the search bar), it was annoying and took a morning to fix.

**Comment by datacompboy** [comment] 2024-10-08 17:35
> is this with the new KB5043145? After I uninstalled it, it didn't pop back until a few days later when I saw that they apparently changed it but I didn't have the patience for another f-up so I have not installed it yet.

there is no "new" update with same number as far as I know.

but i see there is a fresh [KB5044285](https://support.microsoft.com/en-us/topic/october-8-2024-kb5044285-os-builds-22621-4317-and-22631-4317-c1aba548-fc93-420e-855f-8594157c3e9e) -- it fixed wsl issue. now both wsl and start menu is working again.

**Comment by pantharshit007** [comment] 2024-10-10 06:58
![Image](https://github.com/user-attachments/assets/17bd2188-6703-4275-ac0b-2b912ae2a1f9)
with this update powershell, WSL, Docker all are working fine

**Closed** 2024-10-17 07:19 UTC
Labels: needs-author-feedback
