### ISSUE TITLE
Cannot run Intel Compiler ICC or ICPC command in WSL

### ISSUE THREAD

**Issue by macxfadz** [Microsoft/WSL#2608] opened 2017-10-26 15:41 UTC
I recently installed Fresh **Windows 10 (Pro) Fall creators update** (General Release ,**not an Insider Build**).

Enable Linux Subsystem and installed Ubuntu App through Windows 10 App store.
Install relevant updates in Windows and WSL 
Install **Intel Parallel Studio 2018** - Here Parallel studio 2018 comes with .tgz distribution I extract all the content in to a folder in windows side and mount it from WSL bash  and install it from there.Further guide lines obtain from here - [Intel Guide](https://software.intel.com/en-us/download/parallel-studio-xe-2018-install-guide-linux) & [Compile guide](https://software.intel.com/en-us/get-started-with-cpp-compiler-18.0-for-linux-parallel-studio-xe-2018) & [Intel setup guide](https://software.intel.com/en-us/articles/setting-up-the-build-environment-for-using-intel-c-or-fortran-compilers#composer)

- After successful installation I set environment variables as they mentioned.set Atchitecture to **_intel64_** and Platform to **_Linux_**

- Create simple C++ source file tried to compile it using **_icpc_**  intel compiler command but WSL cannot **fork the process** and **identify the command** 

Please help on this matter. How to configure intel C./C++ compiler in WSL  correctly? 

![icpc_error](https://user-images.githubusercontent.com/3683121/32062476-3f7e3d56-ba92-11e7-976b-af6a666d9dd8.PNG)
![icp2](https://user-images.githubusercontent.com/3683121/32062821-3ad673b2-ba93-11e7-95b3-cec5a745d441.JPG)
![icpc3](https://user-images.githubusercontent.com/3683121/32063743-992b2866-ba95-11e7-9382-51294125a679.JPG)
![icpc4](https://user-images.githubusercontent.com/3683121/32063744-995c4270-ba95-11e7-9083-205b02894b75.JPG)

**Comment by therealkenc** [comment] 2017-10-27 09:37
Need a [gist](https://gist.github.com/) of the [`strace`](http://man7.org/linux/man-pages/man1/strace.1.html) so we can check out the `EINVAL`.
```
strace -ff icpc a.cpp 2> icpc.strace
```
Also the output of `ver` from the windows command line. Gonna say #1005, but that's just a guess absent the trace.

**Comment by therealkenc** [comment] 2017-10-27 21:08
`icpc` is not in your path, which is not a WSL thing.

I was referring to the following from you screencap in the OP:
```
icpc: error #10103: can't fork process: Invalid argument
```

**Comment by onomatopellan** [comment] 2017-10-27 22:56
@macxfadz You need to call `source psxevars.sh` every time you open bash.exe in order to use icpc or get the strace.

**Comment by macxfadz** [comment] 2017-10-28 02:56
@onomatopellan  strace was generated but, *.out* or compiled binary output couldn't generated,please need your help on  invoking intel compiler.
![icpc6](https://user-images.githubusercontent.com/3683121/32130634-bcfd3944-bbb9-11e7-91a6-d864fad98567.JPG)

**Comment by macxfadz** [comment] 2017-10-28 03:04
@therealkenc  here is the **strace** file ,that was generated

[icpc.strace.txt](https://github.com/Microsoft/WSL/files/1423877/icpc.strace.txt)

**Comment by therealkenc** [comment] 2017-10-28 04:16
```
open("/tmp/icpcdashvzbvylx", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
close(3)                                = 0
unlink("/tmp/icpcdashvzbvylx")          = 0
rt_sigaction(SIGINT, {SIG_DFL, [INT], SA_RESTORER|SA_RESTART, 0x7f9ed0b954b0}, {0x52a230, [INT], SA_RESTORER|SA_RESTART, 0x7f9ed0b954b0}, 8) = 0
{SIG_DFL, [], SA_RESTORER, 0x7faca86654b0}, 8) = 0
[... more unnotable rt_sigactions]
mmap(NULL, 10489856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9ed00d0000
clone(child_stack=0x7f9ed0acffff, flags=CLONE_VFORK|SIGCHLD) = -1 EINVAL (Invalid argument)
```
Which sure _looks_ like #1005; but you say you are on 16299 FCU -- still no `ver` output from windows command prompt. `CLONE_VFORK|SIGCHLD` was addressed back in Feburary ([message](https://github.com/Microsoft/WSL/issues/1005#issuecomment-277388850)) circa 15046. Anyway, _"there's your problem"_.

**Comment by dmey** [comment] 2017-11-02 22:22
@therealkenc, I am having the same issue:
Microsoft Windows [Version 10.0.16299.19].
Let me know if you need more logs.
Thanks for looking into this.

**Comment by macxfadz** [comment] 2017-12-04 14:24
@therealkenc  any luck ? anyone ran Intel C/C++ compiler successfully in WSL?

**Comment by therealkenc** [comment] 2017-12-04 14:37
I can't tell from the `strace` alone what is causing the `EINVAL`. It the lead up looks alright, assuming I am not staring something in the face (I might). The license terms for Intel Parallel Studio do cause somewhat of an unfortunate drag on investigation. It would be worth contacting your Intel sales rep. It would also be worth trying Insiders, because `CLONE_VFORK` had major surgery as of 17046, and there is a better than zero chance this sorted itself.

**Comment by jstarks** [comment] 2017-12-04 14:43
CLONE_VFORK without CLONE_VM would fail before 17046 but should work fine now. So this may be fixed in recent insider builds.

**Comment by macxfadz** [comment] 2017-12-04 15:47
@therealkenc  @jstarks  , as you guys mentioned , with next Windows 10 this issue will be resolved right? 
`flags=CLONE_VFORK|SIGCHLD) = -1 EINVAL (Invalid argument)`

**Comment by sunilmut** [comment] 2017-12-04 20:02
@macxfadz - Yes, where `next` means the release after Fall Creators Update.

**Comment by macxfadz** [comment] 2017-12-05 03:06
@sunilmut  , `next` implies next Windows 10 major update release on April or May :) ,Thank you for the confirmation.

**Comment by BopngMa** [comment] 2018-01-04 10:26
It also occurs to me!!!

Has this problem solved in the insider version? Anyone tested ?

How to install the insider version?

Thanks

**Comment by kei2e** [comment] 2018-03-15 06:46
It seems to have been resolved in insider build: Had the same problem, but now works fine after updating to 17115.

**Comment by macxfadz** [comment] 2018-03-15 08:24
When we are going to have next major update of Windows 10 1803? this coming April?

**Comment by DarthSpock** [comment] 2018-03-15 12:48
It will be in available in early April. They released a KB a couple days ago that was forcefully installed upon internet connectivity being established to assist upgrading to 1803. I doubt the forced KB would rear it's head in a corporate network but your personal computer will be affected. Of course you can uninstall it (but considering the advantages to WSL and Windows that will be gained I wouldn't).

**Comment by tianyikillua** [comment] 2018-04-30 10:42
I confirm that the problem is now solved within 1803.

**Comment by jstarks** [comment] 2018-04-30 15:16
Great, thanks for confirming.

**Closed by jstarks** 2018-04-30 15:16 UTC
Labels: fixedin1803, fixedininsiderbuilds

**Comment by macxfadz** [comment] 2018-05-01 07:42
@tianyikillua  thank you for the confirmation.

**Comment by macxfadz** [comment] 2018-06-02 22:54
actually, I installed WSL 18.04 with Windows 10 1803 same thing happened again... but I found a fix for this issue , hope this might help you.
![bashrc](https://user-images.githubusercontent.com/3683121/40881506-e8287700-66e5-11e8-8dbe-8a8c1380e8d2.PNG)
![select](https://user-images.githubusercontent.com/3683121/40881508-f03713a2-66e5-11e8-9803-bf34bc95b2b7.PNG)
![setpathandargs](https://user-images.githubusercontent.com/3683121/40881511-f3cf20b8-66e5-11e8-923e-6d168f9f218c.PNG)
![checking](https://user-images.githubusercontent.com/3683121/40881512-f624b292-66e5-11e8-9bf2-ed1ed9155932.PNG)
