### ISSUE TITLE
The application was unable to start correctly 0xc0000142. Click OK to close the application.

### ISSUE THREAD

**Issue by kokosky93** [microsoft/WSL#5448] opened 2020-06-20 08:05 UTC
I installed the Docker by Docker Desktop Installer then I was forced to install WSL by the link:
https://docs.microsoft.com/pl-pl/windows/wsl/wsl2-kernel

I did this and docker is working fine, but during turning off the computer I have wsl.exe error message:
The application was unable to start correctly 0xc0000142. Click OK to close the application.

I have Windows 10 Home. Build number: 19041

**Comment by DHowett** [comment] 2020-06-21 01:41
Does it say the name of the application that has failed to launch at the top of the dialog?

**Comment by DHowett** [comment] 2020-06-21 01:47
(For triage people: I’m here because 0xc0000142 is the error code you get when `conhost` fails to launch before the process finishes launching. If you see errors like this, tag me in!)

**Comment by kokosky93** [comment] 2020-06-22 13:41
@DHowett at the top of the dialog I see wsl.exe

**Comment by endan715** [comment] 2020-06-24 22:11
Yeah, I got the exact the same error. Same setup with docker. 
![IMG_20200624_230437](https://user-images.githubusercontent.com/10730219/85632862-041fb280-b670-11ea-8be9-6de9aa987f79.jpg)

**Comment by garbinmarcelo** [comment] 2020-07-07 18:18
**Here: Windows 10 Pro v2004**

Same error here, but when I shut down or restart the computer with the Docker Desktop open / running.

This started after I quit WSL2 and tried to go back to Hyper-v, but as there was no virtual machine I went back to WSL2 and started this same error.

If the Docker desktop is closed this error does not seem to occur.

**Comment by VinAr22** [comment] 2020-07-18 15:21
I have the same problem. Anyone solved it?

**Comment by maboalim** [comment] 2020-07-21 21:33
I also have the same problem for windows 10 Pro and docker desktop

**Comment by gouthammavuri** [comment] 2020-07-23 15:59
I am also getting same issue in Windows 10 Pro 2004 build and docker desktop.

**Comment by markuspalme** [comment] 2020-07-23 17:32
Same here - let me know if I can provide logs or similar to assist with troubleshooting.

**Comment by jimDNX** [comment] 2020-07-25 22:03
same here.. fresh install...

**Comment by alexhackney** [comment] 2020-07-28 17:40
I went back to WSL1 and it solved everything. It also made docker faster.

**Comment by JonHolman** [comment] 2020-08-27 15:08
Thanks everyone.  After reading the discussion here, I resolved this by going into Docker for Windows settings screen and unchecking "Use the WSL 2 based engine" on the General tab.

**Comment by CodeBrotha** [comment] 2020-09-10 18:33
> Thanks everyone. After reading the discussion here, I resolved this by going into Docker for Windows settings screen and unchecking "Use the WSL 2 based engine" on the General tab.

I wish I could do that, but hat setting is grayed out. Cannot be disabled.

**Comment by kokosky93** [comment] 2020-09-24 20:57
@alexhackney how did you downgrade WSL to version 1?

**Comment by ColinM9991** [comment] 2020-11-16 09:25
In my case this was being caused by a distro which no longer existed physically. To resolve I had to remove this via `wslconfig`

To check this, list all distros with `wslconfig`
```
wslconfig /list
```

Locate any distros which shouldn't be there and remove them by name.

```
wslconfig /u <Distro>
```

Example:
```
wslconfig /u CentOS
```

**Comment by muhammad-usman-anwar** [comment] 2021-01-14 11:10
@DHowett got same error

**Comment by spavett** [comment] 2021-02-01 16:12
I have been getting this issue for the last 6 months and have built my machine twice in that time. I had a look at the distros seems oks: 
```
❯ wslconfig /list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
docker-desktop-data
docker-desktop 
```
no strays.

**Comment by leeand00** [comment] 2021-03-21 16:22
Same issue running a scheduled task that returns  I believe I'm running WSL 1.0 since I have the `wslconfig /list command`.  

Please see https://stackoverflow.com/questions/66727315/process-runs-in-powershell-prompt-but-not-as-a-scheduled-task for more information.

**Comment by o-sdn-o** [comment] 2022-04-05 08:20
In my setup, this error appears randomly (~10/2 fail/ok) when starting any (wsl?) console applications, e.g. multiple errors while installing git4win - The application was unable to start correctly 0xc0000142 (3221225794).

The behavior is like a race condition somewhere.

The issue was resolved by blindly replacing the C:\Windows\System32\conhost.exe file with the "OpenConsole.exe" binary from the latest build of Windows Terminal (by renaming).

**Comment by ortzinator** [comment] 2022-05-12 15:06
This was solved for me by updating Docker for Desktop

Possibly related: docker/for-win#6933

**Comment by fferri** [comment] 2022-12-15 17:23
Everything is up to date, but I always see this error

**Comment by bensoutendijk** [comment] 2022-12-27 21:43
I am seeing this error as well. Win 11 + WSL2 + docker desktop

**Comment by frankhuurman** [comment] 2023-01-12 22:16
Same issue since a week or 2 or 3.
Win 10 22H2, build 19045.2486, Ubuntu 20.04 image, WSL2 + docker desktop.

Didn't have it before, nothing changed.

**Comment by Biswa96** [comment] 2023-01-13 04:35
Try to use `dockerd` in the distribution in WSL2, instead of docker desktop.

**Closed** 2024-02-01 12:17 UTC
Labels: failure-to-launch
