### ISSUE TITLE
I can't install any Linux distro (and WSL in general to some degree) no matter what I try

### ISSUE THREAD

**Issue by lyndsay9968** [microsoft/WSL#12236] opened 2024-11-04 14:25 UTC
### Windows Version

Microsoft Windows [Version 10.0.19044.5011]

### WSL Version

2.3.24.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Repro Steps

I want to use Docker Desktop, but for the past week I have been unable to get WSL to work. Docker Desktop **is not relevant** in this case (not even installed at this point), as other installation methods also fail. It is simply **the end goal**. Of course, the hardware and operating system meet the minimum requirements and is updated, and hardware virtualization is enabled.

Running `wsl --install` from elevated PowerShell ends with (translated to English)

> Installing: Virtual Machine Platform
Virtual Machine Platform has been installed.
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Installing: Windows Subsystem for Linux
The service has not been launched.%                           ]

I don't know what service it is referring to. On the Internet I found information that it is about the LxssManager service, but this one is installed and works. There's also LxssManagerUser_xyz service which can be started manually with no problem.

After that I'm unable to run neither `wsl --install -d Ubuntu` nor `wsl --update`

> wsl --install -d Ubuntu
Installing: Ubuntu
An error occurred during installation. Distribution Name: 'Ubuntu' Error Code: 0x80070426

> wsl --update
Installing: Windows Subsystem for Linux
The service has not been launched.%                           ]

At this point running `wsl --version` ends with an error (unknown parameter, quite as if WSL1 was installed).
Uninstallation and manual installation with system components (add or remove software in the control panel) ends the same way.

Since I have neither a Microsoft account nor a Windows Store account, I tried a manual installation according to the official instructions from this link https://learn.microsoft.com/en-us/windows/wsl/install-manual

Following these steps and manually installing the AppxBundle file (the manual mentions .appx, and installing .AppxBundle according to the instructions from this link https://learn.microsoft.com/en-us/windows/wsl/install-on-server won't even start) ends without problems, without error information, but also without success information.. The distribution is now available as an entry in the start menu, but you still can't launch it (nothing happens after clicking it and `wsl -l -v` shows nothing installed). WSL and WSL Settings also appear. WSL Settings can be opened, but WSL itself only flashes a console window, and a shortcut on closer inspection leads nowhere.

Running `wsl -l -v` ends with a message that no distribution is installed (previous attempts to indicate the default version by --set-default-version despite the success information did not change anything.). Multiple reboots and searching for system updates also did nothing.
The only success is that the `wsl --version` command finally works. But that's actually the only thing that works.
At this point attempting to run the `wsl --install` command ends with an infinite install process, which endlessly shows 0.0% progress. 
Distributions manually installed from .AppxBundle files don't want to run and aren't listed by `wsl -l -v`. `wsl --update` shows there are no updates available.

The only thing I managed to get in a week was a space that disappeared from my drive. Absolutely nothing works here. What am I supposed to do?
I probably tried other things that I did not describe here, I do not remember everything. I looked through a lot of similar (**not exactly the same**) problems on the Internet and on this issue tracker, but absolutely nothing helped. It looks as if some cryptic service is not installed in the first step and no matter what I do, nothing works after that.

### Expected Behavior

Distro is installed/Something actually works for a change.

### Actual Behavior

As described above: nothing works. I'm not even sure if at least WSL2 is properly installed, despite finally being able to get `wsl --version` to output anything on the screen.

**Comment by lyndsay9968** [comment] 2024-11-05 13:13
The collected logs were reviewed and I was told that an alarming amount of data was collected, some of which should have absolutely nothing to do with the handling of this request, and I was not given permission to share it. Apparently, there are some confidentiality agreements involved.

I am very committed to solving this problem and I know that you need additional information for this. Please indicate exactly what information you need on this issue and I will try to provide it. I am confident that there will be no problem on your side with providing the data that is actually needed to diagnose this problem. I apologize for the inconvenience.

**Comment by sirredbeard** [comment] 2024-11-05 15:35
Do you have any third-party security software, like an endpoint manager, installed? I ask because this sounds like a corporate environment where those are more common.

**Comment by lyndsay9968** [comment] 2024-11-05 16:07
No. Only a firewall which was disabled when problem occurred. Windows Store and probably some telemetry stuff was disabled in Group Policy but nothing major. Windows Update and updating of system components work flawless. 

Or rather, with one flaw. For some reason, Microsoft Edge is not updated. It also can not be updated from within the program (0x80080005) or through the offline installer (There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected.). I remind you that the firewall is **disabled** at this point.

There seems to be a problem with this machine. When installing WSL2, some service is not running (if the error message is correct), and the system is unable to update its component (edge), although Windows Update reports no problems (only drivers are excluded from being updated by Windows Update).

**Comment by sirredbeard** [comment] 2024-11-05 16:35
> The service has not been launched.% ]

This is concerning, I wonder what is blocking this from starting.

> wsl --install command ends with an infinite install process

I am curious what would happen if you did a `wsl --import` of a rootfs tar, like one [from Ubuntu](https://cloud-images.ubuntu.com/wsl/noble/current/) (pick amd64 or arm64 as appropriate).

> LxssManager 

Is pretty old, it should be there in Services but only run Manually, I think it's just there for backward compatibility with WSL1 at this point.

You should see the following in TM on recent versions of Windows and WSL:

![Image](https://github.com/user-attachments/assets/3dac6231-de02-4d1d-9e93-ee3c5e4d2fa8)


Also, are you on a version of Windows that has Hyper-V? Can you enable Hyper-V and start a VM? My thought, other than the WSL service is being blocked, is that maybe virtualization of any kind may be disabled.

**Comment by lyndsay9968** [comment] 2024-11-05 16:55
> > The service has not been launched.% ]
> 
> This is concerning, I wonder what is blocking this from starting.

What service is involved here? I think this is the core problem.

> > wsl --install command ends with an infinite install process

I'm not sure how, but I finally got the command to work. The distribution downloads (from outside the store) and installs without a hitch, but it doesn't boot 
`C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu_2204.1.8.0_x64__79rhkp1fndgsc\ubuntu.exe
The service has not been launched`

It is also not visible in the list `wsl -l -v` 
`The Windows subsystem for Linux has no installed distributions.
Wsl/WSL_E_DEFAULT_DISTRO_NOT_FOUND`

> Is pretty old, it should be there in Services but only run Manually, I think it's just there for backward compatibility with WSL1 at this point.
> 
> You should see the following in TM on recent versions of Windows and WSL:
> 
> ![Image](https://github.com/user-attachments/assets/3dac6231-de02-4d1d-9e93-ee3c5e4d2fa8)
> 

Only Windows Subsystem for Linux Service is running.

> Also, are you on a version of Windows that has Hyper-V? Can you enable Hyper-V and start a VM? My thought, other than the WSL service is being blocked, is that maybe virtualization of any kind may be disabled.

Most of the recommended solutions to similar problems from this issue tracker recommended disabling hyper-v, so I didn't even try to enable it because I don't need it. But hardware virtualization is enabled and VirtualBox works. Windows Sandbox also worked, but was disabled in the process of finding the cause of the problems.

**Comment by OneBlue** [comment] 2024-11-05 22:13
Hi, unfortunately without logs we can't root cause the issue so i'll close it for now. Feel free reopen if you're able to upload logs at a later point.

**Closed by OneBlue** 2024-11-05 22:13 UTC

**Comment by lyndsay9968** [comment] 2024-11-07 13:21
It is too early to close this issue. 

The problem seems to be limited to one service that cannot be installed, but for some reason you are unable or unwilling to at least point me to its name.

As I mentioned earlier, I am willing to provide the required logs, but please narrow it down. If you specify exactly what information is needed for this particular request, I am sure I can provide it. It's just that the tool you indicated in collects too much information. It has been pointed out to me that a lot of it should have nothing to do with the issue being reported, which is why I've been given a red light to provide it. If their scope is smaller and more precise, I am sure they will be positively reviewed and I will get permission to share them. Again, I apologize for the inconvenience, I realize that you would prefer to have all the data possible.

In addition @OneBlue , I don't have permissions to reopen this issue.

**Comment by lyndsay9968** [comment] 2024-11-11 11:16
@OneBlue You can mark this issue as fully resolved
