### ISSUE TITLE
ELF section .note.ABI-tag breaks shared libraries

### ISSUE THREAD

**Issue by sthalik** [microsoft/WSL#3023] opened 2018-03-14 07:47 UTC
### Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```
10.0.16299.192
Linux ananke 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux
Debian sid
```

### What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Executing `lupdate` from Qt5 tools, `LD_DEBUG=all ldd /usr/lib/libQt5Xml.so`, etc.

Doesn't treat `libQt5Core.so.5` as a suitable library, as per

```
lupdate: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

### What's wrong / what should be happening instead:

As long as ELF section called `.note.ABI-tag` exists, the library can't be linked to by other shared objects. It can be executed directly by the `ld-linux` linker however.

The workaround is to `strip --remove-section=.note.ABI-tag /usr/lib/libQt5Core.so.5.10.1`.

See how the section's presence influences `file(1)` output:

```
/usr/lib/libQt5Core.so.5.10.1: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=147dcf3333ff6b490dabb4028a217effa08013e3, for GNU/Linux 3.17.0, stripped
```

Finally, without the section:

```
/usr/lib/libQt5Core.so.5.10.1: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=147dcf3333ff6b490dabb4028a217effa08013e3, stripped
```

### Strace of the failing command, if applicable[...]

`openat` of the library, `read`, `lseek`, `close`, barf out error message on the standard error file descriptor and `exit_group`.

Similarly `LD_DEBUG=all` shows opening the ELF without further information other than an error message.

```
      3954:     file=libQt5Core.so.5 [0];  needed by lupdate [0]
      3954:     find library=libQt5Core.so.5 [0]; searching
      3954:      search path=/usr/lib           (system search path)
      3954:       trying file=/usr/lib/libQt5Core.so.5
      3954:      search cache=/etc/ld.so.cache
      3954:      search path=/usr/lib           (system search path)
      3954:       trying file=/usr/lib/libQt5Core.so.5
      3954:
lupdate: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

After removing the tag, the runtime linking process proceeds normally.

**Comment by sthalik** [comment] 2018-03-14 07:53
This "atomic bomb" workaround helps too:

```
find /lib /usr/lib/ /usr/libexec -name '*.so' | xargs strip --remove-section=.note.ABI-tag
```

Will barf out a few errors where libraries are actually linker scripts. No ill effects.

**Comment by jkj** [comment] 2018-04-17 08:06
Just came across this in a Google search. Not sure if it is relevant or not but just FYI glibc creates an ABI-invalid .note section for that exact section. I have just filed a bug against glibc about that.
https://sourceware.org/bugzilla/show_bug.cgi?id=23072
I don't know exactly what lupdate is, but if it is a strictly conforming gABI ELF processor it will get wrong values from that section. Just in case that helps.

**Comment by sthalik** [comment] 2018-05-17 12:03
Works for me on Linux in a VM. The ELF standard notwithstanding, having the runtime linker not work due to a quirk in WSL is an issue.

Interestingly enough, the newer shared objects added the option to call them directly, having them say more or less "I'm a library". Interestingly enough, calling that `.so` directly works, it's only linking to it that's broken.

**Comment by fweimer** [comment] 2018-05-19 09:15
What, exactly, is causing this? The ELF note in a shared object is only parsed by the glibc dynamic linker during program loading, not the kernel, so it is unclear to me why there would be a difference between Linux and Windows in this context.

**Comment by therealkenc** [comment] 2018-05-19 17:26
> What, exactly, is causing this? The ELF note in a shared object is only parsed by the glibc dynamic linker during program loading, not the kernel

I've been also curious for my own edification: What, exactly, is special about the `libQt5Core.so` build process that generates the (let's call it) unusual binary? I understand the bug [cited](https://sourceware.org/bugzilla/show_bug.cgi?id=23072) by jkj. I am just not clear on why `libQt5Core` trips it in this scenario. How would one go about creating a helloworld.so library that exhibits the fail. And why does `libQt5Core` generate the binary that way? I could do a deep dive but I suspect someone in this thread (or Ben) already takes the reason as obvious.

**Comment by fweimer** [comment] 2018-05-19 17:33
Yes, it would certainly be interesting to see the output of `objdump -s -j .note.ABI-tag /usr/lib/libQt5Core.so.5.10.1`. So far, we only know that the object requires kernel version 3.17.

If the Windows kernel self-identifies itself as something earlier than kernel version 3.17, then the dynamic linker is completely right to ignore the object.

**Comment by therealkenc** [comment] 2018-05-19 17:43
> If the Windows kernel self-identifies itself as something earlier than kernel version 3.17

WSL self identifies as `4.4`. But I'd be real real surprised if the linker looks. [I have been surprised before though.]

**Comment by fweimer** [comment] 2018-05-19 19:09
@therealkenc Actually, the glibc dynamic linker looks at the ABI notes and refuses to load incompatible DSOs. To determine the kernel version, it prefers the version reported in the vDSO, followed by uname, followed by the contents of `/proc/sys/kernel/osrelease`. I wonder if the version in the vDSO isn't 4.4.

**Comment by sthalik** [comment] 2018-05-19 21:58
I can't remember the Linux distribution that had the binary. It was either Debian sid or Arch testing. Sorry guys. You can list sections for your own binaries though.

**Comment by therealkenc** [comment] 2018-05-19 22:41
> I can't remember the Linux distribution that had the binary.

Ah. That was kinda relevant to mention in the the OP (grumble). This is possibly related to #2820. In that issue `libQt5Core.so.5` exists but could not be opened. The discussion there subsequently went downhill to what was almost certainly a `rename2()` blind alley, and was ultimately closed for lack of a repro. Something this issue is in need of as well; and is likely a contributing factor to the chirping crickets.

**Comment by noahbaxter** [comment] 2018-05-27 20:52
Any update on this? Running strip --remove-section=.note.ABI-tag /usr/lib/libQt5Core.so.5.10.1 doesn't work because that isn't a file that exists. I've installed PyQt5 through pip. Any ideas?

**Comment by sthalik** [comment] 2018-05-28 01:58
@noahbaxter it's somewhere in `site-packages`.

@therealkenc the issue's reproducible on Debian sid. You can install it into a chroot via `debootstrap` into the default Ubuntu environment, or some other distro on MSFT Store. When debootstrap doesn't work, download `cdebootstrap-static` and manually unpack the `.deb` archive. That one works even on Android.

No idea what causes it to begin with, binutils, gcc, GNU libc or something else...?

**Comment by DarthSpock** [comment] 2018-05-31 14:48
> reproducible on Debian sid. You can install it into a chroot...

Or you could take the easy route and install Debian from the Store, then upgrade.

**Comment by ChrisTX** [comment] 2018-08-08 09:24
>Ah. That was kinda relevant to mention in the the OP (grumble). This is possibly related to #2820, which was on Arch.

I can confirm that stripping the tag resolves the problem with Arch. Afterwards Qt5 works fine.

**Comment by FrankHB** [comment] 2018-09-27 01:42
> 
> 
> This "atomic bomb" workaround helps too:
> 
> ```
> find /lib /usr/lib /usr/libexec -name '*.so' | xargs strip --remove-section=.note.ABI-tag
> ```
> 
> Will barf out a few errors where libraries are actually linker scripts. No ill effects.

This would break programs rely on stripped information in the binary. For example, modified `/lib/ld-2.28.so` would not work with valgrind.

**Comment by du291** [comment] 2018-12-07 13:43
Hello, I have a problem that Qt5 based applications won't run on WSL.  After googling I was drawn here.
I haven't stripped yet the ABI tag from the lib, and hope to create more insight into the problem.

> Yes, it would certainly be interesting to see the output of `objdump -s -j .note.ABI-tag /usr/lib/libQt5Core.so.5.10.1`. So far, we only know that the object requires kernel version 3.17.

Here's the dump

$ objdump -s -j .note.ABI-tag /lib/libQt5Core.so.5|less

/lib/libQt5Core.so.5:     file format elf64-x86-64

Contents of section .note.ABI-tag:
 4ef138 04000000 10000000 01000000 474e5500  ............GNU.
 4ef148 00000000 03000000 11000000 00000000  ................

Feel free to ask for more info.

**Comment by ChrisTX** [comment] 2019-01-08 10:15
For ArchLinux users, it's possible to utilize [pacman hooks](https://wiki.archlinux.org/index.php/Pacman#Hooks) to automatize the stripping of the `libQt5Core.so` during the installation or upgrade of Qt. Simply create a `.hook` file in `/etc/pacman.d/hooks` with the following contents:

```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = qt5-base

[Action]
Depends = binutils
When = PostTransaction
Exec = /usr/bin/strip --remove-section=.note.ABI-tag /usr/lib/libQt5Core.so
```

Upon every Qt5 upgrade after that, the offending section will be stripped automatically. If `qt5-base` was already installed, simply force a reinstallation.

**Comment by du291** [comment] 2019-01-08 12:06
Thanks for the tip. Does the stripping result in any instability? If the ABI versions don't match I would imagine Qt issuing an unsupported syscall sooner or later?

**Comment by therealkenc** [comment] 2019-01-08 17:53
Very nice investigation. 🏆

> @therealkenc can you forward this to whoever is responsible for the vDSO?

I don't really know whose around anymore. @benhillis maybe. 

What might help the chances of this one being looked at immeasurably would be specific rerpo steps to create a shared library with one `int hello()` function that results in the `error while loading shared libraries` when the library is linked with a one-liner `main()` that calls `return hello()`. 
Doing that has the nice properties of: (a) avoids saying '`libQt`' which is technically out of scope (b) avoids saying 'Arch', which isn't in the Store. Which is at base why/how this one went dark.

Same was suggested in [May 2018](https://github.com/Microsoft/WSL/issues/3023#issuecomment-390420031). It might be overkill, your analysis might be self-evident, and this might be a matter of changing a `{0x03,0x0d,0x0b}` constant in the vDSO. But that's a lot of mights, and a new well-formed issue is how I'd try to get attention.

**Comment by ChrisTX** [comment] 2019-01-08 18:47
Right, I'll see if I can generate a simple example. It's easily reproduced by using a similar trick to what Qt5 itself does. They explicitly [add an assembly file](https://github.com/qt/qtbase/blob/5.12/src/corelib/global/minimum-linux.S) with the section information and [have a header](https://github.com/qt/qtbase/blob/5.12/src/corelib/global/minimum-linux_p.h) that differentiates between the available kernel features it was configured with. Qt5 can use `renameat(2)`, `getentropy(2)` and `statx(2)`, which were introduced in 3.16, 3.17, and 4.11 accordingly. It should be noted that WSL (as of 1809 at least) supports all three syscalls despite identifying as 4.4. I suspect the original reason people blamed `renameat(2)` is related to this, too - if you configured Qt5 with it, it requires kernel 3.16, but to glibc it appears as if 3.14.11 was in use, making the binary invalid.

Aside from the mismatch, which can be easily reproduced and argued why it's an issue - LSB also demands that LSB compliant binaries require the proper kernel version, and if `renameat(2)` is used, it should be 3.16 - the second problem at hand here is that the kernel version of 4.4 is too low. It makes little sense to retain an older kernel identifier other than for kernel modules, which WSL obviously does not have.

That aside, I don't understand why Qt5 would be entirely out of scope. Qt is _not_ a GUI library in itself, and there's a lot of features in the library that have nothing to do with GUI or hardware abstractions, like XML parsers, an SQL abstraction layer, networking, concurrency extensions, and these are also common place in the C++ world, even on servers. The problem also has nothing to do with the combination of Qt _and_ certain distros, but rather depends on what syscalls are exposed in the glibc of the system the binary is being built on. If you were to compile Qt5 yourself on Ubuntu, you'd still run into this problem, albeit not in the `statx(2)` case, since it took until glibc 2.28 for that to be implemented in the C library. On the upcoming Ubuntu 19.04, this is going to be the case, though.

**Comment by fweimer** [comment] 2019-01-08 19:23
Qt has fallback code for other kernels. They could do run-time detection and drop the ABI note. The Qt in Red Hat Enterprise Linux 8 has been patched to do just this, to preserve compatibility with the Red Hat Enterprise Linux 7 kernel.
Of course there is still a WSL bug here, the version really should be consistent. (Although calling the kernel 4.4 is a bit of a stretch, considering that various system calls are not implemented properly.)

**Comment by therealkenc** [comment] 2019-01-08 19:56
> Qt is not a GUI library in itself, and there's a lot of features in the library that have nothing to do with GUI or hardware abstractions

Preaching to the choir, brother. Personally I don't think _any_ of these libraries have thing-one to do with 'graphics'. Some of the functions end up reading and writing bytes down a socket, maybe, sometimes, depending on the function. 

But, sadly, this line of reasoning (most unfortunately) falls down, because of issue submissions along the lines of (say, made-up example) "VLC  doesn't run I get `<some libQt* function s---ts bed>`". Which is, in effect, useless for tracking down syscall surface bugs. By taking `libqt` or say `libgtk+` off the table, and limiting the scope to CLI (ie tty) scenarios, there is at least a _snowballs_ chance of getting an actionable repro with a manageable `strace` demonstrating a diverge. The problem has nothing to do with pixels. The distinction doesn't really have to do with ttys either, which is why "server scenarios" are out of scope too. Made-up example would be "My Apache PHP service isn't working, I get error `<whatever>`". Today's necropost on some mysql `EIO` problem comes to mind.

You can game the system of course, and that's exactly what folks should do. Any large graphic or server scenario can be turned into a small CLI one. Chrome (about as big as it gets) used to die because `getdents64()` was subtly broken. People can post "Chrome is broken", and then sit back and enjoy the soothing sound of the chirping crickets. Or folks can post a CLI repro like [this](https://github.com/Microsoft/WSL/issues/1769) and have a fighting chance.

**Comment by sthalik** [comment] 2019-01-09 03:12
> They explicitly add an assembly file with the section information and have a header that differentiates between the available kernel features it was configured with. 

This being an universal issue in itself is good in a way. At some point it's bound to become a problem serious enough for WSL's vendor to fix it. Especially given Debian's and Ubuntu's preference for pulling in all possible compile-time dependencies.

> Does the stripping result in any instability?

Not in practice, either. I'm running some Qt project with `-platform offscreen` at the very least.

**Comment by therealkenc** [comment] 2019-01-09 04:33
> Especially given Debian's and Ubuntu's preference for pulling in all possible compile-time dependencies.

Part of the reason this one went sideways though is Qt apps, even stuff like VLC, run alright on Ubuntu 18.04 from the Store. Then it gets revealed [after](https://github.com/Microsoft/WSL/issues/3023#issuecomment-390437392) the fact it wasn't Ubuntu from the Store and the coffin nails came out. I can't tell you why Qt5 is okay on Ubuntu, because I never looked. But it doesn't require any stripping of `.note` tricks on WSL, even if the WSL vDSO is getting kernel versions crossed.

```
$ cat /proc/version
Linux version 4.4.0-18309-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1000-Microsoft Thu Dec 20 12:56:00 PST 2018
$ lsb_release -d
Description:    Ubuntu 18.04.1 LTS
$ sudo apt-get install qt5-default
[...blah blah kitchen sink]
$ apt-cache show qt5-default | grep Version
Version: 5.9.5+dfsg-0ubuntu1
$ /usr/lib/qt5/bin/qtpaths --qt-version   # look ma no error while loading shared libs
5.9.5
$ ldd /usr/lib/qt5/bin/qtpaths | grep libQt
libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f3683d20000)
```

I suspect (or would like to hope) this issue would have gotten more grease if `qtpaths` or `qmake` or whatever (legit CLI scenarios if there is such a thing) faceplanted on a supported Debian or Ubuntu distro. But that's not how it went down.

**Comment by sthalik** [comment] 2019-01-09 06:40
> I suspect (or would like to hope) this issue would have gotten more grease if qtpaths or qmake or whatever (legit CLI scenarios if there is such a thing) faceplanted on a supported Debian or Ubuntu distro.

So you're saying that some recent Debian version doesn't exhibit this behavior? My sid/experimental with Qt 5.11 has this.

> it doesn't require any stripping of .note tricks on WSL, even if the WSL vDSO is getting kernel versions crossed.

Qt has some dubious stuff where Qt5Core can be invokes as an executable directly too. I don't think it should exist in the tree to begin with, but of course WSL ought to support ELF binaries correctly.

**Comment by benhillis** [comment] 2019-01-09 18:59
@ChrisTX - Excellent job debugging this! Looking through the history I looks like the mismatch version in the VDSO is accidental.

I can update the vsdo to match the version number from uname and the procfs, but while I'm doing that I wonder if there's a different version that we should be reporting...  4.4.0 was a somewhat arbitrary decision, I can look through the Linux kernel release notes and see if a more recent version number would be warranted.

**Comment by therealkenc** [comment] 2019-01-09 20:56
> 4.4.0 was a somewhat arbitrary decision

One (arbitrary) gate on bumping to 4.11 might be [`statx(2)`](http://man7.org/linux/man-pages/man2/statx.2.html) (sycall 332). Dunno if we have that yet; it's never come up AFACT (cred Chris for pointing it out).

**Comment by ChrisTX** [comment] 2019-01-10 03:41
>I can update the vsdo to match the version number from uname and the procfs, but while I'm doing that I wonder if there's a different version that we should be reporting... 4.4.0 was a somewhat arbitrary decision, I can look through the Linux kernel release notes and see if a more recent version number would be warranted.

If it helps you can find a table of all syscalls and when they were implemented in [`syscalls(2)`](http://man7.org/linux/man-pages/man2/syscalls.2.html). 

As for the version, as @fweimer mentioned, it's "not really a version 4.4.0" at the moment, for example `msgget(2)` still being missing (#1443). I suppose outside of assumptions that a given kernel version corresponds to a set of syscalls being available, there's no difference to WSL.

It's worth nothing though, that with Kali Linux in the store, and Arch being available by other means, some very recent userlands have been tested by people, the 4.4.0 report seems to cause few issues other than with Qt5. In the Wiki of "ArchWSL" for instance, [there's a list of know issues](https://github.com/yuk7/ArchWSL/wiki/Known-issues) and it boils down to the absence of `msgget(2)` breaking `fakeroot` and this very issue with Qt5. As I've mentioned above, LSB specifies the use of the `.note.ABI-tag` section, but it sees very little usage.

Conversely, if you bumped the version, this would affect the calls `preadv2(2)`, `pwritev2(2)`, `copy_file_range(2)`, the `pkey_mprotect(2)` family and `statx(2)`. Outside of `pkey_mprotect(2)`, the calls can be emulated by glibc with some degree of comprise.

> One (arbitrary) gate on bumping to 4.11 might be statx(2) (sycall 332). Dunno if we have that yet; it's never come up AFAICT (cred Chris for pointing it out).

I've checked in detail, with the [statx test from the kernel](https://github.com/torvalds/linux/blob/master/samples/statx/test-statx.c) and it's not implemented.

Qt works nonetheless as found on Arch (which is built with it enabled), because they've relegated the `statx(2)` and `renameat2(2)` calls to the glibc wrappers (with the former being available since 2.28), and `statx(3)` approximates the call if the former is not available in the kernel.

>I can't tell you why Qt5 is okay on Ubuntu, because I never looked.

It's because this only affects Qt5 version 5.10 and newer, it was introduced with [this commit.](https://github.com/qt/qtbase/commit/bb8a61866ec6a6de2426012f8c4219d41b3a414a#diff-e4c3c13b1c7ed0faa458312ad4d5c1da)

But I would consider the issue specific to Qt here not a direct problem of WSL: as @fweimer mentioned, there's better solutions for this check, and since a Linux kernel may receive backports, concluding that because a certain kernel version was found, no features from a newer one are available is simply not true with RHEL around. Or in the same way, it will still work with older kernels if glibc >= 2.28 is being used, since the wrapper emulates it.

**Comment by therealkenc** [comment] 2019-01-10 04:42
> it's "not really a version 4.4.0" at the moment, for example msgget(2) still being missing
> the 4.4.0 report seems to cause few issues other than with Qt5

`sync_file_range(2)`, `memfd_create(2)`. That's not counting stuff like `clone()`, `ptrace()`, `setsockopt()` being a big all-singing-all-dancing meta-syscalls bounced off magic option&flag redirects. [Don't get me started on `/proc`.)

Awkward because there's precedent for both overstating and understating the WSL kernel version. There's no right answer. The author of that ArchWSL known issues Wiki page just picked their personal pet peeves (Qt and, utterly at random, `fakeroot`). Different folks have different peeves, with plenty to go around.

But your conclusions are absolutely right. Great synopsis. There isn't much point in exaggerating the kernel version, and good reasons to not.

**Comment by ChrisTX** [comment] 2019-01-10 08:51
>The author of that ArchWSL known issues Wiki page just picked their personal pet peeves (Qt and, utterly at random, `fakeroot`).

`fakeroot` is quite quintessential on Arch, because the `makepkg` tool to build packages from a `PKGBUILD` source heavily relies on it. Without it, it's impossible to build your own packages and thus install anything from the AUR user repository. If you were to use the `dpkg-buildpackage` tool on Debian/Ubuntu, you'd need it for the same reason.

My point wasn't that there's not a number of syscalls broken or bugs in WSL, but rather that even on a rolling userland like Arch, the most common issue _stemming from the 4.4.0 version_ is this `.note.ABI-tag` issue. I've naturally experienced some issues due to emulation, like some threading tests for `libc++` failing, that I still need to debug in detail when I've got time, but as far as the kernel version is concerned, it should be only this issue.

**Comment by rigarash** [comment] 2019-05-01 16:16
FYI, Debian 'Buster' release, which will be released within a few months, will be affected by this bug.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927940 for the discussion in Debian.

**Comment by py563** [comment] 2019-05-08 15:17
i got same issue when installing anaconda3, i found the .so file and trying to run xargs command. i think it is not responding. the shell prompt just blinks indefinitely.

**Comment by py563** [comment] 2019-05-10 00:07
My bad, I did not have binutils in WSL. as it was not throwing any error I didn't realize what was wrong. 

> i got same issue when installing anaconda3, i found the .so file and trying to run xargs command. i think it is not responding. the shell prompt just blinks indefinitely.

**Comment by sthalik** [comment] 2019-06-21 11:15
> The author of that ArchWSL known issues Wiki page just picked their personal pet peeves (Qt and, utterly at random, `fakeroot`)

I haven't read this but see [fakeroot-tcp](https://aur.archlinux.org/packages/fakeroot-tcp/) on AUR if it's an issue for any of you.

I have reservations toward a Hyper-V basis for WSL2. Ballooning doesn't solve memory pressure issues as it can result in OOM. Hyper-V is also inferior in several aspects (USB redirection, running X11 as server, lack of OSX support) to VMware and can't be installed alongside it.

**Comment by ericLemanissier** [comment] 2019-12-04 15:41
For those trying to build qt on WSL (like me), the workaround is to use configure arguments : `-no-feature-statx -no-feature-getentropy -no-feature-renameat2` (I did not try to reduce to the minimum arguments, so maybe only one of those is actually needed)

**Comment by gojimmypi** [comment] 2020-05-19 19:27
Although the issue title is misleading, as detailed in [nextpnr #444](https://github.com/YosysHQ/nextpnr/issues/444) post-close comments, I am seeing this error in a fresh WSL Ubuntu 20.04 install:

```
error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```
```
$ ls /lib/x86_64-linux-gnu/libQt5Core.so.5 -al
lrwxrwxrwx 1 root root 20 Apr  9 00:57 /lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.12.8

$ file /lib/x86_64-linux-gnu/libQt5Core.so.5.12.8
/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e54a6cea97c3942fbcec1973574545fb3ad74015, for GNU/Linux 3.17.0, stripped

$ uname -a
Linux DESKTOP-AHQNIJN 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by NotVexed** [comment] 2020-06-26 17:43
I had an error with libQt5Core on WSL and I fixed it by using this workaround: https://github.com/YosysHQ/nextpnr/issues/444#issuecomment-631558250
I hope WSL can fix this issue.

**Comment by mikofski** [comment] 2021-05-19 03:32
this also happens for octave install in WSL1 Ubuntu focal (20.04LTS) from store on Windows 10.0.18363.1556:
```
$ sudo apt install octave

$ octave  # doesn't work
octave: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

$ sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 

$ octave  # works fine
```

**Comment by thisisnotmyrealname** [comment] 2022-06-26 18:20
Considering running GUI linux apps in win11 is supposed to be a feature, you'd think this 4+ year old bug would have been looked at

**Comment by fweimer** [comment] 2022-07-10 20:44
glibc 2.36 will remove the kernel version check. From the NEWS file:

> * The Linux kernel version check has been removed along with the
>   `LD_ASSUME_KERNEL` environment variable.  The minimum kernel used to built
>   glibc is still provided through `NT_GNU_ABI_TAG` ELF note and also printed
>   when libc.so is issued directly.

**Comment by afidegnum** [comment] 2022-11-28 07:22
I'm also facing a similar situation, applying the patch `strip --remove-section=.note.ABI-tag` at anywhere Qt5Core.so is located didn't help. What else can i do ?

**Closed** 2024-02-01 12:54 UTC
Labels: bug, wsl1

**Comment by Inndy** [comment] 2024-12-07 11:14
Hi, I found a workaround by leverage ld.so to load ELF so WSL won't need to parse the problematic ELF file.

Here is my shim script: https://github.com/Inndy/dotfiles/blob/73c86b582d5c8404ab7e0f5a6f40ca6a9078f4c1/bin/fix-wsl-v1-elf-shim
