### ISSUE TITLE
mv command in UBUNTU terminal  isn't working properly 

### ISSUE THREAD

**Issue by MAGED-2034** [microsoft/WSL#9510] opened 2023-01-19 20:31 UTC
### Version

Microsoft Windows [Version 10.0.19045.2486]

### WSL Version

- [x ] WSL 2
- [] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #2311-Microsoft Tue Nov 08 17:09:00 PST 2022

### Distro Version

Ubuntu 22.04

### Other Software

![Screenshot (11)](https://user-images.githubusercontent.com/91756551/213552425-6cacbb00-a660-4323-8ded-2d9dbc5351c2.png)
 
When I am trying to change name of file IO.cpp to iO.cpp  I received 
mv : 'IO.cpp' and 'io.cpp' are the same file

### Repro Steps

the screen shot explain almost every thing 
![Screenshot (12)](https://user-images.githubusercontent.com/91756551/213553300-271ac953-94e1-4184-9308-b50fd61d3e5f.png)

### Expected Behavior

If mv in any  ubuntu terminal it will rename  the file

### Actual Behavior

![Screenshot (12)](https://user-images.githubusercontent.com/91756551/213553453-8dd144da-cfdc-4557-a802-34a9255c195c.png)

**Comment by cquick01** [comment] 2023-01-19 21:33
Check to make sure things are properly configured for case sensitivity - https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity

By default the Windows filesystem is not case-sensitive

**Comment by OneBlue** [comment] 2023-01-24 02:52
Indeed this folder is on the Windows drive, which is case insensitive by default.

Closing since this is the expected behavior.

**Closed by OneBlue** 2023-01-24 02:52 UTC
