### ISSUE TITLE
Error 0x800703fa while uninstall/install

### ISSUE THREAD

**Issue by danidomi** [Microsoft/WSL#3199] opened 2018-05-15 17:22 UTC
This are the steps for my issue:

1. Had installed the old 'Bash for Windows' which is deprecated since you need to install it using Windows Store, so I unistalled it using:

`>lxrun /uninstall /full`

Result:
`Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore

This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
Error: 0x800703fa`

2. Then since it failed I did the following, which also failed.

`>lxrun /uninstall`

3. Tried to remove manually the folder from Local

`C:\Users\${Username}\AppData\Local\lxss`

4. Now as before I can't install or unistall the folder and it looks like the problem is unable to remove the file:

`C:\Users\${Username}\AppData\Local\lxss\rootfs\usr\lib\x86_64-linux-gnu_dsa\liblinear.so.3.2.`

5. Now I don't have neither the new or older version, which is very very sad

**Comment by DarthSpock** [comment] 2018-05-15 17:27
I would say restart the LXSS service but if anything in the LXSS folder has been deleted, you most likely broke the service and will have to restore from backup or clean install Windows if no backups exist.

**Comment by danidomi** [comment] 2018-05-15 18:01
One more thing does this affect while trying to install from 'Windows Store'`, since when I try to do it this page gets reloaded when clicking "GET" button.

![image](https://user-images.githubusercontent.com/4473684/40074760-d0c2f276-587a-11e8-98ba-4681f166542f.png)

**Comment by DarthSpock** [comment] 2018-05-15 18:07
Try reinstalling the WSL feature and after reboot, wait a few minutes for LXSS to start. You can verify it in services.msc. If it hasn't started, manually start it. Then do your lxrun /uninstall /full. In order to intall the Store version, the old one will need to be removed.

Also your issue is a dupe. Ref: #2576

**Comment by onomatopellan** [comment] 2018-05-15 18:15
@danidomi I also had this problem. You need to close your user session inside the Store App and log in again with the same user name.

**Comment by danidomi** [comment] 2018-05-15 18:15
I actually saw that issue, but I don't think it's the same since when I try to run bash it gives me the following:

![image](https://user-images.githubusercontent.com/4473684/40075450-9ad54d10-587c-11e8-9b09-9c1a640b8d9f.png)

Can you please retell me the steps?

And you saw the issue with the liblinear.so.3.2. not being located in the folder but can't still delete it.

**Comment by danidomi** [comment] 2018-05-15 18:19
@onomatopellan that did the trick!

And now I have different issue, not sure if it makes sense in this issue or not?

![image](https://user-images.githubusercontent.com/4473684/40075726-5598d9c8-587d-11e8-9877-dd43780e1e86.png)





Installing, this may take a few minutes...
Installation Failed!
Error: 0x8000000d
Press any key to continue...

**Comment by DarthSpock** [comment] 2018-05-15 18:26
Great to hear the Store fix worked for that  "Get" not working though you do need to kill your lxrun installation before you can install. Also this is a different issue than the one you opened up and will be a dupe as well but don't have the issue numbers handy

**Comment by danidomi** [comment] 2018-05-16 17:12
After having all (ubuntu, openSuse and debian) running. I restarted the pc and today when trying to launch it I get

![image](https://user-images.githubusercontent.com/4473684/40132463-24ae152e-593d-11e8-816a-66a9b8826a94.png)

**Comment by DarthSpock** [comment] 2018-05-16 17:25
Restart the LXSSManager service or wait a few minutes after reboot and see if it starts on it's own.

**Comment by benhillis** [comment] 2018-05-17 16:29
Markign as duplicate of #2576.

**Closed by benhillis** 2018-05-17 16:29 UTC
