### ISSUE TITLE
Shutting down WSL instance

### ISSUE THREAD

**Issue by alekseymvt** [Microsoft/WSL#3253] opened 2018-05-28 08:43 UTC
Windows 1803/17134. Ubuntu 18.04 from windows store.

Run -> cmd -> wsl.
sudo service nginx start; (nginx/mysql, ...)
exit;
close cmd

Task manager: nginx working, mysql working, ...
Sorry, can not find the answer: How to shutdown WSL?

**Comment by therealkenc** [comment] 2018-05-28 11:09
Sadly there isn't an official one; that I am aware of anyway (I got chirping crickets when I [asked](https://github.com/Microsoft/WSL/issues/709#issuecomment-346923555), natch). This is technically dupe of three digit #200. Ref #2533 (which was framed badly).

You can kill the `init` process of the running WSL instance (there can be more than one instance) with the Windows task manager, per #2496. You'll have to guess which process named `init` is the right one because WSL's `init` is also WSL's spiritual `getty`, so there are multiple `init` processes per instance. In general pick the lowest number. It is tempting to use the magic of interop somehow, but that is problematic per #3174. 

At base I suspect this has been punted because `shutdown(8)` isn't as straightforward as in Ye Olden Tymes, and we don't have `systemd`. Landing zone for that is #994.

**Comment by therealkenc** [comment] 2018-05-30 05:13
> isn't as straightforward as in Ye Olden Tymes

Couple of days later it occurs to me that maybe this doesn't have to be a federal case. Perhaps it would be reasonable as an interim measure if "`sudo /init 0`" behaved like it was in fact [still Ye Olden Tymes](https://github.com/freebsd/freebsd/blob/master/sbin/init/init.c#L216). `/init 0` sends a `SIGUSR2` to PID 1. Catch `SIGUSR2` in `/init` on `PID 1`, and then just die peacefully. Or in the shortest terms possible, "`sudo kill -12 1`" shuts down the WSL instance by fiat. Concrete proposal, anyway. Doable without worming. Beats nuking it with procmon.

**Comment by Line117** [comment] 2018-05-31 15:37
I understood that I didn't understand anything.
I'll wait until you come up with something. :)

**Comment by PhMajerus** [comment] 2018-06-11 16:11
net.exe stop LxssManager will terminate all running instances.
It probably doesn't send the proper shutdown messages, but probably cleaner than killing the init processes.

**Comment by benhillis** [comment] 2018-06-11 16:14
I have added an option to wslconfig (wslconfig.exe /terminate <DistroName>) to shut down a distribution from the command line.  This change is making its way to Insider builds.

**Comment by Biswa96** [comment] 2018-06-11 16:31
Ooooo.... New option like `/upgrade`? Which insider build?

BTW, if someone move or rename the `wslhost.exe`  then `wsl.exe` can not start it with `CreateProcess()`. Consequently the background Lx process will close after closing console window.

**Comment by therealkenc** [comment] 2018-06-11 23:04
> wslconfig.exe /terminate

Beggars can't be choosers, so 👍. But doing it on that side means you can't make a Bash `alias` for `shutdown` to `wslconfig.exe /terminate`, because a running WSL instance doesn't know the name of it's distribution per #2578 ([message](https://github.com/Microsoft/WSL/issues/2578#issuecomment-353856398)). 

Turns out old-school shutdown is supported by [`systemd`](https://manpages.debian.org/stretch/systemd-sysv/init.1.en.html) to this day after all. In a Real Linux VM:
```
$ sudo kill -SIGRTMIN+4 1
```
Who knew. Seems like a reasonable ask. Or something.

**Comment by eode** [comment] 2018-06-13 23:02
So, I've seen a lot of talk regarding Windows/Linux interop.  As far as init goes:

Couldn't we just create an arbitrary folder -- let's say, `/etc/init_wsl.d` -- which just executes every script there, and pipes info into the stdin of that script about what's happening?  Could be JSON for all I care.

I.e., say we have these files:
```bash
/etc/init_wsl.d/50_site.sh
/etc/init_wsl.d/51_sshd.py
```
Each script is called in-order, and receives
```json
{
  "state": "starting up"
}
```
..on `stdin`.

Bonus, environment variable 'WSL_STATE` is set to 'starting up'.

Really, you could load it with whatever info you want.

Any major state changes, such as:
* user logging in
* user logging out
* system start
* system shutting down
* system rebooting

I figure you'd use the windows `/init`, and whenever it receives a signal from the system, it passes that on to the scripts.  End of story.  End of support in that area, for now.

This would allow users and distros to track system state changes, and write their own scripts for handling those events, and integrating them however they wish, and keeps the MS side comparatively simple.

**Comment by therealkenc** [comment] 2018-06-14 07:46
#2530.

**Comment by therealkenc** [comment] 2018-09-07 07:50
`wslconfig /terminate` made it into [17704](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17704). `shutdown(8)` will have to fight another day.

**Closed by therealkenc** 2018-09-07 07:50 UTC
Labels: feature, fixinbound

**Comment by coyotte508** [comment] 2020-10-27 07:57
By the way, now it's just `wsl -t <distribution>`

**Comment by lleeoo** [comment] 2021-04-29 06:28
> By the way, now it's just `wsl -t <distribution>`

Is that a clean shutdown? I.e., are processes given enough time to shutdown?

**Comment by therealkenc** [comment] 2021-04-29 18:21
No it is a big red switch. Per [above](https://github.com/microsoft/WSL/issues/3253#issuecomment-419354342), `shutdown(8)` will have to fight another day.
