### ISSUE TITLE
Behavior of MSG_OOB on WSL2 is different from that in Linux

### ISSUE THREAD

**Issue by datatellstruth** [microsoft/WSL#10369] opened 2023-08-06 12:35 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.1992]

### WSL Version

WSL 版本： 1.2.5.0 内核版本： 5.15.90.1 WSLg 版本： 1.0.51 MSRDC 版本： 1.2.3770 Direct3D 版本： 1.608.2-61064218 DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows 版本： 10.0.22621.1992

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Ubuntu 22.04

### Repro Steps

I tried to use `MSG_OOB` in WSL, and found the behavior of the program in WSL is different from that in Linux. The program `oob_recv.c` is as follows:
```c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <bits/sigaction.h>

#define BUF_SIZE 30
void error_handling(char *message);
void urg_handler(int signo);

int acpt_sock;
int recv_sock;

int main(int argc, char *argv[])
{
    struct sockaddr_in recv_adr, serv_adr;
    int str_len, state;
    socklen_t serv_adr_sz;
    struct sigaction act;
    char buf[BUF_SIZE];

    if (argc != 2)
    {
        printf("Usage : %s <port>\n", argv[0]);
        exit(1);
    }

    act.sa_handler = urg_handler;
    sigemptyset(&act.sa_mask);
    act.sa_flags = 0;

    acpt_sock = socket(PF_INET, SOCK_STREAM, 0);
    memset(&recv_adr, 0, sizeof(recv_adr));
    recv_adr.sin_family = AF_INET;
    recv_adr.sin_addr.s_addr = htonl(INADDR_ANY);
    recv_adr.sin_port = htons(atoi(argv[1]));

    if (bind(acpt_sock, (struct sockaddr *)&recv_adr, sizeof(recv_adr)) == -1)
        error_handling("bind() error");
    listen(acpt_sock, 5);

    serv_adr_sz = sizeof(serv_adr);
    recv_sock = accept(acpt_sock, (struct sockaddr *)&serv_adr, &serv_adr_sz);

    fcntl(recv_sock, F_SETOWN, getpid());
    state = sigaction(SIGURG, &act, 0);

    while ((str_len = recv(recv_sock, buf, sizeof(buf), 0)) != 0)
    {
        if (str_len == -1)
            continue;
        buf[str_len] = 0;
        puts(buf);
    }
    close(recv_sock);
    close(acpt_sock);
    return 0;
}

void urg_handler(int signo)
{
    int str_len;
    char buf[BUF_SIZE];
    str_len = recv(recv_sock, buf, sizeof(buf) - 1, MSG_OOB);
    buf[str_len] = 0;
    printf("Urgent message: %s \n", buf);
}

void error_handling(char *message)
{
    fputs(message, stderr);
    fputc('\n', stderr);
    exit(1);
}
```

The program `oob_send.c` is as follows:
```c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#define BUF_SIZE 30
void error_handling(char *message);

int main(int argc, char *argv[])
{
    int sock;
    struct sockaddr_in recv_adr;

    if (argc != 3)
    {
        printf("Usage : %s <IP> <port>\n", argv[0]);
        exit(1);
    }

    sock = socket(PF_INET, SOCK_STREAM, 0);
    memset(&recv_adr, 0, sizeof(recv_adr));
    recv_adr.sin_family = AF_INET;
    recv_adr.sin_addr.s_addr = inet_addr(argv[1]);
    recv_adr.sin_port = htons(atoi(argv[2]));

    if (connect(sock, (struct sockaddr *)&recv_adr, sizeof(recv_adr)) == -1)
        error_handling("connect() error!");

    write(sock, "123", strlen("123"));
    send(sock, "4", strlen("4"), MSG_OOB);
    write(sock, "567", strlen("567"));
    send(sock, "890", strlen("890"), MSG_OOB);
    close(sock);
    return 0;
}

void error_handling(char *message)
{
    fputs(message, stderr);
    fputc('\n', stderr);
    exit(1);
}
```

Use the following commands to compile them:
```shell
$ gcc oob_send,c -o oob_send
$ gcc oob_recv.c -o oob_recv
```

Then, run the programs using the following command on WSL:
```shell
$ ./oob_recv 2000
$ ./oob_send 127.0.0.1 2000
```
The output of program `oob_recv` is as follows in WSL:
```shell
$ ./oob_recv 2000
123456789
```

However, the output should to be:
```shell
$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
```
in a real Linux system.

### Expected Behavior

```shell
$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
```

### Actual Behavior

```shell
$ ./oob_recv 2000
123456789
```

**Comment by OneBlue** [comment] 2023-08-08 21:29
Thank you for reporting this @datatellstruth. What you're seeing is the expected behavior. 

Unlike UDP, TCP doesn't have a notion of 'packets' so whenever you read from a TCP socket, you'll read all the available data, so both of the outputs you shared are reasonable, based on timing. 

Closing since this is by design.

**Comment by OneBlue** [comment] 2023-08-08 21:41
Disregard my previous message, I didn't notice the MSG_OOBE logic here. Can you share an strace of both the working scenario and the not working one ? (both on the sender and receiver sides)

**Comment by elsaco** [comment] 2023-08-09 20:22
@datatellstruth the output is inconsistent when testing on a non-WSL distro, Ubuntu 22.10 on a Raspberry Pi 4 were used:

```
tux@raspi:~/Test$ ./oob_recv 2000
Urgent message: 0
Urgent message: 0
123
56789
tux@raspi:~/Test$ ./oob_recv 2000
Urgent message: 0
12356789
tux@raspi:~/Test$ ./oob_recv 2000
Urgent message: 0
Urgent message: 0
123
56789
tux@raspi:~/Test$ ./oob_recv 2000
Urgent message: 0
123
56789
tux@raspi:~/Test$ ./oob_recv 2000
Urgent message: 0
Urgent message: 0
123
56789
```

No changes were made to your code.

**Comment by datatellstruth** [comment] 2023-08-11 11:53
> Disregard my previous message, I didn't notice the MSG_OOBE logic here. Can you share an strace of both the working scenario and the not working one ? (both on the sender and receiver sides)

Hi, thanks for your reply. I am not sure what's the explicit meaning of `the working scenario and the not working one` in your comments. I ran the code in WSL2 and Ubuntu system and got different results, and the Ubuntu system (which is a machine privoded by cloud vendor) detail is as follows:
```shell
$ cat /proc/version
Linux version 5.15.0-56-generic (buildd@lcy02-amd64-004) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
```

In addition, as @elsaco shows(in [comments](https://github.com/microsoft/WSL/issues/10369#issuecomment-1672094877)), the behavior of the program may be different during different runs. And I ran the program again in 3 systems. The behavior in WSL is as follows:
```shell
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123456789
```
And the behavior of the program in a cloud machine(which is the same machine in the issue detail) is as follows:
```shell
arcsin2@VM-0-14-ubuntu:~/code/net_program$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
arcsin2@VM-0-14-ubuntu:~/code/net_program$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
arcsin2@VM-0-14-ubuntu:~/code/net_program$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
arcsin2@VM-0-14-ubuntu:~/code/net_program$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
arcsin2@VM-0-14-ubuntu:~/code/net_program$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
arcsin2@VM-0-14-ubuntu:~/code/net_program$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
```

Lastly, the behavior of the program in Ubuntu 22.04 Desktop Version is as follows:
```shell
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
Urgent message: 4 
Urgent message: 0 
123
56789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
Urgent message: 0 
12356789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
Urgent message: 4 
Urgent message: 0 
123
56789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
123456789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
Urgent message: 0 
123
56789
(base) arcsin2@linux:~/code/network$ ./oob_recv 2000
Urgent message: 4 
Urgent message: 0 
123
56789
```

It seems that the program might produce different results, so the behavior in WSL is legal too. But I am not sure whether it is correct, since I am a beginner in network program and got this problem while reading a book and ran the demo code. Maybe the TCP RFC documents is the places to find the right answer.

**Comment by datatellstruth** [comment] 2023-08-11 12:20
I change the code of the `send side` by adding the `sleep` function between the `send` or `write` function call. The modifed code of `oob_recv.c` is as follows:
```c
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#define BUF_SIZE 30
void error_handling(char *message);

int main(int argc, char *argv[])
{
    int sock;
    struct sockaddr_in recv_adr;

    if (argc != 3)
    {
        printf("Usage : %s <IP> <port>\n", argv[0]);
        exit(1);
    }

    sock = socket(PF_INET, SOCK_STREAM, 0);
    memset(&recv_adr, 0, sizeof(recv_adr));
    recv_adr.sin_family = AF_INET;
    recv_adr.sin_addr.s_addr = inet_addr(argv[1]);
    recv_adr.sin_port = htons(atoi(argv[2]));

    if (connect(sock, (struct sockaddr *)&recv_adr, sizeof(recv_adr)) == -1)
        error_handling("connect() error!");

    write(sock, "123", strlen("123"));
    sleep(1);
    send(sock, "4", strlen("4"), MSG_OOB);
    sleep(1);
    write(sock, "567", strlen("567"));
    sleep(1);
    send(sock, "890", strlen("890"), MSG_OOB);
    close(sock);
    return 0;
}

void error_handling(char *message)
{
    fputs(message, stderr);
    fputc('\n', stderr);
    exit(1);
}
```

The `recv side` is the same as original. Then, I re-ran the code, the behavior of the program is the same in WSL and other Linux systems, i.e.,
```shell
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
arcsin2@arcsin2-pc:~/code/network_program_tuorial/Chapter13 source$ ./oob_recv 2000
123
Urgent message: 4 
567
Urgent message: 0 
89
```

The `sleep` function guarantee the TCP segment arrive at the receive side in order and the random factors is removed, so the behavior of the program is consistent in different systems and different runs.

However, as to why WSL always got the output of `123456789`, which is different from both the random beavior in Ubuntu 22.04 Desktop Version and the expected behavior in the cloud machine, maybe it is still a problem. Hope this can help you locate and solve the real problem, thanks a lot. @OneBlue @elsaco

**Closed** 2023-08-22 21:51 UTC
Labels: needs-author-feedback
