### ISSUE TITLE
On DrvFs (D:) mount the access rights are wrong at first and then right

### ISSUE THREAD

**Issue by gaborauth** [microsoft/WSL#4563] opened 2019-10-03 06:42 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18990.1]
Build 18990.vb_release.190921-1704

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

1, Created a new Ubuntu 18.04
2, Started it
3, Try to access my files on D: drive

![image](https://user-images.githubusercontent.com/16724720/66104450-ea59af00-e5b8-11e9-882d-ba3135392241.png)

* What's wrong / what should be happening instead:

I want right access rights for the first time too.

**Comment by Biswa96** [comment] 2019-10-03 07:24
You can configure the default mounting options by editing `/etc/wsl.conf` file. See this blog post here [Automatically Configuring WSL](https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/).

**Comment by gaborauth** [comment] 2019-10-03 07:49
> You can configure the default mounting options by editing `/etc/wsl.conf` file.

I know but it is not related to default mounting options.

The first access of directory/file is wrong, check the `----------' access right on the `zanata.xml` at the first list and the `-rwxrwxrwx` access right on the second list.

**Comment by 0xbadfca11** [comment] 2019-10-03 13:26
Duplicate of #4116 ?

**Comment by gaborauth** [comment] 2019-10-03 15:07
> Duplicate of #4116 ?

Most likely, yes.

**Closed** 2019-10-03 16:20 UTC
Labels: duplicate
