### ISSUE TITLE
per directory case sensitivity breaks Windows builds

### ISSUE THREAD

**Issue by raymod2** [Microsoft/WSL#3328] opened 2018-06-26 17:17 UTC
I upgraded to the latest Windows version (April 2018 Update) and I discovered that my builds are no longer working.  I tracked it down to a case sensitivity issue caused by a new feature described here:

https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/

In my workflow I clone a git repository using WSL into /mnt/c/git.  I perform all development activities in WSL (git actions, file editing, file comparisons, grepping, etc.).  I build the project, however, using a batch file which of course launches a regular Windows cmd.exe process.

The problem is that this new case-sensitive flag is getting set on all directories I create from WSL.  This causes Windows programs to fail when working with files in these directories.  For instance, I use several different Windows compilers and most of them mangle pathnames at some point (making them all uppercase or all lowercase).  With the case sensitive directory flag set these compilers can't find the files in the mangled paths.

The blog I linked above describes how to prevent this new flag from getting set using "options = case=off" in the [automount] section of /etc/wsl.conf.  However, this option also disables case sensitivity inside WSL.  There appears to be no way to restore the old WSL behavior.

This is a mess.  I think the default behavior should be reconsidered because it breaks so many Windows compilers.  And I think there should be a way to restore the old WSL behavior.

**Comment by onomatopellan** [comment] 2018-06-26 20:08
Duplicate of #2937 
Case sensitivity is a work in progress explained in  
https://blogs.msdn.microsoft.com/commandline/2018/06/14/improved-per-directory-case-sensitivity-support-in-wsl/

**Closed** 2018-06-29 01:50 UTC
