### ISSUE TITLE
Robot os no longer working on insider build

### ISSUE THREAD

**Issue by rowanG077** [Microsoft/WSL#2560] opened 2017-10-11 15:09 UTC
Robot OS on WSL was working for me on the stable windows version. 

Microsoft Windows [Version 10.0.15063]

Today I upgraded to windows insider and now the publish subscribe system is no longer working.

My current windows version:

Microsoft Windows [Version 10.0.16299.15]

roswtf errors with the message The following nodes should be connected but aren't.

The output was recorded while running one of the examples. In the following order:

1. Terminal was running roscore.
2. One terminal was running the command: "rosrun turtlesim turtlesim_node". This succesfully launches a window with a turtle in it.
3. The last terminal was running the command "rosrun turtlesim turtle_teleop_key". This launches the app succesfully but no matter what keys are pressed nothing happens.

An interesting thing to note is that running turtle_teleop_key and once that is started running turtlesim_node will work. I can then move the turtle using the keys.

Calling the clear service works in the later case also but I can't verify in the failing case.

Here is the roswtf output for the first case.

```
Loaded plugin tf.tfwtf
No package or stack in context
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules

Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following nodes are unexpectedly connected:
 * unknown (http://DESKTOP-5KR77SI:50230/)->/rosout (/rosout)


Found 1 error(s).

ERROR The following nodes should be connected but aren't:
 * /teleop_turtle->/turtlesim (/turtle1/cmd_vel)
 * /teleop_turtle->/rosout (/rosout)
 * /turtlesim->/rosout (/rosout)
```

and the second working case:

```
Loaded plugin tf.tfwtf
No package or stack in context
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules

Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following nodes are unexpectedly connected:
 * unknown (http://DESKTOP-5KR77SI:50230/)->/rosout (/rosout)


Found 1 error(s).

ERROR The following nodes should be connected but aren't:
 * /teleop_turtle->/rosout (/rosout)
 * /turtlesim->/rosout (/rosout)
```

I can attach strace files if necessary but since this there was allready specific work on ros as I can tell from this issue: https://github.com/Microsoft/BashOnWindows/issues/1450 I don't think it is necessary. They are rather large...

Roscore output:

```
... logging to /root/.ros/log/3533c16a-ae92-11e7-bd23-bc8385db5709/roslaunch-DESKTOP-5KR77SI-12375.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://DESKTOP-5KR77SI:50203/
ros_comm version 1.13.2


SUMMARY
========

PARAMETERS
 * /rosdistro: lunar
 * /rosversion: 1.13.2

NODES

auto-starting new master
process[master]: started with pid [12386]
ROS_MASTER_URI=http://DESKTOP-5KR77SI:11311/

setting /run_id to 3533c16a-ae92-11e7-bd23-bc8385db5709
process[rosout-1]: started with pid [12399]
started core service [/rosout]
```

**Comment by Yay295** [comment] 2017-10-18 22:54
I can confirm this issue. I also checked ROS's log file and there are no errors listed there. However, I had a different issue with ROS before the update that I was able to solve by changing the function

```
def close_half_closed_sockets():
    for proxy in _proxies.values():
        transport = proxy("transport")
        if transport._connection and transport._connection[1] is not None and transport._connection[1].sock is not None:
            state = transport._connection[1].sock.getsockopt(socket.SOL_TCP, socket.TCP_INFO)
            if state == 8:  # CLOSE_WAIT
                transport.close()
```

in `/opt/ros/lunar/lib/python2.7/dist-packages/rosmaster/util.py` to immediately return, and that solved this issue for me as well. I found this solution because the other error I had *did* show up in the log file, so I was able to track the cause. The specific line that causes the issue is `...getsockopt(socket.SOL_TCP, socket.TCP_INFO)`, which previously failed with an error. I'm guessing this option has been stubbed out (though I don't see it in the logs) so it doesn't error now, but it still doesn't work.

**Comment by sunilmut** [comment] 2017-10-30 18:58
@Yay295 - What did you stub to get this work? Do you know the root cause? From your post above, it doesn't sound like `TCP_INFO` was causing the failure.

**Comment by Yay295** [comment] 2017-10-30 21:00
I think I may have been looking in the wrong place before, because I have found the error message now.

Using ROS Lunar version 1.13.2 and the steps in the original post I found this

```
[rosmaster.threadpool][ERROR] 2017-10-30 14:35:11,066: Traceback (most recent call last):
  File "/opt/ros/lunar/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/lunar/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/opt/ros/lunar/lib/python2.7/dist-packages/rosmaster/util.py", line 67, in xmlrpcapi
    close_half_closed_sockets()
  File "/opt/ros/lunar/lib/python2.7/dist-packages/rosmaster/util.py", line 76, in close_half_closed_sockets
    state = transport._connection[1].sock.getsockopt(socket.SOL_TCP, socket.TCP_INFO)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available
```

in `/.ros/log/latest/master.log`.

**Comment by sunilmut** [comment] 2017-10-30 22:01
@Yay295 - Great, thanks. Are you able to stub out the call to getsockopt(TCP_INFO) and see if that resolves the issue? Not suggesting that for proper fix, but, just for information. If so, then we can definitely mark this dupe of #1982. Also, `TCP_INFO` is our backlog.

**Comment by Yay295** [comment] 2017-10-31 03:04
No, `getsockopt` is a read-only method on Python's built-in `socket` class. This does seem like a duplicate of that issue though.

**Closed** 2017-11-29 05:52 UTC
Labels: duplicate
