### ISSUE TITLE
fish shell crashing with partial command entered

### ISSUE THREAD

**Issue by CrshOverride** [microsoft/WSL#2524] opened 2017-09-26 14:49 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.16296.0]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Opened a new shell, pulled recent GitHub changes for a source repo, and then started typing `node` at which point `fish` crashed:

![image](https://user-images.githubusercontent.com/791698/30866740-188e7ef6-a2a8-11e7-9b6d-16fbcdbb8cf4.png)

The text of the error is:

```
nod<E> fish: src/common.cpp:1810: failed assertion: pthread_mutex_unlock(lock_obj): errno 1 (Operation not permitted)
<E> fish: Backtrace:
<E> fish: 0   scoped_lock::unlock() + 81
<E> fish: 1   function_exists_no_autoload(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, env_vars_snapshot_t const&) + 119
<E> fish: 2   highlighter_t::highlight() + 1588
<E> fish: 3   highlight_shell(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::vector<unsigned int, std::allocator<unsigned int> >&, unsigned long, std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > >*, env_vars_snapshot_t const&) + 300
<E> fish: 4   fish() [0x4c0026]
<E> fish: 5   std::_Function_handler<void (), int _iothread_trampoline<highlight_result_t>::perform<std::function<highlight_result_t ()>, void (*)(highlight_result_t)>(std::function<highlight_result_t ()> const&, void (* const&)(highlight_result_t))::{lambda()#1}>::_M_invoke(std::_Any_data const&) + 45
<E> fish: 6   fish() [0x49d5fb]
<E> fish: 7   /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f68123a76ba]
<E> fish: 8   clone + 109
```

* What's wrong / what should be happening instead:

Obviously `fish` shouldn't be crashing here.

**Comment by shevegen** [comment] 2017-09-26 23:43
Hmm... there was another, probably unrelated issue with fish. I am beginning to wonder if these errors are also fish-related; I can't recall that many errors related to zsh or bash yet here. No idea whether the problem is within fish itself at pthread_mutex_unlock() or related to the windows interface. Perhaps someone at windows can give the fish shell a try though, it's a nice shell with some interesting ideas (imo); though I myself use bash, mostly due to laziness and having used it for so many years...

**Comment by therealkenc** [comment] 2017-09-27 05:32
The interesting thing with this one is it isn't in `fish`, it's in `libstdc++`. It is _possible_ `fish` is using C++11 [`scoped_lock` ](http://en.cppreference.com/w/cpp/thread/scoped_lock) unusually or even improperly, but unless there is screeching from Real Linux™ users that's less likely. More likely `fish` recently started using `scoped_lock`, or `stdlibc++` evolved and surfaced the bug. Or there's a WSL regression. It would be nice if someone still on Creators could give it a try (I don't have Creators handy).

An `strace -ff fish 2> fish.strace` (from bash) is a good place to start. But that's a library `assert`, which might or might not be due to a hard syscall fail. More likely it's a behavioural problem, along the lines of the [pthread fails](https://github.com/Microsoft/BashOnWindows/issues/2031#issuecomment-315235409) in the glibc tests. This is probably going to be a tough one, because [`futex(2)`](http://man7.org/linux/man-pages/man2/futex.2.html) "works", as far as it goes; otherwise the whole edifice would be falling down, not just a given bleeding-edge release of `fish`.

**Comment by CrshOverride** [comment] 2017-09-27 14:11
@therealkenc I can verify that I've been using this version of `fish` on both OSX and Linux and this has never happened there.

**Comment by therealkenc** [comment] 2021-05-05 21:38
> failed assertion: pthread_mutex_unlock(lock_obj): errno 1 (Operation not permitted)

Whatever the unknown  problem with `scoped_lock()` on WSL1, it will be better with WSL2. Lots of people use `fish` and there wasn't much uptake on the fail. If anyone repro steps to manifest the error (contrast 'started typing node at which point fish crashed') for WSL1 I'll take a look at the `strace` for the academic value. It might even have been addressed in WSL1 along the way.

**Closed by therealkenc** 2021-05-05 21:38 UTC
