### ISSUE TITLE
No GUI or icon in WSL under Windows 10

### ISSUE THREAD

**Issue by venik212** [microsoft/WSL#4880] opened 2020-02-09 21:24 UTC
I followed the step-by-step guide provided by MS to install WSL and Ubuntu under Windows 10.  I got no errors, but in the end, there was no Ubuntu visible in the Start menu or pinned to the Start menu (I pinned it.. ;-).  I can run Ubuntu 18.04 LTS in the terminal, but that's it.  Trying to install WSL 2 ran into the fact that there is no wsl command.  After you install it, it does not  provide the version information you need to proceed with the wsl 2 installation.  In short-- very frustrating.

**Comment by craigloewen-msft** [comment] 2020-02-10 19:31
Could you help provide a bit more context? When you say: 'After you install it, it does not provide the version information you need to proceed with the WSL2 installation' do you mean after you install base WSL it should give you info on how to start installing WSL2?

Also, our WSL2 install docs are here that will help you in the meantime: https://docs.microsoft.com/windows/wsl/wsl2-install

**Comment by venik212** [comment] 2020-02-10 19:50
Thanks for the response, Craig.  I appreciate it.  I eventually got the response that what I have is Version 1, but using the guide you provided (which I had consulted before I got your email), and trying to install WSL 2, did not seem to work-- the wsl --list --verbose still produced the same response as before: Ubuntu-18.04 version 1.
    I am doing this on a Lenovo Yoga 2 Pro running Windows 10 with a build 190.. (not sure of the exact number-- it is not in front of me.), which I got by registering as a Windows Insider.
   Perhaps I should mention that I have been using mostly Linux for the past 12 years or so, and was delighted to learn of Microsoft's efforts towards moving Windows, even so slightly and at a glacial pace, in that direction.  Keep it up!
Yours,
Venik212


________________________________

**Comment by craigloewen-msft** [comment] 2020-02-10 20:11
Since your `wsl --list --verbose` command works, I'll surmise your on the right build. It seems like you just need to run `wsl --set-version Ubuntu-18.04 2` to get your distro converted over to start using WSL2.

**Comment by venik212** [comment] 2020-02-10 23:44
OK-- by enabling virtualization in the BIOS I finally got it to recognize Ubuntu as Version 2.  I still don't have an icon for Ubuntu anywhere, although I clicked on Pinto Start, but that is minor.
Thanks for your help!

________________________________

**Comment by craigloewen-msft** [comment] 2020-02-11 01:00
Glad to help! I'd double check in your start menu that you've pinned the correct app, but it sounds like the root cause for this issue has been resolved. I'll close it out for our bookkeeping, but please ping it again or reopen if you think the issue persists. Thank you!

**Closed by craigloewen-msft** 2020-02-11 01:00 UTC
Labels: documentation, question

**Comment by mensylisir** [comment] 2021-02-07 12:29
> Glad to help! I'd double check in your start menu that you've pinned the correct app, but it sounds like the root cause for this issue has been resolved. I'll close it out for our bookkeeping, but please ping it again or reopen if you think the issue persists. Thank you!

HI, could you tell us when the version related to GUI will be released
