### ISSUE TITLE
League of Legends will drop frames if wsl2 is enabled unless the 'AntiCheatExpert Service' is turned off during the game.

### ISSUE THREAD

**Issue by janelu9** [microsoft/WSL#10992] opened 2024-01-07 12:01 UTC
It only happends when I install system from the latest Windows ISO image after 2023.5.  If I install my system from the older ISO, it works well.
My system :  
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2861

**Comment by janelu9** [comment] 2024-01-31 02:57
I found it may be related to NVIDIA's GeForce Experience

**Comment by OneBlue** [comment] 2024-04-18 20:27
Closing since this is most likely caused by a third party service.

**Closed by OneBlue** 2024-04-18 20:27 UTC
Labels: feature
