### ISSUE TITLE
Could not mapping path \\wsl$\<distro_name> to network drive

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#3854] opened 2019-02-16 06:21 UTC
* Your Windows build number:
Microsoft Windows [Version 10.0.18836.1000]

* What you're doing and what's happening:
In command prompt, could not pushd under ``\\wsl$\``.
Other file I/O or application can access under ``\\wsl$\``.
I tried "Fresh Start" from Windows Defender app. But this did not solve it.
```cmd
C:\Users\JohnDoe>pushd \\wsl$\Ubuntu\home\john
The network path was not found.
```
![image](https://user-images.githubusercontent.com/7390559/52895175-1545ed00-31fa-11e9-9a51-77967408da6d.png)

* What's wrong / what should be happening instead:
pushd does change current directory under ``\\wsl$\``.
like [this tweet](https://twitter.com/craigaloewen/status/1096523686461337600).
```cmd
C:\Users\JohnDoe>pushd \\wsl$\Ubuntu\home\john

Z:\home\john>
```

* Strace of the failing command, if applicable:
N/A

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
[lxcore.zip](https://github.com/Microsoft/WSL/files/2871658/lxcore.zip)

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by ziggythehamster** [comment] 2019-02-16 07:49
CMD.exe does not support UNC paths consistently. Use PowerShell.

**Comment by benhillis** [comment] 2019-02-19 16:49
@0xbadfca11 - This should work, although there are some more changes inbound to the prerelease branch.  Can you verify that the distribution is already running when you try this?

**Comment by 0xbadfca11** [comment] 2019-02-20 02:09
@benhillis I definitely opened and have not stopped Ubuntu.

**Comment by jstarks** [comment] 2019-02-20 21:28
This was a known issue. I believe net use and pushd will be fixed in a subsequent build.

**Comment by benhillis** [comment] 2019-02-20 22:26
This should work in the 18342 19h1_release.  The fix is making its way to the rs_prerelease branch and should be there soon.

**Comment by 0xbadfca11** [comment] 2019-02-21 07:08
In build 18342, Mostly works expected.
However, found one function that is not working properly.
Right click ``\\wsl$\<distro_name>``, then ``Map network drive...``.
"Folder" field will be ``<distro_name>``, missing ``\\wsl$\``.
I will get "Error code: 0x80070043 The network name cannot be found."
![image](https://user-images.githubusercontent.com/7390559/53148820-3ee28800-35ef-11e9-95f5-5bba34b7d8a2.png)
![image](https://user-images.githubusercontent.com/7390559/53148824-430ea580-35ef-11e9-8a54-00258559df65.png)

**Comment by Biswa96** [comment] 2019-02-27 20:34
> verify that the distribution is already running

@benhillis `Distros.lnk` can show all the distributions if I do a patch in p9np.dll. Should not Windows/WSL check the integrity of 9P components?

**Comment by 0xbadfca11** [comment] 2019-03-28 10:45
Fixed in 18865 (Skip Ahead).

**Comment by Biswa96** [comment] 2019-03-28 15:16
@0xbadfca11 That was fixed in 18860 build. BTW, does Explorer shows correct size of that drive? In my case, Explorer shows the 'Used Space' of the actual drive instead of my distribution installed size. Is it by-design?

**Comment by Biswa96** [comment] 2019-03-28 15:21
@0xbadfca11 That was fixed in 18860 build. BTW, does Explorer shows correct size of that drive? In my case, Explorer shows the 'Used Space' of the actual drive instead of my distribution installed size. Is it by-design? Another thing, `init` process remains after disconnecting that drive.

**Comment by jstarks** [comment] 2019-03-28 15:34
This is by design--we don't track the amount of space the distro is using.

The init process will timeout after a while, or you can terminate it manually with `wsl -t <distro name>`.

**Closed** 2019-04-11 12:38 UTC
Labels: bug

**Comment by LiamKarlMitchell** [comment] 2020-05-20 09:26
Also just a note, unable to map a directory in the distro to a drive but can map the distro share.
Can't mount \\wsl$\Ubuntu-20.04\home\ubuntu
But can mount \\wsl$\Ubuntu-20.04

Possibly by design.

**Comment by BeomohKim** [comment] 2023-03-21 08:03
I'm suffering the same phenomenon.
with Microsoft Windows [Version 10.0.19042.2364]

**Comment by getify** [comment] 2023-03-22 21:47
Someone should definitely pin [this message](https://github.com/microsoft/WSL/issues/3854#issuecomment-631356968) from @LiamKarlMitchell as it's probably the main reason people see this error now. You can only map a drive to a WSL root, not to any arbitrary dir inside that file system.
