### ISSUE TITLE
Only one port can be accessed by the host through localhost at the same time

### ISSUE THREAD

**Issue by ZeddG93** [microsoft/WSL#4769] opened 2019-12-17 12:00 UTC
Windows build number:  10.0.19536.1000

Steps to reproduce:

1. Listen on port A via`nc -l <PortA>`.
2. The browser accesses `http://localhost:PortA`, and the console can output the browser request body.
3. Listen on port B via `nc -l <PortB>`.
4. When the browser accesses `http://localhost:PortB`, the error ERR_CONNECTION_REFUSED directly appears.
5. Shut down wsl2 through the `wsl.exe --shutdown` command, repeat the test in the order of 3, 4, 1, 2, and the result is that PortB can receive the packet, and PortA has an error ERR_CONNECTION_REFUSED.

Another reproduction method:

Using vscode's wsl-remote plug-in, it can be started correctly through the `code .` command for the first time. After closing vscode and using the command to open it again, the file under wsl cannot be displayed and an error message is displayed.

**Comment by BabyDino** [comment] 2019-12-17 12:50
I think I'm running into this issue as well. I've just upgraded to 19536 and can't use vscode and my localhost:3000 app at the same time.

**Comment by ad-on-is** [comment] 2019-12-17 15:06
I have exactly the same issue:

1. Opening a Remote WSL instance in VSCode (works)
2. Run `vue ui`
3. `localhost:8000` gives error ERR_CONNECTION_REFUSED 

After `wsl --shutdown`

1. Run `vue ui`
2.  `localhost:8000` works
3. Open a Remote WSL instance in VSCode gives error
![image](https://user-images.githubusercontent.com/9553253/71007354-23e58500-20e7-11ea-8503-85fbc08a4c90.png)

**Comment by wlbrough** [comment] 2019-12-17 17:35
Similar issue to previous comments, but slightly different error path.

Windows 10 Pro Insider Preview Build 19536.rs_prerelease.191211-1446

1. Open a Remote WSL instance.
2. Start node server *on* WSL (running in a Docker container for an additional complication 🙂 )
3. Cannot access the server at `localhost:3000`, which was working prior to Windows update.

**Comment by prsnnami** [comment] 2019-12-18 15:17
Same issue, multiple connections to localhost doesn't work after the update 19536.1000

Issue Identical to @ad-on-is 's comment. 

Don't know much about WSL's network arch to debug further.

**Comment by berwyn** [comment] 2019-12-18 18:49
I have noticed that this is infinitely more flakey than just one port being available. 

- I have Docker on my machine setup with WSL2 as its backend. I can run as many containers as I like on Docker and all the ports there get correctly exposed to the host.
- With Ubuntu, however, only the first opened port ever gets exposed to the host, and even that never works if the process dies and then I try to re-bind that port (a good example being VS Code -- if I have to re-open the window, the port won't bind).
- Lastly, with CentOS (which I installed to test a theory about the port issue), I can't bind any ports whatsoever, they all fail.

Not sure what steps I can/should take to debug WSL2 networking, but I can confirm the update to 19536 is what broke me.

**Comment by benhillis** [comment] 2019-12-18 18:53
Thanks for reporting, there is an issue in Insider Fast, and a fix is coming in a future build (hopefully next week).

**Comment by alexisferat** [comment] 2019-12-19 08:36
I have a LAMP setup on Ubuntu and I have the same issue. I cannot access my sites when using localhost.

Until the fix is coming, I found a workaround. Do a `ifconfig` and take the inet value of the `eth0` connection and use it instead of localhost (for example in your host file).

**Comment by GMory** [comment] 2019-12-19 16:06
Is there a way to downgrade to previous build? This broke my whole workflow via auto update.

**Comment by berwyn** [comment] 2019-12-19 16:34
Settings -> Update & Security -> Recovery -> Go back to a previous version of Windows 10
![image](https://user-images.githubusercontent.com/1403744/71190988-91aebf80-2253-11ea-9928-2a0cd553a180.png)

**Comment by OctavioBR** [comment] 2019-12-20 19:27
I witness that after `19536` update, it started to give me this same error.

**Comment by alechstong** [comment] 2019-12-24 15:30
I ran into this problem as well. 
I experimented a little and found out that the problem is better described as "one port per ip address".

For example, I start server A on port 3000 and server B on 4000. If I access server A first on 127.0.01:3000 on the windows side, but I cannot access server B on 127.0.0.1:4000. However, I can access server B using wsl's ip address (let's say 172.23.134.64:4000). If I start another server C on port 5000, I cannot access it from either ip.

So if you are like, that are only running at most 2 servers in WSL, you are fine for now, and can wait for the update to drop.

**Comment by FanatikPriest** [comment] 2020-01-02 13:20
@benhillis would you share an update on the fix? Any vague ETA?

**Comment by puco** [comment] 2020-01-06 11:16
Any news on the fix?

**Comment by mituso89** [comment] 2020-01-08 13:36
Any news on the fix?

**Comment by benhillis** [comment] 2020-01-08 14:47
Fix was delayed by holiday break but still inbound.

**Comment by BabyDino** [comment] 2020-01-08 22:52
Just installed 19541. Works for me :)

**Comment by wlbrough** [comment] 2020-01-09 01:05
19541 fixed it for me as well. Thanks @benhillis & WSL team!

**Comment by Joe-Pena** [comment] 2020-01-09 03:06
19541 Seems to have fixed vscode not being able to "fetch remote environment",

However it does NOT seem to have fixed the issue of not being able to access more than one port at a time.

I have a React project which runs on `localhost:3000`, and a Gatsby project which runs on `localhost:8000`, previous to this issue, I could run both of them simultaneously and access them from windows on Chrome.

Follow these steps to recreate the behavior:

- Open WSL2
- Go to the React project root directory and run `npm start` to start the server running on`localhost:3000`
- On a new tab, go to the root directory of the Gatsby project and run `npm start`, this starts the server on `localhost:8000`
- Open Google Chrome and go to `localhost:3000`, you should see the react project.
- Now try to go to `localhost:8000`, you will not be able to see the Gatsby project, and you should see an error like the following:

![image](https://user-images.githubusercontent.com/37708646/72034254-b34b0780-3251-11ea-8a88-5e9c23764e93.png)

Fun thing is you can stop both the servers, ONLY start the gatsby project on `localhost:8000`, and you will get the same error, but if you start another react project, it'll be fine on `localhost:3000`.

It seems like the first port you use while WSL2 is active sticks and becomes the only one you can see from Windows, running `wsl --shutdown` on a command prompt window and starting WSL2 again seems to reset the slate, so say now you start the Gatsby project on `localhost:8000` first then stop it right away, you won't be able to see any apps running on `localhost:3000` if you start them after starting the `localhost:8000` app, you will only have port 8000 visible on windows.

**Comment by rabbitXIII** [comment] 2020-01-09 03:14
@Joe-Pena i observed the same behavior before updating to 19541. :( was feeling hopeful about this version.  Does VSCode work while your server is occupying a port? I've had to resort to just using VIM while leaving my react dev server up..

**Comment by mituso89** [comment] 2020-01-09 03:17
19541 fixed it for me as well. I can able to access port. Thank @benhillis

**Comment by benhillis** [comment] 2020-01-09 03:19
Great thank you all for confirming, and sorry for the disruption.

**Comment by Joe-Pena** [comment] 2020-01-09 03:30
UPDATE: I started an X server to see if using chromium from within my Ubuntu WSL2 would be able to go around the problem, but the issue seems to have resolved itself in a weird way.

I stopped both apps, the one running on `localhost:3000` and the one running on `localhost:8000`, I did not run `wsl --shutdown` before this, and at this point I could view `localhost:3000` but not `localhost:8000`, and vscode had **no issues** connecting to the remote WSL environment. (@rabbitXIII)

I created a started app with `create-react-app` and a starter app with `gatsby new test-project`, here's where I encountered whatever may have fixed it.

I ran `npm start` on the react app to start it on `localhost:3000`, however, I got this error message from windows:

![2020-01-08](https://user-images.githubusercontent.com/37708646/72035423-138f7880-3255-11ea-8678-c093bf5ab997.png)

I simply clicked 'ok' and the server kept running as usual. I then ran `npm start` on the Gatsby starter app and it ran without the windows error.

I opened to different tabs on wsl2 and ran `chromium browser` on each in order to open two chromium windows, I then snapped them to the bottom of the screen and then opened two chrome windows on Windows and snapped them to the top, the left side is viewing port 3000 and the right is viewing port 8000, it seems like they are all working as intended.

![2020-01-08 (1)](https://user-images.githubusercontent.com/37708646/72035575-87ca1c00-3255-11ea-98b1-24cb8ca3f0c9.png)


I will restart my pc and see if the issue comes back.

**Comment by Joe-Pena** [comment] 2020-01-09 04:02
After restarting, the issue seemed to go away, I was able to view both localhost **3000** and **8000** from Chrome on Windows. However whenever I start anything on port 3000, such as the react app, I get the following message:

![2020-01-08 (2)](https://user-images.githubusercontent.com/37708646/72036928-99adbe00-3259-11ea-894e-fb2f28b3d9b8.png)


I decided to start a third app on a different port, an Angular app on port **4200** and the issue seemed to come back.

I opened two Chrome windows running in Windows(top) and two chromium windows running in WSL2 (bottom), left side is port 4200 and right is port 3000:

![2020-01-08 (3)](https://user-images.githubusercontent.com/37708646/72036979-cbbf2000-3259-11ea-9f3b-5f603b060dec.png)


I'm not sure exactly what's causing the issue at this point, but I think the error message could possibly hint at the cause, as for some reason the `\` characters on the word `http://localhost:3000/` are not being escaped on the error message.

I'm gonna mess around with it a bit more then possibly open a new issue if it seems unrelated to this existing issue, but for now, I would suggest this issue remain open.

**Comment by lnneth** [comment] 2020-01-09 05:16
I am using nuxt for my client-sided application and also an express server. When nuxt is ran in development it outputs the url which by default is `http://localhost:3000/` and my express server is located at `http://localhost:8080/`. Only nuxt app was could be reached. 

Interestingly enough, vs code allows us to click links outputted in the console and holding `ctrl` while clicking the links, `http://localhost:3000/` and `http://localhost:8080/`, redirect me to completely different urls that correctly displayed the applications (`http://127.0.0.1:50489/` and `http://127.0.0.1:50570/` respectively)

**Comment by rajivkr** [comment] 2020-01-09 06:52
Same here, Fixed the vscode problem, but the other problem of ports still persists, I tried to bring up two react apps, one in 8080 and other in 1234, I am able to access 8080 from chrome and not the other one. If I shutdown wsl and bring up 1234 first, 8080 fails to load.

**Comment by Brian-Cole** [comment] 2020-01-09 14:52
I can report similar behavior to the others who still have the issue in build 19541.  First port that binds to localhost or 0.0.0.0 generally is the only one that works.

I believe vscode is working around the issue by using the IP of the VM when connecting.
![image](https://user-images.githubusercontent.com/433904/72077710-b4b61780-32c5-11ea-82f0-6d345f3623e2.png)

**Comment by benhillis** [comment] 2020-01-09 15:28
Looked through the commits in 19541 and the fix is actually not there yet. Hopeful for next week...

**Comment by benc-uk** [comment] 2020-01-10 08:31
I can confirm it's not fixed in 19541, but weirdly VSCode seems unaffected now. Looks like they created their [own fix/workaround](https://github.com/microsoft/vscode-remote-release/issues/2060), for me that was the biggest blocker to my work.

Hope to see the full fix land soon

**Comment by andrp92** [comment] 2020-01-12 23:05
Yea, still having same problem build 19541 and VSCode team fixed connection on their end. Hope this gets fixed soon though.

**Comment by sjess** [comment] 2020-01-13 13:59
I hope that too ....

**Comment by nickvlku** [comment] 2020-01-17 03:08
Just got a new fast insider build 19546.1000 and bad news - still no good.  The fastest way I found to test this is spin up a simple ruby or python web server on one port - you're good to go.  Same server on a second port, no good.  Whichever one starts first is fine.

Concretely, ran `rails s -p 3000` and hit http://localhost:3000, got the default page.  Ran `rails -s p 5000`, http://localhost:5000 returns unable to connect.  I reboot and do the reverse and then I can talk to http://localhost:5000 but not http://localhost:3000.

Sad face.

**Comment by tony** [comment] 2020-01-17 15:45
@nickvlku Same, `Version 10.0.19546 Build 19546` still has this problem.

Aside: Thank you to the WSL team. WSL 2 is solid and far better than WSL 1. `npm install` can be ran on multiple projects at the same time, watching thousands of files, with postgres doing massive imports. WSL 2 handles it without a sweat,

**Comment by benhillis** [comment] 2020-01-17 15:52
Fix is in 19548 and later. Next weeks insider fast.

**Comment by nickvlku** [comment] 2020-01-17 19:10
Thank you so much @benhillis!  WSL2 is great!

**Comment by OctavioBR** [comment] 2020-01-20 13:51
Is there any _hidden_ option to **lock updates** until 19548 hits the internet?
![image](https://user-images.githubusercontent.com/4429577/72731338-4d744f00-3b72-11ea-8825-e17148bef103.png)
![image](https://user-images.githubusercontent.com/4429577/72731581-bb207b00-3b72-11ea-860e-9aa35fba9914.png)

**Comment by smonev** [comment] 2020-01-21 13:41
I have ruby / rails server, redis, postgres, elasticsearch running on wsl2 / ubuntu.

I did reverted to an older version and paused updates (while the fix is released), but somehow windows updated last night, and now it says I can not repair it to a previous version (this option is no longer available because your PC was updated more than 10 days ago).

Any workaround greatly appreciated. `ifconfig`  and then using the `eth0` ip address `172.20.*.*` does not work for me.

**Comment by alechstong** [comment] 2020-01-21 14:00
I found out that restart wsl solves the problem.

close wsl terminal
Win+R
Type in `services.msc`
find the `lxssmanager` service
right click and select `restart`
wait for the progress bar to complete, and reopen wsl terminal

**Comment by benc-uk** [comment] 2020-01-21 14:21
Win+R and `wsl.exe --shutdown` is even quicker 😁 
![image](https://user-images.githubusercontent.com/14982936/72812393-53912b00-3c59-11ea-8031-1016e0729d77.png)

**Comment by ad-on-is** [comment] 2020-01-23 16:00
Just a side node what **concurrent setup** surprisingly works right now.

- Running `vue ui` works on port `localhost:8000`.
- Serving an app via `vue ui` on `localhost:8080` DOES NOT work, but on `172.x.x.x:8080` it works
- Having Docker running and serving local domains like `*.mylocal` on port `443` works 
- VSCode Remote works

**Comment by Brian-Cole** [comment] 2020-01-23 20:14
Just installed 19551, from the 30 seconds of testing, it seems to be fixed.

**Comment by rajivkr** [comment] 2020-01-24 06:16
Installed 19551, tested with apps running in 4 different ports, it seems fine now. Thank you.

**Comment by klmdb** [comment] 2020-01-24 07:23
Seems to be fixed for me as well.

**Comment by ralfting** [comment] 2020-01-24 16:23
It was fixed here too

**Closed** 2020-01-24 16:31 UTC
Labels: fixinbound

**Comment by benhillis** [comment] 2020-01-24 16:33
Thanks for confirming!

**Comment by dennmart** [comment] 2020-01-30 12:18
@benhillis Do you know when this fix will get released to the Slow ring?

**Comment by benhillis** [comment] 2020-01-30 15:48
I don't believe this is broken in the slow ring.

**Comment by radix** [comment] 2020-01-30 16:01
I'm on the slow ring, with no updates available, and my build is 191211-1446. This issue is still affecting me.

**Comment by benhillis** [comment] 2020-01-30 16:25
Ok, I will take a look to confirm.

**Comment by radix** [comment] 2020-01-30 20:55
The problem may be that I was originally on the fast ring, and then some time ago switched to slow ring. Maybe I switched to slow right after this bug was introduced to fast? :sob:

**Comment by benhillis** [comment] 2020-01-30 20:58
@radix - Yes, I suspect you are still on a Fast ring build. What is the output of ver.exe?

**Comment by dennmart** [comment] 2020-01-31 02:39
@benhillis I was never on the Fast ring, only the Slow ring.

My current build is 19041.21, which I believe is the latest Slow ring preview build.

**Comment by dpopiashvili** [comment] 2020-01-31 20:22
I can't access any port at all. Slow ringer here. My build is 19041.21 with wsl2 :(

**Comment by saif-ellafi** [comment] 2020-02-02 12:02
Yesterday it worked for me for some reason (on a super clean install).

Today, I booted up but my localhost services are not reachable anymore. I am loading a Hadoop YARN docker image. Not sure if there was any update overnight, I am on build 19041.

**Comment by saif-ellafi** [comment] 2020-02-02 13:49
Okay, apparently what happened is that the docker I was running never released one of the ports I was using (9001). This port is now always stuck in some PID 4 I cannot ever close.

I am running the same docker image on a new port binding 9002 and the service works fine. Now I am very curious whether I'll end up blocking 9002 as well

**Comment by dennmart** [comment] 2020-02-13 12:40
I just checked on the [latest Slow ring update](https://blogs.windows.com/windowsexperience/2020/02/11/releasing-windows-10-insider-preview-build-19041-84-to-the-slow-ring/) and it looks like it fixed this issue for me :tada:

**Comment by Himakar-PV** [comment] 2020-03-30 09:53
I downloaded Microsoft Windows [Version 10.0.19592.1001] through insider (fast).

This has the vhost issue again. None of the above mentioned suggestions worked for me.

**Comment by alexisferat** [comment] 2020-03-30 09:59
I also still have this issue (version 10.0.19041.172, slow ring). I change the IP addresses in my `hosts` file with the inet value of `ifconfig` every time WSL is restarted. Putting `127.0.0.1` is not working 😕.

**Comment by dparker2** [comment] 2020-04-10 17:11
Also having this issue again with version 10.0.19592.1001

**Comment by mMoovs** [comment] 2020-04-14 12:17
Updated from wsl 1 to 2 today and can cofirm this issue is still present. Slow ring, version 10.0.19041.173. Using @alexisferat 's fix for now...

**Comment by Himakar-PV** [comment] 2020-04-16 13:00
@benhillis  please check our above comments, the issue if back in the latest versions. Thank you.

**Comment by ad-on-is** [comment] 2020-04-16 13:06
Windows 200410-1438 Build 19608, no issue here!

**Comment by onomatopellan** [comment] 2020-04-16 13:11
Windows Insider Slow Ring build 19041.207. No issue here trying OP's instructions.

**Comment by dparker2** [comment] 2020-04-17 14:31
Just updated to version 10.0.19608.1000 and the issue appears to be resolved again

**Comment by craigloewen-msft** [comment] 2020-04-17 16:35
If you're experiencing this issue again, could you please collect detailed logs for us (instructions [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)) and post them here so we can help diagnose it?

Thank you!

**Comment by Kenan7** [comment] 2020-05-01 20:54
@craigloewen-msft 
[detailed_logs.zip](https://github.com/microsoft/WSL/files/4566256/detailed_logs.zip)

**Comment by ahmedalnuaimi** [comment] 2020-05-16 16:22
I faced the same problem and found that running Docker commands or any other command that creates listeners with sudo solves the problem! Adding the current user to the docker group made no difference.

**Comment by renevall** [comment] 2020-05-19 16:30
I was having issues with kubectl port-forward. What worked for me was stopping docker desktop(wsl2) windows. Then I ran the port-forward. It suddenly started to work again. I started docker desktop again  and everything seems to work

**Comment by gvalenzuelas** [comment] 2020-05-31 22:56
When upgrade WSL 1 to WSL 2 the apache2 conf only listen on tcp v6 (ubuntu 20.04). I solved this problem, apply configuration in file /etc/apache2/ports.conf to Listen 0.0.0.0:80 (tcp v4)

**Comment by sarim** [comment] 2020-06-17 11:21
This issue comes and goes it seems. One day its working, next day its not. Some ports are working, some ports aren't. Not sure what is going on. Ex: last night everything was working, now i can't connect to my wsl's mysql from windows with localhost:3306.  Where a http server running in 4444 is working fine.

How does this localhost forward work actually? Can I run a powershell cmd to get a list of ports LXSS is current forwarding? Can I reset it? Edit it?

**Comment by onomatopellan** [comment] 2020-06-17 11:46
@sarim Can you check if you have Fast Startup enabled?

**Comment by sarim** [comment] 2020-06-17 12:08
I had fast startup enabled. But I had explicitly disabled hibernate from powercfg. AFAIK fast startup doesn't effectively enables if there is no hiberfil.sys. Which I don't have bcz I disabled hibernate. Nevertheless I explicitly disabled fast startup from registry.

**Comment by sarim** [comment] 2020-06-22 21:38
It happened again. Restarting LxssManager from Task Manager -> Services didn't help. Had to restart windows. Now its working.

**Comment by lemchen** [comment] 2020-06-27 14:55
It happened again. some specific ports not working for localhost:ports, but some other ports works. for example, i run node use  localhost:3000 doesn't work, by changing the port number it does.

**Comment by onomatopellan** [comment] 2020-06-27 15:12
@lemchen That sounds like https://github.com/docker/for-win/issues/7196
What's the output of `netsh int ipv4 show dynamicport tcp` ?

**Comment by lemchen** [comment] 2020-06-27 15:28
> @lemchen That sounds like [docker/for-win#7196](https://github.com/docker/for-win/issues/7196)
> What's the output of `netsh int ipv4 show dynamicport tcp` ?

yes , the port is in the range of excludedportrange by using netsh interface ipv4 show excludedportrange protococol=tcp.
i have solved this problem by disable Hyper-V function and re-enable it.

**Comment by a-abella** [comment] 2020-08-03 02:22
I've began experiencing (I think) some manifestation of this issue. I am not limited to one bound port at a time, but which ports are accessible from the Windows host seems arbitrary. I had ports 3000 and 222 working yesterday. After a shutdown, they are not working today. Additional testing of random ports has yielded the following results:

(testing methodology: `sudo netcat -kl 0.0.0.0 $port` from wsl2, and try to access from browser on Windows host)

```
Working:
1024
1025
1026
1027
1194
2111
4099
4170
4455
4567
6974

Not working:
1111
2024
2025
2026
2027
2255
3000
3005
3456
4000
4001
4002
4003
```

The ports that work always work, even after `wsl --shutdown`. The ports that fail always fail. I'm curious what the condition is that causes this.

The WSL-side iptables are blank:
<details>
<summary>iptables-save output</summary>

```
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*security
:INPUT ACCEPT [29:3752]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*raw
:PREROUTING ACCEPT [49:8733]
:OUTPUT ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*mangle
:PREROUTING ACCEPT [49:8733]
:INPUT ACCEPT [29:3752]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [27:3286]
:POSTROUTING ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*filter
:INPUT ACCEPT [29:3752]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*security
:INPUT ACCEPT [29:3752]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*raw
:PREROUTING ACCEPT [49:8733]
:OUTPUT ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*mangle
:PREROUTING ACCEPT [49:8733]
:INPUT ACCEPT [29:3752]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [27:3286]
:POSTROUTING ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
# Generated by iptables-save v1.6.1 on Sun Aug  2 22:18:51 2020
*filter
:INPUT ACCEPT [29:3752]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [27:3286]
COMMIT
# Completed on Sun Aug  2 22:18:51 2020
```

</details>

**Comment by onomatopellan** [comment] 2020-08-03 10:33
@a-abella Open an elevated Powershell and post the output of these:
`netsh int ipv4 show excludedportrange protocol=tcp`
`netsh int ipv4 show dynamicport tcp`

**Comment by a-abella** [comment] 2020-08-03 18:27
@onomatopellan 

Aha, I knew about `show dynamicport` but not the excludedportrange.

```
Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      1028        1127
      1239        1338
      1675        1774
      1775        1874
      1875        1974
      1975        2074
      2075        2174
      2180        2279
      2280        2379
      2380        2479
      2480        2579
      2580        2679
      4514        4613
      4614        4713
      4714        4813
      4814        4913
      4914        5013
      5041        5140
      5141        5240
      5241        5340
      5355        5454
      5455        5554
      5555        5654
      5655        5754
     50000       50059     *

* - Administered port exclusions.

PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> netsh int ipv4 show dynamicport tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 1024
Number of Ports : 64511
```

This is after a reboot since my previous comment, so it looks like the exclusions affecting my random port findings are now different.

Your comment led me to https://github.com/microsoft/WSL/issues/5306 , which suggested moving the dynamic port range with `netsh int ipv4 set dynamic tcp start=49152 num=16384` Presumably an Insider update or something moved the Start Port to 1024.

After moving the Start Port and rebooting things look sane again, and I can bind ports reliably from WSL2 again.

Thanks a lot!

**Comment by ntrp** [comment] 2020-08-18 14:10
Thanks for this, I wasted 4 hours finding out why it does not work... Did not think about changing port after seeing that a demo python server on 8000 was working fine...

**Comment by danielcinome** [comment] 2021-02-13 23:39
> 19541 Parece que el vscode fijo no puede "recuperar el entorno remoto",
> 
> Sin embargo, NO parece haber solucionado el problema de no poder acceder a más de un puerto a la vez.
> 
> Tengo un proyecto de React que se ejecuta `localhost:3000`y un proyecto de Gatsby que se ejecuta `localhost:8000`, antes de este problema, podía ejecutar ambos simultáneamente y acceder a ellos desde Windows en Chrome.
> 
> Siga estos pasos para recrear el comportamiento:
> 
> * Abrir WSL2
> * Vaya al directorio raíz del proyecto React y ejecute `npm start`para iniciar el servidor en ejecución`localhost:3000`
> * En una nueva pestaña, vaya al directorio raíz del proyecto Gatsby y ejecute `npm start`, esto inicia el servidor en`localhost:8000`
> * Abra Google Chrome y vaya a `localhost:3000`, debería ver el proyecto de reacción.
> * Ahora intente ir a `localhost:8000`, no podrá ver el proyecto Gatsby, y debería ver un error como el siguiente:
> 
> ![imagen](https://user-images.githubusercontent.com/37708646/72034254-b34b0780-3251-11ea-8a88-5e9c23764e93.png)
> 
> Lo divertido es que puede detener ambos servidores, SOLO iniciar el proyecto gatsby `localhost:8000`y obtendrá el mismo error, pero si inicia otro proyecto de reacción, estará bien `localhost:3000`.
> 
> Parece que el primer puerto que usa mientras WSL2 está activo y se convierte en el único que puede ver desde Windows, ejecutarse `wsl --shutdown`en una ventana del símbolo del sistema e iniciar WSL2 nuevamente parece restablecer la pizarra, así que diga ahora que inicia el proyecto Gatsby `localhost:8000`primero luego deténgalo de inmediato, no podrá ver ninguna aplicación ejecutándose `localhost:3000`si las inicia después de iniciar la `localhost:8000`aplicación, solo tendrá el puerto 8000 visible en Windows.

this has worked for me, thank you.

**Comment by gxtaillon** [comment] 2021-04-25 18:18
Same problem as described above. Setup working fine with Docker for Windows & Kube. After restarting the computer, nothing works from the windows side. Running `wsl --shutdown`, restarting docker from the UI and rerunning `kubectl proxy`, now everything works fine.
