### ISSUE TITLE
Can't execute WSL2 from remote PSSession

### ISSUE THREAD

**Issue by bpkroth** [microsoft/WSL#9620] opened 2023-02-09 18:09 UTC
### Version

Microsoft Windows [Version 10.0.22621.1105]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

```pwsh
echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Repro Steps

```pwsh
New-PSSession -ComputerName $remoteComputerFQDN | Enter-PSSession
```
```pwsh
wsl.exe /?
```
```txt
wsl.exe : The file cannot be accessed by the system.
    + CategoryInfo          : NotSpecified: (The file...system.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
```pwsh
Get-Command wsl.exe | Format-List *
```
```txt


HelpUri            :
FileVersionInfo    : File:             C:\WINDOWS\system32\wsl.exe
                     InternalName:     wsl.exe
                     OriginalFilename: wsl.exe.mui
                     FileVersion:      10.0.22621.1 (WinBuild.160101.0800)
                     FileDescription:  Windows Subsystem for Linux
                     Product:          Microsoft® Windows® Operating System
                     ProductVersion:   10.0.22621.1
                     Debug:            False
                     Patched:          False
                     PreRelease:       False
                     PrivateBuild:     False
                     SpecialBuild:     False
                     Language:         English (United States)

Path               : C:\WINDOWS\system32\wsl.exe
Extension          : .exe
Definition         : C:\WINDOWS\system32\wsl.exe
Source             : C:\WINDOWS\system32\wsl.exe
Version            : 10.0.22621.1
Visibility         : Public
OutputType         : {System.String}
Name               : wsl.exe
CommandType        : Application
ModuleName         :
Module             :
RemotingCapability : PowerShell
Parameters         :
ParameterSets      :
```

### Expected Behavior

Should be able to run `wsl.exe` commands via remote powershell session.

### Actual Behavior

wsl.exe returns an error when invoked over a remote PSSesssion, but other executables don't.

This prevents using something like `wsl.exe ip addr show` to discover the current IP address of the WSL instance.

This prevents remotely fixing port forwarding problems, for instance, which would allow one to setup remote SSH to WSL instance when the WSL instance IP addresses change.

Alternatively, static IP addressing for WSL instances could also be useful.  Or else a way to discover the current address of the WSL instance in pwsh directly.

### Diagnostic Logs

See above.

**Comment by Oppfinnaren** [comment] 2023-02-12 10:38
Duplicate of https://github.com/microsoft/WSL/issues/9231

**Comment by pmartincic** [comment] 2023-02-15 12:39
Thanks @Oppfinnaren 

/dupe #9231

**Closed by pmartincic** 2023-02-15 12:40 UTC
