### ISSUE TITLE
X11 drops out when network changes

### ISSUE THREAD

**Issue by pbecotte** [microsoft/WSL#4675] opened 2019-11-13 23:51 UTC
* Your Windows build number:  19018.1

* What you're doing and what's happening: 
**Environment**

1. Running Pycharm inside my WSL2 installation. 
2. Using Mobaxterm to launch the session and be the x11 server. 
3. Have  ```export DISPLAY=`grep -oP "(?<=nameserver ).+" /etc/resolv.conf`:0``` in my .bashrc.
4. Happy to share any other settings that may be useful

**Issue**
Whenever I connect to a network, my x11 session ends. The windows simply dissapear from view, and 20 or 30 seconds later the prompt in my terminal shows `$` to show that its ready for new input. There's no error output, just the last app ending.

This is _not_ 100% of the time (had to cycle airplane mode twice to get it to happen just now of course), but the vast majority. When I get on the train in the morning, I won't bother opening my IDE until I can get my wifi working since I know it will crash whenever that happens.

I figure this is related to the networking/dns setup in some way (I found out the hard way that I can't run a caching dns server and wsl2 at the same time a while back), but am not sure where to troubleshoot beyond that (especially being a linux guy and having basically 0 windows sysadmin experience)

**Comment by karuboniru** [comment] 2019-11-14 12:31
Same here, this happens randomly.And it seems that X11 applications won't be killed then (which should usually happen X applications is disconnected to XServer).

This happends on both VcXsrv and X410 here.

**Comment by therealkenc** [comment] 2019-11-14 18:47
Rephrasing this one in terms some CLI networking scenario (`ssh`,`sshd` lets say) will probably get more eyeballs. Going to be spiritually dupe one of the several VPN  / "my network changed" submissions.

**Comment by edburns** [comment] 2020-01-23 16:53
Another problem.  If you are using VS Code on the WSL side, connected with the WSL "Remote" extension (in this case to your own darn machine), and the connection drops, VS Code gets wonky.  I've even seen it crash in this case.

**Comment by edburns** [comment] 2020-01-24 14:42
In my case, the most fundamental problem was my Surface Dock losing and re-establishing the network connection with its wired ethernet port.  I worked around this by using either WiFi, or the USB/Ethernet adapter.  But I was still wanting to use the ethernet port on the dock.  I found these resolutions:

- [Twiddle some options on the surface dock ethernet adapter](https://www.youtube.com/watch?v=01sjoXheIIo)
- [Update the firmware in the Surface Dock](https://www.windowscentral.com/how-update-microsoft-surface-dock-firmware)

I only did this these steps ten minutes ago, so let's see if they resolve the random disconnect issue.

Of course, being able to use a `localhost` for X is a better option.

**Comment by itspers** [comment] 2020-09-04 07:26
Same problem - working remotely under unstable wifi, which drops and connects periodically, and gui windows just disappear time to time :(

**Comment by anishsane** [comment] 2020-09-07 11:45
Same problem.
Hitting this bug if wifi disconnects and I switch to mobile hotspot or vice versa.
Is there a simpler way, via say port forwarding to forward the windows X server port to Linux and use DISPLAY="localhost:0" ?

**Comment by neodarksaver** [comment] 2020-09-16 19:55
Same issue. I use terminator on WSL2 with X server. On any network change (connect/disconnect to vpn, moving to new AP, docking/undocking), the terminator window just disappears.

**Comment by nbdd0121** [comment] 2020-10-12 22:31
I wrote a workaround that uses vsock to bypass the X11 drop caused by TCP reset: https://github.com/nbdd0121/x11-over-vsock.

**Comment by rommeswi** [comment] 2021-01-19 08:45
As of 2021, the bug persists and is obnoxious as hell.

**Comment by JanzenJohn** [comment] 2021-08-22 10:10
Your hostname changes when you connect to a network

In your hostsfile(/etc/hosts)  is an entry something like this

127.0.1.1 YourHostname

however connecting to a network (for example using network manager) changes your hostname to

YourHostname.YourDomain

For networkmanager you can change this in /etc/NetworkManager/NetworkManger.conf

by adding

`[main]
plugins=keyfile 
hostname-mode=none `

Idk what wsl uses by default though (I had this issue on hardware, using NetworkManager)

**Comment by JanusDC** [comment] 2024-01-27 16:13
I am having the same issue in Windows 11. There is still no solution to this bug opened 4 years ago?

**Comment by chanpreetdhanjal** [comment] 2024-01-29 23:34
Hi. Can you please collect networking logs by following the instructions below?
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#collect-wsl-logs-for-networking-issues

**Comment by JanusDC** [comment] 2024-02-08 21:30
Here it is.
[WslLogs-2024-02-08_18-27-48.zip](https://github.com/microsoft/WSL/files/14214868/WslLogs-2024-02-08_18-27-48.zip)

I started the log, I opened a PDF in Zathura using WSLg, I disconnected my wifi and reconnected again, Zathura GUI was lost (but still running according to ps on my Linux), and stoped the log.

**Comment by OneBlue** [comment] 2024-05-14 21:27
@pbecotte: It looks like you're overriding $DISPLAY to use a network based X server, which explains the symptoms you're seeing. 

Do you see the same behavior if you use wslg instead ? If so, please collect /logs

**Comment by pbecotte** [comment] 2024-05-15 11:03
Wslg didn't exist when I opened this ticket :) In the four years since I opened this wasg came out,  which I used for a while, and jetbrains gateway came out, which is my current approach. I believe this happened with wslg as well, but not as often- but I would no longer be able to provide logs etc since I have run anything other than a 2fa browser over x11 in years.

**Comment by OneBlue** [comment] 2024-05-15 18:22
Ok no problem ! 

Closing the issue since this scenario would most likely be solved via wslg.

**Closed by OneBlue** 2024-05-15 18:22 UTC
Labels: network
