### ISSUE TITLE
[WSL 2.0] How to access git repo with Windows program.

### ISSUE THREAD

**Issue by Drakota** [microsoft/WSL#4273] opened 2019-07-05 19:11 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Try to access a git repo using GitKraken in WSL

* What's wrong / what should be happening instead:
I manage to find the repo in my file explorer using the \\wsl$\Ubuntu path, but when I try to open the repo I get an infinite loop. I've tried with SourceTree also and Github Desktop and I still can't resolve the problem.

**Comment by Biswa96** [comment] 2019-07-05 19:23
Open `\\wsl$` > Right click on Ubuntu folder icon > Select Map network drive (Z:) > Now Z: can be used as other partition/drive.

**Comment by Drakota** [comment] 2019-07-05 19:44
This helps selecting the repo, but the problem is still there, it hangs trying to open the repo and error out that the repo is incompatible (GitKraken, Github Desktop, SourceTree).
![image](https://user-images.githubusercontent.com/22665836/60742519-ae706880-9f3b-11e9-867d-85c1a5eab870.png)

**Comment by mscraigloewen** [comment] 2019-07-05 19:57
I'm unable to repro your issue. I was able to access my files with Git GUI and with Github Desktop. Are you able to access your Linux files normally via `\\wsl$\`?

**Comment by Drakota** [comment] 2019-07-05 20:03
@mscraigloewen I've managed to see the commit history, but I can't push nor pull, how about you?

**Comment by mscraigloewen** [comment] 2019-07-05 20:26
I'm able to pull after I mapped to a drive. I suspect if you're trying to do this from the `\\wsl$\` path you'll run into issues due to UNC pathing.

![Github Desktop](https://user-images.githubusercontent.com/42221804/60743468-a0641d00-9f26-11e9-8993-e3d8ee263a85.png)

**Comment by Drakota** [comment] 2019-07-05 20:30
I've mapped WSL to a drive, one problem was that cloning inside WSL made my files switch to LF which resulted with every single file being modified, which would explain why certain clients where crashing. Only thing now is that the network drive solution seems unstable and I lose the connection to the drive frequently.

**Comment by Biswa96** [comment] 2019-07-05 20:52
> one problem was that cloning inside WSL made my files switch to LF

Configure your `.gitconfig` file properly. Read these:

1. https://help.github.com/en/articles/configuring-git-to-handle-line-endings
2. https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

**Comment by Drakota** [comment] 2019-07-05 23:57
Hi, I've tested on different computers and what I got is that very often without changing anything, the explorer would throw me this error.
![image](https://user-images.githubusercontent.com/22665836/60748579-50ed1380-9f5d-11e9-863e-1bd0899994e5.png)
This makes it impossible to keep a repo open on any git clients since it sometimes doesn't find the path.
On GitKraken, I've found it boosts the CPU usage without ever going back down when a repo is opened this way
![image](https://user-images.githubusercontent.com/22665836/60748695-a675f000-9f5e-11e9-9541-a9902f487349.png)
![image](https://user-images.githubusercontent.com/22665836/60748717-d45b3480-9f5e-11e9-837e-1324fa6f45c4.png)

The CPU usage wouldn't be such a issue if the file system didn't lose it with the error shown above.
I'd be glad to provide further help, since I can reproduce this issue very easily.

**Comment by santo74** [comment] 2019-08-02 07:51
I'm trying to use SourceTree with WSL (WSL mapped to a drive) but similar to what @Drakota describes the cpu usage of the init process is spiking, making the whole setup unusable.
I can't even try to push or pull anything because of the high cpu usage. SourceTree is continuously showing a spinner, indicating it's trying to fetch / refresh data from the mapped drive.

**Comment by Drakota** [comment] 2019-08-06 14:20
@santo74 I fixed it by installing GitKraken inside Ubuntu and install VcXsrv on Windows.
Add this to your .bashrc to set the DISPLAY variable to the Windows host IP.
```
export DISPLAY=$(ip route show default | grep -Po 'via \K\S+'):0.0
```
Open VcXsrv  and make sure to disable Native OpenGL and Disable Access Control.
![image](https://user-images.githubusercontent.com/22665836/62547541-5c20b100-b833-11e9-848b-fc90b0068241.png)
Now I can just run the command `gitkraken` inside a WSL terminal and this opens my git client. 
I don't think SourceTree has a Linux client, but this could help you if you choose to use another client.

**Comment by santo74** [comment] 2019-08-07 09:34
@Drakota , thanks for the feedback, but unfortunately that's not a fix for the actual problem.
Instead of accessing the linux files (WSL) from windows you're now simply accessing them from within linux itself.
Your original issue was with accessing a git repo on linux (WSL) from a Windows program, which should now be possible with the new features introduced in W10 1903 but is apparently causing performance issues, which is exactly what I'm experiencing as well.
SourceTree for instance is not available for Linux, so in this case it's simply not possible to install it in WSL and tunnel it through an XServer.

**Comment by Drakota** [comment] 2019-08-07 19:18
@santo74 Effectively this doesn't fix the issue, but it's a workaround in the meantime.

**Comment by Ridder90** [comment] 2019-10-29 15:14
I am facing the same issue! Found an alternative solution i thought is worth sharing, still facing permission errors on the git index though.  

https://gist.github.com/carlolars/ed976078a66e7d57bb04f959270bdee3

**Comment by aniskhan001** [comment] 2020-06-13 07:16
It eventually opens up for me but after a long period of time.
And then when I try to interact with something, the program can't respond instantly.

For example, if I try to stage a file it shows the loading icon on that module and takes almost 15-20 seconds to finish the operation.

_Screenshot_
![image](https://user-images.githubusercontent.com/2815766/84562614-7f7f8b00-ad77-11ea-8866-81c098be7700.png)

**GitKraken 7.0.1**
**OS Build: 19645.1**

**Comment by kyletechspert** [comment] 2020-09-24 13:56
This appears to be the case to date for members on my team now adopting WSL2 also. I imagine this is the same for Source Tree and GitHub for Desktop when accessing git repos via the WSL "shared drive" - `\\wsl$`?

**Comment by kl3sk** [comment] 2020-10-21 08:54
I'am facing to all the problems decribed above. Installing Gitkraken inside _VcXsrv_ is not a solution for me either.

- Watching failed
- Very slow

Using WSL2 (debian) os WIN 10 2004 
Using shared drive (Z:)
Using gitkraken 7.3.2 (64bit)

**Comment by hourlier96** [comment] 2020-12-02 13:01
Same here.

Watching failed
Very VERY slow (1m checkout branch)

Using WSL2 (Ubuntu 18) os WINDOWS PRO
Using shared drive (U:)
Using gitkraken 6.5.0 (64bit)

Tried with Github Desktop, works 1000x faster

**Comment by TERADA-DANTE** [comment] 2021-01-01 08:53
> Open `\\wsl$` > Right click on Ubuntu folder icon > Select Map network drive (Z:) > Now Z: can be used as other partition/drive.

You saved my day.

**Comment by mrtronje** [comment] 2021-01-22 09:44
Are there any plans to give proper support to WSL2 in GitKraken? I'm not sure, but mapping a Network Drive can give performance issues.

**Comment by craigloewen-msft** [comment] 2021-01-22 17:08
@mrtronje would accessing GitKraken as a Linux app in your Linux environment be a solution for you? We are working on adding Linux GUI app support out of the box that would allow applications (like GitKraken) to access Linux files without having to go through Cross-OS operations.

**Comment by Drakota** [comment] 2021-01-22 17:24
@craigloewen-msft Being able to do this without having to install third-party software like VcXsrv would be very nice. Running an app inside Linux to access Linux files is basically what I'm doing right now, so this being part of WSL by default is very appreciated.

**Comment by JohnDeved** [comment] 2021-02-11 12:46
@craigloewen-msft gitkraken is apparently counting on you guys for this issue :)
![image](https://user-images.githubusercontent.com/24187269/107638094-6bc25680-6c6f-11eb-9e0a-afbd14334e36.png)

**Comment by craigloewen-msft** [comment] 2021-02-11 18:10
![gif4](https://user-images.githubusercontent.com/42221804/107678880-c7c9b280-6c50-11eb-8979-94dfcee62b06.gif)

Just tried this out with an internal build of GUI apps, and it works quite well (We're working more on this feature internally and don't yet have an ETA for when this will hit Insiders)! Question for you folks in this thread: since this app is running in Linux, it will be in a different context than if you have Git Kraken on Windows. That means you might have to change the settings for both, or launch the Windows app to access Windows files, and the Linux app to access Linux projects. What are your opinions for this user experience? I believe this will still be useful so you can access your files in general and would be worth using even if you have to replicate your settings.

**Comment by craigloewen-msft** [comment] 2021-02-11 18:27
Ah-hah! Just for fun I used some WSL magic to synchronize the settings between the Windows and Linux versions automatically. 

![gif5](https://user-images.githubusercontent.com/42221804/107681079-78d14c80-6c53-11eb-8686-e8361e8b1772.gif)

All I did was add symbolic links between the Linux and Windows settings files. Would a set up like this fit your needs? Or does the main requirement of this thread still stand even given this setup (Access Linux projects from the Windows app itself)?

**Comment by kyletechspert** [comment] 2021-02-11 20:19
Hey @craigloewen-msft , I'd love to see our devs move across to using WSL2 and we have a variety of different Windows apps like GitKraken, GitHub Desktop, and Sourcetree in use. I'll feed this back to the team and see if there are any strong opinions, but my two cents is that typically you'll find in cases like this the user is Windows-centric and wants as seamless an experience as possible.

I'll aim to gather some more opinions and let you know if there are any specific technical requirements in mind.

Thanks for following up on this!

**Comment by rfgamaral** [comment] 2021-02-11 20:41
@craigloewen-msft I would love it if the window chrome, fonts, and mouse cursor were the same ones as Windows. The ones from Linux kinda hurt my eyes 😅

**Comment by JohnDeved** [comment] 2021-02-11 21:13
> That means you might have to change the settings for both, or launch the Windows app to access Windows files, and the Linux app to access Linux projects.

@craigloewen-msft I think that's kind of expected and somewhat the point :)
I for one can't wait for this feature to be implemented, it could make my workflow so much easier for wsl
using `\\wsl$` to access files is just really slow and barely usable in many cases.

vscode with the [wsl remote plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) is the only smooth experience with wsl in combination with any kind of GUI so far.

**Comment by Ridder90** [comment] 2021-02-12 07:07
Awesome, would love to test this! I do think that "All I did was add symbolic links between the Linux and Windows settings files." is a bad idea. One thing i can think of is that paths to ssh keys `/home/florian/.ssh/id_key`  for Gitkraken WSL is different then Gitkraken in windows. If it is the same key   it would need to point to //$wsl.. etc

**Comment by gsnerf** [comment] 2021-03-01 11:09
@craigloewen-msft unfortunately that solution would just work for users of clients that have a linux version. What about pure windows clients like SourceTree?

**Comment by craigloewen-msft** [comment] 2021-03-01 18:14
@gsnerf , that's helpful context. As of right now pure Windows clients will need to access the UNC path `\\wsl\<DistroName>\` and so will need to make sure they can access UNC paths. There are other programs like Git Atlas that use this workflow.

**Comment by cavargas40** [comment] 2021-03-06 04:34
I'm quite interested in start using the **_gitkraken_** command from wsl2. any guide to install it there? or it will be released soon? :) (Looking forward to using it)

**Comment by mrtronje** [comment] 2021-03-06 06:48
@cavargas40 with the power of google : https://medium.com/@chuckdries/installing-gitkraken-in-wsl-2-15bf6459f823 😊 It works the most of time but it's not a very stable solution

**Comment by cavargas40** [comment] 2021-03-06 08:00
@mrtronje thanks! I found that too, didn't want to try it because is not an "official" option, but probably I'll try it! any advice is welcome :D

**Comment by cavargas40** [comment] 2021-03-06 08:29
![image](https://user-images.githubusercontent.com/430514/110200454-2c30f980-7e2c-11eb-8630-e1ecfab8919d.png)
up and running. thanks! (quite fast 👍 )

**Comment by jberculo** [comment] 2021-04-17 12:31
On Ubuntu20.04 I tried the approach as described in the medium post. It's not working. I can run the gitkraken command, but nothing happens. No error messages whatsoever. Other applications run just fine using VcXsrv. Any clues?

**Comment by Froxz** [comment] 2021-04-26 10:04
Hi this is now possible  (native solution) with WSL 2.  (WSLg) (currently for windows Insiders only: https://github.com/microsoft/wslg) 

https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/

**Comment by chuckdries** [comment] 2021-05-01 04:35
Can confirm, gitkraken appears to work beautifully on WSLg!

```
wget https://release.gitkraken.com/linux/gitkraken-amd64.deb
sudo dpkg -i ./gitkraken-amd64.deb
sudo apt-get install -f
gitkraken
```

**Comment by therealkenc** [comment] 2021-05-10 21:07
The OP submission was "I get an infinite loop" using Windows GitKraken. There were no repro steps offered to manifest the behavior, but the suggestion was to map a network drive. Call that workaround-available. There was also a "parameter is incorrect" [cited](https://github.com/microsoft/WSL/issues/4273#issuecomment-508881681) in the mix. This much could not be reproduced locally. If the problem persists on 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem.

As a more practical solution, use Linux GitKracken on WSL2 on ext4 (aka `/home/you`) with a remote X11 server (f.e. VcXsrv) or [WSLg](https://github.com/microsoft/wslg).

**Closed by therealkenc** 2021-05-10 21:07 UTC

**Comment by theCrius** [comment] 2021-06-02 11:55
I just finished a clean install on a freshly made laptop.

Installed WSL2, Ubuntu 20 distro. Then WSLg.
Added docker only and checked that everything is in place.

Run:

```
wget https://release.gitkraken.com/linux/gitkraken-amd64.deb
sudo dpkg -i ./gitkraken-amd64.deb
sudo apt-get install -f
```

At this point lots of dependencies errors jump out.
Run `sudo apt --fix-broken install` to fix it and install also the pending gitkraken installation.

The only problem? Running `gitkraken` does absolutely nothing. No error, no warning. Nothing.
![image](https://user-images.githubusercontent.com/2202141/120475802-bba16680-c3a1-11eb-8fd6-46b802f89f87.png)

Anyone knows what is missing?

**Comment by helgatheviking** [comment] 2021-07-05 17:39
>using \\wsl$ to access files is just really slow and barely usable in many cases.

Same for me. My ideal situation would be to run my dev websites in WSL2 (which is significantly faster than any virtualbox/docker options) but still use SourceTree to handle git. 

I see some others are having success with GitKraken in WSL... might need to shell out the $60 for that.

**Comment by TonyTheFerg** [comment] 2021-07-29 14:06
Is there any documentation on using GitHub Desktop to push and pull files that are in WSL2? I am on Windows 10 Pro build 19043.1110, With Ubuntu 20.04. It would be really nice to be able to add a repository from WSL2 to GitHub Desktop.

**Comment by theCrius** [comment] 2021-07-29 14:54
@TonyTheFerg I'm not aware if it exits but my team and I are using GitKraken that does support WSL installation and usage.
It has free use license for public git repositories.

**Comment by NuijtenDev** [comment] 2022-02-23 13:18
To get a git client working (in my case gitkraken, sourcetree and git-fork) you should do the following: 

- map the \\wsl$ dir as a network drive
- in your wsl distro check the folder permissions 
    - if this is admin change it to local user : sudo chown user:group directory/ -R 
- route your git client via the network drive to your repository

now you should be able to see file changes.

I'm on :
- Docker WSL2
- Ubuntu 20.04

**Comment by ardostree2001** [comment] 2022-06-08 05:06
> I'm unable to repro your issue. I was able to access my files with Git GUI and with Github Desktop. Are you able to access your Linux files normally via `\\wsl$\`?

brother actually the command is ''\\wsl"
