### ISSUE TITLE
it's very slow while cd to a git directory 

### ISSUE THREAD

**Issue by clearcodecn** [microsoft/WSL#8633] opened 2022-07-20 12:46 UTC
### Version

Microsoft Windows [版本 10.0.19042.1706]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

20.04

### Other Software

➜  ~ git version
git version 2.25.1

### Repro Steps

I installed ohmyzsh. and when enter a git directory is very slow

### Expected Behavior

very fast

### Actual Behavior

very slow

**Comment by OneBlue** [comment] 2022-07-26 21:28
@clearcodecn: This is probably caused by the git plugin that ohmyzsh comes with by default as @ashemedai  suggests.

Closing since this isn't a WSL issue.

**Closed by OneBlue** 2022-07-26 21:28 UTC
