### ISSUE TITLE
Cannot wake up the PC in sleep with WSL2

### ISSUE THREAD

**Issue by angelog0** [microsoft/WSL#5549] opened 2020-07-06 16:21 UTC
After the upgrade to 2004 (19041.330), I installed, from scratch, WSL2 on a tablet with W10 Home (4 GiB RAM, 64 GiB storage, Z8350 CPU) and noticed that starting Ubuntu 2004 with Windows Terminal, if the tablet goes in sleep I cannot wake up it any more and have to restart it.

On the same tablet, before the upgrade to W10 2004, I used WSL1 since it was released (2015 or 2016?, don't remember) and would reinstall it if it hadn't another `seelp` issure (#4898)...

**Comment by therealkenc** [comment] 2020-07-06 21:04
If you revert to WSL1 and disable "Virtual Machine Platform" do you still experience the "cannot wake up it any more" behavior? It is possible the behavior is related to the hypervisor platform or it might not. Whatever the problem it is going to be specific to the drivers for your tablet hardware. What's the make/model for the data point.

**Comment by angelog0** [comment] 2020-07-06 22:29
As I wrote, I used WSL1 without issues since 2015/16 on this tablet. Obviously, with WSL1 I enabled only WSL and not the virtualization.

> What's the make/model for the data point.

I do not understand what you are asking for... The tablet is an ASUS with the above CPU and Intel Graphics and Realtek for the sound...

As I wrote WSL1 + ubuntu 2004 has the above issue and i do not want to install WSL1 before the issue is fixed in 19041..

**Comment by angelog0** [comment] 2020-07-06 23:11
I think I have also another issue with WSL2 related to the virtualization enabled in `Programs and functionalities`.

After the upgrade to W10 2004 and installed WSL2, I notice that after booting, at login, I had a notification saying that Focus assist is enabled for alarms, and this even disabling Focus Assist each time! In short the system thinks I am duplicating the display for a presentation! But there is only _one_ display! My settings for display looks exactly as described [here](https://community.spiceworks.com/topic/1902041-windows-10-detects-too-many-monitors-does-not-display-on-actual-monitors). I remember I had [this](https://static.spiceworks.com/shared/post/0021/0135/2016-11-02%2002_18_34-Settings.png) before the upgrade and WSL2 installation...

How to set only *one* display?

**Comment by angelog0** [comment] 2020-07-06 23:31
Obviously, for the sake of completeness, I disabled Virtual machine platform and the notification issue has gone.. and even re-enabling it, WSL2 does not work any more...

**Comment by therealkenc** [comment] 2020-07-07 04:21
> I do not understand what you are asking for... The tablet is an ASUS with the above

ASUS makes several tablets. Which one might help in the off chance you get a me2.

Whether you still experience your "if the tablet goes in sleep I cannot wake up it any more and have to restart it" will help determine the problem is related to virtualization being enabled, or not.

**Comment by angelog0** [comment] 2020-07-08 08:21
After recovering WSL2 from disabling virtualization, I cannot reproduce the issue. Obviously my tests are artificial so that they could not be valid to trigger the issue, In any case the tablet is an ASUS T101HA_A. 

I will retrn here if I will have other elements to specify. Thanks.

**Comment by angelog0** [comment] 2020-07-08 08:40
In any case, the issue with virtualization remains: it starts thinking I am doing a presentation duplicating the screen and focus assist always set to *only alarms*. I have each time to clear that setting disabling the Focus assist manually.

**Comment by angelog0** [comment] 2020-07-14 10:19
The issue comes out newly but I don't have a precise recipe to reproduce it. Often it seems it happens after I run this script

```
$ cat system_updater.sh
#!/bin/bash
##

apt update
apt upgrade
apt dist-upgrade
apt autoremove
```

**Comment by angelog0** [comment] 2020-07-14 16:59
Just now the issue occurred and I did not run WSL2 but only Windows Terminal + MSYS2. Maybe this issue is just related to the virtualization needed by WSL2...

**Comment by therealkenc** [comment] 2020-07-21 15:48
Closing as this issue has no repro and is not WSL actionable. For questions like "the tablet goes in sleep I cannot wake up it any more" you may find help/feedback in the [microsoft community](https://answers.microsoft.com/en-us) or possibly ASUS.

**Closed by therealkenc** 2020-07-21 15:48 UTC
Labels: need-repro
