### ISSUE TITLE
tail -f doesn't work properly

### ISSUE THREAD

**Issue by ijesonchen** [Microsoft/WSL#3942] opened 2019-03-28 09:35 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [版本 10.0.17763.379]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
tail -f xxx.log
when another process writing xxx.log， it should output new content of xxx.log. but it doesn't follow the log as it is growing.
BUT when I list the file in another wsl window use 'ls xxx.log', tail output new content immediately. It seem that tail didn't know the file is updated until I list the file.
I found a issue https://github.com/Microsoft/WSL/issues/3292. Someone got the same problem but the issue is closed without solved.

* What's wrong / what should be happening instead:
tail -f should output the new content continuously when the file growing.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/ijesonchen/4493860cf4793c590409eef339bebf55
tailf1.strace：
 run  tail -f testsrv.log. not follow when file growing
tailf2.strace
 run  tail -f testsrv.log. not follow when file growing.then ls testsrv.log in another wsl console. it output new contents

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
NONE

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment] 2019-03-28 20:25
> I found a issue #3292. Someone got the same problem but the issue is closed without solved.

It closed because it is dupe #925. Which was closed by-design [because](https://github.com/Microsoft/WSL/issues/925#issuecomment-357301112) it is an issue with `tail(1)`'s filesystems whitelist, and was addressed upstream. Can't repro with `tail` 8.28.

**Closed by therealkenc** 2019-03-28 20:25 UTC

**Comment by ijesonchen** [comment] 2019-04-04 03:52
> > I found a issue #3292. Someone got the same problem but the issue is closed without solved.
> 
> #3292 was closed because it is dupe of #925. Which was closed by-design [because](https://github.com/Microsoft/WSL/issues/925#issuecomment-357301112) it is an issue with `tail(1)`'s filesystems whitelist, and was addressed upstream. Can't repro with `tail` 8.28.

So you mean it was fixed in coreutils 8.28? But man tail report: GNU coreutils 8.28.
I noticed inotify was supported and tail -f should work in https://devblogs.microsoft.com/commandline/wsl-adds-inotify-filesystem-change-notification-support/.
So I'am a little confused. Is this expected （ doesn't work properly, tail's problem）or should I upgrade something？

**Comment by therealkenc** [comment] 2019-04-04 17:37
> So you mean it was fixed in coreutils 8.28?

I mean, I cannot reproduce your issue with the information given using coreutils 8.28.

**Comment by dcsobral** [comment] 2019-08-20 18:52
I have the same issue. File is being written by a windows application (7 Days to Die, and it's log file) to a folder on my desktop, with NTFS filesystem, and monitored through a `tail` run from a separate folder specifying the full path. Tail does not update, ever. It shows the lines that were present when started, and stays there.  I kept adding options trying to get it to work: `tail  --max-unchanged-stats=5 --sleep-interval=5 -F "${LOG}"`. No success. Then add `---disable-inotify`, and it works. Also, if I happen to `cat` or `tail` the log file, the `tail -f` will get updated. In fact, if I have two `tail -f` on the same file, and exit one, the other will get updated.

Here's my coreutils version:

```
ii  coreutils                         8.28-1ubuntu1                     amd64        GNU core utilities
```

lsb_release -a:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

Mind you, this was *updated from 16*. Also, it worked fine on 16, and stopped on 18.

#3292 has a bunch of thumbs up on the suggestion to use `---disable-inotify`. #925 talks about "unrecognized filesystem", which is not the issue described in #3292 or here.

**Comment by chesucr** [comment] 2019-08-27 11:23
@dcsobral you are right, I had to add `---disable-inotify` as well to the command in order to make it work. I think you could open another issue with the information in your post to draw some attention

**Comment by BercziSandor** [comment] 2025-01-21 11:21
Workaround alias:

alias tail='tail ---disable-inotify'
