### ISSUE TITLE
high vmmem  - memory usage  when converting from wsl1 to wsl2

### ISSUE THREAD

**Issue by ioweb-gr** [microsoft/WSL#4159] opened 2019-06-17 00:10 UTC
I'm experiencing extreme memory usage while converting a wsl1 image to wsl 2. Apparently vmmem keeps increasing steadily, for me it reached up to 16GB of RAM of a 32GB total. 

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version	10.0.18917 Build 18917

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Converting a kali-linux image from wsl1 to wsl2 

* What's wrong / what should be happening instead:
the memory usage is constantly increasing. Possible memory leak? 
![image](https://user-images.githubusercontent.com/20220341/59571432-2837d380-90ad-11e9-8d2b-721081f9000e.png)

Normally the process should be completed with minimum memory usage.

**Comment by mscraigloewen** [comment] 2019-06-17 18:02
Hi @ioweb-gr could you help us out by taking some detailed logs? Instructions to do so are [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

**Comment by benhillis** [comment] 2019-06-18 16:01
Duplicate of #4166.

**Closed by benhillis** 2019-06-18 16:01 UTC
Labels: wsl2

**Comment by theunclebobbyb** [comment] 2020-05-08 21:46
This ever get fixed? WSL just used all 64gb of my ram. I tried shutting down wsl and now its just hanging and it won't allow me to start wsl again.

**Comment by PHBMdeveloper** [comment] 2020-05-10 05:46
![image](https://user-images.githubusercontent.com/30447132/81491779-5b0c2c80-9268-11ea-93fb-b3f0aa3b4fdb.png)
 Temos solução?

**Comment by DevelCL** [comment] 2020-05-14 14:41
There is a WORKAROUND on 14-may: https://github.com/microsoft/WSL/issues/4166#issuecomment-628493643

**Comment by frei-x** [comment] 2020-05-17 05:11
> This ever get fixed? WSL just used all 64gb of my ram. I tried shutting down wsl and now its just hanging and it won't allow me to start wsl again.

fierce!

**Comment by andre-ss6** [comment] 2020-06-25 22:16
As #4166 has been locked; I just hope the final fix doesn't boil down to just putting a hard limit on the VM RAM usage.

**Comment by AnshulKathet** [comment] 2020-06-29 07:18
this is steadily increasing RAM consumption. Suggest a fix please #4166

**Comment by krzystooof** [comment] 2020-08-20 07:39
### Workarounds:
* create `drop_cache` command in your WSL distro like [Yenohal](https://github.com/microsoft/WSL/issues/4166#issuecomment-628493643)
*or*
* create `C\Users\<your user>\.wslconfig` file containing:
```
[wsl2]
memory=6GB 
processors=5 
```
With limits that suits your needs.
### Official support:
As written [in #4166 issue](https://github.com/microsoft/WSL/issues/4166#issuecomment-662705705) in **build 20175** Microsoft has changed the default memory scheme in WSL 2 to **use 50% of your memory in Windows, or 8GB** (whichever is smaller).

**Comment by nielsarts** [comment] 2020-09-10 12:37
I fixed this issue by using the following command in your powershell:
`wsl --shutdown`
start your wsl again and boom

**Comment by davidshen84** [comment] 2020-12-16 22:26
I am trying to convert my wsl 2 to 1, and ran into this memory issue. I tried the `drop_cache` trick in the comments, but it does not work for me. Also, I think that trick is only for releasing the memory while wsl2 is running, but wsl2 is not running while converting, right?

**Comment by ggcaponetto** [comment] 2021-09-18 11:33
This is still a issue in 2021. Does anybody have a workaround?

**Comment by ffyuanda** [comment] 2021-12-31 01:55
Still an issue, just `apt install` eats around 6 GB on my 16 GB Windows 10.

**Comment by gctech1** [comment] 2023-01-20 08:01
2023 any updates pls?

**Comment by tildrum** [comment] 2023-11-07 13:00
Same issue here, there are some fix ? thx :)
