### ISSUE TITLE
Cannot use Java TAR file

### ISSUE THREAD

**Issue by farzadmf** [Microsoft/WSL#811] opened 2016-08-07 23:29 UTC
I tried to use Java the same way I do in normal Ubuntu:
- Download and untar the official Java from oracle
- Create a soft link to the extracted directory
- Set my `PATH` and `JAVA_HOME` in `~/.bashrc` to point to those
- To set my `PATH`, I do the following

```
export JAVA_HOME=/my/symbolic/link
export PATH="${JAVA_HOME}/bin:$PATH"
```

So, I have **two** problems:
- If I set `JAVA_HOME` to my symbolic link, it doesn't recognize it, and if I do `which java`, it's still using `/usr/bin/java`
- If I set `JAVA_HOME` to the actual extracted directory, it recognizes that it should run `java` in that directory, but when I try `java -version`, it just freezes and does nothing!

**Comment by onomatopellan** [comment] 2016-08-08 00:03
Duplicate of https://github.com/Microsoft/BashOnWindows/issues/746
Fix coming in a future insider build.

**Comment by farzadmf** [comment] 2016-08-08 20:41
Actually, I have created a subdirectory under my home directory that contains **jdk-1.8.0_101** and I have a symlink in the same directory, pointing to that:

```
lrwxrwxrwx 1 farza farza    13 Aug  7 19:04 java -> jdk1.8.0_101//
drwxr-xr-x 2 farza farza     0 Aug  7 19:04 jdk1.8.0_101/
```

UPDATE: I noticed the double slash at the end of the link target, so I ran my `ln` command again, and now I have:

```
lrwxrwxrwx 1 farza farza    13 Aug  7 19:04 java -> jdk1.8.0_101/
drwxr-xr-x 2 farza farza     0 Aug  7 19:04 jdk1.8.0_101/
```

It seems that the link issue is now solved (although I think an extra slash wouldn't make that much of a difference), but the problem with freezing still exists, which I hope will be resolved by later builds

**Comment by onomatopellan** [comment] 2016-08-08 20:59
Yes, the symlink with slash at the end of the path is also a known bug. It's very easy to hit especially if you use TAB to complete a path. Should be fixed in next builds too.

**Comment by farzadmf** [comment] 2016-08-09 03:54
Cool, I would really dream of being able to use a full bash on Windows (if that every becomes a reality)

**Closed** 2018-05-29 21:19 UTC
