### ISSUE TITLE
timespace no available

### ISSUE THREAD

**Issue by khoffy** [microsoft/WSL#11653] opened 2024-06-05 01:37 UTC
**Is your feature request related to a problem? Please describe.**
Every time I try to run a flutter program on a virtual device (using an emulator), I get the following error message: "nsenter: cannot open /proc/2566/ns/time"

Using Openvpn, I get the same error. 

"uname -r" on my system returns "4.19.72-microsoft-standard+" which is too old. new version supports those advanced functionalities.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khoffy** [comment] 2024-06-05 01:46
[WslLogs-2024-06-04_21-42-21.zip](https://github.com/user-attachments/files/15572085/WslLogs-2024-06-04_21-42-21.zip)

**Comment by khoffy** [comment] 2024-06-05 02:55
I got the following message after adding the diagnostic logs file "Diagnostic information
.wslconfig found
	Custom kernel found: 'C:\Users\herma\vmlinux-wsl2-snapd'
Detected appx version: 2.1.5.0"

After deleting this config (the custom kernel), everything is working well. Thank you so much for the assistance.

**Comment by OneBlue** [comment] 2024-06-11 23:31
Thank you for following up. Glad to hear that the bot is helpful ! 

Closing since the issue is resolved.

**Closed by OneBlue** 2024-06-11 23:31 UTC
Labels: feature
