### ISSUE TITLE
[WSL STORE] $wsl 9p share die and is not accessible until reboot

### ISSUE THREAD

**Issue by Ansuel** [microsoft/WSL#8009] opened 2022-02-01 22:22 UTC
### Version

Microsoft Windows [Versione 10.0.22543.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu Devel

### Repro Steps

No idea.
This is very random. Most of the time it's triggered by Vs Code scheduled update.

9p $wsl share die and is not accessible untile the system is rebooted.
wsl --shutdown and reopen doesn't fix the problem
wsl is accessible by the vs code remote extension and by terminal.

This is present by using the wsl store version. Using the inbox version (NOT THE STORE VERSION) doesn't suffer from this problem.
Pleas tell me how to better diagnose this as I didn't find an exact way on how to debug 9p crash. Dmesg from wsl doesn't provide any useful logs.

### Expected Behavior

$wsl doesn't die and became inaccessible. 

### Actual Behavior

$wsl became inaccessible from explorer and makes it hangs and crash on the long run.

**Comment by LeonidasJP** [comment] 2022-02-08 09:38
Confirmed... Also from PHPStorm, running an app that is hosted within my Ubuntu distro, WLS dies. When - well, just as @Ansuel mentions - is random, but most likely to be triggered by a Filesystem Sync.
Just as with Ansuel, Inbox WSL has no issues, it's only Store WSL...

Running WSL Store version 0.51.2.0, Ubuntu 20.04. Windows 11 build 22543.1000

**Comment by torshind** [comment] 2022-02-26 16:45
Same issue here:

Default Distribution: Ubuntu
Default Version: 2
WSL version: 0.51.3.0
Kernel version: 5.10.93.2
WSLg version: 1.0.30
Windows version: 10.0.22000.527

**Comment by OneBlue** [comment] 2022-03-01 21:15
This is probably the same root cause as #7883, marking as duplicate

**Closed by OneBlue** 2022-03-01 21:15 UTC
Labels: duplicate

**Comment by Ansuel** [comment] 2022-03-01 21:27
@OneBlue but the description is very different... honestly this seems to be more descriptive of the problem... aka only the store version is affected....
