### ISSUE TITLE
run wsl1 error

### ISSUE THREAD

**Issue by jokefrelon** [microsoft/WSL#9588] opened 2023-02-04 16:16 UTC
### Version

Microsoft Windows [版本 10.0.22621.1245]

### WSL Version

- [ ] WSL 2
- [X] WSL 1

### Distro Version

Ubuntu 20.04

### Repro Steps

run wsl1

### Expected Behavior

I want to run wsl1, but can't! And i have installed "windows subsystem for linux" from ms store.

### Actual Behavior

当前计算机配置不支持 WSL1。
若要使用 WSL1，请启用“Windows Subsystem for Linux”可选组件。
Error code: Wsl/Service/CreateInstance/WSL_E_WSL1_NOT_SUPPORTED
当前计算机配置不支持 WSL1。
若要使用 WSL1，请启用“Windows Subsystem for Linux”可选组件。
Error code: Wsl/Service/CreateInstance/WSL_E_WSL1_NOT_SUPPORTED
当前计算机配置不支持 WSL1。
若要使用 WSL1，请启用“Windows Subsystem for Linux”可选组件。
Error code: Wsl/Service/CreateInstance/WSL_E_WSL1_NOT_SUPPORTED
Press any key to continue...

### Diagnostic Logs

![image](https://user-images.githubusercontent.com/43352356/216777386-42149caa-a081-4b46-b70c-4d3a7eeaa657.png)

![image](https://user-images.githubusercontent.com/43352356/216777446-4f02845e-5914-4f55-bed9-9e3430b98b71.png)

I was able to open wsl1 normally before, but after the latest Windows update, I can't use wsl1, only wsl2 can be used, and now I can't open "windows subsystem for linux"

**Comment by jokefrelon** [comment] 2023-02-04 16:19
dism.log
2023-02-04 23:27:01, Info                  DISM   PID=9848 TID=10196 Scratch directory set to 'C:\Users\jokem\AppData\Local\Temp\'. - CDISMManager::put_ScratchDir
2023-02-04 23:27:01, Info                  DISM   PID=9848 TID=10196 DismCore.dll version: 10.0.22621.1 - CDISMManager::FinalConstruct
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   PID=9848 TID=10196 Successfully loaded the ImageSession at "C:\Windows\System32\Dism" - CDISMManager::LoadLocalImageSession
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Provider Store: PID=9848 TID=10196 Found and Initialized the DISM Logger. - CDISMProviderStore::Internal_InitializeLogger
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Successfully created the local image session and provider store. - CDISMManager::CreateLocalImageSession
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: 
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: <----- Starting Dism.exe session ----->
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: 
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Host machine information: OS Version=10.0.22623, Running architecture=amd64, Number of processors=4
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Dism.exe version: 10.0.22621.1
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Executing command line: dism.exe  /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 physical location path: C:\ - CDISMManager::CreateImageSession
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Event name for current DISM session is Global\{7E761BBB-1EA0-49AC-8C89-DF270E0E0A5E} - CDISMManager::CheckSessionAndLock
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Create session event 0x210 for current DISM session and event name is Global\{7E761BBB-1EA0-49AC-8C89-DF270E0E0A5E}  - CDISMManager::CheckSessionAndLock
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Copying DISM from "C:\WINDOWS\System32\Dism" - CDISMManager::CreateImageSessionFromLocation
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 No Sandbox was created, DISM running in-place. - CDISMManager::CreateImageSessionFromLocation
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Successfully loaded the ImageSession at "C:\WINDOWS\System32\Dism" - CDISMManager::LoadRemoteImageSession
2023-02-04 23:27:01, Info                  DISM   DISM Image Session: PID=6956 TID=7292 Instantiating the Provider Store. - CDISMImageSession::get_ProviderStore
2023-02-04 23:27:01, Info                  DISM   DISM OS Provider: PID=6956 TID=7292 Defaulting SystemPath to C:\ - CDISMOSServiceManager::Final_OnConnect
2023-02-04 23:27:01, Info                  DISM   DISM OS Provider: PID=6956 TID=7292 Defaulting Windows folder to C:\Windows - CDISMOSServiceManager::Final_OnConnect
2023-02-04 23:27:01, Info                  DISM   DISM Provider Store: PID=6956 TID=7292 Attempting to initialize the logger from the Image Session. - CDISMProviderStore::Final_OnConnect
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Provider Store: PID=6956 TID=7292 Found and Initialized the DISM Logger. - CDISMProviderStore::Internal_InitializeLogger
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Image session successfully loaded from location: C:\WINDOWS\System32\Dism - CDISMManager::CreateImageSession
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Target image information: OS Version=10.0.22623.1250, Image architecture=amd64
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Image session version: 10.0.22621.1
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Current image session is [ONLINE] - CTransmogManager::GetMode
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Audit Mode: [No] - CTransmogManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 GetProductType: ProductType = [WinNT] - CTransmogManager::GetProductType
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Product Type: [WinNT] - CTransmogManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Product Type ServerNT : [No] - CTransmogManager::Initialize
2023-02-04 23:27:01, Info                  CSI    00000001 Shim considered [l:126]'\??\C:\WINDOWS\Servicing\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_OBJECT_PATH_NOT_FOUND
2023-02-04 23:27:01, Info                  CSI    00000002 Shim considered [l:123]'\??\C:\WINDOWS\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_SUCCESS
2023-02-04 23:27:01, Info                  DISM   DISM Driver Manager: PID=6956 TID=12836 Further logs for driver related operations can be found in the target operating system at %WINDIR%\inf\setupapi.offline.log - CDriverManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Finished initializing the CbsConUI Handler. - CCbsConUIHandler::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 CBS is being initialized for online use. More information about CBS actions can be located at: %windir%\logs\CBS\CBS.log - CDISMPackageManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Loaded servicing stack for online use. - CDISMPackageManager::CreateCbsSession
2023-02-04 23:27:01, Info                  CSI    00000001 Shim considered [l:126]'\??\C:\WINDOWS\Servicing\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_OBJECT_PATH_NOT_FOUND
2023-02-04 23:27:01, Info                  CSI    00000002 Shim considered [l:123]'\??\C:\WINDOWS\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_SUCCESS
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Processing the top level command token(enable-feature). - CPackageManagerCLIHandler::Private_ValidateCmdLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Attempting to route to appropriate command handler. - CPackageManagerCLIHandler::ExecuteCmdLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Routing the command... - CPackageManagerCLIHandler::ExecuteCmdLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Encountered the option "featurename" with value "Microsoft-Windows-Subsystem-Linux" - CPackageManagerCLIHandler::Private_GetPackagesFromCommandLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Encountered an unknown option "featurename" with value "Microsoft-Windows-Subsystem-Linux" - CPackageManagerCLIHandler::Private_GetPackagesFromCommandLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Initiating Changes on Package with values: 5, 7 - CDISMPackage::Internal_ChangePackageState
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 CBS session options=0x40100! - CDISMPackageManager::Internal_Finalize
2023-02-04 23:27:05, Info                  DISM   DISM Package Manager: PID=6956 TID=4768  Error in operation: (null) (CBS HRESULT=0x800736b3) - CCbsConUIHandler::Error
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed finalizing changes. - CDISMPackageManager::Internal_Finalize(hr:0x800736b3)
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed processing package changes with session options - CDISMPackageManager::Internal_ProcessChangesWithOptions(hr:0x800736b3)
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed ProcessChanges. - CPackageManagerCLIHandler::Private_ProcessFeatureChange(hr:0x800736b3)
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed while processing command enable-feature. - CPackageManagerCLIHandler::ExecuteCmdLine(hr:0x800736b3)
2023-02-04 23:27:05, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Further logs for online package and feature related operations can be found at %WINDIR%\logs\CBS\cbs.log - CPackageManagerCLIHandler::ExecuteCmdLine
2023-02-04 23:27:05, Error                 DISM   DISM.EXE: DISM Package Manager processed the command line but failed. HRESULT=800736B3
2023-02-04 23:27:05, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Finalizing CBS core. - CDISMPackageManager::Finalize
2023-02-04 23:27:05, Info                  DISM   DISM Manager: PID=9848 TID=10196 Closing session event handle 0x210 - CDISMManager::CleanupImageSessionEntry
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: Image session has been closed. Reboot required=no.
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: 
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: <----- Ending Dism.exe session ----->
2023-02-04 23:27:05, Info                  DISM   DISM.EXE:

**Comment by jokefrelon** [comment] 2023-02-04 16:22
dism.log
```
2023-02-04 23:27:01, Info                  DISM   PID=9848 TID=10196 Scratch directory set to 'C:\Users\jokem\AppData\Local\Temp\'. - CDISMManager::put_ScratchDir
2023-02-04 23:27:01, Info                  DISM   PID=9848 TID=10196 DismCore.dll version: 10.0.22621.1 - CDISMManager::FinalConstruct
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   PID=9848 TID=10196 Successfully loaded the ImageSession at "C:\Windows\System32\Dism" - CDISMManager::LoadLocalImageSession
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Provider Store: PID=9848 TID=10196 Found and Initialized the DISM Logger. - CDISMProviderStore::Internal_InitializeLogger
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Successfully created the local image session and provider store. - CDISMManager::CreateLocalImageSession
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: 
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: <----- Starting Dism.exe session ----->
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: 
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Host machine information: OS Version=10.0.22623, Running architecture=amd64, Number of processors=4
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Dism.exe version: 10.0.22621.1
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Executing command line: dism.exe  /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 physical location path: C:\ - CDISMManager::CreateImageSession
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Event name for current DISM session is Global\{7E761BBB-1EA0-49AC-8C89-DF270E0E0A5E} - CDISMManager::CheckSessionAndLock
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Create session event 0x210 for current DISM session and event name is Global\{7E761BBB-1EA0-49AC-8C89-DF270E0E0A5E}  - CDISMManager::CheckSessionAndLock
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Copying DISM from "C:\WINDOWS\System32\Dism" - CDISMManager::CreateImageSessionFromLocation
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 No Sandbox was created, DISM running in-place. - CDISMManager::CreateImageSessionFromLocation
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Successfully loaded the ImageSession at "C:\WINDOWS\System32\Dism" - CDISMManager::LoadRemoteImageSession
2023-02-04 23:27:01, Info                  DISM   DISM Image Session: PID=6956 TID=7292 Instantiating the Provider Store. - CDISMImageSession::get_ProviderStore
2023-02-04 23:27:01, Info                  DISM   DISM OS Provider: PID=6956 TID=7292 Defaulting SystemPath to C:\ - CDISMOSServiceManager::Final_OnConnect
2023-02-04 23:27:01, Info                  DISM   DISM OS Provider: PID=6956 TID=7292 Defaulting Windows folder to C:\Windows - CDISMOSServiceManager::Final_OnConnect
2023-02-04 23:27:01, Info                  DISM   DISM Provider Store: PID=6956 TID=7292 Attempting to initialize the logger from the Image Session. - CDISMProviderStore::Final_OnConnect
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Provider Store: PID=6956 TID=7292 Found and Initialized the DISM Logger. - CDISMProviderStore::Internal_InitializeLogger
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   Initialized Panther logging at C:\WINDOWS\Logs\DISM\dism.log
2023-02-04 23:27:01, Info                  DISM   DISM Manager: PID=9848 TID=10196 Image session successfully loaded from location: C:\WINDOWS\System32\Dism - CDISMManager::CreateImageSession
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Target image information: OS Version=10.0.22623.1250, Image architecture=amd64
2023-02-04 23:27:01, Info                  DISM   DISM.EXE: Image session version: 10.0.22621.1
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Current image session is [ONLINE] - CTransmogManager::GetMode
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Audit Mode: [No] - CTransmogManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 GetProductType: ProductType = [WinNT] - CTransmogManager::GetProductType
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Product Type: [WinNT] - CTransmogManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Transmog Provider: PID=6956 TID=12836 Product Type ServerNT : [No] - CTransmogManager::Initialize
2023-02-04 23:27:01, Info                  CSI    00000001 Shim considered [l:126]'\??\C:\WINDOWS\Servicing\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_OBJECT_PATH_NOT_FOUND
2023-02-04 23:27:01, Info                  CSI    00000002 Shim considered [l:123]'\??\C:\WINDOWS\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_SUCCESS
2023-02-04 23:27:01, Info                  DISM   DISM Driver Manager: PID=6956 TID=12836 Further logs for driver related operations can be found in the target operating system at %WINDIR%\inf\setupapi.offline.log - CDriverManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Finished initializing the CbsConUI Handler. - CCbsConUIHandler::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 CBS is being initialized for online use. More information about CBS actions can be located at: %windir%\logs\CBS\CBS.log - CDISMPackageManager::Initialize
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Loaded servicing stack for online use. - CDISMPackageManager::CreateCbsSession
2023-02-04 23:27:01, Info                  CSI    00000001 Shim considered [l:126]'\??\C:\WINDOWS\Servicing\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_OBJECT_PATH_NOT_FOUND
2023-02-04 23:27:01, Info                  CSI    00000002 Shim considered [l:123]'\??\C:\WINDOWS\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1245_none_e95e4cae42cdfd26\wcp.dll' : got STATUS_SUCCESS
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Processing the top level command token(enable-feature). - CPackageManagerCLIHandler::Private_ValidateCmdLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Attempting to route to appropriate command handler. - CPackageManagerCLIHandler::ExecuteCmdLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Routing the command... - CPackageManagerCLIHandler::ExecuteCmdLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Encountered the option "featurename" with value "Microsoft-Windows-Subsystem-Linux" - CPackageManagerCLIHandler::Private_GetPackagesFromCommandLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Encountered an unknown option "featurename" with value "Microsoft-Windows-Subsystem-Linux" - CPackageManagerCLIHandler::Private_GetPackagesFromCommandLine
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Initiating Changes on Package with values: 5, 7 - CDISMPackage::Internal_ChangePackageState
2023-02-04 23:27:01, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 CBS session options=0x40100! - CDISMPackageManager::Internal_Finalize
2023-02-04 23:27:05, Info                  DISM   DISM Package Manager: PID=6956 TID=4768  Error in operation: (null) (CBS HRESULT=0x800736b3) - CCbsConUIHandler::Error
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed finalizing changes. - CDISMPackageManager::Internal_Finalize(hr:0x800736b3)
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed processing package changes with session options - CDISMPackageManager::Internal_ProcessChangesWithOptions(hr:0x800736b3)
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed ProcessChanges. - CPackageManagerCLIHandler::Private_ProcessFeatureChange(hr:0x800736b3)
2023-02-04 23:27:05, Error                 DISM   DISM Package Manager: PID=6956 TID=12836 Failed while processing command enable-feature. - CPackageManagerCLIHandler::ExecuteCmdLine(hr:0x800736b3)
2023-02-04 23:27:05, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Further logs for online package and feature related operations can be found at %WINDIR%\logs\CBS\cbs.log - CPackageManagerCLIHandler::ExecuteCmdLine
2023-02-04 23:27:05, Error                 DISM   DISM.EXE: DISM Package Manager processed the command line but failed. HRESULT=800736B3
2023-02-04 23:27:05, Info                  DISM   DISM Package Manager: PID=6956 TID=12836 Finalizing CBS core. - CDISMPackageManager::Finalize
2023-02-04 23:27:05, Info                  DISM   DISM Manager: PID=9848 TID=10196 Closing session event handle 0x210 - CDISMManager::CleanupImageSessionEntry
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: Image session has been closed. Reboot required=no.
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: 
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: <----- Ending Dism.exe session ----->
2023-02-04 23:27:05, Info                  DISM   DISM.EXE: 

```

**Comment by OneBlue** [comment] 2023-02-07 22:30
Looking at the logs you shared, the error seems to be: ERROR_SXS_ASSEMBLY_NOT_FOUND.

Can you try running: sfc.exe /scannow in an elevated command prompt and share the output ?

**Comment by jokefrelon** [comment] 2023-02-08 07:32
@OneBlue There are no problems
![image](https://user-images.githubusercontent.com/43352356/217463334-34936976-79f4-4eb5-83d0-545dce62e8f5.png)

**Comment by jokefrelon** [comment] 2023-02-08 07:35
But now I updated to win11 dev preview version, wsl1 works fine again. I don't know what the problem was, but it's solved for now

**Comment by OneBlue** [comment] 2023-02-08 20:23
Glad to hear that ! Closing since the issue is solved.

**Closed by OneBlue** 2023-02-08 20:23 UTC
