### ISSUE TITLE
(chinese)word repeat when enter bash

### ISSUE THREAD

**Issue by wywzxxz** [Microsoft/WSL#202] opened 2016-04-15 04:36 UTC
![1](https://cloud.githubusercontent.com/assets/5335612/14551436/9d4e36fc-0305-11e6-9e07-7b481c5d9c4a.png)

As showed in the picture, when enter bash,each chinese word will double.i.e:"版本"become"版版本本"

in the meantime,chinese word display is not complete.ie: instand the complete word "新建文件夹", the above picture shows only"新建文"
![2](https://cloud.githubusercontent.com/assets/5335612/14551460/0a5cbf0c-0306-11e6-8269-1701bcf15326.png)

I think it's relevant to unicode. one unicode use two char,so the unicode word doubles.and inside the bash, it treat unicode as char, so the length halved.

**Comment by Arthur2e5** [comment] 2016-04-26 21:35
> chinese words

Chinese characters.

> one unicode use two char,so the unicode word doubles.

Inside Linux, wchar_t is 4 bytes long.

> and inside the bash, it treat unicode as char, so the length halved.

Try cygwin/msys or some Linux VM. This is not a Linux-side problem. Readline is (of course) able to do this correctly.

You may want to reword your issue so you are actually blaming conhost. (Ah, another problem with multicol... deb821936, madoko131, UoW202, who's next?)

As a friendly suggestion, try starting UoW using the shortcut in the start menu too. That shortcut does chcp 65001 for you.

**Comment by Arthur2e5** [comment] 2016-05-08 16:08
(And why are you closing this now?... If it really goes wrong this way, keep it open.)

**Comment by sunilmut** [comment] 2016-05-20 19:54
@wywzxxz - Do you mind opening this issue since it looks like a legitimate bug in conhost?

**Comment by Wuvist** [comment] 2016-10-02 07:40
I can't reproduce this bug using cmd.exe, however it only appears when using ConEmu with Build 14936.

It was fine when using Build 14388 to Windows 10 Anniversary Update

**Comment by bitcrazed** [comment] 2018-05-22 22:13
Thanks for the discussion.

Closing this issue since:
1. This is a very old bug and I believe it's been fixed since it was posted. If not, please let us know!
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Closed by bitcrazed** 2018-05-22 22:13 UTC
Labels: console, localization
