### ISSUE TITLE
WSL takes 2 minutes to run a simple PowerShell script

### ISSUE THREAD

**Issue by wzis** [microsoft/WSL#10629] opened 2023-10-12 23:11 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.2428]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Oracle Linux Server release 9.1

### Other Software

I'm running a PowerShell script in WSL. Every time it needs to wait 2 minutes to really get started.

### Repro Steps

 Set-ExecutionPolicy  -ExecutionPolicy Bypass -Scope CurrentUser

[gwz@asus whc]$ date;./bios.ps1;date
Fri Oct 13 09:05:45 AM AEDT 2023
Computer Name                  : ASUS
BIOS                           : S5402ZA.307
Version                        : _ASUS_ - 1072009
Manufacturer                   : American Megatrends International, LLC.
SMBIOSBIOS Version             : S5402ZA.307
Service Tag                    : N4N0CV093754164

Fri Oct 13 09:07:45 AM AEDT 2023

### Expected Behavior

It should avoid the long delay.

### Actual Behavior

[gwz@asus whc]$ date;./bios.ps1;date
Fri Oct 13 09:05:45 AM AEDT 2023
Computer Name                  : ASUS
BIOS                           : S5402ZA.307
Version                        : _ASUS_ - 1072009
Manufacturer                   : American Megatrends International, LLC.
SMBIOSBIOS Version             : S5402ZA.307
Service Tag                    : N4N0CV093754164

Fri Oct 13 09:07:45 AM AEDT 2023

**Comment by wzis** [comment] 2023-10-14 00:44
[WslLogs-2023-10-14_11-37-41.zip](https://github.com/microsoft/WSL/files/12900700/WslLogs-2023-10-14_11-37-41.zip)
Please find the log. Thanks

**Comment by wzis** [comment] 2023-10-14 02:05
[WslLogs-2023-10-14_13-01-44.zip](https://github.com/microsoft/WSL/files/12901356/WslLogs-2023-10-14_13-01-44.zip)
This log should be good. Early one does not cover the whole command run life.

**Comment by wzis** [comment] 2023-10-18 21:47
The issue is very obvious and easy to reproduce.

**Comment by OneBlue** [comment] 2023-10-19 16:54
@wzis: Can you share the content of the powershell script you're trying to run ?

**Comment by wzis** [comment] 2023-10-19 22:00
[root@asus whc]# cat bios.ps1
#!/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
#!/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe Set-ExecutionPolicy BYPASS  -Scope LocalMachine
# WMI query to list all properties and values of the Win32_BIOS class
# This PowerShell script was generated using the WMI Code Generator, Version 1.30
# http://www.robvanderwoude.com/updates/wmigen.html

param( [string]$strComputer = "." )

$colItems = get-WmiObject -class "Win32_BIOS" -namespace "root\CIMV2" -computername $strComputer

foreach ($objItem in $colItems) {
write-host "Computer Name                  :" $env:computername
write-host "BIOS                           :" $objItem.Name
write-host "Version                        :" $objItem.Version
write-host "Manufacturer                   :" $objItem.Manufacturer
write-host "SMBIOSBIOS Version             :" $objItem.SMBIOSBIOSVersion
write-host "Service Tag                    :" $objItem.SerialNumber
write-host
}

**Comment by wzis** [comment] 2023-10-20 02:38
Here is a very simple example:
[root@asus whc]# date;./ps1.ps1;date
Thu Oct 19 06:19:53 PM AEDT 2023


    Directory: \\wsl.localhost\OracleLinux_9_1\home\gwz\myapp\whc


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------         1/16/2023   9:13 AM            770 time.ps1
------         1/16/2023   9:13 AM          55912 win11.bios.ps1
------         1/16/2023   9:13 AM             56 hc.info.SuSE
------         1/16/2023   9:13 AM            155 LICDEF.hidecode
------         1/16/2023   9:13 AM            147 LICDEF.test
------         1/16/2023   9:13 AM            225 PKGBITS
------         1/16/2023   9:13 AM         219280 win10.runas.exe
------         1/16/2023   9:13 AM          17920 runas.exe
------         1/16/2023   9:13 AM            412 hexdc.b
------         1/16/2023   9:13 AM           2971 wexec.b
------         1/16/2023   9:13 AM             57 hc.info.Debian.mips64
------         1/16/2023   9:13 AM         112640 HC-src.1.0_HP-UX.ia64-m64.tar
------         1/16/2023   9:13 AM            815 ARCH
------         1/16/2023   9:13 AM             53 hc.info.RHEL.ppc64
------         1/16/2023   9:13 AM             55 hc.info.Debian.mips
------         1/16/2023   9:13 AM           1162 app.c
------         1/16/2023   9:13 AM           5904 hexdc_base.b
------         1/16/2023   9:13 AM          79872 HC-src.1.0_SunOS.sparc-m64.tar
------         1/16/2023   9:13 AM             96 LICDEF.assh
------         1/16/2023   9:13 AM            147 LICDEF
------         1/16/2023   9:13 AM           2952 binpntnl.b
------         1/16/2023   9:13 AM              4 VERSION
------         1/16/2023   9:13 AM             54 hc.info
------         1/16/2023   9:13 AM            934 info.ps1
------         1/16/2023   9:13 AM           3210 mchid.c
------         1/16/2023   9:13 AM         129336 rl5.login
------         1/16/2023   9:13 AM           8477 hexdc.e
------         1/16/2023   9:13 AM             54 hc.info.RHEL
------         1/16/2023   9:13 AM             40 hc.info.AIX
------         1/16/2023   9:13 AM          42181 hcKey
------         1/16/2023   9:13 AM           1166 Makefile.HP
------         1/16/2023   9:13 AM        2622352 chrome.exe
------         1/16/2023   9:13 AM           5403 thcp.b
------         1/16/2023   9:13 AM             48 hc.info.AIX.powerpc
------         1/16/2023   9:13 AM            148 LICDEF.fcrypt
------         5/29/2022  10:36 AM           3482 Hcpntnl.b
------         1/16/2023   9:13 AM            112 shmain
------         1/16/2023   9:13 AM          46488 hc.e
------         1/16/2023   9:13 AM             49 hc.info.SunOS.i386
------         1/16/2023   9:13 AM          60368 sec.write.exe
------         1/16/2023   9:13 AM         125528 gpggway.lnx.sec
------         1/16/2023   9:13 AM          81920 HC-src.1.0_RHEL-Linux_NOFA.x86_64-m64.tar
------         1/16/2023   9:13 AM           1726 hc_base.b
------         1/16/2023   9:13 AM          47608 sec.bios.ps1
------         1/16/2023   9:13 AM            872 ARCHNO
------         1/16/2023   9:13 AM         204800 WordpadFilter.dll
------         1/16/2023   9:13 AM           1150 computerinfo.ps1
------         1/16/2023   9:13 AM           5138 lichc.c
------         1/16/2023   9:13 AM           3608 binp.b
------         1/16/2023   9:13 AM         967392 s.wordpad.exe
------          4/4/2023  10:24 AM           4918 hcpnt.b
------         1/16/2023   9:13 AM        3063808 wordpad.exe
------         1/16/2023   9:13 AM             50 hc.info.SunOS.sparc
------         1/16/2023   9:13 AM           3657 whcpntnl.b
------         1/16/2023   9:13 AM           3578 binpnt.b
------         1/16/2023   9:13 AM             51 hc.info.HP-UX.ia64
------         1/16/2023   9:13 AM            150 LICDEF.wzcon
------         1/16/2023   9:13 AM          81920 HC-src.1.0_RHEL-Linux.x86_64-m64.tar
------         1/16/2023   9:13 AM          28672 write.exe
------         1/16/2023   9:13 AM          51200 HC-src.1.0.tar
------         1/16/2023   9:13 AM             54 hc.info.RHEL.x86_64
------         1/16/2023   9:13 AM             61 hc.info.Ubuntu.ppc64le
------         1/16/2023   9:13 AM             60 hc.info.Ubuntu.x86_64
------         1/16/2023   9:13 AM            961 bios.ps1
------         1/16/2023   9:13 AM            932 Makefile.UNIX
------         1/16/2023   9:13 AM             98 LICDEF.asftp
------         1/16/2023   9:13 AM            104 LICDEF.WZSysGuard
------         1/16/2023   9:13 AM          24160 util
------         1/16/2023   9:13 AM         185344 app
------          4/4/2023  10:24 AM           3843 hcpntnl.b
------         1/16/2023   9:13 AM            152 LICDEF.passwd
------         1/16/2023   9:13 AM             55 hc.info.HP-UX.9000
------        10/19/2023   6:19 PM             86 ps1.ps1
------         1/16/2023   9:13 AM             57 hc.info.SuSE.powerpc
------         1/16/2023   9:13 AM        1134400 win11.wordpad.exe
------         5/29/2022  10:36 AM           4173 hcpnt.b~
------         1/16/2023   9:13 AM          92160 HC-src.1.0_AIX.powerpc-m64.tar
------         1/16/2023   9:13 AM             74 hc.info.Fedora.aarch64
------         1/16/2023   9:13 AM             59 hc.info.Debian.mips64el
------         1/16/2023   9:13 AM             57 hc.info.RHEL.arm
------         1/16/2023   9:13 AM             55 hc.info.RHEL.ppc64le
------         1/16/2023   9:13 AM            913 hcKey.c
------         1/16/2023   9:13 AM           6144 hc_base.e
------         1/16/2023   9:13 AM             74 hc.info.Fedora.riscv64
------         1/16/2023   9:13 AM          56272 sec.wordpad
------         1/16/2023   9:13 AM             30 TS
------         1/16/2023   9:13 AM        1248072 win11.chrome.sec
------          4/4/2023  10:24 AM           4946 hcp.b
------         1/16/2023   9:13 AM         369421 aix61.login
------         1/16/2023   9:13 AM             58 hc.info.Fedora.arm
------         1/16/2023   9:13 AM           1124 Makefile.AIX
------         1/16/2023   9:13 AM             69 Makefile
------         1/16/2023   9:13 AM         352277 aix61.passwd
------         1/16/2023   9:13 AM             56 hc.info.SuSE.x86_64
------         1/16/2023   9:13 AM          47608 win10.bios.ps1
------         1/16/2023   9:13 AM            112 py1
------         1/16/2023   9:13 AM            533 ep1
------         1/16/2023   9:13 AM            218 php1
------         1/16/2023   9:13 AM            486 erb
------          7/5/2022  11:47 AM          53412 stub.c
------         1/16/2023   9:13 AM         237256 sec.runas.exe
------         1/16/2023   9:13 AM           2536 hc.b
------         1/16/2023   9:13 AM             57 hc.info.Debian.mipsel
------         1/16/2023   9:13 AM           1309 README
------         1/16/2023   9:13 AM            186 hcLic


Thu Oct 19 06:22:04 PM AEDT 2023
[root@asus whc]# cat ps1.ps1
#!/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
Get-ChildItem -Path .
[root@asus whc]#

**Comment by wzis** [comment] 2023-10-26 07:22
Any updates?

**Comment by pmartincic** [comment] 2023-10-26 17:17
I can't reproduce this on my environment. What happens if you change the interpreter from `powershell.exe` to `powershell.exe -noprofile`?

**Comment by pmartincic** [comment] 2023-10-26 17:33
I see a few timeouts in the logs that make me suspect if you have some antivirus/malware running. It's behavior I've seen in the past when defender was attempting to access files from \\wsl.localhost\DISTRO\ with the wrong token. If software is attempting to access \\wsl.localhost\DISTRO\ as user that is not logged in it will hit multiple timeouts (multiples of 20 seconds).

**Comment by wzis** [comment] 2023-10-27 00:16
I tried to add the -noprofile, but it's still same.

**Comment by wzis** [comment] 2023-10-27 00:29
From the strace output, it took the 2 minutes at the following syscall:
11:24:06 poll([{fd=0, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=4, events=POLLIN}], 5, -1) = 1 ([{fd=7, revents=POLLIN}])
11:26:06 read(7, "\r", 4096)            = 1

**Comment by wzis** [comment] 2023-10-27 00:44
The followings are from another session:

169   11:30:35 accept4(4, {sa_family=AF_VSOCK, svm_cid=VMADDR_CID_HOST, svm_port=0xf6c8e14c, svm_flags=0}, [16], SOCK_CLOEXEC) = 7

169   11:30:35 read(7, "\33[6n", 4096)  = 4
169   11:30:35 write(1, "\33[6n", 4)    = 4
169   11:30:35 poll([{fd=0, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=4, events=POLLIN}], 5, -1) = 1 ([{fd=0, revents=POLLIN}])
169   11:30:35 read(0, "\33[30;1R", 4096) = 7
169   11:30:35 write(6, "\33[30;1R", 7) = 7
169   11:30:35 poll([{fd=0, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=4, events=POLLIN}], 5, -1) = 1 ([{fd=7, revents=POLLIN}])
169   11:30:35 read(7, "\33[m\33]0;C:\\Windows\\System32\\Windo"..., 4096) = 71
169   11:30:35 write(1, "\33[m\33]0;C:\\Windows\\System32\\Windo"..., 71) = 71
169   11:30:35 poll([{fd=0, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=4, events=POLLIN}], 5, -1) = 1 ([{fd=7, revents=POLLIN}])
169   11:32:35 read(7, "\n", 4096)      = 1
169   11:32:35 write(1, "\n", 1)        = 1

**Comment by wzis** [comment] 2023-10-27 02:38
I tried on another laptop's WSL2 env, that one is running ok without the 2 minutes delay, and compare the strace outputs, found the problem one has the socket call "socket(AF_VSOCK, SOCK_STREAM|SOCK_CLOEXEC, 0) = 4", why the good one doesn't.

**Comment by pmartincic** [comment] 2023-10-27 18:05
Have you tried disabling whatever antimalware/antivirus you have? As before, I suspect this is due to antimalware/antivirus you have running/installed. You're running a powershell script from a path hosted from within WSL2. I suspect that if you put the script in a path on the host it would run without delay. This looks like an issue we've seen before. Based on what I saw in the logs you collected I'm going to close this. If you disable anything you have running that resembles antimalware/antivirus, and this still happens, please reopen the issue.

**Closed by pmartincic** 2023-10-27 18:05 UTC

**Comment by wzis** [comment] 2023-10-27 22:32
right, it's the avast antivirus software that caused the long delay.
