### ISSUE TITLE
docker run mysql error in mirror mode

### ISSUE THREAD

**Issue by EZzer0** [microsoft/WSL#10584] opened 2023-10-03 08:31 UTC
### Windows Version

10.0.22621.2361

### WSL Version

 2.0.2.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

Arch

### Other Software

docker mysql

### Repro Steps

1. install wsl2
2. setting .wslconfig 
```
[experimental]
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
```
3.install docker 
4. docker run -itd --name mysql-test -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql
5. windows app connect mysql
6. output ：connect ECONNREFUSED 

### Expected Behavior

Expose the 3306 interface through docker. 
Connecting to 127.0.0.1:3306 should be able to connect to the database.

### Actual Behavior

All address displayed using the ip addr command cannot connect to the database.

Add hostAddressLoopback=true
No change

Do not use `mirrored` mode

docker mysql can connect

**Comment by keith-horton** [comment] 2023-10-05 00:37
Hi there. Can you please provide some specific details about your scenario?

How is docker setting up mysql in WSL?
-- is it listing on a port in the root namespace and forwarding it to another port in a different namespace where mysql is running?
What IP address and port is the windows app using to try to connect to mysql?
For mirroring, you should use 127.0.0.1 to connect to the container.

Thanks!

**Comment by zcobol** [comment] 2023-10-05 02:45
With `networkingmode=mirrored ` port `3306` is not being exported to Windows side. If the old way is being used (NAT) then mysql container running inside WSL container can be accessed from Windows over `127.0.0.1:3306`:

```
LocalAddress   : ::1
LocalPort      : 3306
RemoteAddress  : ::
RemotePort     : 0
State          : Listen
AppliedSetting :
OwningProcess  : 15592
CreationTime   : 10/4/2023 7:25:34 PM
OffloadState   : InHost

LocalAddress   : 127.0.0.1
LocalPort      : 3306
RemoteAddress  : 0.0.0.0
RemotePort     : 0
State          : Listen
AppliedSetting :
OwningProcess  : 15592
CreationTime   : 10/4/2023 7:25:34 PM
OffloadState   : InHost

```

![mysql_conn_test](https://github.com/microsoft/WSL/assets/104515072/1ee191c5-99a0-4ad6-91d5-d9479efc2841)

With mirrored mode the above test fails.

**Comment by EZzer0** [comment] 2023-10-05 12:09
> 嘿，你好。您能否提供有关您的方案的一些具体细节？
> 
> Docker如何在WSL中设置mysql？ -- 它是否在根命名空间中的端口上列出并将其转发到运行 MySQL 的不同命名空间中的另一个端口？ Windows应用程序使用什么IP地址和端口来尝试连接到mysql？对于镜像，应使用 127.0.0.1 连接到容器。如果要使用分配给 Windows 的 IP 地址之一（已镜像到容器）进行连接，则需要在 .wslconfig 文件中的 [实验] 下设置 hostAddressLoopback=true。
> 
> 谢谢！

thanks, I tried 'hostAddressLoopback=true' No effect
Port 3306 is occupied in wsl
Port 3306 does not appear occupied in Windows

**Comment by keith-horton** [comment] 2023-10-05 21:26
OK. We are working Docker to make this more seamless.

Can you add ignoredPorts=3306 to your .wslconfig file under [experimental]?

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-configuration-settings

**Comment by EZzer0** [comment] 2023-10-06 05:11
> 还行。我们正在与Docker合作，使这更加无缝。
> 
> 您可以将忽略的端口= 3306添加到[实验]下的.wslconfig文件中吗？
> 
> https://learn.microsoft.com/en-us/windows/wsl/wsl-config#experimental-configuration-settings

I tried it and it doesn't work on my computer

**Comment by shigenobuokamoto** [comment] 2023-10-06 06:15
can you try docker-proxy?

/etc/docker/daemon.json
```
{
    "iptables": false
}
```
restart docker daemon. (`systemctl restart docker` or `wsl --shutdown`)

**Comment by EZzer0** [comment] 2023-10-06 10:37
> iptables
Sorry, my attempt to do this failed

**Comment by CatalinFetoiu** [comment] 2024-06-27 17:53
This is a duplicate of https://github.com/microsoft/WSL/issues/10494 - in both issues docker run -p is used to setup port forwarding and accessing the forwarded port from Windows using 127.0.0.1 does not work

we are working with Docker team to address this in the Docker Engine

/dupe #10494

**Closed** 2024-06-27 17:54 UTC
Labels: duplicate, network
