### ISSUE TITLE
WSL Installation Issue Leading to PC Boot Failure

### ISSUE THREAD

**Issue by Blackhammer98** [microsoft/WSL#11890] opened 2024-08-07 10:32 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3958]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

2

### Other Software

Docker Desktop latest version , i tried many time but didn't succeed , I am facing same problem with WSL installation and Docker Desktop installation after installation when its time to reboot  my machine failed to reboot or it takes lots of time with blank screen and i have to start it with safe mode

### Repro Steps

Here are the steps I followed and the issues encountered:

WSL Installation Attempt:
Initially, I attempted to install WSL via the terminal using the command wsl --install.
Subsequently, I also tried installing it through the Microsoft Store.

Post-Installation Issue:
After completing the installation process, I restarted my PC as prompted.
Upon restarting, my computer gets stuck on a blank screen and does not proceed to the Windows login screen.
One more thing i want to add that when on restarting its start upgrading but after completing 30% it stopped and again shows restart.

Troubleshooting Attempts:
Enabled the 'Virtual Machine Platform' and 'Windows Subsystem for Linux' features in Windows Features.
Despite these adjustments, the issue persists, and my PC fails to restart normally.

### Expected Behavior

I am expecting every thing what WSL provides .e.g. :

New Terminal Options:
A new terminal application for the installed Linux distribution (e.g., Ubuntu, Debian) will be available.
You will have access to a Linux file system that can be navigated using the terminal.

Linux Command Line Tools:
I can run a wide range of Linux command-line tools and applications directly on Windows, such as bash, grep, sed, awk, and more.

Windows Terminal Integration:
If you have the Windows Terminal app installed, you can manage multiple profiles for different WSL distributions, PowerShell, Command Prompt, and more from a single interface.
This is what i know about after installing WSL , what it will provides me

### Actual Behavior

What i faced actually is while installing weather its WSL or Docker Desktop all installation process completed without any single error but after installation when it comes to  reboot my machine its start updating and took time when update reaches at 30% , my machine shows me restart loader and after restart it just blank screen nothing happening on screen no cursor nothing . I tried many times but every time I faced same issue

**Comment by Blackhammer98** [comment] 2024-08-07 10:45
This files are related with WSL logs all are in WSL log folder which i obtained as instructed .
[wslsupport-proxy.txt](https://github.com/user-attachments/files/16522180/wslsupport-proxy.txt)
[acl.txt](https://github.com/user-attachments/files/16522181/acl.txt)
[appxpackage.txt](https://github.com/user-attachments/files/16522182/appxpackage.txt)
[bcdedit.txt](https://github.com/user-attachments/files/16522183/bcdedit.txt)
[HKCU.txt](https://github.com/user-attachments/files/16522184/HKCU.txt)
[HKLM.txt](https://github.com/user-attachments/files/16522187/HKLM.txt)
[optional-components.txt](https://github.com/user-attachments/files/16522188/optional-components.txt)
[P9NP.txt](https://github.com/user-attachments/files/16522189/P9NP.txt)
[Winsock2.txt](https://github.com/user-attachments/files/16522190/Winsock2.txt)
[wpr.txt](https://github.com/user-attachments/files/16522191/wpr.txt)
[wslservice.txt](https://github.com/user-attachments/files/16522192/wslservice.txt)
[wslsupport-impl.txt](https://github.com/user-attachments/files/16522193/wslsupport-impl.txt)

**Comment by OneBlue** [comment] 2024-08-08 18:43
Hi @Blackhammer98: unfortunately WSL doesn't control the Windows update / feature enablement process after reboot. Does manually enabling the virtual machine platform component give the same result ?

**Comment by Blackhammer98** [comment] 2024-08-10 12:08
Yes ,  even after manually enabling those features my unable to reboot .

**Comment by Blackhammer98** [comment] 2024-08-10 12:28
*PC

**Comment by OneBlue** [comment] 2024-08-12 17:59
Ok in this case, that's where the problem is. This might be caused by a hardware / driver issue at the Windows level. Unfortunately this isn't something that WSL can solve. 

Closing since the issue isn't caused by WSL.

**Closed by OneBlue** 2024-08-12 17:59 UTC
