### ISSUE TITLE
WSL2 sources .bash_profile twice, once without Windows PATH entries in PATH

### ISSUE THREAD

**Issue by XanderXAJ** [microsoft/WSL#10415] opened 2023-08-23 20:39 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.2134]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04.2 LTS

### Repro Steps

I discovered this while trying to passthrwough the Windows host ssh-agent through to Ubuntu WSL using `socat` in Linux and `npiperelay.exe` in Windows, with a fallback to a standard Linux ssh-agent if either command wasn't installed. However, when cold-launching the WSL distro, I found it would always fall back to the Linux ssh-agent. Upon closer expamination, removing all of my dotfiles and making a simple test case, I found that my `.bash_profile` was getting sourced twice -- with one of those times not having any Windows PATHs imported -- so it's possibly that my issue is racy.

I'm not sure if this is a bug, a side effect of WSL's implementation, or something I've done, but since starting the Ubuntu 22.04 WSL distro seems to run `.bash_profile` twice when it starts, it's surprising and tripping up my expectations

1. Create a simple `.bash_profile` in WSL that prints the PATH and echoes `.bash_profile` to STDOUT:

    ```shell
    echo "$(date) PATH: $PATH" >> ~/path_debug.log
    echo .bash_profile
    ```

2. In PowerShell on the host, shutdown WSL:

    ```shell
    wsl --shutdown
    ```

3. Launch WSL:

    ```shell
    wsl -d Ubuntu
    ````

4. Note that it prints `.bash_profile` **once**.
5. Note that the `~/path_debug.log` contains **two** entries, **only one with Windows paths**:

    ```shell
    $ cat ~/path_debug.log
    Wed Aug 23 21:15:44 BST 2023 PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/OpenSSH/:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/Program Files (x86)/VMware/VMware Player/bin/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:<snip, you get the idea>
    Wed Aug 23 21:15:44 BST 2023 PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    ```

Further shells opened in the WSL distro will only source `.bash_profile` once and will always have Windows PATH entries available. Once the distro is shutdown, the issue will be reproducible again.

### Expected Behavior

When launching the WSL distro, Windows PATH entries are always available.

My biggest bugbear is that the Windows PATHs aren't always available. However, I was surprised to see that my profiles were being sourced twice, perhaps because my mental model treats WSL as SSH-like. I couldn't find any docs about this behaviour.

### Actual Behavior

When launching a WSL distro, `.bash_profile` was launched twice, with the Windows PATH entries only being added to the PATH in one of the bash invocations (the one that would become my interactive shell).

### Diagnostic Logs

I used a more advanced of the debug script above when trying to get to the bottom of this:

```shell
function path_debug() {
	cat <<-EOF >> ~/path_debug.log
	---
	$(date): $1
	BASH_ARGV0: $BASH_ARGV0
	\$-: $-
	SHLVL: $SHLVL
	PATH: $PATH
	npipereplay.exe: $(type npiperelay.exe)
	EOF
	echo "BASHPID: $BASHPID" >> ~/path_debug.log
	echo "PPID: $PPID" >> ~/path_debug.log
}

path_debug "BASH_PROFILE"
echo ".bash_profile"
```

Which yields the following output:

```shell
$ cat ~/path_debug.log
---
Wed Aug 23 21:36:01 BST 2023: BASH_PROFILE
BASH_ARGV0: -bash
$-: himBH
SHLVL: 1
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/OpenSSH/:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:<snip again>
npipereplay.exe: npiperelay.exe is /mnt/c/Users/xande/go/bin/npiperelay.exe
BASHPID: 393
PPID: 391
---
Wed Aug 23 21:36:01 BST 2023: BASH_PROFILE
BASH_ARGV0: -bash
$-: himBH
SHLVL: 1
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npipereplay.exe:
BASHPID: 437
PPID: 392
```

This reveals both shells are login shells and that one did not launch the other. The parent PIDs (PPIDs) tend to be closely adjacent.

**Comment by ThaDaVos** [comment] 2023-08-24 07:55
Just to note - I am also using the SSH agent from Windows but I don't see my `.bash_profile` being sourced twice - have you tried with a clean distro install?

**Comment by XanderXAJ** [comment] 2023-08-26 09:33
Thanks for the suggestion. I'll take a look.

**Comment by XanderXAJ** [comment] 2023-08-26 10:23
I didn't want to obliterate my current Ubuntu install for convenience's sake, so instead I installed a whole bunch of new distros to test on. So all of the following distros are completely fresh installs.

I *can* reproduce the issue (double source of `.bash_profile`) on:

- Ubuntu 22.04.2 LTS (the pinned version -- in my opening report I'm using the unpinned "Ubuntu" package)
- Ubuntu 20.04.6 LTS
- Ubuntu 18.04.6 LTS

I **could not** reproduce the issue (single source of `.bash_profile`) on:

- Debian (12.0)
- openSUSE Leap 15.5
- openSUSE Leap 15.4
- openSUSE Tumbleweed

I checked both before and after package manager updates on all systems.

It's worth re-iterating the double-source only happens when the VM is booting. Opening a new session in an existing VM will result in a single source of `.bash.profile` as expected.

One more thing I noticed: on the Ubuntu distros, bash always has q1uite a high PID and it isn't consistent between VM boots:

```
BASHPID: 661
PPID: 531
```

Whereas Debian and openSUSE have quite low PIDs were deterministic in my limited testing (bash was always PID 9, its parent always PID 8):

```
BASHPID: 9
PPID: 8
```

So perhaps it is related to a difference in how the distro initialises?

It's looking like it might be distro specific -- I only see the issue in all of the Ubuntu distros. I don't know if that means this isn't WSL-related, but would appreciate any guidance on what to do all the same. 🙂

**Comment by OneBlue** [comment] 2023-08-29 21:36
WSL doesn't change bash's logic so this is probably caused by something else. What might help would be to print which processes are calling bash into your log file to figure out where is bash called from.

Closing since this isn't a WSL issue.

**Closed by OneBlue** 2023-08-29 21:36 UTC
