### ISSUE TITLE
Why ubuntu.exe command redirects me to "~" directory and how can I fix it?

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/WSL#2587] opened 2017-10-22 09:37 UTC
* Your Windows build number:  Windows 10 Version: 1709 Build: 16299.19

When I open windows cmd in "this" directory and run `bash` command it opens WSL in "this" directory where I open cmd. But when I runnnig `ubuntu` command it opens WSL in Ubuntu home "~" directory.

I record a Gif to demonstration:

![wsl-2](https://user-images.githubusercontent.com/20873402/31860660-5be2e7c6-b6d2-11e7-91cc-2de446926610.gif)

How can I fix this?

**Comment by onomatopellan** [comment] 2017-10-22 10:53
It's weird because `ubuntu run bash` works.

**Comment by Zx-EvM** [comment] 2017-10-22 10:54
@onomatopellan can you reproduce this issue on your machine?

**Comment by onomatopellan** [comment] 2017-10-22 10:57
Yes. Typing `ubuntu` goes to /home/user folder. But typing `ubuntu run bash` goes to the directory from it's called.

**Comment by Zx-EvM** [comment] 2017-10-22 11:01
@onomatopellan `ubuntu run bash` runs bash not ubuntu. `chsh` works correctly only with `ubuntu.exe`.

**Comment by onomatopellan** [comment] 2017-10-22 11:02
@Zx-EvM `ubuntu run bash` runs bash inside ubuntu distro. Try `ubuntu run chsh` then.

**Comment by Zx-EvM** [comment] 2017-10-22 11:04
@onomatopellan hm, so it's weird:

![wsl-3](https://user-images.githubusercontent.com/20873402/31861216-25cc4ac2-b6de-11e7-9a48-7add6cf0db19.gif)

**Comment by onomatopellan** [comment] 2017-10-22 11:08
@Zx-EvM You should read this https://msdn.microsoft.com/en-us/commandline/wsl/wsl-config
Even if you have multiple distros installed `bash` will open the default one that is listed with `wslconfig.exe /l`

**Comment by Zx-EvM** [comment] 2017-10-22 11:11
@onomatopellan 

![wsl-4](https://user-images.githubusercontent.com/20873402/31861264-0a599ed8-b6df-11e7-8d5c-23be85df5377.gif)

and `wslconfig.exe /l` output:

```
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
```

**Comment by onomatopellan** [comment] 2017-10-22 11:15
@Zx-EvM what says if you try `wsl.exe` instead of `bash.exe`

**Comment by Zx-EvM** [comment] 2017-10-22 11:18
@onomatopellan it will run `zsh`. Thus it runs ubuntu.

**Comment by onomatopellan** [comment] 2017-10-22 11:48
it's a duplicate of #2570 
The team tagged it as a launcher bug.

**Comment by Zx-EvM** [comment] 2017-10-22 11:50
@onomatopellan thanks. Your this https://github.com/Microsoft/BashOnWindows/issues/2587#issuecomment-338469205 comment is helps for me. We can just set "WSL OS" as default and run it with "special default WSL OS runner".

**Comment by MikeGitb** [comment] 2017-11-10 07:33
Just want to add my +1 to this bug. That behavior is really annoying and while setting the default distro works, it doesn't help if you want to use multiple different distros at the same time.

**Comment by benhillis** [comment] 2018-05-24 16:19
Duplicate of #2385.

**Closed by benhillis** 2018-05-24 16:19 UTC
Labels: launcher
