### ISSUE TITLE
Installing, this may take a few minutes... 远程过程调用失败。

### ISSUE THREAD

**Issue by Snortom** [microsoft/WSL#5951] opened 2020-09-20 03:24 UTC
After installation, the following error appears.

Installing, this may take a few minutes...
远程过程调用失败。
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:

**Comment by xa0082249956** [comment] 2020-09-20 04:52
Duplicate of #5907.

**Closed** 2020-09-20 15:48 UTC
