### ISSUE TITLE
Yeoman takes 1 minute 11 seconds to run in WSL2

### ISSUE THREAD

**Issue by danecreekphotography** [microsoft/WSL#5413] opened 2020-06-15 21:50 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Your Distribution version: Release: 20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019
```

# Steps to reproduce

Follow the instructions at https://code.visualstudio.com/api/get-started/your-first-extension for creating your first VS Code extension:

1. `npm install -g yo generator-code`
2. `yo code`

#  Expected behavior

Yeoman intro UI and first prompt shows up reasonably quickly. (In a PowerShell command line on the same machine it shows up in 3 seconds).

# Actual behavior

It takes 1 minute 11 seconds for the UI and first prompt to show up.

# Additional details

I'm running this command in the `~` directory of my Ubuntu instance.

**Comment by craigloewen-msft** [comment] 2020-06-15 22:01
Hmm I'm not able to reproduce this on my instance. 

![gif](https://user-images.githubusercontent.com/42221804/84710269-b9d45e00-af18-11ea-9517-56943389b419.gif)

To me this indicates that this isn't a systematic problem, but might instead be specific to your machine. If you run `strace yo code` you can see a running output of what system calls are being executed (i.e: The files and resources that are being accessed) and that might help indicate to you where the bottleneck is, my guess is that it's lying somewhere in your Linux environment.

I'll close this issue out for our bookkeeping as I don't believe it's something that we specifically can help with you on the WSL team (since it doesn't seem to be caused by WSL), but I'm happy to follow up on more troubleshooting ideas either here or on Twitter. Thanks for filing this!

**Closed by craigloewen-msft** 2020-06-15 22:01 UTC

**Comment by danecreekphotography** [comment] 2020-06-15 22:04
WHAT SORCERY DID YOU DO I JUST RAN THIS AND IT RAN INSTANTLY ARGH.

I swear. I've had this for more than a week. Bitterly complained to one of my engineers about how slow this was and she couldn't understand why I was complaining (she was on a Mac).

Ran `strace you code` to get stats and it... just worked.

Then ran `yo code` and... it just worked.

🤦‍♂️

**Comment by craigloewen-msft** [comment] 2020-06-15 22:31
Of course once you go through the process of reporting the problem it goes away. :) Glad that it works now!

**Comment by therealkenc** [comment] 2020-06-15 22:51
The behavior can be highly sensitive to nonobvious externalities. Analogy unrelated #5223. The usual suspect is some software/package/subcomponent that uses `$PATH` as a hint to go looking for stuff. Once anything goes `stat(2)ing` or `getdent(2)ing` your `/mnt/c`, because it couldn't find what it was looking for fast and early in the `$PATH` list, all performance bets are off even if it seems like the basic operation was performed off `$HOME`. If that happens in a loop, you get a tragic wallclock time. That might or might not be what happened to you (and we'll probably never know), but it happens enough. These are difficult to track down, because if you breathe on your setup (which devs do all day every day) then `/mnt/c` never gets touched and performance magically improves by a few orders of magnitude.

**Comment by danecreekphotography** [comment] 2020-06-15 23:03
@therealkenc I wonder if just running `strace` was enough to do something :( Thanks for the possible explanation.

**Comment by MarcTer** [comment] 2020-09-27 16:42
Actually it seems that I have identical issue. Working with IBM blockchain VS Code extension and at some point generating project template stopped to work (on calling YEOMAN apparently). I checked yo itself and getting version (yo --version) takes 28 seconds (literally).  WLS 2, Ubuntu 18.04, Win 10 Pro 2004 19041.508

**Comment by IronTooch** [comment] 2021-04-05 20:36
For anyone stumbling around in WSL trying to get Code-generator to work at all, and having it hang or `EACCES: permission denied,`
1) Don't use the root user
2) Install in a location that isn't /mnt/
3) Don't use the **-g** option

so...

> cd 
mkdir codegen
cd codegen
npm install yo code-gen
yo code
npm install 
`

Hopefully this will save you the hours it took me to diagnose and resolve the issue.

**Comment by Kratosgado** [comment] 2023-07-03 01:15
> WHAT SORCERY DID YOU DO I JUST RAN THIS AND IT RAN INSTANTLY ARGH.
> 
> I swear. I've had this for more than a week. Bitterly complained to one of my engineers about how slow this was and she couldn't understand why I was complaining (she was on a Mac).
> 
> Ran `strace you code` to get stats and it... just worked.
> 
> Then ran `yo code` and... it just worked.
> 
> 🤦‍♂️

Strace yo code did some magic and fixed mine too... funny
