### ISSUE TITLE
GreenScreen on opening

### ISSUE THREAD

**Issue by Ansuel** [Microsoft/WSL#3304] opened 2018-06-15 10:50 UTC
Microsoft Windows [Versione 10.0.17692.1000]

As soon as i open The bash shell i have  a green screen with lxcore.sys crashing...

I can't find a way to generate a crashdump.

**Comment by problem233** [comment] 2018-06-15 14:38
+1. When I'm trying to run `wsl` with normal privilege, I get a GSOD on `SYSTEM_SERVICE_EXCEPTION` in `LXCORE.SYS`

**Comment by onomatopellan** [comment] 2018-06-15 17:38
Same here. FeedbackHub asked me what happened and I replied I just tried to opening Ubuntu shell. I don't know if the minidump was automatically sent at that moment though.

**Comment by Brian-Perkins** [comment] 2018-06-15 18:01
Typically you will find the crashdump at \windows\memory.dmp. If you could email that to us -- see [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md), it would be appreciated. If you do not see a memory.dmp file, this option can be configured in the Startup and Recovery UI of System Properties (click start, start typing "view advanced system settings" and you should see the option).

**Comment by Ansuel** [comment] 2018-06-15 18:04
problem is that windows doesn't create it... even if i have the option enabled (tried with full dump and small memory dump 256kb)
nothing in /windows/ no minidump and no memory.dmp

**Comment by therealkenc** [comment] 2018-06-15 20:30
I just upgraded to '692 moments ago in the hopes of getting a dump to send in, but strangely no GSOD for me. I tried `ubuntu.exe` and `ubuntu1804.exe`, both as non-admin natch. So now the game is guessing the variable that is causing some to fail and others not.

**Comment by Ansuel** [comment] 2018-06-15 20:33
Some way to extract them ?

**Comment by Brian-Perkins** [comment] 2018-06-15 20:55
Our most recent instances of GSOD affecting only a small group have been related to AV software. @Ansuel - the only other reliable mechanism would be to attach a [kernel debugger](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/getting-set-up-for-debugging) and capture the information from a separate device.

**Comment by Ansuel** [comment] 2018-06-15 21:01
well... i have windows defender as AV software...

**Comment by onomatopellan** [comment] 2018-06-15 22:30
Ok I tested some things and this is what I found. All these in build 17692 with a practically clean install.

I have installed Ubuntu 18.04 in C: drive through the store and I can open it (normal and elevated) without getting any GSOD.
I also have installed some other distros in G: drive and these can be opened with "run as admin" otherwise I always get the GSOD. A repo would be:
- download centos.zip from https://github.com/x-distro/x.distro/releases
- unzip on a folder and "run as admin" centos.exe to install the distro. Press a key to close the window.
- double click on centos.exe will show the GSOD.

So I think launching distros installed through the Store shouldn't have this issue but distros installed manually should.

**Comment by Ansuel** [comment] 2018-06-15 22:34
look like the disto should be signed in some way and cause this sign doesn't exist in manually installed (or upgraded) dist windows goes GSOD

Open bash with elevated permission skip this check and windows doesn't crash.

**Comment by Biswa96** [comment] 2018-06-16 10:35
I also see this issue but with BSOD and same error of `LxCore.sys`.

As I said in this thread https://github.com/Microsoft/WSL/issues/1744#issuecomment-395531886, there is a new option in `wslconfig.exe /upgrade`. This has some relation with reparse points. In my case, that option solves this problem. 

Also as @Ansuel said, with admin privileges `bash.exe` and `wsl.exe` doesn't cause this BSOD. 👏 for that tip, thanks.

**Comment by Ansuel** [comment] 2018-06-16 12:42
i can't find the wslconfig.exe /upgrade option

**Comment by Biswa96** [comment] 2018-06-16 12:50
That optional. The "run-as-administrator" tip works well ;) OK, that upgrade option works as `wslconfig.exe /upgrade <distro_name>`.

What you said about the signing

**Comment by Biswa96** [comment] 2018-06-16 12:54
That optional. The "run-as-administrator" tip works well. OK, that upgrade option works as `wslconfig.exe /upgrade <distro_name>`. Ssssh.... Don't say it, it's hidden 🤐

What you said about the signing is somehow true. The Appx downloaded from Windows Store has a catalog file which check the integrity of that package. So that no malware can hamper it. Did you try to run the Windows Store distributions as administrator?

**Comment by Ansuel** [comment] 2018-06-16 13:55
i never installed bash on windows from the store.
as my  installation is present before the introduction of bash on windows in the store... i can't even use the upgrade command on the legacy distro...

**Comment by Biswa96** [comment] 2018-06-16 19:37
@Brian-Perkins Is it possible to debug kernel in VirtualBox remotely? Not in Hyper-V please. I've seen the article (from you link) that says about remote kernel debugging with COM port in a VM.

**Comment by Biswa96** [comment] 2018-06-16 19:37
@Brian-Perkins Is it possible to debug kernel in VirtualBox remotely? Not in Hyper-V please. I've seen the article (from your given link) that says about remote kernel debugging with COM port in a VM.

**Comment by Biswa96** [comment] 2018-06-17 18:55
It's seem to be weird. I install build 17692 in VirtualBox and attach windbg with pipe. But there is no blue/green screen with wsl.exe or bash.exe.

**Comment by onomatopellan** [comment] 2018-06-17 21:38
@Brian-Perkins I have sent a kernel memory dump. Hope it helps to fix this issue.

For those who can't generate a memory dump, in order to generate the MEMORY.DMP I had to check "Disable Automatic Deletion of Memory Dumps When Disk Space is Low".

**Comment by SvenGroot** [comment] 2018-06-19 17:40
Those of you who are seeing this problem, can you answer two questions for me:
1. What's the path where you installed your distro (the Windows location of the "rootfs" folder)?
2. What's the output of running `icacls` on that folder and its parent?

Using `wslconfig /upgrade` may fix the issue, but at this point doing this will have a few disadvantages (most notably file timestamps will not behave correctly), and there is no way to undo this upgrade.

**Comment by Ansuel** [comment] 2018-06-19 17:45
@SvenGroot 
Also wslconfig /upgrade doesn't work in Legacy disto...

anyway my rootfs folder is here

C:\Users\Ansue\AppData\Local\Lxss (this is where i have all the data)


C:\Users\Ansue\AppData\Local\Lxss\rootfs (rootfs dir)


```
C:\Users\Ansue\AppData\Local\Lxss BUILTIN\Administrators:(I)(F)
                                  BUILTIN\Administrators:(I)(OI)(CI)(IO)(F)
                                  NT AUTHORITY\SYSTEM:(I)(F)
                                  NT AUTHORITY\SYSTEM:(I)(OI)(CI)(IO)(F)
                                  NT AUTHORITY\SERVIZIO LOCALE:(I)(RX)
                                  NT AUTHORITY\SERVIZIO LOCALE:(I)(OI)(CI)(IO)(GR,GE)
                                  NT AUTHORITY\SERVIZIO DI RETE:(I)(RX)
                                  NT AUTHORITY\SERVIZIO DI RETE:(I)(OI)(CI)(IO)(GR,GE)
                                  BUILTIN\Users:(I)(RX)
                                  BUILTIN\Users:(I)(OI)(CI)(IO)(GR,GE)
                                  AUTORITÀ PACCHETTI APPLICAZIONI\TUTTI I PACCHETTI APPLICAZIONI:(I)(RX)
                                  AUTORITÀ PACCHETTI APPLICAZIONI\TUTTI I PACCHETTI APPLICAZIONI:(I)(OI)(CI)(IO)(GR,GE)
                                  AUTORITÀ PACCHETTI APPLICAZIONI\TUTTI I PACCHETTI APPLICAZIONI CON RESTRIZIONI:(I)(RX)
                                  AUTORITÀ PACCHETTI APPLICAZIONI\TUTTI I PACCHETTI APPLICAZIONI CON RESTRIZIONI:(I)(OI)(CI)(IO)(GR,GE)
                                  BUILTIN\Administrators:(I)(OI)(CI)(IO)(F)
                                  NT AUTHORITY\SYSTEM:(I)(OI)(CI)(IO)(F)
                                  BUILTIN\Users:(I)(OI)(CI)(IO)(RX)
                                  NT AUTHORITY\Authenticated Users:(I)(M)
                                  NT AUTHORITY\Authenticated Users:(I)(OI)(CI)(IO)(M)

Elaborazione completata per 1 file. Elaborazione non riuscita per 0 file

```

**Comment by SvenGroot** [comment] 2018-06-19 17:58
@Ansuel Thanks. From what I can make out, it seems that your user account does not have the "Delete subfolders or files" permission, which is what I suspected.

What's happening is that we're hitting an access denied error, and then the error handling path has a bug which is causing the BSOD. The bug in the error handling path has already been fixed internally. However, we also shouldn't be requiring these permissions, and we will fix that too.

In the mean time, you can work around this issue by granting yourself full control of the *parent* of your rootfs folder:
`icacls "C:\Users\Ansue\AppData\Local\Lxss" /grant "<username>:(OI)(CI)(F)"`

For other people following these instructions, make sure you determine where your "rootfs" folder is located, and use its parent in the above command. It may not be in the same place as this example.

**Comment by onomatopellan** [comment] 2018-06-19 18:19
@SvenGroot Indeed It worked. I used `icacls "G:\WSL\Ubuntu\" /grant "<username>:(OI)(CI)(F)"` and now I can launch Ubuntu non-store version again. Thanks for the workaraound.

wslconfig /upgrade didn't stop the GSODs though and I had to reinstall the distro again.

**Comment by Ansuel** [comment] 2018-06-19 18:49
yes can confirm the command fixed the gsod

**Comment by SvenGroot** [comment] 2018-06-19 18:57
@Ansuel @onomatopellan Thanks, that's good to hear. I'm working on the fix for the permissions issue now.

**Comment by Biswa96** [comment] 2018-06-20 04:47
@SvenGroot Is this permission configured from Windows side or WSL side during installation? Can `chmod` change that permission?

**Comment by shoffmeister** [comment] 2018-06-20 07:39
The temporary work-around was posted in https://github.com/Microsoft/WSL/issues/3304#issuecomment-398489972

**Comment by Biswa96** [comment] 2018-06-20 09:14
@SvenGroot Is this permission configured from Windows side or WSL side during installation? Can `chmod` change that permission? 

From @Voskrese's idea, If I add `SD="D:P(A;;GA;;;WD)"` in `diskpart` and add your options `"<username>:(OI)(CI)(F)"` in `icacls` I can install WSL in a virtual hard disk (.vhd or .vhdx file).

**Comment by Voskrese** [comment] 2018-06-20 09:21
@Biswa96 на самом деле, эти параметры я взял из инструкции, а по факту просто создал виртуальный диск, отформатировал его в NTFS и основное, после присоединения, с корня диска, через GUI параметра, задал ПОЛНЫЙ доступ для ВСЕХ. распаковал дистриб, даже 5 на сегодняшний день, и тогда у меня все заработало

> In fact, these parameters I took from the instructions, and in fact just created a virtual disk, formatted it into NTFS and basic, after attaching, from the root of the disk, through the GUI parameter, set full access for all. Unpacked Distrib, even 5 to date, and then I got everything worked

**Comment by SvenGroot** [comment] 2018-06-20 17:42
@Biswa96 This is a Windows permission and cannot be set with chmod. It can only be set with icacls.exe (as shown above), PowerShell's Set-Acl cmdlet, and the Windows Explorer security UI.

Also, I'd like to reiterate that this is a bug. We should not be requiring this particular permission. I've already fixed it and we'll let you know when the fix reaches an insider build.

**Comment by Brian-Perkins** [comment] 2018-07-11 19:31
The permissions issue should be fixed in Insider Build [17713](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17713)

**Comment by onomatopellan** [comment] 2018-07-12 21:05
>The permissions issue should be fixed in Insider Build 17713

Indeed it works well again. Thanks!

**Comment by Biswa96** [comment] 2018-07-13 01:20
But the installation requires admin privileges or to use the above icacls command.

**Comment by DDoSolitary** [comment] 2018-07-28 06:19
@SvenGroot Setting `FILE_CASE_SENSITIVE_INFORMATION` still requires the "Delete subfolders and files" permission. Is it a security feature by design, or the bug isn't fixed yet?

**Closed** 2018-10-08 21:44 UTC
Labels: fixedin1809

**Comment by DDvO** [comment] 2019-05-28 10:08
Adapting the file access permissions using `icacls` did not help in my case.
What did the trick was to invoke the `bash` command from a Windows shell with admin rights.
Since then I can use WSL / `bash` again also with normal user rights.
