### ISSUE TITLE
ssh session into WSL cannot execute windows binaries

### ISSUE THREAD

**Issue by samwise** [Microsoft/WSL#2414] opened 2017-08-13 00:31 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]   

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
ssh into a WSL  session:

ssh -p 2222 user@host

* What's wrong / what should be happening instead:

When I try to invoke a Windows binary such as MSBuild.exe, no error is returned and no output is printed, the process seemingly hangs. I am able to launch MSBuild.exe and other windows binaries when running directly on the bash console.

**Comment by benhillis** [comment] 2017-08-15 16:20
@samwise - Thanks for posting. Could you provide a bit more information about how you're launching your SSH server?

**Comment by samwise** [comment] 2017-08-16 22:37
You may very well be right. I was unable to reproduce the issue today. I will update this issue if find a reliable repro. Sorry for wasting your time.

**Comment by benhillis** [comment] 2017-08-16 22:42
@samwise - You're definitely not wasting my time, I appreciate all bug reports.  The reason I ask my follow-up question is due to how interop currently works, it's a known limitation that we have plans to address in a future release.

**Comment by nbdd0121** [comment] 2017-09-05 15:16
@benhillis I've reproduced a similar issue using gnome-terminal. As soon as the original bash.exe exits, the interop of all processes launched by that bash.exe will no longer work. This is exactly what you suspect.

**Comment by benhillis** [comment] 2018-01-29 19:55
This was resolved in 17046.

**Closed by benhillis** 2018-01-29 19:55 UTC
Labels: fixedininsiderbuilds, interop
