### ISSUE TITLE
Name resolution does not use domain searchlist

### ISSUE THREAD

**Issue by mat-m** [microsoft/WSL#7453] opened 2021-09-23 12:18 UTC
### Windows Build Number

Microsoft Windows [Version 10.0.19042.1237]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16.3

### Distro Version

Ubuntu 20.04.3

### Repro Steps

Let's say ad.corp.com is the default DNS domain
Add  items in   `DNS Suffix Search List`
Like:
```
ad.corp.com
lab.ad.corp.com
```

> Mine are provided automatically by the AD/DHCP system

In, WSL, try:
```
nslookup server1
nslookup server1.ad.corp.com
nslookup server2
nslookup server2.ad.corp.com
```

### Expected Behavior

All nslookup should be successful

### Actual Behavior

The third nslookup fails in WSL but works in a cmd on the Windows host.

Even `nslookup server2.lab` does not work.

**Comment by phil-blain** [comment] 2022-01-14 14:10
This looks like a duplicate of https://github.com/microsoft/WSL/issues/701 :) I see the same behaviour.

**Closed** 2024-02-01 12:10 UTC
