### ISSUE TITLE
WSL2 randomly terminates when doing VS Code searches

### ISSUE THREAD

**Issue by ccarlsonpb** [microsoft/WSL#5939] opened 2020-09-17 14:53 UTC
# Environment

Windows build number: 
 Win32NT             10.0.20170.0 Microsoft Windows NT 10.0.20170.0

Your Distribution version:
Release:        18.04

Whether the issue is on WSL 2 and/or WSL 1:
Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020

# Steps to reproduce

Originally filed as a vscode issue here https://github.com/microsoft/vscode/issues/106139, but seems like it's an issue with WSL itself. Basically, every couple of days or so, I will begin a project-wide search operation in vs code, and this will cause WSL to terminate. All of my open terminals will close, docker for windows will say that WSL has stopped, etc. Basically, vs code is the catalyst, but the entirety of WSL shuts down.

So far, I have only been able to trigger this crash by using the project search feature of vs code, but I can't intentionally reproduce the crash; Searching works fine for days at a time, but eventually I will begin a search and then WSL will crash.

#  Expected behavior

I'm expecting WSL not to terminate on its own.

# Actual behavior

WSL randomly terminates.

**Comment by reinaldocoelho** [comment] 2020-09-23 16:16
I have the same  problem here.
When running or debugging React/Dotnet with VsCode over WSL the program stops to work. VsCode display an Reconnecting modal and the command line over WSL freezes.
If I open a prompt (powershell) and run `docker ps`, the command not respond until some automatic "restart" occours.

If I open the Task Manager, VMMEM consume a higth CPU and use all configured memory to it (6GB).

I can´t get the steps to reproduce too. :-(

**Comment by ziyunxiao** [comment] 2020-10-09 14:46
I have similar issues. And it is very difficult to reproduce. It crashed my host (Windows) 3 times.

1. Running upgrade of vscode, during vscode restart it crashes the host. inside Linux(Ubuntu 20.04)
2. Running vscode inside Linux and don't know what reason it crashes.
3. Running script to build a docker image inside Linux(Ubuntu 20.04) it crashes the host(Windows) again. It looks like related to steps to access the Windows files system where the docker image stored at (C:/Programdata/dockerDesktop/) . But the error could not be reproduced every time.

Anyway, this is just a comment here. Hopefully, this can give some clue that the support team can find the root cause.

Thanks very much to the team who make WSL2.

**Comment by ccarlsonpb** [comment] 2020-10-09 15:12
So, a week or two ago I tried this workaround - an entry in `%USERPROFILE%\.wslconfig`

```
[wsl2]
memory=8GB
processors=3
```

This is on my machine with 16GB RAM, 4 cores and it seems to have helped quite a bit. I think I haven't had the crashing issue since I made this change. To me it seems like WSL2 is too greedy by default and ends up starving the host of all available resources, which creates a deadlock and ends up killing WSL2 itself.

**Comment by ziyunxiao** [comment] 2020-10-09 15:59
@ccarlsonpb  Thank you for the info. I will try out your workaround.

**Comment by mkymikky** [comment] 2020-11-04 18:17
I can reproduce a similar behaviour with transferring encrypted and deduplicated data via borg to another computer via ssh.
This reproduces termination without message while synchronizing the borg cache..
Where can I obatin the generated logs?

**Closed** 2024-02-01 12:15 UTC
Labels: need-repro
