### ISSUE TITLE
Virtual disk right click open bash shell do not change the correct dir

### ISSUE THREAD

**Issue by purocean** [Microsoft/WSL#3291] opened 2018-06-12 06:34 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17686.1003
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Virtual disk right click open bash shell do not change the correct dir
![1](https://user-images.githubusercontent.com/7115690/41273813-9147f928-6e4d-11e8-8f84-4b01abf96f1e.gif)
other disk work perfect

**Comment by benhillis** [comment] 2018-06-19 19:47
Are you able to navigate to this drive in WSL normally?

**Comment by purocean** [comment] 2018-06-20 01:13
@benhillis yes
![2](https://user-images.githubusercontent.com/7115690/41631973-3160bf54-746a-11e8-8d75-15d1447cbb04.gif)

**Comment by benhillis** [comment] 2018-06-20 21:16
Thanks for reporting. This is a duplicate of #3246, for which I have a fix pending.

**Closed by benhillis** 2018-06-20 21:16 UTC

**Comment by Brian-Perkins** [comment] 2018-07-11 19:30
This should be fixed in Insider Build [17713](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-17713)
