### ISSUE TITLE
cmd.exe error "The syntax of the command is incorrect." using full path

### ISSUE THREAD

**Issue by sakai135** [microsoft/WSL#8259] opened 2022-04-09 07:45 UTC
### Version

10.0.22593.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Other Software

Default Distribution: Ubuntu
Default Version: 2
WSL version: 0.58.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.32
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22593.1

### Repro Steps

In bash, run:
```
cmd.exe /c 'echo a'
```

Then run:
```
/mnt/c/WINDOWS/system32/cmd.exe /c 'echo a'
```

### Expected Behavior

Both steps should return:
```
a
```

### Actual Behavior

The first step using `cmd.exe` will return:
```
a
```

The second step using `/mnt/c/WINDOWS/system32/cmd.exe` will return:
```
The syntax of the command is incorrect.
```

In addition, both will also return the warning:
```
'\\wsl.localhost\Ubuntu\home\ubuntu'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

-----

If I uninstall the WSL Preview from the store and revert to kernel version: 5.10.16, both steps will return the expected value along with the warning.

**Comment by benhillis** [comment] 2022-04-13 15:07
Thanks for filing, I have resolved this issue and it will be available in an upcoming fix.

The warning is by design as cmd.exe does not support UNC paths.

**Comment by benhillis** [comment] 2022-04-14 22:00
Fixed with https://github.com/microsoft/WSL/releases/tag/0.58.1.

**Closed by benhillis** 2022-04-14 22:00 UTC
Labels: bug, fixinbound
