### ISSUE TITLE
Pass ANSI Escape Sequences up to the Console

### ISSUE THREAD

**Issue by austinwagner** [Microsoft/WSL#406] opened 2016-05-20 15:41 UTC
Currently ConEmu cannot process escape codes generated by applications running under the Windows Subsystem for Linux because they are processed before they can reach ConEmu (as stated in Maximus5/ConEmu#573). These sequences should be passed along to be handled at the console level.

**Comment by musmo** [comment] 2016-07-08 05:52
Desperately needed. I mean apple fanboys always try to show off with fancy iterm2, while I hide in the corner living in an 8-bit world.

**Comment by rfc1459** [comment] 2016-08-04 12:59
This not only breaks (potential) 256 color support, but also causes serious issues with basic ANSI functionality (arrow keys among other things - which have been worked around in ConEmu).

Simple reproducer for ANSI reverse:
```bash
printf "Normal\n\x1b[7mReverse\x1b[0m\nNormal\n"
```

The "reverse" sequence is silently swallowed and interpreted locally by the console emulation layer before it can reach ConEmu, so in plain bash.exe it would display "Reverse" with fg/bg swapped, but in ConEmu fg and bg are not swapped.

If you want a more complex reproducer, fire up `aptitude` in both plain bash.exe and ConEmu: the former will correctly highlight the current item, the latter won't because aptitude uses ANSI reverse for the current item.

**Comment by ysc3839** [comment] 2016-10-07 02:44
The bash.exe uses SetConsoleMode setted ENABLE_VIRTUAL_TERMINAL_PROCESSING ([MSDN](https://msdn.microsoft.com/zh-cn/library/windows/desktop/ms686033)). And we can get original ANSI sequences after disable it.
![1](https://cloud.githubusercontent.com/assets/12028138/19177361/0ecc2a4c-8c7b-11e6-807f-35ad285ac7fb.png)

**Comment by Maximus5** [comment] 2016-10-18 19:49
We can't get original ANSI. They are written **directly** into conhost memory. That means one console line would have few chars instead of full line of data.

**Comment by antitoxic** [comment] 2016-10-19 04:58
I am also looking forward this. ref: https://github.com/Microsoft/BashOnWindows/issues/345#issuecomment-254709960

@ysc3839 how do I do this? Are you sure it's possible?

**Comment by ysc3839** [comment] 2016-10-19 13:50
@antitoxic I hooked SetConsoleMode then clear the ENABLE_VIRTUAL_TERMINAL_PROCESSING bit. But ConEmu can't process them.

**Comment by be5invis** [comment] 2016-10-19 16:09
@Maximus5 We should push for the official PTY API, instead of hooking.

**Comment by Maximus5** [comment] 2016-10-19 16:14
There would be no new API. Example of the answer: https://github.com/Microsoft/BashOnWindows/issues/345#issuecomment-249240194

**Comment by be5invis** [comment] 2016-10-19 16:16
@Maximus5 It’s the API for implementing an alternative terminal, instead of an API for writing text in 24 bit colors (or something like that).

**Comment by be5invis** [comment] 2016-10-19 16:16
cf. #1117

**Comment by zadjii-msft** [comment] 2016-10-19 16:44
I agree with @be5invis. Hooking is bad. If you want to hook the console to make your own, then you can go ahead and parse the VT sequences yourself too :p

**Comment by Maximus5** [comment] 2016-10-19 16:51
Unless Microsoft would provide **official** way to implement pty interface, the hooking is only possible technique.
And of course, it has no sense to read VT sequences from console surface because: a) third-party terminal (ConEmu) can't realize what **was** a sequence and what was some RAW data; b) unprocessed VT sequences takes a lot more cells than processes, so "full screen" applications like Vim would not work at all.

**Comment by zadjii-msft** [comment] 2016-10-19 17:00
a) you'd have to implement a VT [parser,](http://vt100.net/emu/vt500_parser.png) and have your own mechanism for determining if it's enabled or not. No, technically there's no way to determine if the output is a sequence or not, but that's because most terminals just assume that it is.

b) That they do. you'd have to assume that the conhost buffer is garbage, and manage it all on your own. 

Again, we're not supporting hooking, and in the most general and vague way possible, we'll have some things to announce in the future that you'll all be very happy about, but we've got a lot to do before that

**Comment by Maximus5** [comment] 2016-10-19 17:15
a) VT parser was implemented in ConEmu years ago. But any application may write to conhost buffer via WriteConsoleOutput. And these sequences are not valid VT sequences. Without hooking or the imaginary pty API ConEmu can't distinct them.

b) I can't. Due to a). And disability to understand are sequences were enabled or disabled. Without hooking I can't restrict bash to turn on 0x200 flag, and even if it would be dropped by ConEmu hooks, there would be absolutely no guarantee that some other application, attached to this console, is not trying to use native WinAPI instead of VT.

So, when it really would be possible, I'll be happy to go of hooking, but till than there is no other way. If you are interested in, hooking is used for many other things in ConEmu. For example, GetConsoleWindow have to return ConEmu window instead of conhost, otherwise applications would work improperly when they use console HWND.

**Comment by be5invis** [comment] 2016-10-20 01:13
@zadjii-msft So, to avoid hooking, we NEED a **PTY API** which makes us able to implement an alternative console host, and things like `tmux`. This thing is missing since the creation of Windows. It's been 30 years, bro.

**Comment by rdeforest** [comment] 2017-07-10 16:34
Was going to submit a bug but it would have been a dupe of this one I think. I too see problems in aptitude as of Windows build 16237. I'd include a screenshot, but it's so easy to repro it would add nothing.

If the bug isn't obvious as soon as you run aptitude, try navigating (down arrow or 'j' or whatever).

**Comment by bitcrazed** [comment] 2018-05-22 22:16
Thanks for the discussion.

Closing this issue since:
1. We're working on a feature that will remedy this issue for @Maximus5 & others
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Closed by bitcrazed** 2018-05-22 22:16 UTC
Labels: console

**Comment by samvv** [comment] 2024-01-17 18:39
@bitcrazed What feature were you referring to? I'm still not able to create true colors using WSL 2 and Ubuntu 22.04.

**Comment by zadjii-msft** [comment] 2024-01-17 19:49
@samvv How have you tried so far? RGB color support has shipped in the console for like, 5 years now. `curl https://raw.githubusercontent.com/csdvrx/sixel-testsuite/master/ansi-vte52.sh | bash` will get you something like:

![image](https://github.com/microsoft/WSL/assets/18356694/6ce82109-d3db-437d-a01b-e12b8c1ff071)

If you're still having troubles, I'd recommend opening a new issue over on the Terminal repo.

**Comment by samvv** [comment] 2024-01-17 19:51
Thanks for the link. I'll be sure to check it tomorrow and open a new issue if it still is relevant.
