### ISSUE TITLE
WSL2 Register Command

### ISSUE THREAD

**Issue by rwilliams** [microsoft/WSL#4762] opened 2019-12-15 02:36 UTC
**Is your feature request related to a problem? Please describe.**
#4591 I recently refreshed Windows install after a hardware upgrade so my WSL distros were deleted from the registry but I still had the .vhdx files. I also exported my distro with the plan of importing it when I re-installed windows. When I tried to import with WSL2 as the default type I get  https://github.com/microsoft/WSL/issues/4530
![image](https://user-images.githubusercontent.com/29144/70857236-63219500-1e9f-11ea-92ea-512140b75ecb.png) 
after quite a few minutes has elapsed. I had to import as WSL1 and then convert to WSL2 after the import. It took ~2.5 hours for a 50gb image on a fast workstation. Even if the import worked directly with WSL2 the process is still very long.

**Describe the solution you'd like**
It would be nice if you could just run something like `WSL --register` with the same options as `--import` (except it looks for a vhdx and not an archive) and have it properly register the distro image in the registry and do anything else that needs to be done. This would allow just backing up the vhdx directly without the need to use import and export.

**Describe alternatives you've considered**
Right now import/export is terribly slow and maybe broken on WSL2 so I don't think it's a good alternative.

**Comment by benhillis** [comment] 2020-01-03 16:59
I like this idea, let me play with it a bit.

**Comment by rwilliams** [comment] 2020-01-03 17:24
It might also be cool if you could specify a UID to set the default user when doing this.

**Comment by synergies** [comment] 2020-01-26 20:49
@therealkenc the issue is I don't have the export like @rwilliams to import. How can I "import" from the existing ext4.vhdx file?

**Comment by rwilliams** [comment] 2020-01-26 20:52
You can create a registry entry for the vhdx though it's not recommenced to mess with the registry.

**Comment by rwilliams** [comment] 2020-01-26 20:58
@synergies sent you an email.

**Comment by synergies** [comment] 2020-01-26 21:32
Thanks @rwilliams for the registry file! For anyone that runs into this issue, below is the registry file I used to "import" the existing ext4.vhdx to show up properly as a WSL distro:

`Windows Registry Editor Version 5.00

[HKEY_USERS\\**[SID]**\\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{**[UUID]**}]
"State"=dword:00000001
"DistributionName"="**[DISTRO_NAME]**"
"Version"=dword:00000002
"BasePath"="\\\\?\\\\**[VHDX_PATH]**"
"Flags"=dword:0000000f
"DefaultUid"=dword:000003e8`

Below are the items you need to update in the registry script above:
- **[SID]:** Open command prompt and run **whoami /user** to get your SID
- **[UUID]:** Go to [this generator](https://www.uuidgenerator.net/) create a UUID
- **[DISTRO_NAME]:** Name of distro you want, for example: _Ubuntu_
- **[VHDX_PATH]:** Path of the distro with escaping slashes, for example: _D:\\\\WSL\\\\Ubuntu_

Hopefully this will help anyone stuck in a similar situation as myself. Good luck!

**Comment by erSitzt** [comment] 2020-03-04 11:29
@synergies 
Thanks for that... got my wsl back this way

Third time i lost my wsl due to a windows update (i guess)

**Comment by mnunezdm** [comment] 2020-04-27 08:59
In my case, the BasePath

> Thanks @rwilliams for the registry file! For anyone that runs into this issue, below is the registry file I used to "import" the existing ext4.vhdx to show up properly as a WSL distro:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_USERS\[SID]\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{[UUID]}]
> "State"=dword:00000001
> "DistributionName"="[DISTRO_NAME]"
> "Version"=dword:00000002
> "BasePath"="\\\\?\\[VHDX_PATH]"
> "Flags"=dword:0000000f
> "DefaultUid"=dword:000003e8
> ```
> 
> Below are the items you need to update in the registry script above:
> 
> * **[SID]:** Open command prompt and run `whoami /user` to get your SID
> * **[UUID]:** Go to [this generator](https://www.uuidgenerator.net/) create a UUID
> * **[DISTRO_NAME]:** Name of distro you want, for example: `Ubuntu`
> * **[VHDX_PATH]:** Path of the distro with escaping slashes, for example: `D:\\WSL\\Ubuntu`
> 
> Hopefully this will help anyone stuck in a similar situation as myself. Good luck!

In my case, I just have to write the path without scaping... `\\?\C:\WSL\ubuntu`

**Comment by Robula** [comment] 2020-08-18 19:19
I've just done the same, had to to reset my PC because of DCOM errors. WSL was wiped however I still have the `ext4.vhdx` file in `Windows.old`. How do I use `wsl --import` to get back to where I was?

**Comment by rwilliams** [comment] 2020-08-18 19:26
@Robula You can re-register the ext4.vhdx using the following https://github.com/microsoft/WSL/issues/4762#issuecomment-578545574 though this method is not officially supported. I don't believe there is a way to use the `wsl --import`  if you don't have a exported backup.

**Comment by Jirubizu** [comment] 2021-04-23 01:19
> 
> 
> I've found this solution https://www.reddit.com/r/bashonubuntuonwindows/comments/gdiubo/wsl2_import_existing_ext4_image/
> 
> It says "Solved this by installing a new Ubuntu instance, removing its EXT4 image, and replacing with the EXT4 image from my old install." and it really worked for me rather than the script mentioned above.

I struggle with this example. How exactly do you open the ext4.vdhx to then move the files over to the localstate. I am unable to find the new installations ext4.vdhx anywhere

**Comment by synergies** [comment] 2021-04-23 12:41
@Jirubizu I can't speak to the steps on the reddit link. However, the process I [commented above](https://github.com/microsoft/WSL/issues/4762#issuecomment-578545574) worked for me. Did that not work for you?

**Comment by andregs** [comment] 2021-07-16 21:01
> In my case, I just have to write the path without escaping... `\\?\C:\WSL\ubuntu`.
> 
> If I escape them I got an error of incorrect path or the one referenced here #4860
> 
> I check other distro installations in the same registry folder, and in the other, there was no escaping

The escaping part is confusing because in the `.reg` file the `BasePath` must be escaped, but when you check the results in `regedit` you'll see that value with no escaping.

**Comment by securedirective** [comment] 2022-06-02 02:15
In case anyone else finds this page and has the same question as @Jirubizu... the "hard drives" for WSL distros will be a .vdhx if WSL version 2, but will be a regular directory of files if WSL version 1. So I'd posit that whoever said "Solved this by installing a new Ubuntu instance, removing its EXT4 image, ..." probably has their WSL set to version 2 by default. But on a freshly-installed Windows 10 (as of May 2022), the default is still version 1.

So, do one of the following:
1. Run `wsl --set-default-version 2` before creating the new WSL distro. Then any new distros will start in .vdhx format.
2. Run `wsl --set-version Ubuntu 2` to convert an existing "Ubuntu" distro to .vdhx format.

**Comment by salyndev0** [comment] 2022-07-26 01:44
For newer come to here like me reinstall window 10 but keep files and you still have ext4.vhdx then you can go to register and make smt like this 
![image](https://user-images.githubusercontent.com/66520542/180904271-6056963a-100b-4165-94b2-bf6950180cb4.png)

You can follow synergies answer above https://github.com/microsoft/WSL/issues/4762#issuecomment-578545574
But the Base Path is not that hard

**Comment by theAkito** [comment] 2022-11-21 23:19
> Thanks @rwilliams for the registry file! For anyone that runs into this issue, below is the registry file I used to "import" the existing ext4.vhdx to show up properly as a WSL distro:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_USERS\[SID]\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{[UUID]}]
> "State"=dword:00000001
> "DistributionName"="[DISTRO_NAME]"
> "Version"=dword:00000002
> "BasePath"="\\\\?\\[VHDX_PATH]"
> "Flags"=dword:0000000f
> "DefaultUid"=dword:000003e8
> ```
> 
> Below are the items you need to update in the registry script above:
> 
>     * **[SID]:** Open command prompt and run `whoami /user` to get your SID
> 
>     * **[UUID]:** Go to [this generator](https://www.uuidgenerator.net/) create a UUID
> 
>     * **[DISTRO_NAME]:** Name of distro you want, for example: `Ubuntu`
> 
>     * **[VHDX_PATH]:** Path of the distro with escaping slashes, for example: `D:\\WSL\\Ubuntu`
> 
> 
> Hopefully this will help anyone stuck in a similar situation as myself. Good luck!

Thanks for this, kind of solved my issue.
As this restoration method seems to have different variations, I'll add mine for future readers.

1. I had to use the escape back slashes. Did not work without.
2. The `DefaultEnvironment` "Multi-String" is missing. Mine looks like this:
  ```
  HOSTTYPE=x86_64
  LANG=en_US.UTF-8
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
  TERM=xterm-256color
  ```
3. The `\\?\` prefix in the `BasePath` might be needed or not. I have distributions that feature this and others that don't. If your distribution is not found, remove that prefix and check again.
4. At first, I did not realise that `BasePath` is actually the path to the **directory**, where the `ext4.vhdx` is supposed to be. If the path to the `ext4.vhdx` is provided, the installation won't be found, either.

**Comment by cool-delete** [comment] 2022-12-10 02:49
After rebuild windows, I found the ext4.vhdx of the old system but could not mount it normally. The disk manager prompted me to format it. I used the 7zip program to check the dir and saw two img.

![image](https://user-images.githubusercontent.com/13638610/206825000-72b09105-55c7-4b6b-a194-9372c3ffe678.png)

**Comment by wangzhankun** [comment] 2023-09-08 12:55
> Thanks @rwilliams for the registry file! For anyone that runs into this issue, below is the registry file I used to "import" the existing ext4.vhdx to show up properly as a WSL distro:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_USERS\[SID]\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss\{[UUID]}]
> "State"=dword:00000001
> "DistributionName"="[DISTRO_NAME]"
> "Version"=dword:00000002
> "BasePath"="\\\\?\\[VHDX_PATH]"
> "Flags"=dword:0000000f
> "DefaultUid"=dword:000003e8
> ```
> 
> Below are the items you need to update in the registry script above:
> 
> * **[SID]:** Open command prompt and run `whoami /user` to get your SID
> * **[UUID]:** Go to [this generator](https://www.uuidgenerator.net/) create a UUID
> * **[DISTRO_NAME]:** Name of distro you want, for example: `Ubuntu`
> * **[VHDX_PATH]:** Path of the distro with escaping slashes, for example: `D:\\WSL\\Ubuntu`
> 
> Hopefully this will help anyone stuck in a similar situation as myself. Good luck!

I have error "Deny ACCESS", Any Solution for it?

**Comment by jamesyinbaare** [comment] 2024-06-26 23:34
working with ubuntu 20.04.6  on Win 11 host and I didn't have any issue with everything that has been described here. I just replaced .vhdx backup and everything worked seamlessly. I just used the same distro, same name and password I was using on the previews installation.

**Comment by Chiichen** [comment] 2024-06-29 11:33
Command `wsl --import-in-place <Distribution name> <path of vhdx>`  can be used now to import the distribution in place

**Comment by OneBlue** [comment] 2024-08-19 21:24
Indeed this is now possible via `wsl --import-in-place`. 
Closing

**Closed by OneBlue** 2024-08-19 21:24 UTC
Labels: feature
