### ISSUE TITLE
Problems restarting after installing WSL error: 0x8004032d (null)

### ISSUE THREAD

**Issue by khalifaa55** [microsoft/WSL#11429] opened 2024-04-06 01:29 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04.3

### Repro Steps

open Ubuntu 22.04.3

### Expected Behavior

<img width="443" alt="Screenshot 2024-04-06 032530" src="https://github.com/microsoft/WSL/assets/124837763/72e1fe1a-3fb5-430b-9582-db2d445c3a94">

### Actual Behavior

 have a laptop and I'm trying to enable WSL on it for development purposes. I installed Ubuntu and it returns the following error:

Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0x8004032d Error: 0x8004032d (null) Press any key to continue...

I searched the internet and saw that the problem must be because I don't have WSL active on Windows. I tried to activate it through "Windows Features", and after the "installation finished", I was asked to restart the computer. During the restart, the error messages appeared:

Feature customization for you. Update 96% complete. Keep the computer turned on.

Followed by the message:

Unable to complete resources. No need to worry: we are undoing the changes. Keep the computer turned on

And after a few seconds, the message appeared:

Something didn't go as planned. No need to worry: we are undoing the changes. Keep the computer turned on.

After the reset was complete, I tried to reopen Ubuntu WSL and received the same error. I went to check Windows Features and saw that WSL was still disabled. I repeated the same process several times, getting the same errors. I tried installing and activating WSL via command prompt as well, and got the same errors.

### Diagnostic Logs

[WslLogs-2024-04-06_03-06-58.zip](https://github.com/microsoft/WSL/files/14891911/WslLogs-2024-04-06_03-06-58.zip)

**Comment by khalifaa55** [comment] 2024-04-06 01:35
How do i reproduce the issue?

**Comment by khalifaa55** [comment] 2024-04-06 01:51
[WslLogs-2024-04-06_03-49-22.zip](https://github.com/microsoft/WSL/files/14891948/WslLogs-2024-04-06_03-49-22.zip)

**Comment by khalifaa55** [comment] 2024-04-08 17:19
Whenever i do that it needs the laptop to reboot to add that feature. During the restart, the error messages appeared:

Feature customization for you. Update 96% complete. Keep the computer turned on.

Followed by the message:

Unable to complete resources. No need to worry: we are undoing the changes. Keep the computer turned on

And after a few seconds, the message appeared:

Something didn't go as planned. No need to worry: we are undoing the changes. Keep the computer turned on.

After the reset was complete, I tried to reopen Ubuntu WSL and received the same error. I went to check Windows Features and saw that WSL was still disabled

**Comment by OneBlue** [comment] 2024-04-08 20:45
Thank you @khalifaa55. This error is unfortunately for WSL since WSL requires virtual machine platform. 

Sadly we don't have deep knowledge on how to root cause optional component issues but I'll recommend: 

- Running sfc /scannow as administrator
- Running chkdsk /f as administrator
- Making sure that you have free disk space for the new feature

And try again. If that still doesn't work the only option that would be unfortunately be to re-install Windows. 

Closing since the issue is external to WSL.

**Closed by OneBlue** 2024-04-08 20:45 UTC

**Comment by maomaozhe** [comment] 2024-05-26 07:46
啊啊，我也遇到了相同的问题，请问解决了吗？然后用`wsl --list --verbose`显示没有下载发行版本（我下载了），（启用计算机功能）里面的（xxx子系统）像楼主说的一样反复96%，在重启时出问题...
