### ISSUE TITLE
No network device when mirrored network is enabled

### ISSUE THREAD

**Issue by ArslanTu** [microsoft/WSL#11423] opened 2024-04-05 10:48 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3374]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-2

### Distro Version

Ubuntu-22.04

### Repro Steps

1. Add such config to `.wslconfig`
```
[wsl2]
networkingMode=mirrored
```
2. `wsl --shutdown` then `wsl`
3. `ifconfig` output is like this:
```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 76  bytes 6824 (6.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 76  bytes 6824 (6.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

There is no eth0 or other device, no matter there is or no proxy in windows.
Remove config above just works well.

### Expected Behavior

There exist some network devices other than lo when mirrored network is enabled.

### Actual Behavior

There is no network device other than lo when mirrored network is enabled.

**Comment by OneBlue** [comment] 2024-04-05 22:10
Closing since the issue is resolved.

**Closed by OneBlue** 2024-04-05 22:10 UTC
