### ISSUE TITLE
WSL sees empty files/directories permissions for files/directories created under linux with ntfs-3g

### ISSUE THREAD

**Issue by xzn** [microsoft/WSL#5157] opened 2020-04-30 12:59 UTC
After creating a bunch of files under linux with ntfs-3g, then rebooting to windows, WSL has trouble reading permissions of the newly created files. Instead of having the default permission from umask/dmask, they show up as a bunch of dashes, ~~and directories cannot be 'ls'ed at all~~.

Steps to reproduce:

1. Have a dual booting system
2. ~~(Not sure, it's possible my ntfs file system is corrupted, though chkdsk shows no error?)~~
3. Boot into linux (Arch linux) with ntfs-3g installed.
4. `cd /j/`
5. `mkdir _test && touch _test/_test`
6. reboot into Windows, open WSL,
7. `cd /j/`
8. `ls -la`

I end up with something that looks like this:
![image](https://user-images.githubusercontent.com/1617680/80762558-246d3e00-8b13-11ea-9c33-1cab4be721d5.png)
The `_test` entries have essentially no permissions.

Note that this doesn't happen on C drive, only on the other drives (d, j, k, l) I have.

~~If this is an issue with corrupted file system please let me know an easy way to fix it (backup software that preserve symlinks and extended attributes for instance) Given that I've found no report on the internet about this elsewhere I feel this bug could be an error on my part.~~

Update: happens with a freshly formatted disk as welll

**Comment by sirredbeard** [comment] 2020-04-30 20:52
Can you please provide clear steps to reproduce?

```
1. echo 'hello world'
2. sudo apt update
...
```

**Comment by xzn** [comment] 2020-04-30 22:00
Hello,

Sure I've updated the first post with steps to reproduce.

**Comment by xzn** [comment] 2020-05-01 23:24
Just checked that this also happens with a freshly formatted disk.

Happens in both WSL/WSL2.

**Comment by davidromerot** [comment] 2021-04-01 13:10
Same problem here.

After this problem shows, I change permissions with chmod, and it works for a while. After a few hours working on my bash, at some point I start randomly losing access to files, with some of them showing permissions as all dashes ("----------") even though they were not created, accessed or modified, on WSL or on Windows, during this time.

Any ideas of how to fix this? This issue makes WSL unusable for me, as I have to keep doing chmod periodically to be able to access files. If I am running scripts, I never know when a script is going to fail because it cannot access the files it needs to.

Thanks.

**Comment by Ryllaz** [comment] 2021-04-08 19:03
> Same problem here.
> 
> After this problem shows, I change permissions with chmod, and it works for a while. After a few hours working on my bash, at some point I start randomly losing access to files, with some of them showing permissions as all dashes ("----------") even though they were not created, accessed or modified, on WSL or on Windows, during this time.
> 
> Any ideas of how to fix this? This issue makes WSL unusable for me, as I have to keep doing chmod periodically to be able to access files. If I am running scripts, I never know when a script is going to fail because it cannot access the files it needs to.
> 
> Thanks.

Hello! I have the same problem. Tried to fix this with `sudo chmod -R 0777 .` in target dir and it helps for some random time.

**Comment by Nightenom** [comment] 2022-05-30 07:47
Possibly duplicate of #4116

**Closed** 2024-02-01 12:17 UTC
Labels: file system
