### ISSUE TITLE
cmd执行bash提示 管理员用策略规则 %2 限制了对 %1 的访问

### ISSUE THREAD

**Issue by wanggan768q** [microsoft/WSL#10934] opened 2023-12-19 12:17 UTC
### Windows Version

Microsoft Windows [版本 10.0.22631.2861]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [X] WSL 1

### Kernel Version

5.4.72

### Distro Version

Ubuntu 22.04.3

### Repro Steps

cmd executing bash prompts the administrator to restrict access to %1 with policy rule %2

### Expected Behavior

wsl commands can be executed and docker can be used

### Actual Behavior

cmd executing bash prompts the administrator to restrict access to %1 with policy rule %2

### Diagnostic Logs

2

**Comment by OneBlue** [comment] 2023-12-19 22:08
Closing this the issue isn't actionable.

**Closed by OneBlue** 2023-12-19 22:08 UTC
