### ISSUE TITLE
Ctrl-C doesn't work in any conhost to cancel the currently typed command.

### ISSUE THREAD

**Issue by AaronFriel** [Microsoft/WSL#1583] opened 2017-01-11 07:13 UTC
# Not A Duplicate. Please read.

I understand #1569 reports an issue with Bash, but it's normal for me when typing in a terminal to use "Ctrl-C" to cancel the currently typed command and clear the current input.

**Right now Ctrl-C doesn't behave correctly in *any* console that uses conhost, and I'm not sure where to report that.** e.g.: `powershell`. (I guess this works now for me in `cmd`, but was not earlier. I may have changed something since my first report or I may be mistaken in it effecting all conhosts and imagined it affecting `cmd`.)

Steps to reproduce:

Steps:
1. Type "foobar" into a `powershell` prompt.
2. Press Ctrl-C

Expected behavior:

Input is cleared.

Actual behavior:

Nothing happens.

**Comment by AaronFriel** [comment] 2017-01-11 07:14
@jackchammons it was rude to close my previous issue (#1581) as a duplicate of #1569 when I mentioned #1569 in the *very first line*.

**Comment by AaronFriel** [comment] 2017-01-11 07:21
And I don't know why I feel like I must clarify this, but let me quote to you exactly why this isn't a duplicate. Here's issue #1569: 

> **Issue:** In Windows 10 Insider build 15002, when running Bash.exe, CTRL + chords are not being correctly handled by the Windows Console.

My issue: Ctrl-chords are not behaving as expected in `powershell` either.

> **Effect:** Users will be unable to terminate Linux apps using CTRL + C, or background running tasks using CTRL + Z, etc. When CTRL + C is hit in Bash, a ‘c’ is displayed in the bash console.

In `powershell` a different behavior occurs: nothing happens at all.

> **Work-Around(s):** Until fixed:
> 1. Run Linux tools that require CTRL + C to terminate in a separate Bash console session; these individual bash consoles can then be closed when needed without disrupting your interactive bash consoles
> 2. Map an alternate key to Ctrl+C. For example, to map Ctrl+K to Ctrl+C run: stty intr \^k. This mapping is per terminal and will have to be done every time bash is launched. Users can include this in their .bashrc if preferred

Obviously this does not work for `powershell` or `cmd`.

> **Scope:** This issue only affects Bash sessions and does not prevent CTRL + C, etc. in other console apps or shells (i.e. Cmd or PowerShell).

This is affecting me in `powershell.exe`.

**Comment by AaronFriel** [comment] 2017-01-11 07:21
CC @bitcrazed

**Comment by benhillis** [comment] 2017-01-11 07:27
You are right, your original issue should not have been closed. In our defense we have been expecting a huge influx of "control c is broken" issues being filed as a result of this bug. At a glance your issue looked to be a duplicate, sorry about that. 

What you are describing is definitely something else broken in the core console code and should certainly be investigated.

**Comment by jackchammons** [comment] 2017-01-11 19:24
@AaronFriel apologies for the preemptive closure. We'll be starting another repository in the future to deal with more console specific bugs like this.

**Comment by AaronFriel** [comment] 2017-01-12 02:37
Thank you, I appreciate that. It's understandable that you would expect an influx of issues, as well. I'm sure many would love to see a repository for general console bugs and improvements to `conhost`. This format works far better for technical issues than the feedback hub, in my opinion.

**Comment by sgtoj** [comment] 2017-01-12 13:37
I am pretty confident this didn't begin with build 15002. I noticed this behavior with PowerShell in the previous Fast Insiders build released before the holidays. Hopefully, this is somewhat useful information.

**Comment by AaronFriel** [comment] 2017-01-12 22:05
Interesting, my desktop was unavailable for five weeks, from late November to a week ago, so I may not have been in PowerShell or noticed during that time.

**Comment by Robotia** [comment] 2017-01-14 08:58
The issue also manifests when using the shell on an android device via `adb shell` through cmd.

Oddly, a single ctrl+c creates 67 lowercase Cs every time:
![image](https://cloud.githubusercontent.com/assets/11097096/21953755/432383f8-da05-11e6-8f45-e176ebf96386.png)

**Comment by jwhipp** [comment] 2017-01-19 18:56
+1 tested with PS, cmd.exe and bash in Windows 10 Insider build 15007, used the default console as well as ConEMU.   Ctrl-C works in cmd.exe and bash but not in PS using both console applications.    Note that ctrl-c works in bash and cmd.exe if when they are launched from PS.

**Comment by Robotia** [comment] 2017-01-20 16:01
In build 15014, Ctrl + C is fixed in bash and cmd but not for PS.

**Comment by jwhipp** [comment] 2017-01-20 16:06
I am on 15014, and ctrl-c in PS is working for me now. 

You can't start typing a command then ctrl-c out if it, but ctrl-c works once something is running which is expected behavior.   I really can't say for sure if PS ever supported ctrl-c out of what you've typed like you can in bash.  I'll let the devs comment on that.

**Comment by simonbuchan** [comment] 2017-01-25 22:54
Is this possibly related to why I see Ctrl-C make `cmd.exe /c some windows commands` return to the prompt, but fail to kill the app?

```
0 app-tester 0 % cmd /c yarn add electron webpack
^C
0 app-tester 130 % yarn add v0.19.1
info No lockfile found.

0 app-tester 130 % [1/4] Resolving packages...

0 app-tester 130 %
<lots more yarn output...>
```

Note `cmd` not `cmd.exe` since I have an alias (as I'm using `/bin/login` which breaks importing the PATH), and I'm pressing enter to get a fresh prompt. Ctrl-C works as expected with native linux commands.

I also noticed while trying to get a nicer prompt that `cmd /c pause` doesn't... pause, and `cmd /c timeout ...` doesn't work at all, but I don't know if that's expected:

```
0 app-tester 0 % cmd /c pause
Press any key to continue . . . # no keypress!
0 app-tester 0 % cmd /c timeout 1
ERROR: Input redirection is not supported, exiting the process immediately.
0 app-tester 1 %
```

**Comment by apintocr** [comment] 2017-02-06 12:08
I'm on 15025 and can't do CTRL+C on PowerShell (using ConEmu or using default shell).
Works on Bash and CMD.

**Comment by jaysonsantos** [comment] 2017-02-10 17:22
With 15031 it started to work again

**Comment by KrunchMuffin** [comment] 2017-10-12 21:22
I am on 15063.608 and I can't get CTRL+C to work in any PS, CMD or BASH. Is there another issue?

**Comment by bitcrazed** [comment] 2018-05-22 23:13
Thanks for the discussion.

Closing this issue since:
1. This issue is very old and has likely been fixed in recent Win10 builds
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Closed by bitcrazed** 2018-05-22 23:13 UTC
Labels: console, ctrl-c
