### ISSUE TITLE
WSL2 Ubuntu-18.04 won't start

### ISSUE THREAD

**Issue by wildflower** [microsoft/WSL#4331] opened 2019-07-24 01:37 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18932.1000]

* What you're doing and what's happening:  
I upgraded following 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
this Ubuntu image was working on WSL 1

PS C:\WINDOWS\system32> wsl -e bash
A device attached to the system is not functioning.

PS C:\WINDOWS\system32> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2

* What's wrong / what should be happening instead:
It doesn't launch

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
[lxcore_etl.zip](https://github.com/microsoft/WSL/files/3424637/lxcore_etl.zip)

**Comment by mscraigloewen** [comment] 2019-07-24 16:58
Duplicate of #4155

**Closed by mscraigloewen** 2019-07-24 16:58 UTC
