### ISSUE TITLE
wsl.exe kills a program when it is put to background by "&"

### ISSUE THREAD

**Issue by karuboniru** [microsoft/WSL#4649] opened 2019-11-05 14:21 UTC
* Your Windows build number: 10.0.19013.1102]

* What you're doing and what's happening:  

  - Create a script in HOME named as test.sh 
  ```
  #!/bin/bash
  if [ -e ~/file1 ]; then
  	rm -f ~/file1
  fi
  ~/test1.sh &
  ```
  and test1.sh
   ```
   #!/bin/bash

   touch ~/file1
   ```
   - Run `chmod +x *.sh`
   - Run in bash as `./test.sh`
   - In cmd run `wsl ~/test.sh`

* What's wrong / what should be happening instead:
   - Run in bash as `./test.sh`
    `file1` shows up
   - In cmd run `wsl ~/test.sh`
   `file1` don't shows up

**Comment by therealkenc** [comment] 2019-11-06 19:51
> In cmd run wsl ~/test.sh
> file1 don't shows up

Can't follow this one. `file1` disappears because you've removed it. Closing because not actionable.

![image](https://user-images.githubusercontent.com/7049700/68332524-d4457f80-008b-11ea-8531-45a3ed1e2e31.png)

**Comment by karuboniru** [comment] 2019-11-07 02:41
> > In cmd run wsl ~/test.sh
> > file1 don't shows up
> 
> Can't follow this one. `file1` disappears because you've removed it. Closing because not actionable.
> 
> ![image](https://user-images.githubusercontent.com/7049700/68332524-d4457f80-008b-11ea-8531-45a3ed1e2e31.png)

Maybe I havn't descripte this clearly. In test.sh file1 is deleted and then call test1.sh which recreate that.
When ran inside bash, test1.sh is properly called and recreated file1.
When ran in wsl.exe test1.sh is not properly started and file1 will not be recreated.

**Comment by karuboniru** [comment] 2019-11-07 03:09
@therealkenc Here is a easier reproducement of this problem:
```
#!/bin/bash
if [ -e ~/file1 ]; then
	rm -f ~/file1
fi
touch file1 &
```
When the script is run by bash, `file1` is deleted and recreated.
When run by wsl.exe, `file1` is deleted and never recreated.

**Comment by therealkenc** [comment] 2019-11-07 08:59
You haven't specified a path to `touch file1` above (missing the `~`), but I see it now. Below is not intended as a work-around, but it does demonstrate the cause of the problem.
```
#!/bin/bash
if [ -e ~/file1 ]; then
	rm -f ~/file1
fi
touch ~file1 &
sleep 1
```

[Unfortunately running the script under `strace(1)` masks the problem also, so I can't fill out the issue template on your behalf.]

Long story short, you've got a `/bin/bash` instance that is about to die, and the shell [job](https://en.wikipedia.org/wiki/Job_control_(Unix)) is still running with a pty open. Which is at best problematic. Consider a background job that runs longer than your typical `touch`.
```
#!/bin/bash
if [ -e ~/file1 ]; then
        rm -f ~/file1
fi
/bin/bash -c "sleep 3; echo hello; /bin/touch $HOME/file1" &
```

I did try the scenario with `ssh` and the client does hang around for the server's children to exit. This behavior is _nonobvious_, but it does suggest intended behavior. So yeah, let's re-open on that basis.

![image](https://user-images.githubusercontent.com/7049700/68373225-4a330080-00f7-11ea-9522-ddf2ffae9429.png)

Launching a job on a bash instance _you know_ is about to die is still pretty iffy however. The fact that `ssh` hung around for 3 seconds utterly negated what (must be) your intent in putting `touch` in the background in the first place.

If you really want `touch(1)` to run in the background, you'd want to dissociate the pty with `[daemonize](https://software.clapper.org/daemonize/)` (or do something similar).

This does take in your `wsl.exe` scenario
```
#!/bin/bash
if [ -e ~/file1 ]; then
	rm -f ~/file1
fi
daemonize touch ~file1
```

**Comment by karuboniru** [comment] 2019-11-08 05:27
@therealkenc I think most time people would want `wsl.exe command` just act like `/bin/bash -c "command"` in a native linux shell. Using `touch` is just for simplifying the whole question. In fact, I'm trying to hack `xdg-open` to allow linux programs to open folders and files using Windows applications without changes in those linux programs.

But many linux programs (such as texdoc) call `xdg-open` by `xdg-open URL &`. That makes it impossible for me to use commands such as texdoc as `wsl texdoc -`, which is a must for a Windows side application to use `wsl something` to replace `something`

**Comment by therealkenc** [comment] 2019-11-08 16:15
> Using touch is just for simplifying the whole question

It doesn't simplify the question. You've spawned a job on a bash shell that is about to die. `cmd.exe` is not a bash shell. It doesn't have jobs.

**Comment by DHowett-MSFT** [comment] 2019-11-09 23:34
You may benefit from using `detach` to remove the job placed into the background (`&`) from the parent shell’s job control. It is, otherwise, nondeterministic as to whether touch completes before the shell exits and terminates it.

`touch file1 & disown`

**Comment by therealkenc** [comment] 2019-11-10 04:59
> It is, otherwise, nondeterministic as to whether touch completes before the shell exits

Any idea what strategy `ssh`/`sshd` uses to keep the session alive? Only ask because I didn't look deep myself; and because before I tried it, I mostly expected the nondeterministic behavior you cite above. I was a bit surprised to see `ssh` wait, instead of the child taking the `SIGHUP` and die. [This issue probably would have ended by-design otherwise.] This doesn't imply WSL interop needs to follow the `ssh` precedent, natch. Just that `ssh` waits was curious.

**Comment by kobenauf** [comment] 2020-01-25 15:27
I am struggling with a problem that might be a use-case for what is being requested.  When developing Rust projects, if I want to view the rust documentation, I can run `rustup doc --std`.  That is supposed to open a browser and load a local file in the browser.  It uses `xdg-open` to do this.  In WSL2 firefox opens correctly, but the browser never opens anything. 

For more detail on what I found, look at the comment I when I reported this to Rust:
https://github.com/rust-lang/rustup/issues/2206#issuecomment-576051236

**Comment by therealkenc** [comment] 2020-09-08 22:12
Tagging needs-attention insofar as the submission needs a ruling by-design versus absence of feature. Assuming an `sshd` running on WSL's default distro, a tight repro is:

```
C:\>wsl.exe sh -c "echo 'sleep 5 &' > $HOME/sleepscript.sh"
C:\>wsl.exe chmod 755 $HOME/sleepscript.sh
C:\>echo "" | wsl.exe $HOME/sleepscript.sh
C:\>echo "" | ssh.exe ken@localhost -p 2222 $HOME/sleepscript.sh
```

![image](https://user-images.githubusercontent.com/7049700/92531063-766d5100-f1e2-11ea-9d94-7c3b5c26b016.png)

Running `sleepscript.sh` via interop returns immediately. Running the script via Windows' `ssh.exe` will block for five seconds before returning to the command prompt. There's a strong-ish case they should behave the same.

**Closed** 2024-02-01 12:19 UTC
Labels: needs-investigation
