### ISSUE TITLE
Translations issues with parameters in localized help files

### ISSUE THREAD

**Issue by bgillet** [microsoft/WSL#8982] opened 2022-10-09 20:28 UTC
### Version

Microsoft Windows [version 10.0.22621.608]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

kali-linux

### Other Software

PowerShell 7.2.6

### Repro Steps

Just type `wsl --help` in a Terminal window.

### Expected Behavior

Help may be translated but not options that are used on command line otherwise, help is useless.

### Actual Behavior

WSL command line parameters are translated but it should not. Some dash characters are also missing.

![image](https://user-images.githubusercontent.com/3019854/194778010-b83746f5-428d-4431-b6c6-1c40a0d39b04.png)

![image](https://user-images.githubusercontent.com/3019854/194778052-4d1f469f-6f27-46b2-a167-7a98fdbbb201.png)

**Comment by upkit** [comment] 2022-10-24 05:56
![image](https://user-images.githubusercontent.com/31933684/197457356-99ed4828-b091-46b1-a465-25fc305798b1.png)
我也出现了

**Comment by orange-pig** [comment] 2022-11-02 07:26
Hope not to translate parameter and option names, it's Guess-based Usage!!!

**Comment by tingjhenjiang** [comment] 2022-11-27 11:29
I encounter this problem as well, [ref 6328](https://github.com/microsoft/WSL/issues/6328).

**Comment by Winson-Huang** [comment] 2022-12-08 08:14
Duplicate of #8857

**Comment by Mulf** [comment] 2023-06-14 17:08
Do you guys find some way to fix this?

**Closed** 2024-06-20 12:11 UTC
Labels: localization
