### ISSUE TITLE
Cannot install oracle-java8-installer with jdk1.8.0_111

### ISSUE THREAD

**Issue by mattpodwysocki** [Microsoft/WSL#1321] opened 2016-11-04 18:12 UTC
Installing the Oracle Java 8 JDK update 111 no longer works on WSL since the change from update 101 to 111.  It seems that dmesg is necessary, but not supported on WSL.

This is the truncated result once the JDK was downloaded from Oracle:
```
Download done.
Removing outdated cached downloads...
mv: cannot move 'jdk1.8.0_111' to 'java-8-oracle': Permission denied
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2ubuntu1) ...
dmesg: read kernel buffer failed: Function not implemented
                                                          /bin/df: /proc/sys/fs/binfmt_misc: Operation not permitted
                                                                                                                    Setting up x11-common (1:7.7+13ubuntu3) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up xfonts-encodings (1:1.0.4-2) ...
Setting up xfonts-utils (1:7.7+3) ...
Setting up gsfonts-x11 (0.24) ...
dpkg: dependency problems prevent configuration of oracle-java8-set-default:
 oracle-java8-set-default depends on oracle-java8-installer; however:
  Package oracle-java8-installer is not configured yet.

dpkg: error processing package oracle-java8-set-default (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.23-0ubuntu3) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Processing triggers for systemd (229-4ubuntu8) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 oracle-java8-installer
 oracle-java8-set-default
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Windows Build: Windows 10 Build 14959

Reproduction steps:

```
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install -y oracle-java8-installer
```

**Comment by therealkenc** [comment] 2016-11-04 20:17
Setting aside a permissions problem on `/dev/kmsg`, relevant strace looks like:
```
open("/dev/kmsg", O_RDONLY|O_NONBLOCK)  = 3
lseek(3, 0, SEEK_DATA)                  = -1 EINVAL (Invalid argument)
read(3, 0x60c3e0, 8191)                 = -1 EAGAIN (Resource temporarily unavailable)
close(3)                                = 0
```
This is one of those (many) cases where stubbing functionality in  WSL would go a long way. Even if all WSL's `/dev/kmesg` contained was the following string it would be a start, and we could see what Oracle was grepping for.
```
5,0,0,-;Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014
```

**Comment by benhillis** [comment] 2016-11-04 21:00
On an internal build I was able to follow the reproduction steps without any install failures... Interesting.

**Comment by therealkenc** [comment] 2016-11-05 00:17
I didn't do an Oracle install, but `sudo dmesg` definitely fails with the `dmesg: read kernel buffer failed: Function not implemented` for me.

**Comment by benhillis** [comment] 2016-11-05 00:29
@therealkenc - Awesome thanks for the clarification. I really like your idea of prepopulating the /dev/kmsg buffer with something (since usually init and other deamons would have written a bunch of stuff to it).

**Comment by therealkenc** [comment] 2016-11-05 00:55
Awesome. Please note the perms while you're there. Should be 644.

**Comment by hdave** [comment] 2016-11-23 14:59
Maybe I'm coming into this wrong, but I am have installed Oracle Java 8 from within Windows, and then from within WSL set my JAVA_HOME to that directory added JAVA_HOME/bin to my path and aliased java='java.exe' and so far it seems to work.   Is there some reason we can't redirect WSL to the Windows installation of Java?  I realize that update-alternatives thinks no java is installed....

**Comment by therealkenc** [comment] 2016-11-23 19:19
Now that pipe marshaling is working it's going to start getting pretty weird for people flying a platform indirection up: JVM, CLR, now wasm (you can never have too many). At least for CLI use cases. So yeah, it's a reasonable work-around. 

Problem, as has been the case for going on 20 year now, is the house of cards falls down once you escape into any nontrivial domain. Microsoft didn't write Edge in C#, and Google didn't write Chrome in Java. Because no one is really willing to drink the cool-aid. If they were, there'd be no reason for WSL in the first place.

**Comment by stehufntdev** [comment] 2017-04-13 21:18
As a workaround to the dmesg failure, please first write something to /dev/kmsg (e.g. `echo foo > /dev/kmsg`).  As mentioned above, dmesg always expects there to be some data in /dev/kmsg which isn't always the case on WSL.

Marking this as a bug so we can track fixing the behavior difference.

**Comment by spoiledsport** [comment] 2017-04-13 23:49
Actually there is  workaround. First of all, after making the change, dmesg doesn't print what is expected of it. Second, this only works for the current window. After you exit bash and start it again, you are back to the same issue.

This worked in previous version of WSL. It actually showed the correct output

**Comment by stehufntdev** [comment] 2017-04-14 00:58
For the workaround you should be able to always write sometime to /dev/kmsg (e.g. put the line above in bash.rc).  Init and other components log through /dev/kmsg so something probably changed in the configuration.  Realistically dmesg shouldn't fail this case but it probably never happens in practice on native Linux.

This is marked as a bug so we will look at fixing it for insider builds.

**Comment by daiconrad** [comment] 2017-04-15 13:30
@hdave What do you mean when you say "so far it seems to work"? If I'm in a BoW directory, I get:

    $ /mnt/c/Program\ Files/Java/jdk1.8.0_121/bin/java.exe Foo
    Unable to translate current working directory. Using C:\WINDOWS\system32
    Error: Could not find or load main class Foo

OTOH, it does work in a directory under /mnt/c

**Comment by Silver-Fang** [comment] 2017-12-12 08:11
@stehufntdev `sudo echo foo > /dev/kmsg` returns `-bash: /dev/kmsg: Permission denied`

**Comment by Brian-Perkins** [comment] 2017-12-12 16:39
You can do something like: echo foo > sudo tee /dev/kmsg

**Comment by therealkenc** [comment] 2018-01-12 20:30
@benhillis in Nov 2016

> I really like your idea of prepopulating the `/dev/kmsg` buffer with something (since usually init and other deamons would have written a bunch of stuff to it).

Pinging because that inexplicably seems to work.

**Comment by almdrx** [comment] 2018-02-13 20:39
Here from #1886 

Just my 2 cents... 

* won't run `dmesg`, returns `dmesg: read kernel buffer failed: Function not implemented`
* `echo foo > /dev/kmsg` returns `bash: /dev/kmsg: Permission denied`

However if passed as a quoted command ...
 
```
user@host:/mnt/c $ sudo bash -c "dmesg -w"
[    0.000000] 
user@host:/mnt/c $ sudo bash -c "echo foo > /dev/msg"
user@host:/mnt/c $
```

**Comment by therealkenc** [comment] 2018-02-20 19:03
`foo` is not a well formed [`kmsg`](https://www.kernel.org/doc/Documentation/ABI/testing/dev-kmsg). You want something like (n.b. the `k` is missing above "However..."):
```
$ sudo bash -c "echo '5,2,0,-;Hello from WSL. Linux version 4.4.0-17101-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4. (GCC) ) #1000-Microsoft Sun Feb 11 10:40:00 PST 2018' >> /dev/kmsg"
```

But, unfortunately, this doesn't seem to take for _reasons_. You can get over the hard `lseek()` [fail](https://github.com/Microsoft/WSL/issues/1321#issuecomment-258536757) by putting _anything_ in the buffer, but it appears that the WSL device corrupts input (or prepends cruft to the output, take your interpretation):
```
ken@DESKTOP-4UTIQSF:~$ cat /dev/kmsg
▒==g▒Z▒▒$5,2,0,-;Hello from WSL. Linux version 4.4.0-17101-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4. (GCC) ) #1000-Microsoft Sun Feb 11 10:40:00 PST 2018
```
This is why `dmesg` always looks something like this in WSL, even after daemons have written to it:
```
$ dmesg
[    0.000000]
```

Same `echo` test works on Real Linux™, natch. 

Given that `rsyslogd` is also inoperable per #534, this pretty much blocks the ability for daemons (which give up the terminal) to provide any kind of feedback to the user. 

As an aside, marking this [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13653522-consider-enabling-cron-jobs-daemons-and-backgroun) as in-preview is, to choose a word generously, "premature". Also worth noting this bug has been open since 2016.

**Comment by therealkenc** [comment] 2018-07-13 18:10
Support for `/dev/kmsg` was added in [17655](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17655-skip-ahead).

**Closed by therealkenc** 2018-07-13 18:10 UTC
Labels: bug, workaround-available

**Comment by kenorb** [comment] 2018-10-04 16:01
After [upgrading WSL](http://wsl-guide.org/en/latest/update.html), it seems to work.
