### ISSUE TITLE
UDP packets of size less than 12 bytes are not sent from WSL to host

### ISSUE THREAD

**Issue by qqshka** [microsoft/WSL#8610] opened 2022-07-13 20:01 UTC
### Version

Microsoft Windows [Version 10.0.22000.795]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

1. Run some sort of UDP server on the host system, in my case I use primitive server writen in golang. Wireshark also is fine.
2. Send UDP packets from the WSL2 system to the host, in my case I use netcat command line utility.
![wsl2-udp-bug](https://user-images.githubusercontent.com/543612/178820044-545dc54a-8209-4ebc-96ee-4c38f93948d7.png)

### Expected Behavior

I sent few UDP packets from WSL2 to the host, starting with UDP payload size of 2 bytes up to 13 bytes, expecting to receive all packets.

### Actual Behavior

Only packets with payload size 12 or more received on the host.

**Comment by elsaco** [comment] 2022-07-14 15:22
@qqshka try `scapy` also. While using `nc` couldn't send small UDP payloads, it works with scapy:

```
>>> send(IP(dst="192.168.64.1")/UDP(sport=5201,dport=5201)/Raw(load="1"))
.
Sent 1 packets.
>>> send(IP(dst="192.168.64.1")/UDP(sport=5201,dport=5201)/Raw(load="12"))
.
Sent 1 packets.
>>> send(IP(dst="192.168.64.1")/UDP(sport=5201,dport=5201)/Raw(load="123"))
.
Sent 1 packets.

```

and the listener on Windows side:

![image](https://user-images.githubusercontent.com/3933920/179017919-156a072c-423c-499e-8ce8-0a7d244af418.png)

**Comment by qqshka** [comment] 2022-07-14 22:59
And your point is? Yes **scapy** works while **nc** does not works. The thing is **nc** here was as example how to reproduce it, the fact is almost **any** application could not send short UDP packets. **scapy** seems to be an exception since I guess it uses raw sockets or something.

**Comment by lucasdrufva** [comment] 2022-07-21 07:26
Got the same issue after a recent windows update, currently on OS version 19044.1826

**Comment by wavemobileDev** [comment] 2022-07-22 10:17
After a lot of messing around trying to debug a test system I can confirm that I have found exactly the same issue. Two of our test systems failed pretty much at the same time, both use UDP based comms (small packets) and Win10/11 with WSL Ubuntu 20.04.4 LTS. Both systems also received Windows updates over the time of failure.

Thank you to qqshka for reporting this - I was beginning to think I was going mad as I went down the rabbit hole of routing, bridging, NAT'ing and firewalls before stumbling on the length issue by typing a cursing rant into netcat!

**Comment by markymarrow** [comment] 2022-07-22 15:00
I'm seeing similar behaviour from an ubuntu-22.04 hyper-v host.
I've spent the day wondering why a tftp transfer was failing - the last packet was 4 bytes,
Adding 8 zero bytes to the end of the file 'fixed' the transfer.

So, might not be WSL's fault?

This is running Windows 11 pro 21H2 (22000.795)

**Comment by gdumke** [comment] 2022-07-22 17:04
I used iperf3 between a WSL2 distro on a Win10 machine (client side) and a Fedora 36 machine (server side) to test the UDP transfers:

- If the client is running Win10 19044.1766 it works like a charm.

- If the client is running Win10 19044.1826, the connection is made but the UDP traffic is blocked (leading to "iperf3: error - unable to read from stream socket: Resource temporarily unavailable").

iperf3 command on client side was `sudo iperf3 -4 -u -c xx.xx.xx.xx -p 5555`
Not found any workaround so far.

**Comment by jstarks** [comment] 2022-07-27 17:06
We are looking into this. In the meantime, you should be able to work around this by disabling checksum offload from within WSL. As root: 

```bash
ethtool -K eth0 tx off
```

This is global across all your distros, but it is not persisted across WSL restarts.

**Comment by dktapps** [comment] 2022-08-18 19:56
I and my team have encountered this in several programs including PHP.

I can confirm that uninstalling update `KB5015807` solves the problem.

**Comment by xulonc** [comment] 2022-08-22 16:22
I have same problem
![141b89060314b6513b340fe76127fe4](https://user-images.githubusercontent.com/77042549/185970516-a849d695-f4de-46b5-9e8a-cdbe643f597a.jpg)

**Comment by julianxhokaxhiu** [comment] 2022-09-01 13:41
Can confirm I had the same problem testing a [simple game server echo bot from Agones](https://agones.dev/site/docs/getting-started/create-gameserver/#3-connect-to-the-gameserver).

**Comment by kvnnap** [comment] 2022-09-12 08:05
Same issue here when using netcat inside WSL2 (or any app using UDP). Small packets do not go through to the receiving end while larger packets do go through. Receiving packets from the other end into WSL2 netcat client works for any size.

**Comment by BubbaJoeX** [comment] 2022-09-20 22:26
Can confirm this issue.

**Comment by PJB3005** [comment] 2022-09-23 18:08
Can confirm, this isn't specific to WSL. It also happens on other Hyper-V VMs, which is how I found this issue (god what a debugging nightmare).

**Comment by gdumke** [comment] 2022-09-27 07:41
> We are looking into this. In the meantime, you should be able to work around this by disabling checksum offload from within WSL. As root:
> 
> ```shell
> ethtool -K eth0 tx off
> ```
> 
> This is global across all your distros, but it is not persisted across WSL restarts.

@jstarks what is the status on this issue please?
We desperately need a fix for this as it impacts a few of our products on the field. The workaround you mentioned is helping a lot but it makes our processes heavier (we need to restart the WSL engine quite a few times a day as we often need to bridge/unbridge the WSL network in order to send broadcast messages from our distros), and not all of us are familiar with CLI.

Is there an estimate on when a fix will be released?

**Comment by gdumke** [comment] 2022-11-14 14:47
It seems fixed by a recent Windows update. However I don't know which one.
I'm running Windows 10 Pro 21H2 build 19044.2130 (last update being KB5018410) and it looks okay.

**Comment by julianxhokaxhiu** [comment] 2022-11-15 08:34
Can confirm that I'm also on 10.0.19045.2251 and it seems to work fine now.

**Comment by xulonc** [comment] 2022-11-15 08:40
I'm windows 11 ( 22H2 22621.819) work fine

**Comment by ravnlock** [comment] 2023-01-16 21:29
Win 11 (22H2 22621.525) still has this problem.

22621.525 is apparently KB5019311, released Sep 27, 2022.
22621.819 is apparently KB5019980, released Nov 8, 2022.

If necessary, this may help someone track down the specific change.

**Comment by grpatter** [comment] 2023-01-16 21:29
Win 11 (22H2 22621.525) still has this problem.

As per https://support.microsoft.com/en-gb/topic/windows-11-version-22h2-update-history-ec4229c3-9c5f-4e75-9d6d-9025ab70fcce
22621.525 is apparently KB5019311, released Sep 27, 2022.
22621.819 is apparently KB5019980, released Nov 8, 2022.

If necessary, this may help someone track down the specific change.

**Comment by Cyvster** [comment] 2023-04-11 03:35
I had this issue the entire time I was running server 2016. I was running a game called SWGEMU in a hyper-v VM with Ubuntu 20.04. I was encountering constant disconnects in that game until I ran the above command(ethtool -K eth0 tx off). I had to run that command every time I started the VM.

I just upgraded to server 2019 and the issue is resolved. I no longer have to run that command on the VM to stay connected to the game server.

**Comment by esolk** [comment] 2023-09-05 03:14
> > We are looking into this. In the meantime, you should be able to work around this by disabling checksum offload from within WSL. As root:
> > ```shell
> > ethtool -K eth0 tx off
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is global across all your distros, but it is not persisted across WSL restarts.
> 
> @jstarks what is the status on this issue please? We desperately need a fix for this as it impacts a few of our products on the field. The workaround you mentioned is helping a lot but it makes our processes heavier (we need to restart the WSL engine quite a few times a day as we often need to bridge/unbridge the WSL network in order to send broadcast messages from our distros), and not all of us are familiar with CLI.
> 
> Is there an estimate on when a fix will be released?

This solve my problem.  I'm working on 22621.2215 , and the client is Ubuntu18.04 on WSL2. Thanks alot

**Closed** 2024-09-05 12:27 UTC
Labels: network
