### ISSUE TITLE
Poor performance with WSL2 and Windows 11

### ISSUE THREAD

**Issue by matpil** [microsoft/WSL#11565] opened 2024-05-07 08:18 UTC
### Windows Version

Microsoft Windows [Versione 10.0.22631.3447]

### WSL Version

2.2.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

Ubuntu 22.04

### Other Software

git version 2.39.2
Debian version 12.5

### Repro Steps

fresh Debian installation
cloning repo git on native wsl2 fs
launch a "git pull" command

### Expected Behavior

The "git pull" execution time should be around 3-4 seconds

### Actual Behavior

The “git pull” execution time takes up to 20-22 seconds

![image](https://github.com/microsoft/WSL/assets/546865/49387ae9-2043-4e24-a53d-40fe46c9124f)

### Diagnostic Logs

[WslNetworkingLogs-2024-05-07_10-23-15.zip](https://github.com/microsoft/WSL/files/15232733/WslNetworkingLogs-2024-05-07_10-23-15.zip)

**Comment by matpil** [comment] 2024-05-07 08:26
[WslNetworkingLogs-2024-05-07_10-23-15.zip](https://github.com/microsoft/WSL/files/15232718/WslNetworkingLogs-2024-05-07_10-23-15.zip)

Here the WSL logs

**Comment by OneBlue** [comment] 2024-05-07 21:00
Thank you @matpil. This delay could be caused by a variety of things, like a slow network connection, or a slow authentication go git.

Do you see the same behavior if let's say you clone / pull a public repo, like https://github.com/microsoft/WSL ?

**Comment by matpil** [comment] 2024-05-08 08:45
Hi,
If I clone a public repo (the same you suggest) the response time is ok
![image](https://github.com/microsoft/WSL/assets/546865/d1ee1966-05df-4bb5-b1be-ef0245168eb8)

To connect to our git server I use a ssh connection (by sshkey)
![image](https://github.com/microsoft/WSL/assets/546865/3024489a-52b8-4307-a9b8-b54550f0fa6c)

btw, I feel to exclude a slow network connection; I don't know how to test a slow auth (as I said, it's by sshkey)

have you any suggest?

**Comment by OneBlue** [comment] 2024-05-08 17:20
Thank you for confirming @matpil. 

The fact that cloning a public repository doesn't reproduce the issue shows the performance problem doesn't come from WSL, so I'll close this issue.

Here are a couple ideas to help you root cause the issue: 

- Look into whether you have configured [git credential manager on WSL](https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-git#git-credential-manager-setup), and see if removing it solves the issue

- Try to run `strace -f git pull` and see where the time is spent

- Check if your ~/.ssh/config has ForwardArgent or ForwardX11, and try to remove those options

**Closed by OneBlue** 2024-05-08 17:20 UTC
