### ISSUE TITLE
WSL2  ERROR: InitCreateProcessUtilityVm:1938: splice failed -1 32

### ISSUE THREAD

**Issue by pawelchcki** [microsoft/WSL#4375] opened 2019-08-04 09:24 UTC
While using WSL2 at one point I found my laptop making some extra fan noise even when I wasn't running any CPU heavy code. Windows process manager shows Vmmem using 15-20% of CPU constantly.

In WSL2 prompt running `top` showed `/init` process with a high pid (31290) using 100% of a CPU constantly.
Looking at dmesg show its spammed with following messages:
```
[23761.347395] init: (31290) ERROR: InitCreateProcessUtilityVm:1938: splice failed -1 32                                [23761.347398] init: (31290) ERROR: InitCreateProcessUtilityVm:1938: splice failed -1 32                                [23761.347402] init: (31290) ERROR: InitCreateProcessUtilityVm:1938: splice failed -1 32                                
```
Running `strace -s 9999 -f -p 31290` shows init process stuck in a loop doing:
```
poll([{fd=-1}, {fd=17, events=POLLIN}, {fd=19, events=POLLIN}, {fd=-1}, {fd=6, events=POLLIN}, {fd=15, events=POLLIN}, {fd=14, events=POLLIN}], 7, -1) = 1 ([{fd=19, revents=POLLIN}])
splice(19, NULL, 13, NULL, 4096, 0)     = -1 EPIPE (Broken pipe)
getpid()                                = 31290
writev(3, [{iov_base="<3>init: (31290) ERROR: InitCreateProcessUtilityVm:1938: splice failed -1 32\n", iov_len=77}, {iov_base=NULL, iov_len=0}], 2) = 77
```

### Windows version
`Microsoft Windows [Version 10.0.18950.1000]`

### Steps to reproduce
I noticed the issue it after a few cycles of setting my laptop to sleep after about 1 day since I had run some heavy commands. So its hard to tell what exactly triggered this issue.

Software I'm running in wsl2:
- docker (via service docker start)
- Remote WSL is vscode
- gcc, make, autotools etc

**Comment by Biswa96** [comment] 2019-08-04 10:16
> /init process with a high pid (31290)

This thing looks suspicious! Did you open too many WSL instances? Is the memory usage too high? Can you reproduce with a specific command? One interesting thing is that the first `fd` in `poll` may/should be positive because it's a input socket.

**Comment by pawelchcki** [comment] 2019-08-04 12:03
Currently my memory use oscillates around 2.5GB for whole Vmmem. I have opened two WSL2 terminal windows. 1 using default one using "Windows Terminal (preview) 0.3.2142.0".
Otherwise I noticed this issue while doing other things, so its hard for me to pinpoint exactly what triggered it. 
I just tried a few commands I probably had run before and so far everything is working as expected.

Note I've since killed that Process by `-9` it.
If I'm able to get more data I'll be sure to post it here.

**Comment by benhillis** [comment] 2019-08-04 14:41
Thanks for posting, I have enough details to fix this issue.

**Comment by Biswa96** [comment] 2019-08-04 17:21
Interesting. While reproducing OP's tests, I ran `strace -f -p 1 -v` as root, then press Ctrl+C after 2 sec. and whole wsl.exe process crashed with high memory usage. Is this a bug or normal Linux-ish things?

The pid 1 is of init process.

**Comment by benhillis** [comment] 2019-09-11 17:20
Fixed in [18990](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-18980).

**Closed** 2020-06-24 21:11 UTC
Labels: fixedinreleasebuild, wsl2
