### ISSUE TITLE
 what():  connect: No buffer space available

### ISSUE THREAD

**Issue by nonyy** [Microsoft/WSL#3986] opened 2019-04-20 17:34 UTC
I made boost::asio program that connects using TCP. On pure Linux it works fine, on WSL it throws the error in tittle.

Any idea how to fix it? Editing parameters doesn't work on WSL apparently.

**Comment by Biswa96** [comment] 2019-04-20 20:32
Any minimal, compact, reproducible sample code?

**Comment by nonyy** [comment] 2019-04-21 12:27
@Biswa96 @therealkenc can I send it using email? Private code.

**Comment by Biswa96** [comment] 2019-04-21 14:18
You don't have to send the actual code. Provide the minimal code the can cause the issue.

For example, let say WSL don't know about `printf()` and it shows error with it.

E.g. your actual code:

```c
#include <stdio.h>

int main()
{
    printf("my hidden secrets");
}
```

Minimal code that reproduce this issue:

```c
#include <stdio.h>

int main()
{
    printf("yolo");
}
```

**Comment by nonyy** [comment] 2019-04-21 19:18
@Biswa96 I thought that it happened due to the size of data I was sending but it seems even connection creation throws it. I will send a sample soon.

**Comment by nonyy** [comment] 2019-04-21 19:28
Alright here's a sample.

What I am trying to achieve: TCP punchthrough (basically 2 clients connecting at the same time).
However, localhost should do the job. Requires boost::asio and linking against boost_system (-lboost_system).

```cpp
#include <iostream>
#include <boost/asio.hpp>
#include <thread>

using boost::asio::ip::tcp;
using namespace std;

typedef unsigned short int us;

struct Client {
	string ip;
	us port;
};

void usage()
{
	cout << "<string> friendIp <unsigned short int> friendPort <unsigned short int> localPort" << endl;
}

string readMessage(tcp::socket& socket)
{
	char buffer[200];
	socket.read_some(boost::asio::buffer(buffer, 200));

	string data(buffer);
	return data;
}

void sendMessage(tcp::socket& socket, string message)
{
	boost::asio::write(socket, boost::asio::buffer(&message, sizeof(message)));
}

tcp::socket connect(Client client, us local_port)
{
    boost::asio::io_service io_service;

    tcp::socket socket(io_service, boost::asio::ip::tcp::v4());

    boost::asio::socket_base::reuse_address option(true);
    socket.set_option(option);

        socket.bind(boost::asio::ip::tcp::endpoint(
      boost::asio::ip::tcp::v4(), local_port));

    boost::system::error_code err;
	cout << "Trying to connect..." << endl;
	int i = 1;
    do {
    socket.connect(tcp::endpoint(boost::asio::ip::address::from_string(client.ip.c_str()), client.port), err);
	cout << "Connection try nr " << i << endl;
	
	if(err.value() > 0)
		cout << "Error code: " << err.value() << endl;
	
	++i;
    } while(err.value());
    return socket;
}

void serve(us port)
{
    boost::asio::io_service io_service;
    tcp::acceptor acceptor(io_service, tcp::endpoint(tcp::v4(), port ));
    tcp::socket socket(io_service);

    acceptor.accept(socket);
}

int main(int argc, char* argv[])
{
    if(argc < 4) 
	{
		usage();
		return 0;
	}

	string fr_ip = argv[1];
	unsigned short int fr_port = atoi(argv[2]);
	unsigned short int local_port = atoi(argv[3]);

	
	std::thread server_thread(serve, local_port);
	
	Client fr;
	fr.ip = fr_ip;
	fr.port = fr_port;

	auto s = connect(fr, local_port);
	string m = "hi from small laptop";
	sendMessage(s, m);
	m = readMessage(s);
	cout << "Message from fr: " << m << endl;
	server_thread.join();

  return 0;
}
```

**Comment by therealkenc** [comment] 2019-04-21 20:06
`./a.out 127.0.0.1 7000 7001` yields the same output on WSL as Real Linux -- stream of `ECONNREFUSED`. No usage no strace, which is most unfortunate.

> boost::asio::socket_base::reuse_address option(true);
> socket.set_option(option);

Gonna say #3909 for lack.

**Comment by nonyy** [comment] 2019-04-22 09:44
@therealkenc 
_./a.out 127.0.0.1 7000 7001 yields the same output on WSL as Real Linux -- stream of ECONNREFUSED. No CLI no usage no strace, which is most unfortunate._

Sure, because as I said - 2 clients connecting at the sime time. So you should run a second console with 2nd client. For me it works on localhost. Problem with buffer starts when connecting outside.

**Comment by nonyy** [comment] 2019-04-22 20:16
@therealkenc I can't really reproduce it anymore after using some googled command to increase buffer space on WSL Linux.

**Comment by therealkenc** [comment] 2019-04-22 20:42
> googled command to increase buffer space on WSL Linux.

What command. 

There aren't any network tunables _on WSL_ (WSL doesn't have a network stack). The [`/proc` entries](https://github.com/Microsoft/WSL/issues/1809) aren't emulated presently. _Windows command_, maybe, plausibly. Can't say for lack of `ENOBUFS` (really `WSAENOBUFS` under the hood) repro to follow here.

In any event, thanks for the report. Closing for lack of actionable, but the issue can serve as a reasonable search target if it comes up again.

**Closed by therealkenc** 2019-04-22 20:42 UTC
Labels: need-repro

**Comment by nonyy** [comment] 2019-04-22 23:48
@therealkenc My guess is that it is a Windows limit that I hit. To setup TCP punchthrough for NAT I need to start connecting A ---- > B    B ------> A at the same time. So I get a bunch of requests that are refused before real connection is created. And this seems to hit a hardcoded limit. I guess rebooting my machine did the job.

You can consult with networking team at Microsoft if this is right explanation of getting this error.

Besides another "weirdness" on Windows - ports are automatically reused across sockets, no extra config required while on Linux it throws port already in use.

So I guess there's another problem WSL team needs to face someday - differences between behavior on Linux and on Windows re: networking.

**Comment by therealkenc** [comment] 2019-04-23 00:54
> So I get a bunch of requests that are refused before real connection is created.

That'll definitely trigger #3951 (formerly #2913). However your OP issue title implies a `ENOBUFS` contrast `EINVAL`.

> I guess rebooting my machine did the job.

Yes. That or restarting LxssManager.

> And this seems to hit a hardcoded limit.

No, all the ip4v limits are configurable on Windows too, as opposed to hard-coded. With effort. But the defaults allow teenagers to download Game of Thrones using (Windows) bittorrent without too much trouble, so that's probably not the cause of your `ENOBUFS` (in isolation).

> Besides another "weirdness" on Windows - ports are automatically reused across sockets, no extra config required while on Linux it throws port already in use.

That's #3909.

**Comment by nonyy** [comment] 2019-05-11 22:01
@therealkenc happened again for no reason, I will try to make a repro.
