### ISSUE TITLE
[BUG] Ctrl+r, input some, Tab, get Suspended !

### ISSUE THREAD

**Issue by nzaquini** [microsoft/WSL#10231] opened 2023-06-22 10:56 UTC
### Windows Version

Microsoft Windows [Versione 10.0.22000.978]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Input Ctrl+r, show: (reverse-i-search)`':
input some thing, like sou show: (reverse-i-search)`sudo mo': sudo mount /dev/sdd1 /mnt/d
Input Tab Then can not do anything

Please consider reopening issue #5934 which was closed to early.
Put there and here the solution please.

### Expected Behavior

Having the possibility to change the command and press <enter> to run it

### Actual Behavior

Stops for several seconds before running the command.

**Comment by onomatopellan** [comment] 2023-07-09 22:16
Please take a look at this thread https://github.com/microsoft/WSL/issues/4966

**Comment by onomatopellan** [comment] 2023-07-14 18:20
If the workaround works for you then it's the same issue. That thread was [closed as a duplicate](https://github.com/microsoft/WSL/issues/4966#issuecomment-837446816) of issue #4197. In WSL2 the access to /mnt/ folders can be so slow that it freezes things like reverse-i-search. The problem is after 3 years the reason why this happens [can't be solved.](https://github.com/microsoft/WSL/issues/4197#issuecomment-604592340)

**Closed** 2024-07-18 12:10 UTC
