### ISSUE TITLE
"Illegal operation attempted on a registry key that has been marked for deletion."

### ISSUE THREAD

**Issue by anorman728** [Microsoft/WSL#3263] opened 2018-05-31 14:17 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
    * Microsoft Windows [Version 10.0.17134.48]
    * Running on a new-ish Surface Book 1, if that's relevant.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

![wsl error](https://user-images.githubusercontent.com/22553388/40787270-d279c524-64b2-11e8-8ffb-555d0bf67004.PNG)

* What's wrong / what should be happening instead:
    * After I *start* my machine and run WSL, I get the above error.  After a *restart*, it works fine.  (Maybe the Surface Book is going into a sort of pseudo-hibernation instead of actually shutting down when I hit the shut down command?)

I'm seeing someone else having the same problem, but no responses.
https://social.technet.microsoft.com/Forums/windows/en-US/2083b5c6-e4b8-45ba-9b3a-05dffd112258/windows-subsystem-for-linux-wont-start-after-restart?forum=win10itprogeneral

**Comment by DarthSpock** [comment] 2018-05-31 15:05
Dupe of #2576

**Comment by benhillis** [comment] 2018-05-31 15:37
Fix is making its way to insider builds and 1803. For now disable fast boot as a workaround.

**Closed by benhillis** 2018-05-31 15:37 UTC

**Comment by Biswa96** [comment] 2018-05-31 15:41
Is that only in 1803 or in any insiders build?

**Comment by benhillis** [comment] 2018-05-31 15:43
Issue also exists in insider builds.
