### ISSUE TITLE
Issue with bash hanging on startup

### ISSUE THREAD

**Issue by ghost** [microsoft/WSL#4968] opened 2020-03-13 20:16 UTC
System info: Microsoft Windows [Version 1909 18363.719]
Distribution: 20190521 build of Ubuntu 18.04 LTS

When I open it with Windows Terminal, Ubuntu, or even cmd, the result is the same. The terminal just hangs, I can't do anything. Ctrol + C doesn't do anything either. I can write all I want but nothing is ever done, it just shows what I write and does nothing.
The only way to get it operational again is rebooting the computer. And even then, sometimes it will just randomly stop working and hangs again, it just freezes. Plus, whenever this happens, there are like 8 files, all called "init" that appear on the Task Manager and takes up 70% of my CPU, rendering my computer useless until the next reboot. 
I have seen this issue on other threads (#3392 for example) but those are quite old, I wouldn't know if they could work on my case. I am quite new to programming, so I don't understand a bunch of these things. 
Any help would be greatly appreciated.

**Comment by KaytonFletcher** [comment] 2020-03-14 00:39
Having the same issue

**Comment by VonDyring** [comment] 2020-03-14 03:21
Same issue

**Comment by Aenariss** [comment] 2020-03-14 10:22
Same issue

**Comment by rcheng15jhu** [comment] 2020-03-15 04:05
Same issue with Windows 10 Home 1903 18362.720, Ubuntu 16.04.

This problem only started happening recently. If I recall correctly, it started after some windows updates, namely after KB4537759, a little longer than a week ago.

![image](https://user-images.githubusercontent.com/14796830/76694877-94e8fa00-664e-11ea-911c-66cbcc7b1b0c.png)

The init file is in the CanoicalGroupLimited/LocalState/rootfs folder.

It looks like there is also a suspended mount process in task manager. m ount is is rootfs/bin.

**Comment by rcheng15jhu** [comment] 2020-03-15 04:08
In addition, the init processes sometimes start without even having to intentionally launch Ubuntu. It seems like this happens when I am checking windows update. When this happens, the CPU usage is also quite high.

**Comment by boulderwebdev** [comment] 2020-03-15 22:04
I'm having the same problem. My computer is Window 10 Pro, version 1903.

**Comment by laybak** [comment] 2020-03-16 18:16
had the same issue, followed this link to update the Linux kernel and it worked: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

for more context, I tried starting bash in the command prompt and got this error message: 
`WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`

**Comment by juannegro** [comment] 2020-03-16 18:31
> had the same issue, followed this link to update the Linux kernel and it worked: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel
> 
> for more context, I tried starting bash in the command prompt and got this error message:
> `WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel`

The issue is that I don't have WSL 2, I have the first version. You can see that my version is 18363, not 18917 or higher

**Comment by sirredbeard** [comment] 2020-03-17 15:32
Seeing these multiple init processes go to that level is odd.

The WSL init should only be mounting /mnt/c and any other custom mounts you have configured in /etc/wsl.conf

This issue should not be confused with issues with the kernel in WSL2 in the recent change in slow ring that @laybak had.

KB4537759 was an Adobe flash security update, so I am not sure about that one.

I will monitor this thread for more reports.

Some things to try:

* Shutting Ubuntu down with wsl --terminate Ubuntu...
* Starting and stopping LXSS: sc stop LxssManager then sc start LxssManager
* Disabling and re-enabling WSL in Windows
* Resetting Ubuntu on WSL (after backing up your data using wsl --export... or Raft WSL)

**Comment by rcheng15jhu** [comment] 2020-03-17 21:19
![image](https://user-images.githubusercontent.com/14796830/76902278-094fb300-6872-11ea-84ca-7600a998236f.png)

So, this is quite odd, but simply navigating to the LocalState folder seems to start up the init processes. It could also just be coincidence, but I believe this has happened to me multiple times already. There are only three init processes this time though.

I also don't seem to have a wsl.conf file in the rootfs/etc folder.

I'll try some of the other things sirredbeard mentioned when I have time.

**Comment by rcheng15jhu** [comment] 2020-03-17 21:45
So, wsl --terminate Ubuntu-16.04 doesn't seem to do anything when there are multiple init processes. It just sits there until I Ctrl-C out of it.

And there also seems to be a different number of init processes every time. Sometimes 3, 7, 9, etc.

**Comment by sirredbeard** [comment] 2020-03-18 15:13
Do you have any third-party security software running that could be interfering with the init mounting process?

**Comment by juannegro** [comment] 2020-03-18 15:22
(Again, new at programming so not 100% following, so sorry)

I have tried your suggestions and nothing different happened. However, it is quite difficult to even try them, as having bash open for 10 minutes triggers the init processes, hanging the terminal and torturing my CPU to the point that a restart is necessary. So I end up restarting every few couple of minutes.
The only security software I have is Avast (which I'll try to uninstall as I don't use it), and the only three party software installed in general is VS Code. 

I'm considering just reinstalling Windows, reseting the whole computer (I have a separate drive just for software and all of my Linux data backed up so it wouldn't be that bad). Do you think that would fix the error?

**Comment by sirredbeard** [comment] 2020-03-18 20:57
Third party security software will often detect things WSL is doing as malware and block it, it could be interfering with the mount process in your case @juannegro. 

Before you reinstall Windows at least try `DISM /Online /Cleanup-Image /RestoreHealth` in the Command Prompt.

**Comment by aboulore** [comment] 2020-03-19 20:13
Same issue, 
Windows 10 home release 18363.720
When closing Ubuntu 18.04, there is one init process still running. If I close it manually, then I can start Ubuntu again.

**Comment by juannegro** [comment] 2020-03-19 23:46
> Third party security software will often detect things WSL is doing as malware and block it, it could be interfering with the mount process in your case @juannegro.


Yep. Deleted Avast, restarted, now it's working as usual. Didn't hang in the 3 hours the computer was on, while before it hanged in the first 15 minutes. Will let you know if anything new happens. 

I'm new to github. Should I close the thread? There are people who had the same issue and I doubt that they can fix it the same way I could.

**Comment by rcheng15jhu** [comment] 2020-03-19 23:52
I have Avast too, so that might just be the issue. I'll try to see if I can make exceptions for the wsl processes.

**Comment by aboulore** [comment] 2020-03-20 17:22
I completely reinstalled windows 10 home edition, with no antivirus software, no other software, just Windows 10. I foillowed the complete procedure to install WSL and Ubuntu 18.04 release. Just did the update and upgrade. I did not install Xming this time.
And the first time I start Ubuntu, 2 init processes start , when I closed the ubuntu window (with command exit), one init process stoped, but one remained active, untill I could kill it manually in the process manager of Windows. 
So it does not seem to be something related to any interference between WSL and other softwares.
I don't know if this can help.

**Comment by boulderwebdev** [comment] 2020-03-23 21:22
Removing Avast solved the problem for me.

**Comment by souradeep100** [comment] 2020-05-03 20:32
I am running wsl 2 Ubuntu and I am having the same issue of multiple init process.
`
souradeep@LAPTOP-L9AIV34E:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
souradeep@LAPTOP-L9AIV34E:~$ uname -a
Linux LAPTOP-L9AIV34E 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
souradeep@LAPTOP-L9AIV34E:~$ ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.2  0.0   1048   640 ?        Sl   01:45   0:01 /init
root         7  0.0  0.0    892    80 ?        Ss   01:45   0:00 /init
root         8  0.0  0.0    892    80 ?        R    01:45   0:00 /init
sourade+     9  0.0  0.0  10172  5212 pts/0    Ss   01:45   0:00 -bash
sourade+   217  0.0  0.0  10836  3480 pts/0    R+   01:55   0:00 ps -aux
`
I have already tried restarting the lxss daemon, shutdown of Ubuntu, restarting the OS and 
DISM online health check. None has helped here.
This seems really odd, I guess this has come mostly after Ubuntu has done a update through the windows app store.

**Comment by souradeep100** [comment] 2020-05-04 10:00
> Seeing these multiple init processes go to that level is odd.
> 
> The WSL init should only be mounting /mnt/c and any other custom mounts you have configured in /etc/wsl.conf
> 
> This issue should not be confused with issues with the kernel in WSL2 in the recent change in slow ring that @laybak had.
> 
> KB4537759 was an Adobe flash security update, so I am not sure about that one.
> 
> I will monitor this thread for more reports.
> 
> Some things to try:
> 
> * Shutting Ubuntu down with wsl --terminate Ubuntu...
> * Starting and stopping LXSS: sc stop LxssManager then sc start LxssManager
> * Disabling and re-enabling WSL in Windows
> * Resetting Ubuntu on WSL (after backing up your data using wsl --export... or Raft WSL)

I am running wsl 2 Ubuntu and I am having the same issue of multiple init process.
souradeep@LAPTOP-L9AIV34E:~$ lsb_release -a No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 20.04 LTS Release: 20.04 Codename: focal
souradeep@LAPTOP-L9AIV34E:~$ uname -a Linux LAPTOP-L9AIV34E 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

souradeep@LAPTOP-L9AIV34E:~$ ps -aux
USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND
root 1 0.2 0.0 1048 640 ? Sl 01:45 0:01 /init
root 7 0.0 0.0 892 80 ? Ss 01:45 0:00 /init
root 8 0.0 0.0 892 80 ? R 01:45 0:00 /init
sourade+ 9 0.0 0.0 10172 5212 pts/0 Ss 01:45 0:00 -bash
sourade+ 217 0.0 0.0 10836 3480 pts/0 R+ 01:55 0:00 ps -aux

I have already tried restarting the lxss daemon, shutdown of Ubuntu, restarting the OS and
DISM online health check. None has helped here.
This seems really odd, I guess this has come mostly after Ubuntu has done a update through the windows app store.

**Closed** 2024-02-01 12:18 UTC
Labels: failure-to-launch
