### ISSUE TITLE
Not boot say not installed but work after time or reboot

### ISSUE THREAD

**Issue by GiovanniMet** [Microsoft/WSL#3321] opened 2018-06-21 22:08 UTC
As said here, i upload the file https://docs.microsoft.com/en-us/windows/wsl/troubleshooting

[lxcore.zip](https://github.com/Microsoft/WSL/files/2125510/lxcore.zip)

my problem is strange: 
I run and have  error saying feature not avaiable, but if I reboot my pc or wait about 5 minutes it work!

**Comment by benhillis** [comment] 2018-06-21 22:10
Thanks for reporting, this is a duplicate of #2576 and a fix is inbound.  A couple workarounds:
1. Disable fast boot.
2. Restart the lxssmanager service (sc stop lxssmanager)

**Closed by benhillis** 2018-06-21 22:10 UTC
Labels: duplicate
