### ISSUE TITLE
WSL2 - File explorer quarantined .wav files during copy to $wsl\Ubuntu\home

### ISSUE THREAD

**Issue by TheRealBard** [microsoft/WSL#6217] opened 2020-11-09 14:24 UTC
I used Windows File Explorer to copy a code project from a recent archive to the $wsl home directory.   File Explorer threw an error over two files being copied:  "are you sure you want to copy this file without its properties?"  If you say Yes, it completes the copy, but generated quarantine files for the two in question.

The files it pukked on were a pair of .wav files.   let's say filename.wav,  the file it created was filename.com.apple.quarantine.

I tried copying the project to my regular windows desktop and had no errors.  I took a look at the two files with Properties.  There is nothing out of the ordinary. I don't see any reference to Apple in the metadata or any other tags; just a 16bit, 44.100kHz stereo file.  These were not the only .wav files in the project, just the ones it took exception to.

# Environment
Windows 20H2, 19042.572
Ubuntu 20.04

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
Not sure if you can reproduce without the files in question. https://1drv.ms/f/s!Apomoggzevs3kO1vpI81slRWQ09LOg  I put one of each in OneDrive in case you want to see.  This is an ordinary copy using File Explorer of a code folder from a Windows location to the $wsl\home directory.

**WSL logs**: 

#  Expected behavior
Expected behavior is an accurate copy of the folder

# Actual behavior
two files were given a quarantine suffix for some reason. But dont see a reason given.

**Comment by riverar** [comment] 2020-11-09 19:03
Believe this is a duplicate of #4609

**Comment by Jockey4her** [comment] 2020-11-09 19:28
well, you may be right, but there is no zone identifier in these copied file. I've seen that zone stuff too.  If it was the same, I'd get the same file suffix. This one definitely says quarantine.  I cant find any mention of that file suffix on the other thread.

**Comment by riverar** [comment] 2020-11-09 19:32
@Jockey4her The name of the alternate data stream doesn't actually matter. I believe it's all related to the same mishandling of NTFS Alternate Data Streams / Extended Attributes. 👍

**Comment by therealkenc** [comment] 2020-11-11 01:19
What is the output of:
```
$ powershell.exe "Get-CimInstance -Namespace root/SecurityCenter2 -ClassName AntivirusProduct" | grep displayName
```

**Comment by Jockey4her** [comment] 2020-11-11 12:05
displayName              : Windows Defender

**Closed** 2024-02-01 12:14 UTC
Labels: duplicate
