### ISSUE TITLE
Execution failed without /bin folder

### ISSUE THREAD

**Issue by marler8997** [Microsoft/WSL#3894] opened 2019-03-05 22:17 UTC
Related to: https://github.com/Microsoft/WSL/issues/3584 (Execution failed without /sbin folder)

It looks like the same issue happens when the distro does not contain a `/bin` folder.  When the `WslLaunchInteractive` function is invoked, it will fail and print this:
```
The specified network name is no longer available.
```

Windows version 1809, build 17763.292

**Comment by benhillis** [comment] 2019-03-05 22:19
@marler8997 - Could you please provide the additional information in the contribution instructions?  What version are you seeing this issue?  This should also be fixed in 18267.

**Comment by marler8997** [comment] 2019-03-05 22:22
I updated the details with my version.

**Comment by benhillis** [comment] 2019-03-05 22:28
Thanks - duplicate of #3584.

**Closed by benhillis** 2019-03-05 22:28 UTC
Labels: duplicate, need-repro

**Comment by marler8997** [comment] 2019-03-05 22:44
Issue #3584 was caused because there was no `/sbin` folder.  In this case, I have a `/sbin` folder but no `/bin` folder.  Are you saying you've confirmed this is also fixed in a later version of windows when the distro does not have a `/bin` folder?

**Comment by benhillis** [comment] 2019-03-05 22:58
@marler8997 - Correct, I fixed the issue for missing /sbin and /bin.
