### ISSUE TITLE
Upgrading from WSL1 to WSL2 causes Vmmem to consume huge amounts of RAM hanging the machine

### ISSUE THREAD

**Issue by ShashankOV** [microsoft/WSL#4669] opened 2019-11-12 19:11 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19013.1122]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Step 1: Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Step 2:  wsl --set-version Ubuntu 2

* What's wrong / what should be happening instead:
The RAM usage by the process Vmmem continues to increase during the upgrade process and uses up the entirety of the Physical RAM causing the machine to hang.

This issue is similar to #4159 which is said to be a duplicate of #4166, which mentions that the bug was rectified in 19013. But not sure why it's still happening.

**Comment by Biswa96** [comment] 2019-11-12 19:13
Try to upgrade to latest fast insider build 19018.

**Comment by liukch** [comment] 2019-11-27 03:31
I use insider build 19025, but it will reproduce stably.
![image](https://user-images.githubusercontent.com/35715689/69691215-5f54eb00-1109-11ea-84c5-d5e129565b8f.png)

**Comment by Big7lion** [comment] 2019-11-29 14:40
same， use insider build 19033

**Comment by Big7lion** [comment] 2019-11-29 15:06
REFER TO: [#4166 recommended comment](https://github.com/microsoft/WSL/issues/4166#issuecomment-526725261)， it works🤣

**Comment by raulf2012** [comment] 2019-12-04 17:56
I just wanted to chime in with my experience

I had this exact issue when upgrading from WSL 1-->2
Vmmem used up all remaining ram on my machhine (~30 GB)

I left my computer running over night and miraculously the process finished by morning

Now WSL2 is installed and running fine as far as I can tell

So I'd recommend to anybody with this issue to give the process a good ~10 hours

**Comment by CodeBrotha** [comment] 2019-12-24 15:15
> I just wanted to chime in with my experience
> 
> I had this exact issue when upgrading from WSL 1-->2
> Vmmem used up all remaining ram on my machhine (~30 GB)
> 
> I left my computer running over night and miraculously the process finished by morning
> 
> Now WSL2 is installed and running fine as far as I can tell
> 
> So I'd recommend to anybody with this issue to give the process a good ~10 hours

Sounds like it might have been more productive to wipe the WSL1 install and start fresh on WSL2.

**Comment by raulf2012** [comment] 2019-12-24 22:41
> Sounds like it might have been more productive to wipe the WSL1 install and start fresh on WSL2.

@CodeBrotha, I didn't consider this, but if this is possible and avoids the issue at hand that would be a good work around, this is assuming that the issue is related to the transition between WS1/2 and not with WSL2 itself, which would need to be tested

**Comment by benhillis** [comment] 2020-01-30 21:48
Build 19555 has a change that should make this experience much better.

**Comment by jolimas** [comment] 2020-02-12 15:30
> Build 19555 has a change that should make this experience much better.

But have this issue: https://github.com/microsoft/WSL/issues/4860 
I do not recommend installing it. Even the Build 19559 still have that issue.

**Comment by craigloewen-msft** [comment] 2020-02-13 23:42
Issue #4860 seems to be resolved, please try build 19564 and you'll have the fix for 4860 and this issue as well.

**Comment by jefferai** [comment] 2020-02-14 00:11
@craigloewen-msft As someone who has only been on Slow ring so far, how scared should I be of Fast ring? I went to Slow for WSL2 when it went there and it's been pretty smooth, but....

**Comment by jefferai** [comment] 2020-02-14 16:21
For reasons I do not understand, trying it a couple of more times actually worked (on Slow build). I also had an issue on import, but after trying it a few more times, that worked too.

**Comment by craigloewen-msft** [comment] 2020-02-14 17:55
@jefferai I wouldn't recommend running anything that is critical to your business, or productivity on the fast ring, as by nature of being on the fast ring sometimes unexpected errors show up. That being said, I personally do run (a version of) the fast ring for my machines at work. I'd consider running the fast ring in a Virtual Machine, or on a computer that you'd be ok with taking a break from for a couple of days if necessary. 

And I'm glad to hear that it worked for you! Once build 19564 (or another build later to it) hits the slow ring, you'll find an improvement to that experience as well.

**Comment by jefferai** [comment] 2020-02-14 22:22
Awesome, thanks for the info!

**Comment by iongion** [comment] 2020-06-03 08:03
Insider build `19631`

![image](https://user-images.githubusercontent.com/867609/83611336-20ed2c80-a581-11ea-9cc9-2a105efed327.png)

No vm running, no WSL running.

So who is using that much memory ?

**Comment by iongion** [comment] 2020-06-03 11:49
I actually am using Docker for Windows and found this https://github.com/docker/for-win/issues/2052 on their bug tracker, maybe related, maybe not :(

**Comment by onomatopellan** [comment] 2020-06-03 13:22
@iongion did you try with `wsl.exe --shutdown`?

**Comment by meizenga** [comment] 2020-06-03 20:49
msdtc -resetlog

vmmem process went from ~2GB to 300MB...... for some minutes, then it back to ~1,5GB

**Comment by shadycuz** [comment] 2020-06-04 09:28
I turned off real time protection and it fixed it for me. #5310 (i think)

**Comment by stevenh** [comment] 2020-06-05 11:20
Just installed Windows 10 2004 and hit this exact issue, surprised that 2004 got released with such an impacting bug still present, disabling real time protection seems like a real risk but may have to do it if the performance is that bad.

**Comment by shadycuz** [comment] 2020-06-05 14:52
@stevenh It was temporary fix to make the upgrade not crash. I soon after turned back on real-time protection.

**Comment by Loligplayer33** [comment] 2020-06-06 09:29
This process stil takes up about 3gb of memory. Any new Information about this?

**Comment by stevenh** [comment] 2020-06-07 23:19
Two console windows open and `vmmem` is using 5GB and seems to be rising

**Comment by dimkir** [comment] 2020-07-08 09:57
As #4166 is locked, this seems to be the best place to post my feedback:

After following the recommendation to set up `.wslconfig`  and limiting RAM usage to 6GB (on my 16Gb machine), I have encountered few sudden symptoms of this WSL2 problem:
 - CPU usage (as reported by Windows Task Manager) spikes to 40% (on "System" process, which seems to refer to Windows Kernel here)
 - SSD/HDD is thrashed with reads of `.vhdx` file (virtual hard disk file)  (See Resource Manager screenshot below)
 - all WSL active bash sessions are almost frozen
 - `$ free -m` reports all memory but 90Mb taken

This constant SSD thrashing reads started to happen about 10 minutes ago and still don't go away. 

![image](https://user-images.githubusercontent.com/3438798/86904255-54831f80-c108-11ea-8f00-bfc2c92c3890.png)


The VM doesn't seem to report any CPU usage for specific processes. But does report 1.2Gb memory usage for WSL VScode server...

![image](https://user-images.githubusercontent.com/3438798/86904631-e559fb00-c108-11ea-9027-c9e022a68147.png)

I am not sure whether this related to WSL managing memory or VSCode WSL Server eating too much memory (why would it do it intentionally?) 


Hope someone can shed the light.

**Comment by shurane** [comment] 2020-07-29 10:34
@iongion I'm getting the same issue after using docker:

![image](https://user-images.githubusercontent.com/541433/88789789-03d17600-d14c-11ea-8ee5-59af88e303fc.png)

`net stop vmcompute` and `net start vmcompute` does seem to alleviate the issue. But it doesn't seem ideal that vmmem is hanging onto that memory without the docker containers running.

![image](https://user-images.githubusercontent.com/541433/88790021-5f036880-d14c-11ea-9cec-0ee2dd0935e3.png)

**Comment by netcore-jroger** [comment] 2020-07-31 06:35
me too.

**Comment by therealkenc** [comment] 2020-08-03 23:00
This was /fixed [19555](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-19555) with some fixed-_harder_ in [20175](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20175). There remains open #5532 and #5410, which (at least hypothetically) may be related to [OP](https://github.com/ShashankOV) `wsl --set-version Ubuntu 2` consuming a lot of memory.

**Closed by therealkenc** 2020-08-03 23:00 UTC
Labels: fixedininsiderbuilds
