### ISSUE TITLE
ETA for Fedora

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/WSL#2584] opened 2017-10-21 17:20 UTC
Sorry, if this has been mentioned already soemwhere, but is there an rough ETA on Fedora? And will it be available for normal Windows FCU or only in insider?

**Comment by benhillis** [comment] 2017-10-21 17:55
When Fedora is ready it will be available on Fall Creators Update.

**Comment by Biswa96** [comment] 2017-10-23 16:21
Se this comment: https://github.com/Microsoft/BashOnWindows/issues/8#issuecomment-212116902

**Comment by ByteEnable** [comment] 2017-10-24 21:45
Fedora is not available in the Fall Creators Update.  I too have searched far and wide.  I have come up empty on any official wording from the Fedora Community.

**Comment by Orbixx** [comment] 2017-10-26 09:18
Fedora seems to be advertised as being available when searching for it on the Microsoft Store, and yet it's not actually there. I imagine it must be coming soon if it's mentioned on the store.

**Comment by cwawak** [comment] 2017-11-29 23:00
It's been a month or so, any update?

**Comment by DarthSpock** [comment] 2017-11-30 20:10
@cwawak I put the question in the Fedora forums under an already existing thread called ['Fedora on the Windows Store'](https://forums.fedoraforum.org/showthread.php?314295-Fedora-on-the-Windows-Store&goto=newpost) . Still waiting for official response. Feel free to check it out along with the other forums as we'll need to know what issues arise specific to Fedora when it is finally available. This will help ensure the WSL team can focus on all the big things we the community have been pinging them on.

**Comment by Biswa96** [comment] 2017-11-30 20:55
Why not you install Fedora from rootfs tarballs (tar.gz)? Those really works in WSL!

**Comment by DarthSpock** [comment] 2017-12-01 14:11
@Biswa96  I'm looking for an officially supported version to be released so any issues I have can be officially supported either here or by Fedora. The same will go for any other distro that gets released into the Store. Since 2 of my target platforms are CentOS and RHEL, having Fedora officially available would be immensely helpful and make things much easier instead of making conversions from Ubuntu.

**Comment by Biswa96** [comment] 2017-12-01 16:56
Yes, the docker rootfs tarball provided in fedora official website: https://download.fedoraproject.org/pub/fedora/linux/releases/ and the procedure is as similar as Windows store provided distros. See my repo.

**Comment by albeauregard** [comment] 2017-12-19 13:37
Is it just me, or does it seem really odd that Microsoft advertises Fedora so prominently on the Microsoft Store, when it still doesn't exist?

**Comment by Biswa96** [comment] 2017-12-19 14:42
@albeauregard No, you're not the only one. If you saw this article [New distros coming to Bash/WSL via Windows Store](https://blogs.msdn.microsoft.com/commandline/2017/05/11/new-distros-coming-to-bashwsl-via-windows-store/), in that image @bitcrazed showed Fedora in build 10.0.16188. So, Fedora may be available for the MS programmers. 🤫

**Comment by bitcrazed** [comment] 2017-12-20 19:37
@All: As per Fedora Lead [@Mattdm (on Twitter)](https://twitter.com/mattdm):

> We're working on resolving some non-technical issues. I'm afraid I don't have any more than that right now.

[Source:](https://twitter.com/mattdm/status/938969950571593728)
![image](https://user-images.githubusercontent.com/961950/34225062-ec986446-e579-11e7-96c0-bdc172db7f68.png)

Please do ping Matt and ask him for updates - he uses your asks as ammo' ;)

**Comment by DarthSpock** [comment] 2017-12-20 19:54
I don't use Twitter but if somebody here does and pings him on this, you can add a +1 from me for getting this to the Store or at the least the offline .appx that was shown (barely visible) on the Flock 2017 Youtube video.

**Comment by thomasfedb** [comment] 2018-01-13 16:29
+1 on this. I've used Fedora since I was 12 and would really much prefer it over Ubuntu or SUSE.

**Comment by benhillis** [comment] 2018-01-13 20:50
I suggest letting Fedora know via their social media channels that this is important to you. The usermode bits belong to them and we can't put them on the store without their permission.

**Comment by thomasfedb** [comment] 2018-01-14 12:26
I would have imagined @benhillis that any and all bits would be free software and you'd be able to at least distribute?

**Comment by bitcrazed** [comment] 2018-01-16 17:34
We understand the excitement (and in some cases, importance) about getting Fedora into the store.


I can confirm that we are working with Fedora to remedy the non-technical issues that have held-up their publishing their distro and we look forward to @tara-raj being able to share news in the next few weeks.

Please bear-with us until then.

**Comment by bitcrazed** [comment] 2018-01-16 17:36
@thomasfedb We have a policy of not publishing others' IP into the store. We believe that the community would **MUCH** prefer to see a distro published by the distro owner vs. seeing it published by Microsoft or anyone else that isn't the authoritative source.

**Comment by thomasfedb** [comment] 2018-01-17 04:06
Cheers @bitcrazed. Good to know it's close to being ready!

**Comment by OfficerHalf** [comment] 2018-02-05 15:11
Yeah, it's odd that it's been three months and the store still lists Fedora even though it's not actually available.

**Comment by benhillis** [comment] 2018-02-05 19:09
As I suggested above, the ball is in Fedora's court.  I suggest letting them know this is important to you.

**Comment by MikeGitb** [comment] 2018-02-05 22:15
Is there any suggested channel for people without twitter?

**Comment by benhillis** [comment] 2018-02-05 22:36
@MikeGitb - https://fedoraproject.org/wiki/Contact

**Comment by thomasfedb** [comment] 2018-02-05 23:39
@mattdm is this something you can update us on?

**Comment by OfficerHalf** [comment] 2018-02-06 15:24
![capture26](https://user-images.githubusercontent.com/4851889/35867504-81af4bf6-0b1f-11e8-828d-ba1d721bb8a2.PNG)

**Comment by thomasfedb** [comment] 2018-02-06 15:39
@benhillis, can you comment on above? Apparently ball is back in your court?

**Comment by benhillis** [comment] 2018-02-06 16:09
@bitcrazed @tara-raj are more up to date on specifics.

**Comment by fquinner** [comment] 2018-02-07 17:54
Should this ticket be closed? Just conscious that it's still being updated and I'm acutely interested in seeing this happen (I'm trying not to grow attached to WSL Ubuntu since I'll be dropping it as soon as this lands).

**Comment by DarthSpock** [comment] 2018-02-07 18:31
You do realize you can run both of them right? You may even find yourself in a situation in which you'd want to run more than one distro for testing out scenarios.

**Comment by fquinner** [comment] 2018-02-07 19:23
I did not know that, that is useful information though thank you. I'd typically only use a single distro though - usually I would just be happy with any Linux terminal but a major project that I work on also requires rpmbuild / mock setup for generating CentOS rpms which is more of a red hat thing so having fedora on WSL would be really handy.

**Comment by DarthSpock** [comment] 2018-02-07 19:35
Trust me, I know your pain. Considering I have CentOS and RHEL in my environment makes this a requirement. If you haven't tried to though, you can install rpm on Ubuntu (and yum as well oddly enough). So you don't have to toss the syntax on the back burner entirely. I do have to admit I prefer the apt method with Ubuntu (syntax is more user friendly but that could just be my view point) but Ubuntu isn't entirely ideal as I already said. I would keep Ubuntu installed for one of those "just in case" situations. Making something that can work on both would be more ideal because it can then be shared more easily if it's not something proprietary.

**Comment by bitcrazed** [comment] 2018-02-08 00:40
Hey all - back in the office after a few days OOF-sick.

Appreciate all the enthusiasm re. Fedora and thanks for your patience while we work through a few things. 

Rest assured that we're keenly working to resolve the blocking issues and will do our utmost to get Matt & team unblocked and able to get Fedora into the store.

When we do, you'll hear A LOT of noise on Twitter from @Mattdm, @tara-raj and I, and on our blog at https://aka.ms/cliblog.

Reopening for now to reflect the issue's actual status, but until it's closed, assume that we're working hard to move forward.

**Comment by fquinner** [comment] 2018-02-08 07:39
Wow there are a *lot* of great things on that blog post list you guys really are making Windows usable for people like me thank you! On the fedora thing I'll wait with bated breath...

**Comment by Conan-Kudo** [comment] 2018-03-07 01:06
Okay, seriously, what's going on with this? What's the hold up for Fedora on WSL now?

I just saw Debian enter the fold, and Fedora was a "launch" partner for the initial multi-distro effort for WSL. How is it that it's still not available?

**Comment by DarthSpock** [comment] 2018-03-07 01:54
Debian? I just checked and I don't see Debian available. Kali Linux is now available though! It does make one wonder if it literally took 2 months for Kali to come to the Store why Fedora has been so much longer. Really puts the emphasis on "non-technical issues"

**Comment by Conan-Kudo** [comment] 2018-03-07 02:32
@DarthSpock It was just announced on the blog...

**Comment by DarthSpock** [comment] 2018-03-07 02:42
It's now available on the Store and I see the blog. That's crazy. Kali was released yesterday and now Debian! We're on a roll here. C'mon Fedora, let's keep the wheels moving.

**Comment by MikeGitb** [comment] 2018-03-07 07:19
I wonder if we will ever learn what exactly the holdup was about.

**Comment by mattdm** [comment] 2018-03-07 11:20
There's nothing super-dramatic; it's just slow to get the legal details worked out. That progress *is* continuing. I'll let you know if I give up. :)

**Comment by polymetis** [comment] 2018-03-08 19:26
Thanks @mattdm

**Comment by mmmmmmbeer** [comment] 2018-03-09 21:06
The Microsoft Store's splash for WSL has me a bit concerned: 
![2018-03-09 16_04_42-microsoft store](https://user-images.githubusercontent.com/16092016/37229953-d08a3216-23b3-11e8-83f2-d2b51e364d02.png)

That real estate used to be occupied by Fedora!

**Comment by benhillis** [comment] 2018-03-09 21:35
@mmmmmmbeer - We can't win...

Fedora is in the list of available distros - "WHERE IS FEDORA"
We remove Fedora from the list - "WHY DID YOU REMOVE FEDORA FROM YOUR LIST"

**Comment by spaletta** [comment] 2018-03-09 21:40
@benhillis I think it’s safe to assume that @mmmmmmbeer’s comment was solely directed at the Fedora side of this issue.

**Comment by mmmmmmbeer** [comment] 2018-03-09 21:43
I just wanted to ensure it didn't portend some sort of falling-out between the two parties! Hope to see Fedora (or any RPM-based distro, for that matter) available soon!

**Comment by sweenish** [comment] 2018-03-10 01:08
My non-technical contribution to this discussion is to point out that SUSE is rpm-based. 

I am anxiously awaiting Fedora, and I hope these issues get sorted out sooner than later.

**Comment by VisserJ** [comment] 2018-03-15 10:10
Still no updates about Fedora coming to the store? Seeing all these distro's coming to the store it does seem like a long wait for fedora. I really hope these "legal details" aren't starting to become something major.

**Comment by mattdm** [comment] 2018-03-15 12:25
We are making progress.

**Comment by Biswa96** [comment] 2018-03-15 12:52
@mattdm will the appx be open source like the debian did?

**Comment by mattdm** [comment] 2018-03-15 13:01
Everything Fedora does is always open source / free software.

**Comment by bitcrazed** [comment] 2018-03-15 20:23
@mmmmmmbeer - absolutely no falling-out or anything else worthy of daytime soap-opera drama. Though it's quite likely I owe @mattdm at least a couple of beers - hope he doesn't hold it against me :)

We're just working-through some paperwork stuff while various parties shipping products, being in and out of the office attending events etc. eating into available time.

Again, please bear with us - we're working on this as quickly as we can.

**Comment by thomasfedb** [comment] 2018-03-18 09:30
Thanks for the updates @bitcrazed and @mattdm. Really looking forward to seeing this go live.

**Comment by benhillis** [comment] 2018-03-20 19:53
@calebmeyer - When the Fedora store is in the store it will be available in the current stable build (Fall Creators Update).

**Comment by sagyvolkov** [comment] 2018-04-05 22:39
any updates? really looking forward to have fedora on my laptop (which I require to run with windows10)

**Comment by bitcrazed** [comment] 2018-04-05 23:08
@sagyvolkov Nothing to announce yet, but please do follow @tara-raj ([tara_msft](https://twitter.com/tara_msft)) and myself ([richturn_ms](https://twitter.com/richturn_ms)) on Twitter and/or keep an eye on [our blog ](https://blogs.msdn.microsoft.com/commandline)- we'll be quite noisy about Fedora when it lands ;)

**Comment by thomasfedb** [comment] 2018-04-07 16:42
Is the open sourcing of the WSL sample at all related to the non-technical details required to get Fedora released for WSL? https://blogs.msdn.microsoft.com/commandline/2018/03/26/wsl-distro-launcher/

**Comment by ericvader** [comment] 2018-04-14 03:52
Looking forward to Fedora on Windows!

**Comment by tgoncuoglu** [comment] 2018-04-19 11:59
Just my opinion in form of a reality check: this very long delay in releasing fedora on WSL store is passing the point where "we are working on non-technical/legal issues" is cutting it. You are losing users to debian/ubuntu/suse every single day that passes. You might at least want to give more details if you expect the community to stay with you. Again, just my opinion, no offense. Personally I'm very excited for the day I can use fedora in my day to day development activities.

**Comment by thomasfedb** [comment] 2018-04-19 14:42
Agreed. It would seem to be in the spirit of the Fedora community to have more transparency as to what is going on here.

**Comment by bitcrazed** [comment] 2018-04-19 19:12
Again, echoing what I said above:
Appreciate all the enthusiasm re. Fedora and thanks for your patience while we work through a few things.
Rest assured that we're keenly working to resolve the last remaining non-technical blockers.
When we do, you'll hear A LOT of noise on Twitter from @mattdm, @tara-raj and I, and on our blog at https://aka.ms/cliblog.

**Comment by Conan-Kudo** [comment] 2018-04-19 19:13
> Rest assured that we're keenly working to resolve the last remaining non-technical blockers.

What _are_ the remaining "non-technical" blockers?

**Comment by bitcrazed** [comment] 2018-04-20 02:46
Just boring paperworkey-things.

![paperwork](https://media.giphy.com/media/DU6kwIChUGYmI/giphy.gif)

**Comment by ericvader** [comment] 2018-04-20 03:07
We hope the paper work can be sorted out soon!

After all, it’s been 6 months and the rest of the distros are out! Missing only Fedora!

**Comment by bitcrazed** [comment] 2018-04-20 03:12
We hear ya: We've all been eager to see Fedora in the store and on WSL since we announced it!!

But doing the Corp' stuff properly is important for everyone. Alas, that can sometimes take time.

Thanks for your continued patience.

**Comment by MikeGitb** [comment] 2018-04-20 06:31
I guess the thing everyone is wondering is what makes fedora's paperwork so different from the other distros?

I'm certainly not asking to reveal  any details about ongoing negotiations (or whatever you are doing right know), but will we at least see at the end, what kind of legal Agreement (If any) was reached between MS and Fedora?

**Comment by thomasfedb** [comment] 2018-04-20 06:34
@mattdm can we get an update from your side of things?

**Comment by DarthSpock** [comment] 2018-04-20 12:41
@MikeGitb I think something everyone here needs to realize is Fedora (and CentOS) fall under the Red Hat umbrella (and have Red Hat employees actively contributing to both projects). The paperwork required is most likely between Red Hat and Microsoft, which as you see not surprisingly takes a decent bit of time (think bureaucracy). I wouldn't be surprised to see after all is said and done, we get not only Fedora but CentOS and RHEL available in the Store, which would be great. At least this is my hope.

**Comment by Biswa96** [comment] 2018-04-20 12:46
Why not you guys suppress your appetite _temporarily_ with docker images? Both Fedora and CentOS docker images can be installed in WSL.

**Comment by mattdm** [comment] 2018-04-20 13:07
I'll check with RH legal about what they feel comfortable with me saying — I don't want to cause more difficulty. As @DarthSpock notes, Red Hat is both the primary sponsor and trademark holder for Fedora, and is the entity which takes on legal risk. (And yes, it's true that if we resolve this for for Fedora, that will clear the runway for CentOS.)

**Comment by DarthSpock** [comment] 2018-04-20 13:14
@mattdm would RHEL be paved open as well? OpenSuse has their Enterprise version available, so it would make logical sense for Red Hat to do the same. They offer a free one-year license subscription for use on WSL (probably because WSL has limitations real Linux doesn't have). It would great to see Red Hat offering the same.

**Comment by mattdm** [comment] 2018-04-20 16:32
@DarthSpock Ah, here we are in clear territory, because I can definitively say that I have absolutely no ability to say anything whatsoever about RHEL plans. :)

**Comment by DarthSpock** [comment] 2018-04-20 16:37
Gotcha, hope something is in the works.

**Comment by tgoncuoglu** [comment] 2018-04-20 17:32
@Biswa96 Unfortunately that doesn't work...ish. Currently WSL distributions are installed like any  windows store application, and on file system get installed in Packages under %APPDATA% in its own directory. (This is why the distro switcher on GitHub doesn't work anymore by the way.) To do what you suggest would mean to install one of the other distros as a dummy package, replace its files with those of a Fedora Docker image, handle some user issues (passwd/shadow/group). While this is doable (I did it), you will end up with a very limited Fedora setup which doesnt even have sudo, has problems with networking (which means you cant just dnf install stuff) etc.  So... doesn't work... ish.

**Comment by tgoncuoglu** [comment] 2018-04-20 17:35
@mattdm Thank you very much for the RH legal trip, it would really help to know at least in part of what is going on.

**Comment by DarthSpock** [comment] 2018-04-20 17:42
@tgoncuoglu Biswa is referring to https://github.com/Microsoft/WSL-distrolauncher/ which is the official method of side-loading distros. Is this what you used? It was only open-sourced quite recently.

**Comment by tgoncuoglu** [comment] 2018-04-20 17:46
@DarthSpock I believe he was referring to https://github.com/RoliSoft/WSL-Distribution-Switcher , which automated the process I described above with docker images, but yes, you are right, I should check that one too. Thank you.

**Comment by MikeGitb** [comment] 2018-04-20 21:34
While I'm looking forward to see fedora on Windows I don't care that much about which distro I'm running in WSL anyway, as it is neither my desktop, nor server OS and most Linux tools work on any distro anyway.

**Comment by bitcrazed** [comment] 2018-04-20 21:42
@MikeGitb While I agree in general, I know that there are often differences between distro's when it comes to installing dependencies, and configuring things, and that its generally less error prone to build packages, etc. on the platforms you aim to deploy onto.

**Comment by NimaSaed** [comment] 2018-05-03 07:54
Any updates? 😃

**Comment by thomasfedb** [comment] 2018-05-03 09:15
@mattdm did RH legal get back to you?

**Comment by lfzamora81** [comment] 2018-05-05 18:28
F28 out now, would be super awesome to play with it in WSL. Any update on the legal ballyhoo?

**Comment by pjjroux** [comment] 2018-05-08 05:26
Also waiting eagerly at the moment. No more XAMPP for my local development needs.

**Comment by hkrware** [comment] 2018-05-08 14:13
fedora should be have been done a long time ago. even second right after ubuntu and then all the other...

**Comment by minexew** [comment] 2018-05-13 11:46
@hkrware The thumbs down could be because your commend adds absolutely nothing to the discussion.

(of course, now I'm equally guilty)

**Comment by thomasfedb** [comment] 2018-05-13 11:55
Anybody on Twitter want to ping @mattdm on the reply from legal? @bitcrazed anything new from your end?

**Comment by mattdm** [comment] 2018-05-13 15:09
I'm following this. I promise updates when I have something I can share.

**Comment by Biswa96** [comment] 2018-05-13 15:14
Is the re any shell script to make Fedora tar.gz file? Like this from Debian by @rhaist: https://salsa.debian.org/rhaist-guest/WSL/blob/master/create-targz.sh

**Comment by hkrware** [comment] 2018-05-14 06:54
@Biswa96  if you've got cygwin, you can use the tar utility:
`tar -xf fedora-27-x86_64-20180307.tar.xz -C outdir/
cd outdir
tar -czf ../fedora-27-x86_64-20180307.tar.gz --hard-dereference *`

**Comment by Biswa96** [comment] 2018-05-14 07:29
I know that. I've posted that process before. But many things don't work with that docker image.

**Comment by rogersachan** [comment] 2018-05-14 23:49
Can't wait for this to land so I can have easier access to mingw tooling.

**Comment by DarthSpock** [comment] 2018-05-15 13:18
@Biswa96 If the Docker image doesn't work so well, have you found an image that doesn't have any issues?

**Comment by Biswa96** [comment] 2018-05-15 13:36
@DarthSpock I was thinking of to make a tar.gz from Fedora ISO (I've done that with Antergos, CentOS). But it is 3.6GB (including Desktop Env). So I asked if there is a script to make a workable tar.gz for WSL.

**Comment by DarthSpock** [comment] 2018-05-15 13:47
Sounds like we'd have to strip down the Docker image (or whatever image is the smallest) to as bare-bones as possible just like Kali does it. We could always create a script from there to install anything that was stripped.

**Comment by hkrware** [comment] 2018-05-15 14:51
@Biswa96 Was CentOS a successful attempt?

**Comment by hkrware** [comment] 2018-05-15 14:58
@Biswa96 Oh, and did you try unxz the **tar.xz** into a **tar** and then **gzip** ?

**Comment by Biswa96** [comment] 2018-05-15 15:07
I installed Fedora successfully 💯. Don't ask me that again. And that procedure works for CentOS well.

**Comment by hkrware** [comment] 2018-05-15 17:26
You asked for a script, I tried to help you. You don't need to be rude. If you don't like it, GitHub is not the place to take it out. Everyone can ask whatever they want. And I asked about CentOS, so you give a tip or something, but nevermind that now.

**Comment by therealkenc** [comment] 2018-05-25 01:51
> Sorry, if this has been mentioned already soemwhere, but is there an rough ETA on Fedora?

[No](https://ask.fedoraproject.org/en/question/114783/when-will-fedora-be-released-for-wsl/).

**Closed by therealkenc** 2018-05-25 01:51 UTC
Labels: discussion

**Comment by metaa** [comment] 2018-05-25 02:35
So why close this now? 🤔

**Comment by dorinlazar** [comment] 2018-05-25 07:18
Most likely because now it's a RedHat issue, not a WSL issue.

**Comment by MikeGitb** [comment] 2018-05-25 08:00
> Most likely because **now** it's a RedHat issue, not a WSL issue.

Has something changed?

**Comment by MikeGitb** [comment] 2018-05-25 09:18
> (which disregards the first two sentences of CONTRIBUTING.md)
Sorry for that.

> was simply answered is all. There is no ETA right now.
Sad, but good enough for me (actually,I was fine with it being closed back in December 2017).

**Comment by metaa** [comment] 2018-09-26 12:58
Yawn 🌵

**Comment by crramirez** [comment] 2018-12-11 17:10
Hello, check this: https://github.com/WhitewaterFoundry/WSLFedoraRemix
