### ISSUE TITLE
Rustup installed cargo can't be run with wsl cargo command.

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/WSL#9983] opened 2023-04-17 15:22 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.1555]

### WSL Version

1.2.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-22621-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1105-Microsoft Fri Jan 01 08:00:00 PST 2016

### Distro Version

Ubuntu 22.04

### Other Software

rustc 1.68.2 (9eb3afe9e 2023-03-27)
cargo 1.68.2 (6feb7c9cf 2023-03-26)

### Repro Steps

1. Install rust with rustup.(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)
2. It created   . "$HOME/.cargo/env" in ~/.bashrc
3. try to run cargo or rustc from windows with "wsl cargo"

### Expected Behavior

user@DESKTOP-P57624Q:/mnt/c/Users/frolo$ cargo --version
cargo 1.68.2 (6feb7c9cf 2023-03-26)

### Actual Behavior

wsl cargo --version
/bin/bash: line 1: cargo: command not found

### Diagnostic Logs

wsl  strace -ff cargo --version
strace: Can't stat 'cargo': No such file or directory

**Comment by kotenok2000** [comment] 2023-04-18 21:26
It do0esn't work if i run command like this:
![image](https://user-images.githubusercontent.com/8822292/232908808-cbb0bdbb-1d4c-4d55-bbbb-f1c35e918b1a.png)

**Comment by pmartincic** [comment] 2023-04-18 21:41
<img width="470" alt="image" src="https://user-images.githubusercontent.com/102559858/232911313-93d55fea-9f90-4de9-91f7-c604deb4b128.png">
I'm closing this as by design. It works if using the `--shell-type` flag.

**Closed by pmartincic** 2023-04-18 21:41 UTC
