### ISSUE TITLE
Ubuntu_22.04 Crashed after not having enough disk space pop-up

### ISSUE THREAD

**Issue by WillyRL** [microsoft/WSL#9787] opened 2023-03-14 13:34 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.1344]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

-

### Distro Version

Ubuntu 22.04

### Repro Steps

While I'm downloading some large data from the distro, I don't realize the disk is full until I got the Not enough disk space pop-up from the windows.  After that my WSL Terminal is terminated.
After cleaning up the large files from my windows, the WSL Distro is able to launch, but my files are gone,
![image](https://user-images.githubusercontent.com/11781111/225017096-473f77c9-ed3e-46be-9fb7-37acf832aa7d.png)

I forgot what steps I've done but 
I ended up with this error now

> The operation timed out because a response was not received from the virtual machine or container.
> Error code: Wsl/Service/CreateInstance/HCS_E_CONNECTION_TIMEOUT

### Expected Behavior

After cleaning up the large files and having the empty space, the WSL should not be affected

### Actual Behavior

WSL Files gone

### Diagnostic Logs

[WslLogs-2023-03-14_19-55-53.zip](https://github.com/microsoft/WSL/files/10969183/WslLogs-2023-03-14_19-55-53.zip)

**Comment by OneBlue** [comment] 2023-03-20 22:07
Thanks for reporting this @WillyRL .

Looking at the logs, the issue is that the distribution disk is corrupted: `[ 2376.105139] EXT4-fs (sdd): VFS: Can't find ext4 filesystem`

Unfortunately, without the list of the command you ran in the distribution it's not possible to root cause how exactly the disk got corrupted.

Closing since the issue is a corrupted distribution vhd.

**Closed by OneBlue** 2023-03-20 22:07 UTC
