### ISSUE TITLE
Unable to use a TTY - (kubectl.exe exec -it ..)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/WSL#2271] opened 2017-06-30 10:09 UTC
Windows 10.0.15063

Trying to run:
```
kubectl.exe exec -it pod-name sh
```
get 

```
Unable to use a TTY - input is not a terminal or the right kind of file
```
Other things with `kubectl.exe`  work quite well in WSL. `kubect exec -it` in windows works well of cource.

**Comment by philips** [comment] 2017-07-05 05:08
Please include an strace.

**Comment by whitecolor** [comment] 2017-07-05 08:06
What trace there was no trace

![image](https://user-images.githubusercontent.com/736697/27855156-d22fbc1a-6182-11e7-95b4-47a8c8e9e4d9.png)

**Comment by sunjoong** [comment] 2017-07-05 16:48
You had known, reference to https://github.com/kubernetes/kubernetes/issues/37471

**Comment by whitecolor** [comment] 2017-07-05 19:28
Linux's versions of gcloud and kubectl worked for me without any problems, I just decided to test if will windows binaries will work in wsl without problems.

But I believe current state of afairs assumes that it is better to use native linux clients for such things. Also `docker-compose.exe` for example works with errors in WSL so I use linux version, though `docker.exe` itself seem to work fine for now, at least I haven't meat problems with it, `gcloud` window's version too works with problems.

**Comment by sunjoong** [comment] 2017-07-05 20:10
> Linux's versions of gcloud and kubectl worked for me without any problems, I just decided to test if windows binaries will work in wsl without problems.

@whitecolor - Hmm... Does Windows have a TTY similar to that of unix? I'm not sure, but what if to try it with https://github.com/rprichard/winpty ? "winpty.exe kubectl.exe exec -it pod-name bash"?

**Comment by whitecolor** [comment] 2017-07-05 20:19
Well at lest I didn't try yet linux's kubectl client on new WSL (xenial) I've installed recently.

I use https://github.com/mintty/wsltty as WSL terminal.

**Comment by sunjoong** [comment] 2017-07-05 20:27
@whitecolor - Wsltty or wsl-terminal are another story :). I mean... kubectl.exe is a windows program and windows does not have a TTY like unix. Winpty has another purpose, I heard. Of course, wheither WSL support tty enough or not is a different issue.

**Comment by whitecolor** [comment] 2017-07-06 08:08
Yes the OP is about how to make kubectl.exe and other alike things to work in WSL. WSL claims to be able to execute native programs (or at least list pipe output) correctly. But in practice currenlty it is better to use (if possible) linux versions of binaries for many things to have them working correctly.

**Comment by sunjoong** [comment] 2017-07-06 13:32
@whitecolor - To sum up, linux native kubectl works well on WSL but windows kubectl.exe (manybe... without winpty?) on WSL doesn't.
> WSL claims to be able to execute windows binaries (actually pipe the output) correctly. But in practice currenlty it is better to use (if possible) linux versions of binaries for many things to have them working correctly.

So, that's a problem. Is that right? Hmm...

**Comment by whitecolor** [comment] 2017-07-06 13:57
> So, that's a problem. Is that right? Hmm...

Yes. There are problems with binaries that produce some extensive output (`docker-compose`) or interactive stdin `kubectl.exe`.

**Comment by sunjoong** [comment] 2017-07-06 14:10
@whitecolor - I see. I think they could mark as "bydesign", "feature" and "discussion" if some member of this tracker check this.

**Comment by TerjeBr** [comment] 2017-08-23 17:41
I have the same issue using Windows 8 MINGW64 console installed by SourceTree.

But from a DOS command prompt (using the program "cmd") it works.
It also works using the above mentioned workaround with winpty.

**Comment by DarthSpock** [comment] 2018-05-11 13:00
This issue belongs in https://github.com/Microsoft/Console and does have an issue open for TTY. FWIW, WSLTTY does in fact address this issue (vice winpty) and there is even a discussion on the Mintty page that discusses the differences between winpty and wsltty (short answer is wsltty works better and that is by design because Mingw has to tweak a port from Cygwin and has less functionality as a result.)

**Comment by benhillis** [comment] 2018-07-11 17:36
This should be fixed in 17618.  Please reopen if you continue to have issues.

**Closed by benhillis** 2018-07-11 17:36 UTC

**Comment by KalyanKumarPichuka** [comment] 2022-12-11 09:16
> winpty

This works for me

**Comment by KalyanKumarPichuka** [comment] 2022-12-11 09:18
one possible solution is to use [winpty](https://github.com/rprichard/winpty), it works fine for me now.

     winpty kubectl.exe exec -it pod-name -- sh

_Originally posted by @larrycai in https://github.com/microsoft/WSL/issues/2271#issuecomment-317006437_

**Comment by KalyanKumarPichuka** [comment] 2022-12-11 09:19
> one possible solution is to use [winpty](https://github.com/rprichard/winpty), it works fine for me now.
> 
> ```
>  winpty kubectl.exe exec -it pod-name -- sh
> ```

This works for me

**Comment by nrobayo-stratio** [comment] 2024-05-14 16:33
in my case, it works fine for me now (using gitbash, only option for me with windows).
`winpty kubectl --kubeconfig $HOME/.kube/config-dev -n ns-core exec -ti postgres-core -- bash`
