### ISSUE TITLE
WSL terminal: read failed 5: I/O error when opening a file with a Windows editor on a file in \\wsl$

### ISSUE THREAD

**Issue by ctataryn** [microsoft/WSL#5878] opened 2020-09-08 15:17 UTC
# Environment

```none
Windows build number: `Microsoft Windows [Version 10.0.19041.450]`
Your Distribution version: `Ubuntu 18.04`
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

**FYI:** This behaviour did not exist under WSL1

See: #5590 for a similar Python related issue.

I use gvim for Windows to edit files on the WSL filesystem. I do this via the `\\wsl$` fileshare via this script: 

`~/bin/gvim`:
```
#!/bin/bash
CMNT='/c'
CMD='/c/Windows/System32/cmd.exe'
GVIM='/c/Program Files (x86)/Vim/vim81/gvim.exe'
FILE=`realpath "${1:-.}"`
if [[ $FILE == $CMNT/* ]] ;
then
  FILE=${FILE/$CMNT\//C:\\}
else
  # replace the first forward slash
  FILE=${FILE/\//\\\\wsl\$\\Ubuntu\\}
fi
# replace the rest
FILE=${FILE//\//\\}
echo Launch gvim for file: $FILE
`"$GVIM" $FILE` &
```

This allows me to type: `gvim myfile` and have it do the necessary conversion of the path from WSL to Windows for `myfile.txt`.  For instance:

```
$ pwd
/home/craiger/tmp
$ gvim myfile.txt
```
This would launch gvim for Windows in the following way:

`/c/Program Files (x86)/Vim/vim81/gvim.exe \\wsl$\Ubuntu\home\craiger\tmp\myfile.txt &`

If I was in a `/c` folder (Windows filesystem) then it'd open `C:\...\myfile.txt` instead.

I will  then receive a: `read failed 5: I/O error` for each character I type in the terminal **as long as** gvim remains open.  As soon as I close gvim, the errors go away.

For instance, here I was typing `ls -al` while that gvim instance was still open, I got the error after typing each character:

![image](https://user-images.githubusercontent.com/435719/92491487-e9150700-f1b7-11ea-985e-4b98cfa31ee8.png)

Is there something I can do to maintain my ability to use gvim to open files within the WSL filesystem but get rid of the error I'm receiving in the terminal as a result?

**Note:** If I simply launch `'/c/Program Files (x86)/Vim/vim81/gvim.exe' \\\\wsl$\\Ubuntu\\home\\craiger\\src\\tmp\\hello.txt &` directly from the command line (without using my gvim script) then the problem is not present.  So I think it has to do with launching a windows program from a bash script.

**WSL logs**: Submitted and issue to the Feedback Hub, however the "Recreate My Problem" button in the Feedback Hub was disabled for me, so I could not submit any logs

#  Expected behavior

Regardless of whether or not I'm editing a file from my Windows process that was spawned from WSL, I should be able to type in my terminal without receiving `read failed 5: I/O error`

# Actual behavior

Launching gvim from a bashscript for a Windows process using `&` to background it whilst editing a file (i.e. error doesn't happen if I just launch gvim without passing it a file) causes the terminal to display `read failed 5: I/O error` when I type in characters. It is only after I terminate the gvim process that the terminal is restored to normal working conditions.

**Comment by DHowett** [comment] 2020-09-08 19:44
This is not related to–and will not help with–your problem, but you might be happy to learn about the `wslpath` utility that is accessible from any WSL distribution. It will do mount-table-aware translation of paths between Windows and WSL. :smile:

**Comment by therealkenc** [comment] 2020-09-08 19:51
> `"$GVIM" $FILE` &

You've started a job on a shell that is about to die. If it worked on WSL1, that was likely [by chance](https://github.com/microsoft/WSL/issues/4649#issuecomment-552147258). Running it from the commandline is not the same putting a `&` inside of a script. [And we're setting aside that a win32 program can't take job control signals, because it isn't a Linux program.]

Wasn't able to reproduce here on WSL2 (your script worked). But that almost certainly has to do with the behavior being undefined. That `EIO` is de-facto by-design. And _probably_ a dupe of #5590, but the OP repro over there is too cray to verify that with any certainty.

You probably want something like:
```
$ powershell.exe -Command 'Start ${env:ProgramFiles(x86)}\Vim\vim82\gvim.exe \\wsl$\focal2\home\ken\Devel\5878\hello.txt'
```

![image](https://user-images.githubusercontent.com/7049700/92519604-128d5d00-f1cf-11ea-996e-9febbf246b1f.png)

Or maybe just:

```
$ powershell.exe Start '${env:ProgramFiles(x86)}\Vim\vim82\gvim.exe' hello.txt
```

![image](https://user-images.githubusercontent.com/7049700/92520285-3604d780-f1d0-11ea-827e-2e7519668887.png)

Also what Dustin said.

**Comment by DHowett** [comment] 2020-09-08 19:57
I dunno; doing job control in a shell that's about to get terminated should be fine. Running a graphical application on actual Linuxen via `thing &` from a script isn't an unusual or uncommon thing to do, and interop _should_ make it quite possible for WSL to do the same.

I'm thinking about my xsession, which starts up a bunch of my GUI applications, then execs my window manager totally replacing itself with something that likewise doesn't have job control. It's encoded in decades of scripting knowledge :smile:

**Comment by therealkenc** [comment] 2020-09-08 20:25
> I dunno; doing job control in a shell that's about to get terminated should be fine. 

That is plenty common. Spawning that `xsession` with `ssh` to a remote machine.... less common. Which is in effect what is happening with that `gvim` and interop (spiritually, anyway). The job control is on the other side of the wire. Hence PS Start.

That said, whether it "should be fine", I won't deign to say. I am not even [sure](https://github.com/microsoft/WSL/issues/4649#issuecomment-552163381) whether #4649 "should be fine" or not. Which is why it is still chirping crickets.

**Comment by ctataryn** [comment] 2020-09-08 20:35
> 
> 
> This is not related to–and will not help with–your problem, but you might be happy to learn about the `wslpath` utility that is accessible from any WSL distribution. It will do mount-table-aware translation of paths between Windows and WSL. 😄

Oh yes, I know about `wslpath` however when I'm in `/c`, gvim won't understand how to get to that path so I have to convert it all to `C:\...`

**Comment by therealkenc** [comment] 2020-09-08 20:40
![image](https://user-images.githubusercontent.com/7049700/92525539-e5de4300-f1d8-11ea-96b0-8bc2a74e7b0b.png)

**Comment by ctataryn** [comment] 2020-09-08 20:45
@therealkenc neat, it'll make my script a lot simpler for sure 👍

**Comment by ctataryn** [comment] 2020-09-09 03:45
@DHowett Thanks for the suggestion of `wslpath -w` and to you @therealkenc for getting it working via Powershell. I'm no longer experiencing the `read failed 5` error.

**Closed** 2024-02-01 12:15 UTC
Labels: file system
