### ISSUE TITLE
WSL automatically inserts a ~ character

### ISSUE THREAD

**Issue by ndland** [microsoft/WSL#12073] opened 2024-09-24 22:22 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.4112]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1

### Distro Version

Ubuntu 24.04

### Other Software

Docker Desktop (Windows)

### Repro Steps

Start up a terminal, afk, `~` is automatically inserted into terminal

### Expected Behavior

No characters are automatically inserted into the terminal.

### Actual Behavior

The `~` character appears if the terminal window is active, and afk'd

**Comment by ndland** [comment] 2024-09-24 22:28
[WslLogs-2024-09-24_18-27-15.zip](https://github.com/user-attachments/files/17121845/WslLogs-2024-09-24_18-27-15.zip)

**Comment by Raven-Singularity** [comment] 2024-09-25 14:45
Did this character always appear on your Ubuntu, or did this start happening recently?

**Comment by OneBlue** [comment] 2024-09-25 16:09
@ndland: Can you share a video of where and how this character gets inserted ?

**Comment by zcobol** [comment] 2024-09-25 16:16
@ndland how do you launch the WSL instance? Does tilde is inserted when running `ubuntu2404.exe` also? Check your launch command. In `bash` the `~` expands to your home directory.

**Comment by Kazmirchuk** [comment] 2024-09-27 12:48
this could be caused by software like Caffeine that sends a virtual keystroke e.g. every minute to keep your screen unlocked

**Comment by ndland** [comment] 2024-09-27 17:32
> this could be caused by software like Caffeine that sends a virtual keystroke e.g. every minute to keep your screen unlocked

Holy shit. I never even considered that. You might be on to something... I do have Caffeine. At any rate, here is a gif of this happening.

![WindowsTerminal_fJGPPPa4SG](https://github.com/user-attachments/assets/a2212acc-3522-4eb9-b8dd-330583fb662c)

**Comment by ndland** [comment] 2024-09-27 17:50
> > this could be caused by software like Caffeine that sends a virtual keystroke e.g. every minute to keep your screen unlocked
> 
> Holy shit. I never even considered that. You might be on to something... I do have Caffeine. At any rate, here is a gif of this happening.
> 
> ![WindowsTerminal_fJGPPPa4SG](https://private-user-images.githubusercontent.com/4358059/371626507-a2212acc-3522-4eb9-b8dd-330583fb662c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTk2MjAsIm5iZiI6MTcyNzQ1OTMyMCwicGF0aCI6Ii80MzU4MDU5LzM3MTYyNjUwNy1hMjIxMmFjYy0zNTIyLTRlYjktYjhkZC0zMzA1ODNmYjY2MmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTc0ODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwMDNhMjgyOGZjZWZjYTFkMDYwMWQyODEwM2VjODQ4Mjc2ZDg1YTJhZDU4MDQ3ODk0OGUzNTMyNjBhOTBmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WeuwLAjejJnB72Y1_Vfy_CD5wiZFZMuxhd3fxifVZa8) [ ![WindowsTerminal_fJGPPPa4SG](https://private-user-images.githubusercontent.com/4358059/371626507-a2212acc-3522-4eb9-b8dd-330583fb662c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTk2MjAsIm5iZiI6MTcyNzQ1OTMyMCwicGF0aCI6Ii80MzU4MDU5LzM3MTYyNjUwNy1hMjIxMmFjYy0zNTIyLTRlYjktYjhkZC0zMzA1ODNmYjY2MmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTc0ODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwMDNhMjgyOGZjZWZjYTFkMDYwMWQyODEwM2VjODQ4Mjc2ZDg1YTJhZDU4MDQ3ODk0OGUzNTMyNjBhOTBmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WeuwLAjejJnB72Y1_Vfy_CD5wiZFZMuxhd3fxifVZa8) ](https://private-user-images.githubusercontent.com/4358059/371626507-a2212acc-3522-4eb9-b8dd-330583fb662c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTk2MjAsIm5iZiI6MTcyNzQ1OTMyMCwicGF0aCI6Ii80MzU4MDU5LzM3MTYyNjUwNy1hMjIxMmFjYy0zNTIyLTRlYjktYjhkZC0zMzA1ODNmYjY2MmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTc0ODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwMDNhMjgyOGZjZWZjYTFkMDYwMWQyODEwM2VjODQ4Mjc2ZDg1YTJhZDU4MDQ3ODk0OGUzNTMyNjBhOTBmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WeuwLAjejJnB72Y1_Vfy_CD5wiZFZMuxhd3fxifVZa8) [ ](https://private-user-images.githubusercontent.com/4358059/371626507-a2212acc-3522-4eb9-b8dd-330583fb662c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTk2MjAsIm5iZiI6MTcyNzQ1OTMyMCwicGF0aCI6Ii80MzU4MDU5LzM3MTYyNjUwNy1hMjIxMmFjYy0zNTIyLTRlYjktYjhkZC0zMzA1ODNmYjY2MmMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTc0ODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEwMDNhMjgyOGZjZWZjYTFkMDYwMWQyODEwM2VjODQ4Mjc2ZDg1YTJhZDU4MDQ3ODk0OGUzNTMyNjBhOTBmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WeuwLAjejJnB72Y1_Vfy_CD5wiZFZMuxhd3fxifVZa8)

As a test, I killed Caffeine, and I ran the same test, and it doesn't appear to be doing the same thing anymore. My guess is, Caffeine is the culprit. Unreal, but thank you @Kazmirchuk for pointing this out.

**Comment by zcobol** [comment] 2024-09-27 17:55
The screenshots revealed more information. It's not just a tilde inserted. `[28` is the beginning of an ANSI control sequence, and that's `conceal off`. Looks like you have a broken sequence somewhere.

Too much caffeine!? 😀

**Comment by ndland** [comment] 2024-09-27 17:56
Ironically, the `[28` appeared after I switched to `fish`. When I was using `zsh` it was just a `~`. Either way, yes, I think I've either had too much or not enough of caffeine. 😆

**Comment by OneBlue** [comment] 2024-09-27 18:10
Thank you for followup on this ! 
Closing since the issue caused by third party software.

**Closed by OneBlue** 2024-09-27 18:10 UTC
