### ISSUE TITLE
Cannot connect to HTTPS

### ISSUE THREAD

**Issue by gitlsl** [microsoft/WSL#5248] opened 2020-05-22 06:42 UTC
my env
win10 20h1,  wsl2,   ubuntu20 lts
same issue with https://github.com/microsoft/WSL/issues/3761#issuecomment-589929456

 apt update sources is ok
but next   (not noly this site,  for most https get this error )
````
 curl https://2020.ip138.com -v
*   Trying 59.57.13.181:443...
* TCP_NODELAY set
* Connected to 2020.ip138.com (59.57.13.181) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 2020.ip138.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 2020.ip138.com:443


 wget https://2020.ip138.com
--2020-05-22 14:42:14--  https://2020.ip138.com/
Resolving 2020.ip138.com (2020.ip138.com)... 59.57.13.181
Connecting to 2020.ip138.com (2020.ip138.com)|59.57.13.181|:443... connected.
Unable to establish SSL connection.
````

**Comment by joseph-so** [comment] 2020-05-23 02:40
Can you try to run sudo update-ca-certificates ? I have a similar problem and found out the /etc/ssl/certs are empty

**Comment by iridian-ks** [comment] 2020-06-10 06:01
I'm also getting the same thing. I tested on Kali, Ubuntu, and SUSE so I think this is WSL2 and not an issue with just a particular distro.

**Comment by triaton** [comment] 2020-07-23 15:19
@iridian-ks I am facing exactly the same issue. Do you have any update on this issue?

**Comment by iridian-ks** [comment] 2020-07-23 17:43
Nope, I am not with Microsoft so I can't really fix this issue. I tried looking at the network interfaces with Wireshark to see where things were hanging. Normal HTTP is actually much slower than the host machine and the additional TLS layer with HTTPS just causes it to hang until it breaks. I also face issues with SSH connections that suddenly drop. I believe there's a direct correlation to the size of the network packets and whether connections drop.

All of this happens only in WSL2 while on VPN, but not for the Docker for Desktop VM. The host machine doesn't have issues so the problem resides with WSL. I wouldn't even say it's a Hyper-V issue because IIRC the desktop OS (Windows) is actually a VM if you're running WSL.

Because of this issue and the fact that it doesn't affect Docker for Desktop... Here's what my ~/.bashrc has in it...

```
function __docker_fn {
    docker run -v ${HOME}/.tmp:/tmp -v $PWD:$PWD --workdir $PWD --rm -ti ${@}
}

function terraform {
     __docker_fn hashicorp/terraform:light ${@}
}

function vault {
     __docker_fn \
         --env VAULT_TOKEN=${VAULT_TOKEN} \
         --env VAULT_ADDR="${VAULT_ADDR}" \
         --env VAULT_SKIP_VERIFY=${VAULT_SKIP_VERIFY} \
         vault ${@}
}

function consul {
     __docker_fn consul ${@}
}

function pulumi {
    __docker_fn -v $HOME/.aws:/root/.aws \
        --env VAULT_SERVER_URL="${VAULT_SERVER_URL}" \
        --env VAULT_SKIP_VERIFY="${VAULT_SKIP_VERIFY}" \
        --env VAULT_TOKEN="${VAULT_TOKEN}" \
        -v $HOME/.pulumi:/root/.pulumi \
        --entrypoint pulumi \
        harbor.rei.com/middleware/pulumi:latest ${@}
}

function ansible-galaxy {
    __docker_fn --entrypoint ansible-galaxy quay.io/ansible/molecule:3.0.4 ${@}
}

function helm {
    __docker_fn --env KUBECONFIG="$KUBECONFIG" \
        -v $HOME/.kube:$HOME/.kube \
        -v $HOME/.kube:/root/.kube \
        -v $HOME/.helm:/root/.helm alpine/helm ${@}
}

function rancher {
    __docker_fn -v $HOME/.kube:/root/.kube -v $HOME/.rancher:/root.rancher rancher/cli2 ${@}
}

function kubectl {
    __docker_fn -u 0:0 --env KUBECONFIG="$KUBECONFIG" \
        -v $HOME/.kube:$HOME/.kube \
        -v $HOME/.kube:/root/.kube \
        -v $HOME/.helm:/root/.helm bitnami/kubectl ${@}
}

function go {
    __docker_fn --env GOPATH=$HOME/go --workdir $HOME/go:$HOME/go --workdir $HOME/go go ${@}
}

function aws {
    __docker_fn --env AWS_PROFILE="${AWS_PROFILE:-default}" -v ${HOME}/.aws:/root/.aws mesosphere/aws-cli ${@}
}
```

Maybe Microsoft ought to adopt VPNKit, which is the open source project that Docker uses to get it's VM to network properly :)

**Comment by AlexWayfer** [comment] 2020-07-29 17:21
> @therealkenc added the question label on May 22

I don't see any question.

**Comment by therealkenc** [comment] 2020-07-29 18:29
The submission (and others) are given the benefit an implied question (here, "why am I unable to establish [an] SSL connection?") in favor of closing outright for lack of repro or an identifiable WSL actionable.

**Comment by AlexWayfer** [comment] 2020-07-29 18:39
> The submission (and others) are given the benefit an implied question (here, "why am I unable to establish [an] SSL connection?")

No, there is no "why", there is "I'm unable" and that's it. People want working product. A work-around is fallback to WSL v1, as I know. So, the problem in WSL v2.

**Comment by joseph-so** [comment] 2020-07-29 22:48
Hi, I faced that issue before not able to connect any site by HTTPS, it is due to missing the root ca certificate in the system. Please run

`sudo update-ca-certificates`

**Comment by NordenF** [comment] 2020-08-26 10:55
Hi! I faced the same issue. The symptoms are the same as indicated in the ticket description.
Windows 10 (version 2004), WSL 2, Ubuntu 20 installed in WSL.

**Comment by blacktea-latte** [comment] 2020-09-15 16:05
Also encountered this issue. I'm running Ubuntu-18.04 (WSL2) on Windows 10 2004 19041.508.
After a fresh installation of Ubuntu, I ran
 `sudo apt update && apt upgrade`
followed by
`curl -v https://pyenv.run | bash`
resulting in error message

```
* Rebuilt URL to: https://pyenv.run/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 216.17.132.34...
* TCP_NODELAY set
* Connected to pyenv.run (216.17.132.34) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4799 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL; CN=pyenv.run
*  start date: Jan 12 00:00:00 2019 GMT
*  expire date: Jan 11 23:59:59 2021 GMT
*  subjectAltName: host "pyenv.run" matched cert's "pyenv.run"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0} [5 bytes data]
> GET / HTTP/1.1
> Host: pyenv.run
> User-Agent: curl/7.58.0
> Accept: */*
>
{ [5 bytes data]
< HTTP/1.1 200 OK
< Server: nginx/1.16.1
< Date: Tue, 15 Sep 2020 15:58:57 GMT
< Content-Type: text/plain
< Content-Length: 285
< Last-Modified: Thu, 03 Oct 2019 14:20:44 GMT
< Connection: keep-alive
< Vary: Accept-Encoding
< ETag: "5d9603bc-11d"
< Accept-Ranges: bytes
<
{ [285 bytes data]
100   285  100   285    0     0    237      0  0:00:01  0:00:01 --:--:--   237
* Connection #0 to host pyenv.run left intact
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
```

**Comment by blacktea-latte** [comment] 2020-09-16 00:12
@therealkenc My previous comment regarding reproducing the issue could have been on my side, thus deleting the comment for now..

**Comment by grant-brady** [comment] 2020-11-25 15:03
It seems that the problem is a VPN trying to MITM your traffic. Try running the below command to see whether there are any suspicious certificates involved.

```
openssl s_client -showcerts -connect https://2020.ip138.com:443
```

**Comment by caesarcxiv** [comment] 2021-03-20 15:17
Similar issue - cannot update helm charts via WSL 2 when connected to VPN

**Comment by evakili** [comment] 2021-12-13 12:39
The workaround here solves my issue: https://sbulav.github.io/wsl/wsl2-vm-tls-handshake-failed/.

**Comment by kczx3** [comment] 2022-03-03 16:31
I'm experiencing this issue with my Ubuntu 18.04 install using **WSL1** yet everything I've found so far seems to only be related to WSL2...

**Closed** 2024-02-01 12:17 UTC
Labels: network
