### ISSUE TITLE
Unify lxss symlinks and win32 symlinks on driveFS?

### ISSUE THREAD

**Issue by fpqc** [Microsoft/WSL#1475] opened 2016-12-08 05:39 UTC
The new builds have unprivileged symlinks available for us to play with in win32.  WSL also does symlinking on DriveFS.  However, when I made a DriveFS to DriveFS symlink from inside of WSL, this symlink appeared as a weird kind of file in Win32. (running `dir` in `cmd` said it was of type `junction [...]`, although it appears to be an invalid junction, since it was not traversable in Windows Explorer or cmd).   

It seems like a natural idea to have DriveFS-to-DriveFS symlinks created as actual NTFS symlinks now that they can be made without administrative privileges.  Also of note: Trying to traverse a Win32 symlink inside of WSL produces the error:

```
Input/output error
```  

Also, for obvious reasons, driveFS symlinks to VolFS/LXFS should maybe remain as they are (to avoid all of the weird and broken things that could happen), and VolFS-to-VolFS or VolFS-to-DriveFS symlinks are already a completely different format (they appear to be textfiles with special attributes if opened from a Win32 text editor).

**Comment by aseering** [comment] 2016-12-08 14:43
This sounds like #559 ?

For what it's worth, I would like this feature, and I have heard from others who would also like this feature.

**Comment by fpqc** [comment] 2016-12-08 14:45
@aseering This is the first build that enables unprivileged creation of symlinks (when in developer mode).

**Comment by aseering** [comment] 2016-12-08 14:56
By "this build", do you mean r14986?  Then it sounds like it's a good time to restart the discussion :-)

**Comment by fpqc** [comment] 2016-12-08 14:58
@aseering Yup. Technically it was announced last week for the cancelled insider build 14972 (because of the switch to the new UUP updater)

**Comment by benhillis** [comment] 2016-12-08 15:12
We've spoken about this internally and I agree it would be a nice feature to have. I'll check with the team about the current plan.

**Comment by fpqc** [comment] 2016-12-08 16:45
@benhillis Also, by the way, if we try to traverse a Win32 symlink with WSL in DriveFS, we get the error:

`Input/Output error`

**Comment by vyv03354** [comment] 2016-12-09 13:25
Although unprivileged create requires the developer mode, it does not matter to WSL because WSL also requires the developer mode anyway.

**Comment by fpqc** [comment] 2016-12-09 13:33
@vy03354 yup!

**Comment by 0xabu** [comment] 2016-12-16 00:04
This would also help with Cygwin interop. Right now, there's no common symlink format understood by both Cygwin and WSL, which makes switching between Cygwin and WSL a painful all-or-nothing affair. Cygwin already has read support for NTFS symlinks.

**Comment by fpqc** [comment] 2016-12-16 01:14
Hey 0xabu. I spoke to the msys2 irc channel and they're going upstream to have it changed there as well to use native symlinks on 14986 in dev mode.

**Comment by ayalon** [comment] 2017-01-18 09:37
From the point of a web developer, the cross use of symlinks is one of the most important missing features of WSL. I'm constantly testing WSL and for now, this missing features is the only left blocker to completely switch from OSX to Windows 10. Maybe the performance of the mounted file system is also annoying, but it's not a show stopper.

Anykind of improvments so that symlinks are seen / shared between the two filesystem would be so much appreciated.

**Comment by DannyT** [comment] 2017-02-08 10:21
What @ayalon said. We utilise grunt/gulp for various frontend dev setup/build processes which all works flawlessly in WSL with the exception of symlinks that are created. Windows not being able to follow symlinks created in WSL is the only show-stopper for our company-wide adoption.

**Comment by MatrixDev** [comment] 2017-02-08 10:28
I have similar problem developing on Android because of "repo" utility. It manages tons of git repositories at once (which is required in my case). Problem appears because all files in ".git" folder are links to actual files in ".repo" folder. Because of this it is impossible to use git on windows side...

**Comment by ayalon** [comment] 2017-02-10 10:27
@benhillis: Will this be considered for the Creators Update? THis would solve us sooo much headache.

**Comment by JFLarvoire** [comment] 2017-04-10 14:38
lxss symlinks break my win32 backup tools.  
+1 for the urgent need to unify lxss symlinks and win32 symlinks.

The tools on both sides of the programming world should be able to view and copy directory trees created on the other side, with all links in the copy usable by both sides as well.  
=> The win32 and Linux subsystems must hide to user-mode programs what target path is really written on disk, and instead return to them converted targets they can understand.  
For relative links this is pretty straightforward: Simply change all slahes to backslashes for the Win32 SS, or forward slahes for the Linux SS.  
For absolute links, the problem is that the targets don't refer to the same root. Yet that root can be identified by the kind of slash written by the link creator:  
- If the link contains back slashes, it was created by a Win32 process relative to a Windows volume.  
- If it contains forward slashes, it was created by a Linux process, relative to the Linux FS root.  
Then the subsystems can convert the link targets to absolute paths formatted as their respective user-mode programs expect.

**Comment by vyv03354** [comment] 2017-06-15 14:24
> Although unprivileged create requires the developer mode, it does not matter to WSL because WSL also requires the developer mode anyway.

This no longer holds. Since build 16215, WSL can run without developer mode enabled.

Another change: Since build 16193, WSL can follow already created NT symlinks. But it is still not possible to create a new NT symlink.

**Comment by 131** [comment] 2017-10-30 13:11
Any update here ?
This is also restraining my team for the switch :/

**Comment by sunilmut** [comment] 2017-10-30 18:11
@SvenGroot was working on this one and might be able to provide updates.

**Comment by 131** [comment] 2017-10-31 00:10
mklink (NTFS junctions) are seen as symlink in WSL (fall creator update 1709)

But beware that it's case sensitive, and WSL cares about it.
```
mklink /D node_modules D:\dvp\node_modules\async 
dir node_modules 
<JUNCTION>     async-co [D:\dvp\node_modules\async-co]
=> seen as symlink to /mnt/d/dvp/node_modules in WSL
```

Whereas 
```
mklink /D node_modules d:\dvp\node_modules\async  (note the lowercase D)
dir node_modules 
<JUNCTION>     async-co [d:\dvp\node_modules\async-co]  (works in windows)
=> invalid link in WSL
```

**Comment by ayalon** [comment] 2017-10-31 07:55
NTFS junctions work since almost a year. The issue is, that symlinks created inside WSDL result in an unreadable file on the NTFS side.
This is the remaining task in this thread.

Tools like composer or modman from magento create tons of symlinks but these do not work on NTFS. 

The missing piece is this:
> ln -s {/path/to/file-name} {link-name}

readable on NTFS.

**Comment by Brian-Perkins** [comment] 2017-11-22 18:56
Windows Insider Build 17046 contains some improvements for symlink compatibility. See the full description in the [release notes](https://github.com/MicrosoftDocs/WSL/releases/tag/17046)

**Comment by heldchen** [comment] 2017-11-22 19:33
awesome, works great!

**Comment by ayalon** [comment] 2017-11-23 08:03
I can wait to test this. This sounds really really awesome!

**Comment by tara-raj** [comment] 2018-07-31 20:28
Closing as this issue is fixed in Insiders Build 17046 as mentioned above https://github.com/Microsoft/WSL/issues/1475#issuecomment-346443150

**Closed by tara-raj** 2018-07-31 20:28 UTC
Labels: feature

**Comment by myuseringithub** [comment] 2018-10-12 18:48
> Closing as this issue is fixed in Insiders Build 17046 as mentioned above [#1475 (comment)](https://github.com/Microsoft/WSL/issues/1475#issuecomment-346443150)

@tara-raj Hi, does that mean that WSL symlinks can be opened with a native Linux container/VM ? I'm trying to do so but cannot seem to get it working. 
https://github.com/Microsoft/WSL/issues/3611 
Help !

**Comment by RDeluxe** [comment] 2018-10-21 15:33
I don't think @myuseringithub issue is the same as depicted here.
It's not a case issue.

**Comment by pldin601** [comment] 2020-02-01 08:46
Windows Build 18362.592
I have problem with Rush-managed monorepo inside WSL. It makes symbolic links inside WSL, which is unreadable from Windows IDE.

```C:\Users\roman\WebstormProjects\...\node_modules>dir
 Volume in drive C is OS
 Volume Serial Number is DE9A-DCBC

 Directory of C:\Users\roman\WebstormProjects\...\node_modules

01/31/2020  09:46 PM    <DIR>          .
01/31/2020  09:46 PM    <DIR>          ..
01/31/2020  09:46 PM    <DIR>          .bin
01/31/2020  09:46 PM    <JUNCTION>     koa [...]
01/31/2020  09:46 PM    <JUNCTION>     koa-body [...]
01/31/2020  09:46 PM    <JUNCTION>     koa-router [...]
01/31/2020  09:46 PM    <JUNCTION>     nodemon [...]
01/31/2020  09:46 PM    <JUNCTION>     parse-strings-in-object [...]
01/31/2020  09:46 PM    <JUNCTION>     rc [...]
               6 File(s)              0 bytes
               4 Dir(s)  80,805,060,608 bytes free
```
