### ISSUE TITLE
problem using clone with flag CLONE_VM

### ISSUE THREAD

**Issue by LexellA** [microsoft/WSL#10655] opened 2023-10-21 15:13 UTC
### Windows Version

10.0.19044.3086

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu 22.04

### Repro Steps

There is a problem when I practice using clone function, here's the code

```
#define _GNU_SOURCE
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>

#define STACKSIZ 8192

int child_progress()
{
    int val = 0;
    while(1)
    {
        printf("child value now = %d\n", val);
        val++;
        sleep(1);

        if (val == 10) {
            break;
        }
    }
    return 0;
}

int main()
{
    char *stack = (char*)malloc(STACKSIZ);
    int flag = CLONE_VM | SIGCHLD;
    pid_t pid = clone(child_progress, stack + STACKSIZ, flag, NULL);
    int status;
    printf("child pid: %d\n", pid);
    wait(0);
    printf("child exited\n");
    return 0;
}
```

I'm not sure if it is a bug, but when I run the code in ubuntu on vmware it works well.
and when I remove the CLONE_VM flag it works well, too.

### Expected Behavior

it should be like this
```
child pid: 5322
child value now = 0
child value now = 1
child value now = 2
child value now = 3
child value now = 4
child value now = 5
child value now = 6
child value now = 7
child value now = 8
child value now = 9
child exited
```

### Actual Behavior

every time it works differently
```
child pid: 25709
child pid: 25709
child value now = 0
child value now = 1
child value now = 2
child value now = 3
child value now = 4
child value now = 5
child value now = 6
child value now = 7
child value now = 8
child value now = 9
child exited
```

```
child value now = 0
child value now = 0
25692
child value now = 1
child value now = 2
child value now = 3
child value now = 4
child value now = 5
child value now = 6
child value now = 7
child value now = 8
child value now = 9
child exited
```

**Comment by OneBlue** [comment] 2023-10-21 20:16
What you're seeing is the expected behavior: When you clone, both threads run in parallel so it's essentially a race as to which is going to print first.

Closing since this is by design.

**Closed by OneBlue** 2023-10-21 20:16 UTC

**Comment by pianoplayeer** [comment] 2023-10-22 04:49
But when I experiment on Linux virtual machine(using VMWare), it just works like this:
child pid: 5322
child value now = 0
child value now = 1
child value now = 2
child value now = 3
child value now = 4
child value now = 5
child value now = 6
child value now = 7
child value now = 8
child value now = 9
child exited

And I have tested several times, the result always behaves like above. So does the WSL have different implementation at the bottom?
