### ISSUE TITLE
/run/nologin is not automatically removed after rebooting Ubuntu in WSL2

### ISSUE THREAD

**Issue by Heng-Zhou** [microsoft/WSL#10977] opened 2024-01-03 21:21 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.3803]

### WSL Version

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3803

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 22.04.3 LTS

### Repro Steps

1) Follow https://learn.microsoft.com/en-us/windows/wsl/install-manual to install WSL2. Step1-3 are the same.
2) In Step 4, download the latest update package of WSL2. After download, restart Windows.
3) After back from reboot, install the update package downloaded in the last step.
4) Open cmd.exe and run `wsl --install -d ubuntu` to install Ubuntu. Input username and password as prompted.
5) When installation of Ubuntu guest OS is done, run the following commands:
```
sudo apt update
sudo apt-mark hold acpid acpi-support
sudo apt upgrade
```
6) Install [ubuntu-wsl2-systemd-script](https://github.com/DamionGans/ubuntu-wsl2-systemd-script/tree/master):
```
cd ~ 
git clone https://github.com/DamionGans/ubuntu-wsl2-systemd-script.git
cd ubuntu-wsl2-systemd-script/
./ubuntu-wsl2-systemd-script.sh
```
7) Exit WSL and Ubuntu. On Windows command line, run:
```
wsl --shutdown
wsl --update
wsl
```
8) On Ubuntu command line, run `ls /run/nologin` to see this file exist. Because of the presence of this file, we cannot ssh into WSL.

### Expected Behavior

`/run/nologin` does not exist. This file is there to prevent ssh login during booting, which is reasonable. When booting is finished, this file should be deleted so that the Ubuntu OS is ready to accept ssh login. It is the case for normal Ubuntu. 

### Actual Behavior

`/run/nologin` is present. It should have been deleted after boot when Ubuntu is ready to accept ssh login. But the presence of this file (long after booting is finished) makes ssh login impossible with an error

> WSL SSH System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8).

### Diagnostic Logs

[WslLogs-2024-01-03_16-19-06.zip](https://github.com/microsoft/WSL/files/13823545/WslLogs-2024-01-03_16-19-06.zip)

**Comment by Heng-Zhou** [comment] 2024-01-03 21:25
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!
> ### Open similar issues:
> 
>     * [Log-out and log-in again with WSL running makes installed distros invisible (#2585)](https://github.com/microsoft/WSL/issues/2585),  similarity score: 0.80
> 
> 
> ### Closed similar issues:
> 
>     * [[Question] Anyway to perfectly start WSL2 on boot without login? (#7365)](https://github.com/microsoft/WSL/issues/7365),  similarity score: 0.81
> 
>     * [WSL2 won't boot up again after adding new user (#8417)](https://github.com/microsoft/WSL/issues/8417),  similarity score: 0.77
> 
>     * [WSL 2.0.1: systemd-logind logs session out after few minutes, purges /run/user/{uid} (#10552)](https://github.com/microsoft/WSL/issues/10552),  similarity score: 0.77
> 
>     * [WSL unchecks after doing restart (#5186)](https://github.com/microsoft/WSL/issues/5186),  similarity score: 0.77
> 
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

All links are inapplicable (even irrelevant). WSL team should rebuild this bot based on ChatGPT which I believe can give much better results.

**Comment by elsaco** [comment] 2024-01-03 21:51
@Heng-Zhou is `systemd` enabled? Because that file is managed by the `systemd-user-sessions`:

```
DESCRIPTION
       systemd-user-sessions.service is a service that controls user logins through pam_nologin(8). After basic
       system initialization is complete, it removes /run/nologin, thus permitting logins. Before system shutdown, it
       creates /run/nologin, thus prohibiting further logins.

```

and if you check the service status:

```
elsaco@texas:~# systemctl status systemd-user-sessions.service
● systemd-user-sessions.service - Permit User Sessions
     Loaded: loaded (/lib/systemd/system/systemd-user-sessions.service; static)
     Active: active (exited) since Wed 2024-01-03 13:42:05 PST; 7min ago
       Docs: man:systemd-user-sessions.service(8)
    Process: 199 ExecStart=/lib/systemd/systemd-user-sessions start (code=exited, status=0/SUCCESS)
   Main PID: 199 (code=exited, status=0/SUCCESS)
        CPU: 2ms

Jan 03 13:42:05 RIPPER systemd[1]: Starting Permit User Sessions...
Jan 03 13:42:05 RIPPER systemd[1]: Finished Permit User Sessions.

```

Notice the last two lines of output.

**Comment by Heng-Zhou** [comment] 2024-01-03 22:52
> systemctl status systemd-user-sessions.service

I know what's going on that makes the `/run/nologin` present, so I know how to solve this problem. I also believe WSL team knows what's going on. I submit this ticket to ask WSL team to confirm this bug and then fix it so that Ubuntu inside WSL can behave the same way as a normal Ubuntu in this aspect.

**Comment by Heng-Zhou** [comment] 2024-01-05 20:18
Instead of deleting `/run/nologin` directly, my workaround is running `sudo systemctl start systemd-user-sessions.service` and adding this command in `.bashrc`. To avoid inputting sudo password at boot time, I created a file `/etc/sudoers.d/service-ssh-start` which contains `<my user name> ALL=(root) NOPASSWD: /usr/bin/systemctl start systemd-user-sessions.service`.

But I think `systemd-user-sessions.service` should not be run explicitly by a normal user, in `.bashrc`. It should be run in background at boot without users even knowing it. I'm guessing it is missing somewhere when entering systemd namespace. I hope this bug can be fixed.

**Comment by OneBlue** [comment] 2024-01-09 22:48
@Heng-Zhou: Do you still see this behavior if you disable systemd ?

**Comment by Heng-Zhou** [comment] 2024-01-10 12:28
> @Heng-Zhou: Do you still see this behavior if you disable systemd ?

There is no `/run/nologin` if I do not install [ubuntu-wsl2-systemd-script](https://github.com/DamionGans/ubuntu-wsl2-systemd-script/tree/master). So, systemd is related to this issue. PS, I have to use systemd for GNOME desktop.

**Comment by OneBlue** [comment] 2024-01-10 19:44
Ok. Looks like that script is the issue. We unfortunately don't support it since this is third party. If you need systemd you can try to set 
```
[boot]
systemd=true
```

in `/etc/wsl.conf` 

Closing since the issue is caused by a third party script.

**Closed by OneBlue** 2024-01-10 19:44 UTC

**Comment by Heng-Zhou** [comment] 2024-01-10 21:38
Script is third party, but command is running in WSL. Don't think you can avoid fixing bugs so easily. I'll reopen it until this problem is solved.

**Comment by evibhm** [comment] 2024-07-10 13:52
@OneBlue I used 

```
[boot]
systemd=true
```

but it still exist `/run/nologin`
