### ISSUE TITLE
WSLENV passing '.' as current path causes segmentation fault

### ISSUE THREAD

**Issue by worksWithTools** [microsoft/WSL#5274] opened 2020-05-27 07:19 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.19041.84]

* Background
Recently I've been trying to use WSL to run make files which pass environment variables with "." meaning "current directory". This results in apparently nothing happening. (I am aware that $CURDIR achieves the same thing, but I working with legacy code here and there's a lot of changes that would need to be made as a workaround).

* Repro steps
However, when trying to repro the behaviour manually I can get a segfault quite reliably as follows:

$ export MYPATH=.
$ export WSLENV=$WSLENV:MYPATH/p
$ cmd.exe
**Segmentation fault**

* What's wrong / what should be happening instead:
The expectation would be that /p would understand that "." means "current path" and and translate from the local WSL current path to a windows formatted current path.
Instead as you can see it segfaults.

(I get the same result if I export MYPATH=foo -- where foo does not exist)

Other's have reported similar behaviour in the past but there are claims that such behaviour was fixed.
e.g. 
https://github.com/microsoft/WSL/issues/4039
https://github.com/microsoft/WSL/issues/4161
https://github.com/microsoft/WSL/issues/3810

I am raising this just in case it's a regression. The same behaviour is observed in WSL1 and WSL2.

Attached are the .etl logs that show the location(s) of the errors...

[bug_trace.zip](https://github.com/microsoft/WSL/files/4687111/bug_trace.zip)

**Comment by therealkenc** [comment] 2020-05-27 18:24
> $ export WSLENV=$WSLENV:MYPATH/p

That going to result in `WLSENV=:MYPATH/p`. Which confirmed segfault:

![image](https://user-images.githubusercontent.com/7049700/83057800-42439b00-a00c-11ea-9750-ff7dc769e460.png)

But is unrelated to '`.``' and the cited issues.

![image](https://user-images.githubusercontent.com/7049700/83058036-99e20680-a00c-11ea-8f72-9c563d975f55.png)

**Comment by worksWithTools** [comment] 2020-05-27 18:38
Thanks. I actually get the segfault whichever way I do things...
![image](https://user-images.githubusercontent.com/40574087/83059175-67a6c800-a051-11ea-801f-05b0ec726731.png)

I should say though, that my WSL is nested inside a Hyper-V - perhaps that's the problem? 
Maybe when I upgrade for real this won't be an issue. I hope so...

**Comment by therealkenc** [comment] 2020-05-27 19:00
You just repeated the original case there (there is "whichever way" above, you just redid the same thing).

> I should say though, that my WSL is nested inside a Hyper-V - perhaps that's the problem?

No the problem is you are missing a '$' on `MYPATH`.

**Comment by worksWithTools** [comment] 2020-05-27 19:38
Apologies - that would not achieve the desired result. 
I want the environment variable called MYPATH to be transferred via WSLENV to Win32 from WSL. 

According to the documentation:

>  A user sets the value of WSLENV to a concatenation of several other already-defined environment vars  , each suffixed with a slash followed by flags to specify how the value should be translated.  An example definition could be something like this:

<em>WSLENV=HOME/w:GOPATH/l:TMPDIR/p …</em>

If you put $ in front of MYPATH then all it is doing is passing the "literal" value across rather than the environment variable to be translated.

**Comment by therealkenc** [comment] 2020-05-27 20:56
Okay follow you now. A repro below that eliminates the `.` variable from the equation. Any path that doesn't resolve will do:

![image](https://user-images.githubusercontent.com/7049700/83071316-c7857a80-a021-11ea-9b0d-15b3fc4500f3.png)

This is a good catch; very much appreciate your follow up.

**Comment by benhillis** [comment] 2020-05-28 02:40
Thanks I’ll take a look at this.

**Comment by benhillis** [comment] 2020-05-28 18:53
Ok, I have a fix for the segfault issue.  Looking at this, when you specify /p or /l, the current logic is treats those as relative paths.  Sounds like you are expecting this to be translated to an absolute Windows path and vise-versa?

For example:
```
ben@LATERALUS:~# MYPATH=.
ben@LATERALUS:~#WSLENV=MYPATH/p
ben@LATERALUS:~#cmd.exe /c echo $MYPATH
"\\wsl$\ubuntu\home\user"
```

This is what it currently does:
```
ben@LATERALUS:~# MYPATH=.
ben@LATERALUS:~# WSLENV=MYPATH/p
ben@LATERALUS:~# cmd.exe /c echo $MYPATH
"."
```

**Comment by worksWithTools** [comment] 2020-05-28 19:07
Hi,
Thanks for fixing. I think to be honest, I may have been incorrect in assuming "." would be translated to an absolute path. If the current behaviour leaves "." as "." and doesn't crash, then that will be fine.

Thanks again.

**Comment by benhillis** [comment] 2020-05-28 20:41
Ok, thanks!

**Comment by therealkenc** [comment] 2020-08-03 23:50
/fixed in 20180. Maybe a bit earlier.

![image](https://user-images.githubusercontent.com/7049700/89237897-46121180-d5a9-11ea-873f-13456938670b.png)

**Closed by therealkenc** 2020-08-03 23:50 UTC
Labels: bug, fixedininsiderbuilds
