### ISSUE TITLE
"Bash Here" Context Menu in Windows Explorer

### ISSUE THREAD

**Issue by Manouchehri** [Microsoft/WSL#603] opened 2016-06-30 06:32 UTC
We should have a context menu that gives an option to open Bash in the current folder.

![image](https://cloud.githubusercontent.com/assets/7232674/16478896/c7fd7c78-3e6a-11e6-9aff-0b1ada299261.png)

**Comment by Manouchehri** [comment] 2016-06-30 06:58
I have already written a reg file if anyone wants to add it now.

https://github.com/Manouchehri/bash-WSL-context-menu

**Comment by Manouchehri** [comment] 2016-06-30 06:59
![image](https://cloud.githubusercontent.com/assets/7232674/16479498/aac63344-3e6e-11e6-9c3e-3de4f2f9c710.png)

**Comment by benhillis** [comment] 2016-06-30 15:22
Thanks, this is great!  One change you should consider making though is remove the hardcoded C:\Windows portion of the path which will only work for user's who have C:\Windows as their Windows directory.  You can fix this by using a REG_EXPAND_SZ registry value.  I'll submit a pull request to your repo :)

**Comment by Manouchehri** [comment] 2016-06-30 15:45
Pull requests are always appreciated. 😊 Sorry, I haven't used Windows
since the 7 Technical Preview so I've forgotten with how directories/paths
work here.

Feel free to add this to LxRun.exe or wherever is appropriate, would be
convenient to have it set up by default.

**Comment by factormystic** [comment] 2016-06-30 15:53
Also there's no need to write to HKCR. If you really do want it to be available for all users, write to HKLM\Software\Classes. If you only want it to apply to the current user, write to HKCU\Software\Classes.

**Comment by Manouchehri** [comment] 2016-06-30 17:57
The reason I wrote it in HKCR is because cmd and Git Bash both did that.

We should probably installing it per user for WSL, right?

**Comment by fpqc** [comment] 2016-06-30 18:50
Yeah, seems like it should be per-user.

**Comment by Manouchehri** [comment] 2016-07-11 07:10
@benhillis Any update on this?

**Comment by benhillis** [comment] 2016-07-11 15:09
Unfortunately this change will not be in the Windows 10 anniversary update.  Thanks for providing the reg key, I think many users will want this functionality and luckily it is easy to achieve with a simple reg key import.

**Comment by Manouchehri** [comment] 2016-07-11 18:00
Thanks, good to know. =)

**Comment by JamesEarle** [comment] 2016-08-03 16:59
Thanks for the reg key! Any word on this being incorporated into future updates?

**Comment by TimothyBramlett** [comment] 2016-08-06 19:48
Yeah, please get this incorporated ASAP.  Because the other windows directories are mounted in `mnt` it makes it to where you cant just easily copy and paste paths from explorer.  So, this is the quickest way to quickly open up the current explorer directory you are viewing, in bash.

**Comment by fpqc** [comment] 2016-08-06 20:23
TimothyBramlett I bet @xilun could add something to cbwin like "wcd" that would do patht translation back from Windows paths to linux ones.

**Comment by xilun** [comment] 2016-08-06 20:32
@fpqc It's quite easy to program but a little bit out of scope on my side... also you would have to single quote escape it due to backslashes - not very convenient. I think ConEmu does path translation on paste, but then of course when you use ConEmu and WSL at the moment there is the current issue of WSL / console keys not working well outside of an unwrapped Windows Console.

**Comment by SaschaNaz** [comment] 2016-10-24 13:02
I'm always getting "/mnt/c/Windows/System32", how can I get "current directory"?

**Comment by Manouchehri** [comment] 2016-10-25 18:46
Please use ConEmu instead, it's much better than my method.

**Comment by bitcrazed** [comment] 2017-02-21 23:07
One of the reasons we can't support file explorer context menu extensions is because we can't launch bash at an arbitrary folder location.

We have it on our backlog to fix for a future release.

**Comment by mklement0** [comment] 2017-02-27 04:57
Here's a working solution that uses an aux. `cmd` command to change to the target directory first, which therefore comes with a _caveat_:  the resulting Bash console window will therefore have `cmd.exe`'s icon and will be grouped with regular `cmd.exe` in the taskbar.

If you **save the following text in a `*.reg` file and open (double-click) it**, you'll be prompted to import the definitions into your user-specific registry hive.

After import, you'll find a `Bash Console Here` command in the context menu of folders in File Explorer, and also when you click in the empty space inside a folder.  
On selecting that command, a Bash console window will open in that folder.



    Windows Registry Editor Version 5.00

    [HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\Background\shell\BashConsoleHere]
    @="Bash Console Here"
    "Icon"=hex(2):25,00,4c,00,4f,00,43,00,41,00,4c,00,41,00,50,00,50,00,44,00,41,\
      00,54,00,41,00,25,00,5c,00,6c,00,78,00,73,00,73,00,5c,00,62,00,61,00,73,00,\
      68,00,2e,00,69,00,63,00,6f,00,00,00
    
    [HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\Background\shell\BashConsoleHere\command]
    @="cmd /c cd \"%V\" && bash.exe"
    
    [HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell\BashConsoleHere]
    @="Bash Console Here"
    "Icon"=hex(2):25,00,4c,00,4f,00,43,00,41,00,4c,00,41,00,50,00,50,00,44,00,41,\
      00,54,00,41,00,25,00,5c,00,6c,00,78,00,73,00,73,00,5c,00,62,00,61,00,73,00,\
      68,00,2e,00,69,00,63,00,6f,00,00,00
    
    [HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell\BashConsoleHere\command]
    @="cmd /c cd \"%1\" && bash.exe"


Alternatively, you can use the following **PowerShell snippet** to create the registry entries:



    $null = 0..1 | % {
      $key = New-Item -Force $('HKCU:\Software\Classes\Directory{0}\shell\BashConsoleHere' -f ('', '\Background')[$_])
      $key | New-ItemProperty -Name '(Default)' -Value 'Bash Console Here' -Type String
      $key | New-ItemProperty -Name 'Icon' -Value '%LOCALAPPDATA%\lxss\bash.ico' -Type ExpandString
      $key = New-Item -Force "$($key.PsPath)\command"
      $key | New-ItemProperty -Name '(Default)' -Value "cmd /c cd `"$(('%1', '%V')[$_])`" && bash.exe" -Type String
    }

To remove the entries later:

    0..1 | % {
      Remove-Item -Recurse -LiteralPath $('HKCU:\Software\Classes\Directory{0}\shell\BashConsoleHere' -f ('', '\Background')[$_])
    }

**Comment by Tetheta** [comment] 2017-10-17 15:22
This works great and all, but at this point definitely seems like a feature that should be an option to have baked in. Any ideas on if there are plans for that?

**Comment by SplittyDev** [comment] 2018-04-06 12:06
Any news on that issue?

**Comment by Brian-Perkins** [comment] 2018-05-09 21:39
Support for a context menu item was added in build [17666](https://github.com/MicrosoftDocs/WSL/releases/tag/17666).

**Closed** 2018-05-29 19:52 UTC
Labels: console, feature, fixedininsiderbuilds

**Comment by mkarpoff** [comment] 2018-05-31 15:35
Something I've noticed is that if you use the open bash here context menu. It doesn't use any of your wsl console settings (eg. colors, fonts, window and font size)

**Comment by sunilmut** [comment] 2018-05-31 18:14
@bitcrazed - Could @mkarpoff's report be console related?

**Comment by fpqc** [comment] 2018-06-01 01:02
@sunilmut without a doubt it is console-related.

**Comment by bitcrazed** [comment] 2018-06-07 18:41
@mkarpoff As described in [our post explaining how Console settings are resolved](https://blogs.msdn.microsoft.com/commandline/2017/06/20/understanding-windows-console-host-settings/), when you launch a distro via Explorer context menu, the Console will look for settings in the following locations and order:

1. Launching shortcut (none in this case)
1. App-specific settings in the Registry
1. Default Console settings in the Registry

As noted above, when you launch via the context menu, you're not launching via a tile, so Console will look for distro settings, or default Console settings from the registry.

If you launch your distro from a start menu tile, or shortcut pinned to your taskbar, your Console settings for that distro will be stored in that tile/shortcut but won't be found/used when launching via the context menu.

Alas, we can't change this behavior in Console as it stands today, because doing so would break MANY users' expected behaviors, etc.

However, we are looking at how we might rationalize, simplify, and improve settings in the future.

**Comment by eromoe** [comment] 2019-04-22 03:54
@Brian-Perkins Could you consider adding an icon ?
shift context menu would show powershell and linux shell 
![image](https://user-images.githubusercontent.com/3938751/56482119-fe22c480-64f4-11e9-9943-e82df2f952d3.png)

This would look ugly with some menu-items had icon
