### ISSUE TITLE
Starting bash in folder issue

### ISSUE THREAD

**Issue by SpontaneousDuck** [Microsoft/WSL#1836] opened 2017-03-30 17:02 UTC
On Windows version 10.0.15063 with bash Ubuntu version 16.04, starting bash from a folder either from right click context menu or explorer address bar "bash" command no longer functions if the folder path has a space in it. Issue can also be seen in Visual Studio Code when using the integrated terminal set to bash.exe. The bash terminal opens up normally with the directory automatically navigated to the correct folder. But, if the folder path has a space in it, the terminal opens to top directory instead.

**Comment by benhillis** [comment] 2017-03-30 17:10
@SpontaneousDuck - Can you clarify what you mean by right click context menu or "explorer address bar bash command"?  Those are not officially parts of WSL.  I've verified that current working directory propagation is working correctly for folders with spaces in them:

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\benhill>cd "\benhill\New Folder"

C:\benhill\New Folder>bash
benhill@BENHILL-STUDIO:/mnt/c/benhill/New Folder$
```

**Comment by SpontaneousDuck** [comment] 2017-03-30 17:31
You are correct! After further, examination the issue only occurs when using the above method to start in a folder created by Google Drive windows application "C:\Users\user1\Google Drive\". The folder has same permission as others I have used to accomplish this:
`drwxrwxrwx 0 root root     512 Mar 29 22:36 Google Drive`
Not sure why that would be... This and all sub-folders cause this error.

**Comment by benhillis** [comment] 2017-03-30 17:37
Is the Google Drive folder a reparse point?

**Comment by SpontaneousDuck** [comment] 2017-03-30 17:47
The folder is not an NTFS junction point (verified by `dir /al`). Is that what you meant or is there another way to verify this?

**Comment by 0xbadfca11** [comment] 2017-04-21 17:06
Google Drive folder is not reparse point. I confirmed this with [NTFS File Sector Information Utility](https://web-beta.archive.org/web/20150223112102/http://support.microsoft.com/kb/253066/en-us).
Instead, I discovered that I found only myself in the NTFS ACL of the Google Drive folder.
Even SYSTEM does not exist. The cause is this.

**Comment by Teifun2** [comment] 2017-05-04 19:28
I Have the same Problem! Is there a fix/workaround for this?

**Comment by Benjoyo** [comment] 2017-05-30 15:08
Would love a fix to this as well!

**Comment by FelipeMartin** [comment] 2017-05-30 20:38
If I am understanding you well, I just opened an issue related to this.

https://github.com/Microsoft/BashOnWindows/issues/2175

As I just updated to Creator's version yesterday, it seems to be related with this update.

**Comment by sunilmut** [comment] 2017-06-09 19:30
This does not look like a WSL/bash specific issue. The team that is responsible for creating the `Google Drive folder` seems to be not setting the right permissions on it. Now, if we could find out which team is that or how to get to them.

**Comment by sunilmut** [comment] 2017-06-09 19:34
Marking this is dupe of #2175

**Comment by FelipeMartin** [comment] 2017-06-09 19:36
@SpontaneousDuck Did you updated to Creators version ? If so, one possible problem is permission. Follow this #2175.

**Comment by FelipeMartin** [comment] 2017-06-09 19:36
@sunilmut Thank you for the reference. Lets help each other.

**Comment by tara-raj** [comment] 2018-09-06 19:37
Closing issue as duplicate. Please refer to issue #2175.

**Closed by tara-raj** 2018-09-06 19:37 UTC
Labels: duplicate
