### ISSUE TITLE
Still unable to launch windows processes from WSL when using long environment variables (see #7947 or #6420))

### ISSUE THREAD

**Issue by MarkusDost** [microsoft/WSL#9052] opened 2022-10-21 15:52 UTC
### Version

Microsoft Windows [Version 10.0.22621.674] / WSL-Version 0.70.0.0 / WSLg-Version 1.0.45

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102

### Distro Version

Ubuntu 22.04

### Other Software

cmd.exe

### Repro Steps

1. Start Ubuntu
2. Execute the attached script
`$ . environment-setup-aarch64-tdx-linux_modified`
[environment-setup-aarch64-tdx-linux_modified.zip](https://github.com/microsoft/WSL/files/9840538/environment-setup-aarch64-tdx-linux_modified.zip)

4. Start cmd.exe

### Expected Behavior

cmd.exe is started

### Actual Behavior

It hangs for a moment and prints
`<3>init: (3508) ERROR: UtilAcceptVsock:244: accept4 failed 110`

The strace of cmd.exe says 
`writev(2, [{iov_base="<3>init: (3512) ERROR: UtilAccep"..., iov_len=63}, {iov_base=NULL, iov_len=0}], 2<3>init: (3512) ERROR: UtilAcceptVsock:244: accept4 failed 110`

**Comment by benhillis** [comment] 2022-10-21 22:46
Thanks for the detailed repro, I will take a look.

**Comment by OneBlue** [comment] 2022-10-25 22:22
Thank you for reporting this @MarkusDost. Unfortunately, I can't reproduce the issue.

Can you share full logs of a repro so we can have a deeper look ? 

/logs

**Comment by MarkusDost** [comment] 2022-10-26 19:09
There you go: 
[WslLogs-2022-10-26_21-06-07.zip](https://github.com/microsoft/WSL/files/9873040/WslLogs-2022-10-26_21-06-07.zip)

I hope, this helps.

Best regards,
Markus

**Comment by OneBlue** [comment] 2022-10-27 22:05
Thank you @MarkusDost. 
Unfortunately nothing jumps out from the logs.

Can you share the full output of `strace -f cmd.exe` ?

**Comment by MarkusDost** [comment] 2022-10-28 07:58
Here it is: 
[strace.log](https://github.com/microsoft/WSL/files/9886443/strace.log)

Best regards,
Markus

**Comment by OneBlue** [comment] 2022-10-31 18:30
Thank you @MarkusDost. It looks like something is timing out on the Windows side of things.

Can you please:

- Run wsl.exe --shutdown to make sure that WSL is stopped
- Reproduce the issue
- Share a dump of all the wsl.exe and wslhost.exe processes on this issue

**Comment by MarkusDost** [comment] 2022-11-01 09:39
What do I have to do to create a dump of the named processes?

Best regards,
Markus

**Comment by OneBlue** [comment] 2022-11-01 17:37
@MarkusDost: The simplest way would be to called collect-wsl-logs.ps1 with `-Dump` (as administrator). For instance:

```
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
Set-ExecutionPolicy Bypass -Scope Process -Force
.\collect-wsl-logs.ps1 -Dump
```

**Comment by MarkusDost** [comment] 2022-11-02 07:41
There are 3 dumps (2x wslhost and 1x wslservice), but the one for wslservice is too big to upload (31 MB as zip, 25 MB are allowed)
[WslLogs-2022-11-02_08-14-21_without_wslservice.zip](https://github.com/microsoft/WSL/files/9917630/WslLogs-2022-11-02_08-14-21_without_wslservice.zip)

**Comment by OneBlue** [comment] 2022-11-04 18:49
Thank you @MarkusDost. Unfortunately I'm not seeing any `wsl.exe` dump in that folder, which is where I would start the investigation. Can you share a `wsl.exe` dump after  reproducing the issue ?

**Comment by MarkusDost** [comment] 2022-11-07 07:04
This one looks better:

- [WslLogs-2022-11-07_07-55-41.zip](https://github.com/microsoft/WSL/files/9948906/WslLogs-2022-11-07_07-55-41.zip)
- [wsl.10500.zip](https://github.com/microsoft/WSL/files/9948910/wsl.10500.zip)
- [wslhost.4092.zip](https://github.com/microsoft/WSL/files/9948912/wslhost.4092.zip)
- [wslhost.16676.zip](https://github.com/microsoft/WSL/files/9948913/wslhost.16676.zip)
- [wslhost.20536.zip](https://github.com/microsoft/WSL/files/9948915/wslhost.20536.zip)
- [wslservice.6824.zip](https://github.com/microsoft/WSL/files/9948916/wslservice.6824.zip)

The dumps are again 7zip-files for better compression.

**Comment by MarkusDost** [comment] 2022-11-09 06:50
> What's the output of $WSLENV before running the script you shared ?
`echo $WSLENV` before running the script prints out nothing, $WSLENV is empty

> Which distribution does this issue happen with ? Does it happen with all distributions ?
I'm using Ubuntu 22.04.1. It also happens with all distributions available online:
- Ubuntu 18.04.6
- Ubuntu 20.04.5
- Debian
- Kali Linux
- SLES-12
- Oracle Linux 8.5
- Oracle Linux 7.9

In SLES-15 calling `cmd.exe` I got the error `command not found`

> Which user are you seeing the issue with ? Does root / non-root make a difference ?
After installation of the distribution I created a user 'gemac' with password 'gemac'. With this user I call the script and `cmd.exe` and get the timeout error.
When I switch to root with `sudo -s`, call the script and `cmd.exe` than I get the error `command not found`. As root I cannot start cmd.exe or explorer.exe.

> What's the output of cat /etc/wsl.conf inside the distro ?
In the file system of the distribution there is no such file. The .wslconf in my Windows user directory looks as follows:
`# Settings apply across all Linux distros running on WSL 2
[wsl2]

# Limits VM memory to use no more than 24 GB, this can be set as whole numbers using GB or MB
memory=24GB 

# Sets the VM to use 12 virtual processors
processors=12

# Sets amount of swap storage space, default is 25% of available RAM
swap=8GB`

My processor is a i712700H with 12 power and 8 efficiency cores.

**Comment by MarkusDost** [comment] 2022-11-09 07:41
I removed the Windows Features "Windows Hypervisor Platform" and "Windows Subsystem for Linux" and the "Windows Subsystem for Linux Update" and reinstalled them. But the error is still present.

**Comment by MarkusDost** [comment] 2022-11-10 08:53
The install problem seems to be the root of the original error.

I logged in as local admin, removed WSL completly from the system, rebooted and installed WSL in a terminal with
```
wsl --install
```
The install process worked without problems. After rebooting and installing Ubuntu I called my script and `cmd.exe` afterwards. No timeout happens and `cmd.exe` started without problems. Calling `SET` within `cmd.exe` shows me my environmental variables correctly.

Now when I try this with my unprivileged domain account I got the above mentioned errors. I cannot install WSL from the store (error 0x80240066) or the command line:
```
wsl --install
Installation: VM-Plattform
VM-Plattform wurde installiert.
Installation: Windows-Subsystem für Linux
Eine angegebene Anmeldesitzung ist nicht vorhanden. Sie wurde gegebenenfalls bereits beendet.
```
Only with the tool "Windows Features" I can install the WSL but then I got the error in the first post.

**Comment by OneBlue** [comment] 2022-11-10 23:25
Thank you @MarkusDost. This is really interesting because I can't reproduce the same issue at all, so there must be something different about your machine.

To give some context what's happening when a Windows process is executed from inside WSL2: 

- The binftmt interpreter (installed by WSL2) sends a message to its interop server (via `$WSL_INTEROP`)
- The interop server sends a message to the wslservice (on the Windows side)
- The server connects to the process created by the binftmt interpreter to relay stdin / stdout / stderr.

I'm wondering if the issue is with the interop server.

To investigate that, can you please:

- Run `wsl.exe --shutdown` to make sure nothing is running
- Then open one shell via `wsl.exe`, and inside that shell run `echo $WSL_INTEROP` (and leave that shell opened)
- This will give you the pid of the interop server for your shell (under the format `/run/WSL/<pid>_interop` )
- Once you have that pid, open ** another ** WSL shell via `wsl.exe` and run `strace -p  8  -v -s 1000 > strace-output.txt 2>&1 ` (and leave it running)
- In the first shell, reproduce the issue where `cmd.exe` fails to execute
- Once `cmd.exe` has failed to execute, use ctrl-C to stop strace, and then share the content of `strace-output` on this issue

**Comment by MarkusDost** [comment] 2022-11-11 08:14
I had to 'sudo' the strace. Here is the log: [strace-output.txt](https://github.com/microsoft/WSL/files/9988250/strace-output.txt)

Do you have an idea, why the normal install of wsl fails with my domain account?

**Comment by OneBlue** [comment] 2022-11-11 20:45
Thank you @MarkusDost. Looking at these logs, It looks like you've been using the inbox WSL (and not the store app) this entire time. With inbox WSL I can actually reproduce the issue (which is fixed in store WSL).

To answer your question, administrator access is required to install store WSL, so that's probably why you're seeing this error.

**Comment by MarkusDost** [comment] 2022-11-14 07:15
Thanks @OneBlue for clarifying how the bug is caused.

Even with administrator access the installation of WSL with my domain account fails.
When I try to install the WSL with an unprivileged account, I get a prompt to enter admin credentials. After entering them I get this error:
```
$ wsl --install
Installation: VM-Plattform
VM-Plattform wurde installiert.
Installation: Windows-Subsystem für Linux
Eine angegebene Anmeldesitzung ist nicht vorhanden. Sie wurde gegebenenfalls bereits beendet.
```
In English (translated with DeepL):
```
$ wsl --install
Installation: VM Platform
VM platform has been installed.
Installation: Windows subsystem for Linux
A specified logon session does not exist. It may have already been terminated.
```
There is no difference when I open a PowerShell with admin rights. I get the same error output

The same is with the store. During installation I have to enter admin credentials, but then the error 0x80240066 appears.

**Comment by MarkusDost** [comment] 2022-11-15 07:36
No, I am not in a remote session. I am physically sitting in front of the computer.

**Comment by OneBlue** [comment] 2022-11-21 18:44
Thank you @MarkusDost.

I wonder if this is a store issue.

Can you with --web-download (wsl --install --web-download) and let me know if you see the same error ?

**Comment by MarkusDost** [comment] 2022-11-22 08:04
Yes I'm seeing the same error:
```
$ wsl --install --web-download
Der angeforderte Vorgang erfordert erhöhte Rechte.
Installation: VM-Plattform
VM-Plattform wurde installiert.
Herunterladen: Windows-Subsystem für Linux
Installation: Windows-Subsystem für Linux
Windows-Subsystem für Linux wurde installiert.
Installation: Ubuntu
Eine angegebene Anmeldesitzung ist nicht vorhanden. Sie wurde gegebenenfalls bereits beendet.
```

Translated:
```
$ wsl --install --web-download
The requested operation requires elevated privileges.
Installation: VM Platform
VM platform has been installed.
Download: Windows Subsystem for Linux
Installation: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.
Installation: Ubuntu
A specified login session does not exist. It may have already been terminated.
```

Although it says WSL has been installed, it has not.
When I repeat the command, I am again asked for administrator credentials, but nothing happens and after a while the command prompt appears again:
```
$ wsl --install --web-download
The requested operation requires elevated privileges.
$
```

**Comment by OneBlue** [comment] 2022-11-24 01:10
Thank you @MarkusDost.

Can you try installing the package directly by:

- [Downloading it manually](https://github.com/microsoft/WSL/releases/download/1.0.0/Microsoft.WSL_1.0.0.0_x64_ARM64.msixbundle)
- Then running: `Add-AppxPackage /path/to/package` in an elevated powershell ?

**Comment by MarkusDost** [comment] 2022-11-24 10:36
With the manually downloaded package I was able to install and use the WSL.
When I install it in an elevated powershell, only the admin got the WSL. So I removed it and I tried to install it with the unprivileged domain account again and that worked too. No admin credentials were necessary.

**Closed** 2022-12-05 06:15 UTC
Labels: bug, interop
