### ISSUE TITLE
Restarting system after enabling virtualization make my sytem stuck and it doesn't get open afterwards and shows disk recovery and repair screen

### ISSUE THREAD

**Issue by priya-jain-1** [microsoft/WSL#5872] opened 2020-09-07 10:48 UTC
# Environment
 
```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
I am not able to open WSL
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

**WSL logs**: 

#  Expected behavior

# Actual behavior

**Comment by MU-Software** [comment] 2020-09-07 17:36
Maybe possible duplicate of #5760 ?
There might be some issues on KB4566782 and VirtualMachinePlatform I guess...

**Comment by ivanix1** [comment] 2021-06-10 04:21
Actually, I found the issue.  The PC (kvm) did not have the CPU / BIOS virtualization features enabled.
In my case the KVM did not have proper nested virtualization. After applying OS booted and WSL2 and docker on desktop worked normally.

**Closed** 2024-02-01 12:15 UTC
Labels: hypervisor-platform
