### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG

### ISSUE THREAD

**Issue by 1446311191** [microsoft/WSL#10297] opened 2023-07-15 16:02 UTC
### Windows Version

Microsoft Windows [版本 10.0.25905.1000]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

custom kernel

### Distro Version

Ubuntu-16.04, Ubuntu-18.04, Ubuntu-20.04, Ubuntu-22.04

### Repro Steps

PS C:\Users\msn14> ubuntu2004.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14> ubuntu1604.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14> ubuntu1804.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14> ubuntu2204.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14>

### Expected Behavior

The wsl distribution system can be entered normally

### Actual Behavior

PS C:\Users\msn14> ubuntu2004.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14> ubuntu1604.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14> ubuntu1804.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14> ubuntu2204.exe
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
参数错误。
Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
Press any key to continue...
PS C:\Users\msn14>

**Comment by Peter-Maguire** [comment] 2023-07-16 20:05
Having the same issue

**Comment by Oldiesmann** [comment] 2023-07-17 01:11
Same problem here. Windows 11 insider preview build 25905

**Comment by MAD-vindi** [comment] 2023-07-17 07:34
I had the same issue. I rolled back the Windows version to its previous build, and the issue is no longer present.

**Comment by 3265** [comment] 2023-07-17 07:41
I have the same issue...

**Comment by Mr-Robby** [comment] 2023-07-17 12:04
I have same issue, build 25905.1000 AMD Ryzen

**Comment by thespatt** [comment] 2023-07-17 19:41
also AMD Ryzen, also having issue

**Comment by ScottKirvan** [comment] 2023-07-18 01:42
Just as an FYI:  I think this may also be breaking NAS Samba (SMB) connections.  I'm seeing the WSL2 failure on my AMD machine, but the SMB problem is showing up on both AMD and Intel based systems.  Rolling back the update on my AMD machine does restore functionality of both WSL and SMB.

**Comment by Manta45** [comment] 2023-07-18 05:56
Good Morning, I have the same issue since 25905.1000.
This is my machine:
Gerätename	MM-Beast
Prozessor	AMD Ryzen 9 5900HX with Radeon Graphics           3.30 GHz
Installierter RAM	64,0 GB (63,4 GB verwendbar)
Geräte-ID	1BB7DD67-616F-423A-8392-21FFC9E00FCA
Produkt-ID	00331-20210-00000-AA847
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Please inform to my e-mail.
Thank you

**Comment by dunxuan** [comment] 2023-07-18 07:09
same AMD 25905

**Comment by Cr4z33** [comment] 2023-07-18 08:04
Devs is there any news on a fix for this please? 🥲

**Comment by Koonarm** [comment] 2023-07-18 08:34
same here , I'm using AMD ryzen 7 5800H window version 25905.1000 . Also already try to restart all service several times. nothing work tho

**Comment by bsylvain** [comment] 2023-07-18 09:17
Same error with a AMD Ryzen 5900X and the build 25905.1000

**Comment by Cr4z33** [comment] 2023-07-18 10:14
WSA is screwed too so I guess it's definitely something caused by latest Windows 11 Inside build!

Btw I've got a Ryzen (5900X) too.

**Comment by Koonarm** [comment] 2023-07-18 10:23
Which update should wait for windows update or WSL update?🤔

**Comment by fx006** [comment] 2023-07-18 17:01
Same error with AMD CPU and the windows version build 25905.1000.   I wonder  when the bug will be fixed?

**Comment by mengyufeng** [comment] 2023-07-19 02:29
需要尽快修复，影响太多了，hyper-v、wsa、wsl、sanbox 等，hyper-v 虚拟机如果在升级25905之前是保存状态，非关机状态时可以正常启动的，但是如果时关机状态就无法启动

**Comment by GPMrks** [comment] 2023-07-19 03:18
Same here. I also rolled back to previous build while I wait for the bug to be fixed.

**Comment by lishmael** [comment] 2023-07-20 10:00
Same here, AMD Ryzen CPU, build 25905.1000. Any workarounds yet?

**Comment by ByronCoet** [comment] 2023-07-22 08:46
same Error code: Wsl/Service/CreateInstance/CreateVm/E_INVALIDARG
any update

**Comment by akhil-rana** [comment] 2023-07-22 16:20
Same issue.
AMD Ryzen 5900x CPU
build 25905.1000

**Comment by paulomanrique** [comment] 2023-07-23 07:38
Looks like an error with Windows itself, not WSL. I use an Android emulator called "Memu"  that's also broken with the current insider build. Rolling back solved the issue.

**Comment by rocwon** [comment] 2023-07-23 17:06
Same issue.
Windows 11 Insider Preview 25905.1000

**Comment by wangzishi** [comment] 2023-07-24 09:19
AMD Ryzen 9 7845HX
build 25905.1000

**Comment by chemistryle2020** [comment] 2023-07-24 13:00
I have the same error.
AMD Ryzen 7 6800H
Windows Feature Experience Pack 1000.25905.1000.0

**Closed** 2023-07-25 21:33 UTC

**Comment by ql11** [comment] 2023-07-27 10:14
same issue

**Comment by wolfyang888** [comment] 2023-10-28 03:05
same issue
