### ISSUE TITLE
wsl2 occur socket hang up

### ISSUE THREAD

**Issue by Sslishy** [microsoft/WSL#10375] opened 2023-08-09 00:44 UTC
### Windows Version

windows [10.0.22621.1992]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

ubuntu 20.04

### Other Software

my custom application

### Repro Steps

My program runs smoothly on Ubuntu 20.04 hosting, but I face a "socket hang up" error when using Windows WSL2.

### Expected Behavior

Please provide me with some methods to avoid this error. Thank you.

### Actual Behavior

error information :
{"ajaxError":true,"runResult":{"message":"socket hang up","name":"Error","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/1.4.0","Content-Length":"865","Accept-Encoding":"gzip, compress, deflate, br"},"method":"post","url":"http://127.0.0.1:7000/api/findShapeModelRun/find","data":"{\"modelName\":\"model\",\"matchAlgorithm\":\"ShapeMatch_BaseComponent\",\"minAngle\":-90,\"maxAngle\":90,\"minScaleExpected\":0.98,\"maxScaleExpected\":1.1,\"inputGraspPoints\":[{\"x\":957.5189583080876,\"y\":563.202925602756}],\"matchRegions\":[{\"regionKey\":\"Rectangle\",\"regionValue\":{\"angle\":4.02252107200553,\"width\":775.8415416590865,\"height\":85.99475188945063,\"centerX\":947.8004161363874,\"centerY\":563.7661457783995}}],\"searchRegions\":[],\"sourceId\":\"03b7a527302beab5/beab3ab282840d93\",\"nodeId\":\"03b7a527302beab5/7e39c6ec36bca235\",\"minResultNum\":1,\"minScore\":0.2,\"httpAgent\":{\"_events\":{},\"_eventsCount\":2,\"defaultPort\":80,\"protocol\":\"http:\",\"options\":{\"keepAlive\":true,\"noDelay\":true,\"path\":null},\"requests\":{},\"sockets\":{},\"freeSockets\":{},\"keepAliveMsecs\":1000,\"keepAlive\":true,\"maxSockets\":null,\"maxFreeSockets\":256,\"scheduling\":\"lifo\",\"maxTotalSockets\":null,\"totalSocketCount\":0}}"},"code":"ECONNRESET","status":null},"continueShootTag":true,"_msgid":"35b3662eb68750f2"}

**Comment by OneBlue** [comment] 2023-08-22 21:57
Closing since there isn't enough information to root cause the issue.

**Closed by OneBlue** 2023-08-22 21:57 UTC
