### ISSUE TITLE
How to run ZSH automatically on Bash startup

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/WSL#1724] opened 2017-02-24 21:30 UTC
I use Windows 10 Build 14393.693

I install `zsh`

```
sudo apt-get install zsh
```

and `oh-my-zsh` using

```
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
```

And now if I run `Bash on Ubuntu on Windows` and enter `zsh` command this work fine.

Now I need to start `zsh` as "default" bash. For that I execute following command:

```
chsh -s /bin/zsh
```

or

```
chsh -s /usr/bin/zsh
```

but after restart terminal nothing happens. I see default bash.

I need this because now I have to use three commands to run zsh and it's uncomfortable:

1) Run Hyper Terminal
2) Run Bash
3) Run ZSH

![23jolkjsa](https://cloud.githubusercontent.com/assets/20873402/23321898/505117d2-fa96-11e6-8e30-3ff26bd12c8e.png)

**Comment by benhillis** [comment] 2017-02-24 21:42
Looks like #477.

**Comment by Zx-EvM** [comment] 2017-02-24 21:50
@benhillis thanks. I try to write `bash -c zsh` to `.bashrc` file in `/home/user` directory and now on bash start have error message

```
bash: /home/user/.bashrc: Input/output error
```

and also I try to write just `/bin/zsh` instead of `bash -c zsh` but have this error too.

Screen:

![screenshot 114](https://cloud.githubusercontent.com/assets/20873402/23322312/25613280-fa98-11e6-8948-2b3957cdbb03.png)

**Comment by benhillis** [comment] 2017-02-24 21:53
Did you add that line from a Windows editor?

**Comment by Zx-EvM** [comment] 2017-02-24 21:54
@benhillis not. from Sublime Text 3. I must use the Windows Notepad for that?

**Comment by benhillis** [comment] 2017-02-24 21:56
You should not edit anything under %localappdata%\lxss from a Windows editor at all.

**Comment by Zx-EvM** [comment] 2017-02-24 21:57
@benhillis oh. Vim?

**Comment by benhillis** [comment] 2017-02-24 21:58
Yes, any editor as long as it's coming from a WSL process.

**Comment by Zx-EvM** [comment] 2017-02-24 22:03
Now I need to reinstall `Bash on Ubuntu on Windows` because `~/.bashrc` file now found through shell :(

![screenshot 115](https://cloud.githubusercontent.com/assets/20873402/23322664/d857ace2-fa99-11e6-8043-68cdb46720f5.png)

Or, maybe, it can be fixed?

**Comment by benhillis** [comment] 2017-02-24 22:05
If you copy the /root/.bashrc (from within bash) to your home directory that should fix it.

**Comment by Zx-EvM** [comment] 2017-02-24 22:13
@benhillis thanks Ben Hillis :) It's helped for me. But I copy that file with Ctrl+C and Ctrl+V and also works fine!

There is a reason for which the "default" `chsh -s /bin/zsh` does not work?

**Comment by benhillis** [comment] 2017-02-24 22:14
Yep, we don't run the login process which is the binary that normally sets up the default shell.  We're looking at changing this in the future.

**Comment by thenitai** [comment] 2017-02-27 21:32
Just add this line on top of the .bashrc:

```
if test -t 1; then
# ...start zsh
exec zsh
fi
```

and it will switch to ZSH whenever you start the WSL. Note: the disk performance is quite poor with the WSL (15042 here) so it will take a few seconds to switch (also depends if you use plugins, zen, etc.)

**Comment by mabdelfattah** [comment] 2017-03-06 07:25
I've a side question, what is the tool you are using for terminal? as your terminal colors and fonts look really neat!

**Comment by Zx-EvM** [comment] 2017-03-06 08:49
@mabdelfattah you can read this article: [How to Install Zsh and Oh My Zsh on Windows 10](https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html)

**Comment by StalkAlex** [comment] 2017-04-17 06:42
@thenitai  advies is helpful, thank you. But one small problem still exists.  
![default](https://cloud.githubusercontent.com/assets/2943154/25081272/cc634116-2362-11e7-86be-1d5b7d4011ea.PNG)
It shows that awfull square symbol instead of user name, how this could be fixed?

**Comment by thenitai** [comment] 2017-04-17 23:01
@StalkAlex You need to install fonts and all:

```
sudo pip install powerline-status
cd "$HOME"
mkdir -p .fonts
mkdir -p .config/fontconfig/conf.d
wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf 
wget https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf .fonts/
fc-cache -vf
mv 10-powerline-symbols.conf .config/fontconfig/conf.d/
```

You need to install python and python-pip for the above to work!

**Comment by StalkAlex** [comment] 2017-04-18 05:25
@thenitai and also fontconfig, just copy-pasted all those commands, then reopened bash and it still shows that square(

**Comment by mxtopher** [comment] 2017-04-19 05:44
@StalkAlex you may want to install the font *Menlo for Powerline* as described here:
https://medium.com/@danielgodigna/how-to-install-zsh-oh-my-zsh-and-themes-in-ubuntu-on-windows-933489b6d6e0

It will solve the square character issue.

**Comment by StalkAlex** [comment] 2017-04-19 06:39
@mxtopher thanks,  I found solution already.  I've been using ConEmu console wirh Solarized theme for windows, added all powerline fonts and installed powerline-status on BOW as @thenitai  instructed. Now it looks really elegant :)

**Comment by aaronpowell** [comment] 2017-11-12 10:02
Rather than creating a new issue I'll add my 2c here.

If you launch `bash.exe` from `C:\Windows\sysnative\bash.exe` rather than the name of an installed distro (eg: `Ubuntu.exe` from `C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\ubuntu.exe`) the shell specified in `/etc/passwd` isn't honored when the distro launches.

You can work around it with adding `-c <shell name>`, such as `bash.exe -c fish`, but I'd expect it to honor the specified shell.

**Comment by KoldFuzion** [comment] 2018-02-14 21:50
Along with everything above, to get my terminal to open to zsh, I had to go to

Terminal > Preferences > General

Then change the "Shells open with:" option to: Default login shell
<img width="717" alt="screen shot 2018-02-14 at 1 48 56 pm" src="https://user-images.githubusercontent.com/8559810/36230058-152f30ac-118e-11e8-8efc-16273dbd6ad4.png">

**Comment by therealkenc** [comment] 2018-02-14 22:30
This one was actually dupe #477 way up top but was never marked as such. Work-around was to exec zsh inside .bashrc, or launch it by whatever creative means you like. These days just wsl.exe will respect the default shell.

**Closed by therealkenc** 2018-02-14 22:30 UTC
Labels: duplicate

**Comment by bcawrse** [comment] 2018-04-10 16:02
If anyone else comes to this thread with issues and don't want to edit config files I got away with `chsh -s $(which zsh)` in Ubuntu under Windows AWS. Worked just fine. chsh is a change shell utility.

**Comment by aborruso** [comment] 2018-06-06 16:52
I have set

```
if test -t 1; then
exec zsh
fi
```

in my `~/.bashrc` file, but I neew always to run `zsh` to have zsh. How to solve this?

Thank you

**Comment by benhillis** [comment] 2018-06-06 16:57
@aborruso - As @bcawrse mentiones, you can use chsh to change your default shell and WSL will respect this value.

https://linux.die.net/man/1/chsh

**Comment by aborruso** [comment] 2018-06-06 17:00
@benhillis I have tried, but it remains the same :(

**Comment by aborruso** [comment] 2018-06-06 17:06
Usually in two ways:

- clicking on the icon;
- running `bash` in explorer path

![immagine](https://user-images.githubusercontent.com/30607/41053714-9e10a4ec-69bc-11e8-93ad-11abcdbe3922.png)

Thank you

**Comment by benhillis** [comment] 2018-06-06 17:30
@aborruso - Both of those methods will always launch /bin/bash (by design).  It would be strange if running "bash" ran something other than /bin/bash, don't you agree?

I'd suggest moving to a new store-based distro and switching to use wsl.exe (which will respect your default shell).

**Comment by aborruso** [comment] 2018-06-06 17:37
@benhillis thank you.

But for me not works in bashrc file:

```
# Switch to ZSH shell
if test -t 1; then
exec zsh
fi
```

And this should work when I run /bin/bash. Am I wrong?

**Comment by bcawrse** [comment] 2018-06-11 14:42
@aborruso, I added your snippet to the bottom of my .bashrc and it switches to zsh for me when I call `bash` from PowerShell. It also works when I call `bash` from a Windows cmd prompt.

What kind of error are you getting?

**Comment by aborruso** [comment] 2018-06-11 15:45
@bcawrse any error: I run bash, and there is not the switch to zsh.

**Comment by aborruso** [comment] 2018-06-11 16:58
@bcawrse any error: I run bash, and there is not the switch to zsh.

**Comment by bcawrse** [comment] 2018-06-12 13:41
@aborruso, try throwing an `echo` in your .bashrc? If that's not firing either then it's a problem with your .bashrc file not being read and not a problem with the exec swapping your shell.

**Comment by aborruso** [comment] 2018-06-12 15:06
@bcawrse  I have deleted my .bashrc and create a new empty one with touch.

I have added only `echo "test"`, but when I run a new bash session I have no echo output :(

Thank you

**Comment by bcawrse** [comment] 2018-06-12 18:27
@aborruso, I believe this other issue may be helpful.
https://github.com/Microsoft/WSL/issues/2067

**Comment by CuriousCat-7** [comment] 2020-01-21 03:15
> @benhillis thank you.
> 
> But for me not works in bashrc file:
> 
> ```
> # Switch to ZSH shell
> if test -t 1; then
> exec zsh
> fi
> ```
> 
> And this should work when I run /bin/bash. Am I wrong?

This is a dangerous move if you use `exec zsh`!  If your zsh is broken, you cannot login to the terminal. I suggest use, just:
```
# Switch to ZSH shell
if test -t 1; then
zsh
fi
```

**Comment by bcawrse** [comment] 2020-01-23 02:11
I guess that's a good point, I haven't dealt with a broken zsh in WSL yet. 

Running `zsh` instead of `exec zsh` will run zsh inside bash though right? Instead of just running zsh? 

I did a quick google because I like your point that it's not good to get stuck with a broken shell, and apparently you can override the profile loading by running bash from powershell directly.

Testing it, I ran `bash` from PowerShell and `echo $SHELL` returned 'usr/bin/zsh' but `echo $0` returned '/bin/bash'; learned something new, I didn't know `$0` was the current shell since I've always used `$SHELL`!

So I'm still inclined to prefer `exec zsh` over `zsh` since it replaces the running process, instead of running a shell in a shell, and there's still a way to get to bash if your zsh is faulty.

[Reference link for starting bash from powershell](https://devblogs.microsoft.com/commandline/a-guide-to-invoking-wsl/)

**Comment by celado** [comment] 2021-07-26 20:58
If problem in nvm, you are using wsl and zsh this might help. Write it in ~/.zshrc to top. 👍 

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

**Comment by floki-dev** [comment] 2021-07-26 20:59
If problem in nvm, you are using wsl and zsh this might help. Write it in ~/.zshrc to top. 👍

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion

**Comment by januwA** [comment] 2021-09-29 07:53
chsh works for me

```sh
# dnf search util-linux-user
# chsh -s /bin/zsh
```
