### ISSUE TITLE
There are no more endpoints available from the endpoint mapper

### ISSUE THREAD

**Issue by byhc2** [microsoft/WSL#4403] opened 2019-08-12 15:28 UTC
Command line fail when I try to upgrade to wsl2.

* Windows build number:  10.0.18956.1000

* What you're doing and what's happening:  
wsl --set-version Arch 2

* What's wrong / what should be happening instead:
There are no more endpoints available from the endpoint mapper

NOTE: The arch is from https://github.com/yuk7/ArchWSL And I think the failure is about the ICS service with my computer. The service was disabled by the admin and I can't start it.

If this issue is due to ICS, is there another way to upgrade to wsl2 without starting ICS?

[lsxx.zip](https://github.com/microsoft/WSL/files/3493213/lsxx.zip)

**Comment by Drakota** [comment] 2019-08-12 15:39
The distribution you're using is not compatible with version 2 of WSL.
Check this issue [#89](https://github.com/yuk7/ArchWSL/issues/89).

**Comment by Biswa96** [comment] 2019-08-12 16:55
There is no "compatibility" criteria for WSL2. If you have a simple she'll and it's dependent libraries (libc) you can run it also. Think WSL as a chroot.

**Comment by Biswa96** [comment] 2019-08-12 16:59
There is no "compatibility" criteria for WSL2. If you have a simple she'll and it's dependent libraries (libc) you can run it also. Think WSL as a chroot.

I've tried many Linux distributions. I have a method to use Arch Linux. Try this https://github.com/Biswa96/WSLInstall/blob/master/docs/Install_Distributions.md.

**Comment by Biswa96** [comment] 2019-08-12 17:00
There is no "compatibility" criteria for WSL2. If you have a simple shell and it's dependent libraries (libc) you can run it also. Think WSL as a chroot.

I've tried many Linux distributions. I have a method to use Arch Linux. Try this https://github.com/Biswa96/WSLInstall/blob/master/docs/Install_Distributions.md.

**Comment by byhc2** [comment] 2019-08-13 15:06
> The distribution you're using is not compatible with version 2 of WSL or atleast has issues discussed in the thread.
> Check this issue [#89](https://github.com/yuk7/ArchWSL/issues/89).

I have tried debian from the store. As long as I choose to install as version 2, it fails.

**Comment by byhc2** [comment] 2019-08-13 15:08
> There is no "compatibility" criteria for WSL2. If you have a simple shell and it's dependent libraries (libc) you can run it also. Think WSL as a chroot.
> 
> I've tried many Linux distributions. I have a method to use Arch Linux. Try this https://github.com/Biswa96/WSLInstall/blob/master/docs/Install_Distributions.md.

If I install the linux as wsl1, everything goes OK. The problem occurs when I try to set the distribution as version 2.

**Comment by Gu0Yu** [comment] 2019-08-22 02:41
Hello, I have encountered this problem. Can you solve it?

**Comment by gordonliang** [comment] 2019-08-23 06:17
I have the same problem when I run "wsl --set-version Ubuntu 2", anyone have any idea to solve it?

**Comment by HZ89** [comment] 2019-09-26 09:06
In my windows evaluation copy build 18980.vb_release.190907-1301 also have this problem, how can i fix it?

``` powershell
PS C:\WINDOWS\system32> wsl -l --all -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Running         1
PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
There are no more endpoints available from the endpoint mapper.
PS C:\WINDOWS\system32>
```

**Comment by craigloewen-msft** [comment] 2019-09-26 17:24
@HZ89 can you send us networking logs for the problem? There are instructions on how to collect them [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs).

**Comment by HZ89** [comment] 2019-09-27 09:20
> @HZ89 can you send us networking logs for the problem? There are instructions on how to collect them [here](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#9-networking-logs).

ok, already submitted

**Comment by benhillis** [comment] 2019-09-27 14:36
@hz89 do you have a link handy?

**Comment by mcwilbur** [comment] 2019-12-14 19:20
I got the same issue while upgrading Ubuntu to WSL2.
Console output : 
```
PS C:\Users\Jonathan> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2\n
There are no more endpoints available from the endpoint mapper.
```

I recorded the issue and submitted it to the Feedback Hub under https://aka.ms/AA6tptp

**Comment by okhowang** [comment] 2019-12-16 11:44
my group disable ics service for security reason,
can wsl 2 do not depend ics service?

**Comment by krwu** [comment] 2020-03-13 05:01
> my group disable ics service for security reason,
> can wsl 2 do not depend ics service?

I'm in the same situation. Will WSL 2 work without ICS in the future?

**Comment by kashan91** [comment] 2020-04-28 19:55
I don't think ICS has anything to do with it. I have it ON and still have the same issue. Any suggestions

**Comment by jcimoch** [comment] 2020-07-10 20:29
I have the same issue, any update on this?

**Comment by jcimoch** [comment] 2020-07-11 09:15
https://aka.ms/AA8y16o

**Comment by jcimoch** [comment] 2020-07-11 11:07
![obraz](https://user-images.githubusercontent.com/5717461/87222810-746c4a80-c377-11ea-8b4d-175f5d2a3c0d.png)

**Comment by Daltz333** [comment] 2020-07-16 22:49
I also have this issue.

**Comment by LOuroboros** [comment] 2020-09-21 02:11
> 
> 
> Command line fail when I try to upgrade to wsl2.
> 
>     * Windows build number:  10.0.18956.1000
> 
>     * What you're doing and what's happening:
>       wsl --set-version Arch 2
> 
>     * What's wrong / what should be happening instead:
>       There are no more endpoints available from the endpoint mapper
> 
> 
> NOTE: The arch is from https://github.com/yuk7/ArchWSL And I think the failure is about the ICS service with my computer. The service was disabled by the admin and I can't start it.
> 
> If this issue is due to ICS, is there another way to upgrade to wsl2 without starting ICS?
> 
> [lsxx.zip](https://github.com/microsoft/WSL/files/3493213/lsxx.zip)

I don't think ICS is causing this problem. I'm also getting the exact same issue *("There are no more endpoints available from the endpoint mapper")*, but enabling and starting that service, reopening CMD and using `wsl --set-version <distro> 2
` didn't solve it on my end.

**Comment by gurnec** [comment] 2020-09-23 21:02
> I disabled WSL and the Virtual Machine Platform, restarted my PC, enabled them again, restarted yet again, ... I got the exact same error.

@LOuroboros FWIW, I also have Hyper-V installed, and although the above did not work for me, removing those two along with all other Hyper-V components, rebooting and reinstalling, *did* work for me. (I only needed to reinstall the components, not the Ubuntu instance/store app.)

I'd guess this would include Guarded Host, Microsoft Defender Application Guard, Windows Hypervisor Platform, Windows Sandbox, and maybe Containers too, if any of them are installed.

Of course, **proceed at your own risk if you are actively using any of these features** lest you lose any config/VMs/containers.

<sub>also pinging @xiaods from the other issue in case it helps</sub>

**Comment by LOuroboros** [comment] 2020-12-18 19:32
I tried **[the process written at Microsoft Docs](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---update-to-wsl-2)** again, but sadly, the result hasn't changed in the past almost 3 months since my post above.
![Untitled2146](https://user-images.githubusercontent.com/4485172/102654017-a071d000-414e-11eb-8de5-2e9b3b0e7017.png)

**Comment by xiaods** [comment] 2021-02-03 05:57
I also have this issue.

**Comment by xiaods** [comment] 2021-02-07 00:51
I have the same issue, any update on this?

**Comment by VPraharsha03** [comment] 2021-04-09 06:57
@LOuroboros 

> I don't think ICS is causing this problem. I'm also getting the exact same issue

But in my case, this problem started after i deleted ICS along with this issue (https://github.com/microsoft/WSL/issues/5821)
Even restoring the service couldn't resolve the issue. I even re-installed WSL and VMP 

My DNS server is listening on port 53, so to keep the ICS disabled i tried deleting the triggers for HNS and this was the first time i'd encountered this and could resolve by restoring those triggers. Now the problem isn't being resolved.

**Comment by slaadvak** [comment] 2021-05-04 12:53
I also have this issue. Windows 1903 with Ubuntu 20.04.

**Comment by therealkenc** [comment] 2021-05-05 18:25
Anyone still experiencing this problem please post the output of `cmd.exe /c ver`. It is unclear if this was #5821, which is better in 20231+.

**Comment by benhillis** [comment] 2021-05-05 18:33
Agreed, I haven't seen this error anymore. I think something was fixed in the networking stack.

**Comment by RobRoseKnows** [comment] 2021-06-02 01:16
I'm getting this on a previous working WSL2 instance once my machine updated to insider build 21387. I was previously having network issues with that build, but unplugging and replugging my wifi dongle seemed to fix them. I'm wondering if that's related?

**Comment by cjatoba** [comment] 2021-07-10 01:55
For me it works again when enabling Windows Defender Firewall on Windows services

**Comment by LOuroboros** [comment] 2021-08-12 15:18
After about a year since I first installed Windows 10, I decided to format my PC today.
Miraculously, I got WSL2 working normally after following the steps written in the article at Microsoft Docs.
![cmd_413](https://user-images.githubusercontent.com/4485172/129222761-c789383b-7245-4f77-9f18-60b3c31d45f3.png)

**Comment by LOuroboros** [comment] 2022-11-22 15:47
> @LOuroboros Which steps did you followed? can you paste the link here? Thanks!

https://learn.microsoft.com/en-us/windows/wsl/install-manual

**Comment by theoparis** [comment] 2023-12-27 02:13
> > @LOuroboros Which steps did you followed? can you paste the link here? Thanks!
> 
> https://learn.microsoft.com/en-us/windows/wsl/install-manual

I am having the exact same error with windows 11 with those steps ;( 
Until WSL decides to work I have no other option but to use a Linux machine remotely

**Comment by eoffermann** [comment] 2024-02-21 06:28
After struggling with this off and on for months on different machines, I found that the following sequence seems to work for me:

```
wsl --set-default-version 1
wsl --install DISTRIBUTION
Enter userid and desired password when asked
Then in a new shell after that's done:
wsl --set-default-version 2
```

Basically, installs seem to fail frequently in wsl 2 but if you switch back to default version 1, install, then switch to version 2 it seems to work.

**Comment by OneBlue** [comment] 2024-05-14 21:23
This issue should be fixed on the latest Windows 10/11. Feel free to reopen if that's not the case though

**Closed by OneBlue** 2024-05-14 21:23 UTC
Labels: network

**Comment by theoparis** [comment] 2024-10-26 22:14
> > > [@LOuroboros](https://github.com/LOuroboros) Which steps did you followed? can you paste the link here? Thanks!
> > 
> > 
> > https://learn.microsoft.com/en-us/windows/wsl/install-manual
> 
> I am having the exact same error with windows 11 with those steps ;( Until WSL decides to work I have no other option but to use a Linux machine remotely

It turns out a [powershell script I ran to "debloat" windows had disabled the Windows Defender Firewall](https://privacy.sexy). I had to generate a new script to revert this option. I do wish the error message said that it needed the firewall service instead though.
