### ISSUE TITLE
Windows WSL interoperability doesn't work in Ubuntu 20.04 but works with Ubuntu 22.04 WSL developer daily release in the same machine

### ISSUE THREAD

**Issue by okibcn** [microsoft/WSL#8023] opened 2022-02-06 03:01 UTC
### Version

Microsoft Windows [Version 10.0.22543.1000]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.81.1

### Distro Version

Ubuntu-20.04

### Other Software

VSCode 1.64.0

### Repro Steps

1. Install Ubuntu 20.04 from MS Store
2. Install Windows Subsystem for Linux from MS Store
3. Open the distro in any way (using wsl command in powershell, or using the Windows Terminal)
4. launch VSCode from Ubuntu using the instruction
`code .bash`
5. close vscode
In a powershell terminal run `dir \\wsl.localhost\Ubuntu-20.04`

It takes a while to replicate the issue, but **for sure is related to the use of VSCode**.

### Expected Behavior

It should return the directory of the Ubuntu system rootfs 

### Actual Behavior

Powershell becomes irresponsive. It is impossible to cancel the command using Ctrl+C or Ctrl-Z

Same happens when trying to open it using explorer.exe or VSCode.

Sadly I am experiencing that issue quite often. After a number of opening and closing files using vscode from WSL, the interop between Windows and WSL fails. At this time the Ubuntu 20.04 distro, installed from Microsoft Store, can't be accessed from Windows. However, WSL can access /mnt/c/ mount point without issue.

I also have the latest daily distro of Ubuntu 22.04 for WSL. And for my surprise, I don't have any problem with this distro. 
At this time, from Windows PowerShell I can do:

`ls \\wsl.localhost\Ubuntu-22.04\`

But powershell hangs when doing this:

`ls \\wsl.localhost\Ubuntu-20.04\`

Same behavior happens when trying to access those locations with explorer.exe

`wsl --shutdown` doesn't fix the issue. 
IP works perfectly, as I can create a webserver from WSL and access it from windows.

**Comment by benhillis** [comment] 2022-02-08 22:18
@OneBlue - this is probably another repro of what you are debugging.

**Comment by OneBlue** [comment] 2022-04-12 21:47
Most likely a duplicate of #7883, closing.

**Closed by OneBlue** 2022-04-12 21:47 UTC
