### ISSUE TITLE
Windows crash while restarting LxssManager in OS Build 20161.1000

### ISSUE THREAD

**Issue by mszhanyi** [microsoft/WSL#5585] opened 2020-07-14 10:39 UTC
# Environment

```none
Windows build number: Version 2004 (OS Build 20161.1000) [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: Ubuntu 18.04 [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce
2 Geforce in windows 10
Nvidia driver is installed
restarting LxssManager with WSL2 window is open.
Windows crash

#  Expected behavior

# Actual behavior

**Comment by therealkenc** [comment] 2020-07-14 15:35
Cannot reproduce here

![image](https://user-images.githubusercontent.com/7049700/87445506-fd1ffc00-c5ac-11ea-9234-e5060f4ebd4c.png)

**Comment by benhillis** [comment] 2020-07-14 16:37
@mszhanyi - Do you a memory dump?  I see you're a MS employee, ping me via Teams and I can take a look at the crash dump.  Thanks!

**Comment by benhillis** [comment] 2020-07-14 18:24
Root caused this to a hypervisor bugcheck, unrelated to WSL.  Fix is inbound to Windows Insider Fast.

**Closed by benhillis** 2020-07-14 18:25 UTC
Labels: external, fixinbound, need-repro
