### ISSUE TITLE
WSL doesn't works

### ISSUE THREAD

**Issue by r00ster91** [Microsoft/WSL#3296] opened 2018-06-13 14:19 UTC
It just happens over and over. Yesterday the WSL worked and now the WSL is broken again for some reason. Even if I didn't changed anything.
![grafik](https://user-images.githubusercontent.com/35064754/41356899-3162ae4e-6f25-11e8-9f32-3181ba0bab79.png)
And everytime I disable the WSL feature and enable it again and reinstall Ubuntu distribution then it works again. But then the next day it's broken again.

**Comment by realternate** [comment] 2018-06-13 14:28
Just restart yout device. Then open again if your problem still happendw

**Comment by shoffmeister** [comment] 2018-06-13 14:33
The screenshot transformed to text says:

WslRegisterDistribution failed with error: 0x800703fa

Have a look at #2576 - you seem to be seeing that.

**Comment by benhillis** [comment] 2018-06-13 16:20
Yep this is a duplicate of #2576.  Fix is making its way to insider builds.

**Closed by benhillis** 2018-06-13 16:20 UTC
