### ISSUE TITLE
git clone https://github.com/benqzq/ulcwe.git cd ulcwe sudo apt install dos2unix dos2unix install.sh git commit -a -m "change line endings to unix-style" git push```

### ISSUE THREAD

**Issue by almeidathomas92** [microsoft/WSL#11202] opened 2024-02-24 04:22 UTC
```
git clone https://github.com/benqzq/ulcwe.git
cd ulcwe
sudo apt install dos2unix
dos2unix install.sh
git commit -a -m "change line endings to unix-style"
git push
```

_Originally posted by @benhillis in https://github.com/microsoft/WSL/issues/2939#issuecomment-365345958_
            
```[tasklist]
### Tasks
```

**Comment by OneBlue** [comment] 2024-02-26 19:53
Closing since this issue doesn't explain what the problem is

**Closed by OneBlue** 2024-02-26 19:53 UTC
