### ISSUE TITLE
Electron app cannot open after some successful attempts

### ISSUE THREAD

**Issue by willchao612** [microsoft/WSL#7321] opened 2021-08-18 03:50 UTC
### Windows Build Number

22000.132

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.10.43.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 20.04

### Other Software

Docker Desktop (Windows): Version 3.5.2
Microsoft Visual Studio Code - Insiders (Remote - WSL): Version 1.60.0

### Repro Steps

git clone https://github.com/stackacademytv/master-electron
cd master-electron
npm install
npm start (or npm run watch)

### Expected Behavior

Open electron app window directly

### Actual Behavior

Whenever I restart the computer, the electron app window appears as expected for the first few times. However, at some point, it just doesn't show up any more. I don't know whether it is caused by some GPU problems or WSL problems.

### Diagnostic Logs

> master-electron@1.0.0 watch /home/will/projects/electron
> nodemon --exec electron .

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `electron .`
NVD3D10: CPU cyclestats are disabled on client virtualization 
NVD3D10: CPU cyclestats are disabled on client virtualization 
NVD3D10: CPU cyclestats are disabled on client virtualization 
NVD3D10: CPU cyclestats are disabled on client virtualization

**Comment by craigloewen-msft** [comment] 2021-08-24 16:38
I installed the repo that you listed and tried running it around 10 times in a row. I wasn't able to reproduce this issue. Do you have any other repro steps here?

As well, could you please file this at the [WSLg repro](https://github.com/microsoft/wslg) repro and we can follow up there?

**Comment by willchao612** [comment] 2021-08-25 07:29
Thanks for the response.

Well it seems the last few lines of error are gone after I installed the `nvidia-340` apt package. The problem of electron app window not showing up is solved together with it.

Clearly now it is a GPU problem. Do I still need to file this at the other repo?

**Comment by craigloewen-msft** [comment] 2021-08-25 16:56
No I don't think so, thanks for filing it here!
It seems like the root cause here was a Linux binary based GPU issue. Since you're now in a working state, and I'm not able to reproduce this, I believe we can close the issue as there isn't anything actionable for this on the WSL team. Please let me know if you're still seeing this issue and would like me to reopen. Thank you!

**Closed by craigloewen-msft** 2021-08-25 16:56 UTC
