### ISSUE TITLE
Cannot Access WSL2 File System from Explorer at Startup [Build 20215]

### ISSUE THREAD

**Issue by dg520** [microsoft/WSL#5945] opened 2020-09-18 02:58 UTC
# Environment

```none
Windows build number: 10.0.20215.1000
Your Distribution version: 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL2
```

# Steps to reproduce

Every new startup of Windows 10 Build 20215 has this issue. 

#  Expected behavior

WSL2 file system should be automatically connected to Windows10 via 9p at startup. 

# Actual behavior

1. On a new startup of Windows 10 Build 20215: In the Explorer, the  Penquin icon is there with Ubuntu folder inside. But clicking on the folder shows folder not accessible.
2. In Windows Terminal, my Ubuntu terminal would start with `~` directory when under Windows Build 20201. But now it starts with /mnt/c/User/XXX in Windows Build 20215. I CAN `cd` into Ubuntu file system without problem though. 
3. Run `wsl --shutdown` and restart WSL2 in Powershell as admin solve the problem. Now Explorer can access the Ubuntu file system and Windows Terminal (Ubuntu Terminal actually) starts correctly with `~` correctly.
4. Restart Windows will reproduce this issue again. 

P.S.: My Ubuntu is on an independent internal disk other than Drive C:\. It has worked fine since Build 20150 until now. I did skip the builds after 20201 and before 20215.

**Comment by Comolli** [comment] 2020-09-18 14:04
same +1

**Comment by ulyssedu45** [comment] 2020-09-18 22:41
same +1

**Comment by jct808** [comment] 2020-09-18 23:34
same +1

**Comment by licanhua** [comment] 2020-09-19 03:06
Thank you to report it. I tried but I didn't reproduce the problem. Can you help to [collect wsl logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) by Feedback Hub?
When the problems happen, what's the output of `wsl -l -v`? If the distro is up and running, can you login to the distro and `dmesg |grep 9p`

When you click Ubuntu and other distro in File Explorer, and if distro is down, it brings up the distro automatically.  When folder is 'not accessible', most likely the distro is not up or 9p service is not up correctly.

@benhillis Do you know about  `~ is changed to /mnt/c/User/XXX`?

**Comment by dg520** [comment] 2020-09-19 03:39
Hi @licanhua ,

Thanks for you response. I've uploaded my screen record to Feedback Hub.
Here is the output for  `wsl -l -v`:
```
PS C:\WINDOWS\system32> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```
I can login to the distro via Windows Terminal and here is the output for `dmesg |grep 9p`:
```
(base) xxxx@DESKTOP-XXXXXXX:~$ dmesg | grep 9p
[    0.942551] 9p: Installing v9fs 9p2000 file system support
[    0.942558] FS-Cache: Netfs '9p' registered for caching
[    0.985865] 9pnet: Installing 9P2000 support
[    1.616591] 9pnet_virtio: no channels available for device drvfs
[    1.722666] 9pnet_virtio: no channels available for device drvfs
[    1.829245] 9pnet_virtio: no channels available for device drvfs
[    1.935976] 9pnet_virtio: no channels available for device drvfs
```
Any suggestions?

**Comment by licanhua** [comment] 2020-09-21 16:45
Add @SvenGroot

**Comment by B3Kay** [comment] 2020-09-22 11:39
```
PS C:\Users\benja> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2

```
Cannot start WSL either:

`The remote procedure call failed.`

**Comment by licanhua** [comment] 2020-09-22 16:46
@dg520 Your log is not enough for troubleshooting. `no channels available for device drvf` here means Linux has problem(or waiting for PCI ready) to mount windows file system like /mnt/c. But your problem is to access Linux file system.

@B3Kay If you are with Windows Insider build, you may hit #5907. Fix is on the way

**Comment by dg520** [comment] 2020-09-22 17:58
Hi @licanhua ,

Could you please let me know what I can do to provide more related logs? Do I need something like `dmesg |grep 9p` but run on the Powershell side?

Best,
Dadi

**Comment by licanhua** [comment] 2020-09-22 18:04
[collect wsl logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) by Feedback Hub and then share the feedback hub link.

**Comment by dg520** [comment] 2020-09-22 18:24
@licanhua Here is my feedback hub [link](https://aka.ms/AA9q32m)

**Comment by licanhua** [comment] 2020-09-22 22:10
@dg520 Thanks to provide the log, but I didn't find the log related to WSL. I want to confirm with you if you were doing like this:
1. After your machine is up, start Feedback Hub, fill the information, and 'start recording'
2. Open File Explorer to reproduce the problem
3. Run 'wsl -l -v' to check the status
4. stop recording and finish send out feedback.

**Comment by dg520** [comment] 2020-09-22 22:55
@licanhua , I tried your instruction again. Does this [link](https://aka.ms/AA9q9lj) contain the log now?

**Comment by licanhua** [comment] 2020-09-23 02:56
@dg520 this log is valid. thanks. I will follow up with this if there is update.

**Comment by xds95** [comment] 2020-09-23 03:03
Duplicate of #5902

**Comment by dg520** [comment] 2020-09-23 03:53
@xds95 I think this is different than [#5902](https://github.com/microsoft/WSL/issues/5902). WSL2 is running in my case and can be used in via terminal. It is just not accessible in explorer on a new Windows start.

**Comment by licanhua** [comment] 2020-09-23 21:31
I think it's a different issue too?
@dg520 From the log, it's related to user's token. Have you disabled UAC? You can see the settings from `Change User Account Control settings`
What's your logon account, built-in administrator account, or a non-administrator account?

**Comment by dg520** [comment] 2020-09-23 21:54
@licanhua Thanks for the insight. My UAC is left as default (`Notify me only apps try to make changes to my computer (default)`). My logon account is the built-in administrator account, with my Microsoft account logged at the same time.

**Comment by christmas-fr** [comment] 2020-09-27 05:36
> ```
> PS C:\Users\benja> wsl -l -v
>   NAME      STATE           VERSION
> * Ubuntu    Stopped         2
> ```
> 
> Cannot start WSL either:
> 
> `The remote procedure call failed.`

Same Build 20221, since 20211 ...

**Comment by licanhua** [comment] 2020-09-28 04:52
`remote procedure call failed` is related to #5902. The fix is on the way, and please check that issue for update

**Comment by dg520** [comment] 2020-10-15 14:55
@licanhua I seems found and partially fixed the issue of my case. 

I have a ps1 script to automatically start WSL2 and its services, run by Windows Task Scheduler. The script looks like:
```
###############################################################
#Start Ubuntu Services, mimic systemd in a real Ubuntu machine
###############################################################
iex "wsl -u root sudo rstudio-server start";
iex "wsl -u root sudo service nginx start";
iex "wsl -u root sudo service ssh start";

###############################################################
#Forward WSL2 ports to Windows ports
###############################################################
$remoteport = bash.exe -c "ifconfig eth0 | grep 'inet '"
$found = $remoteport -match '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}';

if( $found ){
  $remoteport = $matches[0];
} else{
  echo "The 'wsl-port-forwarding' script exited, the ip address of WSL 2 cannot be found";
  exit;
}

#All the ports you want to forward
$ports=@(8762,8772);

#[Static ip]
#You can change the addr to your ip config to listen to a specific address
$addr='0.0.0.0';
$ports_a = $ports -join ",";

for( $i = 0; $i -lt $ports.length; $i++ ){
  $port = $ports[$i];
  iex "netsh interface portproxy delete v4tov4 listenport=$port listenaddress=$addr";
  iex "netsh interface portproxy add v4tov4 listenport=$port listenaddress=$addr connectport=$port connectaddress=$remoteport";
}
```
And I set this scheduler task as `Run whether user is logged on or not`. This used to work fine before Windows Build 20215, meaning 1) WSL2 would start; 2) the WSL2 service would be activated, 3) the ports would be forwarded; and 4) Windows explorer can visit WSL2 system.     

Since Build 20215, 1), 2) and 3) still works but 4) does not work. I've tried with and without `Run with highest privileges` selected.    

The workaround I've found is to change `Run whether user is logged on or not` to `Run only when user is logged on`. Then Windows will be able to visit WSL2 without a permission error.     

Is there a way to make this work at system startup without logged on?

**Comment by Oyami-Srk** [comment] 2021-08-29 19:52
Start WSL service without user login is really a key feature and many of users required for that. Hope that WSL team could managed to implement that.

**Comment by badbod** [comment] 2021-09-28 02:56
After reboot, opening a linux terminal from windows terminal gives cannot access \\wsl$\... error (home folders set to \\wsl$:\home\xxxx or wls$:\root)

running wsl -- any parameter at all, just any other wsl action other than trying to start a wsl terminal,  in PS and now wsl:// becomes available and linux terminals open fine.  once linux terminals are opened /mnt/c etc are available, so seems the linux side P9Service is all good.

was fine before windows 11 upgrade.
I notice in windows 11 the P9RdrService_xxxx  is set to Manual (trigger), start the service and wsl$: appears, linux terminals open fine.

Time for a quick reg hack,,

Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\P9Rdr
Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\P9RdrService
Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\xP9RdrService_xxxx

change Start value from  3 (manual/trigger) to 2 (auto/trigger)

just changing the user specific (P9RdrService_xxxx) Start value saw the value reverting on reboot. Did not test if you need to change all 3, probably just one of the others would have set the other two on reboot? Hey.. can't spend all day on this.

now wsl$:\ file system is available immediately after boot and linux terminals open from windows terminal without having to manually run a wsl command to trigger the P9Service .

only tried a couple of reboots, so far so good, so I will have to report back if it does revert at some point.

Regards
BaDboD

**Closed** 2024-02-01 12:15 UTC
Labels: file system
