### ISSUE TITLE
cannot start wsl 1&2 in win10 20221.1000

### ISSUE THREAD

**Issue by oska874** [microsoft/WSL#5980] opened 2020-09-24 07:20 UTC
I'm update to win10 20221.1000,but wsl cannot start, no matter wsl1 or wsl2.
Shows remote call fails.
![image](https://user-images.githubusercontent.com/4536559/94113400-6a87bd00-fe79-11ea-945a-958bd73a6efb.png)

**Comment by xiaoqidun** [comment] 2020-09-24 09:17
wsl has been broken for a long time

**Comment by 8549** [comment] 2020-09-24 10:51
+1, but my error message is `There are no more endpoints available from the endpoint mapper.` instead of remote procedure call fails.

**Comment by ZILosoft** [comment] 2020-09-24 11:48
any hotfix or any crutch for this?

**Comment by onomatopellan** [comment] 2020-09-24 11:55
Probably a duplicate of #5907
Your only option right now is rolling back to the Windows version you were before upgrading 
`Settings -> Update & Security -> Recovery`

Fix will be available within the next couple of weeks.

**Comment by ZILosoft** [comment] 2020-09-24 15:09
if i cant roll back?

**Comment by DonGuych** [comment] 2020-09-24 16:22
You're screwed, reinstall non insider build or wait for a fix...
It's kinda annoying that they broke WSL 2 **and** 1 ...

**Comment by noofaq** [comment] 2020-09-24 17:40
For those unfortunate who need CUDA support and have missed short opportunity to revert to 20206 (because they were for example out of the office during revert window) there is no solution - non-insider WSL2 works but without CUDA, insider WSL2 is a toast

**Comment by Fagbemi-Jeremiah** [comment] 2020-09-24 21:04
please check out [https://github.com/microsoft/WSL/issues/5973](https://github.com/microsoft/WSL/issues/5973)

**Comment by therealkenc** [comment] 2020-09-24 21:06
A screencap is problematic in this instance because it can't be pasted into a translator. Subscribe #5902. If your problem persists after that issue flips status to fixedininsiders, and you have the Windows update, please submit a new issue and please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) per the template.

**Closed by therealkenc** 2020-09-24 21:06 UTC
