### ISSUE TITLE
"usbipd wsl list" doesn't work and page pointed to doesn't help

### ISSUE THREAD

**Issue by jms19** [microsoft/WSL#11012] opened 2024-01-12 10:32 UTC
### Windows Version

10.0.19045.3930

### WSL Version

 0.2.1

### Are you using WSL 1 or WSL 2?

- [ ] WSL 2
- [X] WSL 1

### Kernel Version

4.4.0-19041-Microsoft

### Distro Version

Ubuntu 22

### Other Software

USBIPD-WIN.

### Repro Steps

Follow instructions at https://learn.microsoft.com/en-us/windows/wsl/connect-usb on a freshly installed Ubuntu 22 under WSL. Install USBIPD-WIN (and reboot) as instructed.

Type

`usbipd wsl list` in an administrative Power Shell.

says

`usbipd: error: The 'wsl' subcommand has been removed. Learn about the new syntax at https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device.` which is where we started give or take some minor URI differences.

### Expected Behavior

I expect a page linked from the output of a command to be more helpful.

### Actual Behavior

As above.

**Comment by elsaco** [comment] 2024-01-12 16:40
@jms19 one of the changes in the latest  `usbipd-win` release is  `The WSL commands have changed, see the README for the new syntax`. See more at https://github.com/dorssel/usbipd-win/blob/master/README.md Microsoft's documentation will take a while to update!

**Comment by OneBlue** [comment] 2024-01-16 22:22
Closing since the issue is related to [usbipd-win](https://github.com/dorssel/usbipd-win).

**Closed by OneBlue** 2024-01-16 22:22 UTC
