### ISSUE TITLE
Q: Identify distro from within distro, under WSL

### ISSUE THREAD

**Issue by cerebrate** [microsoft/WSL#4479] opened 2019-09-08 17:40 UTC
* Your Windows build number:  18970

Is there, or can there be, a supported way of identifying which distribution you are currently executing within? Referring, in this case, to distribution as it is used by `wsl.exe`; `lsb_release` will tell me that I'm running under, for example, Debian, but if I have two Debian installations under WSL, it won't tell me which one. I want to get the distro name as WSL knows it.

This would be useful for, for example, customizing build scripts and so forth, but also for identifying - when using the cross-distro mount feature - which filesystem under /mnt/wsl is the "local" one, and which the "remotes".

**Comment by Biswa96** [comment] 2019-09-08 17:53
I don't know if this is documented or not.

* Requred command: `echo $WSL_DISTRO_NAME`
* How to get it: `env | grep -i wsl`

**Comment by Biswa96** [comment] 2019-09-08 17:54
I don't know if this is documented or not.

* Required command: `echo $WSL_DISTRO_NAME`
* How to get it: `env | grep -i wsl`

**Comment by cerebrate** [comment] 2019-09-08 17:58
Ah, excellent. That'll be great, if we can rely on it sticking around.

**Comment by therealkenc** [comment] 2019-09-09 21:01
This is a dupe of some issue (or or some issue comment) far back but too lazy to find it. You can't depend on `lsb_release` to exist. It doesn't exist on Alpine for example.

In order to do a `systemd` solution from the outside you're looking at wrapping `wsl.exe` for a number of reasons. This is one of them. So, `genie.exe` sets the `$WSL_DISTRO_NAME` environment and spawns `wsl.exe --exec`. Or genie.py. Or a powershell script.

**Comment by cerebrate** [comment] 2019-09-09 22:33
Ah, different project, this one. I'm looking at tracking cross-distro mounts from outside the bottle in order to mirror them inside the bottle, and I'd rather not take an external dependency to do it.

**Comment by Biswa96** [comment] 2019-09-10 05:00
Then try this `echo $WSL2_CROSS_DISTRO`.

**Comment by cerebrate** [comment] 2019-09-10 05:09
I don't seem to have that variable.

**Comment by therealkenc** [comment] 2019-09-12 01:44
> This is a dupe of some issue (or or some issue comment) far back but too lazy to find it.

The other issue was (since closed) #2578 ([message](https://github.com/Microsoft/WSL/issues/2578#issuecomment-353856398)) fwiw.

**Closed** 2019-09-17 20:11 UTC

**Comment by andyneff** [comment] 2021-07-08 19:46
This is not a dupe of #2578, that issue "hard codes I'm in Ubuntu"? 

While `WSL_DISTRO_NAME` is the ideal solution, unfortunately this is set by windows somewhere outside of bash (`/init` is my guess), so when you run a command like `sudo` (one of many other real world examples), this environment variable gets lost. Often,  it's too late to choose to preserve this environment variable, so an alternative method is needed:

Running `wslpath -w /` will give you `\\wsl$\Ubuntu\`, for example

```bash
WSL_DISTRO_NAME="$(IFS='\'; x=($(wslpath -w /)); echo "${x[${#x[@]}-1]}")"
```

Starting in Windows 10 17063 (Dec, 2017), there has been a `wslpath` command.
Starting in Windows 10 18342 (Feb, 2019), Paths have been in `\\wsl$` format, meaning you don't have to do the registry lookup to determine the `DistributionName` given the `BasePath`

So both of these features appear to be in all "supported" versions of Windows 10 (except LTSC) today.

## Alternative

```
cd /
WSL_DISTRO_NAME=powershell.exe  -NoProfile -Command '($(Get-Location).Path -split "\\")[-1]'
```

**Comment by gusbemacbe** [comment] 2022-06-26 19:40
@Biswa96 and @therealkenc 

I tried this code but it doesn't work:

```sh
# Distribution name: Ubuntu
wsl_distro_name="docker-desktop"

# WSL command to find the distribution name
wsl_command="$(wsl.exe -l -v | grep -i '$wsl_distro_name' | awk '{print $2}')"

if [ -z "$wsl_command" ]; then
    echo "Distro not found"
else
    echo "Distro found: $wsl_distro_name"
fi
```

**Comment by fenjen** [comment] 2024-02-29 16:55
```bash
WSL_DISTRO_NAME=$(wslpath -m / | awk -F/ '{print $4}')
```

**Comment by spuaca** [comment] 2024-05-21 14:35
grep '^NAME=' /etc/os-release
