### ISSUE TITLE
wsl: Hyper-V firewall is not supported wsl: Mirrored networking mode is not supported, falling back to NAT networking

### ISSUE THREAD

**Issue by Morrigan-Ship** [microsoft/WSL#10495] opened 2023-09-19 12:15 UTC
### Windows Version

10.0.25931.1000

### WSL Version

2.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.123.1-1

### Distro Version

ubuntu 22 and kali linux

### Other Software

cmd

### Repro Steps

wsl - kali or ubuntu:

error:
wsl: Hyper-V firewall is not supported
wsl: Mirrored networking mode is not supported, falling back to NAT networking

### Expected Behavior

wsl - kali or ubuntu:

error:
wsl: Hyper-V firewall is not supported
wsl: Mirrored networking mode is not supported, falling back to NAT networking

but linux will start

### Actual Behavior

wsl - kali or ubuntu:

error:
wsl: Hyper-V firewall is not supported
wsl: Mirrored networking mode is not supported, falling back to NAT networking

but linux will start

**Comment by Morrigan-Ship** [comment] 2023-09-19 16:02
[WslLogs-2023-09-19_08-58-05.zip](https://github.com/microsoft/WSL/files/12664104/WslLogs-2023-09-19_08-58-05.zip)

**Comment by mlankamp** [comment] 2023-09-19 19:41
Have the same problem
[WslLogs-2023-09-19_21-38-24.zip](https://github.com/microsoft/WSL/files/12665832/WslLogs-2023-09-19_21-38-24.zip)

**Comment by mrdev023** [comment] 2023-09-19 19:45
[WslLogs-2023-09-19_21-43-45.zip](https://github.com/microsoft/WSL/files/12665864/WslLogs-2023-09-19_21-43-45.zip)
Same problem

**Comment by Morrigan-Ship** [comment] 2023-09-19 20:10
i think i know how we can fix it
but i cannot do it because important information
if anyone tested send the result
:

in first remove all linux distro then full remove wsl(dont remove wsl in first)
secend install wsl
install new distro
test with new network config and send result

**Comment by benhillis** [comment] 2023-09-19 21:17
@keith-horton - Could we adjust the error message so it's clear that the version of Windows they are running does not support the feature? It's currently a little confusing.

**Comment by Morrigan-Ship** [comment] 2023-09-19 21:57
@benhillis
i think its because some dll files not installed or registered

**Comment by sforman2861597** [comment] 2023-09-20 05:07
My win11 is dev, Build 23545 ,and have the same problem

**Comment by zhzy0077** [comment] 2023-09-20 05:53
My PC1 with dev channel version: 23550 shows this error
While My PC2 with release preview channel version 22621 doesn't show this error.

**Comment by peigongdsd** [comment] 2023-09-20 06:08
OS build 23545.1000 having this problem too.

**Comment by peigongdsd** [comment] 2023-09-20 06:09
> i think i know how we can fix it but i cannot do it because important information if anyone tested send the result :
> 
> in first remove all linux distro then full remove wsl(dont remove wsl in first) secend install wsl install new distro test with new network config and send result

No luck for me

**Comment by fasterthanlime** [comment] 2023-09-20 07:48
Same here, on OS build	22621.2283

[📦 WslLogs-2023-09-20_09-39-05.zip](https://github.com/microsoft/WSL/files/12670289/WslLogs-2023-09-20_09-39-05.zip)

**Comment by dotlineX** [comment] 2023-09-20 08:38
Having the same issue. Running Windows 11 22621.2283 Home. Could this be related to Home vs Pro versions of windows?

**Comment by AetherMagee** [comment] 2023-09-20 08:58
Same issue. Windows 11 Pro 22621.2283

> Having the same issue. Running Windows 11 22621.2283 Home. Could this be related to Home vs Pro versions of Windows?

I dont think so. Maybe it only works on Insider versions?

**Comment by LordMonoxide** [comment] 2023-09-20 13:32
> Same issue. Windows 11 Pro 22621.2283
> 
> > Having the same issue. Running Windows 11 22621.2283 Home. Could this be related to Home vs Pro versions of Windows?
> 
> I dont think so. Maybe it only works on Insider versions?

I'm on the latest dev channel insider build of Windows 11 and I'm getting the unsupported message for every feature in the blog post that was listed as "Insider Only"

**Comment by The-Monkey-King** [comment] 2023-09-20 15:55
From Craig's [video](https://www.youtube.com/watch?v=OB2Rfzy5V0Y), only autoProxy, autoMemoryReclaim, and sparseVHD can be accessed through Windows 11 22H2 now. You need insider's builds for the other networking. 

What I thought was suggested but not confirmed is that some of these features would be backported to Windows 10. Is this true or not?

**Comment by keith-horton** [comment] 2023-09-20 17:10
Sorry for the confusion.

Hyper-V Firewall and Mirrored networking support will soon be available on the latest Windows 11 release through a Windows Update. Until then, one must opt into Insider Builds - those build numbers will be in the range 255xx.

Opting into Windows Moments is different - those are feature updates to Windows 11, but those do not really go through the Windows Insider program. Those builds numbers will be in the range 235xx.

The traces I've seen so far are either from a Windows release that's not from the Windows Insiders, or the trace wasn't taken while WSL was attempted to be started.

If you have a 255xx build from Windows Insiders, I would be happy to look at the logs.
Features are enabled only when the required APIs are available :)


Thanks!

**Comment by keith-horton** [comment] 2023-09-20 17:22
Right - sorry about that. This would be in the Canary Channel.

**Comment by Morrigan-Ship** [comment] 2023-09-20 18:33
my self fixed issue :)
the reson of issue:
when you install new wsl version from github it need to remove old wslservice and recreate the service for this you should reboot your pc

but before reboot:
if you enter Get-NetFirewallHyperVPort command in powershell as Administrator user you will get invalid class error
you sould fix this issue i fixed by this link:

https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class

if you followed link and get error from "sc config winmgmt start= disabled" no problem ignore this error and continue
and remember to goto %windir%\System32\wbem\ folder and remove folder name repository or repository.001 or any name that have repository

now reboot your PC
wsl network mirrored problem fixed :)
also Get-NetFirewallHyperVPort problem fixed :) 👍

**Comment by Morrigan-Ship** [comment] 2023-09-20 18:33
test my solution if not fixed report it here

**Comment by Morrigan-Ship** [comment] 2023-09-20 18:52
but new problem issue:
if i enable vpn on windows wsl network will use windows vpn
but if enable proxy on windows you need to restart wsl to use proxy :// :|| :\\

**Comment by keith-horton** [comment] 2023-09-20 18:54
Sadly, the Proxy API to detect a proxy can take a while, especially when set in a connectoid like with some VPNs. In those cases we opted to not slow down WSL startup while we waited to see if a proxy was detected; but it does mean you have to restart the container that first time :(

Sorry about that. We tried to balance the best user experience.

**Comment by Morrigan-Ship** [comment] 2023-09-20 18:58
its very important for WSL Enterprise usage and should fix in future
Also i think you should add multi IP Address supporting for WSL in future
because all wsl distro have one IP Address now

**Comment by keith-horton** [comment] 2023-09-20 19:03
Mirrored does support multiple IP addresses, both IPv4 and IPv6.
NAT of course only has a single (NAT'd) address.

**Comment by Morrigan-Ship** [comment] 2023-09-20 19:09
no sir it not using multi IP Addresses for all distro,s
it just make wsl IP same as windows IP
for example in mirrored mode:
windows IP: 192.168.1.102
wsl IP will: 192.168.1.102
they are same

i tested now

**Comment by keith-horton** [comment] 2023-09-20 19:41
Right. Mirroring will mirror the IP addresses that are assigned on the Windows host to network devices created in WSL. In your case, you have one IPv4 address assigned in Windows, so we mirror that in WSL (to a network device that matches your Wi-Fi device).

If your Windows host has multiple addresses (on one or more network adapters), these will be mirrored into WSL.

**Comment by sforman2861597** [comment] 2023-09-21 05:06
> 我自己修复的问题:)问题：当您从 GitHub 安装新的 WSL 版本时，它需要删除旧的 WSLSERVICE 并为此重新创建服务，您应该重新启动您的 PC
> 
> 但在重新启动之前：如果您以管理员用户身份在PowerShell中输入命令，您将获得灵魂 修复了我通过此链接修复的此问题：`Get-NetFirewallHyperVPort``invalid class error`
> 
> https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class 记住将 “” 更改为 “” sc 到 sc.exe并以管理员身份运行`sc config winmgmt start= disabled``sc.exe config winmgmt start= disabled`
> 
> 如果您点击了链接并从“”中收到错误，则没问题，请忽略此错误并继续`sc.exe config winmgmt start= disabled`
> 
> 下一步：并记住转到文件夹并删除文件夹名称或任何具有存储库的名称`%windir%\System32\wbem\``repository``repository.001`
> 
> 现在重新启动您的PC WSL网络镜像问题已修复:)问题也已修复:)👍`Get-NetFirewallHyperVPort`

Doesn't seem to work, I reinstalled my wsl and it still shows “wsl: Hyper-V firewall is not supported wsl: Mirrored networking mode is not supported, falling back to NAT networking”
Windows 11 Pro , build 23545

**Comment by sforman2861597** [comment] 2023-09-21 05:07
> my self fixed issue :) the reson of issue: when you install new wsl version from github it need to remove old wslservice and recreate the service for this you should reboot your pc
> 
> but before reboot: if you enter `Get-NetFirewallHyperVPort` command in powershell as Administrator user you will get `invalid class error` you sould fix this issue i fixed by this link:
> 
> https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class remember change "`sc config winmgmt start= disabled`" to "`sc.exe config winmgmt start= disabled`" sc to sc.exe and run as Administrator
> 
> if you followed link and get error from "`sc.exe config winmgmt start= disabled`" no problem ignore this error and continue
> 
> next step: and remember to goto `%windir%\System32\wbem\` folder and remove folder name `repository` or `repository.001` or any name that have repository
> 
> now reboot your PC wsl network mirrored problem fixed :) also `Get-NetFirewallHyperVPort` problem fixed :) 👍

Doesn't seem to work, I reinstalled my wsl and it still shows “wsl: Hyper-V firewall is not supported wsl: Mirrored networking mode is not supported, falling back to NAT networking”😢
Windows 11 Pro , build 23545

**Comment by Morrigan-Ship** [comment] 2023-09-21 07:18
> Doesn't seem to work, I reinstalled my wsl and it still shows “wsl: Hyper-V firewall is not supported

dont reinstalled follow the link and restart your PC it will work

**Comment by sforman2861597** [comment] 2023-09-21 08:59
> > Doesn't seem to work, I reinstalled my wsl and it still shows “wsl: Hyper-V firewall is not supported
> 
> dont reinstalled follow the link and restart your PC it will work

My wsl still doesn't work properly😢😢, I ran
sc.exe config winmgmt start= disabled
net stop winmgmt

and deleted the folder "C:\Windows\System32\wbem\repository" and made sure there was no folder with "repository" in the name.

I then ran sc.exe config winmgmt start= auto
After restarting my computer, my wsl still shows "wsl: Hyper-V firewall is not supported wsl: Mirrored networking mode is not supported, falling back to NAT networking "

I even ended up running sfc and chkdsk and rebooting, still no luck!

**Comment by onomatopellan** [comment] 2023-09-21 14:26
@sforman2861597 Build 23545 is from the Dev Channel and it doesn't work. I had to upgrade to Canary Channel and got build 25951 where mirrored networking works.

**Comment by keith-horton** [comment] 2023-09-21 16:20
That's correct - right now, only the 25xxx builds have the OS support for these new features. Hopefully soon the 23xxx builds will have it (as well as the latest Windows 11 retail).

**Comment by sforman2861597** [comment] 2023-09-23 04:09
I updated my system to build 23550 and follow the link and restart my PC, after that my wsl still shows "wsl: Hyper-V firewall is not supported wsl: Mirrored networking mode is not supported, falling back to NAT networking"

**Comment by Morrigan-Ship** [comment] 2023-09-23 13:21
> I updated my system to build 23550 and follow the link and restart my PC, after that my wsl still shows "wsl: Hyper-V firewall is not supported wsl: Mirrored networking mode is not supported, falling back to NAT networking"
> 

test it
it solved for me

https://github.com/microsoft/WSL/issues/10495#issuecomment-1728242749

**Comment by sforman2861597** [comment] 2023-09-23 14:41
> sc.exe config winmgmt start= disabled

Right, I tried these steps and restarted my computer and wsl still doesn't work😒

**Comment by LordMonoxide** [comment] 2023-09-23 14:51
> > sc.exe config winmgmt start= disabled
> 
> Right, I tried these steps and restarted my computer and wsl still doesn't work😒

Read the previous comments, Morrigan-Ship is incorrect

**Comment by wangwangwawng** [comment] 2023-09-25 14:21
需要升级到预览版
![image](https://github.com/microsoft/WSL/assets/34119126/389fa006-1675-4602-82e9-d9eb2b67fcbb)
必须要选Canary
然后去系统更新检查更新,安装完成后
重启电脑即可生效

**Comment by marcelloinfoweb** [comment] 2023-09-26 11:34
1+

wsl: Hyper-V firewall is not supported 
wsl: Mirrored networking mode is not supported, falling back to NAT networking

**Comment by Rajackar** [comment] 2023-09-26 11:37
Yes, same issue here. 
Major headaches now :(

**Comment by keith-horton** [comment] 2023-09-26 16:37
Please verify the version of Windows you are running. Right now, only the 25xxx builds have the OS support for these new features. Hopefully soon the 23xxx builds will have it (as well as the latest Windows 11 retail).

**Comment by zcobol** [comment] 2023-09-27 16:28
`KB5030310` released yesterday (Sep. 16) adds the required support for the new WSL features. Tested on Windows 11 version `10.0.22621.2361`

**Comment by craigloewen-msft** [comment] 2023-09-27 16:29
This error is caused by not being on the right Windows version as @keith-horton said!
You need to be on the Windows Insider ["Canary"](https://blogs.windows.com/windows-insider/2023/08/31/announcing-windows-11-insider-preview-build-25941-canary-channel/) channel or the ["Release Preview"](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/) channel to get these features. 
This will be coming to Windows 11 22H2 eventually as part of a backport.

**Closed by craigloewen-msft** 2023-09-27 16:29 UTC
Labels: network

**Comment by Morrigan-Ship** [comment] 2023-09-27 17:52
> This error is caused by not being on the right Windows version as @keith-horton said! You need to be on the Windows Insider ["Canary"](https://blogs.windows.com/windows-insider/2023/08/31/announcing-windows-11-insider-preview-build-25941-canary-channel/) channel or the ["Release Preview"](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/) channel to get these features. This will be coming to Windows 11 22H2 eventually as part of a backport.

please add support for bridge mod for wsl
and make special IP Address for each WSL distro

**Comment by sforman2861597** [comment] 2023-09-28 03:39
> This error is caused by not being on the right Windows version as @keith-horton said! You need to be on the Windows Insider ["Canary"](https://blogs.windows.com/windows-insider/2023/08/31/announcing-windows-11-insider-preview-build-25941-canary-channel/) channel or the ["Release Preview"](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/) channel to get these features. This will be coming to Windows 11 22H2 eventually as part of a backport.

When I get a push from the dev channel, build23550, I see the following prompts
https://blogs.windows.com/windows-insider/2023/09/22/announcing-windows-11-insider-preview-build-23550-dev-channel/

![image](https://github.com/microsoft/WSL/assets/121373973/9b924d93-14b0-453e-aa0f-0f136ae926b9)

but now,wsl have this problom,

**Comment by marcelloinfoweb** [comment] 2023-09-28 11:00
I forced the upgrade to Canary and WSL now works perfectly.

**Comment by onomatopellan** [comment] 2023-09-28 12:09
| Windows Version | Last build | WSL2 |
|--------------------------------------|--:|-------------------------------------------|
| Windows Insider Canary Channel | 25951 |🪞Mirrored networking support |
| Windows Insider Dev Channel | 23550 |🚫 |
| Windows Insider Beta Channel | 22621.2338 |❓ |
| Windows Insider Release Preview Channel | 22631.2361 |🪞Mirrored networking support |
| Windows Public Release (KB5030310) | 22621.2361 |🪞Mirrored networking support |

Dev and Beta should get the support in the next builds.

**Comment by Rajackar** [comment] 2023-09-29 09:07
> > This error is caused by not being on the right Windows version as @keith-horton said! You need to be on the Windows Insider ["Canary"](https://blogs.windows.com/windows-insider/2023/08/31/announcing-windows-11-insider-preview-build-25941-canary-channel/) channel or the ["Release Preview"](https://blogs.windows.com/windows-insider/2023/09/14/releasing-windows-11-build-22621-2359-to-the-release-preview-channel/) channel to get these features. This will be coming to Windows 11 22H2 eventually as part of a backport.
> 
> When I get a push from the dev channel, build23550, I see the following prompts https://blogs.windows.com/windows-insider/2023/09/22/announcing-windows-11-insider-preview-build-23550-dev-channel/
> 
> ![image](https://user-images.githubusercontent.com/121373973/271167374-9b924d93-14b0-453e-aa0f-0f136ae926b9.png)
> 
> but now,wsl have this problom,

This confused me as well. It's specifically mentioned in this blog and I'm on 23555 as mentioned in the same blog.
Yet the feature is not working.

**Comment by oidualc** [comment] 2023-09-30 17:06
I'm on build 25951 and WSL 2.0.2, I enabled networkingMode=mirrored, but I still cannot access the linux IPv4 address from Windows, let alone another device in the same local network.
To test it I just did a simple `python -m http.server` from within linux, and from the Windows host I tried to reach it via the local network address http://192.168.1.200:8000, I just get a ERR_CONNECTION_TIMED_OUT error.
If I understand correctly, with this new feature I should be able to access a WSL distro from a smartphone in the same network, what could I be missing?

**Comment by keith-horton** [comment] 2023-10-02 16:55
Hi there.
When setting Mirrored Mode, please ensure that it's supported by the OS you have installed - either from looking for a warning during startup (if it's not supported), or running 'ip a' in a Linux prompt to see if the IP addresses assigned in the Linux container are the same as the IP addresses assigned to Windows.

If they are the same, and you want to access port 8000, you'll need to add a Hyper-V Firewall rule to allow that inbound traffic. You can use the New-NetFirewallHyperVRule powershell command'let to add a new rule.

**Comment by heww** [comment] 2023-10-03 06:45
The mirrored networking doesn't work with Windows 10.0.22631.2361 although the port is added to the firewall rule.

```
PS C:\Users> wsl --version
WSL 版本： 2.0.0.0
内核版本： 5.15.123.1-1
WSLg 版本： 1.0.57
MSRDC 版本： 1.2.4485
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25880.1000-230602-1350.main
Windows 版本： 10.0.22631.2361
```

**Comment by sforman2861597** [comment] 2023-10-07 15:14
Even the Release version works, but not the dev version, this can be seen as a bug in the dev version, right?

**Comment by oidualc** [comment] 2023-10-13 05:27
> running 'ip a' in a Linux prompt to see if the IP addresses assigned in the Linux container are the same as the IP addresses assigned to Windows.

Confirmed.

> You can use the New-NetFirewallHyperVRule powershell command'let to add a new rule.

My understanding was that using "firewall=true" in .wslconfig and disabling the Windows Firewall altogether, WSL should have picked it up automatically. Not working this way, could you be more specific about what command to run? I tried something like [this one](https://github.com/microsoft/WSL/issues/10535#issuecomment-1734342358) with no luck.

**Comment by keith-horton** [comment] 2023-10-13 05:37
Hi there.

Setting firewall=true in the .wslconfig file will enable Hyper-V Firewall for that WSL container instance. If the host Windows Firewall is enabled, we will mirror all Windows Firewall rules that are based on IP addresses or port numbers (not user ids or applications). And you can run NetFirewallHyperVRule powershell command'lets to view/add/remove rules for Hyper-V Firewall.

If you have an OS with the necessary updates, these powershell commands should work. Both of these must work for Hyper-V Firewall to be enabled.

get-NetFirewallHyperVVMCreator

this should show something like;
VMCreatorId  : {40E0AC32-46A5-438A-A0B2-2B479E8F2E90}
FriendlyName : WSL


get-NetFirewallHyperVProfile

this should show Public, Private, and Domain profiles like

Name                    : {40E0AC32-46A5-438A-A0B2-2B479E8F2E90}
Profile                 : Public
.
.
.

**Comment by isaali93** [comment] 2023-10-27 18:24
> Windows Version	Last build	WSL2
> Windows Insider Canary Channel	25951	🪞Mirrored networking support
> Windows Insider Dev Channel	23555	❓
> Windows Insider Beta Channel	22621.2338	❓
> Windows Insider Release Preview Channel	22631.2361	🪞Mirrored networking support
> Windows Public Release (KB5030310)	22621.2361	🪞Mirrored networking support
> Dev and Beta channels should get the support in the next builds.

Hey, you guys have any word on when this is coming to Dev? It's been sometime already

**Comment by lc-guy** [comment] 2023-11-01 10:46
Any information on having support for this on windows 10, or is it just not coming to it at all?

**Comment by keith-horton** [comment] 2023-11-01 16:28
Sorry, we have asked. As of today, we do not have plans to take this back to Windows 10.

**Comment by isaali93** [comment] 2023-11-01 21:27
Looks like mirrored networking is enabled on the dev channel as of today's 23580 build.

**Comment by hanxinimm** [comment] 2023-11-25 07:30
Error code: Wsl/Service/CreateInstance/CreateVm/ConfigureNetworking/0x803b0015

**Comment by keith-horton** [comment] 2023-11-28 22:54
Hi there. If you are hitting a new error code, can you open a new GitHub issue + capturing traces?

**Comment by K2ouMais** [comment] 2023-12-12 07:42
Can someone explain, why this doesnt work under Windows 10?

```
[experimental]
networkingMode=mirrored
dnsTunneling=true
```

I have a corporate Laptop without any Admin rights, so I have only this way of getting wsl configured.

I really want to get rid of "wsl-vpnkit" when I am behind a VPN.

**Comment by keith-horton** [comment] 2023-12-14 03:19
Sorry, those features are not available on Windows 10. They are only on Windows 11.

**Comment by boan-jfm** [comment] 2024-01-18 18:52
> Sorry, those features are not available on Windows 10. They are only on Windows 11.

But here it states "**Entries with an ** after the value type require Windows version 22H2 or higher.**":  https://learn.microsoft.com/en-us/windows/wsl/wsl-config

![image](https://github.com/microsoft/WSL/assets/13201214/7eab894a-98e5-4c69-ab80-48a888237b38)

**Comment by jtrenaud1s** [comment] 2024-01-25 22:20
> It's a shame this is Windows 11 only where almost every company is still using Windows 10. Sometimes I really question some decisions.

Same boat. Super annoying. Though I do have local administrator privileges, I still have not found any workaround to the VPN issue. Also stuck on windows 10.

**Comment by K2ouMais** [comment] 2024-01-26 06:46
@jtrenaud1s 

The only way right now to get WSL to work on a vpn ist this tool:
https://github.com/sakai135/wsl-vpnkit

**Comment by martopg** [comment] 2024-08-07 05:01
I ran across this as I was getting:

>wsl: Mirrored networking mode is not supported: Windows version <version> does not have the required features

For anyone else that's seeing that: I I was on Win11 23H2 but didn't have the latest updates for it and installing those resolved the issue.
