### ISSUE TITLE
Linux not appearing in file explorer; cannot use `wslview`

### ISSUE THREAD

**Issue by michaelfromyeg** [microsoft/WSL#11252] opened 2024-03-04 22:51 UTC
### Windows Version

Microsoft Windows [Version 10.0.26063.1]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2 

### Distro Version

Ubuntu 20.04

### Other Software

wslu v4.1.1-1

### Repro Steps

Running `wslview <filename>` I get,

```
Start : This command cannot be run due to the error: Element not found.
At line:1 char:128
+ ... oding(437); Start "\\wsl.localhost\Ubuntu\home\mdema\school\cpsc416\c ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

(I believe this is related), also, in file explorer, Linux doesn't appear in the left side bar and I cannot normally access files. I previously had some folders within WSL pinned to quick access; when I click them, I get `Element not found`.

For the second problem, I have a found a workaround. If I directly put `\\wsl.localhost` in the address bar, it takes me to the WSL root (with the `Ubuntu` folder accessible as expected).

### Expected Behavior

wslview should open the file.

Linux should be visible in file explorer. Quick links should take me to the specified directory under WSL.

### Actual Behavior

wslview reports, for all files

```
Start : This command cannot be run due to the error: Element not found.
At line:1 char:128
+ ... oding(437); Start "\\wsl.localhost\Ubuntu\home\mdema\school\cpsc416\c ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

Linux item is missing from file explorer.

**Comment by michaelfromyeg** [comment] 2024-03-04 22:54
I did a log capture while running `wslview`; hopefully it's helpful!

[WslLogs-2024-03-04_14-52-57.zip](https://github.com/microsoft/WSL/files/14488054/WslLogs-2024-03-04_14-52-57.zip)

**Comment by OneBlue** [comment] 2024-03-05 22:25
Thank you @michaelfromyeg. Can you share the output of `dir \\wsl.localhost\<distro>\path\to\file` ?

**Comment by michaelfromyeg** [comment] 2024-03-05 22:28
Here it is!

```
C:\Users\mdema>dir \\wsl.localhost\Ubuntu\home\mdema\raft_diagram.pdf
 Volume in drive \\wsl.localhost\Ubuntu has no label.

 Directory of \\wsl.localhost\Ubuntu\home\mdema

03/05/2024  02:27 PM            47,827 raft_diagram.pdf
               1 File(s)         47,827 bytes
               0 Dir(s)  73,144,909,824 bytes free
```

**Comment by Physikbuddha** [comment] 2024-03-06 11:08
I can confirm. Looks like Windows tried to install a WSL update today, and now my pinned folders from WSL in the file explorer are gone, as well as the Linux shortcut. Accessing via `\\wsl.localhost` or `\\wsl$` still works, but pinning new folders to the quick access are not clickable.

Found one related entry in the event viewer:
Installation Failure: Windows failed to install the following update with error 0x80073D02: 9P9TQF7MRM4R-MicrosoftCorporationII.WindowsSubsystemforLinux

Doing a system restore brought WSL back for a short period, now it's gone again.

**Comment by kmnis** [comment] 2024-03-06 16:39
I can confirm the same issue. I installed the latest windows 11 update (KB5034848) and now Linux icon is gone. When I try to open via `\\wsl.localhost` and try to pin the folder on left, nothing happens.

**Comment by Ramzy1990** [comment] 2024-03-06 19:01
Can confirm the same behavior as well: (no icon, previous quick access pins deleted, not able to make new pins)
Able to use \\wsl$ from the explorer bar.
**wsl --version output:**

> WSL version: 2.1.4.0
> Kernel version: 5.15.146.1-2
> WSLg version: 1.0.60
> MSRDC version: 1.2.5105
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.3155

**Comment by Korred** [comment] 2024-03-06 21:45
I'm experiencing the same issue - the Linux icon has vanished. I'm using the same WSL version as @Ramzy1990, and I'm encountering the same error log as @Physikbuddha:

> error 0x80073D02: 9P9TQF7MRM4R-MicrosoftCorporationII.WindowsSubsystemforLinux

This issue surfaced today, and it seems unrelated to the most recent Windows Update `KB5034848`, since mine disappeared while being on `KB5034467`.

**Comment by mannkeithc** [comment] 2024-03-07 15:27
I received the WSL Update via the Microsoft Store today, 7 Mar 2023, and I also now have the problem where the Linux Folder vanished from Explorer's left-hand folder / drives pane post update. I previously reported this issue when I tried the preview of this WSL update and rolled it back as consequence. Unfortunately, that was ignored. I am currently using the workaround, <windows key> + <R> and enter \\wsl$\ and then pin to Explorer's quick access.

**Comment by Korred** [comment] 2024-03-12 21:10
Looks like there was an update today `Windows Subsystem for Linux. Product version: 2.1.5.0` and the icon is back 👍 

![image](https://github.com/microsoft/WSL/assets/1658897/d8735b36-e7f9-4543-8153-cfd723314a0b)

**Comment by michaelfromyeg** [comment] 2024-03-12 21:26
Can confirm this update fixes my issue at least. For those wondering, run 

```
$ wsl --update --pre-release
Checking for updates.
Updating Windows Subsystem for Linux to version: 2.1.5.
```

2.1.5 fixed both the File Explorer issue and `wslview` so I'm happy, but I'll leave the issue open since there are other related things going on.

**Comment by kmnis** [comment] 2024-03-14 15:04
I upgraded to the new version but issue still not fixed. I don't see Linux in File Explorer left Menu and can't pin any folders to quick access as well.

**Comment by OneBlue** [comment] 2024-03-22 19:04
Fixed in [2.2.1](https://github.com/microsoft/WSL/releases/tag/2.2.1)

**Closed by OneBlue** 2024-03-22 19:04 UTC

**Comment by Premshay** [comment] 2024-05-31 11:35
Can confirm that the update pre release solved it for me as well. Thank you for the tip.

**Comment by MGB-Hadean** [comment] 2024-10-15 11:48
Getting this after 24H2 win11 update: all wsl quick access links were gone after the update.
Updated wsl to 2.3.24.0, after which I created a new quick access link to wsl: this worked fine when tested immediately.
Tried to access it after ~10 mins (new explorer window) get the error message: "Element not found".
Also noted: quick access menu now very flaky.  RMB shows different menus or doesn't change to selected item.  Slow to draw and flickers to different items on draw.

Edition	Windows 11 Pro
Version	24H2
OS build	26100.1742
Experience	Windows Feature Experience Pack 1000.26100.18.0

>wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.1742

**Comment by conan** [comment] 2024-10-16 10:19
Same as @MGB-Hadean above, all my quick access pins disappeared.  I can add them back, but they either give me "Element not found" as above, or do nothing in a dialogue.  

```cmd
>wsl --version
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2033
```
![Image](https://github.com/user-attachments/assets/1b0ce5bb-7cd6-42eb-be41-f28b82d8ff91)

**Comment by MGB-Hadean** [comment] 2024-10-22 16:12
Weirdly, the quick access links have started working fine for me now...

**Comment by freedxmgxd** [comment] 2024-11-11 17:44
Still brokes to me, and wslview not found

**Comment by kiraware** [comment] 2024-11-22 08:10
me too here

**Comment by jaysqvl** [comment] 2024-12-12 10:15
If you navigate to

```
\\wsl$
```

then right click on the Ubuntu folder and map network drive. You can then start pinning folders from within it again. You can also view it under "This PC". Hope this helps anyone else.

**Comment by dadooda** [comment] 2024-12-27 12:27
- Windows 11 Pro
- 24H2
- OS Build 26100.2605
- WSL version: 2.3.26.0

Drive mapping to `\\wsl$` works just as it did before. But `wslview` doesn't work from any of the installed Ubuntu distros with `Element not found` mentioned by the OP.

**Comment by JohnRDOrazio** [comment] 2024-12-31 21:15
I'm also having the same problem of `Element not found` after pinning to Quick Access, and no way to remove from Quick Access. Even if I try re-pinning to unpin, it still won't unpin. And right-clicking doesn't give an unpin optiion.

I mapped to network drive and pinned, but I can't unpin the two unworking pins that are now there.

**Comment by kharisecario** [comment] 2025-01-02 05:26
Confirmed broken path when make quick access

WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605

**Comment by hellodit** [comment] 2025-01-04 04:49
tIt's still buggy

WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605

**Comment by ctlila** [comment] 2025-01-09 14:24
I've found a workaround. 
Map your WSL network drive to a local drive in windows, following [these instructions](https://support.microsoft.com/en-gb/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d).
Then your WSL directory will be accessible from the local drive letter you've assigned to it (for instance W:\).

**Comment by Dengda98** [comment] 2025-01-12 14:22
still has this problem. 

```
WSL version: 2.3.26.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.2605
```

**Comment by ChiefWoods** [comment] 2025-01-18 05:45
> If you navigate to
> 
> ```
> \\wsl$
> ```
> 
> then right click on the Ubuntu folder and map network drive. You can then start pinning folders from within it again. You can also view it under "This PC". Hope this helps anyone else.
> 
> Windows 11 Pro 24H2 WSL Version: 2.4.5 (Pre-release)

This worked, cheers!

**Comment by thiagogabriel** [comment] 2025-02-18 13:04
I upgraded from Windows 11 22h2 to 24h2 this week and this 1 year old issue started happening. Not sure why this issue was closed.
```
$ wslview .
Start : This command cannot be run due to the error: Element not found.
At line:1 char:128
+ ... oding(437); Start "\\wsl.localhost\Ubuntu-24.04\home\borges\Projects\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
After clicking on pinned WSL folder:
![Image](https://github.com/user-attachments/assets/1e66997c-ab95-4f9e-8a4d-7fcde56819c3)

**Comment by srazvan88** [comment] 2025-02-19 09:58
can't remember which insider build I was on, but after the update to 10.0.26120.3073, I noticed today missing Linux icon in explorer.exe; removing and reinstalling Windows Subsystem for Linux is the quickest fix for me.

P.S. This build also reset my Path environment variable

**Comment by AlexJDG** [comment] 2025-02-26 17:25
This is happening to me now as well since updating to 26100.3194

**Comment by notV3NOM** [comment] 2025-02-26 18:35
I [deleted old quick pins](https://superuser.com/questions/1086605/deleting-quick-access-links-from-disconnected-network-drive-in-explorer) and followed https://github.com/microsoft/WSL/issues/11252#issuecomment-2538456962

**Comment by thiagogabriel** [comment] 2025-03-09 19:19
`wsl --update --pre-release` worked for me after I restarted the computer. Thanks @souravsaraf123
