### ISSUE TITLE
Temporary failure in name resolution caused by docker started

### ISSUE THREAD

**Issue by bjornmonkey** [microsoft/WSL#9552] opened 2023-01-28 04:40 UTC
### Version

10.0.22623.1245

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.15.83.1

### Distro Version

Ubuntu 20.04.5 LTS

### Repro Steps

1. create /etc/wsl.conf with command [boot] = service docker start
2. terminate WSL2 and reopen it, input ping under Ubuntu 20.04, it will immediately reponse with tips "temporary failure in name resolution"
3. If I delete wsl.conf file, then teminate WSL2 and reopen it, ping will work fine.

### Expected Behavior

ping ok even docker started

### Actual Behavior

docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:79ff:fec6:2713  prefixlen 64  scopeid 0x20<link>
        ether 02:42:79:c6:27:13  txqueuelen 0  (Ethernet)
        RX packets 49  bytes 2966 (2.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 652 (652.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.9.78  netmask 255.255.240.0  broadcast 172.17.15.255
        inet6 fe80::215:5dff:fe86:502a  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:86:50:2a  txqueuelen 1000  (Ethernet)
        RX packets 1302  bytes 1168664 (1.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 446  bytes 49884 (49.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 34097  bytes 125756777 (125.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34097  bytes 125756777 (125.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth14c7147: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::5c93:59ff:fead:3660  prefixlen 64  scopeid 0x20<link>
        ether 5e:93:59:ad:36:60  txqueuelen 0  (Ethernet)
        RX packets 49  bytes 3652 (3.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24  bytes 1868 (1.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by wallacewvr** [comment] 2023-03-16 12:21
I've the same problem here, when I ping to google domain, before start docker service, it works fine.
But when I ping after start docker service I got temporary failure in name resolution.

**Comment by medi6** [comment] 2023-04-03 09:04
Hi,

If your problem appears after starting docker, the problem is that Docker default IPs are overwritting WSL one.
Modifying Docker bridge IP and / or Docker "VLAN" configuration will solve this.

So, in /etc/docker/daemon.json file, try affecting other IPs, and then restart docker service :

`{
    "bip": "10.88.0.1/16",
    "default-address-pools": [
      {
        "base": "10.89.0.1/16",
        "size": 24
      }
    ]
}`

**Comment by bjornmonkey** [comment] 2023-04-04 02:23
> Hi,
> 
> If your problem appears after starting docker, the problem is that Docker default IPs are overwritting WSL one. Modifying Docker bridge IP and / or Docker "VLAN" configuration will fix this.
> 
> So, in /etc/docker/daemon.json file, try affecting other IPs, and then restart docker service :
> 
> `{ "bip": "10.88.0.1/16", "default-address-pools": [ { "base": "10.89.0.1/16", "size": 24 } ] }`

Thanks for your help. This issue have been closed after the docker application updated.

**Comment by medi6** [comment] 2023-04-04 08:45
Hi, 

so you can close it ?

Thanks,

**Closed** 2023-04-04 08:48 UTC
