### ISSUE TITLE
Error: 0x80070057 when building inside Eclipse CDT

### ISSUE THREAD

**Issue by KenBarr** [Microsoft/WSL#719] opened 2016-08-03 02:44 UTC
Attempting to build Linux c program from inside Windows Eclipse CDT.

From cmd prompt this works as expected:
bash -c "make all"

In eclipse Luna CDT set the C/C++ Build -> Build command:  bash -c
Create a build target all = "make all"

When build target all, output is:

bash -c "make all"
E r r o r : 0 x 8 0 0 7 0 0 5 7

Windows 10 build = 10.0.1.14393.

**Comment by benhillis** [comment] 2016-08-03 04:09
This has to do with input / output redirection for Linux processes. This should be fixed in the first post Anniversary Update Windows insider flight.

**Comment by JeepMatze** [comment] 2017-03-28 07:17
I am also having the exact same problem. 
Since this bug is open for almost 8 months now - is there a chance that it will be fixed in the near future?
Or is there any workaround I could use?

I am using the current official release of Win10/WSL (Version 1607 / Build 14393.953).
Or do I really have to use insider build version?

**Comment by DrWheetos** [comment] 2017-05-26 20:59
I can confirm it's still not fixed in Version 1607 / OS Build 14393.1198.  I can run a bash script fine from a command prompt but not from Eclipse (I'm using Kepler) when configured in the Project Properties.  I've tried configuring Eclipse to run it as an External Tool, but I get the same 0x80070057 error.  Sad.

**Comment by JeepMatze** [comment] 2017-05-27 07:45
For me, installing the Creators Update fixed this problem.

**Comment by aseering** [comment] 2017-05-28 13:07
@DrWheetos -- build 14393 is from last summer, that's why you haven't seen any change since then :-)  The [Creators update](https://www.microsoft.com/en-us/software-download/windows10) that @JeepMatze mentions is build 15063.

**Comment by DrWheetos** [comment] 2017-05-28 19:16
@aseering @JeepMatze Thanks guys for letting me know that it's fixed in the Creators Update.  I'm having to hold off getting that for the moment as I have some Juniper Networks VPN components that don't play nice with it.  Once that problem's been fixed, hopefully early June, I'll apply the Creators Update.  Currently, I'm having to keep some command prompt windows open as a work around.  It works but not as convenient as having everything in the IDE.  Just playing with an Omega 2+ at the moment.

**Closed** 2018-05-25 03:46 UTC
