### ISSUE TITLE
Using a complex path list with WSLENV causes entire process tree to die (WSL2 regression)

### ISSUE THREAD

**Issue by andrewluotechnologies** [microsoft/WSL#4161] opened 2019-06-17 06:07 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.18917.1000]`

WSL:
`Linux DESKTOP-HLO5ULF 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`Distributor ID: Ubuntu`
`Description:    Ubuntu 18.04.2 LTS`
`Release:        18.04`
`Codename:       bionic`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
Running the following three commands causes the entire process tree up to init to die:
`export WSLENV=PATH/l`
`export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/Andrew/AppData/Local/Microsoft/WindowsApps:/snap/bin:/mnt/c/progra~2/micros~1/2019/enterp~1/vc/tools/msvc/1421~1.277/bin/hostx86/x64:/mnt/c/progra~2/micros~1/2019/enterp~1/vc/tools/msvc/1421~1.277/bin/hostx86/x86:/mnt/c/progra~2/micros~1/2019/enterp~1/common7/ide/vc/vcpack~1:/mnt/c/progra~2/micros~1/2019/enterp~1/common7/ide/common~1/micros~1/testwi~1:/mnt/c/progra~2/micros~1/2019/enterp~1/common7/ide/common~1/micros~1/teamfo~1/teamex~1:/mnt/c/progra~2/micros~1/2019/enterp~1/msbuild/current/bin/roslyn:/mnt/c/progra~2/micros~1/2019/enterp~1/teamto~1/perfor~1/x64:/mnt/c/progra~2/micros~1/2019/enterp~1/teamto~1/perfor~1"`
`cmd.exe`

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/andrewluotechnologies/2d6dbf0f902a1d4ef2186a22530c86c1

**Comment by benhillis** [comment] 2019-06-28 18:43
@andrewluotechnologies - Thanks for filing.  'm not able to reproduce this locally, would it be possible for you to take a [trace](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) and attach the files?

**Comment by andrewluotechnologies** [comment] 2019-07-12 00:03
I submitted the logs to InsiderSupport@microsoft.com per the instructions.  I'm not sure if they contain anything sensitive so I'm a bit cautious about posting them publicly.  If they won't contain anything sensitive and if you have more information on what exactly would be captured then I can also attach them here.

One more thing - my Insider build was recently upgraded, however the issue is still reproducible.  I'm now on:

`Microsoft Windows [Version 10.0.18922.1000]`

however the WSL2 version appears to be the same

`Linux DESKTOP-HLO5ULF 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by therealkenc** [comment] 2019-09-21 18:41
Closing for lack of repro. It should be possible to formulate CLI reproduction steps absent sensitive data. You posted the right place; I strongly suspect `InsiderSupport@microsoft.com` isn't going to be able to help; development scenarios aren't really their mandate. I have a pretty ridiculous Windows path myself and it doesn't take down WSL with `WSLENV=PATH/l`. Obviously it does for you, but there is no way to guess why without steps to reproduce the problem. There haven't been any me2s in three months. Suspect there is something "tag external" going on, but I can't prove that either. Debugging this on your local machine would amount to starting over from a clean install, perhaps in a VM, and start adding components (paths) until you find the one that takes down the whole edifice.

**Closed by therealkenc** 2019-09-21 18:41 UTC
Labels: need-repro, wsl2
