### ISSUE TITLE
Invocation of `code.exe` does not terminate with output

### ISSUE THREAD

**Issue by aeschli** [microsoft/WSL#6993] opened 2021-05-26 07:18 UTC
### Windows Build Number

1909 Build 18363.1082

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

4.19.128-microsoft-standard

### Distro Version

Ubuntu 20.04

### Other Software

Visual Studio Code 1.50

### Repro Steps

Moved here from https://github.com/microsoft/vscode-remote-release/issues/3831
Reported on behalf of @piejanssens
I am not able to reproduce on my machine.

In the WSL shell:
- `WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl >/tmp/remote-wsl-loc.txt` does not terminate
- `WSLENV=ELECTRON_RUN_AS_NODE/w ELECTRON_RUN_AS_NODE=1 "/mnt/c/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/Code.exe" "C:/Users/pietejanssens/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js" --locate-extension ms-vscode-remote.remote-wsl` prints to the console but does not terminate

### Expected Behavior

- Command terminates and writes a path to file `/tmp/remote-wsl-loc.txt`
- Command terminates and prints a path to the console

### Actual Behavior

Command hang,

CTRL+C on the first one closes without any output.
CTRL+C on the second one keeps printing "write failed 32: Broken pipe"

**Comment by piejanssens** [comment] 2021-05-26 07:36
Meanwhile, current version:
- Kernel 5.4.72-microsoft-standard-WSL2
- Distro: Ubuntu 20.04
- Host: Windows 10.0.19042.985
- VS Code: 1.56.2

From microsoft/vscode-remote-release#3831: _I completely uninstalled VS Code, deleted all these folders manually, reinstalled VS Code and allowed installation of "Remote WSL" and still have the same issue._

**Comment by therealkenc** [comment] 2021-05-27 21:14
Thanks for the CLI repro steps. Couldn't reproduce here either, but there's been past evidence something (dunno what) is going on ref #3734.

![image](https://user-images.githubusercontent.com/7049700/119897518-5bb84500-bef5-11eb-895f-58c48a537cb7.png)

**Comment by Sublime1** [comment] 2023-09-22 10:13
This started happening to me after I added a remote ssh connection. Ctrl-c allows me to workaround it. It only happens on the first directory I run "code ," - subsequent runs are fine.

**Comment by craigloewen-msft** [comment] 2024-06-04 21:32
This should be fixed in the latest versions of the VS code. If you're still seeing this please open a new issue!

**Closed by craigloewen-msft** 2024-06-04 21:32 UTC
Labels: need-repro
