### ISSUE TITLE
sshuttle not working on WSL

### ISSUE THREAD

**Issue by BerndKue** [Microsoft/WSL#3336] opened 2018-06-28 14:47 UTC
I would like to tunnel all my traffic through a specific ssh server using [sshuttle](http://sshuttle.readthedocs.io/en/stable/)

I installed the package via `apt-get install sshuttle` without issues.

But establishing the connection to the ssh host gives me the following error message:
`
iptables v1.6.0: can't initialize iptables table 'nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
`

It seems that the Ubuntu inside the WSL does not fully support the iptables commands sshuttle is calling.

Using sshuttle to tunnel traffic through so called jump hosts to access a secured infrastructure network is a common practice in IT administration. Our Linux and Mac users are doing this since a long time. On Windows it was always a pain to use solutions like putty as a dynamic port socks proxy. This anyway only does the job for applications that are able to use a socks proxy but not for command line tools.

It is actually the only thing that is holding back some of my colleagues to change from a Mac to a windows workstation.

**Comment by DarthSpock** [comment] 2018-06-28 15:30
Duplicate of #767, which in turn was closed. UserVoice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/32025199-support-iptables)

**Comment by therealkenc** [comment] 2018-06-28 21:22
Calling it #767 but mostly for lack of [CONTRIBUTING.md](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md).

**Closed by therealkenc** 2018-06-28 21:22 UTC

**Comment by AddoSolutions** [comment] 2020-04-19 13:44
Has anyone updated this in WSL2
