### ISSUE TITLE
EACCESS on "rename" unique to ARM64 (Surface Pro X machine)

### ISSUE THREAD

**Issue by pr3johns** [microsoft/WSL#5139] opened 2020-04-26 21:45 UTC
* Your Windows build number:  10.0.19041.207

* What you're doing and what's happening:  I am attempting an npm install for a React project. Part of the install involves a **rename** system call which always fails (full screen shot here):

<img width="1426" alt="eaccess_screen_shot" src="https://user-images.githubusercontent.com/6656516/80320531-cfa48d00-87cb-11ea-93ad-5b1e5f9dd73e.png">

I am also attaching the npm log.

[2020-04-26T21_37_47_987Z-debug.log](https://github.com/microsoft/WSL/files/4536517/2020-04-26T21_37_47_987Z-debug.log)

I have also successfully ran the same **npm install** on the EXACT same project on an Intel machine inside WSL without ANY permission issue. Is there something particular to ARM64 WSL?

Thanks.

**Comment by sirredbeard** [comment] 2020-04-27 14:42
Could you please attach an strace?

$ strace -o strace.log yourfailingcommand

**Comment by pr3johns** [comment] 2020-04-27 15:16
Here you go....
[strace.zip](https://github.com/microsoft/WSL/files/4540471/strace.zip)

**Comment by pr3johns** [comment] 2020-04-27 15:24
Also I'd be happy to post this project on github if someone wants to repro.

**Comment by sirredbeard** [comment] 2020-04-29 16:24
A repro would be very useful.

**Comment by pr3johns** [comment] 2020-04-29 17:54
OK I was able to distill this to the simplest possible repro. Perform these steps:

`npm init
npm install grpc`

(just accept all defaults to the `npm init`). Running these commands in WSL on an ARM64 machine FAILS with the same EACCESS screenshot shown in my original post. Running this command on an Intel device in WSL works. Both machines running npm 6.14.4.

**Comment by sirredbeard** [comment] 2020-04-30 21:13
Duplicate of #14.

**Comment by pr3johns** [comment] 2020-04-30 22:57
I read all the comments in issue #14 (there are a lot!). None of the suggestions worked for me EXCEPT someone suggested that the issue is not prevalent on WSL2. I upgraded to WSL2 and the issue went away. Thanks.

**Comment by therealkenc** [comment] 2020-05-19 08:07
Yeah that's #14 aka #1529 aka others. I should have looked at the screencap closer and was thrown by unique to Arm.

**Closed by therealkenc** 2020-05-19 08:07 UTC
