### ISSUE TITLE
Calling a windows process with a long argument list results in an error on WSL2

### ISSUE THREAD

**Issue by x0wllaar** [microsoft/WSL#6420] opened 2021-01-11 21:12 UTC
Running Windows executables from within WSL results in an error if the argument line is long enough

# Environment

```none
Windows build number: 10.0.21286.1000
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2 (Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020)
```

# Steps to reproduce

```none
$ cmd.exe /C echo $(for i in {1..5000}; do echo -n 'A'; done)
```
**WSL logs**:  uploaded via feedback hub

#  Expected behavior

A lot of A's displayed

# Actual behavior

Instead, it hangs for a moment, and prints

```none
<3>init: (77) ERROR: UtilAcceptVsock:243: accept4 failed 110
                                                            %
```

It works for lower numbers of A's

```none
$ cmd.exe /C echo $(for i in {1..100}; do echo -n 'A'; done)                                                                                                                     
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by therealkenc** [comment] 2021-01-14 19:35
Was able to repro. 

![image](https://user-images.githubusercontent.com/7049700/104639629-7e3f7500-565c-11eb-9fa4-ad8f6ca5d23f.png)

The maximum length of a cmd.exe argument string is 2047 characters, so this is pretty by-design, even if the error is suboptimal. 

What is your use case?

**Comment by x0wllaar** [comment] 2021-01-14 20:49
My use case was calling windows MPV with a wild card as argument:
```none
$ mpv.exe ./Music/*/*.ogg
```
I got around this with a shell script, so all is well for me. :)

> The maximum length of a cmd.exe argument string is 2047 characters

I thought of this too , but what's interesting is that it will work for more than 2047 A's:

```none
/mnt/c$ cmd.exe /C echo $(for i in {1..3000}; do echo -n 'A'; done)
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.....
```
I guess it depends on the working directory of the command, but in /mnt/c it breaks at 3816 A's for me

```none
/mnt/c$ cmd.exe /C echo $(for i in {1..3816}; do echo -n 'A'; done)
<3>init: (286) ERROR: UtilAcceptVsock:243: accept4 failed 110
```

**Comment by x0wllaar** [comment] 2021-01-14 23:00
After digging a bit more (and running Windows programs with `strace`, what a world we live in) , I've found out that there's this call to `write`:

```(none)
$ strace cmd.exe /C echo $(for i in {1..3803}; do echo -n 'A'; done)
.......
write(5, "\6\0\0\0\1\20\0\0\247\2\326M\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4097) = 4097
.......
ERROR: UtilAcceptVsock:243: accept4 failed 110
```

If the size of the buffer in the call is less than or equal to 4096, everything works

```(none)
$ strace cmd.exe /C echo $(for i in {1..3802}; do echo -n 'A'; done)
.......
write(5, "\6\0\0\0\0\20\0\0\250\2\326M\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
.......
+++ exited with 0 +++
```

At least now the length is not a random number but a nice power of 2.

**Comment by benhillis** [comment] 2021-01-14 23:02
@x0wllaar - thanks for the detailed debugging, I will take a look.

**Comment by benhillis** [comment] 2021-01-14 23:49
Looks like this is a real bug, request to launch process isn't making it to the Windows side.  I'm taking a look.

**Comment by jamesthurley** [comment] 2022-01-20 14:40
I've just encountered this (or at least something very similar) with `git pull`:
```
$ git pull
<3>init: (5166) ERROR: UtilAcceptVsock:238: accept4 failed 110
```

**Comment by jamesthurley** [comment] 2022-01-20 14:52
Not git specific actually. From the same folder:
```
$ code .
<3>init: (233) ERROR: UtilAcceptVsock:238: accept4 failed 110
```

Perhaps this is a different issue to the others in this thread.

**Comment by gfmjr** [comment] 2022-01-29 05:52
I was able to resolve my UtilAcceptVsock error by enabling the interop in the .wslconfig file
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig

**Comment by shuffle2** [comment] 2022-03-24 07:23
I got `<3>init: (48852) ERROR: UtilAcceptVsock:244: accept4 failed 110` when building ffmpeg in wsl2. 

The documentation of `/etc/wsl.conf` states that `interop.enabled` defaults to `true`. Explicitly setting it to `true` did **not** help me. ☹️

**Comment by gfmjr** [comment] 2022-03-24 17:11
the .wslconfig file is in your C:\Users\<UserName>\.wslconfig  NOT on the WSL container /etc/wsl.conf that is a different config file.

After you force it to 'true', run a   wsl --shutdown  from your cmd prompt and restart your WSL instance and try then.

**Comment by shuffle2** [comment] 2022-03-24 20:21
@gfmjr amazingly, that worked! so it seems the documentation for those config files is incorrect in at least two ways :/ thanks!

**Comment by shuffle2** [comment] 2022-03-24 20:26
if you saw my now-deleted update: oops, i had run the wrong test.
unfortunately, putting the setting in .wslconfig didn't fix the problem. So probably the documentation is correct, after all.

**Comment by benhillis** [comment] 2022-03-24 21:35
Sorry for the delay on this, this should be fixed in https://github.com/microsoft/WSL/releases/tag/0.56.2.

**Closed by benhillis** 2022-03-24 21:35 UTC
Labels: needs-investigation

**Comment by EmberXD** [comment] 2022-04-25 16:45
I upgrade my wsl to latest version and the problem was resolved.

**Comment by cenit** [comment] 2023-02-03 14:08
```
$ code .
<3>WSL (3302) ERROR: UtilAcceptVsock:246: accept4 failed 110
```

the problem is still real for me, it just came out today
