### ISSUE TITLE
WSL Ubuntu error 0x80004002

### ISSUE THREAD

**Issue by ghost** [Microsoft/WSL#2851] opened 2018-01-17 20:53 UTC
* Your Windows build number:
Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening:
```
C:\WINDOWS\system32>bash
Error: 0x80004002
Press any key to continue...
```

* What's wrong / what should be happening instead:
It should launch bash.  Ubuntu WSL installed via Store and previously working.
I'm unaware of what precipitated the change in behaviour; I was unable to launch
bash from start menu and running bash.exe yields output above.

lxcore trace output sent.

**Comment by benhillis** [comment] 2018-01-17 22:11
Can you double check that the Windows Subsystem for Linux optional feature is still enabled?

**Comment by mgcsams** [comment] 2018-01-17 22:29
Run as administrator:
```
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux



Path          : 
Online        : True
RestartNeeded : False
```

**Comment by mgcsams** [comment] 2018-01-19 16:56
Is there any further detail I can provide to help troubleshoot this issue?

**Comment by juso** [comment] 2018-01-23 13:28
While trying to circumvent the issue https://github.com/Microsoft/WSL/issues/2823 I bumped sporadically into the same error and it always gets away after full WSL re-setup (uninstall Ubuntu, disable WSL and re-do setup again) though it may not be an option for you if you already have various things setup.

**Comment by alycd** [comment] 2018-02-13 18:58
[lxcore_adss.zip](https://github.com/Microsoft/WSL/files/1721226/lxcore_adss.zip)
I ran the commands posted here https://docs.microsoft.com/en-us/windows/wsl/troubleshooting

```Starting bash gives an error code
Download these two .txt files and rename them .cmd https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt
Run start_lxcore_trace.cmd from an admin command prompt
Launch bash.exe (repro the scenario).
Run stop_lxcore_trace.cmd from an admin command prompt
You should now see three .etl files in the directory you ran the script from.
Post the files with your GitHub post to our issue page.```

And Im posting the ETL files here, zipped, hoping that someone can help me.

Thanks in advance

**Comment by nereusuj** [comment] 2018-05-25 01:05
I have same issue.

I observed that when I manually started LxssManager service from service manager, it stop with following message.
"The LxssManager service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other service or programs"

There was no problem with windows 1706. but it happened after upgraded to 1709.

**Comment by benhillis** [comment] 2018-07-11 17:31
Marking as duplicate of #2987.

**Closed by benhillis** 2018-07-11 17:31 UTC

**Comment by SeeYaaa** [comment] 2022-08-09 23:14
I have the same issue! :( 
thanks microsoft! i lost all the data

**Comment by VyacheslavZinch** [comment] 2023-01-14 23:14
> Run as administrator:
> 
> ```
> PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux


thank's. it's works for me

**Comment by asensionacher** [comment] 2023-02-02 14:36
> Run as administrator:
> 
> ```
> PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> 
> 
> 
> Path          : 
> Online        : True
> RestartNeeded : False
> ```

Worked for me

**Comment by qdchenyixuan** [comment] 2023-04-12 01:51
I reset windows don't work,but this is worked for me,tk you.

**Comment by FJianC** [comment] 2023-05-30 08:50
Worked for me
```powershell
Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
```

**Comment by AOOOOOA** [comment] 2023-06-01 14:12
> Worked for me
> 
> ```powershell
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
> ```

Works for me as well. But I met another problem, After execute the two commands, if I directly click the ubuntu18 installed from  Microsoft store, it can successfully run. But if I click the wsl installed from store at firtst, the same error appears. I'm still looking for the reason.

**Comment by BJFQHSM** [comment] 2023-06-06 08:05
> Run as administrator:
> 
> ```
> PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> 
> 
> 
> Path          : 
> Online        : True
> RestartNeeded : False
> ```

worked for me!

**Comment by leollon** [comment] 2023-06-21 05:02
worked for me.
run powershell as administrator,

> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe

**Comment by thahhphuong** [comment] 2023-07-04 07:22
> 
worked for me!

**Comment by thahhphuong** [comment] 2023-07-04 07:23
> worked for me. run powershell as administrator:
> 
> ```
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
> ```



> worked for me. run powershell as administrator:
> 
> ```
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
> ```

worked for me !! Thanks >3

**Comment by BVBee** [comment] 2023-07-10 07:03
> Worked for me
> 
> ```powershell
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
> ```

worked for me, thanks.

**Comment by BVBee** [comment] 2023-07-10 07:22
hi

**Comment by gustavosimon** [comment] 2023-07-26 19:46
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe

Worked for me

**Comment by Harrykeyrun** [comment] 2023-08-07 08:29
Hi,

Run --> wsl.exe --update to update linux kernel package and see if it resolves.

//Harry

**Comment by ivanmirandaf** [comment] 2023-08-22 12:14
> Worked for me
> 
> ```powershell
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
> ```

Obrigado amigo, você é um amigo <3 (y)

**Comment by arielalvesdutra** [comment] 2023-11-06 01:08
> worked for me. run powershell as administrator:
> 
> ```
> Get-AppxPackage |? { $_.Name -like "*WindowsSubsystemforLinux*" }
> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForLinux_1.2.5.0_x64__8wekyb3d8bbwe
> ```

Worked here. Thanks!
