### ISSUE TITLE
duplicate `libd3d12 (1).so` appears after upgrading to 20262

### ISSUE THREAD

**Issue by FanShupei** [microsoft/WSL#6260] opened 2020-11-19 11:26 UTC
# Environment

```none
Windows build number: Version 10.0.20262.1
Your Distribution version: Ubuntu 20.04
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```

# Steps to reproduce

After upgrading to 20262 (from 20257), run `ls /usr/lib/wsl/lib`

**WSL logs**: 

#  Expected behavior

There shouldn't be duplicated so files in `/usr/lib/wsl/lib`

# Actual behavior

You see there are many duplicated so files.

```
fsp@FSP-PC:~$ ls /usr/lib/wsl/lib -l
total 103256
-r--r--r-- 1 root root   124664 Sep 17 10:24  libcuda.so
-r--r--r-- 1 root root   124664 Sep 17 10:24  libcuda.so.1
-r--r--r-- 1 root root   124664 Sep 17 10:24  libcuda.so.1.1
-r--r--r-- 2 root root   785144 Nov  7 21:50 'libd3d12 (1).so'
-r--r--r-- 2 root root   785144 Nov 14 20:15  libd3d12.so
-r--r--r-- 2 root root  5300896 Nov  7 21:50 'libd3d12core (1).so'
-r--r--r-- 2 root root  5300896 Nov 14 20:15  libd3d12core.so
-r--r--r-- 2 root root 25263616 Nov  7 21:50 'libdirectml (1).so'
-r--r--r-- 2 root root 25263616 Nov 14 20:15  libdirectml.so
-r--r--r-- 2 root root   827632 Nov  7 21:50 'libdxcore (1).so'
-r--r--r-- 2 root root   827632 Nov 14 20:15  libdxcore.so
-r--r--r-- 1 root root 40980456 Sep 17 10:24  libnvwgf2umx.so
```

I can confirm that CUDA on wsl2 works correctly, both before and after upgradation. But I haven't test whether DirectML on wsl2 works correctly.

**Comment by dag03tsc** [comment] 2021-01-25 22:17
Same here but it's getting worse and worse with each upgrade since then.

Should we manually remove those extra files from the mirrored `C:\Windows\System32\lxss\lib` directory?

I guess this is due to some kind of rollback feature getting out of control.

It'd be useful to keep immediate previous versions for each of those libs between upgrades; if anything crashes, roll'em back and you're good to go.

But this is nonsense. Whenever there's an upgrade, the system clones those four libs (`libd3d12.so, libd3d12core.so, libdirectml.so and libdxcore.so`), but it doesn't remove old clones from previous upgrades, hence the nonsense buildup of duplicates.

I guess the expected behavior should be, in fact, the one you provided as actual. For the sake of _rollbackness_ (is that even a word?!? 😄), it should keep two versions of each library; current and previous, therefore `libd*.so` and `libd* (1).so`. But my actual behavior seems to be clearly bugged. Is this happening to you too? Does your old clones persist between upgrades?

# Environment
```
Windows build number: Version 10.0.21296.1000
Your Distribution version: Ubuntu 20.10
Whether the issue is on WSL 2 and/or WSL 1: WSL 2
```
# Libraries
```
user@computer:~$ ls /usr/lib/wsl/lib -l
total 436860
-r--r--r-- 1 root root   124664 Sep 17 10:24  libcuda.so
-r--r--r-- 1 root root   785480 Dec  8 19:20 'libd3d12 (10).so'
-r--r--r-- 1 root root   785480 Dec 10 15:29 'libd3d12 (11).so'
-r--r--r-- 1 root root   785480 Dec  8 11:34 'libd3d12 (12).so'
-r--r--r-- 1 root root   785480 Dec 19 10:31 'libd3d12 (13).so'
-r--r--r-- 2 root root   785480 Jan  9 12:18 'libd3d12 (14).so'
-r--r--r-- 1 root root   832936 Sep 12 20:47 'libd3d12 (1).so'
-r--r--r-- 1 root root   832936 Sep 27 01:24 'libd3d12 (2).so'
-r--r--r-- 1 root root   832936 Oct  3 20:10 'libd3d12 (3).so'
-r--r--r-- 1 root root   832936 Oct 11 01:12 'libd3d12 (4).so'
-r--r--r-- 1 root root   785144 Oct 26 00:04 'libd3d12 (5).so'
-r--r--r-- 1 root root   785144 Oct 31 19:44 'libd3d12 (6).so'
-r--r--r-- 1 root root   785144 Nov  7 18:34 'libd3d12 (7).so'
-r--r--r-- 1 root root   785144 Nov 14 20:53 'libd3d12 (8).so'
-r--r--r-- 1 root root   785480 Nov 25 19:12 'libd3d12 (9).so'
-r--r--r-- 1 root root  5300896 Dec  8 19:20 'libd3d12core (10).so'
-r--r--r-- 1 root root  5300896 Dec 10 15:29 'libd3d12core (11).so'
-r--r--r-- 1 root root  5344600 Dec  8 11:34 'libd3d12core (12).so'
-r--r--r-- 1 root root  5345336 Dec 19 10:31 'libd3d12core (13).so'
-r--r--r-- 2 root root  5346360 Jan  9 12:18 'libd3d12core (14).so'
-r--r--r-- 1 root root  5073944 Sep 12 20:47 'libd3d12core (1).so'
-r--r--r-- 1 root root  5115392 Sep 27 01:24 'libd3d12core (2).so'
-r--r--r-- 1 root root  5115392 Oct  3 20:10 'libd3d12core (3).so'
-r--r--r-- 1 root root  5119496 Oct 11 01:12 'libd3d12core (4).so'
-r--r--r-- 1 root root  5300896 Oct 26 00:04 'libd3d12core (5).so'
-r--r--r-- 1 root root  5300896 Oct 31 19:44 'libd3d12core (6).so'
-r--r--r-- 1 root root  5300896 Nov  7 18:34 'libd3d12core (7).so'
-r--r--r-- 1 root root  5300896 Nov 14 20:53 'libd3d12core (8).so'
-r--r--r-- 1 root root  5300896 Nov 25 19:12 'libd3d12core (9).so'
-r--r--r-- 2 root root  5346360 Jan 16 10:59  libd3d12core.so
-r--r--r-- 2 root root   785480 Jan 16 10:59  libd3d12.so
-r--r--r-- 1 root root 25263616 Dec  8 19:20 'libdirectml (10).so'
-r--r--r-- 1 root root 25263616 Dec 10 15:29 'libdirectml (11).so'
-r--r--r-- 1 root root 25263592 Dec  8 11:34 'libdirectml (12).so'
-r--r--r-- 1 root root 25263592 Dec 19 10:31 'libdirectml (13).so'
-r--r--r-- 2 root root 25263592 Jan  9 12:18 'libdirectml (14).so'
-r--r--r-- 1 root root 25069816 Sep 12 20:47 'libdirectml (1).so'
-r--r--r-- 1 root root 25074040 Sep 27 01:24 'libdirectml (2).so'
-r--r--r-- 1 root root 25263360 Oct  3 20:10 'libdirectml (3).so'
-r--r--r-- 1 root root 25263592 Oct 11 01:12 'libdirectml (4).so'
-r--r--r-- 1 root root 25263592 Oct 26 00:04 'libdirectml (5).so'
-r--r--r-- 1 root root 25263592 Oct 31 19:44 'libdirectml (6).so'
-r--r--r-- 1 root root 25263616 Nov  7 18:34 'libdirectml (7).so'
-r--r--r-- 1 root root 25263616 Nov 14 20:53 'libdirectml (8).so'
-r--r--r-- 1 root root 25263616 Nov 25 19:12 'libdirectml (9).so'
-r--r--r-- 2 root root 25263592 Jan 16 10:59  libdirectml.so
-r--r--r-- 1 root root   827632 Dec  8 19:20 'libdxcore (10).so'
-r--r--r-- 1 root root   827632 Dec 10 15:29 'libdxcore (11).so'
-r--r--r-- 1 root root   827904 Dec  8 11:34 'libdxcore (12).so'
-r--r--r-- 1 root root   827904 Dec 19 10:31 'libdxcore (13).so'
-r--r--r-- 2 root root   827904 Jan  9 12:18 'libdxcore (14).so'
-r--r--r-- 1 root root   878768 Sep 12 20:47 'libdxcore (1).so'
-r--r--r-- 1 root root   878768 Sep 27 01:24 'libdxcore (2).so'
-r--r--r-- 1 root root   878768 Oct  3 20:10 'libdxcore (3).so'
-r--r--r-- 1 root root   878768 Oct 11 01:12 'libdxcore (4).so'
-r--r--r-- 1 root root   827632 Oct 26 00:04 'libdxcore (5).so'
-r--r--r-- 1 root root   827632 Oct 31 19:44 'libdxcore (6).so'
-r--r--r-- 1 root root   827632 Nov  7 18:34 'libdxcore (7).so'
-r--r--r-- 1 root root   827632 Nov 14 20:53 'libdxcore (8).so'
-r--r--r-- 1 root root   827632 Nov 25 19:12 'libdxcore (9).so'
-r--r--r-- 2 root root   827904 Jan 16 10:59  libdxcore.so
-r--r--r-- 1 root root 40980456 Sep 17 10:24  libnvwgf2umx.so
```

**Comment by FanShupei** [comment] 2021-01-26 07:27
I observe exactly the same thing on my computer, the file list becomes longer after installing a upgrade. Your analysis sounds plausible.

Though the mechanism looks smelly, I never encounter a real function break during my several month's use. So I guess the bug won't really harm if you **never rollback**. 

Maybe someone could rollback and then see whether correct files are restored, to see whether it's a real bug.

**Comment by dag03tsc** [comment] 2021-01-31 04:35
Then we're experiencing the same issue for sure. Let's hope @craigloewen-msft rises this asap because there're currently 500MB of clones and it's rising about 30MB with each upgrade. It doesn't seem a lot but it's a useless waste of space.

I can't tell for sure but I'd say libs are identified by the file name. Therefore, in theory, one could perform a manual rollback by just switching the name of a file with its chosen clone counterpart and rebooting the WSL (`wsl --shutdown`). E.g., renaming `libd3d12.so` to `libd3d12.so.old` and `libd3d12 (1).so` to `libd3d12.so`.

Anytime a dist cold-starts, it links all libs found inside the directory `/usr/lib/wsl/lib` (mirror of `%WINDIR%\System32\lxss\lib`) but I guess it ignores all `lib* (*).so` clones. So, in theory, one could perform the manual rollback explained above.

**Comment by dag03tsc** [comment] 2021-04-25 22:27
@craigloewen-msft , do you have any news about this?

BTW, WSLg is awesome! Congratulations to you and the team! 👏

**Comment by FanShupei** [comment] 2021-05-01 06:23
In https://blogs.windows.com/windows-insider/2021/04/29/announcing-windows-10-insider-preview-build-21370/
I found 'We fixed OS upgrades creating copies of libdxcore.so and other files when using the Windows Subsystem for Linux.'

Is the problem solved?

**Comment by craigloewen-msft** [comment] 2021-05-04 20:01
This is fixed in the latest Windows Insider build [21370](https://blogs.windows.com/windows-insider/2021/04/29/announcing-windows-10-insider-preview-build-21370/)! 

(Beat me to it @FanShupei , thank you :) )

**Closed by craigloewen-msft** 2021-05-04 20:01 UTC
Labels: GPU

**Comment by dag03tsc** [comment] 2021-05-05 08:18
Nice! I really appreciate!

I've upgraded to 21370 and there's no newer clones, so it seems to be fixed. Anyway, I'll check it again with the next build, just to make sure.

Unfortunately, former clones remain there. @craigloewen-msft , is it right to manually erase them or should we wait for them to be autopurged by any future build?

**Comment by dag03tsc** [comment] 2021-05-11 16:35
Nevermind! The newer 21376 build purges stalled clones.

Thanks a lot!
