### ISSUE TITLE
Error Running Ubuntu

### ISSUE THREAD

**Issue by Code-You-Fools** [microsoft/WSL#2938] opened 2018-02-12 17:23 UTC
* Your Windows build number:  Win 10 Education v1709, build 16299.192

* What you're doing and what's happening:  Installing 'Ubuntu' from the Windows Store, after installing WSL and rebooting - clicking the 'Ubuntu' shortcut in the Start menu produces an error claiming that Windows can't find "C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.92...\ubuntu.exe", entering 'ubuntu' into the Run dialog claims that Windows can't find 'C:\Users\[my name]\AppData\Local\Microsoft\WindowsApps\ubuntu.exe'. Both directories exist and contain 'ubuntu.exe' - the one in %localappdata% has a size of 0kb and produces the same error, while opening the one in Program Files produces a command prompt-like screen that attempts to install Ubuntu, fails, and produces error code 80070005.

* What's wrong / what should be happening instead: Supposedly, doing any one of these would launch a bash shell.

I've tried uninstalling/reinstalling WSL with no success. Using the legacy version (running bash.exe) functions fine.

**Comment by benhillis** [comment] 2018-02-13 17:17
Would it be possible for you to collect logs when trying to launch the app?

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by WalnutBunny** [comment] 2018-02-13 20:22
Here are the logs - the ones labeled 'startmenu' are the result of launching Ubuntu from the shortcut created in the Start menu, and the ones labeled 'run' are the result of running the 'ubuntu' command.
[lxcore.zip](https://github.com/Microsoft/WSL/files/1721565/lxcore.zip)

**Comment by benhillis** [comment] 2018-02-13 22:49
@WalnutBunny - Thanks for posting the logs.  Unfortunately there are no events from any of our providers in the logs.  Have you checked the Windows Event Viewer to see if there are any relevant errors there?

**Comment by WalnutBunny** [comment] 2018-02-13 23:49
Each launch generates two AppModel-Runtime errors, IDs 208 and 216. Event 216 says "0x80070002: Cannot create the Desktop AppX container for package CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc because an error was encountered configuring the runtime." and 208 says "0x80070002: Cannot create the process for package CanonicalGroupLimited.UbuntuonWindows_1604.2017.922.0_x64__79rhkp1fndgsc because an error was encountered while configuring runtime. [LaunchProcess]"

**Comment by WalnutBunny** [comment] 2018-02-24 02:51
@benhillis any ideas what's causing this problem?

**Comment by cdenneen** [comment] 2018-02-28 23:21
I have similar problem... Had fresh install of 
`Microsoft Windows [Version 10.0.16299.248]`
Everything was working fine. Then had some issues with testing `wslbridge` and decided to just uninstall WSL, Ubuntu, and all remaining files.
Followed the helpful guides for 0x80070005.

I reinstall WSL and Ubuntu but Ubuntu fails.
I have been able to do `lxrun /install /y` from Administrative prompt (not normal prompt)
I've been able to setdefaultuser to something other than root (otherwise bash.exe drops me directly as root user).

But every time I try to click on Ubuntu tile it gives me failure error above.
```
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
```
It seems like an "Elevated issue"... 

However if I run bash.exe directly or click on `Bash on Ubuntu on Windows` tile my bash prompt works.
How do I get the Ubuntu tile to work or how do I debug it to provide necessary logging information.

--- 
So while writing this I had a few other ideas to try... 

In the thought that it was elevated issue if I click on the Ubuntu tile and right click "Run as Administrator it now runs with `Installing, this may take a few minutes`. Then asks for username and password and drops to bash prompt... 

Now if I click on the Ubuntu tile it works without elevation and no error.

I know it's working but i'm more confused than ever... any ideas?

**Comment by cdenneen** [comment] 2018-02-28 23:32
There is still something wrong with this "working" install because now if I close a session that I ran `service ssh --full-restart` sshd dies again... 

What would be the proper steps to uninstall cleanly and reinstall with `lxrun /install /y` from an "UnElevated prompt" or from the "Ubuntu" tile from the Windows Store?

**Comment by benhillis** [comment] 2018-03-01 20:04
@cdenneen - if you're installing a distro from the store you can ignore lxrun completely.  Uninstalling the store app via right clicking the tile is all you need to do.

**Comment by cdenneen** [comment] 2018-03-01 20:53
@benhillis As I mentioned above the uninstall didn't work properly.
I "Uninstalled Ubuntu" and Removed the WSL Feature.
But still was having issues "reinstalling Ubuntu" kept failing with 

```
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue..
```

Then I tried to install via lxrun but was getting same issue...
Then tried lxrun from Admin prompt and it worked but when running bash.exe would end up as `root@COMPUTER`. So run the `setdefaultuser` and then `chris@COMPUTER` worked.

Tried the Ubuntu tile again but same "error"
Ran the Ubuntu tile as **Administrator** and it worked.
Ran the Ubuntu tile again as **normal user** and now worked.

I'm curious as it appears I had to do some stuff as "Elevated" user rather than Install Ubuntu tile from store as normal user. Is there some cleaner way to "uninstall" that reinstall will work without elevated/admin prompt? I verified after all uninstall the LXSS was gone.

**Comment by benhillis** [comment] 2018-03-01 21:24
@cdenneen - This is not intended behavior. Uninstalling and reinstalling the app via the tile (or selecting "Reset" in Ubuntu settings) is the correct way to uninstall.  You don't need to disable the subsystem feature.  If you're able to get into this state again taking a trace would be useful:

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by cdenneen** [comment] 2018-03-01 22:51
So I wiped again and here is results.
I've installed Ubuntu from Windows Store
Clicked Launch and received:

```
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
```

I actually still had ConEmu installed so tried launching bash.exe from there with the following error displayed:

```
wslbridge error: failed to start backend process
note: bash.exe output: Error: 0x80070003


ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...
```

and from Powershell I get:

```
PS C:\Users\cdenneen> bash.exe
Error: 0x80070003
Press any key to continue...
```






[lxcore_trace.zip](https://github.com/Microsoft/WSL/files/1773061/lxcore_trace.zip)

**Comment by cdenneen** [comment] 2018-03-01 22:54
@benhillis I tried the **detailed-logs** post and got the following so hopefully the above works as well:

```
PS C:\Users\cdenneen\Downloads> logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749843B3F5C9} -mode 0x00000008 -ft 10:00 -o .\lxcore_kernel.etl -ets logman.exe : A value that is not valid (.\lxcore_kernel.etl) was specified for the outputFormat parameter. Valid values are Text and Xml.
At line:1 char:1
+ logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter

PS C:\Users\cdenneen\Downloads> logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749843B3F5C9} -mode 0x00000008 -ft 10:00 -o .\lxcore_kernel.etl -ets
```

**Comment by benhillis** [comment] 2018-03-01 23:00
@cdenneen - Run the command in cmd.exe, not powershell.

**Comment by cdenneen** [comment] 2018-03-01 23:07
@benhillis Thanks... here it is
[lxcore_kernel.zip](https://github.com/Microsoft/WSL/files/1773098/lxcore_kernel.zip)

**Comment by benhillis** [comment] 2018-03-01 23:09
@cdenneen  - Took a look at your trace and somehow the on your system your non-admin user account does not have write access to %TEMP%.  I have not seen this in the past.  Luckily the way we extract tar files has changed so this will no longer be a problem when the next version of Windows ships.  In the meantime as a workaround launching Ubuntu.exe as admin will work.

**Comment by cdenneen** [comment] 2018-03-01 23:33
I was able to delete %TEMP% with no issue.
Here is another trace:

[lxcore_user.zip](https://github.com/Microsoft/WSL/files/1773161/lxcore_user.zip)

**Comment by benhillis** [comment] 2018-03-01 23:36
I'll reiterate - this has already been fixed in Insider builds and will be available when the next official Windows release ships.

**Comment by WalnutBunny** [comment] 2018-03-01 23:38
@benhillis are you talking about my problem or the one @cdenneen brought up?

**Comment by WalnutBunny** [comment] 2018-03-01 23:40
@benhillis I'm confused - is my problem being fixed with the FCU or no?

**Comment by benhillis** [comment] 2018-03-01 23:41
@WalnutBunny - It's unclear to me what your problem is.  Based on your event log entries it looks like there is an issue before WSL is even involved.

**Comment by cdenneen** [comment] 2018-03-02 00:51
@benhills I understand the way  extraction of files handle is changed in new builds (going by latest still available) but the original install worked so why doesn’t it work anymore. Also the fact that %TEMP% can be deleted was hoping for something else in second capture because that permission issue appears false.

**Comment by cdenneen** [comment] 2018-03-02 02:53
@benhillis So I ran the Ubuntu install as "Administrator" to get around the install issue.
I was able to run and install packages. Looked like all was well (still unsure why it had to be installed with Elevated permissions when it didn't the first install, but anyway).
I then tried to launch bash.exe from cmd.exe and Command Prompt as Administrator and from "Bash on Ubuntu on Windows" (both as normal user and "run as administrator") and all yielded the same error.

Here is screenshot and new capture.

[trace.zip](https://github.com/Microsoft/WSL/files/1773519/trace.zip)
Top shows the "Ubuntu tile works now after running initially as Administrator to complete the install" but all others are failing with same message `Error: 0x80070003`.
![capture](https://user-images.githubusercontent.com/720097/36881090-5552a0fc-1d9a-11e8-99ee-d9be6e1f1347.PNG)

Only reason I am bringing this up is since I can't run `bash.exe` (or `wsl.exe` for that matter) directly I can't access it via VSCode Terminal, cmder, ConEmu, etc.

Please let me know if there is any other information I can provide or test I could run.

Thanks

**Comment by swarfega** [comment] 2018-03-10 09:37
Hello. I have been having problems with installing the new Debian WSL. It installs ok but errors when I set up the user. Please see screenshots. I have been in conversation with Rich Turner on Twitter regarding this issue. See http://bit.ly/2HinASH. Please see screenshot.
![debianwsl](https://user-images.githubusercontent.com/2217248/37240651-7dea69ac-2446-11e8-924c-c33b1951e93b.PNG)

I have tried this on FCU 16299 and Insider skip-ahead 17618 on two different machines.

**Comment by swarfega** [comment] 2018-03-11 21:35
I have managed to fix this issue. What was causing it was I had moved the save location of apps in settings to F: which apparently it doesn't like. Perhaps a fix for that?

**Comment by cdenneen** [comment] 2018-03-16 14:48
@benhillis so went to Store and installed Debian and Kali (first time downloading and installing).
Once downloaded and installed I ran from Start Menu and got the same error above.
I ran both as Administrator to complete the install (enter username/password). So it's not just happening on a "reinstall" of Ubuntu but even fresh installs of any new Linux as well.

I agree its a permission issue as you mentioned but I don't know how to reach those trace files in order to determine where and %TEMP% seems to be just fine for my user not elevated to delete content in. (from CMD just created a file and deleted file in %TEMP% with no issues.)

**Comment by DarthSpock** [comment] 2018-04-18 13:40
@sean-mcmanus I would recommend RS4 once it's officially released. However it appears this issue is being observed by some when attempting to launch the Store version from a drive other than the system drive, which isn't supported due to the UWP infrastructure being utilized and the UWP team hasn't addressed that issue yet. Verify that your appx is installed on your system drive usually C:\. Alternatively you could build your own appx for any distro of choice using the WSL-DistroLauncher project. This should allow you to install to a different drive and prevent the Error: 0x80070005 issue.

**Comment by therealkenc** [comment] 2021-02-25 22:20
This issue went stale without a local repro, and the `lxrun.exe` app has been deprecated in favor of `wsl.exe`. If the problem persists on Windows 20H2 aka 19042 (or better), please open a new issue following the issue template and include [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs), catching the `0x80070005` or ` "0x80070002` from `wsl.exe` if it persists.

**Closed by therealkenc** 2021-02-25 22:20 UTC
