### ISSUE TITLE
install on server problem

### ISSUE THREAD

**Issue by xtoolkit** [Microsoft/WSL#3145] opened 2018-05-03 17:57 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.1]

hi, i install wsl (ubunbu) on server with this guide: [install-on-server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server)
wsl good work, but when shutdown and turn on, wsl has error:
```
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
```
and i have to install again wsl and install my dpkg ...
Is there a solution?
sry 4 my bad english

**Comment by jaredlt** [comment] 2018-05-23 08:06
For your reference, I got this this morning when I turned my computer on. AFAIK there was no Windows update so I was a bit perplexed as to what had caused it.

On the advice of this comment https://www.reddit.com/r/bashonubuntuonwindows/comments/8j5igr/subsystem_using_lxss_folder_broke_today/dyx9ubu/ I just rebooted my computer (literally did nothing else) and that fixed it.

Still have no idea what caused it.

Win 10 Version	10.0.17134 Build 17134

**Comment by Biswa96** [comment] 2018-05-23 08:11
Possible cause:
1. Lxss registry may be removed.
2. The rootfs folder may be deleted.
3. That folder permission may be changed temporarily.

**Comment by benhillis** [comment] 2018-06-20 21:22
This is a duplicate of #2576.

**Closed by benhillis** 2018-06-20 21:22 UTC
