### ISSUE TITLE
Attempting to upgrade ansible with pip results in a segfault

### ISSUE THREAD

**Issue by akulbe** [microsoft/WSL#4703] opened 2019-11-21 18:36 UTC
Your Windows build number:  Microsoft Windows [Version 10.0.19028.1]

What I'm attempting to do? Upgrade ansible to the latest release, in WSL - Ubuntu-18.04

➜  ~ pip3 install --upgrade ansible
Collecting ansible
Collecting cryptography (from ansible)
  Using cached https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl
Collecting PyYAML (from ansible)
Collecting jinja2 (from ansible)
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->ansible)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->ansible)
  Using cached https://files.pythonhosted.org/packages/49/72/0d42f94fe94afa8030350c26e9d787219f3f008ec9bf6b86c66532b29236/cffi-1.13.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting MarkupSafe>=0.23 (from jinja2->ansible)
  Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->ansible)
Installing collected packages: six, pycparser, cffi, cryptography, PyYAML, MarkupSafe, jinja2, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.1.2 ansible-2.9.1 cffi-1.13.2 cryptography-2.8 jinja2-2.10.3 pycparser-2.19 six-1.13.0
[1]    348 segmentation fault  pip3 install --upgrade ansible

* What's wrong / what should be happening instead: I should be able to upgrade ansible via pip, and no segfault occur.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

I have run an strace, and the resulting output is 50MB. When trying to create a gist for it, the site times out. it's over 521K lines. I put the text file in my OneDrive. https://1drv.ms/u/s!ApEXGJp7Ipuxk6VuHyJRU40vozTV8A?e=WUB9Xc

**Comment by sirredbeard** [comment] 2019-11-21 22:41
So I did this in an an attempt to reproduce:

1. `sudo apt-get install python3-pip`
2. `pip3 install pip --upgrade`
3. then ran into this issue https://github.com/pypa/pip/issues/5447#issuecomment-408849802 fixed with `sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall`
4. `pip3 install ansible`

Resulting in:

```
Installing collected packages: PyYAML, pycparser, cffi, six, cryptography, MarkupSafe, jinja2, ansible
Successfully installed MarkupSafe-1.1.1 PyYAML-5.1.2 ansible-2.9.1 cffi-1.13.2 cryptography-2.8 jinja2-2.10.3 pycparser-2.19 six-1.13.0
```

How do you have pip/pip3 configured?

**Comment by akulbe** [comment] 2019-11-21 22:50
I had simply installed it with apt, like you did. 

`apt -y install python3-pip`

**Comment by therealkenc** [comment] 2019-11-22 17:21
> Microsoft Windows [Version 10.0.19028.1]

Assume we're talking WSL2 here. In which case this thread is likely going to converge linux userspace behavior.

> I have run an strace, and the resulting output is 50MB. When trying to create a gist for it, the site times out. it's over 521K lines.

Anything north of the string "Successfully installed MarkupSafe-1.1.1" can be deleted from the trace (which will probably be most of it). You could in principle fire it up under `gdb` and grab the backtrace; although this is sometimes a nontrivial exercise. Both data points might get more eyeballs in a Python forum. That segv is going to be deep down in a Python wrapper, most likely.

**Comment by therealkenc** [comment] 2019-11-22 17:27
ref [this](https://github.com/ansible/ansible/issues/30591) and [this](https://github.com/pyca/cryptography/issues/3815). Which might or might not point to cause/solution (probably not).  But the latter does point to some debug strategies.

**Comment by therealkenc** [comment] 2021-05-10 22:11
This submission could not be reproduced locally. If the problem persists on WSL2 1904[23], please open a new ticket following the template, including detailed CLI steps to manifest the problem. #3815 suggests the problem is/was external.

![image](https://user-images.githubusercontent.com/7049700/117730715-a91c7e80-b1a1-11eb-81fa-04d2a5a4a472.png)

**Closed by therealkenc** 2021-05-10 22:11 UTC
