### ISSUE TITLE
Node.js core dumped when require files from symlink at Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by jerrywdlee** [Microsoft/WSL#2359] opened 2017-07-20 16:04 UTC
* **Node.js Version**: 8.1.3
* **Platform**: Bash on Ubuntu on Windows ( Ubuntu 14.04.5 LTS / Windows10 64-bit ) (Japanese)
* **Windows build number**: Microsoft Windows [Version 10.0.14393]
* **Subsystem**: [module](https://nodejs.org/dist/latest-v8.x/docs/api/modules.html#modules_module)

I created a Symbolic link under `node_modules` via `create_root_path.js` below.
Then run `require_func.js` to require `test_func.js` from different ways.
It worked well on MacOS, Ubuntu(vagrant) and Windows, but core dumped at Bash on Ubuntu on Windows.

#### Scripts:
```create_root_path.js
// create_root_path.js

const fs = require('fs');
// create symlink from ../ to node_modules/ROOT_PATH
try {
  fs.unlinkSync('node_modules/ROOT_PATH');
} catch (e) {
  console.error(e);
}
try {
  fs.symlinkSync('../', 'node_modules/ROOT_PATH', 'dir');
} catch (e) {
  console.error(e);
}
```

```require_func.js
// require_func.js

const test_func1 = require('./test_func');
const test_func2 = require('ROOT_PATH/test_func');
const test_func3 = require(__dirname + '/test_func');

console.log('test_func1.a', test_func1.a);
console.log('test_func2.a', test_func2.a);
console.log('test_func3.a', test_func3.a);
test_func1.increase_a();
console.log('test_func1.a', test_func1.a);
console.log('test_func2.a', test_func2.a);
console.log('test_func3.a', test_func3.a);

/*
  Response:
  test_func1.a 1
  test_func2.a 1
  test_func3.a 1
  test_func1.a 2
  test_func2.a 2
  test_func3.a 2
*/
```

```test_func.js
// test_func.js

module.exports = {
  a: 1,
  increase_a: function () {
    this.a ++;
  },
};
```

#### Core Dump:
```
$ node require_func.js 
/home/USER_NAME/.nodenv/versions/8.1.3/bin/node[845]: ../src/node_file.cc:527:void node::InternalModuleReadFile(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(numchars) 
>= (0)' failed.
 1: node::Abort() [node]
 2: node::Assert(char const* const (*) [4]) [node]
 3: 0x13a045a [node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 5: 0xb43f48 [node]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x81be2e8437d
中止 (コアダンプ)
```

**Comment by benhillis** [comment] 2017-07-28 16:18
@jerrywdlee - There have been massive changes since Anniversary Update, would it be possible for you to upgrade to Creator's Update and see if you still have the same issues.  I know we vastly improved node support.

**Comment by therealkenc** [comment] 2017-12-01 22:45
Confirmed the OP test case works in recent WSL; I used FCU+ but I am sure at least Creators would work too. We'll never know what the problem was here because no `strace`. Closing.

**Closed by therealkenc** 2017-12-01 22:45 UTC
