### ISSUE TITLE
Unable to manually change system time in WSL: automatic sync with Windows overrides changes

### ISSUE THREAD

**Issue by abtswath** [microsoft/WSL#11318] opened 2024-03-18 02:50 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3296]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1

### Distro Version

Debian GNU/Linux 12

### Repro Steps

I changed the system time to test a program.

1. Turn off the automatic time sync service, like `systemd-timesyncd`.
2. Use the `date -s` command or `timedatectl set-time` command to modify the time.

### Expected Behavior

I'm not entirely sure if this really counts as a problem because I found out it's actually a [patch](https://lore.kernel.org/linux-hyperv/20231127213524.52783-1-pmartincic@linux.microsoft.com/T/#u) introduced to fix issue #10006. Also, when I set the kernel parameter hv_utils.timesync_implicit=0, the time won't automatically sync with Windows time.

### Actual Behavior

A few seconds later, check the current time using the `date` command, the system time gets synced back to the Windows time.

**Comment by pmartincic** [comment] 2024-03-19 21:07
As you noticed, we changed things. I'm glad you found `hv_utils.timesync_implicit=0` but I'm going to close this as by design. In an ideal world the hypervisor would have been patched, and you wouldn't notice this till a major power event happens.

**Closed by pmartincic** 2024-03-19 21:07 UTC
