### ISSUE TITLE
WSL hangs when deleting a file behind a Windows junction

### ISSUE THREAD

**Issue by BladeMF** [Microsoft/WSL#2746] opened 2017-12-11 20:06 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.16299.64

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Executing `unlink /mnt/d/Documents/VS2017/g.txt` hangs WSL. In the command: `/mnt/d/Documents/VS2017` is a junction pointing to `/mnt/d/Documents/Visual Studio 2017`, `g.txt` is a plain text file created with a previous command.

* What's wrong / what should be happening instead:
The file should've been deleted.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)
N/A

* Notes
The same command does not hang WSL when the path is the original one (without the junction). After the WSL hangs, there is no other option except restarting the computer.

**Comment by benhillis** [comment] 2018-07-10 23:35
I was not able to reproduce this in 17711, and I suspect this is fixed in 1803 (17134).  Please reopen if you can hit this on 1803.

**Closed by benhillis** 2018-07-10 23:35 UTC
