### ISSUE TITLE
cp -p not preserving date and time

### ISSUE THREAD

**Issue by cmendl** [Microsoft/WSL#1939] opened 2017-04-17 21:21 UTC
Microsoft Windows [Version 10.0.14393]

Copying files using cp -p does not retain date of source file (on Windows filesystem)

user@SCHORSCH:/mnt/c/tmp$ cp -p foo.txt foe.txt
user@SCHORSCH:/mnt/c/tmp$ ls -la
total 28
drwxrwxrwx 2 root root 0 Apr 17 14:17 .
drwxrwxrwx 2 root root 0 Apr 17 14:16 ..
-rwxrwxrwx 1 root root 7 Apr 17 14:17 foe.txt
-rwxrwxrwx 1 root root 7 Apr 17 14:16 foo.txt

Copied file "foe.txt" should have date and time of source file "foo.txt", but instead gets assigned current time.

**Comment by stehufntdev** [comment] 2017-04-18 16:43
Are you seeing the same behavior in lxfs (e.g. root directory) or just in drvfs?  IIRC, we recently found an issue with drvfs timestamps but I'll double check.

**Comment by cmendl** [comment] 2017-04-18 20:02
I'm seeing the issue only when copying files within the windows filesystem; cp -p works as expected within my home directory of the bash shell, and also when copying a file form the windows filesystem into my home directory.

Chris

**Comment by SvenGroot** [comment] 2017-04-18 20:32
This is due to the way that Windows updates timestamps, which it only does when the handle closes. When you use "cp -p" it opens the target file, writes to it, sets the timestamp, then closes it. Setting the timestamp doesn't use the same handle due to our VFS design, so when the file is closed Windows updates the timestamp again because that handle was written to.

We're working on ways to mitigate this issue.

**Comment by sunjoong** [comment] 2017-04-28 00:33
@SvenGroot - Because `make` is a timestamp based utility, it would be problem. I hope it will be fixed soon.

**Comment by jstarks** [comment] 2017-12-19 22:14
This should be fixed in [insider build 17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes).

**Closed** 2018-05-24 22:00 UTC
Labels: bug, fixedininsiderbuilds

**Comment by michael-ts** [comment] 2022-09-13 20:58
@jstarks I'm seeing this bug in the WSL(2) in Windows 10, however the issue is that while the seconds part of the timestamp is preserved, the milliseconds part is zeroed out in the destination file.
