### ISSUE TITLE
interop pipe of special exe programs breaks on Windows 10 build 16170

### ISSUE THREAD

**Issue by gdh1995** [Microsoft/WSL#1912] opened 2017-04-14 08:07 UTC
On the newest Windows 10 Insider Preview build 16170 for PC (x64), I find some programs like `ping.exe` and `route.exe` can only work on `cmd.exe` and `powershell`, but them fail to work on the WSL bash and my `bash.exe`  of `msys2.

The problem is their output stream (pipe) breaks on WSL bash.

```
gdh1995@gdh-server:/mnt/c/Users/gdh1995$ /mnt/d/sft/pscp.exe --version
pscp: Development snapshot 2017-01-21.73e5b6d
Build platform: 32-bit Windows
Compiler: Visual Studio 2015 / MSVC++ 14.0 (_MSC_VER=1900)
Source commit: 73e5b6db25f4f2e3b3a52744d0a8df5acc98ef4d
gdh1995@gdh-server:/mnt/c/Users/gdh1995$ /mnt/c/Windows/System32/PING.EXE
bash: /mnt/c/Windows/System32/PING.EXE: 输入/输出错误
gdh1995@gdh-server:/mnt/c/Users/gdh1995$ export LANG=en_US.utf8
gdh1995@gdh-server:/mnt/c/Users/gdh1995$ /mnt/c/Windows/System32/PING.EXE
bash: /mnt/c/Windows/System32/PING.EXE: Input/output error
gdh1995@gdh-server:/mnt/c/Users/gdh1995$
```

And, on my msys2 `bash.exe`, system commands like `ping`, `ipconfig` and `route` output nothings, without the `Input/output error` message on WSL bash.

All 3rd-party command-line programs like my `pscp` work well on all shells. I don't know why `ping.exe` fails.

**Comment by benhillis** [comment] 2018-01-29 19:53
I believe this was a duplicate of #2096, please let me know if you're still seeing issues.

**Closed by benhillis** 2018-01-29 19:53 UTC
