### ISSUE TITLE
Annoying highlighting which ruins visibility

### ISSUE THREAD

**Issue by dehlong** [microsoft/WSL#10484] opened 2023-09-17 19:37 UTC
### Windows Version

Microsoft Windows [Version 10.0.19044.3448]

### WSL Version

Invalid command line option: --version

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Go to a folder which has a subfolders, Run cd+TAB and you will see stupid folder highlighting:
![image](https://github.com/microsoft/WSL/assets/112163027/5f4056af-7f1b-48a4-a964-25b660e4e9a9)

### Expected Behavior

No highlight, just different color like in ls after fix:
![image](https://github.com/microsoft/WSL/assets/112163027/506c628d-f357-4710-ad98-98884e794d97)

### Actual Behavior

Highlighting that makes folders' names impossible to read:
![image](https://github.com/microsoft/WSL/assets/112163027/5f4056af-7f1b-48a4-a964-25b660e4e9a9)

I have already managed to remove this thing for ls but it appears even with cd and no resources online mention the fix. I consider this a bug because it makes folders' names impossible to read with most popular terminal themes such as Nord, Gruvbox, Catpuccin, material, etc.

**Comment by elsaco** [comment] 2023-09-17 22:48
@dehlong Ubuntu has `ls` aliased to `ls --color=auto`. In a shell run `type ls` and you'll get `ls is aliased to 'ls --color=auto'` most likely. The `stupid folder highlights` are telling you those are directories and depending on you color scheme it could be hard to read. You get the same directory highlight when running  `ls` in a powershell session. Use `ls --color=never` to hide them when running `ls`.

**Comment by OneBlue** [comment] 2023-09-18 18:41
Indeed these directory are highlighted that way by design. To work around it I'd recommend switching your color theme or looking into [overriding colors](https://askubuntu.com/questions/466198/how-do-i-change-the-color-for-directories-with-ls-in-the-console).

Closing since this is by design.

**Closed by OneBlue** 2023-09-18 18:41 UTC
