### ISSUE TITLE
Ubuntu 20.04 LTS installation fails, PC freezes & restarts after launching ubuntu, no error code

### ISSUE THREAD

**Issue by simon-eda** [microsoft/WSL#6761] opened 2021-04-05 17:47 UTC
Dear All, 
i recently upgraded to Win 10 Version Dev (Build 21343.1000). 
i followed your guidance to install WSL2 and Ubuntu. https://docs.microsoft.com/de-de/windows/wsl/install-win10

after installing Ubuntu 20.04 LTS (or ver 18) from microsoft store, the ubuntu window opens displaying "ubuntu installing. this will take a few minutes...". Than the PC freezes and restarts. when i retry to open ubuntu, same error occurs. 
There is no error code shown. 

deinstallation and reinstallation of WSL does not help. 
automatic or manual installation does not make a difference. 

Can you please help to indentify the issue and to fix it? 

Many thanks,
Simon

**Comment by adrastogi** [comment] 2021-04-05 18:50
Thanks for reporting this. Can you please [submit logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs)?

**Comment by simon-eda** [comment] 2021-04-05 18:57
Hi, many thanks for immediate Reply. Which log file would be most helpful and where to find it? Best,simon  From: adrastogiSent: Montag, 5. April 2021 20:50To: microsoft/WSLCc: simon-eda; AuthorSubject: Re: [microsoft/WSL] Ubuntu 20.04 LTS installation fails, PC freezes & restarts after launching ubuntu, no error code (#6761) Thanks for reporting this. Can you please submit logs?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by craigloewen-msft** [comment] 2021-04-06 16:50
Potentially a dupe of this issue: https://github.com/microsoft/WSL/issues/5911

Please check that thread and see if any suggestions there resolve you!

**Comment by bpulliam** [comment] 2021-05-07 13:50
Without logs, we will assume that this was a duplicate of #5911

**Closed by bpulliam** 2021-05-07 13:50 UTC
Labels: duplicate
