### ISSUE TITLE
Failed to LLVM threadpool in WSL2

### ISSUE THREAD

**Issue by shjiyang-intel** [microsoft/WSL#11056] opened 2024-01-22 09:16 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.3007]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-microsoft-standard-WSL2

### Distro Version

Ubuntu-20.04

### Repro Steps

#include <llvm/Support/ThreadPool.h>
auto ctx = op->getContext();
auto& threadPool = ctx->getThreadPool();

### Expected Behavior

without error

### Actual Behavior

return error:
thirdparty/llvm-project/mlir/lib/IR/MLIRContext.cpp:601: llvm::ThreadPool& mlir::MLIRContext::getThreadPool(): Assertion `isMultithreadingEnabled() && "expected multi-threading to be enabled within the context"' failed.

### Diagnostic Logs

I am using MLIR and LLVM.
The function is fine in the original Ubuntu, but has issue only in WSL2. 
I have turned on `LLVM_ENABLE_THREADS` in CMake.
Does WSL2 need to set some extra configure to support llvm::threadPool?

**Comment by OneBlue** [comment] 2024-01-22 19:45
Closing since this issue doesn't seem to be caused by WSL.

**Closed by OneBlue** 2024-01-22 19:45 UTC
