### ISSUE TITLE
Couldn't detect the AVX2 instruction on Bash on Ubuntu!

### ISSUE THREAD

**Issue by nth2710** [microsoft/WSL#2234] opened 2017-06-19 07:55 UTC
Hi everybody,
I've an issue when using the Bash on Ubuntu on Window 10 (build 15063).
It's can't detect the AVX2 intruction, althought I used the Haswell chip.

> model name      : Intel(R) Xeon(R) CPU E3-1280 v3 @ 3.60GHz
stepping        : 3
microcode       : 0xffffffff
cpu MHz         : 3601.000
cache size      : 256 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand

The version of Bash is:

> Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Do you know How to solve this issue?

**Comment by therealkenc** [comment] 2017-06-19 09:33
Interestingly I get the same behavior in my VM too with stock Ubuntu and kernel 4.10.0-22-generic. So maybe it's non-obvious but correct Linux behavior. I have a Skylake and CPU-Z shows AVX2.

> Do you know How to solve this issue?

You didn't mention your use case, which helps the WSL people prioritize tracking the cause. Also someone may be able to offer a work-around.

**Comment by Yienschwen** [comment] 2017-09-23 11:52
I don't think it's correct Linux behavior. My laptop's CPU is i7-7500U, AVX2 and FMA is detected in both native Fedora 26 and Fedora 26 virtual machine running on VMware Workstation, but not detected in BashOnWindows.

**Comment by therealkenc** [comment] 2017-09-23 17:32
Yeah it's incorrect behaviour alright. I don't know (but would be academically curious to know) what makes it tough. I'm guessing it can't be bog-straightforward to implement or it would be already. Here's a random [query](https://askubuntu.com/questions/699077/how-to-enable-avx2-extensions-on-a-ubuntu-guest-in-virtualbox-5) related to Ubuntu on VirtualBox, which only "recently" (2016) gained AVX2 support. The [feature request](https://www.virtualbox.org/ticket/11347) took four years to close, but I have no idea whether that was because of the technical challenge or because of neglect. Or maybe the VM folks didn't want to flip the switch until they could emulate AVX2 in software on non-AVX2 chips, which is a different kettle. I'd like this too, because I think it will speed up llvmpipe a bit if it can detect support.

@benhillis is this doable, or intrinsically difficult?

**Comment by benhillis** [comment] 2017-09-23 19:19
We're probably just missing checking for the instruction when we generate the cpuinfo file.

**Comment by therealkenc** [comment] 2017-09-23 19:26
Hope it's that easy. :)

**Comment by sunilmut** [comment] 2017-09-25 17:33
@nth2710 - As @therealkenc mentions, it will be helpful for us to know if this is blocking any scenario for you (or what is the repro)? I am curious if the missing entry in `/proc/cpuinfo` is blocking anything.

**Comment by therealkenc** [comment] 2017-09-25 21:31
@sunilmut - It won't in general _hard_ block anything, since anything of a widely-released variety will fall back to a slow path when AVX2 is unavailable. So you could hypothesise a issue ticket like: "Software x.265 decoding slower on WSL than on Real Linux". Which, yeah.

Here's a Phoronix article where they [compare](https://www.phoronix.com/scan.php?page=article&item=ubuntu-wsl-opensuse&num=2) Himeno performance on WSL vs Linux:

> Himeno is one of the workloads where it's CPU bound but Windows 10 WSL is much slower than the native Linux installations. Himeno is AVX-heavy and it's possible under WSL that AVX is not working correctly or the like as a possible reason for the difference.

**Comment by therealkenc** [comment] 2018-02-15 01:12
SSE4A is also missing with no know blocking use cases as of this writing.

**Comment by bitcrazed** [comment] 2018-11-14 19:47
Filed internally: 19627559

**Comment by benhillis** [comment] 2018-11-14 19:57
Let's not post internal bug numbers, they are meaningless outside MSFT.

**Comment by mqudsi** [comment] 2019-02-07 19:02
@benhillis may I humbly inquire as to whether this is as simple as it outwardly seems to be, and would just require the addition of a new item in the list of cpu flags to copy over to `/proc/cpuinfo`? If it isn't insanely complicated and doesn't rely on a zillion other things, may I very meekly request that it be considered for inclusion in the next release?

As @honnibal says, there are quite a few number-crunching, *nix-only packages that we're now luckily able to run under WSL that would greatly benefit from being aware of the presence of certain CPU flags.

fwiw, if use of these instruction sets is gated at compile-time, it can be worked around by explicitly specifying compiler flags like `-march=native -msse4a -mavx2 -mfma -msha`, but that unfortunately doesn't work for programs that compile with the various codepaths enabled but dynamically choose between them at runtime based off the contents of `/proc/cpuinfo` (which, of course, cannot be edited).

**Comment by benhillis** [comment] 2019-02-07 19:08
@mqudsi - Thanks for the ping. @Brian-Perkins actually very recently made a change that should address this.  You can look forward to it in an upcoming Insider build, likely next week.

**Comment by mqudsi** [comment] 2019-02-07 19:10
That is great news, thank you both!

**Comment by benhillis** [comment] 2019-02-20 22:23
Fixed in 18342.

**Closed** 2020-02-15 21:35 UTC
Labels: fixedin1909
