### ISSUE TITLE
Envoy pre-compiled binaries not working on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by ravgupms** [microsoft/WSL#4538] opened 2019-09-23 18:29 UTC
When I'm trying to run Envoy on WSL, its crashing whenever I hit a request. On talking to [Envoy team](https://github.com/envoyproxy/envoy/issues/8319), they mentioned that `WSL doesn't implement getsockname system call correctly in WSL 1`

* Windows Version
>![image](https://user-images.githubusercontent.com/32916246/65451606-5d626900-ddf4-11e9-99f0-a7c76aeb37c6.png)

* I'm trying to run Envoy per-compiled binary onto WSL.

*Repro steps*:
> 1) On a Windows machine, enable Windows Subsystem for Linux: [link](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
>2) Install Envoy using following steps.
https://www.getenvoy.io/platforms/envoy/ubuntu/
>3) Download sample google example config
> 4) Run Envoy: envoy -c google_com_proxy.v2.yaml
> 5) Hit curl http://localhost:10000/

* What's wrong / what should be happening instead:
>Instead of routing request to google.com, Envoy process is crashing.

![image](https://user-images.githubusercontent.com/32916246/65369276-c3d26600-dbff-11e9-9d90-e6165b19b315.png)

**Comment by Biswa96** [comment] 2019-09-23 18:33
Any `strace` output file? Please use GitHub gist to add that output and use `strace -ff`, if possible.

**Comment by Biswa96** [comment] 2019-09-23 18:34
Any `strace` output or Windows Event Logs? See this [guide][1] for more. Please use GitHub gist to add that output and use `strace -ff`, if possible. 

[1]: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md

**Comment by ravgupms** [comment] 2019-09-24 04:46
Please find `strace` logs below: 
[stracelogs.zip](https://github.com/microsoft/WSL/files/3645255/stracelogs.zip)

**Comment by Biswa96** [comment] 2019-09-24 05:12
If I grep `getsockname` results show zero return value which signifies success.

**Comment by ravgupms** [comment] 2019-09-24 05:54
I looked further into Envoy code and looks like its failing at `setsockopt` system call.

Failed assertion:
![image](https://user-images.githubusercontent.com/32916246/65484773-c11c7e80-de54-11e9-8527-b1f06e1ce99d.png)
https://github.com/envoyproxy/envoy/blob/v1.11.1/source/common/network/connection_impl.cc#L239


`setsockopt` call before the assertion:
![image](https://user-images.githubusercontent.com/32916246/65484809-d72a3f00-de54-11e9-9153-8e8631927df4.png)

and I can see it being called in the `strace` logs as well.
![image](https://user-images.githubusercontent.com/32916246/65484840-f4f7a400-de54-11e9-8bea-4808fb7daf7b.png)

**Comment by Biswa96** [comment] 2019-09-24 06:16
Tried a simple code, no error is shown:

```c
int main(void)
{
    const int s = socket(AF_INET, SOCK_STREAM, 0);
    const int flag = 1;
    const int ret = setsockopt(s, IPPROTO_TCP, TCP_NODELAY, &flag, sizeof flag);
    assert(ret == 0);
}
```
Even wslbridge and wslbridge2 use that flag.

**Comment by therealkenc** [comment] 2019-09-28 22:29
It would take a look at the calls on fd `36` leading up to the EINVAL in @ravgupmps' screencap (I haven't).

Mostly going to be academic in this case. That's #ifdef __APPLE__ is telling here. The WSL1 TCP stack is really a Windows TCP stack, and it behaves subtly different in some edge cases versus Real Linux. This is one such case, apparently, although I can't find a dupe in a quick search. The realistic solutions here are going to be: (a) comment out that `RELEASE_ASSERT()` and recompile. (b) Use WSL2 which has hits own Real Linux TCP stack.

**Comment by RaviGitHubAccount** [comment] 2019-09-30 21:49
@therealkenc given WSL1 is still supported, are there any plan to fix such issues? Or moving to WSL2, which is not officially release yet, is the only option?

**Comment by therealkenc** [comment] 2019-10-01 01:27
> is the only option?

There were two options presented.

I have no special insights on future plans for open WSL1 issues. They are all unique. For this one, some deductive reasoning might be applied given a combination of: (1) A hypothetical fix could not appear in 19H2 since that window closed. (2) WSL2 is out in the next official release cycle 20H1. (3) There isn't yet a root cause fix identified here because no one has dug far enough to find out why a bare minimal test case passes but that TCP_NODELAY in the screencap doesn't (4) The hard-death behavior is at best iffy since there is an Apple work-around to ignore the setsockopt fail outright (5) This isn't the only WSL1 networking gap (6) This (whatever 'this' is exactly) wasn't reported until 2019, meaning it  can't be a widespread hard blocker on a large number of apps. (7) The likelihood of a mad rush of thumbs up on the OP or a flood of +1 Me2 is probably...small.

Noting I say "might be applied" because stuff does get fixed all the time. 11,000 likes on the Envoy hub. Fails in a massively popular project like that certainly have a better chance than some niche use case. Bonne chance.

**Closed** 2020-06-03 05:18 UTC
Labels: fixed-in-wsl2
