### ISSUE TITLE
Unable to open any PORT in bash

### ISSUE THREAD

**Issue by tianxiaxi** [Microsoft/WSL#1498] opened 2016-12-13 16:06 UTC
I use `sudo /usr/sbin/sshd -d -p 222` to set up ssh server, it seems it work fine.
```
root@kylin:~# sudo /usr/sbin/sshd -d -p 222
debug1: sshd version OpenSSH_7.2, OpenSSL 1.0.2g  1 Mar 2016
debug1: private host key #0: ssh-rsa SHA256:n3TQlnEiwWtPiOVqQnclmSZgI6DwpuqkzNQwSTp6Qqc
debug1: private host key #1: ssh-dss SHA256:hQ3FMTjSMSdLIpnuhc0AFc34Vw8y8ELLI3syKBbt7Yk
debug1: private host key #2: ecdsa-sha2-nistp256 SHA256:h3gvZq4ENKxOO3xYtJCbJYJu99hZsl41UKRZy9/ICew
debug1: private host key #3: ssh-ed25519 SHA256:WYZhx5y+qlwqLgMw1gx4e+T09pfy23URzwQElOHQ2aw
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-p'
debug1: rexec_argv[3]='222'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 222 on 127.0.0.1.
Server listening on 127.0.0.1 port 222.
```

I was refused when I login by ssh, 
```
root@kylin:~# ssh -vvv root@127.0.0.1 -p 222
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "127.0.0.1" port 222
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 222.
debug1: connect to address 127.0.0.1 port 222: Connection refused
ssh: connect to host 127.0.0.1 port 222: Connection refused
```

It seems the port 222 was not open.

+ Windows version
> Microsoft Windows [版本 10.0.14965]

+ bash version
> root@kylin:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by jackchammons** [comment] 2016-12-14 22:07
Have you allowed access to the ports through the Windows firewall?

**Comment by tianxiaxi** [comment] 2016-12-15 01:40
Yes. I already have allowed access for all ports through the windows firewall. And it also does not work if the firewall closed.

By the way, I set up mysql server and I could connect the port 3306.

**Comment by Nogitsune101** [comment] 2016-12-16 19:43
I'm not sure if this is the issue but try a port above 1024, if I remember correctly anything below that are essentially reserved on the Windows side.

**Comment by tianxiaxi** [comment] 2016-12-17 08:10
I have test some ports above 1024 which still not working. 
such as: 2222, 2345, 9999, 5678 .... 

For test propose, I set up a java web service and a nodejs web service, even if the the output seems fine, but still get connection refused.

**Comment by Sixoloy** [comment] 2016-12-17 08:39
@tianxiaxi Hey Bro, if your problem is solved, could you please tell me ?

**Comment by tianxiaxi** [comment] 2016-12-19 14:01
@Sixoloy This was not fixed. I have to use the origin `cmd` for bath.

**Comment by sunilmut** [comment] 2016-12-19 19:46
@tianxiaxi - Thanks for the post. Can you please share the detailed repro steps?

**Comment by tianxiaxi** [comment] 2016-12-22 05:21
After I install WSL, I did the following steps:

1. Install Nodejs
2. write a test web service by Nodejs
3. start the web service, the output seems everything OK, and listening the port 3000
4. open IE and navigation to http://127.0.0.1:3000 (`Not work`)
5. Allow all TCP/UDP for Inbound / Outbound， try again (`Not work`)
5. Disable windows default firewall and defender, try again  (`Not work`)
6. ----- no idea

**Comment by lefty-kreouzis** [comment] 2016-12-29 08:20
This looks like the same issue I am facing reported in issue  #1554

**Comment by sunilmut** [comment] 2016-12-29 20:51
@tianxiaxi - Can you please try these repro steps?

1. sudo apt install apache2
2. Change the default apache2 port in `/etc/apache2/ports.conf` from 80 to something else, like 8080
3. sudo /etc/init.d/apache2 start -> It will log some error about `APR_TCP_DEFER_ACCEPT`, but it looks like the service starts fine. To confirm, do `sudo /etc/init.d/apache2 status`
4. Open a web browser and connect to `http://localhost:<port>`

If the above works for you, then something is special about your `Nodejs` setup that we have to figure out. If this also does not work for you, then it would seem like a system wide problem.

**Comment by tianxiaxi** [comment] 2016-12-31 13:45
@sunilmut, Unfortunately it does not work for me (`Dell Inspiron 7000`). But I have another laptop `thinkpad x1` works fine, I could set up any http/https services on it.

Due to they both using the same win10 version, I think it might be some problem in BIOS or the drives, there is no solution how I can determine it.

**Comment by sunilmut** [comment] 2017-01-03 17:43
@tianxiaxi - That's unfortunate, but drivers or BIOS interfering here seems unlikely. Just to confirm, have you tried uninstalling any AV software that you might be running?

**Comment by tianxiaxi** [comment] 2017-01-29 05:29
@sunilmut I have tried reinstall windows 10 for 14393, the sshd works fine, But if I join Windows Insider and upgrade the OS to 15019. Although the sshd service could be started, but I got the Connection refused

**Comment by sunilmut** [comment] 2017-01-31 00:40
@tianxiaxi - Have you tried any workarounds from #1554?

**Comment by yuantongkang** [comment] 2017-03-23 03:11
Did you solved this porblem , I also have the same ? could you tell me how to solved it ?@tianxiaxi

**Comment by hxhlb** [comment] 2017-04-01 07:27
I have the same problem too... The sshd can listen and bind the port on 0.0.0.0, but can't to connect, and any port can't shown in Windows.  My system ver 10.0.15063

**Comment by shsmith** [comment] 2017-04-22 15:03
Same here. The port is BOUND but not LISTENING according to output of netstat.
```
C:\>netstat -a -q -n | findstr ":22"
  TCP    0.0.0.0:22             0.0.0.0:0              BOUND
  TCP    192.168.69.115:22      0.0.0.0:0              BOUND
```

**Comment by bornytm** [comment] 2017-05-09 08:57
Same issue after updating to version 1703 build 15063. 

Previously I've just reverted to early windows versions where this issue was not present. Are there any workarounds for this or forthcoming fixes? Disabling the firewall/attempting to add rules seems to have no effect.

`
C:\Users\comp>netstat -a -q | findstr "8000"
  TCP    127.0.0.1:8000         surf:0                 BOUND
  TCP    [::]:8000              surf:0                 BOUND
  TCP    [::]:8000              surf:0                 BOUND
`

**Comment by sunjoong** [comment] 2017-05-09 15:07
I'm looking for the way to make tcp port listen too.
```
sunjoong@SUNJOONG-DESKTOP ~ $ python
Python 3.4.5 (default, Apr 23 2017, 18:30:40) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket                                                          
>>> s = socket.socket()                                                          
>>> s.bind(('127.0.0.1', 55555))                                                          
>>> 
```
I commanded to bind, and then it bound. But, I expected it should listen, `TCP    127.0.0.1:55555        SUNJOONG-DESKTOP:0     LISTENING`.
```
C:\Users\sunjoong>netstat -qp tcp | findstr 55555
  TCP    127.0.0.1:55555        SUNJOONG-DESKTOP:0     BOUND
C:\Users\sunjoong>
```

**Comment by sunilmut** [comment] 2017-05-12 20:23
@sunjoong - Thanks for sharing your experience. It looks like your Anti-Virus was blocking the program from listening. If you have a way to contact your Anti-Virus software vendor, please do ask them to support WSL by implementing the Pico process notification. If they need more information, they can reach us directly and we will be happy to help them with the information.

@bornytm - I have replied to you on the other post #1853

**Comment by sunjoong** [comment] 2017-05-14 22:11
@sunilmut - Thanks for comment. I asked to SK Telecom custermer center to send my report to Anti-Virus software vendor just now. SK Telecom is my internet provider; They use SK Broadband line and SK Broadband bunddles this software. So, I think the report including this issue will be sent to SK Telecom --> SK Broadband --> Anti-Virus software vendor.

**Comment by wilon** [comment] 2017-05-15 12:35
I uninstall the update `KB4016871` and reboot.
Then I open the `bash`, get `nginx` & `ssh` work!

![image](https://cloud.githubusercontent.com/assets/7512755/26057841/d916b6a2-39ad-11e7-8dff-e302cfd615c7.png)

But can't see any port in `bash`.
![image](https://cloud.githubusercontent.com/assets/7512755/26057483/701c827c-39ac-11e7-8eb3-805a80f1abb7.png)

I reinstall `KB4016871`, it still work.

**Comment by zhlicen** [comment] 2017-05-23 03:37
@wilon 
Still not working in my 15063, what's your os build?

**Comment by rishavs** [comment] 2017-06-12 04:11
Not working for me either. I am trying webdev on bash but the dev host at localhost:3000 is refusing to connect.

**Comment by ChenYangShao** [comment] 2017-06-12 16:05
大兄弟， 你解决这个问题了么？ @tianxiaxi

**Comment by dexgeh** [comment] 2017-06-19 13:02
After a lot of troubleshooting I resolved uninstalling the Juniper Network Client; it does install a driver that break the networking inside bash.

**Comment by shinezyy** [comment] 2017-06-30 11:30
I also encounter this problem after update to windows 10 1703 from windows 10 1607, either on ubuntu 14.04 or ubuntu 16.04.

**Comment by didyhu** [comment] 2017-07-04 14:00
Uninstall tencent TGP and restart. Works for me.

Thanks to: [https://github.com/Microsoft/BashOnWindows/issues/1554](url)

**Comment by sunjoong** [comment] 2017-07-04 14:34
@didyhu - Good for you. But anchor of #1554 you reffered seems to be broken; #1554 is still there but that points wrong url linked :) I think you might want to tell this, https://github.com/Microsoft/BashOnWindows/issues/1554#issuecomment-307573568 ;
> Third-party VPN software is probably going to be difficult for WSL to support. But I'd still like to know why these drivers (filters) are causing localhost to fail. From my naive viewpoint, localhost shouldn't be in the path. I'm also curious why some VPN software breaks WSL, while others do not. I have been running OpenVPN with TAP since day one and have never had a problem. Other tunneling software obviously causes difficulty. I have no idea why some VPN software works and others do not.

**Comment by didyhu** [comment] 2017-07-04 16:50
@sunjoong Thanks for reminding. Fixed.

**Comment by vaynewang** [comment] 2017-07-06 07:11
@ChenYangShao did you installed tencent  TGP ?  uninstall  it.

**Comment by rishavs** [comment] 2017-07-28 10:49
I dont have tencent. But around the time the problem first started, i was dabbling with VPNs. i have uninstalled all VPNs now but the problem is still there. Anyway to rest my networking?

**Comment by sunilmut** [comment] 2017-08-01 18:08
@rishavs - There is no way to just reset network. If you are working with VPN's and face n/w connectivity issues, there is a workaround [here](https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#bash-loses-network-connectivity-once-connected-to-a-vpn). But, not being able to open ports can be because one of many reasons. You have to allow that port through the Windows firewall and sometimes Antivirus software also interferes with bash. As a last resort, you can try uninstall/re-install of bash. To uninstall, do `lxrun /uninstall` and to re-install, either `lxrun /install` or download from Windows store. Just a note that if you are on Insider build, `lxrun /install` option may not be available.

**Comment by rishavs** [comment] 2017-08-02 13:59
sunil. i have done these things. I tried without antivirus and firewall. I have reinstalled bash multiple times. Unfortunately, there was no success.

**Comment by rishavs** [comment] 2017-08-02 13:59
sunil. i have done these things. I tried without antivirus and firewall. I have reinstalled bash multiple times. Unfortunately, there was no success.

**Comment by MendesMartini** [comment] 2017-10-20 13:35
In Windows firewall, add a permission/exception for the program:

C:\Windows\System32\wsl.exe

And be happy.

**Comment by taigadigital** [comment] 2017-11-03 13:08
The above does not work.

**Comment by MendesMartini** [comment] 2017-11-03 16:18
This solution worked on all machines in my network... 🤔

**Comment by bornytm** [comment] 2017-11-03 16:24
@MendesMartini Your solution didn't work for me either (version 1703, build 15063.674). @taigadigital What did fix the problem was uninstalling the program "Networx" and restarting.

**Comment by andrewalisa** [comment] 2017-11-06 22:09
Honestly I just gave up and used Ubuntu on Virtualbox.

**Comment by dexgeh** [comment] 2017-11-09 10:01
For anyone still having this issue, you can check which network driver is loaded using Nirsoft DriverView.
Anything non-related to the hardware driver can cause a problem; filter out microsoft driver and sort by file type to get the network drivers.
The openvpn tap driver is working fine, the juniper one causes the issue.

![immagine](https://user-images.githubusercontent.com/210321/32599491-05c8f00a-c53d-11e7-9501-d7c93a510d0f.png)

**Comment by Xixi20160512** [comment] 2017-12-15 07:07
uninstall tencent TGP

**Comment by sunilmut** [comment] 2017-12-19 02:22
@all having problems with opening port, take a look at [this](https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927) blog post and see if it resolves your issue. Also, insider build [17046](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046) has the workaround fix for this issue.

**Comment by mosaice** [comment] 2017-12-19 03:39
I have uninstalled TGP(Wegame) and everything is fine

**Comment by tanjiancheng** [comment] 2018-01-11 06:31
i fixed this problem by uninstall all product of Juniper and reboot,then work
![image](https://user-images.githubusercontent.com/7401570/34811328-3f6a9988-f6db-11e7-982d-9c4f907a358b.png)

**Comment by sunilmut** [comment] 2018-01-11 20:34
It has been reasonably demonstrated that the issue of ports not listening is due to the TDI filter driver interference (follow up from [here](https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927)). I am marking this issue duplicate of #1554.

**Comment by Stupidism** [comment] 2018-01-14 08:36
Tried all your solutions but failed. 
Reset windows and reinstall ubuntu from windows store saved my time.
Thanks to https://github.com/Microsoft/WSL/issues/1554#issuecomment-295036488.

**Comment by maysara** [comment] 2018-01-18 11:45
facing the same issue, reinstalling did not help, but had event 16001 and it was associated with Driver\NgFilter from aventail VPN client. uninstalling it solved the issue. worth noting though, it worked for me briefly before without uninstalling aventail, and uninstalling a different software (zScaler); but then broke again.

**Comment by sunilmut** [comment] 2018-01-18 21:17
@maysara - If you have a support channel with these applications, you can log a ticket with them to move away from TDI filter, which is a deprecated feature.

Also, starting build [17046](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046), WSL will start bypassing TDI filter driver. What that means is that starting that build, you should no longer see this issue. That fix will also be available in the next major public Windows 10 release. But, getting the applications to move away from TDI is the right approach as to who knows where else things will go south.

**Closed by sunilmut** 2018-01-18 21:17 UTC
Labels: duplicate, fixedininsiderbuilds

**Comment by zs2619** [comment] 2018-04-01 15:49
WTF！  Uninstalling wegame is effective.

**Comment by lch32111** [comment] 2018-07-14 23:44
If there is anybody stuck in this problem, try updating your ubuntu version.

In my case, I can't connect to the local host, and the version of my ubuntu 16.04.

[(https://www.zdnet.com/article/how-to-upgrade-to-ubuntu-linux-18-04/)]
With this link which let me know how to update ubuntu,
I updated my ubuntu and it made my program works for localhost.
