### ISSUE TITLE
Sign out and Sign in to Windows : WSL stops working temporarily

### ISSUE THREAD

**Issue by mgravell** [Microsoft/WSL#3373] opened 2018-07-11 18:40 UTC
Prior state: WSL with Ubuntu, working fine - dev tools installed; all good. OS: Windows 10 Enterprise, x64 Intel i7 CPU, up to date, standard consumer branch.

Here's a screenshot I took on "old" "bash on ubuntu on windows":

![old school](https://pbs.twimg.com/media/Dh0XvL7XkAUAtG_.jpg:large)

and here's something similar on Ubuntu 18.04 from the Microsoft Store:

![image](https://user-images.githubusercontent.com/17328/42592599-e3dac41c-8541-11e8-92d0-ad08e8d97f6d.png)

Both times, it was working fine, and then I did "sign out" (Windows), then signed in, and re-loaded WSL.

I also ran `wslconfig /l`; sometimes I get

```
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
```

but when it is failing, I get the exact same message from the 1st screenshot about not having any and visiting the Microsoft Store, like this:

![image](https://user-images.githubusercontent.com/17328/42592826-9bf6b402-8542-11e8-9265-93822e7f9ac2.png)

---

And this is on the same machine about 5 minutes later, having **done nothing**:

![image](https://user-images.githubusercontent.com/17328/42592980-2ce87824-8543-11e8-90d9-ac095b04d16f.png)

**Comment by benhillis** [comment] 2018-07-11 19:02
Thanks for reporting, duplicate of #2576.

**Closed by benhillis** 2018-07-11 19:02 UTC

**Comment by israelrichie** [comment] 2025-05-22 19:55
![Image](https://github.com/user-attachments/assets/ec65d2b4-223f-4b28-ab53-a22ecb7f2467)

pls i am facing the same issues
