### ISSUE TITLE
checkout of a git repo with filenames containing ":" failes on /mnt/c/.....

### ISSUE THREAD

**Issue by wvervoorn** [Microsoft/WSL#2936] opened 2018-02-12 09:54 UTC
When I checkout a repo that contains filename with ":" this fails when I do this on a directory under /mnt/c/... and works fine in the "home" directory.

I guess this is because the windows file system treats this as an alternate data stream.

This of course isn't the intention.

How can I make sure this is handled in the correct way, after all I do need to access these files both from Windows and the bash environment.

The checkout is fine if I do this from cygwin or using windows tools. But fails when checking out from the bash environment.

**Comment by benhillis** [comment] 2018-02-12 14:53
Please fill out the issue template. What build are you using?  I know @SvenGroot has made some recent changes to file paths with illegal Windows characters on DrvFs.

**Comment by therealkenc** [comment] 2018-02-12 16:20
#2741 #2070 #1514. Not addressed as of 17093.

**Comment by benhillis** [comment] 2018-02-12 16:29
There are some changes in this area in an upcoming Insider build.

**Comment by benhillis** [comment] 2018-02-14 16:42
Marking as duplicate of #1514.

**Closed by benhillis** 2018-02-14 16:42 UTC
