### ISSUE TITLE
Running bash from ssh (using built-in SSH Server Broker/Proxy) causes error 0x8007048f

### ISSUE THREAD

**Issue by sebmaynard** [Microsoft/WSL#777] opened 2016-08-05 08:36 UTC
- A brief description
  - I've got the Anniversary update. 
  - I've installed Windows Subsystem for Linux, and installed bash (by running bash from a command line)
  - After a couple of reboots, I noticed 2 new services for "Windows SSH Server": "SSH Server Proxy" and "SSH Server Broker" which get started on boot.
  - I ssh to localhost which gives me a command prompt (as in cmd.exe)
  - From there, I run bash, which gives me a (slightly garbled) WSL BashOnWindows prompt.
  - If I ssh into localhost again (again using the native ssh server) I can start the garbled bash again and it doesn't give an error; it just doesn't work very well as it seems to be ignoring all of the shell escape codes. 
  - If I then try and run bash again (from a normal cmd) I get error 0x8007048f and it refuses to start again that way until I reboot
- Expected results
  - Bash runs as normal, and doesn't prevent future bashes from running outside of the native ssh session
- Actual results (with terminal output if applicable)
  - The bash running inside the ssh session continues to work
  - No other bash will run (i.e. from a normal command prompt, or from powershell)
- Your Windows build number
  - 14393.10
- Steps / commands required to reproduce the error
  - Install the Anniversary update, enable linux subsystem, install bash
  - Reboot a few times
  - SSH into localhost
  - Run bash from connected ssh session
- Strace of the failing command
  - n/a
- Required packages and commands to install
  - n/a

**Comment by bitcrazed** [comment] 2016-08-05 12:51
The ssh server you're seeing is actually a minimal ssh server used for device discovery (when developer mode is turned on) and should really be avoided since it lacks many of the features one might otherwise expect of a full ssh server.

**Comment by ducalpha** [comment] 2016-08-05 13:15
I tried to turn on ssh from Bash on Windows but got an error on privilege separation as follows:

> $ sudo /usr/sbin/sshd
> Missing privilege separation directory: /var/run/sshd

I don't want to disable privilege separation of SSH server (by editing /etc/ssh/sshd_config). Is there any better way?

**Comment by fpqc** [comment] 2016-08-05 17:09
@ducalpha you have to turn off privilege separation in /etc/sshd.conf or whatever the configuration file is.

**Comment by bitcrazed** [comment] 2016-08-11 02:09
Closing this issue for now since, as mentioned above, this SSH server is only a minimal SSH server used for device discovery scenarios and it doesn't support all the high-fidelity SSH features one would expect or rely upon. 

If you want to run an OpenSSH Server on Windows, know that the real OpenSSH is currently being ported to support Windows as we type: https://github.com/PowerShell/Win32-OpenSSH

And if you can always run sshd from Bash, but obviously, only when you've got a bash shell running.

**Comment by benhillis** [comment] 2016-08-11 02:18
I think this should be debugged. Reopening.

**Comment by Efreak** [comment] 2016-08-12 20:57
On the latest preview version of Windows 10, the error code is different, I've got [Error: 0x80070020](http://i.imgur.com/hA9Cc5G.png). Not sure if it makes a difference, but this post helped me figure out the issue.

**Comment by gertcuykens** [comment] 2016-10-17 21:04
I got Error: 0x80070005

The minimal broker / proxy sshd server should be upgraded to a real one. So in summary we have 3 sshd servers now.

1. bash
2. powershell
3. broker/proxy

Only the broker / proxy is the way forward if you ask me. It is currently the only solution that resembles the low level control and performance you expect from a sshd server.

I assume the broker / proxy is out of the linux bash scope and need to be addressed by a complete other internal team from Microsoft?

I suggest the following when decision is made to keep the broker / proxy server minimal permanently then please use another default port for it and reserve the 22 port for a real sshd server.

What to avoid at all cost is that developers are developing a powershell or bash sshd solutions that can run as services in windows and then all effort is been lost because the broker \ proxy from microsoft has been upgraded making a bash sshd solution useless both on security and performance because the former its backed into the windows kernel.

So please be clear on the decision and keep us updated, thanks.

**Comment by fpqc** [comment] 2016-10-17 21:22
@gertcuykens Yeah, connecting to an ssh server is so much simpler than Enter-PSSession or WMI.  I hope they add it as a Nano server role.

**Comment by yurymik** [comment] 2017-01-15 19:10
I get 0x8007048f or 0x80070020 when try to ssh to the localhost and run bash there. Here are ETL files for 0x8007048f case:

[lxcore_etl_trace.zip](https://github.com/Microsoft/BashOnWindows/files/706819/lxcore_etl_trace.zip)

**Comment by kvz** [comment] 2017-02-08 13:19
> And if you can always run sshd from Bash, but obviously, only when you've got a bash shell running.

I'd like to do this as a workaround, are there any tutorials for it? The obvious `sudo apt-get install ssh && sudo /etc/init.d/ssh restart` is not working for me. `sudo netstat -tupan` reports no open port. I changed the port to `223` as to not conflict with anything that might already be running on `22` but to no avail. No `syslog` or `auth.log` or`messages` log so i'm a bit lost

**Comment by aseering** [comment] 2017-02-09 02:35
For what it's worth, there's a thread discussing how to do this, here:

https://wsl-forum.qztc.io/viewtopic.php?f=6&t=10

**Comment by sunilmut** [comment] 2017-03-02 00:00
@yurymik - Thanks for the traces. Can you describe your setup a bit more in detail:

1. What ssh server are you running?
2. Is your bash [setup complete](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)? Are you able to launch bash locally without ssh?

**Comment by yurymik** [comment] 2017-03-02 00:06
That was taken on Win10 anniversary edition; bash setup completed, can run it locally.

Ssh server? I was trying to use built-in SSH Server Broker/Proxy that comes with WSL and has no options to configure (boo!). If you meant ssh client, then it was Putty.

**Comment by sunilmut** [comment] 2017-03-02 00:35
@yurymik - Thanks. I am a bit confused with your setup/problem `when try to ssh to the localhost and run bash there`. If you are able to successfully SSH into the SSH server running on WSL, then it's all good, isn't it? Can you please provide your detailed repro steps?

**Comment by yurymik** [comment] 2017-03-02 00:41
Well, as the title of this bug says, the problem is in running bash from inside SSH session. Here are the steps:

1. Run Putty
2. Ask it to connect to the localhost
3. WSL server responds and establish connection, you're in the cmd shell
4. Type bash and press enter
5. Get an angry error code 0x8007048f or 0x80070020

Sometimes, step 4 succeeds without a problem and I can work in bash, but sometimes it prints error code and refuses to continue.

What's the reason to ssh to the localhost? Not much, I was just troubleshooting the setup, before moving to the remove machine.

**Comment by benhillis** [comment] 2017-10-17 15:23
I believe this should be fixed in 17017.

**Closed** 2017-10-30 18:45 UTC
Labels: fixedininsiderbuilds
