### ISSUE TITLE
WSL2 crashes at startup

### ISSUE THREAD

**Issue by PedroLamas** [microsoft/WSL#4768] opened 2019-12-17 10:28 UTC
* Your Windows build number: Microsoft Windows [Version 10.0.19041.1]

* What you're doing and what's happening: I just opened Ubuntu from the start menu, console window appeared and 5 seconds afterward, it silently closed.

* What's wrong / what should be happening instead: Ubuntu bash should appear on the console window.

Logs attached
[Logs.zip](https://github.com/microsoft/WSL/files/3972754/Logs.zip)

**Comment by craigloewen-msft** [comment] 2019-12-17 19:10
Having checked your logs, your VM is not being created since it's running into a network related error: 0xFFFFFFFF. We are tracking this issue here: https://github.com/microsoft/WSL/issues/4364

This could be caused by a myriad of things, but I think it's likely that it could be that port 53 is in use, maybe from an app like docker. I'd recommend trying the work around of ensuring port 53 is available (You can see if it's in use by running 'Resource Monitor' -> 'Network' -> 'Listening Ports' ) and then try and rerunning your WSL2 instance to see if that fixes it.

I'll mark this as a duplicate, since it's already being tracked in the other thread. Please feel free to comment and follow up there for any updates as we work on resolving this! :) 

/dupe #4363

**Closed by craigloewen-msft** 2019-12-17 19:10 UTC

**Comment by PedroLamas** [comment] 2019-12-17 22:45
@craigloewen-msft indeed, I can see port 53 is used by Docker for Windows

![image](https://user-images.githubusercontent.com/85504/71040220-0da6eb80-211e-11ea-8a4a-66e705b8951b.png)

I know that there's a new version of Docker for Windows that is optimized for WSL2, but I use the latest production release instead, as I need to run Windows containers for work! That might be the issue here...

**Comment by PedroLamas** [comment] 2019-12-17 22:54
After running `docker network prune`, I can now open Ubuntu from the start menu!

Interestingly, I still see that port 53 is in use by docker, so I guess this was a different issue of sorts...

![image](https://user-images.githubusercontent.com/85504/71041132-37f9a880-2120-11ea-8798-97462bb40149.png)

**Comment by craigloewen-msft** [comment] 2019-12-17 23:16
Interesting! If you are able to find a repro please let me know, we've been trying to repro this consistently and haven't been able to do so.

**Comment by PedroLamas** [comment] 2019-12-18 12:36
We have 2 different machines here on the same state (my Dell XPS and @VaticanUK with his HP Spectre), in common they have Docker with Windows containers enabled, and we are both on the Windows 10 Insider Slow ring (currently on 19041.1).

Mind you, I only noticed this issue after the last Windows 10 Insider update (I was already using WSL2 before on the previous build and that was ok)

**Comment by devbeard** [comment] 2020-01-10 07:35
I have the same issue with my work laptop that runs Umbrella Roaming Client (from Cisco), and the subprocess "dnscrypt-proxy.exe" that is listening on port 53. The fun part is that since this is security software, I am unable to kill the process and get WSL running again. I'm thinking that all these clashes on the same port is going to be a common issue. At least consider a proper error message in the output from wsl.exe that gives the actual error to the end user.
