### ISSUE TITLE
WSL2 Apache2 vhost not working

### ISSUE THREAD

**Issue by UdVi86** [microsoft/WSL#4347] opened 2019-07-28 08:43 UTC
Hello!

I installed apache2 in WSL2,
modified root directory in _apache2.conf_:

```
<Directory /home/udvi/Projects/>
...
</Directory>
```

I create a test.conf in _/etc/apache2/sites-available_ folder. It contains:

```
ServerName test.tld
DocumentRoot /home/udvi/Projects/test

```
Add test.tld to _/system32/drivers/etc/hosts_

`127.0.0.1 test.tld`

But not loading site _test.tld_

I modified DocumentRoot to _/home/udvi/Projects/html_ in _000-default.conf_ and localhost sometimes loads well and sometimes doesn't, but test.tld never loads.

The error is: ERR_CONNECTION_REFUSED

**Comment by ad-on-is** [comment] 2019-07-28 10:11
Same here with nginx, running in a docker-container.

**Comment by Drakota** [comment] 2019-07-29 17:46
I have the same issue, sometimes it loads forever and the second time it loads instantly.
I've managed to make a vhost work by adding this in the hosts file.
```
127.0.0.1 test.tld
::1 test.tld
```
But it is extremely unstable and can't be used like this at the moment.
Sometimes a request load infinitely so I have to spam the same request until one goes through.

[Here's an example of the issue](https://berrycast.app/conversations/0dc4a02f-4be4-5215-bbfb-f7c3aed96440)

**Comment by Biswa96** [comment] 2019-07-29 18:09
Just curious, can anyone point out the exact error in an `strace -f -o` output?

**Comment by Drakota** [comment] 2019-08-01 02:45
Seems to be related to #4340

**Comment by UdVi86** [comment] 2019-08-02 17:05
> 127.0.0.1 test.tld
> ::1 test.tld

Thanks, it works! :)

**Comment by mscraigloewen** [comment] 2019-08-06 20:03
The `ERR_CONNECTION_REFUSED` message indicates to me that this has to do with what IP address the apache server is bound to. We have a bug fix coming in to make this work, and are tracking it over in issue #4353 . I'll close this issue out as a duplicate to that one since I believe they have the same root cause. Thanks for filing!

**Closed by mscraigloewen** 2019-08-06 20:03 UTC

**Comment by douglascorrea** [comment] 2019-12-20 15:34
> 127.0.0.1 test.tld
> ::1 test.tld

This didn't work for me, any other workaround?

**Comment by douglascorrea** [comment] 2019-12-20 15:42
I realized that, if I put:

```
::1             test.tld localhost
```
instead of 

```
::1             localhost test.tld
```

in the Windows hosts file, it works, I don't know if this is a normal behaviour for IPv6

**Comment by btassone** [comment] 2020-07-31 21:32
This worked for me

**Comment by ledunggit** [comment] 2020-10-13 07:58
![image](https://user-images.githubusercontent.com/64201705/95832494-838eda00-0d64-11eb-9512-e901f8359576.png)
It's work for me, thanks lot ♥ You saved my time ♥

**Comment by ledunggit** [comment] 2020-10-13 07:59
> I have the same issue, sometimes it loads forever and the second time it loads instantly.
> I've managed to make a vhost work by adding this in the hosts file.
> 
> ```
> 127.0.0.1 test.tld
> ::1 test.tld
> ```
> 
> But it is extremely unstable and can't be used like this at the moment.
> Sometimes a request load infinitely so I have to spam the same request until one goes through.
> 
> [Here's an example of the issue](https://berrycast.app/conversations/0dc4a02f-4be4-5215-bbfb-f7c3aed96440)

![image](https://user-images.githubusercontent.com/64201705/95832584-aae5a700-0d64-11eb-81bb-03adf27b8e69.png)
It's work for me, thanks lot, you saved my time ♥

**Comment by nicktchernikov** [comment] 2021-02-22 13:07
can confirm that the
`::1 `
trick worked after some hair pulling

**Comment by abetoots** [comment] 2021-06-02 06:13
Also worked for me but still encountered errors related to DNS.  I tried flushing dns in windows host using `ipconfig /flushdns` and now it works
