### ISSUE TITLE
New WSL installation backported with KB5004296 breaks WSL-detection in Eclipse 2021-06.

### ISSUE THREAD

**Issue by ams-tschoening** [microsoft/WSL#7268] opened 2021-08-03 06:34 UTC
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1110]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Other Software

Eclipse 2021-06

### Repro Steps

Some new features have been backported to WSL, like described in the following article:

https://devblogs.microsoft.com/commandline/install-wsl-with-a-single-command-now-available-in-windows-10-version-2004-and-higher/

I've manually searched for Windows Updates in the settings app, which resulted in the optional preview for KB5004296 being shown, afterwards I clicked to download and install, restarted etc. Eclipse 2021-06 is able to start different terminals in some project directory using the context menu of that directory. After KB5004296 was installed, that context menu entry contained lots of WSL-related individual lines of its help messages. Of course none of those lines was actually usable to run WSL on that folder at all.

The important thing is that I DO NOT had WSL installed at all and don't want to use it right now. Instead, Eclipse only checks for WSL being available to optionally add it to that context menu. Before installing KB5004296 and after uninstalling it that works properly, WSL is NOT added to the context menu, as it's simply not installed. With KB5004296 being installed, Eclipse somehow thinks WSL is installed, which is wrong.

While I've filed a [bug on this for Eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=575159) first, in my opinion this is a regression. Eclipse seems to have executed `wsl -l -q`, which should simply fail on my machine and still does without KB5004296 being installed on the shell. Though, during debugging this with KB5004296 being installed using ProcMon, I couldn't see any WSL process being executed at all and am somewhat sure to have not filtered it. Additionally, my current Windows 10 Insider Preview VM still fails when executing `wsl -l -q` on the shell as well. Though, vor various different reasons I can't install KB5004296 right now again to test `wsl -l -q` for that.

But my expectation is that it still fails for the shell, while whatever Eclipse does under the hood most likely triggers some new behaviour you have introduced with KB5004296. So this might hit a lot of other similar use cases as well.

![Clipboard01](https://user-images.githubusercontent.com/6223655/127968827-94ff7b61-8ab3-4268-b797-0f877dab255f.png)

![Clipboard02](https://user-images.githubusercontent.com/6223655/127968838-dafe918b-b611-416f-94ef-e806d0758872.png)

![Clipboard06](https://user-images.githubusercontent.com/6223655/127968843-49e00e90-093c-4289-a80f-88dbb698395b.jpg)

![Clipboard07](https://user-images.githubusercontent.com/6223655/127968852-28ff2152-6f28-49c6-a611-302782da4e8a.jpg)

### Expected Behavior

Eclipse 2021-06 should have behaved the same with or without KB5004296 being installed. No WSL help lines should be available in its context menu.

### Actual Behavior

Eclipse 2021-06 added WSL related context menu entries for its terminal settings which don't make any sense at all.

**Comment by craigloewen-msft** [comment] 2021-08-03 16:37
As you identified above, as part of the recent backport we added `wsl.exe` by default to Windows. This means that even when the WSL optional component is not turned on, `wsl.exe` will still be present on the box. We recommend checking the exit code of `wsl --list` to determine if WSL is installed or not, which is how [Windows Terminal does this](https://github.com/microsoft/terminal/blob/9e83655b0870f7964789a7a17ccfd232cab4945a/src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp#L55). Please let me know if you have any questions, I'm closing this issue out as it's by design but I'll follow up with any more comments on here!

**Closed by craigloewen-msft** 2021-08-03 16:37 UTC
