### ISSUE TITLE
Feature request: Netdiscover incompatibility 

### ISSUE THREAD

**Issue by francesco1119** [Microsoft/WSL#1695] opened 2017-02-12 08:50 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description: Netdiscover is not working on Windows Bash

* Expected results: Netdiscover should work 

* Actual results (with terminal output if applicable): When you launch Netdiscover an error prompt up and says: `pcap_open_live(): wifi0: socket: Invalid argument`

* Your Windows build number: 15025.rs_prerelease.170127-1750

* Steps / All commands required to reproduce the error from a brand new installation: 

1. `apt-get install netdiscover`
2. `netdiscover`

* Strace of the failing command [here](https://gist.github.com/francesco1119/17b564dab6bc29aa6066523e8137bfc9)

* Required packages and commands to install: `apt-get install netdiscover`

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by francesco1119** [comment] 2017-02-12 08:55
I think [this ](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1412283.html) may be the cause. At least the error looks similar

**Comment by francesco1119** [comment] 2017-02-17 23:49
My version is Microsoft Windows [Version 10.0.15025]

**Comment by sunilmut** [comment] 2017-03-01 20:35
@francesco1119 - Thanks for the feedback, detailed post and the trace. Your trace outlines the problem:

```
socket(PF_PACKET, SOCK_RAW, 768) = -1 EAFNOSUPPORT (Address family not supported by protocol)
socket(PF_INET, SOCK_PACKET, 0x300 / IPPROTO_??? */) = -1 EINVAL (Invalid argument)
```

WSL currently does not support the 'PF_PACKET' socket address family (also see #1515). [Here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) is the user voice page for supporting `PF_PACKET`. Please up-vote if you would like to see support for this in future. We use user voice page to prioritize our future work.

**Comment by sunilmut** [comment] 2017-03-01 20:35
Marking this duplicate of #1515.

**Closed** 2018-08-21 20:11 UTC
Labels: duplicate, feature, network
