### ISSUE TITLE
Unusable git: high cpu usage.

### ISSUE THREAD

**Issue by vadv** [Microsoft/WSL#1991] opened 2017-04-24 12:23 UTC
High CPU usage with running `git log` command on Microsoft Windows [Version 10.0.15063]. 

How to repeat:

```bash
git clone https://github.com/postgres/postgres.git
cd postgres
git log -p .
```

100% utilization of one processor:

![alt text](http://image.prntscr.com/image/acd1790355314cb4ae8dc43d6d4afdd5.png "linux top")

![alt text](http://image.prntscr.com/image/4c205259344c49d2b7a06e1981ae19d5.png "kernel time")

![alt text](http://image.prntscr.com/image/74bce67a91774d15a92cf739a2318eb7.png "perfomance graph")

**Comment by therealkenc** [comment] 2017-04-24 18:27
#1305 #981 and friends. If it is any consolation, Microsoft seems to have [drank the `git` cool-aid](https://blogs.msdn.microsoft.com/bharry/2017/02/03/scaling-git-and-some-back-story/) and there have been a number of comments indicating they are aware of, and are working on, performance improvements. Since MSFT is invested in `git`, I am pretty confident this is going to improve; possibly by orders of magnitude if everything comes together. 

Right now, the Party Line seems to be to do development on `/mnt/c`, which means you can use [Windows Git](https://git-for-windows.github.io/) as a "work around". It isn't absolutely ideal (if you are from a Mac or Linux worldview) but it works well and teams with _massive_ projects are using it successfully.

ob-xkcd

![git](https://cloud.githubusercontent.com/assets/7049700/25351952/2a011808-28df-11e7-8a0d-9735d7f6f559.png)

**Comment by vadv** [comment] 2017-04-24 18:33
I understand that the speed of git under WSL is not high, but it is better then git centos in vmware workstation on 'shared folder' storage. Thanks Microsoft, I dont use vmware, I have enough WSL with creator update :)

I'm talking about the case when git does nothing, just show the static log!

**Comment by therealkenc** [comment] 2017-04-24 18:57
I tried your repro:
```
ken@DESKTOP-9BDQA3V:~/Devel/postgres$ time git log -p . > log.out

real    2m6.000s
user    1m11.313s
sys     0m46.797s
ken@DESKTOP-9BDQA3V:~/Devel/postgres$ wc log.out
 26719142 118138709 957691219 log.out
```
This is on a fast SSD with an i7-6700K. If you run the command on your system in one window, and then do a `tail -f log.out` in another, you should see it churning along. If it is actually spinning (doing "nothing") please confirm. This is on 16179, but nothing has changed in this area since 15063 that I have heard.

**Comment by vadv** [comment] 2017-04-24 19:38
just open `git log` big repo, statically with doing "nothing" and watch what 100% cpu utilization:
![alt text](http://image.prntscr.com/image/6c5de0b31adc4414a3a32c508dedca7a.png "top")

**Comment by vadv** [comment] 2017-04-24 20:09
dell notebook precision 5510 with Xeon(R) E3-1505M v5:
```
$ time git log -p . > log.out

real    2m7.293s
user    1m21.594s
sys     0m44.328s

$ wc log.out
 26331304 116586129 947874610 log.out
```

screenshot without tmux:
(http://image.prntscr.com/image/97bb77ff5e7c4a2b86162c25643a6427.png "without tmux")

**Comment by therealkenc** [comment] 2017-04-24 20:16
I am not getting the spinning CPU behavior with:
```
git log -p . | less
```
On my system, that just blocks git with 0 CPU on the first page. So the trick here is going to be figuring out what you have set up different on your system.

**Comment by hickeng** [comment] 2017-06-05 20:28
May well be related - I 50x slower `git status` performance vs git running in mingw.

Mingw:
```
real    0m0.138s
user    0m0.000s
sys     0m0.015s
```

WSL:
```
real    0m6.952s
user    0m0.906s
sys     0m5.938s
```

Attaching WSL strace with timestamps in case it's of help: 
[git_status.zip](https://github.com/Microsoft/BashOnWindows/files/1053105/git_status.zip)

**Comment by nzbart** [comment] 2017-07-10 03:11
Another data-point comparing native Windows with BashOnWindows performance.

PowerShell on Windows (sub-second):
```text
PS> measure-command { git status } | select -expand TotalMilliseconds
418.486
```

Bash on Windows - run 1:
```text
real    0m8.952s
user    0m0.359s
sys     0m48.156s
```

Bash on Windows - run 2:
```text
real    1m20.446s
user    0m3.719s
sys     1m55.219s
```

I don't know what might have caused the big difference in results on Bash on Windows.

It's possible that my Windows setup has a different configuration, but nothing seemed to stand out.

Note that I saw the same CPU usage as mentioned above. Initially, all 8 cores maxed out, but then it settled down to 100% of a single core.

This should give you a feel for the size of the repository:
```text
PS> ls -r | measure-object | select -expand Count; git ls-files | measure-object | select -expand Count
258163
206872
```

**Comment by chx** [comment] 2017-09-17 11:32
This is a duplicate of a million issues penultimately https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13386252-filesystem-slow-compared-with-native-ubuntu-system

**Comment by therealkenc** [comment] 2017-11-18 22:05
Dupe #981

**Closed by therealkenc** 2017-11-18 22:05 UTC

**Comment by KenHenson** [comment] 2019-09-30 03:46
When is this going to be fixed? This issue has been around toooooooooo long!
