### ISSUE TITLE
htop displays black screen

### ISSUE THREAD

**Issue by agostini01** [microsoft/WSL#5141] opened 2020-04-27 13:59 UTC
**Please fill out the below information:**
* Your Windows build number:  Microsoft Windows [Version 10.0.18363.778]

* What you're doing and what's happening:  Programs such as htop are not working in WSL Ubuntu 20.04LTS. After I run `htop` I get a black screen that I can only leave with `CTRL+C` command.

* What's wrong / what should be happening instead: I was expecting to see htop on the cmd, or windows terminal.

* Strace of the failing command, if applicable:  https://gist.github.com/agostini01/dfa637de22743894ca845039f1d3e3f6

* Additional notes: may be related to issue#25 (https://github.com/Microsoft/WSL/issues/25) . Can be an ncurses problem.

Let me know how can I further help. Thanks

**Comment by sirredbeard** [comment] 2020-04-27 14:41
Thank you for reporting this.

This is a duplicate of #4898 and there is a workaround for htop specifically there.

A fix is in testing.

It is being tracked in Ubuntu WSL here https://bugs.launchpad.net/ubuntuwsl/+bug/1871129

This bug report should be closed but you can subscribe to those other two bugs for updates.

**Closed** 2020-04-27 15:07 UTC

**Comment by kaneorotar** [comment] 2020-06-22 04:19
> 
> 
> Is this really a dupe? I'm seeing this under WSL 2 and not WSL 1, which is what #4898 refers to ...

It is. The workaround in #4898 works in WSL2 as well.

**Comment by challenger128** [comment] 2020-08-26 22:33
> > I'm getting a black screen on wsl 2
> 
> Just follow these steps:
> 
> sudo add-apt-repository ppa:rafaeldtinoco/lp1871129
> sudo apt update
> sudo apt install libc6=2.31-0ubuntu8+lp18711291 libc6-dev=2.31-0ubuntu8+lp18711291 libc-dev-bin=2.31-0ubuntu8+lp1871129~1 -y --allow-downgrades
> sudo apt-mark hold libc6

This versions don't exist now. How to make htop work?

**Comment by LtAwesome16** [comment] 2020-08-28 20:03
Tried the fix, same problem above as "woreom"

**Comment by Bearbite** [comment] 2020-09-11 07:55
Same problem here as woreom. 
Black screen in the htop and the update is failed. 

Reading state information... Done
E: Version '2.31-0ubuntu8+lp18711291' for 'libc6' was not found
E: Version '2.31-0ubuntu8+lp18711291' for 'libc6-dev' was not found

**Comment by joebadmus** [comment] 2020-11-06 09:09
I'm getting the same version found error.. Has there been any update on this issue?
