### ISSUE TITLE
Wsl/ERROR_NOT_FOUND after installing Windows updates

### ISSUE THREAD

**Issue by target-san** [microsoft/WSL#10782] opened 2023-11-17 07:52 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.3693]

### WSL Version

2.0.9.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

N/A

### Distro Version

N/A

### Repro Steps

Install Windows updates (possibly KB5032189)

### Expected Behavior

Wsl works

### Actual Behavior

Error:
```
Element not found.
Error code: Wsl/ERROR_NOT_FOUND
```

### Diagnostic Logs

[WslLogs-2023-11-17_09-50-38.zip](https://github.com/microsoft/WSL/files/13388866/WslLogs-2023-11-17_09-50-38.zip)

**Comment by target-san** [comment] 2023-11-17 14:31
Didn't work. I erased service record, uninstalled WSL components from installer. Now I cannot even install it, installer simply closes immediately. WSL CLI returns same error.

**Comment by target-san** [comment] 2023-11-17 14:47
`wsl --install` ends with 0x80070490
Is there some proper way to clean WSL completely and then reinstall from scratch?
Or some comprehensive registry of WSL errors?

**Comment by target-san** [comment] 2023-11-17 14:55
After `wsl --update` and installing required kernel update MSI, I'm down to square one, `Wsl/ERROR_NOT_FOUND`

**Comment by OneBlue** [comment] 2023-11-17 23:23
@target-san: I'm not seeing anything in the logs you shared.

Can you try to manually install the [latest release](https://github.com/microsoft/WSL/releases/tag/2.0.9) and see if that helps ? 

Please share /logs again if a failed startup if that doesn't help

**Comment by target-san** [comment] 2023-11-18 05:52
@OneBlue 
[wsl.2.0.9.0.x64.log.zip](https://github.com/microsoft/WSL/files/13399107/wsl.2.0.9.0.x64.log.zip)
Well, according to log installation succeeded 🤷 
As of logs, I'm getting issue with [importing `AppX` module ](https://github.com/PowerShell/PowerShell/issues/13138). Was present before reinstall, just didn't notice. Need to solve before I get real logs. Honestly it's extremely frustrating how MS products tend to hide error information at all cost.

**Comment by target-san** [comment] 2023-11-18 05:55
Finally logs: 
[WslLogs-2023-11-18_07-54-11.zip](https://github.com/microsoft/WSL/files/13399140/WslLogs-2023-11-18_07-54-11.zip)

**Comment by osavoskin** [comment] 2023-11-18 11:54
@target-san 

I have just run into this issue myself. Spent half a day trying to fix it. Nothing has worked except for:

* reinstall of the windows components: virtual machines support & wsl support
* uninstall all the wsl updates
* wsl --install --no-distribution
* now wsl --status at least produces the report, but requires an update 
* run wsl --update --inbox (only the kernel)

Now you should be able to run your containers, at least. But any update to wsl (up to 2.0.9) will break it again, unfortunately.

** I guess the windows components reinstallation step is excessive and can be skipped. Try to just uninstall all the wsl updates and update the kernel (--inbox) to make it work.

**Comment by pahar0** [comment] 2023-11-19 03:46
https://github.com/microsoft/WSL/issues/10788#issuecomment-1817734924

**Comment by target-san** [comment] 2023-11-19 13:52
@pahar0 Yup, thanks. Works for me too. At least for now.
Though it's interesting what causes this requirement out of thin air.

**Comment by osavoskin** [comment] 2023-11-19 14:38
> Launching WSL from a terminal with administrator privileges works for me. [#10788 (comment)](https://github.com/microsoft/WSL/issues/10788#issuecomment-1817734924)

Hm, does not work for me, for some reason..

**Comment by pahar0** [comment] 2023-11-19 14:46
Launching WSL from a terminal with admin privs it's a workaround while we wait for a proper solution. We should be able to run it as a regular user.
@osavoskin interesting... could you try this https://github.com/microsoft/WSL/issues/10793#issuecomment-1817780109 ?

**Comment by osavoskin** [comment] 2023-11-19 16:20
Doesn’t help either. I have already tried everything. The only thing that worked is uninstalling all the updates. It allows me to work, at least. But the cli becomes unresponsive when the —shutdown command executed. So, the UX is awful

**Comment by DemonPenguin** [comment] 2023-11-20 12:56
Same issue, but I have also noticed that wslg.exe is missing and I can't seem to get it back no matter what I do

**Comment by baiciluigi** [comment] 2023-11-20 13:31
Same issue, can only run wsl with admin rights, everything else fails. Have to manually run it on admin.
Docker Desktop fails, but when launched with admin rights, succeeds aswell.
For now I can work like this but it needs to be fixed..

**Comment by bsatts** [comment] 2023-11-20 15:30
Yup running with admin rights is the only thing that works atm.

**Comment by OneBlue** [comment] 2023-11-20 21:53
Thanks everyone for reporting this.


To give some clarity: there are two issues with WSL 2.0.9:

1) `Wsl/CallMSI/E_ABORT`

We've identified the issue and working on a fix. You can workaround it by enabling the WSL optional component and rebooting

2) ` Wsl/ERROR_NOT_FOUND` 

We've not been able to reproduce the issue yet. We're investigating but to root cause it we'd need COM logs. 

If you can reproduce the issue, please follow these instructions to collect logs: 

* Download and extract [ComTrace.zip](https://github.com/microsoft/WSL/files/13419733/ComTrace.zip)
* Open an elevated command prompt
* Run: `wpr  -start ComTrace.wprp -filemode` 
* Reproduce the issue (example: `wsl.echo echo test`)
* Run `wpr -stop logs.etl`
* Share `logs.etl` on this issue

**Comment by bsatts** [comment] 2023-11-20 22:16
@OneBlue The problem is wsl works when the command is launched from an elevated terminal. That is the current workaround for the issue. Can we get the trace from a non-elevated terminal?

**Comment by OneBlue** [comment] 2023-11-20 22:18
> @OneBlue The problem is wsl works when the command is launched from an elevated terminal. That is the current workaround for the issue. Can we get the trace from a non-elevated terminal?

@bsatts: Yes you can start the trace from an elevated terminal and then reproduce the issue from another, non-elevated terminal. The log collection will capture that repro

**Comment by bsatts** [comment] 2023-11-20 22:24
Thank you. I started the wpr, then opened a new command prompt and typed wls. Then ended the wpr

[logs.zip](https://github.com/microsoft/WSL/files/13419930/logs.zip)

**Comment by OneBlue** [comment] 2023-11-20 23:13
Thank a lot @bsatts. We're getting closer. 

Can you try to execute: `C:\Program Files\WSL\wsl.exe` as non-elevated and see if that works ?

**Comment by pahar0** [comment] 2023-11-20 23:22
Some logs @OneBlue 
[logs.zip](https://github.com/microsoft/WSL/files/13420218/logs.zip)

**Comment by OneBlue** [comment] 2023-11-20 23:40
Thank you @bsatts and @pahar0. We have a theory now. To validate it, could you please use regedit to export the content of `HKLM\Software\Classes\PackagedCom` and share the .reg file with us ?

**Comment by pahar0** [comment] 2023-11-21 00:26
[regedit.zip](https://github.com/microsoft/WSL/files/13420512/regedit.zip)
There you go @OneBlue

**Comment by OneBlue** [comment] 2023-11-21 01:25
Thank you @pahar0. This confirms our theory: There is an old WSL installation that's conflicting with the latest package.

Can you try to: 

- Delete: `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PackagedCom\ClassIndex\{A9B7A1B9-0671-405C-95F1-E0612CB4CE7E}`
- See if that solves the issue

(You can use the .reg you just captured as backup if needed)

**Comment by benhillis** [comment] 2023-11-21 01:58
Thanks for all the help on this folks. This is a strange MSIX / packaged COM issue that we have not seen in internal testing. I know this issue is causing you all a lot of pain, and I'm hopeful we will have a fix to push out before turkey day.

**Comment by pahar0** [comment] 2023-11-21 07:13
Issue solved deleting `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PackagedCom\ClassIndex\{A9B7A1B9-0671-405C-95F1-E0612CB4CE7E}` in regedit.
Thank you guys @OneBlue @benhillis

**Comment by OneBlue** [comment] 2023-11-21 08:11
Thank for confirming @pahar0. So this confirms that the issue is this registry key being left over by previous install. We'll update our install logic to automatically remove it in the next update.

**Comment by Alkarex** [comment] 2023-11-21 11:08
On Windows 10, just deleting the newest WSL entry in the list of Windows applications worked for me https://github.com/microsoft/WSL/issues/10767#issuecomment-1816540839

**Comment by rgaiacs** [comment] 2023-11-21 11:41
I also had the same issue and confirm that deleting HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PackagedCom\ClassIndex\{A9B7A1B9-0671-405C-95F1-E0612CB4CE7E} in regedit resolve the issue.

**Comment by target-san** [comment] 2023-11-21 11:50
Same for me. Erasing that key solved issue permanently.

**Comment by DemonPenguin** [comment] 2023-11-21 14:18
Deleting the key worked for me. Now to sort out the display issue on wslg which seems to have a weird overlay on top of GUI apps.

![Screenshot 2023-11-21 141807](https://github.com/microsoft/WSL/assets/88834710/4f1c31da-464d-4aa7-8a37-77fa2b867021)

**Comment by benhillis** [comment] 2023-11-21 15:17
Thanks for the confirmation! @OneBlue is working on a fix now.

**Comment by aleluis79** [comment] 2023-11-21 20:48
![imagen](https://github.com/microsoft/WSL/assets/3486008/feb493e0-c2d0-4281-b142-2e1ed5cfa82d)

I added a dash to the old keys. That worked for me.

**Comment by JonasBollgruenDedalus** [comment] 2023-11-22 09:47
I deleted the ClassIndex {A9B.....} and the problem still persists

**Comment by AKN-CPH** [comment] 2023-11-22 14:36
> Issue solved deleting `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PackagedCom\ClassIndex\{A9B7A1B9-0671-405C-95F1-E0612CB4CE7E}` in regedit. Thank you guys @OneBlue @benhillis

THANK YOUUUUUUU. Deleting the reg. key also solved all WSL update problems for me.

**Comment by benhillis** [comment] 2023-11-22 19:24
Fixed with https://github.com/microsoft/WSL/releases/tag/2.0.11.

**Closed** 2023-11-22 19:42 UTC

**Comment by andjsouza** [comment] 2023-11-23 17:29
Issue solved deleting `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PackagedCom\ClassIndex\{A9B7A1B9-0671-405C-95F1-E0612CB4CE7E}`

Thanks :)

**Comment by lukasz-mitka** [comment] 2023-11-24 10:01
> Fixed with [`2.0.11` (release)](https://github.com/microsoft/WSL/releases/tag/2.0.11).

`wsl --update` was unable to pick it up. Had to manually install `msi` from the release.

**Comment by truongleeuet** [comment] 2023-11-26 08:39
I found a solution in: [here](https://answers.microsoft.com/en-us/windows/forum/all/error-code-wslerrornotfound/e09855f9-93f7-42a4-bf5a-8b6a2165522a). You can try it

**Comment by gignsky** [comment] 2023-12-13 20:54
Can confirm installing version 2.0.11 (pre-release) works in resolving this issue of not being able to access WSL without elevated privileges.
