### ISSUE TITLE
Emacs 29.1 fails to start emacsclient with '-n' flag

### ISSUE THREAD

**Issue by wang1zhen** [microsoft/WSL#10645] opened 2023-10-19 11:17 UTC
### Windows Version

Microsoft Windows [Version 10.0.22621.2428]

### WSL Version

1.2.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Debian 12 bookworm

### Other Software

GNU Emacs 29.1

### Repro Steps

1. install emacs 29.1 from testing or sid or stable-backports
2. run `emacsclient -c -a "" -n`

### Expected Behavior

emacsclient summonned

### Actual Behavior

emacs hangs in background

### Diagnostic Logs

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050953

**Comment by sirredbeard** [comment] 2023-10-23 21:34
I can reproduce this bug upgrading from emacs 1:28.2+1-15 in bookworm to 1:29.1+1-5 in testing.

The strace logs show that in 1.28:
```
sendto(3, "-env SHELL=/bin/bash -env WSL2_G"..., 3534, 0, NULL, 0) = 3534
recvfrom(3, "-emacs-pid 1632\n", 8192, 0, NULL, NULL) = 16
recvfrom(3, "", 8192, 0, NULL, NULL)    = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

However in 1.29 something goes wrong and the process is eventually killed:
```
sendto(3, "-env SHELL=/bin/bash -env WSL2_G"..., 3541, 0, NULL, 0) = 3541
setsockopt(3, SOL_SOCKET, SO_RCVTIMEO_OLD, "\36\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
recvfrom(3, "-emacs-pid 1632\n", 8192, 0, NULL, NULL) = 16
recvfrom(3, "-window-system-unsupported \n", 8192, 0, NULL, NULL) = 28
```

`emacsclient -c -a "" -n -nw` (with the -nw no window option set) does properly launch the emacs daemon in the background on 1.29.

This, along with the `-window-system-unsupported` mention in the strace suggests and issue with WSLg in emacs 1.29.

According to the release notes for emacs, 1.29 added official support for Wayland, dropping XWayland.

It may not be properly detecting Wayland in WSLg.

[emacs128.txt](https://github.com/microsoft/WSL/files/13079361/emacs128.txt)
[emacs129.log](https://github.com/microsoft/WSL/files/13079362/emacs129.log)


`GDK_BACKEND=x11 emacsclient -c -a "" -n` does not work.

**Comment by OneBlue** [comment] 2023-10-24 21:48
Thank you @wang1zhen. This indeed looks like a wslg issue. Transferring.

**Closed by OneBlue** 2023-10-24 21:48 UTC
