### ISSUE TITLE
WSL resolv.conf populated with DNS servers from disconnected network

### ISSUE THREAD

**Issue by fencepost** [Microsoft/WSL#2694] opened 2017-11-27 04:08 UTC
**Your Windows build number:**
10.0.16299.64

**What you're doing and what's happening:**
1. Enabled WSL, rebooted
1. Installed Ubuntu from the Store
1. Launched newly-installed Ubuntu
1. Ran a few sudo apt-get installs with no problems. 
1. Left for a while, 
1. Tried sudo apt-get update and unable to resolve security.ubuntu.com and archive.ubuntu.com
1. Did a bit of sleuthing
   1. Ping to 8.8.8.8 works, resolving does not
   1. resolv.conf has 3 DNS server entries - local firewall plus 2 servers at a client location I haven't been to for a couple weeks.
   1. No active interfaces on Windows have those client servers as DNS (via ipconfig /all)
   1. No interfaces that I checked (connected or disconnected) have static DNS entries at all (checking properties of the network adapters), including the Ethernet port and the disconnected SSTP VPN to that client. I did not actually check properties on all network interfaces before moving to the next step.
   1. Searched the registry for one of the client site IP addresses, found it in HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\\{GUID} on the DhcpNameServer value
   1. Searched the registry for the GUID, found it in HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkCards\3 on the ServiceName value. Corresponding value for Description is "Intel(R) 82579LM Gigabit Network Connection" which would be the internal Ethernet on the laptop. Entirely feasible that the last time that was connected was at that client site, and it may have been a month or more since that time.  

**Special Note:** This computer was upgraded from Windows 7 Pro to Windows 10 Pro since the last time it was at that location or connected to a wired network.

**What's wrong / what should be happening instead**
Probably shouldn't be pulling DNS values for networks that aren't connected. Not clear exactly how it's getting the DNS server addresses, because in looking through the Interfaces section mentioned above I did find one additional name server address that was not added to resolv.conf, so I don't think it's just enumerating the interfaces from the registry.

**Comment by Biswa96** [comment] 2017-11-28 14:02
>Not clear exactly how it's getting the DNS server addresses

@fencepost With IDA pro, I probably guess that the DNS IP address may be updated with help of `/init` daemon in GNU/Linux usermode. LxssManager may be behind all of these. init updates `/etc/resolv.conf` to get DNS from Windows. See the image below:

![init_config_update_network_info](https://user-images.githubusercontent.com/31443074/33323565-e396c3dc-d472-11e7-8622-7886c4c83ba5.png)

**Comment by rodrymbo** [comment] 2017-11-30 17:41
The OP doesn't say whether or not the Windows interfaces are getting set up with information from a DHCP server. If it is DHCP, that's where the DNS resolvers are coming from, or at least when I've had problems with the wrong DNS servers in resolv.conf, I've gone to the DHCP server and forced it to send the correct resolvers in the correct order, and fairly soon the resolv.conf that WSL (init?) generated was fixed to show those servers in that order.  (I.E. delete the resolv.conf and restart Windows.) If each interface has its own DHCP server configuring it, each would generate a different set of resolvers, which Windows must merge somehow into the list that gets into resolv.conf,

It sounds like the suggestion is that Windows should check the resolver info it gets from DHCP (or the configuration of the interface if static) for all the interfaces and, for the aggregate list of resolvers (which is what it passes to WSL to put in /etc/resolv.conf) confirm that (a) the resolvers are reachable and (b) they are appropriate for all possible routes in the current routing table (c) the resulting single list of resolvers complies with the intentions of the routing table (e.g. that certain hosts be routed through a VPN or other interface via one address from a higher priority local DNS resolver rather than the normal public address from a public resolver further down the list). That sounds like more telepathy than my computer can handle...

Of course, if the interfaces are set to "Use the following DNS server addresses" and somehow init is finding other **non-listed** DNS servers to put in resolv.conf, or if it is **not** using servers that **are** configured, that would be different. At least that's what I'd expect the GUI provided by Windows should do. If another configuration method is used, I'd expect it to be similarly deterministic.

Resolv.conf is created when WSL is initialized, and I think it is supposed to be updated when the configuration changes in Windows. If it is in the wrong state, e.g. when it was created Windows hadn't yet started a VPN, so the VPN's DNS choices aren't reflected) resolv.conf is supposed to get updated with the new information. If it is not, that would be something else to report.

WSL is passing networking off to Windows. If there are several interfaces on the Windows side (e.g. representing VPNs or different subnets) it would be the routing on the Windows side that determines whether the correct interface is being used. All WSL can do is resolve DNS with the resolvers in /etc/resolv.conf in the order provided by Windows, until an address is found, then pass the address to Windows and hope Windows uses the proper interface/routing.

(Or maybe when I wasn't looking we have gained the ability in WSL to bind to one interface, exclusive of routing on the Windows side, and use that interface instead of passing things off to Windows and hoping for the best?)

IPv6 can do things differently, so it might be good to turn off ipv4 when investigating ipv6 and vice versa.

**Comment by fencepost** [comment] 2017-11-30 17:57
(terse, on a phone)

Approximate time line: months ago, running Windows 7 and physically
connected to network at a client. Disconnected. Used in many locations on
wifi since. Updated to Windows 10. WSL and Ubuntu installed. Resolv.conf
contains dns servers from that client network even though connected to home
network.

**Comment by rodrymbo** [comment] 2017-11-30 19:20
@fencepost: 

What I'm getting from your latest is that Windows is somehow getting bogus resolvers from the registry to give to WSL/init, if it's not getting it from DHCP or from a static configuration. I assume you have deleted the resolv.conf and rebooted to let Windows create it again?

On my machine resolv.conf is definitely being created with information from some of the interfaces. I changed one and rebooted, and the two resolvers from that interface were what ended up first in resolv.conf, along with the first entry of the three on the other interface (which came from DHCP). (All of my interfaces are active, and the resolver I want it to use for all of them as the primary is still first on the resulting resolv.conf list, so I was happy. Maybe I shouldn't be?) So either Windows is selecting the resolvers from all the interfaces, and giving the top three (by creating an arbitrary sort order for the interfaces) to WSL/init to be put into resolv.conf, or WSL/init is choosing the top three and ignoring the rest. In other words, I was wrong, and it is not putting all resolvers into resolv.conf, just some of them. 

I'm not kidding about "arbitrary", The interface whose resolvers got priority has ID 16, while the other is 9; both ipconfig and route list 9 first then 16. Maybe 16 had the most recent creation so its got used first? Or maybe Windows has some other way to decide which interface has priority. Doesn't explain why Windows should even think about using resolvers configured for the non-connected interface, especially if the resolvers don't show up in ipconfig /all .

**Comment by Brian-Perkins** [comment] 2017-11-30 20:22
The current model is not ideal since resolv.conf is just a three item list (you can add more, but only the first three are used). This doesn't account for more interesting VPN scenarios using split horizons, etc. and picking the three to add to the list is just a heuristic built up via trial and error (#5) over time. The current version prioritizes first by VPN (which today just means PPP interface), then by the Windows concept of ["best"](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365922(v=vs.85).aspx) internet interface, and then finally by IPv4 since we see a lot of IPv6 issues due to configuration issues.

In this case the prioritization of the PPP/VPN interface is likely causing problem. The interface was likely left with an IP address and DNS server, so is being treated as an active VPN. Currently there is no explicit check for an interface being active. Many interfaces lose their IP address and/or DNS server when they are not active, so filtering out non-active interfaces is happening as a side-effect. Seems reasonable to make this explicit. I will check back when this change makes an Insider build to see if the problem is addressed.

**Comment by rodrymbo** [comment] 2017-12-01 15:16
I still think the best solution, as long as WSL passes all networking off to Windows, is to set up a resolver that runs as a service on the Windows side, listening to localhost and therefore usable by an app in WSL. If it used the normal Windows API to resolve DNS queries, and could be listed in /etc/resolv.conf for WSL apps to use, it would solve the problem of DNS/resolv.conf kludges in WSL resulting in a different result than what you get on the Windows side. That seems to have been the complaint right along: 'DNS works in Windows, why doesn't it "just work" in WSL.' It would also solve the UX "I can't connect" complaint when the reason is that DNS isn't resolving, but it's not obvious to the user. Assuming it resolves on the Windows side, the resolution would be available to a WSL application that queried it; and if it didn't resolve on the Windows side, one would use normal Windows Troubleshooting to figure out why.

This wouldn't necessarily need to be an "official" program, though by my way of thinking it would be implied by the way WSL does networking. Anything less than using Windows itself as the resolver (instead of some three of the resolvers that Windows knows about and passes along to WSL but not necessarily the ones it would use itself) will inevitably result in inconsistencies.

If I had better programming skills I'd work on it myself ...

**Comment by therealkenc** [comment] 2017-12-01 16:56
> If it used the **normal Windows API to resolve DNS queries**, and could be listed in /etc/resolv.conf for WSL apps to use, it would solve the problem of DNS/resolv.conf kludges in WSL resulting in a different result than what you get on the Windows side.

That is a usermode API; there is no DNS kernel surface in either NT or Linux. Queries are resolved by `glibc` (or [musl](https://wiki.musl-libc.org/) or [bionic](https://android.googlesource.com/platform/bionic/)). What you are postulating works for something like Cygwin, but does not for WSL because WSL has no idea (or care) what reasons `glibc`/`musl`/`bionic` are making the syscalls they make on port 53. It could be a web server listening on that port for all the kernels care.

I would wax lyrical on another approach, but the team is already aware of that avenue, and at this point I think I face an uphill battle convincing them not to expend resources reimplementing `tmpreaper` or `system-tmpfiles` let alone more complicated Linux startup infrastructure like `resolv.conf`. Until another day.

**Comment by jstarks** [comment] 2017-12-19 22:18
This should be improved in [insider build 17063](https://docs.microsoft.com/en-us/windows/wsl/release-notes).

**Comment by diveyez** [comment] 2018-03-14 16:20
SHOULD BE IMPLEMENTED. Any SSH tunnels or VPN usage kills WSL connectivity. This is NOT GOOD.

**Comment by diveyez** [comment] 2018-03-14 16:24
cp /etc/resolv.conf ~/backup.resolv.conf
nano /etc/resolve.conf 
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver <ip of your vpn connection>

ctrl+x y enter

DONE

**Closed** 2018-05-24 22:15 UTC
Labels: fixedininsiderbuilds

**Comment by loganmancuso** [comment] 2019-07-02 02:14
i used this at the end of my bashrc to update the nameserver fir WSL2 hopefully this helps someone
local_addr=$(tail -1 /etc/resolv.conf | sed 's/^.\{11\}//')                                                                       export DISPLAY=$local_addr:0.0
