### ISSUE TITLE
Rails server spams log due to getsockopt(2) TCP_INFO ENOPROTOPT

### ISSUE THREAD

**Issue by ArsalanDotMe** [microsoft/WSL#1982] opened 2017-04-22 06:47 UTC
Microsoft Windows [Version 10.0.15063]

Clean installed rails 5.0.2 on Ruby 2.4.0 through rebenv 1.1.0-2-g4f8925a.
Went into a directory owned by Windows. Created a new project and started the server with `rails s`. The command was extremely slow to start and once it showed the following output, I made a simple GET request to localhost:3000. 

```
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/app_loader.rb:40: warning: Insecure world writable dir /home/arsalan/.rbenv/versions in PATH, mode 040777
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.1 (ruby 2.4.0-p0), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

On making the GET request, the following error showed up.

```
2017-04-22 11:40:02 +0500: Read error: #<Errno::ENOPROTOOPT: Protocol not available - getsockopt(2)>
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.8.1/lib/puma/server.rb:124:in `getsockopt'
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.8.1/lib/puma/server.rb:124:in `closed_socket?'
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.8.1/lib/puma/server.rb:563:in `handle_request'
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.8.1/lib/puma/server.rb:425:in `process_client'
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.8.1/lib/puma/server.rb:289:in `block in run'
/home/arsalan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/puma-3.8.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I don't know if strace of this command will be useful as it keeps continuously spitting out lines at the speed of light. Never exits.

The relevant error-throwing line from puma seems to be
```ruby
socket.getsockopt(Socket::SOL_TCP, Socket::TCP_INFO)
```

**Comment by ArsalanDotMe** [comment] 2017-04-22 06:59
It looks like the TCP_INFO option on the linux getsockopt(2) is not supported at this point. 

Please see: [TCP Options](http://man7.org/linux/man-pages/man7/tcp.7.html)

TCP_INFO (since Linux 2.4)
              Used to collect information about this socket.  The kernel
              returns a struct tcp_info as defined in the file
              /usr/include/linux/tcp.h.  This option should not be used in
              code intended to be portable.

**Comment by sunilmut** [comment] 2017-04-22 07:07
@ArsalanDotMe - Thanks for reporting the issue and the detailed information. Very helpful. Yes, we don't need the whole trace. You have already provided the relevant pieces. I can confirm that WSL currently does not implement the `TCP_INFO` socket option.

> It looks like the TCP_INFO option on the linux getsockopt(2) is not supported at this point.

Why do you feel that Linux does not support this socket option? I don't think that is accurate (otherwise the above wouldn't run on Linux). Are you confusing between `portable` vs `supported`?

Irrespective, I have opened a task at our end to track this. Thanks again for trying WSL and providing feedback.

**Comment by sunilmut** [comment] 2017-04-22 07:09
@ArsalanDotMe - Thanks for reporting the issue and the detailed information. Very helpful. Yes, we don't need the whole trace. You have already provided the relevant pieces. I can confirm that WSL currently does not implement the TCP_INFO socket option.

I have opened a task at our end to track this. Thanks again for trying WSL and providing feedback.

**Comment by guenard** [comment] 2017-06-06 17:36
Just wanted to add that I got a similar log from PHP-FPM 5.6. ~ one line per second is written in `/var/log/php5.6-fpm.log` (_TCP_INFO for socket: Protocol not available_). Same as #2090.

**Comment by adamluzsi** [comment] 2017-06-12 13:31
+1

**Comment by linhecheng** [comment] 2017-07-20 09:46
+1

**Comment by sunilmut** [comment] 2017-07-20 22:19
Can someone share clear (and if possible targeted) repro steps for this? I am looking into it right now and need that for validation.

**Comment by ArsalanDotMe** [comment] 2017-07-21 07:19
I'm happy to provide more detailed reproduction steps, but looking at the first message in the thread, what do you think is missing in detail to reproduce the error? I tried to provide exact version numbers and steps for all software involved.

**Comment by sunilmut** [comment] 2017-07-21 18:54
@ArsalanDotMe - Thanks. Yes, the first thread does provide the exact versions, but I was hoping to get exact instructions since I am not familiar with rails. That way, I can copy paste the instructions for the repro and focus on fixing the issue.

**Comment by ArsalanDotMe** [comment] 2017-07-22 14:25
The guide I followed is this one: https://gorails.com/setup/windows/10

You don't need to setup mysql or postgres, otherwise the guide is the same.

**Comment by adamluzsi** [comment] 2017-07-22 20:06
Hy @sunilmut ,

Here is a [example repo](https://github.com/adamluzsi/rack-example) where all you need is to install and run (or if you have both ruby and bundler all you need is to start the app).
I tried to create an install script but I couldn't test it because I'm not in wsl/ubuntu now.

I met with this too and the problem is about a yet not implemented socket protocol. 
I can't confirm that the bug stills on, but if you clone the repo and run it and try call it with some http requests, than you can reproduce the problem.

**Comment by Marthyn** [comment] 2017-07-26 12:53
👍 	
Ruby 2.2.4
Rails 4.2.7.1
Running `bundle exec unicorn -p 5001` 

Results in
`Protocol not available- setsockopt(2) (Errno::ENOPROTOOPT)`

**Comment by bitcrazed** [comment] 2018-03-30 23:35
@ArsalanDotMe Could you try repro'ing on a recent Insiders build? I am running build 17364, and cannot repro your scenario - all looks good to me!

I installed rvm using [DigitalOcean's instructions](https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rvm-on-ubuntu-16-04), and then installed rails, and created a new rails templated site using `rails new ./rubytest`. I then ran `rails s` to build & serve the site, and navigated to its URL:

![image](https://user-images.githubusercontent.com/961950/38155897-2e7f4024-342f-11e8-990d-72a9191e07eb.png)

Please let us know if your issue persists.

**Comment by therealkenc** [comment] 2018-03-31 00:27
I _think_ this got picked up with #393 #68.  AFAIK, Rails has worked for a while (there would be more noise if it didn't). Best @sunilmut weigh in on the status of `TCP_INFO`. Caveat being, stuff is being worked around upstream, and it is hard to tell whether the surface was fixed or just dealt with. There is no mention of `TCP_INFO` for [some time](https://github.com/Microsoft/WSL/issues/393#issuecomment-230519977). Nothing in the release notes (natch).

**Comment by bitcrazed** [comment] 2018-04-02 17:38
Yep - difficult to know if this is upstream or WSL now supporting TCP_INFO - what say you @sunilmut? 😁

**Comment by Yay295** [comment] 2018-05-03 01:03
This is still not supported in Redstone 4. A quick test with Python
```
import socket
socket.socket().getsockopt(socket.SOL_TCP, socket.TCP_INFO)
```
shows
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 92] Protocol not available
```

**Comment by brucek2** [comment] 2018-06-18 07:51
Since #2090 was duped to here and closed, I'll note that for me php7.1-fpm is still generating a once per second log entry:
ERROR: failed to retrieve TCP_INFO for socket: Protocol not available (92)

FPM is otherwise working but it'd be nice if there was a fix for this nuisance. Anyone have a good workaround?

**Comment by therealkenc** [comment] 2018-06-18 10:00
Thanks @brucek2 and @Yay295 for confirming. So `TCP_INFO` is just not implemented. The work-around would be to recompile php without config [`HAVE_LQ_TCP_INFO`](https://github.com/php/php-src/blob/be49d61b19cea80ccc76e82f8faf2b2a640b658c/sapi/fpm/fpm/fpm_sockets.c#L480). Or for that matter, just comment out the `zlog()` [line](https://github.com/php/php-src/blob/be49d61b19cea80ccc76e82f8faf2b2a640b658c/sapi/fpm/fpm/fpm_sockets.c#L490). It isn't fatal, but I can imagine the over-aggressive logging once second is pretty problematic.

@sunilmut - You don't from any practical standpoint have to [wait on](https://github.com/Microsoft/WSL/issues/393#issuecomment-230519977) the NT tcp stack people to implemented this. The feature wasn't forthcoming from them in April of 2016, and it probably isn't forthcoming in 2018 either. Just let `getsockopt()` succeed and fill in the `struct tcp_info` with zeros. As long as `.tcpi_sacked` is zero then php will just [move on](https://github.com/php/php-src/blob/be49d61b19cea80ccc76e82f8faf2b2a640b658c/sapi/fpm/fpm/fpm_sockets.c#L507) (and, mercifully, does so without spamming the log).

There is a decent backgrounder on `TCP_INFO` [here](https://linuxgazette.net/136/pfeiffer.html).

**Comment by jbrooksuk** [comment] 2018-07-23 18:02
I'm seeing:

```
ERROR: failed to retrieve TCP_INFO for socket: Protocol not available (92)
```

Every second (although not since changing `log_level = alert`) but nginx does not respond with anything, it's just a blank screen - although this may be fault of valet-wsl?

**Comment by SamSaffron** [comment] 2018-08-14 02:14
The ruby unicorn web server is definitely not working right per: 

https://bogomips.org/unicorn-public/CAAtdryOtTO8HGTeKLy_JbeRhWLC7JZpCABVpbpEK+z67JHx=ew@mail.gmail.com/T/#u

**Comment by tara-raj** [comment] 2018-08-24 16:30
We’re investigating approaches to address this issue and will report back when we have something concrete to share. Will update this thread at that time with details!

**Comment by SamSaffron** [comment] 2018-08-27 04:13
Awesome @tara-raj , if you need any help testing I am happy to flick whatever switches I need to run bleeding edge wsl.

**Comment by Haacked** [comment] 2018-09-20 22:11
I'm happy to test as well. Ran into this with nginx and a ruby sinatra app.

**Comment by maatinito** [comment] 2018-10-20 01:32
So to resume: 
Unicorn doesn't work which breaks dev with rails and there are two problems: 
  - getsockopt(socket.SOL_TCP, socket.TCP_INFO) ==> ENOPROTOPT 
  - getsockopt(TCP_CORK/TCP_NOPUSH) ==> ENOPROTOPT 

WSL is very promising, very exciting so good luck guys and thanks :-)

**Comment by lustremedia** [comment] 2019-05-21 15:01
> 
> 
> So to resume:
> Unicorn doesn't work on WSL and there are two problems:
> 
>     * getsockopt(socket.SOL_TCP, socket.TCP_INFO) ==> ENOPROTOPT
> 
>     * getsockopt(TCP_CORK/TCP_NOPUSH) ==> ENOPROTOPT
> 
> 
> Waiting for more support, as Unicorn is just a way to laucnh multiple rails server for performance, for the dev, I removed the dependency on Unicorn in file Gemfile, uninstall unicorn using `sudo gem uninstall unicorn` and everything works fine :-)
> 
> WSL is very promising, very exciting so good luck guys and thanks :-)



> 
> 
> 👍
> Ruby 2.2.4
> Rails 4.2.7.1
> Running `bundle exec unicorn -p 5001`
> 
> Results in
> `Protocol not available- setsockopt(2) (Errno::ENOPROTOOPT)`

Unicorn is still not working for me, ruby 2.4.0 rails 4.2.8

**Comment by lustremedia** [comment] 2019-05-21 15:02
> 
> 
> So to resume:
> Unicorn doesn't work on WSL and there are two problems:
> 
>     * getsockopt(socket.SOL_TCP, socket.TCP_INFO) ==> ENOPROTOPT
> 
>     * getsockopt(TCP_CORK/TCP_NOPUSH) ==> ENOPROTOPT
> 
> 
> Waiting for more support, as Unicorn is just a way to laucnh multiple rails server for performance, for the dev, I removed the dependency on Unicorn in file Gemfile, uninstall unicorn using `sudo gem uninstall unicorn` and everything works fine :-)
> 
> WSL is very promising, very exciting so good luck guys and thanks :-)

Unicorn is still not working for me, ruby 2.4.0 rails 4.2.8, I will try this workaround, just switched to WSL!

**Comment by lustremedia** [comment] 2019-05-21 15:03
> 
> 
> So to resume:
> Unicorn doesn't work on WSL and there are two problems:
> 
>     * getsockopt(socket.SOL_TCP, socket.TCP_INFO) ==> ENOPROTOPT
> 
>     * getsockopt(TCP_CORK/TCP_NOPUSH) ==> ENOPROTOPT
> 
> 
> Waiting for more support, as Unicorn is just a way to laucnh multiple rails server for performance, for the dev, I removed the dependency on Unicorn in file Gemfile, uninstall unicorn using `sudo gem uninstall unicorn` and everything works fine :-)
> 
> WSL is very promising, very exciting so good luck guys and thanks :-)

Unicorn is still not working for me, ruby 2.4.0 rails 4.2.8, I will try this workaround, just switched to WSL!

**Comment by jobs-git** [comment] 2019-12-30 20:23
Which windows version has this been solved?

**Comment by Morgy93** [comment] 2020-02-17 17:47
Any update on this one?
Seems to be the same case for [symfony](https://symfony.com/):

```
$ symfony serve

Feb 17 18:44:17 |DEBUG| PHP    Reloading PHP versions 
Feb 17 18:44:18 |DEBUG| PHP    Using PHP version 7.4.2 (from default version in $PATH) 
Feb 17 18:44:18 |INFO | PHP    listening path="/usr/sbin/php-fpm7.4" php="7.4.2" port=51199
Feb 17 18:44:18 |DEBUG| PHP    started 
Feb 17 18:44:19 |INFO | PHP    'user' directive is ignored when FPM is not running as root 
Feb 17 18:44:19 |INFO | PHP    'group' directive is ignored when FPM is not running as root 
Feb 17 18:44:19 |ERROR| PHP    failed to retrieve TCP_INFO for socket: Protocol not available (92) 
Feb 17 18:44:19 |INFO | PHP    fpm is running, pid 26731 
Feb 17 18:44:19 |INFO | PHP    ready to handle connections 
Feb 17 18:44:19 |INFO | PHP    systemd monitor interval set to 10000ms 
                                                                                                                        
 [OK] Web server listening on http://127.0.0.1:8001 (PHP FPM 7.4.2)                                                     
                                                                                                                        

WARNING unable to find the application log
Feb 17 18:44:20 |ERROR| PHP    failed to retrieve TCP_INFO for socket: Protocol not available (92) 
Feb 17 18:44:21 |ERROR| PHP    failed to retrieve TCP_INFO for socket: Protocol not available (92) 
Feb 17 18:44:22 |ERROR| PHP    failed to retrieve TCP_INFO for socket: Protocol not available (92) 
Feb 17 18:44:23 |ERROR| PHP    failed to retrieve TCP_INFO for socket: Protocol not available (92) 
Feb 17 18:44:24 |ERROR| PHP    failed to retrieve TCP_INFO for socket: Protocol not available (92)
... and so on ... every second ...
```

**Comment by SamSaffron** [comment] 2020-02-18 00:09
strongly recommend just closing this issue as "is fixed with WSL2, will not be fixed with WSL1" 

No point carrying it around forever.

**Comment by Yay295** [comment] 2020-02-18 03:45
It would be nice if it were fixed in WSL1 though.

**Comment by sarim** [comment] 2020-06-05 16:32
> strongly recommend just closing this issue as "is fixed with WSL2, will not be fixed with WSL1"
> 
> No point carrying it around forever.

@SamSaffron why? Did Microsoft announced WSL1 as abandoned, deprecated product already? As far as I remember when announcing WSL2, they said both wsl1 and wsl2 would be maintained. I'd like to see msft continuing to make wsl1 as complete as possible, which means implementing `TCP_INFO` somewhere in the future.

**Closed** 2020-06-05 18:18 UTC
Labels: fixed-in-wsl2, network

**Comment by Morgy93** [comment] 2020-06-06 07:58
> > strongly recommend just closing this issue as "is fixed with WSL2, will not be fixed with WSL1"
> > No point carrying it around forever.
> 
> @SamSaffron why? Did Microsoft announced WSL1 as abandoned, deprecated product already? As far as I remember when announcing WSL2, they said both wsl1 and wsl2 would be maintained. I'd like to see msft continuing to make wsl1 as complete as possible, which means implementing `TCP_INFO` somewhere in the future.

You're right. In fact there are even official [exceptions for using WSL 1 rather than WSL 2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions#exceptions-for-using-wsl-1-rather-than-wsl-2)

But to answer the question:
> What will happen to WSL 1? Will it be abandoned?
> We currently have no plans to deprecate WSL 1. You can run WSL 1 and WSL 2 distros side by side, and can upgrade and downgrade any distro at any time. Adding WSL 2 as a new architecture presents a better platform for the WSL team to deliver features that make WSL an amazing way to run a Linux environment in Windows.
Source: https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#what-will-happen-to-wsl-1-will-it-be-abandoned

**Comment by sarim** [comment] 2020-06-06 12:08
well if existing valid issue about wsl1 keep getting closed with `fixed-in-ws2` tag, I don't see much hope for msft fixing wsl1 issues. Sad.

**Comment by jobs-git** [comment] 2020-06-28 08:36
My hardware has driver problem with recent windows 10 releases so I am using wsl1. I hope they get it fixed there.

**Comment by privatehosting** [comment] 2020-08-24 15:42
@jobs-git  Install Update KB4566116 for Windows 10 1909 and sex wsl to version 2. Then you can continue your work.

**Comment by abdulrehman3222** [comment] 2022-02-22 19:07
I was having a similar issue with

WSL: `1`, Ruby: `2.5.0`, Rails: `4.2.1`, and Puma: `3.8.0` 

my rails s was working I was getting the following error whenever I send a Get request:

```
    Read error: #<Errno::ENOPROTOOPT: Protocol not available - getsockopt(2)>
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:124:in `getsockopt'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:124:in `closed_socket?'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:563:in `handle_request'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:425:in `process_client'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:289:in `block in run'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I struggle a lot for fixing that issue even I try the above solution but that didn't work either. 

at last, I found a simple solution that I need to update my Pum from 3.8 to 3.12+ and it works perfectly for me.
