### ISSUE TITLE
WSL is unoperable (all non built-in commands segfault or throw I/O error)

### ISSUE THREAD

**Issue by mcDandy** [microsoft/WSL#8275] opened 2022-04-12 10:39 UTC
### Version

Microsoft Windows [Version 10.0.22593.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 21.10?

### Repro Steps

1. Have installed php 3.7.4 and apache2 with default everything from using apt
2. download PHP 3.8.1 to \\wsl.localhost\Ubuntu\tmp\mozilla_daniel0
3. extract it to that place (I used 7zip and I needed to fix executibility by chmod +x on relevant files and miss ./build/shtool)
4. run ./configure
5. install missing library using adb
6. repeat untill ./configure does not need anything to install
7. run make
8. run make test
9. fix executability of ./build/shtool
10. repeat 6 and 7
11. run make test
12. only builtin commands works.

### Expected Behavior

I can run any command and copy files from windows or create them.

### Actual Behavior

```
make test
...
SKIP sapi_windows_set_ctrl_handler() [sapi/cli/tests/sapi_windows_set_ctrl_handler.phpt] reason: this test is for Windows platforms only
PASS Testing ftell() on std streams [sapi/cli/tests/std_streams.phpt]
TEST 12580/12696 [sapi/cli/tests/upload_2G.phpt]
Warning: file_put_contents(/tmp/mozilla_daniel0/php-8.1.4/sapi/cli/tests/upload_2G.exp): Failed to open stream: Read-only file system in /tmp/mozilla_daniel0/php-8.1.4/run-tests.php on line 2748
ERROR: Cannot create expected test output - /tmp/mozilla_daniel0/php-8.1.4/sapi/cli/tests/upload_2G.exp
rm: cannot remove '/tmp/mozilla_daniel0/php-8.1.4/tmp-php.ini': Read-only file system
make: *** [Makefile:204: test] Error 1
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ make test > tst.log
-bash: tst.log: Read-only file system
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ touc a
-bash: /usr/lib/command-not-found: Input/output error
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ touch a
Segmentation fault
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ touch ad
Segmentation fault
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ mv ../php-8.1.4 ~
Segmentation fault
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ cp ../php-8.1.4 ~
Segmentation fault
daniel@DANIEL-NTB:/tmp/mozilla_daniel0/php-8.1.4$ cd ~
daniel@DANIEL-NTB:~$ touch a
Segmentation fault
```

When copying from wsl: cannot read from source dics 
![image](https://user-images.githubusercontent.com/18588943/162938329-0cb88286-95a7-4baa-804f-17442d63f5bb.png)

when copying to the disc: Disc protected agnist rewrite 
![image](https://user-images.githubusercontent.com/18588943/162938558-52744f26-0f6d-4bac-a7b0-fbada950ab59.png)

It is also not possible to get exact ubuntu version which I do not remember.

### Diagnostic Logs

`strace -ff touch
-bash: /usr/bin/strace: Input/output error`

**Comment by mcDandy** [comment] 2022-04-12 11:15
It might be helpfull that I had very little space left on drive C:. I freed some space, but it did not fix anything.

**Comment by mcDandy** [comment] 2022-04-12 11:30
appears to be fixable by reinstalling/updating wsl
```
Microsoft Windows [Version 10.0.22593.1]
(c) Microsoft Corporation. Všechna práva vyhrazena.

C:\Windows\System32>wsl.exe --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 28.03.2022
WSL automatic updates are on.

Kernel version: 5.10.102.1

C:\Windows\System32>wsl.exe --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

C:\Windows\System32>wsl.exe --status
Výchozí distribuce: Ubuntu
Výchozí verze: 2
Verze WSL: 0.58.0.0
Verze jádra: 5.10.102.1
Verze WSLg: 1.0.32
Verze MSRDC: 1.2.2924
Verze Direct3D: 1.601.0
Verze Windows: 10.0.22593.1

C:\Windows\System32>
```

**Comment by OneBlue** [comment] 2022-04-12 21:28
Thanks for reporting this @mcDandy.

Low disk space shouldn't cause segfaults, but low memory can.
I'm closing for now since the issue appears to be fixed, but please reopen and collect some logs if it happens again (see https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually )

**Comment by mcDandy** [comment] 2022-04-13 13:40
It is happening again, but I cannot reopen it.

**Comment by mcDandy** [comment] 2022-04-13 13:57
@OneBlue can you reopen it?
the way I used does no longer fix it becouse I am the latest version and I have 3GB of RAM free.
The main problem is that I cannot read or write to wsl drive.

**Comment by mcDandy** [comment] 2022-04-13 14:13
It appears I cannot create profile manually. And I might have clicked on something that is not other in centrum feedback, but I am not sure.
```
PS D:\Users\Daniel Martinek\Documents\wprp> wpr -start wsl.wprp -filemode
PS D:\Users\Daniel Martinek\Documents\wprp>  wpr -stop wsl.etl
Press Ctrl+C to cancel the stop operation.

        There are no trace profiles running.

        Error code: 0xc5583000
PS D:\Users\Daniel Martinek\Documents\wprp> wpr -start wsl.wprp -filemode

        The profiles are already running.

        Profile Id:

        Error code: 0xc5583001
PS D:\Users\Daniel Martinek\Documents\wprp> wpr -stop wsl.etl
Press Ctrl+C to cancel the stop operation.

        There are no trace profiles running.

        Error code: 0xc5583000
PS D:\Users\Daniel Martinek\Documents\wprp>
```

Sometimes it works and sometimes not.

**Comment by mcDandy** [comment] 2022-04-13 14:35
RAM is above 5GB free, disk got filled and error is back.

**Comment by mcDandy** [comment] 2022-04-13 15:09
can be fixed by restart of ubuntu, but it can be as easily back by running php 8.1.4 checker.

**Comment by OneBlue** [comment] 2022-04-13 19:45
Hmm I'm wondering if the issue is that there's just no more space to write the log file. In that case I'm not sure how we can gather logs for this.


Maybe the log capture automatically stops once the machine runs out of space. What's the output of 'dmesg' once the message gets into that state ?

**Comment by mcDandy** [comment] 2022-04-14 15:33
Thats wierd... Now the trace works.

**Comment by mcDandy** [comment] 2022-04-14 15:48
Windows does not know that message and when wsl is in that broken state it doesnot premit of running any program which is not built-in. I am trying to recreate the broken state with profiller running. No luck yet.

**Comment by mcDandy** [comment] 2022-04-14 17:25
I managed to recreate it. It is caused by full disc.
[wsl2.zip](https://github.com/microsoft/WSL/files/8491106/wsl2.zip)

**Comment by OneBlue** [comment] 2022-04-18 22:52
Thank you @mcDandy.

Looking at the logs, this looks like the root cause of the segfault you're seeing:
```
[69281.945980] sd 0:0:0:2: Device offlined - not ready after error recovery
[69282.310303] EXT4-fs (sdc): failed to convert unwritten extents to written extents -- potential data loss!  (inode 119429, error -30)
```

Which makes sense since the Windows disk is full.

Unfortunately, this is not something that WSL can fix easily, if there's no space left on disk and the WSL guest tries to write to its virtual disk, things will inevitably start failing.

**Closed** 2022-05-03 22:26 UTC

**Comment by afilp** [comment] 2023-01-11 06:14
It is happening to me also, Windows 10, wsl2.
