### ISSUE TITLE
Subversion error E070008 when working in /mnt/c/

### ISSUE THREAD

**Issue by ShimShamSam** [Microsoft/WSL#350] opened 2016-05-12 16:36 UTC
I get the following error when running something as simple as **svn stat**:

```
$ svn: E070008: Can't read directory '/mnt/c/Users/Sam/trunk': Partial results are valid but processing is incomplete
```

SVN commands work fine if not in /mnt/c

**Comment by fpqc** [comment] 2016-05-12 20:02
This is a known issue, and it is by design:

https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/

See the difference between VoIFS and DriveFS.  DriveFS (which behaves like linux mounts of NTFS partitions) is not well-behaved for lots of stuff.

However, some of the devs mentioned that they are considering making DriveFS more compatible with Linuxy stuff if lots of problems arise in actual use.

**Comment by therealkenc** [comment] 2018-03-24 20:50
Per-directory case sensitivity for DrvFs was added in 17093, metadata for stat in 17063, symlinks in 17046. If the `svn stat` scenario still has outstanding fails, please file a new issue following the template.

**Comment by tara-raj** [comment] 2018-05-22 20:55
Closing as per https://github.com/Microsoft/WSL/issues/350#issuecomment-375923979. Fixed in [Insiders Build 17093](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17093)

**Closed by tara-raj** 2018-05-22 20:55 UTC
Labels: fixedininsiderbuilds
