### ISSUE TITLE
emacs hangs on scratch buffer for 2 seconds when opening unless key is pressed

### ISSUE THREAD

**Issue by vemacs** [microsoft/WSL#1775] opened 2017-03-13 18:29 UTC
**Description:** emacs-nox takes an order of magnitude slower to load than on a "real" Ubuntu 14.04 machine with worse specifications, and other text editors

**Expected results:** emacs should open almost instantaneously, allowing you to edit files

**Actual results:** emacs hangs on a scratch buffer for about 2 seconds before opening any file. You can "skip" this delay by pressing a random key, but that inserts weird characters at the top of the file (#1505) and isn't something you want to do every time you want to edit a file.

Timings on Bash on Ubuntu on Windows:
```
[01:22:48] ylin:~ $ time emacs --debug-init --eval '(kill-emacs)'

real    0m2.253s
user    0m0.016s
sys     0m0.203s
[01:23:26] ylin:~ $ time emacs --debug-init -eval '(kill-emacs)' -Q

real    0m2.247s
user    0m0.047s
sys     0m0.141s
````

Timings with real Ubuntu 14.04.5 installation on a slower computer:
```
[06:30:04] vemacs@vlt-stor:~ $ time emacs --debug-init --eval '(kill-emacs)'

real    0m0.097s
user    0m0.028s
sys     0m0.024s
[06:30:56] vemacs@vlt-stor:~ $ time emacs --debug-init --eval '(kill-emacs)' -Q

real    0m0.088s
user    0m0.024s
sys     0m0.012s
```

**Windows build number:** 15055, this has happened on every Bash on Ubuntu on Windows since 14393.

**Steps:** 

    sudo apt-get install emacs24-nox
    emacs myfile.txt

Timing commands are provided in the Actual Results section.

**Comment by stehufntdev** [comment] 2017-03-14 16:31
Thanks for reporting the issue.  Can you please share out an strace with timestamps of the emacs launch?

**Comment by vemacs** [comment] 2017-03-15 19:44
strace with relative timestamps: http://paste.ubuntu.com/24184468/

The hang appears to be at:

        1.995777 ioctl(3, FIONREAD, [0])   = 0

**Comment by stehufntdev** [comment] 2017-03-17 01:18
Thanks for providing the strace!  Looking through the code the only thing I can think of here is waiting with a lock held, but I'll need to get a local repro and report back.

**Comment by vemacs** [comment] 2017-03-22 01:58
I upgraded my Bash on Ubuntu on Windows installation to 16.04 and this is still an issue, by the way.

**Comment by stehufntdev** [comment] 2017-04-07 20:50
Thanks for the update.  Marking this as a bug for tracking.

**Comment by vemacs** [comment] 2017-04-15 19:16
Sorry for bothering you guys again, I just took a new strace on 16.04 and the hanging call is slightly different. Here's the strace: http://paste.ubuntu.com/24389133/

Here's the hanging call:

         1.995286 poll([{fd=6, events=POLLIN}], 1, 0) = 0 (Timeout)

**Comment by stehufntdev** [comment] 2017-04-18 18:38
Not a bother at all, and thanks for the update.  Based on the above, we're probably missing an epoll update.

**Comment by xarthurx** [comment] 2018-03-10 22:27
I can confirm with this issue. using Emacs25.

Another observation is, it seems the problem is related to FS IO.
emacs open/read files for the first time will be painfully slow.
But after that, reopen/re-read will be fast as long as you don't kill emacs or close bash.exe.

**Comment by zachmu** [comment] 2019-08-07 00:40
Issue is still alive and well. Has anyone discovered a workaround?

**Comment by HenryGessau** [comment] 2020-06-18 00:46
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu)
Windows 10 Pro, Version	10.0.19041 Build 19041
WSL2
Still seeing the problem.

**Comment by therealkenc** [comment] 2020-09-23 04:01
@HenryGessau what is the output you get from the OP repro on 19041:

![image](https://user-images.githubusercontent.com/7049700/93965300-a6eed800-fd16-11ea-8b9e-c335993907df.png)

**Comment by HenryGessau** [comment] 2020-09-23 13:55
@therealkenc I am no longer encountering this issue. Sorry, I don't know when it stopped happening.

**Closed** 2021-05-05 16:52 UTC
