### ISSUE TITLE
WSL2 cannot access 'c': Input/output error

### ISSUE THREAD

**Issue by Chelayel** [microsoft/WSL#6174] opened 2020-10-30 14:05 UTC
# Environment
Windows 10 Pro 19041.572

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Whether the issue is on WSL 2 and/or WSL 1: [run `cat /proc/version` in WSL]
```

# Steps to reproduce

From the wsl2 console navigate to c folder
Perform any operation on any c folder, such as ls, or vim.
I get WSL2 cannot access 'c': Input/output error.
wsl --shutdown does not fixt the issue

**WSL logs**: 
https://aka.ms/AAa4w8z

#  Expected behavior
I need to be able to do any IO operations on the C drive.
On WSL1, this issue is invalid. It only occurs on WSL2

# Actual behavior

Getting cannot access 'c': Input/output error when accessing the c folder

**Comment by kwint** [comment] 2020-10-31 00:20
Related: https://github.com/microsoft/WSL/issues/4377 Altough people there can fix it by `wsl --shutdown`

**Comment by Ludorg** [comment] 2020-11-04 22:47
Same issue here, may be after a migration/conversion from WSL1 to WSL2 of Ubuntu 20.04

```
[Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```
`dmesg` output captured hereafter
![image](https://user-images.githubusercontent.com/3078575/98174878-df78f880-1ef5-11eb-80e1-ad871330eb82.png)

`wsl --shutdown` and restart of wsl is a working workaround (but not so comfortable)

Some (hopefully useful additional information)
```console
ludorg@Cyndor:/$ uname -a
Linux Cyndor 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ludorg@Cyndor:/$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

As it may be a mount issue, 
```ps
PS C:\Windows\system32> wmic diskdrive get Availability,Capabilities,CapabilityDescriptions,DeviceID,InterfaceType,MediaLoaded,MediaType,Model,Name,Partitions
Availability  Capabilities  CapabilityDescriptions                                       DeviceID            InterfaceType  MediaLoaded  MediaType              Model                    Name                Partitions
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE1  IDE            TRUE         Fixed hard disk media  ST4000DM004-2CV104       \\.\PHYSICALDRIVE1  1
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE2  IDE            TRUE         Fixed hard disk media  WDC WD2003FZEX-00Z4SA0   \\.\PHYSICALDRIVE2  1
              {3, 4, 10}    {"Random Access", "Supports Writing", "SMART Notification"}  \\.\PHYSICALDRIVE0  IDE            TRUE         Fixed hard disk media  V Series SATA SSD 480GB  \\.\PHYSICALDRIVE0  3
```

**Comment by MrObvious** [comment] 2020-11-10 15:54
Same on Windows 1909 (can't upgrade due to corporate system). Workaround of sudo umount /mnt/c and sudo mount -t drvfs C:\\ /mnt/c works.

**Comment by Chelayel** [comment] 2020-11-19 14:33
even unmounting and remounting c does not work in my case

**Comment by Chelayel** [comment] 2020-11-26 13:51
another update: adding 
`[automount]
options = "metadata"` to `/etc/wsl.conf` seems to fix the issue for now. Will keep monitoring and mention if it reoccurs

**Comment by rlabrecque** [comment] 2020-11-26 21:31
My dmesg looks similar to the one above

```
[ 1905.707824] init: (267) ERROR: StopHostListener:372: write failed 32
[ 1922.197206] hv_utils: TimeSync IC version 4.0
[ 2207.563658] scsi 0:0:0:2: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[ 2207.564091] sd 0:0:0:2: Attached scsi generic sg2 type 0
[ 2207.565077] sd 0:0:0:2: [sdc] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[ 2207.565079] sd 0:0:0:2: [sdc] 4096-byte physical blocks
[ 2207.565220] sd 0:0:0:2: [sdc] Write Protect is off
[ 2207.565222] sd 0:0:0:2: [sdc] Mode Sense: 0f 00 00 00
[ 2207.565619] sd 0:0:0:2: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[ 2207.569335] sd 0:0:0:2: [sdc] Attached SCSI disk
[ 2207.587169] EXT4-fs (sdc): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[ 2207.841664] FS-Cache: Duplicate cookie detected
[ 2207.841667] FS-Cache: O-cookie c=00000000c57344f3 [p=00000000427d31fd fl=222 nc=0 na=1]
[ 2207.841667] FS-Cache: O-cookie d=00000000b4ccfcc7 n=0000000056ea76b0
[ 2207.841668] FS-Cache: O-key=[10] '34323935313538303538'
[ 2207.841670] FS-Cache: N-cookie c=00000000c8c8a89f [p=00000000427d31fd fl=2 nc=0 na=1]
[ 2207.841670] FS-Cache: N-cookie d=00000000b4ccfcc7 n=000000000f0ae1d1
[ 2207.841671] FS-Cache: N-key=[10] '34323935313538303538'
[ 2207.845107] FS-Cache: Duplicate cookie detected
[ 2207.845110] FS-Cache: O-cookie c=00000000c57344f3 [p=00000000427d31fd fl=222 nc=0 na=1]
[ 2207.845110] FS-Cache: O-cookie d=00000000b4ccfcc7 n=0000000056ea76b0
[ 2207.845111] FS-Cache: O-key=[10] '34323935313538303538'
[ 2207.845113] FS-Cache: N-cookie c=00000000db15470e [p=00000000427d31fd fl=2 nc=0 na=1]
[ 2207.845113] FS-Cache: N-cookie d=00000000b4ccfcc7 n=00000000fe350d2e
[ 2207.845114] FS-Cache: N-key=[10] '34323935313538303538'
[ 2207.848617] FS-Cache: Duplicate cookie detected
[ 2207.848621] FS-Cache: O-cookie c=00000000c57344f3 [p=00000000427d31fd fl=222 nc=0 na=1]
[ 2207.848621] FS-Cache: O-cookie d=00000000b4ccfcc7 n=0000000056ea76b0
[ 2207.848622] FS-Cache: O-key=[10] '34323935313538303538'
[ 2207.848624] FS-Cache: N-cookie c=00000000be4e5493 [p=00000000427d31fd fl=2 nc=0 na=1]
[ 2207.848624] FS-Cache: N-cookie d=00000000b4ccfcc7 n=000000007cb4f2ba
[ 2207.848625] FS-Cache: N-key=[10] '34323935313538303538'
[ 2207.861666] init: (1) ERROR: UpdateTimezone:97: America/Los_Angeles timezone not found. Is the tzdata package installed?
[ 2207.861671] init: (1) ERROR: InitEntryUtilityVm:2425: UpdateTimezone failed
[ 2207.977660] FS-Cache: Duplicate cookie detected
[ 2207.977663] FS-Cache: O-cookie c=00000000dc0d7d01 [p=00000000427d31fd fl=222 nc=0 na=1]
[ 2207.977663] FS-Cache: O-cookie d=00000000b4ccfcc7 n=0000000072d06c36
[ 2207.977664] FS-Cache: O-key=[10] '34323935313538303731'
[ 2207.977666] FS-Cache: N-cookie c=0000000065928e0b [p=00000000427d31fd fl=2 nc=0 na=1]
[ 2207.977666] FS-Cache: N-cookie d=00000000b4ccfcc7 n=000000002e699faa
[ 2207.977667] FS-Cache: N-key=[10] '34323935313538303731'
[ 2207.983257] FS-Cache: Duplicate cookie detected
[ 2207.983260] FS-Cache: O-cookie c=0000000065928e0b [p=00000000427d31fd fl=222 nc=0 na=1]
[ 2207.983260] FS-Cache: O-cookie d=00000000b4ccfcc7 n=00000000ad69007d
[ 2207.983261] FS-Cache: O-key=[10] '34323935313538303732'
[ 2207.983262] FS-Cache: N-cookie c=00000000ff50fe93 [p=00000000427d31fd fl=2 nc=0 na=1]
[ 2207.983263] FS-Cache: N-cookie d=00000000b4ccfcc7 n=000000005ba8fda6
[ 2207.983263] FS-Cache: N-key=[10] '34323935313538303732'
[ 2207.985947] FS-Cache: Duplicate cookie detected
[ 2207.985950] FS-Cache: O-cookie c=0000000065928e0b [p=00000000427d31fd fl=222 nc=0 na=1]
[ 2207.985951] FS-Cache: O-cookie d=00000000b4ccfcc7 n=00000000ad69007d
[ 2207.985952] FS-Cache: O-key=[10] '34323935313538303732'
[ 2207.985956] FS-Cache: N-cookie c=00000000ff50fe93 [p=00000000427d31fd fl=2 nc=0 na=1]
[ 2207.985956] FS-Cache: N-cookie d=00000000b4ccfcc7 n=00000000ce1ea4ed
[ 2207.985957] FS-Cache: N-key=[10] '34323935313538303732'
[ 2207.989327] init: (1) ERROR: UpdateTimezone:97: America/Los_Angeles timezone not found. Is the tzdata package installed?
[ 2207.989330] init: (1) ERROR: InitEntryUtilityVm:2425: UpdateTimezone failed
[ 2208.191034] scsi 0:0:0:3: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[ 2208.191699] sd 0:0:0:3: Attached scsi generic sg3 type 0
[ 2208.192752] sd 0:0:0:3: [sdd] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[ 2208.192754] sd 0:0:0:3: [sdd] 4096-byte physical blocks
[ 2208.192930] sd 0:0:0:3: [sdd] Write Protect is off
[ 2208.192932] sd 0:0:0:3: [sdd] Mode Sense: 0f 00 00 00
[ 2208.193222] sd 0:0:0:3: [sdd] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[ 2208.201379] sd 0:0:0:3: [sdd] Attached SCSI disk
[ 2209.443428] EXT4-fs (sdd): recovery complete
[ 2209.447219] EXT4-fs (sdd): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[ 2209.480636] init: (2) ERROR: UtilCreateProcessAndWait:474: /bin/mount failed with 2
[ 2209.480776] init: (1) ERROR: UtilCreateProcessAndWait:489: /bin/mount failed with status 0x
[ 2209.480778] ff00
[ 2209.480781] init: (1) ERROR: ConfigMountFsTab:2077: Processing fstab with mount -a failed.
[ 2209.481818] init: (3) ERROR: UtilCreateProcessAndWait:474: /bin/mount failed with 2
[ 2209.481916] init: (1) ERROR: UtilCreateProcessAndWait:489: /bin/mount failed with status 0x
[ 2209.481918] ff00
[ 2209.481922] init: (1) ERROR: MountPlan9:478: mount cache=mmap,noatime,trans=fd,rfdno=8,wfdno=8,msize=65536,aname=drvfs;path=C:\;uid=0;gid=0;symlinkroot=/mnt/
[ 2209.481924]  failed 17
[ 2209.482611] init: (4) ERROR: UtilCreateProcessAndWait:474: /bin/mount failed with 2
[ 2209.707564] ISO 9660 Extensions: RRIP_1991A
[ 2209.800157] ISO 9660 Extensions: RRIP_1991A
[ 2216.410017] cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation
[ 2219.500611] init: (519) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2219.500613] ) failed 5
[ 2219.593558] init: (523) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2219.593560] ) failed 5
[ 2219.682810] init: (527) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2219.682812] ) failed 5
[ 2219.786193] init: (531) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2219.786194] ) failed 5
[ 2219.885397] init: (535) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2219.885399] ) failed 5
[ 2223.241316] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
[ 2223.258114] IPv6: ADDRCONF(NETDEV_UP): br-7933f945a796: link is not ready
[ 2224.559637] init: (680) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2224.559639] ) failed 5
[ 2224.659336] init: (683) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2224.659338] ) failed 5
[ 2224.762721] init: (691) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2224.762723] ) failed 5
[ 2224.889299] init: (694) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2224.889300] ) failed 5
[ 2224.980902] init: (697) ERROR: CreateProcessEntryCommon:612: chdir(/mnt/c/WINDOWS/System32
[ 2224.980903] ) failed 5
[ 2236.036468] WSL2: Performing memory compaction.

~
[ 13:27:54 ] $ cd /mnt/c

/mnt/c
[ 13:30:30 ] $ ls
ls: cannot open directory '.': Input/output error
```

**Comment by AntonTrapp** [comment] 2021-01-04 05:35
Maybe this helps figuring out what's going on. On my system (exported/imported multiple Debian VMs, fresh Windows installation with WSL2 - no WSL1 ever been on that system) I am getting those connection issues almost every day (using Docker Desktop) and/or docker issues (forgetting which WSL2 integrations it should have).

The workaround that seems to be working for me:

- disable docker autostart
- start Windows, make a `wsl --shutdown` - so docker and the VMs are down
- start Docker Desktop (`wsl --list -v` shows all VMs with a docker connection as running)
- open a terminal and... everything is working including the network

If I don't do that I have the input/ouptut errors (almost every time) or the VM can't work with docker or ... - maybe this is helping figuring out what's going on (timing issue with network/docker/wsl/...) or helping somebody to make wsl usable. In the 2nd case we could write a short script for a "semi stable boot process" until this issue is solved...

If one of the other tickets regarding this error is the correct one... feel free to move or give me a hint.

**Comment by cdecompilador** [comment] 2021-01-07 03:13
In my case with WSL2 debian even if I restart `wslhost.exe` via `wsl --shutdown` the problem persist

**Comment by AntonTrapp** [comment] 2021-01-07 06:11
@cdecompilador do you have docker Desktop running while you do the shutdown? In my case it's only working reliably if I boot the system without docker, perform the shutdown (list shows all stopped), then start docker and wait until docker startet the machines with the integration. With docker running it was more like a 50:50 on my system.

**Comment by borb** [comment] 2021-02-02 23:20
This happens for me on every boot. I have Docker Desktop installed but it doesn't start on boot (I don't always need it so start it when I do). `wsl --shutdown` fixes it every time. Periodically - and I mean once in a blue moon, system boots and it's fine. To reiterate, running `wsl --list --verbose` shows the Docker distributions always as "stopped" when I run `wsl --shutdown` to remedy the filesystem access.

As an aside, though I doubt it means anything, I _do_ have Google Drive File Stream installed (and thus a `/mnt/g` filesystem). Generally it never works, but I've wondered if this has an impact on the 9p filesystem handling.

**Comment by hwooo** [comment] 2021-02-23 19:48
CLion cannot find Make and C/C++ compiler installed in WSL Ubuntu because of this issue.

**Comment by cspavlou** [comment] 2021-02-26 07:56
Same happens to me. I'm not sure whether this is a random thing or happens right after sleep or hibernate. Will have to investigate more. Anyway, there are 2 workarounds that work for me.

1. Restart WSL2. I'm not a big fan of this solution, as I'm running some Docker containers, and restarting WSL2 will interrupt my work. How to restart: Open CMD and run
```
wsl.exe --shutdown
```
Then, start your WSL2 instance again

2. Unmount and then mount again your drive(s). I prefer this solution, as it doesn't interfere with my WSL2 instance at all.
```
# umount /mnt/c
# mount -t drvfs C:\\ /mnt/c
```

**Comment by devbyaccident** [comment] 2021-04-19 00:23
I'm getting this now, and I ran `wsl --shutdown` and tried to start my distro back up, I get this message

```
An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
```

Except I can't get into my distro to run `dmesg` :(

**Comment by theAkito** [comment] 2021-04-24 13:55
To me this happened after I created a new virtual machine in Hyper-V and trying to run it. I think both things are related, because I have never seen this WSL2 problem before and I did not use Hyper-V for a long time. Now, both things happened at the same time.

Perhaps this issue is caused by a problem with the virtualisation, in the first place.

**Comment by JCMais** [comment] 2021-04-29 14:44
This has started happening more and more often, right now I need to do a `wsl --shutdown` almost every time the PC comes back from sleep or after boot, otherwise I'm not able to reach WSL ports from Windows.

**Comment by rlabrecque** [comment] 2021-04-29 17:21
For what it's worth, on the same PC I reinstalled windows, have all the same settings and no longer have this issue.

¯\_(ツ)_/¯

I'm sure it will come back though...

**Comment by Adrianilloo** [comment] 2021-05-04 17:04
> For what it's worth, on the same PC I reinstalled windows, have all the same settings and no longer have this issue.
> 
> ¯\_(ツ)_/¯
> 
> I'm sure it will come back though...

I've passed through that 'sensation' once or twice. Once you install VSCode it just takes about 1-2 months for the issue to re-appear (not sure if the WSL install date affects it).

**Comment by mknj** [comment] 2021-05-10 13:44
For me this issue appears seconds after calling "git pull" or "npm install" under /mnt/c. This happens on all of our corporate Laptops. We are using bitlocker and "BeyondTrust Privilege Management".
So WSL2 is currently unusable here.

**Comment by UsrLightmann** [comment] 2021-05-25 17:01
Switched from WSL to WSL2 a few weeks back and have had this issue from the get-go. Only occurs for me after the initial launch of WSL. Once fixed, by running `wsl --shutdown` and `wsl`, the issue is resolved until a full pc reboot. 

Saw on another thread that canceling a process (ctrl+C) may be the culprit. Haven't been paying that close attention, but my most recent run in with this issue occurred immediately following the canceling of a process. 

Windows v10.19042.985 & Linux kernel v5.4.72-microsoft-standard-WSL2

**Comment by mknj** [comment] 2021-06-08 08:30
related to #5469.

i can reproduce the problem, let me know which logs you need to debug this issue.

**Comment by JPetiwale** [comment] 2021-07-12 20:42
I have the same issue whenever I start my windows and open the Linux terminal this error comes:
/mnt/c: Input/output error
/mnt/d: Input/output error
but once when I do `wsl --shutdown` and reopen the Linux terminal it works but its a bit uncomfortable to always restart the Linux terminal after startup

**Comment by rodrigoreis** [comment] 2021-07-18 22:27
Well `wsl --shutdown` is a workaround. There is ain't no solution yet?

**Comment by techiechap** [comment] 2021-07-20 17:57
wsl --shutdown works, i got u-18 and u-20, this particular error thrown when i went to change my sudo password,

**Comment by rodrigoreis** [comment] 2021-07-20 19:08
> wsl --shutdown works, i got u-18 and u-20, this particular error thrown when i went to change my sudo password,

When you have to run it routinely I can't believe it's a solution.

**Comment by skuirrels** [comment] 2021-07-26 23:02
Restarting the Lxssmanager services solves it for about 2-4 hours and then it happens again.  This bug needs to be assigned to someone.

**Comment by pa-vpap** [comment] 2021-08-11 10:51
try the following command, it worked for me, with no need to restart WSL
sudo mount -t drvfs C:\\ /mnt/c

**Comment by rodrigoreis** [comment] 2021-08-11 12:05
> try the following command, it worked for me, with no need to restart WSL
> sudo umount /mnt/c ; sudo mount -t drvfs C: /mnt/c -o metadata
> 
> https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/

This is an old post. Even if it solves this post's related problem, you will have to run this mount command routinely every time you restart WSL. An alternative is to put these suggested mount settings into /etc/wsl.conf as suggested in the post below.

https://devblogs.microsoft.com/commandline/automatically-configuring-wsl/

(PS. this post "automatically-configuring-wsl" is also very old)

**Comment by rodrigoreis** [comment] 2021-08-11 12:21
I guess it can be related to 9P protocol used to mount Windows drive in WSL version 2. This was a big change from version 1, which used drvfs.

**Comment by jorgediaz-lr** [comment] 2021-08-11 12:22
I have the error randomly sometimes when I reboot the computer, the first time I open a WSL console.

As a workaround I have added following lines to the **.bashrc** file:
```
ls /mnt/c > /dev/null
if [ $? != 0 ]; then
        echo ""
        echo "Error with windows integration :-("
        echo "Applying workaround to solve it"
        sudo umount /mnt/c
        sudo mount -t drvfs C: /mnt/c
fi
```

So it will ask me to enter the sudo password only in case it detects the issue.

**Comment by anagavaraa-chwy** [comment] 2021-08-12 07:47
Was consistently facing IO error with any operation on /mnt/c. IO performance is poor on /mnt/c. wsl --shutdown works temporarily but issue keeps coming back. I ended up moving my workspace to home dir
Refer: https://nickjanetakis.com/blog/3-gotchas-with-wsl-2-around-disk-space-memory-usage-and-performance

**Comment by karanj798** [comment] 2021-08-28 15:10
> 
> 
> I have the error randomly sometimes when I reboot the computer, the first time I open a WSL console.
> 
> As a workaround I have added following lines to the **.bashrc** file:
> 
> ```
> ls /mnt/c > /dev/null
> if [ $? != 0 ]; then
>         echo ""
>         echo "Error with windows integration :-("
>         echo "Applying workaround to solve it"
>         sudo umount /mnt/c
>         sudo mount -t drvfs C: /mnt/c
> fi
> ```
> 
> So it will ask me to enter the sudo password only in case it detects the issue.

If you want to avoid entering the password upon logon or any sort of prompts, I've added a slight modification.
```sh
# Mount-Point fix
ls /mnt/c > /dev/null 2>&1
if [ $? != 0 ]; then
        echo <pass> | sudo -S -p '' umount /mnt/c
        echo <pass> | sudo -S -p '' mount -t drvfs C: /mnt/c
fi
```

**Comment by elvisli** [comment] 2021-09-14 07:05
Hi, I have tried both workaround mentioned in this post,
`wsl --shutdown`
`wsl`
or,
sudo umount -l /mnt/c
sudo mount -t drvfs C: /mnt/c

sudo mount -t drvfs C:\\ /mnt/c
<3>init: (78) ERROR: UtilConnectVsock:401: connect port 50002 failed 110
Operation timed out

but still failing whenever I need to create a file.

I have to switch to WLS1 for now, until the issue is fixed.

**Comment by 9jaboy** [comment] 2021-10-30 04:27
False alarm, the issue still exists.

**Comment by AntonTrapp** [comment] 2021-10-30 04:39
I don't think anybody will fix this. But... on Windows 11 (installed it on 1 Laptop to test it) I can:

- shutdown the system without docker and/or wsl2 crashing trying to restart the service that is shutting down
- boot with docker for windows enabled without the need to restart wsl2 manually because the whole file sharing / mounting is not working

Only the 2nd day - so not too optimistic atm, but until now not a single crash which at least is way more stable than every Windows 10 system I run (with docker and wsl2). So... let's hope this will continue.

**Comment by lambda-science** [comment] 2021-11-01 11:32
Any update on this ?
Having to use powerhsell to wsl.exe --shutdown each time I want to open VSCode in WSL mode is exhausting
This happens on both of my computer (work and home).

**Comment by humbienri** [comment] 2022-01-21 20:53
I am also hitting a wall on this. The wsl shutdown and restart does not work for me. I've not yet tried unmounting and mounting the C drive on my Debian WSL distro.
![VSCode_2022Jan21_144232_WSLServerError](https://user-images.githubusercontent.com/1178569/150598501-f0c18896-abe8-4b4d-b933-5e3532a02e40.png)

**Comment by shinebayar-g** [comment] 2022-01-21 20:55
@humbienri `wsl --shutdown` should work generally. If not you can try restart the service called `LXSSMANAGER`. If either of them works, try doing the full reboot.

**Comment by lambda-science** [comment] 2022-01-21 20:57
Looks like last Windows Update I had fixed this issue. (21H2 19044.1466)

**Comment by humbienri** [comment] 2022-01-21 21:08
Restarting the laptop did not work. Restarting that LXSSManager service did not work.

Windows 11 sounds tempting!

**Comment by humbienri** [comment] 2022-01-21 23:55
Nope, Windows 11 did not fix it for me. Same error same everything.

Does the fact that I am running VS Code portably matter? i.e it's not really installed on the Windows 10/11 side, but running off a USB drive. Maybe there's some setting I need to manually configure?

**Comment by rcmosher** [comment] 2023-07-18 01:16
Just got this error after Windows rebooted my computer without my consent. Update history doesn't indicate it installed anything. I had upgraded to WSL2 a week or two ago.

One problem of the workaround of unmounting then remounting is git will "fatal: detected dubious ownership in repository at ..." since it is now owned by root. I don't seem to be able to mount C: myself without shutting down WSL and restarting it.

**Comment by SuperBeagleDog** [comment] 2023-08-16 03:57
> @humbienri `wsl --shutdown` should work generally. If not you can try restart the service called `LXSSMANAGER`. If either of them works, try doing the full reboot.
> 
> Btw, I no longer see this issue on Windows 11. :)

Work for me, thank you

**Closed** 2024-08-15 13:04 UTC
Labels: file system

**Comment by kerneltravel** [comment] 2025-05-03 12:47
One possible reason is that Windows' C drive is full. In this case, wsl --shutdown won't solve the issue. You should clean the Recycle Bin or delete some temporary files in the C drive.
