### ISSUE TITLE
wsl.exe commandline option is translated!

### ISSUE THREAD

**Issue by cloudhan** [microsoft/WSL#6328] opened 2020-12-11 14:41 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21277.1000]
Your Distribution version:
Whether the issue is on WSL 2 and/or WSL 1:
```

# Steps to reproduce

`wsl --help`

#  Expected behavior

所有命令行选项都应该以最初在渶格蘭哋岖蓅哘の呅牸呈现！
If you don't know what the above sentence means, try google translate. And if it doesn't help,  then you got what I mean!

# Actual behavior

![image](https://user-images.githubusercontent.com/1279292/101915433-986ed900-3c00-11eb-86e5-658882eafd8b.png)

options like `--设置-默认-版本` is not valid!

**Comment by lbs-rodrigo** [comment] 2021-03-18 14:50
same problem occurs with the portugues-br (pt-br) language

# Environment
```
Windows build number: 10.0.21337.1000
WSL: 5.4.72-microsoft-standard-WSL2
```

# Steps to reproduce
```
wsl --help
```

# Print

![image](https://user-images.githubusercontent.com/15225366/111646136-25b56100-87e0-11eb-82bd-d4ada80d044c.png)

**Comment by bpulliam** [comment] 2021-04-28 12:11
Fixed in 21370

**Closed by bpulliam** 2021-04-28 12:11 UTC
Labels: bug, fixedininsiderbuilds, i18n

**Comment by tingjhenjiang** [comment] 2022-11-27 09:44
I get into this problem as well after upgrade to wsl 1.0 .
details of wsl --version:
WSL version： 1.0.1.0
core version： 5.15.74.2
WSLg version： 1.0.47
MSRDC version： 1.2.3575
Direct3D version： 1.606.4
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version： 10.0.22000.1281

**Comment by tingjhenjiang** [comment] 2022-11-27 11:34
reopen this issue.

**Comment by tingjhenjiang** [comment] 2022-12-25 06:45
> Duplicate of #8857

#6328 is ahead of this #8857, and therefore this issue is not a duplicate of #8857, and it implies that the earlier issue(the #6328) cannot be justified in not reopening the issue because it is not a duplicated one, and therefore please correct the statement here (duplicate of #....).

**Comment by tingjhenjiang** [comment] 2022-12-25 06:47
> Duplicate of #8857

#6328 is ahead of this #8857, and therefore this issue is not a duplicate of #8857, and it implies that the earlier issue(the #6328) cannot be justified in not reopening the issue because it is not a duplicated one, and therefore please correct the statement here (duplicate of #....).
