### ISSUE TITLE
WSL2 start folder is `/mnt/wsl/docker-desktop-bind-mounts/.../mnr/c/Users/me` instead of `/mnt/c/Users/me`

### ISSUE THREAD

**Issue by uishon** [microsoft/WSL#6464] opened 2021-01-25 11:03 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Your Distribution version: Ubunutu, Release:        20.04
Whether the issue is on WSL 2 and/or WSL 1: Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020

```

# Steps to reproduce

Docker Desktop running, latest version- 3.1.0 (51484) with WSL2 integration enabled.
Start any distribution (whether docker wsl2 integration is enabled for that specific distro or not), you get the long path as your current start (home) folder.

```bash
PS C:\Users\uisho> wsl
uri@milky-way:/mnt/wsl/docker-desktop-bind-mounts/Fabric/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1/mnt/c/Users/uisho$
```
where _Fabric_ is the name of one of the distributions (originally an Ubuntu-18.04 distro).

**WSL logs**: 

#  Expected behavior

    uri@milky-way:/mnt/c/Users/uisho$

    uri@milky-way:/mnt/wsl/docker-desktop-bind-mounts/Fabric/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1/mnt/c/Users/uisho$

**Comment by uishon** [comment] 2021-01-25 11:10
https://aka.ms/AAay5xt

**Comment by benhillis** [comment] 2021-01-25 13:32
I believe this is a dupe of #6196

**Comment by uishon** [comment] 2021-01-26 11:51
Well, I trust your judgement although - if I managed to get #6196 right - it's not the exact same case. In my case, I *can* access `/mnt/c/Users/` folder. I can `cd` to it and it seems to be mounted correctly. The issue is that from some reason, the start folder WSL starts with is that long folder that is under the `/mnt/wsl/docker-desktop-bind-mounts` root. Did I misunderstand #6196? Do you still think it's the same root cause despite the difference?

**Comment by uishon** [comment] 2021-01-26 18:13
Just realized it's more similar than I thought. On one distro, I do see `/mnt/c/Users` but there are others where it's missing. Not sure why but out of the 3 distros I'm using - 2 have `/mnt/c` mounted properly (although WSL still uses the long path for the start directory) and the 3rd distro doesn't even have it mounted.

**Closed** 2021-05-06 15:57 UTC
