### ISSUE TITLE
WSL shows recycle bin contents when directory deleted

### ISSUE THREAD

**Issue by joshholding** [microsoft/WSL#4512] opened 2019-09-16 21:32 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.18362.329]

* What you're doing and what's happening: 
1. create c:\tmp dir
2. create c:\tmp\test.txt file
3. 
```
$ cd /mnt/c/tmp
$ ls
test.txt
```
4. within windows file explorer, delete c:\tmp
4a. create c:\tmp
4b. create c:\tmp\test2.txt file
5.
```
$ ls
test.txt
$ cd ..
$ cd tmp
$ ls
test2.txt
```

* What's wrong / what should be happening instead:
Should show the new contents, not what is in the recycle bin

**Comment by therealkenc** [comment] 2019-09-17 00:34
Cannot reproduce here on 18980. At step (5) I get `test2.txt`.

**Comment by superantho** [comment] 2019-09-17 15:11
I was able to recreate using the exact steps provided.  this looks like a bug to me.

Version	10.0.18362 Build 18362

**Comment by DHowett-MSFT** [comment] 2019-09-22 01:21
This is actually by design -- The current working directory is typically held in the kernel as a handle or descriptor, and that handle transcends exactly where that directory is in the filesystem.

Here's an example from "Real Linux": `Linux antares 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux`

|**Shell A**|**Shell B**|
|-|-|
|`/tmp % mkdir hello`<br> `/tmp % cd hello`<br> `/tmp/hello % echo hi > test.txt`<br> `/tmp/hello % ls`<br> `test.txt`||
||`/tmp % mv hello pretend_it_was_deleted`<br>`/tmp % mkdir hello`<br>`/tmp % cd hello`<br>`/tmp/hello % echo goodbye > test_2.txt`<br>`/tmp/hello % ls`<br>`test_2.txt`|
|`/tmp/hello % ls`<br>`test.txt`||

If you ask shell A what its PID is (here 10333), then check in `/proc/$pid`, you get this interesting result:

```
(antares) /tmp/hello % ls -la /proc/10333
...
lrwxrwxrwx   1 dustin domain users 0 Sep 21 18:17 cwd -> /tmp/pretend_it_was_deleted
```

Since moving something to the recycle bin is really just moving it around in the filesystem (from `C:\whatever` to `C:\$RECYCLE.BIN\S-1-15-xyz-abc-def\hashed_name`), WSL1 is acting as expected. WSL2 probably will be the same.

**Comment by therealkenc** [comment] 2019-09-22 03:23
Yeah, that's right. If the shell (or any other program for that matter) is holding onto an inode pointing at some dnode (here `/mnt/c/tmp`) then the contents of that directory (children of the dnode) isn't going to change even if the (parent) dnode itself is [`rename(2)ed`](http://man7.org/linux/man-pages/man2/rename.2.html).

You can see this effect in action easier than exploring `/proc`. If you rename a directory out from under `bash(1)` in "Shell B" with "`mv /tmp/hello /tmp/foo`", the shell builtin `pwd` (and typically the shell `$PS1` prompt) in "Shell A" will report the old `/tmp/hello` path, because `bash` caches the `$PWD` string in memory and hasn't the slightest idea anything changed. But if you run [`/bin/pwd(1)`](http://man7.org/linux/man-pages/man1/pwd.1.html) it will report the renamed dentry. In the OP example the new dentry and old dentry both have the same `/mnt/c/tmp` path, but the effect is the same.

[Note: This `/bin/pwd` experiment _does not_ work with 9p; `/bin/pwd` _won't_ report the new /mnt/c/$RECYCLE.BIN\S-1-15-xyz-abc-def/hashed_name` for example. But such behavior isn't atypical of network filesystems (like f.e. NFSv2).]

Which makes me have to retry the OP sequence, which I had said I could not reproduce on 18980. On a more careful retry, it does, of course. I suspect strongly I didn't follow the sequence correctly in the drive-by. That's on me. Appreciate the follow up and correction muchly 👍.

**Closed by therealkenc** 2019-09-22 03:23 UTC

**Comment by joshholding** [comment] 2019-09-23 21:30
Fair enough, just unexpected from my end. I validated the same behavior in centos & raspbian.

Thanks all-
