### ISSUE TITLE
WSL hangs when visiting drvfs drive randomly

### ISSUE THREAD

**Issue by fockez** [microsoft/WSL#9473] opened 2023-01-12 05:23 UTC
I have a Windows 11 PC installed WSLg to support massive computation under Linux.
It is a Vostro 3910 with i7-12700 CPU, 64GB memory and two 16TB WDC hard drive.
Now, some times my program with massive hard drive IO hangs there forever, and all other programs involved with this drive will hangs too, such as df or ls or cd. No error reports.
The other drive with less IO will live.

I tried all major release kernels from 5.10 to 5.15, Ubuntu 22.04 and Debian, dynamic disk and basic disk, switch IO between two hard drives, no use. Host windows can write and read the drive normally when WSL hangs. After wsl --shutdown, all the data can be visit too. 

And, on the other PCs, I have not met this kind of issue, just this PC. 

So what's the problem and how could I trace this kind of problem?

**Comment by OneBlue** [comment] 2023-01-17 22:27
If a specific program generates a lot of IO it's possible that it "starves" other programs from IO so unfortunately this isn't something that WSL itself can solve.

Closing since this isn't a WSL issue.

**Closed by OneBlue** 2023-01-17 22:27 UTC

**Comment by JonasCz** [comment] 2023-01-19 08:50
I have this problem too; it's new since a few days.. Program that generates a lot of IO to a drvfs (Synology share), works for a while (few minutes to a few hours), then completely hangs indefinitely, CTRL+C does nothing, new session and any command that interacts with that mounted drive (`df -h` `ls` to it), also hangs indefinitely and no interaction (CTRL+C, etc.) is possible.

This is not IO starved slowness, it just completely breaks.

I think this may be new in 1.0.3, will try reverting to 1.0.0 and report back.

**Comment by JonasCz** [comment] 2023-01-20 05:18
Update: 1.0.0 is ineed still working ~24 hours of continuous usage later.

**Comment by OneBlue** [comment] 2023-01-20 23:14
> But I think IO it's not that massive. I switch to use cifs mount the same disk and do the same IO, works fine. And it not that the program starves other programs, the program itself hangs too. So when it stucks, no effective IO has been done.

Can you still open new WSL prompts when you reach that "hanging" state ?

**Comment by fockez** [comment] 2023-01-20 23:25
> > But I think IO it's not that massive. I switch to use cifs mount the same disk and do the same IO, works fine. And it not that the program starves other programs, the program itself hangs too. So when it stucks, no effective IO has been done.
> 
> Can you still open new WSL prompts when you reach that "hanging" state ?

Yes, in this case, I can open new WSL prompts and execute other programs, but if problem disk involved, it hangs too.

**Comment by fockez** [comment] 2023-01-20 23:26
> Update: 1.0.0 is indeed still working ~24 hours of continuous usage later.

I tried from maybe 0.6 (Kernel 5.10.19) to the newest release, problem still there.

**Comment by robpomeroy** [comment] 2023-07-31 09:42
> I have this problem too; it's new since a few days.. Program that generates a lot of IO to a drvfs (Synology share), works for a while (few minutes to a few hours), then completely hangs indefinitely, CTRL+C does nothing, new prompt/session and any command that interacts with that mounted drive (`df -h` `ls` to it), also hangs indefinitely and no interaction (CTRL+C, etc.) is possible.
> 
> Synology share still accessible from Windows even when it's hung in WSL; with `wsl --shutdown` it works again (for a while).
> 
> This is not IO starved slowness, it just completely breaks.
> 
> I think this may be new in 1.0.3, will try reverting to 1.0.0 and report back.

Identical symptoms here, when the default WSL distro is AlmaLinux 9 and the network share is on a Synology NAS. At the same time the AlmaLinux distro exhibits this issue though, an Oracle Linux 8 distro appears to be unaffected.

Symptoms:

- At some point after boot, VS Code (with WSL connection) stops being able to browse network shares mounted under `/mnt` in the default distro.
- Running `ls /mnt` in the distro hangs indefinitely.
- No relevant events are logged in the Windows event logs.
- Terminating the default distro temporarily fixes the problem (but it can recur within minutes).

I'm mounting a network share mapped to H: within Windows, so this is the line in `/etc/fstab`:

```
H: /mnt/h drvfs uid=1000,gid=1000,umask=22 0 0
```

And `/etc/wsl.conf` is:

```
[automount]
options="metadata,umask=0033"
```

I suspect VS Code is contributing to the issue since it hammers the file system (Git extension checks, linting, etc.). I'll switch to cifs mounting, but it's a pity since the WSL integration is generally really good these days. 🙂

**Comment by fockez** [comment] 2023-10-12 06:22
Updates:
WSL updated to 2.0.3, problem still there.

**Comment by zynfly** [comment] 2023-12-15 14:32
@OneBlue I have also encountered this problem, which occurs when synchronizing files with rsync and when compiling projects with cmake. As long as there are enough file operations across file systems, problems will arise.

**Comment by narbhar** [comment] 2024-02-12 15:08
@OneBlue  I have this issue too. I host an algorithm on WSL that works on data hosted on the windows drives. My scripts are in python. Whenever I have a process writing to windows drive such as an image and I'm doing a simple polling operation from python to check if the files have finished saving, I can reliably reproduce this bug where the windows drives can no longer be accessed anymore. If my has C, D and E drives  on windows and I'm running my ops on E drive, I can see that the issue is prevelant on all the drives too. Any commands such as `ls` or even force remounting the drives won't work. The worst part is since any filesystem access commands don't return any results, all my python scripts fail silently. Interrupt commands don't work in this state too. The only solution so far seems to be restarting WSL using `wsl --shutdown`

**Comment by narbhar** [comment] 2024-02-12 22:52
> > @OneBlue I have this issue too. I host an algorithm on WSL that works on data hosted on the windows drives. My scripts are in python. Whenever I have a process writing to windows drive such as an image and I'm doing a simple polling operation from python to check if the files have finished saving, I can reliably reproduce this bug where the windows drives can no longer be accessed anymore. If my system has C, D and E drives on windows and I'm running my ops on E drive, I can see that the issue is prevalent on all the drives too. Any commands such as `ls` or even force remounting the drives won't work. The worst part is since any filesystem access commands don't return any results, all my python scripts fail silently. Interrupt commands don't work in this state too. The only solution so far seems to be restarting WSL using `wsl --shutdown`
> 
> @narbhar: This is very interesting. If possible, could you share a version of that script that reproduces the issue with us ?

In my workflow a windows process dumps the data to the windows disk and my python script polls the destination and then starts processing data in the algo. I couldn't exactly replicate the code due to these reasons but I created two simple scripts here (https://gist.github.com/narbhar/09928b0c93f3f69a4dd162bee3df0f95) in python where one writes large images to the disk while the other polls the save location for a timeout. I tried to parallelize the I/O as much as possible to hit the bandwidth of the the disk. I wasn't able to reproduce this issue on my laptop while I was able to encounter this bug on our server which runs Windows Server 2022. I am running Ubuntu 22.04.3

Here's additional WSL related info on the server:
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.20348.1850

WSL info on Windows 10 laptop where I couldn't reproduce it:
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3803
