### ISSUE TITLE
bash hangs after "Extracting Filesystem"

### ISSUE THREAD

**Issue by mguetlein** [Microsoft/WSL#3008] opened 2018-03-09 09:57 UTC
When I try to install linux as subsystem, the installation hangs after extracting filesystem when I run the bash command in the shell. I re-tried with an admin-shell after running "lxrun /uninstall /full", but that did not change anything.

I am using Windows 10, build 14393.

I read in other tickets that I should "disable all but one of your pagefiles", but I think I only have a single one (I only have a single disk). I have no Avast running. 

I have an encrypted disk, maybe that is the problem?

Thanks for your help.

**Comment by fpqc** [comment] 2018-03-09 11:42
14393 is like two years old.

**Comment by mguetlein** [comment] 2018-03-09 11:44
yes, but I have no other options

**Comment by fpqc** [comment] 2018-03-09 13:17
WSL was a beta in 14393. It is no longer supported.

**Comment by benhillis** [comment] 2018-03-09 16:45
Duplicate of #565.

**Closed by benhillis** 2018-03-09 16:45 UTC

**Comment by mguetlein** [comment] 2018-03-12 06:54
Sorry to hear that

#565 was solved by disabling avast, this is not my problem

if installing on older builds is no longer supported, you should change https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by sunilmut** [comment] 2018-03-12 18:37
cc @scooley to see if anything needs to be updated with the documentation.

**Comment by fpqc** [comment] 2018-03-12 20:03
@mguetlein It's not supported per se, but I think there was a trick if you decompressed the OS image, which is compressed using the CompactOS functionality. It's worth trying maybe?
