### ISSUE TITLE
git: "fatal: fsync error  Permission denied"

### ISSUE THREAD

**Issue by atlefren** [microsoft/WSL#3556] opened 2018-09-20 11:10 UTC
* Your Windows build number: Microsoft Windows [Version 10.0.18234.1000]

* What you're doing and what's happening:  

atlefren@atlsve-M4800:/mnt/d/code$ git --version
git version 2.7.4
atlefren@atlsve-M4800:/mnt/d/code$ git clone git@ssh.dev.azure.com:v3/path/to/repo
Cloning into 'repo'...

path/to/repo is of course edited

...
remote: Found 319 objects to send. (11 ms)
Receiving objects: 100% (319/319), 186.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (132/132), done.
fatal: fsync error on '/mnt/d/code/repo/.git/objects/pack/tmp_idx_QfTqP5': Permission denied
fatal: index-pack failed
atlefren@atlsve-M4800:/mnt/d/code$

* What's wrong / what should be happening instead:

The permission denied part and the fact that repo is not cloned. 

I get the same error when doing a git pull on an existing repo. However, this does not happen with all repos.

I recently edited the /etc/wsl.conf file to contain this:

```
[interop]
enabled=false # enable launch of Windows binaries; default is true
appendWindowsPath=false # append Windows path to $PATH variable; default is true

[automount]
options=case=off

```
the windows drives are mapped like so:

```
atlefren@atlsve-M4800:/mnt/d/code$ mount
rootfs on / type lxfs (rw,noatime)
root on /root type lxfs (rw,noatime)
home on /home type lxfs (rw,noatime)
data on /data type lxfs (rw,noatime)
cache on /cache type lxfs (rw,noatime)
mnt on /mnt type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C:\ on /mnt/c type drvfs (rw,relatime,uid=1000,gid=1000,case=off)
D:\ on /mnt/d type drvfs (rw,relatime,uid=1000,gid=1000,case=off)
```

Also: git clone of the same repo works fine /home/atlefren and works fine on Windows using git on windows. Guess it's related to the mounting in some way. Problem appeared after updating Windows and adding the [interop]-part to /etc/wsl.conf

* Strace of the failing command, if applicable:  https://gist.github.com/atlefren/ac570fe8b3f3e1cdd302964d917f7173

**Comment by dominicsayers** [comment] 2018-09-23 15:27
I noticed this only affects '/mnt' folders (at least for me)

**Comment by Deadpoolddt** [comment] 2018-09-23 16:36
Having the same error in Version 1809 build 18242.1000 and mounted drives to "/" instead

```
git clone git@bitbucket.org:myrepo/myproject.git
Cloning into 'myproject'...
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (15/15), 4.16 KiB | 236.00 KiB/s, done.
fatal: fsync error on '/d/dev/projects/myproject/.git/objects/pack/tmp_idx_oQEgk4': Permission denied
fatal: index-pack failed
```

Mounted as such: 
```
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,noatime)
C:\ on /c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off)
D:\ on /d type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off)
```
Also I'm using this wsl.conf (if helps)
```
[automount]
enabled = true
root = /
options = "metadata,umask=22,fmask=11"
mountFsTab = false
```

**Comment by benhillis** [comment] 2018-10-01 21:13
We have identified the issue and @SvenGroot is working on a fix. Thanks for filing the issue.

**Comment by dannyk81** [comment] 2018-10-04 18:52
@SvenGroot @benhillis any workaround for this perhaps that you can share? 🙏

**Comment by benhillis** [comment] 2018-10-04 18:55
@dannyk81 - Working outside of DrvFs would be a workaround, or reverting to an earlier Insider build (or 1803 / 1809).

**Comment by dannyk81** [comment] 2018-10-05 02:02
Thanks @benhillis I've moved this repo to the lxfs and it works fine, looking forward for the fix 🙏

**Comment by atlefren** [comment] 2018-10-05 10:13
As I need to access the repo from windows my temporary solution is to use git on windows to clone the repo, seems like git on wsl still works for most other things

**Comment by dominicsayers** [comment] 2018-10-05 10:42
I've gone back to working in a HyperV VM :-(

**Comment by nocko** [comment] 2018-10-05 18:11
Ugh, painful bug. I hope the fix goes out quickly.

**Comment by Dinfyru** [comment] 2018-10-08 11:41
+1

**Comment by neoadventist** [comment] 2018-10-09 19:36
oh man this is sad.

**Comment by khuongduybui** [comment] 2018-10-09 20:13
I've only seen this problem when cloning. Pulling and pushing work just fine. So I've been cloning outside /mnt then move the whole thing over. In rare cases I have had to run gir clone from Windows. Again pulling and pushing work just fine for me.

**Comment by NowhereResident** [comment] 2018-10-11 07:28
Confirming the issue on rs_prerelease (18252.1000) - I only seem to experience it when cloning down. I've not had any problem with push or pull (perhaps issues with pulling occur where new files are involved?).

I've been doing as @khuongduybui and just cloning into a directory in the linux filesystem and then moving it into my symlinked /mnt directory (I have /srv/sites symlinked to a Sites/ directory in my Windows user folder) and this works just fine.

One extra step, but it means I can stick to my setup!

**Comment by dannyk81** [comment] 2018-10-11 12:52
`pull` started failing for me too...

```
$ git pull
remote: Counting objects: 148, done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 105 (delta 73), reused 0 (delta 0)
Receiving objects: 100% (105/105), 9.78 KiB | 133.00 KiB/s, done.
Resolving deltas: 100% (73/73), completed with 23 local objects.
fatal: fsync error on '.git/objects/pack/tmp_pack_VmGVIF': Permission denied
fatal: index-pack failed
```

**Comment by AndyGauge** [comment] 2018-10-11 17:08
I've  attempted to clone the repository in the linux FS and move it onto /mnt, but git thinks all of the files have been modified.

**Comment by orozco30** [comment] 2018-10-11 18:51
$ git pull
remote: Counting objects: 148, done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 105 (delta 73), reused 0 (delta 0)
Receiving objects: 100% (105/105), 9.78 KiB | 133.00 KiB/s, done.
Resolving deltas: 100% (73/73), completed with 23 local objects.
fatal: fsync error on '.git/objects/pack/tmp_pack_VmGVIF': Permission denied
fatal: index-pack failed

**Comment by Habitats** [comment] 2018-10-13 18:30
Anyone figured out a workaround? Or ETA on fix?

**Comment by mqudsi** [comment] 2018-10-13 20:16
The workaround is to alias `git` to `git.exe` :)

**Comment by atlefren** [comment] 2018-10-15 08:49
@mqudsi I assume this is a joke, right?

**Comment by atlefren** [comment] 2018-10-15 13:45
@mqudsi So basically running windows git on WSL? I've removed all the windows binaries from my WSL PATH, so no option for me. But, yeah, why not? 

On the other hand: this issue will hopefully be resolved soon...

**Comment by dannyk81** [comment] 2018-10-17 21:28
@SvenGroot @benhillis I just saw the release notes for Build 18262, but don't see this issue in the "Fixed" or "Known issues" list, can you update if a fix is coming with that build?

Thanks!

**Comment by benhillis** [comment] 2018-10-17 21:33
@dannyk81 - Looks like the fix for this issue just missed the 18262 build.  I suspect the fix will be in next week's build.

**Comment by dannyk81** [comment] 2018-10-17 21:37
Thanks for the update!

**Comment by Inigo-Pascall** [comment] 2018-10-18 16:19
+1 for this. Please fix, this is a massive pain in the ass.

If it helps anyone, the only solution I've found is to restart my machine, then it works...

**Comment by benhillis** [comment] 2018-10-24 21:48
Fixed in 18267.

**Comment by dannyk81** [comment] 2018-10-26 13:32
Thanks @benhillis, just upgraded to 18267 and issue is gone 👏

**Comment by non1979** [comment] 2018-10-27 20:49
still got problems  in 18267 

non@10PC:/mnt/f$ mkdir los16
non@10PC:/mnt/f$ cd los16
non@10PC:/mnt/f/los16$ repo init -u git://github.com/LineageOS/android.git -b lineage-16.0
error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
fatal: cloning the git-repo repository failed, will remove '.repo/repo'

**Comment by Inigo-Pascall** [comment] 2018-10-31 12:38
Possibly a noob question, but how do I update to 18267; Do I need to be on the Windows Insider Program, or is there some other way to do this manually? I'm currently on Windows 10 version 1803.

**Comment by khuongduybui** [comment] 2018-10-31 14:51
Yes you do need to be on Insider Fast ring.
Or you can download the ISO on the internet and update your Windows, but that's is NOT recommended or supported. Use at your own risk.

**Comment by Uldiniad** [comment] 2019-02-10 14:06
> still got problems in 18267 (ubuntu 16.04)
> 
> non@10PC:/mnt/f$ mkdir los16
> non@10PC:/mnt/f$ cd los16
> non@10PC:/mnt/f/los16$ repo init -u git://github.com/LineageOS/android.git -b lineage-16.0
> error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
> error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
> error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
> error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
> error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
> fatal: cloning the git-repo repository failed, will remove '.repo/repo'
> 
> $ cat /proc/version
> Linux version 4.4.0-18267-Microsoft ([Microsoft@Microsoft.com](mailto:Microsoft@Microsoft.com)) (gcc version 5.4.0 (GCC) ) #1001-Microsoft Sat Oct 20 19:08:00 PST 2018
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 16.04.5 LTS
> Release: 16.04
> Codename: xenial
> 
> Tried 18.04, the same problems
> error: chmod on /mnt/f/los16/.repo/repo/.git/config.lock failed: Operation not permitted
> fatal: could not set 'core.filemode' to 'false'
> fatal: could not create /mnt/f/los16/.repo/repo
> fatal: cloning the git-repo repository failed, will remove '.repo/repo'

@non1979 you are not supposed to use mnt. download to folders within the subsystem https://forum.xda-developers.com/android/software-hacking/guide-how-to-build-lineageos-15-1-t3750175

**Comment by MikePach** [comment] 2019-02-27 04:00
for me i found out why it would still error out in later versions of Insider
i found that if i cloned/push/pull on my internal drive (formatted ntfs) it would work fine
if i tried it on a flash drive (exfat) it fails with permission failed.
my theory is that its a drive format specific issue now (as the issue that surrounded with ntfs was fixed)

**Comment by ioweb-gr** [comment] 2019-02-27 08:13
I can confirm it's the same for me. I just formatted a drive in drvfs as NTFS and it works but it's broken for other filesystems that it used to work on.

**Comment by ryancheung** [comment] 2019-12-21 19:03
I found `sudo git` just fixed the permission issue....

**Comment by ttimasdf** [comment] 2020-02-02 04:22
I've gotten into the same problem, finally found that (in my case) it's the Windows Defender problem. A feature rather than a bug.

I've enabled [Controlled folder access](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/controlled-folders) inside Windows Defender allowing only a whitelist of program to modify the content of My Documents. None of the programs inside WSL is put into my list. If a normal Windows program trying to modify the protected folder, Windows Defender will show a notification that the file operation is blocked. However, if I modify the protected file inside WSL **it will just silently failed**! After I turning off ransomware protection temporarily, the file operation works again.

So, the same for you all, the fsync error maybe an antivirus problem. Try to disable it and try again.

**Comment by gund** [comment] 2020-02-24 20:28
I've got the same errors and turns out it's Vscode in WSL that causes this issues.
It's called folder pinning and there is an issue in either Vscode or WSL somewhere that tracks this bug but in general when you open a folder in Vscode under WSL it blocks some folders access and permissions are failing even on windows side.

If you close Vscode - then permissions are back online =)

**Comment by zinefer** [comment] 2020-04-19 05:41
I am seeing this error in 18362:

```
git clone git@github.com:microsoft/WSL.git                                                                                                                                                                                                                         
Cloning into 'WSL'...
remote: Enumerating objects: 37, done.
fatal: Unable to create temporary file '/mnt/files/code/WSL/.git/objects/pack/tmp_pack_XXXXXX': Permission denied
fatal: index-pack failed:  45% (17/37)
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (33/33), done.
```

**Comment by zinefer** [comment] 2020-04-19 06:23
I am running into this error on 18363:

```
git clone git@github.com:microsoft/WSL.git
Cloning into 'WSL'...
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (33/33), done.
fatal: Unable to create temporary file '/mnt/files/WSL/.git/objects/pack/tmp_pack_XXXXXX': Permission denied
fatal: index-pack failed
```

**Comment by Beguiled** [comment] 2020-04-24 14:40
Came here to also state I see this in 1909 (18363.815)
```
error: insufficient permission for adding an object to repository database .git/objects
error: .gitignore: failed to insert into database
error: unable to index file .gitignore
fatal: adding files failed
```
This is on a drive mounted to a network share with full r/w. All files in the share list as owned by root:root and have full 777 permissions by default.

**Comment by taro-ball** [comment] 2020-10-25 02:35
running into same issue on 2004 (19041.572)
ffs it's over 2 years already and still hasn't been fixed???

**Comment by taro-ball** [comment] 2020-10-25 02:41
@therealkenc i'm running the latest windows, and it doesn't look like this has been fixed

**Comment by clementbiron** [comment] 2020-11-02 18:34
`error: insufficient permission for adding an object to repository database .git/objects`

This does not seem to me to be corrected either, does there exist a workaround ?

**Comment by therealkenc** [comment] 2020-11-02 19:55
This one went fixininsiderbuilds [Oct 2018](https://github.com/microsoft/WSL/issues/3556#event-1924719756), [18267](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18267)

To the extent interested parties would like to open a new issue following the [template](https://raw.githubusercontent.com/microsoft/WSL/master/.github/ISSUE_TEMPLATE/bug_report.md), please ensure you've got (1) [metadata enabled](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-per-distro-launch-settings-with-wslconf), (2) that the submission has a CLI reproduction step sequence that will execute when pasted into a terminal, (3) that the current [working directory](https://man7.org/linux/man-pages/man1/pwd.1.html) of any relative paths is indicated in the steps, and, (4) that the submission includes a link to a [gist](https://gist.github.com/) of a threaded [`strace(1)`](https://man7.org/linux/man-pages/man1/strace.1.html) log.

Noting that `error: insufficient permission for adding an object to repository database .git/objects` is not [the same](https://github.com/microsoft/WSL/issues/3556#issue-362137697) error as `fatal: fsync error on '/mnt/d/code/repo/.git/objects/pack/tmp_idx_QfTqP5': Permission denied`.

**Closed by therealkenc** 2020-11-02 19:55 UTC
Labels: fixedinreleasebuild

**Comment by clementbiron** [comment] 2020-11-03 07:29
Ok thanks 🤗

**Comment by xobs** [comment] 2021-05-24 03:23
I arrived on this page after doing an Internet search because I was experiencing `Permission denied` errors when attempting to use `repo`. For example:

```
Fetching:  0% (0/14) warming uperror: Cannot fetch fsl-community-bsp-base (Error: [(<DirEntry 'heads'>, '/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/projects/sources/base.git/refs/heads', "[Errno 13] Permission denied: '/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/projects/sources/base.git/refs/heads'"), (<DirEntry 'tags'>, '/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/projects/sources/base.git/refs/tags', "[Errno 13] Permission denied: '/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/projects/sources/base.git/refs/tags'"), ('/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/project-objects/fsl-community-bsp-base.git/refs', '/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/projects/sources/base.git/refs', "[Errno 13] Permission denied: '/mnt/d/Code/Ion/Yocto/imx-yocto-bsp/.repo/projects/sources/base.git/refs'")])
```

The solution was to to to the Windows side add `Everyone` to the newly-created `Yocto` directory and give them `Full control`. After doing this, `repo sync` was able to successfully update from WSL1.

I'm posting this here in case it helps anyone else who runs into a similar problem.

**Comment by amit133** [comment] 2021-06-11 08:15
"repo sync" command failed with permission denied message. I opened the Ubuntu as an administrator and it works fine now.
