### ISSUE TITLE
WSL Service Disables Automatically After Reboot or Logoff

### ISSUE THREAD

**Issue by Haerbin23456** [microsoft/WSL#11582] opened 2024-05-13 16:25 UTC
### Windows Version

Microsoft Windows [版本 10.0.22631.3447]

### WSL Version

2.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.146.1-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

Avast One, version 24.4.6112 (build 24.4.9067.835)

### Repro Steps

1.  Try to run command `wsl.exe --status`, and the result be like:
```pwsh
无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。
Error code: Wsl/0x80070422
```
Then I found out the WSL Service is disabled.
2. Configure WSL service to Automatic start and ensure it is running. Now command `wsl.exe --status` succeed.
3. Restart the computer or log off and then log back in.
4. Check the status of the WSL Service. Observe that the WSL Service is disabled again. Try to run command `wsl.exe --status`, failed just like before.

### Expected Behavior

The WSL service should remain enabled and set to automatic start after a system reboot or logoff/logon cycle, maintaining its state across system sessions.

### Actual Behavior

After rebooting the system or logging off and on, the WSL service is found to be disabled. This issue occurs intermittently and has been observed to happen within approximately 20 seconds after logging in, as indicated by system logs. This behavior persists despite the service being manually set to automatic start and confirmed to be running prior to reboot or logoff.
I suspect there might be an interaction with Avast One antivirus software affecting the WSL service. However, I have already added the WSL service executable (C:\Program Files\WSL\wslservice.exe) to Avast's exceptions list, but the issue persists.

### Diagnostic Logs
[WslLogs-2024-05-11_16-40-56.zip](https://github.com/microsoft/WSL/files/15297449/WslLogs-2024-05-11_16-40-56.zip)

**Comment by Haerbin23456** [comment] 2024-05-13 16:40
> The logs show that wslservice is disabled. Try to run (elevated command prompt): `sc.exe config wslservice start= demand` and see if that solves the issue
> 
> Diagnostic information

WSL Service started at first, but got disabled again shortly after reboot.

**Comment by OneBlue** [comment] 2024-05-13 18:49
Thank you @Haerbin23456. Do you have some kind of AntiVirus / security solution installed ? 

For instance we know that AVG can disable wslservice unless you create an exclusion rule.

**Comment by Haerbin23456** [comment] 2024-05-14 02:34
> Thank you @Haerbin23456. Do you have some kind of AntiVirus / security solution installed ?
> 
> For instance we know that AVG can disable wslservice unless you create an exclusion rule.

I installed Avast One, but I have added the WSL service executable (C:\Program Files\WSL\wslservice.exe) to Avast's exceptions already. The issue persists.

**Comment by OneBlue** [comment] 2024-05-14 16:24
For the sake of experimentation, can you try uninstalling Avast One to see if that resolves the issue ?

**Comment by Haerbin23456** [comment] 2024-05-15 14:58
> For the sake of experimentation, can you try uninstalling Avast One to see if that resolves the issue ?

Yes, that resolves the issue.

**Comment by OneBlue** [comment] 2024-05-15 18:21
Ok thank you. In that case it's pretty clear that the issue is caused by Avast One. 

Closing since the root cause of the issue is Avast.

**Closed by OneBlue** 2024-05-15 18:21 UTC

**Comment by IricsDo** [comment] 2026-05-10 18:26
I have the same issue with Window 11 and WSL 2 Ubuntu.  I installed AVG TuneUp, but already uninstall it.
But I still get the error message Error code: Wsl/0x80070422.
Do you have any suggestion? 
Thank you
