### ISSUE TITLE
Files in DrvFs still reporting wrong type?

### ISSUE THREAD

**Issue by Warblefly** [microsoft/WSL#2464] opened 2017-08-31 15:33 UTC
In Build 16278, I'm seeing plenty of compilations fail with GCC complaining in ways such as:

`/usr/include/x86_64-linux-gnu/sys/select.h:33:25: fatal error: lto/bits/sigset.h: Invalid argument`

...which is the type of error that used to happen when DrvFs-mounted drives were borked a few flights ago. "Invalid argument" meaning a file is a wrong type (e.g. directory) not merely missing. Is this still happening?

**Comment by benhillis** [comment] 2017-08-31 17:53
@Warblefly - That issue should be fixed. Can you give us some reproducible steps so we can check this out locally?

Adding @SvenGroot.

**Comment by SvenGroot** [comment] 2017-08-31 17:58
This actually looks like an LxFs issue, since it's referring to a file under /usr. LxFs was not affected by the previous issue, and hasn't received any real changes recently.

As @benhillis said, we need a repro to look into this.

**Comment by Warblefly** [comment] 2017-08-31 20:33
OK, I'll try. Just got this, though, in a `make -j 8` situation... (and the "fork: Invalid argument" has been happening for a while, too so I should write this up separately?)

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../source/gmp-6.1.2/printf -I.. -D__GMP_WITHIN_GMP -I../../source/gmp-6.1.2 -fexceptions -O2 -pedantic -fomit-frame-pointer -m64 -c ../../source/gmp-6.1.2/printf/doprnti.c -o doprnti.o
../libtool: fork: Invalid argument
../libtool: line 1: wait_for: No record of process 23189
Makefile:435: recipe for target 'obvprintf.lo' failed
```

**Comment by Warblefly** [comment] 2017-08-31 21:01
Not sure if this is related. Every time I try this series of compilations, something happens (and screens and screens of this just now, but failing at a different point)

Do I interpret this correctly? Something created earlier, that a program expects to be a simple file, is now a directory?

```
2017-08-31 21:57:12 URL:http://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz [62312628/62312628] -> "gcc-7.2.0.tar.xz" [1]
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/stable_partition/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/set_intersection/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/set_intersection/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/set_intersection/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/set_intersection/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/reverse_copy/explicit_instantiation/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/reverse_copy/explicit_instantiation/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/next_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/next_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/next_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/next_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/prev_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/prev_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/prev_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/25_algorithms/prev_permutation/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/pareto_distribution/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/pareto_distribution/requirements/explicit_instantiation/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/simd_fast_mersenne_twister_engine/cons/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/simd_fast_mersenne_twister_engine/cons/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/simd_fast_mersenne_twister_engine/cons/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/simd_fast_mersenne_twister_engine/cons/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/ext/random/simd_fast_mersenne_twister_engine/cons/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/22_locale/codecvt/codecvt_utf8_utf16/requirements/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry_01/operators/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/subtract_with_carry/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/linear_congruential/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/linear_congruential/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/linear_congruential/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/linear_congruential/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/linear_congruential/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/linear_congruential/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/normal_distribution/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/5_numerical_facilities/random/normal_distribution/requirements/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/7_regular_expressions/basic_regex/assign/char/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/7_regular_expressions/basic_regex/assign/char/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/7_regular_expressions/basic_regex/assign/char/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/7_regular_expressions/basic_regex/assign/char/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/7_regular_expressions/basic_regex/assign/char/PaxHeaders.13071/: Is a directory
pax: Unable to create gcc-7.2.0/libstdc++-v3/testsuite/tr1/7_regular_expressions/basic_regex/assign/char/PaxHeaders.13071/: Is a directory
```

**Comment by Warblefly** [comment] 2017-08-31 22:40
And every time I try to compile GCC from a directory on the DevFs system, a different file has been transformed into something wrong:

```
In file included from /usr/include/stdio.h:35:0,
                 from ../../source/gcc-7.2.0/gcc/system.h:46,
                 from ../../source/gcc-7.2.0/gcc/cp/expr.c:23:
/usr/include/x86_64-linux-gnu/bits/types.h:121:62: fatal error: cp/bits/typesizes.h: Invalid argument
compilation terminated.
Makefile:1099: recipe for target 'cp/expr.o' failed
```

**Comment by Warblefly** [comment] 2017-09-01 07:10
As for steps to a reproducible error, mine are to compile GCC 7.2.0 as a cross-compiler, using -j 8 to make.

**Comment by Warblefly** [comment] 2017-09-02 09:14
Completely uninstalled the subsystem, deleted lxss, removed all working directories, re-installed, and `#include` directives still randomly fail with "invalid argument":

```
g++ -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -Icp -I../../source/gcc-svn/gcc -I../../source/gcc-svn/gcc/cp -I../../source/gcc-svn/gcc/../include -I../../source/gcc-svn/gcc/../libcpp/include -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/pkgs/gmp/gmp-6.1.2-x86_64/include -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/pkgs/mpfr/mpfr-3.1.5-x86_64/include -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/pkgs/mpc/mpc-1.0.3-x86_64/include  -I../../source/gcc-svn/gcc/../libdecnumber -I../../source/gcc-svn/gcc/../libdecnumber/bid -I../libdecnumber -I../../source/gcc-svn/gcc/../libbacktrace -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/pkgs/isl/isl-0.18-x86_64/include  -o cp/decl.o -MT cp/decl.o -MMD -MP -MF cp/.deps/decl.TPo ../../source/gcc-svn/gcc/cp/decl.c
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:168:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:34,
                 from /usr/include/x86_64-linux-gnu/sys/param.h:26,
                 from ../../source/gcc-svn/gcc/system.h:298,
                 from ../../source/gcc-svn/gcc/cp/call.c:26:
/usr/include/limits.h:151:29: fatal error: cp/bits/xopen_lim.h: Invalid argument
compilation terminated.
Makefile:1099: recipe for target 'cp/call.o' failed
make[1]: *** [cp/call.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm gcov.pod fsf-funding.pod gpl.pod cpp.pod gfdl.pod gfortran.pod gcc.pod gcov-dump.pod gcov-tool.pod
make[1]: Leaving directory '/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/pkgs/gcc/build/gcc'
Makefile:4225: recipe for target 'all-gcc' failed
make: *** [all-gcc] Error 2
```

**Comment by Warblefly** [comment] 2017-09-02 18:40
The same problem occurs on Build 16281, which landed on my machine today. The host GCC is the supplied Ubuntu GCC, which is version 5.4.0

```
g++ -fno-PIE -c  -DIN_GCC_FRONTEND -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -Ic -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/c -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/../include -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/../libcpp/include -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/bld/gcc/./gmp -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gmp -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/bld/gcc/./mpfr/src -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/mpfr/src -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/mpc/src  -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/../libdecnumber -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/../libdecnumber/bid -I../libdecnumber -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/../libbacktrace -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/bld/gcc/./isl/include -I/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/isl/include  -o c/c-decl.o -MT c/c-decl.o -MMD -MP -MF c/.deps/c-decl.TPo /mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/c/c-decl.c
In file included from /mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/coretypes.h:369:0,
                 from /mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/c/c-lang.c:23:
/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/src/gcc-7.2.0/gcc/hash-table.h:237:21: fatal error: c/hashtab.h: Invalid argument
compilation terminated.
Makefile:1099: recipe for target 'c/c-lang.o' failed
```

**Comment by Warblefly** [comment] 2017-09-02 21:04
Is this issue #1735 again, perhaps?

**Comment by Warblefly** [comment] 2017-09-03 08:45
Compiling GCC on the 'native' Linux filesystem entirely within lxss does not fail. But on DrvFs, it does.

**Comment by nutcasev15** [comment] 2017-11-27 15:29
Experiencing the same issue on build 16299.64.

Compiling Linux kernel 3.10 with GCC 7.1 custom toolchain.

The compiler errors on a different file each time but the error code is always the same.
`In file included from drivers/external_drivers/intel_media/bld/merrifield/tng/../../../display/tng/drv/mdfld_csc.c:28:0:
drivers/external_drivers/intel_media/bld/merrifield/tng/../../../display/tng/drv/psb_drv.h:35:10: fatal error: drivers/external_drivers/intel_media/graphics/rgx/services/shared/devices/rgx/ttm/ttm_object.h: Invalid argument
 #include "ttm/ttm_object.h"
          ^~~~~~~~~~~~~~~~~~
  CC      net/ipv4/tcp_sociopath.o
compilation terminated.
  CC      drivers/external_drivers/intel_media/bld/merrifield/tng/../../../display/tng/drv/psb_socket.o
scripts/Makefile.build:308: recipe for target 'drivers/external_drivers/intel_media/bld/merrifield/tng/../../../display/tng/drv/mdfld_csc.o' failed
make[4]: *** [drivers/external_drivers/intel_media/bld/merrifield/tng/../../../display/tng/drv/mdfld_csc.o] Error 1`

The source for the same is here [https://github.com/nutcasev15/Holo-N/tree/RW](url)
The TC is here [https://github.com/nutcasev15/Custom-TC](url)

The issue is resolved if I delete all the files in the git repo with rm -rf * & then force checkout the branch. But it only stays as long as the laptop is on. If I shut down and try to compile after rebooting the issue appears again.

The source & the TC are both on /mnt/d i.e. DrvFs.

**Comment by kwaegel** [comment] 2017-11-29 23:25
This just started happening to me too, build 16299.rs3_release. I keep getting `Invalid argument` errors for paths that do not exist, and it's always a different file.

**Comment by Lin-Buo-Ren** [comment] 2018-09-08 07:56
Got a similar error here when building a snap package under Ubuntu 16.04 WSL(Windows 10 version 1803 build 17134.254):

```
make[3]: Entering directory '/home/brlin/utsushi-snap/parts/utsushi/build/lib'
  CXX      exception.lo
  CXX      connexion.lo
  CXX      device-info.lo
  CXX      log.lo
../libtool: fork: Invalid argument
g++: error: : 沒有此一檔案或目錄(No such file or directory)
Makefile:678: recipe for target 'connexion.lo' failed
make[3]: *** [connexion.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by HinTak** [comment] 2018-09-08 11:34
What is underneath drvfs? Ntfs or?

**Comment by bpulliam** [comment] 2021-05-07 13:43
Much has changed in the WSL world since this was filed.  If you still see this issue, please file a new one. Thanks!

**Closed by bpulliam** 2021-05-07 13:43 UTC
Labels: need-repro
