### ISSUE TITLE
Touchscreen scrolling is not passed through to mouse-mode applications

### ISSUE THREAD

**Issue by lilred** [Microsoft/WSL#1406] opened 2016-11-22 01:05 UTC
When using mouse mode applications such as `tmux` and `vim`, Surface Book touchscreen scrolling is not properly forwarded to the app.

For example, if I start `vim ~/.bashrc` and enter `set mouse=a`, I would expect touchscreen scrolling to scroll through the file.

Instead, I "break out" of Vim and scroll past it.

This is on Windows 14965.

**Comment by fpqc** [comment] 2016-11-22 03:55
@lilred I bet this also happens on Linux.  The problem is that scroll-wheel scrolling is actually implemented by passing the terminal escape sequences (which you can see if you ever accidentally disconnect from ssh while in tmux).  I'm guessing that Microsoft implements touchscreen scrolling as smooth scrolling directly in Windows (by passing it directly to the scroll widget of the associated window). 

@zadjii-msft might be able to tell you what the prospects are for adding in this behavior.

**Comment by lilred** [comment] 2016-11-22 12:32
@fpqc I'm no stranger to the mechanics of scrolling, see for example #1390 :)

>I bet this also happens on Linux.

That may be so. I have no way to check right now! But trackpad scrolling on BoW *is* passed through to mouse-mode applications (albeit poorly), so I'm still hopeful.

**Comment by zadjii-msft** [comment] 2016-11-29 17:05
@lilred Out of curiosity, does touchscreen scrolling work for normal cmd/powershell? I don't have a touchscreen machine on hand to verify for myself. 

Without any more info, I'd assume that this is probably related to #1390

**Comment by fpqc** [comment] 2016-11-29 17:21
@zadjii-msft Time to requisition a surface book?

**Comment by lilred** [comment] 2016-12-01 02:43
Touchscreen scrolling works perfectly in all three of cmd, powershell and bash. The problem is that bash handles touchscreen scrolling differently from mouse scrolling when within a mouse mode application.

**Comment by zadjii-msft** [comment] 2016-12-08 23:03
So, after investigating this today, it turns out that adding touch support isn't all that trivial of a fix. Any touch support we have right now is support that we get for free from the OS itself. I'm creating backlog items to add more support for touch in a future release.

Until then, touch scrolling will still work outside VT mouse mode, and touch clicking/dragging will work in VT mouse mode. Sorry there's not a better outcome to this, but it's now definitely on our radar.

**Comment by lilred** [comment] 2016-12-09 19:35
Thanks for keeping us up to date. 

>So, after investigating this today, it turns out that adding touch support isn't all that trivial of a fix. Any touch support we have right now is support that we get for free from the OS itself.

Don't forget to file a bug with the relevant team(s), maybe they can help out :)

**Comment by bitcrazed** [comment] 2018-05-22 22:46
Thanks for the discussion.

Closing this issue since:
1. This issue is being tracked on our internal bug tracker, but is dependent on us overhauling the Console's input and rendering system - work that is in the queue but will take a while to complete
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Closed by bitcrazed** 2018-05-22 22:46 UTC
Labels: backlog, console, feature
