### ISSUE TITLE
WSL cannot start Windows Store exe files

### ISSUE THREAD

**Issue by agowa338** [microsoft/WSL#5076] opened 2020-04-12 22:18 UTC
WSL is unable to start windows executables that have been created by windows store apps e.g.
`C:\Users\Klaus\AppData\Local\Microsoft\WindowsApps\EmEditor.exe`

strace:
```
ubuntu@PC-001:~$ strace EmEditor.exe
execve("/mnt/c/Users/Klaus/AppData/Local/Microsoft/WindowsApps/EmEditor.exe", ["EmEditor.exe"], 0x7fffc9aa51d0 /* 18 vars */) = -1 ENOEXEC (Exec format error)
fstat(2, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(2, "strace: exec: Exec format error\n", 32strace: exec: Exec format error
) = 32
getpid()                                = 67
exit_group(1)                           = ?
+++ exited with 1 +++
```

This may occur because these files are empty and are a special kind of symbolic link (at least I guess that's how it works)

**Comment by DHowett-MSFT** [comment] 2020-04-13 01:00
This is a duplicate of #4969.

**Closed** 2020-04-15 02:15 UTC
