### ISSUE TITLE
WSL2 fails to start following 18965 update

### ISSUE THREAD

**Issue by Cisien** [microsoft/WSL#4432] opened 2019-08-21 23:32 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.18965.1000]`

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

I noticed that Docker Desktop was reporting that Ubuntu 18.04 was not installed, when I was recently using the WSL2 tech preview prior to the current insider update. When I tried to launch from the command line, I received an error: 0xffffff

```
C:\Users\ccurw>wsl
Error: 0xffffffff

C:\Users\ccurw>ubuntu
Error: 0xffffffff
```
Since the `ubuntu` install was already existing, I attempted to install ubuntu1804 from the store, and when trying to run, i receive a similar error, this time with slightly more detail:
```
C:\Users\ccurw>ubuntu1804
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xffffffff
Error: 0xffffffff (null)
Press any key to continue...
```

* What's wrong / what should be happening instead:
I'm expecting to get a bash prompt after running `wsl`, `ubuntu`, or `ubuntu1804`, and I'm expecting docker desktop to pick up the WSL install

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
strace of the `wsl` command: https://paste.cisien.com/f/lvoovmt3.strace

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).
logs taken of the `wsl` command
`lxcore_kernel.etl`: https://paste.cisien.com/f/hts2g5mi.etl
`lxcore_user.etl`: https://paste.cisien.com/f/sjtjk1z3.etl
`lxcore_service.etl`:https://paste.cisien.com/f/zzffoqa3.etl

**Comment by Fincodr** [comment] 2019-08-23 07:56
For me this error appeared when I upgraded from 18965.1000 to 18965.1005

**Comment by songpr** [comment] 2019-08-23 09:06
I got the same error with os build 18936.1000

WSL 1 work properly. But I cannot start ubuntu with WSL2

**Comment by glenfordwilliams** [comment] 2019-08-23 15:32
Error: 0xffffffff

installed on 8/14/2019
version 1903
ob build 18956.1000

**Comment by fr34kyn01535** [comment] 2019-08-26 11:15
Error: 0xffffffff

installed on 8/26/2019
version 1903
ob build 18956.1005

**Comment by fr34kyn01535** [comment] 2019-08-26 11:18
Duplicate of #4364

**Comment by fr34kyn01535** [comment] 2019-08-26 11:25
Following @puco's hint, uninstalling Docker Desktop seems to fix the issue.

**Closed** 2019-08-26 13:41 UTC

**Comment by fr34kyn01535** [comment] 2019-08-26 15:31
Did you restart the machine?

**Comment by fr34kyn01535** [comment] 2019-08-26 15:54
Did you have Docker Desktop installed before? I switched to linux containers before i uninstalled. I also have a slightly newer Windows build...

**Comment by Fincodr** [comment] 2019-08-27 04:40
These steps worked for me!
1. Start Docker Desktop
2. Docker Desktop Menu > Switch to linux containers (takes awhile)
3. Exit Docker Desktop and Uninstall Docker Desktop
4. Reboot
5. Download and install Ubuntu 18.04 from Microsoft Store
6. WSL2 works again!

**Comment by fr34kyn01535** [comment] 2019-08-27 06:39
Actually, reinstalling Docker Desktop reintroduces the problem for me, and downloading ubuntu again is not necessary.

**Comment by glenfordwilliams** [comment] 2019-08-29 10:02
trying to reinstall ubuntu

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0xffffffff
Error: 0xffffffff (null)
Press any key to continue...

**Comment by Rustywolf** [comment] 2019-09-05 03:53
For anyone who's trying to fix this, it wasn't working for me as port 53 was bound. Use Resource Monitor > Network > Listening Ports to find out what has it bound, and stop the service temporarily.

**Comment by ducmthai** [comment] 2019-09-10 17:55
Here's a workaround to make it works again:

1. Uncheck 'Start Docker Desktop when you log in'
2. Restart the computer
3. Open PowerShell as Administrator and enter the following command:
`Stop-Service com.docker.service`
Note: You can use other methods to stop this service.
6. Start wsl
7. Switch back to PowerShell and enter teh following command:
`Start-Service com.docker.service`
9. Open Docker Desktop and start the WSL daemon manually.

**Comment by agustindidiego** [comment] 2019-09-24 16:54
I was having this issue and it resulted to be my port 53 being used by AcrylicService. After stopping the service and installing the distro on wsl 2 worked

**Comment by dacioromero** [comment] 2019-11-26 05:18
In case anyone else has this issue. Simple DNSCrypt was the problem for me.

**Comment by PejmanNik** [comment] 2020-04-13 05:45
If you have the DNSCrypt problem. change the DNSCrypt service startup type from **Automatic** to **Automatic (Delayed Start)** it will solve the problem.

**Comment by martanto** [comment] 2020-05-29 12:47
> 
> 
> In case anyone else has this issue. Simple DNSCrypt was the problem for me.

I have DNSCrypt too. Temporary disabled it, fixed the issue

**Comment by jrmessias** [comment] 2020-06-29 02:19
I have AcrylicDNS. Temporary disabled it, fixed the issue.
Alter port for no future issues

**Comment by rhonivanpareja** [comment] 2020-07-01 13:12
Can confirm @jrmessias fix. Disabled AcrylicDNS too. thanks man saved my life there!

**Comment by doomy** [comment] 2020-07-10 08:37
Anyone managed to get WSL2 and Acrylic running alongside each other?
It used to work on my older machine so it has to be possible!
Setting my acrylic port to 55 breaks the DNS functionality, so that one doesn't seem to work out for me. Or do I need to set the port also semewhere in Windows settings?

**Comment by mxmp210** [comment] 2020-07-30 10:52
> 
> 
> Anyone managed to get WSL2 and Acrylic running alongside each other?
> It used to work on my older machine so it has to be possible!
> Setting my acrylic port to 55 breaks the DNS functionality, so that one doesn't seem to work out for me. Or do I need to set the port also somewhere in Windows settings?

Bump on same, trying to figure out setting up DNS server alongside WSL2 as port 53 is occupied and router wont accept server with custom port.

**Comment by zimmermann-dev** [comment] 2020-08-02 18:01
> For anyone who's trying to fix this, it wasn't working for me as port 53 was bound. Use Resource Monitor > Network > Listening Ports to find out what has it bound, and stop the service temporarily.

Thanks that was the problem. AdGuard runs on port 53!

**Comment by usaguerrilla** [comment] 2020-08-12 23:30
DNS and WSL2 are fighting for port 53. Any solution?

**Comment by mxmp210** [comment] 2020-08-13 10:35
> 
> 
> DNS and WSL2 are fighting for port 53. Any solution?

I ended up with shifting my dns server to another machine since there's no fix for port 53, also if you can move DNS server port and utilize without legacy UDP client it may solve your problem as WSL and HyperV for WSL2 requires it, there's no solution for now. it's hardcoded into system and without that svchost service running on port 53 WSL wont start or convert any images from v1 to v2 or v2 to v1

**Comment by edwinchenloo** [comment] 2020-08-30 12:59
i had to stop DNSCrypt and SharedAccess services.

**Comment by hyuuki** [comment] 2020-09-01 07:47
Disabling SharedAccess/Internet Connection Sharing (ICS) solved my problem, DNSCrypt still enabled though.

**Comment by hakankaan** [comment] 2020-10-23 11:16
> Disabling SharedAccess/Internet Connection Sharing (ICS) solved my problem, DNSCrypt still enabled though.

thanks for information. this was the easiest solution imo

**Comment by VarunAgw** [comment] 2020-11-02 16:00
> Disabling SharedAccess/Internet Connection Sharing (ICS) solved my problem, DNSCrypt still enabled though.

How do you do that? I don't recall enabling them anywhere.
