### ISSUE TITLE
Unable to Restart SSH Service.

### ISSUE THREAD

**Issue by JoaquinMVR** [Microsoft/WSL#1737] opened 2017-03-01 00:14 UTC
I wanted to restart the SSH server but it failed.

This is what I got: 

```
JoaquinMVR@ELITEBOOK-8470P:~$ sudo service ssh restart
[sudo] password for JoaquinMVR:
initctl: Imposible conectar con Upstar: Failed to connect to socket /com/ubuntu/upstart: Conexión rehusada
sshd: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
Aborted (core dumped)
```
```
JoaquinMVR@ELITEBOOK-8470P:~$ sudo service ssh --full-restart
 * Stopping OpenBSD Secure Shell server sshd                                                                     [ OK ]
 * Starting OpenBSD Secure Shell server sshd                                                                            sshd: ../sysdeps/posix/getaddrinfo.c:2583: getaddrinfo: Assertion `(__extension__ ({ const struct in6_addr *__a = (const struct in6_addr *) (sin6->sin6_addr.__in6_u.__u6_addr32); __a->__in6_u.__u6_addr32[0] == 0 && __a->__in6_u.__u6_addr32[1] == 0 && __a->__in6_u.__u6_addr32[2] == __bswap_32 (0xffff); }))' failed.
Aborted (core dumped)
                                                                                                                 [fail]
```
Windows Build is: Version 1607 - Compilation: 14393.693

**Comment by aseering** [comment] 2017-03-01 00:40
Hi @JoaquinMVR , thanks for posting!  Hm...  I don't know the exact cause of.this issue, but I do know that a large number of networking bugs have been fixed in more-recent [Insider builds](http://insider.windows.com).

If you're willing to try an Insider build, it would be interesting to know whether it fixes your problem.

**Comment by benhillis** [comment] 2017-03-01 01:44
The error you're seeing is about not being able to connect to the upstart daemon (which is expected because we don't run it).  I'd suggest restarting your ssh service with the below script:

`sudo /etc/init.d/ssh restart`

**Comment by Zx-EvM** [comment] 2017-03-01 09:27
@benhillis it is possible to implement `upstart`? or it's very hard or inexpedient and it will not be implemented?

**Comment by aseering** [comment] 2017-03-01 12:03
@benhillis -- with respect, could you elaborate on why you believe that an `assert()` in the `sshd` binary is due to Upstart in this case?  (Do you believe that the Upstart warning has more significance here than it has in other tickets regarding sshd, where users have been able to safely ignore it?)

@Zx-EvM , regarding Upstart -- @benhillis is the right person to answer your question.  (He actually works on the WSL team; I'm just another user :-) )  But I will observe that Ubuntu itself has actually dropped Upstart in more-recent releases.  If you install the latest WSL Linux image using a Windows [Insider build](http://insider.windows.com), you'll find that the latest version doesn't use Upstart at all.  However, it uses systemd instead; unfortunately, systemd doesn't work yet either :-)

**Comment by benhillis** [comment] 2017-03-01 16:09
@aseering - I was referring to this line:

`initctl: Imposible conectar con Upstar: Failed to connect to socket /com/ubuntu/upstart: Conexión rehusada
`

You're right the second error probably has to do with networking support, but if you can't connect to upstart you can't launch services using the 'service' binary.

@Zx-EvM - Regarding upstart and other daemons in general: It's something we're looing at supporting in a future release.

**Comment by aseering** [comment] 2017-03-01 20:14
@Zx-EvM -- <digs some more>  Oh, I think this is the same error as is seen on #1113 .  The core dump is in the same file and line number, anyway.  That ticket discusses a couple specific workarounds; perhaps one of those might help you?

@benhillis -- I buy the reasoning that upstart isn't working, but I'm struggling to see how it follows that it's preventing sshd from starting in a reproducer where an sshd process that has been started is segfaulting?

If you do have evidence that that is the case, perhaps you could post that as an update/clarification to [some](https://github.com/Microsoft/BashOnWindows/issues/300#issuecomment-238922708) [of](https://github.com/Microsoft/BashOnWindows/issues/143#issuecomment-240180711) [the](https://github.com/Microsoft/BashOnWindows/issues/695#issuecomment-248344418) [tickets](https://github.com/Microsoft/BashOnWindows/issues/791#issuecomment-238027584) where others (including [one of your colleagues](https://github.com/Microsoft/BashOnWindows/issues/734#issuecomment-237298259) at Microsoft) appear to believe that this error message does not impact the functionality of this script?

Anyway, I'll stop interrupting; after all, this is y'all's forum :-)  If you say it's Upstart, I'll take your word for it.  Something just seems funny, is all.

**Comment by benhillis** [comment] 2017-03-01 20:23
@aseering - I stand corrected - When I tried this on an internal build the service command works.

It's possible the "service" binary is only trying to connect to upstart to let the daemon know that it's starting a service. I don't even see the message about not connecting to upstart though so probably something has changed in userland between 14.04 and 16.04.

**Comment by aseering** [comment] 2017-03-01 22:44
Yeah, a lot has changed in userland between 14.04 and 16.04 in Ubuntu's init system :-)  systemd appeared, for starters.

**Comment by Zx-EvM** [comment] 2017-03-02 01:56
@aseering @benhillis thanks, I prefer to just wait. Without experiments.

But I have question about this:

@benhillis you tell above: `Regarding upstart and other daemons in general: It's something we're looing at supporting in a future release.` but I've read about what WSL will go from `Ubuntu 14.04` to `Ubuntu 16.04` in the next release and in `16.04` used `systemd` instead of `upstart` as @aseering written.

**Comment by SangHLee** [comment] 2017-04-19 20:24
@Zx-EvM I am also interested in whether bash on windows ubuntu 16.04.2 LTS will support upstart or systemd? It would be great to run rstudio-server on bash on windows 10.

**Comment by therealkenc** [comment] 2018-05-29 01:46
> Windows Build is: Version 1607 - Compilation: 14393.693

`sudo service ssh start` has worked on WSL since at [least 14361](https://github.com/Microsoft/WSL/issues/300#issuecomment-223698109). Why the OP was getting a segfault here we will probably never know for sure. Adam's hypothesis this was dupe #1113 is good enough for me.

**Closed by therealkenc** 2018-05-29 01:46 UTC
Labels: workaround-available
