### ISSUE TITLE
missing ‘msgget’ system call！

### ISSUE THREAD

**Issue by QinHuasong** [microsoft/WSL#1443] opened 2016-12-01 02:29 UTC
I've tried WSL , my apps can be compiled correctly. 
But when I execute , it says "msgget: Operation not supported".
while my source code is like this:
_

1. int msgqid = -1;
2. msgqid = msgget(key, 0666 | IPC_CREAT);
_

@bitcrazed 
I've @ you on twitter . Appreciate your reply.

**Comment by therealkenc** [comment] 2016-12-01 08:20
#1016 ([message](https://github.com/Microsoft/BashOnWindows/issues/1016#issuecomment-243507723))

**Comment by stehufntdev** [comment] 2016-12-01 17:58
Closing this out as a duplicate of #1016 so we can track the issue there.

**Comment by benhillis** [comment] 2017-07-05 23:33
Reopening this issue since this is the only piece of the System V family of system calls that is still unimplemented.

**Comment by rodar21** [comment] 2017-08-02 00:44
Yes we need this as its fundamental to our runtime and messaging systems used by some of our fortune level customers. (msgget etc). it precludes any of our customers using WSL.

**Comment by yeedog** [comment] 2018-02-19 01:04
Has there been any update to this issue?  

I need to use message queues for work and while I can run on the target hardware, being able to test things out in the WSL is often faster than cross compiling and loading code.

**Comment by bitcrazed** [comment] 2018-03-04 19:11
@oshz AS @benhillis says [above](https://github.com/Microsoft/WSL/issues/1443#issuecomment-313254655) - we've not yet implemented Queue support

**Comment by oshz** [comment] 2018-03-05 06:26
@bitcrazed Thanks. Any plans on getting this implemented?

**Comment by hippiehunter** [comment] 2018-05-17 16:41
msgget is very important to my company. When built for linux, our product uses queues to talk between long running processes and short lived ones. Transitioning this to use sockets lead to a massive performance hit when we tried it in the past. We're trying to move our customers to do all of their development work on windows (even if they ultimately test/deploy on linux) to take advantage of visual studio as much as possible. Having this issue fixed would make this push significantly easier.

**Comment by WeirdBob** [comment] 2018-07-12 08:30
Hi @benhillis @bitcrazed , any news on this? I can imagine this is not the most important feature you have to implement but for some of us this is a show stopper. That's too bad because WSL is really impressive and I'm looking forward to ditching my last VMs!

**Comment by bitcrazed** [comment] 2018-07-12 15:02
Hey Bob! I'll leave feature scheduling/planning decisions to @tara-raj and @benhillis & team. 

But yeah, I agree it'd be great to get this family of syscalls built-out :D It's mostly "just" a matter of resources x schedule x prioritization :)

**Comment by tara-raj** [comment] 2018-07-12 17:19
Thanks for raising this. In general, we've been implementing syscalls on a per-need basis. Based on the feedback from this thread, we've started the work needed to implement this syscall. It is a fairly large change, so this is still "in the pipeline." I will update this thread when the work is complete and flighted.

As [@bitcrazed mentioned](https://github.com/Microsoft/WSL/issues/1443#issuecomment-404543744) the time taken for you to see this change will mainly depend on our ship schedule and other priorities.

**Comment by yeedog** [comment] 2018-07-12 22:34
Awesome.  I'm glad message queues are going to be implemented in a future version as this was one feature that was holding me.back from fully embracing wsl for everyday development.

While wsl is not my target it is extremely useful for development with clion and initial testing.  Then only running on the target hardware to get final results.

**Comment by Snapstromegon** [comment] 2019-06-11 12:53
It's been a while - is there any progress on this?

**Comment by lnicola** [comment] 2019-06-11 12:54
It will be fixed in WSL 2: https://devblogs.microsoft.com/commandline/announcing-wsl-2/.

**Closed** 2020-06-03 05:12 UTC
Labels: fixed-in-wsl2
