### ISSUE TITLE
wsl --import/--export does not handle paths with spaces or quoted paths correctly

### ISSUE THREAD

**Issue by 0xbadfca11** [Microsoft/WSL#3932] opened 2019-03-22 11:44 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.1]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
```cmd
C:\Users\JohnDoe> wsl --export Ubuntu "Ubuntu.tar"
The filename, directory name, or volume label syntax is incorrect.
```
![image](https://user-images.githubusercontent.com/7390559/54819995-0bc01100-4ce1-11e9-9e9f-4cf1688d8d43.png)
```cmd
C:\Users\JohnDoe> wsl --import Ubuntwo C:\Ubuntu "C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc\install.tar.gz"
The filename, directory name, or volume label syntax is incorrect.
```
![image](https://user-images.githubusercontent.com/7390559/54820206-b1738000-4ce1-11e9-9ed2-fe7ad845e292.png)

* What's wrong / what should be happening instead:
Both file paths should be treated correctly.

**Comment by 0xbadfca11** [comment] 2019-03-22 11:46
* Workaround
Use stdin/stdout.
```cmd
> wsl --import Ubuntwo C:\Ubuntu - < "C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc\install.tar.gz"
```

**Comment by benhillis** [comment] 2019-03-22 15:39
Good find, I'll sort this out.

**Comment by Brian-Perkins** [comment] 2019-05-01 21:11
Fixed in Windows Insider Build [18890](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md#build-18890)

**Closed** 2019-05-02 04:42 UTC
Labels: bug, fixinbound

**Comment by jarmo** [comment] 2019-11-30 19:05
My Windows version is `10.0.18362.476`.

I have the same problem - I cannot even export.

wsl -l shows:
```
Legacy (Default)
```

Trying to export it:
```
wsl --export "Legacy (Default)" ubuntu.tar
```

Shows me the exact same error as above:
```
The filename, directory name, or volume label syntax is incorrect.
```

I tried to pipe it directly to file like this:
```
wsl --export "Legacy (Default)" > ubuntu.tar
```

`ubuntu.tar` will include the exact same error message.

I suspect that the problem is with the distribution name (`Legacy (Default)`) itself. Can I rename distribution somehow to test it out? How would I solve this problem with a workaround?

**Comment by jarmo** [comment] 2019-11-30 20:38
Forgot to mention - I tried different working directories without having any positive effect.

**Comment by jarmo** [comment] 2019-11-30 20:54
After upgrading Windows to `10.0.19033.1` via Insider Program I managed to export like this:
```
wsl --export "Legacy" ubuntu.tar
```

Note, that I had to exclude " (Default)". I also tried that with the previous version and got an error message that Distribution with the name "Legacy" was not found.
