### ISSUE TITLE
Launching a second "Ubuntu" (bash) window results in a window that's not in focus

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/WSL#3123] opened 2018-04-24 22:30 UTC
Repro:
1) Left-click "Ubuntu" shortcut on the task bar -> a bash opens and the window is in focus, meaning you can start typing right away and the text appears in the bash.
2) Right-click the "Ubuntu" shortcut, then left-click "Ubuntu", to launch a second bash window. This window is then **not** in focus. You have to first click it before it's in focus.

* Your Windows build number:  Microsoft Windows [Version 10.0.16299.402]

**Comment by mpa7** [comment] 2018-04-25 10:02
Yeah, this one has been annoying me for a while.  Specifically, it appears the new window is not placed at the top of the z-order (as seen via Alt-Tab).

I can also repro it **intermittently** by Shift-left-click (when distro running) and left-click (when not running).  It may be shell/console rather than WSL because when trying with Command Prompt - I can repro (intermittently) with Shift-left-click but not at all via right-click menu.  File Explorer, Edge etc don't seem to be affected.

Also repros on build 17650 (skip ahead).

**Comment by wkbrd** [comment] 2018-05-15 13:41
FYI, this appears to be a duplicate of #2597

**Comment by patrikhuber** [comment] 2018-05-15 13:54
Yep, that issue looks very similar. @zadjii-msft, could we get an update on this? That would be much appreciated.
Thank you very much!

**Comment by zadjii-msft** [comment] 2018-05-15 16:15
I'm closing this as a dupe of #2597

**Closed by zadjii-msft** 2018-05-15 16:15 UTC
