### ISSUE TITLE
WSL2 Ubuntu - how to start as regular user

### ISSUE THREAD

**Issue by ARW-UBT** [microsoft/WSL#11109] opened 2024-02-01 08:43 UTC
### Windows Version

Windows Server 2022 (21H2)

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 22.04

### Repro Steps

I have installed WSL2 Ubuntu-2204 in a regular user account via "Power Shell as Administrator". Ubuntu can be started from within this shell as administrator. 
For regular use, I would like to start Ubuntu as a regular user without admin rights, but this seems not be possible. 
I assume, it is due to access rights to WSL2 files and folders. 

In addition: I cannot see an "Ubuntu" icon in Windows Start menue (I have seen this when I installed WSL2 Ubuntu on an admin account). How can I create a start icon for Ubuntu (probably after solving the issue above)?

Best regards

### Expected Behavior

I was expecting to start Uuntu in Power Shell

### Actual Behavior

Ubuntu cannot started in Power Shell as regular user without admin rights

**Comment by ARW-UBT** [comment] 2024-02-05 08:18
Issue solved with the following actions: 

In order to start WSL-Ubuntu on a Windows 2022 server, the following modifications work for me: 
- The users were added to the "Power Users" group
- A Windows Power Shell was started from the user account without administrator privileges
- WSL was updated by: `wsl --update` 
- Ubuntu was installed by: `wsl --install -d Ubuntu`

The Ubuntu start icon is now availabe in each user's start menu, Ubuntu can be started without any admin priviledges. 

If there are moderators in this microsoft open community, I would appreciate if somebody could check whether the procedure described above would be an appropriate way to install WSL for Windows Server 2022 regular users. 

Best,

**Comment by OneBlue** [comment] 2024-02-07 22:59
This is indeed the right way to start WSL non-elevated (start it from a non elevated shell). Closing since the issue is resolved.

**Closed** 2024-02-13 22:20 UTC
