### ISSUE TITLE
Compiler intermittently fails to find include files after April 2018 upgrade

### ISSUE THREAD

**Issue by pgerell** [Microsoft/WSL#3204] opened 2018-05-16 08:41 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:  When building my project using parallel jobs (`make -j8`) the compiler sometimes fails to find include files. If I restart `make` the file is found and the build continues only to fail at some other file. Eventually the project will build. If using `make` without the `-j`-option it always builds at first attempt. The file not found always resides on DrvFs, never on VolFs.

```[ 48%] Building CXX object shared/utils/CMakeFiles/utils.dir/Report.cpp.o
In file included from /home/pg/repos/tools/build/external_boost/boost_x/include/boost/type_traits/alignment_of.hpp:15:0,
                 from /home/pg/repos/tools/build/boost/optional/optional.hpp:36,
                 from /home/pg/repos/tools/build/boost/optional.hpp:15,
                 from /home/pg/repos/tools/src/shared/utils/Report.cpp:5:
/home/pg/repos/tools/build/boost/type_traits/intrinsics.hpp:16:10: fatal error: boost/type_traits/detail/config.hpp: No such file or directory

 #include <boost/type_traits/detail/config.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

* What's wrong / what should be happening instead: I did not have this problem before upgrading to the April 2018 edition. Others seem to have the same issue. [https://stackoverflow.com/questions/50206890/intermittent-random-file-not-found-errors-under-windows-subsystem-for-linux](url)

**Comment by therealkenc** [comment] 2018-05-16 10:02
**#2712** #2780  #2484 #2448 #2495 #1735. Your scenario might be addressed in [17655](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17655-skip-ahead). You are on '134.

**Comment by therealkenc** [comment] 2018-05-16 11:06
Calling this dupe #2712 because @heldchen [confirmed](https://github.com/Microsoft/WSL/issues/2712#issuecomment-389476949) it probably didn't manifest in 16299, which I assume is from whence you came. Bonne chance.

**Closed by therealkenc** 2018-05-16 11:06 UTC
