### ISSUE TITLE
Mixed language copy-paste. Output depends on current keyboard language and scrumbled output text.

### ISSUE THREAD

**Issue by Ioannischatzis** [Microsoft/WSL#1056] opened 2016-09-06 06:45 UTC
Mixed Language copy paste, pastes only the one of the languages.

I want to copy-paste mixed language text (Greek and English) from any source to Bash.
When I make a copy of two test strings 
String1: "This is a test. Αυτό είναι ένα τεστ."
String2: "This Αυτό is είναι a ένα test τεστ."
the result that is finally pasted depends on the keyboard language at use.

When the keyboard is in English the part of the string is pasted.
String1: "This is a test. ."
String2: "This is a test ."
When the keyboard is in Greek the part of the string is pasted.
String1: " . Αυτ εναι να τεστ."
String2: " Αυτ εναι να τεστ."

As we can see the output is also scrumbled in some cases in the case of Greek.

Microsoft Windows [Version 10.0.14393]

**Comment by Ioannischatzis** [comment] 2016-09-06 07:01
Mixed Language copy paste, pastes only the one of the languages.

I want to copy-paste mixed language text (Greek and English) from any source to Bash.
When I make a copy of two test strings 
String1: "This is a test. Αυτό είναι ένα τεστ."
String2: "This Αυτό is είναι a ένα test τεστ."
the result that is finally pasted depends on the keyboard language at use.

When the keyboard is in English the part of the string is pasted.
String1: "This is a test.    ."
String2: "This  is  a  test ."
When the keyboard is in Greek the part of the string is pasted.
String1: "   . Αυτ εναι να τεστ."
String2: " Αυτ  εναι  να  τεστ."

As we can see the output is also scrumbled in some cases in the case of Greek.
 
Microsoft Windows [Version 10.0.14393]

**Comment by sunilmut** [comment] 2016-09-06 16:40
@bitcrazed, @miniksa might have more information on this.

**Comment by ronicat** [comment] 2016-09-07 15:34
The information I have is that pasted text is definitely converted into key presses via your currently selected keyboard layout and then converted back to a string again when bash.exe reads it and that will influence what you see. 

I have filed this internally as 8787986 to track investigating what we can do about it.

**Comment by miniksa** [comment] 2016-09-07 15:35
The information I have is that pasted text is definitely converted into key presses via your currently selected keyboard layout and then converted back to a string again when bash.exe reads it and that will influence what you see. 
I have filed this internally as 8787986 to track investigating what we can do about it.

**Comment by wizardist** [comment] 2016-09-19 12:20
I can reproduce this issue for the Russian keyboard layout.

Source text in clipboard: `https://github.com/Microsoft/BashOnWindows/issues/1056`
Paste using the EN layout: `https://github.com/Microsoft/BashOnWindows/issues/1056` (good)
Paste using the RU layout: `://.////1056` (not good at all 🙈).

Typing using layouts other than EN works fine though.

Reproduced using **Version 1607 (OS Build 14393.187)** (Insider Program: Release Preview).

**Comment by ilyaigpetrov** [comment] 2017-02-01 10:08
What [uservoice](https://wpdev.uservoice.com) ticket should I star to prioritize this issue?

**Comment by miniksa** [comment] 2017-02-01 16:04
It looks like this issue was resolved internally because no one could reproduce it.

I just tried it myself against 14393 and 15024 and it doesn't reproduce for me in either case.

**Comment by ilyaigpetrov** [comment] 2017-02-01 16:14
I can reproduce it on `10.0.14393` 64x Pro:

1. Configure two keyboard layouts in the system with different characters (e.g. RU/EN).
2. Launch bash window.
3. Paste "foo-фи" with a right click of a mouse. (Compose another string for another layouts).
4. Depending on the current layout selected either "foo" (for EN) or "-фи" (for RU) will be pasted.

**Comment by miniksa** [comment] 2017-02-01 16:43
Oh. With Bash. Sorry, forgot where I was.

I can reproduce it against 14393, the July release. But it has already been resolved in the Insider Previews for the upcoming spring update.

**Comment by wizardist** [comment] 2017-02-02 08:30
@miniksa I confirm, at least on 14986 this issue cannot be reproduced - thus considered fixed.

**Comment by benhillis** [comment] 2017-02-02 16:15
@wizardist - Thanks for the confirmation!

**Closed** 2018-03-26 00:38 UTC
Labels: console, fixedincreatorsupdate
