### ISSUE TITLE
Internet connection crashes while using usb tethering internet share

### ISSUE THREAD

**Issue by cdecompilador** [microsoft/WSL#7557] opened 2021-10-17 08:04 UTC
### Version

Microsoft Windows [Version 10.0.22000.258] (Windows 11)

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Debian (it does not matter)

### Repro Steps

Connect phone with internet connection to pc (any kind of connection) and enable usb tethering. 
For simple `ping`s and `wget`s seems to keep up, but when you try some exhaustive connection like `sudo apt update` in less than 10 seconds the connection crashes, even in Windows, only unplugging solves the problem. Seems to be some adapter issues, when i try to get information about it while reproducing the issue all windows related to it start to not respond.

### Expected Behavior

To work and not crash internet connection.

### Actual Behavior

Crashes internet connection

### Diagnostic Logs

Showing the Windows device error logs, some weird error about ip invalid appear after crash. Ah also note that common wifi adapters and ethernet cable don't have this issue in my device, just usb tethering.

**Comment by McHulotte** [comment] 2021-11-21 11:41
Yes I confirm too,
I had the same issue, so now, I use WSL 1 waiting for it to be fixed

**Comment by foragerDev** [comment] 2022-01-16 17:13
I am getting the same issues, I am trying to upgrade some packages on WSL2 Ubuntu but as soon as I try to download something connection fails, the only way to fix it reconnect the phone, and this keeps happening.

**Comment by sequencerr** [comment] 2023-09-28 03:17
> Confirmed Network works fine until I try a git pull - then it always crashes at the same %
> 
> Same problem for sudo updates and the like.
> 
> The solution for now is to use portable hotspot or bluetooth tethering (haven't tried the latter, may not work).

Isn't solution you described it is what causing the issue?

**Comment by keith-horton** [comment] 2023-09-29 16:55
Please collect traces. What does it mean for a connection to crash? Does your machine bluescreen? Does the WSL container crash/go away?

Thanks!

**Comment by sequencerr** [comment] 2023-09-29 17:54
> Please collect traces. What does it mean for a connection to crash? Does your machine bluescreen? Does the WSL container crash/go away?
> 
> Thanks!

I think it's dupe of #5313

**Closed** 2024-10-03 12:19 UTC
Labels: network
