### ISSUE TITLE
Can't connect to WSL from more than 1 client

### ISSUE THREAD

**Issue by samuelpares** [microsoft/WSL#4785] opened 2019-12-26 17:55 UTC
* Your Windows build number:  
Microsoft Windows [versão 10.0.19536.1000]

* What you're doing and what's happening:
I can't connect to WSL2 using VSCode (Remote - WSL plugin) if I have already connected to the postgres through DBeaver, and vice verse, I mean, if I first connect to WSL2 in VSCode, I can't connect to postgres through DBeaver.
WSL2 - Ubuntu 18.04
Postgres 12 running at WSL2.
DBeaver on windows 6.2.5
It was working fine until last week.

![vscode connect](https://user-images.githubusercontent.com/51299360/71485291-2fbffe00-27ef-11ea-8f2b-42140147b8df.png)

![dbeaver connect](https://user-images.githubusercontent.com/51299360/71485313-377fa280-27ef-11ea-8d07-2acd977fd269.png)

* What's wrong / what should be happening instead:
Both connections should work, as it was last time I used.

* Strace of the failing command, if applicable: 
N/A

* For WSL launch issues, please [collect detailed logs]
N/A

**Comment by alekseymvt** [comment] 2019-12-27 08:32
Windows 10.0.19536.1000

* wsl --shutdown ✔
* run wsl2 (ubuntu 18.04) ✔
* service nginx/php7.4-fpm/postgress start ✔
* open local site in browser.  ✔
* open vscode ❌
![изображение](https://user-images.githubusercontent.com/22454101/71509180-7d924000-289b-11ea-8995-58bafcecfad5.png)

* wsl --shutdown ✔
* run wsl2 (ubuntu 18.04) ✔
* service nginx/php7.4-fpm/postgress start ✔
* open vscode ✔
* open local site in browser. ❌

**Comment by nickvlku** [comment] 2019-12-31 05:41
I'm having the same problem on my desktop running windows insider fast ring build:  19536.1000
My laptop is on the slow ring and seems to be fine.  build: 19041.1

**Comment by nikosdouvlis** [comment] 2020-01-01 16:09
I'm experiencing the same. This issue is also mentioned here: https://github.com/microsoft/vscode-remote-release/issues/2060 

Reverting back to 19041.1 seems to work, at least as a temporary workaround until a fix is ready.

To go back to a previous update, start -> control panel -> update & security -> recovery -> go back to the previous version of windows 10, and then follow the on screen instructions (takes about 5-10 minutes)

**Comment by benhillis** [comment] 2020-01-03 17:07
Very likely a dupe of #4769

**Comment by zoftdev** [comment] 2020-01-06 03:56
so sad I upgrade more than 10days so I can't recovery.

**Comment by therealkenc** [comment] 2020-01-26 21:32
> Very likely a dupe of #4769

Calling it #4769 for lack. Addressed 19548.

**Closed by therealkenc** 2020-01-26 21:32 UTC
