### ISSUE TITLE
WSL will allow the creation of reserved file names

### ISSUE THREAD

**Issue by brady1408** [microsoft/WSL#4544] opened 2019-09-25 13:25 UTC
Windows 10 Enterprise [18362.356]

When cloning a repository using git I was able to pull in a file named aux.tsx to my /mnt/c/workspace directory.  Afterword I was not able to delete the file using WSL, CMD, or Explorer.

The following list of reserved file names should not be created on the Windows file system through WSL.
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9

**Comment by DHowett-MSFT** [comment] 2019-09-25 19:36
Why shouldn't it?

**Comment by benhillis** [comment] 2019-09-25 19:41
@DHowett-MSFT - agreed.

@brady1408 - I am not able to reproduce your statement that the files is not able to be deleted via WSL, can you confirm?

```
root@BENHILL-DELL:/c/Users/benhill# echo foo > CON
root@BENHILL-DELL:/c/Users/benhill# rm CON
root@BENHILL-DELL:/c/Users/benhill# stat CON
stat: cannot stat 'CON': No such file or directory
```

**Comment by therealkenc** [comment] 2019-09-25 23:38
Ref #2689 fwiw. Can't reproduce here either.

![image](https://user-images.githubusercontent.com/7049700/65647218-d7d8e780-dfb2-11e9-9449-407926c7e848.png)

You can see the file from the win32 side. [You'd need to take [special measures](https://tpenguinltg.wordpress.com/2013/06/04/deleting-files-and-folders-with-reserved-names-on-windows/) to delete them over there, naturally.]

**Comment by therealkenc** [comment] 2019-09-27 23:42
Let's call this #2689 as LZ. That one probably could/should be closed by-design if the equivalent of ntfs-3g `-o windows_names` on our 9p, is, from a practical standpoint, not in the cards. [It isn't clear if anyone has a major use case on Real Linux for the option, but the flag probably isn't there for it's health either.]

**Closed by therealkenc** 2019-09-27 23:42 UTC
