### ISSUE TITLE
"docker build" and "docker pull" hang if sudo is not used.

### ISSUE THREAD

**Issue by fprin** [microsoft/WSL#5735] opened 2020-08-08 14:56 UTC
# Environment

```none
Windows build number: 10.0.20185.1000
Your Distribution version: Ubuntu 18.04
Whether the issue is on WSL 2 : Linux version 4.19.104-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Feb 19 06:37:35 UTC 2020]
```
I had also create a docker Diagnostic ID:  363079DD-B649-40C1-8B67-C6807E54EE35/20200808143903 (I think that it will give you more details of my current setup)

# Steps to reproduce

This problem wasn't happens to me before. I had done an update to Docker and I got this problem. 
1. Install docker in windows, I use this link -> https://hub.docker.com/editions/community/docker-ce-desktop-windows/, and installed the stable version.
![image](https://user-images.githubusercontent.com/61423717/89713046-9fd45c00-d95a-11ea-9f62-c94c1b445a7a.png)
2. Install docker as is mention in this link:  https://docs.docker.com/engine/install/ubuntu/
3. Open the dashboard of docker and make the corresponding configurations:
![image](https://user-images.githubusercontent.com/61423717/89713073-d6aa7200-d95a-11ea-84c1-0312a11e0db8.png)
![image](https://user-images.githubusercontent.com/61423717/89713088-e5912480-d95a-11ea-8157-646e41b86931.png)
4. I had follow this steps to be able to run `Docker` without `sudo`  https://docs.docker.com/engine/install/linux-postinstall/
![image](https://user-images.githubusercontent.com/61423717/89713295-7a485200-d95c-11ea-9e31-1fd57e2286b8.png)

#  Expected behavior

After the previous setup, this command should rpull the image without problems.
```bash
fprin@LAPTOP-UG6JIFUS:~$ docker --debug pull hello-world
Using default tag: latest
```

# Actual behavior

It is just hanging there.
```bash
fprin@LAPTOP-UG6JIFUS:~$ docker --debug pull hello-world
Using default tag: latest
```

I have to use sudo to actually pull the image.
```bash
fprin@LAPTOP-UG6JIFUS:~$ sudo docker --debug pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:49a1c8800c94df04e9658809b006fd8a686cab8028d33cfba2cc049724254202
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest
```

**Comment by fmichenaud** [comment] 2020-08-08 17:37
Duplicate of #5648

**Comment by fprin** [comment] 2020-08-08 19:17
running this command fixed my problem:
```
rm -fr ~/.docker/config.json
```
**This comment help me:** https://github.com/docker/for-win/issues/7990#issuecomment-670443735

@fmichenaud , it is rather a duplicate of https://github.com/docker/for-win/issues/7990, thanks for your comment!!!

**Closed** 2020-08-09 04:13 UTC
