### ISSUE TITLE
Cannot open WSL folder in Android Studio

### ISSUE THREAD

**Issue by Archisman-Mridha** [microsoft/WSL#9320] opened 2022-12-13 14:14 UTC
### Version

Microsoft Windows [Version 10.0.22623.875]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79.1

### Distro Version

Debian 11

### Other Software

Android Studio - Latest Version.

### Repro Steps

I am trying to create an android project using Android Studio and i am trying to use WSL as the storage location of my project.

### Expected Behavior

The android project should be created successfully with the files being stored in the WSL folder location i specified.

### Actual Behavior

It is showing that the WSL folder location is not writable. I guess it is some write operation denied error.

**Comment by OneBlue** [comment] 2022-12-13 22:09
Thanks for reporting this @Archisman-Mridha. Which folder are you trying to write to, what's the distribution default user, and what are the folder permissions ?

**Comment by Archisman-Mridha** [comment] 2022-12-14 05:45
> Thanks for reporting this @Archisman-Mridha. Which folder are you trying to write to, what's the distribution default user, and what are the folder permissions ?

I am trying to create a project in */home/archi/Documents/jetpack-compose-todo-app*. I am using Debian distribution and its default user is *archi*. I don't have any idea about the folder permissions.

**Comment by OneBlue** [comment] 2022-12-14 19:40
Can you share the output of `ls -la /home/archi/Documents/jetpack-compose-todo-app` and `whoami` from within WSL ?

**Comment by Archisman-Mridha** [comment] 2022-12-15 06:15
> Can you share the output of `ls -la /home/archi/Documents/jetpack-compose-todo-app` and `whoami` from within WSL ?

Output of `ls -la /home/archi/Documents/jetpack-compose-todo-app` -
```log
total 8
drwxr-xr-x 2 archi archi 4096 Dec 14 16:17 ./
drwxrwxrwx 4 archi archi 4096 Dec 14 17:55 ../
```

And output of `whoami` -
```log
archi
```

**Comment by Archisman-Mridha** [comment] 2022-12-21 19:02
> Thanks @Archisman-Mridha. The permissions look good to me. What about `/home/archi/Documents/` ?
> 
> Also which exact error do you get ?

![Screenshot (1)](https://user-images.githubusercontent.com/36650528/208983140-cadf77bf-4edb-4589-b723-6ae0e4461c08.png)

**Comment by OneBlue** [comment] 2022-12-27 20:10
> > Thanks @Archisman-Mridha. The permissions look good to me. What about `/home/archi/Documents/` ?
> > Also which exact error do you get ?
> 
> ![Screenshot (1)](https://user-images.githubusercontent.com/36650528/208983140-cadf77bf-4edb-4589-b723-6ae0e4461c08.png)

Can you create a new folder with the Windows explorer if you navigate to that path ?

**Comment by Archisman-Mridha** [comment] 2022-12-27 20:29
> > > Thanks @Archisman-Mridha. The permissions look good to me. What about `/home/archi/Documents/` ?
> > > Also which exact error do you get ?
> > 
> > ![Screenshot (1)](https://user-images.githubusercontent.com/36650528/208983140-cadf77bf-4edb-4589-b723-6ae0e4461c08.png)
> 
> Can you create a new folder with the Windows explorer if you navigate to that path ? 

Yes i can

**Comment by OneBlue** [comment] 2022-12-27 20:31
Thank you @Archisman-Mridha. In that case the issue is probably within Android studio so I'd recommend reporting it [here](https://developer.android.com/studio/report-bugs).

Closing since this is not a WSL issue.

**Closed by OneBlue** 2022-12-27 20:31 UTC
