### ISSUE TITLE
Smart App Control blocking some or all features of WSL and Kali Linux app 

### ISSUE THREAD

**Issue by tgithub8** [microsoft/WSL#9596] opened 2023-02-06 14:43 UTC
### Version

Microsoft Windows [Version 10.0.22621.1194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.79

### Distro Version

Kali Linux

### Repro Steps

1. Perform a clean install of Windows 11 22H2 and change Smart App Control from Evaluation Mode to "On".
2. Install Windows Subsystem for Linux Preview from the Microsoft Store app or Command Prompt (run as admin).
3. Install Kali Linux (or any other WSL distro) from the Microsoft Store app or Command Prompt (run as admin).
4. Attempt to run the distro or run any wsl.exe command

### Expected Behavior

WSL commands execute without errors.
Normal use of Kali Linux (or any other WSL distro) app and its terminal.

### Actual Behavior

![Screenshot 2023-02-05 214154](https://user-images.githubusercontent.com/112350103/216979785-a05aedcd-e541-4d06-8655-e70343ccf5a8.jpg)
![Screenshot 2023-02-05 214247](https://user-images.githubusercontent.com/112350103/216979826-5befe6e5-5fb9-43f5-b746-14a5ef4b075d.jpg)
![Screenshot 2023-02-05 214328](https://user-images.githubusercontent.com/112350103/216979866-1220a9c0-b1d3-4eb3-8d17-01fd11a82010.jpg)

Able to use Kali Linux on the WSL terminal but Smart App is still blocking some features and blocking the Kali Linux app and Command Prompt access. Smart App will probably block other WSL distros.

### Diagnostic Logs

https://aka.ms/AAjhoj4

**Comment by OneBlue** [comment] 2023-02-07 22:25
Thanks for reporting this @tgithub8. Unfortunately this is by design given that [Smart App Control has a block rule for wsl.exe](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules) 

Closing since this is not something that can be fixed from the WSL side.

**Closed by OneBlue** 2023-02-07 22:25 UTC
