### ISSUE TITLE
WSL2: allow direct access to block devices

### ISSUE THREAD

**Issue by wmertens** [microsoft/WSL#5135] opened 2020-04-25 14:38 UTC
**Is your feature request related to a problem? Please describe.**

* I dual-boot windows and Linux, and I wish to share its partition between WSL2 and Linux
* I attach USB drives with exotic filesystems to my computer, and I wish to mount them
* I develop Linux systems, and I wish to directly access disks to set up partition tables etc

**Describe the solution you'd like**
I would like to make any block device of my choosing available to a certain WSL2 container so that it shows up under /dev as a block device that can be read from and written to.

**Describe alternatives you've considered**
Install StarWind SAN Free and serve the block device over iSCSI. This probably works, but is extremely cumbersome, requiring a license (free avalailable), 300MB of disk space, juggling with IP adresses etc.

**Additional context**
This request is a refinement of #689, starting fresh, only requesting low-level block access from a WSL2 container.

**Comment by sirredbeard** [comment] 2020-04-27 14:52
This is a duplicate of #689.

**Closed** 2020-04-27 15:05 UTC
