### ISSUE TITLE
Vmmemwsl - High CPU Usage

### ISSUE THREAD

**Issue by stumarr** [microsoft/WSL#9081] opened 2022-10-28 14:02 UTC
### Version

Microsoft Windows [Version 10.0.22000.1098] / WSL version: 0.70.4.0

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.68.1

### Distro Version

20.04.5 LTS

### Other Software

n/a

### Repro Steps

After computer wakes up from sleep, wsl does not respond. 

### Expected Behavior

WSL to respond after waking up computer from sleep without rebooting.

### Actual Behavior

Windows responds slowly and checking task manager, CPU usage for the vmmemwsl process is spiking.
![high-cpu-wsl2](https://user-images.githubusercontent.com/77361472/198625867-2c8db7d3-e8f6-4305-b634-183c1c7a0b37.jpg)
Attempting to kill the process from task manager does not work as I get 'Access denied', even if I run task manager as Administrator. Same result from the command prompt. When I run 'wsl.exe --shutdown' from the command prompt, it just hangs and never completes. The only way to recover WSL is to reboot. I've tried a fix that I found in a forum that suggested adding the lines below to the .wslconfig, but still does not resolve the issue.
[wsl2]
guiApplications=false

I was unable to upload the log in the 'Diagnostic Logs' section below so I placed it here.
[WslLogs-2022-10-28_08-40-49.zip](https://github.com/microsoft/WSL/files/9889007/WslLogs-2022-10-28_08-40-49.zip)

**Comment by Perksey** [comment] 2022-10-28 17:03
I've also been getting this recently! So glad it's not just me.

**Comment by LiaraAlis** [comment] 2022-10-30 23:02
I think this is a duplicate of https://github.com/microsoft/WSL/issues/6982.
I also have this issue and still not resolved.

**Comment by stumarr** [comment] 2022-10-31 13:47
Not sure if you were able to send logs of the issue, but I was able to capture them while the issue was happening. Hopefully, we can get a solution. It's frustrating, as it happens almost daily.

Kind Regards,

Stu Marroquin


Stu Marroquin
Information Management Senior Specialist
The Walt Disney Account
Atos North America
407-619-2498
***@***.******@***.***>
(DISC) 5601 Center Drive
Orlando, FL 32830
www.na.atos.net<http://www.na.atos.net/>

[Atos]

This e-mail and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it. As its integrity cannot be secured on the Internet, the Atos group liability cannot be triggered for the message content. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted

**Comment by Perksey** [comment] 2022-10-31 14:21
Yep, happens whenever I hibernate my laptop which is very often!

**Comment by heigum** [comment] 2022-11-01 07:48
I also start every day with this issue if I forget to shutdown wsl before I end my day.

**Closed** 2022-11-10 23:59 UTC

**Comment by asalaneck** [comment] 2023-01-17 17:18
I am still getting this issue, has it been resolved?

**Comment by LOuroboros** [comment] 2023-01-31 22:00
I just had this same problem happen to me. This issue didn't even let me boot up WSL again, so I was forced to reboot my PC.
Relevant specs:
> WSL version: 1.0.3.0
> Kernel version: 5.15.79.1
> WSLg version: 1.0.47
> MSRDC version: 1.2.3575
> Direct3D version: 1.606.4
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22621.1194

**Comment by tcarolan** [comment] 2023-02-03 18:58
I experience this same issue. Getting my computer back from hibernation is impossible. Thought it was hardware, but its been VmmemWSL the whole time.

**Comment by hima-gadupudi** [comment] 2023-02-07 17:38
Same problem as @tcarolan mentioned.  Getting my computer out of hibernation everyday morning is impossible. VmmemWSL is taking too much CPU

**Comment by obar1** [comment] 2023-02-12 09:08
anybody tried already playing with ` .wslconfig` to mitigate ?
https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file
like disabling GUI if not needed and set processors param?

**Comment by YAmikep** [comment] 2023-03-15 02:37
> anybody tried already playing with ` .wslconfig` to mitigate ? https://learn.microsoft.com/en-us/windows/wsl/wsl-config#example-wslconfig-file like disabling GUI if not needed and set processors param?

@obar1 I limited processors to half of what I have but then I have WSL sucking 50% of my cpu anyway which slows down everything...
As for the GUI, I am using it so did not try to disable it.

**Comment by theritz1990** [comment] 2023-04-18 21:39
need to run cmd as admin and type "wsl --shutdown" don't even need to close docker if you are running it. it should immediately throttle back. do a system restart and you should be good.

**Comment by Sangresz** [comment] 2023-06-02 20:51
I dont know if my problem relates to this issue or not but i have Vmmemwsl process active and i can't even run `wsl --shutdown` because it just hangs there
