### ISSUE TITLE
Share directory between distros

### ISSUE THREAD

**Issue by giggio** [microsoft/WSL#5177] opened 2020-05-06 21:49 UTC
**Describe the solution you'd like**
In WSL2, I'd like to be able to share a directory between distros. I can see it is possible, as Docker for Windows is doing it by creating devices (`/dev/sdd`, `/dev/sdc` on my system, using ext4) and mounting them on `/mnt`.

I see 2 options:

1. A data drive, that does not belong to any distro and is shared by the ones I want.
2. A directory could belong to a distro, and be shared with others.

You could also try to change something on the namespaces and maybe use symbolic links between distros, that would be good enough, and wouldn't need mounting. I'm not sure how feasible that would be. I don't really care about the implementation.

**Describe alternatives you've considered**
I can't see a clear alternative.

**Additional context**
My use case it that I'd like to share `/home/user`. It would save space and help a lot.

**Comment by beltaurus** [comment] 2020-05-06 22:08
I currently already share a directory available on the Windows platform, as my home directory for the different distros I have.
1. Somewhere in my Windows 10 infrastructure, I have a `...WSL_HOME/<user>` directory.
2. Note that this directory is going to be on one of my drives (e.g. C:), and therefore show up in WSL (e.g. /mnt/c)
3. In my WSL distros, I bind that directory to a directory in my WSL infrastructure (in the `/etc/fstab` file):
```
#   /etc/fstab
...
C: /mnt/c drvfs rw,noatime,metadata,uid=1000,gid=1000,umask=022,fmask=011
/mnt/c/.../WSL_Home /<user> /home/<user> drvfs bind
```

This requires that the `/home/<user>` directory is empty..., so you need to move all the files and directories from your original WSL created home directory, to the mounted location in Windows first...

You could also bind this directory to any other directory (e.g. /mnt/h), and then change your `/etc/passwd` file to make that directory your home directory...

**Comment by onomatopellan** [comment] 2020-05-06 22:36
The second option is actually implemented. You can create a directory in `/mnt/wsl/`, mount whatever you want on it and it will appear on every distro installed.

For example, just adding this to my Ubuntu ~/.profile it automatically mounts on launch an external Alpine /home folder that appears in every distro under `/mnt/wsl/Alpine`.
```bash
# mount external /home folder from Alpine distro
if [ ! -d /mnt/wsl/Alpine ]; then
    mkdir /mnt/wsl/Alpine
    wsl.exe -d Alpine mount --bind /home/ /mnt/wsl/Alpine/
fi
```

**Comment by beltaurus** [comment] 2020-05-06 23:43
I was not aware of the second option, thanks @onomatopellan !
I did now find https://github.com/microsoft/WSL/issues/4577, which explains why I'm not aware of it :-).
Also, it seems that this crossDistro option is only available for WSL2?
I'm still stuck with WSL...

**Comment by onomatopellan** [comment] 2020-05-07 00:01
@beltaurus Yes, it's a WSL2 only thing since all the running distros in WSL2 are just containers on a single kernel/lightweight VM.

**Comment by giggio** [comment] 2020-05-07 16:45
I was not aware of this functionality, @onomatopellan, very cool.
Unfortunately, /mnt/wsl uses tmpfs, so when wsl shutsdown you loose everything that was there. What I could do is when Ubuntu (my main distro) comes up, it adds a symlink from `/home/user` to `/mnt/wsl/homeuser/`, and when OpenSuse comes up, it does the oposite, it mounts from `/mnt/wsl/homeuser/` to `/home/user`.
The problem is that if OpenSuse starts before Ubuntu, there will be nothing at `/mnt/wsl/homeuser/`.
So it kinda works, but there are issues.

**Comment by beltaurus** [comment] 2020-05-07 17:28
@giggio : Can you use my suggestion then? Or are there other obstacles with sharing a given windows directory over the different distros?

**Comment by onomatopellan** [comment] 2020-05-07 18:17
@giggio Correct, it's tmpfs but you only loses the folder used as mount point. In my case I can modify the Alpine home files from Ubuntu and, of course, the changes are preserved after wsl shutdown.

I can understand why this feature is undocumented and so far it's only used by Docker devs. Things can become dangerous fast, especially with different user file permissions. But it's still very useful and the most important thing to know is this:

 **Every time you launch a distro it attaches that distro's VHDX to the running WSL2 VM as a new sdx device.**

You can observe that with `sudo lsblk` for example. After knowing that it's the user's decision when and where to mount them although `/mnt/wsl/` will still be the only folder truly shared by all distros.

**Comment by giggio** [comment] 2020-05-07 23:21
Yes, I'm not using Windows because it's slow at the moment.

I don't like that I have to have another distro running to be able to mount. There should be a way to mount a device to multiple distros, a device that does not belong to any of the distros.
They are just separated by namespaces, they could share that.
For example, I create a device (using wsl.exe), and it is auto mounted to any distro that starts up.

**Comment by onomatopellan** [comment] 2020-05-09 09:17
@giggio It looks like the Docker team already asked for something similar https://github.com/microsoft/WSL/issues/4730.

Something like that solution would be great. @benhillis

**Comment by beardedeagle** [comment] 2020-07-28 20:12
@onomatopellan I seem to only be able to mount a single distro with this method. Do we happen to know if this by design?

    if [ ! -d /mnt/wsl/NewishUbu ]; then
        mkdir /mnt/wsl/NewishUbu
        wsl.exe -d NewishUbu mount --bind /home/beardedeagle/ /mnt/wsl/NewishUbu/
    fi

    if [ ! -d /mnt/wsl/OldUbu ]; then
        mkdir /mnt/wsl/OldUbu
        wsl.exe -d OldUbu mount --bind /home/beardedeagle/ /mnt/wsl/OldUbu/
    fi

which produces the following:

    mount: /mnt/wsl/OldUbu/: mount point does not exist.

**Comment by onomatopellan** [comment] 2020-07-28 21:14
@beardedeagle are you sure both distros are WSL2? If OldUbu is WSL1 it won't work since there is no `/mnt/wsl` in WSL1.

**Comment by beardedeagle** [comment] 2020-07-29 02:13
@onomatopellan yup, they are all wsl2:

    PS C:\Windows\System32> wsl -l -v
      NAME                   STATE           VERSION
    * Ubuntu                 Running         2
      OldUbu                 Stopped         2
      NewishUbu              Stopped         2

To clarify both `NewishUbu` and `OldUbu` started their life as wsl1 containers on another machine. I imported them as wsl2 though.

**Comment by onomatopellan** [comment] 2020-07-29 09:45
@beardedeagle  I just tried with two distros and it works. I think the mount command should be called by the root user which is default in Alpine but not in Ubuntu.
Try with this:
`wsl.exe -d OldUbu -u root mount --bind /home/beardedeagle/ /mnt/wsl/OldUbu/`

**Comment by therealkenc** [comment] 2020-09-01 22:34
The shared `/mnt/wsl` directory behavior mentioned in #4577 ([message](https://github.com/microsoft/WSL/issues/4577#issuecomment-545192865)) shipped to Insiders sometime last fall and landed in 20H1 aka 2004 aka 19041.

Creating a bind mount inside a Ubuntu-18.04 instance would look something like...
```
$ sudo mkdir /mnt/wsl/Ubuntu-18.04
$ sudo mount --bind / /mnt/wsl/Ubuntu-18.04  # share all of /
```

... but you can pick whatever you want for the source and target of the mount, so long as the target is under `/mnt/wsl`. The feature is only available in WSL2.

/fixed 19041

**Closed by therealkenc** 2020-09-01 22:34 UTC

**Comment by giggio** [comment] 2020-09-01 23:00
@therealkenc this issue has not been addressed.

Yes, you can share a drive from a distro to another, but I don't want that. I want a drive that is not part of any distros, so I can add my home directory there and use it in any distro that boots first. I don't want to have to boot them in order.

Also, please see this comment with other issues: https://github.com/microsoft/WSL/issues/5177#issuecomment-625368935

It is not possible to do what I need with today's implementation.

**Comment by therealkenc** [comment] 2020-09-02 00:46
That's #689. [If this issue was interpreted as "I want a drive that is not part of any distros" contrast issue title "Share directory between distros" it wouldn't have survived a dupe-closed in May.]

> Unfortunately, /mnt/wsl uses tmpfs, so when wsl shutsdown you loose everything that was there. 

Yeah, there's that. Feel free to open a new feature request "persist /mnt/wsl mountpoints" or somesuch.

**Comment by justinmchase** [comment] 2021-05-02 03:35
In my default distro (which was upgraded from wsl1 a long time ago) I do not have the folder `/mnt/wsl`. I have no idea why not.

Simply creating the folder and then following the instructions in this thread do not seem to work, the mounted folder is not available in other distros.

Is there a way to properly repair the distro such that the /mnt/wsl folder is mounted properly?

**Comment by onomatopellan** [comment] 2021-05-02 11:20
@justinmchase Make sure you are in a WSL2 distro with `wsl.exe -l -v` and you have latest linux kernel installed with `uname -a`. Running `mount` you should see something like `tmpfs on /mnt/wsl type tmpfs (rw,relatime)`

**Comment by justinmchase** [comment] 2021-05-03 14:35
In the end to fix it I had to completely uninstall Ubuntu and then re-install it from the store. This created a new distro which had the /mnt/wsl folder functioning correctly.

I have no idea how I got in that bad state but it was possibly an error in the upgrade process and I never noticed the issue until now.

**Comment by horror-proton** [comment] 2022-09-09 03:55
But what if one (or both) of them are WSL1, is there a better way of sharing their filesystems. I guess mounting over network is the only option, but any suggestions on which one to use, is it possible to have something like sshfs but piping file through `wsl.exe` instead of the real `ssh`[^1], it could be annoying to have a daemon running in all of the WSL instances.

[A related stackexchance question](https://superuser.com/questions/1709190)

[^1]: I'm not sure if that is how sshfs works

**Comment by didibus** [comment] 2023-07-10 06:42
I'm not very Linux saavy, so how to I make it so my home dir is shared between my WSL 2 distros? Without it being a slow windows mount?

**Comment by maica1** [comment] 2024-09-12 02:04
> In my default distro (which was upgraded from wsl1 a long time ago) I do not have the folder `/mnt/wsl`. I have no idea why not.
> 
> Simply creating the folder and then following the instructions in this thread do not seem to work, the mounted folder is not available in other distros.
> 
> Is there a way to properly repair the distro such that the /mnt/wsl folder is mounted properly?

I had this problem too, I actually found out that the bind mount were in the wrong place, issuing `mnt | grep wsl` showed me that the podman sockets were being mounted under /wsl/podman-sockets/machine-default

this happens because I had the [automount option](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings) configured to / on my /etc/wsl.conf on this distro, so keep your eyes on this config.

Anyway you can either revert the default path for wsl mounts ou you can discover where the sock is being mounted and point the podman connection to the right place.

After solving this I was able to run devcontainers in vscode, if anyone came here with this problem
