### ISSUE TITLE
Racket 5.3.6 segfaults

### ISSUE THREAD

**Issue by timfel** [Microsoft/WSL#900] opened 2016-08-15 12:26 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  Attempting to run racket v5.3.6 segfaults
- Expected results
  It should startup and give me a REPL
- Actual results (with terminal output if applicable)

``` bash
~/Dev/RSqueak system ❰git:(tim/ruby-plugin)❱ ✔  racket
Welcome to Racket v5.3.6.
SIGSEGV SI_KERNEL SI_CODE 128 fault on addr 0x7f6f5b4344b0 sent by kernel
Aborted (core dumped)
~/Dev/RSqueak system ❰git:(tim/ruby-plugin)❱ ✘  
```
- Your Windows build number
  14393.67
- Steps / commands required to reproduce the error

``` bash
sudo apt-get install racket && racket
```

**Comment by stehufntdev** [comment] 2016-08-16 19:15
Thanks for reporting the issue.  Can you please share out a strace of the racket command?  Was hoping to see if there were any errors before the segfault indicating missing functionality.

**Comment by timfel** [comment] 2016-08-16 20:59
Sure, it's attached.
[racket.txt](https://github.com/Microsoft/BashOnWindows/files/421278/racket.txt)

**Comment by stehufntdev** [comment] 2016-08-16 23:06
Great, thanks!  Going through the strace I'm not seeing any obvious failures around the time of the SIGSEGV so we'd have to do some more debugging to understand where WSL diverges from native Linux.  Best way to communicate the desire here would be to go vote on the [User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) so we can prioritize the requests.

**Comment by stehufntdev** [comment] 2016-08-17 02:11
I did a quick comparison here against native Ubuntu, and racket seems to checking for SIGSEV with the SEGV_ACCERR code (and patching them up) but WSL is reporting SIGSEV with SI_KERNEL.  We are tracking improving our conversion from exception to signals but please give feedback on the user voice page.

**Comment by lateau** [comment] 2016-08-23 14:01
If someone has a same problem please vote this feedback ;)

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15686589-racket-does-not-work

**Comment by Hayate84** [comment] 2016-10-03 04:59
how to solve this?

**Comment by bmastenbrook** [comment] 2016-10-28 22:26
There's a second issue blocking Racket from working. If you build racket with --enable-cgcdefault, it will use a different garbage collector that does not rely on accurate siginfo, but running Racket will still hang. This is because racket is creating an epoll descriptor, then using the poll syscall to wait on the epoll set and on another fd. Per `epoll(7)` this ought to work, but WSL does not seem to handle it correctly; the poll syscall never returns. You can see this most easily by building minimal Racket (start with the prebuilt packages source distribution) and then running `./racket/racketcgc` in the build directory under strace:

```
epoll_ctl(6, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=0}}) = 0
epoll_wait(6, [], 1, 0)                 = 0
epoll_wait(6, [], 1, 0)                 = 0
poll([{fd=6, events=POLLIN}, {fd=3, events=POLLIN}], 2, -1
```

You should be able to make the epoll set readable by entering a line of input, but the poll syscall never returns.

**Comment by misenesi** [comment] 2016-12-02 23:58
@bmastenbrook I have recently fixed an [epoll behavior](https://github.com/Microsoft/BashOnWindows/issues/1068) that sounds like it could be related to the hang you are seeing.

The actual exception handling and accurate siginfo is something that we are tracking internally, I just haven't got around to fixing that yet.

**Comment by misenesi** [comment] 2016-12-29 23:49
I have a fix under review for SIGSEGV handling. With this one and the epoll one racket gets all the way to the start prompt. It doesn't receive input. The reason for that seems to be related to missing Asynchronous I/O support for TTY, which happens to be what I am also working on.

**Comment by misenesi** [comment] 2016-12-30 20:11
I have checked in the fix for SIGSEGV handling. I am looking into the AIO support next.

**Comment by pierrebeaucamp** [comment] 2017-05-12 15:47
Just installed Racket v6.8 from the official racket ppa. I can confirm that the repl starts up correctly, but it's not receiving any input. (Insider preview, Slow Ring, Build 15063.138)

**Comment by sleibrock** [comment] 2017-06-15 15:36
Using Racket 6.9 and the REPL seems to not want to process any input whatsoever. It will handle Ctrl+C breaks properly but entering anything, the REPL does not process it.

Using Racket's runtime will run programs fine but the REPL is unresponsive.

**Comment by benhillis** [comment] 2018-06-12 20:33
Just tried that on 1803 and racket works as expected.

**Closed by benhillis** 2018-06-12 20:33 UTC
Labels: bug
