### ISSUE TITLE
The remote procedure call failed

### ISSUE THREAD

**Issue by dualer** [microsoft/WSL#9796] opened 2023-03-16 02:36 UTC
### Windows Version

 10.0.22623.1037

### WSL Version

 1.1.5.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.1

### Distro Version

Ubuntu-18.04

### Repro Steps

Open WSL

### Expected Behavior

Run correctly

### Actual Behavior

Say "The remote procedure call failed"

**Comment by clearly-a** [comment] 2023-03-16 04:13
me too

**Comment by Stark-X** [comment] 2023-03-16 08:41
same here 

- 1.1.5 WSL from MicrosoftStore 
- Windows version: 22H2, 19045.2728 

when I launch the wsl, it return "The remote procedure call failed"

**Comment by EricFengFuuuu** [comment] 2023-03-16 09:54
PS C:\Users\ingre> wsl -v
WSL 版本： 1.1.5.0
内核版本： 5.15.90.1
WSLg 版本： 1.0.50
MSRDC 版本： 1.2.3770
Direct3D 版本： 1.608.2-61064218
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.1413
PS C:\Users\ingre> wsl
远程过程调用失败。
Error code: Wsl/Service/RPC_S_CALL_FAILED
PS C:\Users\ingre>

**Comment by EricFengFuuuu** [comment] 2023-03-16 09:56
This happened after updating wsl yesterday, how to solve it?

**Comment by zzy9001** [comment] 2023-03-16 12:06
> This happened after updating wsl yesterday, how to solve it?

Reinstall version 1.1.3 temporarily solve this problem for me

**Comment by dualer** [comment] 2023-03-16 14:24
> > This happened after updating wsl yesterday, how to solve it?
> 
> Reinstall version 1.1.3 temporarily solve this problem for me
It's solved, thank you

**Comment by dualer** [comment] 2023-03-16 14:25
> > This happened after updating wsl yesterday, how to solve it?
> 
> Reinstall version 1.1.3 temporarily solve this problem for me
It's solved, thank you

**Comment by benhillis** [comment] 2023-03-16 16:10
If somebody is in this state, could you please collect a dump of wslservice.exe? I'm not seeing this crash locally, might be something specific to your locale.

(As admin)
1. sc stop wslservice
2. sc start wslservice
3. windbg -p <pid>
4. in the debugger, "g" to continue.
5. run wsl command
6. Observe crash
7. .dump /ma <path_to_dump>
8. zip and upload dump

**Comment by mirror-kt** [comment] 2023-03-16 17:25
Hi!
I reproduced it in my environment, so I share the information below.
It is a ja_JP environment.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/43880251/225698062-677db99f-1ba3-4a8e-a432-e1c61ff7af11.png">

https://drive.google.com/file/d/1R3dbDfOsm2Zbk_KngCu3V0tKodj3-K2M/view?usp=sharing

**Comment by benhillis** [comment] 2023-03-16 20:13
@mirror-kt - thanks for the dump. I've verified this is an issue we fixed and will be releasing in 1.1.6 soon. In the meantime I would suggest clearing the contents of your `%userprofile\.wslconfig` file, because there are some invalid values in there (namely "localhostForwarding").

**Comment by benhillis** [comment] 2023-03-16 20:14
I've removed the link to your dump since I have what I need. Thanks!

**Comment by rui-qi-kg** [comment] 2023-03-17 19:29
After locating the .wslconfig file in `C:\Users<username>`, and after removing the settings below, it returned to normal.
```
[system-distro-env] 
WESTON_RDP_MONITOR_REFRESH_RATE=144
```
![image](https://user-images.githubusercontent.com/106638022/226000873-a64a29f8-c17c-41bc-a3f1-db40238049c6.png)

**Comment by the-exile-110** [comment] 2023-03-17 19:31
After locating the `.wslconfig` file in `C:\Users<username>`, and after removing the settings below, it returned to normal.

```
[system-distro-env] 
WESTON_RDP_MONITOR_REFRESH_RATE=144
```

![image](https://user-images.githubusercontent.com/45879990/226002195-9166eef8-c31d-478b-9837-1f38b76e0d68.png)

**Comment by EricFengFuuuu** [comment] 2023-03-18 15:41
> 在 中找到文件并删除以下设置后，它恢复正常。`.wslconfig``C:\Users<username>`
> 
> ```
> [system-distro-env] 
> WESTON_RDP_MONITOR_REFRESH_RATE=144
> ```
> 
> ![image](https://user-images.githubusercontent.com/45879990/226002195-9166eef8-c31d-478b-9837-1f38b76e0d68.png)

But there is no such content in my .wslconfig file
![image](https://user-images.githubusercontent.com/42857023/226115772-fe243c28-97e8-48fe-a4ba-1979b79a1466.png)

**Comment by the-exile-110** [comment] 2023-03-18 15:44
@EricFengFuuuu 

Have you tried deleting unnecessary settings?

**Comment by pilishen** [comment] 2023-03-19 06:12
```
[network]
generateResolvConf = false
```

in my case, delete this part from my config works, really weird

**Comment by Stark-X** [comment] 2023-03-20 03:30
```
[user]
default=stark
```
I delete this section solve my problem.

After taht, I try to put it back, the WSL will failed to start in several seconds.

**Comment by dawnli-github** [comment] 2023-03-22 11:01
I had the same problem, open the ".wslconfig", then opening the WSL once after commenting (deleting) the "swapFile", then recovering the entry and opening the WSL again.

**Comment by Tokimekis** [comment] 2023-03-22 12:31
> 

me too，thanks!

**Comment by Tokimekis** [comment] 2023-03-22 12:57
> delete "swapFile" is work for me
me too,thanks!

**Comment by xmapst** [comment] 2023-03-23 02:48
empty ".wslconfig" worked for me

**Comment by benhillis** [comment] 2023-03-29 22:34
Fixed with https://github.com/microsoft/WSL/releases/tag/1.1.6.

**Closed by benhillis** 2023-03-29 22:34 UTC
Labels: fixinbound

**Comment by PaxtonPenguin** [comment] 2024-04-26 01:41
this is still happening to me, some how
