### ISSUE TITLE
Running a simple JS file via "Run and Debug" takes 3 minutes

### ISSUE THREAD

**Issue by henryfoster** [microsoft/WSL#11001] opened 2024-01-09 19:42 UTC
### Windows Version

Microsoft Windows [Version 10.0.22635.2921]

### WSL Version

2.1.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.137.3-1

### Distro Version

Ubuntu 22.04

### Other Software

Visual Studio Code 1.85.1 with WSL extension v0.81.8

### Repro Steps

1. create a folder with a .js file
2. add some code for example : `console.log("test");`
3. go to run tab and click start debugging
4. select node
5. debug console opens with a command that should start your code but nothing happens after: /home/edu/.nvm/versions/node/v18.17.1/bin/node ./two-sum.js
6. after around 3 minutes it prints "test" to the console (executes the code in general)

### Expected Behavior

1. it should not take 3 minutes to execute a print statement

### Actual Behavior

1. after around 3 minutes it prints "test" to the console

![image](https://github.com/microsoft/WSL/assets/16246186/a3504de1-6dd6-4e9e-8947-16b373569ca6)

after 3 minutes:

![image](https://github.com/microsoft/WSL/assets/16246186/e83773a7-ecb1-4ede-96ab-1211628bcb28)

If I just run the same command that VScode runs in the terminal, I get the result immediately. So the node and the general setup works fine. It happens only if I run the code via "RUN and Debug"

Also, if I use the same project setup on Linux native or windows it works only in VSCode+WSL I have this issue.

### Diagnostic Logs

/home/edu/.nvm/versions/node/v18.17.1/bin/node ./two-sum.js
test

**Comment by OneBlue** [comment] 2024-01-09 22:30
Do you know what's taking time here ? If files under /mnt need to be accessed when this program executes that could explain the delay, otherwise you'd probably need to strace your program (or its interpreter) to root cause this. 

Closing since there isn't enough information to root cause

**Closed by OneBlue** 2024-01-09 22:30 UTC

**Comment by henryfoster** [comment] 2024-01-10 08:36
Hi @OneBlue,
you don't need to close this report right away. I filled all the required fields in the form. I'm happy to provide any meaningful information to you if you can tell me what you need.

> If files under /mnt need to be accessed when this program executes that could explain the delay

The whole program is just one line printing hello world in javascript it does not access any files.

> otherwise you'd probably need to strace your program (or its interpreter) to root cause this.

You probably mean I need to strace VSCode while executing? Cause the one line of JS code executes in ms if calling the interpreter via the terminal directly. The problem only occures when executing via VSCode "Run and Debug" also this seems not to be a VSCode issue cause it works fine on a system without WSL.
