### ISSUE TITLE
Win32 interop GUI executable produces unexpected console output only when backgrounded

### ISSUE THREAD

**Issue by 0xabu** [microsoft/WSL#8497] opened 2022-06-10 20:03 UTC
### Version

Microsoft Windows [Version 10.0.22000.675]

### WSL Version

- [X] WSL 2
- [X] WSL 1

### Kernel Version

N/A

### Distro Version

N/A

### Repro Steps

```
C:\src\tmp>type guihello.c
#include <windows.h>
#include <stdio.h>

int APIENTRY WinMain(HINSTANCE hInst, HINSTANCE hInstPrev, PSTR cmdline, int cmdshow)
{
    printf("Hello world\n");
    return 0;
}

C:\src\tmp>cl guihello.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31328 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

guihello.c
Microsoft (R) Incremental Linker Version 14.32.31328.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:guihello.exe
guihello.obj

C:\src\tmp>guihello.exe

C:\src\tmp>wsl -e /bin/sh
$ ./guihello.exe
$ ./guihello.exe &
$ Hello world
```

### Expected Behavior

 * Running a Win32 GUI program via interop should produce the same output regardless of whether launched in the background or foreground.
 * (Probably) running a Win32 GUI program via interop should produce the same console output as from CMD.

### Actual Behavior

When launching a GUI executable backgrounded, its console output unexpectedly appears in my shell. I first noticed this as https://github.com/sumatrapdfreader/sumatrapdf/issues/2710, but it's clearly more general, and GUI apps do not expect their console output to appear if they didn't create a console.

**Comment by elsaco** [comment] 2022-06-11 18:23
Linux console has `stty -tostop` by default.  To prevent console output from `bg` jobs set `stty tostop` before running the app.

**Comment by 0xabu** [comment] 2022-06-11 18:59
@elsaco I believe that's unrelated. My bug is that the process produces output when started backgrounded, and not when started in the foreground. I suspect the bug is on the Win32 interop side, not in the shell / job control.

**Comment by owenschupp** [comment] 2022-06-14 21:37
Thank you for reaching out! This is by design because Windows programs executed via WSL always have a console attached to them. Closing as by design.

**Closed by owenschupp** 2022-06-14 21:37 UTC

**Comment by 0xabu** [comment] 2022-06-14 21:42
@owenschupp are you really telling me it's by design that a process started in the background gets a console but one started in the foreground doesn't?? I still smell a bug here.

Also note that if I start it in the foreground and then move it to the background (via C-Z and `bg`) it doesn't magically acquire a console.

**Comment by elsaco** [comment] 2022-06-14 23:05
@0xabu running `guihello.exe` on the Windows side inside `bash.exe` it outputs `Hello world` string when not backgrounded also.

Sample output:

```
elsaco@RIPPER MINGW64 /c/Test/foo/bar
$ ./guihello.exe
Hello world
```

and backgrounded:

```
elsaco@RIPPER MINGW64 /c/Test/foo/bar
$ ./guihello.exe &
[1] 1217
Hello world
[1]+  Done                    ./guihello.exe
```

If a console should not be allocated, so `stdout` won't have anywhere to go, where is the `Hello world` coming from? Thx!

**Comment by 0xabu** [comment] 2022-06-14 23:08
@elsaco is that mingw64 / cygwin bash.exe, or WSL? My bug is about WSL.

**Comment by 0xabu** [comment] 2022-06-14 23:22
Assuming this is mingw64 or cygwin, I believe the behaviour in https://github.com/microsoft/WSL/issues/8497#issuecomment-1155791879 is reasonable, in that it's at least consistent between foreground and background execution. That's not what I see on WSL.
