### ISSUE TITLE
etc/hosts being overwritten

### ISSUE THREAD

**Issue by scwiek** [Microsoft/WSL#2625] opened 2017-11-02 13:27 UTC
Just got the Creator Update (10.0.16299.19) and my etc/hosts file was overwritten by System32\drivers\etc\hosts.  No big deal, but before I updated I had the option to stop this behavior by removing this line from etc/hosts in WSL:
`#This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.`

This line no longer exists in etc/hosts in WSL, so now my only option is to edit System32\drivers\etc\hosts.

Was this option intentionally removed in the Creator Update?

**Comment by erkinalp** [comment] 2017-11-12 11:47
Because Windows has its own hosts file and DNS-resolver operates system-wide.

**Comment by heldchen** [comment] 2017-11-12 11:57
that is not entirely true, @erkinalp. the dns resolver is not system-wide. you can change `/etc/resolv.conf` as well as `/etc/hosts` and WSL respects those entries:

``` 
me@devbox:~$ sudo bash -c 'echo "8.8.8.8 bubu" >> /etc/hosts'
me@devbox:~$ ping bubu
PING bubu (8.8.8.8) 56(84) bytes of data.
64 bytes from bubu (8.8.8.8): icmp_seq=1 ttl=57 time=3.31 ms
```

and it does make sense to have separate, extra hosts entries defined in WSL only. my debian dev toolchain for example relay on some extra entries to our build servers, but I don't want them in the "global" windows hosts file. as a workaround, a script is re-adding them to `/etc/hosts` when WSL is started, but that is a bit ugly.

**Comment by erkinalp** [comment] 2017-11-12 12:26
Do you have `/home/somebody/etc/hosts` in Debian? Similar design choice.

**Comment by heldchen** [comment] 2017-11-12 14:20
I do not, but I do have different hosts files in each VM and each docker container. the WSL environments is much more similar to a docker container than to another windows user... so yeah.

I'm not saying that the windows hosts file should not propagate into WSL. I'm saying the WSL has its own dns resolver and thus it makes sense to wanting (but not necessary needing) to have a different set of hosts entries.

**Comment by erkinalp** [comment] 2017-11-12 18:03
@heldchen: You got WSL wrong. Windows Subsystem for Linux is an OS personality, i.e. a system-level feature. Distribution installations being in user data does not change that. Different personalities of the OS will share configuration, what could be sounder than that?

**Comment by heldchen** [comment] 2017-11-12 18:10
let's just agree to disagree then, as I'm sticking to my point: your initial claim is wrong as each WSL env has its own resolver, and thus having the possibility to have per WSL instance hosts entries can make sense for some usages. you might not need it, but others do.

**Comment by benhillis** [comment] 2018-01-23 21:14
@scwiek - Thanks for asking, this change was intentional. Marking as by design.

**Closed by benhillis** 2018-01-23 21:14 UTC
