### ISSUE TITLE
Error Code: 0x80004005

### ISSUE THREAD

**Issue by Harpartap0117** [microsoft/WSL#11633] opened 2024-05-30 07:44 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.3593]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

kali-linux

### Repro Steps

When I tried installing kali-linux in my wsl, I would get the following error.
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80004005
Error: 0x80004005 Unspecified error

Press any key to continue...
```

Here is a screenshot: 
![image](https://github.com/microsoft/WSL/assets/144525711/1fd0a07f-6611-4436-8551-4c68496f8edd)

Here are the log files: 
[WslLogs-2024-05-30_12-41-43.zip](https://github.com/microsoft/WSL/files/15495441/WslLogs-2024-05-30_12-41-43.zip)

### Expected Behavior

The expected behaviour was that kali-linux would install without any errors.

### Actual Behavior

It is giving the above mentioned errors.

### Diagnostic Logs

[WslLogs-2024-05-30_12-41-43.zip](https://github.com/microsoft/WSL/files/15495454/WslLogs-2024-05-30_12-41-43.zip)

**Comment by OneBlue** [comment] 2024-05-30 18:33
Thank you @Harpartap0117. It looks like the tar from kali is confusing bsdtar when installing: 

```
Microsoft.Windows.Lxss.Manager	Error	05-30-2024 00:12:01.851	"	"	"code: 	
failurecount: 	5
file: 	onecore\vm\wsl\lxss\service\dll\lxssusersession.cpp
function: 	
hr: 	0x80004005
linenumber: 	1248
message: 	""./var/log/journal/: Invalid extended attribute encountered bsdtar: Error exit delayed from previous errors. ""
threadid: 	1824
type: 	0"	onecore\vm\wsl\lxss\service\dll\lxssusersession.cpp			3744	1824	2		14879194-b25f-0007-41c8-87145fb2da01		
``` 

Can you try installing the [latest version of WSL](https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi) and see if that solves the issue ?

**Comment by Harpartap0117** [comment] 2024-06-01 00:56
> Thank you @Harpartap0117. It looks like the tar from kali is confusing bsdtar when installing:
> 
> ```
> Microsoft.Windows.Lxss.Manager	Error	05-30-2024 00:12:01.851	"	"	"code: 	
> failurecount: 	5
> file: 	onecore\vm\wsl\lxss\service\dll\lxssusersession.cpp
> function: 	
> hr: 	0x80004005
> linenumber: 	1248
> message: 	""./var/log/journal/: Invalid extended attribute encountered bsdtar: Error exit delayed from previous errors. ""
> threadid: 	1824
> type: 	0"	onecore\vm\wsl\lxss\service\dll\lxssusersession.cpp			3744	1824	2		14879194-b25f-0007-41c8-87145fb2da01		
> ```
> 
> Can you try installing the [latest version of WSL](https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi) and see if that solves the issue ?

Thanks for the reply. I updated the WSL and it solved the issue for me.

**Comment by OneBlue** [comment] 2024-06-03 06:30
Glad to hear ! Closing since the issue is resolved.

**Closed by OneBlue** 2024-06-03 06:30 UTC

**Comment by hassan524** [comment] 2025-05-19 18:51
```
C:\Users\Microsoft>wsl --install -d kali-linux
Downloading: Kali Linux Rolling
Installing: Kali Linux Rolling
./var/log/journal/: Invalid extended attribute encountered ]
bsdtar: Error exit delayed from previous errors.===========]
Importing the distribution failed.
Error code: Wsl/InstallDistro/Service/RegisterDistro/WSL_E_IMPORT_FAILED

C:\Users\Microsoft> 
```

I am facing this can anyone help ??
