### ISSUE TITLE
WSL 2 - The Windows Subsystem for Linux instance has terminated.

### ISSUE THREAD

**Issue by chandralanka2** [microsoft/WSL#5318] opened 2020-06-02 15:53 UTC
I have recently upgraded to Windows 10 Version 2004 and installed WSL 2 with Ubuntu-20.04.
When I am trying to access the WSL 2 I am getting the below error

The Windows Subsystem for Linux instance has terminated.
[process exited with code 4294967295]

**Comment by benlumia007** [comment] 2020-06-02 16:37
I believe you need to install the update for the Windows Subsystem Linux 2 as well.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by chandralanka2** [comment] 2020-06-02 17:13
I have already installed wsl2-kernel when I have upgraded from WSL1 to WSL2.
The problem resolved after the system restart. However, the issue may come again

**Comment by benlumia007** [comment] 2020-06-02 18:31
oh ok. yeah, I can't help u there, I skipped WSL1 and went to WSL2.

**Comment by craigloewen-msft** [comment] 2020-06-02 23:44
Hey @chandralanka2 I'll mark this issue as closed for now since it seems resolved via the restart, however if you do experience it again please don't hesitate to reopen it! Thank you for filing this issue :)

**Closed by craigloewen-msft** 2020-06-02 23:44 UTC

**Comment by HQDragon** [comment] 2020-06-16 00:47
> Hey @chandralanka2 I'll mark this issue as closed for now since it seems resolved via the restart, however if you do experience it again please don't hesitate to reopen it! Thank you for filing this issue :)

It happened randomly，i did wsl --export then wsl --import to change the ubuntu20.04 location

**Comment by debmaj2** [comment] 2020-07-10 21:53
degerister wsl and re-register.

**Comment by stevenlafl** [comment] 2020-07-15 07:55
> degerister wsl and re-register.

I randomly experienced this issue after my computer had been running for a couple days. WSL working fine for 2 years prior. I took off WSL from the Windows Features On/Off dialog and turned it back on. I also started "Host Network Service" but this does nothing.

I was able to get another VM in the `wsl -l -v` list to start, but my Debian instance just fails. I get:
`The Windows Subsystem for Linux instance has terminated.`

I have no idea how to fix. I suspect a harddrive corruption of some kind. Yet - I am able to launch Windows itself fine. Where would I even start to repair this?

**Comment by andremorata** [comment] 2020-08-27 17:31
> > degerister wsl and re-register.
> 
> I randomly experienced this issue after my computer had been running for a couple days. WSL working fine for 2 years prior. I took off WSL from the Windows Features On/Off dialog and turned it back on. I also started "Host Network Service" but this does nothing.
> 
> I was able to get another VM in the `wsl -l -v` list to start, but my Debian instance just fails. I get:
> `The Windows Subsystem for Linux instance has terminated.`
> 
> I have no idea how to fix. I suspect a harddrive corruption of some kind. Yet - I am able to launch Windows itself fine. Where would I even start to repair this?

I have been able to solve this problem by converting the instance to WSL1 then the problem is gone. But resolving this for WSL 2 required removing the changes I made on /etc/fstab and convert it back to wsl 2.

**Comment by gujacob** [comment] 2020-09-01 12:02
Same problem here.
WLS 2 crashes randomly.

**Comment by andremorata** [comment] 2020-09-01 12:06
> Same problem here.
> WLS 2 crashes randomly.

Did you change anything recently on /etc/fstab? If you did, try following the steps I described previously.

> I have been able to solve this problem by converting the instance to WSL1 then the problem is gone. But resolving this for WSL 2 required removing the changes I made on /etc/fstab and convert it back to wsl 2.

**Comment by gujacob** [comment] 2020-09-01 12:09
No changes on fstab.
I have upgraded from WLS 1 to WLS 2 a couple of weeks ago and everything was working perfect.. Suddenly, my WLS started to crashes... It usually crashes 1 or 2 times every day. I could not find any logs on my linux instance, and nothing relevant on windows logs...

**Comment by akheron98** [comment] 2021-06-28 14:25
I also got this message "The Windows Subsystem for Linux instance has terminated" when I reboot.  If I try again later (~30 minutes), it's working.   Just like the subsystem takes a lot of time to boot correctly.

**Comment by chadallee** [comment] 2021-09-23 17:05
I've been struggling with this issue for the last couple of days as well.
For me, it looks like the failure was related to the network drives (all cifs) that I was trying to connect to via /etc/fstab

I was able to workaround it as such:
1) Stop LxssManager service via CTRL+SHIFT+ESC
2) Rename ext4.vhdx to ext4-broken.vhdx (location: %LOCALAPPDATA%\Packages\CanonicalGroupLimited.UbuntuonWindows_...\LocalState)
3) Reinstall Ubuntu, which will create a new ext4.vhdx
4) Launch WSL
5) Mount ext4-broken.vhdx using guestmount:
* sudo apt update
* sudo apt install libguestfs-tools
* sudo apt install linux-image-generic
  * This is necessary because guestmount will fail when it can't find anything in /boot/
* sudo guestmount --add /mnt/c/Users/callee/AppData/Local/Packages/CanonicalGroupLimit
ed.UbuntuonWindows_.../LocalState/ext4-dead.vhdx -i /mnt/dead
6) Edit the misbehaving /etc/fstab
* sudo su
  * I probably messed up my mounting permissions here, because I couldn't access /mnt/dead as a normal user..
* vim /mnt/dead/etc/fstab
* Commented out all of my network shares (added **#** to the start of the line)
  * hit I to go into Insert Mode
  * hit <ESC> -> wq -> <ENTER> to save
* exit
* exit
* wsl --terminate Ubuntu
7) Stop LxssManager service again via CTRL+SHIFT+ESC
8) Rename ext4.vhdx to ext4.vhdx.bak
9) Rename ext4-dead.vhdx to ext4.vhdx
10) Run wsl again

**Comment by nedvajz** [comment] 2021-12-16 14:25
Same here as @alexanderKubra here.  
  
For me helps to reinstate possibility to log to terminal.  
`wsl.exe --shutdown`   
`wsl.exe`   
  
In any case it is like 1 minute to proceed these 2 steps and then I have to reopen all the terminals what was still open and otherwise working as they exited due shutdown ..

**Comment by njmulsqb** [comment] 2022-11-25 11:37
It is happening to me now on WSL 2 on Windows 11.
