### ISSUE TITLE
Connection to WSL 2 via 127.0.0.1:80 randomly killed

### ISSUE THREAD

**Issue by Trey96** [microsoft/WSL#9564] opened 2023-01-31 18:11 UTC
### Version

Microsoft Windows [Version 10.0.22621.1194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.83.1-microsoft-standard-WSL2

### Distro Version

 Ubuntu-20.04

### Other Software

Google Chrome

### Repro Steps

- Run WSL
- Setup a webserver on port 80 inside of WSL distro
- Access the webserver via browser
- Wait a variable amount of time
- Attempt to access the webserver again 
- Notice the connection refused error
- Verify WSL is no longer listening on 127.0.0.1:80

### Expected Behavior

Webserver running inside of WSL remains available indefinitely or until WSL is shutdown

### Actual Behavior

I have a Nginx webserver running on port 80 inside of WSL 2, running multiple domains. Externally, on my Windows machine, I have all those domains pointing to 127.0.0.1. Everything has been working just fine until very recently I started randomly getting "Connection Refused" 

![image](https://user-images.githubusercontent.com/60182680/215841868-e5766edb-e10e-497e-b137-af506803f2b2.png)

whenever I tried to visit one of the domains. I found that completely shutting down WSL with ```wsl --shutdown``` and then restarting again, would temporarily fix the issue and I would be able to access the site again. However, eventually it will stop working and I'll have to restart again. 

I really have no idea what could be causing this issue. Like I said, it has been working just fine for months, and I haven't made any recent changes. Any help would be greatly appreciated!

### Diagnostic Logs

When I first start WSL and everything is working I can run these commands and see WSL listening on port 80 from 127.0.0.1
![image](https://user-images.githubusercontent.com/60182680/215843099-9822d10f-9ce9-4cd9-b46d-3e62824f452e.png)

That at some point, the port seems to be closed and I get the following error
![image](https://user-images.githubusercontent.com/60182680/215844392-85b5043f-49c7-4c0b-bf5f-cb4fab577d6c.png)

I also noticed that the "Idle" process tends to start listening on the same port and eventually seems to kill the WSL connection
![image](https://user-images.githubusercontent.com/60182680/215846618-bc6ea341-69ed-4689-b2b0-04c31ca9bcf0.png)

![image](https://user-images.githubusercontent.com/60182680/215846789-ef63022e-b643-4dd9-9518-96f7370f0e3b.png)

**Comment by benhillis** [comment] 2023-01-31 22:07
We are rolling out a fix for this issue shortly, this is a dupe of several other issues.

**Closed by benhillis** 2023-01-31 22:07 UTC
