### ISSUE TITLE
wsl.exe and wslconfig.exe will not execute

### ISSUE THREAD

**Issue by typically** [microsoft/WSL#9824] opened 2023-03-21 22:19 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.2728]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)

### Distro Version

Ubuntu 20.04.5 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)

### Other Software

Visual Studio Code v.1.76.2 with WSL extension v.0.76.1

### Repro Steps

1. Open Windows PowerShell 7.3.3 in Administrator mode. Type "wsl.exe" or "wslconfig.exe" or the same with any arguments. 
2. Open Ubuntu terminal from start menu
3. Run "code ." from the Linux terminal

### Expected Behavior

The command should execute and a Linux terminal should open.

### Actual Behavior

![image](https://user-images.githubusercontent.com/4228898/226745519-bc497856-e3f5-4837-9535-6270b819a5b8.png)

Ubuntu terminal will not open from Start Menu. 

Linux mount **will** open from Windows Explorer, but I get a Remote Desktop Connection Usage argument list window.

Windows Subsystem for Linux **will** run from the start menu, but will also give the same Remote Desktop window.

If I run `code .` from the Linux terminal, the VSCode WSL extension tells me there are no WSL distros found.

### Diagnostic Logs

[wsl_strace.txt](https://github.com/microsoft/WSL/files/11033868/wsl_strace.txt)
[wslconfig_strace.txt](https://github.com/microsoft/WSL/files/11033869/wslconfig_strace.txt)
[WslLogs-2023-03-21_22-19-32.zip](https://github.com/microsoft/WSL/files/11033871/WslLogs-2023-03-21_22-19-32.zip)

**Comment by OneBlue** [comment] 2023-03-21 23:47
Thank you for reporting this @typically.

I wonder if this is caused by a WSL upgrade that went wrong.

Does uninstalling [Store WSL](http://aka.ms/wslstorepage)  and re-installing help ?

**Comment by typically** [comment] 2023-03-22 11:13
Thanks @OneBlue, uninstalling and reinstalling has indeed restored functionality.

**Comment by OneBlue** [comment] 2023-03-22 16:47
Thanks you. Closing since the issue has been resolved.

**Closed by OneBlue** 2023-03-22 16:47 UTC
