### ISSUE TITLE
WSL 2 - Can't access to localhost after server reloaded

### ISSUE THREAD

**Issue by dangxquang** [microsoft/WSL#4366] opened 2019-08-01 08:26 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows build 18945.
* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)
When I run a new react server (i.e create-react-app), I can access localhost from windows. Then I try to edit some page, the react server rebuild but I can't reload the page. The browser keeps loading the page without response. It may take some minutes to be accessed again or I need to restart the server manually.
If access via wsl-2 IP address, everything works like a charm.
* What's wrong / what should be happening instead:
App reload should be accessed via localhost without problems

**Comment by velosodigital** [comment] 2019-08-01 18:15
Duplicate of #4340

**Closed** 2019-08-01 20:17 UTC
