### ISSUE TITLE
Building SageMath fails on WSL

### ISSUE THREAD

**Issue by mikecroucher** [Microsoft/WSL#1757] opened 2017-03-07 12:34 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

The build script is 

```
wget http://www.mirrorservice.org/sites/www.sagemath.org/src/sage-7.5.1.tar.gz
tar -xzf ./sage-7.5.1.tar.gz
cd sage-7.5.1
make
```

* Expected results

Compilation of SageMath

* Actual results (with terminal output if applicable)

The error message is 

```
[gcc-5.4.0] /home/walkingrandomly/github/sagemath/sage-7.5.1/local/var/tmp/sage/build/gcc-5.4.0/gcc-build/./gcc/as: 32: /home/walkingrandomly/github/sagemath/sage-7.5.1/local/var/tmp/sage/build/gcc-5.4.0/gcc-build/./gcc/as: Cannot fork
```

Full details at https://gist.github.com/mikecroucher/5a37c402d74774de15f015c3efd77139#file-gistfile1-txt

A subsequent `make` results in 

```
make build/make/Makefile
make[1]: Entering directory `/home/walkingrandomly/github/sagemath/sage-7.5.1'
make[1]: `build/make/Makefile' is up to date.
make[1]: Leaving directory `/home/walkingrandomly/github/sagemath/sage-7.5.1'
build/bin/sage-logger \
                "cd build/make && ./install 'all'" logs/install.log
./install: fork: Cannot allocate memory
```

* Your Windows build number

Windows 10 Home. Version 1607.
OS Build: 14393.693

* Steps / All commands required to reproduce the error from a brand new installation 

You'll probably need `apt-get install build-essentials` and maybe others.

```
wget http://www.mirrorservice.org/sites/www.sagemath.org/src/sage-7.5.1.tar.gz
tar -xzf ./sage-7.5.1.tar.gz
cd sage-7.5.1
make
```

* Strace of the failing command

Don't have it...sorry. See below.

OK. So this is odd.

While trying to get the `strace`, I started getting errors for EVERY command I tried. Even an `ls` resulted in `cannot allocate memory`.

I **restarted** Bash for Windows and started up a new `make` command. Currently running fine. Will update later.

**Comment by iz0eyj** [comment] 2017-03-07 17:49
I'm testing on Build 15048

**Comment by iz0eyj** [comment] 2017-03-08 05:29
@mikecroucher the compiler is still alive

**Comment by iz0eyj** [comment] 2017-03-08 19:29
@mikecroucher:
```
Testing that Sage starts...
[2017-03-08 19:32:53] SageMath version 7.5.1, Release Date: 2017-01-15
This looks like the first time you are running Sage.
Updating various hardcoded paths...
(Please wait at most a few minutes.)
DO NOT INTERRUPT THIS.
Done updating paths.
/home/federico/Scaricati/sage-7.5.1/local/lib/python2.7/site-packages/psutil/_pslinux.py:364: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 2] No such file or directory: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
Yes, Sage starts.
make[2]: uscita dalla directory "/home/federico/Scaricati/sage-7.5.1/build/make"
make[1]: uscita dalla directory "/home/federico/Scaricati/sage-7.5.1/build/make"

real    1551m37.745s
user    273m34.125s
sys     1372m20.688s
Sage build/upgrade complete!

To install small scripts to directly run Sage's versions of GAP,
the PARI/GP interpreter, Maxima, or Singular etc. (by typing e.g.
just 'gap' or 'gp') into a standard 'bin' directory, start Sage
by typing 'sage' (or './sage') and enter something like

    install_scripts('/usr/local/bin')

at the Sage command prompt ('sage:').

federico@Bestia:~/Scaricati/sage-7.5.1$
```

**Comment by iz0eyj** [comment] 2017-03-08 20:05
federico@Bestia:~/Scaricati/sage-7.5.1$ ./sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 7.5.1, Release Date: 2017-01-15                   │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
/home/federico/Scaricati/sage-7.5.1/local/lib/python2.7/site-packages/psutil/_pslinux.py:364: RuntimeWarning: 'sin' and 'sout' swap memory stats couldn't be determined and were set to 0 ([Errno 2] No such file or directory: '/proc/vmstat')
  warnings.warn(msg, RuntimeWarning)
sage:

there are a warning on vmstat.

**Comment by therealkenc** [comment] 2017-03-08 22:55
`/proc/vmstat` is #1071 and is just a soft fail.

**Comment by iz0eyj** [comment] 2017-03-10 13:55
I think this report can be declared closed in the part relating to the compilation and duplicated on vmstat.

@benhillis: 
I read that Microsoft had offered his support to the porting of this extraordinary software on Win32 but did not get the desired result; perhaps it would be good to warn that now, thanks to WSL, the package became available.

**Comment by mikecroucher** [comment] 2017-03-13 11:53
I'm still getting build failure.  I've upgrade a few things:-

* Build 15048
* Upgraded the WSL to 16.04 

Now it doesn't need to compile gcc but it's failing with similar error to before....fork can't allocate memory. What are you doing differently to me @iz0eyj ?

```
[flint-2.5.2.p1] /home/walkingrandomly/github/sagemath/sage-7.5.1/build/bin/sage-spkg: fork: Cannot allocate memory
Makefile:1631: recipe for target '/home/walkingrandomly/github/sagemath/sage-7.5.1/local/var/lib/sage/installed/flint-2.5.2.p1' failed
make[2]: *** [/home/walkingrandomly/github/sagemath/sage-7.5.1/local/var/lib/sage/installed/flint-2.5.2.p1] Error 254
make[2]: Leaving directory '/home/walkingrandomly/github/sagemath/sage-7.5.1/build/make'
Makefile:887: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/walkingrandomly/github/sagemath/sage-7.5.1/build/make'
```

**Comment by mikecroucher** [comment] 2017-03-13 22:12
I installed the flint library from the Ubuntu repo and the Sage build failed on OpenBLAS. So, I installed OpenBLAS from the repos and then the build failed on Python 2.7.

It's always memory related. e.g. 
```
[python2-2.7.13.p0] error: [Errno 12] Cannot allocate memory
[python2-2.7.13.p0] Makefile:559: recipe for target 'sharedmods' failed
```
I have 32Gb of RAM so have no idea what the problem is.

**Comment by mikecroucher** [comment] 2017-03-13 22:17
As I saw once before, now no commands work. E.g.

```
walkingrandomly@DESKTOP-HD5MT2B:~/github/sagemath/sage-7.5.1$ ls
bash: fork: Cannot allocate memory

walkingrandomly@DESKTOP-HD5MT2B:~/github/sagemath/sage-7.5.1$ uname
bash: fork: Cannot allocate memory
```

**Comment by benhillis** [comment] 2017-03-14 00:34
@mikecroucher - Would you mind taking an strace of one of the failing commands?

**Comment by mikecroucher** [comment] 2017-03-14 08:37
I'd love to but....

```
walkingrandomly@DESKTOP-HD5MT2B:src$ strace ls
bash: fork: Cannot allocate memory
````

Restarting the session fixes this but it's as if there is a memory leak somewhere.  Sooner or later, things start failing this way and, when they do, its all over.

**Comment by iz0eyj** [comment] 2017-03-14 17:38
@mikecroucher:
Hi Mike, I merely follow the steps indicated by you.

Machine is Dell XPS 2720, Core i7. Compiltion time was abt 25 hours.

**Comment by therealkenc** [comment] 2017-03-14 21:20
Builds okay here too, FWIW.

**Comment by mikecroucher** [comment] 2017-03-15 07:21
So now I feel all lonely :) 
I wondered if I had broken my WSL somehow so reinstalled 

Sagemath failed while trying to build Python. This was the command that the build system said failed

```
gcc -pthread -c -fPIC -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall  -Wno-unused  -I. -IInclude -I./Include  -fPIC -DPy_BUILD_CORE -o Modules/_math.o Modules/_math.c
[python2-2.7.13.p0] make[3]: fork: Cannot allocate memory
```

The way this bug manifests is such that eventually all commands will fail with the `fork: Cannot allocate memory` message. Even strace itself. So, to make sure that I had something in an strace, I reran make again like this: `strace make &> 1`  

The result is in this gist: https://gist.github.com/mikecroucher/b14100247bbdb9aa4647ffbac28db2fe

**Comment by therealkenc** [comment] 2017-03-15 08:38
Spitballing, try opening [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer) (or similar tool of choice) and see if there is anything untoward in your process list when you are in the failed state. Look for anything lingering from the `make`, like `gcc` or the usual build related suspects. Also try running `top -o VIRT` in another terminal during the run. You can't run `ps` (or _anything_) after the fail, but maybe `top` will keep running and show something.

You can also try giving yourself a huge page file (like 32GB) if you have the disk space. No, I don't think that will help, and yes, you have plenty of RAM, but desperate times call for desperate measures. When I did my run I was looking for (hoping for) anything suggesting a leak, but it looked pretty vanilla for a large build. You seem to have done all the right things, for what it's worth, though that's small consolation.

**Comment by therealkenc** [comment] 2017-03-15 08:47
Also, do you happen to be running any 3rd party antivirus software? That's kind of a go-to blame for a number of WSL ills that are hard to repro, but again we're in the "grasping" for explanation phase here. I haven't actually heard of AV causing process or memory related problems.

**Comment by iz0eyj** [comment] 2017-03-21 09:12
@mikecroucher 
The command to complete uninstall the environment is
`lxrun /uninstall /full.`

**Comment by mikecroucher** [comment] 2017-03-28 09:57
@lz0eyj yep. Tried that. Still doesn't work

**Comment by iz0eyj** [comment] 2017-03-28 12:08
@mikecroucher:
Strange compiles without problems both for me and for @therealkenc , if you need I can send you a zip file with the compiled executable.

Is there a test suite to make sure that it works? I do not use these programs, but from what I understand it is an important product, and would be good to finally have it on Windows.

**Comment by mikecroucher** [comment] 2017-04-01 10:53
Thanks for the offer but I'd really like to understand why it's not working for me.  Being able to build it is more important in many ways than simply having the executables.  

It's not just SageMath on my machine....it's everything that's large that eventually fails this way and is severely limiting the utility of WSL for me.  I'm trying to think what the problem may be. What's possibly different about my set up to yours.  I'm clutching at straws but...

* I've got the Home edition of Windows 10 
* The laptop is very new. A Dell XPS 9560 with 32Gb of RAM, a Kaby Lake CPU and NVIDIA GPU

**Comment by iz0eyj** [comment] 2017-04-01 11:22
@mikecroucher:
I use a Dell XPS 2720 with Win 10 Pro, but I do not think the problem is to be found in this but in the development environment configuration, maybe something that I and @therealkenc  installed and you do not.
At what point of the compilation gives you the error?

**Comment by mikecroucher** [comment] 2017-04-10 13:35
Sorry for the delay....vacation.

When it fails varies every time. If I restart the session, I can continue but it eventually fails on building OpenBLAS (that definitely IS a Haswell issue and not related to WSL). If I switch to using ATLAS for linear algebra then it never succeeds...probably because ATLAS takes a lot of time to build.

The behavior is such that it's as if I am steadily running out of resource...like a memory leak. This isn't just a sagemath issue. I always get this problem eventually if I attempt to build something large.

**Comment by iz0eyj** [comment] 2017-04-13 10:44
But... the compiler fails or you stop it?
My compilation time was 25+ hours on a Core i7.
Could you give me the name of another program that gave you similar problems at compile time? it would be important to eliminate this type of bug.

**Comment by tara-raj** [comment] 2018-08-21 20:27
Can you please try this on a more recent Windows Build and let us know if you're still running into issues

**Closed** 2018-08-21 20:27 UTC

**Comment by therealkenc** [comment] 2018-08-21 23:04
Never ran it myself but this is almost certainly same as #2959, which dangles open.
