### ISSUE TITLE
libx265 causes ffmpeg to segfault

### ISSUE THREAD

**Issue by josephby** [Microsoft/WSL#2805] opened 2018-01-03 17:52 UTC
Windows Build 10.0.16299.125

I'm attempting to transcode video to h265 using ffmpeg and am getting a segmentation fault. Seems, odd. The same command works fine with h264. Strace at https://gist.github.com/7928fe3172e20f62092276f93d2435c9 , output below:

> foo@sage:/mnt/c/Users/josephby/Pictures/2017-12$ ffmpeg -i "00019.MTS" -c:v libx265 -crf 28 -c:a copy "00019-hevc.mp4"
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc
 --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-la
dspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme
--enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnapp
y --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable
-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mpegts, from '00019.MTS':
  Duration: 00:03:17.22, start: 1.033367, bitrate: 16465 kb/s
  Program 1
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:2[0x1200]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090), 1920x1080
x265 [info]: HEVC encoder version 1.9
x265 [info]: build info [Linux][GCC 5.3.1][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
x265 [info]: Main profile, Level-4 (Main tier)
Segmentation fault (core dumped)

**Comment by therealkenc** [comment] 2018-01-04 01:26
Possibly:
```
open("/sys/devices/system/node/node0/cpumap", O_RDONLY) = -1 ENOENT (No such file or directory)
```
But use case.....

**Comment by dkisselev** [comment] 2018-09-13 20:09
I was running into the same issue on 16.04 but just did a full release upgrade to 18.04.1 and its looks like the updated binaries have resolved the issue.

Windows 10.0.17134
Ubuntu 18.04.1
ffmpeg 3.4.4

**Comment by therealkenc** [comment] 2018-09-15 22:12
> and its looks like the updated binaries have resolved the issue.

That's good news. Tempting to chalk this up to tag 'external' (aka fixed-upstream; it has been done before) but it would be nice to know what was broken and what was fixed before closing. Right now we know neither. 

On your working setup, can you do an `strace` and see if the `/sys/devices/system/node/node0/cpumap` `ENOENT` is still in there. It might be there, but is now either harmless on recent ffmpeg, or was always harmless (and the problem was "something else").

Maybe we'll never know the cause (no one is going to take the trouble to bisect) but at least we'll know whether WSL's absence of `cpumap` is worth keeping around as an open issue.

**Comment by therealkenc** [comment] 2018-09-19 06:53
Alright thanks. Actually that does tell us something, namely that the code in question was tweaked (as opposed to being the same as the OP strace). That fd returned by `openat()` is going to be (or rather would have been) used by _something_ subsequently if the call had succeeded, but the fact that it is ENOENT doesn't cause a fatal regardless.

Going to do the pragmatic thing and close this external just because I can't see anyone jumping on `/sys/devices/system/node` in the absence of a hard blocker anyway. Appreciate you confirming `ffmpeg` x265 is operational (whatever the reason) and for the follow up.

**Closed by therealkenc** 2018-09-19 06:53 UTC

**Comment by bormat** [comment] 2019-04-02 03:12
Same problem, I resolved it by updating the version http://ubuntuhandbook.org/index.php/2018/10/install-ffmpeg-4-0-2-ubuntu-18-0416-04/
