### ISSUE TITLE
Unusual Behavior Converting Distro To WSL2 18947+

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/WSL#4394] opened 2019-08-09 13:15 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

18947-18956

* What you're doing and what's happening: 

```
PS C:\Users\username> wsl --set-version WLinux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Exporting the distribution failed.
bsdtar: Write error
```

![62743620-ad35ce00-ba08-11e9-9e7b-b83182002d1a](https://user-images.githubusercontent.com/33820650/62781499-232c4a80-ba86-11e9-8fb3-40554bf0d144.png)

* What's wrong / what should be happening instead:

Conversion of distros to WSL2 is failing with a bsdtar error under mysterious circumstances.

This appears to affect all distros, including Pengwin and Ubuntu.

We began tracking this issue here https://github.com/WhitewaterFoundry/Pengwin/issues/504.

After duplication with other distros are reporting upstream while we continue to investigate.

Reducing the size of the installed distro by resetting it to original image seems to help.

**Comment by egroenen** [comment] 2019-08-11 08:26
I had the same issue, `bsdtar: Write error`. I reran the conversion and it succeeded the second time around. 

`wsl --set-version Ubuntu-18.04` 

`wsl --list --verbose` shows that it is now running as Version 2. I ran bash and confirmed that everything was still there and that it was indeed version 2.

**Comment by ltomes** [comment] 2019-08-12 14:28
I see the same behavior as @egroenen converting distros so far.
Note I did disable realtime virus and thread protection between my attempt so that also could have been a factor.

```
PS C:\WINDOWS\system32> wsl --set-version WLinux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Exporting the distribution failed.
bsdtar: Write error

PS C:\WINDOWS\system32> wsl --set-version WLinux 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.
PS C:\WINDOWS\system32>
```

**Comment by Biswa96** [comment] 2019-08-12 14:57
Has anyone got `strace -ff` output or event trace logs as provided [here][1]?

[1]: https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md

**Comment by craigdods** [comment] 2019-08-13 13:50
Can confirm I experienced the same issue as others. @ltomes, doesn't seem like AV/thread protection plays a role here. Simply re-running the conversion seems to work:

> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Exporting the distribution failed.
bsdtar: Write error

> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.

> wsl --list --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
  Legacy    Stopped         1`

**Comment by benhillis** [comment] 2019-08-13 17:07
Interesting, looks like there still may be some issues with conversion.  I will take a look.

**Comment by eblount** [comment] 2019-08-15 17:53
In case it helps someone: I had this error after a different error. I resolved the first error using this method: https://github.com/microsoft/WSL/issues/4103#issuecomment-501885534

After that, I got the error here (bsdtar) no matter how many times I ran `--set-version`.

Following a reboot, the conversion process succeeded. I'm not sure whether just restarting Powershell would have done the trick.

**Comment by jerrodrs** [comment] 2019-08-19 23:34
@eblount What distribution are you using? I am in the exact same situation but after fixing the #4103 issue, I always get a `bsdtar: Write error` even after reboot. Trying to export a fresh Ubuntu 18.04 install.

**Comment by eblount** [comment] 2019-08-20 01:04
@jerrodrs Yeah, I'm using Ubuntu 18.04. I installed it fresh because I had an older Ubuntu from WSL1, and I needed 18.04 for the Docker WSL2 preview. Sorry about the troubles, it was a headache getting past all these little issues, but I'll confirm that it's worth it once you get there - Docker on Windows has never been faster, and the whole Ubuntu experience has been great on WSL2. I guess make sure you're upgrading the correct distro by name, if you have multiple, and failing that, maybe uninstall all the distros and start over?

**Comment by eblount** [comment] 2019-08-20 01:23
@jerrodrs Oh, also, make sure you have enough disk space. My hunch is that this conversion process requires a good deal of it.

**Comment by jfelixoptimiumnc** [comment] 2019-08-27 05:13
Disabling Windows Real Time protection did the trick!

**Comment by yuhcaesar** [comment] 2019-09-01 16:26
Same here, but it's fixed after freeing some disk space.

**Comment by Biswa96** [comment] 2019-09-01 16:37
Did anyone update to latest Windows insider build 18970? I've tested, this issue is fixed in that build.

**Comment by sirredbeard** [comment] 2019-09-02 15:37
@Biswa96 

@benhillis will probably have to tell us.

I think there is a _chance_ the fix for you was incidental. Two reasons: 1. This bug is not listed as fixed in the release notes or marked as such and they are pretty good at doing that, but maybe it was fixed. 2. I have also gotten at least one report of this bug on 18970, though that could have been unrelated.

**Comment by chutzimir** [comment] 2019-09-06 04:29
For what it's worth, as a workaround I did `wsl --export` and `wsl --import` so I got a copy of my original Linux running on wsl2. Now just to figure out how to set the user for my wsl2 instance (it starts as root) and will be perfect.

**Comment by MikaelUmaN** [comment] 2019-09-08 20:45
Running: Microsoft Windows [Version 10.0.18970.1005]

I got this issue:
```

PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Exporting the distribution failed.
bsdtar: Write error

PS C:\WINDOWS\system32> wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.
PS C:\WINDOWS\system32> wsl -l --verbose
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2
```

As you can see, seemingly with no change in-between it suddenly worked the second time around...

**Comment by Biswa96** [comment] 2019-09-08 21:14
Is this error occurs with distros installed from Windows Store? Anyone tried to manually install a distro in Desktop or Documents folder?

**Comment by MikaelUmaN** [comment] 2019-09-09 04:14
I installed from the store

**Comment by greggmarshall** [comment] 2019-09-09 12:48
One more data point on build 18970 on a fresh computer, first attempt failed, second attempt worked, no changes made in between attempts.

**Comment by zachl123** [comment] 2019-09-09 21:25
For the record, for me, it worked after turning off AV protection (Windows Defender).  May have just been luck, but it failed multiple times before I did so and I noticed Defender activity the last time it failed.

**Comment by sirredbeard** [comment] 2019-09-09 23:50
Thanks, @greggmarshall and @zachl123. I think a tough issue with this bug is reproducibility.

**Comment by griest024** [comment] 2019-09-12 00:39
Adding `bsdtar` to the list of excluded processes in virus protection also worked.

**Comment by richb-hanover** [comment] 2019-09-16 13:30
Another report: Windows Build 18980.vb_release.190907-1301

I tried to --set-version to "Ubuntu 2" multiple (3-4) times. Each time gave `bsdtar: Write error`  Only the last time worked with no obvious change (and only ~15 minutes) between attempts. See below.

```
PS C:\Users\1> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
PS C:\Users\1>

…

PS C:\Users\1> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Exporting the distribution failed.
bsdtar: Write error

PS C:\Users\1> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
PS C:\Users\1> wsl -l --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         1
PS C:\Users\1> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.
PS C:\Users\1> wsl -l --verbose
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
PS C:\Users\1> wsl
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

richb@system1234:/mnt/c/Users/1$
```

**Comment by fedevegili** [comment] 2019-09-19 17:32
I had the same error after I installed Ubuntu-18.04. I tried everything mentioned here, but no success. So I uninstalled 18.04 and just installed "ubuntu" from windows store. The conversion worked on the first try.

**Comment by Yacodo** [comment] 2019-09-25 17:27
Disabling AV protection did the trick on 18990, without I was already at 5 failed tries.

As a bonus point, it does it faster (since `/` dir is not in WDefender exclusion path).

**Comment by canozmen** [comment] 2019-09-25 19:21
I got it working after disabling WDefender and killing Search Everything (everything.exe)

I then added the \AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\ folder to Everything's excluded folders, re-enabled WDefender with same excluded folder. Both WSL2 and Everything seems to work fine now.

**Comment by ajeet001** [comment] 2019-10-17 02:28
I turned off Windows Reatime Protection, and it fixed the issues with WSL2.
However, **my windows machine won't shut down completely. I have to press and hold the power button to shut down completely.**
Anyone facing similar issue

**Comment by greggmarshall** [comment] 2019-10-17 03:11
The shut down problem seems to be unrelated and a known issue.  Check the Windows Insider feedback forum, there was a thread there about it.

**Comment by ajeet001** [comment] 2019-10-17 03:37
Thanks Greg. 
Running `sfc /scannow` command fixed the corrupted file, and the issues. Windows build 18999.1

**Comment by OlafHaag** [comment] 2020-07-17 22:52
I was also getting `bsdtar: Write error`. What didn't work: disabling anti-virus, rebooting, limiting memory through .wslconfig.
Some other comments brought my attention to the RAM. And I could repeatedly predict when it was going to fail, namely when RAM was maxed out.

I had a big distro, so i removed the android ndk, sdk, tmp files, built folders etc. until the distro was smaller than available RAM. Tried again and it worked.
![WSL2Convert_rbsdtar_write_error](https://user-images.githubusercontent.com/4630661/87836126-5c249000-c88f-11ea-8719-b8b5df6ed29f.png)
But it would be more convenient if it worked without having to figure that out first and having to reinstall everything I had to remove, obviously.

**Comment by CompSciMaj13** [comment] 2020-08-12 22:45
I ran into quite a few issues when converting from WSL 1 to WSL 2 that relates to this ticket. I detailed my environment and the journey I took to work around them in the following comment.

https://github.com/microsoft/WSL/issues/4102#issuecomment-673145649

**Comment by untanglereality** [comment] 2021-04-27 11:17
> I was also getting `bsdtar: Write error`. What didn't work: disabling anti-virus, rebooting, limiting memory through .wslconfig.
> Some other comments brought my attention to the RAM. And I could repeatedly predict when it was going to fail, namely when RAM was maxed out.
> 
> I had a big distro, so i removed the android ndk, sdk, tmp files, built folders etc. until the distro was smaller than available RAM. Tried again and it worked.
> ![WSL2Convert_rbsdtar_write_error](https://user-images.githubusercontent.com/4630661/87836126-5c249000-c88f-11ea-8719-b8b5df6ed29f.png)
> But it would be more convenient if it worked without having to figure that out first and having to reinstall everything I had to remove, obviously.
> 
> Windows10 v2004 Build: 19041.388
> 

I also had the same issue trying to convert Kali to WSL2 version. (I also had Ubuntu installed, but converting it to WSL2 worked smoothly.) I have attempted it several times, at first, there didn't seem to be much issue with the memory usage, but it kept giving the same error: 
```
Exporting the distribution failed.
bsdtar: Write error
```
After the first several tries, I tried again a couple of more times, and my browser kept crashing after saying "Out of Memory". Another try, and I got a black screen, which made me finally realise, it was because RAM was full. 

There were some solutions listed requiring making changes to distro file settings in LocalAppData, but I didn't want to mess with it. 

After starting the conversion again, I started monitoring memory usage. `Vmmem` seems to be responsible for the high memory usage, then Antivirus started acting up, which I disabled. Then started [Process Tamer](https://www.donationcoder.com/software/mouser/popular-apps/process-tamer), which seemed to decrease the memory usage immediately to a reasonable level, and the conversion was completed successfully.

**Closed** 2021-04-30 16:12 UTC
Labels: bug, wsl2
