### ISSUE TITLE
Ctrl+V does not work

### ISSUE THREAD

**Issue by sba923** [Microsoft/WSL#2614] opened 2017-10-28 07:40 UTC
I'm running French RS3 build 16299.19 with a French keyboard but with English MUI (as a software engineering professional, that's my working language with computers), and the Store Ubuntu distro.

Hitting Ctrl+V in bash (or bash running 'bc -l', or anything...) doesn't paste: the first time nothing happens, if I hit it twice in a row ^V is displayed.

QuickEdit mode is enabled.

Mouse right-click does paste.

The usual "Alt+Space E P"  does not work (nothing happens).

**Comment by Grix** [comment] 2017-10-28 12:52
Vote on the feature suggestion here: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341399-bash-copy-paste

**Comment by stianl** [comment] 2017-10-28 22:01
Sounds like a duplicate of #235. There's a lot more details in that issue.

**Comment by zadjii-msft** [comment] 2017-10-30 15:26
Yep, this has been reported and discussed quite a bit. Closing as a dupe.

**Closed by zadjii-msft** 2017-10-30 15:26 UTC
Labels: bug, console, duplicate
