### ISSUE TITLE
WSL2 fails to start with Error code: Wsl/Service/CreateInstance/CreateVm/MountVhd/HCS/0x800706bf

### ISSUE THREAD

**Issue by ilyaradko** [microsoft/WSL#11033] opened 2024-01-16 11:50 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.3930]

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1-1

### Distro Version

Ubuntu 20.04

### Repro Steps

Try to start WSL from command line: `wsl`.

### Expected Behavior

WSL starts.

### Actual Behavior

WSL throws an error:
```
C:\Users\dtu>wsl
Failed to attach disk 'C:\Program Files\WSL\system.vhd' to WSL2: The remote procedure call failed and did not execute.
Error code: Wsl/Service/CreateInstance/CreateVm/MountVhd/HCS/0x800706bf

C:\Users\dtu>
```

This happens after a recent Windows updates (KB5034122 and KB5033909). I tried to rollback the updates, but they are pushed again by the group policies, so can't roll them back.

### Diagnostic Logs

[WslLogs-2024-01-16_12-42-26.zip](https://github.com/microsoft/WSL/files/13949374/WslLogs-2024-01-16_12-42-26.zip)

**Comment by OneBlue** [comment] 2024-01-16 22:11
Thank you @ilyaradko. It looks like something is failing inside the storage stack. 

Can you collect storage logs of  repro ? You can do this via (powershell): 

```
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
.\collect-wsl-logs.ps1 -LogProfile storage 
```

**Comment by manofsticks** [comment] 2024-01-25 13:14
I am encountering the same issue, and here are the additional steps I've tried.

-I unregistered my installed Distributions by running the following

`wsl --unregister Debian' 

Upon trying to reinstall, I get the same error code with a different message

`wsl --install debian

wslRegisterDistribution failed with error: 0x800706bf
Error: 0x800706bf The remote procedure call failed and did not execute`


After getting this error, my computer will fail with a bluescreen within a few minutes with the following message:

`Stop code: SYSTEM_SERVICE_EXCEPTION
What failed: dxgkrnl.sys`

I've also tried with ubuntu and get the same error.

**Comment by ilyaradko** [comment] 2024-01-25 13:25
Yes, it seems that the problem is not in WSL itself, but in an RPC that is called to mount the .vhdx image of the Linux. Just trying to mount it (`wsl --mount`) without starting WSL also fails.

**Comment by manofsticks** [comment] 2024-02-16 13:53
This error appears to have resolved itself with the most recent Windows Update for me; unfortunately I'm not knowledgeable enough about Windows update process to better inform which update specifically resolved it, and my only Windows device is my work machine so I can't experiment to find out.

**Comment by ilyaradko** [comment] 2024-02-16 15:25
@manofsticks, if you press Win+R (run window) end execute appwiz.cpl, you will see a window with installed apps. In that window, click "View installed updates" in the upper left corner. Then sort updates by the last column (Installed On) and scroll down till "Microsoft Windows". You will see the recently installed Windows updates. I would very much appreciate if you post here the updates that were installed recently. For me the problem still persists and I can try manually installing the same updates to fix it. Thank you!

**Comment by manofsticks** [comment] 2024-02-16 16:46
Here are the most recent updates listed there. 

![image](https://github.com/microsoft/WSL/assets/5444847/b5a4c399-df3d-4b3d-9211-f0a8cd83d7ed)

**Comment by ilyaradko** [comment] 2024-02-19 10:52
Thank you @manofsticks for posting it. I have exactly the same last three updates, but the problem is still there.

**Comment by lcrok** [comment] 2024-03-02 06:47
I started receiving this same error today. The only update I see today is the KB5034466. I believe this could be causing this error.
I cannot Run, Import nor Install any distro on WSL.
Has anyone found a solution for this?

**Comment by lcrok** [comment] 2024-03-05 12:20
I found the issue on my system. It was Avecto Trust Center that was updated as a company wide push that broke it. Upon downgrading Avecto, WSL erro was gone. So, my advice is, look for other apps/av/sec software that may be have been installed recently.

**Comment by ilyaradko** [comment] 2024-03-05 14:44
@lcrok, thanks a lot for the hint! Indeed, the problem was caused by Avecto. I disabled the Avecto's kernel-level driver PDDriver.sys to test it, and WSL started.

Avecto is known to be a problem for a lot of software to the extent that they introduced a registry key for exclusions. However, I tried adding wsl.exe into `HKLM\SOFTWARE\Avecto\Privilege Guard Client\"ManagedHookExclusions"` and `HKLM\SOFTWARE\WOW6432Node\Avecto\Privilege Guard Client\"ManagedHookExclusions"` without success. Perhaps, it is not wsl.exe that fails, but the modules it depends on (vmcompute.exe, vmwp.exe, vmmem, etc.)

**Comment by OneBlue** [comment] 2024-03-13 21:57
Thank you for the conclusion @ilyaradko.

Closing since the issue is caused by a third party driver.

**Closed by OneBlue** 2024-03-13 21:57 UTC

**Comment by uncreativespace** [comment] 2024-05-02 22:11
> @lcrok, thanks a lot for the hint! Indeed, the problem was caused by Avecto. I disabled the Avecto's kernel-level driver PGDriver.sys to test it, and WSL started.
> 
> Avecto is known to be a problem for a lot of software to the extent that they introduced a registry key for exclusions. However, I tried adding wsl.exe into `HKLM\SOFTWARE\Avecto\Privilege Guard Client\"ManagedHookExclusions"` and `HKLM\SOFTWARE\WOW6432Node\Avecto\Privilege Guard Client\"ManagedHookExclusions"` without success. Perhaps, it is not wsl.exe that fails, but the modules it depends on (vmcompute.exe, vmwp.exe, vmmem, etc.)

It's 2 of the dependencies that need hook exclusions set, yeah. 

C:\Windows\system32\vmcompute.exe
C:\Windows\system32\vmwp.exe

... Need to be set in the 64 & 32 bit locations for ManagedHookExclusions. You'll still see PGHook.dll get injected with them set in that key but it won't do anything.
