### ISSUE TITLE
Buffer Issue with CTRL+D 

### ISSUE THREAD

**Issue by omgbrbttyl** [microsoft/WSL#4332] opened 2019-07-24 03:30 UTC
Windows Version : Microsoft Windows [Version 10.0.17134.885]

I was working on an assignment using Windows Subsystem for Linux. Below is the C Code that was used to write a mini-shell for this assignment. 
I ran into an interesting issue using WSL. On line 35, you can see that I call the read function to read in the buffer and it does a check for zero. When pressing <kbd>Ctrl</kbd>+<kbd>D</kbd>, while using WSL, it will go into the if statement and prints the print message on line 36 infinitely and does not stop until I used <kbd>Ctrl</kbd>+<kbd>C</kbd> to exit. When running this program on a Linux machine, it behaves appropriately and prints once, and brings us to the top of the loop.  

For compilation

      gcc shell.c -o shell

Program Below:

    #include <stdio.h>
    #include <stdlib.h>
    #include <unistd.h>
    #include <sys/wait.h>
    #include <errno.h>
    #include <string.h>
    #include <sys/types
    #include <unistd.h>
    #include <error.h>

    char prompt[] = "$ ";

    static int
    Fork()
    {
      pid_t pid;
    
      if ((pid = fork()) < 0)
        error(EXIT_FAILURE, errno, "fork error");
        return(pid);
    }
    
    int    
    main(void)
    {
      long MAX = sysconf(_SC_LINE_MAX);
      char buf[MAX];
      pid_t pid;
      int status, n;
    
      do {
        write(STDOUT_FILENO, prompt, strlen(prompt));
        fflush(NULL);
        memset(buf, 0, MAX);
        if((n = read(STDIN_FILENO, buf, MAX)) == 0) {
          printf("use exit to exit shell\n");
          continue;
        }
        buf[strlen(buf) - 1] = '\0'; // chomp '\n'
    
        if (strncmp(buf, "exit", MAX) == 0) { // match
          break;
        }
        pid = Fork();
        if (pid == 0) {  // child
          execlp(buf, buf, (char *)NULL);
          error(EXIT_FAILURE, errno, "exec failure");
        }
        // parent
        if ((pid = waitpid(pid, &status, 0)) < 0)
          error(EXIT_FAILURE, errno, "waitpid error");
      } while(1);
      exit(EXIT_SUCCESS);
    }

**Comment by mscraigloewen** [comment] 2019-07-24 17:17
I ran your sample code and didn't encounter the behaviour you described. My Windows build is 18944, so this may be something that has already been fixed in an update.

![image](https://user-images.githubusercontent.com/42221804/61814157-41dee000-adfc-11e9-9668-ee07bf3514b6.png)

What distro are you running it in?

**Comment by omgbrbttyl** [comment] 2019-07-24 17:31
I am currently running Ubuntu 18.04.1

**Comment by Biswa96** [comment] 2019-07-24 18:02
@omgbrbttyl Your Windows 10 version is old.

**Comment by mscraigloewen** [comment] 2019-07-24 21:16
I ran your build in a VM and was able to reproduce your issue there. This can be solved by upgrading to a newer version of Windows. I'm going to close the issue out since I'm confident that will solve your problem, if you run into any further issues please feel free to reopen! Thanks.

**Closed by mscraigloewen** 2019-07-24 21:16 UTC
