### ISSUE TITLE
WSL2 Converstion Failed with Error: 0x80041002

### ISSUE THREAD

**Issue by CodePunk-** [microsoft/WSL#5329] opened 2020-06-03 18:02 UTC
- Microsoft Windows 10 Pro, 10.0.19041 N/A Build 19041

- What you're doing and what's happening:
  - I have enabled and disabled multiple times the Windows Subsystem for Linux, Virtual Machine Platform, and Hyper-V features, but I get the same error every time.
  - I have reinstalled the WLS multiple times but the conversion always fails.
- What's wrong / what should be happening instead:
  - I am trying to convert my distro to wsl2, but I am getting the error: 0x80041002.
![image](https://user-images.githubusercontent.com/8890049/83668752-12f5d680-a596-11ea-8fe5-dd9d91c68a0c.png)

**Comment by afallenhope** [comment] 2020-06-04 16:04
Also receiving this.

- Microsoft Windows 10 Pro, 19041.264
- I've uninstalled everything and even tried to re-install and having the same issue.
- Now i can't even install an OS from MS Store :\

**Comment by benhillis** [comment] 2020-06-04 16:59
Interesting, I suspect the error code is indicating something wrong with us trying to use hvsockets to communicate with the guest.

Could one of you please take a [trace](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)?

**Comment by ifrond** [comment] 2020-06-04 21:19
i have took trace while trying to load subsytem for issue #5340 
[logs.zip](https://github.com/microsoft/WSL/files/4732772/logs.zip)

**Comment by CodePunk-** [comment] 2020-06-04 21:44
I installed Windows 10 on a different driver in the hopes of fixing the issue, but now I am getting error 0x800706d9. 
![Capture_2](https://user-images.githubusercontent.com/8890049/83813206-8c6af300-a682-11ea-94d8-a017f72a639f.PNG)
Here are my mine.
[logs1.zip](https://github.com/microsoft/WSL/files/4732864/logs1.zip).

**Comment by ifrond** [comment] 2020-06-04 22:15
ok. i have looked at logs and found error 
Error, 3, 10420, onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp, 1355, 0, 3, 10420, 0x80041002, HcnCreateNetwork failed (null), , , 1, 65,046756900
maybe it can be related to #4364 but i checked my 53 port and it is free 
+ Get-Process -Id (Get-NetUDPEndpoint -LocalPort 53).OwningProcess
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (53:UInt16) [Get-NetUDPEndpoint], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_LocalPort,Get-NetUDPEndpoint
also i have no docker at my host or any custom dns service

**Comment by dh13ker** [comment] 2020-06-06 05:47
Today!!! Before, more one week i use WSL2 fine! Today get a error: 
![Аннотация 2020-06-06 084306](https://user-images.githubusercontent.com/61443581/83937014-c72f7100-a7d1-11ea-9206-c56f54f9904a.png)
Reinstall WSL; Virtual Machine Platform; All network drivers - nothing helped.

**Comment by CodePunk-** [comment] 2020-06-06 06:33
I found the issue. In my case, it was the COMODO Firewall. I disabled its components multiple times before converting the WSL, but it seems the only way to fix the issue, was to remove it completely.

**Comment by dh13ker** [comment] 2020-06-06 14:18
Okey. Its problem in COMODO. WSL2 need a full access to WSL2 hosts(random)<->Loopback
IP 172.016.0.0 Mask 255.240.0.0 <-> IP 127.0.0.1 Mask 255.0.0.0
In comodo rules repaired all my WSL dist

**Comment by serak** [comment] 2020-06-10 07:11
on Windows build 19041.264 ,i dont have comodo or any antivirus apart from windows security center but i am still having this issue. and i dont also use docker on my PC. i only have vmware workstation 15.

**Comment by froilson** [comment] 2020-06-14 16:44
Hi, 
I'm on Windows 10 ver.2004 (19041.329) an have the exactly same issue with wsl 2, I can install all following all steps from this [](https://docs.microsoft.com/es-es/windows/wsl/install-win10).

All works good, the conversion to wsl2 but when reboot the system this error has shown all the time, uninstalling and reinstalling doesn't work and uninstall dnscrypt-proxy running on port 53 either.

Windows Events log shows this to errors:
SNP no pudo crear vmswitch con el error '0x80041002' y el id. de adaptador = '4861B171-DCCF-4DFC-B11E-BDAA4D5FF7D9'.

HNS-Network-Create :- 
 Id. de red = '{b95d0c5e-57d4-412b-b571-18a81a16e005}'.
 Tipo de red = 'ICS'.
  Código de resultado = '0x80041002'. 

I can't fix the error yet.

**Comment by afallenhope** [comment] 2020-06-16 00:15
> 
> 
> Okey. Its problem in COMODO. WSL2 need a full access to WSL2 hosts(random)<->Loopback
> IP 172.016.0.0 Mask 255.240.0.0 <-> IP 127.0.0.1 Mask 255.0.0.0
> In comodo rules has repaired all my WSL
> 
> Update: Today error repeated again. Hyper-V Virtual adapter cannot be created.
> 
> cmd.exe (Admin)
> net stop hns
> net start hns
> 
> ![Аннотация 2020-06-07 173006](https://user-images.githubusercontent.com/61443581/83971564-a3a91b00-a8e4-11ea-922d-89244aef5bd3.png)
> ![Аннотация 2020-06-07 173031](https://user-images.githubusercontent.com/61443581/83971569-ab68bf80-a8e4-11ea-8cbc-1e7b00cc33ef.png)
> 
> UPD: Comodo **v12.0.0.6882** working fine for me
> no BSOD, no system freezing, no errors in logs. Creating vSwitch working fine, WSL2 too.
> Winver: Windows 10, v2004 (19041.329) with installed all available updates on 6/10/2020.
> 
> Issue on Comodo forum: https://forums.comodo.com/bug-reports-cis/ethernet-adapter-vethernet-wsl-cant-create-with-installed-comodo-t125940.0.html

I'm having the issue too.
Can you share your COMODO  settings?
I disabled everything and then tried.. and I'm still getting issues.
Only works when I uninstall COMODO.

**Comment by dh13ker** [comment] 2020-06-16 09:51
> > Окей. Его проблема в COMODO. WSL2 нужен полный доступ к хостам WSL2 (случайным образом) <-> 
> > IP-адрес обратной связи 172.016.0.0 Маска 255.240.0.0 <-> IP-адрес 127.0.0.1 Маска 255.0.0.0 
> > В правилах comodo исправлены все мои WSL
> > Обновление: сегодня ошибка повторилась снова. Виртуальный адаптер Hyper-V не может быть создан.
> > cmd.exe (Администратор) 
> > net stop hns 
> > net start hns
> > ![Аннотация 2020-06-07 173006](https://user-images.githubusercontent.com/61443581/83971564-a3a91b00-a8e4-11ea-922d-89244aef5bd3.png)
> > ![Аннотация 2020-06-07 173031](https://user-images.githubusercontent.com/61443581/83971569-ab68bf80-a8e4-11ea-8cbc-1e7b00cc33ef.png)
> > UPD: Comodo **v12.0.0.6882** работает нормально, у меня 
> > нет BSOD, нет зависания системы, нет ошибок в логах. Создание vSwitch работает нормально, WSL2 тоже. 
> > Winver: Windows 10, v2004 (19041.329) с установленными всеми доступными обновлениями 10/10/2020.
> > Проблема на форуме Comodo: https://forums.comodo.com/bug-reports-cis/ethernet-adapter-vethernet-wsl-cant-create-with-installed-comodo-t125940.0.html
> 
> У меня тоже проблема
> Можете ли вы поделиться своими настройками COMODO (может быть, ваши зоны межсетевого экрана и порядок)?
> Я отключил все, а затем попытался .. и я все еще получаю проблемы.
> Работает только при удалении COMODO.

Comodo 12.0.0.6882 only work fine. Other versions NOT WORKING!
Add WSL zone 172.016.0.0 255.240.0.0
In global rulles allow In&OUT IP to WSL zone (172.016.0.0 255.240.0.0)

**Comment by gjf** [comment] 2020-06-18 10:05
Same issue for me. Cannot install anything.

# Environment

```
Windows build number: Microsoft Windows [Version 10.0.19041.329]
Your Distribution version: Kali and Ubuntu 20.04LTS
Whether the issue is on: WSL 2 (set as default)
```

# Steps to reproduce

1, Install distributive in Windows Appstore.
2. Start it to install into WSL.

#  Expected behavior

It should install.

# Actual behavior

It is not showing Error: 0x80041002 (WslRegisterDistribution failed with error: 0x80041002)

[logs.zip](https://github.com/microsoft/WSL/files/4797847/logs.zip)

**Comment by kinekt4** [comment] 2020-06-18 10:37
Comodo user here. I experienced the same issue as #5340 . 

I managed to resolve by disabling two settings:

* Auto-Containment (This setting I sometimes have to do with WSL1); And
* VirusScope

I have managed to do the following with no issues:

    sudo apt update
    sudo apt upgrade

Comodo Product Version: 12.2.2.7036

**Comment by gjf** [comment] 2020-06-18 10:42
> I managed to resolve by disabling two settings:
> 
> * Auto-Containment (This setting I sometimes have to do with WSL1); And
> * VirusScope
> 

Nope, did not help.

**Comment by kinekt4** [comment] 2020-06-18 10:44
> Nope, did not help.

Did you uninstall/re-install Ubuntu first?

**Comment by gjf** [comment] 2020-06-18 10:47
> > Nope, did not help.
> 
> Did you uninstall/re-install Ubuntu first?
> 
> I would suggest:
> 
> * Uninstall Ubuntu
> * Disable the two settings above
> * Re-install ubuntu
> * Run commands

I have installed it already using WSL 1, now I can simply try to convert it to WSL 2 to observe the error.
And again: these two settings were disabled from the beginning.

**Comment by kinekt4** [comment] 2020-06-19 01:13
I retract my **fix**. It doesn't help. I likely ran the commands in WSL1 mode.

I would like to note the following though:

    # Show Default
    PS C:\Users\user> wsl --list
    Windows Subsystem for Linux Distributions:
    Ubuntu-20.04 (Default)

    # Show version
    PS C:\Users\user> wsl --list --verbose
      NAME            STATE           VERSION
    * Ubuntu-20.04    Stopped         1

    # No Error
    PS C:\Users\user> wsl --set-default-version 2
    For information on key differences with WSL 2 please visit https://aka.ms/wsl2

    # Error
    PS C:\Users\user> wsl --set-version Ubuntu-20.04 2
    Conversion in progress, this may take a few minutes...
    For information on key differences with WSL 2 please visit https://aka.ms/wsl2
    Error: 0x80041002

Note that setting

**Comment by gjf** [comment] 2020-06-19 08:55
@kinekt4 I can even add more.
After creation of Linux in WSL 1 you cannot open it in //wsl$/kali-linux (or any name - it depends what distributive you have installed).
After execution of wsl --set-version kali-linux 2 you will get an error, but //wsl$/kali-linux appears.

**Comment by Searinox** [comment] 2020-06-20 20:35
Another COMODO user here, getting this error when attempting to install Ubuntu.

**Comment by theAkito** [comment] 2020-06-25 10:04
I had Debian WSL2 installed for good. It worked perfectly and I had already plenty experience with WSL1.

Yesterday, I installed Comodo Internet Security Premium. After the second PC restart I hit this error and WSL became unusable. I turned off most Comodo features, reset some settings in it, but after an additional restart the problem still appears.

What to do?

**Comment by gjf** [comment] 2020-06-25 10:47
@theAkito Me too - and I even started the thread to discuss all Comodo's bugs: https://forums.comodo.com/news-announcements-feedback-cis/haters-scream-t126009.0.html

The only way is to:
1. Downgrade Comodo
2. Do not install/convert WSL 2 (my option)
3. Wait until Comodo will release an update.

**Comment by theAkito** [comment] 2020-06-25 10:51
@gjf 
I agree with the most part you wrote in that topic.

Confirming your concerns, I cannot revert to your workaround.

The sole purpose I even upgraded my Windows version to the most currernt one is only WSL2. I need the quasi native Docker support, etc. So uninstallation of COMODO was the only option for me, after all.

However, I have been using COMODO since years and I never was this disappointed. I think it is still way better than most competitors out there. Look at Avast and Norton for example. They block games and create unforeseen/unexpected errors since so many years. So, at least comparatively, COMODO is not that bad.

**Comment by gjf** [comment] 2020-06-25 11:02
@theAkito 
I was so happy with introduction WSL2 having possibility to test kernel modules - and what a surprise!
I remember Comodo when it was a really good solution with fast and intuitive interface. 
And now...
Damned marketing...

**Comment by Jurigag** [comment] 2020-07-22 20:22
I updated comodo to 7036 version which was supposed to work but still it doesn't :/

**Comment by Searinox** [comment] 2020-07-22 21:46
https://forums.comodo.com/bug-reports-cis/ethernet-adapter-vethernet-wsl-cant-create-with-installed-comodo-t125940.0.html

**Comment by Jurigag** [comment] 2020-07-22 21:54
So they didn't add it basically? Well removed comodo for now because WSL2 is way too great.

**Comment by 3941** [comment] 2020-08-03 21:57
You must have misread that post... They said the problem is IN 7036 and will be fixed in the NEXT version, which isn't out yet.

**Comment by sounakofficial** [comment] 2020-08-10 22:14
Hey so i found a workaround that worked for me. Please try it and give feedback if it works. 

1. I disabled the wsl feature and virtual machine platform
2. restarted and cleaned the registry with ccleaner
3. Re-enable 2 features mentioned in point no 1 and restart

it did the work for me.

**Comment by dh13ker** [comment] 2020-08-11 03:53
> Hey so i found a workaround that worked for me. Please try it and give feedback if it works.
> 
> 1. I disabled the wsl feature and virtual machine platform
> 2. restarted and cleaned the registry with ccleaner
> 3. Re-enable 2 features mentioned in point no 1 and restart
> 
> it did the work for me.

Really? Reboot more two times and ... it will not work for u.

**Comment by sounakofficial** [comment] 2020-08-11 05:13
> > Hey so i found a workaround that worked for me. Please try it and give feedback if it works.
> > 
> > 1. I disabled the wsl feature and virtual machine platform
> > 2. restarted and cleaned the registry with ccleaner
> > 3. Re-enable 2 features mentioned in point no 1 and restart
> > 
> > it did the work for me.
> 
> Really? Reboot more two times and ... it will not work for u.

Nope it's been solid through multiple reboots for me. I have been using the wsl2 back-end for docker, so I'm pretty sure wsl2 is working.

**Comment by sajithneyo** [comment] 2020-08-14 10:46
With the recent windows update, WSL started throwing this error. Docker also fails as WSL 2 backend is enabled.

**Comment by moikkasisu** [comment] 2020-08-15 13:31
Hi, @CodePunk- @gjf  have you got a fix for the error? i am new here, I am experiencing the same thing. i could not set wsl as default 2, so i had to install Ubuntu on wsl 1 first, then i manually installed wsl_update, but still could not use the command in powershell to convert Ubuntu-20.04 to wsl 2

**Comment by gjf** [comment] 2020-08-15 13:35
Nope. Comodo have to release a fix. But they didn't yes because of lack of good coders.

**Comment by moikkasisu** [comment] 2020-08-15 13:36
> With the recent windows update, WSL started throwing this error. Docker also fails as WSL 2 backend is enabled.
hi @sajithneyo  have you fixed your error? do u have any suggestion (other than )


> Nope. Comodo have to release a fix. But they didn't yes because of lack of good coders.

I am not even using Comodo :(....

**Comment by CodePunk-** [comment] 2020-08-15 22:45
> 
> 
> Hi, @CodePunk- @gjf have you got a fix for the error? i am new here, I am experiencing the same thing. i could not set wsl as default 2, so i had to install Ubuntu on wsl 1 first, then i manually installed wsl_update, but still could not use the command in powershell to convert Ubuntu-20.04 to wsl 2

For me, it was the Comodo Firewall app. I uninstalled it, and I haven't had this issue since. Some people on this thread have mention that stopping any services running on port 53 solved it for them. You could running the line below and try terminating the program. Hope that helps.

`Get-Process -Id (Get-NetUDPEndpoint -LocalPort 53).OwningProcess`

**Comment by moikkasisu** [comment] 2020-08-16 03:58
> > Hi, @CodePunk- @gjf have you got a fix for the error? i am new here, I am experiencing the same thing. i could not set wsl as default 2, so i had to install Ubuntu on wsl 1 first, then i manually installed wsl_update, but still could not use the command in powershell to convert Ubuntu-20.04 to wsl 2
> 
> For me, it was the Comodo Firewall app. I uninstalled it, and I haven't had this issue since. Some people on this thread have mention that stopping any services running on port 53 solved it for them. You could running the line below and try terminating the program. Hope that helps.
> 
> `Get-Process -Id (Get-NetUDPEndpoint -LocalPort 53).OwningProcess`

hi @CodePunk- really appreciate your help...I was not sure about UDP port 53, so I only changed the "allow app through firewall (windows defender...)", i ticked allow Virtual Machine Monitoring - private. Then actually it did not work either, but I out-of-blue installed Windows Terminal....then i thought ok, let me try in VM (I opened my VMware Windows VM to test installing in the same way), while I was waiting for updating that VM, I install another openSUSE from Windows store, SUSE worked on WSL2...so I tried to install Ubuntu 20.04 LTS again, this time it works this time!  - sorry for my lengthy narrative. Thank you very much everyone

**Comment by tarohida** [comment] 2020-09-30 06:27
I encountered this error when trying to install WSL2 on my company PC.
The user account on my PC is managed in the company's Active Directory and has no administrative rights (let's call it a "User account"). I usually work by using the "User account".
So, when I needed administrative privileges, I would enter the information for the account with administrative privileges (let's call it the "Manager account") into the prompt and run it with administrative privileges.
When I tried to enable WSL that way, it failed with the following error.

````
Error: 0x80041002
````

I asked the AD administrator to grant me administrator privileges, but they did not allow it.
I logged into my local machine with a "Manager account" and went through the WSL2 activation process.

The setup under "Manager account" completed successfully without the above error.

Then I performed the WSL2 switchover procedure again with a user account without my administrative privileges, and the process was completed successfully.

In the past, I have repeated the setup procedure three times with user accounts, but it did not work like this. It's common for people to inadvertently skip the steps, but I believe this time is different.

I can't be sure, but I suspect that if you are using an account that doesn't have administrative privileges and you enter the information for an account with administrative privileges into the prompts each time, the setup won't complete properly.

I hope this experience is helpful.

Reference documentation: https://docs.microsoft.com/en-us/windows/wsl/install-win10

Enviroment: Windows10 Professional, Version 1909, Build 18363

Installed Ubuntu App: [Ubuntu20.04](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6)

**Comment by wsyxbcl** [comment] 2020-09-30 11:42
I encountered with this Error after enabling **Prevent Installation of Devices not described by other policy settings** in Local Group Editor. Though I don't know why, WSL2 works again after changing it back to 'Not configured'.

**Comment by Lauri-Nomme** [comment] 2020-09-30 12:24
> **Prevent Installation of Devices not described by other policy settings**

Hi, I was able to track down which devices wsl2 is trying to install: `ROOT\VMS_VSMP\0000` and `ROOT\VMS_MP\0000`.
Those can be whitelisted in 'Allow installation of devices that match any of these device instance IDs'

**Comment by moikkasisu** [comment] 2020-10-04 16:33
It is unconfigured in my setting: Prevent Installation of Devices not described by other policy settings. 
2mths ago, i was able to install ubuntu on wsl2 with some luck, but a few weeks ago, after some windows update, not sure which one, ubuntu stopped working, and i could not reinstall it, still this same error message.... i just installed the preview form of Windows 10 May 2020 Update KB4577063 , still not working.

**Comment by RootAndroid58** [comment] 2020-10-11 10:55
> ok. i have looked at logs and found error
> Error, 3, 10420, onecore\vm\wsl\lxss\service\lib\utilityvmcontext.cpp, 1355, 0, 3, 10420, 0x80041002, HcnCreateNetwork failed (null), , , 1, 65,046756900
> maybe it can be related to #4364 but i checked my 53 port and it is free
> 
> * Get-Process -Id (Get-NetUDPEndpoint -LocalPort 53).OwningProcess
> * ```
>                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>   
>   * CategoryInfo          : ObjectNotFound: (53:UInt16) [Get-NetUDPEndpoint], CimJobException
>   * FullyQualifiedErrorId : CmdletizationQuery_NotFound_LocalPort,Get-NetUDPEndpoint
>     also i have no docker at my host or any custom dns service

I am really confused i dont use Comodo Firewall i just use default windows firewall can you help me to solve that error

```
C:\WINDOWS\system32>wsl --set-version  Ubuntu-20.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Error: 0x80041002
```

**Comment by maminkhanpour** [comment] 2020-11-03 15:49
> 
> 
> Hey so i found a workaround that worked for me. Please try it and give feedback if it works.
> 
>     1. I disabled the wsl feature and virtual machine platform
> 
>     2. restarted and cleaned the registry with ccleaner
> 
>     3. Re-enable 2 features mentioned in point no 1 and restart
> 
> 
> it did the work for me.

I can confirm that this method work

**Comment by LeandroFrazao** [comment] 2020-11-04 14:21
Still having the same problem here. Error: 0x80041002

**Comment by jeanmonet** [comment] 2020-11-13 21:38
For those with Comodo on their system, installing the beta version from this link should work (note instructions for the host file): https://forums.comodo.com/beta-corner-cis/first-impressions-of-cis-v12227062-unofficial-release-topic-t126297.0.html

**Comment by ste93cry** [comment] 2020-11-13 21:46
I tried the beta, and although it (almost always, there are still random times it doesn't) solves the problem of the Hyper-V NIC not being created at boot time I still cannot get WSL working because a second NIC should be created and Comodo prevents this from happening. Unfortunately it's so sad to see that Comodo developers seems to not really be focused on fixing this as it's months that this bug has been reported on their forums and nothing changed

**Comment by jeanmonet** [comment] 2020-11-14 09:57
@ste93cry  I declared victory too quickly. After a few restarts, WSL2 doesn't start, same error. I'm just uninstalling Comodo now.

**Comment by sponnusa** [comment] 2020-12-01 05:59
> @ste93cry I declared victory too quickly. After a few restarts, WSL2 doesn't start, same error. I'm just uninstalling Comodo now.

Yep. That's the only way forward. I did the same the error is gone now. I'm articulating to install an older version of comodo and disabling the update feature. Will update the progress here. Thanks.

**Comment by gjf** [comment] 2020-12-01 08:57
The most interesting: Comodo released an update 12.2.2.7062, but the bug still is not fixed. Pity...

**Comment by Searinox** [comment] 2020-12-01 09:15
It was not in the changelog that .7062 would fix it. And either way they have been notified that the issue does persist.

**Comment by Ryonez** [comment] 2020-12-01 09:28
Given the issues has been present for half a year, and they have some code where they know it worked alright, I'm not really confident that it's something they even care to fix.

Currently I've just yeeted Comodo. As much as I loved it, breaking windows components to they point they can't be used at all is a no no for me.

**Comment by gjf** [comment] 2020-12-01 09:53
Yeah, this bug that definetely was fixed in latest build is much more vital
[No welcome screen at startup](url=No welcome screen at startup)

**Comment by vanelk** [comment] 2020-12-05 17:45
I had the same issue I had to downgrade wsl 2 to wsl 1 and then install ubuntu again.
- run `wsl --set-default-version 1` to downgrade and try reinstalling your distro

**Comment by sponnusa** [comment] 2020-12-06 19:17
For people who need firewall, I recommend TinyWall. Though not as intuitive like comodo allow / reject popups, it does work fantastic with WSL. So far no issues and and it has been working with other application combinations. Check it out.

**Comment by Searinox** [comment] 2020-12-09 11:31
[Some good news for COMODO users.](https://forums.comodo.com/bug-reports-cis/ethernet-adapter-vethernet-wsl-cant-create-with-installed-comodo-t125940.0.html;msg904200#msg904200)

**Comment by DaClone** [comment] 2020-12-15 05:18
I updated to the latest version of COMODO, still getting this error when trying to install Ubuntu on WSL2, so perhaps is not quite fixed after all...

**Comment by Searinox** [comment] 2020-12-15 08:06
> I updated to the latest version of COMODO, still getting this error when trying to install Ubuntu on WSL2, so perhaps is not quite fixed after all...

Read the post. It will be fixed in an update. Version 12.2.2.7062 was already out when this was stated. There is yet no update out.

**Comment by DaClone** [comment] 2020-12-15 09:29
> > I updated to the latest version of COMODO, still getting this error when trying to install Ubuntu on WSL2, so perhaps is not quite fixed after all...
> 
> Read the post. It will be fixed in an update. Version 12.2.2.7062 was already out when this was stated. There is yet no update out.

My bad, I thought it referenced the latest update but it is not... guess I'll have to wait

**Comment by ksrjcons** [comment] 2020-12-26 15:49
If you are using Comodo as your anti-virus / firewall, forget about anything else. That is where your issue is. See this link for what to do. It worked for me. https://forums.comodo.com/bug-reports-cis/ethernet-adapter-vethernet-wsl-cant-create-with-installed-comodo-t125940.0.html

**Comment by BlueNoob** [comment] 2021-03-03 07:40
https://docs.microsoft.com/zh-cn/windows/wsl/install-win10
=======================================
wsl --set-version kali-linux 2
ERROR: 0x80041002
=======================================
wsl --list --online
My wsl has no commont of "--online"
=======================================
wsl product version: 10.0.19041.488
wsl file version: 6.2.190401.488 
winver: Vsersion 20H2 (19042.804)

**Comment by BlueNoob** [comment] 2021-03-03 07:58
> ```
> https://docs.microsoft.com/zh-cn/windows/wsl/install-win10
> =======================================
> wsl --set-version kali-linux 2
> ERROR: 0x80041002
> =======================================
> wsl --list --online
> My wsl has no commont of "--online"
> =======================================
> wsl product version: 10.0.19041.488
> wsl file version: 6.2.190401.488 
> winver: Vsersion 20H2 (19042.804)
> ```

COMODO FIREWALL version: 12.2.2.7098

**Comment by BlueNoob** [comment] 2021-03-03 08:00
https://docs.microsoft.com/windows/wsl/install-win10
=======================================
wsl --set-version kali-linux 2
ERROR: 0x80041002
=======================================
wsl --list --online
My wsl has no commont of "--online"
=======================================
wsl product version: 10.0.19041.488
wsl file version: 6.2.190401.488 
winver: Vsersion 20H2 (19042.804)
=======================================
COMODO FIREWALL version: 12.2.2.7098

**Comment by BlueNoob** [comment] 2021-03-03 08:00
```
https://docs.microsoft.com/windows/wsl/install-win10
wsl --set-version kali-linux 2
ERROR: 0x80041002
wsl --list --online
My wsl has no commont of "--online"
wsl product version: 10.0.19041.488
wsl file version: 6.2.190401.488
winver: Vsersion 20H2 (19042.804)
COMODO FIREWALL version: 12.2.2.7098
```

**Comment by BlueNoob** [comment] 2021-03-03 08:05
> Interesting, I suspect the error code is indicating something wrong with us trying to use hvsockets to communicate with the guest.
> 
> Could one of you please take a [trace](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs)?

Do you wanna follow my issue? I can give you more logs or remote desktop to find out the problem and resolve it.

**Comment by nulman** [comment] 2021-03-30 21:55
comodo FINALLY [released an update](https://forums.comodo.com/news-announcements-feedback-cis/comodo-internet-security-2020-v12228012-released-t126945.0.html) which specifically claims to solve the issue (And it does for me).

> Fixed
> - WSL 2 can not work when install CIS

**Comment by Ryonez** [comment] 2021-03-30 21:59
> comodo FINALLY [released an update](https://forums.comodo.com/news-announcements-feedback-cis/comodo-internet-security-2020-v12228012-released-t126945.0.html) which specifically claims to solve the issue (And it does for me).
> 
> > Fixed
> > 
> > * WSL 2 can not work when install CIS

If only it wasn't nearly a year later, long after I stopped using Comodo because of this issue.

**Comment by sandrix** [comment] 2021-04-21 02:01
Confirmed that version CFW 12.2.2.8012 is working fine with WSL2

**Comment by rajatshenoy56** [comment] 2021-04-22 11:07
> Hey so i found a workaround that worked for me. Please try it and give feedback if it works.
> 
> 1. I disabled the wsl feature and virtual machine platform
> 2. restarted and cleaned the registry with ccleaner
> 3. Re-enable 2 features mentioned in point no 1 and restart
> 
> it did the work for me.

This worked for me too. I guess I had changed something in the registry earlier which might have caused this problem.

**Comment by zhuweiji** [comment] 2021-06-14 03:06
> I had the same issue I had to downgrade wsl 2 to wsl 1 and then install ubuntu again.
> 
> * run `wsl --set-default-version 1` to downgrade and try reinstalling your distro

worked for me

**Comment by bot202102** [comment] 2021-06-18 21:05
Use comodo firewall 12.2.2.8012
worked for me

**Comment by j-a-h-i-r** [comment] 2021-07-23 12:37
I don't use the comodo firewall and the WSL update to version 2 is still showing this error.

```
wsl --set-version Ubuntu-20.04 2
```

Shows `WSL2 Converstion Failed with Error: 0x80041002`

**Comment by bot202102** [comment] 2021-07-23 12:41
> I don't use the comodo firewall and the WSL update to version 2 is still showing this error.
> 
> ```
> wsl --set-version Ubuntu-20.04 2
> ```
> 
> Shows `WSL2 Converstion Failed with Error: 0x80041002`

Upgrade to comodo 12.2.2.7098

**Comment by hamzaelgannouni** [comment] 2021-08-09 23:42
I had the same problem.  I got it to work by setting the WSL version to 1 via PowerShell:

wsl --set-default-version 1

I did want to use version 2, but having version 1 is better than nothing.

**Comment by Ryonez** [comment] 2021-08-10 05:37
> I had the same problem. I got it to work by setting the WSL version to 1 via PowerShell:
> 
> wsl --set-default-version 1
> 
> I did want to use version 2, but having version 1 is better than nothing.

Comodo is meant to have fixed the issue in an update, this workaround shouldn't be required anymore @hamzaelgannouni 

That fix though took around a year as far as I know to come out. And I made the decision after trying to live with it for a while that software that interferes with the os in a way it's not meant to isn't worth using when the devs don't really care to fix it. And giving the amount of time it took, I read it as they didn't. So I haven't been using Comodo for a long time now.

If the latest version is screwing things up again then it really didn't last long.

**Comment by musabgultekin** [comment] 2021-08-18 09:11
I fixed it by doing this:
- Enable Vritualization in bios
- wsl --set-default-version 1
- Install ubuntu
- wsl --set-version ubuntu 2
- wsl --set-default-version 2

**Comment by micenote** [comment] 2021-09-04 15:33
> I fixed it by doing this:
> 
> * Enable Vritualization in bios
> * wsl --set-default-version 1
> * Install ubuntu
> * wsl --set-version ubuntu 2
> * wsl --set-default-version 2

not worked! mei luan yong!

**Comment by b-hayes** [comment] 2021-11-03 07:20
Running current distro on machine that has been fine for a year, suddenly stopped working.
Uninstalling and reinstalling proved impossible.
Installed WSL on a brand new machine app store refuses to download.
Install via comandline Error: 0x80041002 (null)

Nothing I do on any windows machine right now can get me a working copy of WSL. I cant do my job thanks windows.

**Comment by ScullKeith** [comment] 2022-01-15 03:15
> 

Dude, he said he doesn't use Comodo..

**Comment by ScullKeith** [comment] 2022-01-15 18:28
> > > I don't use the comodo firewall and the WSL update to version 2 is still showing this error.
> > > ```
> > > wsl --set-version Ubuntu-20.04 2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Shows `WSL2 Converstion Failed with Error: 0x80041002`
> > 
> > 
> > Upgrade to comodo 12.2.2.7098
> 
> Upgrade to latest version 12.2.2.8012 As COMODO team wrote WSL2 related issue is fixed in this version. https://forums.comodo.com/news-announcements-feedback-cis/comodo-internet-security-2020-v12228012-released-t126945.0.html
> 
> I personally tested and confirm issue is fixed in this release of COMODO

Dude.. he said he doesn't use Comodo; you're suggesting he upgrade his version of Comodo rofl

**Comment by demius** [comment] 2022-03-02 13:50
In my case, I seemed to have had a previously registered Hyper-V switch lying around. Don't shoot more for this, because I have no idea what that has to do with the price of eggs, but I stumbled upon this helpful magical "FixStuff" tool from Microsoft which resolved the issue: https://docs.microsoft.com/en-us/troubleshoot/windows-client/virtualization/cannot-create-hyper-v-virtual-switch

**Comment by XJIOP** [comment] 2022-03-03 11:02
> In my case, I seemed to have had a previously registered Hyper-V switch lying around. Don't shoot more for this, because I have no idea what that has to do with the price of eggs, but I stumbled upon this helpful magical "FixStuff" tool from Microsoft which resolved the issue: https://docs.microsoft.com/en-us/troubleshoot/windows-client/virtualization/cannot-create-hyper-v-virtual-switch

MicrosoftEasyFix20159.mini.diagcab not working, not supported with Windows version. (Windows 10 x64 20H2)

**Comment by sillasbernardo** [comment] 2022-03-07 02:56
So I had the same issue with my wsl2 installation and I dig deep until I found what the error 0x80041002 means. It basically means that the wsl2 couldn't create a Hyper-V Virtual Ethernet Adapter. This error doesn't come from wsl2, it comes from Hyper-V as shown in the event viewer. 

First you NEED Hyper-V enabled, and second check if you have another vm adapter such as Oracle or vmware. In my case what happened was that I installed vmware in a second hard drive and I removed the HD from my PC, since the vmware ethernet adapter couldn't find the source and IT'S linked to my Realtek physical controller, it somehow was making it impossible for Hyper-V to create a link as well.

Let's say that whatever virtual machine you use WILL use your physical controller as a link and if one of your virtual adapter is failing, it will block others from linking as well.

So check if a vmware, oracle, VPN or anything is interfering with your physical controller because that's what the code 0x80041002 means. Once more: "It can't create a virtual ethernet adapter from the physical controller because something is blocking it from doing"

**Comment by OsamaAbdelhameed** [comment] 2022-09-09 11:51
I want wsl2 for docker desktop and I got this error for more than a week, I don't have comodo and Ubunto is not allowing me to set it to 2

**Comment by AmroAbdrabo** [comment] 2022-12-17 09:50
The answer from sillasbernardo led me to right clicking on the VMWare executable installer file and then repair, and then it worked.

**Closed** 2024-02-01 12:17 UTC
Labels: failure-to-launch

**Comment by hionwi** [comment] 2024-04-19 02:20
Using the registry to disable the firewall can also cause this problem, enabling it can solve it.

**Comment by AbdelrhmanUZaki** [comment] 2024-07-24 23:40
> I fixed it by doing this:
> 
> * Enable Vritualization in bios
> * wsl --set-default-version 1
> * Install ubuntu
> * wsl --set-version ubuntu 2
> * wsl --set-default-version 2

## This works!
### Steps to Upgrade WSL 1 to WSL 2

Run Command Prompt as Administrator
   ```cmd
   wsl --set-default-version 1
   ```
Download and Install Ubuntu from the Microsoft Store.

Check WSL Version:

```cmd
wsl --list --verbose
```

Upgrade to WSL 2:

```cmd
wsl --set-version Ubuntu-22.04 2
```

Error:

>Failed to configure network (networkingMode Nat). To disable networking, set `wsl2.networkingMode=None` in C:\Users\YOUR_USERNAME\\.wslconfig
Error code: Wsl/Service/CreateVm/ConfigureNetworking/HNS/0x80041002

Create or Edit .wslconfig in C:\Users\YOUR_USERNAME\:

```ini
[wsl2]
networkingMode=None
```

Shutdown WSL and Retry the Conversion:

```cmd
wsl --shutdown
wsl --set-version Ubuntu-22.04 2
```
Verify the Conversion:

```cmd
wsl --list --verbose
```
Output Should Be:

>NAME            STATE           VERSION
>Ubuntu-22.04    Stopped         2
