### ISSUE TITLE
[Query] Unable to connect via OpenSSH

### ISSUE THREAD

**Issue by Vivraan** [microsoft/WSL#5869] opened 2020-09-07 04:50 UTC
## Info

**Edition/Version/Build:**  Windows 10 Home/2004/19041.450
**WSL version:** 2
**WSL distro:** Ubuntu 20.04

## Issue
I'm assuming that some forwarding or tunnelling is not occurring since I can connect to the requested remote through Windows LibreSSL but not through the WSL OpenSSL.

What I get on WSL is
```
ssh -v mukherjee@192.168.1.49
OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.1.49 [192.168.1.49] port 22.
debug1: connect to address 192.168.1.49 port 22: Network is unreachable
ssh: connect to host 192.168.1.49 port 22: Network is unreachable
```

However, this was working perfectly only a few days ago when I was using an ethernet connection on the remote and with the address for the ethernet connection set as 192.168.1.64 (which I'd queried from the remote).

**Comment by therealkenc** [comment] 2020-09-09 02:30
> I cannot connect to the requested remote through Windows LibreSSL but not through the WSL OpenSSL.

Assume you mean **can** connect with win32 LibreSSL, or the 'but' doesn't make sense in the sentence above.

There is no way to tell what externality changed between "only a few days ago". There is no path to reproduce this. Please collect [WSL logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-collect-wsl-logs) and post the backlink to the feedback item here. Also please identify any third-party networking software that has been installed on Windows. Also your build number, and whether you are running WSL1 or WSL2, per the template that was deleted.

**Comment by Vivraan** [comment] 2020-09-09 06:19
> Also please identify any third-party networking software that has been installed on Windows.

@therealkenc could you give me examples of such software? Are VPNs such software? I believe I don't have anything like this running at the moment.

**Comment by Vivraan** [comment] 2020-09-09 06:21
> > I cannot connect to the requested remote through Windows LibreSSL but not through the WSL OpenSSL.
> 
> Assume you mean **can** connect with win32 LibreSSL, or the 'but' doesn't make sense in the sentence above.

Indeed - I've fixed the grammar!

**Comment by Vivraan** [comment] 2020-09-09 06:27
I'll update the WSL Log once I re-enable virtualisation on my machine.

**Comment by therealkenc** [comment] 2020-09-09 06:44
> Could you give me examples of such software? Are VPNs such software?

Usually VPNs. Anti-virus software. Anything that might cause your setup to not work, but a clean Windows install to be okay.

If you updated windows and there is no route to _anywhere_ (`ping 1.1.1.1`), there are a few open issues from people experiencing that. If you are only having trouble reaching `192.168.1.49` on your LAN, then I unfortunately have no guesses as to what changed in your environment since a few days ago.

**Comment by Vivraan** [comment] 2020-09-09 07:26
`ping 1.1.1.1` works from Powershell.

I'll update the WSL Logs, they will be more relevant.

**Comment by therealkenc** [comment] 2020-09-09 08:10
> ping 1.1.1.1 works from Powershell.

I take that to mean you can't access the network at all from WSL. Cannot access anywhere on the Internet.

What is the output of:

```
$ ip address
$ ip route
```

That will at least show the state of your WSL network. If you've got a Windows backup you can roll back to ("a few days ago") that might be one option to try. Desperate measures....

**Comment by Vivraan** [comment] 2020-09-09 11:33
I think I haven't set up backups on this machine. I do remember that when I had tried connecting to the remote using its ethernet address (not the wireless LAN one) it had worked.

**Comment by Vivraan** [comment] 2020-09-09 11:34
> What is the output of:
> 
> ```
> $ ip address
> $ ip route
> ```
> 
> That will at least show the state of your WSL network.
> 

```
virnrvrul@NARVRUL:/mnt/c/Users/shiva$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether c2:8b:5a:cb:9a:e5 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 8a:27:8e:47:30:82 brd ff:ff:ff:ff:ff:ff
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:0c:43:0d brd ff:ff:ff:ff:ff:ff
    inet 172.20.92.235/20 brd 172.20.95.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fe0c:430d/64 scope link
       valid_lft forever preferred_lft forever
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
virnrvrul@NARVRUL:/mnt/c/Users/shiva$ ip route
default via 172.20.80.1 dev eth0
172.20.80.0/20 dev eth0 proto kernel scope link src 172.20.92.235
```

**Comment by Vivraan** [comment] 2020-09-09 11:41
@therealkenc Strangely, the connection seems to be working now. Very odd.

Should I send a log regardless?

**Comment by therealkenc** [comment] 2020-09-09 12:52
Not if it is working, no. Happy to hear you are live. If it goes down again, you could collect logs in a fail condition. Better would be to try to figure out what is changing. Could be network related. Some software running or not running. There isn't enough to work with here to guess.

**Comment by Vivraan** [comment] 2020-09-09 17:20
Should I close the issue or wait for a failure and report back?

**Comment by therealkenc** [comment] 2020-09-09 18:01
Close the issue once you are satisfied it is working. When is up to you.

**Closed** 2021-01-27 22:39 UTC
Labels: network
