### ISSUE TITLE
Unable to immediately start typing after starting new window from context menu

### ISSUE THREAD

**Issue by wkbrd** [Microsoft/WSL#2597] opened 2017-10-24 23:54 UTC
Starting a new Ubuntu/openSUSE window from the context menu does not allow for immediate text entry.  The legacy "bash on Ubuntu on Windows" does not exhibit this problem and allows for immediate text input.  A workaround is to click the window using the mouse, touch the window, or switch windows using Alt-Tab and back.

* Your Windows build number:   10.0.16299.19

* What you're doing and what's happening:  
Right-click on Ubuntu or openSUSE taskbar icon.  Click on application name (e.g., Ubuntu).  Console window appears.  Then try to immediately type something, like "ls".  The text entered does not appear in the console window.

* What's wrong / what should be happening instead:
The text input should appear in the window rather than being lost.

* Strace of the failing command, if applicable:  N/A

**Comment by wkbrd** [comment] 2017-11-07 12:57
Additionally, when opening the console window as reproduced above, the window appears to not be the focused window (as it does not contain the accent color around the edge of the window).

**Comment by wkbrd** [comment] 2017-11-12 17:03
FYI, this also reproduces with 10.0.17035.1000.

**Comment by wkbrd** [comment] 2018-03-18 14:04
Update: This still reproduces with 10.0.17123.1.

**Comment by wkbrd** [comment] 2018-05-08 21:39
Update: This still reproduces with 10.0.17134.1.

**Comment by DarthSpock** [comment] 2018-05-15 13:51
@zadjii-msft probably hasn't been made aware since this wasn't correctly filed in [Console](https://github.com/Microsoft/Console)

**Comment by patrikhuber** [comment] 2018-05-15 13:56
Still repros in 10.0.17134.48.

**Comment by zadjii-msft** [comment] 2018-05-15 16:16
(For the record, I'm not triaging the WSL github page anymore - any console issues should be filed over at https://github.com/Microsoft/Console)

I'm not seeing this repro on 17670 (internally) but that doesn't necessarily mean it's fixed. It's definitely not behavior that we control - it sounds like the shell has decided not to focus our window in that case. I can keep an eye out for it.

**Comment by patrikhuber** [comment] 2018-05-15 21:40
@DarthSpock Oh well I am sorry that I asked where to report a bug and that I do not know what "Console" is or how it is related to WSL...

**Comment by zadjii-msft** [comment] 2018-05-15 21:45
The "Console", or `conhost.exe`, is the window that runs all commanline applications in Windows. So bash, cmd, powershell, they're all running attached to conhost.exe, which is responsible for rendering the "terminal".

https://github.com/microsoft/console is "the official Windows Console issues & samples repo", for all your console related issues. We used to have both console and WSL issues in the WSL repo, but that ended up creating a lot of extra noise for both teams, so we've pulled them apart now.

**Comment by patrikhuber** [comment] 2018-05-15 21:53
@zadjii-msft Cool! Thank you very much for the explanation! :-)

**Comment by bitcrazed** [comment] 2018-05-17 22:47
Thanks for reporting this issue @patrikhuber. Appreciate your patience - we have several repo's & try to direct issues to the teams that most closely own/relate to the issue at hand.

As @zadjii-msft states, Windows Console == the Terminal app on Linux or Mac. Console is responsible for sending keystrokes & input to the command-line app/tool/shell (e.g. Cmd, PowerShell, Linux/WSL) that it's connected to, and for rendering the text returned by the app/tool/shell.

I can confirm that I can repro this issue and will work with @zadjii-msft to debug and diagnose. We'll reply in the https://github.com/Microsoft/console/issues/179 issue.

Closing this issue - please follow the master thread here: https://github.com/Microsoft/console/issues/179

**Closed by bitcrazed** 2018-05-17 22:47 UTC
Labels: external

**Comment by mariusstrom** [comment] 2018-08-17 02:48
@zadjii-msft FYI I'm also at MSFT and I have a repro. Feel free to ping me on corpnet if you need to see a repro.

**Comment by bitcrazed** [comment] 2018-08-17 20:43
Thanks for the info @mariusstrom - but please note - this issue in this repo is not being monitored by the Console team. Please head over to the Microsoft/console#179 issue to track progress.
