### ISSUE TITLE
Cannot upgrade to wsl2, black screen on restart

### ISSUE THREAD

**Issue by Pika-Pool** [microsoft/WSL#7887] opened 2022-01-03 15:16 UTC
### Version

Microsoft Windows [Version 10.0.19044.1415]

### WSL Version

- [x] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 4.4.0-19041-Microsoft

### Distro Version

Ubuntu-20.04

### Repro Steps

Followed the instructions at https://docs.microsoft.com/en-us/windows/wsl/install-manual

- Enable the Windows Subsystem for Linux
`dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart`

- Enable Virtual Machine feature
`dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`

- Restart machine

### Expected Behavior

System restarts and I'm able to upgrade to wsl2

### Actual Behavior

- on restart, the screen hangs at a black screen indefinitely
- I have to boot into safe mode to run `dism.exe /enable-feature /featurename:VirtualMachinePlatform` to be able to use my machine again

WSL1 does work perfectly fine though

**Comment by ndrewtl** [comment] 2022-06-15 16:46
I'm experiencing this as well. My ASUS laptop has a black screen and the fans go furiously when I try to install WSL 2. What hardware are you using?

**Comment by ndrewtl** [comment] 2022-06-15 16:55
Could this be a duplicate of #4784 ?

**Comment by Aldolc30** [comment] 2023-09-08 17:22
> I'm experiencing this as well. My ASUS laptop has a black screen and the fans go furiously when I try to install WSL 2. What hardware are you using?

Hi, can you solve that problem? I have the same problem with my Asus Vivobook. Is a problem directly with Asus laptops?

**Closed** 2024-09-12 12:23 UTC
