### ISSUE TITLE
Sound through mini displayport my accasualy stop working

### ISSUE THREAD

**Issue by rosti-il** [microsoft/WSL#11546] opened 2024-05-01 15:39 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.4291]

### WSL Version

2.2.4.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.153.1-2

### Distro Version

I use no distro. I need WSL mainly for Docker Desktop.

### Repro Steps

At the beginning I thought this is a Docker Desktop issue (end even filled a very similar bug report on their github) but it happens now even after I've uninstalled it and left only WSL installed.

Sound through mini displayport of my monitor may stop working. When it happens playing Youtube videos at least in the Firefox browser slows down and looks like it play in slow motion. If I switch to any other sound device, for example to my headphones (connected into USB) or to the integrated Realtek sound card the sound works properly again and Youtube videos are played correctly. If I reboot my computer the sound and the youtube in Firefox may start to work properly through the mini displayport until next unpredictable time this issue happens. The "Troubleshoot sound problem" of Windows sometimes helps as well, after it reinstall the Intel Display Audio driver.

I have the latest drivers of my Intel HD 4600 video card (20.19.15.5171) and of Intel Display Audio (6.16.0.3208).
I use Windows 10 Professional 22H2 build 19045.4291 with all latest updates installed.
Hyper-V is disabled, only Virtual Machine Platform and WSL are enabled.
Tried with WSL versions: 2.2.4 (now), 2.2.3, 2.2.2, 2.1.5
Before I started to use WSL this issue never happened for many years.

### Expected Behavior

I expect no problem with sound happen

### Actual Behavior

Sound through mini displayport my accasualy stop working

**Comment by rosti-il** [comment] 2024-05-02 16:47
Logs:
[WslLogs-2024-05-02_19-45-13.zip](https://github.com/microsoft/WSL/files/15191322/WslLogs-2024-05-02_19-45-13.zip)

**Comment by rosti-il** [comment] 2024-05-02 16:50
I reproduced the issue. When I click on the volume level the regular sound of Windows doesn't work. If I change the output sound device from Display Audion to something else it works.

**Comment by rosti-il** [comment] 2024-05-02 16:52
Could any real human check this issue and update the labels?
GitHub bot seems not intelligent enough to understand.

**Comment by OneBlue** [comment] 2024-05-03 22:21
@rosti-il: Does the issue reproduce with WSL uninstalled ? WSL doesn't interact with video drivers so it's difficult to see how having WSL installed could cause this

**Comment by rosti-il** [comment] 2024-05-04 07:40
@OneBlue I don't know how to uninstall WSL completely. Previously I installed it from [`wsl.2.2.4.0.x64.msi`](https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi) and now, after disabling the "Windows Subsystem for Linux" in the "Programs and Features" I see the WSL is still in the `C:\Program Files\WSL` directory. Do you know how to uninstall it completely? The sound issue still happens sometimes but I suspect this is because WSL is not completely uninstalled/removed from the system.

**Comment by rosti-il** [comment] 2024-05-04 07:46
@OneBlue I've just found how to uninstall WSL completely. I right clicked on the downloaded [wsl.2.2.4.0.x64.msi](https://github.com/microsoft/WSL/releases/download/2.2.4/wsl.2.2.4.0.x64.msi) file and chose "Uninstall".
![image](https://github.com/microsoft/WSL/assets/45571812/32b72b51-1458-4e9b-ab3c-27b003beca76)

Let's wait a couple of days if this sound issue will happen again.

**Comment by rosti-il** [comment] 2024-05-04 09:33
@OneBlue This issue happened again, after WSL was completely uninstalled. I've noticed that at the same time the sound through mini displayport stopped working three events like following appeared:
```
The machine-default permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{C2F03A33-21F5-47FA-B4BB-156362A2F239}
 and APPID 
{316CDED5-E4AE-4B15-9113-7055D84DCC97}
 to the user XXXXX\xxxxxxx SID (S-1-5-21-3250475200-3059155199-2685345549-1001) from address LocalHost (Using LRPC) running in the application container Microsoft.Windows.ShellExperienceHost_10.0.19041.4239_neutral_neutral_cw5n1h2txyewy SID (S-1-15-2-155514346-2573954481-755741238-1654018636-1233331829-3075935687-2861478708). This security permission can be modified using the Component Services administrative tool.
```

**Comment by OneBlue** [comment] 2024-05-04 20:04
Thank you @rosti-il. This helps show that this issue isn't caused by WSL so unfortunately I'll have to close this.

Also for further notice, WSL can be installed via: `wsl --uninstall`.

**Closed by OneBlue** 2024-05-04 20:04 UTC

**Comment by rosti-il** [comment] 2024-05-06 19:52
@OneBlue
After also disabling the "Virtual Machine Platform" in my Windows 10 I've no issue with the sound through mini displayport. I think it is worth to reopen this issue and investigate it further.

Could it be that WSL changes something in the configuration of something related to monitor or sound and that wrong configuration (for example wrong DCOM component registration or a bug in that DCOM component) triggers this issue sometimes? Anyway I'm not the only one who experiences this issue.

**Comment by rosti-il** [comment] 2024-05-08 14:38
@OneBlue Could you explain what @github-actions wants from me? I've already provided logs and have no other logs. Could you just reopen this issue and investigate it?

**Comment by OneBlue** [comment] 2024-05-08 18:50
Unfortunately WSL doesn't own the virtual machine platform component. Based on the results you're seeing, I'd guess that the issue might be with the driver itself. Maybe it doesn't support well when virtualization is enabled. 

Sadly the best next steps would be to contact the driver's publisher, but this isn't something that can be done from the WSL side.
