### ISSUE TITLE
wsl hangs while doing operations on windows drives from linux

### ISSUE THREAD

**Issue by Jivko1212** [Microsoft/WSL#2613] opened 2017-10-27 23:24 UTC
I had several hangs while doing operations such as running a devops python script that copies files between directories. Here is how starting ubuntu looks after hanging:

![capture](https://user-images.githubusercontent.com/25863991/32128430-4c0ff9fc-bb86-11e7-94cf-31bd825fdfff.PNG)

Bash cannot be killed from Task Manager or Process Explorer. The problem seemed really easy to trigger when I was working on a TrueCrypt drive. I assumed it might have something to do with TrueCrypt and unlinked it. Then it also happened on a regular drive that is linked in my home directory in linux.

My windows ver is: [Version 10.0.16299.19].

The hang is fixed by a system restart. One time, when I did system restart the system needed to be turned off from the power button because it hanged on restarting. Other times Windows restart worked ok.

Let me know if I can send any logs or additional information.

**Comment by Jivko1212** [comment] 2017-10-30 13:16
To leave an update. The problem does not occur if I used the linux filesystem, only when I symlink window drives and operate on them.

**Comment by rhinoceraptor** [comment] 2017-10-31 21:52
This happens to me as well using Node, working in the Windows file system from WSL. NPM installs fail almost every time once WSL has been running for more than a couple minutes. I end up having to completely shut down and re-start my development environment several times a day.

 Doing an ```rm -rf node_modules``` has killed my entire PC about a dozen times in the past month or so. I'm also running 10.0.16299.19.

Something is seriously busted with the file system in WSL.

**Comment by rhinoceraptor** [comment] 2017-11-01 15:52
I just had to reboot my PC for the second time today due to disk intensive operations breaking WSL.

Maybe 2018 will be the year of the Windows desktop, when Windows is finally stable enough to use as a functioning workstation for developers. In the meantime, I would recommend Linux if you want a stable desktop OS with good software compatibility :)

**Comment by Jivko1212** [comment] 2017-11-01 16:07
It is very annoying that the bash process cannot be killed via task
manager. I even tried with process explorer to set the permissions but it
also didn’t work. At the end I resorted to make a copy of the windows files
to the Linux filesystem and it is working ok now. It is stupid however to
be unable to kill a deadlocked process and to have to restart the whole
system.

**Comment by therealkenc** [comment] 2017-11-03 08:27
> It is very annoying that the bash process cannot be killed via task
manager. 

I had hoped for a `/nukeinstance` feature back in September 2016, #1086 ([message](https://github.com/Microsoft/WSL/issues/1086#issuecomment-247525568)), which would unceremoniously tear down the stack as a last resort (like a hard reboot). Basically the equivalent reloading the lxcore/lxsys drivers and restarting `LxssManager`. Just linking for posterity; it doesn't help your instant problem, but I had the similar feeling back when I was having to reboot my machine. Back then the root problem with `mv` was ultimately addressed and the killswitch idea quietly faded. It would probably not be straightforward to implement such a thing. Or, that's what I've assumed anyway.

**Comment by BladeMF** [comment] 2017-12-11 11:53
I too have experienced such hangs from doing file system operations. One instance I traced to be trying to use chown/chmod, which caused it 100 out of 100 times.

**Comment by BladeMF** [comment] 2017-12-12 08:34
Guys, please check if you have a windows junction somewhere in the path passed to rm -rf or chown. I've had problems with both leading to freezes. The workaround is to use a Linux symlink. I've posted the issue here: #2746

**Comment by superherointj** [comment] 2017-12-13 12:19
When running BuckleScript on watch mode, WSL crashes, and won't start to Bash prompt only recovers after a few restarts.

Running Ubuntu on WSL
Version 10.0.16299 Build 16299

**Comment by rhinoceraptor** [comment] 2017-12-18 19:35
My machine just crashed two times in a row doing a ```rm -rf node_modules``` inside of the WSL FS.

**Comment by sunilmut** [comment] 2017-12-19 01:59
@rhinoceraptor - If you can follow the instruction from [here](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for BSOD's, that would be great.

@superherointj - Can you please post the Windows ver (`ver` from a CMD) and the repro steps, that would be useful?

**Comment by superherointj** [comment] 2017-12-20 13:36
![ubuntu-wsl-error](https://user-images.githubusercontent.com/5861043/34209531-a7234124-e579-11e7-908f-3c6ae213a7ea.jpg)

I've generated etl files following FAQ instructions:
[bashdebug.zip](https://github.com/Microsoft/WSL/files/1575648/bashdebug.zip)

Current way to reproduce problem is to just use bucklescript/webpack in my project and eventually it crashes WSL. I can't say exactly what is causing this. I believe it might be related to symlink but it is a guess.

**Comment by superherointj** [comment] 2018-01-15 12:38
@sunilmut Screenshots of problem:

![ubuntu-wsl-error](https://user-images.githubusercontent.com/5861043/34209531-a7234124-e579-11e7-908f-3c6ae213a7ea.jpg)

Current way to reproduce problem is to just use bucklescript/webpack in my project and eventually it crashes WSL with error: `0x80070040`. I can't say exactly what is causing this.

Workaround is to restart computer several times. And WSL works again after a few attempts.

**Comment by DarthSpock** [comment] 2018-01-21 00:09
I would like to add to this discussion that it's not just bash that's the issue. Any linux process found in Task Manager is unable to be killed in the Task Manager. Nor does using `taskkill /im some_linux_process /t /f` Interestingly enough, Using PS tools, specifically `./pskill -t PID of the linux process` says "Process PID killed." but when you look in Task Manager, it's still there. I tried using the name of the process instead but it just hangs. This is both CMD and Powershell. From what I've researched, you've have to kill the process using Linux but since WSL hangs, I can't get into Ubuntu or OpenSuse to kill it. In fact, I tried to reinstall both distros and the install portion fails. (Figured if the distros were uninstalled, the process would die because the path no exists to no longer execute) but the process still lives. I'm going to try that restart computer several times workaround mentioned above and hope it works. Oh and for purpose of record, the specific process I'm having issues with is `qdbus` which is generated by QT Creator. Apparently it can cause WSL to hang when it randomly crashes. First major breakage I've experienced (usually stayed away from doing things that cause known issues like the plague).

**Comment by rivaros** [comment] 2018-01-23 17:15
![hangs](https://user-images.githubusercontent.com/1242369/35290047-b5130f54-0071-11e8-9661-e5e8f6c66ced.png)

**Comment by rivaros** [comment] 2018-01-23 17:15
Another one. Yes I use symlinks from Windows.

**Comment by codehtmai** [comment] 2018-04-13 21:34
I am also seeing this issue when developing with Node/Webpack in WSL but the code directory in Windows.  I'm on Version 10.0.16299.371.

**Comment by jamezrin** [comment] 2018-08-13 12:41
This also happens to me when using Node or Ruby, I'm on 17713

**Comment by DarthSpock** [comment] 2018-08-13 12:56
This was fixed in 17134. I'm able to kill any process I want under Task Manager, including `init`. So it appears there was a regression (hope it's fixed before next stable or I'll be forced to stay with current stable).

**Comment by mtwilliams** [comment] 2018-10-02 20:34
This is affecting me on my workstation. I'm on 17134. Not using symlinks or junctions, just prodding a few files with Python. Seems like all I/O eventually dies.

**Comment by superherointj** [comment] 2019-02-01 09:48
https://github.com/Microsoft/WSL/issues/2746
Was this fixed in #2746?

**Comment by therealkenc** [comment] 2019-02-01 20:04
Let's call it #2746 for lack. There is no repro for "running a devops python script that copies files between directories" out of the gate.

**Closed by therealkenc** 2019-02-01 20:04 UTC

**Comment by innovoix** [comment] 2019-03-22 08:53
WSL hangs (is idle) on first launch of WSL "WSL is installing, this can take a few minutes" and when doing ```apt install``` operations. I can proceed by hitting enter key but it happens frequently.

**Comment by emretuna** [comment] 2019-09-11 12:39
Add your project dir and C:\Users\username\Appdata\Local to Windows defender exclusion list.
It helps on some cases but not a permanent fix.

**Comment by GiancarloZ** [comment] 2020-03-02 18:06
Was there a fix for this? I am having same issue with Ubuntu in general. I've uninstalled both VS COde and Ubuntu several times. Still have issue. Have only ubuntu installed, when open it works for few seconds/minutes and then it hangs and mutliple init, or bash, or env open in task manager making cpu 100%.

**Comment by lukasrusty** [comment] 2020-03-02 19:22
Exactly the same behavior for me as @GiancarloZ . 

Couple minutes everything works. Then when opening bash or running command from already opened terminal - hangs, CPU usage 100%, bash and init processes cannot be killed. Only restart helps. Very frustrating.

The issue started today.

**Comment by GiancarloZ** [comment] 2020-03-03 14:59
@lukasrusty I just tried using Debian instead of Ubuntu thinking that was the issue and I got the same problem. Maybe its the windows 10 Subsystem for Linux?

**Comment by GiancarloZ** [comment] 2020-03-03 20:03
@lukasrusty check out thread below. Seems to have solved the issue.....for now. 

https://github.com/microsoft/WSL/issues/4936
