### ISSUE TITLE
Win 11 WSL

### ISSUE THREAD

**Issue by rayj00** [microsoft/WSL#7925] opened 2022-01-13 22:41 UTC
How can I use the WSL Ubuntu on my local network?

Right now,  the host is Win 11 on my local 192 network.  It can ping the wsl Ubuntu just fine (172.x.x.x).
However,  wsl cannot ping the host Win 11.

I also installed apache2 on the wsl but cannot browse to it from the host.

Thanks,

**Comment by elsaco** [comment] 2022-01-14 02:01
@rayj00 you need to open your firewall.

**Comment by rayj00** [comment] 2022-01-14 18:16
> @rayj00 you need to open your firewall. Add ICMPv4 to your `Inbound Rules` or any other application you protocol/port you desire.

The firewall on the host or the Ubuntu WSL?

**Comment by elsaco** [comment] 2022-01-14 18:24
@rayj00 your Window firewall. IFIK WSL instances are not firewalled. `win+r` then `firewall.cpl` and select `Advanced Settings`. Add a new rule to your `Inbound Rules` to allow pings.

**Comment by rayj00** [comment] 2022-01-14 18:30
Not familiar with Rules.  Is it Program, Port, Predefined or Custom?

**Comment by elsaco** [comment] 2022-01-14 19:02
This are the steps I did for `echo` only:

1. New Rule
2. Custom
3. All programs
4. Protocol type: ICMPv4
5. Any IP address
6. Allow the connection
7. Public

**Comment by rayj00** [comment] 2022-01-14 19:20
After all that,  still cannot browse from Win 11 host to wsl ubuntu!

**Comment by elsaco** [comment] 2022-01-14 19:46
The above rule is for ICMPv4 only, i.e. ping and other echo requests. What do you mean by `can't browse`? You'll have to open more holes in your firewall for other protocols. Here's sample ping output from WSL Ubuntu to Windows host (IP 192.168.1.195) after opening the firewall:

```
tux@RIPPER:~$ ping -c 2 192.168.1.195
PING 192.168.1.195 (192.168.1.195) 56(84) bytes of data.
64 bytes from 192.168.1.195: icmp_seq=1 ttl=127 time=0.354 ms
64 bytes from 192.168.1.195: icmp_seq=2 ttl=127 time=0.548 ms

--- 192.168.1.195 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1014ms
rtt min/avg/max/mdev = 0.354/0.451/0.548/0.097 ms
```

**Comment by rayj00** [comment] 2022-01-14 20:01
I have apache2 installed on the wsl ubuntu.  It has a 172.x.x.x IP.
My host Win 11 has a 192.x.x.x IP.

I should be able to browse (http://172.x.x.x)  from my host to the wsl ubuntu.  What does this have to do with the Win 11 inbound firewall?

Ray

**Comment by rayj00** [comment] 2022-01-14 20:02
BTW,  ping from the wsl ubuntu to the host still does not work.

**Comment by elsaco** [comment] 2022-01-14 20:08
The replies were to help with your `wsl cannot ping the host Win 11` issue only. Good day to you, sir!

**Comment by craigloewen-msft** [comment] 2022-01-14 21:22
Hi @rayj00 this seems like a duplicate of this issue: https://github.com/microsoft/WSL/issues/7820 (or https://github.com/microsoft/WSL/issues/4150 )

We're aware of the request to be able to access WSL from the local area network and this request is being tracked by those two open items above. Please check those threads for workarounds, and check [this docs page](https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan) for some instructions that might also help. Thank you for filing!

**Closed by craigloewen-msft** 2022-01-14 21:22 UTC
Labels: feature

**Comment by rayj00** [comment] 2022-01-14 21:54
![image](https://user-images.githubusercontent.com/6609523/149590275-9c884e11-7734-4b4f-9ba6-6a9b1b966a28.png)

Still no ping

**Comment by rayj00** [comment] 2022-01-14 21:56
Thanks Craig.  

 

Ray
