### ISSUE TITLE
Create symbolic link only work on the first layer of directory and all sub directories are repeat the first layer and again again

### ISSUE THREAD

**Issue by thinksource** [Microsoft/WSL#1137] opened 2016-09-29 06:45 UTC
- A brief description
  I try to create a soft link of directory by command line "ln", and it is only works for the first layer of dirctory.
- Expected results
  for instance I have directory F:/work/test

after I use `ln -s /mnt/f/work work`
I expect the I can enter work and test directory.
but Actually, I can not go inside the sub directories,
- Actual results (with terminal output if applicable)

```
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work# ls
ExpressPayment  manage.py  PayMate  startup.sh  templates  work
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work# cd work
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work/work# ls
ExpressPayment  manage.py  PayMate  startup.sh  templates  work
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work/work# ls
ExpressPayment  manage.py  PayMate  startup.sh  templates  work
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work/work# cd work
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work/work/work# ls
ExpressPayment  manage.py  PayMate  startup.sh  templates  work
(dpe) root@DESKTOP-6GTI9HG:~/virtualenvs/dpe/PayMate/work/work/work#
```

you can see the is loop, when I came in the sub directory there is same directory as it above.
- Your Windows build number
  OS Build 14393.187
- Steps / All commands required to reproduce the error from a brand new installation 
  use the ln -s an directory in windows and try to go the sub directory
- Strace of the failing command
  the command do not failing
- Required packages and commands to install
  nothing

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by Sajito** [comment] 2016-09-29 15:09
Are you sure you created it exactly as you wrote ("ln -s /mnt/f/work work")? Or was it maybe with a trailing slash after work like this "ln -s /mnt/f/work/ work", in linux the effect is the same, but here it's still different.

**Comment by grasshoppergn** [comment] 2016-10-03 05:44
Had the same issue - the problem is indeed in that trailing slash: "ln -s /mnt/f/work work" - works well, while "ln -s /mnt/f/work/ work" creates that loop

**Comment by Levara** [comment] 2016-10-19 22:40
I can confirm both the bug and the grasshoppergn's solution. The loop also messes up the TAB completiton.

**Comment by omegamormegil** [comment] 2017-02-23 18:21
I too can confirm the behavior and that it seems related to the trailing slash in the symlink. Strangely, if I cd into the new directory pwd seems to see the subdirectory correctly, but if I use touch to create a new file, it's created in the parent directory.

**Comment by aseering** [comment] 2017-02-23 18:27
For what it's worth, there's a known issue with symlinks containing trailing slashes:  #650 .  It is fixed in Insider builds.  The fix will be in the next major Windows update, which is rumored to maybe be coming out within the next few months.

**Comment by benhillis** [comment] 2018-07-11 00:41
Duplicate of #650 which has been fixed for some time.

**Closed by benhillis** 2018-07-11 00:41 UTC
