### ISSUE TITLE
Virtual hard disk files must be uncompressed

### ISSUE THREAD

**Issue by winecos** [microsoft/WSL#4190] opened 2019-06-19 02:50 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18917.1000]

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

> The error message as below 
> PS E:\temp> wsl --set-version kali-linux 2
> Conversion in progress, this may take a few minutes...
> For information on key differences with WSL 2 please visit https://aka.ms/wsl2
> **The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.**

* What's wrong / what should be happening instead:

> Set a distro to be backed by WSL 2 using the command line

**Comment by benhillis** [comment] 2019-06-19 03:37
Duplicate of #4103.

**Closed by benhillis** 2019-06-19 03:37 UTC
