### ISSUE TITLE
Can't run cron jobs

### ISSUE THREAD

**Issue by grantdobbe** [Microsoft/WSL#344] opened 2016-05-11 18:57 UTC
When trying to add a recurring job to my crontab, I get the following message:

```
crontab: installing new crontab
/var/spool/cron/: mkstemp: Permission denied
```

I'm able to work around the issue by using Task Scheduler to call bash.exe with the script I wanted to run, but that seems kludgy. A lot of applications depend on cron to run routine maintenance tasks, and having to set them up in Task Scheduler is sub-optimal.

**Comment by sunilmut** [comment] 2016-05-11 22:33
@grantdobbe Unfortunately, we currently don't have support for background task execution. Please help us prioritize it by providing the feedback in our user voice page. I do see one related [post](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13653522-why-crontab-conuldn-t-use-on-it-permission-den), if you would like to up vote it.

**Comment by rodrymbo** [comment] 2016-05-12 13:36
There is another issue: normal userspace commands in linux are, for some reason, restricted to root, with no good reason (that is, it might make sense if the underlying NTFS filesystem prohibited it, which it usually doesn't). So even if cron background jobs worked, the current implementation denies permission for unprivileged users to use it. Lots of other things are in the same boat. 

So for example, if you do `sudo crontab -e` and you don't get "permission denied", but you do get "permission denied" with plain `crontab -e,` this is not crontab not working, it is another of several unwarranted restrictions on linux unprivileged account behavior. 

I'm not saying that cron is working, just that the crontab -e command is being denied to normal users without good reason. Making crontab work is thus, strictly speaking a **different** issue.

**Comment by matthewpersico** [comment] 2016-08-11 15:56
sudo crontab -u $USER -e is a reasonable workaround. I'll upvote the cron support.

**Comment by sampablokuper** [comment] 2018-03-10 02:36
@sunilmut wrote:
> Please help us prioritize [background task execution] by providing the feedback in our user voice page.

This is less than helpful for people who don't use UserVoice, but would like to see WSL support `cron`.

Microsoft already has, right here, a bug tracker for WSL. So, why ask people to go to UserVoice as well or instead? To fragment discussion? To increase the effort required, in the hope that people will give up instead of speaking up?

**Comment by sunilmut** [comment] 2018-03-12 17:46
@sampablokuper - 
> To fragment discussion? To increase the effort required, in the hope that people will give up instead of speaking up?

That was definitely not the intent. This bug tracker is good for tracking bugs, but, it's difficult to do a consolidated voting based feature request here (nothing that I am aware of). If you have any feedback on how we take feature requests for WSL, please feel free to also reach out to @tara-raj 

We actually look at our user voice page on feature requests. As for this particular request to support background tasks, that was added recently. See [here](https://blogs.msdn.microsoft.com/commandline/2017/12/04/background-task-support-in-wsl/). Hopefully that clarifies few things here. 

We appreciate all feedback!

**Comment by sampablokuper** [comment] 2018-03-12 18:54
@sunilmut wrote:
>> To fragment discussion? To increase the effort required, in the hope that people will give up instead of speaking up?
> That was definitely not the intent.

Good to have that confirmed :)

(Microsoft's track record re: user feedback, averaged over the last couple of decades, has, sadly, warranted the level of scepticism you can see in my comment above :/ )

> it's difficult to do a consolidated voting based feature [requests in this bug tracker].

Is it? Enough to warrant fragmenting the "official" discussion threads across at least three different websites (GtiHub, UserVoice, Microsoft forums) run by three different companies?

Why not just do something like [sorting on the number of thumbs up per bug report](https://github.com/Microsoft/WSL/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)?

> please feel free to also reach out to @tara-raj

Done :)

> As for this particular request to support background tasks, that was added recently. See [here](https://blogs.msdn.microsoft.com/commandline/2017/12/04/background-task-support-in-wsl/).

Thanks for the link. That is progress, but there's a long way to go until the behaviour as a whole is really `cron`-like.

**Comment by therealkenc** [comment] 2018-03-13 00:17
The OP in this issue was:
```
crontab: installing new crontab
/var/spool/cron/: mkstemp: Permission denied
```
This is because [`cron(8)`](http://man7.org/linux/man-pages/man8/cron.8.html) was not running, and that directory (possibly) did not have correct permissions. The 'possibly' caveat because no `strace` of the failing [`crontab(1)`](http://man7.org/linux/man-pages/man1/crontab.1.html) was provided.

The issue was marked as 'feature' because at the time WSL did not support background tasks. This was addressed in [Insider 17046](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17046) and will hit the Spring Update RSN.

You can start `cron` with `sudo service cron start`.
```
$ sudo service cron start
 * Starting periodic command scheduler cron                              [ OK ]
$ ls -l /var/spool/cron
total 0
drwx-wx--T 1 root crontab 512 Apr  5  2016 crontabs
$ echo "*/1 * * * * echo hello `date` >> /tmp/hello" | crontab -
$ crontab -l
*/1 * * * * echo hello `date` >> /tmp/hello
$ cat /tmp/hello
hello Mon Mar 12 17:08:01 DST 2018
hello Mon Mar 12 17:09:01 DST 2018
```

If anyone finds any further problems with `cron(8)` or `crontab(1)` please feel encouraged to open a new issue following CONTRIBUTING.md. The popular github hang-out for launching of `init` tasks like `cron` (or `sshd`, or `syslogd`, or `dbus-daemon`, or ...) is #994.

**Comment by tara-raj** [comment] 2018-05-22 20:53
Fixed in release 1803. You can read more about how to do this in our [blog post on background tasks](https://blogs.msdn.microsoft.com/commandline/2017/12/04/background-task-support-in-wsl/)

**Closed by tara-raj** 2018-05-22 20:53 UTC
Labels: fixedininsiderbuilds
