### ISSUE TITLE
wsl 2 breaks vcxsrv X11 server

### ISSUE THREAD

**Issue by imagtek** [microsoft/WSL#6941] opened 2021-05-14 03:05 UTC
wsl 2 breaks the vcxsrv X11 server. 
My LINUX application [REX www.imagtek.com] cannot find Display :0 with vcxsrv running.

vcxsrv works fine under wsl 1

Windows 10 O/S Build 19042.985     wsl build from wsl website 13 May 21  Ubuntu-20.04

**Comment by devcircus** [comment] 2021-05-14 05:01
on wsl2, networking has changed and display should be set like this:
```export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0```

**Comment by imagtek** [comment] 2021-05-14 12:35
I implemented this in .bashrc and it appends :0.0 to my IP address. No problems there.
The problem is vcxsrv now fails to return control from attempting to connect to the display. I gave it a full minute.
I would very much like to run wsl2 since I work with very large image files.
Below is the section of code that is hanging. It has run flawlessly for 20 years.
Your further input greatly appreciated.
/*
  Func: CONNECT_REX_DISPL()
  Desc: Connect REX to X display server and define the toplevel widget
*/
short CONNECT_REX_DISPL()
{
  short stat;
  int32 argc, xOfs, yOfs;
  char  *argv[16];

  if( REXdisplay != NULL )     // already initialized
    return 0 ;
/*
  Initialize connection; returns applicationShellWidgetClass Widget
*/
  xOfs     = 128;
  yOfs     = 64;
  argc     = 0;
  toplevel = XtVaOpenApplication(&app, "REX", NULL, 0, &argc, argv,
               NULL, applicationShellWidgetClass,
	       XmNx, xOfs, XmNy, yOfs,
	       XmNtitle, "REX Image Analysis", (char *)NULL);
  if( !toplevel ){
    fprintf(stderr, "\n***CONNECT_REX_DISPL(): XtVaAppInaitialize() fail\n");
    exit( 1 );
  }

  REXdisplay = XtDisplay( toplevel );
  vscrn_no  = XDefaultScreen( REXdisplay );
  vscrn_ptr = XDefaultScreenOfDisplay( REXdisplay );

  ROOTwin = XRootWindow(REXdisplay, vscrn_no);
  if(!ROOTwin){
    fprintf(stderr,"\n***CONNECT_REX_DISPL)_: XRootWindow() fail\n");
    return -1;
  }

// define dimensions of 'full screen' view
  rootCols = XWidthOfScreen(vscrn_ptr);
  rootRows = XHeightOfScreen(vscrn_ptr);

  dispDim.RootCols = rootCols;       // screen resolution
  dispDim.RootRows = rootRows;

  #ifdef DEBUG
    fprintf(stderr, "\nCONNECT: screen cols, rows= %d %d", rootCols, rootRows);
  #endif
/*
  Get 24 bit visual, if it exists
*/
  stat = GET_REX_VIS(&REXvi, REXdisplay, vscrn_no);
  if(stat){
    fprintf(stderr,
        "\n***CONNECT_REX_DISPL(): 24 bit (Truecolor) graphics fail\n" );
    return -2 ;
  }
  return 0;
}

**Comment by benhillis** [comment] 2021-05-14 15:38
WSLg recently released - if you're able to try it out you'll have a much better experience using that.

**Comment by pmop** [comment] 2021-05-14 15:47
Same issue here. Using x410 though.

**Comment by imagtek** [comment] 2021-05-14 17:04
Well...
There is a lot about this issue on the web, and I faithfully implemented suggested modifications all the way through the Windows firewall, multiple reboots, and still nothing.
So it looks like wsl 2 is vaporware. On my machine anyway.
I'm an application coder, not a hacker. I don't have time for this so I'm done with it for now.
Many thanks to those who responded and continue working this problem.

**Comment by therealkenc** [comment] 2021-05-20 00:14
Closing discussion ran course. Could not reproduce locally with VcXsrv (below). Even better with[ WSLg](https://github.com/microsoft/wslg).

![image](https://user-images.githubusercontent.com/7049700/118900247-52abf000-b8c5-11eb-9b35-4a5cabac98d6.png)

**Closed by therealkenc** 2021-05-20 00:14 UTC
Labels: discussion

**Comment by imagtek** [comment] 2021-05-20 10:45
Thank you for investigating.
I spent the better part of a day on this unsuccessfully. Might be user 
error.
I am moving to WSLg when it comes out in the next W10 release.
John Powers
