### ISSUE TITLE
commands and options don't localize in HELP command

### ISSUE THREAD

**Issue by jp311** [microsoft/WSL#8978] opened 2022-10-09 08:14 UTC
### Version

Microsoft Windows [Versoin 10.0.22621.608] Chinese Edtion

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Repro Steps

wsl --help

### Expected Behavior

show english command or option, dotn't translate to chinese.

### Actual Behavior

![image](https://user-images.githubusercontent.com/336683/194745612-b75a040d-145e-4f85-ae29-4c9f2692cf85.png)

**Comment by cofedream** [comment] 2022-11-22 07:59
I have the same problem.

**Comment by Winson-Huang** [comment] 2022-12-08 08:14
Duplicate of #8857

**Closed** 2023-03-07 00:10 UTC
