### ISSUE TITLE
mkdir on drvfs network share creates regular file.

### ISSUE THREAD

**Issue by silicontrip** [microsoft/WSL#3423] opened 2018-07-30 04:33 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.15]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I have mounted a network share with the following command:
`sudo mount -t drvfs \\\\10.0.0.230\\weather /mnt/weather`
then attempt to make a directory within that mount

`cd /mnt/weather`
`mkdir Localisations`

Localisations is created as a regular file, not a directory.

* What's wrong / what should be happening instead:

`ls -la | grep Localisations`
expected:
`drwxrwxrwx 1 root root 512 Jul 30 14:28 Localisations`

seen:
`-rwxrwxrwx 1 root root 0 Jul 30 14:28 Localisations`

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).

the command doesn't produce any errors

* For WSL launch issues, please [collect detailed logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs).

See [our contributing instructions](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment] 2018-07-30 15:52
@SvenGroot - could you take a look at this?

**Comment by SvenGroot** [comment] 2018-07-30 18:53
Hi @silicontrip,

I was unable to reproduce this problem either on 1709 (your version), 1803 (the current release version), or current internal builds.

Is there something unusual about the network share itself? What server is it using (regular Windows SMB or some other server)?

Thanks.

**Comment by silicontrip** [comment] 2018-07-31 00:08
It appears to be a bug between lxss and our Isilon file server.  
I can mount a share from another device and create directories from within lxss 
I can also create directories on the Isilon from Explorer or Powershell.

How do I go about explaining this bug to Dell EMC?

I did a packet capture of the mkdir from both lxss and powershell although I don't understand SMB2 enough to determine what it happening.

For both PS and LXSS. I see a Create Request File followed by a Create Error Response saying Object Name Not Found.
I see that some of the flags are different in the create request between the two.

But then I see a Notify response from the Isilon saying that the file has been added, which I don't see in the PS capture.

I assume the differences in the Create File Request are confusing our NAS.

**Comment by silicontrip** [comment] 2018-08-01 04:02
I've upgraded to Microsoft Windows [Version 10.0.17134.191] and the problem persists.

I really have no idea how to report this to our NAS vendor as a bug.  Is there some way to reproduce the fault in another application so I can demonstrate to them that the bug is in their device?

Thanks

**Comment by api2001** [comment] 2018-11-15 07:42
Same for me when trying to mkdir on an NFS share of an Isilon storage server.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.345]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
In WSL I type for example:
> mount -t drvfs //nfs.isilonstor.local/home/me /mnt/me     (is successful)
> cd /mnt/me
> mkdir 2018
> ls -l
-rwxrwxrwx 1 root root   0 Nov 15 08:35 2018
> cd 2018
-bash: cd: 2018: Not a directory

* What's wrong / what should be happening instead:

The mkdir 2018 command creates a file, not a folder on the NFS mount.
I had expected that 2018 would be a directory??!? ;-)
But it is a file I can even write things to.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here).
https://gist.github.com/api2001/71fb5d5bd1ecc3914644de9f624ccdb3#file-mkdir-strace

**Comment by hansmitgans** [comment] 2019-07-17 15:13
We have the same problem! An Isilon file server and the client is Windows 10 Enterprise version 1803 build 17134.829.

**Comment by hansmitgans** [comment] 2019-08-30 17:04
I have the same problem. windows 10 enterprise 1803 build 17134.885 and isilon file server.

**Comment by SDeans0** [comment] 2019-09-10 12:52
Me too - has anyone found a workaround, or is this fixed in a more recent Windows 10?

**Closed** 2024-02-01 12:53 UTC
Labels: file system
