### ISSUE TITLE
go build command-line-arguments: read |0: interrupted system call

### ISSUE THREAD

**Issue by tg123** [Microsoft/WSL#349] opened 2016-05-12 12:05 UTC
Microsoft Windows [Version 10.0.14342]

install go from apt-get install golang

```
$ go version
go version go1.2.1 linux/amd64

go build
go build command-line-arguments: read |0: interrupted system call
```

However, it cloud work without error sometimes

**Comment by stehufntdev** [comment] 2016-05-12 14:08
Thanks for reporting the issue.  We investigated this locally and it is caused by missing support for restartable system calls (i.e. SA_RESTART flag).

Please give us feedback on the [uservoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) page so we can prioritize.

**Comment by mvadu** [comment] 2016-05-22 07:33
@stehufntdev the repo readme says "This repo is for the reporting of issues found within and when using Bash on Ubuntu on Windows", and you are asking us to go to UserVoice? Then what is the point of reporting it here?

**Comment by aseering** [comment] 2016-05-22 14:38
@stehufntdev -- Github is good at capturing and discussing technical information about a bug or feature request.  But there are many (I'm guessing at least hundreds if not thousands?) of people reporting bugs or requesting features or (etc) against WSL.  I've seen bug trackers where bugs for popular issues get tons of "me too!"'s, and it's a real pain to read through all of those comments to figure out what the actual bug is, find the latest updates from the people who are actually debugging it, etc.  So the important bugs actually become more annoying to fix.

I think Microsoft is trying to differentiate between technical issues and use cases.  Your report is both -- "`go build` is an important command for developing Go software" is a use case; "`go build` doesn't work because of lack of `SA_RESTART` support" is a technical issue.  So it's useful to have it in both places.

**Comment by mvadu** [comment] 2016-05-23 01:04
@aseering I did create a [new user voice topic ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14046789-add-support-for-restartable-system-calls-i-e-sa)for this as well.

**Comment by simonbuchan** [comment] 2016-06-01 08:56
Also happens with github's hub command (written in go). Since that's recommended to be aliased to git, this can hit pretty often!

**Comment by egtann** [comment] 2016-07-18 20:22
Any idea on a timeline @stehufntdev? This issue prevents the development and use of [my project](https://github.com/itsabot/abot) on Windows. It would be great to offer Windows support.

**Comment by RobWC** [comment] 2016-08-02 18:53
+1

**Comment by technowar** [comment] 2016-10-11 14:03
Any updates on this?

**Comment by tg123** [comment] 2016-10-11 14:24
fixed in 14905
https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

works fine now

**Comment by retorquere** [comment] 2016-10-19 19:22
How do I get 14905 on my system?

**Comment by stehufntdev** [comment] 2016-10-20 00:19
14905 is a Windows insider build, to get that on your system you need to enroll the machine in the Windows insider program.

**Comment by sleaze** [comment] 2016-10-24 18:11
What if we don't want to opt into full telemetry? :s

**Comment by MikeCook9994** [comment] 2016-11-23 21:50
You don't get windows insider. Windows insider isn't for you to get builds and fixes early. It's to get information about their new builds.

**Comment by aseering** [comment] 2016-11-23 21:57
@MikeCook9994 -- could you provide a reference for that statement?  I install Insider builds from here on a regular basis:  https://insider.windows.com/

**Comment by cheynewallace** [comment] 2016-12-26 20:33
Is there any indication as to when this 14905 build will be generally available?  I am trying to move some of my build operations from Mac to Windows and this has completely blocked me as I cannot `go build` from bash.  I'd prefer to not have to enroll in some insiders program and just use the stable release.

**Comment by benhillis** [comment] 2016-12-26 21:11
The Windows 10 Creators update which is due early 2017.

**Comment by ausrasul** [comment] 2016-12-28 20:57
I got this problem right after I modified files in Bash FROM WIndows C:/Users/myself/AppData/loca/lxss/

I cloned my project again on another directory and now it works. Will edit files via ssh from now on.

**Comment by ausrasul** [comment] 2016-12-29 22:18
@cheynewallace I'm running Stable, having the same problem here.

**Comment by robbiev** [comment] 2017-01-29 11:13
I read somewhere that go 1.6.x might work and indeed, 1.6.4 does work for me. More recent versions of go don't work.

**Comment by Zanndorin** [comment] 2017-02-10 15:05
I can confirm that go 1.6.4 works 

thank you @robbiev

**Comment by sunilmut** [comment] 2017-03-01 23:11
@robbiev - Thanks for the post. Can you please provide more details on which version of `go` is not working and detailed repro steps?

**Comment by mrbeskin** [comment] 2017-03-10 19:37
`go` `go1.8.linux-amd64.tar.gz` not working with WSL.

Repro:

1. download and install according https://golang.org/doc/install using `wget`
2. `go build` on any go main package (I just did the default `hello.go`)


Errors: 

```
 hello → go run hello.go                                                  ⍉
go build command-line-arguments: /usr/local/go/pkg/tool/linux_amd64/compile:
 read |0: interrupted system call
```

**Comment by stehufntdev** [comment] 2017-03-10 19:42
@mrbeskin can you please let us know which Windows build you are running?  There is a known issue preventing go from working in the Anniversary update which has been fixed for insider builds.

**Comment by mrbeskin** [comment] 2017-03-11 00:38
@stehufntdev Sorry, deleted my comment before I saw there was a reply . . . I realized I was on the Anniversary update. I am working on getting my hands on the latest available build and I will test there. Thank you for your reply.

**Comment by stehufntdev** [comment] 2017-03-11 00:41
No worries, thanks for the confirmation!  Please let us know if you see any issues for insider builds.

**Comment by cweeks12** [comment] 2017-03-16 20:19
Is there any indication of when this build is going to be available generally? I just ran into this issue in my Go development

**Comment by benhillis** [comment] 2017-03-16 20:35
@cweeks12 - Creator's update is due soon. I don't have an exact date but I think April or early May.

**Comment by fraklo** [comment] 2017-03-22 22:29
Not sure if it's been noted, but I get the same issue when trying to run
`go run test.go`
if however I run
`go run ./*`
or even go up a directory and run
`go run test_dir/*`
The file runs.

**Comment by JamieSinn** [comment] 2017-05-30 05:14
This issue is still persisting.

**Comment by sunilmut** [comment] 2017-06-12 23:04
@fraklo and @JamieSinn - I tried this simple example https://gobyexample.com/reading-files and it worked fine for me. I was able to run the file using the command `go run test.go`. I am running go version 1.6.2. This was on Insiders build 16215. If the issue persists for you, please include the Windows build that you are running (output of the `ver` command) and an strace `strace -o <strace_file> -ff <failing_cmd>`

```
$go version
go version go1.6.2 linux/amd64
```

**Comment by JamieSinn** [comment] 2017-06-13 02:36
I am using go 1.8, I have not used an insider's build.

**Comment by sunilmut** [comment] 2017-06-13 15:05
@JamieSinn - Ok, thanks. Please also post your Windows version (using the `ver` CMD) and full repro steps.

**Comment by kanonji** [comment] 2017-08-21 04:47
I tried https://gobyexample.com/reading-files and not worked.

```
$ go run reading-files.go
go build command-line-arguments: /home/kanonji/local/stock/go1.8.3.linux-amd64/pkg/tool/linux_amd64/compile: read |0: interrupted system call
```

```
$ cat go-run-reading-files-go.sh
#!/bin/sh
go run reading-files.go

$ strace -ff -o straced/go-run-reading-files-go ./go-run-reading-files-go.sh
go build command-line-arguments: /home/kanonji/local/stock/go1.8.3.linux-amd64/pkg/tool/linux_amd64/link: read |0: interrupted system call
```

`strace` generates 20 files. Do you need all files or maybe only last one?


```
$ go version
go version go1.8.3 linux/amd64
```
```
>ver

Microsoft Windows [Version 10.0.14393]
```

**Comment by therealkenc** [comment] 2018-03-24 20:57
The OP here was related to restartable system calls and was addressed in 14905 and by extension Creators Update 15063.

**Closed by therealkenc** 2018-03-24 20:57 UTC
Labels: feature, go
