### ISSUE TITLE
wslpath -u C: returns C: rather than /mnt/c

### ISSUE THREAD

**Issue by deliverystack** [microsoft/WSL#7111] opened 2021-06-23 23:50 UTC
### Windows Build Number

21390.2025

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

 5.10.16

### Distro Version

Ubuntu 20.24

### Repro Steps

$ file `which wslpath`
/usr/bin/wslpath: symbolic link to /init

$ wslpath -u "C:\\"
/mnt/c/

$ wslpath -u "C:"
C:

### Expected Behavior

wslpath -u "C:" returns /mnt/c

### Actual Behavior

wslpath -u "C:" returns "C:"

**Comment by therealkenc** [comment] 2021-06-24 21:31
Effectively #4908. Different under the premise drives are special paths.

**Comment by deliverystack** [comment] 2021-06-25 06:21
@therealkenc Disagree, I don't see this as a feature request for missing paths, but as a defect correction for existing paths.

**Comment by craigloewen-msft** [comment] 2021-06-29 16:57
Hi @deliverystack this is currently expected behaviour. Currently as wslpath is implemented the string `C:` is not seen as an existing file but `C:\` is. 

Is there a scenario that you're blocked with from this behaviour? Or anything that it's breaking for you?

In the meantime I'll close this issue out as 'by design' for our tracking but am happy to follow up on this thread, and am tracking #4908 to improve wslpath for scenarios like this. 

Thanks!

**Closed by craigloewen-msft** 2021-06-29 16:57 UTC
Labels: feature

**Comment by deliverystack** [comment] 2021-06-29 18:18
Thanks, I am not blocked, I can just add the trailing backslash on C:\ in my code or workaround it otherwise, but it is unpredicted and inconsistent behavior that may affect other projects. I think at the very least it might appear as a note in help for the command, or if passed -u [A-Za-z]:[^\\/], as from my perspective, C: exists and is equivalent to C:\, the only difference is the slash token.

**Comment by craigloewen-msft** [comment] 2021-06-29 18:28
Got it! That sounds very reasonable to me, I'll keep it tracked in 4908 as part of general improvements there. Thanks for the feedback :)

**Comment by NathanielPerryAtAwatoXello** [comment] 2021-09-08 20:25
This is an issue when using `wslpath` in combination with Environment Variables in cases where a user needs to refer to the home or system drive. Both of these values are set to simply `C:` in the environment variables, so this is a problem:

- `wslpath $( wslvar HOMEDRIVE )` - Actual: `C:` - Expected: `/mnt/c/`
- `wslpath $( wslvar SystemDrive )` - Actual: `C:` - Expected: `/mnt/c/`

Yes, you could append the slash to the variable, but I don't think that is a reasonable solution because we don't know what odd values `HOMEDRIVE` or other default environment variables might be set to that could cause problems with appending a slash.

It would be reasonable to expect this to work `mkdir -p $( wslpath $( wslvar HOMEDRIVE ) )/projects/some-specific-project`
