### ISSUE TITLE
Firefox browser window's resizing doesn't work right

### ISSUE THREAD

**Issue by aki-k** [microsoft/WSL#10355] opened 2023-08-02 06:04 UTC
### Windows Version

Microsoft Windows [Version 10.0.19045.3271]

### WSL Version

0.0.0.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.90.3-microsoft-standard-WSL2

### Distro Version

Ubuntu 22.04

### Other Software

wsl 2 1.3.14
firefox-115.0.2.tar.bz2

### Repro Steps
```
# apt-get install libdbus-glib-1-2 bzip2 libgtk-3-0 libasound2 ubuntu-restricted-extras mate-terminal
$ mkdir ~/Downloads
$ cd ~/Downloads
$ wget https://ftp.mozilla.org/pub/firefox/releases/115.0.2/linux-x86_64/en-US/firefox-115.0.2.tar.bz2
$ tar -xf firefox-115.0.2.tar.bz2
$ ./firefox/firefox
```
Window resizing is really clunky. But if I start Firefox like this, there's no problem any more with window resizing:
```
$ mate-terminal -e ~/Downloads/firefox/firefox
```
### Expected Behavior

window resizing should work smoothly

### Actual Behavior

window resizing is very clunky

**Comment by elsaco** [comment] 2023-08-02 16:21
@aki-k try running `firefox` under `wayland` instead of `X` by setting `MOZ_ENABLE_WAYLAND=1` before launching it. Wayland apps are snappier on WSL. Also `firefox-116` is out which has better wayland support.

**Comment by aki-k** [comment] 2023-08-02 16:34
> by setting MOZ_ENABLE_WAYLAND=1 before launching it

Yes, that works. Thanks

**Comment by OneBlue** [comment] 2023-08-02 18:37
Closing since the issue is resolved

**Closed by OneBlue** 2023-08-02 18:37 UTC
