### ISSUE TITLE
Cannot start any WSL distros or docker desktop in WSL 2 mode

### ISSUE THREAD

**Issue by zavitax** [microsoft/WSL#7046] opened 2021-06-08 12:36 UTC
### Windows Build Number

Microsoft Windows [Version 10.0.19043.1023]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Installed kernel update, can't run "wsl --status"

### Distro Version

Ubuntu-20.04, can't run any other distro

### Other Software

Docker Desktop (Windows): 3.3.3.64133

### Repro Steps

Option 1:
Open command prompt, run "wsl", observe the following output:
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

----

Option 2:
Search for "Ubuntu" in Microsoft Store, click "Launch" for "Ubuntu", observe the following output:
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070422
Error: 0x80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

----

In both cases, the LxssManager service is up and running

### Expected Behavior

WSL 2 working.

### Actual Behavior

WslRegisterDistribution failed with error: 0x80070422
Error: 0x80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### Diagnostic Logs

Diagnostic log attached:
[wsl.etl.gz](https://github.com/microsoft/WSL/files/6616430/wsl.etl.gz)

**Comment by onomatopellan** [comment] 2021-06-08 13:25
That looks like a Windows Update problem. Try to download and run the WU troubleshooter https://aka.ms/wudiag

**Comment by zavitax** [comment] 2021-06-08 14:00
> That looks like a Windows Update problem. Try to download and run the WU troubleshooter https://aka.ms/wudiag

"Troubleshooter couldn't identify the problem"

![image](https://user-images.githubusercontent.com/14030887/121198660-f9f3c580-c87a-11eb-8419-58218fb2df47.png)

**Comment by onomatopellan** [comment] 2021-06-08 14:54
I forgot in WSL 0x80070422 is E_SERVICE_DISABLED. Did you take a look at #3815?

**Comment by zavitax** [comment] 2021-06-08 20:08
> I forgot in WSL 0x80070422 is E_SERVICE_DISABLED. Did you take a look at #3815?

Yes, it has nothing to do with LxssManager startup mode.
I also went over all the troubleshooting suggestions in there: no luck.

**Comment by zavitax** [comment] 2021-06-08 21:24
> Do you have installed any security solution/firewall different from Windows Security?

Nothing. I'm using Windows Defender & Windows Firewall as security measures.

**Comment by onomatopellan** [comment] 2021-06-08 23:54
Then the WSL2 install is broken. Try reinstalling WSL2:
* open "Turn Windows Features on or off"
* untick "Virtual Machine Platform" and "Windows Subsystem for Linux"
* reboot
* tick "Virtual Machine Platform" and "Windows Subsystem for Linux"
* reboot

After that try again and see if the error message appears yet.

**Comment by zavitax** [comment] 2021-06-09 08:52
> Then the WSL2 install is broken. Try reinstalling WSL2:
> 
> * open "Turn Windows Features on or off"
> * untick "Virtual Machine Platform" and "Windows Subsystem for Linux"
> * reboot
> * tick "Virtual Machine Platform" and "Windows Subsystem for Linux"
> * reboot
> 
> After that try again and see if the error message appears yet.

Those steps did not help.

I used to have WSL 2 working, then it stopped (noticed when docker started refusing to start).

My guess would be that some part of persistent configuration broke which is not reset bb reinstalling the platform.

**Comment by zavitax** [comment] 2021-06-09 16:58
Attaching logs generated by `diagnostics/networking.bat`:

[wsl.etl.gz](https://github.com/microsoft/WSL/files/6625541/wsl.etl.gz)
[packets.etl.gz](https://github.com/microsoft/WSL/files/6625545/packets.etl.gz)

**Comment by zavitax** [comment] 2021-06-10 08:24
Giving it a bit more thought, it seems that the whole thing collapsed after I installed (and perhaps uninstalled) Oracle VirtualBox.

**Comment by zavitax** [comment] 2021-06-10 11:45
It seems that the service which fails to start is Windows Sandbox.

**Comment by zavitax** [comment] 2021-06-14 10:45
Ok, I found the source of the trouble: the `WinNAT` driver was disabled on my system.
It seems that WSL requires that driver.

**Comment by benhillis** [comment] 2021-06-15 17:13
@zavitax - is disabling WinNAT something you did?

**Comment by zavitax** [comment] 2021-06-15 19:00
> @zavitax - is disabling WinNAT something you did?

Yes. I have previously disabled the WinNAT driver.

The reason for doing so is that WinNAT prevented software I develop for a client from binding to certain TCP ports as described in this post:
http://www.herlitz.nu/2020/12/01/docker-error-ports-are-not-available-on-windows-10/

Since I observed no issues after running "net stop winnat", I decided to disable the driver completely. It took me a while to figure out that this also prevented WSL2 from working.

**Comment by benhillis** [comment] 2021-06-15 23:22
Ok makes sense. Well as you've found WSL networking relies on the presence of WinNAT so I'm marking this as by design.

**Comment by zavitax** [comment] 2021-06-15 23:29
> Ok makes sense. Well as you've found WSL networking relies on the presence of WinNAT so I'm marking this as by design.

Oh that's fine. I suppose it would be helpful to have a list of drivers/services WSL requires available somewhere for other folks like me down the road?

**Comment by picwellwisher12pk** [comment] 2021-09-06 13:29
> Enter cmd with admin privileges and type `sc config LxssManager start=auto` . Worked for me.

worked for me

**Comment by jplopezmolinari** [comment] 2021-09-07 17:32
are you using zsh?

**Comment by eltonbenevidesPREPARATODOS** [comment] 2021-09-12 01:43
Thx @mirunica , that works sweet o/

**Comment by alexruimy** [comment] 2021-10-01 17:20
>[error 0x8007010b when launching `wsl.exe -d Ubuntu']

This did not work for me. I am using zsh (@jplopezmolinari )

**Closed** 2024-02-01 12:11 UTC
Labels: bydesign, failure-to-launch
