### ISSUE TITLE
Web directory in wsl2 soft connects to win10 web directory, accessible but very laggy response【请求帮助！！！3Q】

### ISSUE THREAD

**Issue by stuffren** [microsoft/WSL#11576] opened 2024-05-11 15:21 UTC
I have set up a LAMP environment in **WSL2**:
WSL2 ---version--- Ubuntu 22.04.4 LTS
MySQL ---version--- 8.0.36
PHP ---version--- 8.1.2
Apache ---version--- 2.4.52 (Ubuntu)

My website's root directory is located in var/www/ucoredata in WSL2, and I have created a symbolic link between this directory and the local D:\formalpro\ucoredata directory in Windows 10.
Currently, I can use an editor to directly modify and edit the PHP source code in the D:\formalpro\ucoredata directory on Windows 10, and the changes will be successfully mapped back to the /var/www/ucoredata root directory in WSL2.
I have configured a virtual domain, ucoredata.com, in the hosts file of Windows 10, and I can successfully access the website locally through this virtual domain.

My goal is to develop and test PHP programs (websites) directly on Windows 10 without using remote tools like WSL2 remote in VS Code to open the website's source code in WSL2. Although I have achieved this goal, there are two issues:

**Issue 1:** Although the website can be accessed successfully, I have noticed that the response time is very slow during operation. What are the typical causes of this? Is it due to the cross-filesystem setup? The use of a virtual domain? Or some other reasons?

**Issue 2:** What are the common approaches to resolve the issue of slow response time?

Looking forward to your help and answers, thanks in advance！！

**Comment by stuffren** [comment] 2024-05-12 11:30
/question
There's no need to collect WSL logs because
github-actions bot autoresponders to similar questions - https://github.com/microsoft/WSL/issues/6366 has solved my problem. Thanks!

**Comment by OneBlue** [comment] 2024-05-13 18:51
Closing since the issue is solved;

**Closed by OneBlue** 2024-05-13 18:51 UTC
Labels: feature, question
