### ISSUE TITLE
Arrows ignored by bash when it started in ConEmu

### ISSUE THREAD

**Issue by Maximus5** [Microsoft/WSL#111] opened 2016-04-10 20:58 UTC
I'm the author of [ConEmu](https://github.com/Maximus5/ConEmu) - alternative terminal for Windows. My users have created the issue Maximus5/ConEmu#629. When bash is started in ConEmu console, it totally ignores all extended keys (Arrows, Fn, etc.), so users can't access command line history with Up/Down arrows.

What is the problem with bash? Up/Down arrows properly cycle cmd.exe history, when it's started in ConEmu, but bash ignores them.

ConEmu is GUI application, so it get keyboard events via WM_KEYUP/WM_KEYDOWN and forward them to the created (usually hidden) real console using WriteConsoleInput.

**Comment by Maximus5** [comment] 2016-04-12 09:03
I've created workaround in [ConEmu build 160411](https://conemu.github.io/blog/2016/04/11/Build-160411.html). However, it would be nice to know, is it a bug or intended behavior.

**Comment by Maximus5** [comment] 2016-04-13 09:13
Unfortunately, arrow keys still do not work in vim.

**Comment by sunilmut** [comment] 2016-04-13 12:31
bash.exe has its own logic to read from console directly (this is as per the design today and subject to change in future releases). I am not a console expert, but I wonder if ConEmu interacting with the console directly is interfering with bash.exe's ability to process keyboard events?

**Comment by Maximus5** [comment] 2016-04-13 12:35
ConEmu use official console API WriteConsoleInput to post keypressed into the conhost input buffer. That worked perfectly until "Bash on Ubuntu" appears.

**Comment by sunilmut** [comment] 2016-04-13 12:50
Ok. I am not sure I fully understand the problem here. My understanding of this issue is that bash is not able to process arrow keys when launched from within ConEmu? Can you help clarify.

**Comment by Maximus5** [comment] 2016-04-13 14:37
Short answer: Yes.

Many words below. 
Let's take for example UpArrow key.

When user press and release UpArrow, normal console application
recieves two console key events:
1) bKeyDown = TRUE; wVirtualKeyCode = VK_UP;
2) bKeyDown = FALSE; wVirtualKeyCode = VK_UP;
References: PeekConsoleInput, ReadConsoleInput, INPUT_RECORD, KEY_EVENT_RECORD.

But Unix console applications expect different key sequences.
For UpArrow keypress either `ESC [ A` or `ESC O A` sequences are expected
depending on requested ‘DECCKM’ mode.
References: ANSI sequence `ESC [ ? 1 h` and `ESC [ ? 1 l`.

The `bash.exe` **is** Windows console application, therefore it's expected
that this application would work properly with standard Windows console API
keypresses (KEY_EVENT_RECORD, VK_UP). But, I'm not sure who, the translation
is done when user presses UpArrow. And `bash.exe` recieves `ESC [ A` instead.

Well, that is rude workaround, but if `bash.exe` is started in ConEmu with
`-cur_console:p1` switch, ConEmu does this translation and arrows magically
start working.

That is really rude, because ConEmu does not recieve ANSI sequences from
linux processes. And, when user starts `vim` from bash prompt, ‘DECCKM’ is not changed.
Therefore, ‘Arrows are not working in vim under ConEmu’.
There are absolutely no way to determine that `vim` was started from bash,
or vim has requested to change ‘DECCKM’ mode.
Seems like linux processes (init, bash, vim) somehow write their console output
directly to conhost, bypassing `bash.exe`. That's bad, because ConEmu has absolutely
no control over linux processes (started from service), only `bash.exe` may be hooked
to catch it's output and ‘fix’ input.

If you would like to check, download latest ConEmu build (alpha 160411 ATM),
and run from `Win+R`:

~~~
ConEmu.exe -basic -cmd bash.exe -cur_console:p1
~~~

**Comment by DanielGGordon** [comment] 2016-05-02 16:09
So Just to be clear here - you guys are talking about `bash.exe` - that is or is not the same thing as the new Ubuntu Subsystem in the most recent Windows 10 dev build?

**Comment by Maximus5** [comment] 2016-05-02 19:30
Sure, it is. Monday, 02 May 2016, 07:09PM +03:00 from Daniel Gordon < notifications@github.com> :

**Comment by DanielGGordon** [comment] 2016-05-02 20:12
@Maximus5 I deleted my comment because I figured it out on my own by looking at the top of this page 10 seconds after I posted my comment... Sorry for the confusion.

**Comment by bigonazzi** [comment] 2016-05-14 09:10
Hi, console2 and consoleZ, two other terminal emulators, have the same problem with arrows not working on bash.

**Comment by Maximus5** [comment] 2016-05-14 09:16
@bigonazzi Of course they are. Only ConEmu is able to send xterm-ish keyboard sequences, which LX kernel expects.

**Comment by xilun** [comment] 2016-05-14 20:31
Just would like to add that IMO this is quite important to have WSL working properly with ConEmu, because some serious console users (myself included) are not going to be satisfied with the basic Windows Console (which is now quite better than the legacy one, but still far away from any random XWindow Console we are used to)

For now I'm doing some dev under WSL on the Windows Console (for now coping with the international keyboard bugs it has by switching to a US layout) but I will be seriously disappointed if I can't use ConEmu for a vast majority of WSL software, and that obviously includes vim...

@Maximus5 thanks for your excellent ConEmu btw :)

**Comment by bigonazzi** [comment] 2016-05-14 20:40
@xilun +1

@Maximus5 I like conemu, all I'm saying is that the issue is bigger than just one program and it should be addressed with high priority.

**Comment by Darktex** [comment] 2016-05-14 21:22
@xilun +1

The Windows default terminals don't have nearly enough features for any power user

**Comment by djmott** [comment] 2016-05-28 11:01
@Maximus5 thank you for ConEmu. It's a huge productivity improvement. MS should ditch the POS default console, give you a few million USD and ship it with every install of Windows.

**Comment by sunilmut** [comment] 2016-05-28 17:47
@Maximus5 - Given the popularity of ConEmu, you could also convert it to a UWP using [“Project Centennial."](https://developer.microsoft.com/en-us/windows/bridges) and submit it to Windows Store for even a wider audience.

**Comment by nigurr** [comment] 2016-07-13 13:18
+1 Please fix this

**Comment by miniksa** [comment] 2016-07-14 17:23
Sorry, this is my bad. @zadjii-msft and I overlooked this portion of the design when we implemented the virtual terminal input handling in the console host such that it doesn't present itself properly for ConEmu and friends. Unfortunately because it's a design flaw, it's a little bit more work than a quick bug fix. 

I have it tracked internally as 7640020. I can't commit to a date it'll be fixed, but know that it is in our tracker, it is understood, and it is being ranked/prioritized.

**Comment by bigonazzi** [comment] 2016-07-14 19:48
@miniksa good to hear that you're listening to user feedback!

**Comment by Novynn** [comment] 2016-07-22 05:27
Ah, just came across this issue. I hope we'll see some progress soon!

**Comment by Maximus5** [comment] 2016-07-22 05:49
@Novynn What progress do you want to see? ConEmu had implemented workaround and arrows started working months ago.

**Comment by Novynn** [comment] 2016-07-22 05:56
@Maximus5 I was meaning more towards on Microsoft's end, I wasn't aware of a workaround!

I've just started using Cmder today, which reports it's ConEmu as being 160710 stable (I see this version is the latest release on GitHub) and I am unable to use arrow keys.

I'm using cmd.exe in Cmder to start Bash on Windows to ssh into a screen session on a Linux machine. This is on the Windows 10 Insider Preview 14393.

**Comment by Maximus5** [comment] 2016-07-22 05:58
ConEmu.exe -basic -run {bash}

**Comment by Novynn** [comment] 2016-07-22 06:02
Ah, that makes a lot more sense! Works perfectly thanks.

**Comment by pbecotte** [comment] 2016-07-26 16:35
I have this issue trying to use the new bash terminal in Pycharm.  They could probably implement the workaround listed here, but doesn't that still leave the terminal not working for things like vim?

**Comment by DanielGGordon** [comment] 2016-07-26 19:19
Last time I tried it out, arrows worked on the command line, but not in
VIM. Has this changed with a recent update?

**Comment by pbecotte** [comment] 2016-07-26 19:24
Pycharm has the parameters to call the executable with hard-coded in, so I can't just use the workaround out of the box (at least I think that's what's happening :) )

**Comment by gfairchild** [comment] 2016-08-03 15:23
I'm experiencing the same vim issues another few users are reporting. Arrows work on the command line, but not in vim.

**Comment by Zardoz89** [comment] 2016-08-04 18:02
**htop** looks that does weird things with the arrow keys. and **Midnight Comander** (mc), don't get any notice of arrow keys being pressed.

**Comment by nergdron** [comment] 2016-08-04 18:06
I've found that with the workarounds in ConEmu, htop locally works as expected now, but remotely via SSH it still gives the weird broken default behaviour.

**Comment by meta-inf** [comment] 2016-08-05 08:30
Neovim does not receive arrow keys properly with the {bash} profile.

**Comment by qrmn** [comment] 2016-08-06 09:02
Same as nergdron, but also can confirm this is _not_ a ConEmu issue: the exact same thing happens when using ssh under Bash in vanilla conhost.

It appears to be a WSL/conhost design fault that needs fixing if we're going to use ssh on Windows.

**Comment by i336** [comment] 2016-08-06 12:34
I just found this bug linked from [a random Hacker News comment](https://news.ycombinator.com/item?id=12236155), and while I'm not using Windows at the moment (hope remains for a future upgrade and dualboot at some point) I wanted to chime in and say something while this issue is actively being discussed.

As M$ is certainly well aware, the console subsystem in Windows has historically been incredibly difficult to work with. I'm admittedly unsure how much Powershell has fixed the situation (if at all), but going forward, I think that it would be 100% worth it to take the time (eg, a few extra months) to architect a solution that makes it possible to sanely manage console access for Linux apps, and possibly even Windows console apps too.

I cannot emphasize enough that there will be much appreciation and gratefulness if the race conditions (I understand ConEmu opens a hidden cmd process and constantly polls it for updates?) and other issues that plague Windows' current builtin console support can be sidestepped using a new API. It doesn't have to be perfect nor the easiest to work with; it just has to be predictable, consistent and well-documented. Fast would be nice too, so we can run `find /` without 100% CPU usage :P

Currently we've only got ConEmu, but now that Linux support is becoming more and more usable, I think bits of the Linux "scene" are slowly going to leak over to Win32, and it's possible that will include terminal emulators - either in the form of new Windows-specific apps, or hybrid codebases that can compile for Windows and Linux (and maybe macOS).

In my (possibly not completely thought through) opinion, a Really Good Way(TM) to fix this might be to make it possible to get at/create a Linux pty (ie what you'd get from a call to `posix_openpt`) from the namespace of a Windows process. Then a terminal application just needs to read/write the handle(s) it gets on the Win32 side of the fence to handle display and user input.

That only covers Linux tty access though. If there's some even lower-level approach you guys can use to fix it for Linux *and* Windows, I'm definitely in support of using these bugs to justify the development time :+1:

**Comment by bigonazzi** [comment] 2016-08-07 07:28
+1 @i336

**Comment by miniksa** [comment] 2016-08-08 17:06
@i336... I know. Everything you have said is on my mind and I'm considering ways we can solve it for Windows in the future. I'm quite proud of how far we've come in the Windows Console space in my short few years on this team, but I know we have a long way to go. 

I can't speak in detail about planning and pre-production because that makes a lot of people cranky and means I have to spend my day making them all un-cranky instead of fixing actual problems. But do know that the spirit of what you've said is very well captured in my design plans. 

I know the underlying console infrastructure on Windows is problematic. I know that other terminal emulators out there are better than what we've achieved for the Windows Console Host. I know that ConEmu's Maximus in particular has done an unbelievably good job at dealing with the BS that our API and console infrastructure is. I am trying my hardest to come up with a comprehensive solution that can make all of you happy, continues to advance the inbox Windows Console Host, allows other terminals to be very viable alternatives, and keeps my corporate overlords happy. 

My team and I have a lot more in store for the console in the coming year. Please bear with us as we work. We look forward to pleasantly surprising you (hopefully!) as much next year with what we still have to deliver as we did this year with what we achieved in releasing Bash on Ubuntu on Windows.

------

Also... just as a little aside... The "M$" is not appreciated. I understand that sort of phrasing is common when referring to my company and its behavior especially in the past. Heck, I was guilty of it in college when I solely used Linux and hated on Microsoft products. But it's quite hurtful to me, my team, and all the engineers here like us who are working very hard every day to change how Microsoft operates and bring our products and community closer to yours. This company has come a long way in the past few years, and I'd like your help in embracing where we can go and what you and I can achieve together... not the missteps of former products and people here that might have colored your opinion. I wouldn't work here if I thought all that we did was for the money and nothing else. I hope that my team, my fellow Microsoft engineers, and I can change your opinion in that respect.

**Comment by Tyriar** [comment] 2016-08-08 18:06
Just chiming in from Visual Studio Code, users that attempt to use `bash.exe` as the shell in the integrated terminal is also hitting this issue. It uses [winpty](https://github.com/rprichard/winpty) to communicate with `bash.exe`.

**Comment by i336** [comment] 2016-08-09 01:46
@miniksa: Thanks so much for your candid response (and so fast too!) - it's awesome to hear it. I've had a vague awareness for some time that the console infrastructure is broken, and it's really really cool to be talking to someone on the team who's going to be working on fixing it <3

Based on what you've said, I get the impression things are the way they are possibly because of 3rd-party application compatibility? (Always technically curious. I reckon that insight on the current infrastructure and its technical evolution - posted to somewhere like [The Old New Thing](https://blogs.msdn.microsoft.com/oldnewthing/) - would make for a very interesting read for a lot of people, once things are a bit different.)

Regarding your aside, I must admit my embarrassment at my subconscious choice of contraction of the word *Microsoft* - I actually intended it as a benign reference, and didn't think of the ever-present connotations behind the `$`. Thanks for reminding me (and helping clarify) that Microsoft is in a very different position today, with a different focus - `s/M\$/Microsoft/g` from me from this point forward :)

**Comment by miniksa** [comment] 2016-08-09 15:36
@i336: It's cool. Thanks for understanding. :) 

Compatibility is one factor of many for why things often stay the same or get extended in an interesting way. Most of the console's oddities are explained by organic growth of the code base over 27+ years, so you could call it evolution. It's a system with many, many customers and had a steady stream of different owners. It hasn't had a thorough dose of dedicated comprehensive love until my team formed a couple years back and started cracking the nut. 

I have a wall outside my office full of post-it notes and yarn scraps of the architecture, the customers, the issues, and the dependencies. There is a lot more to it than most realize, so any change often affects all the other parts.
![wincon](https://cloud.githubusercontent.com/assets/18221333/17521724/33f202b0-5e09-11e6-9c2a-e66931bb3a46.jpg)
 ConEmu and similar tools are up there as the fifth pink (or "server-side customer") square in from the left under "Customers" and are connected to various of the orange "Issues" below, one of which is "Non-public server API" which makes Maximus do the polling as you observed. Trust me, it's all captured on that wall. 

@bitcrazed and I have been discussing coming up with a series of blog posts about the good, the bad, and the ugly of the console system. I hope to get to doing that soon since it seems you and others would be interested.

**Comment by ericblade** [comment] 2016-09-28 14:45
FWIW, I'm also interested in this bug, as a user of ConsoleZ, with 6 different command processors currently installed :-D

**Comment by fpqc** [comment] 2016-10-17 22:19
@miniksa Will you be starting a console blog like the WSL blog, with or without Seth Channel 9 videos?

**Comment by miniksa** [comment] 2016-10-18 16:07
@fpqc We'll be starting something whenever I can wrangle our PM @bitcrazed into helping me get it all set up and approved. He's been very busy recently with another more time-critical scenario, so the blog/video/etc. plan has been on the backburner and the rest of us devs have been busy coding away on the console host in the meantime. We didn't forget, trust me. I nag him in stand up meetings several times a week for when he's going to be done with his other work so we can get to setting this up. :P

**Comment by jrock2004** [comment] 2016-11-08 11:15
Wanted to add another twist. I am using zsh and my arrow keys don't work. It does not matter which terminal I use.

**Comment by zadjii-msft** [comment] 2016-11-08 15:27
@jrock2004 Could you open a new issue for that? They should be working in conhost.exe, and a new issue would be the easiest way to debug your issue (without constantly pinging the other 22 people already in this particular discussion)

**Comment by bitcrazed** [comment] 2016-11-11 18:16
@fpqc It's true ... @miniksa & @zadjii-msft and the rest of the team REALLY DO nag me at least once a day on a number of things I'm not helping him with!!

Yes, we do have a developer blog where we post articles about all things command-line - Console, Bash, and hopefully PowerShell too: https://blogs.msdn.microsoft.com/commandline. 

We'll be posting more stuff about the Console's new features in a couple of weeks (honest Mike!), we've just got to get some high-pri stuff out of the way first ;)

**Comment by miniksa** [comment] 2016-11-11 18:17
@bitcrazed I'll believe it when I see it. :P

**Comment by arcanis** [comment] 2016-12-12 20:43
HyperTerm just released its first official Windows build, but unfortunately it also suffers from this issue.

**Comment by arcanis** [comment] 2017-01-21 21:26
Worth noting that a relatively easy workaround is to start bash using [wslbridge](https://github.com/rprichard/wslbridge) instead of a direct `bash` command. It also fixed a few other display issues I had on Hyper.

**Comment by Tyriar** [comment] 2017-01-21 22:28
@arcanis also Hyper is in the process of adopting the new version of [`node-pty`](https://github.com/Tyriar/node-pty) which should fix the issue without needing wslbridge due to a newer version of [winpty](https://github.com/rprichard/winpty).

**Comment by khards** [comment] 2017-02-26 12:55
Would be good to see this bug fixed

**Comment by Serubin** [comment] 2017-03-06 21:09
@Tyriar Do you know which branch that is of Hyper if there is one?

**Comment by Tyriar** [comment] 2017-03-06 21:31
@Serubin latest Hyper should include the fix.

**Comment by Serubin** [comment] 2017-03-06 21:35
@Tyriar You're right. Thanks!

**Comment by pinonpierre** [comment] 2017-03-10 14:56
Any news about this issue ?
It's very annoying !

It will be the Bug Anniversary soon !

**Comment by khards** [comment] 2017-03-20 20:27
Weekly bump the bug bump

**Comment by zadjii-msft** [comment] 2017-03-20 20:40
Okay so just to clarify, nothing has particularly changed since @miniksa's post from July 14, 2016:
>[we] overlooked this portion of the design when we implemented the virtual terminal input handling in the console host such that it doesn't present itself properly for ConEmu and friends. Unfortunately because it's a design flaw, it's a little bit more work than a quick bug fix.
> I have it tracked internally as 7640020. I can't commit to a date it'll be fixed, but know that it is in our tracker, it is understood, and it is being ranked/prioritized.

Unfortunately, we have a lot of other things that are a lot higher priority than fixing this. Rest assured, when there's an update on our end, we'll post here. That way we can avoid sending weekly pings to the 27 people on this thread (and quite possibly more watching)

**Comment by ericblade** [comment] 2017-04-14 02:48
Adding +1 here.  ConsoleZ user, arrow keys do not function in the slightest inside the ConsoleZ window.

**Comment by bgshacklett** [comment] 2017-04-15 03:28
@jackchammons For those of us not in the know, could you give a quick summary of why this is no-longer considered a bug?

**Comment by zadjii-msft** [comment] 2017-04-17 16:44
@bgshacklett Right now it's being tracked internally as work item MSFT:7640020. It's a little bit more than just a simple "bug" fix - this is more "feature" level work. Internally, the distinction makes quite a bit of difference on how we're able to plan work. This should have the feature label now to make sure that this is labeled appropriately.

**Comment by nigurr** [comment] 2017-04-18 03:57
@zadjii-msft Thanks for the update. it would be great if you can assign the milestone or tentative timeline for shipping this

**Comment by zadjii-msft** [comment] 2017-04-18 16:02
@nigurr Unfortunately I don't have a tentative timeline for this fix at the moment, sorry.

**Comment by jackchammons** [comment] 2017-04-19 19:18
@bgshacklett Just doing a little house keeping on the GH labels. It's still an issue that we plan on addressing but it's being tracked internally as a feature. Semantics, I know, but it helps us keep things organized.

**Comment by tobico** [comment] 2017-08-11 02:41
Please consider prioritizing the fix for this. Having a wide variety of quality Terminal applications available is very important for WSL to be a useful feature of Windows.

**Comment by DropsOfZut** [comment] 2017-08-19 05:12
solved?

**Comment by ichenfeng** [comment] 2017-08-19 05:36
Please consider fixing this.
In ConsoleZ(another third-party terminator), Arrows doesn't  work too. and The reason for using third-party terminator is for the terrible font setting for CMD and PowerShell in Chinese edition.

**Comment by i336** [comment] 2017-08-19 05:59
That's a very good point - the new console subsystem needs to have really, really good Unicode support. Modern programming languages support unicode strings and expect to be able to use it for I/O, and there are lots of prompt hacks using unicode characters as well.

I figured I might as well ride the bit of traffic that's been generated right now to chime in and add that ***the community remains super interested in a series of blog posts on the architectural updates***. An in-depth writeup that adds every last detail that's legally possible would be widely appreciated - both because architectural upgrade trivia is always really fun, and also because it'll clearly explain why everything took so long.

I personally completely understand that this bugfix is the tail end of a lot of planets ~~aligning~~ being  strong-armed into place, and that it'll take a little while. The console subsystem probably still has design cruft in it from Windows 3.1 - the NTVDM code doesn't ship in most (64-bit) installations, but is still builds for 32-bit, so it's still in the codebase. Knowing Microsoft's obsession with backward-compatibility, fixing this will **not** be easy.

For people frustrated about this, I have an open question (I don't have any Windows-capable hardware at the moment, so I unfortunately can't try this out myself): Can urxvt or xterm from Cygwin running on a Windows X server talk to WSL? If it can, that could be a very workable alternative.

For the MS devs working on this issue, when you see this update - I understand that speculating on timelines creates lots of avoidable fallout, so I won't ask for that. What I *will* ask for is a vague idea of the status of the internal tracking bug. How far have 7640020 and/or its dependencies/blockers progressed since the bug was initially filed (around August last year)?

I'm not trying to extricate an executive "I'm impatient, hurry up" summary. This is not ready yet, not much to do except face that. That's fine. But to know that there has been some movement would be cool.

Ah, if only you could share internal details. Then you could keep us in the loop about "the architecture, the customers, the issues, and the dependencies" :D and what the progress is with each. We wouldn't mind <3

**Comment by rprichard** [comment] 2017-08-19 09:23
FWIW, winpty works around this issue by detecting when the console's `ENABLE_VIRTUAL_TERMINAL_INPUT` flag is enabled and, when it is, switching to an alternate system for generating console input:

 * For most input, winpty replaces the keydown `INPUT_RECORD` with records representing the VT/100 encoding of the key.  (See https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/agent/ConsoleInput.cc#L722.)

 * For navigation keys (arrows keys, Home/End), when no modifier was used (i.e. no Alt/Shift/Ctrl), winpty instead sends keydown/keyup window messages.  This special case is necessary for Midnight Commander and probably vim too.  (See https://github.com/rprichard/winpty/issues/90 and https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/agent/ConsoleInput.cc#L684.)

Unfortunately, sending a window message doesn't work quite right, because the resulting console input records seem to use modifier state from the keyboard.  winpty would like to synthesize the modifier state, but I don't think there's a way to do that using `SendMessage`.  This issue also affects Ctrl-C handling, which is a more noticeable problem with winpty.  (See https://github.com/rprichard/winpty/issues/116 and https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/agent/ConsoleInput.cc#L361.)

**Comment by rprichard** [comment] 2017-08-19 09:46
AFAIK, other console emulators on Windows (e.g. ConEmu and ConsoleZ) ought to be able to work around this issue the same way that winpty does.

@i336

> Can urxvt or xterm from Cygwin running on a Windows X server talk to WSL?

AFAIK, one could run WSL urxvt or xterm connecting to any Windows X server, including Cygwin's.  One could also run any Cygwin terminal emulator (including mintty, urxvt, xterm) and connect to WSL using https://github.com/rprichard/wslbridge (a program I wrote).  wslbridge is also shipped as part of https://github.com/mintty/wsltty, a standalone package bundling mintty, wslbridge, and a Cygwin runtime DLL.

**Comment by Maximus5** [comment] 2017-08-19 10:02
FYI ConEmu has implemented a *workaround* long long ago

**Comment by fpqc** [comment] 2017-08-20 18:01
@Maximus5 I once got the msys2 bridge + wslbridge working together in tandem, but it stopped working.  Have you done any testing with it?

**Comment by Maximus5** [comment] 2017-08-20 18:17
Of course. It's working. Just use **latest** ConEmu version.

**Comment by zadjii-msft** [comment] 2017-09-08 18:32
Hey everyone,

I finally have an update on this bug! I have a potential fix in code review right now. 

To summarize the problem: We were only translating KEY_EVENTs into appropriate VT sequences when the events arrived from the window message loop. I moved the translation layer around, and now the INPUT_RECORDs written to the input buffer from the API (WriteConsoleInput) will also get translated appropriately.

It's not going to be available in the Fall Creator's Update, but it should be in the release that follows.

Thanks for your patience!

**Comment by jarun** [comment] 2017-09-08 19:24
Good news. :+1: I just wasted an hour figuring out the issue and reached here.

**Comment by rprichard** [comment] 2017-09-08 20:08
@zadjii-msft Good to hear.  A few questions:

1. Does this also affect recognition of Ctrl-C or Ctrl-Break? That is, when `ENABLE_PROCESSED_INPUT` is on, will `WriteConsoleInput` send a signal for these key presses? It currently doesn't, and I'm guessing that won't change. (If it did, I might be able to fix https://github.com/rprichard/winpty/issues/116.)

2. Is mouse input affected? There's an analogous situation where mouse input should produce VT escape sequences, and the encoding is controlled by mouse mode flags (e.g. 1006 for the "SGR mouse encoding"). I haven't gotten around to testing the console yet, so maybe `WriteConsoleInput` calls already do this conversion.

3. Do you have suggestions on how programs can detect this behavior change (i.e. so that a workaround can be disabled)? For my situation (winpty), I think it'd be worth it to temporarily enable the VT input mode and test whether input is converted (by calling `WriteConsoleInput` then `ReadConsoleInput`). I'm guessing there isn't a better approach, though I suppose checking the OS version could be faster.

**Comment by ericblade** [comment] 2017-09-11 15:24
That is great news (not so great that it won't make Fall.. oh well :-) ) .. just curious if this means that it ended up being significantly less work than initially expected? :-D

**Comment by zadjii-msft** [comment] 2017-09-11 16:11
@rprichard 
1. I don't believe it will. The change is pretty limited in scope to just the VT translator, so I don't believe any of the rest of the input is modified.
2. Mouse is unfortunately *not* fixed by this change. The keyboard events were easier to move than the mouse events unfortunately. I have a work item to address that issue before the end of the next release. 
3. I don't have any good recommendations on that topic, sorry. Both the mechanisms you describe sound like they should work, though I have no idea which would be faster.

It was a bit easier than anticipated, but like I mentioned, mouse input is actually *harder* than anticipated unfortunately.

**Comment by bgshacklett** [comment] 2017-09-11 18:41
Sorry, guys, I know you're being bombarded, but can you tell us how being on the Windows Insider fast track might affect the speed at which we see some of these changes?

**Comment by zadjii-msft** [comment] 2017-09-11 19:13
@bgshacklett If you're on the fast ring, you'll see these changes pretty immediately after they hit winmain, which is usually a month or so after I commit the code on my end. Otherwise, if you're on just a non-insider's build, you'll have to wait for the entire release to be finished, which is about twice a year (based on previous Windows 10 releases)

**Comment by bitcrazed** [comment] 2018-05-22 22:11
Thanks for the discussion.

Closing this issue since:
1. This issue is now fixed
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Closed by bitcrazed** 2018-05-22 22:11 UTC
Labels: console, feature, fixinbound

**Comment by maietta** [comment] 2023-08-27 14:35
I DO NOT CARE WHAT YOU PEOPLE KEEP SAYING. THIS ISSUE IS NOT FIXED IN WINDWOS 11 AND WSL2.

Why is this still an issue in 2023?

**Comment by nikhil-swamix** [comment] 2024-08-23 13:40
for people running cli scripts in python: disable this

Terminal › Integrated: Windows Enable Conpty

key navigation will work, for packages like rich, fire, click cli tools...
