### ISSUE TITLE
Can't find "Bash on Ubuntu on Windows" icon from start menu

### ISSUE THREAD

**Issue by trainto** [Microsoft/WSL#696] opened 2016-07-27 23:00 UTC
I installed bash properly, but I can't find "Bash on Ubuntu On Windows" icon.
I'm using the latest insider preview version, and language is Korean.
Just except the icon missing, everything just works fine.
I can run bash via cmd prompt, or windows + R and run bash.

**Comment by czy1996** [comment] 2016-07-28 14:02
I have encountered the same problem, and my language is Chinese. Is that the cause?
Bash still working though.

**Comment by benhillis** [comment] 2016-07-28 15:08
Interesting, do you recall seeing an error message during install about not being able to create the start menu icon?

Could you take a look in the below Windows path and see if the shortcut is there?

`"%APPDATA%\Microsoft\Windows\Start Menu\Programs"`

**Comment by trainto** [comment] 2016-07-29 00:23
I didn't see any error message about net being able to create the icon.
(When I enabled developer mode, it showed error msg, but there was no any problem installing bash)
I'll have a look in the path mentioned when I get home.(I'm at work, and Windows 7 is installed)

**Comment by trainto** [comment] 2016-07-29 09:03
I've checked the directory which @benhillis mentioned, and found shortcut there.
However the file name is wrong. That was the problem.
The file name was "Windows.lnk의 Ubuntu에 대한 Bash". So I changed the file name to
"Bash on Ubuntu on Windows.lnk" and then the icon appeared in the start menu and everything is ok.
It might be problem of translation to other language from English.

**Comment by benhillis** [comment] 2016-07-29 23:59
Thank you very much for confirming. Yes it looks like the localization of this message was done incorrectly for some languages.  I'm inclined to agree with you that it probably doesn't need to be localized at all.

**Comment by iz0eyj** [comment] 2016-08-02 06:56
Hi Ben,
still lack ICMP for non-superuser.
We need to create a link and seti it "run as Administrator"... not the best :)
Again, would be possible to remove "Developer mode" setting for the Anniversary?

**Comment by cloudhan** [comment] 2016-08-03 18:18
I install bash with administrator, and installed with no error. But interestingly, what I find under `"%APPDATA%\Microsoft\Windows\Start Menu\Programs"`
is 
`Windows 中的 Bash on Ubuntu。lnk`
where the `。` is the Chinese version for `.`, which makes this link haven't a proper extension for the filename.

**Comment by leon0516** [comment] 2016-08-27 12:51
change C:\Users\XXXX\AppData\Roaming\Microsoft\Windows\Start Menu\ ` Programs Bash on Ubuntu。lnk `
with  C:\Users\XXXX\AppData\Roaming\Microsoft\Windows\Start Menu\ ` Programs Bash on Ubuntu.lnk `

**Comment by divyampandey** [comment] 2016-10-10 08:02
I have also checked the directory but there is nothing. Also I am not able to save any file from bash terminal.Can anyone help plz.

**Comment by sunilmut** [comment] 2016-10-10 18:05
@divyampandey - Can you provide more details around what is that you are trying (repro steps would be nice)? What is the error that you are seeing? If your issue is unrelated, opening a new issue with [this](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) format would get you the most traction.

**Comment by ioweb-gr** [comment] 2016-10-26 09:28
Today also my icon went missing. Maybe some antivirus/antimalware cleaned it up because I can't find it on `"%APPDATA%\Microsoft\Windows\Start Menu\Programs"`. 
Is there a command to restore it?

**Comment by cloudhan** [comment] 2016-10-26 11:14
@ioweb-gr it is basically a link with target,
```C:\Windows\System32\bash.exe ~```,
you can just create on your own

**Comment by ioweb-gr** [comment] 2016-10-26 12:10
I see, thank you. I never paid attention to it so I was thinking it might be something like cygwin's bat file.

**Comment by tara-raj** [comment] 2018-05-29 20:41
Closing this issue as it's based on lxrun (older version of distro acquisition path).

**Closed by tara-raj** 2018-05-29 20:41 UTC
Labels: localization, workaround-available
