### ISSUE TITLE
dnsmasq serving dhcp on Hyper-V Switch fails

### ISSUE THREAD

**Issue by philips** [microsoft/WSL#2232] opened 2017-06-18 06:35 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  

I am trying to run a dhcp server on a [NAT network configured for Hyper-V](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network) with the end goal of booting [minikube](https://github.com/kubernetes/minikube/issues/1598) on Windows with a NAT between the host network.

My NAT network IP is showing up in WSL:

```
4: eth2: <BROADCAST,MULTICAST,UP> mtu 1500 group default qlen 1
    link/ether 00:15:5d:56:aa:04
    inet 10.0.75.1/24 brd 10.0.75.255 scope global dynamic
       valid_lft forever preferred_lft forever
    inet6 fe80::8530:6a71:1dec:f59b/64 scope global dynamic
       valid_lft forever preferred_lft forever
```

And I have configured dnsmasq to work using this setup.

```
$ cat dnsmasq.conf
dhcp-range=eth2,10.0.75.2,10.0.75.150,12h
interface=eth2
listen-address=10.0.75.1
```

```
sudo dnsmasq -C dnsmasq.conf  -d --log-dhcp
```

However, hosts on the network are not getting DHCP with this configuration. I verified my networking is setup correctly to support a dhcp server in two ways:

1. Boot Ubuntu VM via hyper-v attached to the same bridge and run dnsmasq there. The other Hyper-V VMs get DHCP offers just fine.
2. Running a Go program that runs under WSL which servers up DHCP: https://github.com/krolaw/dhcp4/blob/master/example_test.go

Both of these solutions worked OK. So, there must be something wrong with dnsmasq + WSL.

* What's wrong / what should be happening instead:

dnsmasq should work

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

https://drive.google.com/open?id=0B9EpUQkaXcl-SE1rY3JLclBkdlk

**Comment by therealkenc** [comment] 2017-06-26 22:47
This one has been dangling for a bit. Here's the [gist](https://gist.github.com/therealkenc/6ba43a4b6fad67c7d09e2d863ed1dcf3)....
```
[...]
socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 4
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
setsockopt(4, SOL_IP, IP_MTU_DISCOVER, [0], 4) = 0
setsockopt(4, SOL_IP, IP_TOS, [192], 4) = 0
setsockopt(4, SOL_IP, IP_PKTINFO, [1], 4) = 0
setsockopt(4, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
bind(4, {sa_family=AF_INET, sin_port=htons(67), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
[...]
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=10, events=POLLIN}, {fd=11, events=POLLIN}], 8, -1) = 1 ([{fd=4, revents=POLLIN}])
time(NULL)                              = 1497766351
recvmsg(4, 0x7fffd4d62bf0, MSG_PEEK|MSG_TRUNC) = -1 EINVAL (Invalid argument)
[... ad nauseum]
```

Socket descriptor 4 looks okay at first glance, but maybe there are some gaps in those socket options. `MSG_TRUNC` is supported as far as I know. There are no hits on `MSG_PEEK` in github so maybe that's novel; dunno.

There's also a lot of fails on `/dev/log` (descriptor 13), but they all look soft.

**Comment by therealkenc** [comment] 2021-05-05 17:44
Whatever the cause of that `EINVAL` on `recvmsg`, it will be better in WSL2. Marking that much fixed in WSL2. Serving up DHCP will fail for unrelated reasons on WSL2 (as of 19043 and 21370) for reasons unrelated to the syscall fail (#4150 and friends).

**Closed by therealkenc** 2021-05-05 17:44 UTC
