### ISSUE TITLE
Ubuntu2004 Can't start

### ISSUE THREAD

**Issue by Aylaasia-LiYiyang** [microsoft/WSL#8258] opened 2022-04-09 06:31 UTC
### Version

Microsoft Windows [version 10.0.22000.556]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Distro Version

Ubuntu 20.04

### Other Software

PS C:\Users\86183> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu20.04LTS         Stopped         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2

### Repro Steps

PS C:\Users\86183> ubuntu2004.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070050
Error: 0x80070050 ?????

### Expected Behavior

entry bash.

### Actual Behavior

PS C:\Users\86183> ubuntu2004.exe
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070050
Error: 0x80070050 ?????

**Comment by ql11** [comment] 2022-04-09 09:17
Try WSL.exe
Ref https://github.com/microsoft/WSL/issues/8257
![屏幕截图 2022-04-09 171521.png](https://s2.loli.net/2022/04/09/qN4swjWXA3h8xMy.png)

**Comment by xygdys** [comment] 2022-04-09 16:39
I faced this error too.

I solved it by unregistering ubuntu20.04.

This command will delete your files.

So you need to backup your files before doing this.

**Comment by NotTheDr01ds** [comment] 2022-04-11 15:25
For anyone having this issue, please see my answers to a related question on [Ask Ubuntu](https://askubuntu.com/q/1401830/1165986).  And please let me know the results so that I can update the answers accordingly.

**Comment by pmartincic** [comment] 2022-04-12 21:44
Duplicate of #8257

**Closed by pmartincic** 2022-04-12 21:44 UTC
