### ISSUE TITLE
metadata allows us to have correct permissions, but saving a file overrides permissions back to 755

### ISSUE THREAD

**Issue by nickjj** [Microsoft/WSL#3165] opened 2018-05-07 18:26 UTC
* Your Windows build number:  Version 10.0.17134.1 (Windows 10 Pro, Spring 2018 edition)

* What you're doing and what's happening:

1. Enable metadata in your `/etc/wsl.conf`
2. Go to one of your WSL mounted drives
3. `touch hi.txt`
4. `chmod 644 hi.txt`
5. `stat -c "%a %n" hi.txt` => 644 hi.txt
6. Open `hi.txt` in VSCode, make changes to the file and save it.

* What's wrong / what should be happening instead:

I would expect that `hi.txt` still has 644 permissions but if you run `stat -c "%a %n" hi.txt` you'll see that it returns 755 now instead.

It's like the metadata permissions are being stripped away.

* Thoughts:

Someone on Reddit says this is because VSCode forces safe writes which means a new file gets copied to a tmp directory which is to help prevent data loss.

However, VSCode has no option to disable this, so metadata is essentially not available since every file you edit will end up having it removed.

Is this something that can be fixed and patched into the stable version of Windows without having to wait 6+ months for the next big release?

**Comment by DarthSpock** [comment] 2018-05-07 18:35
This has to do with VS Code honoring permissions therefore is a VS Code actionable which has already has an issue: https://github.com/Microsoft/vscode/issues/49021. I recommend adding your input there to help prioritize the work.

**Comment by nickjj** [comment] 2018-05-07 18:41
Thanks, I didn't notice that open issue on the VSCode side of things.

Other editors seem to have worked around this by disabling safe writes (phpStorm specifically). I don't personally use that, but I'm going by what I read here https://github.com/andrewmackrodt/docker-sync-wsl-native#use-wsl-as-the-default-terminal-in-phpstorm.

**Comment by DarthSpock** [comment] 2018-05-07 18:56
Well you can run the Linux version of VS Code in the meantime if you like. That is, if you don't mind installing VcxSrv or Xming. If the permissions aren't a hard stop though, I'd just chmod it again after saving the changes.

**Comment by nickjj** [comment] 2018-05-07 19:03
Yeah previously I ran Sublime Text through mobaxterm because prior to either 17.09 or 18.03 stable you couldn't run VSCode through WSL (along with other Electron apps).

Trying to avoid that now simply because it's nice having 1 editor that works on both sides and I run all of my code through Docker so I'm not really losing anything in terms of code complete (there's no support either way currently).

chmodding it afterwards is pretty brutal because in a typical web development session you might end up touching 30 files and it would be hard to keep track of that. Writing a script to chmod all files back to 644 might be dangerous too, since you could have legit executable files.

Hopefully it gets fixed on the nodejs side of things and then merged into VSCode shortly after.

**Comment by DarthSpock** [comment] 2018-05-07 19:17
Yep, that can get messy quickly. With the extended attributes, you should still be able to save to /mnt/c or whatever directory from Linux VSCode. 

> since you could have legit executable files.

I'd keep anything not legit in their own directory (the same directory for all non-legit), symlink them and run a script against that directory. But web development isn't my main area so maybe that isn't practical for you.

**Comment by therealkenc** [comment] 2018-05-07 21:51
> Trying to avoid that now simply because it's nice having 1 editor that works on both sides

One pretty common approach, which predates WSL by a decade or more with Samba shares and the like, is to just ignore it; especially if you spend a lot of time on the "Windows Side". On Windows, there sits all those `.html` files with the Windows exec bit set, and you never thought twice about it. The reason you don't think twice about it because `cmd.exe dir` doesn't draw the files in green. It _doesn't matter_ that they're green in WSL/Linux.

Other way to go is to just use native Linux VS Code in WSL like DarkSpock says. It already "works on both sides", if there is such a thing. I'm betting your `.html` and `.js` files don't end in `CRLF` either (nevermind the file mode). Which can be worked around. So can Windows `git`. But why.

**Comment by nickjj** [comment] 2018-05-07 22:07
I did have to configure VSCode to use `"files.eol": "\n"` to get beyond some CRLF related issues (especially with Docker entrypoint scripts).

You are right in that I could choose to ignore them. My main gripe isn't so much getting smacked in the face with a bunch of green text, it's every file I commit to version control ends up being tagged as executable. All of my recent repos on Github are filled with executable files that shouldn't be.

I extensively researched this and wasn't able to find any git setting that would get around that. I don't use Windows git, or really develop anything Windows specific.

99% of the time when I edit a file it's by running `code .` through ConEmu in a WSL mounted directory. Working on Docker powered web applications or Bash scripts / Ansible stuff.

The only semi-nice thing about having a VSCode Windows installation is having the right click menu context for editing a single file but I rarely use it.

One perk of going native WSL VSCode that I see so far is that you can now edit files like your `~/.bashrc` within WSL's "real" file system using VSCode. The Windows version wouldn't open those files.

By the way if anyone is curious, the native WSL VSCode does respect permissions. The test case presented in this issue produces the expected result.

**Comment by therealkenc** [comment] 2018-05-07 22:17
> it's every file I commit to version control ends up being tagged as executable

Yeah, in this "approach" you ignore that too. Consider, Microsoft has about 3.5 million lines of C/C++ code committed to their [internal git repo](https://blogs.msdn.microsoft.com/bharry/2017/05/24/the-largest-git-repo-on-the-planet/) with the exec bit set and CRLF EOL, and none of their 4000 programmers care. To be clear, it isn't how I roll. It isn't how you roll. I'm not saying go that way. But that doesn't change the nonpartisan observation that it _doesn't matter_.

> By the way if anyone is curious, the native WSL VSCode does respect permissions. The test case presented in this issue produces the expected result.

Exactly. Because of course it does. 👍

**Comment by nickjj** [comment] 2018-05-07 22:35
Fair enough. Do you think we should leave this one open, or could this eventually make its way into WSL so that editing files within Windows won't mess with the metadata?

**Comment by therealkenc** [comment] 2018-05-07 22:48
> or could this eventually make its way into WSL

There's no WSL actionable. It would be like asking Linus Torvalds if it will make its way into the Linux kernel running in Docker with a `C:\` share and Windows VS Code editing a file on the share. The feature needs to be implemented in Windows VS Code. As to closing, meh. Your poison.

**Comment by nickjj** [comment] 2018-05-07 22:55
Are you ok with keeping it open for a bit to see if anyone else has an opinion, since it's labeled as discussion? If it dies out, I'll close it in a few days.

**Comment by therealkenc** [comment] 2018-05-07 23:01
Sure. Plenty others where this one came from. Eventually they get closed (on no particular schedule) when the discussion dies out; or close it yourself whenever you want.

**Comment by nickjj** [comment] 2018-05-07 23:30
Most projects I work on are under 50,000 lines of code and at most hundreds of files. Typical Ruby / Python / Elixir based web applications with a lot of HTML, CSS and JS mixed in.

Startup time in a project with 17,000 lines of code was about 500ms slower with native WSL if I just eyeball the speed. There's a noticeable delay before the window becomes visible but it's not a deal breaker.

That is good to know tho, I'm sure others work on much larger projects.

One of my main focuses is readability. I do notice the font looking a bit worse on native WSL VSCode (it's quite thin, a little blurry and looks like the AA is jacked up). Readability is important because I record video tutorials for developers. That's one more potential downside to native WSL VSCode.

**Comment by therealkenc** [comment] 2018-05-07 23:46
> I do notice the font looking a bit worse on native WSL VSCode (it's quite thin, a little blurry and looks like the AA is jacked up

You might try VcXsrv and make sure your have "native opengl" off (sic) and `LIBGL_ALWAYS_INDIRECT` not set (despite poor advice to the contrary). Don't run compiz, because that's crazy. I get results that look about the same as Real Ubuntu, at least to the naked eye on my standard HD rig. But we're treading dangerously into #637 territory, so I'll quit now while I'm ahead.

**Comment by fpqc** [comment] 2018-05-09 03:27
@therealkenc I always wondered if MS could just add additional metadata caching directly to the read and write file functions in the Windows SDK.  Right now, programs like sublime do cache the Windows permission bits, and I assume that is automatic, so I would also assume that they could also cache and rewrite the new LX data.

Why couldn't this work (so all programs compiled on the latest SDK would work)?

**Comment by Biswa96** [comment] 2018-05-09 03:31
You can read and write that metadata with NtQueryEaFile and NtSetEaFile.

**Comment by therealkenc** [comment] 2018-05-09 05:17
"Caching" has nothing to do with it. The problem is [VS Code](https://github.com/Microsoft/vscode), via [Electron](https://github.com/electron/electron), via Electron's [NodeJS](https://github.com/nodejs/node), via [libuv](https://github.com/libuv/libuv) has no idea how to set WSL's file and directory mode bits. If you [look](https://github.com/libuv/libuv/blob/1954e9e3c1f89c1c65ffbe89de8dd838fef02b1b/src/win/fs.c#L403) at the libuv code, it (obviously) doesn't set the mode bits on file creation. Because, there was no API to do so. The API is now, presumably, [`NtSetInformationFile()`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntsetinformationfile) with [`FileStatLxInformation`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/ne-wdm-_file_information_class) and [`struct _FILE_STAT_LX_INFORMATION`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_stat_lx_information). Presumably, because I haven't actually tried it.

`libuv` could be updated to call `NtSetInformationFile()` if someone were motivated enough. There's a minor gap in that Windows has no process `umask`, but that could probably be hand waved. But just recompiling against a new SDK doesn't get you there, because said SDK has no idea what mode to give the new file or directory. On Linux, that's the third param of [open()](http://man7.org/linux/man-pages/man2/open.2.html) passed from userspace ([here](https://github.com/libuv/libuv/blob/1954e9e3c1f89c1c65ffbe89de8dd838fef02b1b/src/unix/fs.c#L265), that's libuv). [CreateFile()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx) knows of no such animal.

So you say, just have CreateFile() set some reasonable defaults. Okay. But that is, or at least should be, the `umask`/`dmask`/`fmask` you configure when you mount DrvFs. Just like [ntfs-3g](https://linux.die.net/man/8/ntfs-3g). The "reasonable default" MSFT has chosen for now, sadly, as Nick discovered, `0755`. There is nothing to recompile. You just don't like the defaults.

**Comment by therealkenc** [comment] 2018-05-28 05:12
> Are you ok with keeping it open for a bit to see if anyone else has an opinion, since it's labeled as discussion? If it dies out, I'll close it in a few days.

Pretty "ran course" at this point.

**Closed by therealkenc** 2018-05-28 05:12 UTC
Labels: discussion

**Comment by mindplay-dk** [comment] 2018-12-11 13:02
Team of PHP developers using PHP Storm here.

This is a huge problem for us - it's really hard to understand what the problem is, because we didn't use to have this problem with previous versions of WSL.

I use the Git integration in PHP Storm on Windows - and for that to work, I have to run a Windows version of Git for Storm, as well as a Linux version of Git for general use in the Linux console.

This combo worked just fine in early versions of WSL.

Then came this update where we had to manually enable metadata in the WSL config file - at this point, things started to break, but enabling metadata in the config file seemed to fix it.

Some time after that, another update must have been rolled out, because everything went to sh*t - I make a rule of always checking out in the Linux console, and usually, after that, there's been no problem, but since one of the last update, everything is completely messed up.

I'm either seeing *all* files as modified with `git status` on the Linux console - or seeing random files as modified in Storm, since the files have permissions that can't be applied to the Windows file-system.

Many developers don't notice the file permission changes and end up committing and pushing those - and I clone them on Windows, and half the files immediately appear to be changed, and there's no way to get them to appear as not changed.

I'm getting desperate. I have my entire work environment set up with WSL, as this was working beautifully for a long time. Suddenly there's an update and my whole work environment is trash.

I'm *not* Linux savvy, *at all* - I'm a programmer, not a sysadmin.

If there's any way to set up a WSL that worked as it did originally, please, can somebody provide step-by-step instructions?

Or should I just quit Windows and put up with an actual Ubuntu installation? 😭

**Comment by teras** [comment] 2018-12-17 19:48
>  there's no way to get them to appear as not changed.
I have exactly the same issue here  ☹️

**Comment by thefallentree** [comment] 2019-01-17 22:37
what is the conclusion here?  Either we need an way to tell windows create file in 0644 mode , or we need to fix every IDE to properly detect metadata on NTFS files and know to preserve that when doing "write"

**Comment by herrvigg** [comment] 2019-03-10 23:55
@mindplay-dk wrote:
> This is a huge problem for us - it's really hard to understand what the problem is, because we didn't use to have this problem with previous versions of WSL.

Same here, i used to have something working nicely by editing in Windows and pushing to real Linux systems but now it's become a complete chaos with the file permissions. It seems it worked fine when everything was owned by root in WSL but i can't really remember how the permissions were set. In any case it has become worse now (from [this](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/)?) and even if i mount the windows drives without metadata the problem is not solved 😭

**Comment by mindplay-dk** [comment] 2019-03-23 15:30
> In any case it has become worse now (from [this](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/)?)

Possible.

From this article:

> For files that don’t have metadata, we apply the same approach as what is described in pre-17063 builds.
> ...
> Once the file or folder has metadata, Windows and Linux permissions will not remain in lock-step with each other.

Perhaps the mistake was enabling the metadata feature?

As I recall, I started having problems before the metadata feature was introduced - and it seemed like enabling metadata solved those problems for a while, and then later it all went south.

I'd be fine with a single owner of everything - I'm obviously only using the Linux thing for local development and don't plan on running a public Linux web-server from under Windows. (Does anyone?)

**Comment by jonreeve** [comment] 2019-06-24 20:30
Bit of a dead thread to post I know but since it doesn't look like there was a great answer for people working with git projects under WSL, I would suggest `git config core.filemode false` to tell git to ignore that executable bit flip-flopping, and just see it as unchanged. You can of course toggle this off again if you want to specifically set it, then turn it back on. Helps me keep some of my sanity with IntelliJ IDEA and WSL 😜

**Comment by gerardbosch** [comment] 2020-05-02 10:33
> Sadly, this needs to be done for every repository manually, which is a pain. Also, `--global` does not work since git `init` and `clone` override what is set in clone for core.filemode see [1](https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes)

You can add a git alias for `clone` and `init` and use it from now on to newly cloned repos:
`.gitconfig:`
```
[alias]
    cl = clone --config core.filemode=false
    in = init --config core.filemode=false
```
Just use `git cl` from now on in Windows.
