### ISSUE TITLE
Nested WSL invocations fail with 'Operation not supported'

### ISSUE THREAD

**Issue by mystor** [Microsoft/WSL#3334] opened 2018-06-27 22:18 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

```bash
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.492]

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

I am using the Ubuntu WSL distribution from the Windows Store.

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

From within WSL's bash environment, I invoke a native windows program. As part of that windows program's execution, it executes `wsl.exe` to do work inside the linux environment. This nested call into WSL fails with the error:
```
 O p e r a t i o n   n o t   s u p p o r t e d .
```

![wsl nested](https://user-images.githubusercontent.com/1261662/42002311-d0de7ea2-7a34-11e8-8a28-dceef46847b5.PNG)

This can also be triggered with the one-liner from WSL bash, which works if run directly from powershell/cmd.exe:
```bash
$ cmd.exe /C wsl.exe ls
```

* What's wrong / what should be happening instead:

One of the following:
1. A more clear error message which explains that nested calls into WSL are not supported, ideally with a reference to a document where I can read an explanation, or
2. The nested call into WSL should succeed as I would expect.

* Strace of the failing command, if applicable:  (If `some_command` is failing, then run `strace -o some_command.strace -f some_command some_args`, and link the contents of `some_command.strace` in a [gist](https://gist.github.com/) here)

I cannot strace the call into WSL (as it is from windows), however I can strace the call into the cmd.exe process.

https://gist.github.com/mystor/096aced5700e28ae53916c73889e703a

**Comment by benhillis** [comment] 2018-06-27 22:21
This works in newer Insider builds.

**Comment by benhillis** [comment] 2018-06-27 22:23
Marking as duplicate of #2370.

**Comment by mystor** [comment] 2018-06-27 22:24
Oh awesome! Thanks @benhillis :-)

**Closed by benhillis** 2018-06-27 22:23 UTC
