### ISSUE TITLE
ls: cannot access '/mnt/c/': Input/output error without admin rights

### ISSUE THREAD

**Issue by sinapis** [microsoft/WSL#4489] opened 2019-09-11 09:04 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18975.1000]
WSL: 4.19.59-microsoft-standard

* What you're doing and what's happening: 
launch cmd.exe as regular user and then execute:
wsl ls /mnt/c
the output received is:
ls: cannot access '/mnt/c': Input/output error

* What's wrong / what should be happening instead:
/mnt/c content should be listed

Note that if I launch cmd.exe as administrator and then execute "wsl ls /mnt/c", content is listed as expected

**Comment by Biswa96** [comment] 2019-09-11 09:11
Duplicate of https://github.com/microsoft/WSL/issues/4377

**Comment by sinapis** [comment] 2019-09-11 10:20
@Biswa96 are you sure it's the same? I only get the error when I run as non-elevated user

**Comment by benhillis** [comment] 2019-09-11 14:00
Yes it is very likely the same issue.

**Closed by benhillis** 2019-09-11 14:00 UTC
