### ISSUE TITLE
Files created on Host machine from within WSL2 cause error code 0x80004005 when attempting to move files.

### ISSUE THREAD

**Issue by Doommius** [microsoft/WSL#7632] opened 2021-11-02 00:10 UTC
### Version

[Version 10.0.22000.282]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

20.04

### Other Software

SCP/rsync from remote machine onto /mnt/C/folder/..

### Repro Steps

SCP files from remote machine onto /mnt/ location and observe that windows explorer is unable to move the files.

### Expected Behavior

Windows explorer should be able to move these files.

### Actual Behavior

![image](https://user-images.githubusercontent.com/13621747/139758807-6b7c9286-0c7d-4344-900d-c9d8e59e3be7.png)

**Comment by OneBlue** [comment] 2021-11-09 18:31
@Doommius: Based on the error the issue is most likely that those files are not writable by your default wsl user for this distro.

This should be fixed by either giving write access to your default wsl user, or changing the default wsl user to root via `[distro] config --default-user root`

**Comment by OneBlue** [comment] 2021-11-09 18:32
If that doesn't work, feel free to [capture logs](https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually) and attach them to this issue

**Comment by Doommius** [comment] 2021-11-09 23:28
Hey @OneBlue. The issue isn't that WSL is given issues. The issue is that the host(windows) is having permission issues with files created via WSL. Which logs Files should I provide for this?

**Comment by OneBlue** [comment] 2021-11-09 23:31
When accessing files through the explorer, the files are accessed as the default wsl user so if this user doesn't have permissions to change those files, neither does the explorer.

Can you run `ls -la /path/to/folder`  to check the permissions and then `whoami` to see who the default user is ?

**Comment by Doommius** [comment] 2021-11-09 23:49
jervelund@Doommius-Desktop:/mnt/f/uploaded/store-2021-09-25-1$ ls -la
Total 0
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:55  .
drwxrwxrwx 1 jervelund jervelund 512 Nov  2 11:46  ..
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:52 'SF reliabledict RR (RR)'
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:55 'SF reliabledict RR (RR) '
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:52 'SF reliabledict S (S)'
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:55 'SF reliabledict S (S) '
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:55  current
drwxrwxrwx 1 jervelund jervelund 512 Sep 25 21:52  latest
jervelund@Doommius-Desktop:/mnt/f/uploaded/store-2021-09-25-1$ whoami
jervelund

And if I run ls in powrshell in the same folder I get
mode, ... 
d-----,....

**Closed** 2024-02-01 12:09 UTC
