### ISSUE TITLE
Error: 0x8007005 when Installing Ubuntu

### ISSUE THREAD

**Issue by longtth** [microsoft/WSL#3671] opened 2018-11-18 13:39 UTC
I've check other related threads but can't find solution so I post a new one. 

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
`Microsoft Windows [Version 10.0.16299.726]`
```
Windows(R), Enterprise edition:
    Volume activation will expire 5/12/2019 5:48:52 PM
```

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I choose to manual install ubuntu1804 but after activated WSL I can't run the ubuntu1804.exe, got `Error: 0x80070005` problem despite using an elevated Powershell to run command. 

```
PS C:\users\longnx> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux 
(OK, Windows ask me for restart) 
(Restarted PC)
PS C:\wsl\ubuntu> .\ubuntu1804.exe
Error: 0x80070005
```

* What's wrong / what should be happening instead:
Can't install Ubuntu1804 on my Windows 10 
It should be installed sucessfully. 

I've tried to collect log but got error: 
```
PS C:\wsl\ubuntu> logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749843B3F5C9} -mode 0x00000008 -ft 1
0:00 -o .\lxcore_kernel.etl -ets
logman.exe : A value that is not valid (.\lxcore_kernel.etl) was specified for the outputFormat parameter. Valid
values are Text and Xml.
At line:1 char:1
+ logman.exe create trace lxcore_kernel -p {0CD1C309-0878-4515-83DB-749 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter
```

**Comment by chrisjbreisch** [comment] 2019-03-07 17:55
Do you have McAfee Endpoint Security installed? If so, then this is likely a duplicate of [#2940](https://github.com/Microsoft/WSL/issues/2940).

**Comment by longtth** [comment] 2019-03-11 16:15
@chrisjbreisch sorry for late reply, yes, I have McAffee Endpoint Security install on my machine.

**Comment by lothario5** [comment] 2019-12-30 08:29
try below WA:
1) download lxrun from below url
https://github.com/DDoSolitary/LxRunOffline/releases
2) install subsystem linux from microsoft store.
3) execute below command to install your linux in you dir with administrator.
PS C:\Users\***> C:\Users\***\Downloads\LxRunOffline-v3.4.0\LxRunOffline.exe install -n <name> -d 'dir which you want to installed' -f 'C:\Program Files\WindowsApps\<your linux distribution>\install.tar.gz'
example:
PS C:\Users\test> C:\Users\test\Downloads\LxRunOffline-v3.4.0\LxRunOffline.exe install -n ubuntu1804 -d 'C:\subsystem\ubuntu1804' -f 'C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2019.522.0_x64__79rhkp1fndgsc\install.tar.gz'
4) then you can use bash/wsl to login your subsystem with root user. then uninstall subsystem linux from microsoft store, you don't need it anymore.

**Closed** 2024-02-01 12:52 UTC
Labels: failure-to-launch
