### ISSUE TITLE
WSL2: Unable to start WSL2 distro while WSL1 works normally.

### ISSUE THREAD

**Issue by SmartPolarBear** [microsoft/WSL#4115] opened 2019-06-13 15:43 UTC
## Windows Version
Microsoft Windows [Version 10.0.18917.1000]
## Steps required to reproduce
Follow the instructions on https://docs.microsoft.com/en-us/windows/wsl/wsl2-install
## Copy of the terminal output

PS C:\WINDOWS\system32> ubuntu
An existing connection was forcibly closed by the remote host.
PS C:\WINDOWS\system32> ubuntu
An existing connection was forcibly closed by the remote host.
PS C:\WINDOWS\system32>
## Expected Behavior

The ubuntu distro should have started.

Sent from Mail for Windows 10

**Comment by benhillis** [comment] 2019-06-13 15:59
Duplicate of #4105.

**Closed by benhillis** 2019-06-13 15:59 UTC
