### ISSUE TITLE
Can't mount encfs-encrypted volume using Linux encfs

### ISSUE THREAD

**Issue by kkeane** [Microsoft/WSL#1074] opened 2016-09-11 19:25 UTC
This is a companion to #1073 .

The Linux version of encfs does not work on bash on Ubuntu on Windows. When attempting to mount an encrypted volume, an fusermount issue prevents mounting.
- Expected results
  kkeane@LENOVO4G:~$ mkdir -p ./plaintextdir
  kkeane@LENOVO4G:~$ /usr/bin/encfs ./encrypteddir ./plaintextdir
  EncFS Password:
  kkeane@LENOVO4G:~$ ls ./plaintextdir
  <decrypted contents of encfs drive>
- Actual results (with terminal output if applicable)
  (Note: bin/kpmount is a script that automates the encfs call with the same paramters as provided above)

kkeane@LENOVO4G:~$ bin/kpmount
EncFS Password:
fuse: device not found, try 'modprobe fuse' first
fuse failed.  Common problems:
- fuse kernel module not installed (modprobe fuse)
- invalid options -- see usage message
  kkeane@LENOVO4G:~$
  kkeane@LENOVO4G:~$ sudo modprobe fuse
  sudo: unable to resolve host LENOVO4G
  [sudo] password for kkeane:
  modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.4.0+/modules.dep.bin'
- Your Windows build number
  14393
- Steps / All commands required to reproduce the error from a brand new installation 
  cd
  mkdir ./plaintextdir
  create an encfs-encrypted directory on another system
  copy encrypted directory to ./encrypteddir
- Strace of the failing command
  N/A
- Required packages and commands to install
  encfs
  fusermount (which can't work since it is a kernel module).

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment] 2016-09-11 20:47
Thanks for posting the follow-up ticket!  Just for completeness, this presumably has the same root cause as #17 and #412 , among others.

**Comment by therealkenc** [comment] 2016-09-14 00:16
I really hope FUSE/CUSE given consideration after the obvious low-hanging syscall surface stuff is done. Given that kernel modules in the native sense can't ever be a thing on WSL, and open-source is a non-starter for reasons, FUSE is one way out of WSL pico-process jail. There's a User Voice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl) that isn't getting enough love.

**Comment by therealkenc** [comment] 2017-11-16 12:49
Dupe of #17 and others like Adam indicated.

**Closed by therealkenc** 2017-11-16 12:49 UTC
Labels: duplicate
