### ISSUE TITLE
dmesg: read kernel buffer failed: Function not implemented

### ISSUE THREAD

**Issue by spoiledsport** [Microsoft/WSL#1886] opened 2017-04-12 02:40 UTC
I am getting this error when running dmesg on the latest version of Creators Edition. THis was working before. I uninstalled and reinstalled WSL to no avail. 

Is this a known issue?

**Comment by stehufntdev** [comment] 2017-04-13 16:49
Can you please fill out the template?  For this issue we would need a strace to see what syscall is failing.

**Comment by spoiledsport** [comment] 2017-04-13 20:58
[strace.dmesg.txt](https://github.com/Microsoft/BashOnWindows/files/920830/strace.dmesg.txt)

* Expected results
printing of the boot up information 
* Actual results (with terminal output if applicable)
dmesg: read kernel buffer failed: Function not implemented

* Your Windows build number
Microsoft Windows [Version 10.0.15063]

* Steps / All commands required to reproduce the error from a brand new installation 
1.- run bash on Ubuntu for windows
2.- run dmesg

* Strace of the failing command

**Comment by stehufntdev** [comment] 2017-04-13 21:09
Thanks for the strace!  Looks like it is failing because it wasn't able to read from kmsg, which looks like a duplicate of #1321.  Can you please confirm?

open("/dev/kmsg", O_RDONLY|O_NONBLOCK)  = 3
lseek(3, 0, SEEK_DATA)                  = -1 EINVAL (Invalid argument)
read(3, 0x60c3e0, 8191)                 = -1 EAGAIN (Resource temporarily unavailable)
close(3)                                = 0

**Comment by larsbrinkhoff** [comment] 2017-10-13 11:05
Reproduced.  Same output from strace.  Writing something to /dev/kmsg makes dmesg work.

**Comment by dman777** [comment] 2018-02-05 15:28
I am hitting this also. Any updates?

**Comment by therealkenc** [comment] 2018-02-05 15:59
Only that this is dupe #1321. It was pinged three weeks ago ([message](https://github.com/Microsoft/WSL/issues/1321#issuecomment-357345985)).

**Closed by therealkenc** 2018-02-05 15:59 UTC
Labels: duplicate

**Comment by almdrx** [comment] 2018-02-13 20:40
Same here... 😕

**Comment by bcyphers** [comment] 2018-09-19 22:51
Same here. Encountered trying to install something with `apt-get`, and now I can't run any `apt-get` commands.

**Comment by kenorb** [comment] 2018-10-04 16:02
It's fixed now. Please [upgrade WSL](http://wsl-guide.org/en/latest/update.html).

**Comment by Starnovice** [comment] 2019-08-03 18:32
I have followed all of  upgrade WSL and nothing changed.  Does anybody have a real fix for this problem?
