### ISSUE TITLE
Kali Linux release 2/22/2018 through Store, WslRegisterDistribution fails with error 0x80070057

### ISSUE THREAD

**Issue by PhMajerus** [Microsoft/WSL#3054] opened 2018-03-26 23:29 UTC
Windows 10.0.16299.334 Pro x64 en-us (current public release build with current cumulative update KB4089848 at time of issue).
Kali Linux installed through the Store on original release date, no problem observed (but not used much).
Other distributions (Ubuntu and Debian) working fine.
Today Kali Linux got updated through the Store, to version 1.1.2.0 released on 2/22/2018.

After update, launching the Kali Linux instance shows the following:
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

![kalifail](https://user-images.githubusercontent.com/25664275/37938406-f3d27000-315d-11e8-9840-a5ad7ab50dcb.png)

Uninstalling and reinstalling Kali Linux package works.

**Comment by DarthSpock** [comment] 2018-03-26 23:59
I think you'll need to address this with the Kali Linux team as they are responsible for the appx. Probably an update in response to the update to the launcher that is now open-source. See https://github.com/offensive-security/kali-linux-docker as that seems to be the go-to place for WSL issues that don't involve the WSL team. FWIW, I had no issues with the update but I don't have a clean image either.

**Comment by laoshancun** [comment] 2018-03-27 06:56
![image](https://user-images.githubusercontent.com/4952748/37951450-0335c486-31cf-11e8-9d7f-ca0e72b68eaf.png)
got this too.

**Comment by ioxplo** [comment] 2018-03-27 09:31
hi I am having the same issue. anyone has any idea on how to fix this? thanks so much

**Comment by Biswa96** [comment] 2018-03-27 10:38
I've not install the Kali-linux from store directly. But I've downloaded the appx-bundle from Store. The install.tar.gz gets ~30MB extra than previous. The extracted .tar.gz file is installed successfully (without appx). The problem may lies in the kali.exe. Kali developers changed many codes in that launcher. 
I shall find the problem....

**Comment by Biswa96** [comment] 2018-03-27 13:38
Whn I extract the kali.exe and install.tar.gz from Appx package, Kali installs rootfs successfully.

**Comment by ioxplo** [comment] 2018-03-27 14:14
Hi @Biswa96, where can you get the Appx package which contains kali.exe and install.tar.gz? Thanks

**Comment by TooYoungTooSimp** [comment] 2018-03-27 15:02
Same issue
![image](https://user-images.githubusercontent.com/6648049/37975936-eddede1c-3212-11e8-852a-cd9f64e26a7d.png)

**Comment by Biswa96** [comment] 2018-03-27 15:08
@ioxplo If you install it from Windows Store you don't need the Appx package. Enable hidden file view in explorer. Just go to C:\ProgramFiles\WindowsApps\ folder in file explorer. There may be a folder with "Kali" name. Open it. You may see the .exe and .tar.gz file. Copy it anywhere and run Kali.exe.

**Comment by bardware** [comment] 2018-03-27 15:14
> Whn I extract the kali.exe and install.tar.gz

What do you do with these files after extracting?

**Comment by Biswa96** [comment] 2018-03-27 15:19
Just run the kali.exe. Make sure to place kali.exe and install.tar.gz in same folder.

**Comment by Biswa96** [comment] 2018-03-27 15:21
@ioxplo If you install it from Windows Store you don't need the Appx package. Enable hidden file view in explorer. Just go to C:\ProgramFiles\WindowsApps\ folder in file explorer. There may be a folder with "Kali" name. Open it. You may see the .exe and .tar.gz file. Copy it anywhere and run Kali.exe. 

@bardware Then run the kali.exe. Make sure to place kali.exe and install.tar.gz in same folder.

**Comment by kevin-valerio** [comment] 2018-03-27 18:04
![screenshot_1](https://user-images.githubusercontent.com/24193167/37985826-1ac6110c-31fa-11e8-8056-93b341fa0247.png)

Same here...

**Comment by benhillis** [comment] 2018-03-27 21:22
Would it be possible to collect logs while attempting the install?

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by USTC-HuangZA** [comment] 2018-03-28 06:53
Same issue

**Comment by godmodenewbie** [comment] 2018-03-28 11:50
same issue, but when trying to run "bash" command from cmd, it works.
![screenshot 26](https://user-images.githubusercontent.com/28520136/38027062-13ebf208-32c1-11e8-9fa6-ba5bbe7902f4.png)

**Comment by Biswa96** [comment] 2018-03-28 13:12
Has anyone tried to uninstall the Kali Linux package fully from Windows Store and reinstall? 
The distro name has been changed in latest version.

**Comment by kyuuketsukikurai** [comment] 2018-03-28 14:05
Running kali.exe fixed it for me.

**Comment by bardware** [comment] 2018-03-28 14:33
> fixed it for me.

Running kali.exe actually brought the errormessage from the above screenshots.

**Comment by benhillis** [comment] 2018-03-28 14:38
If somebody that is hitting the issue could collect logs it would be helpful in getting this fixed. 

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by Biswa96** [comment] 2018-03-28 14:41
I installed it in a fresh VM and it works. So I advice to fully uninstall Kali from Windows Store and reinstall it. I may have find the cause.

**Comment by zikhan** [comment] 2018-03-28 16:24
I just started getting the problem today.
![image](https://user-images.githubusercontent.com/8488326/38041878-84308f86-3278-11e8-8326-910283597cf9.png)

I did notice when I run the wsl.exe, kali will run since it's the only distro on the system.
![image](https://user-images.githubusercontent.com/8488326/38041962-b3cd27e0-3278-11e8-955c-4dd37084ffd1.png)

Here are some logs:
[LinuxLogs.zip](https://github.com/Microsoft/WSL/files/1856806/LinuxLogs.zip)

**Comment by benhillis** [comment] 2018-03-28 17:28
Thanks, I have identified the issue and will work with Kali to get this fixed.

**Comment by DarthSpock** [comment] 2018-03-28 19:40
So the bare image for WSL stems from the link I had referenced above but it appears the official page is https://github.com/offensive-security/Kali-WSL-chroot where it shows in the main page: 

> Kali Linux Windows App for WSL chroot builder script.

So we should probably file Kali issues there instead. I edited my post above to remove the link.

**Comment by matte1006** [comment] 2018-03-28 22:01
same problem after the update

**Comment by thecmac** [comment] 2018-03-29 09:47
Any update on this?  I have installed metasploit, and would like to preserve my config without re-installing...

any advice welcome.

**Comment by benhillis** [comment] 2018-03-29 19:36
Unfortunately the updates version of the kali app uses a different distribution identifier than the previous version. This is causing WSL to think that the app is not installed, and when the install is attempted it fails because the root file system already exists.  The easiest way to rectify this issue will be to select Reset from Kali App Settings or uninstall and reinstall the app.

If you'd like to back up any information from your previous install you can use wslconfig.exe and wsl.exe:

```
C:\Users\benhill>wslconfig.exe /list
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
kali-rolling
openSUSE-42

C:\Users\benhill>wslconfig.exe /setdefault kali-rolling

C:\Users\benhill>wsl.exe
ben@BENHILL-DELL:/mnt/c/Users/benhill$ <back up files to somewhere in DrvFs>
```

**Comment by diveyez** [comment] 2018-03-30 03:25
wslconfig.exe /setdefault kali-rolling
bash

DONE

**Comment by diveyez** [comment] 2018-03-30 03:26
benhillis, why back it up? Just set the default to kali and type bash... 
This wont impact others neither as you can launch them by name.

**Comment by benhillis** [comment] 2018-03-30 03:30
Because Kali.exe won't work until you reinstall it reset.

**Comment by diveyez** [comment] 2018-03-30 03:33
Its working fine for me.
[https://imgur.com/a/lBbha](url)

**Comment by diveyez** [comment] 2018-03-30 03:44
Also, I realize there is an issue with using proxy/vpn in the WSL that I believe you commented on before.
nano /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
search google.com 
ctrl+x 
y enter
ping google, or anything you need. This is how I use openvpn with it.

**Comment by thecmac** [comment] 2018-03-30 09:13
cheers diveyez, all sorted.  I specified the default, and now my services will start.

**Comment by bityob** [comment] 2018-04-01 09:43
@zikhan 

> I just started getting the problem today. I'm scared to uninstall since I have some private keys on the instance for an ssh server that doesn't have username login.

You can access your kali (or any WSL app) file system, via the windows itself - 

```
C:\Users\<username>\AppData\Local\Packages\KaliLinux<randomchars>\LocalState\rootfs
```

**Comment by Izumiko** [comment] 2018-04-01 11:19
move rootfs folder to somewhere else
reset kali app
launch kali, wait it installing
delete the newly installed rootfs and move the old one back

then I can use command "kali"

**Comment by bardware** [comment] 2018-04-01 12:47
> reset kali app

I reset `kali` after this documentation: http://www.thewindowsclub.com/reset-windows-store-apps-windows-10
I use a german language Windows 10 - there are minor differences but now `kali.exe` works again.

**Comment by diveyez** [comment] 2018-04-03 08:46
PSA: Do not update windows unless you have to, right now there is a breakage going around with WSL.
My debian install got broken with the RS4 update, It will not reinstall from the store. I get a "debian.exe" not found error. They really like to break stuff at Microsoft. Why the hell do they call it an APP and put it in their Store anyway?

**Comment by DarthSpock** [comment] 2018-04-03 13:02
@diveyez If you have nothing meaningful to contribute, please don't flame out on MS as we do get email notifications for this and don't particularly like being spammed.

**Comment by alexverboon** [comment] 2018-04-04 18:34
@diveyez  thanks for the tip, wslconfig.exe /setdefault kali-rolling did the trick

**Comment by ioxplo** [comment] 2018-04-04 23:12
I did what @Izumiko mentioned
> move rootfs folder to somewhere else
> reset kali app
> launch kali, wait it installing
> delete the newly installed rootfs and move the old one back

with @bityob info to move the rootfs from
`C:\Users\<username>\AppData\Local\Packages\KaliLinux<randomchars>\LocalState\rootfs`

and Kali works again with installed packages still intact

**Comment by jdmurrayPluralsight** [comment] 2018-04-08 16:29
IMPORTANT: You must move the rootfs folder out of the C:\Users\<username>\AppData\Local\Packages\KaliLinux<randomchars>\LocalState for safe keeping because everything in the LocalState folder will be deleted. If you simply rename the rootfs folder (e.g., rootfs.sav) in place it will be deleted and you will loose your packages and content.

**Comment by laoshancun** [comment] 2018-04-11 12:48
mark it!!!
```bash
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800703fa
Error: 0x800703fa ???????????????????????

Press any key to continue...
```

**Comment by SquatchRage** [comment] 2018-05-14 03:50
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007019e
Error: 0x800703fa Illegal operation attempted on a registry key that has been marked for deletion.

Press any key to continue...

Tried all the suggested remedies and none of them have worked, anyone else getting this error?

**Comment by bkr32** [comment] 2018-05-14 05:04
@SquatchRage  a reboot fixed it for me

**Comment by gabrieldemarmiesse** [comment] 2018-05-23 17:18
I had this error:

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x800703fa
Error: 0x800703fa Illegal operation attempted on a registry key that has been marked for deletion.

Press any key to continue...
```

I went in "services" looked for the service called "LxssManager". Click on "start" or "restart". Reopened linux and it worked.

**Comment by DarthSpock** [comment] 2018-05-23 18:07
@gabrieldemarmiesse That's #2576

**Comment by gabrieldemarmiesse** [comment] 2018-05-23 18:15
My bad, I'll remove that comment to avoid confusing people.

**Comment by qpanapuk** [comment] 2018-06-06 20:50
***BAD ENGLISH***
1) go there => https://docs.microsoft.com/en-us/windows/wsl/install-win10
2) copy there => Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
3) run as administrator PowerShell
4) Paste it (2) and press Y and Enter
5) Wait until the computer reboots
6) Run Kali Linux again
7) Profit

**Comment by hleach** [comment] 2018-06-12 14:24
In my case the LxssManager service was set to manual and needed to be started up after every reboot. The startup type could not be set in services.msc (even as admin).

I had to manually set the the registry key here:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager

Start = 2

**Comment by benhillis** [comment] 2018-07-11 17:24
Closing out since issue is resolved.

**Closed by benhillis** 2018-07-11 17:24 UTC
Labels: workaround-available

**Comment by benhillis** [comment] 2018-08-28 15:34
Looks like the distribution name got changed again. I'll follow up with the Kali dev that owns the package.

**Comment by 31i73-73aM** [comment] 2018-08-28 23:26
I tried to start Kali Linux on my Windows PC and here is the problem:

Installation, it may take a few minutes ...
WslRegisterDistribution Failed with Error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Another solution to overcome this problem that worked on my pc:

1- Go to C:\Program Files\WindowsApps\KaliLinux_1.1.4.0_x64 __ *
2- Click kali.exe to launch it
3- In the open console type: apt-get update
                                                       apt-get dist-upgrade
                                                       apt-get upgrade
                                                       apt-get install kali-linux-all
                                                  or
                                                       apt-get install kali-linux-full
4- Type exit
5- click on the magnifying glass search kali then launch it.
6- kali starts normally.

The problem is now solved

See You

**Comment by firewave** [comment] 2018-08-30 07:51
@31i73-73aM I have no idea how that can even work as the error occurs when you try to run kali.exe

@benhillis There was a 1.1.5 update today which probably fixed the problem but broke it again for me. As none of the suggested workaround worked for me it took me hours to get this working again and probably will again now. There really need to be some proper safe guards for this...

**Comment by Kesims** [comment] 2018-09-21 16:30
hi, just run microsoft powershell as administrator adn type in: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

Thats all...

**Comment by nnuemad** [comment] 2018-12-28 09:37
need WSL on  in windows and all work.

**Comment by Raymar242** [comment] 2019-02-03 04:34
> 
> 
> Windows 10.0.16299.334 Pro x64 en-us (current public release build with current cumulative update KB4089848 at time of issue).
> Kali Linux installed through the Store on original release date, no problem observed (but not used much).
> Other distributions (Ubuntu and Debian) working fine.
> Today Kali Linux got updated through the Store, to version 1.1.2.0 released on 2/22/2018.
> 
> After update, launching the Kali Linux instance shows the following:
> Installing, this may take a few minutes...
> WslRegisterDistribution failed with error: 0x80070057
> Error: 0x80070057 The parameter is incorrect.
> 
> ![kalifail](https://user-images.githubusercontent.com/25664275/37938406-f3d27000-315d-11e8-9840-a5ad7ab50dcb.png)
> 
> Uninstalling and reinstalling Kali Linux package works.

tu problema es no haber iniciado powershell como administrador con esto solucionas el problema

**Comment by m-shahbaz-kharal** [comment] 2020-10-09 06:15
just use this command to set your WSL version to 1
wsl --set-default-version 1
then type kali, it'll install fine, then you can migrate to WSL version 2 using this command
wsl --set-default-version 2

**Comment by juniormayhe** [comment] 2021-12-12 15:23
> just use this command to set your WSL version to 1
> wsl --set-default-version 1
> then type kali, it'll install fine, then you can migrate to WSL version 2 using this command
> wsl --set-default-version 2

OMG 😲, thanks for this. After so many restarts, preparing and resetting linuxs apps installed by Microsoft Store, and several dism and wsl install commands you find one useful to make kali Linux run under Linux subsystem. This should be in some official documentation.

**Comment by Ssri7774** [comment] 2022-04-23 11:39
> the updates version of the kali app uses a different distribution identifier than the previous version. This is causing WSL to think that the app is not installed, and when the install is attempted it fails becaus

You can backup your wsl distro using the below command from Powershell

wsl --export kali-rolling kali-rolling.tar.gz

**Comment by aditya-digitalai** [comment] 2022-08-30 06:36
I am facing this issue.
Tried uninstalling WSL and installing it again.
Gives the same error again and again 

"Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070003
Error: 0x80070003 The system cannot find the path specified.

Press any key to continue..."

[
![Uploading Screenshot (135).png…]()
](url)

**Comment by Ssri7774** [comment] 2022-08-30 07:34
@aditya-digitalai 

set the following registry key value to 1:
HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel\obcaseinsensitive

Ref: https://github.com/microsoft/WSL/issues/6363

**Comment by aditya-digitalai** [comment] 2022-08-30 09:01
Tried setting the value in registry
And there is no file .wslconfig present in %USERPROFILE%.

**Comment by robinduerhager** [comment] 2022-11-14 23:41
> just use this command to set your WSL version to 1 wsl --set-default-version 1 then type kali, it'll install fine, then you can migrate to WSL version 2 using this command wsl --set-default-version 2

This will install kali with WSL 1. The `wsl --set-default-version 2` won't upgrade the WSL 1 Kali Terminal to WSL 2 (open up a Powershell instance with `wsl -l -v`). For upgrading you'd have to use `wsl --set-version Debian 2` for example. When i try to use this command, i again get the `The system cannot find the path specified.` error though.

**Comment by waelssi** [comment] 2023-10-27 15:56
> **UPDATE 27/10/2023**

**Solution for all WSL errors codes**
**1.** Press ‘Win + R’ keys on the keyboard together to open the Run dialog box and type the following into the run box: REGEDIT
Navigate to the following registry key:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager
On the right pane, locate Start and set the Value Data to 2.
> **Exit REGEDIT, and Reboot the machine.**

**2.** **Install WSL from MS Store**

![image](https://github.com/microsoft/WSL/assets/149183495/65a9d9e9-3577-4361-a353-27af5d23cfb0)

**3.** **Run PowerShell and type** 

PS C:\Users\xxxx> **wsl.exe --list --online**
![image](https://github.com/microsoft/WSL/assets/149183495/11747720-d54b-434d-a2d0-1d747a271112)

**Choose Kali-Linux**
PS C:\Users\xxxx> **wsl.exe --install kali-linux**
Then kali will install without any problem .. THE MAGIC WORKS
> **Type youre username and password**

![image](https://github.com/microsoft/WSL/assets/149183495/315248d8-1337-4537-a1c6-68d06be8af41)

**Installation successful! WITH NO ERROR.. ENJOY ;)** 😉

![image](https://github.com/microsoft/WSL/assets/149183495/178c680b-d8a7-4f23-8f66-9f21cab54967)

**Comment by devfemibadmus** [comment] 2024-03-09 22:03
> **Choose Kali-Linux** PS C:\Users\xxxx> **wsl.exe --install kali-linux** Then kali will install without any problem .. THE MAGIC WORKS

![image](https://github.com/microsoft/WSL/assets/84607331/62809fce-0578-435f-893f-cd88dc535eef)
