### ISSUE TITLE
When I use command 'wsl' in powershell, there is no respond.

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [microsoft/WSL#9827] opened 2023-03-22 09:55 UTC
### Windows Version

Microsoft Windows [Vision 10.0.25314.1010]

### WSL Version

1.1.3.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Jan 27 02:56:13 UTC 2023

### Distro Version

Ubuntu 1804

### Repro Steps

PS C:\Users\25122> wsl

### Expected Behavior

when I use command 'wsl', I expect to see :
![image](https://user-images.githubusercontent.com/84905965/226865840-1860d110-6c01-4db0-878a-09e38fdd2ddf.png)

### Actual Behavior

However nothing happened.
But if I open cmd and type command 'wsl', It can run smoothly. However if I have opened my windows and worked for a while, wsl cann't be opened.

**Comment by chetanguptaa** [comment] 2023-03-22 11:33
try restarting it.
Run the command 'Get-Service LxssManager | Restart-Service'

**Comment by MatthewARM** [comment] 2023-03-22 11:39
Could be duplicate of #8696

**Comment by Ethan-Chen-plus** [comment] 2023-03-24 12:56
[WslLogs-2023-03-24_20-50-10.zip](https://github.com/microsoft/WSL/files/11062213/WslLogs-2023-03-24_20-50-10.zip)
However today I can open wsl without any error occur. I am wondering why?
![image](https://user-images.githubusercontent.com/84905965/227526960-10d97581-dc34-4023-9001-d50d31cfb98a.png)

**Closed** 2024-03-28 12:01 UTC
