### ISSUE TITLE
automatically switches the input method when open wsl terminal on win11 

### ISSUE THREAD

**Issue by yuchiXiong** [microsoft/WSL#7511] opened 2021-10-09 07:17 UTC
### Windows Build Number

Microsoft Windows [版本 10.0.22000.194]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.60.1

### Distro Version

Ubuntu 20.04

### Repro Steps

use `win` + `r` then input `wsl`.

At this time, WSL terminal will be opened, but at the same time, the system starts to switch the input method continuously, and I cannot use WSL terminal normally due to the out-of-focus caused by the switch of input and transmission.

This is to demonstrate: https://www.youtube.com/watch?v=4QulGOXSiCQ

### Expected Behavior

Open the terminal and input method shouldn't be switched.

### Actual Behavior

Open the terminal, while the input method has been switched

**Comment by yuchiXiong** [comment] 2021-10-13 14:54
> I'm guessing this is a TSF (text service framework) bug. :P
> 
> As a workaround (perhaps), I suggest using windows terminal instead. XD

Thank you for reply and suggestions, but the problem is still not solved after try to use Windows Terminal :-(.

**Comment by finnonly** [comment] 2021-11-15 06:08
I am sure that this happens when the mstsc.exe process is started.
It also appears when I open docker, because the mstsc.exe process is also started.

**Comment by yuchiXiong** [comment] 2021-11-15 06:23
> I am sure that this happens when the mstsc.exe process is started. It also appears when I open docker, because the mstsc.exe process is also started.

I can't use Win11 + WSL for work and study because of this problem. Now I have returned to Win10 :-(

**Comment by jasselin** [comment] 2021-11-17 21:36
Upgrading WSL through the Microsoft Store seems to have fixed it for me. Have you tried it?

**Comment by Solybum** [comment] 2021-12-20 07:59
I haven't noticed my IME being switched (as in can't confirm nor deny) but I do sometimes experience my open windows losing focus repeatedly.

> I am sure that this happens when the mstsc.exe process is started. It also appears when I open docker, because the mstsc.exe process is also started.

This is definitely on the right track, I was able to track down this behaviour to wslhost.exe starting mstcs.exe over and over, with each instance of mstsc terminating right as it is started.

Force closing wslhost.exe stops the behaviour, in my computer there are 4 wslhost instances, 3 of which have a child mstsc process, if I close the one doing this, soon after one of the others does the same thing until I closed all 3 that had an mstsc process.

I can't reproduce the issue, it seems to happen randomly for me.

**Comment by thgossler** [comment] 2021-12-29 20:40
I have the same issue here.

Upgraded to Windows 11 from Windows 10 Enterprise (latest), everything standard configuration, latest WSLg Preview is installed via "wsl --update". 

Whenever WSL is starting (Ubuntu, freshly installed), one of the 3 wslhost processes is trying to start mstsc.exe over and over again (which seems to be crashing every time), and this leads to constantly switching apps and window focus between mstsc and the other active window, e.g. Windows Terminal, cmd, etc.

Killing the wslhost processes immediately stops the behavior, i.e. no more mstsc instances are started and the window "flickering" stops.

This seems to make WSL completely unusable. But, uninstalling "Windows Subsystem for Linux WSLg Preview" under "Apps and Features" mitigates the issue. Doesn't allow easy use of Linux GUI apps anymore, but at least WSL command line is usable again.

I hope Microsoft is fixing this soon in WSLg.

Linux GUI apps can still be used with limitations (no wayland, no GPU, no sound) by running an X server app on Windows (like x410) and configuring the DISPLAY environment variable correctly to the Windows host IP address and display 0 like

export DISPLAY="$HOST_IP_ADDRESS:0.0"

**Comment by thgossler** [comment] 2021-12-29 20:55
According to this thread 

https://issueexplorer.com/issue/microsoft/wslg/443

the problem is fixed in the latest pre-release version (1.0.28+) of WSLg which can be downloaded as MSI from 

https://github.com/microsoft/wslg/releases 

and installed over the currently released version 1.0.26.

**Comment by Fasand** [comment] 2022-01-27 13:36
Thanks @thgossler, disabling `guiApplications` worked for me; I didn't even realize they were on by default.
Just as a note: this behaviour was happening to me only when I took a screenshot with the ClipClip tool, or I manually killed the mstsc.exe process. I have no idea why but I've sent a ticket to their developer team. One way I was able to live with it for so long was to lock the computer, wait a few seconds and then log back in, which seemed to stop this respawning frenzy.

**Comment by Tumb1eweed** [comment] 2022-05-31 11:16
Met the problem too, open wsl2 and using ubuntu would automatically switch input method continuously, I can reappear this BUG very easily.

**Comment by dulfer** [comment] 2022-06-02 09:01
I have been struggling with this problem for more than a year now.
In the background mstsc.exe is being started and stopped/crashed, which has a severe impact on system performance as well. I experienced loss of keystrokes and overall slowdown of the system.

![procexp64_fnpyx9DkL7](https://user-images.githubusercontent.com/30404904/171592349-693b2b08-21d3-4ec0-a496-b93030e8e6b3.gif)

Creating .wslconfig in my profile directory and disabling guiApplications fixed it for me.
```
# %.wslconfig
[wsl2]
guiApplications=false
```
https://docs.microsoft.com/en-us/windows/wsl/wsl-config
I assume this can also be disabled on a per distribution/image basis.

**Comment by thgossler** [comment] 2022-06-04 19:03
Any news here? The problem is still happening for me, even after uninstalling WSL completely and reinstalling it from the Microsoft Store.

If somebody needs to see the problem happening, I can reproduce it reliably and would be willing to join a call with screen sharing.

**Comment by Tumb1eweed** [comment] 2022-06-06 09:22
> ### Windows Build Number
> Microsoft Windows [版本 10.0.22000.194]
> 
> ### WSL Version
> * [x]  WSL 2
> * [ ]  WSL 1
> 
> ### Kernel Version
> 5.10.60.1
> 
> ### Distro Version
> Ubuntu 20.04
> 
> ### Other Software
> _No response_
> 
> ### Repro Steps
> use `win` + `r` then input `wsl`.
> 
> At this time, WSL terminal will be opened, but at the same time, the system starts to switch the input method continuously, and I cannot use WSL terminal normally due to the out-of-focus caused by the switch of input and transmission.
> 
> This is to demonstrate: https://www.youtube.com/watch?v=4QulGOXSiCQ
> 
> ### Expected Behavior
> Open the terminal and input method shouldn't be switched.
> 
> ### Actual Behavior
> Open the terminal, while the input method has been switched
> 
> ### Diagnostic Logs
> _No response_

not only 20.04, 18.04/22.04 can produce this BUG too.

**Closed** 2024-02-01 12:10 UTC
