### ISSUE TITLE
You are missing the following 32 bit libraries, libc.so.6

### ISSUE THREAD

**Issue by GithubAccount453** [Microsoft/WSL#1644] opened 2017-01-30 07:28 UTC
Hi I am trying to get steam working in BashOnWindows and when running the application I get the error "You are missing the following 32-bit libraries, and Steam may not run: libc.so.6" I have tried updating and reinstalling the application but so far it continues to have the error.

**Comment by aseering** [comment] 2017-01-30 07:31
Hi @GithubAccount453 , thanks for posting!  WSL does not currently support graphical applications, audio, or 32-bit libraries or applications (it's 64-bit only).  So you're unfortunately going to have a hard time getting Steam to work :-)  If this is something that you care about, I'd suggest posting about it (or upvoting it, if it's already there?) on the [UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo).

**Comment by therealkenc** [comment] 2017-01-30 17:59
User voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel) FWIW (not that it matters in the context). Very bizarre the "we don't support a 32-bit launcher because some of our games are 32-bit" non-sequitur debate over in steam-land.

**Comment by tara-raj** [comment] 2018-08-21 20:06
Closing as duplicate of Issue #2468

**Closed by tara-raj** 2018-08-21 20:06 UTC
Labels: feature
