### ISSUE TITLE
/etc/resolv.conf is wrong when using VPN

### ISSUE THREAD

**Issue by ayanamist** [Microsoft/WSL#1986] opened 2017-04-23 03:31 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Using a WiFi to connect to internet, then use a VPN (like AnyConnect) to dial into company private net.
Then use `nslookup` to see effective DNS server:
![image](https://cloud.githubusercontent.com/assets/406779/25310489/ff4f2c48-2817-11e7-9767-6131aaf7f158.png)
However, `/etc/resolv.conf` shows that this dns server is not the first one.
![image](https://cloud.githubusercontent.com/assets/406779/25310492/0fd35c4c-2818-11e7-9adb-f463af74e8be.png)
So some queries which only 10.20.0.98 can answer is failed.

* What's wrong / what should be happening instead:
WSL use the same dns order like windows

**Comment by legigor** [comment] 2017-04-25 11:01
Same here #1881

**Comment by sunilmut** [comment] 2017-07-25 18:11
If you are connected to a VPN and lose connectivity within bash, please try the workaround posted [here](https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#bash-loses-network-connectivity-once-connected-to-a-vpn). It should work for Creators Update and above. Post Fall Creators Update, we will be looking at a better support for other VPN solutions.

Thanks to @bradley101, who first pointed out the workaround. Also, marking this duplicate of #1350

**Closed** 2017-11-10 17:45 UTC
Labels: duplicate, workaround-available
