### ISSUE TITLE
Bash freezes when clicked

### ISSUE THREAD

**Issue by brnelsons** [Microsoft/WSL#1223] opened 2016-10-18 19:52 UTC
- While bash is running a command and the console window is clicked the output of the command stops and requires a ctrl+c to continue command output.
- Bash should continue outputting and running a command regardless of something being selected or not.
- Bash ~expects~ me to be attempting to copy text from the console when in fact I am giving the console window focus.
- os build: 14393.321
- Run a command, give focus to something other than the console, click inside the console window.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment] 2016-10-18 20:19
This is how the Windows console works.  It may change over the next year or so, but this is by design (although for legacy reasons).

**Comment by brnelsons** [comment] 2016-10-18 21:00
Yes, i know this is currently how the Windows Console works. But, it is a pain to work with and it should be improved. gnome-terminal in Ubuntu and other Linux distros is the perfect example of how a console window should behave.

**Comment by fpqc** [comment] 2016-10-18 21:03
@brnelsons They are working on it.  The most detail we've gotten is in #111 if you want to read the posts of miniksa.

**Comment by brnelsons** [comment] 2016-10-18 21:13
An alternative is adding`export DISPLAY=:0;` to the ~/.bashrc
and running gnome-terminal from bash on windows.
seems to work well. havent done much testing though...

**Comment by fpqc** [comment] 2016-10-18 21:16
@brnelsons In the mean time, I suggest using wsltty.

**Comment by brnelsons** [comment] 2016-10-18 21:30
@fpqc I can currently use mintty through Git Bash terminal.

**Comment by fpqc** [comment] 2016-10-18 21:37
Then all you need is the wslbridge by @rprichard 

Compile and install in your cygwin environment.

**Comment by zadjii-msft** [comment] 2016-10-18 22:24
Yes. As @fpqc has said, this is the expected behavior, which is legacy from the DOS days. And yes, making it optional is definitely already on the feature backlog :)

**Comment by rprichard** [comment] 2016-10-19 00:42
FWIW: [winpty](https://github.com/rprichard/winpty) relies on this freezing behavior to atomically read the console screen buffer.  It'd be great if Windows left in some way for winpty to continue working as-is.  (Or, maybe, provide a proper public "server" API for consoles.  The PowerShell OpenSSH project clearly needs such an API, too.)

winpty detects new lines by placing a vertical "marker" into one of the columns of the screen buffer, in the history/scrollback portion that isn't visible.  Once the console window reaches the end of the buffer, each new line scrolls the marker up one line, so winpty can count the new lines by measuring how far the marker has moved upwards.  winpty really needs the console output frozen while it's doing this work, though.  It needs to:

- Get the window, buffer, and cursor coordinates.
- Search for the old marker, to determine how many lines may have changed.  It does this by reading the entire marker column.
- Read in all the lines that are visible or were visible during the last poll.
- Write down a new marker when the old one has moved upward too much.

winpty is depending on undocumented Windows behavior, so I don't think Windows is ordinarily *expected* to preserve the behavior, but AFAIK, there's no better way to do what winpty does, and a bunch of programs are now using winpty (e.g. Visual Studio Code, IntelliJ, Eclipse).

If the option were configurable like other recent console options, I suppose winpty could ensure old behavior by creating an `HKCU\Console\<path-to-winpty-agent.exe>` entry, maybe.

**Comment by fpqc** [comment] 2016-10-19 01:18
@rprichard If you read #111 It looks like they will be making a new console-reading API available in the future. I don't want to commit the MS people to anything, but that might be a better solution in the future.

**Comment by zadjii-msft** [comment] 2016-10-19 16:16
> winpty is depending on undocumented Windows behavior

Well I think you've really hit the nail on the head. There's a lot about the console that's undocumented behavior, but then someone somewhere depends on it, and then changing it, even if it's wrong, breaks someone somewhere.

That being said, we are working on a solution that we think everyone will be very happy with, but it's still a long while off. So be patient :)

**Comment by bitcrazed** [comment] 2018-05-22 22:51
Thanks for the discussion.

Closing this issue since:
1. This issue is actually an essential feature of the Windwos Console that is depended upon by MANY users. We tried disabling it once on internal builds and were nearly overrun by angry engineers with pitchforks and burning torches! We do, however, hear you and agree that it should be a configurable behavior, and so have added this ask to our internal feature tracking system and will consider implementing in a future build.
1. This is the WSL issues repo, but this is an issue in Console which has its own [Console GitHub Repo](https://github.com/Microsoft/console)
1. GitHub doesn't allow issues to be moved between repos, preserving posters' identity :(

If you have further asks/issues, please file new issues on our [Console GitHub Repo](https://github.com/Microsoft/console).

**Closed by bitcrazed** 2018-05-22 22:51 UTC
Labels: backlog, console, feature

**Comment by HBelusca** [comment] 2019-05-24 18:04
So can we also get the "Mark/Select" label in the terminal title when click for selecting is done?
