### ISSUE TITLE
nmap still does not work on WSL

### ISSUE THREAD

**Issue by sephethus** [microsoft/WSL#5160] opened 2020-04-30 14:29 UTC
As of two years since this was last reported and ignored as a problem this still does not work. 

Windows 10 1909, 18.363.778, Ubuntu WSL:

```
Starting Nmap 7.60 ( https://nmap.org ) at 2020-04-30 10:23 EDT
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
NSOCK ERROR [0.0530s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #1): Protocol not available (92)
NSOCK ERROR [0.0530s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #2): Protocol not available (92)
NSOCK ERROR [0.0530s] mksock_bind_device(): Setting of SO_BINDTODEVICE failed (IOD #3): Protocol not available (92)
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
socket_bindtodevice: Protocol not available
Problem binding to interface , errno: 92
```

**Comment by aress31** [comment] 2020-04-30 17:04
+1 some people's job rely heavily on the use of network scanners, particularly `nmap`, therefore if you want to win them over and have them ditch their VM to fully commit to `WSL` this issue should be treated as a high priority issue.

**Comment by Biswa96** [comment] 2020-04-30 17:15
> some people's job rely heavily on the use of network scanners

Them they should use the Windows version of nmap or use a real GNU/Linux distribution with its nmap package. Without relaying on any type of VM or compatibility layer.

**Comment by sirredbeard** [comment] 2020-04-30 20:45
This is a duplicate of at least #5083, #1349, #3859, #3521, #3440, #2039, #2548, #1349.

By knowingly opening a duplicate bug report you take time from developers working on new features. It does not help the developers ship it faster.

This is fixed in WSL 2 which is available on all Insiders channels. If you want to try it in a VM without upgrading your system, you can [follow this guide](https://boxofcables.dev/tag/miscellaneous/). If you are interested in using WSL 2 for security, you should watch [How we use WSL at Kali](https://www.youtube.com/watch?v=f8m6tKErjAI).

**Closed** 2020-05-18 19:21 UTC
Labels: duplicate

**Comment by dukman83** [comment] 2020-09-19 10:07
@sirredbeard 

> This is fixed in WSL 2 which is available on all Insiders channels.
 - incorrect. The problem is still present with WSL2 Ubuntu.

**Comment by denzuko** [comment] 2021-04-04 00:51
@sirredbeard your guide link has been taken down and only returns a 404 page.

for those coming from google, make sure you have gone though the steps to enable wsl then to upgrade from wsl 1 to wsl 2:
```
wsl --version 2
wsl --set-version default 2
```

**Comment by udoline** [comment] 2021-12-14 21:18
@denzuko your second command is false, right is

`wsl --set-version-default 2`

**Comment by colin-morrell** [comment] 2026-02-25 05:34
for posterity, because this was my top google result, the command is now

`wsl --set-default-version 2`
