### ISSUE TITLE
Python EOFError for 2nd Input on WSL Only

### ISSUE THREAD

**Issue by timethrow** [Microsoft/WSL#3924] opened 2019-03-19 19:51 UTC
**Please fill out the below information:**
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17763.379

* What you're doing and what's happening:  (Copy&paste the full set of _specific_ command-line steps necessary to reproduce the behavior, and their output. Include screen shots if that helps demonstrate the problem.)

* What's wrong / what should be happening instead:

I have a basic script that I am running in a WSL Terminal (Ubuntu 18.04) that gets 2 inputs from a user to create an email, essentially it get the message and then the server to use.

It prompts for the message first and allows the user to enter the input, this works fine. After that it then does a regex search for a servername in the message, if its not found it prompts for it, however each time it does it comes up with an EOFError and I can't find why.

```ServerTraceback (most recent call last):
File "/home/dev/bin/script", line 155, in <module>
create_report()
File "/home/dev/bin/script", line 98, in create_report
servername=get_servername()
File "/home/dev/bin/script", line 10, in get_servername
servername = raw_input("Server")
EOFError```

Oddly if I run the same script with python2 -i /home/dev/bin/script it works, but from the WSL terminal it comes up with the EOFError.

Any help would be really appreciated, I am new to this and a bit lost as to whats happening.

This is the 2nd input, the one that produces the EOFError

```def get_servername():
servername = raw_input("Server")
return servername```

From an strace I also see this;

```26004 read(3, "log_info(\"Parsing report for IPs"..., 512) = 512
26004 read(3, " break\nif not servername:\n    lo"..., 512) = 512
26004 write(2, "    ", 4)               = 4
26004 write(2, "servername = raw_input(\"Server N"..., 40) = 40
26004 close(3)                          = 0
26004 write(2, "EOFError", 8)           = 8
26004 write(2, "\n", 1)                 = 1
26004 rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc31ec3ef20}, {sa_handler=0x7fc31f76c130, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fc31ec3ef20}, 8) = 0
26004 exit_group(1)                     = ?
26004 +++ exited with 1 +++```

The script works fine in Interactive mode, and also when run on a Linux machine directly with no changes to the script.

I thought it may be an issue with stdin, however the first input works as expected, so this does not seem to be the case and as it works elsewhere, I am reasonably confident the script itself is working as expected.

Any help greatly appreciated.

**Comment by therealkenc** [comment] 2019-03-19 21:30
No concrete guesses with what's provided above. Repro steps like a test case extracted from the actual script would be a starting point. Or someone might be able to guess from complete strace logs from WSL vs Linux. 

Hand waving, it looks like the problem might be input driven (possibly due to an earlier fail) as opposed to a syscall diverge at the point of the `SIGINT`. Or there might be other unknown external differences in your WSL vs. Real Linux setup (it is hard to get actual equivalence sometimes). Anyway, those buffered `read()`s succeeded just fine, but it looks like the script didn't like what it saw and s--- the bed.

**Comment by timethrow** [comment] 2019-03-19 22:24
Thanks for taking a look.

The script is one I have at work, currently at home on a completely separate device, and have managed to reproduce it here using a quick script I made. Doing this makes me wonder if its something to do with a Multi Line input and the CTRL + D return? 

I have been looking at it for the past few days before posting here as I wanted to rule out as much as possible, but just thought of this, but am at a real loose end now, and to be honest a bit out of my depth, I need to read up more on the strace stuff as most of that looks a little beyond me at the moment.

Here is the script I used for this test;

```
#!/usr/bin/env python

input1=raw_input("Gimme something 1")

print("Enter/Paste your content. Ctrl-D to save it.")
contents = []
while True:
    try:
        line = raw_input("")
    except EOFError:
        break
    contents.append(line)

input2=raw_input("Gimme more. Input2: ")
```

This is the error I see (the input may vary between the gists);
```
Gimme something 1aaa
Enter/Paste your content. Ctrl-D to save it.
aGimme more. Input2: Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    input2=raw_input("Gimme more. Input2: ")
EOFError
```

Here is the full strace of that script. from WSL;
https://gist.github.com/timethrow/3dd18f0b25d78cc8e17fbab2b167058a

and here is a full strace of the same script from a Linux VM running the same Ubuntu version.
https://gist.github.com/timethrow/329022d316975c569089ba471a338a36

If anyone needs anything further please do let me know.

Thanks

**Comment by therealkenc** [comment] 2019-03-19 23:48
Awesome. Very much appreciate the follow-up.

**Comment by therealkenc** [comment] 2019-03-20 00:32
Alright; this is almost certainly variation #3421, which is on the chirping cricket pile. Apologies I didn't connect them right away (I must be getting slow).

Also thanks for the data-point on it being possibly a distant regression. Which from your standpoint is academic, but it is mildly interesting to know.

Going to dupe this, which in no way reflects badly on your submission. The other just has a tight minimal repro without inviting Python to the party. But I'll hold yours open for a bit in case someone more familiar with Python might suggest a work-around for you (I don't really 'do' Python). You might also try a Python forum to see if they can suggest a different approach. That's what I'd do. Or maybe run with something inert as your terminator like Ctrl-X if that is an option.

**Comment by therealkenc** [comment] 2019-03-20 21:24
Suggested work around over in #3421. Closing this out. We can re-open / re-visit in the unlikely event there is something subtly different about the Python repro, but that seems unlikely.

**Closed by therealkenc** 2019-03-20 21:24 UTC
Labels: duplicate
