### ISSUE TITLE
Obscure launching method

### ISSUE THREAD

**Issue by mintty** [Microsoft/WSL#2348] opened 2017-07-17 19:27 UTC
Users need to know how WSL is actually invoked, but this is artificially obscured (no target info for Start Menu icons, weird installation redirection).
There needs to be transparent information about the WSL installation that exist on the system (or for the user), and how to invoke each of them, and which icon to use for it.

**Comment by fjsuarez** [comment] 2017-07-17 21:46
The target for the icon on my Start Menu shows `C:\Windows\System32\bash.exe ~`
I'm not sure if that is what you are talking about.

**Comment by benhillis** [comment] 2017-07-17 22:32
@mintty - I believe he's talking about the tiles that get installed when you install a WSL distro from the store.

**Comment by shevegen** [comment] 2017-07-18 01:29
Actually I did not even know where bash.exe was situated - now I know thanks to fjsuarez. :)

I think that mintty has one additional point; when not only ubuntu is available but, say, opensuse, and perhaps even more, then people may be a bit confused as to what is installed where. E .g. what is linked at /mnt/c - and what about other distributions, what do they install and so forth. Good documentation would be very helpful here but I am sure that once features/functionality work as designed, documentation will also be provided.

**Comment by mintty** [comment] 2017-07-18 06:22
`C:\Windows\System32\bash.exe` is the launcher for the preliminary version.
With the current update, they changed installation. WSL is now [available from the Windows Store](https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/), and even without another of the planned distros installed, it is very obscure where to find it:
For the current version, the launcher is `%PROGRAMFILES%/WindowsApps/CanonicalGroupLimited.Ubu
ntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc/ubuntu.exe` and the icon is `%PROGRAMFILES%/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc/images/icon.ico`.
This cryptic name does not look version-compatible, and what will it be for other distros?

**Comment by mintty** [comment] 2017-07-18 06:41
Actually, the installed distros are listed per user in the registry under `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]`, with their distro folders (`BasePath`). However, the names of the launcher and icon are not registered there.

**Comment by factormystic** [comment] 2017-07-18 14:27
Can't you just use `c:\windows\system32\wsl.exe`/

**Comment by factormystic** [comment] 2017-07-18 14:27
Can't you just use `c:\windows\system32\wsl.exe`?

**Comment by leojbgiusti** [comment] 2017-07-18 14:50
I read somewhere, probably a comment on the blog post announcing the new store versions that bash.exe will continue to work launching any of the store distros. Also the long cryptic paths are a result of the store.

**Comment by mintty** [comment] 2017-07-18 15:01
Maybe. But if there are (in future) multiple distros installed, how would I tell bash.exe which to use?
And how do I identify the respective icon for each one?

**Comment by leojbgiusti** [comment] 2017-07-18 15:08
Use the new wslconfig command. Scott Hanselman has a blog post about it all. https://www.hanselman.com/blog/UbuntuNowInTheWindowsStoreUpdatesToLinuxOnWindows10AndImportantTips.aspx

**Comment by fpqc** [comment] 2017-07-18 15:46
@mintty Here:

```
C:\Windows\System32>where ubuntu
C:\Users\fpqc\AppData\Local\Microsoft\WindowsApps\ubuntu.exe

C:\Windows\System32>echo %PATH%
C:\Program Files\ImageMagick-7.0.5-Q16;C:\Program Files (x86)\Python35-32\Scripts\;C:\Program Files (x86)\Python35-32\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\fpqc\AppData\Local\Microsoft\WindowsApps;C:\adb;C:\Program Files (x86)\vim\vim80;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSH-Win64;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\fpqc\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code Insiders\bin;C:\Users\fpqc\.babun;C:\Users\fpqc\AppData\Local\Microsoft\WindowsApps;C:\Users\fpqc\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;
```

**Comment by mintty** [comment] 2017-07-18 15:50
Ah, that looks like giving almost the missing information, thanks. I'll try later.
Still missing though, how to find respective icons.

**Comment by mintty** [comment] 2017-07-18 15:54
@fpqc: `where ubuntu` does not help about multiple distros...

**Comment by fpqc** [comment] 2017-07-18 15:56
@benhillis Do you have any idea what kind of mysterious symlink (or something else) that is in the `%localappdata%\Microsoft\WindowsApps` directory?  I tried poking it and prodding it and opening it up in a hex editor and I got nothing out of it.

**Comment by benhillis** [comment] 2017-07-18 16:04
@fpqc - it's an execution alias: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-extensions

**Comment by fpqc** [comment] 2017-07-18 16:04
Ah thanks!

**Comment by benhillis** [comment] 2017-07-18 16:07
@fpqc - they are implemented as custom reparse points. https://msdn.microsoft.com/en-us/library/windows/desktop/aa365503(v=vs.85).aspx

**Comment by fpqc** [comment] 2017-07-18 16:09
Super cool! Are there any plans to extend dir and mklink to be able to use them, because right now they display no information with the usual tools.

**Comment by benhillis** [comment] 2017-07-18 16:12
@fpqc - I'm not sure about future plans, since that's not an area my team owns.

**Comment by fpqc** [comment] 2017-07-18 16:12
@mintty Yes it does. That directory `localappdata%\Microsoft\WindowsApps` is the location of the execution alias that gets picked up in the system PATH.  All of the distros installed should be in that directory with their own execution aliases.

**Comment by fpqc** [comment] 2017-07-18 16:13
@benhillis Alright maybe I'll ask Rich on Twitter and he'll ping in the right person.

**Comment by benhillis** [comment] 2017-07-18 16:16
@fpqc - Yeah Rich (@bitcrazed) would definitely know the right people to get in touch with about execution aliases.  The design is pretty new and I'm not sure if it's fully realized yet.

**Comment by fpqc** [comment] 2017-07-18 16:21
Yeah, it's newer than I expected, like brand new 16226.

Here's their blogpost https://blogs.windows.com/buildingapps/2017/07/05/command-line-activation-universal-windows-apps/

**Comment by zadjii-msft** [comment] 2017-07-18 17:45
I'll just hop on before Rich comes down to my office and pings me manually.

Yes, `%localappdata%\Microsoft\WindowsApps` is where the execution aliases live. Careful though - distros aren't the only ones to use those, so you have to have a way to find only the distros. Note that there is another copy of the execution alias under the directory corresponding to the app in that folder - eg `%localappdata%\Microsoft\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc`

Yes, the distros are registered under the Lxss key. Beware that changing any of these values could corrupt that app's install, but you may want to look at the PackageFamilyName key.

I leave it as an exercise for the reader to figure out how to enumerate all of the execution aliases that correspond to distros :)

**Comment by mintty** [comment] 2017-07-18 18:28
@zadjii-msft
> ... figure out how to enumerate all of the execution aliases that correspond to distros :)

Thanks, with wslconfig or the Lxss key there are two fairly easy ways. But I'd appreciate if you can tell us how to find the proper icon for each respective distro.

**Comment by fpqc** [comment] 2017-07-18 18:31
@zadjii-msft No worries, I think @mintty is trying to have the wsltty installer pick up the distros and launchy mintty and wslbridge for each distro (which is why he cares about the icons).

**Comment by zadjii-msft** [comment] 2017-07-18 18:37
@mintty I'm afraid I don't know how to find the icons. There was a console PR a while back that mentioned "Make the console host try using the window title as a search path for the icon." but I don't know how that works exactly, or if it's relevant in this case.

I'd look at `C:\Program Files\WindowsApps`, but you'd need admin privileges to poke around in there so I'm not sure it'd be that useful.

Sorry I can't be more help.

**Comment by therealkenc** [comment] 2017-07-18 19:20
> but I don't know how that works exactly, or if it's relevant in this case.

https://stackoverflow.com/questions/37417757/extract-icon-from-uwp-application

**Comment by mintty** [comment] 2017-07-18 20:36
Thanks, that sounds like a theoretical solution; however, I don't feel like writing an application and spending hours or days on reverse engineering its problems for such a simple requirement. There should be an MS command-line tool (or maybe 3rd party tool) to simply extract the icon from the exe.

**Comment by MikeGitb** [comment] 2017-07-21 19:09
@zadjii-msft: not sure if the PR you mentioned is related, but one thing I found a bit irritating is that if I start bash from the explorer  address bar, the console title doesn't pick up the Ubuntu Icon. 
This is only a cosmetic issue, but if it would be fixed, it would help to quickly distinguish bash and normal console windows. (I'm running CU btw.)

**Comment by zadjii-msft** [comment] 2017-07-21 19:58
@MikeGitb That fix is on it's way up and out to Insider's already, it is indeed the PR I was referring to.

**Comment by MikeGitb** [comment] 2017-07-21 20:20
Thanks for the info! Can't wait for fall CU (especially due to serial support). 

Just hope the windows side doesn't get screwed up ;)

**Comment by bitcrazed** [comment] 2017-07-21 22:43
@fpqc - you could also ask me here too 😜 

ExecutionAliases are required because aps cannot be launched directly. There are several reasons for this, including the fact that apps can (theoretically) be moved from one location to another, and we don't want you to have to go and hunt down where the app is today.

While Execution Aliases are custom reparse points today, we are having discussions about some improvements we could make to them, as I type. Of course, we'd like to make any changes without affecting users' experience.

We're also considering a change that'll allow you to enumerate available installed distro's, so that you and/or tooling can launch specific distro(s).

Bear with us.

**Comment by mintty** [comment] 2017-07-22 15:01
> ... apps can (theoretically) be moved from one location to another ...

Would that be reflected in the registry, so that from HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss, information about the WSL distros can reliably be derived?
Couldn't the icon path be stored there as well, so we do not have to guess its location to be at %PROGRAMFILES%\WindowsApps\[PackageFamilyName]\images\icon.ico?

**Comment by benhillis** [comment] 2017-07-22 15:19
@mintty - App registration predates WSL so that information is already stored elsewhere.

**Comment by mintty** [comment] 2017-07-22 15:26
@benhillis, not sure what you mean. I could interpret your response so that the registry mechanism is outdated from WSL point of view, but I don't think you mean that; also, registry entries were created during Ubuntu installation. Is there a better way to retrieve detailed information about installed WSL packages than to look up that registry key?

**Comment by benhillis** [comment] 2017-07-22 15:28
No I mean that store app install information is already stored elsewhere. That component is responsible for creating the tile with the icon file.

**Comment by mintty** [comment] 2017-07-22 15:33
> app install information is already stored elsewhere

Ok, so _where_ is it stored, please?

**Comment by therealkenc** [comment] 2017-07-23 00:58
> Ok, so where is it stored, please?

The registry information isn't outdated. You still have to walk the `CurrentVersion\Lxss` registry to get the `DefaultDistribution` UID, and all the UIDs if say you want to put a shortcut on the desktop for all the distributions with their icons.

From a practical standpoint the icons live in `%PROGRAMFILES%/WindowsApps/magic_string_you_parsed_out_of_base_path\images\icon.ico`, as you already discovered. But like Rich pointed out, the location can theoretically move. The Store App assets are separate from the application data (which in WSL's case is the souper seekrit lxfs root filesystem).

Yes they could just stick the icon path in the Lxss registry. As a practical matter, maybe they should (shrug). But moving the app assets is an operation independent of WSL. It's a function of the Store infrastructure.

To find the path "reliably" you have to key off the PackageFamilyName in the registry like Mike alluded. You can query the installation path with powershell, or with the UWP APIs.

At least for SUSE and Ubuntu `images\icon.ico` appears to be a reliable fixed sub-path to the icon. But If one wants to quibble, you need to dig into the app manifest because what constitutes an 'icon' these days isn't as straightforward as it used to be.

Anyway don't look at me. If they do some enumeration API that wraps this all up in a pretty bow so much the better.

```
PS C:\> Get-AppxPackage | where PackageFullName -match CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc

Name              : CanonicalGroupLimited.UbuntuonWindows
Publisher         : CN=23596F84-C3EA-4CD8-A7DF-550DCE37BCD0
Architecture      : X64
ResourceId        :
Version           : 1604.2017.711.0
PackageFullName   : CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc
InstallLocation   : C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc
IsFramework       : False
PackageFamilyName : CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
PublisherId       : 79rhkp1fndgsc
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
IsPartiallyStaged : False
```

**Comment by therealkenc** [comment] 2017-07-23 05:42
> There should be an MS command-line tool (or maybe 3rd party tool) 

[EnumWSL](https://github.com/therealkenc/EnumWSL/releases).
```
LxUID: {12345678-1234-5678-0123-456789abcdef}
DistributionName: Legacy
LaunchPath: "C:\WINDOWS\system32\bash.exe"
IconPath: "C:\Users\ken\AppData\Local\lxss\bash.ico"
IsDefault: true

LxUID: {b405c97d-5ee3-4d1f-a23c-13d4b4a4c88d}
DistributionName: openSUSE-42
PackageFamilyName: 46932SUSE.openSUSELeap42.2_022rs5jcyhyac
LaunchPath: "C:\Users\ken\AppData\Local\Microsoft\WindowsApps\openSUSE-42.exe"
IconPath: "C:\Program Files\WindowsApps\46932SUSE.openSUSELeap42.2_1.0.3.0_x64__022rs5jcyhyac\images\icon.ico"
IsDefault: false

LxUID: {e23840cc-dc7b-451f-9b14-28300d1474b7}
DistributionName: Ubuntu
PackageFamilyName: CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
LaunchPath: "C:\Users\ken\AppData\Local\Microsoft\WindowsApps\Ubuntu.exe"
IconPath: "C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc\images\icon.ico"
IsDefault: false
```

**Comment by benhillis** [comment] 2017-07-24 15:33
@therealkenc - Even if the applications are moved folders in the app install directory are replaced by reparse points, so in theory the "old" paths will still work.

**Comment by mintty** [comment] 2017-07-25 15:01
@benhillis, is there an option, like in the Legacy distro, to start the WSL shell in a specific directory rather than the WSL home directory?

**Comment by benhillis** [comment] 2017-07-25 15:30
@mintty - That would be up to each individual distribution. They are in control of their launcher executable and what arguments it supports.

Once you have a distribution installed you can still use bash.exe / wsl.exe to launch it which support the ~ operator.  You simply have to set it to your user's default using the wslconfig.exe command line too.  Afterwards when you launch bash.exe or wsl.exe it will use whichever distro you specified.

**Comment by zadjii-msft** [comment] 2017-07-25 15:44
@mintty by default you should be able to, yes. For example, `ubuntu run bash` will launch ubuntu's bash in the current directory.

**Comment by mintty** [comment] 2017-07-25 19:13
@benhillis:
> You simply have to set it to your user's default using the wslconfig.exe command line too.

I would certainly prefer a solution without having to tamper with the default setting.
On the other hand, `ubuntu ~` does not work; how does `bash ~` delegate its ~ parameter to ubuntu? Especially as it cannot really know which default user is configured... Really mysterious.

@zadjii-msft:
> by default you should be able to, yes

If you mean "I should be", I agree. But it doesn't work. `ubuntu` starts in the default user's home directory. `ubuntu run ...` is a new surprise, it's not documented anywhere. How should anyone know how to configure WSL invocation in a generic manner?
@benhills, there should be a common approach to this issue. A well-defined interface to run a distribution (and not necessarily the default one) and start in either a selected (or current) or the home directory.

**Comment by zadjii-msft** [comment] 2017-07-25 19:15
@mintty 
```
migrie@MIGRIE-DESKTOP>ubuntu help
Launches or configures a linux distribution.

Usage:
    <no args>
      - Launches the distro's default behavior. By default, this launches your default shell.

    run <command line>
      - Run the given command line in that distro, using the default configuration.
      - Everything after `run ` is passed to the linux LaunchProcess call.

    config [setting [value]]
      - Configure certain settings for this distro.
      - Settings are any of the following (by default)
        - `--default-user <username>`: Set the default user for this distro to <username>

    clean
      - Uninstalls the distro. The appx remains on your machine. This can be
        useful for "factory resetting" your instance. This removes the linux
        filesystem from the disk, but not the app from your PC, so you don't
        need to redownload the entire tar.gz again.

    help
      - Print this usage message.

```

**Comment by sunilmut** [comment] 2017-07-25 19:49
@zadjii-msft - I agree that there should be some common way of dealing with this and hopefully not a very distro specific thing. Also, is there any way we can improve the usage text, specifically `Everything after run is passed to the linux LaunchProcess call.`? As an end user, what do I know about `LaunchProcess` or why should I care about it?

**Comment by mintty** [comment] 2017-07-26 09:26
@zadjii-msft, thanks for the info but it doesn't really help with the use case; who guarantees that each distro will have a `run` parameter, or even just a `help` parameter?

**Comment by therealkenc** [comment] 2017-07-26 12:01
That `<no args>` help line doesn't make sense. `ubuntu` launches Ubuntu and `opensuse-42` lauches SUSE. It doesn't launch your default shell.... It launches the shell you asked for.

Both executables spit out the exact same help, but differ in size by around 30k (ie they're different). Which means, I think, someone is cutting and pasting source code we haven't seen. If that's right and I'm not misinterpreting things, "boo".

>
```
migrie@MIGRIE-DESKTOP>ubuntu help
Launches or configures a linux distribution.

Usage:
    <no args>
      - Launches the distro's default behavior. By default, this launches your default shell.
```

**Comment by therealkenc** [comment] 2017-07-26 13:30
@mintty - it looks like the CLI parameters to `wsl.exe` are like this:
```
C:\WINDOWS\system32\wsl.exe {E23840CC-DC7B-451F-9B14-28300D1474B7} ~ 
```
So, best I can tell, `ubuntu.exe` is dead weight from wslbridge's standpoint. You don't have to go to:
```
%PROGRAMFILES%/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1604.2017.711.0_x64__79rhkp1fndgsc/ubuntu.exe
```
You don't need to destructively tamper with `wslconfig`. Forget you ever heard the words "execution alias". You just need the magic `LxUID` (or whatever you call it). Until someone explains otherwise, anyway.

**Comment by benhillis** [comment] 2017-07-26 15:38
@therealkenc - I'll defer to @zadjii-msft since he owns the distribution launcher code.

**Comment by zadjii-msft** [comment] 2017-07-26 16:32
@therealkenc they most certainly are different exe's. I don't know how exactly they differ from one another, but they do set up their initial user differently, so that's something.

@mintty There is no guarantee that every distro will have such a param, as the launcher is ultimately under their control.

I'd agree that `wsl <guid>` or `wsl {guid} ~` is probably a better way for what I know your use case to be. 

`ubuntu run <commandline>` is a nice invocation for other users to intuitively call a particular commandline for a particular distro (certainly more legible than `wsl.exe {E23840CC-DC7B-451F-9B14-28300D1474B7} echo foo`)

**Comment by rprichard** [comment] 2017-07-26 23:19
FWIW, it'd be nice if we had a precise description of how the command-line from `bash.exe`, `wsl.exe`, and `ubuntu.exe run` is eventually turned into a Linux argument vector.

Here's what I *think* is going on (as of 10.0.16232.1000):

| GetCommandLine | WSL execv arg vector |
|-----|-----|
| "bash.exe " + CmdLine | ["/bin/bash", "-c", "/bin/bash " + CmdLine] |
| "wsl.exe " + CmdLine | ["/bin/bash", "-c", CmdLine] |
| "ubuntu.exe run " + CmdLine | CmdLine is split into argc/argv for MSVCRT `[w]main()`, then joined with spaces for an argv of ["/bin/bash", "-c", " ".join(MSArgSplit(CmdLine))] |

The `ubuntu.exe run` case is the strangest one, because AFAICT it's the only one that involves ordinary Windows-style command line splitting (e.g. `CommandLineToArgvW`).  I don't think it actually uses `CommandLineToArgvW`, though -- it behaves more like MSVCRT's startup:

 * <code>ubuntu run echo "1&nbsp;&nbsp;&nbsp;2"</code> ==> echoes `1 2`
 * `ubuntu run A="B sh" -c 'echo A=$A'` ==> echoes `A=B`
 * `ubuntu run echo "a\\\\"c` ==> echoes `a\c`
 * `ubuntu run echo "a\\\\b"c` ==> echoes `a\\bc`
 * `ubuntu run echo 1""""""2` ==> echoes `12`
 * `ubuntu run echo "1""""""2"` ==> error: unexpected EOF looking for `"`.  This case demonstrates how `ubuntu run` uses MSVCRT arg splitting rather than `CommandLineToArgvW`.  `CommandLineToArgvW` turns `"1""""""2"` into [`1""2`], but MSVCRT turns it into [`1"""2`].

Is the `ubuntu.exe run` behavior intentional?

Currently, wslbridge invokes `bash.exe`.  I have a tentative change where it would invoke `wsl.exe` with a GUID.  wslbridge wraps arguments with single quotes to avoid shell interpretation.  The wslbridge Cygwin frontend passes an argument vector to its WSL backend, so it could use an arbitrary encoding.

**Comment by skylize** [comment] 2017-09-04 19:56
@shevegen 
> Good documentation would be very helpful here but I am sure that once features/functionality work as designed, documentation will also be provided.

😃What makes you so sure of that? Documentation is a completely different animal than designing features. (And docs are typically much easier to write well along the way, rather than waiting until massive changes to a code base are complete.)
 
Features can only work as designed. The tricky part is actually designing them as intended. 😃😃😃

**Comment by fpqc** [comment] 2017-09-05 02:55
@skylize things are likely already partially documented in private docs (that's how ubuntu and suse released as apps on the windows store).  The documentation, however, is for a non-public API.  Documentation will become available if/when the API becomes public, I assume.  I'm not sure that this particular API will be made public.  On the other hand, SuSe accidentally released without stripping debug symbols, so a lot of the API has already been reverse-engineered by @Rolisoft

**Comment by Biswa96** [comment] 2017-10-25 15:17
https://github.com/Microsoft/WSL/issues/2348#issuecomment-315969482
> This cryptic name does not look version-compatible, and what will it be for other distros?

@mintty I find some process to get that name without installing WSL.

Microsoft provided the distros appx files in this [article](https://msdn.microsoft.com/en-us/commandline/wsl/install-on-server). Here I download the Ubuntu (https://aka.ms/wsl-ubuntu-1604) and follow these steps:
1. Open the appx (or redirected to ZIP file) with 7ZIP, extract `resources.pri` file from it.
2. If Windows SDK is installed, open CMD, use this command to dump `resources.pri` file to .xml file::`makepri.exe" dump /if resources.pri /of resources.xml`. See more at [MakePri.exe command options](https://docs.microsoft.com/en-us/windows/uwp/globalizing/makepri-exe-command-options).
3. Open that dumped XML file in any text editor and see the first which reveals the distro name:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PriInfo>
	<ResourceMap name="CanonicalGroupLimited.UbuntuonWindows" version="1.0" primary="true">
		<Qualifiers>
```

* Here is the list (may be changed in future):
    - Ubuntu: "CanonicalGroupLimited.UbuntuonWindows"
    - OpenSUSE: "46932SUSE.openSUSELeap42.2"
    - SLES: "46932SUSE.SUSELinuxEnterpriseServer12SP2"
----
https://github.com/Microsoft/WSL/issues/2348#issuecomment-316169762
@therealkenc This XML file also reveal the icon paths.

**Comment by mintty** [comment] 2017-10-26 12:14
Thanks; actually the registry is a more reliable source (as referring to the actual system deployment).
Mintty 2.8.0 meanwhile retrieves this information so you can simply call it like `mintty --WSL=Ubuntu`.
The WSLtty 1.8.0 package also make use of this capability and provides launch icons, context menu entries etc. for all installed distributions.

**Comment by bitcrazed** [comment] 2017-10-27 01:45
> "There needs to be transparent information about the WSL installation that exist on the system (or for the user), and how to invoke each of them, and which icon to use for it."

I have an idea about how we can make this MUCH easier. Bear with ;)

**Comment by ljani** [comment] 2018-05-03 16:16
I wonder if I could (ab)use that same reparse point for adding aliases for traditional third-party apps? Currently the reparse point seems to contain the package family name and application id, but is there any way around to that?

For example I'd like to alias `%localappdata%\Microsoft\WindowsApps\ps.exe` to `C:\Program Files\PowerShell\6.0.2\pwsh.exe`.

I tried to dig this, but didn't get really far. It seems `ApiSetHost.AppExecutionAlias.dll` is responsible for reading the reparse point.

**Comment by ljani** [comment] 2018-05-03 16:34
@Biswa96 If you mean writing a separate wrapper program, that's what I'm doing now, but it's not perfect (obscure bug with the standard streams and `SIGINT`). I'd much prefer if the trampoline was not there, and the correct process was launched directly.

**Comment by benhillis** [comment] 2018-07-11 17:39
Discussion has run its course.  Also in recent insider builds a "-d, --distribution" flag was added to wsl.exe to specify a specific distribution to launch.

**Closed by benhillis** 2018-07-11 17:39 UTC
Labels: discussion, launcher
