### ISSUE TITLE
Connection refused when using WSL/Windows Unix Socket interop

### ISSUE THREAD

**Issue by PJB3005** [microsoft/WSL#8321] opened 2022-04-23 20:05 UTC
### Version

Microsoft Windows [Version 10.0.19043.1645]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1

### Distro Version

Ubuntu 20.04

### Repro Steps

Following [this blog post](https://devblogs.microsoft.com/commandline/windowswsl-interop-with-af_unix/)

* Make a directory on the Windows driver, put all the example sources in there.
* Compile on windows (`cl .\af_unix_win_server.cpp  Ws2_32.lib`) and on Linux (`gcc client.c -o client`)
* Run server on Windows
* Run client on Linux

### Expected Behavior

The socket connection to succeed and some test bytes to be transferred.

### Actual Behavior

Socket fails to connect with a "Connection refused" error

### Diagnostic Logs

I uploaded the logs via Feedback Hub but I didn't bother signing in, so I can't link to it. The titles should match though.

**Comment by craigloewen-msft** [comment] 2022-04-26 21:24
It looks like you're using a WSL 2 type distro. You can verify this by looking at `wsl -l -v`. AF_UNIX calls are not supported on WSL 2 distros. Please try running `wsl --set-version <DistroName> 1` to put your distro to a WSL 1 distro and try this again and it should work.

I'll close this out as by design as this is expected, and we are tracking AF_UNIX support as a feature request! THank you!

**Closed by craigloewen-msft** 2022-04-26 21:24 UTC

**Comment by PJB3005** [comment] 2022-04-27 07:43
At, that's a shame. If you don't mind me asking though: what would you recommend as the closest alternative for communication between WSL2/Host for this purpose? I'm trying to make a little program to bridge credentials storage over so I can access passwords from WSL2 sanely. I figured using a Unix socket made a lot of sense when I found out about it being a possibility.
