### ISSUE TITLE
WSL does not start anymore when upgrading from 2.0.1 to 2.0.2

### ISSUE THREAD

**Issue by felipecrs** [microsoft/WSL#10560] opened 2023-09-28 13:14 UTC
### Windows Version

Microsoft Windows [Version 10.0.22631.2338]

### WSL Version

This command does not work

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.102.1 (from WSL status)

### Distro Version

Ubuntu 22.04

### Repro Steps

https://github.com/microsoft/WSL/assets/29582865/054fe930-5b40-4d87-91ba-52e8724c9a28

### Expected Behavior

To upgrade properly.

### Actual Behavior

The upgrade process finishes, but calling the wsl.exe seems to call the old system one.

**Comment by fargiolas** [comment] 2023-09-28 13:37
If I try --update it says:
_The package installation failed because a version of the service exists outside of APPX packaging. Please contact your software vendor._

**Comment by felipecrs** [comment] 2023-09-28 13:42
Ops:

```console
❯ wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

❯ wsl --version
WSL version: 2.0.1.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.2338

❯ wsl echo "from wsl"
Failed to attach disk 'C:\Users\felip\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc\LocalState\ext4.vhdx' to WSL2: The process cannot access the file because it is being used by another process.
Error code: Wsl/Service/CreateInstance/MountVhd/HCS/ERROR_SHARING_VIOLATION
```

**Comment by fargiolas** [comment] 2023-09-28 13:44
> _The package installation failed because a version of the service exists outside of APPX packaging. Please contact your software vendor._

not working here, see the error above

**Comment by fargiolas** [comment] 2023-09-28 13:44
> The workaround for me is to run:
> 
> ```
> wsl --update
> ```
> 
> After it's broken, so that wsl returns back to 2.0.1.

not working here, see the error above

**Comment by felipecrs** [comment] 2023-09-28 13:47
> Ops:
> 
> ```
> ❯ wsl --update
> Installing: Windows Subsystem for Linux
> Windows Subsystem for Linux has been installed.
> 
> ❯ wsl --version
> WSL version: 2.0.1.0
> Kernel version: 5.15.123.1-1
> WSLg version: 1.0.58
> MSRDC version: 1.2.4485
> Direct3D version: 1.608.2-61064218
> DXCore version: 10.0.25880.1000-230602-1350.main
> Windows version: 10.0.22631.2338
> 
> ❯ wsl echo "from wsl"
> Failed to attach disk 'C:\Users\felip\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc\LocalState\ext4.vhdx' to WSL2: The process cannot access the file because it is being used by another process.
> Error code: Wsl/Service/CreateInstance/MountVhd/HCS/ERROR_SHARING_VIOLATION
> ```

After rebooting the Windows, it works for me again with version 2.0.1.

**Comment by fargiolas** [comment] 2023-09-28 14:01
Unfortunately reboot doesn't do anything here, still get the APPX error if I try to upgrade, or get it from the store. Help!

**Comment by felipecrs** [comment] 2023-09-28 14:15
Try to uninstall WSL from Programs and Features, then `wsl --update` again.

**Comment by fargiolas** [comment] 2023-09-28 14:24
--status says:
```
Default Distribution: Ubuntu
Default Version: 2

WSL automatic updates are on.

The WSL 2 kernel file is not found. To update or restore the kernel please run 'wsl --update'.
```

@felipecrs I'd like to get some official feedback before doing anything as I have data in wsl. I have backups but it will still be a shame to reconfigure everything.

**Comment by craigloewen-msft** [comment] 2023-09-28 14:26
If you're able to, please hold onto your state for now! We would like to see if we can get logs or feedback on this. 

If you're unable to, please try reinstalling WSL manually by [downloading the latest .msixbundle](https://github.com/microsoft/WSL/releases) from our release page and then double clicking on it. 

Your distro data should be preserved.

**Comment by fargiolas** [comment] 2023-09-28 14:37
@craigloewen-msft thanks for looking into this! I guess I could wait maybe until tomorrow morning CEST time, it's not the first time I upgrade to a pre-release (or even my own builds) and it always went fine, it must be something specific to this version.

**Comment by marcorotondi** [comment] 2023-09-28 15:26
> If you're able to, please hold onto your state for now! We would like to see if we can get logs or feedback on this.
> 
> If you're unable to, please try reinstalling WSL manually by [downloading the latest .msixbundle](https://github.com/microsoft/WSL/releases) from our release page and then double clicking on it.
> 
> Your distro data should be preserved.

Confirm that download installe and run it all works

**Comment by fargiolas** [comment] 2023-09-28 15:28
> > If you're able to, please hold onto your state for now! We would like to see if we can get logs or feedback on this.
> > If you're unable to, please try reinstalling WSL manually by [downloading the latest .msixbundle](https://github.com/microsoft/WSL/releases) from our release page and then double clicking on it.
> > Your distro data should be preserved.
> 
> Confirm that download installer and run it wsl is installed fine and works as aspect

Might as well wait a bit at this point, just for reference did you download and install latest installer (2.0.2) or latest known to work (2.0.1)?

**Comment by marcorotondi** [comment] 2023-09-28 15:37
> > > If you're able to, please hold onto your state for now! We would like to see if we can get logs or feedback on this.
> > > If you're unable to, please try reinstalling WSL manually by [downloading the latest .msixbundle](https://github.com/microsoft/WSL/releases) from our release page and then double clicking on it.
> > > Your distro data should be preserved.
> > 
> > 
> > Confirm that download installer and run it wsl is installed fine and works as aspect
> 
> Might as well wait a bit at this point, just for reference did you download and install latest installer (2.0.2) or latest known to work (2.0.1)?

I download 2.0.2 only change was ip address changed

**Comment by felipecrs** [comment] 2023-09-28 16:26
> Try to uninstall WSL from Programs and Features, then `wsl --update` again.

As far as I know this won't cleanup your data. But of course, the risk is yours.

**Comment by felipecrs** [comment] 2023-09-28 17:36
> If you're able to, please hold onto your state for now! We would like to see if we can get logs or feedback on this.

I can easily reproduce the issue here, and I can provide any information you want. You can even share a Teams meeting link in case you want to see my screen or whatever. :)

**Comment by fargiolas** [comment] 2023-09-29 06:39
> If you're able to, please hold onto your state for now! We would like to see if we can get logs or feedback on this.
> 
> If you're unable to, please try reinstalling WSL manually by [downloading the latest .msixbundle](https://github.com/microsoft/WSL/releases) from our release page and then double clicking on it.

Needed this fixed for work so I followed your advice, I can confirm installing from the latest bundle solves it! Just gave me a warning about binding a new ip address. Now kernel is the correct one and wsl is updated. Let me know if I can still provide any feedback to help you with this issue.

From what I can tell from wsl-install-logs.txt there wasn't any problem with the first update.

**Comment by tristanbarcelon** [comment] 2023-09-29 14:53
My symptoms were slightly different. I was able to update from latest stable to 2.0.0 when it was released. Updating to 2.0.1 failed. Tried a couple of days after and it installed 2.0.2. I can run it just fine but some commands were broken. For example, --version and manage commands didn't work. I downloaded latest msixbundle and re-installed. So far so good.

**Comment by felipecrs** [comment] 2023-09-29 15:37
> For example, --version and manage commands weren't being recognized at all.

Well, that is exactly what I showed in the video. So I think your symptoms are the same. :)

**Comment by fargiolas** [comment] 2023-09-29 17:12
> > I downloaded latest msixbundle and re-installed. So far so good.
> 
> Do you mean the MSI? https://github.com/microsoft/WSL/releases/download/2.0.2/wsl.2.0.2.0.x64.msi

msixbundle is the multiarch package, guess they're the same if you're in x64

**Comment by felipecrs** [comment] 2023-09-29 17:40
Oh, got  it. Thanks.

**Comment by felipecrs** [comment] 2023-09-29 17:42
After updating with the MSIXBUNDLE file (succesfully, no errors, through the App Installer), `wsl --version` still shows 2.0.1.

@fargiolas, mind sending the output of `wsl --version`?

**Comment by felipecrs** [comment] 2023-09-29 17:43
Oh. Nevermind. After `wsl --shutdown`, now it shows correctly:

```
~ ❯ wsl --version                                                                                                                       14:40:51
WSL version: 2.0.1.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.2338
~ ❯ wsl --shutdown^C                                                                                                                    14:41:38
~ ❯ wsl --version                                                                                                                       14:41:53
WSL version: 2.0.2.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.2338
```

**Comment by craigloewen-msft** [comment] 2023-09-29 18:57
We believe we have a fix for this. This was only during the upgrade and only affected for users running `wsl --update`. We'll close this issue when it's available.

**Comment by OneBlue** [comment] 2023-09-29 22:44
Solved with [2.0.3](https://github.com/microsoft/WSL/releases/tag/2.0.3)

**Comment by felipecrs** [comment] 2023-09-30 16:34
I would try to confirm the fix but...

```console
❯ wsl --version                                                                                                                       13:32:18
WSL version: 2.0.2.0
Kernel version: 5.15.123.1-1
WSLg version: 1.0.58
MSRDC version: 1.2.4485
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.2338

❯ wsl --update --pre-release                                                                                                          13:32:15
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

**Comment by OneBlue** [comment] 2023-09-30 22:42
> I would try to confirm the fix but...
> 
> ```
> ❯ wsl --version                                                                                                                       13:32:18
> WSL version: 2.0.2.0
> Kernel version: 5.15.123.1-1
> WSLg version: 1.0.58
> MSRDC version: 1.2.4485
> Direct3D version: 1.608.2-61064218
> DXCore version: 10.0.25880.1000-230602-1350.main
> Windows version: 10.0.22631.2338
> 
> ❯ wsl --update --pre-release                                                                                                          13:32:15
> Checking for updates.
> The most recent version of Windows Subsystem for Linux is already installed.
> ```

New GH releases can take a bit of time to become visible via the API. You should be able to update now

**Closed by OneBlue** 2023-09-30 22:42 UTC

**Comment by felipecrs** [comment] 2023-10-01 14:07
Ok, I upgraded to 2.0.3 and everything worked well.
