### ISSUE TITLE
Loop devices

### ISSUE THREAD

**Issue by Damjen** [microsoft/WSL#4980] opened 2020-03-17 14:25 UTC
Please implement loop devices. They are SO useful.

**Comment by Biswa96** [comment] 2020-03-17 14:27
Use WSL2.

**Comment by sirredbeard** [comment] 2020-03-17 15:08
Duplicate of #131 #1562 #1691 and is fixed in WSL2.

**Closed** 2020-03-18 01:56 UTC

**Comment by SilentException** [comment] 2020-03-21 11:27
> fixed in WSL2.

@sirredbeard I'm not expert in this field so if you don't mind me asking, fixed in what way? 
I tried to use pishrink to shrink some SD images yet it threw an error and told me to do 'modprobe loop' and:

```
$ modprobe loop
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.84-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module loop not found in directory /lib/modules/4.19.84-microsoft-standard
```

This is Ubuntu 18.04 from Windows Store, using WSL2 and Windows Slow Ring (10.0.19041.153).

```
> wsl --list -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
```

**Comment by yphuangms** [comment] 2020-06-22 06:53
Hi, @sirredbeard , as you mentioned this is fixed in WSL2, do you know which exact version of kernel support loop device feature? Or any specific way of installation can we have this loop device enabled?

I'm running Windows 10 (2004), the WSL2 kernel is 
`4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
`
But there's no loop device at /dev/loop*, and when to probe kernel module, using "modprobe loop", the error is still the same as the time of WSL1.

```
user@host:~$ modprobe loop
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-19041-Microsoft/modules.dep.bin'
modprobe: FATAL: Module loop not found in directory /lib/modules/4.4.0-19041-Microsoft

```

**Comment by therealkenc** [comment] 2020-06-22 18:22
> 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

That's WSL1. On WSL2:

![image](https://user-images.githubusercontent.com/7049700/85321967-6911b780-b47a-11ea-8f84-76f7bdac9493.png)

Above is on insiders but loop has been there from [the start](https://github.com/microsoft/WSL2-Linux-Kernel/blob/d0e50c681f72373b5093b4b1b5f6b9335c0b5355/Microsoft/config-wsl#L1286).

**Comment by yphuangms** [comment] 2020-06-23 11:53
@therealkenc  Thanks! It really helps.

The instructions in document is a little bit confusing, this command does not really change the version for existing linux subsystem on windows.
https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-your-distribution-version-to-wsl-1-or-wsl-2 
```
Additionally, if you want to make WSL 2 your default architecture you can do so with this command:
> wsl --set-default-version 2
```

It's only for linux subsystem installed after this command is set.
I mistook this command for upgrading all linux subsystem to WSL2.

For those who make the same mistake as me, please do use following commands:

```
C:\Windows\System32>wsl --list --verbose
  NAME            STATE           VERSION
* Legacy          Stopped         1
  Ubuntu-18.04    Stopped         1

C:\Windows\System32>wsl --set-version Ubuntu-18.04 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Conversion complete.

C:\Windows\System32>wsl --list --verbose
  NAME            STATE           VERSION
* Legacy          Stopped         1
  Ubuntu-18.04    Stopped         2
```

**Comment by shawnz** [comment] 2020-08-14 13:52
Will WSL 1 get loop devices? Perhaps if WSL 1 supported loop mounts, that could solve the issues with filesystem performance, for those who aren't able to use Hyper-V/WSL 2?

**Comment by almirus** [comment] 2023-10-02 20:38
```
>modprobe loop
modprobe: FATAL: Module loop not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2

>ls /dev/ | grep loop
loop0
loop1
loop2
loop3
loop4
loop5
loop6
loop7
loop-control

>uname -a
Linux vivo 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux

```
