### ISSUE TITLE
WSL crashed when compiling OpenSSL

### ISSUE THREAD

**Issue by Dounx** [microsoft/WSL#11191] opened 2024-02-21 18:44 UTC
### Windows Version

10.0.22631.3155

### WSL Version

2.0.14.0

### Are you using WSL 1 or WSL 2?

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.133.1

### Distro Version

Ubuntu 22.04

### Repro Steps

```bash
# 1. Install asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0

# 2. Add ruby plugin
asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git

# 3. Install ruby 3.3.0
asdf install ruby 3.3.0
```

### Expected Behavior

Install ruby 3.3.0 successful.

### Actual Behavior

```bash
(base) dounx@PC:~$ asdf install ruby 3.3.0
==> Downloading openssl-3.1.4.tar.gz...
-> curl -q -fL -o openssl-3.1.4.tar.gz https://dqw8nmjcqpjn7.cloudfront.net/840af5366ab9b522bde525826be3ef0fb0af81c6a9ebd84caa600fea1731eee3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.8M  100 14.8M    0     0  2489k      0  0:00:06  0:00:06 --:--:-- 2622k
==> Installing openssl-3.1.4...
-> ./config "--prefix=$HOME/.asdf/installs/ruby/3.3.0/openssl" "--openssldir=$HOME/.asdf/installs/ruby/3.3.0/openssl/ssl" zlib-dynamic no-ssl3 shared
-> make -j 32

[process exited with code 1 (0x00000001)]
```

### Diagnostic Logs

[WslLogs-2024-02-22_02-33-03.zip](https://github.com/microsoft/WSL/files/14363717/WslLogs-2024-02-22_02-33-03.zip)

**Comment by Dounx** [comment] 2024-02-23 10:10
I find an article about 13th-Gen Intel CPU issue, and I am using 13900KF.

So I changed the CPU Performance Core Ratio from default value x55 to x54, now everything works fine.

![image](https://github.com/microsoft/WSL/assets/16432276/081b38c2-e271-4f9f-960f-8e3c003163ea)

https://www.ithome.com/0/751/470.htm

**Comment by OneBlue** [comment] 2024-02-28 19:55
Looking at the logs, it looks like this was caused by a kernel panic WSL2: 

```
7246	False	Microsoft.Windows.Lxss.Manager	GuestLog	0	02-21-2024 10:33:25.223	"	"	"text: 	""PC login: [  300.395083] invalid opcode: 0000 [#1] SMP NOPTI ""
vmId: 	{6a40b9ac-8d76-4803-bd57-e973e679de38}"				5772	3560	5		00000000-0000-0000-0000-000000000000		
``` 

So this could indeed explain the symptoms you're seeing. Closing for now but feel free to reopen if this happens again.

**Closed by OneBlue** 2024-02-28 19:55 UTC
