### ISSUE TITLE
localedef: ../sysdeps/unix/sysv/linux/spawni.c:360: __spawnix: Assertion `ec >= 0' failed.

### ISSUE THREAD

**Issue by JackieKu** [Microsoft/WSL#1878] opened 2017-04-11 09:12 UTC
* A brief description
When running `locale-gen` it always failed with the following assertion failure:

> localedef: ../sysdeps/unix/sysv/linux/spawni.c:360: __spawnix: Assertion `ec >= 0' failed.

This is because by default charmaps (/usr/share/i18n/charmaps) are gzipped and localedef invokes posix_spawn in order to decompress those files.

* Expected results
No errors when running locale-gen with gzipped charmap files.

* Actual results (with terminal output if applicable)
`localedef: ../sysdeps/unix/sysv/linux/spawni.c:360: __spawnix: Assertion `ec >= 0' failed.`

* Your Windows build number
15063

* Steps / All commands required to reproduce the error from a brand new installation 
1. Edit the locale list at `/etc/locale.gen`.
2. Run `locale-gen' as root.

* Strace of the failing command
None. This bug is easy to be reproduced and the line numbers are available.

* Required packages and commands to install
glibc 2.25

**Comment by therealkenc** [comment] 2017-04-11 10:22
It's only "easy to reproduce" if you are on 16.10. I went back to Xenial unfortunately, but wasn't hitting it at the time I looked in early March (see #1660). Link a [gist](https://gist.github.com/) of `sudo strace -ff locate-gen` somewhere and someone can take a look.

**Comment by Pyrepenol** [comment] 2017-04-13 19:10
The same error shows up when attempting to run Fish Shell on an alternative OS. Perhaps it's related somehow?

https://github.com/alwsl/alwsl/issues/37

**Comment by therealkenc** [comment] 2017-04-13 19:53
Almost certainly the same problem. Arch uses newer glibc etc. See for example #1578. Still no strace....

**Comment by skyem123** [comment] 2017-04-13 19:54
While this is not for `locale-gen`... I got a very similar error for Ninja (and m4 while trying to compile strace), I am currently working on getting a friend to compile me a hopefully working version of strace on a real Linux system.

**Comment by skyem123** [comment] 2017-04-13 20:18
Hopefully this helps... https://github.com/Microsoft/BashOnWindows/issues/1306#issuecomment-294010706

**Comment by Christoph-Wagner** [comment] 2017-04-14 18:01
For those who land here and don't know a lot about linux, unpacking the relevant file (e.g. `gunzip --keep `/usr/share/i18n/charmaps/UTF-8.gz`) avoids the problem and locale-gen runs.

**Comment by therealkenc** [comment] 2017-04-14 20:04
Okay let's do this one. The crux is the following from man [`clone(2)`](http://man7.org/linux/man-pages/man2/clone.2.html):
```
       CLONE_VFORK (since Linux 2.2)
              If CLONE_VFORK is set, the execution of the calling process is
              suspended until the child releases its virtual memory
              resources via a call to execve(2) or _exit(2) (as with
              vfork(2)).
```
On WSL the caller isn't being suspended. Test case below, which is a variation on #1005. It can be run on Xenial. Get the 'Oops' path on WSL but not Real Linux.
```
/* clone-test.c */
#define _GNU_SOURCE
#include <sched.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
#include <signal.h>

#define STACK_SIZE 16364

struct posix_spawn_args
{
  char *hello;
  int err;
};

static int spawni_child(void *arguments) 
{
  struct posix_spawn_args *args = arguments;

  printf("child arg: %s -- sleeping\n", args->hello);
  sleep(1);
  args->err = 0;
  _exit(0);
  return 0;
}

int main(int argc, char *argv[]) 
{
  struct posix_spawn_args args;
  void** child_stack;
  pid_t new_pid;
  int ec;

  args.hello = "hello";
  args.err = -1;
  
  child_stack = (void **)malloc(STACK_SIZE);
  
  // clone is supposed to suspend calling thread 
  // until the child calls execve or _exit
  new_pid = clone(spawni_child, 
      child_stack + STACK_SIZE, 
      CLONE_VM|CLONE_VFORK|SIGCHLD, 
      &args);

  if (new_pid > 0) {
    printf("we should get here only after child called _exit()\n");
    if (args.err < 0) {
      printf("Oops -- args.err should be 0 because it was set in the child\n");
    }
    waitpid(new_pid, NULL, 0);
    printf("child finished doing it's thing\n");
  } else if (new_pid == -1) {
    printf("this path was fixed in #1005\n");
  }

  printf("exiting main\n");
  return 0;
}
```

**Comment by bronze51** [comment] 2017-04-15 02:41
I unpacked the relevant file, ran locale-gen, but still got this error when installing gtkd from the AUR (on WSL). Is there another locale I need to set beyond en_US.UTF-8?

**Comment by skyem123** [comment] 2017-04-16 13:36
The same thing also happens when I use clang, from what I can tell.

**Comment by derekyu56** [comment] 2017-04-23 02:12
I ran into the same problem trying yocto project build in Ubuntu 16.04 in WSL:
`automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
AUTOV is 1
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --system-acdir=/home/derekyu/poky/build/tmp/work/x86_64-linux/libtool-native/2.4.6-r0/recip
e-sysroot-native/usr/share/aclocal/ -I /home/derekyu/poky/build/tmp/work/x86_64-linux/libtool-native/2.4.6-r0/libtool-2.
4.6/m4/ -I /home/derekyu/poky/build/tmp/work/x86_64-linux/libtool-native/2.4.6-r0/libtool-2.4.6/tests/ --force -I m4
m4: ../sysdeps/unix/sysv/linux/spawni.c:360: __spawnix: Assertion `ec >= 0' failed.
m4: internal error detected; please report this bug to <bug-m4@gnu.org>: Aborted
autom4te: m4 failed with exit status: 2
aclocal: error: echo failed with exit status: 2`

Is there any get around in this issue?

**Comment by therealkenc** [comment] 2017-04-23 02:44
@derekyu56 - That's somewhat curious, if you are on 16.04 (Xenial). What does `m4 --version` report? Also `ldd --version`. You should see m4 1.4.17 and glibc 2.23. The problem reported here shouldn't happen until glibc 2.24 or 2.25 (I never took the time to figure which, since it's academic either way).

**Comment by derekyu56** [comment] 2017-04-23 15:22
Sorry, I was wrong. Yocto did shipped with m4 and it is version 1.4.18. I will see if I can replace it with the one from Xenial.

**Comment by therealkenc** [comment] 2017-04-23 15:50
You can also try to find an older version of Yocto that uses glibc 2.23. [`m4` version isn't _really_ the problem here.] In other words rather than "use the one from Xenial", find a Yocto that is better aligned with the toolchain that ships with Xenial. Either way good luck.

**Comment by derekyu56** [comment] 2017-04-23 17:36
Unfortunately, older version has different problems and I was not able to use that either. Thanks for the suggestion. I guess I will have to wait until this issue is resolved.

**Comment by vc12345679** [comment] 2017-04-26 13:32
@Christoph-Wagner That exactly helps! THX dude.

**Comment by bobvanderlinden** [comment] 2017-08-17 09:08
What is needed to get this actually fixed? The workarounds are fine for each use-case, but it those aren't permanent solutions. I'm running into this issue when using NixOS, which uses m4. My guess is that eventually LTS distros will also run into these issues.

**Comment by oblitum** [comment] 2017-08-17 15:08
@bobvanderlinden I've followed this on ArchLinux https://wiki.archlinux.org/index.php/Install_on_WSL, it contains links for fixed packages, and it works, I just installed them. Not sure it's easy to port it to your plataform.

**Comment by therealkenc** [comment] 2017-08-18 02:15
I keep putting off doing a wsl-glibc PPA for Ubuntu with the [cherry pick](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=4b4d4056bb154603f36c6f8845757c1012758158;hp=8d3bd947483f50b57aee7c35c07dc1927d6e8a27) I mentioned in [April](https://github.com/Microsoft/BashOnWindows/issues/1878#issuecomment-294225751). This blocks Yakkety/Ardvark as well as the rolling update distros like Arch&Gentoo. That said, Ubuntu 18 won't go LTS for a long time. It is a pain for people running static binaries like Yocto though, and there isn't much you can do there except rebuild against a working glibc.

**Comment by oblitum** [comment] 2017-08-18 02:23
@therealkenc cherry picking or reverting [just like the AUR wsl-glibc package does](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=glibc-wsl#n29)?

**Comment by therealkenc** [comment] 2017-08-18 02:27
@oblitum - Yep. If you are motivated enough just `apt-get source glibc` and revert the change locally.

**Comment by oblitum** [comment] 2017-08-18 02:31
@therealkenc I can't say for others but my motivation is enough to have my working Arch now rather than Ubuntu ;-)

**Comment by bobvanderlinden** [comment] 2017-08-18 07:35
@oblitum It's harder to do in NixOS, since packages are build with reference to one exact copy of glibc. Changing glibc would usually result in all packages needing to be rebuild. In addition, patching each and every distro with a custom glibc package doesn't seem like a good solution. I'm wondering what is needed to get the right functionality in WSL and whether I can help in any way to do so?

**Comment by fpqc** [comment] 2017-08-18 14:30
@bobvanderlinden The thing right now is that since there are workarounds, this isn't prioritized. It is definitely on their radar though

**Comment by oblitum** [comment] 2017-08-18 19:15
> @therealkenc I can't say for others but my motivation is enough to have my working Arch now rather than Ubuntu ;-)

Sad, I've just discovered that [systemd/systemctl doesn't work on WSL](https://github.com/Microsoft/BashOnWindows/issues/2209). This is a show stopper...

**Comment by therealkenc** [comment] 2017-08-18 20:42
@oblitum - You can vote for that [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13653522-consider-enabling-cron-jobs-daemons-and-backgroun).

**Comment by tuxzz** [comment] 2017-09-13 02:56
This bug is annoying, i have to recompile glibc every time i upgrade it. It wastes me a lot of time.

**Comment by goreliu** [comment] 2017-09-15 04:36
@tuxzz You can backup` /usr/lib/locale/locale-archive`, when glibc upgrades, restore it.

**Comment by tuxzz** [comment] 2017-09-15 10:27
@goreliu Not only locale-gen but also clang and many other programs crash due to this bug.

**Comment by jstarks** [comment] 2017-10-13 20:54
I've been working hard at fixing this. Supporting CLONE_VM correctly has required some significant refactoring. Please hold on a little longer.

**Comment by ardhitama** [comment] 2017-10-20 18:13
Extra tidbits, it also affects me after upgrading to `Ubuntu 17.10` when doing the first `apt upgrade`.
With following error:
```
Preparing to unpack .../bash_4.4-5ubuntu1_amd64.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:368: __spawnix: Assertion `ec >= 0' failed.
dpkg: error processing archive /var/cache/apt/archives/bash_4.4-5ubuntu1_amd64.deb (--unpack):
```

**Comment by heldchen** [comment] 2017-10-21 14:06
@ardhitama here too. "solved" it temporarily by holding offending packages before `do-release-upgrade`:
```
sudo apt-mark hold bash
sudo apt-mark hold ebtables
```

**Comment by TerrorJack** [comment] 2017-10-30 12:44
@heldchen The `apt-mark` trick unfortunately doesn't work here. I recommend WSL users to stick on zesty for now.
Also, can anyone confirm if this is fixed on 17025?

**Comment by heldchen** [comment] 2017-10-30 12:47
@TerrorJack it worked fine for me, and so does 17.10 :)
```
me@devbox:~$ uname -a
Linux devbox 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
me@devbox:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
me@devbox:~$
```

**Comment by therealkenc** [comment] 2017-10-30 15:27
Curious: What does `ldd --version` return after you upgrade to 17.10 artful if you pin `bash`.

**Comment by heldchen** [comment] 2017-10-30 15:47
```
me@devbox:~$ ldd --version
ldd (Ubuntu GLIBC 2.26-0ubuntu2) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by therealkenc** [comment] 2017-10-30 16:36
Thanks, appreciated. [My insider upgrade took down all of Windows with a green screen loop at boot so couldn't check myself until I deal with that.] 

Since you've got `2.26`, I suspect you'll find `fish`, `m4`, `clang`, and all the rest cited in this thread above (plus whatever undiscovered gems) will still fail. You could hold them all of course, assuming you knew everything that is going to take the `glibc` `CLONE_VM` dependency. But that's sort of where we started.

**Comment by jstarks** [comment] 2017-10-30 18:19
Good news -- we've got this fixed in an internal build now, and I'm successfully running Ubuntu 17.10 on my machine.

Sorry this didn't make 17025 -- I'll post an update once this makes it into an insider build.

**Comment by matshch** [comment] 2017-10-30 18:22
@jstarks, so, release users should stick on 17.04?

**Comment by admo** [comment] 2017-10-30 18:45
@derekyu56 You can use newest yocto (e.g. rocko) on WSL without this problem. There is only one thing you have to do:
`git checkout ce7e0252c498c25c782e181283172591d3e8b76b -- meta/conf
/distro/include/yocto-uninative.inc`
It changes version of the uninative package to the one which has glibc which works on WSL.

**Comment by heldchen** [comment] 2017-10-30 20:20
> Since you've got 2.26, I suspect you'll find fish, m4, clang, and all the rest cited in this thread above (plus whatever undiscovered gems) will still fail.

absolutely. holding bash only fixes the `do-release-upgrade` erroring out on zesty >> artful. 

glad to see a fix is inbound tho.

**Comment by jstarks** [comment] 2017-10-31 14:58
@matshch Stick with 16.04 LTS for now.

**Comment by TerrorJack** [comment] 2017-10-31 15:57
@matshch I'm on insider 17025 and sticking on 17.04 for now, no problem so far.

**Comment by derekyu56** [comment] 2017-11-01 02:19
Thanks, I will give a try.

**Comment by derekyu56** [comment] 2017-11-02 00:42
The yocto build still failed in rocko build with the git checkout. This
time it did build 1031 packages, much better than before but it failed in:
  /home/derekyu/yocto/poky/meta/recipes-devtools/gcc/gcc-cross_7.2.bb:
do_compile

/home/derekyu/yocto/poky/meta/recipes-kernel/linux-libc-headers/linux-libc-headers_4.12.bb:
do_package
This is a different topic so I'll stop here. Thanks anyway.

**Comment by K900** [comment] 2017-11-08 21:10
@jstarks is the fix supposed to be included in 17035? Doesn't look like it for me :(

**Comment by jstarks** [comment] 2017-11-08 21:14
No :(. We've had some unfortunate delays getting WSL fixes into the insider builds lately. We'll get that unblocked as soon as we can.

**Comment by nstrelow** [comment] 2017-11-16 21:56
Was this fixed in 17040 ?

**Comment by heldchen** [comment] 2017-11-16 23:06
@nstrelow nope:

```
me@devbox:~$ sudo apt-mark unhold bash
Canceled hold on bash.
me@devbox:~$ sudo apt-get upgrade bash
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  bash
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 625 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu artful/main amd64 bash amd64 4.4-5ubuntu1 [625 kB]
Fetched 625 kB in 0s (1,948 kB/s)
(Reading database ... 38045 files and directories currently installed.)
Preparing to unpack .../bash_4.4-5ubuntu1_amd64.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:368: __spawnix: Assertion `ec >= 0' failed.
dpkg: error processing archive /var/cache/apt/archives/bash_4.4-5ubuntu1_amd64.deb (--unpack):
 subprocess new pre-installation script was killed by signal (Aborted), core dumped
dmesg: read kernel buffer failed: Function not implemented
                                                          update-alternatives: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
Errors were encountered while processing:
 /var/cache/apt/archives/bash_4.4-5ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
me@devbox:~$
```

**Comment by Brian-Perkins** [comment] 2017-11-22 18:52
Windows Insider Build 17046 has improved CLONE_VFORK and CLONE_VM support.

**Comment by K900** [comment] 2017-11-22 18:54
This is great news! Does this mean the behavior is fully compliant, or are there still incompatibilities left?

**Comment by heldchen** [comment] 2017-11-22 19:19
> Windows Insider Build 17046 has improved CLONE_VFORK and CLONE_VM support.

`apt-get upgrade bash` went through without the `Assertion 'ec >= 0' failed` error

**Comment by Brian-Perkins** [comment] 2017-11-22 19:39
The behavior is not yet fully compatible. There are still some flags including CLONE_NEWUSER and CLONE_SIGHAND that do not work, and some supported flag combinations that either are not 100% compatible or haven't yet been verified to be. Some of these we are already looking at and others will be prioritized, as per usual, when interesting scenarios emerge involving them.

**Comment by glaubitz** [comment] 2017-11-26 20:30
Just as a heads-up, this issue affects qemu-user as well:

```bash
dpkg: warning: ignoring pre-dependency problem!
Preparing to unpack .../archives/bash_4.4-5_m68k.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:366: __spawnix: Assertion `ec >= 0' failed.
qemu: uncaught target signal 6 (Aborted) - core dumped
dpkg: error processing archive /var/cache/apt/archives/bash_4.4-5_m68k.deb (--unpack):
 new bash package pre-installation script subprocess was killed by signal (Aborted)
Selecting previously unselected package bsdutils.
dpkg: regarding .../bsdutils_1%3a2.30.2-0.1_m68k.deb containing bsdutils, pre-dependency problem:
 bsdutils pre-depends on libsystemd0
  libsystemd0 is not installed.
```

**Comment by erikly01** [comment] 2017-11-29 21:21
I'm also getting the same error with qemu-user
```
dpkg: warning: ignoring pre-dependency problem!
Preparing to unpack .../archives/bash_4.4-5_arm64.deb ...
preinst: ../sysdeps/unix/sysv/linux/spawni.c:366: __spawnix: Assertion `ec >= 0' failed.
qemu: uncaught target signal 6 (Aborted) - core dumped
dpkg: error processing archive /var/cache/apt/archives/bash_4.4-5_arm64.deb (--unpack):
 new bash package pre-installation script subprocess was killed by signal (Aborted)
```

**Comment by LocutusOfBorg** [comment] 2017-12-08 17:29
same error message here http://paste.ubuntu.com/26140607/

**Comment by jstarks** [comment] 2017-12-08 17:41
These errors are all expected pre-build 17046. If you see these errors on 17046 or newer, please let us know.

**Closed** 2018-01-04 17:48 UTC
Labels: bug, fixedininsiderbuilds

**Comment by Zenexer** [comment] 2018-02-07 23:48
For those of you not on the Insider channel, I made a [workaround script](https://gist.github.com/Zenexer/10bc12fa5c99848b4b2150184f6beee5).  If you want to update to Ubuntu 17.10, that should do the trick, but be warned it could have unintended side effects in scenarios I haven't tested, and could cause problems when you do eventually receive the fix from Microsoft.
