### ISSUE TITLE
When starting a new session, the following message is displayed: "sed: couldn't open temporary file /etc/update-manager/sedzeLB5B: Permission denied"

### ISSUE THREAD

**Issue by haosmos** [microsoft/WSL#9590] opened 2023-02-04 23:00 UTC
### Version

10.0.22000.1455

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

WSL: 1.1.2.0 kernel: 5.15.83.1

### Distro Version

Ubuntu-22.04

### Repro Steps

wsl (VmmemWSL process) takes a very long time to start (~30 seconds) and every time you start a new wsl session (sessions start quickly, unlike the start of the VmmenWSl process itself), the following message is displayed:

sed: couldn't open temporary file /etc/update-manager/sedzeLB5B: Permission denied

value after "sed" changes in every new session: sed: couldn't open temporary file /etc/update-manager/sed${new value in every new session}: Permission denied 

sed: couldn't open temporary file /etc/update-manager/sedzeLB5B: Permission denied
sed: couldn't open temporary file /etc/update-manager/sed7DEhQv: Permission denied
sed: couldn't open temporary file /etc/update-manager/sedA31vLd: Permission denied

some time ago there were no such problems - wsl started quickly - ~5-10 seconds and such a message was never displayed on the console. I don't remember at what point it started.

perhaps this is due to the problem that I described in the windows terminal repository - for some reason I can not run windows terminal (as well as the preview version) in normal mode, - the windows terminal and preview version only run in administrator mode.

in vscode and in jetbrains products (webstorm) every new wsl session in terminal starts without such message as in windows terminal (sed: couldn't open temporary file /etc/update-manager/sedA31vLd: Permission denied)

### Expected Behavior

wsl starts quickly - not 30 seconds and when starting a new wsl session, no message is displayed: "sed: couldn't open temporary file /etc/update-manager/sedzeLB5B: Permission denied"

### Actual Behavior

wsl (VmmemWSL process) takes a very long time to start (~30 seconds) and every time you start a new wsl session (sessions start quickly, unlike the start of the VmmenWSl process itself), the following message is displayed:

sed: couldn't open temporary file /etc/update-manager/sedzeLB5B: Permission denied

value after "sed" changes in every new session: sed: couldn't open temporary file /etc/update-manager/sed${new value in every new session}: Permission denied 

sed: couldn't open temporary file /etc/update-manager/sedzeLB5B: Permission denied
sed: couldn't open temporary file /etc/update-manager/sed7DEhQv: Permission denied
sed: couldn't open temporary file /etc/update-manager/sedA31vLd: Permission denied

**Comment by OneBlue** [comment] 2023-02-06 20:10
Thanks for reporting this @haosmos.

Can you share the output of: `cat /etc/wsl.conf`,  `cat ~/.bashrc` and `cat ~/.bash_profile` inside your WSL distro ?

**Comment by haosmos** [comment] 2023-02-07 09:38
> Thanks for reporting this @haosmos.
> 
> Can you share the output of: `cat /etc/wsl.conf`, `cat ~/.bashrc` and `cat ~/.bash_profile` inside your WSL distro ?

yes, sure: 

`cat /etc/wsl.conf` --> 

```
1   │ [boot]
2   │ systemd=true
3   │ #command="/usr/libexec/wsl-systemd"
4   │
5   │ [user]
6   │ default=chaosmos
```
`cat ~/.bash_profile` --> 

```
export HISTTIMEFORMAT="%d/%m/%y %T "
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
```

maybe it will be useful for you to know - I use zsh and [here](https://pastebin.com/M0dNCahd) is my .zshrc config (I posted it on pastebin because this file is big).

`cat ~/.bashrc` --> 

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"


export PATH="${PATH}:/home/chaosmos/.cargo/bin/navi"
. "$HOME/.cargo/env"

source /home/chaosmos/.config/broot/launcher/bash/br

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
```

**Comment by OneBlue** [comment] 2023-02-07 22:28
Thank you @haosmos. I wonder if this issue is caused by something in your .zshrc.

Do you see this error if you do: 
- wsl.exe --shutdown
- wsl --shell-type none bash

?

**Comment by haosmos** [comment] 2023-02-08 10:05
> No, if I run the wsl session as you indicated there is no such message. What does that tell you? That the problem is in my .zshrc configuration? What is the way to find out the reason?



> Thank you @haosmos. I wonder if this issue is caused by something in your .zshrc.
> 
> Do you see this error if you do:
> 
> * wsl.exe --shutdown
> * wsl --shell-type none bash
> 
> ?

No, if I run the wsl session as you indicated there is no such message. What does that tell you? That the problem is in my .zshrc configuration? What is the way to find out the reason?

![WindowsTerminal_P1B9TU3jmP](https://user-images.githubusercontent.com/30666874/217498508-be6deae2-6aa9-4f84-b5cd-281f89019b40.png)

**Comment by haosmos** [comment] 2023-02-08 11:51
I found this file: /var/lib/dpgk/info/ubuntu-release-upgrader-core.preinst

![WindowsTerminal_Bckn5KeaQo](https://user-images.githubusercontent.com/30666874/217521416-be989018-8d12-4fc5-a3ff-51506a32c580.png)

here is its content:

![chrome_OOlwZiVJMN](https://user-images.githubusercontent.com/30666874/217521459-5774513e-d7eb-4bde-baf7-42334e027012.png)

looks like this block of code is causing my message:

![WindowsTerminal_oqgYNKuPTd](https://user-images.githubusercontent.com/30666874/217521915-5e042dc3-958b-4cb6-ae53-eb7facc3b541.png)

apparently it has something to do with ubuntu update settings, but I don't get it.

**Comment by haosmos** [comment] 2023-02-08 12:15
Here is information about the contents of the /etc/update-manager directory:

![WindowsTerminal_jfTX2Con6A](https://user-images.githubusercontent.com/30666874/217527015-de62bc26-6f1d-4bc0-a3c2-8b57983a84fc.png)

**Comment by OneBlue** [comment] 2023-02-08 20:40
Thank you @haosmos. This is indeed caused by the scripts running as part your .zshrc configuration. 
You can try to run `zsh -x` to help diagnosing where this is called from.

Closing since this is not a WSL issue.

**Comment by haosmos** [comment] 2023-02-08 23:11
> Thank you @haosmos. This is indeed caused by the scripts running as part your .zshrc configuration. You can try to run `zsh -x` to help diagnosing where this is called from.
> 
> Closing since this is not a WSL issue.

this command prints out a huge number of messages from which I have trouble understanding what the problem is. Here are some screenshots: 

![WindowsTerminal_WevgZv6QOm](https://user-images.githubusercontent.com/30666874/217672139-39b4a146-d41a-4448-a181-97044d3e635f.png)

![WindowsTerminal_E2KAA07bDR](https://user-images.githubusercontent.com/30666874/217672146-bbfd5cdf-d499-44b7-88a9-6267186ef2d4.png)

![WindowsTerminal_XYPONI60RS](https://user-images.githubusercontent.com/30666874/217672148-21217aae-d426-436e-865d-52ade17ab1e2.png)

![WindowsTerminal_CE3EEF0uuo](https://user-images.githubusercontent.com/30666874/217672151-b677cd87-47b1-4f0c-a576-23883d7c4ae6.png)

![WindowsTerminal_2TyGbVQQRQ](https://user-images.githubusercontent.com/30666874/217672153-9cbd7eba-ea93-47ee-adee-d2410d6e316b.png)

one observation that catches your eye is that there are a lot of posts here related to the topic oh-my-zsh - powerlevel10k
But I've been using this theme for probably three years now, and I've never had this problem..

maybe you have any ideas what could be wrong?

**Comment by Mandras** [comment] 2023-02-12 03:36
Hello

I got the exact same problem on my WSL 1 Ubuntu 20.04 LTS

I managed to fix the problem, with those commands:

(replace `your_default_user` by your linux user)

`sudo chmod 775 /etc/update-manager`
`sudo chown root:your_default_user /etc/update-manager`
`sudo echo -n '' >> /var/log/upgrade-policy-changed.log`
`sudo chmod 664 /var/log/upgrade-policy-changed.log`
`sudo chown root:your_default_user /var/log/upgrade-policy-changed.log`

Hope it's help, and btw, I don't have zsh (I use my WSL for LAMP, Python, Docker, ...)

**Comment by haosmos** [comment] 2023-02-12 14:28
> Hello
> 
> I got the exact same problem on my WSL 1 Ubuntu 20.04 LTS
> 
> I managed to fix the problem, with those commands:
> 
> (replace `your_default_user` by your linux user)
> 
> `sudo chmod 775 /etc/update-manager` `sudo chown root:your_default_user /etc/update-manager` `sudo echo -n '' >> /var/log/upgrade-policy-changed.log` `sudo chmod 664 /var/log/upgrade-policy-changed.log` `sudo chown root:your_default_user /var/log/upgrade-policy-changed.log`
> 
> Hope it's help, and btw, I don't have zsh (I use my WSL for LAMP, Python, Docker, ...)

Thank you! did you manage to figure out the cause of this problem? why did this happen at all and what caused this message to be displayed?

**Comment by Winson-Huang** [comment] 2023-02-14 09:58
@haosmos I notice you use Windows Terminall, in your profile of WSL Ubuntu, the "command line"  value are probably "Ubuntu.exe" or so, try to change it to "wsl.exe -d <distro-name>", in your case maybe "wsl.exe -d Ubuntu-22.04". Then the error message could disappear. I guess "Ubuntu.exe" is a wrapper of WSL bash, and it may contains some bugs. 
In my case this method does work, don't know if this works for your case too.

**Comment by haosmos** [comment] 2023-02-16 08:47
> @haosmos I notice you use Windows Terminal, in your profile of WSL Ubuntu, the "command line" value are probably "Ubuntu.exe" or so, try to change it to `wsl.exe -d <distro-name>`, in your case maybe `wsl.exe -d Ubuntu-22.04`. Then the error message could disappear. I guess "Ubuntu.exe" is a wrapper of WSL bash, and it may contains some bugs. In my case this method does work, don't know if this works for your case too.

Thank you very much! it helped! 👍🚀

**Closed** 2023-02-16 08:47 UTC
